### ISSUE TITLE
docs(locators.js): Example - how do I get the image url?

### ISSUE THREAD

**Issue by petermajor** [angular/protractor#1000]
The documentation example for "by.repeater" show the following html:

``` html
<div class="book-img" ng-repeat-start="book in library">
  <img ng-src="{{book.imgUrl}}"></img>
</div>
<div class="book-info" ng-repeat-end>
  <h4>{{book.name}}</h4>
  <p>{{book.blurb}}</p>
</div>
```

However, it doesn't show how I can get the value for "book.imgUrl".

I've tried:
element.all(by.repeater('book in library').column('imgUrl'));

But I get the error message:
Error: No element found using locator: by.repeater("book in library").column("imgUrl")

Could we have some extra description in the docs on how to check this particular property please?

**Comment by jainshravan123** [comment]
Hi @juliemr 

I can see very clearly that you helped so many people. Please help me to get out one problem.

<div class="unique_class" my-attribute="obj.data"></div>

So how can i get the actual value of (obj.data) using protractor?

I tried to use getAttribue() method but it's returning only (obj.data) as text not the value of it. So how can i get the actual value of it. Please help me.

Thank You

Regards,
Shravan Jain

**Comment by wswebcreation** [comment]
Hi @jainshravan123 

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


If you post it on Stackoverflow and provide more info I'll try to answer it.

**Comment by jainshravan123** [comment]
Will post it there but it's a small problem please reply here only. I need the solution asap. If you reply then that would be really helpful.

**Comment by TakaDN** [comment]
hello
i have question:
i have img tag: 
```
<h1 _ngcontent-c1>
    <img _ngcontent-c1 alt height="30" src="./assets/images/logo.png" width="auto">
</h1>
```
and my code is
```
it ('should have logo image', function() {
        expect(element(by.xpath("//img[@src='/assets/images/logo.png']")).isPresent()).toBe(true);
    });
```
it met error: 
Failed: Error while waiting for Protractor to sync with the page: "Could not find testability for element."

**Comment by wswebcreation** [comment]
@TakaDN 

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
