### ISSUE TITLE
browser.manage().getCookie() doesn't work correctly with IE

### ISSUE THREAD

**Issue by theking-laptop** [angular/protractor#1004]
My code:

```
browser.manage().getCookie(cookie_key)
                .then(function (cookie) {
                    // put some expect clauses here
                });
```

I try this code with Chrome, Firefox and it work perfectly, but when I test in IE, it fails if I use 'expiry' field. So I inspect the cookie which is returned, in Chrome and Firefox, its value is `{ name : 'my_cookie', domain : 'localhost', secure : false, value : 'my_val', path : '/', httpOnly : false, class : 'org.openqa.selenium.Cookie', hCode : -309474065, expiry : 1404199805 }`; and in IE, its value is `{ name : 'my_cookie', secure : false, value : 'my_val', path : '/', httpOnly : false, class : 'org.openqa.selenium.Cookie', hCode : -309474065 }`. It doesn't include 'expiry' and 'domain' fields.

=== More information:
OS: Ubuntu 12.04
IE8 + IE11 (virtualbox)

**Comment by mchopra1004** [comment]
Is there any alternative for this?
