### ISSUE TITLE
element.all vs Protractor.prototype.findElements

### ISSUE THREAD

**Issue by ghost** [angular/protractor#1008]
While going through the docs here:  https://github.com/angular/protractor/blob/master/docs/api.md#api-protractorby

I am not very clear on what is the fundamental difference between 

`element.all vs  Protractor.prototype.findElements`

or for that matter

`element vs  Protractor.prototype.findElement`

What I have inferred from reading the docs is that **Protractor.prototype.findElements** will wait for protractor to synchronize before starting its search while element.all does not i.e it internally uses _ptor.ignoreSynchronization=true_

Am i right in my inference ?

**Comment by KWodarczyk** [comment]
im my case im trying to do:

```
var elementsPromise= element.all(by.repeater('itemin items'));
        var someElement= elementsPromise[0].element(by.css('my selector '));
        someElement.click();
```

but get, **Cannot read property 'element' of undefined**
