### ISSUE TITLE
How to pass Environment based parameters in jasmine framework to protractor test

### ISSUE THREAD

**Issue by prakashomp** [angular/protractor#1016]
Hi,

I want to pass the arguments to the browser in jasmine frame work configuration file.
like " multiCapabilities: [{
'browserName': 'chrome',
maxInstances: 1,
name:'chrome',
'args': ['user=user1']
}, {
'browserName': 'firefox',
shardTestFiles: true,
maxInstances: 1,
name:'firefox',
'args': ['user=user2']

}
],
and also read in the test file how to read and use according to the browser.

**Comment by Saurabh06** [comment]
@aidaeology  for me its not working i have tried

capsPromise.then(function(caps){
       var browserName = caps.caps_.browserName.toUpperCase();
       var browserVersion = caps.caps_.version;
       var platform = caps.caps_.platform;
       var prePendStr = browserName + "_" + browserVersion + "_"+ platform+ "_";});

![image](https://cloud.githubusercontent.com/assets/17181080/15015537/22cd5e1a-122a-11e6-9ae4-0c95d416fc21.png)
