### ISSUE TITLE
reading configuration parameters from the configuration file

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#102]
I am trying to set some configuration parameters in configuraiton file and reading the same in my protractorjs file. As per my understanding I can set the config parameters in conf.js file. But i am trying to read the same in my protractor js file. Can you tell me how to read or which function to call to read these parameters. Some sample code snippet would be helpful

**Comment by zahafyou** [comment]
HOW DID YOU DO ? an example code please nithyanatesan

**Comment by djom20** [comment]
Hi @juliemr ,

I have a similar question, I need to access for the cucumberOptions to know if the tests are running on dry-run, is it possible?
