### ISSUE TITLE
setup and teardown methods at class/file level

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#103]
Do we have setup and teardown methods at class/file level. beforeEach and afterEach runs before and after each test case. Do we have setup and teardown at class level

**Comment by hankduan** [comment]
Note that with 1.6.0 you will be able to use jasmine2 with protractor. There you can use beforeAll/afterAll

**Comment by ramkatwix** [comment]
Hi, What is the latest news about beforeAll/afterAll with protractor?

**Comment by juliemr** [comment]
1.6.0 has been released - you may now use `framework: jamsine2`, which allows the use of `beforeAll` and `afterAll`

**Comment by americos** [comment]
```beforeAll``` and ```afterAll``` work like a charm in 1.6.0, Thanks guys!

**Comment by extdevelopment** [comment]
Please help me, What am I doing wrong?

<pre>protractor --version
Version 1.6.1 </pre>

<pre>
Message:
  ReferenceError: afterAll is not defined
Stacktrace:
  ReferenceError: afterAll is not defined
   [chrome #2]     at [object Object].jasmine.Env.describe_ (\node_modules\minijasminenode\lib\jasmine-1.3
.1.js:913:21)
</pre>

**Comment by americos** [comment]
@extdevelopment I think that error happens when you don't specify jasmine2 inside ```protractor.conf.js```  make sure you add this line: ```framework: jasmine2``` to your protractor.conf.js

**Comment by extdevelopment** [comment]
@americos thx ```framework: 'jasmine2'``` helped

**Comment by ljwagerfield** [comment]
After adding `framework: 'jasmine2'` I get the following error when trying to use `ddescribe` at the root of my test file:

```
launcher] Error: ReferenceError: ddescribe is not defined
```

Furthermore, `ddescribe` and `iit` take no effect inside the test suite.

**Comment by hankduan** [comment]
@ljwagerfield Please read the upgrade guide. https://github.com/angular/protractor/blob/master/docs/jasmine-upgrade.md#focused-specs

ddescribe and iit -> fdescribe, fit
