### ISSUE TITLE
Pasting text and protractor

### ISSUE THREAD

**Issue by ghost** [angular/protractor#1037]
I have a text-area element on my page. Associated with thsi text-area is a directive. The job of this directive is to capture the text has is "pasted" into the textarea and do some processing on it.

Now when I do paste a line of text into the textarea, my directive is able to capture every word in this line and perform related parsing and processing. However when using **sendkeys** in-order to paste text (i.e enter text) into textarea, the same behavior is not displayed. This time around only first few words are captured by my directive. 

Ofcourse this could be something to do with the pace with which sendKeys enters text.

Is there anyway to make sendKeys work similar to Ctrl+v ?

**Comment by mrzmyr** [comment]
I solved this by simulating the event:

```js
var el = element(by.model('your.model'))
var script = 
  "value = arguments[0].value;" + 
  "var event = new Event('paste', {});" + 
  "event.clipboardData = { getData: function () { return value; } };" + 
  "arguments[0].dispatchEvent(event);";

browser.executeScript(script, el.getWebElement());
```

This works with `ngPaste`, in this single case when using `$event.clipboardData.getData('text/plain')`.

example
```html
<input type="text" ng-paste="onPaste($event)">
```

```js
$scope.onPaste = function ($event) {
  var data = $event.clipboardData.getData('text/plain');
}
```
