### ISSUE TITLE
How to wait to load the element in browser

### ISSUE THREAD

**Issue by prakashomp** [angular/protractor#1046]
hi
i created a common function to wait to load page but not working the code.

this.waitForElements=function(element){  
            for (var sec = 0;; sec++) {  
                if(sec>120){
                    break;
                }
                if(this.checkingElement(element)==true){
                    break;
                }
                browser.sleep(1000);  
    }
        };

```
    this.checkingElement=function(availableElement){        
        val=false;
        availableElement.isPresent().then(function(){
            val=true;
        });
    return val;
    };
```

when i call 'waitForElements(pageobject element)' i am getting error while waiting for Protractor to sync with the page
how to control this one.
script was executing with out wait .

Thanks& Regards
OmPrakash

**Comment by yakovpinhasov** [comment]
hey guys i am having similar problem. In my function i am having three elements to be filled in but the second element jumps to the third index. Which wait function should i use

**Comment by gijop** [comment]
But here it will wait until the wait time expires, i think it is not a good way. Any other way to wait for the locator upto the presence or availability of that ?
