### ISSUE TITLE
IE Drivers often time out when loading a page

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1052]
The errors we see most often with IE driver are
- timed out waiting for page to load
- timed out waiting for protractor to sync with page
- Angular could not be found on the page http://localhost:8081/index.html#/form : retries looking for angular exceeded
- Error: Error while running testForAngular: Timeout expired waiting for async script
- Angular could not be found on the page http://localhost:8081/index.html#/form : angular never provided resumeBootstrap

**Comment by mzgol** [comment]
I have 100% reproducibility on the message:
```
Angular could not be found on the page http://localhost:8500/ : angular never provided resumeBootstrap
```
in IE11 in my app that otherwise tests fine with Chrome/Firefox (checked on IE11 on Windows 8.1 on BrowserStack).

**Comment by afuertes** [comment]
Hi, good morning, i have a problem with ie11, my test is unable to find an element into a header block, works correctly in chrome and firefox. I'm using protractor and jasmine framework.

**Comment by juliemr** [comment]
See also https://github.com/angular/protractor/issues/1999

**Comment by NickTomlin** [comment]
We've had issues reproducing this regularly in https://github.com/angular/protractor/issues/1999. 

I'm going to close this issue. For anyone that continues to experience issues in IE: please open a new issue with a small reproducible example that we can work on together. That will hopefully keep the discussion focused.
