### ISSUE TITLE
Smoke-test Node 0.11

### ISSUE THREAD

**Issue by mzgol** [angular/protractor#1053]
Node 0.11.13 is technically unstable, but there are reports the stable 0.12 version is coming. It would be good to at least smoke-test on Node 0.11 to be able to catch simple regressions and be compatible with 0.12 once it's released.

See e.g. #1005 that makes Protractor Selenium installation impossible with Node 0.11 currently.

**Comment by juliemr** [comment]
This is now done with 0.12
