### ISSUE TITLE
Testing multiple specs

### ISSUE THREAD

**Issue by jurgenvo** [angular/protractor#1077]
Hi,

I am trying to run multiple specs that are defined in the config.js file.

specs: ['folder1/test1.spec.js', 'folder2/test1.spec.js', 'folder2/test2.spec.js']

When I run this, one browser window opens and it starts the first test, but then without finishing the first test, it will start the second.

Is there some option that makes sure that the test will start when the other test is finished? Or am I doing something wrong here?

Thanks in advance!

**Comment by reddynr** [comment]
I have  to run two senerios using protractor. config.js I given two of the spec name. But not running second one. here is the sample. Please advice. Thanks

config.js
 specs: ['mcac_jm_online_NRE_flow.js','mcac_jm_online_RTE_flow.js'],

**Comment by Pankaj-Pippin** [comment]
Hi,

Is it possible to include the 2nd file in the end of 1st test file ?

Like with coding in asp or php we can transfer execution to other file can this be done with jasmine 

specs: ['sendmsg.ts']

sendmsg.ts 

describe(){
it (){
run case
}
call readmsg.ts;
}

Thanks
