### ISSUE TITLE
Just loading a Blank screen when using Browser.get()

### ISSUE THREAD

**Issue by kuroiokami** [angular/protractor#1078]
Hello I'm getting a blank screen when I try to do a browser.get() on my screen. If I go in an press enter manually it loads up but initially when protractor does it, it just shows a blank screen (the url is correct and it does show the correct title of the page on the browser)

I also get this Error

Error: Error while running testForAngular: javascript error: document unloaded while waiting for result\n

**Comment by yokeshvaradhan** [comment]
when i run npm run e2e test starts good but browser shows a white screen and test gets terminated 
![screen shot 2016-07-08 at 6 27 36 pm](https://cloud.githubusercontent.com/assets/13794462/16688871/c7822f3a-453d-11e6-95e8-5a5ae9a5a841.png)
