### ISSUE TITLE
Protractor not waiting for page to load?

### ISSUE THREAD

**Issue by andrewboni** [angular/protractor#1086]
I'm running into an issue where protractor seemingly doesn't wait for the page to load before running the tests. Started noticing this after updating to the latest version of protractor. Here's my code:

``` coffeescript
describe "Lists page", ->
  beforeEach ->
    browser.ignoreSynchronization = true
    browser.get "/segmentation"

  # Title assertions
  it "the title should be correct", ->
    # Find the title element
    title = element(By.tagName("h2")).getText()
    expect(title).toBe "Segmentation"

  it "should have overall reach", ->
    title = element(By.tagName("h3"))
    expect(title.getText()).toBe "Overall reach"
```

And the output:

``` bash
Failures:

  1) Segment lists page the title should be correct
   Message:
     Expected '' to be 'Segmentation'.


  2) Segment lists page should have overall reach
   Message:
     Expected '' to be 'Overall reach'.
```

Anything obvious that I should be doing or am not doing? Thanks!

**Comment by drrust** [comment]
I don't know if there is a better solution for this in the framework (just started using it) but I wanted to post my solution, which is just a small cleanup of what davidwparker posted above.

in my conf.js I have:

```
exports.config = {
 ...
  onPrepare: function(){
	  global.waitForNonAngularSiteToLoad = function () {
		return browser.driver.wait(function() {
			return browser.driver.getCurrentUrl(function(url) {
				return /activity/.test(url);
			});
		});
	  }
	global.isAngularSite = function(flag){
		browser.ignoreSynchronization = !flag;
	};
  }
...
}
```

and in any of my spec files where I need to test some non angular page I do:

```	
it('when I click the login button I am redirected to a login screen and enter my username, password and click the sign on button', function() {
	myAngularPageObj.clickLoginButton(); //click login button to get redirected from angular page to a non-angular page
	isAngularSite(false); //read http://ng-learn.org/2014/02/Protractor_Testing_With_Angular_And_Non_Angular_Sites/ if you want to understand this
	waitForNonAngularSiteToLoad(); //davewparker's solution
	//test non-angular page (for my case it was an authentication server)
	isAngularSite(true);
});
```

This seems to work for me, I was running my tests with firefox and chrome and for some reason in firefox the test would SOMETIMES annoyingly fail attempting to write the value in the username textbox, I guess it wasn't loaded, but thanks to you guys I have this working now.

In my case I don't have multiple tests, just one run through so I didn't put the fix in a beforeEach block.
