### ISSUE TITLE
Using Protractor to run tests against multiple user roles

### ISSUE THREAD

**Issue by jpetraws** [angular/protractor#1088]
I am trying to run the same test for different roles in the application.

The problem is since there is no logout/login page(SSO magic). I can't logout and login is a different user on the same browser.

I have been trying to get around this and look up a way to pull up a new browser instance or anything.

The only thing that got kind of close was if I tried to use multiCapabilities:

```
multiCapabilities: [{
    browserName: 'chrome',
    acceptSslCerts: true,
    trustAllSSLCertificates: true,
    specs: ['claimsoverview/login-claims-analyst.spec.js']
}, {
    browserName: 'chrome',
    acceptSslCerts: true,
    trustAllSSLCertificates: true,
    specs: ['claimsoverview/login-supervisior.spec.js']
}],
```

Each individual spec works, but when I run them together they do not and I get Unknown error unsupported protocol. And also  Error: Error while waiting for Protractor to sync with the page: {}

Before each test I have to hit an Oracle SSO page which is non-angular then I can finally be re-routed to the url that is angular. 

```
//Here is the beginning of one spec..
it('should load homePage from Oracle Sign in Page', function() {

   var dvr = browser.driver;

    //To get around the untrusted cert issue per browser
    dvr.get('https://url');
    UntrustedCertOverride(dvr);

    //Get SSO PageObject and run login()
    var oracleSsoPage = new OracleSsoPage(dvr);
    oracleSsoPage.login(browser.params.claimsAnalyst.userName, browser.params.claimsAnalyst.password);

    //Expect the title to be ConDOR
    expect(browser.getTitle()).toEqual("homePage");
});
```

**Comment by skidvd** [comment]
@jpetraws Thanks for posting this.  

I too am attempting to perform some tests with differing specs for each required role.  Surprisingly, this does not seem to be supported in any other manner than what you have demonstrated.  Please let me know if you may have found other avenues as I'm still searching.

While your approach accomplishes the main goal of being able to have different specs for each role, I believe it has one drawback.  Perhaps you may have a way around this as well?  The drawback that I see with this approach, is that we can no longer use the suites capabilities and consequently invoke protractor to only run a subset of suites (--suite=suite1,suite2).  Any thoughts on this?

TIA!

**Comment by makwanaparth94** [comment]
I want to add multiple credential at run time while running my automation test for Login screen.
How can i do that?

**Comment by stgakki** [comment]
1) Write one function for login.
2)Add multiple credentials in json file
3)Include json file using  [ var myjsonData = require("../myjson.json"); ]
4)Iterate using loop and call login function in it and pass parameters to function as data in  json file  randomly.
