### ISSUE TITLE
addMockModule not overriding with manually bootstrapped applications.

### ISSUE THREAD

**Issue by chiller-whale** [angular/protractor#1090]
When calling a addMockModule with a manually bootstrapped application, I am unable to override existing modules. 

The mocked modules code does execute, but only after the real modules code has executed. 

In issue #66 I see that there are issues with manually bootstrapped applications; however,
I am not getting any errors. I do get different behavior when working with apps which are bootstrapped with ng-app, in which the real modules code is not executed at all. Could this be an issue with using a manually bootstrapped application?

**Comment by pablolopezmera** [comment]
Did you get resolved?

**Comment by thawon** [comment]
I am also having the same issue where requireJs is used and need to manually bootstrap. 

ApacheTyler, do you a solution, if yes, could you please share the code?

juliemr, is there a plan for the Protractor to support manual bootstrap in the future?

**Comment by ApacheTyler** [comment]
I was not able to find a solution.

**Comment by thawon** [comment]
Thanks for letting me know, I did not find anything either so I decided to give up using requireJs.

**Comment by americoneto1** [comment]
@ApacheTyler Did you test with ignoreSynchonization disabled before call browser.get? I tested here and works well!

**Comment by ApacheTyler** [comment]
@americoneto1 I havn't revisited this issue in over a year; but I believe so. Thanks for the update!
