### ISSUE TITLE
Please expose the prototype's of `ElementFinder` and `ElementArrayFinder`

### ISSUE THREAD

**Issue by Joel-Kornbluh** [angular/protractor#1102]
I would love to see the prototype's of `ElementFinder` and `ElementArrayFinder` exposed, so it could be extended dynamically from within a pageObject or a test.

Just a suggestion!

**Comment by cjroth** [comment]
+1, this would be super useful for adding methods to elements such as the above.

**Comment by hankduan** [comment]
@cjroth It's actually there. See https://github.com/angular/protractor/issues/1584

**Comment by cjroth** [comment]
Oh. Awesome. Thanks @hankduan.
