### ISSUE TITLE
[Jasmine] "grep" option to selectively select it/describe cases to run from spec files

### ISSUE THREAD

**Issue by theogravity** [angular/protractor#1116]
I know that Protractor uses `minijasminenode` (was unsure to post here or there about it), and was wondering if there was a way to selectively run it/describe blocks based on a grep of the descriptor for the blocks. 

Using `iit` or `ddescribe` would not be feasible as we would have to manually go in to around a large amount of test files to exclusively include (or exclude via `xit` or `xdescribe`).

The functionality would be like how `mocha` has a `-g` option.

```
  -g, --grep <pattern>            only run tests matching <pattern>
  -i, --invert                    inverts --grep matches
```

**Comment by hankduan** [comment]
implemented at https://github.com/angular/protractor/pull/1690

**Comment by hankduan** [comment]
committed with https://github.com/angular/protractor/commit/0b930035905d1868225667de358222e51394f3ac

**Comment by sakshinagpal** [comment]
How to tag test cases based on test type like smoke test, regression test to make use of grep option
