### ISSUE TITLE
Fail except in promise's then causes test run to stop.

### ISSUE THREAD

**Issue by brad8118** [angular/protractor#1125]
I'm using Protractor(v 0.24.1), Cucumber(v 0.4.0), Chai(v 1.9.1) and Chai-as-promised (v 4.1.1). 
Selinium-server-standalone.jar (v 2.41.0)
chromedriver(v 2.10)

In this step I'm verifying the count 2 different ways. One in the then of the promise and the second way uses the chai-as-promised library to verify the count.

```
element.all(by.css('[ticket-id]')).then(function (tickets) {
    expect(tickets.length).to.equal(2, "length correct");
    //expect(tickets.length).to.equal(3, "length wrong");
});
expect(element.all(by.css('[ticket-id]')).count()).to.eventually.to.equal(2).and.notify(next);
```

This passes and I get the message:

```
1 scenario (1 passed)
3 steps (3 passed)
Process finished with exit code 0
```

Now when I change the expect inside the then to fail everything dies.

```
element.all(by.css('[ticket-id]')).then(function (tickets) {
    //expect(tickets.length).to.equal(2, "length correct");
    expect(tickets.length).to.equal(3, "length wrong");
});
```

Now I only get the message:

```
Process finished with exit code 1
```

This failure stops the test execution without a stack trace or anything to help debug.
Does anyone know why or a way around this?

We are looking at updating Protractor which might help.

**Comment by aluzardo** [comment]
Similar issue happening with protractor 4 https://github.com/angular/protractor/issues/3491 https://github.com/angular/protractor/issues/3553
