### ISSUE TITLE
Add conventional wisdom document?

### ISSUE THREAD

**Issue by cesarandreu** [angular/protractor#1134]
As I've been writing tests, I've discovered which things are better suited as e2e or unit tests. When I first got started with protractor I wanted to test *everything* on my app with protractor, but then it started taking a long time for the whole suite to run. I eventually started to cut back on what I was testing with protractor, focusing on testing key user interactions.

I think it'd be extremely useful to have a reference doc with conventional wisdom. I'd assume that just like me, this is be the first time a lot of people do e2e/integration testing.

One example is the page objects document, which I found really useful when getting started. It helped me write better tests, because I could change a page, and then I would only have to update the page object, not all of my tests. 

Another example, in the [JavaScript Jabber podcast on Protractor](http://javascriptjabber.com/106-jsj-protractor-with-julie-ralph/) a lot of great suggestions are given:

> I think there are a couple of types of weird things. If it’s a weird thing that you can catch in unit tests like validation for a form, you don’t want to check every type of form validation using and end-to-end test because you could just take forever on that. But other things like what if you get an error from the server? That’s something that you might not be able to test really well in a unit test where there’s no real server and no full UI and you want to see. If you have a butter bar, does the butter bar show up? So, I think you have to pick carefully the bad cases that you want to test and things that are related to what’s going on with the server, what’s going on with something like user authentication or interaction with third parties, are probably the areas where you’ll get a lot of benefit.

A lot of things that were mentioned in the podcast were things that I ended up learning on my own.

I would propose either adding a new file to the docs or a section in the FAQ.  If it seems like a good idea, I can create a PR, and we could go on from there, slowly iterating on it. Thoughts? Otherwise I'll probably just create a blog post, but that's would get less exposure.

**Comment by juliemr** [comment]
@andresdominguez Can we modify and externally publish the best practices doc you wrote? I think it would answer a lot of these questions.

**Comment by andresdominguez** [comment]
@juliemr I will.

**Comment by juliemr** [comment]
cc @CarmenPopoviciu

**Comment by NickTomlin** [comment]
I'm going to close this now that the [style guide](https://github.com/angular/protractor/blob/master/docs/style-guide.md) has been merged in by dd4ef900867ab72a5e58b2f34fdeb3fda94788cc.
