### ISSUE TITLE
How to take screen shot of the application whenever expect fails

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#114]
Is there any wait to capture screen shot of the application whenever expect fails. Idea it to capture all points of failure. Selenium driver supports some feature like this.Is there any kind of switch in protractor also .

**Comment by abhishekswain** [comment]
I have written a Protractor plug in , that takes screenshot for every 'expect' failure and spec failure as well. Screenshot names are meaningful too.
Here is the npm module:
https://www.npmjs.com/package/jasmine2-protractor-utils

Note: It is compatible with Jasmine2 only.

**Comment by sjelin** [comment]
@abhishekswain You want me to add your plugin to the [community plugins](http://www.protractortest.org/#/plugins#community-plugins) list?

**Comment by abhishekswain** [comment]
@sjelin Yes please , if it is possible. :)
Somehow I missed your mention here and it got skipped for a long time now.

**Comment by bhantol** [comment]
Any way to take screenshot of the screen while (and including) Javascript alert open captured ?

**Comment by azachar** [comment]
Hi there!

I have forked and improved @abhishekswain tool.  

Now the brand new fork called [protractor-screenshoter-plugin] (https://github.com/azachar/protractor-screenshoter-plugin)  captures for **each browser instance** a screenshot and console logs. The snapshot is made optionally for each expect or spec. It comes with a beautiful angular and bootstrap based analytics tool to visually check and fix tests results.

Check it out at https://github.com/azachar/protractor-screenshoter-plugin.

Also, I created a list of all available [alternatives] (https://github.com/azachar/protractor-screenshoter-plugin/wiki/Alernatives), so if you find something else, please do not hesitate to add it there.

**Comment by Sereda-Fazen** [comment]
Hi all! Could you help me to investigate jasmine-allure for fails screens?
I got next 
```
 jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));	
    var AllureReporter = require('jasmine-allure-reporter');
    jasmine.getEnv().addReporter(new AllureReporter({
        resultsDir: 'reports/allure-results'
    }));
	var pass = jasmine.getEnv().afterEach(function(done){
      if(!pass)
      browser.takeScreenshot().then(function (png) {
			allure.createAttachment('Screenshot', function () {
			  return new Buffer(png, 'base64')
			}, 'image/png')();
			done();
		  })
    })
```

**Comment by azachar** [comment]
Hi there, 

Feel free to use https://github.com/azachar/protractor-screenshoter-plugin <https://github.com/azachar/protractor-screenshoter-plugin>  instead (disclaimer: I am the maintainer of it).

Cheers,
Andrej
