### ISSUE TITLE
Object [object Object] has no method 'cssContainingText'

### ISSUE THREAD

**Issue by deloschang** [angular/protractor#1141]
Trying to use the method cssContainingText in order to select a particular value from a dropdown in Protractor. 

The method seems to be outlined here: https://github.com/angular/protractor/blob/master/docs/api.md#api-protractorby-prototype-csscontainingtext

> ```
>  element(by.cssContainingText('option', 'System Productivity')).click();
> ```

Output: 

>  TypeError: Object [object Object] has no method 'cssContainingText'

Am I missing something?

Edit: Using Protractor v1.0.0

**Comment by ebragaparah** [comment]
I'm here just to thanks @mattvv for the help with `cssContainingText` method. Awesome.
