### ISSUE TITLE
How do I simulate a page refresh?

### ISSUE THREAD

**Issue by staalburger** [angular/protractor#1143]
I want to test my apps view for the event that a user might refresh the page by either pressing "F5" or by using the browser's refresh button.

How would an e2e test with AngularJS and Protractor look like?
I cannot seem to get any relevant information on the web.

Thank you.

**Comment by smitabusar** [comment]
browser.driver.navigate().refresh() vs browser.refresh().
browser.refresh() - refresh to the url that I used in browser.get()
browser.driver.navigate().refresh() - refreshes the current url in the window. It respects the click after the browser.get().

Thanks Andy

**Comment by webbywebb** [comment]
Is there such a think as a hard browser refresh (Shift-Refresh)?
