### ISSUE TITLE
Element not clickable in IE

### ISSUE THREAD

**Issue by ToddRB** [angular/protractor#1144]
I've got some buttons in Internet Explorer that I am unable to access via .click() or .sendKeys();

I can perform checks on them return true, but any actions against them fail. The same test works fine in Chrome. 

ptor.findElement(protractor.By.id('TransferFromBtn_0')).then(function (result) {
                expect(result.isEnabled).toBeTruthy();
                expect(result.isDisplayed).toBeTruthy();                
            });

The above checks both return true. The actions below both fail with "Element is not displayed".
  
ptor.findElement(protractor.By.id('TransferFromBtn_0')).sendKeys(protractor.Key.ENTER); 
ptor.findElement(protractor.By.id('TransferFromBtn_0')).click();

Any ideas?

**Comment by juliemr** [comment]
Haven't heard any updates. Please open a new issue if there is a still a problem.
