### ISSUE TITLE
seleniumAddress under SSL

### ISSUE THREAD

**Issue by zazoomauro** [angular/protractor#1150]
I'm trying to run my tests using appium under an https server.
But my server is retuning me that log:
`[01/Aug/2014:08:24:26 +0000] [http] "POST /wd/hub/session HTTP/1.1" 301 178 "-" "-"`
I'm setting up the server address in the seleniumAddress field

**Comment by burkestar** [comment]
It seems that selenium-webdriver only supports HTTP and not HTTPS for seleniumAddress.
