### ISSUE TITLE
seleniumServerJar does not work on mac

### ISSUE THREAD

**Issue by vipper** [angular/protractor#116]
Guys,

Im trying use seleniumServerJar option on a mac and the below error is presented.

/Users/damorim/Gitspace/orientacao_pedagogica/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
Error: Server exited with 1
    at Error (<anonymous>)
    at ChildProcess.onServerExit (/Users/damorim/Gitspace/orientacao_pedagogica/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:193:11)
    at ChildProcess.g (events.js:175:14)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)

Do you have some idea what is going on?

my config file is below:
exports.config = {

  seleniumServerJar: '../../selenium/selenium-server-standalone-2.35.0.jar',
  seleniumPort: 4444,
  chromeDriver: '../../selenium/chromedriver',

  capabilities: {
    'browserName': 'chrome'
  },
  specs: ['onProtractorRunner.js'],

  jasmineNodeOpts: {
    showColors: true,
  }
};

**Comment by vikikamath** [comment]
get up-to-date path using `path.relative`.
```js
   const path = require(`path`);
   const jar = require(`selenium-server-standalone-jar`);
   
   // somewhere in the protractor config
  'seleniumServerJar':  path.relative(require.resolve(`protractor`), jar.path)

```
