### ISSUE TITLE
Dragging mouse on the screen

### ISSUE THREAD

**Issue by aarkanov** [angular/protractor#1194]
Hi, 

Not sure if anyone has encountered this issue, but I have a webapp where I need to swipe between screens (i.e drag the mouse from one side to another).

I've tried using:

```
   browser.actions().mouseMove({x:0, y:300}).mouseMove({x:200, y:300}).perform();
```

but that doesn't seem to do anything, and I don't get any errors. Does anyone have any suggestions?

Any help would be appreciated.

**Comment by dhinakarankannan** [comment]
var plot0 = ptor.element(protractor.By.id(''));
			ptor.driver.actions()
			.dragAndDrop(plot0, {x: 100, y: 100})
			.mouseMove(plot0, {x: 100, y: 100}) // 100px from left, 100 px from top of plot0
			.mouseDown()
			.mouseMove({x: 400, y: 0}) // 400px to the right of current location
			.perform();

**Comment by maiasmith** [comment]
I figured out how to draw a rectangular loop on the screen with simulated mouse down, drags, and mouse up:
```

browser.driver.actions()
      .mouseDown(graphElement)
      .mouseMove({ x: 200, y: 0 })
      .mouseMove({ x: 0, y: 200 })
      .mouseMove({ x: -200, y: 0 })
      .mouseMove({ x: 0, y: -200 })
      .mouseMove({ x: 200, y: 0 })
      .mouseUp()
      .perform();
```
