### ISSUE TITLE
How do I get the current url from protractor?

### ISSUE THREAD

**Issue by sheldonhall** [angular/protractor#120]
I get the following error message:  Object [object Object] has no method 'currentUrl'

My code is below

var util = require('util');

describe('validate login', function() {
  var ptor;

  describe('in forms', function() {
    ptor = protractor.getInstance();

```
beforeEach(function() {
  ptor.get('test/mobile/login');
},20000);


it('should find the login page', function() {
ptor.waitForAngular();
    expect(ptor.currentUrl()).toContain('mobile/login');
}, 200000);
```

 });
});

**Comment by edgarechm** [comment]
get CurrentUrl will return the full URL address(hostname+path+...).

What about the hostname or domain only?
