### ISSUE TITLE
How to validate that bootstrap validation popup message is being displayed ? [question]

### ISSUE THREAD

**Issue by JesusLopezCh** [angular/protractor#1209]
Whenever I click on save/submit button leaving field in blank, or entering an invalid email, validation error message is displayed, is there any way I can validate this?, since it is not in the DOM.

![bootstrap popup](https://cloud.githubusercontent.com/assets/7446271/3974266/24485a8e-27f2-11e4-8dcf-f9a8afa166a4.png)

**Comment by sharath7kashyap** [comment]
Hi , did anyone find a solution for this problem?
