### ISSUE TITLE
Run protractor tests in eclipse

### ISSUE THREAD

**Issue by prajula** [angular/protractor#1211]
I am new to Protractor and I have successfully run the tests . I want to create a project in SVN which suits eclipse environment, so that it can be run from anywhere.
How can i create a project under eclipse to run these tests? Or Do I need a different IDE to do that? Or any suggestions to achieve it? 
Please guide me through this.

**Comment by patro1985** [comment]
I am looking for some insights of protractor testing in eclipse, can anybody please provide some code samples or steps to begin with, thanks!

**Comment by testcts** [comment]
Hi,
I new in protractor and also looking for the same, how can setup protractor in eclipse or any others  free tool IDE therefore can i use for protractor. Please anybody suggest or provide some detailed steps to begin with.
Thanks!!

**Comment by Lmahalin** [comment]
Even i am searching the same for dayysssss please help us guys. I have used the Webstorm it is a licence version. Also is there any other tool (Free and Opensource) that can be used to setup protractor for writing and executing code.

**Comment by angelozerr** [comment]
For your information, AngularJS Eclipse starts providing a protractor support. See https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor

**Comment by Lmahalin** [comment]
guys better search for any crack file for webstorm r there is a activation key use that. Webstorm is very useful now.

**Comment by utkarsh56** [comment]
Hi angelozerr,
I am looking for some insights of protractor testing in eclipse using page object approach, can you please provide some code samples so that i can import in eclipse and proceed further.
I have gone through all the links, got all the basics idea but i want how to proceed in eclipse.
Please team if you have sample project share it.

**Comment by angelozerr** [comment]
@utkarsh56 I'm very busy please take time to read https://github.com/angelozerr/angularjs-eclipse/wiki/Protractor

If you have some questions, problems, please create issues at https://github.com/angelozerr/angularjs-eclipse/issues to avoid disturbing this github.
