### ISSUE TITLE
by.repeater not working on angularjs example from website

### ISSUE THREAD

**Issue by vipper** [angular/protractor#1212]
Hi,

I've used those angularjs examples form the website to give trainings and hands on.
One of them is this below:
        li ng-repeat="todo in todos"
            input type="checkbox" ng-model="todo.done"
            span class="done-{{todo.done}}" {{todo.text}} /span
        /li
and in this case when I try to use the follow command it doesn't work:
element(by.repeater('todo in todos').row(0).column('todo.text'));

I'm facing this error:
Error: No element found using locator: by.repeater("todo in todos").row("0").column("todo.text")
Would I be doing something wrong?

**Comment by askie** [comment]
+1
