### ISSUE TITLE
Use ES7 Generators for flow management

### ISSUE THREAD

**Issue by urish** [angular/protractor#1214]
The current way protractor handles async control flows includes a lot of magic - and I believe it can be greatly simplified by using ES6 Generators. Consider this code example, adapted from [angular.js documentation](https://docs.angularjs.org/guide/e2e-testing):

      it('should filter results', function*() {
        yield element(by.model('user')).sendKeys('jacksparrow');
        yield element(by.css(':button')).click();
    
        var tasks = yield elements.all(by.repeater('task in tasks'));
        expect(yield tasks.length).toEqual(10);
        var firstTaskText = (yield tasks[0].getText()).toLowerCase();

        // Yield makes it simple to use the result of one call as a parameter to another one:
        element(by.model('filterText')).sendKeys(firstTaskText);

        // Verify that now there is only one item in the task list
        tasks = yield element.all(by.repeater('task in tasks'));
        expect(tasks.length).toEqual(1);
      });

Thoughts?

**Comment by juandopazo** [comment]
FWIW, this shouldn't be implemented with generators. It should be implemented with async functions. And there is nothing that really needs to happen, except for maintaining Mocha's handling of promises.

Same example using an async function and Mocha:

```js
  it('should filter results', async function () {
    await element(by.model('user')).sendKeys('jacksparrow');
    await element(by.css(':button')).click();

    var tasks = await elements.all(by.repeater('task in tasks'));
    expect(tasks.length).toEqual(10);
    var firstTaskText = (await tasks[0].getText()).toLowerCase();

    // await makes it simple to use the result of one call as a parameter to another one:
    element(by.model('filterText')).sendKeys(firstTaskText);

    // Verify that now there is only one item in the task list
    tasks = await element.all(by.repeater('task in tasks'));
    expect(tasks.length).toEqual(1);
  });
```

No need to write something custom that understands generators. The async function always returns a promise and if anything throws inside it, the promise is rejected. And that's how Mocha gets the test result.

**Comment by juliemr** [comment]
Check out the example of this working at https://github.com/angular/protractor/tree/master/exampleTypescript/asyncAwait
