### ISSUE TITLE
problems running angularjs e2e testing with protractor in phantomjs

### ISSUE THREAD

**Issue by svuppala** [angular/protractor#1229]
When doing E2E tests with Protractor and PhantomJS and doing things like

expect(element(by.repeater('book in library') row(0).column('{{book.name}}')).getText()).toBe('Some Text');
fails only in PhantomJS, but not in Firefox or Chrome.

Html

<div>
  <ui tabset> 
    <li tab ng-repeat="book in library track by id"> 
      <span tab-heading>{{book.name}}</span>      
      <div ui-view="test"></div>
    </li>
  </ui>
</div>
Protractor E2E test case:

 it('test', function () {
  var bookName = element(by.repeater('book in library track by id').row(0).column('{{book.name}}'));
  expect(bookName.getText()).toEqual('test');
 });
I am using angularjs 1.2.14, protractor:1.0.0-rc4, phantomjs:1.9.7-14 on linux This test case runs well in Chrome and Firefox but fails in PhantomJS and the error I get is

 Error:Expected '' to equal 'test'
When I do count on rows works fine but trying to fetch column value, I am getting the empty string.

// works fine:
expect(element.all(by.repeater('book in library track by id')).count()).toEqual(9); 
// test fails:
expect(bookName.getText()).toEqual('test');
Is there way to fix this?

**Comment by jberube** [comment]
@svuppala , I had a similar problem and worked around it by replacing :
```javascript
return element(by.className('navbar-title')).getText();
```
by
```javascript
return element(by.css('.navbar-title span')).getWebElement().getInnerHtml();
```
for the given html:
```html
<div class="navbar-title"><span class="ng-binding">Select a theme</span></div>
```

**Comment by gesellix** [comment]
We have the same problem and also made it work by changing `getText()` to `getInnerHtml()` (without `getWebElement()`). Would this issue be Protractor specific or should we file an issue at the PhantomJS project?

**Comment by jberube** [comment]
For posterity:

`getText()` returns the text in the visible part of the element, or an empty string if the element is hidden somehow. See http://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.getText

In my particular case, the viewport of phantomjs was ridiculously small (300x400 if i remember correctly).

I have a mediaquery that hides the element when the screen is narrow, so `getText()` was actually right: there was no text _displayed_.

Setting your phantomjs viewport to a reasonable size could also have an impact on the result of `getText()`.

**Comment by juliemr** [comment]
Sounds like the issue was small viewport. Closing as answered.
