### ISSUE TITLE
sendKeys on tel input fields not working in Chrome

### ISSUE THREAD

**Issue by rtsio** [angular/protractor#1232]
`element(by.id('phone')).sendKeys('5555');` (it does not matter what the input is, it can be a valid phone number) on an `<input type="tel">` will not work in Chrome; the driver will focus the phone field, but not send any keys and then move on to the next thing. The expected behavior however works in Firefox. I haven't tested other drivers to see if it's just Chrome. 

Running this on Sauce Labs.

**Comment by superxuwei** [comment]
sendKeys on tel input fields not working in Phantomjs

**Comment by superxuwei** [comment]
same issue, in phantomjs.

            cardObj = self.browser.find_element_by_id("cardNo")
            is_visiable = self.check_element_visiable(cardObj)
            if is_visiable:
                cardObj.send_keys(code)
            else:
                raise Exception("cardNo Obj is no visiable!!!")

 "cardObj.send_keys(code)" is not working.
