### ISSUE TITLE
Add option to automatically redirect browser logs

### ISSUE THREAD

**Issue by gunta** [angular/protractor#1234]
This is a feature request about usability.

Currently, to see the browser console **errors/logs**, one has to write the [following](https://github.com/angular/protractor/blob/master/docs/faq.md#how-can-i-get-hold-of-the-browsers-console) in **every test suite**, which is far from being user-friendly:

```javascript
afterEach(function() {
    browser.manage().logs().get('browser').then(function(browserLog) {
      console.log('log: ' + require('util').inspect(browserLog))
    })
  })
```

Please add an option like `browserLogs: true` to be able to accomplish this in any project/suite without having to resort to the above code.

Also, currently even by executing this, one gets a quite ugly (non formatted and uncolored) log like the following:
```
log: [ { level: { value: 1000, name: 'SEVERE' },
    message: 'http://localhost:7120/api/v1/auth/mock 0:0 Failed to load resource: the server responded with a status of 400 (Bad Request)',
    timestamp: 1409043866570,
    type: '' },
  { level: { value: 1000, name: 'SEVERE' },
    message: 'http://localhost:7120/api/v1/auth/mock 0:0 Failed to load resource: the server responded with a status of 400 (Bad Request)',
    timestamp: 1409043867771,
    type: '' },
  { level: { value: 1000, name: 'SEVERE' },
    message: 'http://localhost:7120/api/v1/auth/mock 0:0 Failed to load resource: the server responded with a status of 400 (Bad Request)',
    timestamp: 1409043900321,
    type: '' } ]
```
The above could be improved easily by human-readable formatting and some [nice coloring](https://github.com/sindresorhus/chalk).

Given that currently a lot of errors will go **unnoticed**, and the whole purpose of testing is to be aware of bugs early and often, it seems important that this option is set to **true** by default.

**Comment by juliemr** [comment]
Done with https://github.com/angular/protractor/pull/1916
