### ISSUE TITLE
Error: Invalid or corrupt jarfile when installing from node

### ISSUE THREAD

**Issue by dasois** [angular/protractor#1243]
I run node.js v0.10.30 on Arch-Linux and did `npm install protractor -g` and then `webdriver-manager update`.
After that i tried `webdriver-manager start` and I get:
`Error: Invalid or corrupt jarfile /usr/lib/node_modules/protractor/selenium/selenium-server-standalone-2.42.2.jar`

According to [this Stackoverflow answer](http://stackoverflow.com/a/20684302/3085821) it seems to be a corrupt version on npm?

**Comment by karthiktv006** [comment]
I am seeing SELF_SIGNED_CERT_IN_CHAIN error recently. Is there a way to resolve this issue?
