### ISSUE TITLE
If an XPath selector containing unicode characters is passed to by.xpath, no element can be found.

### ISSUE THREAD

**Issue by crocket** [angular/protractor#1249]
```
element(by.xpath(//tr[contains(@class, 'itemList') and not(contains(@class, 'folder'))]/td[@id='fileName']/a[contains(normalize-space(.), 'BnR_\uD070_\uBC14\uC704_\uC5BC\uAD74.epub')])).click()
```
doesn't work because it contains unicode characters.

However, if I pass the same xpath selector to $x defined by jQuery, $x finds the relevant element very well.

Therefore I concluded that by.xpath works for ascii characters but not for unicode characters.

How do I fix it?

**Comment by juliemr** [comment]
This is a webdriver behavior that Protractor has no control over.
