### ISSUE TITLE
[Feature request] seleniumServerJar wildcard in path

### ISSUE THREAD

**Issue by Anubis-Black** [angular/protractor#1265]
I am not quite sure how oftern the Selenium standalone version is updated, but having to hard code the path to a specific version means that it needs to be changed every time an update appears. If the seleniumServerJar could understand 

```javascript
'../node_modules/protractor/selenium/selenium-server-standalone-*.jar'
```
or
```javascript
'../node_modules/protractor/selenium/selenium-server-standalone-^2.42.2.jar'
```
or
```javascript
'../node_modules/protractor/selenium/selenium-server-standalone-~2.42.2.jar'
```
(similar to Bower and npm), then this problem would be avoided. Another possible solution is to have the webdriver-manager modify the seleniumServerJar variable in the file upon update completion.

**Comment by cnishina** [comment]
Please see #2998.

In lieu of wildcard matching, the `config.json` can be overridden to download and start different versions of selenium server. The different versions that could be downloaded are listed on the [selenium-release](https://selenium-release.storage.googleapis.com/) page.
