### ISSUE TITLE
How well is Mocha Support in Protractor?

### ISSUE THREAD

**Issue by demisx** [angular/protractor#1274]
Hi. We are considering standardizing our testing framework to be `Mocha+Chai` across the board (Angular + Node.js/Express). The protractor docs mention limited support for Mocha. I am wondering how limited that is. Will I be able to substitute current Jasmine framework with the Mocha one and still have a smile at the end of the day? Please share your experience. Thank you!

**Comment by canercandan** [comment]
:+1: works very well however I didnt succeed to use the mocha --watch option by using:
```
mochaOpts: {
    ui: 'bdd',
    reporter: 'dot',
    timeout: 30000,
    bail: true,
    watch: true
}
```

Any help on this ?

Thanks

**Comment by canercandan** [comment]
Edit: I fixed the `watch` issue at the grunt level with `grunt-contrib-watch`

**Comment by demisx** [comment]
@canercandan We use `gulp.watch()` for watching various types of code. For unit tests, we usually do something like this:

```js
gulp.task('unit', function () {
  gulp.src('app/**/*.spec.js', { read: false })
    .pipe(mocha({
      reporter: 'dot',
      bail: true
    }))
    .on('error', function (err) {
      console.error(colors.red(err));
    });
});

gulp.task('watch:unit', function () {
  gulp.watch('app/**/*.js', gulp.parallel('unit'));
});
... ... ...

```

**Comment by canercandan** [comment]
@demisx thanks for your code snippet very useful. I had an issue with mocha output colors that were hidden when I was using grunt, problem fixed with gulp :+1:
