### ISSUE TITLE
Not clicking on menu option after right clicking on app in chrome.

### ISSUE THREAD

**Issue by satpal82bhandari** [angular/protractor#1280]
I did this : -

describe('should drag and drop', function() {
ptor = protractor.getInstance();
driver = browser.driver;
it('should drag and drop', function() {

driver.get('http://codef0rmer.github.io/angular-dragdrop/#/');
driver.manage().window().maximize();
browser.waitForAngular();
var dragElement = element(by.model("list1"));

dragElement.click();
driver.actions().click(protractor.Button.RIGHT).perform();  // For doing right click on mouse.
driver.actions().sendKeys(webdriver.Key.ARROW_DOWN).perform(); //To send arrow down.
driver.actions().sendKeys(webdriver.Key.ENTER).perform();  // To send enter.

}, 60000);

});

Same code is clickingthe menu after right click on mouse on firfox as well as on IE. but on chrome. it shows the option after right click but does not click on any option . also it is not giving any error. test scripts just pass.

**Comment by Zrollan** [comment]
I'm facing the same problem now,have you find a way to solve this?
