### ISSUE TITLE
Sharding and reporting issue

### ISSUE THREAD

**Issue by lightsaway** [angular/protractor#1281]
When tests are executed with shardTestFiles option set to true, reports per each file are created separately, since onPrepare is called per each file and only on this level new Reporter instance is added to Reportes. Can there be a way to create more global onPrepare function, to attach something like whole suite listener once per suite?
Here is example config:

``` javascript
exports.config = {
    seleniumAddress: seleniumAddress || 'http://localhost:4444/wd/hub',
    multiCapabilities: [

        {
            'browserName': 'chrome',
            'version': browserVersion || '',
            shardTestFiles: true,
            maxInstances: 1
        }
    ],
    suites: {
        homepage: ['specs/loginTest.js', 'specs/angularTest.js']
    },
    jasmineNodeOpts: { showColors: true,
        isVerbose: true,
        includeStackTrace: true
    },
    onPrepare: function () {
        require('jasmine-reporters');
        var HtmlReporter = require('protractor-html-screenshot-reporter');
        jasmine.getEnv().addReporter(new HtmlReporter({
            baseDirectory: 'screenshots33', docTitle: 'my reporter'
        }));
    }
};
```

At this point only last executing spec will be reported (since it is overridden). But i think it should be grouped.

**Comment by oliverdennis** [comment]
Hi there,

I tried this but is doesn't seem to work for me, I still only see one of the shards in the results. I also saw this which seems to indicate the feature isn't available yet;

https://github.com/jintoppy/protractor-html-screenshot-reporter/issues/43

**Comment by adokania** [comment]
Is this resolved anywhere? I see the files only for one of the shards as well

**Comment by d-werner** [comment]
I experience the same problem with each shard overwriting the previous report (protractor 3.2.2, jasmine-reporters 2.1.1).

And lightsaway's solution does not work for me, too. For every single spec being tested a new reporter instance is created. States in the scope of the config file are not stored across the test runs.

**Comment by Xotabu4** [comment]
Hi, is there any working solution? Tried singleton, and https://github.com/bhovhannes/junit-report-merger
And both does not work.

**Comment by qualityshepherd** [comment]
Yeah, this doesn't work for me either... sadface

**Comment by nnennajohn** [comment]
Me too. :(

**Comment by Xotabu4** [comment]
@nnennajohn @qualityshepherd 
I did reporting with:
https://github.com/bhovhannes/junit-report-merger


So logic is - 
1) Generating separate junit xml for each thread
2) After - using this merger in afterLaunch function in config to combine all together. Here is my code, hope this might help
```javascript
combineReportFiles(SPECS_REPORTS_PATH, JUNIT_TEST_REPORT, exitCode) {
        // Since shardTestFiles = true; executes onPrepare() each time - our report files are overwritten each execution.
        // Logic is to report results from test files each to his own file, and then combine into one XML file,
        // that is suitable for Jenkins

        var xmlMerger = require('junit-report-merger');
        var fs = require('fs');
        var defferMerge = Promise.defer();

        let filesList = fs.readdirSync(SPECS_REPORTS_PATH);
        let filesWithPaths = filesList.map(function (filename) {
            return `${SPECS_REPORTS_PATH}/${filename}`;
        });

        console.log('Combining all XML files with specs reports into one...', filesWithPaths);
        // It took me 2 days to understand that 3rd parameter is options, not callback.
        xmlMerger.mergeFiles(JUNIT_TEST_REPORT, filesWithPaths, undefined, function (err, result) {
            if (err) {
                console.error(err, '\n Problems while combining test results to single file.')
            } else {
                console.log(`JUNIT test report created: ${JUNIT_TEST_REPORT} `);
            }
            defferMerge.resolve(exitCode);
        });
//Returning promise - protractor will wait for it to be resolved before finishing nodejs process.
        return defferMerge.promise;
    };
```

**Comment by Saqibm128** [comment]
I think I tried the singleton option. It appears that since protractor.conf.js is called multiple times when shardTestFiles is set, that its not fundamentally a singleton anymore...

**Comment by Saqibm128** [comment]
```
var Base = require('mocha').reporters.Base
var mochaMulti = require('mocha-multi')

var getReporter = function(runner, options) {
		if (global.currentReporter) {
			console.log("was already populated")
			Base.call(global.currentReporter, runner)
			global.currentReporter._reporters.forEach(reporter => Base.call(reporter, runner))
		} else {
			console.log("we hit/n/n/n\n\n\n\n")
			console.log(global.currentReporter)
			global.currentReporter = mochaMulti
			global.currentReporter(runner, options)
		}
		console.log("returning", currentReporter)
}
```

**Comment by Saqibm128** [comment]
looked at code... they start a new command line process each time for each file, which seems stupid >:(
