### ISSUE TITLE
New_York time-zone not supported in default capabilities for Selenium/Saucelabs?

### ISSUE THREAD

**Issue by mattysan** [angular/protractor#1287]
I don't know if this is an issue on the protractor side or the SauceLabs side, but I'm trying to change the time zone of a SauceLabs VM using defaultCapabilities in the protractor config file to EST (New_York):

  exports.config.multiCapabilities = [_.assign({}, defaultCapabilities, {
    "time-zone": "New_York",
    "browserName": "firefox",
    "version": "30"
  }), _.assign({}, defaultCapabilities, {
    "time-zone": "New_York",
    "browserName": "chrome",
    "version": "35",
    "platform": "OS X 10.9"
  })];

I receive an error that it is an unsupported time zone. When I pass in Chicago or Detroit, it works as expected. When I pass in New_York, it says it is unsupported. Thoughts?

**Comment by valeria20** [comment]
Hi! Coul you help me. How to set local/custom time zone for protractor test?
'timeZone': 'London' in capability doesn't work.

**Comment by wswebcreation** [comment]
@valeria20 

You are reacting on a closed issue. I don't think this is smart. Secondly your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
