### ISSUE TITLE
[Feature request][webdriver-manager] Allow a command-line switch to get 32bit browser driver(s)

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1297]
The 64bit IE driver is horrendously bad when used with recent versions of IE - see selenium's [bug tracker](https://code.google.com/p/selenium/issues/detail?id=5116).

Currently, if I want to test IE with protractor, I need to run `node webdriver-manager update`, then manually download the 32bit IE driver. Currently, there is the `--ie` switch for webdriver-manager, but it will _always_ get the 64bit IE driver if your system architecture is 64bit. It would be pretty nice to specify `--ie32` or something to automatically download the 32bit IE driver

**Comment by dpaquette** [comment]
+1
This is desperately needed

**Comment by codecadwallader** [comment]
+1 as well.  Currently I'm using a workaround of running 32-bit node (See #1506).

**Comment by rogierschouten** [comment]
+1

**Comment by rogierschouten** [comment]
Fixed in PR #2406
