### ISSUE TITLE
Question: How to add cookie?

### ISSUE THREAD

**Issue by Surekh** [angular/protractor#130]
Hi. I am trying to add cookie like this -

beforeEach(function(){
        ptor = protractor.getInstance();
        var test_cookie = new Object();
        test_cookie = {
            "name": "test",
            "value": "some value"
        };
        ptor.manage().addCookie( test_cookie );
    });

But it fails and I see Message: UnknownError: java.util.HashMap cannot be cast to java.lang.String. 

Can you help me?

**Comment by pmerson** [comment]
The parameters to addCookie changed in Protractor 5 / webdriver 3. 
[See more on SO](https://stackoverflow.com/a/41820302/317522).
