### ISSUE TITLE
Add command for element explorer

### ISSUE THREAD

**Issue by FrankyBoy** [angular/protractor#1314]
Hi!
Please add a command for the element-explorer. Its a very useful tool, but having to do "node [huge-path-to-js]" is very inconvenient as well as hiding the (again: very useful) tool from the users.
Ty :)

PS: sorry if there is already a defect for this, didn't find any.

**Comment by hankduan** [comment]
After https://github.com/angular/protractor/pull/1693, elementExplorer will be part of protractor. 
Run elementExplorer via `protractor --elementExplorer [options] [configFile]`.
