### ISSUE TITLE
Have element-explorer use embedded chrome driver

### ISSUE THREAD

**Issue by FrankyBoy** [angular/protractor#1315]
I really like the option to use the embedded chrome driver for protractor. It would be very convenient to be able to use the same in the element-explorer.

**Comment by hankduan** [comment]
After #1693, you can enter element explorer via flag `--elementExplorer`. You may use the embedded chrome driver by specifying either a conf or options like you would normally do when running protractor, for example:
  `protractor --elementExplorer --directConnect` 
or
  `protractor --elementExplorer conf.js`.

**Comment by FrankyBoy** [comment]
this is seriously neat!

**Comment by hankduan** [comment]
Done at https://github.com/angular/protractor/pull/1693#issuecomment-69835756
