### ISSUE TITLE
How to find date picker class object?

### ISSUE THREAD

**Issue by PriyaSr** [angular/protractor#1317]
In my Application, I have date picker class in one field. And I want it to be clicked automatically using protractor. To do so, the object have to be recognized by the protractor. Can anyone please help me to get interact with the date picker class..??

**Comment by Zehra-Naqvi-10p** [comment]
if we have two date picker fields one is working one is not please help
  1-element(by.model("vm.opp.date.start")).sendKeys("30 August 2015");
  2-element(by.model("vm.opp.date.end")).sendKeys("30 August 2015");

first one is works second not ???

**Comment by nealmadlani** [comment]
@Zehra-Naqvi-10p, probably going to need to see the code that you're trying to target. Also, usually this is due to race-conditions. Try putting in a sleep before the second one runs as perhaps the element is not on the page when your code runs.

**Comment by Zehra-Naqvi-10p** [comment]
I did, but for second picker it only opens picker dropdown and do nothing.
I added     mydriver.sleep(20); between these two

**Comment by nealmadlani** [comment]
@Zehra-Naqvi-10p Have you tried to do this manually? I don't know anything about the website, but is it possible to set the start-date and end-date as the same day? Seems like there could be validation stopping it. In the second picker, try a different date after the start-date.

**Comment by Zehra-Naqvi-10p** [comment]
no can't select same day.
oh! problem is it always take current date, I don't know why even I send different dates.
Do you have any Idea.
      it('From date', function()
      {
            element(by.model("vm.opp.date.start")).sendKeys("1 September 2015");


            console.log("-From date entered");
            mydriver.sleep(70);
        });

        it('To date', function()
        {
         element(by.model("vm.opp.date.end")).sendKeys("10 September 2015");


            console.log("-To date entered");
            mydriver.sleep(20);
        }, 60000);

**Comment by abbas-husain** [comment]
Even i am facing same date picker issue second picker it only opens picker dropdown and do nothing, however first one set the value

**Comment by abbas-husain** [comment]
1-element(by.model("vm.opp.date.start")).sendKeys("30 August 2015");
2-element(by.model("vm.opp.date.end")).sendKeys("30 August 2015");

second one not set

**Comment by SinghRajKr** [comment]
I would suggest going through this video link to automate datepicker using the class: https://www.youtube.com/watch?v=T8QRDQjt5lw&t=26s
