### ISSUE TITLE
 UnknownError: unknown error: Cannot read property 'get' of undefined with 1.3.0-rc.1  browser.wait

### ISSUE THREAD

**Issue by acostaf** [angular/protractor#1318]
Hi All

Just change my angular version from 1.3.88 to  1.3.0-rc.1 and found that all the browser.wait are broken with this bizarre error 'UnknownError: unknown error: Cannot read property 'get' of undefined' browser.wait(function () { return browser.isElementPresent(containersRepeater); }, 4000);

**Comment by MahendranShanmugam** [comment]
Hi ,

I am also getting this issue and i am using the 5.1.2 version.
Please see the below snap.
![image](https://user-images.githubusercontent.com/36536483/39816656-7bcc48f0-53b9-11e8-9e22-012bab8bad27.png)

Please provide the solution for this.

Regards,
Mahendran S.
