### ISSUE TITLE
mocha json reporter

### ISSUE THREAD

**Issue by devastadus** [angular/protractor#1321]
I think the mocha json reporter does not work with protractor. If i run a mocha test i can call `mocha myTest.js -R json`  and it will output to json. In my config file i change my mochaOpts so that it is now 

`mochaOpts: {
  reporter: "json"
  slow: 10000
}`

But still outputs to spec. Is there something I am missing or does the mocha json reporter not work?

**Comment by sjelin** [comment]
Works on my computer.  Maybe the bug got fixed in some update.
