### ISSUE TITLE
actions() not working as expected

### ISSUE THREAD

**Issue by mattysan** [angular/protractor#1328]
I was able to find a workaround, but after searching for how to perform a mouseMove onto an element, I saw a lot of examples showing that I could do:

ptor.actions().mouseMove(dayButton).perform();

...where dayButton is a WebElement that was already found. I verified that indeed dayButton is the correct WebElement by performing a click() operation on it. However, when I use it in the context above, I keep getting the following TypeError:

TypeError: Cannot read property 'x' of undefined

My workaround was:

browser.actions().mouseMove(dayButton.getLocation()).perform();

which does the trick. I guess I'm just surprised that, based on the suggestions posted here (https://github.com/angular/protractor/issues/159) and elsewhere, that my original line of code was not working.

**Comment by lubna-shaikh** [comment]
Get the following error 
`Failed: location.getId is not a function`
for 
`browser.driver.actions().click('#flightForm div:nth-child(1) mat-form-field').sendKeys("SIN").perform();`
