### ISSUE TITLE
How to automate file download using protractor?

### ISSUE THREAD

**Issue by narottamgla** [angular/protractor#1345]
When we download file than windows pop-up will open & not able to interact with  that pop-up in protractor.

**Comment by AnjumMomin** [comment]
When we download file than windows pop-up will open & not able to interact with that pop-up in protractor.....what's the solution??

**Comment by shitanshulall** [comment]
Under browser capabilities, for download preferences use property 'prompt_for_download':false
Example:
capabilities: {
        browserName: 'chrome',
        proxy: {
            proxyType: 'manual',
        },
        count: 1,
        shardTestFiles: false,
        maxInstances: 1,
        'chromeOptions': {
            args: ['--no-sandbox', '--test-type=browser'],
            // Set download path and avoid prompting for download even though
            // this is already the default on Chrome but for completeness
            prefs: {
                'download': {
                    **'prompt_for_download': false**,
                    'directory_upgrade': true,
                    'default_directory': 'Downloads'
                }
            }
        }
    }
