### ISSUE TITLE
Chrome preferences for browserstack

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#1354]
I'm experiencing a weird issue and I'm not sure on which side things go wrong.

I have a couple of tests with disabled javascript and disabled cookies. In order to disable js, you need to pass `--disable-javascript` argument in the chrome arguments; in oder to disable cookies, you need to set  `profile.default_content_settings.cookies` preference to `2`. This is proven to work for me.

The problem is that setting `prefs` object inside the `chromeOptions` doesn't work for browserstack:

``` javascript
capabilities: {
    'browserstack.user' : browserstackUser,
    'browserstack.key' : browserstackKey,
    'browserstack.local' : 'true',
    'browserstack.debug': 'true',

    'browserName' : 'chrome',
    'os' : 'OS X',
    'os_version' : 'Mavericks',
    'resolution' : '1024x768',

    chromeOptions: {
        args: [
            '--disable-javascript'
        ],
        prefs: {
            'profile.default_content_settings.cookies': 2
        }
    },

    specs: [
        'disabledCookies/*.js'
    ]
},
```

In this case javascript would get disabled, but cookies would be still enabled.

FYI, running the tests locally (changing `seleniumAddress` and omitting browserstack-specific keys) works perfectly.

Is it something on the protractor's side, or the problem is browserstack-specific? Thank you.

**Comment by UmangSardesai** [comment]
This works for me. Just checked on BrowserStack. 

```
var capabilities = {
  'browserName' : 'chrome',
  'browser_version' : '46.0',
  'browserstack.user' : '<username>',
  'browserstack.key' : '<automate-key>', 
  'chromeOptions': {
        prefs: {
          profile: {
            default_content_settings: {
              cookies: 2
            }
          }
        }
    } 
}
```

**Comment by alecxe** [comment]
@UmangSardesai thank you, I'll try that!
