### ISSUE TITLE
Support setting of Saucelabs session name

### ISSUE THREAD

**Issue by jabclab** [angular/protractor#1366]
I've got `protractor` up and running with Saucelabs using the following config:

``` js
var config = {
  sauceUser: process.env.SAUCELABS_USER,
  sauceKey: process.env.SAUCELABS_KEY
};
```

This is all working fine but the query I have is I don't appear to be able to set the name of the Saucelabs session hence we end up with the following:

![screen shot 2014-09-24 at 16 13 44](https://cloud.githubusercontent.com/assets/225286/4390469/7c3cb1f0-43fd-11e4-8b99-73a77fc549b4.png)

Would it be possible to add support for this, maybe via a `sauceSession` config parameter?

Something like the following would work nicely for us:

``` js
var pkg = require('./package');
var config = {
  sauceSession: pkg.name + '@' + pkg.version
};
```

Thanks :smile:

**Comment by abhagupta** [comment]
Hi @joshhornby , did you find a way to send the name of the test to Saucelabs? I am looking for a similar thing.
