### ISSUE TITLE
How to do Canvas Testing with Protractor

### ISSUE THREAD

**Issue by KamalakannanPE** [angular/protractor#1369]
Hi,
  I'm new to protractor, I need to test drawing on canvas. With Java in Selenium, I can able to simulate click and hold mouse button with clickAndHold() and as well as I can  move mouse with moveMouseOffsetTo(). But how can we achieve this with Protractor ?

**Comment by djom20** [comment]
Hi @juliemr ,

I have a similar issue right now, I have this code to move the mouse:

```
let _el = element(by.css('.signature-pad'));

browser.actions().mouseDown(_el).perform();

return browser.actions().mouseMove(_el, {
   x: 500,
   y: 50
}).perform();

browser.actions().mouseUp().perform();
```

But in the signature pad, I didn't get any move of the mouse or any error, so I had to use a plugin to see the cursor position and I get this image in the report:

![image](https://user-images.githubusercontent.com/1834808/45717042-590acc80-bb5e-11e8-9d12-7ef2841299e7.png)

Could you suggest me any solution for this situation?. It would be great if you could help me with this, Thanks.

**Comment by sedja** [comment]
Hey, @djom20 

If your question is still relevant, this worked for me

`
private drawLine(canvasElement) {
    const actions = browser.actions();

    return actions
      .mouseMove(canvasElement, { x: 50, y: 50 })
      .perform()
      .then(() => actions.mouseDown(canvasElement).perform())
      .then(() => actions.mouseMove(canvasElement, { x: 250, y: 250 }).perform())
      .then(() => actions.mouseUp(canvasElement).perform());
  }
`
