### ISSUE TITLE
Example of config file setting chrome user agent

### ISSUE THREAD

**Issue by sheldonhall** [angular/protractor#138]
I am pretty new to these style of tools and I know that there is documentation here: 

https://code.google.com/p/selenium/wiki/DesiredCapabilities#Proxy_JSON_Object

However I've tried a couple different ways to configure the user agent for chrome and it doesn't seem to work.

Can anyone provide an example of how I would configure this for protractor using a chrome webdriver?

This is what I have done:

  capabilities: {
    'browserName': 'chrome',
    'chrome-switches' : [{'user-agent' : 'Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30'}]
  },

**Comment by posva** [comment]
@AntonTrapp This is a year later, yet, I found this solution (http://stackoverflow.com/questions/26872481/activating-chrome-language-flags-when-activating-from-protractor-selenium)

```js
chromeOptions: {
      // How to set browser language (menus & so on)
      args: [ 'lang=fr-FR' ],
      // How to set Accept-Language header
      prefs: {
        intl: { accept_languages: "fr-FR" },
      },
```

I didn't need the arg variable.
Hope it helps if someone see this issue

**Comment by monkpit** [comment]
Not sure why the discussion here changed from setting Chrome User Agent to setting the browser language - but I am still not able to set the User Agent in Protractor config.

I have tried `chromeOptions: { args: ['--user-agent="test"']}` and also `'chrome-switches': ['--user-agent="test"']` - neither have worked.
