### ISSUE TITLE
Not able to use jasmine-expect matchers in protractor 

### ISSUE THREAD

**Issue by kumarvarun1252** [angular/protractor#1396]
Hi,

I am trying to use the jasmine-expect matchers in my protractor e2e tests.

For example, jasmine-expect have a matcher to "expect(string).toEndWith(substring)". I have installed jasmine-expect using "npm install jasmine-expect" but I guess protractor or webdriverjs doesn't understand these matchers.

I see "TypeError: Object #<Object> has no method 'toEndWith'" this error.
It would be really helpful if we can use jasmine-expect matchers for protractor e2e test verifications.

Thanks,
Varun Mukka

**Comment by JamieMason** [comment]
@juliemr @kumarvarun1252 the jasmine-expect side of this issue should be fixed now in 2.0.0-beta1 via issue https://github.com/JamieMason/Jasmine-Matchers/issues/29
