### ISSUE TITLE
how to read text value of a element

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#140]
I am trying to read the text value of binding element. I have used function getText() to read the text value of elements but its not working. Is there any other way to do so

ptor = protractor.getInstance();
    ptor.get('http://www.angularjs.org');

```
ptor.findElement(protractor.By.input("yourName")).sendKeys("Julie");
```

var greeting = ptor.findElement(protractor.By.binding("{{yourName}}!"));

console.log(greeting.getText());

**Comment by QuantumInformation** [comment]
is it ok to use $ instead of ` browser.findElement',`
```js
  it('should return the same result as browser.findElement', function() {
    browser.get('index.html');

   // var e = element(by.id('new_todo'));
    var e = $('#new-todo');
    e.sendKeys("foo");

    expect(e.getAttribute('value')).toEqual(
      "foo")
  });
```
