### ISSUE TITLE
Count Bindings

### ISSUE THREAD

**Issue by cristifilip** [angular/protractor#141]
I'm trying to find somehow the number of binded "cat" rows - How can I do that?

I want to check if there is at least one element on a list (generated with ng-repeat="cat in pets")

ptor.findElements(protractor.By.repeater("cat in pets")).length() doesn't work.

I want to get the number of binded rows and then verify if it is grater than 0. Am I doing it right? Or does protractor has any other instruction to check existence of minimum one element from a list?

**Comment by anjalisingh824** [comment]
@juliemr I am trying to get contents of the first row as 	
element(by.repeater("result in memory").row(0)).getText().then(
						function(text) {

							console.log(text);

						});
but it is showing me the error as: NoSuchElementError: No element found using locator: by.repeater(result in memory").row("0")
Can u pls provide me the solution for asap
