### ISSUE TITLE
Test in-browser only

### ISSUE THREAD

**Issue by richtera** [angular/protractor#1419]
I ported protractor to run locally in the browser so that I can show the same scripts on my test pages and run them remotely. Would anyone be interested in this?

**Comment by NickTomlin** [comment]
We haven't seen any movement on this since 2014 so i'm going to close.

**Comment by richtera** [comment]
Sorry. I had implemented it but it became proprietary for the company I was
working for. I should have closed it a long time ago
Thanks
Andy
