### ISSUE TITLE
Feature Request: to have an option to restart new browser session between each test case/scenario

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#1435]
It is kind of related to https://github.com/angular/protractor/issues/1431.
I searched on stackoverflow.com and there was no good ways to start a new browser session in each test case whether it is cucumber or Jesmine framework.
The only way to ensure each test case is independent from each other is to have a new session in each test case.  When I am used to test with Capybara in Ruby, that is how it works.
I think that protractor should do the same or at very least give an option from commandline to do so.

**Comment by vipper** [comment]
Is there a way to restart the browser for a specific test?

**Comment by monkpit** [comment]
@hankduan I was confused by your link to 1638, so I'm adding a link to the actual solution here:

https://github.com/angular/protractor/commit/167038499aacfd5def03472f9f548529b273e1e0
