### ISSUE TITLE
seo not possible on the protractor website

### ISSUE THREAD

**Issue by jlguenego** [angular/protractor#1445]
It seems that the protractor website is an angularJS app. Unfortunately there is no proper hashbang (#!) allowing google to perform a proper crawl of the website. Therefore it is not referenced.

This article describes the issue.
http://builtvisible.com/javascript-framework-seo/

I would suggest to simply add the ! prefix to the $locationProvider.

**Comment by juliemr** [comment]
This is obsolete, see http://googlewebmastercentral.blogspot.ch/2015/10/deprecating-our-ajax-crawling-scheme.html
