### ISSUE TITLE
Not able to use keyPress

### ISSUE THREAD

**Issue by snehas17-11** [angular/protractor#1446]
I have one flash video site to be automated and when clicked on full screen element , video is displayed in full screen.

I want to go back to normal view with ESCAPE keyboard event,

But it does not working 
browser.actions().keyPress(protractor.Key.ESCAPE).perform();

It throws an error like
TypeError: Object [object Object] has no method 'keyPress'
When I used keyDown 
browser.actions().keyDown(protractor.Key.ESCAPE).perform(); then it gives me another error.
  Error: Not a modifier key

Please Help.

**Comment by Tarlochan** [comment]
Hi,
I am facing the same issue. Has someone solved this.?
I am preparing a generic keyword for my test cases to press escape key whenever require.
The test case pases but the action is never completed.
