### ISSUE TITLE
Strange behavior with browser.get versus clicking on anchor 

### ISSUE THREAD

**Issue by rzajac** [angular/protractor#1458]
I started writing e2e tests for my app and noticed strange behavior. My `beforeEach` at first looked like this:

```
beforeEach(function()
{
  browser.get('/login');
  element(by.model('loginObj.email')).click().clear().sendKeys('testUser1@example.com');
  element(by.model('loginObj.password')).click().clear().sendKeys('testPass1');
  element(by.id('loginSubmit')).click();  // After executing this line my app redirects to /user/profile
  browser.get('/profile/edit/basic'); // Go to profile edit page
});

it('should pass', function()
{
  var status = element(by.model('profBasic.status'));
  expect(status.all(by.tagName('option')).getAttribute('value')).toEqual(['0', '1', '2', '3', '4', '5', '6', '7']);
});
``` 

With this setup all tests were failing with error `No element found using locator`.  Adding `browser.waitForAngular()` after `browser.get('/profile/edit/basic');` did not help. Then I added `browser.sleep(700);` this helped but I don't like to slow my tests so I started to look for other solutions.

After some time and trying things like `browser.driver.get('http://local.dev:8080/profile/edit/basic');` I find out that adding `element(by.id('tbEditProfile')).click();` right after `browser.get` solves the problem.

Now what is the difference between going to the page by URL and clicking on anchor. This should be pretty much the same as far as tests go. Isn't it?

**Comment by juliemr** [comment]
Haven't heard any updates - please submit a new issue if there are still problems.
