### ISSUE TITLE
protractor not finding Angular through Atom-Shell

### ISSUE THREAD

**Issue by jmartine** [angular/protractor#1464]
I'm currently working on a project that is using a automatically bootstrapped Angular application that is being rendered in [Atom-Shell] (https://github.com/atom/atom-shell).

I have been running successful e2e testing using protractor(1.3.1) with chrome with no issues. 

[Webdriver support](https://github.com/atom/atom-shell/blob/master/docs/tutorial/using-selenium-and-webdriver.md) was recently added to the Atom-Shell project.   Using the example provided I was able to use webdriver to start the Atom-Shell and navigate to the web application and run some test.  

Going a bit further I've attempted to configure protractor in the same fashion. 

```coffee
exports.config =
  framework: "jasmine"

  jasmineNodeOpts:
    isVerbose: true

  chromeDriver: '/Downloads/chromedriver'
  browserName: "chrome"
  chromeOptions:
      binary: "/Downloads/Atom.app/Contents/MacOS/Atom"
```

When the tests are ran, the Atom-Shell is launched and the application is loaded correctly.  However protractor will time out with the error:

Error: Angular could not be found on the page http://mywebapp.com/ : angular never provided resumeBootstrap

I was wondering if anyone has tried to do Atom-Shell testing with protractor?   It seems likely that disabling the angular syncing would get me past this but I would like that to be a last option if possible.

**Comment by brandonecraig** [comment]
We found a work around for this problem.

1) Remove the ng-app directive
2) Manually bootstrap using this code:

```
<script>
        angular.element(document).ready(function() {
            if (location.search.indexOf("test=protractor") > -1) {
                window.name = 'NG_DEFER_BOOTSTRAP!' + window.name;
            }
            document.body.setAttribute('ng-app', 'voip');
            angular.bootstrap(document, ['voip']);
        });
    </script>
```

When testing the application, add test=protractor to the web app's query string.

This will allow angular to defer bootstrapping during protractor tests and also let the web app run normally when not testing.

**Comment by NickTomlin** [comment]
Since we have a workaround, and this is an external issue that we cannot do anything about, i'm going to go ahead and close this.

**Comment by evilaliv3** [comment]
This seems to be still actual and be affecting safari 12 and 13;

Do you know if this solution is still valid and could be used in production?
