### ISSUE TITLE
Protractor commands cease to work if there's a short delay during setup

### ISSUE THREAD

**Issue by rluba** [angular/protractor#1466]
If there's a short delay within a `beforeEach` block, Protractor commands (for example `browser.get(...)`)  will cease to have any effect and the test runs into a timeout. (At least when using *mocha*, I haven't tried *jasmine*.)

I've created a small [git repository](https://github.com/rluba/protractor-bug) with a [minimal test](https://github.com/rluba/protractor-bug/blob/master/test/e2e/main.js) that demonstrates the problem.

I've discovered the problem when we tried to call an external API during test setup to create test data.

**Comment by juliemr** [comment]
External issue has been fixed.
