### ISSUE TITLE
ng-repeat with ng-model bindings

### ISSUE THREAD

**Issue by Elexy** [angular/protractor#147]
My markup looks like this:
My markup looks like this:
```
<div ng-repeat = "cat in pets">
   <div contenteditable ng-model="cat.name"></div>
</div>
```
And I tried to test if there is anything in the repeater with this test:
```
cats = ptor.findElements(
      protractor.By.repeater('cat in pets').column('cat.name')
    )
    vats.then (arr) ->
      console.log arr
      expect(arr[0]).toBeDefined() <-- not defined
      expect(arr.length).toBeGreaterThan(0) <-- not defined
```
i tried different values for the binding 'cat', 'name' and '{{ cat.name }}' at no avail.

When I add a regular binding to my markup like {{ project.title }} like in the samples here: https://github.com/angular/protractor/blob/master/spec/findelements_spec.js#L9
I get some results in 'arr'.
It seems to only look for the combination of 'ng-binding' and the exact column() string.

For now the only way I see to test if the repeater is empty is by selecting the first row and testing if that exists.

For anybody interested in the content a the found element: 
```
 { then: [Function: then],
    cancel: [Function: cancel],
    isPending: [Function: isPending],
    errback: [Function: reject],
    driver_: { session_: [Object], executor_: [Object], flow_: [Object] },
    id_: 
     { then: [Function: then],
       cancel: [Function: cancel],
       isPending: [Function: isPending] },
    click: [Function],
    sendKeys: [Function],
    getTagName: [Function],
    getCssValue: [Function],
    getAttribute: [Function],
    getText: [Function],
    getSize: [Function],
    getLocation: [Function],
    isEnabled: [Function],
    isSelected: [Function],
    submit: [Function],
    clear: [Function],
    isDisplayed: [Function],
    getOuterHtml: [Function],
    getInnerHtml: [Function],
    findElement: [Function],
    findElements: [Function],
    isElementPresent: [Function],
    evaluate: [Function] }
```
This leaves me with the problem of determining whether a row was added when 'addRow' was clicked

**Comment by juliemr** [comment]
I think this is all possible to do with `element.all` and filtering now. Closing.

**Comment by reddynr** [comment]
HI All,

I have issue to validate the value using protractor. Please advice highly appreciated. Thanks

Failed: No element found using locator: by.model("ctrl.formData.branchAddressLine1")

code:

element(by.model('ctrl.formData.branchAddressLine1')).getAttribute('value').then(function (value) {
         expect(value).toEqual('Plaza Scotiabank');
         })
