### ISSUE TITLE
Expose currently running suite name, e.g. `protractor.currentSuite`

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#1508]
Useful to know the currently running suite name if any, should be `undefined` if none.
Should work not only when CLI param `--suite` is provided but when omitted too as long as there is a `suites` config.
Should also work when multiple suites are specified to the CLI, e.g. `--suite=smoke,fast,full`

Use case for me is a plugin I'm working on, also for CI integrations.

**Comment by juliemr** [comment]
Can you clarify what behavior you'd like when there's no `--suite` parameter? Would it then be all the suites specified in the config?

**Comment by elgalu** [comment]
I was thinking that `protractor.currentSuite` should have only 1 value at a current time, depending of which test is running, if that test/spec file belongs to a suite then set `protractor.currentSuite` to the suite name else `undefined`.
When `--suite` parameter is set to 1 value `protractor.currentSuite` is easy, simple assigns to argv.suite.
When `--suite` is set to multiple values or omitted then it gets trickier because the current value of `protractor.currentSuite` depends on pattern matching the current test file name with the suites listed in the configuration.

Perhaps I'm wishing suites to be a first class citizen, meaning we attach more info to it, for example to do other things like providing a summary of test results at suite level:

```sh
  Summary of run suites:
    ch_camp_enUS - ✔
    ch_packages_enUS - ✔
    ch_paste_enUS - ✔
    ch_smoke_enUS - ✔
    ch_loginvalid_enUS - ✔
    ie10_camp_enUS - skipped
    ie10_packages_enUS - ✔
    ie10_paste_enUS - skipped
    ie10_smoke_enUS - FAILED!
```

**Comment by hhaamm** [comment]
@juliemr Please note that I'm currently working on a PR for this issue. Just saying to avoid duplicating effort :)

**Comment by hankduan** [comment]
Can you elaborate on your use case? Do you just need to know from the runner, or do your tests need to know this information?

If you're trying to map each file name and `config.suite` against `config.suites`, there is some complexity in that jasmine runner does not run each file separately, but globbed together. This means protractor cannot determine which file is currently being run. (Of course, we can manually invoke jasmine multiple times to get the files to run separately, but before doing that, if you can explain your use case, it'd be great).

**Comment by elgalu** [comment]
> Do you just need to know from the runner, or do your tests need to know this information?

My tests also need to know

> This means protractor cannot determine which file is currently being run

I see now this is a particular Jasmine limitation and precisely why determining the current suite or current spec #587 file name implies an architectural change width the added complexity that may change with Jasmine 2.0.

> can explain your use case, it'd be great

This got me thinking that I'm actually trying to use the `--suite` feature as a tagging [mhevery/jasmine-node/issues/343](https://github.com/mhevery/jasmine-node/issues/343) feature, something I miss from my days with [cucumber tags](https://github.com/cucumber/cucumber/wiki/Tags)

**Comment by hankduan** [comment]
Jasmine2 is available for use on protractor now. However, it will not address this either. In particular, Jasmine does a simple `require` on every file in the glob, which loads all the `describe`/`it`. It does not keep track of which test comes from which file.

**Comment by lmr3796** [comment]
In my case I would need this feature, too.
We want to specify different testing accounts for different suites on the product, and I want specify them in config files.

**Comment by hhaamm** [comment]
@lmr3796 Can you process an initial config file inside each suite (first file of the suite)? You could set up there your testing accounts.

**Comment by lmr3796** [comment]
@hhaamm I think that's a good idea, too.
I'll try it. Thanks a lot!

Although I still want to have this feature...

**Comment by FagnerMartinsBrack** [comment]
@hankduan @juliemr 

I will explain my use case using Grunt that probably justifies this feature:

There are several suites being run, but one of them `orange` depends upon a specific configuration file `orange.config.json` that is different from `apple.config.json`. If I run `grunt run-tests --suite=apple` or `grunt run-tests --suite=orange`, then I can retrieve the information of the current suite being run from the arguments of the command-line, and therefore load the correct configuration, but when I run protractor without specifying a suite it is impossible to know which config file to load, because the current suite is not exposed.

By making protractor to expose the current suite, it is possible that I create a routine that copies the correct `*.config.json` before each suite is run in order to satisfy the desired dependency, then I wouldn't rely in the command-line anymore and all tests would work just with a `grunt run-tests` command.

**Comment by g2graman** [comment]
Can't this be accomplished by putting `console.log(require('yargs').argv.suite);` into `protractor.conf.js` ?

**Comment by juliemr** [comment]
I think because this is a framework issue with Jasmine, and as @g2graman mentions you can easily store or get the suite param you passed in, there's nothing actionable for us here.

**Comment by muzamilabbasi** [comment]
@FagnerMartinsBrack did you figured out a solution for it?

**Comment by muzamilabbasi** [comment]
@g2graman  that was useful
