### ISSUE TITLE
Protractor: Button click fails on IE 11 but works fine on Chrome and FireFox

### ISSUE THREAD

**Issue by SwarupD** [angular/protractor#1522]
Hello Everyone,

I am 4 weeks into Protractor and writing tests on an Angular JS application. It's a login page with text box for username and password and a button which is disabled until values are entered into the text boxes.

The html part of button is :

<div class="btn-group clear">
    <button type="submit" ng-disabled="LoginForm.username.$pristine  || LoginForm.password.$pristine || (!LoginForm.username.$pristine && LoginForm.username.$invalid) || (!LoginForm.password.$pristine && LoginForm.password.$invalid)" class="btn btn-default">Login</button>
</div>

The code to identify the button is :

var logInButton = element(by.css('[class="btn btn-default"]'));
logInButton.click();

My issue here is, this button click works perfectly fine on Chrome and FireFox, latest version. But fails on IE 11.

I have tried different ways by taking id, cssContainingText but nothing is working on IE.

Need some help here, please.

Thanks,
Swarup

**Comment by sssalib42** [comment]
I'm facing the same issue. https://github.com/angular/protractor/issues/2244. The links offered above didn't provide an answer.
