### ISSUE TITLE
Inbuilt Protractor Drag and Drop function failing to drag one element to another element

### ISSUE THREAD

**Issue by Cle-13** [angular/protractor#1525]
I'm writing a test where I need to simulate a drag and drop of one element onto another but the dragging and dropping is not happening. I'm using Protractor 1.4 and chromedriver for my tests. Here's how I wrote the test:

```
var x = element(by.cssContainingText('span.data-dimension--text','1.05 Employment-to-population ratio'));
var targetX = element(by.css('div.chart-dimension-drop-target.chart-dimension-x'));
browser.actions().dragAndDrop(x, targetX).perform();
```

**Comment by EvanBurbidge** [comment]
Hi @sjelin  Was the selenium issue ever sorted for drag and drop i've been trying the past few hours to get something working but so far no luck.

**Comment by sjelin** [comment]
I would guess that it wasn't tbh

**Comment by tyaga001** [comment]
Hi Guys, Is there any update on drag&drop event in protractor of HTML5 elements. we are facing similar issue in chrome, unable to drag&drop in protractor.

**Comment by sachinndt** [comment]
Hey Guys,

Do anyone have update on drag&drop event in protractor
