### ISSUE TITLE
Element is not clickable at point (1254, 21). Other element would receive the click: in protractor, Testing Angularjs UI with selenium server

### ISSUE THREAD

**Issue by rajit-daffodil** [angular/protractor#1530]
I am using protractor and selenium server with angularjs for UI testing,

This is my TestCase

it('Click on Top Headings one by one', function () {  
         //click on Top Heading one by one
        ptor.element.all(by.repeater('application in workbenchOptions.applications')).then(function (arrs) {
            ptor.sleep(3000);
            arrs[2].click()
            ptor.sleep(3000);
            arrs[3].click()
            ptor.sleep(3000);
            arrs[1].click()
            ptor.sleep(3000);
            arrs[2].click()
            ptor.sleep(3000);
            arrs[0].click()
            ptor.sleep(2000);
        });
    })
everything is clicking , but if in the begining suppose arrs[0] is already open then I am not able to click on this again and I got a error message

UnknownError: unknown error: Element is not clickable at point (1254, 21). Other element would receive the click: ...

I have use both chrome and Firefox and same error occurs

I have also use ptor.actions().mouseMove(arrs[0]).click().perform()  , but this also does not working
![screenshot from 2014-11-15 10 20 23](https://cloud.githubusercontent.com/assets/7080384/5056941/622c4656-6cc8-11e4-84d5-ae714ba25ad2.png)
![screenshot from 2014-11-15 10 42 28](https://cloud.githubusercontent.com/assets/7080384/5056942/696306bc-6cc8-11e4-8196-444c3bc2accb.png)
![screenshot from 2014-11-15 10 42 35](https://cloud.githubusercontent.com/assets/7080384/5056943/6cb2c500-6cc8-11e4-8785-d6b0068f0a52.png)

**Comment by vlikin** [comment]
I've got a such problem as. The problem is that the button changes its location. When you try click at the second time. The driver click on the old place. It does not call event. It emulates the mouse click. I use IONIC navigation bar. It uses translate3d. It shifts the main area. If I move back it. The button test becomes work again.

**Comment by rajit-daffodil** [comment]
Thank you, you are right

**Comment by DedrickEnc** [comment]
```
var elem = element(by.id('yourId'));
browser.actions().mouseMove(elem).click();
```

**Comment by dinukacgx** [comment]
I tried with @DedrickEnc solution. It's also worked fine for me.

**Comment by kalexmills** [comment]
@DedrickEnc's solution works for me sometimes. Other times it results in the above error. :confused:
