### ISSUE TITLE
Protractor CLI provides mechanism for parameterizing baseUrl

### ISSUE THREAD

**Issue by aeisenberg** [angular/protractor#1531]
I need to run protractor with different `baseUrl`s depending on context (eg- snapshot builds vs production builds).  Currently, the only way to change `baseUrl` is by directly accessing node's `process.argv`. It is not possible to use `--params` since the `baseUrl` must be set before the params have been initialized.

My suggestion is to provide a new CLI parameter (-eg `--baseUrl`) where you can set the baseUrl while calling protractor.

For more context, please see this stackoverflow question: http://stackoverflow.com/questions/26951009/how-do-i-parameterize-the-baseurl-property-of-the-protractor-config-file

**Comment by shanlashari** [comment]
Please can anyone update on this issue, why its closed without any comments

**Comment by aeisenberg** [comment]
This was a documentation issue. I'm not sure if the documentation was ever updated to reflect these command line parameters, but see the stackoverflow link for how to do this.
