### ISSUE TITLE
Unable to run test on IE(9) browser , when latest protractor version and IE9 version is in place.

### ISSUE THREAD

**Issue by malviya84** [angular/protractor#1536]
Hi Team,

I downloaded the latest protractor version and trying to run test on IE9 version ,but getting following exception.
1. Conf.js
   // An example configuration file.
   exports.config = {
   directConnect: true,
   
   // Capabilities to be passed to the webdriver instance.
   capabilities: {
     'browserName': 'internet explorer'
   },
   
   // Spec patterns are relative to the current working directly when
   // protractor is called.
   specs: ['example_spec.js'],
   
   // Options to be passed to Jasmine-node.
   jasmineNodeOpts: {
     showColors: true,
     defaultTimeoutInterval: 30000
   }
   };
   ---
   
   2.example_spec.js
   describe('angularjs homepage', function() {
   it('should greet the named user', function() {
     browser.get('http://www.angularjs.org');
   
     element(by.model('yourName')).sendKeys('Julie');
   
     var greeting = element(by.binding('yourName'));
   
     expect(greeting.getText()).toEqual('Hello Julie!');
   });
   
   describe('todo list', function() {
     var todoList;
   
     beforeEach(function() {
       browser.get('http://www.angularjs.org');
   
   ```
   todoList = element.all(by.repeater('todo in todos'));
   ```
   
     });
   
     it('should list todos', function() {
       expect(todoList.count()).toEqual(2);
       expect(todoList.get(1).getText()).toEqual('build an angular app');
     });
   
     it('should add a todo', function() {
       var addTodo = element(by.model('todoText'));
       var addButton = element(by.css('[value="add"]'));
   
   ```
   addTodo.sendKeys('write a protractor test');
   addButton.click();
   
   expect(todoList.count()).toEqual(3);
   expect(todoList.get(2).getText()).toEqual('write a protractor test');
   ```
   
     });
   });
   });

---

Exception : 
C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protractor\example>protra
ctor conf.js

C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protractor\node_modules\q
\q.js:126
                    throw e;
                          ^
Error: browserName (internet explorer) is not supported with directConnect.
    at DirectDriverProvider.setupEnv (C:\Users\amit malviya\AppData\Roaming\npm\
node_modules\protractor\lib\driverProviders\direct.js:34:13)
    at Runner.run (C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protra
ctor\lib\runner.js:215:31)
    at C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protractor\lib\lau
ncher.js:163:14
    at _fulfilled (C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protra
ctor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (C:\Users\amit malviya\AppData\Roaming\npm\node
_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (C:\Users\amit malviya\AppData\Roaming\np
m\node_modules\protractor\node_modules\q\q.js:759:13)
    at C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protractor\node_mo
dules\q\q.js:820:14
    at flush (C:\Users\amit malviya\AppData\Roaming\npm\node_modules\protractor\
node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)

can you please help me to understand this issue and resolve it.

Thanks
Amit

**Comment by nishankkumar1994** [comment]
Please make sure to install
`npm install protractor`

Update web driver manager
`webdriver-manager update`

Run this command from your root
`node node_modules\protractor\bin\webdriver-manager update`

Now start up a server with:
`webdriver-manager start`

Also make sure that your protractor.conf.js file has below line
`// baseUrl: 'http://localhost:4200/',`
 ` seleniumAddress: 'http://localhost:4444/wd/hub/',`


Now run your e2e tests on different browesers
`ng e2e`
