### ISSUE TITLE
RUNNER SHOULD (OPTIONALLY) KEEP SELENIUM OPEN

### ISSUE THREAD

**Issue by jeffbcross** [angular/protractor#155]
It would be nice for the Protractor runner to start my selenium server, run my tests, and keep the selenium server open to run my tests again later without having to start up the selenium server, since it takes soooo long to start.

This is achievable right now by starting the selenium server myself, setting the address of the server in protractorConf, and then running Protractor. But it's 2013 and I want everything to happen in one command!

As discussed IRL with @juliemr, here is one way this feature could be implemented:
- An option in protractorConf that says keepSeleniumOpen (or something better)
- Hit enter in the shell of the running protractor process to run tests again

**Comment by twler** [comment]
@jeffbcross can you elaborate on why webdriver manager solves this?  I'd also like to keep the browser open between runs.
