### ISSUE TITLE
How to handle authentication pop up on protractor

### ISSUE THREAD

**Issue by andrepm06** [angular/protractor#1554]
I'm writing a few tests in protractor (in a non-angularJS application) and I found an authentication pop up/alert window. Now, I'm stuck and I can't continue to write my tests. Is there a way where I can handle this pop up alert, like input data or work with asserts?

Specifically in this test, I'm trying to log in a restricted page, which I have no clue of how I will handle it.

I'm thinking something like:

browser.driver.switchTo().alert().sendKeys(user:pw);
browser.driver.switchTo().alert().click(OkBtn);

Additionally, i've already tried browser.driver.get('https://username:password@url'); but apparently it didn't worked.

**Comment by arbaz22** [comment]
Hi 
  In my project am facing one issue am not able to inspect one browser popup which is not inspectable and i have tried handling using multiple methods like using window handlers or using auto-select-desktop-capture-source="Entire screen" nothing seems to be working.Please let me know the solution for this problem

Thanks,
Arbaz
