### ISSUE TITLE
Shadow DOM support

### ISSUE THREAD

**Issue by amitit** [angular/protractor#1566]
Is there any way to access a shadow DOM?

In paper-elements 0.5.1 `paper-action-dialog` is being transferred to a shadow before being opened. Any attempt to access an element under the shadow gets the following error:

```
StaleElementReferenceError: stale element reference: element is not attached to the page document
```

For the following attempt:

```
        $('overlay-host::shadow paper-action-dialog').then(function (element) {
            console.log('just trying to access', element.getAttribute('opened'));
        })
```

Thanks

**Comment by alecxe** [comment]
Isn't it fixed in 1.7.0? (https://github.com/angular/protractor/commit/d220ecf5ebc7ba023eab728d4a684e978ff77c83)?

**Comment by juliemr** [comment]
Yes! Closing. Thanks for noticing.

**Comment by amitit** [comment]
This is great, thank you!
