### ISSUE TITLE
sendKeys example uses webdriver.Key instead of protractor.Key

### ISSUE THREAD

**Issue by plynchnlm** [angular/protractor#1567]
On the [sendKeys API page](http://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.sendKeys), the example reads " element.sendKeys("text was", webdriver.Key.CONTROL, ...."   When I tried something like that, I got an error that webdriver was not defined.  It took me a while before I found that I could use protractor.Key.CONTROL instead.

**Comment by sjelin** [comment]
@juliemr Which approach would you prefer?  The (probably imperfect) regex or the (potentially breaking) `webdriver`?

**Comment by sjelin** [comment]
@juliemr If you don't express a preference by EOD I'm just gonna go with the regex :stuck_out_tongue:

**Comment by sjelin** [comment]
In the end I decided to just put a disclaimer at the top of each page which uses webdriver syntax.  Automatically converting the syntax from webdriver to protractor wasn't going to work.

**Comment by andresdominguez** [comment]
See #2169
