### ISSUE TITLE
Support directConnect PhantomJS through GhostDriver

### ISSUE THREAD

**Issue by jonhoo** [angular/protractor#1585]
Given that PhantomJS has built-in support ([GhostDriver](https://github.com/detro/ghostdriver)) for WebDriver, might it be possible to add `directConnect` support for it? It would certainly be very convenient to be able to run headless tests without spawning Selenium separately...

**Comment by juliemr** [comment]
This would be a feature of WebDriverJS, so I'm going to close the issue here.
