### ISSUE TITLE
sendKeys to TEXTAREA loses '/' and reverts string chunks

### ISSUE THREAD

**Issue by mickeyvip** [angular/protractor#1586]
Running Protractor 1.4.0 on Ubuntu 14, Chrome 37 (Jenkins job).

When I send URL into `<textarea></textarea>` it seems like every 1st forward slash `/` encountered is causing the cursor to jump to the beginning of the line:

```javascript
myElement.sendKeys("http://google.com");
myElement.getAttribute("value").then(function(val) {
  console.log(val);
});
```

I see in log:

```bash
 $ /google.comhttp:
```

I tried to `sendKeys` one by one while replacing the '/' with `protractor.Key.DIVIDE`:

```bash
$ http:google.com
```

It does not occur on `<input type="text"/>`, only on `<textarea></textarea>`.

Thank you.

##### Update 1

It is working correctly in Firefox (v31)

**Comment by NickTomlin** [comment]
I'm going to close this as it It looks like this was fixed in Chromedriver `2.16`, and protractor is on `2.20`.

Please feel free to reopen if this is still an issue.

**Comment by DajMiNazwe** [comment]
This issue still exists on chromedriver `2.32`.

**Comment by chrismwendt** [comment]
The bug also exists on chromedriver `2.26` on Mac Sierra `10.12.6` on Chrome `61.0.3163.100`.
