### ISSUE TITLE
Protractor Failed to run after new Enterprise Policies push to the computer "loading of unpacked extensions is disabled by the administrator"

### ISSUE THREAD

**Issue by acostaf** [angular/protractor#1589]
I got this  this nice error with the new policies "loading of unpacked extensions is disabled by the administrator"
![untitled](https://cloud.githubusercontent.com/assets/1760318/5281723/31b21b66-7af8-11e4-946c-9d731d53ae90.png)

**Comment by zsong** [comment]
seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['disable-extensions', 'disable-plugins']
        }
    },

I got same exact error. Here is my config.

**Comment by VishwaKumar** [comment]
I got the same issue today "Error loading Extension" and this is my config

`exports.config = {
    directConnect: true,

    // Capabilities to be passed to the webdriver instance.
    capabilities: {
        'browserName': 'chrome'
    },

    // Framework to use. Jasmine is recommended.
    framework: 'jasmine',

    // Spec patterns are relative to the current working directory when
    // protractor is called.
    specs: [
        '../ui.apps/src/test/e2e/control-flow-delay.js',

        '../app/src/test/e2e/mypage.test.js',
    ],

    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        defaultTimeoutInterval: 1000000
    },

    allScriptsTimeout: 120000,

    onPrepare: function() {
        setTimeout(function() {
            browser.driver.executeScript(function() {
                return {
                    width: window.screen.availWidth,
                    height: window.screen.availHeight
                };
            }).then(function(result) {
                browser.driver.manage().window().setSize(result.width, result.height);
            });
        });
    },
};
`

When i ran protractor, the error was coming and chrome browser would open and be idle with "No Secure data" in the address bar.

But strangely i found out that , once i commented the lines of code in the onPrepare function, the error "Error loading Extension" still came but the chrome browser ran normally and all my test cases got executed successfully. I am new to node and protractor so i couldn't debug why commenting those lines of code ran my test-cases normally.
