### ISSUE TITLE
How to similulate mouse over events such as click a link on mouse over

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#159]
I have a main menu. If i click on main menu it opens sub menu on mouse over. This sub menu us hidden element. Protractor is clicking on the main menu but not cant simulate the action on mouse over event

Tried below four ways to simulate mouse hover action
1.  driver.executeScript("document.getElementById('dBysuspect typeLabel')[0].mouseover();");
2.  driver.executeScript("return ptor.By.id('dBysuspect typeLabel').hover();");
3.  reviewProviderPage.reviewProvidersBySuspect.hover();
4.  driver.executeScript("reviewProviderPage.reviewProvidersBySuspect.hover():");

Got below error.
Message:
     Type Error: Object [object Object] has no method 'hover'

**Comment by abhagupta** [comment]
@aricearice - Were you able to find out the solution for your problem. I have stumbled upon same issue in Safari.

**Comment by bmsoko** [comment]
Same here, I've stepped on this issue too... Did anyone find a workaround?

Thanks

**Comment by daluu** [comment]
For Safari issue, see also #1526. As mentioned by @aricearice, comments 57 & 60 in the referenced Selenium issue on Google Code should have the workaround.

Basically, the workaround is to execute JS code in the browser to simulate mouse events (rather than use native events which SafariDriver does not yet support). Javascript based mouse over or hover, something you can search online about to get a better understanding of it (as well as more code samples), if comments 57 & 60 are not easy to decipher.

Also, if one needs javascript based drag & drop, see #1526, where I mention another reference to JS code snippet for that.

Also, if one wants mouse click instead of hover or drag & drop, can do that too. I have a blog post about all these JS simulations here:

https://autumnator.wordpress.com/2013/02/09/javascript-is-your-ally-for-selenium-webdriver/

**Comment by csanthoshi** [comment]
I am unable to hover over an element( hyper link). I observed that when I placed my physical mouse pointer on the browser( launched through automation ) the element did not hovered but once I moved the  physical pointer outside of the browser as soon as run gets triggered, the hovering action is passing successfully. I am running the script in chrome browser using protractor

The code snippet that I used is 

browser.sleep( 8000 );
var ele = element( by.xpath( '//tf-infobox//*[normalize-space(.)="Error 1"]/following-sibling::*//a' ) );
browser.actions().mouseMove( ele ).perform();
browser.sleep( 5000 );

**Additional Info:** I can able to click the element but hovering is not possible.
Chrome-driver version: 2.21

Can someone help me out to solve my problem.

Thanks!

**Comment by latobibor** [comment]
A thing to note if you are using `actions.mouseMove`: if your existing, hardware mouse is in the browser area, it won't do anything. This sucks because you can't guarantee on test machines that no-one will leave the mouse over the territory where your tests are running.

**Comment by latobibor** [comment]
I second @csanthoshi . Is there a way to fire it only from script without the interference of the physical mouse?

**Comment by amod-thakur** [comment]
I sort of discovered a workaround to the mouse hover issue on chrome by accident. If we chain the mouseMove() method twice , it works.

**Code that doesn't work on chrome:**
`browser.actions.mouseMove(element).click().perform();`

**Code with workaround(which works)**
`browser.actions.mouseMove(element).nouseMove(element).click().perform();`

**Comment by vijayjdk** [comment]
> You'll need to use an _action sequence_ for hovering:
> 
> ```js
> ptor.actions().
>     mouseMove(ptor.findElement(protractor.B.id('foo'))).
>     perform();
> ```
> 
> See https://code.google.com/p/selenium/source/browse/javascript/webdriver/actionsequence.js for the full actions API.

Hi @juliemr 
Above code is working fine in chrome. But i need to run my script for firefox and this code is failing in firefox browser. Below is the error i am facing while executing same code on firefox 

**

> UnknownCommandError: POST /session/24e1787f-7623-4690-b9a9-92ba32c552e1/moveto did not match a known command

**
Please help me to solve this issue

**Comment by viniciusrad** [comment]
almost 10 years later I ran into the same situation.
And I ended up creating a very simple solution

A function at (mouseenter)="myFunc($event)" in element
 and then

   myFunc(event: any){
    event.target.click()
  }

Done, no pain
