### ISSUE TITLE
Unable to update/change 'auth' value in protractor/lib/driverProviders/sauce.js

### ISSUE THREAD

**Issue by jtalon21** [angular/protractor#1595]
The company I work for uses Sauce Labs for their testing. We have a large number of Angular applications in development that would like to use Protractor for their functional testing. Our Sauce Connect tunnel is located on a central server so everyone can access it. The issue I'm having is that the address for the  Sauce Connect server within our network is "https://saucelabs.company:443/wd/hub". If I look in the code (below), I dont see anyway to update the auth variable to use "https". It looks to be hard coded to use only "http". It would be nice to be able to pass in the protocol as "sauceSeleniumAddress" option so it's possible to use either.

  this.config_.capabilities.accessKey = this.config_.sauceKey;
63	  var auth = 'http://' + this.config_.sauceUser + ':' +
…	
63	  var auth = 'http://' + this.config_.sauceUser + ':' +
64	    this.config_.sauceKey + '@';
65	  this.config_.seleniumAddress = auth +
66	      (this.config_.sauceSeleniumAddress ? this.config_.sauceSeleniumAddress :

**Comment by juliemr** [comment]
Closing stale issues - for the record, you can always add additional capabilities in the `capabilities` object.
