### ISSUE TITLE
how to close browser after execution of all testcase or after fail of testcase

### ISSUE THREAD

**Issue by rajit-daffodil** [angular/protractor#1609]
Hi,

I am able to run testcases with protractor using selenium server with angularjs

I want to close my browser after execution of all testcase or after fail of testcase,

I am able to do this by writing 

browser.close() in the last testcase, but this will not work if testcase fails , is there any other way to close the browser in this case also, or is there any different name for after like afterEach

Thanks in advance..

**Comment by Saurabh06** [comment]
@rajit-daffodil , Can you help me how to use with my script using jasmine 2 framework https://github.com/nonplus/jasmine-beforeAll
