### ISSUE TITLE
Browser basic authentication - unable to sign in 

### ISSUE THREAD

**Issue by Nickproger** [angular/protractor#1611]
![error-protructor](https://cloud.githubusercontent.com/assets/1409078/5357049/b11de9ea-7fab-11e4-982b-9d3dbe985a91.jpg)
Hello. How to implement it in Chrome? 
we've tried the approach - http://stackoverflow.com/questions/27234785/how-to-handle-basic-authentication-with-protractor

```
baseUrl: 'https://username:password@url' 
```

and

```
 capabilities: {
        'browserName': 'chrome',
        'chromeOptions' : {
            args: ['--login-user=foo', '--login-password=bar']
        }
}
```

**Comment by aniruddhadas9** [comment]
I am facing the same issue and I tried all possible way I found everywhere. I am trying to test my application in sauce lab and what I give it still popping up for username and password.
I understand there is a way chrome provides but unable to handle that in sauce lab account.

is there a way to input username and password using protractor?

**Comment by aniruddhadas9** [comment]
More over if you have a domain name to add before your username it more problematic  to input.
