### ISSUE TITLE
Adding Protractor to Yeoman generator-angular

### ISSUE THREAD

**Issue by johnjelinek** [angular/protractor#163]
Not sure where to submit this questions: Can we please have this added to the generator? I've done it manually, and it was really time-consuming.

**Comment by dKab** [comment]
Please, add it already. I've tried to install and config protractror on top of Yeoman-generated angular app by myself and apparently broke something. Please, please.

**Comment by radiart** [comment]
Any progress on that? :)

**Comment by BrodaNoel** [comment]
Any progress?

**Comment by zhekaus** [comment]
It's nonsense not to include protractor.
