### ISSUE TITLE
Provide error if locator is not supported by Selenium Server

### ISSUE THREAD

**Issue by mitchhentges** [angular/protractor#1632]
See the [issue posted on the Selendroid issue tracker](https://github.com/selendroid/selendroid/issues/748).

I'm running my tests for a hybrid app on an Android tablet. After properly configuring the server's capabilities, I kept running into a `StaleElementReferenceException`. It turns out that this is because `by.model` doesn't work with Selendroid.

An error should be provided if a locator is not supported.

**To reproduce:**
1. Have a hybrid Android app that uses Angular
2. Set up configuration 
```
seleniumAddress: 'http://localhost:4444/wd/hub',
capabilities: {
    browserName: 'ANDROID',
    targetPlatform: {androidVersion}, //like 'ANDROID19'
    aut: {applicationId}
},

onPrepare: function() {
    var wd = require('wd'),
        protractor = require('protractor'),
        wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);
    wdBrowser.context('WEBVIEW');
},
```
3. As part of the test, locate an element `by.model(...)` and then attempt to do `sendKeys(...)`.

**Comment by juliemr** [comment]
I think I'm going to close this issue since the original premise isn't something we need to address. However, deciding on better mobile support is definitely on our todos. We've started to clarify the docs, and better support will be coming soon.
