### ISSUE TITLE
Tests on chrome doesn't work when an instance is already open

### ISSUE THREAD

**Issue by kaahxd** [angular/protractor#1636]
I'm testing protractor features and when I have an instance of chrome open, for example, I'm searching something on google and working with protractor tests and I wanna run the tests on chrome the google chrome opens a new tab with "data:," on address bar and the tests doesn't work. follow the log:

[chrome #2] PID: 6868
[chrome #2] Specs: C:\...\default_spec.js
[chrome #2] 
[chrome #2] Using the selenium server at http://localhost:4444/wd/hub
[chrome #2] ERROR - Unable to start a WebDriver session.
[chrome #2] 
[chrome #2] C:\...\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113
[chrome #2]   var template = new Error(this.message);
[chrome #2]                  ^

**Comment by juliemr** [comment]
Haven't heard anything in several weeks, closing as obsolete.
