### ISSUE TITLE
Is there a way to run a single test from the command line?

### ISSUE THREAD

**Issue by gsastry** [angular/protractor#164]
I'd like to pass in a single test name to run from the command line. Is this possible? (new to jasmine/protractor, any help would be appreciated)

**Comment by F1LT3R** [comment]
So... now that it is supported in Jasmine 2.0: how is this done with Protractor?

**Comment by mmigdol** [comment]
For anyone looking to do this in Jasmine 2.0+, use ddescribe or iit to isolate a single describe() or it() function.  I couldn't find this documented anywhere, but discovered it via [this StackOverflow question](http://stackoverflow.com/questions/24536572/how-to-run-a-single-specific-test-case-when-using-protractor)

**Comment by Bretto** [comment]
For Karma now you have to use fdescribe or fit ('f' is for focus). How ever in the protractor context nothing is working...

**Comment by rohitkadam19** [comment]
Without fit and xit how can we run single test in protractor?

**Comment by cancerberoSgx** [comment]
Don't know from the command line, but you can do it using the API like this
```
var jasmine = new Jasmine();
jasmine.specFiles = ['/home/sg/myproject/foo/bar/someSpec.js'];
jasmine.execute();
```

**Comment by sumittech17** [comment]
Hi All, @juliemr 

Is it possible to run a single test or group of tests (not complete file)  in protactor from command line ?

I tried using --grep option , but it is not working . 

Note : Using  framework: 'jasmine2'

**Comment by Xotabu4** [comment]
@sumittech17 
Hi, i don't know if that would help - i mark tests that i want to run in a file with - fdescribe or fit  - this skips all tests except marked, then you could run your protractor with  --specs mydir/mytestfile.js 
It works for me, but makes you keep eye on to not commit fit or fdescribe to repo.

**Comment by sumittech17** [comment]
@Xotabu4 
this is working for me now .
protractor --specs='tests/e2e/login.js' --grep="SingleLoginTest"


However I am not able to add GREP option in gruntfile now .

**Comment by jasminejeane** [comment]
@Xotabu4 Thank you so much ... that worked for me !!!!

**Comment by sakovias** [comment]
In my test suite I have nested `describe`s some of which have `afterAll` or `beforeAll` hooks. I'm noticing that in `--grep` mode I have `beforeAll` and `afterAll` hooks from unrelated tests being executed. This is not the case with `mocha`. Anyone else finding this inconvenient?

**Comment by andyman09** [comment]
Hi @sakovias, I am having the same issue on with using --grep. Did you happen to find any solution to skip beforeAll for spec that does not match the grep value?

**Comment by vickyru** [comment]
This is what working for me, if i want to run a particular 'it' block from a particular suit

protractor protractor.conf.js --suite test-suite-name --grep="it-block-name"

**Comment by juanbrein** [comment]
You can do all that, but I found way more convenient to have a wrapper script that basically inject the files I want to test on the protractor.config.ts. Then I write one test per file and use a common sense naming convention like:

user/create-article.e2e.ts
user/update-article.e2e.ts
user/delete-article.e2e.ts

So now I can run things like

./run-e2e.sh user/create

Sometimes is easier to build things yourself ...

**Comment by vickyru** [comment]
> You can do all that, but I found way more convenient to have a wrapper script that basically inject the files I want to test on the protractor.config.ts. Then I write one test per file and use a common sense naming convention like:
> 
> user/create-article.e2e.ts
> user/update-article.e2e.ts
> user/delete-article.e2e.ts
> 
> So now I can run things like
> 
> ./run-e2e.sh user/create
> 
> Sometimes is easier to build things yourself ...

For sure it will work I didn't think it is good way to achieve it as if one have to change any config.js property he/she have to in all three places. More configuration file more will be the fragility.
