### ISSUE TITLE
WaitForAngular does not wait for $routeChangeSuccess event

### ISSUE THREAD

**Issue by 0xR** [angular/protractor#1641]
Scenario:
Click on an element
A route is loaded using $location
The $routeChangeSuccess event is fired
Its eventhandler loads the contents of the page using an $http call

Protractor code:
element(...).click()
element(...).first().getText()

Error:
Index out of bound. Trying to access element at index:0, but there are only 0 elements

Expected outcome:
No error, but a future containing the text of the elemement

If my expectation is correct and this is not a known bug I can provide a code example.

I debugged this using notifyWhenNoOutstandingRequests to log on the console when angular was ready. And other console.log calls when the $http call was made and finished.

My output looks like this:
Angular ready
Starting $http call
Call finished

The expected output is:
Starting $http call
Call finished
Angular ready

I am running protractor 1.4.0 and I'm currently refactoring my code to upgrade to 1.5. I might have similar issues where the view loaded by ng-route only contains ng-if logic. Protractor is supposed to also wait for this I suppose. I am currently investigating this further, to determine if protractor is also not waiting for this logic.

**Comment by SquadraCorse** [comment]
Maybe also nice to document that ID selector doesn't work. Then you get injector errors.

My html container was:
<div id="tif-wishlist-example" class="tif-wishlist-example">
And inside there was ui-view using ui-router. Now all my tests normally have ID selector and was fine. Now it didn't but stack trace was not giving a lot of information.

rootElement: '.tif-wishlist-example' >> was ok
rootElement: '#tif-wishlist-example' >> gave injection errors

**Comment by mgiambalvo** [comment]
Still seems to be an issue, being tracked in #2954

**Comment by mgiambalvo** [comment]
Actually, doesn't seem like this is a problem anymore. I mapped out all the $apply and $digest cycles around route changes, and even with slowly loading templates protractor consistently does the right thing.

Note that given app is not a valid test - it waits for outstanding requests synchronously, but protractor does all of its waiting asynchronously in webdriver callbacks. However, there is a PR for angular that fixes this issue.

**Comment by 0xR** [comment]
I disagree that the given app is not a valid test. The main feature of protractor is that you can write your test synchronously and protractor will wait for angular. Or do you mean something else @mgiambalvo?

**Comment by juliemr** [comment]
@0xR The thing about that app is that it's using testability directly, not via Protractor. When Protractor calls `whenStable` it will be executing the code via WebDriver's `executeScript` command, which *always* runs asynchronously.
