### ISSUE TITLE
Remove timeout for single jasmine spec

### ISSUE THREAD

**Issue by cakesmith** [angular/protractor#1642]
Is there a way (or could a way be implemented) to have one specific jasmine spec never time out? I am aware of the 3-argument syntax of 

``` js
it('Has a custom timeout', function() {
  expect(true).toBeTruthy();
}, msec)
```

that sets a custom timeout of `msec`. Is there a way to pass an argument that lets this spec never time out? Say, maybe passing a negative number, or just plain `false` or something?

**Comment by alecxe** [comment]
Here is a follow-up on StackOverflow: http://stackoverflow.com/questions/32336575/infinite-jasmine-timeout.
