### ISSUE TITLE
Inside onPrepare forking new browser instances throwing an error 100

### ISSUE THREAD

**Issue by svapreddy** [angular/protractor#1643]
In `onPrepare` event handler of protractor conf file, I am trying to fork numeber of browsers I need for test like below  

```
  browsers = {
        a: browser,
        b : browser.forkNewDriverInstance(),
        c : browser.forkNewDriverInstance(),
        d : browser.forkNewDriverInstance()
  };
```

But is throwing an error "Protractor failed with error code 100". Should not I fork new browser instance in onPrepare? If not, please let me know how I can do it

**Comment by lam2558** [comment]
hi, how would this work if my structure is based on page objects?  How do i switch between browser if i use page object?

example:

--test.js--
logingpage.setuserNameInputElement(userInfo.client.username);

--loginpage.po--
  this.setuserNameInputElement = function (name) {
    commonsMethod.findElementDriver(this.userNameInputPath).then(function (foundElement) {
      foundElement.clear();
      foundElement.sendKeys(name);
    });
  };

how do i switch between browser to use different page object. currently this work for a singular browser. would i need to update my page object to now accept a browser as well?

**Comment by hankduan** [comment]
Yes. Here's an example: https://github.com/angular/protractor/blob/master/spec/interaction/interaction_spec.js

**Comment by lam2558** [comment]
Thanks for the example, but it seem like you're doing a browser assignment for each method. I found out that I can just switch the default browser so it'll run in serial instead.

config:::
```
onPrepare: function () {
    global.browsers = {
      a: browser,
      b: browser.forkNewDriverInstance()
    };
    browsers.a.manage().timeouts().pageLoadTimeout(baseConfig.timeout.pageLoad);
    browsers.a.manage().timeouts().implicitlyWait(baseConfig.timeout.implicitWait);
    browsers.a.driver.manage().window().setSize(400,800);
    browsers.b.manage().timeouts().pageLoadTimeout(baseConfig.timeout.pageLoad);
    browsers.b.manage().timeouts().implicitlyWait(baseConfig.timeout.implicitWait);
    browsers.b.driver.manage().window().setSize(400,800);
}
```

test.js::
```
 it('A open and click login page', function () {
    browser = browsers.a;
    landingpage.getUrl();
    landingpage.clicklogInLinkElement();
    console.log('this is a click login page');
  });
  it('B open and click login page and sign in', function () {
    browser = browsers.b;
    landingpage.getUrl();
    landingpage.clicklogInLinkElement();
    logingpage.loginElement(userInfo.username,userInfo.password);
    console.log('this is b logging in');
  });
  it('A click sign in', function () {
    browser = browsers.a;
    logingpage.loginElement(userInfo.username,userInfo.password);
    console.log('this is a loggin in');
  });
```

**Comment by hankduan** [comment]
Are you sure that is working? You've never reassigned `element` to global so it's always using the original browser. 

Anyway, even if you assign element like you did with browser, it only works because you're not using the browsers in parallel. So yes it will work for this case, but once you start mixing the browser, your test will break. 

Consider:
```
it ('test', function() {
  browser = browser.a
  element = browser.a.element
  element(by.xyz).getText().then(function(text) {if (text === 'abc') {element(by.abc).click()});  
  browser = browser.b
  element = browser.b.element
})
```

Now `element(by.xyz)` will work against browser1 but `element(by.abc)` will work against browser2 because your assignment is synchronous while promises are async. You will understand what I'm saying once you start working with this.
