### ISSUE TITLE
Errors using ElementFinder returned from promise

### ISSUE THREAD

**Issue by rnavarette** [angular/protractor#1656]
I'm having some problems using an ElementFinder that is returned from a promise in my tests.

At best, It seems that any time an ElementFinder is accessed from a promise (this happens in some helper 'component' classes used for dealing with custom components) the code is requiring that the element in question exists.  Using the ElementFinder directly though, we do not receive any errors for non-existing elements, we simply get a falsy value from isPresent().

Additionally, we've noticed a consistent crash scenario when we use an element finder for a non-existant element in reused promise.  This isn't a direct case that we would normally test, but in failure scenarios this causes Protractor to crash rather than just failing the test.

A number of tests are included below illustrating the errors here.  The second to last test demonstrates the crash behavior, which I think is most interesting.  Additionally, its interesting to note the difference in behavior when using protractor.promise.fulfilled to create the promise (no crash when reused) vs using protractor.promise.when or returning the locator in the return statement of a chained promise (this causes crash).

Any help here would be greatly appreciated as we hope to be able to have protractor more cleanly handle these failure cases.

Thanks,
Ray

```javascript
	it('should not error when using elementFinder with invalid element',function(){
		var elementFinder = element(by.xpath('//bar'));
		expect(elementFinder.isPresent()).toBeFalsy();
	});

	it('will not crash when using elementFinder for valid element in reused promise',function(){
		var promise = protractor.promise.when(element(by.xpath('//*[1]')));
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeTruthy();
		});
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeTruthy();
		});
	});

	it('should not find element', function(){
		expect(element(by.xpath('//bar')).isPresent()).toBeFalsy();
	});

	it('ERROR: will not resolve when using elementFinder for invalid element in promise',function(){
		var promise = protractor.promise.fulfilled(element(by.xpath('//bar')));
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeFalsy();
		});
	});

	it('ERROR: will error when using elementFinder for invalid element in reused promise (protractor.promise.fulfilled)',function(){
		var promise = protractor.promise.fulfilled(element(by.xpath('//bar')));
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeFalsy();
		});
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeFalsy();
		});
	});

	it('ERROR: will CRASH when using elementFinder for invalid element in reused promise (protractor.promise.when)',function(){
		var promise = protractor.promise.when(element(by.xpath('//bar')));
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeFalsy();
		});
		promise.then(function(elementFinder){
			expect(elementFinder.isPresent()).toBeFalsy();
		});
	});

	it('should still be running after the preceding test is executed', function(){
		expect(true).toBeTruthy();
	});
```

**Comment by hankduan** [comment]
The reason that this is happening is that `then` will keep resolve its arguments until it is no longer a promise. 

In your case where you wrapped the ElementFinder (which is a promise) in a promise, webdriver will first resolve the outer promise. Then seeing the ElementFinder is also a promise, resolve that as well, resulting in the failure. There is no way to tell `then` to only resolve once. 

```javascript
it('error', function(){
      var el1 = element(by.xpath('//bar')); //this is a promise
      var el2 = protractor.promise.fulfilled(el1); //this is also a promise
      el1.then() //this resolves the promise and results in an ElementNotFound exception
      el2.then() //this resolves the outer promise, which is fine, but also tries to resolve e1, which causes the same exception
});
```

**Comment by hankduan** [comment]
Note that there isn't any way to make this nicer, because as part of protractor's API contract:
```javascript
elementFinder.then(function(e) {
  //e should be a raw web element, and has to throw ElementNotFound.
})
```

Of course we can break this contract in a breaking change, which I am supportive of because people make lots of mistakes with this (see below for example), but that's a separate discussion. 

All in all, you should never wrap ElementFinder in a promise, because that's a recipe to failure and flakiness. Imagine this:

```javascript
var el1 = element(by.css('some_valid_css'));
var promise = protractor.promise.fulfilled(el1);
promise.then(function(elementFinder){
    elementFinder.click();
    expect(elementFinder.getText()).toEqual('some value');
});
```

Many people erroneously think the above is equivalent to:
```javascript
var el1 = element(by.css('some_valid_css'));
el1.click();
expect(el1.getText()).toEqual('some value');
```

But that's not the case because in the first snippet, `elementFinder` is actually not an element finder, but a raw webelement resolved from `el1`. The result? If your `click()` performs some action, nothing is synced and you will get flake.

**Comment by juliemr** [comment]
This should no longer be able to be a problem after https://github.com/angular/protractor/pull/1926

**Comment by sdseenu** [comment]
var promiseWhile = Promise.method(function (condition, action) {
   if (!condition()) return;
   return action().then(promiseWhile.bind(null, condition, action));
});
lastRow.elm = $$('.ui-grid-row').last();

am getting error how to solve this: 

![image](https://user-images.githubusercontent.com/25522319/27138885-340f7a14-513f-11e7-91dc-b7797fddd2ff.png)

**Comment by vinodkumar117** [comment]
Hi,
i have to send the current time in  a field in time format (1205) while running the script .
already populated time in that field is always 15 minutes greater than current time for example if current time is 1155 then already populated time will be 1210.
i changed the populated time into integer and reduced by 15 minutes, its working fine for ex,(if current time is 1135 then populated time will be 1150 and after minus 15, current time is 1135 )
but if populated time is 1203 then how to subtract 15 minutes. (1203-1148 ?????)??
