### ISSUE TITLE
1.5.0 breaks backwards compatibility

### ISSUE THREAD

**Issue by cesarandreu** [angular/protractor#1660]
Is protractor following semver?

If it is, then please release a 1.5.1 patch with protractor.getInstance re-added, and bump current version to 2.0.0.  I can do a PR with the change if it's desired.

Otherwise, could we add a note to the README that specifies that protractor is not following semver? I was under the (possible incorrect?) impression that after 1.0.0 protractor would be following semver.

**Comment by juliemr** [comment]
I think we can close this - again, apologies if we unexpectedly broke you.

**Comment by cesarandreu** [comment]
It's alright, thank you.
