### ISSUE TITLE
Protractor seem to ignore debouce settings while executing sendKey command

### ISSUE THREAD

**Issue by vbaibus** [angular/protractor#1671]
Hi,
We noticed that protractor does not works correctly in case of debounce property is setup in ng-model-options of the control like below:

         <div class="input-group">
             <input id="email" type="text" inputmode="email" ng-model="user.email" name="uEmail" required class="form_control std-rounded" placeholder="email address"
         ng-model-options="{ debounce: 10000 }" ng-focus="focus('email');">
         </div>

         <div class="input-group">
             <input id="password" novalidate ng-minlength="6" type="password" inputmode="paidessword" name="uPassword" ng-model="user.password" required class="form_control std-rounded" placeholder="password"
            ng-model-options="{ debounce: 10000 }" ng-focus="focus('password');">
             ng-focus="focus('password');">
         </div>

When you run something like this:

  var txtEmail = element(by.model('user.email'));
  var txtPassword = element(by.model('user.password'));
  var btnSignIn = element(by.buttonText('Sign In'));
...
    txtEmail.sendKeys("qqq@asd.com");
    txtPassword.sendKeys("qqqqq");
    btnSignIn.click();

....click will be performed prior to  txtPassword field will be populated.

**Comment by ryanhart2** [comment]
You have ng-minlength="6" on your password input field, but are sending a password that is only 5 characters long. As a result, the model value is expected to be undefined.

**Comment by juliemr** [comment]
Thanks @ryanhart2 for taking a look! I think we can close this then.

**Comment by mohitjee15** [comment]
@juliemr Even I am facing similar issue.
I have a input box
`<input type="text" id="select" ng-model-options="{ debounce: 1000 }" ng-model="selectedItem.displayText" > `
This input is acting as a filter for a ng-repeat.

But since protractor is not respecting the debounce setting, I am getting incorrect list for the ng-repeat in my test.

**Comment by felixzapata** [comment]
Hi, I have the same problem. Due to accessibility and to inform the user the number of items filtered, I have added a debounce in the phonecat project but after that, the e2e do not work.

**Comment by mohitjee15** [comment]
@felixzapata Hi felix for the time being I have fixed the issue using `browser.sleep`

```
beforeEach(function () {
        CHF.multiselect.input(0).sendKeys('w');
	browser.sleep(700);
});
```

**Comment by felixzapata** [comment]
hi @mohitjee15 , thanks but it is not valid for me

**Comment by felixzapata** [comment]
Nevermind, After a review, I think that my problem is related with another issue in my code.
