### ISSUE TITLE
can't launch repl from wd-debug>

### ISSUE THREAD

**Issue by seglo** [angular/protractor#1677]
I'm using protractor `Version 1.5.0`.  I set a browser.pause() at the appropriate `it` block I want to debug.  When I attempt to drop into a repl as described in https://github.com/angular/protractor/blob/master/docs/debugging.md I am told it's an invalid command. 
```
wd-debug> repl
Unrecognized command.
```

**Comment by hankduan** [comment]
Sorry the feature is advertised a little early. You need to wait till protractor1.6 for this feature to work, or check out master. 

Closing as this is not really an issue.

**Comment by seglo** [comment]
My bad.  Thanks.
