### ISSUE TITLE
Allow element.evaluate to take functions

### ISSUE THREAD

**Issue by naturalethic** [angular/protractor#1680]
Like so:

```
functions.evaluate = function(element, expression) {
  if (/^function \(/.test(expression)) eval("expression = " + expression);
  return angular.element(element).scope().$eval(expression);
};
```

**Comment by juliemr** [comment]
What's the use case for this feature? It would be great if you could expand your example to show how you'd like to use this in a test. It seems like you could get this functionality really easily by just doing `browser.executeScript`.

**Comment by naturalethic** [comment]
For me the use case is it to be able to set values on the scope, and I might as well use the protractor wrapper because you've got the element and scope already figured out here.  If element.evaluate is going to call $eval anyway, might as well allow it to take a function, like $eval does.  I can turn this in to a real PR with tests and docs if you like, just got other things to do first so it might be awhile.

**Comment by juliemr** [comment]
You can already do `element.evaluate('a=90');`, which will set `scope.a = 90`. Is this not sufficient?

**Comment by naturalethic** [comment]
I thought I had tried that, but actually I was doing something more complex:
```date = moment().add(16, 'days').format('YYYY-MM-DD')```
I could format the date outside the evaluate and then set it, so you are correct, I don't need the feature to solve this particular case.  If I find a situation where I do need it, I'll badger you again.

**Comment by juliemr** [comment]
OK great - I'll close this for now then.
