### ISSUE TITLE
Expected conditions in protractor

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#1681]
This is a follow-up to [Expected conditions in protractor](http://stackoverflow.com/questions/27737333/expected-conditions-in-protractor) stackoverflow topic.

Long story short, as far as I understand the closest analogy to explicit waits for expected conditions is using `browser.wait()`. 

In [python-selenium](http://selenium-python.readthedocs.org/en/latest/waits.html#explicit-waits) or [java-selenium](https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html), there are multiple built-in commonly used expected conditions shortcuts, like:

 * [text_to_be_present_in_element_value](http://selenium-python.readthedocs.org/en/latest/api.html#selenium.webdriver.support.expected_conditions.text_to_be_present_in_element_value)
 * [invisibility_of_element_located](http://selenium-python.readthedocs.org/en/latest/api.html#selenium.webdriver.support.expected_conditions.invisibility_of_element_located)
 * [title_is](http://selenium-python.readthedocs.org/en/latest/api.html#selenium.webdriver.support.expected_conditions.title_is)

Is it possible to have these shortcuts built-in to protractor? Or, if not, what would be the appropriate way to implement it and use with protractor?

If the request doesn't make any sense, please close the issue. Thank you!

**Comment by hankduan** [comment]
I think this is a duplicate of https://github.com/angular/protractor/issues/1557, right?

**Comment by alecxe** [comment]
@hankduan very similar definitely, let's consider it as a dup. Thanks for the reference.
