### ISSUE TITLE
Live candlestick chart test

### ISSUE THREAD

**Issue by JackyTrad** [angular/protractor#1682]
Has anyone tried to test live candlestick chart ?
like in this sites: http://www.amcharts.com/demos/candlestick-chart/
                          http://www.highcharts.com/demo/dynamic-update/grid-light

**Comment by hankduan** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
