### ISSUE TITLE
browser.pause() does not pause the test

### ISSUE THREAD

**Issue by jdgblinq** [angular/protractor#1687]
I'm running Protractor 1.5 on Mac OSX with selenium webdriver standalone. `browser.pause()` and `browser.debugger()` do nothing when running protractor normally, or in debug mode. Protractor does not pause. This document indicates they should do something: https://github.com/angular/protractor/blob/master/docs/debugging.md

The only way I can get a breakpoint is to use `debugger` when running protractor in debug mode.

Is the documentation wrong, or is it my environment?

**Comment by juliemr** [comment]
This feature will be out in the 1.6 release which should be very soon!

**Comment by juliemr** [comment]
FYI - documentation on the github repo is for the version at 'master'. You can see documentation for the current release at http://www.protractortest.org or under the tagged branch for the appropriate version.
