### ISSUE TITLE
do beforeEach and afterEach process returned promises before continuing?

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/protractor#1689]
I've seen some commentary (can't find it now) suggesting that beforeEach and afterEach process returned promises before continuing.

Is this true?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks! 

Jasmine will not resolve a returned promise before continuing. Mocha will - see [asynchronous code](http://mochajs.org/#asynchronous-code)
