### ISSUE TITLE
setup data for a particular test using post to db instead of onPrepare

### ISSUE THREAD

**Issue by darrellsap** [angular/protractor#1694]
Similar to issue #1676.
I want to setup data for a particular test let say create a user and go to a page without requiring to carry out the login ui tasks.

To do this I need to 
1) post the new user credentials
2) take token from response
3) add token to cookies
4) Go to page for testing

How do I do a post from within a protractor test

I don't want to do this in the onPrepare as during testing I may have other data setup, so I can test the ui section in isolation.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by juliemr** [comment]
Protractor tests are run in node.js, so just use node.js's [http module](http://nodejs.org/api/http.html) to do a post.
