### ISSUE TITLE
[feature request] Attach protractor to existing webdriver session

### ISSUE THREAD

**Issue by quietlyconfident** [angular/protractor#1695]
It would be useful to be able to have protractor use an existing selenium browser session rather than always create a new one.

Note that I'm *not* asking to be able to attach to an already running local browser, for example that the console user has started up themselves (e.g. [Issue 18](https://code.google.com/p/selenium/issues/detail?id=18) ).

Rather, what I mean is, if I have started up a selenium browser session using, for example, a different testing framework or language bindings (e.g. python selenium ), run some tests in there, and exported the session ID into the environment or in some other way made it available, it would be nice to be able to configure protractor in the normal way (e.g. using an option in the protractor configuration file) to access this session.  Something like the below pseudo-code snippet.  It seems like this should be possible and relatively straightforward using the capabilities described here: [attachToSession](http://angular.github.io/protractor/#/api?view=webdriver.WebDriver.attachToSession).

In my particular use case, I'm doing some testing in Python involving creating a new user, resetting the password, logging in, &c; which in my application do not involve Angular JS.  At the end of these tests, I have a browser session on the app with a newly created, logged-in user with a randomized credentials. I'd like to proceed to test the Angular app with Protractor using the existing browser session, I can get the sessionId from the Python binding, and I can quit the python testing process without closing the browser.

I know that I could re-write all these tests to use protractor but that would be a huge pain, because I'm making use of a bunch of convenient python libraries to check email accounts for password reset emails.

I also know that i could just go ahead and close the browser, and then re-open a new session with protractor, but I pay by the minute for my remote browser service and would rather not burn the two minutes to wind-down and wind-up a new session.

```javascript
exports.config = {
    ...
    'capabilities': {
        ...
        'sessionId':'uuid-of-an-existing-selenium-session',
        // or even better . . . 
        'sessionId':process.env.SELENIUM_SESSION_ID,
        ...
    },
    ...
}
```

I searched the issues and the google groups and couldn't find this.

**Comment by juliemr** [comment]
Reasonable request: this could be done as a new [driver provider](https://github.com/angular/protractor/tree/master/lib/driverProviders).

**Comment by blabno** [comment]
We've got this in Arquillian and it speeds up the test development by order of magnitude.
It would be great to have this also in Protractor.
+1

**Comment by danghs** [comment]
I am also look for a way like this to continue a journey from legacy java e2e tests to protractor.
+1

**Comment by tristanstraub** [comment]
In the mean time, here's a gist that monkeypatch that overrides webdriver to capture and keep open any 
new browser sessions. https://gist.github.com/tristanstraub/d1c36ddaf9dcced570a6

Just call `captureBrowser` outside of the config, before the session is created.

**Comment by juliemr** [comment]
Done with https://github.com/angular/protractor/commit/3f3805f9496fb130ae01b3e3278ee1ea7684d8e7

**Comment by NextSoftTis** [comment]
Hi everyone, is there some way for getting all sessions inside of conf.js?

**Comment by andreasmarkussen** [comment]
Hi @NextSoftTis 

Yes! Now there is a way to get sessions inside the conf.js

    https://github.com/andreasmarkussen/webdriver-reuse-session/

This removes the 10 secs start-up time and increases the overall test with 10 to 30% since the cache is warm. You do, however, have to take responsibility for cookies, local storage etc but that you have to do anyway

Hope this helps.
