### ISSUE TITLE
Adding a new method to restart browser: browser.restart()

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#1696]
Thought we implement restart config for restart between test case (it/scenario), I think that it can be even more useful if we can have browser.restart() method so we can put into an step/scenario/feature/suite/it/describe level depending on test framework and users' needs.

**Comment by hankduan** [comment]
For now, you can clone a browser (`browser. forkNewDriverInstance`), then call `browser.quit()` on the current browser

**Comment by juliemr** [comment]
I think Hank's solution is good here.

**Comment by avdd** [comment]
#2685
