### ISSUE TITLE
Error: Error: config.framework (jasmine2) is not a valid framework.

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#1704]
I have installed latest version of protractor - Version 1.5.0.

and added following to the config file. 
 framework: 'jasmine2'

and i am seeing below error message while trying to run the script. Please see the attached screenshot for failure message. 
![screen shot 2015-01-09 at 10 45 35](https://cloud.githubusercontent.com/assets/6057889/5678723/15a54742-97ed-11e4-86ce-328f9e21c919.png)

Am i missing any package and that needs installing ?. Help would be appreciated. Thanks in Advance.

**Comment by hankduan** [comment]
The latest is protractor 1.6 and you need it for jasmine 2

**Comment by smahalingam** [comment]
Thanks that works
