### ISSUE TITLE
Running Protractor with Existing Cookies

### ISSUE THREAD

**Issue by Kaleb8812** [angular/protractor#1706]
I am currently testing a website that requires you to sign in through an authentication page. However, this page is not written in Angular so protractor gives me the generic "Error: Angular could not be found on the page" message. If I am using chrome regularly, I can collect the cookies from the login page and thus I can close the tab I am logged in to and reopen it without having to log in again. Finally my question: Is there a way to make the new chrome window Protractor opens carry cookies from my earlier chrome sessions? Or is there someting I can add to the Protractor code files that would automatically store my cookies? Thanks!

**Comment by hankduan** [comment]
See http://stackoverflow.com/questions/27234785/how-to-handle-basic-authentication-with-protractor/27388698#27388698 if you're dealing with basic authentication. 

If it's a login page, there are also many threads covering this:
https://github.com/angular/protractor/blob/master/docs/faq.md
https://github.com/angular/protractor/issues/51
http://stackoverflow.com/questions/26536933/test-login-with-protractor-on-a-non-angular-page

Please post follow up questions on stackoverflow, as github is for issues and feature requests. Thanks!
