### ISSUE TITLE
There was a webdriver error: RangeError Maximum call stack size exceeded in debug, while executing executeScript

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#1711]
In debugging session, (got running `node ./bin/elementexplorer.js <urL>`) if  try to execute 
```
browser.executeScript(function() {
                        arguments[0].scrollIntoView();
                    }, el);
```
 it throws
`There was a webdriver error: RangeError Maximum call stack size exceeded`

**Comment by juliemr** [comment]
What is `el`? I expect you're getting into an infinite loop with webdriver trying to resolve it as a promise.

**Comment by axelsayegh** [comment]
Are you passing 'ElementFinder' (el) to method? try el.getWebElement()

**Comment by juliemr** [comment]
Closing as obsolete.

**Comment by bitliner** [comment]
The cause was because it was not `el.getWebElement()` (it was just the element `el(by.css(...)) )` .
