### ISSUE TITLE
Phantom js showing empty page source when page is non angular

### ISSUE THREAD

**Issue by rkchunduri** [angular/protractor#1714]
I am using phantomjs and protractor to automate one of the angular js based applications,login page for this application is non-angular.When I am trying to  open that non angular login page,it is showing empty page source.
<html><head></head></html>

Angular based pages are working like a charm.

I am using Protractor 1.60,Selenium 2.44 and Phantom js 1.9.8.Can some one help me on this issue.l

**Comment by juliemr** [comment]
This doesn't sound like a Protractor issue, but a PhantomJS one. Closing - please open up an issue with PhantomJS. Thanks!
