### ISSUE TITLE
Jasmine report in latest protractor - 1.0.6

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#1715]
I installed latest version of protractor - 1.0.6 and updated the config file to use jasmine2. 

![screen shot 2015-01-12 at 14 06 20](https://cloud.githubusercontent.com/assets/6057889/5704004/3975e698-9a65-11e4-8b1c-2e9ee26ca220.png)
![screen shot 2015-01-12 at 14 06 53](https://cloud.githubusercontent.com/assets/6057889/5704008/3c57a306-9a65-11e4-841c-936ad4490ba2.png)

and my onPrepare file contains
![screen shot 2015-01-12 at 14 14 23](https://cloud.githubusercontent.com/assets/6057889/5704025/53dfae4c-9a65-11e4-8bcd-4879f161a6d1.png)

Did i missed anything ?

Thanks

**Comment by hankduan** [comment]
Can you check two things first:
* Did you mean to say you have `1.6.0` instead of `1.0.6`?
* What version of jasmine-reporters are you running. You need to run the latest version so that it's compatible with jasmine 2.x (i.e. don't install jasmine-reporter@1.x.x)

**Comment by smahalingam** [comment]
@hankduan - Thanks for your reply.

Yes i meant to mention - 1.6.0 - It was typo. I am using "2.0.3" version of  jasmine-reporters. 

I am not sure what would i put on the 'onPrepare' file
