### ISSUE TITLE
isVerbose not working with jasmine 2

### ISSUE THREAD

**Issue by brendancwood** [angular/protractor#1716]
updated with jasmine2 and found the isVerbose flag isn't working as before.

**Comment by hankduan** [comment]
Nope it's not. `isVerbose` was something `minijasminenode` added, but now that jasmine has their own npm module, we opted for that while upgrading to jasmine2 and will only support anything that jasmine officially supports here https://github.com/jasmine/jasmine-npm.

**Comment by juliemr** [comment]
Do you think this should be documented in the upgrade guide?

**Comment by hankduan** [comment]
Updated: https://github.com/angular/protractor/commit/3fe4cfc419ba566c730eb528ac03a3c62fa6afe2

**Comment by juliemr** [comment]
Great! I think we can close this then.
