### ISSUE TITLE
Deleting Cookies

### ISSUE THREAD

**Issue by cristifilip** [angular/protractor#172]
I'm trying to delete all cookies before running my tests.
I didn't find how to delete them.

Somebody told me on StackOverflow that I should use session.deleteAllCookies() method. http://stackoverflow.com/questions/19380014/delete-cookies-in-webdriverjs?noredirect=1#comment28721420_19380014

I used:
ptor.driver.session.deleteAllCookies();
but this gives an error: Cannot call method 'deleteAllCookies' of undefined.

**Comment by cp5w** [comment]
For those that arrive here from Google, the correct call is now
```
browser.manage().deleteAllCookies();
```
note that `ptor` is now `browser`

**Comment by rcomblen** [comment]
With protractor 4.0.5, correct call is

    browser.driver.manage().deleteAllCookies();

beware that it only clears the cookies for the domain of the current page, so no point in doing that in a `beforeEach`.

**Comment by djom20** [comment]
With protractor 4.0.9, in chrome fails:

`browser.driver.manage().deleteAllCookies();`

Normally I have been deleting all the cookies before each test, but now it not working in chrome, and I still didn't find how to delete them.

**Comment by Chriskimm1** [comment]
browser.driver.manage().deleteAllCookies(); does not work in safari ?
