### ISSUE TITLE
Simple test passes in jasmine1 but fails on jasmine2

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#1721]
I had a simple test which passes in Jasmine1 but fails in Jasmine2.0 

Script,
![screen shot 2015-01-13 at 12 44 10](https://cloud.githubusercontent.com/assets/6057889/5720863/08157f6a-9b22-11e4-8e5a-048ca659125a.png)

Test result on Jasmine1
![screen shot 2015-01-13 at 12 43 53](https://cloud.githubusercontent.com/assets/6057889/5720968/6e6985b2-9b23-11e4-8878-b47b894340e3.png)

Test result on Jasmine2
![screen shot 2015-01-13 at 12 44 04](https://cloud.githubusercontent.com/assets/6057889/5720971/734bfe02-9b23-11e4-9216-412640464d63.png)

Not sure what's wrong in my script as it passes in jasmine1.0 but fails in jasmine2.0

Thanks

**Comment by smahalingam** [comment]
Detailed error report for Jasmine2 run
![screen shot 2015-01-13 at 14 12 38](https://cloud.githubusercontent.com/assets/6057889/5721852/571d9e38-9b2e-11e4-9738-46c7fbdfc790.png)

**Comment by hankduan** [comment]
What does your config look like? I just ran with 

```javascript
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',

  framework: 'jasmine2',

  suites: {
    hank: './hank_spec.js',
    lib: 'basic/lib_spec.js',
  },

  allScriptsTimeout: 30000,

  multiCapabilities: [{
    'browserName': 'chrome',
  }],

  baseUrl: 'http://localhost:8081',
};
```

```
node lib/cli.js spec/hankConf.js --suite=hank
```

**Comment by smahalingam** [comment]
Thanks for your reply @hankduan @juliemr.

My config file looks as,
// Configuration for E2E testting for my stack portal
exports.config = {
  //seleniumServerJar: '',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  //seleniumAddress: 'http://10.72.197.162:4444/wd/hub',

  allScriptsTimeout: 30000,

  // How long to wait for a page to load.
  getPageTimeout: 10000,

  // A base URL for your application under test. Calls to protractor.get() with relative paths will be prepended with this.
  baseUrl: 'https://uat2-mystack.pearson.com/',

  // Alternatively, suites may be used. When run without a command line parameter, all suites will run.
  // If run with --suite=sanity, only the patterns matched by that suite will run.
  suites: {
    addUsers: './**/UsersAndTeams_spec.js',

    test: './**/Cleanup_spec.js',
  },

  multiCapabilities: [{
    'browserName': 'chrome',
  }],


  // Patterns to exclude.
  exclude: [],

  framework: 'jasmine',

  resultJsonOutputFile:'result1',

  // Options to be passed to jasmine2.
  //
  // See the full list at https://github.com/jasmine/jasmine-npm
  jasmineNodeOpts: {
    // If true, print colors to the terminal.
    showColors: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 60000,
    // Function called to print jasmine results.
    print: function() {},
    // If set, only execute specs whose names match the pattern, which is
    // internally compiled to a RegExp.
    // grep: 'Cleanup_spec.js',
    // Inverts 'grep' matches
    invertGrep: false
  },

  // A callback function called once protractor is ready and available, and before the specs are executed
  // You can specify a file containing code to run by setting onPrepare to the filename string.
  onPrepare: './onPrepare/startup.js',
};

**Comment by hankduan** [comment]
What's the startup script (or can you try running your conf without it)? I just ran with your conf (without the startup script) and it worked fine. 

One thing to note though is that you passed a noop function as the print function, so nothing will print. I added that empty function definition in the reference doc to show people that they can pass in functions, not for people to copy it as is =)

**Comment by smahalingam** [comment]
This line in the startup was issue, 
var passed = jasmine.getEnv().currentSpec.results().passed();

Can i know what should go into the 'print: function() {},' ?

**Comment by juliemr** [comment]
If you don't specify anything (just remove he line specifying print) it will default to printing to the console.

Sounds like this is resolved.

**Comment by hankduan** [comment]
Yes that's the 1.3 syntax. `currentSpec` is no longer supported in 2.x. 
You can pass any function into the print:

i.e. log to console? `print: console.log`
log to file? `print: funcction(text) {fs.appendFile('message.txt', text)}`
you get the point

**Comment by smahalingam** [comment]
@hankduan - Yes that makes sense. Thanks
