### ISSUE TITLE
How to put implicitlywait in onComplete method

### ISSUE THREAD

**Issue by Raghulraj** [angular/protractor#1725]
Hi,

I am writing a custom reporter and i have to wait for IO write.  My reporter function gets trigger in onComplete method. How to implicitly put wait on onComplete?

I have tried below ways.

1.browser.manage().timeouts().implicitlyWait(20000);

2.onComplete: function() {
      browser.wait(function() {
      ....
      finalreport.generateHtmlReport();
      },20000);
      },

None of the above worked. Any other working solutions...

Thanks in Advance,
Raghul

**Comment by hankduan** [comment]
There isn't any way to do that right now unfortunately, as we're limited by the test runners on what we can do (i.e. jasmine). Can you not use writesync? (http://nodejs.org/api/fs.html#fs_fs_writesync_fd_buffer_offset_length_position)

**Comment by Raghulraj** [comment]
Thanks for the information. I have used writesync and it worked.
