### ISSUE TITLE
Locator not respecting exclude

### ISSUE THREAD

**Issue by kirkstrobeck** [angular/protractor#1726]
http://stackoverflow.com/questions/27911772/locator-not-respecting-exclude

I expect the selector

```js
element(by.css('html:not([data-spellcheck="false"])'))
// or
element(by.css('*:not([data-spellcheck="false"])'))
```

to return any element without the data attribute `data-spellcheck="false"`, but it doesn’t work. How should I change it?

**Comment by hankduan** [comment]
Like I asked on stackoverflow: what exactly doesn't work? Does it return elements with the `data-spellcheck="false"` attribute? Or does it do something else?

Also, like the other comment mentioned on stackoverflow, `html:not()` will only return html elements, and you probably want `html :not()`

I'm closing this. Please respond to my question on stackoverflow, and I'll try to help you there.
