### ISSUE TITLE
Cant find the correct webview context

### ISSUE THREAD

**Issue by BarTsouri** [angular/protractor#1727]
Hi all,

I have a pretty complex mobile-app with 2 webviews, where one of them has angular embedded and the other doesn't.

When calling wdBrowser.contexts I get an array which looks like that:  [ 'NATIVE_APP', 'WEBVIEW_1', 'WEBVIEW_5' ]

Most of the times contexts[1] is the angular embedded one, but when it is not my automation tests fail because of the requirement for angular.

Does anyone have a workaround for changing the context to the angular embedded webview in 100% of the times?

I tried to inspect the webview's url the after choosing it, but non angular webview throws an exception when using getCurrentUrl() : 'Error while waiting for Protractor to sync with the page'

Thanks in advance for your help

**Comment by juliemr** [comment]
Can you describe your setup more explicitly? Are you using appium? This might be a better question for the appium forums, since it sounds like the root problem is figuring out which webview to use.

**Comment by BarTsouri** [comment]
Yes I do use Appium.
I think that I will have to use their infrastructure for that.
Thanks
