### ISSUE TITLE
Host protractor's test app

### ISSUE THREAD

**Issue by hankduan** [angular/protractor#1729]
Now that we have our own website, is it possible to host our testapp somewhere on it (updated whenever we update the website) so that we can use it to provide examples when answering questions? Sometimes it's really hard to find an easy to understand public angular app that uses all the angular features. 

It's just a small convenience so feel free to close this if it's not something easy.

**Comment by juliemr** [comment]
The only slightly tricky part is that the test app has an actual backend and isn't 100% static files serving, unlike the website. I agree that this would be nice though, we just need to set it up.

**Comment by chris-ramon** [comment]
:+1:

**Comment by juliemr** [comment]
Done! Check out http://www.protractortest.org/testapp/
