### ISSUE TITLE
Drag And Drop not working for slider bar 

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#173]
I am trying to do Drag And Drop of slider bar , when i launch protractor , the following scripts get executed without any errors or warning but i don't see the slider bar moving.

ptor.get('URL');
//slider bar object 
var slider = ptor.findElement(protractor.By.xpath(".//*[@id='leftcolumn']/div[2]/div/a[1]"));  
ptor.actions().dragAndDrop(slider,{x:1000,y:0}).perform();
ptor.sleep(10000);

**Comment by ew9001** [comment]
I got it to work with this:

var slider2 = browser.driver.findElement(By.xpath('//*[@id="resize-grid"]/div/div/div/div/div/div[2]/label/div[2]/span[2]'));
 browser.driver.actions().dragAndDrop(slider2,{x:1000,y:0}).perform();
