### ISSUE TITLE
Is there any way to integrate Protractor with TestRail API?

### ISSUE THREAD

**Issue by MahmudulHasan** [angular/protractor#1733]
I am using protractor to automate a Angular website. I need to log the test result in TestRail. Is there any way to do it using protractor?

**Comment by smahalingam** [comment]
It is possible to generate test result in JUnitXml & NUnitXml format. Does TestRail have plugin to for junit Or nunit report ?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
