### ISSUE TITLE
Element Validation within If Statement

### ISSUE THREAD

**Issue by zalow517** [angular/protractor#1735]
I'm having issues when adding an element validation within an if-statement.

Basically, irrelevant of the result of the if-statement, Protractor is still trying to find the element specified within the if-statement.

Here is the code that is still running even though the if-statement returned false:

                if (thisIsAlwaysFalse == true) {
                    
                    console.log(':::::::::::::::' + thisIsAlwaysFalse);
                    it('If-statement test', function(done) {

                        var elementToFind= element(by.xpath('//td[contains(@class,"hello")]'));                  

                        browser.wait(function() {
                            return browser.isElementPresent(elementToFind);
                        }, 5000);            

                        elementToFind.click();

                        done();
                    });        
                }

Also, funny thing is that the console.log part is successfully ignored!

Anyone has a solution for this or possibly knows why this is happening?

Thanks in advance :)

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
