### ISSUE TITLE
Additional methods like getLocationPath, getLocationSearch, etc.

### ISSUE THREAD

**Issue by qoobaa** [angular/protractor#1737]
I think it'd be nice to have additional methods from `$location` service, i.e. `getLocationPath` or `getLocationSearch` available on the browser object. I can try to implement it and create a PR if you agree it's a good idea.

**Comment by hankduan** [comment]
`getLocationPath` === `browser.getCurrentUrl()`
`getLocationSearch` === `browser.getCurrentUrl().then(url) {return require('url').parse(url, true).query;}`

I guess you can make `getLocationSearch` easier to get at, but it doesn't seem to fit as part of protractor.

**Comment by juliemr** [comment]
I agree - this is stuff you can parse easily from `getCurrentUrl` or `getLocationAbsUrl`. Can you give an example use case that cannot be easily done like @hankduan suggested?

**Comment by qoobaa** [comment]
If we have access to the whole URL we can parse it - that's totally true. I just thought that it might be useful to have a little bit more methods there. Close the issue if you say that it's not a part of protractor. Thanks.

**Comment by juliemr** [comment]
These utils are pretty easy to do with node's [url](http://nodejs.org/api/url.html) module, so I think they don't need to be duplicated in protractor. Closing.
