### ISSUE TITLE
Error: Invalid or corrupt jarfile selenium-server-standalone-2.44.0

### ISSUE THREAD

**Issue by Sam-Davis** [angular/protractor#1739]
I'm following the instructions on here to install:
http://www.ng-newsletter.com/posts/practical-protractor.html

I changed the:
webdriver-manager update 
to be: 
webdriver-manager update --proxy="<my proxy>" --ignore_ssl

to get around the proxy, but when trying to run
webdriver-manager start

I get: 
Error: Invalid or corrupt jarfile C:\Users\sam\AppData\Roaming\npm\node_modules\
protractor\selenium\selenium-server-standalone-2.44.0.jar
Selenium Standalone has exited with code 1

I have also tried downloading the file by going to the URL, but this does not work either. Is there another version of the jar available?

**Comment by juliemr** [comment]
I'm very confused that it doesn't work by downloading the file directly. How does that fail? Is it the same corrupt jarfile problem?

**Comment by Sam-Davis** [comment]
Yes it is

**Comment by Sam-Davis** [comment]
It turns out the virus scanner here was silently rejecting the file and truncating it. Thanks anyway for your quick response on this.
