### ISSUE TITLE
$$ should be listed under "element.all(locator)" instead of "element(locator)"

### ISSUE THREAD

**Issue by marneborn** [angular/protractor#1740]
$$ is the shortcut for element.all (right?), but in the API documentation it's listed under "element(locator)", it would be more clear if it were under "element.all(locator)".

**Comment by juliemr** [comment]
`$$` is a shortcut for `element.all(by.css(...))`, not generic `element.all`.

This is slightly confusing, but those entries in the docs are actually describing the fact that you can chain element with $.

`element(by.id('foo')).$('.myclass')`
or
`element(by.id('foo')).$$('.myclaass')`

So it makes sense that they're listed under `element`. What we probably should do is highlight the exported globals (`$`, `$$`, `browser`, `element`, etc) in the docs somewhere).

**Comment by sjelin** [comment]
Fixed
