### ISSUE TITLE
how to implement protractor JavaScript API in Java to use in existing Selenium Java Frameworks

### ISSUE THREAD

**Issue by sravanmedarapu** [angular/protractor#1746]
Hi There,

I would like to use Protractor from existing Selenium Java Framework , Can some one suggest me the approach on How to implement it in Java ,  I can spend some time to do this :)

Thanks
Sravan

**Comment by sjelin** [comment]
Are you asking how to re-write protractor into Java?

**Comment by sravanmedarapu** [comment]
Yes Sjelin, I would like to know the implementation procedure to re-write into Java. Can you please share some basics of this .

**Comment by jlin412** [comment]
I heard that there is an angular.js plugin for java selenium webdriver but
I never use it personally.

**Comment by sjelin** [comment]
All of the code is in the `lib` folder.  A lot of it is stuff for setting up the environment or integrating with frameworks like `jasmine`, which you probably aren't interested in.  Probably what you care about are the protractor-specific selectors, which are implemented in [locators.js](https://github.com/angular/protractor/blob/master/lib/locators.js#L6).  Hope that helps!
