### ISSUE TITLE
How to view HTML reports from Jasmine2

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#1748]
We've been eagerly awaiting Jasmine2 support and have started using it.

Unfortunately, our HTML reports and screenshots are no longer working (using https://github.com/jintoppy/protractor-html-screenshot-reporter)

A few queries:

1. Looking at [boot.js](http://jasmine.github.io/2.0/boot.html) for Jasmine2, it looks like an HTML reporter is included as standard. However, I can't see anything being output when I run my protractor tests. Is this something I can configure? 

2. The [Protractor reference config file](https://github.com/angular/protractor/blob/master/docs/referenceConf.js) suggests there are more options for jasmineNodeOpts and points me to find the full list at https://github.com/jasmine/jasmine-npm. I have not been able to find the list at https://github.com/jasmine/jasmine-npm (or by Googling) - should this be referencing a different page?

3. Our code for the HTML reporter was as shown below (within onPrepare). Is there anything that needs to be tweaked within this code that would easily make it work for jasmine 2?

  ```
  var jasmineEnv = jasmine.getEnv();
  var HtmlReporter = require('protractor-html-screenshot-reporter');
    jasmineEnv.addReporter(new HtmlReporter({
    baseDirectory: '../tmp/screenshots'
  }));
```

Thanks for any help!

**Comment by juliemr** [comment]
1. boot.js is for running Jasmine2 included in html on a website, and is not used by Protractor when running tests with the jasmine2 framework.

2. We should link to a better list - here is where the options are used in the code: https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L28

@hankduan were you able to find better documentation on this?

3. I believe protractor-html-screenshot-reporter is not yet compatible with jasmine2 - you'll have to bring this up with them.

**Comment by hankduan** [comment]
No the code is pretty much the documentation for jasmine-npm. Do you think it's better if I remove "// See the full list at https://github.com/jasmine/jasmine-npm" since I think I pulled all the important options into the referenceConf already.

**Comment by juliemr** [comment]
Let's say `// See https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js for the exact options availabls` so at least people know they're looking for code.

**Comment by hankduan** [comment]
done: https://github.com/angular/protractor/commit/3880b2738234c1e4375965c31e026bfa1dd6febb

**Comment by juliemr** [comment]
I think we can close after the doc updates.
