### ISSUE TITLE
Setting Chrome Options

### ISSUE THREAD

**Issue by Ardesco** [angular/protractor#175]
I'd like to add some extensions to my chrome instance, using the WebDriver JavaScript API I would do this:

```
var options = new chrome.Options().
    addExtensions("pathToExtension");

var driver = new webdriver.Builder().
    withCapabilities(webdriver.Capabilities.chrome()).
    setChromeOptions(options).
    build();
```

How would I do the same thing in protractor?  

It looks like you are parsing the capabilities section of the JSON to work out how to build the driver object, but I don't see anything in the structure that would accept a series of options.

As a side note is there a google group/mailing list for protractor, it would be good to put queries like this there rather than cluttering up the issues list.

**Comment by intergleam** [comment]
is there any way to load unpacked extension from a folder?

**Comment by saulshanabrook** [comment]
@intergleam yeah you can use the Chrome CLI flags to pass in a path to a directory which will be loaded. Here I load an extension at the path `/dist`:

```javascript
config.capabilities.chromeOptions.args.push("--load-extension=/dist")
```

The [ChromeDriver docs](https://sites.google.com/a/chromium.org/chromedriver/extensions) document this approach to loading an unpacked extension.

**Comment by hadanhtoi** [comment]
Hi, i got a problem. Can someome help me ! 
i want to export file from export button in js page and download file to a directory in my project for testing. But i cant change download default_directory. when i run test, it was downloaded in /Downloads  , not /resource/download/ directory. 
This is my protractor-config.js 

  directConnect: true,
  multiCapabilities: [{
      browserName: 'firefox',
      acceptInsecureCerts: true,
      'moz:firefoxOptions': {
        args: ["--headless"        ]
      },
      prefs: {
                   'download': {
                'prompt_for_download': false,   
                'default_directory': process.cwd() + "/resources/test/download",
                'directory_upgrade': true
            },

        },
    },
    {
      browserName: 'chrome',
      acceptInsecureCerts: true,
      chromeOptions: {
        args: [
          "--headless",    
    ]
      },
      prefs: {        
            'download': {
                'prompt_for_download': false,                        
                'default_directory': process.cwd() + "/resources/test/download",       
               'directory_upgrade': true,               
            },
        },
    }
  ],
![image](https://user-images.githubusercontent.com/14163857/53617011-e414e600-3c17-11e9-80b6-84cdb4693ded.png)

**Comment by murcraft** [comment]
I have the same problem:
```
capabilities: {
      browserName: 'firefox',
      marionette: true,
      acceptInsecureCerts: true,

      'moz:firefoxOptions': {
        args: [
          //'--headless',
          'window-size=1920,1080'
        ],
            prefs: {
              'browser.download.folderList': 2,
              'browser.download.dir': './artifacts/downloads',
              'services.sync.prefs.sync.browser.download.useDownloadDir': true,
              'browser.download.useDownloadDir': true,
              'browser.download.manager.alertOnEXEOpen': false,
              'browser.download.manager.closeWhenDone': true,
              'browser.download.manager.focusWhenStarting': false,
              'browser.download.manager.showWhenStarting': false,
              'browser.helperApps.alwaysAsk.force': false,
              'browser.download.manager.showAlertOnComplete': false,
              'browser.download.manager.useWindow': false,
              'browser.helperApps.neverAsk.saveToDisk': 'application/x-www-form-urlencoded; gzip,application/pdf; application/csv; application/xlsx; application/xml; image/webp; image/apng; application/signed-exchange',
            }
          }
    },
```

protractor: 5.4.2

**Comment by murcraft** [comment]
Resolved https://github.com/angular/protractor/issues/175#issuecomment-481584687.
You should delete geckodriver from node_modules and run webdriver-manager update. I noticed prefs didn't work with selenium.standalone 3.4.0
