### ISSUE TITLE
What is the best way to wait for a custom event?

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#1750]
My solution would be to inject js code inside the page to hook an handler executed on a custom event and then make the browser wait until the handler is executed.
In other words:

```
browser.executeScript('window.on('customEvent', function(){ 
  window.hasBeenTriggered=true;
})
)')
browser.driver.wait(function(){
  return browser.executeScript('return window.hasBeenTriggered;' )===true;
});
```

Is there a better way to do it?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
