### ISSUE TITLE
Tests can not pass on Mozilla Firefox 35.0.1

### ISSUE THREAD

**Issue by coldmind** [angular/protractor#1759]
After update of firefox, tests can not pass Mozilla Firefox 35.0.1.
At least `Protractor.waitForAngular()` seems not working.
Before update all was well.
Can anyone check tests on this firefox version?

**Comment by ericmdantas** [comment]
Hey, @coldmind!

We've got this issue opened right here too: #1734.

Right now, we're just waiting for the [selenium fix](https://github.com/angular/protractor/issues/1734#issuecomment-70704685).

If you really, really need to test against Firefox, you'll have to downgrade it to version 33 or 34.

**Comment by coldmind** [comment]
Thanks!
Sorry, duplicate issue, closing it now.
