### ISSUE TITLE
feat(elementExplorer): allow passing context to browser.enterRepl()

### ISSUE THREAD

**Issue by tb** [angular/protractor#1762]
With `browser.enterRepl()` added in https://github.com/angular/protractor/pull/1693
it is not possible to access objects loaded in test context or to load anything with `require`.

For example:

    page = require('./some_feature_page')

    describe 'Some Feature', ->
      it 'should work', ->
        page.open()
        browser.enterRepl()
    
Here, I would expect is to have access to `page` object within interactive console so that I can interact with page via helper methods I defined in `some_feature_page.coffee`.

@hankduan suggested in https://github.com/angular/protractor/pull/1693#issuecomment-71892470 it might be solved by passing context object to `browser.enterRepl()`

    context = {page: page}
    browser.enterRepl(context)

**Comment by juliemr** [comment]
Done with https://github.com/angular/protractor/pull/1931
