### ISSUE TITLE
protractor hangs indefinitely on "[launcher] Running 1 instances of WebDriver"

### ISSUE THREAD

**Issue by dseravalli** [angular/protractor#1764]
OSX Yosemite 10.10.1
Node 0.10.26
Protractor 1.6.1
Java 1.8.0_31

webdriver-manager is running and I can hit the server at http://localhost:4444/wd/hub and manually create a chrome session if i want. But when I run protractor it just hangs forever. If i switch my config file to use sauce labs instead of `seleniumAddress` everything works fine. 

Nothing is outputted in the webdriver-manager log or web gui at all. No chrome session starts. nothing...

```
-> protractor public/test/protractor.conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
```

Another weird thing is i cant pass any flags to protractor. It will just print the help if I try any of them.

config file:
```
exports.config = {

    seleniumAddress: 'http://localhost:4444/wd/hub',

    capabilities: {
      browserName: 'chrome'
    },

    suites: {
        nuf: 'e2e/nuf.spec.js'
    },

    framework: 'mocha',
    mochaOpts: {
        reporter: "spec",
        timeout: 30000,
        slow: 3000
    }
};
```

**Comment by deveshmaheshwari** [comment]
Only workaround I have found is to downgrade Node.

**Comment by dseravalli** [comment]
Just tried 0.10.36 and 0.10.32 and had same behavior as 0.10.26

**Comment by dseravalli** [comment]
This was a local network issue

**Comment by borisdiakur** [comment]
@dseravalli Any idea, how a local network issue can cause the indefinete hanging? Why are no timeouts triggered?

**Comment by brunofin** [comment]
@dseravalli can you please expand your solution? I'm running into the same problem running in a Ubuntu 14.04.1 Vagrant box.

**Comment by dseravalli** [comment]
@brunofin In my Vagrantfile, I had port 4444 forwarded, which is the port webdriver uses. Removing that allowed me to hit the webdriver server.
