### ISSUE TITLE
Accommodate data consistency tests with some kind of blocking then() statement

### ISSUE THREAD

**Issue by isaaclyman** [angular/protractor#1766]
I enjoy the asynchronous capabilities of promise-returning functions in the Protractor API. But I frequently write tests that check for the consistency of data across various pages in my team's web app. As a very simple example, I'll use a `getText()` to grab a user name from a list, then click on that user to get to their personal user page, use another `getText()`, and make sure the names match. If I try to store a `getText()` in a variable, manipulate it slightly (e.g. changing it from 'First Name Last Name' to 'Last Name, First Name') and then compare it to an expected result, the test fails because the variable is parsed before it has a value and it's undefined until the promise comes back (asynchronously).

Currently, my solution is to do my first `getText()`, and in the `then()` statement I insert the rest of the test, until I get to another promise-returning function and then I break the `then()` statement and tack another `then()` statement on the end of it, like so:
```javascript
var elementText;
element(username).getText().then(function(text) {
  elementText = text;
  element(nextPage).click();
})
.then(function() {
  element(username2).getText().then(function(text) {
    expect(text).toEqual(elementText);
  });
  element(finalPage).click();
})
.then(function() {
  element(username3).getText().then(function(text) {
    expect(text).toEqual(elementText);
  });
  element(logout).click();
});
```
As you can see, most of these tests end up being a long chain of `then()` statements. It would be nice if there were a less work-around-ish way to do this.

I propose:
1) An alternative `then()` statement of some kind. Maybe a `blockingThen()` statement as an alternative to a regular `then()` statement, meaning that statements beyond the block closure should not be parsed or added to the Command Queue until the current promise returns.
2) Some kind of `wait()` statement that actually puts parsing on hold until the enclosed statement has returned a promise.
3) I don't know if this is possible, but it would be neat to allow user-defined functions that have a `return` statement inside of a `then()` statement, and wait for them to finish before moving on to the next statement.

If none of these are possible, my current solution is passable enough. I'd just like to make things more understandable.

**Comment by juliemr** [comment]
I don't think that 1) or 2) are possible without some pretty ugly javascript hacks, but I think that some of what you want is already implemented. For example, you can do:

```js
element(foo).getText().then(function(text) {
  return protractor.promise.delayed(400);
});
element(bar).getText();
```
The second call to `getText` won't execute until the delayed promise is done. I believe this is what you're asking for in 3).

You might also want to take a look at [promise.all](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/promise.js#L769).

**Comment by juliemr** [comment]
I don't think there's a feasible feature request for Protractor here that's new, so I'm closing the issue - please feel free to continue discussion here or open up a new issue if you feel it hasn't been resolved.
