### ISSUE TITLE
localStorage empty after calling browser.get()

### ISSUE THREAD

**Issue by ceelian** [angular/protractor#1767]
I am not absolutely sure if this is a bug or an intended behavior. I do a login procedure in a parent describe block which stores the auth token in localStorage. Then in the `beforeEach()` of child describe block a `browser.get('/')` to start from the main page and signed in. But I got signed out, and tests failed,  because the app accesses an empty localStorage. 

Pseudo code for clarification:

```
describe('Private Webapp', function () {
	browser.get('/');
	//do all the login stuff which saves the auth token to local storage
	var mainPage = new MainPage(browser);
	mainPage.doLogin('testuser', 'testpwd');

	describe('do authenticated tests',function(){
		beforeEach(function(){
			browser.get('/');
		});

		it('authenticated test 1', function() {
			//do and expect some stuff
		});
		
		it('authenticated test 2', function() {
			//do and expect some stuff
		});
	});
});
```

If I use `browser.setLocation('/')` in the `beforeEach()` everything works as expected.
 `browser.get('/')` and `browser.navigate().refresh()` seems like it resets the localStorage.

Is this behaviour documented somewhere?

Tested in Chrome and Firefox.

Thanks for clarification!

**Comment by juliemr** [comment]
This is unexpected - `browser.get` should not affect localStorage. 

I think the error is with the way that your test is set up. In Jasmine, you should be using `beforeEach` or or `beforeAll` (this latter one requires that  your framework be `jasmine2`) instead of doing things directly inside the `describe` block. Can you try that and see if it solves your issue?

**Comment by ceelian** [comment]
Unfortunately same effect with the `beforeAll()` statement. LocalStorage seems empty to the app.

Changed pseudo code:
```
describe('Private Webapp', function () {
    var mainPage = new MainPage(browser);
    
    beforeAll(function(){
         browser.get('/');
         mainPage.doLogin('testuser', 'testpwd');
    });

    describe('do authenticated tests',function(){
        beforeEach(function(){
            browser.get('/');
        });

        it('authenticated test 1', function() {
            //do and expect some stuff
        });

        it('authenticated test 2', function() {
            //do and expect some stuff
        });
    });
});
```

Protractor config:

```
exports.config = {
		seleniumAddress: 'http://localhost:4444/wd/hub',
		specs: ['test/e2e/stories/*.story.js'],
		baseUrl: 'http://localhost:8080',
		framework: 'jasmine2',
		jasmineNodeOpts: {
			// If true, print colors to the terminal.
			showColors: true
		}
	}
```

**Comment by ceelian** [comment]
Also with the following test suite layout no success.

Pseudo code type 3:
```
describe('Private Webapp', function () {
    var mainPage = new MainPage(browser);

    beforeAll(function(){
         browser.get('/');
         mainPage.doLogin('testuser', 'testpwd');
    });

    beforeEach(function(){
        browser.get('/');
    });

    it('authenticated test 1', function() {
        //do and expect some stuff
    });

    it('authenticated test 2', function() {
        //do and expect some stuff
    });

});
```

**Comment by juliemr** [comment]
I've just confirmed that localStorage does persist after `browser.get` calls, so that is not the core issue. Are you sure that the log in works properly? What is the output that makes it look like localStorage is empty?

**Comment by hankduan** [comment]
The failure is probably unrelated to localStorage being cleared. Have you tried checking that localStorage was set in the beforeAll, and that it was in fact cleared after the beforeEach?

This worked fine for me:

```javascript
describe('test', function() {
  beforeAll(function(){
    browser.get("http://www.angularjs.org");
    browser.executeScript('localStorage.setItem("foo", "bar");');
  });

  describe('do authenticated tests',function(){
    beforeEach(function(){
      browser.get("http://www.angularjs.org");
    });

    it('authenticated test 1', function() {
      var result = browser.executeScript('return localStorage.getItem("foo");');
      expect(result).toEqual("bar")
    });

    it('authenticated test 2', function() {
      var result = browser.executeScript('return localStorage.getItem("foo");');
      expect(result).toEqual("bar")
    });
  });
});
```

**Comment by ceelian** [comment]
Thank you for investigation. Finally I nailed it down with localStorage injection from the test suite which worked as you say.

In the end it was an embarrassing mistake on my side. I accidentally unchecked the "remember me" checkbox on the login page from my test cases, perfectly decoupled (hidden) in the page object. Therefore auth token was not stored in the local storage.

Shame on me and sorry for wasting your time.
