### ISSUE TITLE
Filter stack traces for Jasmine2

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1768]
Because jasmine2 default reporter does not accept a `stackFilter` (like minijasminenode used to), stack traces are not filtered for jasmine2. Should we introduce a step to do this?

**Comment by hankduan** [comment]
They fixed it here: https://github.com/jasmine/jasmine/issues/734
I'm just waiting for jasmine to release a new version now.

**Comment by juliemr** [comment]
I think there's two related issues
 - Jasmine doesn't use stack traces from errors on done.fail (jasmine/jasmine#734, https://github.com/angular/jasminewd/tree/jasminewd2)
 - Jasmine doesn't accept a `stackFilter` function (to remove lines from stack traces that we don't want) like minjasminenode did.

A new version of Jasmine will fix the first but not the second, correct?

**Comment by hankduan** [comment]
I totally misread that as jasmine2 does not accept `stackTrace`. Yup, that's right.

**Comment by hankduan** [comment]
created PR for jasmine: https://github.com/jasmine/jasmine-npm/pull/24

**Comment by hankduan** [comment]
It's merged in now: https://github.com/jasmine/jasmine-npm/commit/a0c025851374aeb7acbb046af5a78f2e0f294c47

Just need to wait for a new version of jasmine-npm

**Comment by srajagopalan1712** [comment]
I am using protractor 1.7 with framework: 'jasmine2', in my conf.js. I am seeing this. How do I get the latest fix of jasmine in my ptrotractor test. I really do not know where this is failing.

Message:
    Failed: Cannot call method 'bind' of undefined
  Stack:
    Error: Failed: Cannot call method 'bind' of undefined
        at /Users/<path>/node_modules/protractor/node_modules/jasminewd2/index.js:104:16
