### ISSUE TITLE
referenceConf.js should show 'name' in capabilities

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#1773]
When running tests on SauceLabs they all appear as 'Unnamed job'. This can be fixed by specifying 'name' within a capability.

This isn't shown in the referenceConf or https://code.google.com/p/selenium/wiki/DesiredCapabilities - might be nice to add it?

I would like to be able to pass in the build number as well. Do I need to add a node module to read in the command line params, or is there a built-in way of doing this in the config file? (as browser.params isn't available)

**Comment by sjelin** [comment]
Just to confirm, you're saying that the `name` option should be added [here](https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L109). Correct?

With respect to your question about the build number, any command line flags you pass in should make their way into the config file, which you can access via `browser.getProcessedConfig()`

**Comment by PaddyMann** [comment]
Correct. And will try `browser.getProcessedConfig()` - cheers!

**Comment by hankduan** [comment]
Please note `getProcessedConfig` will not be released until protractor 1.7. You can use it if you are using the master branch of protractor though.
