### ISSUE TITLE
Unexpected warning for "$('.class')", for multiple elements

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#1774]
Hi,

in Protractor `$()` returns one element while `$$()` returns multiple elements. I would expect `$()` to work like `$$().first()`, however it warns me about `more than one element found for locator`. I think this is a little bit unexpected, because `$()` doesn't just expects IDs. It's _normal_ to pass generic selectors like `$('.class')`.

**Comment by abazylewicz** [comment]
This warning gives you heads up that there are more elements matching your selector, so your test may be unpredictable - when you wrote $$().first() you do it deliberately, so no warning there. 

So, in my opinion warning is expected and desired, unless there is a function that throws error when more then one matching element is found.

**Comment by hankduan** [comment]
Yes, when you use `$`, it means, give me the element that matches a selector, not give me the first element that matches. That could mean `$().first()`, `$().last()`, or `$().get(n)` when there are multiple matches.

**Comment by donaldpipowitch** [comment]
Despite the warning all `$()` does is `$$().first()` or not? I think by _not_ using an ID, but a selector like `p` or `.common-class` my intention to _get one element out of multiple elements_ would be clear enough. If the user should really be prevented to query one element out of multiple elements `$()` should only accepts IDs (imo).
