### ISSUE TITLE
Test timeout depending on ordering of tasks.

### ISSUE THREAD

**Issue by M-Ismael** [angular/protractor#1775]
### I have 2 tasks inside one test.  Seems that whenever I have them in a specific order the second one fails. If I change the order they both pass.

First here's the exact message I get when a test fails:
`timeout: timed out after 30000 msec waiting for spec to complete`

A thing to note is I have `browser.ignoreSynchronization = true` in my configuration file. We are **manually bootstrapping** Angular so this seemed like a must.

Here is what my spec looks like:

```javascript
describe('Check if the homepage has products', function() {

  beforeEach( function() {
    // get to the login page before each test
    browser.get('#/home/index');
    browser.waitForAngular();
    browser.wait( function() {
      return element(by.model('user')).isPresent();
    });
    // log in
    element(by.model('user')).sendKeys( "SOMEUSER" );
    element(by.model('pass')).sendKeys( "PASSWORD" );
    element(by.buttonText('Log Me In')).click();
    element(by.linkText('Home')).click();
  });

  afterEach( function() {
    // log out
    element(by.css('div[ng-controller="Menu"]')).click();
    element(by.linkText('Log out')).click();
  });

  // NOTE: Bug in Protractor. For some reason if this test is second it fails
  it('should have at least one product', function() {
    browser.wait( function() {
      return element(by.repeater('item in stuff.resultsList')).isPresent();
    });
    var itemList = element.all(by.repeater('item in stuff.resultsList'));
    expect( itemList.count() ).toBeGreaterThan(0);
  });

  it('should navigate to the homepage', function() {
    expect( browser.getCurrentUrl() ).toMatch(/\/home\/index/);
  });

});
```

The last 2 "it" tasks are ordered this way so that they both pass. If I change the order to this, the second fails:

```javascript
  it('should navigate to the homepage', function() {
    expect( browser.getCurrentUrl() ).toMatch(/\/home\/index/);
  });

  // NOTE: Bug in Protractor. For some reason if this test is second it fails
  it('should have at least one product', function() {
    browser.wait( function() {
      return element(by.repeater('item in stuff.resultsList')).isPresent();
    });
    var itemList = element.all(by.repeater('item in stuff.resultsList'));
    expect( itemList.count() ).toBeGreaterThan(0);
  });
```

> I apologize if this issue has already been mentioned. I did my best to find a similar issue, there does seem to be a lot of flakiness with timeouts in general.

:running::dash:

**Comment by juliemr** [comment]
Is the timeout reliable (does it happen every time, or just sometimes?) Does it go away if you increase the default timeout?

**Comment by M-Ismael** [comment]
Yes it's reliable, happens every time. If I swap the 2 tasks it consistently fails. I increased the timeout and tried it again a few times looks to have the same results.

**Comment by M-Ismael** [comment]
Actually I take that last comment back. Now it's on and off, timeout is set to the default (30 seconds).  It passed twice in a row before failing again. You think it might be some sort of race condition?

**Comment by juliemr** [comment]
which task is timing out? I wonder if the `wait` for `resultList` is timing out randomly, and it just happens to have occurred when you've flipped it to run that block second.

**Comment by M-Ismael** [comment]
Yea it's always failing on the "should have at least one product" whenever that test comes second. but it seems to pretty consistently pass if it came first.

**Comment by juliemr** [comment]
Can you provide more detail about which task (not which test) is timing out? Is it during the login, or the wait for `resultList`?

**Comment by M-Ismael** [comment]
So it doesn't really tell me. The stacktrace only says `undefined`. But from the watching the test it looks like it timeouts here: `element(by.linkText('Home')).click();`

**Comment by juliemr** [comment]
Is it possible that your application has issues when logging in twice?

Sorry we can't be more helpful - I suspect that something about your application is interacting poorly with your tests - I don't think that this is a general issue with Protractor. Your code looks sane to me. I would try changing the second test to just be a copy of the first test and see if it fails then, and then commenting out the first test to just run the second, to try to pinpoint your problem further.

**Comment by M-Ismael** [comment]
Okay that's fine. I'm going through and trying to better pinpoint the exact problem. I guess before we close this issue one last thing. I noticed that the fail message I receive says this:

```
The last active task was: 
unknown
  should have at least one product - fail
```

Looks like it doesn't know what the last active task name is.

**Comment by juliemr** [comment]
Is this still relevant? Is there any general issue?
