### ISSUE TITLE
protractor-html-screenshot-reporter does not add Failed test cases to final report

### ISSUE THREAD

**Issue by sallojusuresh** [angular/protractor#1776]
Today updated my protractor version to 1.6.1 and run the my previously written test cases on latest protractor and observed  the following:
1. Failed test cases are not showing on final Report 
2. A blank page has been displayed when open Screenshots(.png) files

Note: It was working fine with my previous protractor version: 1.5.0

Can anyone help me, Thanks in advance

**Comment by juliemr** [comment]
Sounds like this is an issue for protractor-html-screenshot-reporter. Please open it up with that repository!
