### ISSUE TITLE
Pass parsed config to beforeLaunch()  function 

### ISSUE THREAD

**Issue by SebastianM** [angular/protractor#1781]
When a beforeLaunch() function is configured in the protractor configuration file, it would be very useful to get the parsed protractor configuration as a function parameter:

```js
beforeLaunch: function(protractorConfig) {
...
}
```

My current workaround is very hacky in my opinion:
```
var ConfigParser = require('protractor/lib/configParser.js');
var configParser = new ConfigParser();
configParser.addFileConfig(configFile);

var argv = optimist.parse(process.argv.slice(2));
configParser.addConfig(argv);
var config = configParser.getConfig();
```

https://github.com/angular/protractor/blob/fb099dedf92a64732d88401dd1b0d4d30b22650d/lib/launcher.js#L119

**Comment by hankduan** [comment]
Please see here for how to access config variables:
https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L197
and https://github.com/angular/protractor/blob/master/lib/runner.js#L190
Do note that this code is in master but not released yet.
