### ISSUE TITLE
Reduce calls to waitForAngular in map function

### ISSUE THREAD

**Issue by smhc** [angular/protractor#1784]
The following to query the text for each cell of a table performs a 'waitForAngular' for every cell, which is very slow for a large table.

Is it possible to only call 'waitForAngular' once when invoked via 'map' ? Is there any way to turn off the synchronisation during this iteration? Using 'ignoreSynchronisation=true' doesn't allow turning sync on and off arbitrarily mid test due to the queuing design of web driver.

```javascript
getTableText = function() {
        return element.all(by.repeater('row in rows')).map(function(rowResults) {
            return rowResults.all(by.repeater('col in cols')).map(function(cellResults) {
                return cellResults.getText();
            });
        });
    };
```

**Comment by juliemr** [comment]
We can't turn off `waitForAngular` for all calls to map, since some may modify the page and cause race conditions. We can probably do something to give better control over using `ignoreSynchronization` though.

**Comment by FuturaITLtd** [comment]
Would it be quicker to wait for the table to load then get the data via jquery? That's what we did and it reduced time to read data significantly.

**Comment by smhc** [comment]
> We can probably do something to give better control over using ignoreSynchronization though.

Yes please. A method to 'queue' the setting for ignoreSynchronization would help address the problem.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/issues/1939
