### ISSUE TITLE
Possible incorrect error message

### ISSUE THREAD

**Issue by pedrocatre** [angular/protractor#1796]
So I had a problem that I explain in [this stackoverflow post](http://stackoverflow.com/questions/28408560/protractor-tocontain-failing-when-tests-configured-with-shardtestfiles-true/28417316#28417316). It turns out I was distracted and used getText agains the result of element.all (which I knew only had one element, but still should have just gotten the 1st element out).

The thing is two strange things happened:
1) The test only failed when sharding is set to true and passed when it wasn't.
2) the error message seems incorrect to me.

Regarding my second point:

If I do this:

```javascript
var processingPathsInTable = element.all(by.repeater('processingPath in merchant.processingPaths'));
expect(processingPathListElement.count()).toEqual(1);
expect(processingPathListElement.getText()).toContain('Integration Test Acquirer Automatically generated EUR');
```

I get no error if the tests are not sharded but I get the following error if the tests are sharded:

> expect: Expected [ 'Integration Test Acquirer Automatically generated EUR,GBP,USD activated' ] to contain 'Integration Test Acquirer Automatically generated EUR'. Error: Failed expectation at null.<anonymous> (/Users/bamboo/bamboo-home/xml-data/build-dir/IOG-TESTFE61-JOB1/test/e2e/merchants/merchant/merchantMPOSSpec.js:177:69) at /usr/local/lib/node_modules/protractor/node_modules/jasminewd/index.js:94:14 at webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1640:20) at webdriver.promise.ControlFlow.runEventLoop_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1505:8) at wrapper [as _onTimeout] (timers.js:252:14) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)expect: Expected [ 'Integration Test Acquirer Automatically generated EUR,GBP,USD activated' ] to contain 'GBP'. Error: Failed expectation at null.<anonymous> (/Users/bamboo/bamboo-home/xml-data/build-dir/IOG-TESTFE61-JOB1/test/e2e/merchants/merchant/merchantMPOSSpec.js:178:69) at /usr/local/lib/node_modules/protractor/node_modules/jasminewd/index.js:94:14 at webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1640:20) at webdriver.promise.ControlFlow.runEventLoop_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1505:8) at wrapper [as _onTimeout] (timers.js:252:14) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)expect: Expected [ 'Integration Test Acquirer Automatically generated EUR,GBP,USD activated' ] to contain 'USD activated'. Error: Failed expectation at null.<anonymous> (/Users/bamboo/bamboo-home/xml-data/build-dir/IOG-TESTFE61-JOB1/test/e2e/merchants/merchant/merchantMPOSSpec.js:179:69) at /usr/local/lib/node_modules/protractor/node_modules/jasminewd/index.js:94:14 at webdriver.promise.ControlFlow.runInNewFrame_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1640:20) at webdriver.promise.ControlFlow.runEventLoop_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1505:8) at wrapper [as _onTimeout] (timers.js:252:14) at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

So:
> Expected [ 'Integration Test Acquirer Automatically generated EUR,GBP,USD activated' ] to contain 'Integration Test Acquirer Automatically generated EUR'. 

does not seem like a great message because "Integration Test Acquirer Automatically generated EUR" is actually contained in "Integration Test Acquirer Automatically generated EUR,GBP,USD activated".

Anyway the fix I used when running sharded tests was the one I accepted as the solution in the stackoverflow post, I now do:

```javascript
expect(processingPathListElement.first().getText()).toContain('Integration Test Acquirer Automatically generated EUR');
```

Also might be important to point out that other similar tests did not fail (when they were sharded and when they were not sharded).

Example that never failed:
```javascript
var processingPathsInTable = element.all(by.repeater('processingPath in merchant.processingPaths'));
expect(processingPathListElement.count()).toEqual(1);
expect(processingPathListElement.getText()).toContain('Company X0000001, ... EUR activated');
```

**Comment by hankduan** [comment]
1) Sharding has no effect on the test execution. All it does is run each test in a separate process. That being said, sharding could affect your test IF the state of your app was affected by previous tests. 

Do this: 
```
processingPathListElement.first().getText().then(console.log)
```

See if the log is 'Integration Test Acquirer Automatically generated EUR' for the unsharded test, but 'Integration Test Acquirer Automatically generated EUR,GBP,USD activated' for the sharded test. If that is the case, see if a PREVIOUS test in the unsharded test case is affecting the state of your app. 

2) `expect(a).toContain(b)` checks if `a` contains `b`. If `a` is an array, it checks if `b` is an element of that array. If `a` is a string (i.e. array of char), it checks if `b` is a substring of that string. 

`expect(['abcd', 'efgh']).toContain('abc')` should fail because 'abc' is not an element of the array ['abcd', 'efgh']. 

Whereas `expect('abcd').toContain('abc') would pass because 'abc' is a substring of 'abcd'. 

The error message should be good as is.

**Comment by pedrocatre** [comment]
1) I do know that sharding should have no effect. I also don't see where the state of my app could have been affected by previous tests. But I will recheck this.

2) Makes sense! Thank you. It was actually staring me right in the face. That explains why the other tests don't fail since there I don't use part of the string on the contains but the entire string, so it returns true because it is one of the elements of the array.

I assume for now that 1) it is a mistake on my part since the second point clearly was (and it was also my main point). I will close the ticket so not to waste your time and resources.

Thank you for your help.
