### ISSUE TITLE
Cucumber Coffee: properly expose By selectors

### ISSUE THREAD

**Issue by Phoscur** [angular/protractor#1801]
I'm not a fan of global variables, but this seems an easy way defining the steps.
Coffeescript has "by" as a reserved word, so that global is not accessible, "By" is not reserved.

Solution: export both as by and By

Workaround: Add ```By = protractor.By``` in coffee step files

**Comment by hankduan** [comment]
This is already the case: https://github.com/angular/protractor/blob/master/lib/runner.js#L159
