### ISSUE TITLE
Docs: add anchors to sections, apply header offset for sections

### ISSUE THREAD

**Issue by cesarandreu** [angular/protractor#1806]
Two usability improvements suggestions for the docs:

1. Add anchor link to sections. [Github](https://www.dropbox.com/s/06c3hszx5jat0tb/Screenshot%202015-02-12%2012.35.28.png?dl=0) does this. 

2. Apply header offset on anchor links. For example, if you link to [How to deal with my log-in page?](http://angular.github.io/protractor/#/faq#how-do-i-deal-with-my-log-in-page-), it will [cover](https://www.dropbox.com/s/05ydtctjvot6jkn/Screenshot%202015-02-12%2012.48.04.png?dl=0) the section. This is [easily solved](http://fellowtuts.com/html-css/offsetting-anchor-hash-tag-links-to-adjust-for-fixed-header/) by using the :before css selector and setting a height with a negative margin.

**Comment by juliemr** [comment]
This is done with the commits above.

**Comment by cesarandreu** [comment]
Awesome! Thanks, I think this really helps usability.

**Comment by avdd** [comment]
The character used for this (&#x1f517;) is not visible on Ubuntu 14.04.

**Comment by sjelin** [comment]
@avdd I am using Ubuntu 14.04, and is is visible
