### ISSUE TITLE
Problem with browser.getLocationAbsUrl()

### ISSUE THREAD

**Issue by rabbitjar** [angular/protractor#1812]
I'm using `browser.getLocationAbsUrl()` throughout the tests when the page being tested is changed. I haven't got any issues until now. For this particular page I'm getting the following error.

Simplified test code:
```
describe('Test', function() {

    it('Access url', function() {

        browser.get('#/subjects/subject:Sample/jobs/job:Sample:Job/tasks');
        expect(browser.getLocationAbsUrl()).toMatch("http://localhost:9080/#/subjects/subject:Sample/jobs/job:Sample:Job/tasks");

    });

});
```
Error message:
```
Expected 'http://localhost:9080/#/subjects/subject:Sample/jobs/job:Sample:Job/tasks' to match 'http://localhost:9080/#/subjects/subject:Sample/jobs/job:Sample:Job/tasks'.
```

The `baseUrl` is set to `http://localhost:9080`. I'm using latest protractor (v1.6.1). 

Any tips?

**Comment by juliemr** [comment]
You probably want 'toEqual' instead of 'toMatch' - 'toMatch' is trying to convert to a regular expression and causing your issues.

**Comment by rabbitjar** [comment]
Thank you!
