### ISSUE TITLE
set base url

### ISSUE THREAD

**Issue by edin-m** [angular/protractor#1816]
If we have some route:
```
/campaigns/:campaignId
```

which has many subroutes
```
/campaigns/:campaignId/tab1
/campaigns/:campaignId/tab2
/campaigns/:campaignId/tab3
```
it would be good if we could do something like

test 1:
```
// create campaign
browser.setLocation('campaigns/create')
....
```

test 2:
// browser getCurrentUrl() is now /campaigns/:campaignId
we must say:
```
browser.setLocation('/campaigns/:campaignId/tab1')
browser.setLocation('/campaigns/:campaignId/tab2')
```
but :campaignId is difficult to track (since it is fetched with XHR and is json, and is not present in html so it is not retrievable with any selectors)

it would be better to do something like
browser.baseUrl = 'http://whatever/campaigns/:campaignId' // which may be getCurrentUrl()

and subsequent calls would be:
```
browser.setLocation('tab1')
browser.setLocation('tab2')
```
This makes much more sense with Page Objects. I have searched for some feature like this - setting absolute url, setting base url, etc but I was unable to find anything helpful.

**Comment by juliemr** [comment]
`baseUrl` is just a property of `browser`, you can just go ahead and set it as you showed. Please file a new issue if you're still seeing problems!
