### ISSUE TITLE
Appium-Protractor for native iOS apps

### ISSUE THREAD

**Issue by gpmishra** [angular/protractor#1819]
I have designed appium framework for iOS app automation. Now we need to use protractor with it. I have heard about appium-protractor bridge.

Please suggest how we can proceed.

**Comment by hankduan** [comment]
Here are the instructions: https://github.com/angular/protractor/blob/master/docs/mobile-setup.md.

**Comment by hankduan** [comment]
Sorry I might have misread your post. Are you talking about testing safari on iOS (i.e. webdriver test) or testing general native apps on iOS? If you're talking about the latter, protractor does not support it.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/issues/1940
