### ISSUE TITLE
Chrome not firing by default through the webdriver-manager

### ISSUE THREAD

**Issue by Lornz-** [angular/protractor#1823]
Hi there,

I'm a newbie in e2e tests with protractor and I've recently encountered an issue. When I try to run my test (which is basically the same one I found on the official protractor website), the server starts by using Firefox as a default browser. As I read, chrome supposed to be the one used by default. 
```
16:17:24.345 INFO - Executing: [new session: Capabilities [{count=1, browserName=firefox}]])
16:17:24.345 INFO - Creating a new session for Capabilities [{count=1, browserName=firefox}]
16:17:27.305 INFO - Done: [new session: Capabilities [{count=1, browserName=firefox}]]

```

Due to the Firefox issue [#1734](https://github.com/angular/protractor/issues/1734), the test fails all the time 

```
Failures:

  1) angularjs homepage todo list should add a todo
   Message:
     timeout: timed out after 36000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 36.777 seconds
1 test, 1 assertion, 1 failure

```
So I added chrome as another browser to use into the configuration file 

**conf.js**

```javascript
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',      
  capabilities: {
   browserName: 'chrome'
  },
  specs: ['todo-spec.js'],
  framework: 'jasmine'
};
```

Here's the test 

**todo-spec.js**

```javascript
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('http://angularjs.org');

    element(by.model('todoText')).sendKeys('write a protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write a protractor test');
  });
});
```
But it still does not work. What am I doing wrong here? 

Thanks for your help!

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
