### ISSUE TITLE
"data:," in address bar and tests don´t run - Chrome

### ISSUE THREAD

**Issue by MarkusPint** [angular/protractor#1825]
I just started trying Protractor and can't get it running.

I followed the tutorial on protractortest.org

First I launched the selenium server with: webdriver-manager start.
Then I used "protractor protractor.conf.js", which results in a new Chrome being opened with "data:," in the address bar. Nothing else happens after that.

In the selenium terminal window I see stuff like:
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException

All help appreciated.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
