### ISSUE TITLE
not able to set firefox profile with directConnect enabled 

### ISSUE THREAD

**Issue by geedubey** [angular/protractor#1826]
I am using example available at below URL Demo-samples to set Firefox profile (for few security and Proxy) 
https://github.com/juliemr/protractor-demo/tree/master/howtos/setFirefoxProfile

it is working fine when I am invoking firefox through selenium server, but i am getting below error when i am trying to use Firefox directly using directConnect.

Error: browserName (undefined) is not supported with directConnect.
    at DirectDriverProvider.setupEnv (D:\Program Files\Node\node_modules\protractor\lib\driverProviders\direct.js:37:13)
    at Runner.run (D:\Program Files\Node\node_modules\protractor\lib\runner.js:252:31)
    at TaskRunner.run (D:\Program Files\Node\node_modules\protractor\lib\taskRunner.js:123:19)
    at createNextTaskRunner (D:\Program Files\Node\node_modules\protractor\lib\launcher.js:160:20)
    at D:\Program Files\Node\node_modules\protractor\lib\launcher.js:183:7
    at _fulfilled (D:\Program Files\Node\node_modules\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (D:\Program Files\Node\node_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (D:\Program Files\Node\node_modules\protractor\node_modules\q\q.js:759:13)
    at D:\Program Files\Node\node_modules\protractor\node_modules\q\q.js:525:49
    at flush (D:\Program Files\Node\node_modules\protractor\node_modules\q\q.js:108:17)

further directConnect is working fine without firefox profile setting.

please suggest any solution to me.

**Comment by hankduan** [comment]
Are you using protractor 1.6 or above? If so, you need to change your conf.js and helper like what I did here: https://github.com/juliemr/protractor-demo/pull/15

**Comment by geedubey** [comment]
@hankduan , i am using protractor 1.7 , I did changes as per repository ,  i am not getting any error now but instead of FIREFOX , CHROME is getting invoked , any Suggestion.

**Comment by hankduan** [comment]
Can you do --version on protractor? And are you running the demo as is (with the PR patch)?

**Comment by geedubey** [comment]
Protractor version --
D:\Xperiments\Protractor>protractor --version
Version 1.7.0

here is Conf.js used ,  Remeber " I am trying directConnect feature and  firefox profile ".

var helper = require('./helper.js');
exports.config = {
  directConnect: true,
  firefoxPath : 'D:\\Xperiments\\Protractor\\Firefox34\\firefox.exe',
  specs: [
    'spec.js'
  ],
  getMultiCapabilities: helper.getFirefoxProfile()  
};

here is helper.js  used

var q = require('q');
var FirefoxProfile = require('firefox-profile');

exports.getFirefoxProfile = function() {
  var deferred = q.defer();

  var firefoxProfile = new FirefoxProfile();
  firefoxProfile.setPreference('browser.newtab.url', 'https://www.angularjs.org');
  firefoxProfile.setPreference('security.warn_entering_secure', true);
  firefoxProfile.encoded(function(encodedProfile) {
    var multiCapabilities = [{
     browserName: 'firefox',
      firefox_profile : encodedProfile
    }];
    deferred.resolve(multiCapabilities);
  });

  return deferred.promise;
};

waiting for suggestion.........

**Comment by hankduan** [comment]
You didn't copy the demo conf properly. Should be
```
getMultiCapabilities: helper.getFirefoxProfile
```

i.e. getMultiCapabilities takes a function that returns a promise, not a promise

**Comment by geedubey** [comment]
Sorry my mistake ,  now firfox is getting launched but facing new issue .  now  firefox profile is not effective ie.  opening new tab  is not opening https://www.angularjs.org as it should after setting profile with firefoxProfile.setPreference('browser.newtab.url', 'https://www.angularjs.org');
I am on win 7 , Firefox 34.
any help??

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by nishankkumar1994** [comment]
Please make sure to install
`npm install protractor`

Update web driver manager
`webdriver-manager update`

Run this command from your root
`node node_modules\protractor\bin\webdriver-manager update`

Now start up a server with:
`webdriver-manager start`

Also make sure that your protractor.conf.js file has below line
`// baseUrl: 'http://localhost:4200/',`
 ` seleniumAddress: 'http://localhost:4444/wd/hub/',`


Now run your e2e tests on different browesers
`ng e2e`
