### ISSUE TITLE
How to check that element is NOT displayed in protractor?

### ISSUE THREAD

**Issue by iljapavlovs** [angular/protractor#1827]
Actually, I cannot find any normal way to do this. Since an element is not displayed, an Exception is thrown. How to workaround this?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by Biptor** [comment]
Please @juliemr, if you know the answer, share it, we need to be more effective with the answers and not run to close the cases with bureaucratic phrases

**Comment by Biptor** [comment]
hi @iljapavlovs 

I'm facing the same problem and I can't found a solution, even I used a try catch segment but still the exception appears and my test fall to broken

Thanks
