### ISSUE TITLE
Global step definitions undefined for *.feature files in sub-directories

### ISSUE THREAD

**Issue by BevanR** [angular/protractor#1828]
As a BDD test suite grows it is useful to group related feature files in directories.  E.g.

```
features/
    homepage.feature
    legal.feature
    contact.feature
    user/
        login.feature
        reset.feature
        register.feature
    content/
        create.feature
        publish.feature
        delete.feature
```

This works fine with something like `exports.config.specs: ['features/*.feature', 'features/*/*.feature']`.

1. **Feature request**: It would be nice if it would work with globs like `exports.config.specs: 'features/**.feature'`.
2. **Bug**: To focus on a specific test, it is useful to specify a single feature file.  E.g. `exports.config.specs: 'features/user/login.feature'`.  This fails.  All global step definitions are undefined. Protractor appears to be looking for `step_definitions/global.js` relative to `features/user/` instead of `features/`.

I have two ideas for possible solutions:

1. Assume `global.js` (and `world.js`?) are located relative to the current directory or relative to the configuration file, instead of a feature file.
2. Allow `global.js` (and `world.js`?) to be specified in the configuration.  Or if it is already possible, document how.

**Comment by sjelin** [comment]
Closing this because we split cucumber off with https://github.com/angular/protractor/pull/2710
