### ISSUE TITLE
element explorer not listens on port 4444 and it listens on random port

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#1834]
I installed the latest version of protractor and tries to start the element explorer and it tries to listens on random port. It's not listening on 4444. 

Ran this command:
./node_modules/protractor/bin/p
![screen shot 2015-02-20 at 17 22 17](https://cloud.githubusercontent.com/assets/6057889/6305726/3e3581dc-b925-11e4-81ff-02198df1c5b1.png)
rotractor --elementExplorer

**Comment by hankduan** [comment]
You can pass the port to it like '--seleniumAddress http://localhost:4444'

**Comment by smahalingam** [comment]
Thanks @hankduan. Below works, 
./node_modules/protractor/bin/protractor --seleniumAddress http://127.0.0.1:4444/wd/hub --elementExplorer
