### ISSUE TITLE
Protractor with Hybrid App

### ISSUE THREAD

**Issue by csharsha** [angular/protractor#1837]
Hi,

I have an hybrid app with AngularJS and IBM Worklight adapters which works on Andriod Webview and not on Mobile browser. Is it possible to use Protractor with Android WebView. If yes, please help me with the steps.

Thanks

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
