### ISSUE TITLE
does protractor supporting angularjs version 1.0.7

### ISSUE THREAD

**Issue by ekarudianto** [angular/protractor#1838]
as the subject says... that is the question that I would like to ask.. I've read in the documentation here
http://angular.github.io/protractor/#/faq

that "Protractor supports angular 1.0.6/1.1.4 and higher - check that your version of Angular is upgraded."

so just to confirm is Protractor also support the 1.0.7 version ?

**Comment by ericmdantas** [comment]
We have this project that uses the version 1.0.7 and when I tried to run the e2e tests with protractor, it didn't work. The tests just wouldn't run. And then, when I updated angular, it'd work like a charm.

By the way, this is a bit weird:

> Protractor supports angular 1.0.6/1.1.4 and higher - check that your version of Angular is upgraded.

To me it says: version 1.0.6 is supported, everything until 1.1.3 is **not** supported, and everything after 1.14 is supported again.

**Comment by juliemr** [comment]
Angular was on two release tracks, so that 1.0.x was a separate track from the unstable track, 1.1.x. This is why the versioning is a bit weird :)

But yes, version 10.7 should be supported. If you're having a specific issue, please reproduce a minimal case and file a new issue. Thanks!

**Comment by ericmdantas** [comment]
That's nice, to know.

When I get back to this specific project I'll give it a try again and let you know if something fails.

Thanks!

**Comment by ekarudianto** [comment]
I see thanks for answering my question!
