### ISSUE TITLE
Custom binaries url for webdriver manager 

### ISSUE THREAD

**Issue by noamokman** [angular/protractor#1839]
Hi there,
I wanted to implement a simple option on the webdriver manager.
Add the ability to specify an alternate cdn to the required binaries (IEDriver, chromedriver, selenium-server-standalone).
Similar to what [Phantomjs](https://github.com/Medium/phantomjs#custom-binaries-url) did.
 
Should I PR?

Thanks,
Noam.

**Comment by juliemr** [comment]
Yes, this sounds reasonable - make sure the method to switch is well documented and easy to use, and it sounds good to me.
