### ISSUE TITLE
Not finding multiple ng-repeat='foo' on a page

### ISSUE THREAD

**Issue by ChuckKollar** [angular/protractor#1840]
I am writing E2E tests for an application that (from the user's perspective) displays a table with different data depending on the state of a button. This is implemented by placing the one table in a
```
<div id="div A" ...
```
and another in a
```
<div id="div B" ...
```
(for example). Each of these divs has some code that displays the table that uses something like...
```
<tr ng-repeat="row in table" ... 
```
There is a button on the page that "toggles" which div '.isDisplayed()', but that's not important for this discussion.

So, Protractor appears to be good about returning an array in the case where it finds multiple associations with the same label of the same thing. But in this case it seems to only return the one that appears second in the 'page source', and looses the first.

When I verify that "div A" is displayed I use some code that looks like this...
```
element.all(by.repeater('row in table')).filter(function(row, index) {
   return row.evaluate('row.title').then(function(title) {
      console.log(title + ' index: ' + index);
      });
   });
```
and it happily shows me the titles of the data that would appear in the table for "div B".
In theory something like this which selects the first 'by.repeater' on the page should work...
```
element.all(by.repeater('row in table')).get(0).filter(function(row, index) {
```
but I get the error message..
```
TypeError: Object [object Object] has no method 'filter'
```
which likely indicates that only one of the 'ng-repeat=' entries is being kept from the page and the first one is being thrown away.

Any help would be greatly appreciated.

Sincerely,
Charles

**Comment by ChuckKollar** [comment]
Ooops... it looks like this works...
```
  element(by.id('div A')).all(by.repeater('row in table')).filter(function(row, index) {
```

**Comment by juliemr** [comment]
Sounds like this is fixed!

**Comment by ChuckKollar** [comment]
Yes! Thank you for looking!
