### ISSUE TITLE
Locator docs CSS could be clearer

### ISSUE THREAD

**Issue by mryellow** [angular/protractor#1849]
https://github.com/angular/protractor/blob/master/docs/locators.md

From example to example it switches from `by.css('.myclass')` to `by.css('some-css')`.

It doesn't really seem to explain what the actual locator does, wrongly assumed it targets classes. An example that includes HTML tags, `h1.class` or something would clear this up.

**Comment by hankduan** [comment]
Is this really necessary? by.css follows normal css selector syntax, and it's not defined by protractor.

**Comment by juliemr** [comment]
Agreed. Closing.
