### ISSUE TITLE
Unable to Fetch the Growl Message if we have an interval to get hide after 5 sec

### ISSUE THREAD

**Issue by RashmiChauhan** [angular/protractor#1851]
1. I am writing test cases in protractor E2E.
2. I want that when I run the case, and when I press save, then a Growl message is shown with success or error.

this.growlMessage = function (){
		return element(by.css("div[ng-bind='message.text']")).getText();}

3. Now I am able to fetch the message if we are having error because it stays there as long it is closed.
4. But the success message disappears after some time automatically.

In Protractor, the case keeps waiting for the Growl to disappear and then perform the next execution. I think protractor is waiting for the growl to finish it work. 

How can we wait for this and get the text ?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
