### ISSUE TITLE
Chrome doesn't start or pop up

### ISSUE THREAD

**Issue by c0debreaker** [angular/protractor#1861]
I'm wondering why Chrome application doesn't show when I start testing. The test do work though. When I change setting to Firefox, it will show the Firefox application.

Is this a normal behavior?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
