### ISSUE TITLE
Cannot Check If Element Doesn't Exist

### ISSUE THREAD

**Issue by mboudreau** [angular/protractor#1869]
I've looked through everything and tried it all.  Every time I try to get an element based on css, I always get the same error:

```
Message:
    Failed: No element found using locator: By.cssSelector(".section.opened")
  Stack:
    Error: Failed: No element found using locator: By.cssSelector(".section.opened")
        at /home/michelb/Work/form-runner/node_modules/jasminewd2/index.js:104:16
        at /home/michelb/Work/form-runner/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
        at [object Object].webdriver.promise.ControlFlow.runInNewFrame_ (/home/michelb/Work/form-runner/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
        at notify (/home/michelb/Work/form-runner/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
```

I've tried:

```
element(by.css('.section.opened)).isPresent();
element(by.css('.section.opened)).isDisplayed();
element.all(by.css('.section.opened)).count() === 0;
$('.section.opened').count() === 0;
$$('.section.opened').count() === 0;
browser.isElementPresent(by.css('.section.opened')).then(...);
browser.findElements(by.css('.section.opened')).then(...);
browser.driver.isElementPresent(by.css('.section.opened')).then(...);
...
```

You get the point.  I've tried every single permutation without any luck.  I just want to make sure that .section.opened is not there since I've closed it.  It always gives me the same error.

This is using Protractor 1.7.0, Selenium Web Driver 2.44.0, Chromedriver 2.14.1, Jasmine 2.2.1.  I'm not sure if this is bug since I've seen some stackoverflow answers mention what I've tried above, but I simply cannot get anything to work for me without creating an error.

**Comment by mboudreau** [comment]
Disregard.  Seems like it was a line before that was giving the issue:

```
expect(section.evaluate('isOpen')).toBeFalsy();
```

section being `element(by.css('.section.opened'))`.

**Comment by damiangreen** [comment]
Also hit the same issue. What was the solution?

**Comment by makwanaparth94** [comment]
Requirement is: If elements exist on web page then Test case failed .

Currently i am able to find the element is present through protractor but not getting any idea that how to failed that test cases 

Help me
