### ISSUE TITLE
Experienced Error: spawn ENOENT on Windows 8 Node v0.10.18

### ISSUE THREAD

**Issue by ettysekhon** [angular/protractor#187]
I created some tests and they worked fine on my mac. On my Windows 8 machine  it generated an error spawn child ENOENT error. This is because java was not installed on the machine (which is required by selenium standalone) and there was no system path environment variable to the java bin directory. I installed java and added system path environment variable to the java bin directory which resolved the issue. Could be worth adding this in the readme.

**Comment by yesobo** [comment]
chromeOnly:true was the solution for me as well, thangs @warrensearle

**Comment by srizvi1** [comment]
chromeOnly: true,

did not work for me. So I am still trying to understand the issue and how will it get resolve the ELIFECYCLE error. 

I noticed that when I run like "./node_modules/.bin/protractor e2e-tests/protractor.conf.js" the error does not come. but when I run using "npm run protractor" the errors come. 

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srizvi/IdeaProjects/protractor/pna-functionaltest-protractor/npm-debug.log

the npm-dubg.log is as follows.

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'protractor' ]
2 info using npm@2.5.1
3 info using node@v0.12.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-seed@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-seed@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-seed@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid angular-seed@0.0.0
12 verbose cwd /Users/srizvi/IdeaProjects/protractor/pna-functionaltest-protractor
13 error Darwin 14.0.0
14 error argv "node" "/usr/local/bin/npm" "run" "protractor"
15 error node v0.12.1
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error angular-seed@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 error Exit status 1
19 error Failed at the angular-seed@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
19 error This is most likely a problem with the angular-seed package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor e2e-tests/protractor.conf.js
19 error You can get their info via:
19 error     npm owner ls angular-seed
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

Any help will be appreciated.

**Comment by iwarner** [comment]
Ditto to the last message I still get this issue

**Comment by srizvi1** [comment]
don't waste time on this technology. No proper documentation, No proper steps for people setting up in for the first time, No community help. And the best part that errors are very helpful. ELIFECYCLE looks like a new movie name from Marvel.

**Comment by nmehta6** [comment]
I am getting this error as well. I tested on OSX with the same config and works fine. I am trying to target phantomjs.

**Comment by robertpateii** [comment]
chromeOnly didn't work for me either. I had to add the java bin directory to my path for it to work.
