### ISSUE TITLE
Question about .map()

### ISSUE THREAD

**Issue by hokkaido** [angular/protractor#1879]
As far as I can see, calling an ElementArrayFinder's map() function automatically resolves any underlying promises.

    it('should work', function() {
    
      var ListElement = function(el) {
        this.foo = el.element(by.css('span.foo'));
        this.bar = el.element(by.css('span.bar'));
      };    

      var matches = element.all(by.css('li')).map(function(el) {
        return new ListElement(el);
      });
    
      browser.get('/mypage/'); 
    });

This immediately triggers an error,`"No element found using locator: By.cssSelector("span.foo")"`, before visiting the page.

I think this is a bit counter-intuitive, especially when considering the documentation for .map() and the general behaviour of calls to .get(), .first() and so on. It's also hard to apply a decent page object pattern with a larger code base. Is there a reason why we can't wait with the resolution here? I.e. only resolving the underlying ElementFinders (foo and bar and their parents) when we actually use them?

**Comment by juliemr** [comment]
Labeling as needs investigating to figure out what should be done here - I think of `map` as a form of `get`, which means that it should actually go through and get the element, but I can see how that would be counterintuitive.

**Comment by hankduan** [comment]
I think this is consistent.
Map does not (necessarily) return element finders, as it could return anything (text/numbers/objects/etc). So if you have something like

```javascript
var result = element.all(by.xyz).map(function(el) {
  return el.getText();
})
result.then(function(resolved) {
  console.log(resolved);
})
```

When would we actually retrieve the element? At `map` or at `then`? We chose to resolve at `map` because otherwise it would be inconsistent with the normal case:

```javascript
var result = element(by.xyz).getText();
result.then(function(resolved) {
  console.log(resolved);
})
```

which resolves at the `getText()`.

**Comment by hokkaido** [comment]
I see how it's consistent with calls to getText(), unfortunately the opposite is true for ElementFinders and objects that encapsulate them inside the map function. 

I think it would be worthwhile to highlight this in the documentation?

**Comment by n2liquid** [comment]
My 2 cents: I think `.get()` is *also* very counterintuitive for the same reason. Shouldn't the current behavior be invoked with something like `.getWebElement(index)` instead? If you have a single element and you want to actually grab the element right away, you use `.getWebElement()`, right? So having the same function do something similar for a group of elements seems natural to me.

**Comment by juliemr** [comment]
@n2liquid not quite. `ElementFinderArray.get(index)` returns an `ElementFinder`, whereas `ElementFinder.getWebElement` returns a `WebElement`.

**Comment by n2liquid** [comment]
Hmm, so I thought the whole point of `ElementFinder` was precisely to postpone actually finding an element, but apparently it also has an API which is useful even when the element has already been found? I feel like I may be making a really huge confusion, but it kind of makes sense... :)

**Comment by juliemr** [comment]
This has been open for a while, and I don't see a compelling reason to change `map`. Closing for now.
