### ISSUE TITLE
Main Global variable state (it's value)

### ISSUE THREAD

**Issue by singh-gurpreet** [angular/protractor#1882]
I am running Selenium Grid for Protractor test executions. For that I am reading data from Excel. Now for each test case it reads the data from Excel, because on test case execution even global variables aren't persisting their old values. 
Is there a way I can declare some variable and that can be accessible across all test case executions without losing it's value. I already tried Params, Browser nothing worked. They don't have any value over when next test file get executed:
1. onPrepare
2. beforeEach
Note: Each test case is in different file.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by singh-gurpreet** [comment]
Hello Julie,
Thanks, but I think I wasn’t clear in that description:
So here is the thing, declare a global variable run one test case file and you are fine nothing wrong it persists values. Now enable sharedfiles = true, it will start losing global variable values. So I think we can do something about it. If not that is also fine as am not Protractor expert. But I like it a lot good work you guys thanks ☺

Thanks and Regards
Gurpreet Singh
