### ISSUE TITLE
Mocked module isn't called with Protractor 1.8

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#1883]
On 1.6.x I used a mocked module like this:

````
  onPrepare: function() {
    browser.addMockModule('myApp', function() {
      console.log('hello');
      angular.module('myApp').config(function config(MockApiProvider) {
        MockApiProvider.enabled(true);
      });
    });

    console.log('waiting for session...');
    return browser.driver.getSession()
      .then(function() {
        return browser.driver.manage().window().maximize();
      }).then(function() {
        console.log('...session acquired.');
      });
  },
````

It looks like this doesn't work after my update to 1.8. `'hello'` never appears in the console.

````
    // inside onPrepare
    console.log('waiting for session...');
    return browser.driver.getSession()
      .then(function() {
        return browser.driver.manage().window().maximize();
      }).then(function() {
        return browser.get('#').then(function() {
          browser.executeScript('// custom logic to enable my MockApiProvider (needs to be persisted in session storage, so it is used in every following browser.get)');
        });
      }).then(function() {
        console.log('...session acquired.');
      });
````

**Comment by juliemr** [comment]
I tried running your example against 1.8, and I do see 'hello' logged in the browser console. Can you make a test case which reproduces your error in https://github.com/angular/protractor/blob/master/spec/basic/mockmodule_spec.js?

**Comment by donaldpipowitch** [comment]
I'm back to 1.6.1 and the problem still exist. Very strange. I currently don't know what I could have changed besides the Protractor version... I'll continue to look for the reasons...

**Comment by donaldpipowitch** [comment]
I'm not sure if this is a problem with Protractor, Selenium, ui-router or something else, but the problems occurs because of a reload which happens, if we use `browser.get('#');` instead of `browser.get('#/');`.  Closing this for now.
