### ISSUE TITLE
Alias ElementArrayFinder.prototype.each to forEach

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#1884]
Minor API enhancement: I intuitively tried to use `forEach` on an ElementArrayFinder instance an got `undefined is not a function` so I thought there was no "forEach"-functionality for ElementArrayFinder which seemed weird as it has `filter`, `map`, etc. It turns out there is a "forEach"-functionality and that the functions is called `each`. It would be nice to introduce an alias here to match an API which is similar to native `Array`.

**Comment by juliemr** [comment]
I'm a bit wary of introducing an API that is very similar to native arrays, and making devs think that `ElementArrayFinder` is actually just an array. Then they could be very frustrated when it isn't, and they find subtle errors. I'm open to other opinions though, so leaving this open for discussion.

**Comment by donaldpipowitch** [comment]
I don't know what others think about this, but because of `filter` and `map` I already think this would be Array-like and it is more an Array than something else.

But I do understand your suspicion. One could argue to rename `count()` to `length()` or `getLength()` to be more inline with a native Array API - but on the other hand `count()` behaves clearly different from Arrays `length` while ElementArrayFinders `each()` is quite the same as Arrays `forEach()`.

**Comment by juliemr** [comment]
Hi, this has been open for a while, and I don't see a convincing reason to change. You can always alias yourself if it's a big problem for you.
