### ISSUE TITLE
Can't waitForAngular() with jasmine2

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#1885]
Using `framework: 'jasmine2',` the following code snippet throws `Failed: Timed out waiting for Protractor to synchronize with the page after 0 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
        at /my-app/node_modules/protractor/node_modules/jasminewd2/index.js:104:16`:

````
describe('My apps navigation bar', function() {
  var page = {
    navigationBarItems: $$('.e2e-navigation-bar-items')
  };

  beforeEach(function() {
    browser.get('#');
    browser.waitForAngular();
  });

  it('should let me navigate to all states', function() {
    page.navigationBarItems.each(function(navigationBarItem) {
      navigationBarItem.click();
      browser.waitForAngular();
      expect(navigationBarItem.getAttribute('class')).toContain('e2e-navigation-bar-active-item');
    });
  });
});
````

No problem with `framework: 'jasmine',`.

**Comment by juliemr** [comment]
The timeout of 0 seconds seems suspect to me. Are you setting a timeout somewhere in your config?

**Comment by donaldpipowitch** [comment]
No, I don't change the default settings for timeouts.

I don't know if this is related to `browser.waitForAngular();` somehow? I didn't need this sometime before.  Between `navigationBarItem.click();` and `expect(navigationBarItem.getAttribute('class')).toContain('e2e-navigation-bar-active-item');` should just be some `$timeout`.

**Comment by juliemr** [comment]
You should still not need to manually do a `browser.waitForAngular`. What happens when you remove it?

**Comment by juliemr** [comment]
Haven't heard any updates in a while, so I'm closing this issue as stale. Please open a new issue if you think there is a remaining general problem.
