### ISSUE TITLE
Visual Studio 2013 intellisense

### ISSUE THREAD

**Issue by chaossepp** [angular/protractor#1886]
Hey, not sure if this is the right place to ask, but can someone of you help me getting intellisense for protarctor functions working? Would be nice if my IDE suggest functions like 'model' eg element(by.model).
I already referenced all *.js files that come with protractor.
Do I miss something?
Thx for your help!

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
