### ISSUE TITLE
browser.pause() crashes

### ISSUE THREAD

**Issue by cacrookes** [angular/protractor#1893]
Hi, I seem to have protractor working fine, unless I use a browser.pause() statement. When it hits the pause, it tells me "Debugger listening on port 5858", but nothing after that. No debugger interface. And no commands work, although ^c quits the process. It does pause the Chrome browser, however it is blank, and in the address bar it says "data:,". I've also tried using Firefox, with the same result except the browser address bar is blank. I have the same problem using both mocha and jasmine.

I am running Mac OS 10.10.2, and protractor 1.8.0.  

Here is my protractor.conf.js:
```javascript
exports.config = {
    specs: [
        'test/e2e/**/*.spec.js'
    ],
}
```

and my spec file
```javascript
describe('foo', function(){
  it('bar' function(){
    browser.get('http://www.angularjs.org');
    browser.pause();
    $('html').getText().then(console.log);
  });
});
```

It runs fine if I comment out the browser.pause() line.

My output running protractor --troubleshoot is:
```
⇒  protractor --troubleshoot
DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 1.8.0
DEBUG - Your base url for tests is undefined
DEBUG - Attempting to find the SeleniumServerJar in the default location used by webdriver-manager
DEBUG - Attempting to find the chromedriver binary in the default location used by webdriver-manager
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.1.102:57351/wd/hub
DEBUG - WebDriver session successfully started with capabilities { caps_:
   { applicationCacheEnabled: false,
     rotatable: false,
     mobileEmulationEnabled: false,
     chrome: { userDataDir: '/var/folders/n2/5qxzhv2904l2flzqj4wdlyvm0000gn/T/.org.chromium.Chromium.a5g4Eb' },
     takesHeapSnapshot: true,
     databaseEnabled: false,
     handlesAlerts: true,
     version: '40.0.2214.115',
     platform: 'MAC',
     browserConnectionEnabled: false,
     nativeEvents: true,
     acceptSslCerts: true,
     'webdriver.remote.sessionid': '365da574-1948-4b75-9ca4-722eb9c84237',
     locationContextEnabled: true,
     webStorageEnabled: true,
     browserName: 'chrome',
     takesScreenshot: true,
     javascriptEnabled: true,
     cssSelectorsEnabled: true } }
Starting debugger agent.
Debugger listening on port 5858
```

**Comment by hankduan** [comment]
What's your version of node?

**Comment by cacrookes** [comment]
node is v0.12.0

**Comment by hankduan** [comment]
ah yes. So apparently node has changed their 'debugger' module several times since v0.10.30.

Namely v0.10.31 causes significant delays when you use element explorer/pause (see https://github.com/angular/protractor/issues/1890)
and v0.12.0 simply breaks element explorer/pause

The first issue I've filed a bug against node (again, see issue). The second issue, I am currently fixing; but even after I fix it, elementexplorer/pause is still unusable with the delay. 

The only workaround I can think of right now is use node 0.10.30 or earlier.

**Comment by cacrookes** [comment]
Thanks, switching to node 0.10.30 works.

**Comment by shicholas** [comment]
:+1: I was using .12 then had to revert to .10 for the same issue.
