### ISSUE TITLE
element.click() is not passed to children on Firefox

### ISSUE THREAD

**Issue by Jenselme** [angular/protractor#1896]
In my application, I have images within divs. When an image is clicked, its position should change. I have a test in protractor for that. Here is the HTML:
```
<div ng-repeat="card in currentPlayerCards" class="movementsCardContainer">
    <img class="movementsCard"
        ng-class="{selectedCard: isSelected(card.name, card.color)}"
        ng-click="viewPossibleMovements(card.name, card.color)"
         ng-src="/inc/img/cards/movement/{{card.name| lowercase}}_{{card.color| lowercase}}.png"
    />
</div>
```
If I select the elements with `var cards = element.all(by.repeater('card in currentPlayerCards'))` and then click on the first card (`cards.get(0).click()`) nothing happen on firefox. However, this works fine in chrome.

I can work around the problem by using `$$('.movementsCard')` but I still think that the click event should be passed to the elements contained by the div.

- Protractor: 1.8.0
- Firefox: 36.0
- Selenium: 2.45.0

**Comment by Noag2** [comment]
Experiencing the same problem: a click on a div that contains an <a ui-sref> doesn't change the state.. happens only on firefox..
Same env: Ptor 1.8.0, selenium 2.45, firefox: 36.0
Worked until upgrade with Ptor 1.6, selenium 2.43, firefox 34..

**Comment by jlin412** [comment]
I think that it is a known issue for firefox and IE.  I has never seen it
worked since 0.23.

**Comment by LuciferWings** [comment]
I work around the click() issue by replace click() with mouseDown().mouseUp()

**Comment by ericmdantas** [comment]
Yeah, I've got a simular issue. Mine is a bit simpler, though.

```html

<div id="abc" i-change-routes="/abc"></div>

```

The thing is, my directive ```i-change-routes``` is the one in charge to switch the routes. It doesn't have anything fancy, it's just a ```location.path()``` that's called onClick.

While using protractor: in Chrome it works great, but not in Firefox. 

If I just test it manually, it works on both browsers.

Since I didn't have any 'div clicks' before, I don't know which version used to work or not. But I'm using ```protractor 2.0.0```, ```firefox 36.0.4``` and ```selenium-webdriver 2.45.1``` by now.

**Comment by hankduan** [comment]
I get the same behavior in Chrome:

```html
  <div id="outsideDiv">
    <img id="imgButton" ng-click="doAlert()" src="image.png"/>
  </div>
```

```controller
  $scope.doAlert = function() {
    $window.alert('Hello');
  };
```

```
  it('alert should open', function() {
    browser.get('http://localhost:8081');
    $('#outsideDiv').click(); // Does not work
    // $('#imgButton').click(); // Works
    browser.sleep(5000); // Sleep to manually check if the alert opened. 
  });
```

Anyways, I don't know whether clicking on a parent element should propagate the click event into its children, but I suspect this is working as intended.

**Comment by hankduan** [comment]
Here's a somewhat related issue: https://code.google.com/p/selenium/issues/detail?id=7566, but I don't know what the story is at the moment for FF and for chrome. 
Anyway, just clicking the intended element seems like the best thing to do.
