### ISSUE TITLE
RegExp objects do not survive transit through addMockModules()

### ISSUE THREAD

**Issue by gefilte** [angular/protractor#1897]
When passing argument(s) through the `addMockModule()` interface, a `RegExp` object on the protractor side will become an empty object (`{}`) on the browser side. I've worked around this problem with ugly hackery like:

    // Protractor side handling argument passed to addMockModule()
      if (Object.prototype.toString.call(mockDef.url) == '[object RegExp]') {
        // Serialize RegExp with special prefix flag
        mockDef.url = REGEXFLAG + mockDef.url.source;
      }

    // In function sent to addMockModule()
        if (mockDef.url.indexOf(REGEXFLAG) === 0) {
          // Marshal RegExp from special string
          mockDef.url  = new RegExp(mockDef.url.substr(3));
        }

This is an ugly hack, but without it the `RegExp` is "lost in translation".

I recognize this may be a problem with *selenium-webdriver* and not protractor, but it might be useful to track it here as well if that turns out to be the case (and changes can be made to *s-w* to fix.)

**Comment by juliemr** [comment]
This is actually due to the WebDriver spec - regexp isn't supported as a type to be transferred as an argument. See http://www.w3.org/TR/webdriver/#javascript-command-parameters

Please feel free to open up an issue with WebDriver to discuss this - I'm happy to leave this one open as a note to future viewers.

**Comment by gefilte** [comment]
This makes sense to me. I opened up an "enhancement" issue on the spec itself:

https://www.w3.org/Bugs/Public/show_bug.cgi?id=28146

Thanks!

**Comment by juliemr** [comment]
Closing since this discussion has moved to the enhancement issue. Thanks for opening that!!
