### ISSUE TITLE
elementExplorer is very slow

### ISSUE THREAD

**Issue by jperry** [angular/protractor#1899]
Hi,

I am trying out the debugging tools ```protractor --directConnect --elementExplorer``` in the "Testing Out Protractor Interactively" section and making calls using the REPL is very slow, roughly 1 minute or so for each element command to find an make an action on the DOM.  Is this normal or am I doing something wrong?  I don't see this type of behavior when running the tests through grunt.  Please advise if this is a bug or not.  Thanks!

**Comment by hankduan** [comment]
This is same issue as https://github.com/angular/protractor/issues/1890

**Comment by jperry** [comment]
thanks @hankduan
