### ISSUE TITLE
URL encoding breaks browser.get

### ISSUE THREAD

**Issue by notclive** [angular/protractor#1901]
I found this issue when trying Protractor with PhantomJS 2.

The wait at https://github.com/angular/protractor/blob/master/lib/protractor.js#L451 is returning too soon.
In PhantomJS 2 `return window.location.href;` returns `data:text/html,%3Chtml%3E%3C/html%3E` instead of the expected `data:text/html,<html></html>`.
This causes the condition on line 454 to return true, even though the new page hasn't been loaded.

This causes the following error
```
Error: Error while running testForAngular: {
  "errorMessage":"Detected a page unload event; asynchronous script execution does not work across page loads.",...
```

I'm happy to create a pull request that fixes this issue, as long you think this is a reasonable case to support.

**Comment by sjelin** [comment]
I think this might be an error on PhantomJS's part, but as long as it doesn't create problems for other browsers I have no problem supporting this case :smile:

**Comment by juliemr** [comment]
Is this still an issue? Can any phantom users chime in?

**Comment by NickTomlin** [comment]
I'm going to close this as there hasn't been any forward movement on it in over a year and it seems limited to PhantomJS 2.

If this is still an issue, please feel free to open a PR 😄
