### ISSUE TITLE
Protractor is not working with Firefox 30

### ISSUE THREAD

**Issue by BrodaNoel** [angular/protractor#1902]
I have the same issue that there is in this issue:
https://github.com/angular/protractor/issues/1734

But, with Firefox 30 on Windows XP

**Comment by mzgol** [comment]
From http://angular.github.io/protractor/#/browser-support:
"Protractor supports the two latest major versions of Chrome, Firefox, Safari, and IE."

This means Protractor doesn't support Firefox 30.

**Comment by juliemr** [comment]
Correct, we support the two latest versions.
