### ISSUE TITLE
Firefox and Chrome treats by.buttonText() differently when CSS text-transform is used

### ISSUE THREAD

**Issue by igorshubovych** [angular/protractor#1904]
Here is the main extracts from code:

app.css
```css
.my-sick-button {
  text-transform: uppercase;
}
```

app.html
```html
<button>Button 1</button>
```

app.spec.js
```js
function () {
  element(by.buttonText('Button 1')).click(); // fails in Chrome, works in Firefox
  element(by.buttonText('BUTTON 1')).click(); // fails in Firefox, works in Chrome
}
```

When the text is transformed via CSS property text-transform to uppercase, Chrome can find the element only by capitalized text (same as user see it). In the same case, Firefox can find the element by original text (same as written in HTML).

See full demo here:
https://github.com/igorshubovych/protractor-ff-issue

**Comment by sjelin** [comment]
Nice catch!  Fixing now
