### ISSUE TITLE
Travis should run the website tests

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#1906]
Currently he just runs the unit tests :disappointed:

**Comment by deveshmaheshwari** [comment]
@Sjelin We are running protractor tests as part of Travis using headless browser... and have not seen issues so far. We found that phantomjs doesn't behave properly.

**Comment by sjelin** [comment]
We aren't running the website's tests

**Comment by deveshmaheshwari** [comment]
what tests are you running or trying to run ? I think I didn't get your point completely

**Comment by sjelin** [comment]
There's a separate set of tests in the `/website/` folder

**Comment by juliemr** [comment]
Since the website doesn't update except when a new version is released, I think this might just slow down the test suite - is there something that slipped through the cracks that this would have caught?

**Comment by sjelin** [comment]
Yeah, I noticed when reviewing [marcy's PR](https://github.com/angular/protractor/pull/1891) that she broke some of the website tests and I didn't notice until I was looking through it for the second or third time.  It is true that it didn't make it all the way to the website though.  Maybe a better solution is to have the `generate-docs.sh` refuse to run unless you've run the tests on the current version.

**Comment by sjelin** [comment]
We decided against this ages ago
