### ISSUE TITLE
Select form elements by associated label

### ISSUE THREAD

**Issue by ravinggenius** [angular/protractor#191]
Given markup like:

``` html
<label for="your_name">Name</label>
<input id="your_name" />
```

... I should be able to fill in the input with `ptor.findElement(protractor.By.label('Name')).sendKeys('My Name');`.

Is this currently possible?

**Comment by Ema-jar** [comment]
This question helped a lot: http://stackoverflow.com/questions/34712495/protractor-select-a-form-element-using-label

**Comment by jamesthomasonjr** [comment]
In case anyone runs across this from Google and wants a simple solution using `by.addLocator`:

```js
function findElementByLabel(labelText, opt_parentElement) {
    const using = opt_parentElement || document;
    const xpath = `//input[@id=string(//label[. = '${labelText}']/@for)]`;
    return document.evaluate(xpath, using, null, XPathResult.FIRST_ORDERED_NODE_TYPE).singleNodeValue;
};

by.addLocator('label', findElementByLabel);
```
