### ISSUE TITLE
Zombie promises?

### ISSUE THREAD

**Issue by hhaamm** [angular/protractor#1911]
It's possible a log like this?

    07-<...>.js
    ...
       Stacktrace: [31m[31mError: Failed expectation[31m
    [31m    at [object Object].<anonymous> (...06-....js)[31m[31m[22m[39m

So, it basically something is failing in file *06* when I'm already processing file *07* inside a suite. 

There is an option to say to protractor / webdriver.js something like "hey don't wait for previous promises to be resolved". I guess not, but maybe there is a known scenario where this can happen.

Sorry for the little information. I can't give much more info. Please let me know if I should move this to another (wiki, forum) site. 

This is a similar issue, I think it's related with the previous one:

    [32m46 tests, 11 assertions, 0 failures
    [39m
    [launcher] BUG: launcher exited with 1 tasks remaining

And I have another case where I have an error stacktrace -after- the tests, assertions and failures line.

Protractor version: 1.7
node version: 0.10.36

**Comment by tullmann** [comment]
This is more of a stackoverflow issue than a bug report.   Please report it there: http://stackoverflow.com/questions/tagged/protractor

(You have async callbacks/promises running that protractor/webdriver are not aware of.)

**Comment by hhaamm** [comment]
@tullmann You are right, sorry for that. I've created a SO question: http://stackoverflow.com/questions/28915136/async-callbacks-promises-running-that-protractor-webdriver-is-not-aware-of

Closing this issue.
