### ISSUE TITLE
How to test svg pie charts and graphs using protractor?

### ISSUE THREAD

**Issue by snehacharkha** [angular/protractor#1915]
I was wondering if some one could direct me how to test svg pie charts and graphs using protractor .

I have to read data on pie charts when hovered on it or read data on graphs when hovered to the data points .

**Comment by jlin412** [comment]
I am curious how it could be done correctly.  When hovering over pie
charts, the results are inconsistent and it complains about other element
receives the click since pie chart are not a rectangle shape.

**Comment by snehacharkha** [comment]
Agreed according to the attached screen shot , the svg spreads across two other svgs . How can we garb the right path and hover on it 
![screen shot 2015-03-10 at 3 05 15 pm](https://cloud.githubusercontent.com/assets/6864700/6586488/204e8bb2-c737-11e4-8d23-3b8916b15e11.png)

**Comment by snehacharkha** [comment]
Agreed according to the attached screen shot , the svg spreads across two other svgs . How can we garb the right path and hover on it 
![screen shot 2015-03-10 at 3 05 38 pm](https://cloud.githubusercontent.com/assets/6864700/6586500/32d2b470-c737-11e4-83a4-2e69833a87ec.png)

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks! 

That said - can you add ids or classes to your svg elements to get a hold of them? They should act like other elements from WebDrivers' point of view.

**Comment by glepretre** [comment]
@snehacharkha Could you paste the link to your StackOverflow question when you will ask it please ? That's a very interesting one and I would like to follow the discussion. Thanks! :smile:

**Comment by snehacharkha** [comment]
Here you go :)

http://stackoverflow.com/questions/28973918/how-to-test-svg-pie-charts-and-graphs-using-protractor
