### ISSUE TITLE
How to extract only inner text from html tag

### ISSUE THREAD

**Issue by duchoang** [angular/protractor#1920]
For example with the following html code:
```html
<div id="content">
    Content  <span>ABC</span>
</div>
```
I can use getText() to extract the string "Content ABC" with the code:
```javascripts
element(by.id('content')).getText()
```
But what I want is to extract only the string "Content". I know I can wrap the text into another html tag e.g. span to achieve this. But I don't want to touch the view code. I hope I can try to extract the information in the protractor side. Does anyone know how to do that?
Thanks.

**Comment by juliemr** [comment]
Unfortunately, this is not a supported behavior for WebDriver. You can do `element(by.id('content')).getInnerHTML` to get the whole thing and parse it yourself, if you'd like.

Closing as a question - Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
