### ISSUE TITLE
Protractor iOS Automation: A Jasmine spec timed out. Resetting the WebDriver Control Flow.

### ISSUE THREAD

**Issue by bhawani2008** [angular/protractor#1921]
Hi , I am using Protractor @1.7.0 and appium to automate an iOS Hybrid app. I am getting Timeout error all the time while executing the tests.  Kindly Advise.

Config.js.....
exports.config = {
  allScriptsTimeout: 50000 ,
  getPageTimeout: 50000 ,
  seleniumAddress: 'http://localhost:4723/wd/hub',
   specs: ['PageObjectSpec.js'],
   capabilities: {
     browserName: 'iOS' ,
    'appium-version':'1.3.4',
     platformName:'iOS'   ,
     platformVersion: 7.1 ,
     deviceName:'iPhone' ,
     autoWebview:true , 
     },
   baseUrl: 'http://localhost:8100',   
   jasmineNodeOpts: {showColors: true, defaultTimeoutInterval:50000} ,
 };

Spec.js....
'use strict';
describe('Abbvie app test', function() 

{
 var userName = element(by.model('credentials.username'));  
 var passwd = element(by.model('credentials.password'));
 var signin = element(by.buttonText('Sign In'));
var name="patientqq" ;
var pass="Healthy1" ;

 it('Login Page test', function()
 {
 userName.click()
 userName.sendKeys(name)

 passwd.click()
 passwd.sendKeys(pass)
signin.click()

});
});

Protractor Logs:
Using the selenium server at http://localhost:4723/wd/hub
[launcher] Running 1 instances of WebDriver
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
Protractor.waitForAngular()
    at [object Object].webdriver.WebDriver.schedule (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:345:15)
    at [object Object].Protractor.executeAsyncScript_ (/usr/local/lib/node_modules/protractor/lib/protractor.js:251:26)
    at [object Object].Protractor.waitForAngular (/usr/local/lib/node_modules/protractor/lib/protractor.js:274:15)
    at [object Object].getWebElements (/usr/local/lib/node_modules/protractor/lib/element.js:136:19)
    at [object Object].getWebElements (/usr/local/lib/node_modules/protractor/lib/element.js:669:31)
    at [object Object].ElementArrayFinder.applyAction_ (/usr/local/lib/node_modules/protractor/lib/element.js:391:28)
    at [object Object].self.(anonymous function) [as click] (/usr/local/lib/node_modules/protractor/lib/element.js:77:19)
    at [object Object].self.(anonymous function) [as click] (/usr/local/lib/node_modules/protractor/lib/element.js:698:11)
    at [object Object].<anonymous> (/Users/qualcomm/Desktop/ProtractorTest/PageObjectSpec.js:13:11)
F

Failures:

  1) Abbvie app test Login Page test
   Message:
     timeout: timed out after 50000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 57.396 seconds
1 test, 1 assertion, 1 failure

[launcher] 0 instance(s) of WebDriver still running
[launcher] iOS #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

Appium Logs:

info: [debug] Socket data being routed.

info: [debug] Got result from instruments: {"status":0,"value":"PORTRAIT"}
info: [debug] Setting auto webview
info: [debug] Waiting for 4000 ms before navigating to view.

info: [debug] Navigating to most recently opened webview

info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray

info: [debug] Picking webview WEBVIEW_1

info: [debug] Attempting to set context to 'WEBVIEW_1'
info: [debug] [REMOTE] Debugger web socket connected to url [ws://localhost:27753/devtools/page/1]
info: [debug] [REMOTE] Unregistering from page readiness notifications
info: [debug] Waiting for app source to contain elements
info: [debug] Pushing command to appium work queue: "au.mainApp().getTreeForXML()"
info: [debug] Sending command to instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-03-12 14:09:43 +0000 Debug: Running system command #2: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":"PORTRAIT"}...

info: [debug] [INST] 2015-03-12 14:09:48 +0000 Debug: Got new command 2 from instruments: au.mainApp().getTreeForXML()

info: [debug] [INST] 2015-03-12 14:09:48 +0000 Debug: evaluating au.mainApp().getTreeForXML()
info: [debug] [INST] 2015-03-12 14:09:48 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:09:48 +0000 Debug: responding with:ull,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0","x":0,"y":0,"width":320,"height":568},">":[{"UIAScrollView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0","x":0,"y":0,"width":320,"height":568},">":[{"UIAWebView":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/0/0/0","x":0,"y":0,"width":320,"height":568},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/1","x":316.5,"y":0,"width":3.5,"height":568},">":[]}},{"UIAImage":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":false,"hint":null,"path":"/0/0/0/2","x":0,"y":564.5,"width":320,"height":3.5},">":[]}}]}}]}},{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1","x":0,"y":0,"width":320,"height":568},">":[{"UIAStatusBar":{"@":{"name":null,"label":null,"value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0/1/0","x":0,"y":0,"width":320,"height":20},">":[{"UIAElement":{"@":{"name":"No SIM","label":"No SIM","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/0","x":6,"y":0,"width":42,"height":20},">":[]}},{"UIAElement":{"@":{"name":"3 of 3 Wi-Fi bars","label":"3 of 3 Wi-Fi bars","value":"SPAN-GENERAL","dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/1","x":53,"y":0,"width":13,"height":20},">":[]}},{"UIAElement":{"@":{"name":"7:39 pm","label":"7:39 pm","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/2","x":137,"y":0,"width":46,"height":20},">":[]}},{"UIAElement":{"@":{"name":"100% battery power, On AC Power","label":"100% battery power, On AC Power","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":"Swipe down with three fingers to reveal the notification center., Swipe up with three fingers to reveal the control center, Double-tap to scroll to top","path":"/0/1/0/3","x":248,"y":0,"width":67,"height":20},">":[]}}]}}]}}]}}}
info: [debug] [INST] 2015-03-12 14:09:48 +0000 Debug: Running system command #3: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":{"UIAApplication":{"@":{"name":"AbbVie Care Global","label":"AbbVie Care Global...

info: [debug] Socket data received (3021 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":{"UIAApplication":{"@":{"name":"AbbVie Care Global","label":"AbbVie Care Global","value":null,"dom":null,"enabled":true,"valid":true,"visible":true,"hint":null,"path":"/0","x":0,"y":20,"width":320,"height":548},">":[{"UIAWindow":{"@":{"name":null,"label":null,"value":null,"dom":n
info: [debug] Device launched! Ready for commands
info: [debug] Setting command timeout to the default of 7200 secs
info: [debug] Appium session started with sessionId fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8

info: <-- POST /wd/hub/session 303 12286.856 ms - 9 

info: --> GET /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8 {}
info: [debug] Responding to client with success: {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"browserName":"iOS","appium-version":"1.3.4","platformName":"iOS","platformVersion":7.1,"deviceName":"iPhone","autoWebview":true,"count":1},"appium-version":"1.3.4","platformName":"iOS","platformVersion":7.1,"deviceName":"iPhone","autoWebview":true,"count":1},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}
info: <-- GET /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8 200 6.085 ms - 556 {"status":0,"value":{"webStorageEnabled":false,"locationContextEnabled":false,"browserName":"iOS","platform":"MAC","javascriptEnabled":true,"databaseEnabled":false,"takesScreenshot":true,"networkConnectionEnabled":false,"warnings":{},"desired":{"browserName":"iOS","appium-version":"1.3.4","platformName":"iOS","platformVersion":7.1,"deviceName":"iPhone","autoWebview":true,"count":1},"appium-version":"1.3.4","platformName":"iOS","platformVersion":7.1,"deviceName":"iPhone","autoWebview":true,"count":1},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: --> POST /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8/timeouts/async_script {"ms":50000}

info: [debug] Set iOS async script timeout to 50000ms
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}
info: <-- POST /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8/timeouts/async_script 200 6.598 ms - 76 {"status":0,"value":null,"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: --> POST /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8/execute_async {"script":"try { return (function (rootSelector, callback) {\n  var el = document.querySelector(rootSelector);\n\n  try {\n    if (!window.angular) {\n      throw new Error('angular could not be found on the window');\n    }\n    if (angular.getTestability) {\n      angular.getTestability(el).whenStable(callback);\n    } else {\n      if (!angular.element(el).injector()) {\n        throw new Error('root element (' + rootSelector + ') has no injector.' +\n           ' this may mean it is not inside ng-app.');\n      }\n      angular.element(el).injector().get('$browser').\n          notifyWhenNoOutstandingRequests(callback);\n    }\n  } catch (err) {\n    callback(err.message);\n  }\n}).apply(this, arguments); }\ncatch(e) { throw (e instanceof Error) ? e : new Error(e); }","args":["body"]}

info: [debug] Response url for executeAsync is http://127.0.0.1:4723/wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8/receive_async_response

info: [debug] [REMOTE] Executing atom in default context
info: [debug] [REMOTE] Sending javascript command

info: [debug] [REMOTE] Remote debugger data sent [{"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){var l=this;\nfunctio...]

Debugger web socket received data :  {"result":{"result":{"type":"undefined"},"wasThrown":false},"id":1}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert

info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:54 +0000 Debug: Got new command 3 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:54 +0000 Debug: evaluating au.alertIsPresent()
info: [debug] [INST] 2015-03-12 14:09:55 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-12 14:09:55 +0000 Debug: responding with:
       2015-03-12 14:09:55 +0000 Debug: Running system command #4: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:56 +0000 Debug: Got new command 4 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:56 +0000 Debug: evaluating au.alertIsPresent()
info: [debug] [INST] 2015-03-12 14:09:56 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:09:56 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-12 14:09:56 +0000 Debug: Running system command #5: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:57 +0000 Debug: Got new command 5 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:57 +0000 Debug: evaluating au.alertIsPresent()
info: [debug] [INST] 2015-03-12 14:09:57 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-12 14:09:57 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-12 14:09:57 +0000 Debug: Running system command #6: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:58 +0000 Debug: Got new command 6 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:58 +0000 Debug: evaluating au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:58 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:09:58 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-12 14:09:58 +0000 Debug: Running system command #7: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:59 +0000 Debug: Got new command 7 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:09:59 +0000 Debug: evaluating au.alertIsPresent()
       2015-03-12 14:09:59 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-12 14:09:59 +0000 Debug: responding with:

info: [debug] [INST] 2015-03-12 14:09:59 +0000 Debug: Running system command #8: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}
info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:00 +0000 Debug: Got new command 8 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:00 +0000 Debug: evaluating au.alertIsPresent()
info: [debug] [INST] 2015-03-12 14:10:00 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:10:00 +0000 Debug: responding with:
       2015-03-12 14:10:00 +0000 Debug: Running system command #9: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:01 +0000 Debug: Got new command 9 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:01 +0000 Debug: evaluating au.alertIsPresent()
       2015-03-12 14:10:01 +0000 Debug: evaluation finished
2015-03-12 14:10:01 +0000 Debug: responding with:

info: [debug] [INST] 2015-03-12 14:10:01 +0000 Debug: Running system command #10: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:02 +0000 Debug: Got new command 10 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:02 +0000 Debug: evaluating au.alertIsPresent()
       2015-03-12 14:10:02 +0000 Debug: evaluation finished
2015-03-12 14:10:02 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-12 14:10:02 +0000 Debug: Running system command #11: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)
info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:03 +0000 Debug: Got new command 11 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:03 +0000 Debug: evaluating au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:03 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:10:03 +0000 Debug: responding with:
       2015-03-12 14:10:03 +0000 Debug: Running system command #12: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:04 +0000 Debug: Got new command 12 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:04 +0000 Debug: evaluating au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:04 +0000 Debug: evaluation finished
info: [debug] [INST] 2015-03-12 14:10:04 +0000 Debug: responding with:
info: [debug] [INST] 2015-03-12 14:10:04 +0000 Debug: Running system command #13: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: [debug] atom did not return yet, checking to see if we are blocked by an alert
info: [debug] Pushing command to appium work queue: "au.alertIsPresent()"
info: [debug] Sending command to instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:05 +0000 Debug: Got new command 13 from instruments: au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:05 +0000 Debug: evaluating au.alertIsPresent()

info: [debug] [INST] 2015-03-12 14:10:05 +0000 Debug: evaluation finished

info: [debug] [INST] 2015-03-12 14:10:05 +0000 Debug: responding with:
       2015-03-12 14:10:05 +0000 Debug: Running system command #14: /Applications/Appium.app/Contents/Resources/node/bin/node /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/appium-uiauto/bin/command-proxy-client.js /tmp/instruments_sock 2,{"status":0,"value":false}...

info: [debug] Socket data received (28 bytes)

info: [debug] Socket data being routed.
info: [debug] Got result from instruments: {"status":0,"value":false}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: <-- GET /wd/hub/status 200 5.238 ms - 178 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: --> GET /wd/hub/status {}

info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: <-- GET /wd/hub/status 200 5.005 ms - 178 {"status":0,"value":{"build":{"version":"1.3.5","revision":"a124a15677e26b33db16e81c4b3b34d9c6b8cac9"},"isShuttingDown":false},"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: --> DELETE /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8 {}

info: Shutting down appium session
info: [debug] Stopping ios
info: [debug] Destroying instruments client socket.
info: [debug] Closing socket server.
info: [debug] Instruments socket server was closed
info: [debug] Sending sigterm to instruments

info: [debug] [INST] 2015-03-12 14:11:41 +0000 Stopped: Script was stopped by the user

info: [IOS_SYSLOG_ROW ] Mar 12 19:40:46 iPhone com.apple.launchd[1] (UIKitApplication:com.span.sampleTest[0x7dca][1303]) <Notice>: (UIKitApplication:com.span.sampleTest[0x7dca]) Exited: Killed: 9

info: [IOS_SYSLOG_ROW ] Mar 12 19:40:46 iPhone backboardd[31] <Warning>: Application 'UIKitApplication:com.span.sampleTest[0x7dca]' exited abnormally with signal 9: Killed: 9

info: [IOS_SYSLOG_ROW ] Mar 12 19:40:47 iPhone DTPower[185] <Warning>: Task info failed for task com.span.sampleTest

info: [debug] [INST] Instruments Trace Complete (Duration : 67.278687s; Output : /tmp/appium-instruments/instrumentscli0.trace)

info: [debug] [INSTSERVER] Instruments exited with code 0

info: [debug] Cleaning up after instruments exit
info: [debug] Stopping iOS log capture
info: [debug] Running ios sim reset flow
info: [debug] Killing the simulator process
info: [debug] Killall iOS Simulator

info: [debug] Killing any other simulator daemons

info: [debug] [REMOTE] Disconnecting from remote debugger

info: [debug] On a real device; cannot clean device state

info: [debug] Cleaning up appium session
info: [debug] Responding to client with success: {"status":0,"value":null,"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}

info: <-- DELETE /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8 200 843.700 ms - 76 {"status":0,"value":null,"sessionId":"fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8"}
info: <-- POST /wd/hub/session/fc13cf29-cd3e-43cc-8ad3-5efbfbee6cf8/execute_async - - ms - -

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
