### ISSUE TITLE
In ElementExplorer loop, require is not defined

### ISSUE THREAD

**Issue by SomeKittens** [angular/protractor#1930]
Just upgraded from 1.2 to 1.8.

Under 1.2 we were able to run Protractor in interactive mode via:

    noglob node /usr/local/lib/node_modules/protractor/bin/elementexplorer.js localhost:3001

In interactive mode, we could use `require` to pull in page objects and operate with them.  Now, when we run

    noglob node /usr/local/lib/node_modules/protractor/bin/elementexplorer.js http://localhost:3001

We get

    > require('crypto')
    ReferenceError: require is not defined

I've looked into [elementor](https://github.com/andresdominguez/elementor) but it doesn't seem to support requiring page objects, only selectors.

**Comment by juliemr** [comment]
This is due to our refactor of ElementExplorer - https://github.com/angular/protractor/commit/fb099dedf92a64732d88401dd1b0d4d30b22650d

We use `vm.runInThisContext` to execute code, which, AFAICT, does not allow access to `require`. I'm not sure if there's a good way around this, any ideas?

**Comment by SomeKittens** [comment]
We could blow a big hole in the VM by passing `require` in the context:

    'use strict';

    var vm = require('vm');

    var ctx = {
      require: require.bind(require),
      log: console.log
    };

    var str = "var c = require('crypto'); log(c.getCiphers());"

    vm.runInNewContext(str, ctx);


This requires creating a new context instead of `runInThisContext`.  I'm not sure how this impacts elementExplorer.  It also defeats a large part of the purpose of sandboxing, security-wise.

I couldn't tell the purpose of running the code with `vm` in the commit you referenced, though that's probably due to my lack of knowledge than anything to do with Protractor.  Would adding `require` break the intention?

**Comment by SomeKittens** [comment]
Having `require` available to the Protractor REPL is important to us because our page objects are doing a lot of heavy lifting that's difficult to replicate line-by-line.

**Comment by hankduan** [comment]
Something like this would work https://github.com/angular/protractor/pull/1931
alternative, we can also expose require as a global variable and keep the code the same as before.

**Comment by hankduan** [comment]
will be resolved in protractor version > 1.8.0

**Comment by SomeKittens** [comment]
@hankduan Sweet.  ETA on that release?

**Comment by hankduan** [comment]
It's not set in stones, but likely around 1 or 2 weeks. 
That being said, it's a simple patch, so you can just copy those changes into your local protractor and require would work for you.

**Comment by SomeKittens** [comment]
We'll need it before then so I'll copypasta.  Thanks again.

**Comment by SomeKittens** [comment]
The fix does not work for me:

    $ protractor --elementExplorer --baseUrl http://localhost:3001
    Starting selenium standalone server...
    Selenium standalone server started at http://10.1.10.13:53628/wd/hub
    Hit SIGUSR1 - starting debugger agent.
    debugger listening on port 5858
    Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

    Type <tab> to see a list of locator strategies.
    Use the `list` helper function to find elements by strategy:
      e.g., list(by.binding('')) gets all bindings.
    > require
    SyntaxError: Unexpected token u
        at Object.parse (native)
        at /usr/local/lib/node_modules/protractor/lib/debugger/modes/commandRepl.js:86:34
        at Client._onResponse (_debugger.js:260:5)
        at Protocol.execute (_debugger.js:134:14)
        at Client.<anonymous> (_debugger.js:175:14)
        at Client.emit (events.js:95:17)
        at Client.<anonymous> (_stream_readable.js:764:14)
        at Client.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)
    > require('crypto')
    SyntaxError: Unexpected token D
        at Object.parse (native)
        at /usr/local/lib/node_modules/protractor/lib/debugger/modes/commandRepl.js:86:34
        at Client._onResponse (_debugger.js:260:5)
        at Protocol.execute (_debugger.js:134:14)
        at Client.<anonymous> (_debugger.js:175:14)
        at Client.emit (events.js:95:17)
        at Client.<anonymous> (_stream_readable.js:764:14)
        at Client.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)
    > require('./test/e2e/pages/InstancePage')
    Error: Cannot find module './test/e2e/pages/InstancePage'
    > require('/Users/full/path/to/test/e2e/pages/InstancePage')
    SyntaxError: Unexpected token u
        at Object.parse (native)
        at /usr/local/lib/node_modules/protractor/lib/debugger/modes/commandRepl.js:86:34
        at Client._onResponse (_debugger.js:260:5)
        at Protocol.execute (_debugger.js:134:14)
        at Client.<anonymous> (_debugger.js:175:14)
        at Client.emit (events.js:95:17)
        at Client.<anonymous> (_stream_readable.js:764:14)
        at Client.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)

**Comment by juliemr** [comment]
Are you sure you're synched properly? The same example is working for me.

**Comment by SomeKittens** [comment]
I've opened `/usr/local/lib/node_modules/protractor/lib/protractor.js` and pasted the code found [here](https://raw.githubusercontent.com/angular/protractor/master/lib/protractor.js).  Not sure what could go wrong but it's entirely possible I borked something.

**Comment by hankduan** [comment]
You can't do a full file copy+paste. There are difference between master and 1.8.0. You have to apply the diff only

**Comment by SomeKittens** [comment]
Oh duh.  Sorry about that.  Working fine now.  You folks are wonderful.
