### ISSUE TITLE
Make it easier to control when `ignoreSynchronization` is off or on

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1939]
It's kind of difficult to know how it interacts with the control flow at the moment.

**Comment by hankduan** [comment]
Can we just wrap all our command in control flow, and make a function that sets ignoreSynchronization in control flow. 

i.e. `browser.get` (simplified to capture the idea)
now:
```javascript
if (ignoreSynchronization) {driver.get(...)}
else {waitForAngular(); driver.get(...)}
```

after:
```javascript
flow.execute(function() {
  if (ignoreSynchronization) {driver.get(...)}
  else {waitForAngular(); driver.get(...)}
})
```

and make 
```javascript
setIgnoreSynchronization = function(val) {
  flow.execute(function() {
    ignoreSynchronization = val;
  })
}
```

This will make cloning browsers more robust too

**Comment by juliemr** [comment]
Yeah, I think that's reasonable and probably the simplest way to do it. The hardest bit will be making clear docs about usage :)

**Comment by smhc** [comment]
If this were implemented.. I wonder if synchronisation could be turned off automatically by 'get' operations, and on when an action is performed that interacts with the page. i.e 

```javascript
waitForAngular()
click() - turn on sync
waitForAngular()
getText() - turn off sync
getText() - turn off sync
getText() - turn off sync
getText() - turn off sync
getText() - turn off sync 
click() - turn on sync
waitForAngular()
getText()  - turn off sync
```

Does that make sense? I think in some cases it could result in a fairly reasonable performance improvement, without the overhead of having to manage the sync on and off manually.
I don't know how practical it is however.

**Comment by juliemr** [comment]
@smhc I think that's out of scope for this change, but I'm working on an entirely new way of doing waits that will incorporate this sort of smart waiting. Stay tuned :)

**Comment by martin770** [comment]
Any update on this? I was wondering about even just retrieving browser.ignoreSynchronization as a promise or setting/getting within the context of the control flow somehow.

    setIgnoreSynchronization = function(arg) {
        arg = arg === undefined ? true : arg;
        controlFlow().execute(function() { browser.ignoreSynchronization = arg };
    }
    getIgnoreSynchronization = function() {
        return controlFlow().execute(function() { return browser.ignoreSynchronization });
    }

So then in waitForAngular() you can have

    this.getIgnoreSynchronization.then(function(shouldNotSync) {
        if (shouldNotSync) {
          return
        } else {
          ... waitForAngularStuff ...  
        }
    }

It would be nice to have the ability to use ignoreSynchronization within various points in the control flow. It seems to work ok when changing in onPrepare, beforeEach, or afterEach, but it isn't very useful when trying to change in the middle of a test.

**Comment by smhc** [comment]
Has this been addressed by https://github.com/angular/protractor/commit/cae175cbe632828172e9a7065aacfe67dd51d8dd ?

**Comment by martin770** [comment]
@smhc: No, `cae175c` doesn't mention the controlFlow. So while the plugin may be able to change the synchronization value during onPrepare, beforeEach, etc, it won't be able to change the value multiple times within the body of the test. To write the failing test, you would need to turn off synchronization, perform some action, expect some thing, turn it back on, perform some other action, expect some thing.

By the way, I like your previous suggestion of waitForAngular after click (and navigate, sendKeys, etc), and have been thinking about incorporating it into my page objects. It would be interesting to see if there is any performance benefit.

**Comment by juliemr** [comment]
We'll have an opportunity to fix this when moving to Blocking Proxy. See https://github.com/angular/protractor/issues/3375

**Comment by mgiambalvo** [comment]
In #3813, we added `browser.waitForAngularEnabled()`. This method will replace setting the `browser.ignoreSynchronization` proxy in future versions of Protractor.
