### ISSUE TITLE
Support Appium's additional WebDriverJS commands

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1940]

**Comment by LeninChristopher** [comment]
How to select date which is in date picker using protractor

**Comment by chrisfelix82** [comment]
Can't wait for this to be ready!

**Comment by idaneliz** [comment]
Is this solution ready for usage?

**Comment by LeninChristopher** [comment]
May we know the release date of protractor support for hybrid apps.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/pull/3326/files

**Comment by yfebles** [comment]
@juliemr  i was facing the same issue when trying to test an hybrid ionic app on a webview on android.  

It seems to me an  autoWebView : true  error using it  inside protractor. First i cant even start the tests cause the request were  been made using asycn methods of the webdriver api and on webviews should use implicitlyWait. 

I change the runner.js file on the createBrowser method to be able to load the tests and execute them  but of course inside the tests any call that is made by asycn methods has the same error from server. 

In the appium [forum ](https://discuss.appium.io) there was other situations like this one. I will try to fix the issue to use protractor for the e2e test, so any help on docs is welcome.

**Comment by gkohen** [comment]
@yfebles and @juliemr  , could you share a configuration for testing a hybrid app with Protractor and Appium?
The one article in the Protractor repository about the matter is for mobile browsers, not hybrid app.
I do manage to get to the step up to the point I'm getting:

> [debug] [JSONWP Proxy] Got response with status 200: {"sessionId":"579045442705f7f0e10147786203060d","status":13,"value":{"message":"unknown error: unable to discover open pages\n  (Driver info: chromedriver=2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1),platform=Mac OS X 10.11.6 x86_64)"}}

I've been going at it for days now and ready to back out of testing my Angular Hybrid app with Protractor which is a pretty big disadvantage considering Protractor semantic knowledge of an NG app.

**Comment by sjelin** [comment]
We don't have a setup for hybrid apps yet, just mobile browsers.  Hybrid apps will probably require quite a bit of work on top of that.  I wouldn't hold your breath unless someone already has a clean solution

**Comment by maciejkamela** [comment]
Is it possible to use Protractor + Appium for native android/IOS apps?

**Comment by asifetisalat** [comment]
@juliemr - Please let me know if it is possible to test Hybrid mobile app (not a web app) using Protractor + Appium.

**Comment by ansreenath** [comment]
Is it possible to use Protractor + Appium for native Android apps particularly messaging ?
Does protractor support native apps? Kindly confirm at the earliest.
