### ISSUE TITLE
Can I reuse/call existing API in Selenium-Java Framework into the Protractor Framework?

### ISSUE THREAD

**Issue by kumarvarun1252** [angular/protractor#1943]
Hi All,

We have a very sophisticated Selenium Webdriver-Java framework. But now some parts of our application is being implemented in AngularJS. We would like to use protractor for test automation. But we have some API in the existing framework which we would like to reuse. Is there a possibility to do so or do we need to re-write all the existing API in protractor?

Thanks,
Varun

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
