### ISSUE TITLE
Website: in-page links kick you back to the landing page

### ISSUE THREAD

**Issue by marcysutton** [angular/protractor#1946]
On the new Plugin documentation page, the internal links are affected by client-side routing. When I click on "Accessibility Plugin", for example, I'm routed back to http://angular.github.io/protractor/#/.

**Comment by juliemr** [comment]
Interesting, I don't see this on other pages, just the plugin docs one.

**Comment by Gillespie59** [comment]
Hi Julie, 

Instead of http://angular.github.io/protractor/#/#accessibility-plugin we should have http://angular.github.io/protractor/#/plugins#accessibility-plugin ?
