### ISSUE TITLE
Understanding function parameters

### ISSUE THREAD

**Issue by ch0wdan** [angular/protractor#1951]
Hey guys,

I'm trying to build a tests suite and i'm wanting to use parameters in my function. 

My test suite is using PageObject structure, so we have a PO for our main view which contains all the elements of that view(assigned to variables) , and we have methods to click(), get and return them. 

We also have a PageObject for other types of views with similar concepts, however these other views we are inputing text into some elements. 

One of our pages has 2 different types, Type A and Type B. I was hoping to create a method that contained a function thats parameterized so we can do both Type A and Type B, however I dont ahve much knowledge of Parameterization. 

Would someone by any chance be able to direct me towards understanding parameterization? Any web resources/ebooks/stackoverflow links that are relating to parameterization of functions in methods? Or maybe even some github projects that make use of this?

Thanks!

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by ch0wdan** [comment]
Thanks! I didn't realize there was a guideline! My apologies for this!
