### ISSUE TITLE
setFileDectector unable to set remote file detector

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#1959]
I upgrade to 2.0.0 to test browser.setFileDetector()
It is working locally with browser.setFileDectector(browser.FileDectector);
However, it is not working with remote selenium server.
I try browser.setFileDectector(browser.remote.FileDectector);
It seems that selenium-webdriver/remote is not exposed from protractor.
According to upload_test.js,
https://github.com/SeleniumHQ/selenium/blob/baa16a551fb8d57f4a176b2f49c7af633dba2893/javascript/node/selenium-webdriver/test/upload_test.js
We should do something like driver.setFileDetector(new remote.FileDetector);
so I tried
``` javascript
    var absolutePath = path.resolve(__dirname, filePath);
    var remote = require('../../../../node_modules/protractor/node_modules/selenium-webdriver/remote');
    browser.setFileDetector(new remote.FileDetector);
    $('input[type="file"]').sendKeys(absolutePath);
```
But I got UnknownError: invalid code lengths set

      From: Task: WebElement.sendKeys()

**Comment by juliemr** [comment]
What happens if you log `absolutePath`? Is that getting grabbed correctly?

**Comment by jlin412** [comment]
I have the console.log.  It is showing:
Image is uploading from /Users/linj/redbox_spa/redbox_angular/ext/branding/brookst/img/login-background.png

Nevertheless, this code is working locally when I remove "browser.setFileDetector(new remote.FileDetector);" or just using "browser.setFileDectector(browser.FileDectector); instead to test local server" so I know that path is good.

**Comment by Ravi-ratnakaram** [comment]
any update about the issue reported. I am also facing similar issue whie uploading the file. Please suggest if you have any work around..

**Comment by sjelin** [comment]
It's a WebDriver issue/feature, so it's beyond our control

**Comment by raghavan85** [comment]
Could we please know how to fix this issue ?

**Comment by sjelin** [comment]
You could ask on stackoverflow for help

**Comment by amex-mi** [comment]
The file upload was done based on the commit:

https://github.com/angular/protractor/commit/aadc68e7e9e68fac6922c1f3d1196839374aa1f6

https://github.com/angular/protractor/issues/2153

http://stackoverflow.com/questions/21305298/how-to-upload-file-in-angularjs-e2e-protractor-testing/21314337#21314337. I thought this was the right forum for this question / raise the issue.

**Comment by raghavan85** [comment]
The file upload was done based on the commit:

https://github.com/angular/protractor/commit/aadc68e7e9e68fac6922c1f3d1196839374aa1f6

https://github.com/angular/protractor/issues/2153

http://stackoverflow.com/questions/21305298/how-to-upload-file-in-angularjs-e2e-protractor-testing/21314337#21314337. I thought this was the right forum for this question / raise the issue.

**Comment by raghavan85** [comment]
I'd appreciate if someone can please look into this issue and see how we can fix it soon. This issue has been reported a while ago.

**Comment by raghavan85** [comment]
Is there a reason why the more info label is still present on this issue?

**Comment by raghavan85** [comment]
This issue has been reported in here as well: https://github.com/angular/protractor/issues/2371.

**Comment by raghavan85** [comment]
Could someone please troubleshoot this issue and provide a fix ?

**Comment by sjelin** [comment]
It's difficult for us to do anything because it's a problem with WebDriver.

**Comment by trietadatao** [comment]
var remote = require('protractor/node_modules/selenium-webdriver/remote');
browser.setFileDetector(new remote.FileDetector());

The above script works for me when testing with browserstack.
I'm using protractor 2.5.1

**Comment by JemiloII** [comment]
@trietadatao So do we just add these two lines and we're done, nothing else needed to be done?

**Comment by trietadatao** [comment]
Yes

**Comment by JemiloII** [comment]
Awesome! Thanks :)

**Comment by JemiloII** [comment]
@trietadatao So I can upload files, however, I am running into issues downloading. Was there anything special you had to do with the downloads? I appreciate your help.

**Comment by trietadatao** [comment]
I don't test download ever

**Comment by JemiloII** [comment]
Ahh alright, thanks~

**Comment by kristinjackvony** [comment]
I ran into this problem as well and was completely stumped until I found this article:  http://www.paulmcilwaine.com/development/protractor-saucelabs-and-file-upload.  The author mentions that there is a bug where files larger than 80KB can't be uploaded.  When I switched to using an 8 KB file I was able to upload with no problem.

**Comment by alecxe** [comment]
Cross-referencing this related SO post: [Remote File Upload Protractor test](http://stackoverflow.com/questions/34215697/file-upload-protractor-test/34367189#34367189).

**Comment by jfountain** [comment]
Still seeing this problem but this worked for me as well...
http://www.paulmcilwaine.com/development/protractor-saucelabs-and-file-upload
Didn't have a problem with larger than 80k files uploading though.

**Comment by JemiloII** [comment]
I did what @trietadatao recommended and I can upload gigabyte files at ease.

**Comment by juliemr** [comment]
Closing as answered. Thanks all!
