### ISSUE TITLE
Timeline starts in December 1969

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#1960]
Trying to use the `timeline` plugin, but the `Selenium Client` line starts with December 1969:

![screen shot 2015-03-23 at 1 10 42 pm](https://cloud.githubusercontent.com/assets/1291983/6785771/147388ac-d15e-11e4-970d-f5c3b98f4403.png)

I swear I started the tests in 2015 :)

Using protractor 2.0.0. The setup is pretty much common. What am I doing wrong? Let me know what additional information should I provide. Thanks.

**Comment by alecxe** [comment]
Interestingly enough, I have commented out the `protractor-html-reporter` initialization in the `onPrepare`:

    jasmine.getEnv().addReporter(new HtmlReporter({
        baseDirectory: "test-results/screenshots"
    }));

I've got a far more interesting timeline report:

![screen shot 2015-03-23 at 1 17 59 pm](https://cloud.githubusercontent.com/assets/1291983/6785896/0fe7ba0a-d15f-11e4-839d-346fab3721b4.png)

**Comment by juliemr** [comment]
Moving to protractor-timeline-plugin repo
