### ISSUE TITLE
Protractor API reference for version 1.8.0

### ISSUE THREAD

**Issue by lucasprus** [angular/protractor#1964]
Where is it now? http://angular.github.io/protractor/#/api only shows reference for the latest version.

**Comment by juliemr** [comment]
At the moment, we only keep the latest version on the website. You can always see the code for previous versions on the github repo by using the old version release tags. 

I'm not sure if it makes sense to have a versioned website, the way Angular does. We document changes thoroughly in our changelog, and do not support multiple branches so old versions are not officially supported. Is there a reason you cannot upgrade to 2.0?

**Comment by lucasprus** [comment]
Thanks Julie,

I managed to make the old website work locally following these instructions https://github.com/angular/protractor/tree/1.8.0/website

And I had this problem https://github.com/angular/protractor/issues/1969 when trying to install 2.0 so thought I would rely on 1.8.0 which works fine for me.

**Comment by juliemr** [comment]
Cool, sounds like this is handled.

**Comment by derekakers** [comment]
sometimes version upgrades are restricted by management for <insert adjective> reasons.  Being able to reference the correct API documentation is fundamentally necessary in these cases.

**Comment by fenduru** [comment]
This doesn't really seem like a solution. Even if a version is no longer supported, not having API reference is a huge PITA when dealing with existing code. I'm in the same boat as @derekakers - not everyone can be on the latest version all the time.

**Comment by rnavarette** [comment]
Running into exactly this issue now.  It would be _really_ nice if i could easily bring up online API docs for a previous, say 2.5.1 :), version.

**Comment by Matrosskin** [comment]
I have similar problem too. I use nodejs v0.12.9 so I can use only protractor v2. But I can't access documentation. On this page https://github.com/angular/protractor/blob/2.5.1/docs/api.md I see only link to latest api. How can I access api documentation for Protractor v2.5.1?

**Comment by alex-bigfoot** [comment]
Same issue here. When you've worked with supporting software products for a while, you'll realize this is a no-brainer. Especially for a non-typesafe, non-self-documenting, global-variable atrocity like javascript. 

How do I find the old API docs in github? Are they gone forever?

**Comment by cnishina** [comment]
I hope that this helps @alex-bigfoot, @Matrosskin, @rnavarette. The documentation is not gone forever...you should still be able to view the old documentation:

- switch to the tag [2.5.1](https://github.com/angular/protractor/tree/2.5.1)
- in the website directory, `npm install`
- then to start the website, use `npm start`

This should start gulp on localhost:8080. Hopefully that works.

**Comment by rnavarette** [comment]
Thanks @cnishina , but I think the point was something a little different.

While its good to know that we can build and launch the docs after doing a local checkout, I think the point was having access to something much more convenient.  The OP actually commented very early in the thread that the docs could be built locally.  However, having the previous versions available online would help quite a bit for those times when we can't or aren't (for some reason or another) on the latest version.

**Comment by Matrosskin** [comment]
And also in documentation built locally is not available sections "Inherited from webdriver.WebDriver" so we need to build protractor's docs and also search somehow which webdriver methods also available. Such solution does not help much :(

**Comment by barroudjo** [comment]
I agree, same here, we have to remain on an older version of protractor (v3) and it's very time consuming  tohave every developper in our 80 people team checkout and install the doc for even simple corrections.
