### ISSUE TITLE
Does browser.driver.wait accept element or webElement? 

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#1965]
What is correct?
```
browser.driver.wait(protractor.until.elementIsVisible(el))
```

or

```
browser.driver.wait(protractor.until.elementIsVisible(el.getWebElement()))
```

I am asking for it because there is no any check and no errors are thrown.

**Comment by juliemr** [comment]
I think you're actually asking if `elementIsVisible` accepts an `ElementFinder` or a `WebElement` - `wait` accepts a function or promise.

Both a `ElementFinder` or `WebElement` will work with `elementIsVisible`. Under the hood, it's using the `isDisplayed` method, which both expose.
