### ISSUE TITLE
Protractor terminates execution of a test before test really finishes 

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#1966]
It is really strange, maybe something in memory that does not  get updated.

```
 return browser.driver.wait(protractor.until.elementIsVisible(bbb)).then(function() {
       console.log('2----------->');
       bbb.click(function() {                                       
              console.log('----> 2.5')                                       
              element.all(by.css('....
```

This is just a snippet of the test case. 
Anyway the first console.log works fine, but the second is never reached. The test stops just before, returning directly to the reporter (it is like protractor does not see other `expect` execution after that, even if there are)

**Comment by juliemr** [comment]
`click` does not accept a parameter. You want `click().then(function...)`
