### ISSUE TITLE
Since protractor 2.0 is using Jasmine 2.1.1, does it mean we can use beforeAll()?

### ISSUE THREAD

**Issue by blaiseliu** [angular/protractor#1967]
I tried using `beforeAll()` inside a `describe` block, but still get 

> ReferenceError: beforeAll is not defined

Is it still unavailable?

**Comment by blaiseliu** [comment]
A check on the jasmine version shows I am still using **1.3.1**.  But my `package.json` in `protractor\node_modules\jasmine` says **2.1.1**. 

Is there anything we need to pay attention when upgrading protractor?

**Comment by juliemr** [comment]
Yes, please read http://angular.github.io/protractor/#/jasmine-upgrade
