### ISSUE TITLE
Switch from jshint to eslint

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#1968]
There is a rather new but pretty much mature linting tool called [`ESLint`](http://eslint.org/). 

I've personally been using it for a while and pretty happy with it. What is unique about - is that it is highly customizable and pluggable through *plugins and custom rules*. There is a rich set of built-in rules, there are several third-party plugins, like [`eslint-plugin-angular`](https://www.npmjs.com/package/eslint-plugin-angular) or [`eslint-plugin-jasmine`](https://www.npmjs.com/package/eslint-plugin-jasmine), and it is easy to create custom rules specific to the `protractor` internal code style guidelines.

Consider making switch and let me know if you need PRs here. If this doesn't make sense, feel free to close. Thanks.

**Comment by juliemr** [comment]
Thanks for the heads up! We probably won't move the Protractor hinting libs until the rest of the angular repo switches over, just to keep things consistent, so I'm going to close this for now.

**Comment by alecxe** [comment]
Yeah, that makes sense. Thank you.
