### ISSUE TITLE
Python not available warnings when installing Protractor 2.0.0

### ISSUE THREAD

**Issue by lucasprus** [angular/protractor#1969]
This is what I am getting when I am trying to install protractor from npm

![image](https://cloud.githubusercontent.com/assets/2707997/6821519/7143ab44-d2cf-11e4-8a7f-a7f0a01d51d0.png)

Do we need to follow node-gyp's installation steps now to install protractor?
https://github.com/TooTallNate/node-gyp

**Comment by lucasprus** [comment]
This is a similar issue https://code.google.com/p/selenium/issues/detail?id=8566. Is it really save to ignore these errors?

**Comment by juliemr** [comment]
I believe it is safe to ignore the errors, but I agree that it's alarming that they occur. I wonder if we can work with WebDriverJS to make sure they don't appear? Maybe removing `ws` as a dep is an option.

**Comment by juliemr** [comment]
Consolidating these issues under https://github.com/angular/protractor/issues/2035
