### ISSUE TITLE
protractor runs a spec only once although I explicitly specify it twice

### ISSUE THREAD

**Issue by javedlalani** [angular/protractor#1972]
I am using Version 1.6.1 on ubuntu 14
I have configured my suites option configured as below in protractor config file:

suites: {
        reporting_vms_tests: ['setup_spec.js', 'ReportingVMs.js', 'teardown_spec.js'],
        reporting_res_tests: ['setup_spec.js', 'ReportingRes.js', 'teardown_spec.js'],
    }

When I run individual suite with command line option like --suite reporting_vms_tests or --suite reporting_res_tests, everything run fine. But when I dont specify a --suite option which means I want to run all suites, the setup_spec.js and teardown_spec.js are ran only for first suite. And the second suite will fail.
So although the spec name appears twice, it is being run only once. Is there any workaround to this?

**Comment by juliemr** [comment]
This is working as intended, we use glob to make sure we don't duplicate spec files. I suggest putting the setup/teardown in a helper file, and then just doing `require` on that from your test file.

**Comment by javedlalani** [comment]
Hi Julie, 
Is browser and protractor available in helper files? In my setup and teardown specs I have to do some actions in browser

**Comment by juliemr** [comment]
Yes, `browser` and `protractor` are available on the global context.

**Comment by mukherjee-debasish** [comment]
I have suites defined like -
{
mysuite1:['login.js','testShellApp1.js','logout.js']
mysuite2:['login.js','testShellApp2.js','logout.js']
}
Is there a way to make sure that the duplicate tests run with this configuration? I am using '5.4.4' version.
