### ISSUE TITLE
Protractor - Appium - how to differentiate testing on Desktop, Mobile browsers

### ISSUE THREAD

**Issue by rajesh825** [angular/protractor#1976]
Hello, 

I  have recently started using Protractor to test web application both on Desktop, mobile (using appium).  However I have noticed an issue where certain functionality available only in Desktop resolution, not in Mobile screen resolutions.

  eg: One of the webpage displays breadcrumbs in Desktop browsers and not in mobile display. 

Would you please advise if there is any approach to check breadcrumb display only on desktop Browsers.
 

Thanks in advance.

Regards,
Raja

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks! 

See https://github.com/angular/protractor/pull/1724 to learn about getting your config information in your tests.
