### ISSUE TITLE
Chrome not closing when Error is detected

### ISSUE THREAD

**Issue by seyedx** [angular/protractor#1979]
So im cleaning up this e2e configuration a former employee has written, everything seems to work except one of my grunt tasks which involves running Unit tests + E2E tests whenever a change is made. 

The problem i'm having is that when an error such as EADDRINUSE is detected during startup and listening process of selenium, a chrome window pops up(which it should during e2e testing) but of course something is wrong and its just blank with the address bar saying: "data.,", and the chrome window doesn't close. So if i make another change, and I get similar error as above, another chrome window pops up. 
![screen shot 2015-03-27 at 14 45 51](https://cloud.githubusercontent.com/assets/9695816/6868942/0b676e88-d490-11e4-9cb8-a530f87637f4.png)

Normally when there is no error, a chrome window does pop up, runs all the clicking and navigating my e2e tests are supposed to do, then closes the chrome window and all test fails and successes are printed to console. 

Notice, my issue is NOT with the error, i know why i'm getting that error and how to handle it, my issue is with the Chrome window popping up and not closing as it should. 

So my grunt file looks like this for the protractor part:
```javascript
protractor: {
            options: {
                keepAlive: true
            },

            e2e: {
                configFile: "config/protractor.conf.test.js"
            }
        },
```

And grunt task looks like this:
```javascript
    grunt.registerTask('e2edev', function(){
        grunt.task.run([
            'clean:server',
            'concurrent:server',
            'browserify:app',
            'browserify:spec',
            'compass:server',
            'concat',
            'autoprefixer',
            'karma:unit',
            'connect:livereloadE2e',
            'protractor:e2e',
            'focus:e2edev'
        ]);
    });
```

And my protractor config:
```javascript
exports.config = {

    // The timeout in milliseconds for each script run on the browser. This should
    // be longer than the maximum time your application needs to stabilize between
    // tasks.
    allScriptsTimeout: 180000,

    // How long to wait for a page to load.
    getPageTimeout: 10000,

    // To connect to a Selenium Server which is already running
    //seleniumAddress: 'http://localhost:4444/wd/hub',

    // Spec patterns are relative to the location of this config.
    specs: ['../test/e2e/**/*.js'],

    capabilities: {
        'browserName': 'chrome'
    },

    seleniumPort: 4444,

    // A base URL for your application under test.
    baseUrl: 'http://localhost:9000/',

    //// Maximum number of total browser sessions to run
    maxSessions: 1,
    framework: 'jasmine2',


    jasmineNodeOpts: {
        // If true, display spec names.
        isVerbose: false,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 30000
        // Function called to print jasmine results.
        //print: function() {}
    },

    onPrepare: function() {
       var jasmineReporters = require('jasmine-reporters');

        //implicit and page load timeouts
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            filePrefix: 'test-results-e2e'
        }));

    }
};
```

Any tips or tricks on how to get the Chrome window to close would be helpful.

thanks in advance!

**Comment by seyedx** [comment]
Would appreciate some help with this!

**Comment by juliemr** [comment]
I cannot reproduce this by trying to start a selenium standalone server on a port which is already in use. 

You will get an open browser which does not close if there is an error thrown outside the control of Protractor. See https://github.com/angular/protractor/issues/1772

If you think that there's a specific place where we should be catching an error, please open up a new issue and let us know. Otherwise, I wonder if this is something going on with the grunt adapter - can you bring it up with them?
