### ISSUE TITLE
restartBrowserBetweenTests may have occasional hanging issues

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#1983]
I've only observed this in the angular/angular repository benchpress tests, which are doing all sorts of crazy stuff with getting perf logs. Here's an example: 

https://travis-ci.org/angular/angular/jobs/56131021

**Comment by juliemr** [comment]
One thing I notice in the logs - when closing the browser, we get:

```
12:56:53.721 INFO - Executing: [delete session: 46363891-e95b-4a7a-b2ca-02dc12dfec8a])
12:56:56.320 INFO - Command failed to close cleanly. Destroying forcefully (v2). org.openqa.selenium.os.UnixProcess$SeleniumWatchDog@7ecf0746
12:56:56.322 INFO - Done: [delete session: 46363891-e95b-4a7a-b2ca-02dc12dfec8a]
```

**Comment by juliemr** [comment]
Spent a long time looking into this today, and didn't get much of anywhere, but https://github.com/angular/protractor/commit/667111856627b9e81bedb92f3337fb0aba5a139c may help slightly.

**Comment by szikszail** [comment]
Hi, I am experiencing some similar issue now.

Somewhere around protractor@2.2.0 restartBrowserBetweenTests just closed the browser and did not open a new one. Now, if I use protractor@2.5.1, it just hands, the browser not closes, just waits... and waits...

I am using: protractor@2.5.1, cucumber@0.7.0, selenium-webdriver@2.47.0 and Google Chrome v46.0.2490.80 m

**Comment by juliemr** [comment]
This is pretty stale - closing as not useful, we can open a new one if we find new issues.
