### ISSUE TITLE
Returned elements don't contain the text

### ISSUE THREAD

**Issue by robertoriv** [angular/protractor#1984]
Hi,

I'm writing tests for our project and I've run into an issue with the $$ and element.all locators.

We've got a table with a number of columns. Amongst them are columns for a date value (class: `first-prod-date-cell`) and the state (class: `state-cell`):
```html
<div role="gridcell" style="left: 1300px; z-index: 790; width:200px;" class="jqx-grid-cell jqx-item first-prod-date-cell gridrow-0">
  <div style="overflow: hidden; text-overflow: ellipsis; padding-bottom: 2px; text-align: left; margin-right: 2px; margin-left: 4px; margin-top: 3px;">2014-11-01T05:00:00.000Z</div>
</div>
...
<div role="gridcell" style="left: 200px; z-index: 798; width:75px;" class="jqx-grid-cell jqx-item state-cell gridrow-0">
  <div style="overflow: hidden; text-overflow: ellipsis; padding-bottom: 2px; text-align: left; margin-right: 2px; margin-left: 4px; margin-top: 3px;">TX</div>
</div>
```

I also have a few functions for validating the values:

```javascript
        var column_data = function(column) {
            var selector = 'div.' + column + '-cell';
            console.log('selector: ' + selector);
            return $$(selector);
        };

        this.validate_text = function(column, expected_value) {
            column_data(column).then(function(elements) {
                expect(elements.length).toBeGreaterThan(1);
                for (var i in elements) {
                    expect(elements[i].getText()).toBe(expected_value);
                }
            });
        };

        this.validate_date_column = function(column, expected_value) {
            column_data(column).then(function(elements) {
                expect(elements.length).toBeGreaterThan(1);
                for (var i in elements) {
                    expect(elements[i].getText()).toBe(expected_value); //this was modified to be exactly the same as the previous function
                }
            });
        };
```

When I call those functions with the date's selector, I'm getting the following error for the `validate_date_column` function:

`- Expected '' to be Date(Fri Mar 27 2015 18:36:28 GMT-0500 (CDT)).`

The selector used when calling it is: `$$('div.first-prod-date-cell')`. I thought there was something wrong with my code, but the I tried using the same function to validate the `state-cell` column (`$$('div.state-cell')`) and that works just fine.

Using both selectors on the console with jQuery works perfectly (`$('div.first-prod-date-cell')`, `$('div.state-cell')`) returning the 10 rows each. But while protractor returns an array with 10 elements, none of them return a getText() value when using the selector for the date column. I also tried escaping the selector (`$$('div.first\-prod\-date\-cell')`). No dice.

Not sure if this is a bug with protractor, or if I'm going in the wrong direction. Figured I'd file an issue.

**Comment by juliemr** [comment]
Is there a chance that the text is not visible on screen? The WebDriver spec defines that `getText` returns the visible text of the element, so if it's hidden (maybe beneath another element), it will return an empty string.

**Comment by robertoriv** [comment]
Interesting.

I thought it would work as long as the element was rendered on the page. Our table is pretty wide, and that particular column is out of sight with the browser size that protractor is defaulting to (maximizing still leaves it out of sight on a Mac).

What are our options? Scrolling would be a pretty obvious solution here, but is there any way to get around it? Having to "calculate" how much to scroll for every column seems particularly bad.

Thanks a lot! :+1:

**Comment by juliemr** [comment]
If you interact with an element, WebDriver will attempt to scroll it on to the screen - so if you just click on the div before reading its input, that should fix it.

**Comment by juliemr** [comment]
Closing as an answered question.
