### ISSUE TITLE
Protractor 2.0. installation failed with MSBUILD error MSB3428 on Windows 8

### ISSUE THREAD

**Issue by jmcollin78** [angular/protractor#1985]
After resolving Python installation error (cf. http://stackoverflow.com/questions/29197828/cannot-install-protractor-2-0-0-enoent-in-bufferutil-while-node-gyp-rebuild) there is still errors on Windows 8:
<pre>
$ npm install -g protractor
npm http GET https://registry.npmjs.org/protractor
npm http 304 https://registry.npmjs.org/protractor
npm http GET https://registry.npmjs.org/jasmine
npm http GET https://registry.npmjs.org/jasminewd2
npm http GET https://registry.npmjs.org/minijasminenode
...
npm http 304 https://registry.npmjs.org/brace-expansion

> bufferutil@1.0.1 install C:\Users\Jean-Marc\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

C:\Users\Jean-Marc\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil {git}
{lamb} node "d:\Developpement\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http GET http://nodejs.org/dist/v0.10.28/node.lib
gyp http GET http://nodejs.org/dist/v0.10.28/x64/node.lib
gyp http GET http://nodejs.org/dist/v0.10.28/node.lib
gyp http GET http://nodejs.org/dist/v0.10.28/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.28/x64/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.28/node.lib
gyp http 200 http://nodejs.org/dist/v0.10.28/x64/node.lib
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
MSBUILD : error MSB3428: Impossible de charger le composant Visual C++ "VCBuild.exe". Pour corriger le problème, vous devez 1) installer le Kit de développement .NET Framework 2.0 SDK, 2) installer Microsoft Visual Studio 2005 ou 3) ajou ter l'emplacement du composant au chemin d'accès système, s'il est installé ailleurs.  [C:\Users\Jean-Marc\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil\build\binding. sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (d:\Developpement\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "d:\\Developpement\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jean-Marc\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
npm http GET https://registry.npmjs.org/concat-map
npm http GET https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map
npm http 304 https://registry.npmjs.org/balanced-match
</pre>

The msbuild.exe at path C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe exists and is runnable but it fails at run and I don't figure out why.

**Comment by juliemr** [comment]
Any other windows users seeing issues?

**Comment by jmcollin78** [comment]
Another user with this error here: http://stackoverflow.com/questions/29204994/installation-of-protractor-2-0-and-msbuild-error-msb3428

JM.

**Comment by ericmdantas** [comment]
Yeah, same error here.

But I was just reading the node-gyp docs, and there's this piece:

> On Windows:
Python (v2.7.3 recommended, v3.x.x is not supported)

> Windows XP/Vista/7:
Microsoft Visual Studio C++ 2010 (Express version works well)
For 64-bit builds of node and native modules you will also need the Windows 7 64-bit SDK
If the install fails, try uninstalling any C++ 2010 x64&x86 Redistributable that you have installed first.
If you get errors that the 64-bit compilers are not installed you may also need the compiler update for the Windows SDK 7.1

> Windows 7/8:
Microsoft Visual Studio C++ 2012/13 for Windows Desktop (Express version works well)


I don't have Visual Studio installed, so that could be it.

**Comment by jmcollin78** [comment]
I don't have Visual Studio C++ installed. And it should not be mandatory to have it installed to be able to install Protractor, I think.

JM.

**Comment by ericmdantas** [comment]
I agree, but that's node-gyp's error. I'm not sure if there's much what the protractor team can do.

But other than the log error, I'm still able to use protractor with no problems. Can't you?

**Comment by juliemr** [comment]
I believe this is due to new indirect npm dependencies that Protractor has in 2.0.0 with the upgrades to WebDriverJS.

**Comment by juliemr** [comment]
Consolidating this issues under https://github.com/angular/protractor/issues/2035

**Comment by micmor** [comment]
Got the same error, nevertheless protractor ( 3.0.0 ) is working properly. No need to fix that issue

**Comment by micmor** [comment]
Got the same error with protractor on windows 10. Installing visual studio 2015 community solved the problem.

https://www.visualstudio.com/de-de/products/visual-studio-community-vs.aspx
