### ISSUE TITLE
browser.wait is not blocking further execution. protractor@2.0.0

### ISSUE THREAD

**Issue by gijohn** [angular/protractor#1994]
browser.wait is not blocking further execution. The same code works fine with protractor@1.8.0.

browser.wait(element(by.id('some-element1')).isPresent, 5000);
browser.wait(element(by.id('some-element2')).isPresent, 5000);

Both  of them are getting triggered at the same time.

**Comment by LeninChristopher** [comment]
Ya i faced similar issue .. Tried both - wait(5000) and browser.driver.wait(5000) .. Both didn't affect the remaining part of the script to wait.. Finally it showed 'element not found error'

**Comment by juliemr** [comment]
You should be getting function binding issues in JavaScript with this - you're sending an unbound 'isPresent' function into `browser.wait`. I'm not sure why this worked before. Try

```js
    browser.wait(function() {
      element(by.id('some-element1')).isPresent();
    }, 5000);
    browser.wait(function() {
      element(by.id('some-element2')).isPresent();
    }, 5000);
```

**Comment by juliemr** [comment]
browser.wait(function() {
      element(by.id('some-element1')).isPresent();
    }, 5000);
    browser.wait(function() {
      element(by.id('some-element2')).isPresent();
    }, 5000);

**Comment by juliemr** [comment]
Note that there were some changes to the way the WebDriverJS node module handles wait, that are probably causing this issue to surface - see https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

**Comment by juliemr** [comment]
@LeninChristopher I think you may be looking for `browser.sleep`, which takes a single parameter which is the timeout to wait for.

I'm going to close this as a feature that was never fully supported, with a documented workaround, but please open a new issue if there are lingering problems.

**Comment by ghpabs** [comment]
Hi Julie,

I'm also having issues with `browser.wait` behaving in a non-blocking manner - at least when `browser.ignoreSynchronization` is set to `true`.

The snippet below opens google.com and input some text in the search field.

*conf.js*
```
'use strict';

exports.config = {
	framework: 'jasmine2',

	capabilities: { 
		browserName: 'chrome'
	},

	specs: ['spec.js'],

	onPrepare: function(){
		browser.ignoreSynchronization = true; 
		browser.driver.get('http://www.google.com/');

		var input = element(by.id('lst-ib'));

		browser.wait(function(){
			return input.isPresent();
		}, 5000);
		
		input.sendKeys('Protractor is... sometimes... cool.');
		browser.sleep(2000);
	}
};
```


*spec.js*
```
'use strict';

describe('foo', function() {
	it('bar', function() {
		expect(true).toBe(true);
	});
});
```

I get the following error:
```
NoSuchElementError: No element found using locator: By.id("lst-ib")
at exports.config.onPrepare (C:\...\spec.js:22:9)
```

Now if I use the `.then` syntax it works fine.

```
var input = element(by.id('lst-ib'));
browser.wait(function(){
	return input.isPresent();
}, 5000).then(function(){
	input.sendKeys('Protractor is... sometimes... cool.');
	browser.sleep(2000);
});
```

Please let me know if I'm missing something here.

Thanks

**Comment by ghpabs** [comment]
So.. I think I should be using `browser.driver.findElement` instead of `element`.
