### ISSUE TITLE
protractor hanging

### ISSUE THREAD

**Issue by peterpisljar** [angular/protractor#1995]
when running protractor 9 out of 10 times it hangs. 1 out of 10 times it works normally. no idea whats going wrong. my spec only opens the page in browser (and pauses, but even without pause i am getting same behaviour)

node v0.12.0
protractor 2.0.0
webdriver: latest (webdriver-manager update says its up to date ... )
os: win7

conf.js
----------------
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['homepage.js'],
  framework: 'jasmine2',
  capabilities: {
    "browserName": "chrome",
    "chromeOptions": {
      binary: "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe",
      args: [],
      extensions: []
    }
  }
};

spec.js
------------------
describe('home page', function() {
  it('should show frontpage', function() {
    browser.get('https://test2.e-invite.eu/admin/');
    browser.pause();
  });
});

error when it fails:
-----------------------------------
C:\Program Files (x86)\EasyPHP-DevServer-13.1VC9\data\_inviter>protractor tests\protractor\conf.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
F

Failures:
1) home page should show frontpage
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at Timer.listOnTimeout (timers.js:110:15)

1 spec, 1 failure
Finished in 30.028 seconds

**Comment by peterpisljar** [comment]
just tested with chrome, firefox and ie driver ... it happens for all of them
i tried downgrading to protractor 1.8, still the same result.

**Comment by peterpisljar** [comment]
also tried upgrading no node 0.12.2 ... still the same. must have something to do with my environment. 
where can i find the logs ?

**Comment by juliemr** [comment]
This looks like a support question - please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
