### ISSUE TITLE
Error after executing testsuite with directConnect in protractor 2.0.0 on Windows 8

### ISSUE THREAD

**Issue by beltsazar** [angular/protractor#1996]
When executing a testsuite in protractor 2.0.0 on Windows 8, all tests are run successfully but I do get an error from the webdriver:
....
Finished in 7.936 seconds
241 tests, 3 assertions, 0 failures

C:\git\psavingstab\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:640
  return flow.execute(function() {
              ^
>> 
Warning: Tests failed, protractor exited with code: 1 Use --force to continue.

Aborted due to warnings.
Process finished with exit code 1

I am using the following config options:

    directConnect: true,
    capabilities: {
        browserName: 'firefox'
    },

When testing against a selenium grid, everything works fine.

**Comment by juliemr** [comment]
Closing as stale.
