### ISSUE TITLE
Random failing tests in waitForAngular (IE11)

### ISSUE THREAD

**Issue by andrenarchy** [angular/protractor#1999]
We see a lot of random failing tests with Internet Explorer 11. The error message (see also [here](https://travis-ci.org/paperhub/paperhub-frontend/builds/55778796#L693)) always points to a timeout in `Protractor.waitForAngular()`:

```
[iexplore #3] Failures:
[iexplore #3] 
[iexplore #3]   1) PaperHub homepage Test page title
[iexplore #3]    Message:
[iexplore #3]      [31mScriptTimeoutError: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
[iexplore #3] Command duration or timeout: 4.09 seconds
[iexplore #3] Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
[iexplore #3] System info: host: 'WIN-8LIIH1BGM1D', ip: '172.20.27.132', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_60'
[iexplore #3] Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXc5e9d7c9
[iexplore #3] Driver info: org.openqa.selenium.ie.InternetExplorerDriver
[iexplore #3] Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=about:blank, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}][0m
[iexplore #3]    Stacktrace:
[iexplore #3]      ScriptTimeoutError: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
[iexplore #3] Command duration or timeout: 4.09 seconds
[iexplore #3] Build info: version: '2.40.0', revision: 'fbe29a9', time: '2014-02-19 20:54:28'
[iexplore #3] System info: host: 'WIN-8LIIH1BGM1D', ip: '172.20.27.132', os.name: 'Windows Server 2008 R2', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_60'
[iexplore #3] Session ID: XXXXXXXX-XXXX-XXXX-XXXX-XXXXc5e9d7c9
[iexplore #3] Driver info: org.openqa.selenium.ie.InternetExplorerDriver
[iexplore #3] Capabilities [{platform=WINDOWS, javascriptEnabled=true, elementScrollBehavior=0, ignoreZoomSetting=false, enablePersistentHover=true, ie.ensureCleanSession=false, browserName=internet explorer, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss, version=11, ie.usePerProcessProxy=false, cssSelectorsEnabled=true, ignoreProtectedModeSettings=false, requireWindowFocus=false, handlesAlerts=true, initialBrowserUrl=about:blank, ie.forceCreateProcessApi=false, nativeEvents=true, browserAttachTimeout=0, ie.browserCommandLineSwitches=, takesScreenshot=true}]
[iexplore #3] ==== async task ====
[iexplore #3] Protractor.waitForAngular()
[iexplore #3]     at [object Object].<anonymous> (/home/travis/build/paperhub/paperhub-frontend/test/spec.js:5:20)
[iexplore #3] ==== async task ====
[iexplore #3] Asynchronous test function: it()
[iexplore #3] Error
[iexplore #3]     at [object Object].<anonymous> (/home/travis/build/paperhub/paperhub-frontend/test/spec.js:2:3)
[iexplore #3]     at Object.<anonymous> (/home/travis/build/paperhub/paperhub-frontend/test/spec.js:1:63)
[iexplore #3] 
[iexplore #3] Finished in 8.197 seconds
[iexplore #3] [31m1 test, 1 assertion, 1 failure
```

Do you have any hints? Possibly this is related to #1476.

**Comment by juliemr** [comment]
4 seconds seems like a pretty slow timeout for the async script. Have you changed any timeout settings anywhere? Maybe the default for IE is getting set incorrectly in some way.

**Comment by andrenarchy** [comment]
There's only one timeout setting in the [config](https://github.com/paperhub/paperhub-frontend/blob/master/test/protractor.js) and it is set to 60 seconds. Do you see any other suspicious code in the config that could be related? :)

**Comment by juliemr** [comment]
No, your config looks good to me. We'll investigate!

**Comment by andrenarchy** [comment]
Thx!

**Comment by luisuribe** [comment]
I'm having the same problem, is there a way to debug this by ourselves or to send more information about it?

**Comment by racerbajs** [comment]
Me too have the same problem. A for loop that works flawlessly in Chrome / Firefox fails with the same message as in OP.
I've tried increasing allScriptsTimeout: xyz, to no avail. The test just times out after the set time.

Let me know if I can help by providing the test.

**Comment by drptbl** [comment]
:+1:

**Comment by racerbajs** [comment]
Sorry for the delay, I've had a man cold for a couple of days...

Here's my test below. It's supposed to create _number of systems, but what happens is in IE the test times out after first iteration (so only one system is created). In Chrome and Firefox the test works fine.

Let me know if you need any more info.

----

this.createSystems = function (number) { //create i number of systems

		//TODO: FAILS IN IE AFTER ONE ITERATION......

		var testSystemName = "System #";
		var testSystemDescription = "SystemDescription #";

		browser.get(toolKitUrl);

		function create(x) {
			toolKitPage.systemDropDown.click();
			toolKitPage.systemDropDown_CreateSystem.click();

			toolkitSystemCreatePage.systemName.clear();
			toolkitSystemCreatePage.systemDescription.clear();

			var field = toolkitSystemCreatePage.Description;
			var value = "{}";

			field.clear();
			_completeInput(field,value );

			function _completeInput(field, value) {
				return field.getAttribute('value').then(function(v) {
					if (v.length < value.length) {
						field.clear()
						return field.sendKeys(value).then(function() {
							return _completeInput(field, value);
						});
					};
				});
			};

			toolkitSystemCreatePage.systemName.sendKeys(testSystemName + x);
			toolkitSystemCreatePage.systemDescription.sendKeys(testSystemDescription + x);
			toolkitSystemCreatePage.createButton.click();
		}

		var funcs = [];

		for (var i = 0; i < number; i++) {
			funcs[i] = create.bind(this, i);
		}

		for (var j = 0; j < number; j++) {
			funcs[j]();
		}

	};

**Comment by Chexpir** [comment]
I have plenty of flakiness examples (tests that randomly fail) in IE11 but works perfectly in Chrome. I don't think people is using IE11 in production e2e tests, as it is impossible.

**Comment by evilaliv3** [comment]
I confirm that the timeout time seems being set randomly:

```
Failed: Error while running testForAngular: Timeout expired waiting for async script (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 330 milliseconds
```

i've not set any timeout manually, and this number is that low for a timeout and everytime changing.

@juliemr maybe the setting used by testForAngular is using a call to a function that is instable during the browser startup?

**Comment by sawpresto** [comment]
Any updates on this issue? I'm running Protractor 3.3.0 and WebDriver 10.0.1 against IE 11 and I'm getting the same result after changing the getPageTimeout property. Thanks!

**Comment by cnishina** [comment]
After investigation, I cannot get this to reproduce.

Here's my test:

spec
https://github.com/angular/protractor-cookbook/blob/master/protractor-typescript/spec.ts

config
```
import {Config} from 'protractor';

export let config: Config = {
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  capabilities: {
    browserName: 'internet explorer'
  },
  specs: ['spec.js']
}
```

**Comment by mgol** [comment]
@cnishina if using the 64-bit driver is discouraged, couldn't `webdriver-manager` use the 32-bit version by default?
