### ISSUE TITLE
Best practice to avoid non deterministic results?

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2005]
Too many times I get non deterministic results.

Are there any best practice to follow to avoid them?

Is there any way to understand when it can be a network problem?

As an example, I run my test on selenium grid with 3 node instances, 2 are ok, 1 fails.

Furthermore: shouldn't be scrollIntoView() method automatically executed before each click? Any click needs that action, so why any developer have to execute that line of code every time for example?

**Comment by cerdman** [comment]
We are dealing with this a lot with v1.4.0 and `browser.executeScript('window.scrollTo(...)').then()` but the issue seems to be isolated to CI servers.

**Comment by bitliner** [comment]
@cerdman did you fix the size of the screen for each test? Sometimes that can happen because the CI servers have a different screen size and scrollTo has a different result from what you can see on your local machine.

**Comment by juliemr** [comment]
I don't think there's anything actionable here, going to go ahead and close.

**Comment by bitliner** [comment]
The actionable, that I think should be written clear on the documentation, capital letters, is that it is mandatory to use .then(), and fix the screen-size.

Without then(), no deterministic result are almost a guarantee according to my experience.
