### ISSUE TITLE
protractor test gets to Timeout on Chrome but not on FF

### ISSUE THREAD

**Issue by zivSher** [angular/protractor#2006]
hey,
I'm running  a test that performs login on a non-angular page and then gets to an Angular page.
after the log-in succeeded, I get the home page and then, after 30 seconds, get this message:

    timeout: timed out after 30000 msec waiting for spec to complete

I have set the Jasmin timeout also to 36000 but I just keep waiting and waiting so it's meaningless.
I've just found out that it happens on Chrome but on FF it works fine and the test ends successfully. 
any ideas what would cause that?
protractor version 1.8.0
chrome version  41.0.2272.118
FF version 36.0.4

thanks.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
