### ISSUE TITLE
baseUrl doesn't allow paths

### ISSUE THREAD

**Issue by pmowrer** [angular/protractor#2008]
Setting `baseUrl` as `http://localhost:9876/app` seems basically equivalent to setting it as `http://localhost:9876`. Everything after the slash appears to get thrown out on `browser.get` (though `browser.baseUrl` returns `http://localhost:9876/app`).

It's unclear whether this is meant to be disallowed as the [docs](https://github.com/angular/protractor/blob/25aec6cac875b8b8e9a11a4cf5099c113359faa6/docs/referenceConf.js#L158) don't talk about it.

    // A base URL for your application under test. Calls to protractor.get()
    // with relative paths will be prepended with this.

Unless there's a good reason not to allow this, I think it'd be helpful.

**Comment by juliemr** [comment]
This is not generally true. For example, I set `baseUrl: http://localhost:8000/examples/src/hello_world` and then do `browser.get('foo.html')`, and the application loads `http://localhost:8000/examples/src/hello_world/foo.html`. 

Maybe your application is doing some sort of redirect? I'm closing this as not a general issue, but if you can provide a general case where you think there is a problem, please go ahead and open up a new issue.

**Comment by pmowrer** [comment]
@juliemr You're right, its not generally true. Looking into it further, it's due to how Node's `url.resolve` works. Specifically, the third example from the [docs](https://nodejs.org/api/url.html#url_url_resolve_from_to) is what's biting me:

```
url.resolve('http://example.com/one', '/two') // 'http://example.com/two'
```

As an example, what wasn't working for me was setting `baseUrl` to `http://localhost:9876/app` and then doing `browser.get('/sign-in')` would resolve to `http://localhost:9876/sign-in`.
