### ISSUE TITLE
Protractor navigates to the baseUrl after each it block

### ISSUE THREAD

**Issue by bodeamariuscosmin** [angular/protractor#2009]
My protractor tests were running fine until I have upgraded from Windows 7 to Windows 8.1. I have re-installed the protractor and the rest of the dependencies as before.

The tests started to behave strange, for example on a sign up modal, just half of the fields were completed and the page navigated to the next page, like protractor would not wait until everything is filled in.

My beforeEach looks like this:

<code> beforeEach(function () {
    browser.ignoreSynchronization = true;
    browser.manage().timeouts().implicitlyWait(100000);
  });</code>

I have fixed the wait inserting the <code>browser.manage().timeouts().implicitlyWait(100000);
on each function form the page objects.

BTW, I have another issue now and it seems to be related to the first one. I have a test script with several it blocks. After the first it block is completed, instead of continuing with the second it block, the tests navigates to the baseUrl and the rest of the tests fail.

Here it is my test script:
<code>var HomepageDC = require('../pages/HomepageDC.js'),
    RegistrationDC = require('../pages/RegistrationDC.js'),
    BuyMapPageDC = require('../pages/BuyMapPageDC.js'),
    AuthDC = require('../pages/AuthDC.js');

describe('Should sign up form the Contact Agent modal map', function () {

  var homepageDC = new HomepageDC(),
      registrationDC = new RegistrationDC(),
      buyMapPageDC = new BuyMapPageDC(),
      authDC = new AuthDC();

  beforeEach(function () {
    //browser.ignoreSynchronization = true;
    browser.manage().timeouts().implicitlyWait(100000);
  });

  it('Should navigate to the Buy map page', function () {
    homepageDC.navigate();
    browser.sleep(5000);

    buyMapPageDC.navigate();

    buyMapPageDC.mapView.click();
    expect(browser.getCurrentUrl()).toContain(browser.baseUrl + '/search/?listingTypes=2&view=map');
    browser.sleep(5000);
  });

  it('Should click on a city', function () {
    buyMapPageDC.borough.click();

    browser.sleep(10000);
  //});

  //it('Should click on a neighborhood', function () {
    buyMapPageDC.neighborhood.click();

    browser.sleep(10000);
  //});

  //it('Should click on a pin', function () {
    buyMapPageDC.pin.click();

    browser.sleep(10000);
  //});

  //it('Should open a listing', function () {
    buyMapPageDC.pinListing.click();
    browser.sleep(1000);
  //});

  //it('Should click on Contact Agent button and register', function () {
    buyMapPageDC.contactAgent.click();

    registrationDC.registrationPhone();

    browser.sleep(10000);
  //});

  //it('Should navigate to the homepage', function () {
    homepageDC.navigate();

    expect(homepageDC.me.getText()).toEqual('Me');

    authDC.logout();
  });
});</code>

Any idea what it going on? Is it because of the protractor 2.0 or am I doing something wrong?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
