### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by BrodaNoel** [angular/protractor#2011]
Hi!
I'm getting this error:
  2) xxxxxxxxxxxxxxxxxx
   Message:
     InvalidSelectorError: invalid selector: An invalid or illegal selector was specified
  (Session info: chrome=41.0.2272.118)
  (Driver info: chromedriver=2.14.313457 (3d645c400edf2e2c500566c9aa096063e707c9cf),platform=Windows NT 6.3 x86_64)

Please, could you add more information about WHICH is the invalid selector?
Thanks!

**Comment by juliemr** [comment]
These errors come directly from the WebDriver browser driver. Hopefully the stack trace was helpful in finding which line triggered that error - other than that, I don't think we want to get into the business of parsing webdriver errors and adding more information. (Note that the error returned from webdriver could be different text for different browsers). You could bring this up as a feature request with https://github.com/SeleniumHQ/selenium
