### ISSUE TITLE
Running protractor cucumber features in Webstorm

### ISSUE THREAD

**Issue by gziebold** [angular/protractor#2013]
I'm trying to run/debug cucumber features in WebStorm and I've hit a roadblock.  I have the following setup in my run configuration:

Working directory: /User/username/probjectName
JavaScript file: /Users/username/probjectName/node_modules/protractor/lib/cli.js
Application parameters: /Users/username/probjectName/protractor-cucumber.config.js

And here is the contents of the protractor-cucumber.config.js file

exports.config = {
  capabilities: {
    'browserName': 'chrome'
  },
  baseUrl: 'https://172.17.1.230/admin/',
  framework: 'cucumber',
  cucumberOpts: {
    format: "pretty",
    tags: "~@ignore"
  }
};

When I try and run/debug it in WebStorm I get "Error: Spec patterns did not match any files."  I'm assuming this is telling me it can't read the feature files that I have in /Users/username/probjectName/features?  

Any help would be greatly appreciated it!

**Comment by ToJo1** [comment]
Hi
Looks like you need to add a 'require' to the cucmberOpts.
something ike this:
   require: ["features/stepdefs/*.js", "features/support/pageObjects/*/*.js", "features/support/*.js"],

**Comment by gziebold** [comment]
Thanks for the tip.

I added 
require: ["features/navbar.feature", "features/step_definitions/nav-bar_steps.js", "features/support/nav-bar_page.js"]

...but I still get same result of 'Spec patterns did not match any files.'

**Comment by gziebold** [comment]
I have been able to get this to work!

created a node configuration in my IDE with the following...
Working directory: whatever is your project location
JavaScript file: node_modules/protractor/lib/cli.js
Application parameters: --specs=features/navbar.feature protractor-cucumber.config.js

Now in the IDE I'm able to either run or debug using said configuration.

Another thing I notice was that within my steps I need to have something like this:

  this.When(/^I change language to spanish/, function (callback) {
    this.navBar.spanishAnchor.click()
      .then(function () {
        callback();
      });
  })

And put the breakpoint on the callback(); line to get to the point where it has actually done the step of clicking the spanishAnchor in the browser.
