### ISSUE TITLE
Locator by.buttonText() and by.cssContainingText() no longer ignores markup inside matched elements

### ISSUE THREAD

**Issue by mwtorkowski** [angular/protractor#2018]
After upgrading to lastest version of Protractor and switching to Jasmine 2, it seems that behavior of two mentioned locators have changed. 
In case of `by.buttonText()` and markup like this:

    <button type="button" class="btn btn-default dropdown-toggle" ng-disabled="processing">
       View
       <span ng-show="actionableFilter === 'all'"> all</span>
       <span ng-show="actionableFilter === 'training'"> for training</span>
       <span class="caret"></span>
    </button>

Previously I was able to find that button using: `element(by.buttonText('View all'))`
Where as now this throws "no element found" error. In order to fix it, I need to either modify markup, and move "View" string to both spans, or use `by.partialButtonText('View')`. Looks like when looking for button now, text cannot span across different HTML nodes _inside_ button element (hope this makes sense).

Now, similar behavior is observed when using `by.cssContainingText()` - again, given this markup:

    // ...
    <tr>
        <td>Lorem <span ng-show="truthyValue">ipsum</span></td>
    </tr>

I'm no longer able to match above `<td>` using: `elment(by.cssContainingText('td', 'Lorem ipsum')` - I have to either target "Lorem" part of text or "ipsum".

And yes, I verified in more than one way that the ng-show evaluates to true so given text is actually displayed in the browser.

**Comment by juliemr** [comment]
Interesting, the code for `by.buttonText` hasn't changed so this is probably due to changes in WebDriver when you upgraded Protractor. Can you tell me how you are connecting to selenium webdriver (directConnect, using webdriver-manager, etc) and what version and browser you are using?

**Comment by mwtorkowski** [comment]
I'm using Google Chrome 41.0.2272.118 and my protractor config has "directConnect: true" so that answers your question I suppose.

**Comment by juliemr** [comment]
Can you reproduce this outside of being run by circleCI?

**Comment by hankduan** [comment]
Closing stale issue. Please open a new issue if necessary.
