### ISSUE TITLE
set a sensible implicitWait

### ISSUE THREAD

**Issue by rweng** [angular/protractor#202]
What do you think of adding an implicit wait [when the session is started](https://github.com/angular/protractor/blob/master/lib/runner.js#L190)? I ran into the issue that elements could not be found due to the js still processing.

Could be as simple as this one line:

```
driver.manage().timeouts().implicitlyWait( config.implicitWaitTimeout )
```

**Comment by creitzel** [comment]
I prefer an idiom like this:

    int restoreWait = setImplicitWait( LARGE_TIMEOUT );
    // do some stuff that needs to wait
    setImplicitWait( restoreWait );

    this.implicitWait = DEFAULT_IMPLICIT;  // Perhaps from config (+1)
    
    this.setImplicitWait = function( secondsToWait ) {
        var currentWait = this.implicitWait;
        if ( secondsToWait != this.implicitWait ) {
            browser.driver.manage().timeouts().implicitlyWait( secondsToWait );
            this.implicitWait = secondsToWait;
        }
         return currentWait;
    }

The benefit of this idiom is that methods/sub-routines that need waiting can be called in different contexts.  This allows one such method to call another and the outer-most caller can safely control the waiting time.
