### ISSUE TITLE
Wait timed out.

### ISSUE THREAD

**Issue by ikermart** [angular/protractor#2022]
Architechture: Ubuntu 14.04, Chrome Version 41.0.2272.101 (64-bit).
Yesterday suddenly started to NO PASS, all tests using:
```javascript
browser.wait(function(){
          return element(by.id('doughnut')).isPresent();
})
```
In my logs files appears like this:
![prtractor](https://cloud.githubusercontent.com/assets/1992268/7069161/97f4f95c-dead-11e4-8dac-4bd2039c8bc3.png)
Time outs on 52ms only! 
All my tests are working fine on Mac OSX environment.
Any help would be apreciated.

**Comment by RamonDonnell** [comment]
Had the same problem when upgrading from protractor 1.4 to 2.0
Workaround:
Add a timeout to the wait.
````javascript
browser.wait(function(){
          return element(by.id('doughnut')).isPresent();
}, 10000)
````

**Comment by juliemr** [comment]
Yes, this is a change in WebDriverJS, where a `wait` without a timeout will now set it to 0 instead of indefinite.  It will be reverted in the next version of WebDriverJS.

**Comment by juliemr** [comment]
I've added a note about this in the breaking changes section of the changelog.
