### ISSUE TITLE
Test doesn't fail if one of the promises failed

### ISSUE THREAD

**Issue by sixinli** [angular/protractor#2030]
Hi all,

I have been hitting a weird issue. Suppose I have the following code:

...
openFormElement.click();
inputElement.setText("new text");
...

and setText() will fail because it tries to click an unclickable element, which rejects the promise.

I would expect the test to also fail because setText() fails, however, it keeps going and passes the test. I am not sure if I am doing anything wrong here, or is this behavior expected?

Thanks for your time!

Edit:
Verify that the test is failing correctly in 2.0.0, but not any of the 1.x.x versions.

**Comment by juliemr** [comment]
Sounds like this is working correctly in the latest version. Closing - please open a new issue if you think there is still a problem. We have tests for failures at https://github.com/angular/protractor/blob/master/spec/errorTest/baseCase/error_spec.js - if you can make  PR showing something there that should fail but doesn't, that would be very helpful.
