### ISSUE TITLE
Saucelabs cannot change browser

### ISSUE THREAD

**Issue by spenoir** [angular/protractor#2031]
I have these capabilities in saucelabs protractor config but neither I or saucelabs support can work out why my tests still run on the default platform and latest version, which is Linux and (Firefox) 37.0 respectively. I'm well aware that my setup could be the problem as there are many variables but it would be nice to get the correct capabilities config confirmed so that I can rule out this being part of the problem. Just to be clear, its only the Platform and Version capabilities that are not working, everything else is fine. I suspect there could be a problem with the teamcity plugin but thats another issue all together.

    capabilities: {
        'browserName': 'Firefox',
        'platform': 'OS X 10.10',
        'version': '36.0',
        'name': 'tests',
        'tunnel-identifier': process.env.AGENT_NAME
    },
    ...

**Comment by juliemr** [comment]
Your config looks sane to me. You might want to try running protractor with the `--troubleshoot` flag, which will output the capabilities as Protractor sees them. Additionally, see our configuration, which runs against sauce labs, at https://github.com/angular/protractor/blob/master/spec/ciFullConf.js.

Please open up a new issue if you find that this is a problem with Protractor.
