### ISSUE TITLE
Java Error even when I have JRE Installed 

### ISSUE THREAD

**Issue by mohsen1** [angular/protractor#2041]
After I updated my OS X protractor stopped working. 

Here is what I get:
**To view this web content, you need to install the Java Runtime Environment.**
![screen shot 2015-04-13 at 4 52 41 pm](https://cloud.githubusercontent.com/assets/543633/7127750/8880dd76-e1fd-11e4-98aa-a0c6e101d2d7.png)

![screen shot 2015-04-13 at 4 53 48 pm](https://cloud.githubusercontent.com/assets/543633/7127758/ad56a194-e1fd-11e4-860d-0247079c8b67.png)

**Comment by juliemr** [comment]
Is java available on your command line path?

**Comment by mohsen1** [comment]
I had JRE but didn't have JDK. I needed to install JDK again after upgrading my OS X. This issue was resolved by installing JDK.

**Comment by Twansparant** [comment]
Thank you mohsen1, that fixed it for me too!
