### ISSUE TITLE
taskId using extended ascii char which is invisible when 

### ISSUE THREAD

**Issue by quiz1991** [angular/protractor#2042]
![screen shot 2015-04-13 at 5 58 49 pm](https://cloud.githubusercontent.com/assets/5345051/7128444/1399f056-e207-11e4-8483-e99d6461713a.png)
I have more than 128-97 = 31 spec files to run for single capabilities, in which case the following code
```javascript
if (queue.specLists.length > 1) {
    taskId += String.fromCharCode(97 + queue.specsIndex); //ascii 97 is 'a'
}
```
would create a taskId with extended ascii chars and these chars are invisible in our screwdriver which causes lots of confusion.

Maybe create taskId like "#1aa" instead?

**Comment by juliemr** [comment]
I knew supporting sharding was a bad idea :)

**Comment by quiz1991** [comment]
Thanks @juliemr !

**Comment by juliemr** [comment]
2.1 is out.
