### ISSUE TITLE
browser action raises stale element exception in protractor 2.0

### ISSUE THREAD

**Issue by Mellbourn** [angular/protractor#2043]
We have lots of protractor tests that worked fine in protractor 1.4
Now we are trying to upgrade.
It seems to me that all browser.actions() are now failing for us.

For example, this code used to work:
```javascript
        var cellToRightClick = row.element(by.css(cssSelector)).getWebElement();
        return browser.actions().click(cellToRightClick, protractor.Button.RIGHT).perform();
```

but now we get this when running the same code
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
```

Other places in the code, we were using browser.actions to left click. Those I could repair by doing a more straightforward element.click(). But I don't know how to do right mouse click without using browser.actions.

**Comment by Mellbourn** [comment]
I have now fixed the problem.

Apparently you should no longer use "getWebElement()". If you do, you now get "stale element". But if I remove it in the code above, it works for me.

It is a good change I guess, but maybe it should be pointed out somewhere. Feels like a breaking change to me.

**Comment by juliemr** [comment]
I'm not 100% sure where between 1.4 and 2.0 this actually broke. We've recommended passing element finders directly to `browser.actions` methods since v0.21 (https://github.com/angular/protractor/blob/master/CHANGELOG.md#bug-fixes-23). 

Feel free to submit a PR adding any documentation that you feel would be helpful!
