### ISSUE TITLE
browser.pause() is not working. It waits forever.

### ISSUE THREAD

**Issue by bdarwin** [angular/protractor#2044]
Environment:
Node version - any (tried 0.10.32, 0.12.0 and 0.12.2)
Protractor 2.0.0
Selenium (2.45.0) and Chromedriver 2.14
 
Config:
exports.config = {
    seleniumServerJar:'/usr/local/lib/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.45.0.jar',
    chromeDriver : '/usr/local/lib/node_modules/webdriver-manager/selenium/chromedriver',
    specs:['../firstSpec.js']
};

Command:
./node_modules/.bin/protractor test/conf/protractor.conf.js

When I run my tests, it says starting debugger but never takes me to console, it waits forever. Tried assigning different port numbers still no luck.
![protractor_never_goes_into_debugger](https://cloud.githubusercontent.com/assets/4622018/7142358/8be315c0-e30a-11e4-8bbd-21386581f143.png)
 

Protractor 1.8.0 and Node 0.10.32 seems to be fine though.

**Comment by hankduan** [comment]
Encountered this myself last night. It's because of some breaking changes in webdriver 2.45.0

**Comment by hankduan** [comment]
Fixed here: https://github.com/angular/protractor/pull/2046

**Comment by hankduan** [comment]
fix is merged and will be released in the next version

**Comment by juliemr** [comment]
2.1 is out.
