### ISSUE TITLE
How to do swipe & datepicker selection

### ISSUE THREAD

**Issue by LeninChristopher** [angular/protractor#2048]
Hi..i have two queries
1. Tile in my application dashboard which requires swipe to be performed to load the next set of data..how to achieve this
2. How to deal with date picker controls..the textbox which is used to enter date is set to read only so to select a date we need to use only date picker..how to do it using protractor.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
