### ISSUE TITLE
Write protractor tests in ES6

### ISSUE THREAD

**Issue by jonricaurte** [angular/protractor#2049]
Hi,
 
Saw there was discussion about using coffeescript to write protractor tests, however, I didn't see any that involved ES6. I see the current pattern is to write tests in ES6 and have a gulp task compile them into a separate directory and then have protractor use the compiled files for testing. It would be nice to have something similar to karma-babel-preprocessor to write tests with where we don't need a gulp task.

Thanks.

**Comment by juliemr** [comment]
See also https://github.com/angular/protractor/issues/1214

Many ES6 features are already available in node, provided you have the right flags. What features, specifically, are you looking for? I wonder if the ideal way to do this is to wait for es6 features to hit node so that compilation can be avoided altogether.

**Comment by jonricaurte** [comment]
I was looking to use classes and arrow functions, which don't seem to be stable. Since coffeescript seems to be supported out of the box, is it possible to have ES6 also be supported by using babel or traceur?

**Comment by juliemr** [comment]
I'd prefer not to build preprocessors in to the core framework - I think doing this as a gulp task makes the most sense for now.

**Comment by jonricaurte** [comment]
Ok, that works for me.

**Comment by jamieconnolly** [comment]
Stumbled across this issue after finding my own solution for the same thing. It seems my (somewhat basic) needs are fulfilled by adding ```require('babel/register');``` to the prototractor configuration file. I can then use ES6 to write my tests :+1:

**Comment by datatypevoid** [comment]
@jamieconnolly Your solution works perfectly for my end to end testing needs. Thanks!

**Comment by jonricaurte** [comment]
@jamieconnolly Thanks for the tip! I totally forgot about doing it this way; this is how we used to have to do it for running coffeescript tests before it was built in.

**Comment by stringbeans** [comment]
@jamieconnolly that method allows us to use ES6 to write our tests, however if there are any errors it doesn't report the line numbers correctly. Do you know how to utilize source maps in this case?

**Comment by tsubik** [comment]
@stringbeans I've also had the same problem. `require('babel/register')` generates and installs source maps by itself, but everything is done on the fly. Protractor also try to install source maps, but checking source files from disk which are not changed at all. Looks like [this line](https://github.com/angular/protractor/blob/master/lib/runner.js#L162) overrides good source maps loaded by `require('babel/register')` so as a workaround I'm invoking that hook later in `onPrepare` function. 

```
exports.config = {
    framework: "jasmine2",
    baseUrl: "http://localhost:4200",
    seleniumAddress: "http://localhost:4444/wd/hub",
    specs: ["integration/**/*.js"],
    capabilities: {
        "browserName": "chrome"
    },
    onPrepare: function () {
        require("babel/register");
    }
};
```
Other option could be add some config for protractor to disable loading source maps.

**Comment by PinkyJie** [comment]
@tsubik Works for me, thanks!

**Comment by dfguo** [comment]
@tsubik i still couldn't get proper line number after moving ```require("babel/register");``` to ```onPrepare```. Did you manage to get it working for you?

**Comment by PinkyJie** [comment]
@dfguo My full protractor.config.js is here https://github.com/PinkyJie/angular1-webpack-starter/blob/master/protractor.config.js, check this to see if it could help.

**Comment by vredchenko** [comment]
Hi, came here looking for solution to the proper line numbering problem. Just want to confirm that @PinkyJie method of moving `babel/register` to `onPrepare()` worked for our project, too. Thanks! :)

**Comment by 0xR** [comment]
For me putting `babel/register` in onPrepare didn't work. Running protractor 2.2.0.

**Comment by 0xR** [comment]
As a workaround this seems to help: `require('babel/register')({retainLines: true});` 
See https://babeljs.io/docs/usage/options/

**Comment by nsteenbeek** [comment]
I had to use require("babel-core/register") to get it working.

**Comment by PeterStegnar** [comment]
require("babel/register");

Is old name.

You should use:

require("babel-register");

**Comment by hirunatan** [comment]
Thanks @nsteenbeek and @PeterStegnar, searched a lot of sites, but this was what i needed. Now it works!

**Comment by PeterStegnar** [comment]
@hirunatan no problem, happy to help!

**Comment by adityagautam** [comment]
Can some one tell me what is wrong in my onPrepare function as I am not able to use ES6.
```
onPrepare: () => {
         require("babel-register");
         require("babel-core/register")({presets: ["es2015"]});

       let origFn = browser.driver.controlFlow().execute;

        browser.driver.controlFlow().execute = function () {
            let args = arguments;

            origFn.call(browser.driver.controlFlow(), function () {
                return protractor.promise.delayed(this.delayBrowserTimeInSeconds * 100);
            });

            return origFn.apply(browser.driver.controlFlow(), args);
        };

        browser.driver.manage().window().setSize(window.screen.availWidth, window.screen.availHeight);
        browser.driver.manage().window().maximize();
    }
```

**Comment by wswebcreation** [comment]
@adityagautam 

You are reacting on a closed issue and secondly asking a question that is not related to Protractor. I don't think it's that wise to do that. 

Having said that, your error suggests that you are on a version of node that is equal to 4.x. Protractor requires 6.9 at least. If you upgrade you will see this will solve your initial problem.

Secondly. Are you using babel to transpile your ES6 to ES5? If so, then your code isn;t logic,m because you are running an `arrow` function (ES6) to call Babel to transpile ES6 to ES5. Or am I wrong?

**Comment by geyuqiu** [comment]
Since babel 7 it is now 

```javascript
require("@babel/register");
```

after

```bash
npm install --save-dev @babel/register
```
of course :)
