### ISSUE TITLE
Setting Window Object Before Angualr Loads

### ISSUE THREAD

**Issue by btormey** [angular/protractor#2050]
I'm using CefSharp to run an AngularJS application. CefSharp has a method to RegisterJsObject, which assigns objects or properties onto the window before any of the client scripts execute.

I need to replicate this functionality to run Protractor tests without getting `cannot read property 'xyz' of undefined`. Is it possible to register properties and objects onto the `window` object before Angular loads up?

I have tried to use the `executeScript` and `executeAsyncScript`, however, the objects don't seem to register before Angular attempts to use them via `$window.xyz`. 

```
describe('my test', function () {
    it('should do stuff', function () {
        browser.driver.manage().timeouts().implicitlyWait(10000);
        browser.get('#/');
        browser.executeAsyncScript(function(cb) {
            window.xyz = { foo: { bar: "something" } };
            cb(true);
        }).then(function (cb) {
            browser.wait(function () {
                element(by.id('some-element')).isPresent();
            });
            expect(element(by.id('some-element')).isPresent()).toBe(true);
        });
    });
});
```

Are my promises off here or am I doing something wrong? Or is it just not possible to assign `window` objects before loading up the Angular scripts?

Link to SO: http://stackoverflow.com/questions/29652704/protractor-tests-assign-window-objects

**Comment by juliemr** [comment]
Answered on SO.
