### ISSUE TITLE
Plugin references in documentation links are dead

### ISSUE THREAD

**Issue by gkohen** [angular/protractor#2053]
On http://angular.github.io/protractor/#/plugins when clicking on any of the 3 default plugins, we do not get to the appropriate page (if any exists).

**Comment by ryanhart2** [comment]
The linked content is further down on the same page. Using ng-hint as an example, the links navigate incorrectly from
http://angular.github.io/protractor/#/plugins
to 
http://angular.github.io/protractor/#/#nghint-plugin
instead of
http://angular.github.io/protractor/#/plugins#nghint-plugin

**Comment by juliemr** [comment]
Thanks for pointing this out - this is an issue with converting our markdown docs to also work on the website
