### ISSUE TITLE
Need help on protractor setup

### ISSUE THREAD

**Issue by amitwalke** [angular/protractor#2057]
I have installed Nodejs on my windows 7 machine.

I am facing error while executing below command : webdriver-manager update

I am getting output as below :

C:\Users\amit_walke>webdriver-manager update
selenium standalone is up to date.
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.14/chromedriver_win32.
zip...
Error: Got error Error: self signed certificate in certificate chain from https:
//chromedriver.storage.googleapis.com/2.14/chromedriver_win32.zip
I can download chromedriver win32 zip using browser but on command prompt facing above issue. 
i am behind proxy (from office location) .

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
