### ISSUE TITLE
Console plugin does not fail on error on Firefox

### ISSUE THREAD

**Issue by qoobaa** [angular/protractor#2058]
I'm trying to use the console plugin with Firefox and it seems to work only partially. The only thing that works is logs filtering (the `exclude` option), but none of `failOnError`, `failOnWarning` doesn't seem to work properly, they work when I tested on Chrome.

**Comment by juliemr** [comment]
This is because the firefoxdriver implements log grabbing slightly differently. We should clarify that the console plugin is only guaranteed against chrome.

**Comment by szimek** [comment]
@juliemr Do you think it would make sense to report it to Selenium to make the Firefox driver work similarly to the Chrome one?

**Comment by szimek** [comment]
One more thing - I'm getting random `NS_ERROR_XPC_BAD_CONVERT_NATIVE`  errors in console when running tests in Firefox (no idea why) that actually make tests fail:
```
Fail:  Console output
       SEVERE: NS_ERROR_XPC_BAD_CONVERT_NATIVE:
```
so it looks like it works in some cases :)
