### ISSUE TITLE
Incorrect dependency for selenium-webdriver in version 1.8.0

### ISSUE THREAD

**Issue by andrew-qa** [angular/protractor#2059]
According to changelog (https://github.com/angular/protractor/blob/master/CHANGELOG.md) Protractor version 1.8.0 should contain selenium of version 2.45.0.

But in fact it contains webdriver 2.44.0. (https://github.com/angular/protractor/blob/29ce5c6ad0d24d06f03f0a7736af4f6a91d4bf3f/package.json)

It will be better to get rid of such inconsistency to avoid confusing.

**Comment by juliemr** [comment]
Both are true :) 

1.8.0 depends on Selenium Standalone Server v2.45.0, and selenium-webdriver nodejs module v2.44.0. This was discussed in https://github.com/angular/protractor/issues/1872
