### ISSUE TITLE
e2e test the datetime format with regular expression question.

### ISSUE THREAD

**Issue by BoykaZhu** [angular/protractor#2061]
Hi guys,

I am a fresh and facing problem when using the regular expression to test the Datetime format in the page.

The expect display is like "Last update: Apr 17 at 1:21PM"
So I wrote something in specs like:
```javascript
it('DEPLOYMENT CHART TITLE AND UPDATE AUTOMATICALLY01', function () {
    var titleFormat = function (success) {
         var patrn = /^[L]{1}[ast]{3}\s[update]{6}[:]\s[A-Z]{1}[a-z]{2}\s[0-3]?[0-9]{1}\s[at]{2}\s[0-1]{1,2}[:][0-5]{1}[0-9]{1}[A,P]{1}[M]$/;
         if (!patrn.exec(success)) {
            return false; 
         } else{
            return true; 
         } 
    };
    var depCharTitle = element(by.binding('curTime'));
    expect(titleFormat(depCharTitle.getText())).toBe(true);
  }); 
```
I tried to verify the expression manually, it is correct I think.
But the script running result always reture "false".

Can someone help on this? Appreciate it.

**Comment by BoykaZhu** [comment]
@juliemr can you help on this?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by juliemr** [comment]
Looks like you have an issue where `depCharTitle.getText()` is returning a promise, but you're treating it like a string.

**Comment by BoykaZhu** [comment]
@juliemr thanks  for your response, I fixed it.
