### ISSUE TITLE
Using webdriver.promise.all() in a then bock causes execution of next

### ISSUE THREAD

**Issue by jithin1987** [angular/protractor#2062]
Protractor 2.0.0
Selenium (2.45.0) 
Mocha (2.2.4)

If I use 

```
webdriver = require('selenium-webdriver');
---
}).then(function() {
   return webdriver.promise.all([
     ...
  ]);
}).then() {
...
```

executing promise.all() causes that test to exit current it block and move to next it block. Kindly advise if this usage is supposed to work and if should then where should this issue belong to? - Protractor itself or Mocha. 

My use case is to execute promises in parallel so that I can save few lines of code of then blocks. Is using webdriver.promise.all() not the right way to do this ?

**Comment by juliemr** [comment]
It's hard to tell what your problem is from your description. Could you please include a snippet which shows the full `it` block which is being exited from early?

**Comment by jithin1987** [comment]
Here is a snippet of the problematic it block.
```
/* global browser, $, it, describe, before, $$, by */

var chai = require("chai"),
    expect = chai.expect,
    chaiAsPromised = require("chai-as-promised"),
    chaiWebdriver = require('chai-webdriver'),
    utils = require("../libs/utils"),
    kb = require("../libs/keyboard").keyboard,
    conf = require("../libs/confs"),
    webdriver = require('selenium-webdriver');


chai.use(chaiAsPromised);
chai.use(chaiWebdriver(browser.driver));

describe("editor test", function () {
    describe("as user non expert", function () {
    ....
    });
    describe("as user expert", function () {
        before(function () {
            return browser.wait(function () {
                return login(browser, "editor", "expert").then(function () {
                    return utils.filterView(filterParams);
                });
            });
        });
        it('is confirming user is expert', function () {
            expect(css).dom.to.have.htmlClass('expert');
        });
        it('is testing shortcuts', function () {
            var firstTrans = [],
                secondTrans = [],
                editStr = 'Keyboard edit ' + timestamp;
            $(conf.transFirstTarget).click().then(function () {
                return utils.waitToBeDisplayed($(conf.transEdit));
            }).then(function () {
                //return true;
                return webdriver.promise.all([
                    $(conf.transFirstTarget).getText(),
                    $(conf.transFirstLocale).getText()
                ]);
            }).then(function (params) {
            .....
            }).thenCatch(function (err) {
                return $(transEdit).$(".cancel").click();
                console.log(err, err.stack);
            });
        });
        it('is editing', function () {
            $(conf.first).getAttribute("class").then(function (classList) {
            ...
        });

    });
});
```

Problem is at it block 'is testing shortcuts' in the second then block where I am using promise.all(), If do do not use promise.all() and just use a regular return (of a value or promise) control flow works fine. But the moment promise.all is encountered, the next it ('is editing') is executed.

**Comment by juliemr** [comment]
I suspect there is something else going on with your specific setup. I am able to successfully use promise.all in this example:

```js
describe('promise.all', function() {
  it('should greet the named user', function() {
    browser.get('http://juliemr.github.io/protractor-demo');

    $('div').click().then(function () {
      return protractor.promise.all([
          $('h3').getText(),
          $('h4').getText()
      ]);
    }).then(function (params) {
      console.log('A');
    });
  });

  it('does something else', function() {
    console.log('B');
  });
```

output
```
A
    ✓ should greet the named user (1606ms)
B
    ✓ does something else
```

Are you able to make a minimal reproducible example that we can run?

**Comment by jithin1987** [comment]
I found my issue. Problem was with me using promise from **require('selenium-webdriver');** using **protractor.promise** fixed control flow. Does protractor.promise do any extra processing?

**Comment by juliemr** [comment]
No, it doesn't. It's possible that you've got the `selenium-webdriver` module installed in two different places with conflicting versions.

In any case, closing this as solved!

**Comment by jithin1987** [comment]
Thank @juliemr, that explains it, I do have different ```selenium-webdriver``` versions from different dependencies.
