### ISSUE TITLE
Mocha onPrepare can't perform browser maximize()

### ISSUE THREAD

**Issue by lismdq** [angular/protractor#2064]
Hi everyone, I've researched how to maximize browser (Firefox or Chrome in my case) window and I found the following sentence: 

`browser.driver.manage().window().maximize();`

When I add that line to onPrepare function in conf.js using Mocha as framework

```
var spec = process.env.SPEC || './spec/*.spec.js';
var browser = process.env.BROWSER || 'chrome';
var slowThreshold = 5000;
var allScriptsTimeout = 20000;
var defaultPageLoadTimeout = 2000;
var mochaTimeout = 50000;
var firefox = require('protractor/node_modules/selenium-webdriver/firefox');
var firefox_profile = new firefox.Profile();
firefox_profile.setPreference('webdriver_accept_untrusted_certs', 'true');
var capabilities;
if ('firefox' === browser) {
  capabilities = {
      'browserName': browser,
    'firefox_profile': firefox_profile
  };
} else {
  capabilities = {
    'browserName': browser
  };
}

exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  allScriptsTimeout: allScriptsTimeout,
  baseUrl: 'https://localhost:3000',
  capabilities: capabilities,
  specs: [spec],

  framework: 'mocha',
  mochaOpts: {
    reporter: 'spec',
    slow: slowThreshold,
    timeout: mochaTimeout
  },
  onPrepare: function setup() {
    var chai = require('chai');
    var chaiAsPromised = require('chai-as-promised');
    console.log('########## PROTRACTOR ##########');
    chai.use(chaiAsPromised);
    global.expect = chai.expect;

    browser.driver.manage().window().maximize();
  }
};
```

I got the following error ```Cannot call method 'manage' of undefined``` in line of browser maximize.

I'm using Protractor 1.8.0 but I try with version 2 and the result is the same.

As I have read in Stack-overflow and other forums I guess that may be something related to Protractor or Mocha 

Thanks you

**Comment by hankduan** [comment]
The issue is that you overwrote the global `browser` variable with a string in your set up: `var browser = process.env.BROWSER || 'chrome';`. 

Then when you did `browser.driver.manage().window().maximize();`, `driver`

**Comment by lismdq** [comment]
Thanks @hankduan . Now it works fine.
