### ISSUE TITLE
export a .idea lib for WebStorm to help autocomplete

### ISSUE THREAD

**Issue by iPraetorian** [angular/protractor#2074]
I'm working through the tutorials and I'm seeing that there are a few instances where the method is undefined..I get the squiggly line and message: unresolved function or method getTitle(). Normally I could add libraries etc. but I'm having a difficult time with this one, not sure why I cannot find the correct library?
expect(browser.getTitle().toEqual('title of webpage');

**Comment by juliemr** [comment]
What editor are you using?

**Comment by iPraetorian** [comment]
I'm using WebStorm.
Thanks,

**Comment by juliemr** [comment]
@andresdominguez as our resident WebStorm expert, have you had trouble getting syntax highlighting with protractor?

**Comment by andresdominguez** [comment]
I have been thinking about generating an auto-complete library for tooling. It would be relatively easy to change the dgeni generator to build a mini idea lib just for auto-complete.

I will take a look at the generator.

**Comment by juliemr** [comment]
Cool. I'm going to relabel this as a feature request then.

**Comment by iPraetorian** [comment]
Closing this.
thanks,
