### ISSUE TITLE
Protractor dependencies not installed when using grunt-protractor-runner

### ISSUE THREAD

**Issue by kcelestine** [angular/protractor#2075]
I'm using grunt with protractor and it seems like all of the dependencies are not being installed.

package.json

	"devDependencies": {
	    "protractor": "0.23.0",
	    "grunt-protractor-runner": "~1.0.0"
	 }

Gruntfile.js

    protractor: {
	    options: {
		    ....
	    },
	    admin {
		    ...
		}
	}
```
git clone PROJECT_DIR; cd PROJECT_DIR
npm install
grunt protractor
```
```
Running "protractor:admin" (protractor) task
PROJECT_DIR/node_modules/protractor/lib/driverProviders/local.dp.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at PROJECT_DIR/node_modules/protractor/selenium/chromedriver.exe
    at LocalDriverProvider.addDefaultBinaryLocs_ (PROJECT_DIR/node_modules/protractor/lib/driverProviders/local.dp.js:42:15)
    at LocalDriverProvider.setupEnv (PROJECT_DIR/node_modules/protractor/lib/driverProviders/local.dp.js:59:8)
    at Runner.run (PROJECT_DIR/node_modules/protractor/lib/runner.js:375:31)
    at Object.init (PROJECT_DIR/node_modules/protractor/lib/launcher.js:243:12)
    at Object.<anonymous> (PROJECT_DIR/node_modules/protractor/lib/cli.js:129:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Fatal error: protractor exited with code: 8
```

From the grunt-protractor-runner [tutorial](https://www.npmjs.com/package/grunt-protractor-runner), I had to update the webdriver-manager ...
```
./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update
```
... but none of the node modules were there.
```
bash: ./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager: No such file or directory

ls ./node_modules/grunt-protractor-runner/
Gruntfile.js	LICENSE-MIT	README.md	package.json	tasks		test
```

So, I ran npm install, then updated the webdriver manager and that seemed to fix the problem.

```
cd ./node_modules/grunt-protractor-runner/

npm install; cd ../../

./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update

grunt protractor
```

**Comment by hasanyousuf** [comment]
add 
  "scripts": {
    "install": "node node_modules/protractor/bin/webdriver-manager update"
  }
to the end of package.json file.
after adding this you donot need to update webdriver-manager manually

**Comment by juliemr** [comment]
I have no idea why the file was not available initially. This seems like an `npm install` problem or something wrong with grunt-protractor-runner - that is definitely the file location under the `protractor` directory.

Could you bring this up with grunt-protractor-runner?

**Comment by c-johnson** [comment]
@hasanyousuf that solution worked great!  thank you :)
