### ISSUE TITLE
httpBackend set up in onPrepare does not work after 302 redirect

### ISSUE THREAD

**Issue by dragonflypl** [angular/protractor#2076]
I have a ```onPrepare```:
``` javascript
onPrepare: function(){
	browser.addMockModule('httpBackendMock', function() {
		angular.module('httpBackendMock', ['ngMockE2E', 'app'])
			.run(function ($httpBackend) {
				$httpBackend.whenGET("orderFlow/limits").respond(...);
				$httpBackend.whenGET(/.*/).passThrough();
		});
	});
}
```

My first test in suite, checks log in feature:

```javascript
it('should log in', function() {
	// browse to app, by default it is redirected to login page due to missing permissions
	browser.get(''); 
	element(by.id("j_username")).sendKeys(browser.params.login.username);
	element(by.id("j_password")).sendKeys(browser.params.login.password);
	// submit the form. As a result 302 is send back that navigates to app's Home page
	element(by.css(".login-button-submit")).click();
})
```

App's Home page does the call to ```orderFlow/limits```. And this call hits the server instead of returning ```httpBackend``` configured response.

What is interesting is that subsequent tests executed after login test also issue ```orderFlow/limits``` request, and these request do not hit the server - which is good. But it works **ONLY** if I add at least one ```browser.get(''); ``` call somewhere in the subsequent tests (so that browser has page that was fetched explicitly by Protractor, and not the one returned with 302).

Is it common issue with redirects? Or I'm doing something wrong?

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/issues/996
