### ISSUE TITLE
Rest call to fetch Json data

### ISSUE THREAD

**Issue by hasanyousuf** [angular/protractor#2077]
Hi!

I am new to protractor. I am working with E2E using grunt-protractor-runner. I want to use live data for testing and donot want to use mock objects. I need to fetch data from couchdb which is having Rest interface for communication. Is there any way to deal with this issue? I have tried two ways but unsuccessful.

Specifications:
node: v0.12.1
jasmine 1.3
npm 2.5.1

I tried to use request node module using
     var request = require('request');
            console.log("using Request");
            request('http://www.google.com', function (error, response, body) {
                console.log(body);
                if (!error && response.statusCode == 200) {
                    console.log(body); // Show the HTML for the Google homepage.
                }
            });

it did't work.

I used another package frisby
        it("it should fetch data from couchdb",function(){
            var frisby = require("frisby"),
             //var   restUrl='http://httpbin.org/get?param1=hello';
            var restUrl='https://ourserver.me:443/couch/mydatabase/';
            frisby.create('Access Couchdb')
                .get(restUrl)
                .after(function (err, res, body) {
                    console.log( body);
                    //expect(JSON.parse(body).args.param1).toMatch('hello')
                })
                .toss();
        });

I get in the body "Destination URL may be down or URL is invalid, Error: self signed certificate in certificate chain"

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!

**Comment by butzelbovat** [comment]
I have a similar Problem. I enter a value into a form and then submit the form. Now i get the HTTP Code 200 and a repsonse code. i never worked with such request / response. What do i need and how can i get the response code?
![2015-06-22](https://cloud.githubusercontent.com/assets/11351039/8281007/de5b86fc-18e3-11e5-87ca-a3ade4114f24.png)

**Comment by hasanyousuf** [comment]
Hi @butzelbovat !

I had the same problem using frisbyjs against couchdb. It is not the greatest way to resolve the issue but at least it resolved the same issue you have for me. Add to you Spec.

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
