### ISSUE TITLE
File upload not working with absolute URI

### ISSUE THREAD

**Issue by pjrostema-se** [angular/protractor#2081]
I think this issue might be the same one listed in [#612](https://github.com/angular/protractor/issues/612).  Since it hasn't moved in about a month I wanted to double check if my issue was the same.

I have a file that exists on the same machine that hosts a 3rd party site I depend on.  I want to upload that file to the 3rd party site so it gets deployed.

```javascript
var path = 'file:///C:/Program%20Files/App/bin/myFile.txt';
element(by.id('myFileInput')).sendKeys(path);
```

When I run this I get:

'Failed: unknown error: path is not absolute: file:///C:/Program%20Files/App/bin/myFile.txt'

The site is non angular, but I wouldn't think that would cause this.  I have checked pasting the URI straight into chrome and that seems to open the file just fine.

**Comment by andresdominguez** [comment]
What happens if you get rid of `file:///`

```javascript
var path = 'C:/Program%20Files/App/bin/myFile.txt';
element(by.id('myFileInput')).sendKeys(path);
```

**Comment by pjrostema-se** [comment]
Thanks! it looks like that makes the error go away.  

Clicking the submit button doesn't seem to want to upload the file for some reason. On further investigation I think it's because the 3rd party upload form is trying to do some fancy validation that doesn't play nicely with Protractor.  Anyway, Thanks for your help!
