### ISSUE TITLE
protractor ends immediately when run with jasmine2 with reference config file

### ISSUE THREAD

**Issue by jnizet** [angular/protractor#2085]
I just installed the latest version of protractor on a brand new project, and used the reference config file to start my tests, which defaults to jasmine2. And I searched for half an hour why my tests didn't run, although they passed fine when setting the framework to jasmine. 

I finally found why: because the default options contain

```
    // If set, only execute specs whose names match the pattern, which is
    // internally compiled to a RegExp.
    grep: 'pattern',
```

Sure, I should have read that with more attention, but in previous versions, just taking the default options and adapting the paths was sufficient to have the tests run fine. This new config option, on the other hand, basically excludes all the test files by default, which is not obvious. 

It would be nice to have a pattern here including everything by default, instead of excluding by default.

Another nice thing to have is to set chromedriver to

```
chromeDriver: './node_modules/protractor/selenium/chromedriver'
```
 by default instead of

```
chromeDriver: './selenium/chromedriver',
```

since webdriver-manager installs the chrome driver in `./node_modules/protractor/selenium/chromedriver`.

**Comment by juliemr** [comment]
The reference configuration file is not supposed to be a seed configuration file, but a reference of all options. It is not actually a valid configuration file.

This has caused confusion once in the past, so maybe we should add a disclaimer to the top.

**Comment by juliemr** [comment]
Done with 3bf0c5a972c77c8f7e2db7e849c8babeb7381d0b
