### ISSUE TITLE
Populating fields inside an element directive with Protractor

### ISSUE THREAD

**Issue by trazek** [angular/protractor#2087]
Consider the following view model:

    $scope.data = {};
    $scope.data.person = {};
    $scope.data.person.firstname = "";
    $scope.data.person.lastname = "";
    $scope.data.person.username = "";

and the following element directive:

    <custom-form-directive ng-model="data.person"></custom-form-directive>

which contains three input tags to display the data. How do I use protractor to populate the input fields by targeting `ng-model="data.person"`?

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
