### ISSUE TITLE
Calling expect(element).toBe("text") anywhere in the test hangs the browser

### ISSUE THREAD

**Issue by szimek** [angular/protractor#2091]
I had a test where I was incorrectly calling `expect(element).toBe("text")` instead of `expect(element.getText()).toBe("text")`. This line was at the end of the test, yet when I ran this test with this incorrect line in both Chrome and Firefox, it only opened the browser window with `data:,` URL and just hanged there without any error message. After a few seconds I got the following error
```
FATAL ERROR: JS Allocation failed - process out of memory
Abort trap: 6
```
without any stack trace or information what caused it. It would be awesome if such cases were handled somehow by Protractor and generated any kind of stack trace/error message that could hint at the error.

**Comment by hankduan** [comment]
I am not getting this.

Here's my test:
```javascript
  it('should fail', function() {
    browser.get('http://www.angularjs.org');
    element(by.model('yourName')).sendKeys('Hank');
    // expect(element(by.binding('yourName')).getText()).toBe('Hello Hank!');
    expect(element(by.binding('yourName'))).toBe('Hello name!');
  });
```

It fails with "Expected ...SOME_VERY_LONG_JSON_REPRESENTATION_OF_THE_ELEMENT_FINDER_OBJECT... to be 'Hello name!'" with the proper stack trace pointing to the issue, which makes the problem very obvious.

Can you show the set up you have that caused Protractor to run out of memory?

**Comment by juliemr** [comment]
Closing as stale.
