### ISSUE TITLE
Exposing protractor/node_modules/selenium-webdriver/remote.FileDetector via protractor object

### ISSUE THREAD

**Issue by jithin1987** [angular/protractor#2092]
remote.FileDetector is useful to do file upload to a browser running on a remote selenium server. Currently to use this one has to do 
```
remote = require('protractor/node_modules/selenium-webdriver/remote');
browser.driver.setFileDetector(new remote.FileDetector());
```
 It would have been ideal if remote is exposed via protractor. Something like ```browser.driver.setFileDetector(new protractor.remote.FileDetector());```

**Comment by jlin412** [comment]
Does it work for you?
I tried this with a .jpg file.  It is giving me some errors.

**Comment by jithin1987** [comment]
@jlin412 Yes, it works for me. I am using protractor 2.0.0

**Comment by sjelin** [comment]
Probably the best thing to do would be to include `selenium-webdriver` as a `devDependency` in your project and do something more like:

```js
remote = require('selenium-webdriver/remote');
browser.driver.setFileDetector(new remote.FileDetector());
```

Unfortunately we can't integrate every feature in selenium directly into protractor.  Is there some sort of documentation which would have been useful for you?

**Comment by jithin1987** [comment]
I wonder why I need to add selenium-webdriver again as a dependency when protractor itself has it. All I need is protractor to expose this remote which comes from the functionality of webdriver. Since protractor exposes webdriver already via browser.driver and also allows to call setFileDetector(), I would argue that it is better for protractor to expose all available detectors. Else we will have to track yet another dependency and make sure selenium-webdriver version in devDependency is uptodate with version protractor uses.

A document describing how to get a handle on remote filedetector would have been useful.

**Comment by sjelin** [comment]
I'm open to the idea of exposing more webdriver features, but it's important to keep in mind that webdriver has several separate files like this, and exposing each one would be a bit much.

The fact that Protractor depends on webdriver is sort of besides the point.  Protractor also depends on `q`, but you wouldn't access `q` by going `require('protractor/node_modules/q')`, nor is it Protractor's job to expose `q`.  Perhaps in the future `npm` and node will get more intelligent about sorting out redundant dependencies like this.

That said, protractor is supposed to serve as a replacement for `webdriver` in some sense, so if someone can think of a clean solution to this problem I'd be interested.

**Comment by juliemr** [comment]
@cnishina thoughts on how we should expose stuff that's in subfolders of selenium?

**Comment by cnishina** [comment]
This shouldn't be that hard to expose the subfolders of selenium under Protractor.

**Comment by cnishina** [comment]
After discussion (at desk) we will expose `remote`, `http`, and `firefox` subdirectories.
