### ISSUE TITLE
suppress basic authentication with through the url and e-mail as user with protractor 

### ISSUE THREAD

**Issue by npocmaka** [angular/protractor#2093]
usual way to suppress login us to use "user:password@somewhere.som". But this does not work when the username is an e-mail.  I've tried with "user%40email.com:password@somewhere.som" but does not work.  Is there a proper way to do this?

**Comment by npocmaka** [comment]
Appeared that I need unicode escaping instead of URI . So connection link should look like:
"user\u0040email.com:password@somewhere.som"

**Comment by npocmaka** [comment]
the unicode escape does not work with phantomjs  - may be should address issue there...

**Comment by hankduan** [comment]
What do you mean unicode escaping "doesn't work"? You are sending an unicode-escaped url and the ghostdriver is not resolvoing to the right url?

**Comment by npocmaka** [comment]
hellp hankduan ,

Not sure if the link is parsed properly as the protractor/phanotm hangs , with firefox and chrome browser just flashes for a moment (even without close() called) - even though I can see the link in the address bar.Tested against pages that do not require login everything is ok.
I've tried to escape the "@" with unicode uri encoding , both , double uriencoding but seems that using email as user name cannot be made work.

**Comment by juliemr** [comment]
It sounds like the only remaining issue here is with phantomjs. Can you open up an issue for them?
