### ISSUE TITLE
Report accessibility plugin results

### ISSUE THREAD

**Issue by david-gang** [angular/protractor#2096]
Hi all,

This is a crosspost from https://stackoverflow.com/questions/29913799/report-accessibility-plugin-results

I have the following protractor.conf

```javascript
// An example configuration file.
// https://raw.github.com/angular/protractor/master/example/conf.js



exports.config = {
    // The address of a running selenium server.
 //   seleniumServerJar: './node_modules/protractor/selenium/selenium-server-standalone-2.41.0.jar', // Make use you check the version in the folder
    //seleniumAddress: 'http://localhost:4444/wd/hub',
    // Capabilities to be passed to the webdriver instance.
    capabilities: {
        'browserName': 'chrome'
    },
    framework: "jasmine2",
    onPrepare: function() {
        var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            filePrefix: 'xmloutput',
            savePath: 'testresults'
        }));
    },
    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000
    },
    plugins: [{
        chromeA11YDevTools: true,
        path: 'node_modules/protractor/plugins/accessibility'
    }]
};
```

Is it possible to configure protractor so that the jasmine-reporter will report also the results from the accessibility plugin?
If not, could this be a valid feature request?

Thanks,
David

**Comment by juliemr** [comment]
This is not possible with the plugin framework. The problem is that plugins are agnostic to the test framework being used, so they do not emit test results in a way specific to jasmine-reporters.

You can get all test and plugin results in JSON format using `resultJsonOutputFile` in the config. I'd suggest doing that, and then processing it in any way you need.
