### ISSUE TITLE
ECONNREFUSED error

### ISSUE THREAD

**Issue by zaknuces** [angular/protractor#2097]
I am trying to use 'http' in onPrepare function and its giving me the following error:

Error: Error: connect ECONNREFUSED
at ClientRequest.<anonymous> (...)
at ClientRequest.emit (events.js:107:17)
at Socket.socketErrorListener (_http_client.js:271:9)
at Socket.emit (events.js:107:17)
at net.js:459:14
at process._tickCallback (node.js:355:11)

Following is my code:

return q.fcall(function() {
    http.get({
	url: 'urlToGo',
	qs: {customerName: browser.params.tenant}
    }, function (response) {
	// all good
    }).on('error', function (e) {
		throw new Error(e);
    });
});

I have already checked that 'urlToGo' is a valid url. The url can be accessed via POSTMAN as well. But, when i am trying to access it from Node http, it is causing an error mentioned above.

**Comment by juliemr** [comment]
can you access it from a simple node script outside of the context of protractor?

**Comment by juliemr** [comment]
Closing as stale. Please file a new issue if you believe there is still a general problem.
