### ISSUE TITLE
After update of Protractor and WebDriver browser.wait stop working

### ISSUE THREAD

**Issue by sisillV** [angular/protractor#2098]
Hi,
I update my Protractor from 1.4 to 2.0 and upgrade my webdriver to 2.45 and my browser.wait function stop working.

function waitForElementIsPresent(element) {
		return browser.wait(function () {
			console.log('wait');
			return element.isPresent();
		});
	}
Before the update - function really wait for the element, now after a second it give me error: 
"Error: Wait timed out after 248ms".

Please help me! All my tests don't work any more!

**Comment by jlin412** [comment]
I saw in other thread that you will need to add the second argument timeout
in millisecond.  It used to wait forever like 15~30 minutes if no default
set.  Now, we are forced to set a default.  In my opinion, this is the
right approach.  You never know that the condition may never be fulfilled.

**Comment by sisillV** [comment]
Please tell me how can I set default timeout for browser.wait function?

**Comment by smahalingam** [comment]
Please see following thread, 
https://github.com/angular/protractor/issues/2086

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
