### ISSUE TITLE
ECONNREFUSED error when running tests in parallel

### ISSUE THREAD

**Issue by imavroukakis** [angular/protractor#2105]
I configured protractor to shard and run my tests in parallel. Whilst all tests run and complete when configured for a single capability, I'm getting `ECONNREFUSED connect ECONNREFUSED` on most of them when running in parallel. The configuration is

```
multiCapabilities: [{
        browserName: 'chrome',
        shardTestFiles: true,
        maxInstances: 2
    }]
```

Protractor version is 2.0.0

**Comment by imavroukakis** [comment]
Unsurprisingly, It turns out it's something I did wrong. There's a `pkill` statement in my cleanup that's there to kill any hung chromedrivers. When the tests run in parallel, the first one that returns kills all the other sessions.

**Comment by hankduan** [comment]
Looks like this is a non-issue. Closing.
