### ISSUE TITLE
onAbort event

### ISSUE THREAD

**Issue by svapreddy** [angular/protractor#2107]
Is there any way I can detect user exited protractor tests manually using OS options. I think `onComplete`, `onCleanup` does not work for for this case.

It will be useful incase if user is adding few things on launch and want to clear them on exit. When user closes it, protractor or selenium closes all the open browser windows. At that context if onAbort event is fired, it helps a lot to clean up things

Thanks

**Comment by hankduan** [comment]
If you set up something (i.e. app server) in `beforeLaunch`, you should close it in `afterLaunch`. See https://github.com/angular/protractor/blob/master/docs/referenceConf.js. Please let me know if it doesn't address your needs, otherwise I'll close this issue in a few days.

**Comment by svapreddy** [comment]
`afterLaunch` is not called when it exited.

**Comment by hankduan** [comment]
Can you provide your set up? If you put a console.log in afterLaunch it doesn't print?

**Comment by svapreddy** [comment]
@hankduan afterLaunch is working when protractor itself has closed after everything is completed. But when user explicitly closed using Cmd + C or some other command or using close button, it is closing all browser windows but afterLaunch is not executed. I am afraid if this is a limitation.

**Comment by svapreddy** [comment]
@hankduan Thanks for feature request tag. Hope it will be resolved in future node versions. I have observed this of feature in ruby thin server. It quite useful to clean things up after exit or close.

**Comment by juliemr** [comment]
Cleaning up our issues - closing this as unfeasible given that we run with node.
