### ISSUE TITLE
protractor.getInstance() is undefined

### ISSUE THREAD

**Issue by mato75** [angular/protractor#2108]
var ptor;
	beforeEach(function () {
		browser.get('http://localhost:8383/v2');
		ptor = protractor.getInstance();
	});

.getInstance() is undefined

**Comment by hankduan** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks! 

FYI, http://stackoverflow.com/questions/27690814/object-object-has-no-method-getinstance-when-trying-to-run-protractor-tests
