### ISSUE TITLE
Docs List of features which are not testable without protractor

### ISSUE THREAD

**Issue by svanschu** [angular/protractor#2109]
Hi,

normaly I would just take the test environment of angular, but we have a lot of products, only one with angular and we are trying to create one test environment for all products. That's why I search for angular features which are only testable with protractor.

I looked for a list of arguments and couln't find one (if there is one sorry for issuing it). I thought there should be a easy list/table, which shows the difference between with protractor and without. Like you can't test a slider without protractor, because you need access to the data-binding, to get the changed value ...

It's just my opinion, because there are more projects or companys which are starting with angular and are discussing, if they should use their testtool or protractor and who could make a better list of arguments then the people creating it.

**Comment by hankduan** [comment]
Protractor simply uses webdriver to do everything, so there isn't anything Protractor can do that webdriver cannot. 

The being said, the main purpose of Protractor is allow you to do those things easier and with better syntax.
