### ISSUE TITLE
Turn debugInfo On for protractor 

### ISSUE THREAD

**Issue by acostaf** [angular/protractor#2116]
I am disabling debugInfo ($compileProvider.debugInfoEnabled(false)) but I don't know how turn debugInfo back on when running protractor

I have already try to use angular.reloadWithDebugInfo() on onPrepare the same way I disable Animations but with not luck

**Comment by christianrondeau** [comment]
What I did in `onPrepare` was to set directly `window.name` to `NG_ENABLE_DEBUG_INFO`, which is what `reloadWithDebugInfo` seems to actually do.

Here's my code:

```
browser.executeScript('window.name = "NG_ENABLE_DEBUG_INFO"');
```

That seems to do the trick (until now... because this is not documented by the Angular team, I don't know how reliable that will be in the future)

**Comment by sjelin** [comment]
I would suggest trying what @christianrondeau said, or using some other sort of `executeScript` in your `onPrepare` which sets some global variable telling `$compileProvider.debugInfoEnabled(false)` not to run.  If that doesn't work, then once #2104 is merged in you could solve this problem with a plugin which sets some sort of global variable in `onPageLoad`.

Also, please ask questions on stackoverflow

**Comment by gkohen** [comment]
I've added a question in [StackOverflow](http://stackoverflow.com/questions/30867969/how-to-protractor-test-an-angular-application-which-has-debuginfoenabled-enabled/30867970#30867970) pointing to @christianrondeau 's solution with a follow-up question on if we can utilize Angular's `angular.reloadWithDebugInfo`method. Any ideas?

**Comment by christianrondeau** [comment]
I could not find a better solution; for Protractor to "connect" to AngularJS, debug has to be enabled, and onPrepare is called *before* your AngularJS app has been loaded, so it's a chicken and egg situation. @gkohen I added it as a comment to StackOverflow too.

**Comment by gkohen** [comment]
@sjelin  and @christianrondeau  I've added a [PR](https://github.com/angular/protractor/pull/2261) related to this issue.

**Comment by akshaybapat** [comment]
Another way to go about this in your protractor code is, right after logging in or at the point you are fairly convinced angular is loaded in the browser, just add the following code to your protractor tests:

browser.executeScript('angular.reloadWithDebugInfo()');
