### ISSUE TITLE
browser.executeScript timeout Error after Protractor 2.0 update

### ISSUE THREAD

**Issue by KilicY** [angular/protractor#2119]
After we updated to Protractor 2.0, we get an error for our test specs. As our application is available in multiple languages, our test specs are also written for multiple languages. So before the test specs starts, it must know which language is set in the browser.

So we get the locale string during the init protractor step:

	browser.localeStringPromise = browser.executeScript('return foo.localeString').then(function (key) {
			localeKey = key;
	//...
	}
localeKey is global variable, which is asked in the test specs for language identifications. 

and our onPrepare function within the protractor.conf.js looks like 

	onPrepare: function () {		
		initProtractor();
		//..
		return browser.localeStringPromise;
	}

So the test specs don't run until the locale key promise is resolved.

As I said before we updated protractor, all test specs passes smoothly with chrome. Now during the browser.executeSript step, protractor throw this error in the stacktrace:

		/$SPECPATH/e2e/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1877
      var result = fn();
                   ^
		Error: Wait timed out after 7268ms

Timeout varies on each run.

**Comment by hankduan** [comment]
A few things: 

- Does your onPrepare call out to `browser.get`? If not, you might have to use `browser.driver.executeScript`. 

- Double check that there is no other change besides upgrading to 2.0. (i.e. does downgrading protractor fix the problem)

- I can't really help by looking at just these snippets. Can you post the full (even better is a reduced case) conf/onprepare/spec?

- Just as a general comment, it's probably better for you to pass the locale into your test instead of relying on figuring it out in the beginning of the test.

**Comment by KilicY** [comment]
Hi Hankduan,
thanks for the quick response. First of all I solved the problem. It is not the <code>browser.executeScript</code>. When I was snipping the code for you, I found the problem. In onPrepare, we have doLogin() function. Before each testspec, you must login to our webApp. This function returns a Promise, which is true when successfully logged in. It looked like this:

<code>

var loginPromise;

function __doLogin(username, pwd, forceLogin) {

	if (loginPromise && forceLogin !== true) {
		return loginPromise;
	}

	if (!username || !pwd) {
		throw 'MISSING_ARGUMENT_EXCEPTION';
	}

	var loginDeferred = protractor.promise.defer(),		
		baseUrl = browser.params.baseUrl,
		loginUrl = require('url').resolve(baseUrl, 'login');

	loginPromise = loginDeferred.promise;
	browser.driver.get(loginUrl);

	loginView.getLoginNameEl().sendKeys(username);
	loginView.getPasswordEl().clear();
	loginView.getPasswordEl().sendKeys(pwd);
	loginView.getSubmitButtonEl().click();
//CRASHING HERE
	browser.driver.wait(specificPromiseToWaitFor).then(loginDeferred.resolve); 


	return loginPromise;
}
</code>

So after I set a specific value for the timeout in <code>browser.driver.wait</code> like this:

<code>
browser.driver.wait(specificPromiseToWaitFor, 35000).then(loginDeferred.resolve); 
</code>

the test specs run succesfully (besides the breaking changes with the element locator)

Thanks for your help!
Best Regards
