### ISSUE TITLE
In the locators document the Protractor specific locator link does not work

### ISSUE THREAD

**Issue by gkohen** [angular/protractor#2120]
Hi,
On the [Locators document](https://github.com/angular/protractor/blob/master/docs/locators.md) the link to "For a list of Protractor-specific locators, see the Protractor API: ProtractorBy." does not work.
It should point to : http://angular.github.io/protractor/#/api?view=ProtractorBy (Or the equivalent in github)
Instead it's pointing to: 
https://github.com/angular/protractor/blob/master/docs/locators.md#/api?view=ProtractorBy

Thanks.

**Comment by sjelin** [comment]
Thanks for finding this!  Just made #2140 which will fix this
