### ISSUE TITLE
Cucumber reports with Jenkins

### ISSUE THREAD

**Issue by gziebold** [angular/protractor#2121]
There is a plugin with Jenkins that allows for a nice presentation of Cucumber tests (https://wiki.jenkins-ci.org/display/JENKINS/Cucumber+Test+Result+Plugin).  I've used this kind of thing in the past while using Cucumber-JVM with something like this:

@Cucumber.Options(format = {"pretty", "html:target/cucumber", "json:target/cucumber.json"}

Is it possible to do something similar with protractor...something like this:

  cucumberOpts: {
    format:  ['pretty', 'html:target/cucumber', 'json:target/cucumber.json'],
  }

And this:

  cucumberOpts: {
    format: "pretty",
    output: "path/file.json"
  }

Neither work.  

Anyone been able to get this to work?

**Comment by sjelin** [comment]
Not sure, but please ask questions on stackoverflow
