### ISSUE TITLE
node errors invisible with protractor 

### ISSUE THREAD

**Issue by nishakchaudhari** [angular/protractor#2131]
I had some regex error in my test case code.
code which has error : `var devDocs = new RegExp('*something');`
when I ran the test case, instead of showing me the error (cause of program exit),
It just gave me the following message -
```
[launcher] BUG: launcher exited with 1 tasks remaining0
```

Its very hard to debug with this type of error.
Instead it should give me following error and then exit:

```
SyntaxError: Invalid regular expression: /*something/: Nothing to repeat
    at new RegExp (native)
```

Can we fix this?

**Comment by sjelin** [comment]
Where do you have this error?  In your spec files?  I get a stacktrace just fine.

**Comment by juliemr** [comment]
I think this is due to asynchronous errors never being caught by promises. See this old issue: https://github.com/angular/protractor/issues/1772

**Comment by nishakchaudhari** [comment]
sorry for late reply... I have this error in my test case not in spec file.
In protractor-source code, launcher.js file line :179 
process.on('exit', function(code) {
      if (code) {
        log_('Process exited with error code ' + code);
      } else if (scheduler.numTasksOutstanding() > 0) {
        log_('BUG: launcher exited with ' +
          scheduler.numTasksOutstanding() + ' tasks remaining');
        process.exit(RUNNERS_FAILED_EXIT_CODE);
      }
    });

Here only the error code is considered. we should also display
process.stdout and process.stderr to get more info about errors and output.

Please correct me if I am wrong and suggest any workaround this?

**Comment by sjelin** [comment]
I think the stacktrace gets logged in a different part of the code.

Could you provide me with the entire file containing `var devDocs = new RegExp('*something');`?  Because when I put it into one of my test files the correct error logging comes up just fine.

**Comment by juliemr** [comment]
I'm closing issues as stale. If there is still a reproducible problem, please open a new issue!
