### ISSUE TITLE
Protractor 2.0 hangs on browser.pause()

### ISSUE THREAD

**Issue by jonricaurte** [angular/protractor#2133]
When adding a browser.pause(), I get to this point:

------- WebDriver Debugger -------
 ready

press c to continue to the next webdriver command
press d to continue to the next debugger statement
type "repl" to enter interactive mode
type "exit" to break out of interactive mode
press ^C to exit

And then nothing happens. It just hangs there for a few minutes without it doing anything.

**Comment by mal90** [comment]
@jonricaurte i had the same issue , but after updating to the latest , the issue was solved . i suggest you to have a look at https://github.com/angular/protractor/issues/2044 .

**Comment by hankduan** [comment]
Sorry for the issue. #2044 fixes it (pending release)

**Comment by CodeTrol** [comment]
when next release will be?

**Comment by hankduan** [comment]
Hopefully next week.
