### ISSUE TITLE
Tests fail with message: "Error while waiting for Protractor to sync with the page: "Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by haroldcampbell** [angular/protractor#2135]
When running the tests, I am consistently getting the above message.

The error is occurring in the protractor/lib/protractor.js file:

```
Protractor.prototype.waitForAngular = function(opt_description) {
  var description = opt_description ? ' - ' + opt_description : '';
  if (this.ignoreSynchronization) {
    return webdriver.promise.fulfilled();
  }
  return this.executeAsyncScript_(
      clientSideScripts.waitForAngular,
      'Protractor.waitForAngular()' + description,
      this.rootEl).
      then(function(browserErr) {
        if (browserErr) {
         /* ERROR OCCURS HERE */
          throw 'Error while waiting for Protractor to ' +
                'sync with the page: ' + JSON.stringify(browserErr);
        }
    }).then(null, function(err) {
      /* ... deleted for brevity */
    });
};
```

If this line is commented, the tests function as expected (passing and failing when they should).

Has anyone else had this problem?

My system is as follows:
Protractor: 2.0.0, (commit: 1d8f14e)
Chrome: 41.0.2272.118
ChromeDriver: 2.14.313457
Selenium-webdriver: 2.45.0

**Comment by sjelin** [comment]
This seems like it's a bug in your webapp of some kind, though it's not clear to me exactly what.  Is that the full error message?

Also: Please ask questions on stackoverflow.
