### ISSUE TITLE
Firefox does not recognize directive for dropdown

### ISSUE THREAD

**Issue by chocochik92** [angular/protractor#2136]
I have some dropdowns on my page that open by using directives. They open in Chrome but in Firefox (I'm using 34.0) it shows the element being clicked but the dropdown doesn't open. Here's the html for the dropdown and the error I get:

    <ul class="main-nav-btn-left unselectable">
        <li class="welcome-username" drop-menu>
            <div drop-menu-toggle>
                <p class="username">{{userName }}</p>
            </div>
            <ul class="select-dropdown">...</ul>
        </li>
    </ul>

`Failed: Element is not currently visible and so may not be interacted with Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50' System info: host: 'Amandas-MacBook-Pro.local', ip: '192.168.1.166', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.3', java.version: '1.7.0_79' Driver info: driver.version: unknown`

And here's the directive

    function dropMenuToggle() {
        var directive = {
            require: '?^dropMenu',
            link: link
        };
        return directive;

        function link (scope, element, attrs, dropMenuCtrl) {
            var isOpenWatcher;
            if (!dropMenuCtrl) {
                return;
            }
            dropMenuCtrl.toggleElement = element;
            var toggleDropdown = function toggleDropdown (event) {
                event.preventDefault();
                if (!element.hasClass('disabled') && !attrs.disabled) {
                    dropMenuCtrl.toggle();
                }
            };
            element.bind('click', toggleDropdown);
            isOpenWatcher = scope.$watch(dropMenuCtrl.isOpen, function dropMenuToggleIsOpenWatcher (isOpen) {
                element.attr('aria-expanded', !!isOpen);
            });
            scope.$on('$destroy', function dropMenuToggleDestroyScope () {
                if(_.isFunction(isOpenWatcher)){
                    isOpenWatcher();
                }
                element.unbind('click', toggleDropdown);
            });
        }
    }

**Comment by sjelin** [comment]
Well, is the element visible?

**Comment by chocochik92** [comment]
It's supposed to be visible when the button is clicked. Here's my test:

     var username = element(by.css('.welcome-username'));
     username.click();
     var dropdown = element(by.css('ul.select-dropdown'));
     expect(dropdown.isDisplayed()).toBeTruthy();

**Comment by eolognt** [comment]
@chocochik92 If you watch what is done in the browser when running Protractor you should be able to see if the element is visible to the user or not and tell if the specs should really fail or if you're test code is poor.

**Comment by juliemr** [comment]
Closing stale issues. Please open a new issue if you feel there is still a general bug.
