### ISSUE TITLE
ExpectedConditions.elementToBeClickable doesn't account for other elements covering the target

### ISSUE THREAD

**Issue by hgted** [angular/protractor#2139]
In the following:

	var element = $('#div');
	browser.wait(protractor.ExpectedConditions.elementToBeClickable(element), 5000, 'Element not clickable');
	element.click();

If `$('#div')` is covered by another element `element.click()` results in a selenium error:

> unknown error: Element is not clickable at point (10, 10). Other element would receive the click: \<div id="cover">...\</div>

Even through `browser.wait(protractor.ExpectedConditions.elementToBeClickable(element), 5000, 'Element not clickable')` does not result in an error.

**Comment by jlin412** [comment]
I definitely see this behavior as well and want to see this fixed.
Currently, I use EC.and(EC.elementToBeClickable(element),
EC.invisibleOf(overlayElement)) as a workaround.

**Comment by juliemr** [comment]
Correct, right now `elementToBeClickable` just checks that it's visible and enabled.

**Comment by hankduan** [comment]
I don't think there is anything that can be done here unless webdriver exposes an API that returns all elements for a particular coordinate. Also, for reference, the behavior is consistent with Java and Python's expected condition libraries (i.e. https://code.google.com/p/selenium/source/browse/java/client/src/org/openqa/selenium/support/ui/ExpectedConditions.java)

**Comment by sjelin** [comment]
We would address this using [`document.elementFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) and [`element`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) pretty easily actually.  The consistency issue is real though

**Comment by dbartholomae** [comment]
Hi there, I ran into the same issue. How about adding something like elementNotToBeCovered? That way the functionality would be easily available without creating inconsistencies :-)

**Comment by sjelin** [comment]
@hankduan thoughts on @dbartholomae's suggestion?

**Comment by hankduan** [comment]
Closing this issue in favor of the more specific issue https://github.com/angular/protractor/issues/2313

**Comment by alllx** [comment]
I have wrote small check utility method, keep in mind it will click on element immediately when it become clickable:

   ```
 import { ElementFinder, promise } from 'protractor';
    
    export let testHelpers = {
      isClickable(el: ElementFinder): promise.Promise<boolean> {
        return new promise.Promise(resolve => {
          let interval = setInterval(() => {
            el.click().then(() => {
              clearInterval(interval);
              setTimeout(() => {
                resolve(true);
              }, 500);
            }, () => { });
          }, 100);
        });
      }
    }
```
In your test code:
    ```
import { testHelpers } from '../src/core/e2e/helpers';

    describe('App', () => {
      it('should do something', () {
        let btn = $('.cls');
        browser.wait(testHelpers.isClickable(btn), 3000);
      });
    });
```

**Comment by amilbeck** [comment]
@alllx Out of curiousity, why are you resolving inside the `setTimeout`? I think you're solution will work for what I'm trying to do with a slight modification. Just curious why you are resolving the promise this way before I implement.

**Comment by alllx** [comment]
Hi @amilbeck sorry, for now, I don't remember there was some delay needed, was tested only in Chrome. Maybe now in newer versions, it is don't needed.

**Comment by xiaoxiaofeixiang** [comment]
Failed: Cannot click on element
    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
    System info: host: 'DESKTOP-RPOSEHB', ip: '192.168.12.227', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.2'
    Driver info: driver.version: unknown
  Stack:
    MoveTargetOutOfBoundsError: Cannot click on element
    who can help me
