### ISSUE TITLE
Add an example of "executeScript" passing in a regular function

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2143]
[How can I interact directly with the JavaScript running in my app?](https://github.com/angular/protractor/blob/master/docs/faq.md#how-can-i-interact-directly-with-the-javascript-running-in-my-app) section of the FAQ provides an example of `executeScript()` with a js code passed in as a string:

    browser.executeScript('your script as a string')

But, it is possible to pass in a regular function also, e.g. getting all element's attributes:

```javascript
function getAllAttributes (arguments) {
    var items = {}; 
    for (index = 0; index < arguments[0].attributes.length; ++index) { 
        items[arguments[0].attributes[index].name] = arguments[0].attributes[index].value; 
    }
    return items;
}

browser.executeScript(getAllAttributes, elm).then(function (attrs) {
    console.log(attrs);
});
```

With the absence of multi-line strings in js (as e.g. triple quotes in Python) - this becomes important when it comes to multi-line js code needed to be executed.

It would great if protractor docs would mention it. What do you think?

**Comment by juliemr** [comment]
Sure, feel free to send us a PR updating the docs!
