### ISSUE TITLE
make possible configure a different baseurl for each capability configuration

### ISSUE THREAD

**Issue by evilaliv3** [angular/protractor#2148]
While working on [GlobaLeaks](github.com/globaleaks/GlobaLeaks) an integrating our unit test environment with Saucelabs we are facing the need to run multiple tests in parallel launching multiple instances of the application with different listening tcp ports: https://github.com/globaleaks/GlobaLeaks/issues/1274

This would require having the possibility to instantiate protractor with different per-capability baseUrls.

I think this would be a valuable possibility for all the projects.

Currently we are trying to tackle the issue with the following configuration: https://github.com/globaleaks/GlobaLeaks/blob/issue/1274/client/tests/glclient/protractor-sauce.config.js

    // for each run we need a different port;
    //
    // for the list of usable ports read:
    // - https://docs.saucelabs.com/reference/sauce-connect/
    capabilities = [
      { port: "2000", browserName: "firefox", platform: "Linux" },
      { port: "2001", browserName: "firefox", platform: "OS X 10.10" },
      { port: "2020", browserName: "firefox", version: "36.0", platform: "Windows 8.1" },
      { port: "2109", browserName: "firefox", version: "37.0", platform: "Windows 8.1" },
      { port: "2310", browserName: "chrome", platform: "Linux" },
      { port: "3000", browserName: "chrome", platform: "OS X 10.10" },
      { port: "3001", browserName: "chrome", version: "37.0", platform: "Windows 8.1" },
      { port: "3030", browserName: "chrome", version: "38.0", platform: "Windows 8.1" },
      { port: "3210", browserName: "chrome", version: "39.0", platform: "Windows 8.1" },
      { port: "3333", browserName: "chrome", version: "40.0", platform: "Windows 8.1" },
      { port: "4000", browserName: "chrome", version: "41.0", platform: "Windows 8.1" },
      { port: "4001", browserName: "chrome", version: "42.0", platform: "Windows 8.1" },
      { port: "4040", browserName: "safari", platform: "OS X 10.10" },
      { port: "4321", browserName: "internet explorer", version: "11", platform: "Windows 8.1" }
    ]

      onPrepare: function() {
        // hack needed in order to change the baseUrl at each run
        browser.getProcessedConfig().then(function(config) {
          browser.baseUrl = 'http://127.0.0.1:' + config.capabilities.port + '/';
        });
      }

anyhow this solution seems to work only partially and we are facing various non understandable errors: https://saucelabs.com/u/globaleaks

what would be the right solution?

**Comment by evilaliv3** [comment]
i've currently solved in this way: https://github.com/globaleaks/GlobaLeaks/issues/1274

the solution would be relevant as suggestion for other projects.

**Comment by sjelin** [comment]
The problem with your current solution is basically that you're setting baseUrl too late.

Another approach would be to have a template config, something like:

```js
module.exports = function(capability, port) {
  return {
    ...
    capabilities: [capability],
    baseUrl: 'http://127.0.0.1:' + port + '/',
    ...
  };
}
```

And then have other config files like:
```
module.exports = require('./template')({ browserName: "firefox", platform: "Linux" }, 2000})
```

Would this suit your needs?

**Comment by evilaliv3** [comment]
yep i think so sjelin, thanks

was i was suggesting is more to add an internall feature to protractor in order to run each browser test on a different port given a battery of ports.

anyhow this is how i've currently fixed for globaleaks, by also parallelizing the tests:
https://github.com/globaleaks/GlobaLeaks/blob/devel/.travis.yml
https://github.com/globaleaks/GlobaLeaks/blob/devel/client/tests/glclient/protractor-sauce.config.js

this would be probably of interest of other users

**Comment by juliemr** [comment]
I think your solutions here are good. I would like to keep the configuration file as simple as possible, and I think that the simpler solution in this case is to use a template configuration and generate multiple config files, or name the capabilities and change the URL within each test.
