### ISSUE TITLE
Setting Safari browser window size

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2151]
Hi,
Im able to set the chrome window size using the chromeOptions
```
chromeOptions : {
     args: ['--lang=en','--window-size=1024,768']
 }
```
Is there a way to do the same in Safari too. Im trying to run the tests in different browsers with different window sizes.

Thank You.

**Comment by sjelin** [comment]
Use [`browser.window.setSize`](http://angular.github.io/protractor/#/api?view=webdriver.WebDriver.Window.prototype.setSize)

**Comment by spatchamatla** [comment]
@sjelin The problem is setting the browser size error'd out when i try to run in iPad safari, so im looking for, if there is any options to set the size of the browser in the capabilities itself.

**Comment by sjelin** [comment]
Not to my knowledge, which isn't that extensive.  I would just detect if you're on iPad safari and not use browser.window.setSize in that case
