### ISSUE TITLE
Identify the step number were protractor test failed 

### ISSUE THREAD

**Issue by rayeesnp** [angular/protractor#2156]
I am developing tightly coupled Protractor + Jasmine automation system with our test cases management system.

Steps in test procedure also documented in test script also, when ever protractor test cases fails, I want to identify in which step this is failed and reported in XML

example Test expected like this

@step1 login_page.enterUserName('user1');

@step2 login_page.enterPassword('password');

@step3 home_page = login_page.selectLogin();

If this test failed @ step2, this should be reported in XML ,any thought for implementing this ?

Regards, Rayees

**Comment by sjelin** [comment]
Use a jasmine reporter.

**Comment by rayeesnp** [comment]
Not sure why this ticket is closed ???? I am using jasmin already , requesting for new feature in protractor if does not exist

**Comment by sjelin** [comment]
Oh, sorry, I didn't realize that it's not the most straight-forward process to install a jasmine reporter in protractor.

**Comment by sjelin** [comment]
Ok, here's what you do:

In your `onPrepare`, you should be able to do something like

```js
jasmine.getEnv().addReporter(yourReporter)
```

Where your custom reporter follows the spec from http://jasmine.github.io/2.1/custom_reporter.html

Let me know if that handles your needs

**Comment by rayeesnp** [comment]
@sjelin  I have already provided reported in spec file 

I am not sure, they  feature should be from Protractor Or Jasmine, here is my use case

My test cases name "Loginto_system_and_checkvaliduser"

Procedure in Testcase management system 
Step 1 : Enter URL
Step 2 : Enteruser Name
Step 3 : Enter Password
Step 4: Select Submit button 
Step 5: Verify user is valid or not

Steps in javaScript

login_page = accessURL(https://.......)
login_page.enterUserName('user1');
login_page.enterPassword('password');
home_page = login_page.selectLogin();
homa_page.verify()

During the automation run, if test case failed at "step 4" ie home_page = login_page.selectLogin(); it should be able to identify which step its failed "here its 4", based on this I want to create JIRA ticket with the summary "Test cases Loginto_system_and_checkvaliduser failed at step4 ", while creating JIRA ticket i will pull actual steps from test case management system.

Here the advantage is developer no need to go and re run the test to reproduce the issue, they can map the step number were automation failed and corresponding test case in Test case management system ?

It make sense ? @sjelin

**Comment by rayeesnp** [comment]
@juliemr  any thoughts or suggestion ??

**Comment by juliemr** [comment]
You should be able to find the line of failure from the stack trace of the error. Is this not working for you?

**Comment by rayeesnp** [comment]
Stacktrace work, it will give at which line test case failed but i want to know in which step the test case failed, script line get change always , 

If you look the scenario i mentioned above you must be clear what I am looking, please let me know if that is not clear enough

**Comment by juliemr** [comment]
I assume you don't have actual `@step1` annotations in your code, since you say you are using Jasmine and not some crazy extension to JS which would allow annotations like that. So I don't understand what else you need. The line in your test should be somewhere in the stack trace, and you should be able to parse it out.

**Comment by rayeesnp** [comment]
Yes I am using jasmine only 

@Step 1 is example i mentioned here, I am thinking is there any way protractor can extend functionality to identify the failure based on annotation like @Step instead of parsing stacktrace , then identify the line number then find corresponding step for that failure like number

**Comment by juliemr** [comment]
What are you using to parse annotations?

**Comment by rayeesnp** [comment]
As i said earlier currently i dont have any annotation like @Step in my script, my request is it possible to implement this in protractor and based on this annotation report the failure 

example in javascript file 

line 1    @ Step 1 
line 2    some protractor script ..
line 3     .......
line 4     ......
line 5   @ Step 2 
line 6    some protractor script ..
line 7    .......

If test case failed at line 7, protractor should report failed with message, test failed at Step 2

**Comment by juliemr** [comment]
Ah, I see what you are asking. Implementing annotations is out of scope for Protractor, sorry. We won't be implementing any changes to JavaScript.

Depending on what you need, you could get similar behavior by putting each step into its own `it` block. They always run in order in Jasmine:

```
it('should do the first step', function() { ... });
it('should do the second step', function() {...});
```

I'm going to close this since it's out of scope.

**Comment by rayeesnp** [comment]
If i go with your suggestion, then each step will be consider and different test case, i dont want to do this.

Another option i can think, after complete test case, get line number for this specific test case and scan the test script again and identify this test is under which step, but its not quite straight forward and i dont like :(
