### ISSUE TITLE
Error in function invoked in browser.controlFlow().execute() closes browser but masks error making test pass

### ISSUE THREAD

**Issue by jonsamwell** [angular/protractor#2158]
Hi,

I am using the browser.controlFlow().execute() method to go to a page and fill in some input.  However I have noticed that it if the function passed to the execute method errors (in my case a InvalidElementStateError) the test stops but no error is written to the console and the test to passes.  Simple code to reproduce below.

```javascript
describe('As a user I can login', function() {
  function populate(el, data) {
    el.sendKeys(data);
  }

  it('should allow the user to login', function() {
    function executeLogin() {
      var defer = protractor.promise.defer();
      browser.get('http://app.app.com#/login');

      var submitButton = element(by.css('#sumbitButton'));
      var emailControl = element(by.model('vm.model.email'));
      // for the test ensure this control is readonly so a InvalidElementStateError should be thrown
      // when the code tries to enter a value into it.
      var passwordControl = element(by.model('vm.model.password'));

      populate(emailControl, 'me@gmail.com');
      passwordControl.clear(); //this function seems to be the problem and masks the error
      populate(passwordControl, 'password');

      // the browser will exit but no error is logged in the console (in webstorm) and the test passes!
      submitButton.click().then(function() {
        defer.fulfill();
      }, defer.reject);

      return defer.promise;
    }

    browser.controlFlow().execute(executeLogin);
  });
});
```

I'm not sure what I am doing wrong and if this is expected behaviour when you add to the control flow.  I have tried wrapping this code in a try catch but as it's all promised based it didn't make any difference.

Any pointers would be really useful.

Thanks

**Comment by juliemr** [comment]
Sorry for the slow responses here. Since updates to the control flow have occurred in the latest version of selenium-webdriver, could you try again with the latest version and file a new issue if you are still having problems? Thank you!
