### ISSUE TITLE
Running Protractor in Chromebook chrome

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2172]
Hi,
is Protractor able to run tests on Chromebook Chrome? Can you point to the any documentation regarding that.

Thank you.

**Comment by sjelin** [comment]
Hi,

As per our `CONTRIBUTING.md`, please ask this kind of question on stackoverflow or the google group.  The github issue tracker is poorly suited for this kind of question.

I believe this is possible through chromedriver, though I don't know the details.

Best,
Sammy
