### ISSUE TITLE
jasmine2 support for per-spec timeouts

### ISSUE THREAD

**Issue by prabhu-telsiz** [angular/protractor#2175]
Im using 
"jasmine": "2.3.1"
"Protractor: Version 2.1.0"

it('does stuff', function() {
...
}, 1000);

I tried this and I got this error.

Jasmine spec timed out. Resetting the WebDriver Control Flow.
" Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."

But the same spec used to work before updating protractor and Jasmine.

Is there any work around for this??

**Comment by sjelin** [comment]
As per our `CONTRIBUTING.md` guidelines, please ask questions like this on StackOverflow.

Also, I do not run into this problem running jasmine on my machine.  Presumably you have an `it()` or something somewhere with an asynchronous callback function that you're failing to call
