### ISSUE TITLE
"afterEach" is not getting executed for first "it block" in protractor

### ISSUE THREAD

**Issue by YatheeshKumar** [angular/protractor#2176]
Hi,

When running protractor scripts, for first "IT Block" of a spec, afterEach method has not executed, so to fix this we placed one empty it block as first one which worked fine (for second it block(actual code block) the afterEach block has executed). 

This issue has come only when we integrated TestRail API with protractor to push the protractor results(pass, fail)  to TestRail. We placed the TestRail API in afterEach method. 

We have got same issue for last it block also, so we have placed one empty it block to suppress the issue. 

Is there any workaround for this? 

Thanks in advance,
Yatheesh.

**Comment by juliemr** [comment]
I can't reproduce this. Can you share an example?

**Comment by YatheeshKumar** [comment]
Please find my spec file...
var importHomePageFunctionality=require("..\\pageFunctionalities\\angularjs_PageFunctionalities.js");
var setHomePageObj;
var importSafeActions=require("..\\Util\\safeAction.js");
var setSafeAction;
var importTestRailAPI=require("..\\testRailAPI.js");
var testRailAPI;

var fs = require('fs');
var runId;

describe("1Checking The Github Functionalities",function(){
    beforeEach(function(){
        setHomePageObj=importHomePageFunctionality.getHomePageFunctionality(browser);
        setSafeAction=importSafeActions.getSafeActionsObject(browser);
        browser.manage().window().maximize();
        browser.ignoreSynchronization = true;
        browser.get("https://www.angularjs.org");
    });

    it("29Should search for a topic based on keyword",function(){
        setHomePageObj.searchKeyword();
    });

    it("29Should search for a topic based on keyword",function(){
            setHomePageObj.searchKeyword();
    });

     it("10Should navigate to gitHub page when clicked in view button",function(){
        setHomePageObj.viewGitHub();
        expect(browser.getCurrentUrl()).toBe("https://github.com/angular/angular.js");
    });

    it("11should clear the cookies",function(){
        setSafeAction.clearCookies();
    });

    it("12should disable the cookies for browser",function(){
        setSafeAction.disableCookies();
    });

    it("",function(){});

    afterEach(function(){

        fs.readFile(".\\temp.txt", function(err, data) {
            if(err) throw err;
            runId = data.toString();
            console.log("***runId***"+runId+" type of runId "+typeof runId);
        });

        testRailAPI=importTestRailAPI.getTestRailAPI();

        var caseName=jasmine.getEnv().currentSpec.description;
        var caseId = caseName.replace ( /[^\d.]/g, '' );
        console.log("***caseName:***"+caseName+"***caseId:***"+caseId+" type of caseId:"+typeof caseId);
        console.log("failed count***:"+jasmine.getEnv().currentSpec.results().failedCount);
        if(jasmine.getEnv().currentSpec.results().failedCount>0){
            testRailAPI.add_Result_For_Case(runId,5,caseId,"TestCaseFailed");
        }else{
            console.log("***inside if rundId***:"+runId);
            testRailAPI.add_Result_For_Case(runId,1,caseId,"Testcase Passed");
        }
    });
});

**Comment by sjelin** [comment]
Could you come up with a more minimal example?  It's difficult to understand what might be going wrong here since so much here is dependent on external files which we don't have access to.

**Comment by YatheeshKumar** [comment]
Hi,

**Comment by YatheeshKumar** [comment]
Thanks for the reply.
We have simplified a spec by removing the dependency and we couldn't reproduce the same issue.
