### ISSUE TITLE
Logic code in protractor - if statement

### ISSUE THREAD

**Issue by vuilendi1212** [angular/protractor#2182]
Hi All,

I have a problem with if statement. I have a function as below:

```js
Lib.prototype.selectStorageTarget = function (arg1, callback) {
        var found = false;
        var leftMenu;
        element.all(by.repeater("menu in menus")).then(function(itemList) {
            itemList.forEach(function(item) {
                leftMenu = item.element(by.css('[class="ng-binding"]'));
                leftMenu.getText().then(function(clickedMenu) {
                    if (clickedMenu == arg1)
                    {   
                        found = true;
                        leftMenu.click();
                        return callback();
                    }
                });
            });
        }).then(function() {
            if (!found) {
                return callback(new Error(arg1 + ' is not found'));
            }
        });
    };
```

and cucumber syntax: When I want to select "Storage Target", which is the one part of menu on my page. Result receiving from protractor when i execute is attached in 
![error_01](https://cloud.githubusercontent.com/assets/12620739/7828674/ea80fc42-0460-11e5-96a3-72931edf39de.PNG)

If i change content of if statement to if (found == "false"), result will be successful. 
![error_02](https://cloud.githubusercontent.com/assets/12620739/7828699/3e7bdd9e-0461-11e5-8df8-eefd98c503fc.PNG)

but it is problem when i change cucumber syntax to: When I want to select "Example", which does not exist on my page, result will be 
![error_03](https://cloud.githubusercontent.com/assets/12620739/7828722/a84a03e0-0461-11e5-854b-2c4fa9a5a3b7.PNG)

Please help me solve this problem, thank you very much.

**Comment by sjelin** [comment]
`found == "false"` checks if the `found` variable equals the *string* `"false"`, rather than the boolean `false`.  So when you change the `if` statement to `if(found == "false")` then the conditional is never true and so the error callback never gets run.

**Comment by vuilendi1212** [comment]
Thanks for your comment, i will research and find out the best way for my code
