### ISSUE TITLE
importing external java reporting package into the Protractor

### ISSUE THREAD

**Issue by patesuj** [angular/protractor#2183]
Hi Everyone,
I have a external reporting package implemented in Java which produces very well detailed reporting page. Can I use that external package inside Protractor code? If yes then how I can do that? 
Please reply.
Thanks in advance.
Patesuj

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
