### ISSUE TITLE
getOuterHtml shows some attributes missing

### ISSUE THREAD

**Issue by michaelstack** [angular/protractor#2185]
**Edit:** I was mistaken regarding --elementExplorer and elementor. They can't resolve these elements. They could in the case of the issue I posted on stackoverflow. I now think that this issue is unrelated to that one, which was just a timing/waiting issue.

I am having trouble resolving elements with protractor. ~~When I browse the same page using --elementExplorer or elementor I can resolve them ok. But the same locators do not find anything when run in normal protractor tests.~~

~~I previously asked about this issue here:~~

~~http://stackoverflow.com/questions/30295073/protractor-finds-element-in-elementexplorer-mode-but-not-in-normal-mode/30299043~~

~~The answer given by user Dziamid seemed to work in the specific case I was dealing with at the time but I have since encountered situations where it does not.~~ 

While investigating, I tried a brute force approach:
1. get all elements of the required type on the whole page using element.all. Example: element.all(by.tagname('a'))
2. iterate over the collection and view the html per element as returned by getOuterHtml()

In the verbose output I found that I could see the element that I wanted to resolve. But it had the id attribute removed. So that explains why my seemingly simple and obvious element locators were failing. 

It is not just the id. Other attributes are sometimes missing from the value returned by getOuterHtml. So far it seems that if the attribute is not present in the getOuterHtml value then protractor can't resolve the element using that attribute as a locator. ~~However --elementExplorer and elementor still resolve it ok.~~

I see similar behaviour when I try to resolve nested by.repeaters. I can resolve the outer repeater but then a call to <element-located-by-outer-repeater>.all(by.repeater(<inner-repeater>)) finds 0 elements. I have structured the code as close as possible to the example given by hankduan on Jun 24, 2014 on this thread:

https://github.com/angular/protractor/issues/722

Once again, in my attempt to resolve this nested repeater, I logged out the html of the outer repeater (this time using getInnerHtml). Again, I can see the required elements in the output. 

Interestingly, I can even resolve the inner repeater elements as long as I resolve everything on the page using element.all(by.repeater(<inner-repeater-details>)). I just can't resolve them in the context of an element resolved by the outer repeater.

I'm hoping to write and post a small example program that demonstrates this behaviour. However I don't know whether the behaviour will manifest in the sample or whether it is specific to my application (which I can't post online). 

So, I'll begin by posting this description in the hope that I've missed something obvious and someone out there can point me to the appropriate section of the documentation.

**Comment by sjelin** [comment]
Interesting.  A minimal example would be great, thanks!

**Comment by michaelstack** [comment]
@sjelin I'm working on it. Of course I can't get the bug to manifest in isolation!

**Comment by michaelstack** [comment]
I should have mentioned in my original post that we are using requirejs and manual bootstrapping. Batarang does not work at all with our application because of this. 

I didn't think of it at first because protractor looks like it is working (albeit flakily) where batarang does nothing at all.

**Comment by michaelstack** [comment]
One more detail: it seems that the class attribute is not removed, but its value is. Below is an example. The data-arbitrary attribute is missing from the value returned by getOuterHtml. The class is still there, but empty.

in the html:

    <tr ng-repeat-start="task in milestone.tasks" ng-if="!task.$$edit" ng-class="{ mandatory : task.mandatory}" class="taskPtor" data-arbitrary="arbitrary">

in output from getOuterHtml:

    <tr ng-repeat-start="task in milestone.tasks" ng-if="!task.$$edit" ng-class="{ mandatory : task.mandatory}" class="">

When I delete the class from the html, I still get a class="" in the output.

**Comment by juliemr** [comment]
What happens if you look at the outerHTML of the element from the browser console? Is this an issue with what  webdriver is reporting as outerHTML, or with your application looking different from the template?

**Comment by michaelstack** [comment]
I have moved on to a new company. 

My colleague @jjulicher is still working on this project. He might still be interested in resolving this issue.

**Comment by juliemr** [comment]
Closing as we haven't heard any updates confirming that this is still an issue. Please open a new issue if there is still a problem.
