### ISSUE TITLE
Disconnected : Unable to receive message from renderer on switching between 2 windows alternatively

### ISSUE THREAD

**Issue by ShobanaV** [angular/protractor#2187]
I am testing an application that switches between 2 windows alternatively. I am using browser.getAllWindowHandles() to get available handles and switching back and forth between them. I have to switch for around 1000 times. But, protractor is throwing the error 'Disconnected: unable to receive message from renderer' after 10 to 15 switches. 

How to fix this problem? 

And also, 'Chrome not reachable' error occurs after some time. After some operations, chrome is crashing unexpectedly. I am not able to run more than 3 to 5 tests at a stretch.

**Comment by sjelin** [comment]
@hankduan This is more your domain

**Comment by ShobanaV** [comment]
And it is a nodwebkit application. I use sockets to communicate to the first window to close itself after another window gets opened up.

**Comment by hankduan** [comment]
What do you mean switch between windows? Do you have multiple tabs you are switching between, or multiple drivers?

**Comment by ShobanaV** [comment]
Our app actually loads a window, and on clicking a button a whole new app will get loaded in a new nodewebkit window. (node modules, source code and everything completely loaded new).

When I load like this, 'console' is undefined in the newly loaded node modules in protractor tests alone. That was the reason behind the crash.

I am not able to find out why 'console' is undefined in the newly loaded node modules in protractor tests alone.

**Comment by juliemr** [comment]
Is there still an issue here? Otherwise I will be closing as stale.

**Comment by juliemr** [comment]
Closing stale issues. Please open a new issue if you feel there is still a general bug.
