### ISSUE TITLE
Problem with getText empty - not element found possible

### ISSUE THREAD

**Issue by wazodevs** [angular/protractor#2188]
Hi guys! I am having trouble developing one test. This is the code:

```js
var mensajes = element.all(by.css('.error fill_msg')).all(by.tagName('span'));
expect(mensajes.getAttribute("value")).toEqual(['Rellene este campo', 'Acepte las condiciones legales.']);
```		

It's too easy, expect if one  element is throught the css selector. This should give to elements

```html
<div class="for_error" data-ng-message="required">
    <p class="error fill_msg" data-translate="">
        <span class="ng-scope">Rellene este campo</`span`>
    </p>
</div>

<div class="for_error" data-ng-message="required">
    <p class="error fill_msg" data-translate="">
        <span class="ng-scope">Acepte las condiciones legales.</`span`>
    </p>
</div>
```

But this is returning at the code, 
    `Expected [] to equal  [ 'Rellene este campo', 'Acepte las condiciones legales.' ].`

The reason of these is that is not founding the elements, but I pause the browser when that expect is going to be called and it's visible and using the chrome console I get the two elements.

¿Any idea?

Thx guys!

**Comment by wazodevs** [comment]
I fix this issue:

`expect(element.all(by.className('fill_msg')).getText()).toEqual(['Rellene este campo', 'Acepte las condiciones legales.'])`

But i don't understand why is the reason that the other code is not working....

**Comment by sjelin** [comment]
The other CSS doesn't mean what you think it means.

`by.css('.error fill_msg')` would select something like:

```html
<div class="error">
  <fill_msg></fill_msg>
</div>
```

The selector you wanted would have been `by.css('.error.fill_msg')`

**Comment by wazodevs** [comment]
Thx for all sjelin
