### ISSUE TITLE
Font weight check

### ISSUE THREAD

**Issue by LeninChristopher** [angular/protractor#2189]
is it possible to check font-weight ...whether its bold or italic..in my angular page i need to check resultset text values displayed in bold and italics in random order.

**Comment by sjelin** [comment]
You should be able to use [`getCssValue()`](http://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.getCssValue)

Also, as per our [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask this kind of question on StackOverflow
