### ISSUE TITLE
Support for hybrid apps

### ISSUE THREAD

**Issue by LeninChristopher** [angular/protractor#2201]
Hi..any update on date we can expect the release of protractor support for hybrid apps..since its a very important issue because most of the applications uses native controls which also needs to automated.. .. eagerly waiting for the release date of support for hybrid apps.

**Comment by sjelin** [comment]
We're not currently planning on creating tools for controlling native apps.  Some people have found ways to use tools like appium to get Protractor working on mobile browsers, presumably including the case of hybrid apps.  We're still figuring out our story around mobile

**Comment by LeninChristopher** [comment]
i asked about hybrid apps which is intalled in android in apk format.

**Comment by sjelin** [comment]
We're not currently planning on creating tools for controlling the native portions of hybrid apps.  Try tools like appium for the webview portions.

**Comment by LeninChristopher** [comment]
Thanks for the response sjelin...i have some questions 
Julimr had mentioned that support for hybrid apps in progress on 15-Feb-2015 for the issue raised by my team member...kindly refer the below link.
https://github.com/angular/protractor/issues/1798
* Our project is developed with AngularJS wrapped as a apk using IBM Worklight and the adaptors has been provided to support native parts like Google Notification services,camera etc.
* How to use the same protractor script with APK's and also using appium we can open the application only in mobile browser and its not possble to work with the installed application..if we go with direct appium then it supports only HTML5 which should have properties like name,id,classname or xpath but only protractor provides the way to work with angular properties like model,repeater,css...Kindly provide a explanation.. its a urgent requirement.

**Comment by sjelin** [comment]
All the information we have about using appium is here: http://angular.github.io/protractor/#/mobile-setup

You can also ask questions on StackOverflow.  However, we're still working on our mobile story and it might be that some of the things you want to do won't be possible.

**Comment by sridevi-15** [comment]
Hi, 
   I am able to run protractor test against ios simulator and ios device, but I have issues with identifying invisible elements i.e the element is false when I check xpath in appium inspector. Can Protractor coders help if you have any API to identify invisible elements. Can I use something like 'mobile: tap' in protractor. It worked with 'mobile: tap' with java script code in selenium+ APPIUM+ java framework. It will be great if you can provide information whether protractor has support for this. Also can you please let me know if protractor has full support for native app testing both on simulator and device

**Comment by emna24** [comment]
@sridevi-15 : did you use appium and protractor for your hybrid app to run you tests ?

**Comment by sridevi-15** [comment]
No, I switched back to selenium, appium java framework as protractor does not have all support.
Thanks,Sridevi
