### ISSUE TITLE
On node v0.12 util.puts gives warnings 

### ISSUE THREAD

**Issue by bobbijvoet** [angular/protractor#2204]
Everytime I run protractor I get these warnings:
`util.puts: Use console.log instead`
util.puts is deprecated according to node.js docs <https://nodejs.org/api/util.html#util_util_puts>

**Comment by sjelin** [comment]
@juliemr I've been wondering about this too

**Comment by juliemr** [comment]
Yes - but we should have already done that, so I'm confused. The only instance of `util.puts` that I see is in our test application.

**Comment by sjelin** [comment]
I've been wondering about that part too tbh

**Comment by sjelin** [comment]
That is, I've been wondering why I see the warning given that we don't seem to use `util.puts`

**Comment by NickTomlin** [comment]
@sjelin @bobbijvoet What specific version of node are you running? I haven't been able to replicate with `0.12.0` or `0.12.4` and protractor 2.1.0. This is very curious :)

**Comment by juliemr** [comment]
Closing this issue, as I don't see these warnings and we do not use util.puts. Please open a new issue with how to reproduce if there is still a problem.
