### ISSUE TITLE
Please update the request node_module [vulnerability]

### ISSUE THREAD

**Issue by vdclouis** [angular/protractor#2205]
As the version in the `package.json` has an old version of `qs` which has this vulnerability:
https://portal.requiresafe.com/advisories/qs_dos_memory_exhaustionhttps://portal.requiresafe.com/advisories/qs_dos_memory_exhaustion

**Comment by sjelin** [comment]
At the risk of saying something stupid, I don't see a dependency on `qs` in our `package.json`.

**Comment by vdclouis** [comment]
@sjelin yeah, this is indeed not clear.
what I mean is this:
`protractor > request > qs`

protractor uses on 'old' version of request which depends on an 'old' version of qa which has the vulnerability.
I hope this makes more sense now ^^
