### ISSUE TITLE
"Port 5858 is already in use" when using browser.pause more then once

### ISSUE THREAD

**Issue by eolognt** [angular/protractor#2206]
I have the line `browser.pause();` in a beforeEach-function in my Protractor spec and I thought it would act as a breakpoint for me to pause before every `it` and check out the browser before continuing with the command `d` to continue to the next debugger statement (which should be the beforeEach again). But when Protractor reach beforeEach for the second time I get the error: 
```
Port 5858 is already in use. Please specify another port to debug.
[launcher] Process exited with error code 1
```
Isn't this how you're supposed to use the pause function? What's purpose of the `d`-command if you can't use `browser.pause()` multiple times in the code?

**Comment by gitjul** [comment]
Encountering the exact same issue.

**Comment by siulung4073** [comment]
+1

**Comment by misbahkhan** [comment]
I'm not sure what the implications of this are, but you can specify the port as a param to `browser.pause()`. So something like
```
$('button').click();
browser.pause(5001);
$('#close').click();
browser.pause(5002);
```
would allow you to pause multiple times without crashing.

**Comment by dtaylor-employii** [comment]
I am also experiencing this.  I have tried both closing the debugger and continuing to the next debugger statement with the same result.

I think the hesitance to use the multiple ports is that this would appear to leave the ports open, so if you are running a long test suite, with multiple browser.pause, you would have a number of debug ports open.  As well, the OPs issue is hitting the pause in the beforeEach, so this would require incrementing a debug variable after each pause to avoid the issue.

**Comment by nvega-ms** [comment]
Same issue here -> http://screencast.com/t/8CFTi1eGD0

**Comment by w-green** [comment]
+1

**Comment by juliemr** [comment]
I'm seeing this now even when running pause just once. @hankduan do you have time to take a look?

**Comment by SidBala** [comment]
+1 hitting same issue.

**Comment by martinsznapka** [comment]
+1

**Comment by hankduan** [comment]
Fixed here: https://github.com/angular/protractor/pull/2763

**Comment by pellekrogholt** [comment]
@hankduan I tried out you #hack branch because I ran into the port problem.

I have a node project using 

    $ node --version
    v5.2.0
    $ npm --version
    3.3.12

    packages.json ->    
    ...
    "protractor": "git@github.com:hankduan/protractor.git#hack",
    "webdriver-manager": "^7.0.1",
    "jasmine-core": "^2.3.4",
    "karma": "0.13.8",
    "karma-jasmine": "^0.3.5",

using you branch I run some e2e tests ~ (https://github.com/angular/protractor/blob/master/debugging/failure_spec.js)

    $ ./node_modules/.bin/protractor debug protractor.conf.js 

raises:

    Using the selenium server at http://localhost:4444/wd/hub
    [launcher] Running 1 instances of WebDriver
    Starting debugger agent.
    Debugger listening on port 5858
    debug> connecting to localhost:5858 ... ok
    debug> break in timers.js:57
     55 };
     56 
    >57 function listOnTimeout() {
     58   var msecs = this.msecs;
     59   var list = this;
    debug> c
    There was an internal error in Node's debugger. Please report this bug.
    read EIO
    cError: read EIO
        at exports._errnoException (util.js:856:11)
        at TTY.onread (net.js:545:26)

    debug> debug> Segmentation fault (core dumped)

is this a nodejs or a protractor issue ?

if its a pure nodejs issue I have already added a comment to an existing issue https://github.com/nodejs/node-v0.x-archive/issues/8030#issuecomment-165433998

which node version do you  / others use successfully for protractor debugging ?

**Comment by hankduan** [comment]
That branch is for using Protractor with multiple `browser.pause`, not debug. 
If all you did was add a `debug` to the commandline and did not touch the spec file, AND if the spec file runs without the `debug` property, then chances are it's a node issue, since it is controlled entirely by node.

And just as a background on what the debug command does, protractor simply calls node with `--nodeDebug`. See https://github.com/angular/protractor/blob/master/lib/cli.js

That being said, I have not been able to reproduce your issue (I've used 4.x and 5.0)

**Comment by pellekrogholt** [comment]
@hankduan ok I get the debugger thing and leaves to out for now.

I should have made it more clear that I also have an e2e test with multiple browser.pause() along the `failure_spec.js`:

    describe('portal', function() {
        it('must provide login', function() {
            browser.get('http://localhost:3000');

            browser.pause();

            element(by.model('email')).sendKeys('anemail');
            element(by.model('password')).sendKeys('apassword');
            var selector = by.cssContainingText('a,button', 'Sign in');
            var button = browser.findElement(selector);
            button.click();

            browser.pause();

            expect(element.all(by.css('.search-inner')).count()).toEqual(1);
        });
    });

now I downgrade to node 5.0.0 and use you protractor branch and gets the port already in use error:

    $ ./node_modules/.bin/protractor debug protractor.conf.js
    Using the selenium server at http://localhost:4444/wd/hub
    [launcher] Running 1 instances of WebDriver
    Starting debugger agent.
    Debugger listening on port 5858
    debug> connecting to localhost:5858 ... ok
    debug> break in timers.js:56
     54 };
     55 
    >56 function listOnTimeout() {
     57   var msecs = this.msecs;
     58   var list = this;
    debug> [8Gc

    debug> debug> Started
    Port 5858 is already in use. Please specify another port to debug.
    [launcher] Process exited with error code 1

any hints further suggestions ?

**Comment by hankduan** [comment]
Run it as `./node_modules/.bin/protractor protractor.conf.js`, not `./node_modules/.bin/protractor debug protractor.conf.js`. Let me know if that fixes your problem.

**Comment by pellekrogholt** [comment]
@hankduan thank you for the patience without the `debug` param the steps works.

**Comment by juliemr** [comment]
This is out in the 3.1.0 release!

**Comment by troggo** [comment]
This seems to be happening again on 3.3.0. I tried 3.2.0 and 3.1.0 and it works on both.

Error:
````
P:\test>node node_modules\protractor\bin\protractor conf.js
...
wd-debug> Resuming code execution
Port 5858 is already in use. Please specify another port to debug.
[15:20:45] E/launcher - Process exited with error code 1
````

Test files:
````
// conf.js
exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['spec.js']
}

// spec.js
describe('Protractor Demo App', function() {
  it('should have a title', function() {
  	browser.pause();
    browser.get('http://juliemr.github.io/protractor-demo/');
    browser.pause();
    expect(browser.getTitle()).toEqual('Super Calculator');
  });
});
````

**Comment by robertye112** [comment]
+1 this is happening to me in version 3.3.0. (this never used to happen, I know how to use these pause/debug features, it's specific to 3.3.0)

**Comment by tommyz0123** [comment]
+1 4.0.4 happening as well

**Comment by mgiambalvo** [comment]
I fixed this issue in 4.0.5

https://github.com/angular/protractor/pull/3504

**Comment by isian8814** [comment]
+1
It still happened in 4.0.11

**Comment by bvasilchik** [comment]
+1
Yeah I thought maybe I did something wrong by using browser.pause more than once. I got the same error and thought it was odd. B/c essentially it's like a breakpoint and I wanted to step to the next breakpoint

**Comment by mgiambalvo** [comment]
Sorry, I'm able to repro the problem in 4.0.11. It's working for me, but maybe my test case is too simple. If you're still seeing duplicate port errors, could you open a new issue with some more details? For example, is the error consistent or intermittent? Do you see it with browser.pause() in different it() blocks? A repro example is always really helpful when debugging issues like this.

Also, if you happen to have multiple Protractor instances doing browser.pause(), you'll see this error. That's a known issue, and we can fix it if it's a problem for people.

**Comment by kemerydev** [comment]
Fixed easily enough in osx or linux by killing the protractor process that is taking the port.  In a terminal window, "ps -A | grep protractor" will show the running process which is consuming the port, and the problem will be solved with "kill -s kill <pid>" where <pid> is the number of the listed process from the previous command
