### ISSUE TITLE
browser.manage().logs().get('browser') logs are not retrieving browser debug logs 

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2207]
Hi,
The app logs some debug logs after clicking on a button.I'm trying to capture those debug logs using 
```
browser.manage().logs().get('browser').then(function(browserLog) {
            logger.debug('log: ' + require('util').inspect(browserLog));
});
```
and it not capturing the debug browser logs.

**Comment by sjelin** [comment]
What browsers are you using?  I don't know if this works properly outside of chrome

**Comment by spatchamatla** [comment]
Protractor v2.1.0,
selenium-server-standalone v2.45.0
chromedriver v2.15

i  ran the tests only on Chrome.

**Comment by juliemr** [comment]
This is because chrome only captures warnings and errors from the log by default. See https://github.com/webdriverio/webdriverio/issues/491
