### ISSUE TITLE
Document how to add a custom locator

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2208]
From what I understand, there is no place inside the protractor docs describing how to add a custom locator using `by.addLocator()`.

Let me know if you agree with the proposal and which place would be the best for this kind of information. Thank you.

**Comment by sjelin** [comment]
http://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.addLocator

**Comment by alecxe** [comment]
@sjelin  got it, was looking through `docs/`, but completely forgot about the autodoc and the API reference. Thanks!
