### ISSUE TITLE
"Firefox quit unexpectedly" pop-up received when running tests on variants of firefox 38 yet tests continue to run

### ISSUE THREAD

**Issue by desecheo** [angular/protractor#2210]
Protractor version 2.1.0 and versions of firefox 38 (tested on 38.0.1 and 38.0.5).

The warning dialog window stays up but tests continue to execute. I could not replicate the behavior with firefox 37.0.2.

![screen shot 2015-06-04 at 4 15 06 pm](https://cloud.githubusercontent.com/assets/12515144/7993561/e9c40e46-0ad4-11e5-8d5b-bc42b5a75521.png)

**Comment by sjelin** [comment]
This seems like a firefox/webdriver bug
