### ISSUE TITLE
Not able to set the IEDriverServer.exe path via command line

### ISSUE THREAD

**Issue by testdev-hyd** [angular/protractor#2211]
I would like to give the path of IEDriverServer.exe in order to start working with Internet explorer. I am providing the 

seleniumArgs: ['-Dwebdriver.ie.driver=../selenium/IEDriverServer.exe'] in the conf.js file, 

The above is working fine. 

But when i am trying to provide the same as a command line argument like

protractor -Dwebdriver.ie.driver=path to the IEDriverServer.exe conf.js

it is not executing the script instead it shows that the driver executable path must be set.

Please let me how to set this as command line argument.

**Comment by sjelin** [comment]
As per our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask this kind of question on StackOverflow

Also, I believe you would want `protractor -seleniumArgs "['-Dwebdriver.ie.driver=../selenium/IEDriverServer.exe']"`

**Comment by testdev-hyd** [comment]
@sjelin: Thank you for you comment. I am looking for the same.

**Comment by sjelin** [comment]
Uh, I think it might actually be `protractor --seleniumArgs "['-Dwebdriver.ie.driver=../selenium/IEDriverServer.exe']"`.  Regardless, if you can't find the question on StackOverflow, you should just ask it yourself
