### ISSUE TITLE
Cucumber tag: @ignore is ignored

### ISSUE THREAD

**Issue by sebastianwoinar** [angular/protractor#2212]
Hey,
I'm trying to exclude one particular scenario with @ignore.
Unfortunately, this doesn't work. 

Do I have to configure protractor somehow in order to support that?

Does this issue belongs rather to the cucumber-js module?

KR, Sebastian

**Comment by gquemener** [comment]
I'm also having this issue of `@ignore` tag not ignored.

**Comment by sjelin** [comment]
Closing this because we split cucumber off with https://github.com/angular/protractor/pull/2710
