### ISSUE TITLE
Unable to pass options before config file

### ISSUE THREAD

**Issue by tmulry** [angular/protractor#2214]
The options prompt `protractor [options] [configFile]` is misleading. I get an error when I pass the options before the config file.  Putting the options after the config file works fine.  

    $ protractor config.js --verbose
    Using ChromeDriver directly...
    [launcher] Running 1 instances of WebDriver
    <sometests run here>
    Finished in 13.275 seconds
    3 tests, 3 assertions, 0 failures

    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 passed
    $ protractor --verbose config.js
    **you must either specify a configuration file or at least 3 options. See below for the options:

    Usage: protractor [options] [configFile]
    configFile defaults to protractor.conf.js

**Comment by sjelin** [comment]
I think the issue with your example is that it thinks you're setting the `verbose` variable to `config.js`, but sure, we'll change this
