### ISSUE TITLE
.map not returning anything

### ISSUE THREAD

**Issue by qualityshepherd** [angular/protractor#2218]
Map seems to be broken... or has changed, and the documentation needs to be updated. 

Example:
```
browser.ignoreSynchronization = true;
browser.manage().timeouts().implicitlyWait(5000);

describe('map test', function() {
	it('should return an array of objects', function() {
		browser.get('http://qualityshepherd.com');

		var posts = element.all(by.css('div.post')).map(function(post, index) {
			return {
				index: index,
				title: post.$('h2 a').getText()
			};
		});

		// these pass
		expect($$('div.post').count()).toEqual(5);
		expect($$('div.post').get(0).$('h2 a').getText()).toBe('Google Calendar Event List Javascript Script');
		// these fail with: Cannot read property 'index'/'title' of undefined
		expect(posts[0].index).toEqual(0);
		expect(posts[0].title).toBe('Google Calendar Event List Javascript Script');
	});
});

```

**Comment by eolognt** [comment]
`posts.index[0]` is incorrect. I think you want `posts[0].index` instead. The same goes for the following line.

**Comment by qualityshepherd** [comment]
Woops... yeah, fudged that on the example, but the problem remains (I updated my example. ). Map is not returning anything.

**Comment by eolognt** [comment]
`element.all().map()` return a promise and you are trying to read `posts` as an array when it really is a promise. Either you only pass `posts` to `expect` and expect the resolved value to be something (like in this [example](https://angular.github.io/protractor/#/api?view=ElementArrayFinder.prototype.map)), or you add a `then` to the promise `map()` returns and expect the value of the array to be something inside the callback passed to `then()`.

**Comment by qualityshepherd** [comment]
Thanks for the reply. Yeah, I figure I was thinking about this wrong. Because I was using it in an element, I thought the promise would resolve, and it should work like an array at that point. Clearly it doesn't :)
