### ISSUE TITLE
Problem with visualization

### ISSUE THREAD

**Issue by kartlife** [angular/protractor#2220]
Hi guys, i write a test using protractor and it is working in one pc but when I tried to use it in another pc the visualization is not working (I can´t see the pages where the protractor is) but the specs are working fine. The window of chrome stuck on white screen and when the specs end the browser is closed.

¿Any solution?
P.D: Browser used is Chrome.

**Comment by sjelin** [comment]
Is there a difference between the PCs?  Or chrome versions?

**Comment by wazodevs** [comment]
The chromes versions are equals, but there are differences about the PCs. 
(PC ok VS PC problem visualization)


Windows 7 Enterprise (SP1) VS Windows 7 Professional(SP1)
Imagen Corp 64 VS HP EliteBook 8460p
i5-4570 CPU @ 3.2GHz VS i5-2520M CPU @ 2.5GHz
4GB RAM VS 4GB RAM
SO 64 bits VS SO 64 bits

Thx!

**Comment by sjelin** [comment]
This is very strange.  Have you tried reinstalling protractor/chromedriver on the problematic PC?

**Comment by wazodevs** [comment]
Yeah is a strange issue, because all the specs are working correctly... i'll try again to reinstalling all and I write here what happens!

Thx!

**Comment by juliemr** [comment]
Closing stale issues. Please open a new issue if you feel there is still a general bug.
