### ISSUE TITLE
Unable to set --seleniumArgs through command line 

### ISSUE THREAD

**Issue by testdev-hyd** [angular/protractor#2221]
Hi Team,

I am unable to use some selenium arguments like setting IEDriver path using the --seleniumArgs argement via command line. Also, If i look for help using 

    C>protractor --help,

The options doesn't include --seleniumArgs.

Is there anyway to set the IEDrvierServer.exe path using command line argument?

**Comment by sjelin** [comment]
It's true that `protractor --help` doesn't list `--seleniumArgs` but that shouldn't matter.  What is the command you're running and what is the error you're getting?

**Comment by sjelin** [comment]
Update: presumably it's because what you're passing from the commandline would be interpreted as a string, where as you'd like it to be parsed as a JSON object.

**Comment by testdev-hyd** [comment]
@sjelin:

I am using the following command at command line 


C:\Users\admin\AppData\Roaming\npm\node_modules\protractor\example>protractor --seleniumArgs "['webdriver.ie.driver=../selenium/IEDriverServer.ex
e']" conf.js

And I am getting the following error message:

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://xxx.xxx.xxx.xxx:60830/wd/hub

C:\Users\admin\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: The path to the driver executable must be set by the webdriver.ie.driver system property; for more information, see http://code.google.com/p/selenium/wiki/InternetExplorerDriver. The latest version can be downloaded from http://selenium-release.storage.googleapis.com/index.ht
ml

**Comment by testdev-hyd** [comment]
@sjelin : I have followed your thought on providing the selenium argument as JSON object in the command line and got succeeded. Here is the solution.

C:\Users\admin\AppData\Roaming\npm\node_modules\protractor\example>protractor --seleniumArgs "{webdriver.ie.driver:'../selenium/IEDriverServer.exe'}" --seleniumAddress "http://localhost:4444/wd/hub" conf.js

Note: We have to  provide the seleniumAddress either in conf.js or pass as a command line argument.

Thanks for your idea @sjelin . You really rockz
