### ISSUE TITLE
input[type="email"] doesn't register as valid upon sendKeys()

### ISSUE THREAD

**Issue by mrowles** [angular/protractor#2225]
I am having intermittent issues when testing form input for email types in both Chrome & Firefox:

       betaSignUpForm.formName.click().then(function () {

            // Input name
            betaSignUpForm.formName.sendKeys('Sepp Blatter').then(function () {
                betaSignUpForm.formName.sendKeys(protractor.Key.TAB).then(function () {

                    // Input email address
                    betaSignUpForm.formEmail.sendKeys('seppblatter@fifa.com').then(function () {
                        betaSignUpForm.formEmail.sendKeys(protractor.Key.TAB).then(function () {

                            // Input password
                            betaSignUpForm.formPassword.clear().sendKeys('bungabunga1').then(function () {
                                betaSignUpForm.createBtn.click().then(function () {

                                    expect(betaSignUpForm.formName.getCssValue('border-color')).toEqual(greenRgb);

                                    // This is breaking due to a possible race condition
                                    // it actually appears red border only during tests
                                    expect(betaSignUpForm.formEmail.getCssValue('border-color')).toEqual(greenRgb);

                                });
                            });
                        });
                    });
                });
            });
        });

I have tried a number of different ways of approaching this, such as `clear()`, `browser.sleep()`, staggering key sends, backspacing and correcting, tabbing in and out...very odd! The password and text fields work fine.

Update:
I am using protractor ~2.1.0 and gulp-protractor ~1.0.0

Thanks

**Comment by sjelin** [comment]
When you look at the browser, is `seppblatter@fifa.com` being put into the email box?

**Comment by mrowles** [comment]
@sjelin yes, all the fields are populated fine. I cannot replicate this issue outside of protractor in any browser. It's very odd! As stated, tried to tackle this from every which way but it just seems like a race condition, at the very least it is intermittent with about a 25% success rate.

**Comment by sjelin** [comment]
Could you show me the javascript which changes the color of the email form?

**Comment by mrowles** [comment]
Well, its CSS, utilizing Angular's form input ng-touched and ng-in/valid classes. Perhaps one of the classes isn't being toggled because ng-pristine is not adding ng-touched since we're not touching it, but that would be confusing since the text and password inputs seem to work fine.

**Comment by mrowles** [comment]
*technically not touching it...

**Comment by sjelin** [comment]
If you send the exact same sequence of keystrokes manually you can't reproduce the problem?  including navigating by the tab key?

**Comment by mrowles** [comment]
Correct, it's weird behaviour...tried everything I could think of. I'll have to do a browser.pause() tonight and investigate further, I didn't have capacity to do it last night. I have a feeling one of the angular form classes isn't being attached sometimes for whatever reason. I've read elsewhere that it can break when the browser isn't focused (which could be sometimes in the background).

**Comment by juliemr** [comment]
Just to clarify - when running the test, you can see that the email is being populated?
Also, there's no need to be doing so much `.then` indenting. You can write this as:

```
   betaSignUpForm.formName.click();

   // Input name
  betaSignUpForm.formName.sendKeys('Sepp Blatter');
  betaSignUpForm.formName.sendKeys(protractor.Key.TAB).;

  // Input email address
  betaSignUpForm.formEmail.sendKeys('seppblatter@fifa.com');
  betaSignUpForm.formEmail.sendKeys(protractor.Key.TAB);
  // etc
```
That's the beauty of the control flow!

**Comment by mrowles** [comment]
@juliemr @sjelin 
Hi,

I've found a way to do this successfully, the issue is due to protractor using the computed styles, and CSS2 - not CSS3 - to boot. So you have to check the `border-top-color` attribute, so in this case it would be:

    expect(betaSignUpForm.formEmail.getCssValue('border-top-color')).toEqual('rgba(247, 98, 98, 1)');

Some more information at these links:
* http://stackoverflow.com/questions/20535167/selenium-webdriver-get-border-color
* http://stackoverflow.com/questions/29796095/protractor-check-the-border-radius-using-getcssvalue

Thanks,
Matt
