### ISSUE TITLE
Testing chrome extension - angular never provided resumeBootstrap

### ISSUE THREAD

**Issue by GabiGrin** [angular/protractor#2229]
Hi,

I'm trying to write e2e tests for an Chrome extension. The extension is a button that popups a mini page.
Because AFAIK there is no way of actually clicking the extension button in a test, what I am doing is navigating to chrome-extension://[id] page, for example: 
chrome-extension://ellddmdnejjhcdhhondpoachlnmiaenb/popup.html.

Now the problem is that I get this error - `angular never provided resumeBootstrap` (my ng-app is in the body tag, not on other elements).
After some digging in protractor code, I found that protractor gives the window a name so angular knows to defer the bootstrapping (https://github.com/angular/protractor/blob/master/lib/protractor.js#L530),
and this line doesn't seem to happen when navigating a chrome-extension:// page.

I tried adding to my app code the following:
```
window.name = 'NG_DEFER_BOOTSTRAP!';
```
and it worked. A hacky solution to this problem is to change the window.name based on a query string, so it runs only in tests, but it doesn't feel right.

Do you guys have an idea why the window.name set is not working there, or ideas on where to further investigate this? I tried playing around with protractor.js to see if I find a suspect but got stuck.

Thanks in advance!

**Comment by sjelin** [comment]
This is very weird.  Is there anything that would trigger unexpected navigation (e.g. a redirect)?  Also, I'm assume the mini page is an angular page?

**Comment by GabiGrin** [comment]
No redirections in the code. Mini page is angular indeed. I'll try to create a very lean demo repo recreating the problem soon.

**Comment by juliemr** [comment]
Haven't heard any updates - closing as stale. Please open a new issue if a reproducible issue is found!
