### ISSUE TITLE
IE9 hitting "angular could not be found on the window" after hashbang redirect

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2230]
I have a test-script that opens a couple of non-angular pages and then jumps to an Angular one. 

Running it on Chrome, Firefox, latest IE fine. But running it on IE9 via SauceLabs hits this error: 

`Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window"`

The video shows that the page is loading, so unclear what's causing the error. My guess is it relates to the hashbang redirect (from /mypage to /ie#mypage). I haven't tried running tests on IE9 in yonks so may be missing something obvious...

**Comment by sjelin** [comment]
Basically this means that `waitForAngular` is being called before Angular has loaded.  This issue may be a duplicate or https://github.com/angular/protractor/issues/2181.  Can I see your test code?

**Comment by PaddyMann** [comment]
My test code isn't the easiest to share as it's buried in page objects ... I've pasted some in below in case it does help.

It sounds like I'm experiencing the redirect issue you mentioned in #2181 (You browser.get() to a page... Protractor waits for Angular to load on the page... Angular loads and Protractor finds it... The page redirects to a second page... Protractor, thinking that Angular has already been loaded, executes the next command in your test script. This is the step where the error message is generated... The second page loads Angular, but too late!)

I guess I'm surprised as redirecting to a hashbang URL for older versions of IE is standard practice. So I expected there to be something built into Protractor to handle this. Or at least for other people to have stumbled into it and for their to be a standard solution.

As it is, I think I'll need to put in some IE specific code within my page loading function. Assuming this is the case, what's the most efficient way to check if we're using a given version of IE in Protractor? 


---

The code...:

page.js, which extends astrolabe's Page. (https://github.com/stuplum/astrolabe/blob/master/lib/astrolabe/page.js)

```
  /*
   * Loads the page, using the provided params
   *
   * @param params an object of parameters to use in the URL
   */
  load: {
    value: function(params, forceLoad, options) {
      var page = this;

      // Set page.params, used when generating the URL
      page.params = params || {};

      var flow = browser.controlFlow();
      return flow.execute(function () {
        // Whether or not to force a page load even if the current URL is the same as the new
        forceLoad = forceLoad ? true : false;
        // Further options
        options = {
          // Whether to load with the expectation of a 404 page
          test404: options && options.test404 ? options.test404 : false
        };

        // Always ignoreSynchronization for getCurrentUrl() to be safe
        browser.ignoreSynchronization = true;
        return browser.getCurrentUrl().then(function(currentUrl) {
          // If the page doesn't include Angular, don't wait for it to load
          browser.ignoreSynchronization = !page.containsAngular;

          // Don't reload the page if we're already there (unless forceLoad is true)
          var currentRelativeUrl = currentUrl.replace(/^.*\/\/[^\/]+/, '');
          if(!forceLoad && (currentRelativeUrl === page.url || currentRelativeUrl === 'ie#' + page.url)) {
            return;
          }

          // Open the page using this.url
          page.go();

          // If we're testing for a 404 page load, then wait for .error-404 to be present and then return (rather than
          // waiting for this page to load properly which will never happen)
          if(options.test404) {
            browser.wait(function() {
              return $('.error-404').isPresent().then(function(isPresent) {
                return isPresent;
              });
            }, this.loadTimeout);
            return;
          }

          // Wait for the page to load
          return page.waitForLoad();
        });
      });
    }
  },
  waitForLoad: {
    value: function() {
      // If page includes Angular, Protractor will wait for Angular to load. Else use our own isLoaded check
      if(!this.containsAngular) {
        var page = this;
        return browser.wait(function() {
          return page.isLoaded();
        }, this.loadTimeout);
      }

      return true;
    }
  }
```

The specific page object (which extends page.js):

```
  isLoaded: {
    value: function() {
      return $('.modal-header').getText().then(function(text) {
        return text === 'Team members';
      });
    }
  },
```

Within my spec:
```
      teamPage.load({
        projectId: project.id
      });
```

**Comment by sjelin** [comment]
We're working on the issue.  Should be solved soon.  I'm going to close this issue for now but if you're sill having the problem after https://github.com/angular/protractor/pull/2217 is merged in let me know

**Comment by PaddyMann** [comment]
Thanks Sammy - I monkeypatched in your update. 

But, I now get an `Page reload detected during async script` error - which happens when there's a page redirect (according to previous comments by Julie in #1395).

So.. the error may be more useful to pinpointing my issue, but it does't solve the issue. 

I think I'm going to need to:

1. Call `browser.getCapabilities()` and check if the test is running from IE9
2. If it is, send the test directly to the IE version of the page (/ie#/mypage rather than /mypage)
3. Add a separate test that tests the IE redirect is working as expected (with `browser.ignoreSynchronization` set to `true`)

If anyone has a better solution, I'll be happy to hear it :)

**Comment by PaddyMann** [comment]
Have implemented 1 and 2 and specs run successfully (so can confirm it's definitely the IE redirect that caused the issue).

**Comment by sjelin** [comment]
Well, ideally we should be able to handle redirects like this.  My solution assumes the `waitForAngular` call happens after the redirect, but it could very well happen before.  I'll think about it some more
