### ISSUE TITLE
Multicapabilities specs ignore the --specs flag on the command line and run anyway

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2231]
I have set up multicapabilities to support certain specs only running in Chrome or a given version of IE - this works great.

But, when I then specify to only run a single spec on the command line...

```protractor protractor.conf.js --specs route/to/my/specs.js``` 

... it decides to also run those specs specified in multicapabilities. It's a tad annoying as it slows down diagnosing and fixing an issue with a specific test or environment.

**Comment by sjelin** [comment]
Protractor will run any specs listed in the [`spec`](https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L135) property of a capability in addition to those specified in the [`spec`](https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L80) property of the config file.  The `--spec` flag only overwrites the `spec` property of your config file, not the capabilities, so the capability specs continue to run.

**Comment by PaddyMann** [comment]
That's what I figured. But... that's undesirable right?

It's not what I expected as a user, and there's no workaround other than to copy your config file and remove these lines every time you want to diagnose a specific issue.

(Note: Rather than specifying a specific spec on the command line, I'd be happy to use fit/fdescribe if it wasn't for Jasmine2's odd behaviour with beforeAll/afterAll combined with fit/fdescribe. That is, it treats beforeAll/afterAll like beforeEach/afterEach which breaks my tests. I know this is a known issue and Julie has let them the Jasmine team know that it confuses Protractor users)

**Comment by sjelin** [comment]
You could use `--multiCapabilities

**Comment by PaddyMann** [comment]
Perfect - thanks :)
