### ISSUE TITLE
Able to run protractor test without starting webdriver-manager

### ISSUE THREAD

**Issue by testdev-hyd** [angular/protractor#2232]
Team,
I am able to run my protractor test without starting selenium-server via webdriver-manager or having the seleniumAddress parameter in the conf.js for firefox and chrome browsers. 

But I have to start the webdriver-manager in order to run my test against IE browser along with seleniumAddress parameter in the conf.js file.

Is the above two features are bug or the intended behavior of protractor. Please let us know, as we are little confused. Also let us know the main purpose to use webdriver-manager

**Comment by sjelin** [comment]
You should always be able to execute your tests, regardless of if a selenium-server server is running.  However, if you try to actually interact with the browser, and there's no selenium-server, your tests will fail.
