### ISSUE TITLE
Unable to run protractor test with selenium grid

### ISSUE THREAD

**Issue by testdev-hyd** [angular/protractor#2233]
Team,

I am trying to execute my protractor test through selenium grid in order to reduce execution time. I have followed the following steps , but unfortunately I couldn't be able to do parallel execution

1. started webdriver-manager start in a command line
2. Opened new command line and started the protractor conf.js

Contents of conf.js are
----------------------------
```js
exports.config = {
  directConnect: false,
  
  seleniumAddress: 'http://localhost:4444/wd/hub',
  // Capabilities to be passed to the webdriver instance.
 
multiCapalilities:[
    {
    browserName: 'firefox',
	shardTestFiles:true,
	maxInstances :2
  },
  {
	  browserName : 'chrome',
	  shardTestFiles : true,
	  maxInstances:3
  }
],
 
 maxSessions:2,

  // Framework to use. Jasmine 2 is recommended.
  framework: 'jasmine2',

  // Spec patterns are relative to the current working directly when
  // protractor is called.
  specs: ['TestSpec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
	showColors: true,
    defaultTimeoutInterval: 90000
  }
};

```
Please let me know how to execute protractor tests
1) using grid with parallel execution.

**Comment by sjelin** [comment]
As per our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask this kind of question on StackOverflow
