### ISSUE TITLE
I got this spawn error in MacOS

### ISSUE THREAD

**Issue by Naixor** [angular/protractor#2238]
After I `protractor conf.js`, I got this: 
![77353fc0b80e1caa4ccd8b03cc66877e](https://cloud.githubusercontent.com/assets/5070106/8123538/f5b16ea4-10fd-11e5-8801-23fec31c86d1.png)

**Comment by Naixor** [comment]
My chrome version is 43.0.2357.124, I guess it can not be supported.

**Comment by sjelin** [comment]
Can you post your config & spec files?

**Comment by juliemr** [comment]
Closing as stale.
