### ISSUE TITLE
Call a function when an expect fails

### ISSUE THREAD

**Issue by yentheo** [angular/protractor#224]
We want to take a screen shot when there is an expect that fails.

Is there a way to plug in to some sort of onFail event that runs with every 'expectation fail'.

I looked at writing a jasmine reporter. But these only have events that run after a spec is completed (or before). The problem with this is that I could have an expect in the middle of my test, I want to see a screenshot of that moment.

Is something like this possible with the current protractor version?

Thanks in advance!

**Comment by yakshithkj** [comment]
The below code works well for capturing a screenshot of failure step by saving locally. But, how we can embed this screenshot to HTML report with in the same code? I've tried with this code stream.attach(new Buffer(png, 'base64').toString('binary'), 'image/png'); by including before stream,end(); but its throws an undefined error. Can you please provide me a solution for this?

browser.takeScreenshot().then(function (png) {
    var fs = require('fs'),
        buf = new Buffer(png, 'base64'),
        stream = fs.createWriteStream('exception.png');
        stream.write(buf);
        stream.end();
});
