### ISSUE TITLE
Attach build identifier to tests on SauceLabs

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2240]
SauceLabs has just been updated so you can pass your CI build identifier and it'll group all the tests for that build together.

Neat!

Is there anyway we currently set this up within our protractor config (or better yet, on the command line) ?

They want it in this format:

    "build": "build-1234"

**Comment by sjelin** [comment]
Sounds like a good idea!  Probably the best idea is to make it a property of the config file.  After all, you can set any property of the config file through the command line.  It'd be great if you could write a PR for this!  Otherwise we'll get to it when we get the chance

**Comment by PaddyMann** [comment]
We're normally doing multiple releases a week, but currently working towards a biggie due mid-August, so adding this functionality will have take a low priority for me until then. If it's not implemented by that point, I'll take a look :)

**Comment by juliemr** [comment]
You can do this by adding it to the configuration file under `capabilities`. We do this, for example, at https://github.com/angular/protractor/blob/master/spec/ciFullConf.js#L23

Closing as easy to do!
