### ISSUE TITLE
Update to WebDriver 2.47.1

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2245]
This will fix several issues, but is currently blocked because `selenium-webdriver` node module @ 2.46.0 is causing issues with `ElementArrayFinder.each`, probably due to control flow changes.

**Comment by elifa** [comment]
I would appreciate if you could add the proxy support to Protractor that comes with WebDriver 2.46 as well.
I suggest adding this row to the `driverProvider.js` file:

```javascript
DriverProvider.prototype.getNewDriver = function() {
    // ...
    usingWebDriverProxy(this.config_.seleniumProxy).
    // ...
}
```

**Comment by juliemr** [comment]
See also https://github.com/angular/protractor/pull/2263

**Comment by hankduan** [comment]
Here's a test which hangs with webdriver 46, but not 45.

```javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().
  usingServer('http://localhost:4444/wd/hub').
  withCapabilities(webdriver.Capabilities.chrome()).
  build();
var flow = webdriver.promise.controlFlow();

driver.get('http://www.w3schools.com/html/html_lists.asp');

var printTexts = function(webElems) {
  var attrVals = webElems.then(function(arr) {
    var results = arr.map(function(webElem) {
      return webElem.getText();
    });
    return webdriver.promise.all(results);
  });

  flow.execute(function() {
    return attrVals.then(function(res) {
      console.log(res[0]);
    });
  });

  return true;
};

driver.findElements(webdriver.By.css('.example_result li')).then(function(arr) {
  var result = arr.map(function(webElem) {
    var webElemsPromise = webdriver.promise.fulfilled(webElem).then(function(webElem) {
      return [webElem];
    });
    return webdriver.promise.fullyResolved(printTexts(webElemsPromise));
  });
  return webdriver.promise.all(result);
})

driver.quit();
```

**Comment by hankduan** [comment]
fyi, this is pending https://github.com/SeleniumHQ/selenium/issues/796

**Comment by juliemr** [comment]
NOTE - the pending issue is still pending, but with WebDriverJS 2.47 out and other issues beginning to crop up because of the stale version of WebDriverJS (such as install warnings with node.js 4.1 and errors with new browsers when using `directConnect`) we are going to go ahead and do the upgrade anyway. We will attempt to outline potential new issues clearly in the breaking changes section of the release notes. Stay tuned!

**Comment by juliemr** [comment]
Update:

I've release a new version of `jasminewd2`, 0.0.6 which appears to solve most of the issues. 

There is one lingering failure in our test suite, which is that elementExplorer no longer works. The server starts, but is shut down immediately. I've confirmed that this is due to the `selenium-webdriver` version update.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/pull/2559

**Comment by juliemr** [comment]
Done with #2559.
