### ISSUE TITLE
Where is default timeout for browser.wait?

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2253]
I'm running tests with Jasmine2, and have config set up with:

    allScriptsTimeout: 11000,
    getPageTimeout: 10000,
    jasmineNodeOpts: {
      defaultTimeoutInterval: 90000
    }

I used to specify a timeout with each `browser.wait` call. e.g.:

    browser.wait(function () {
       ...
    }, 3000);

But when getting cross-browser tests to run, I discovered I didn't need to specify the 3000 manually and was better off letting it run until it hit the configured limits.

But... now I'm running the tests locally again and it seems to ignore the configuration. I've checked that it is set up in the same way (using `browser.getProcessedConfig` and reviewing the output), but all my `browser.wait`s are failing too quickly. e.g. `Failed: Wait timed out after 110ms`.

Am I missing something obvious?

**Comment by sjelin** [comment]
Could you give a small example?

**Comment by PaddyMann** [comment]
From a page object:

    lblSuccessMessage: {
      get: function() {
        return $('.edit-team-member_success-message');
      }
    },

    ...
    
    goSubmitAndClose: {
      value: function () {
        var page = this;
        page.btnAddTeamMember.click();
        browser.wait(function () {
          return page.lblSuccessMessage.isPresent();
        });
        page.btnCloseSuccess.click();
      }
    }

The browser.wait gives the error:

    Message:
        Failed: Wait timed out after 65ms
      Stack:
        Error: Wait timed out after 65ms
            at Array.forEach (native)
        From: Task: <anonymous wait>
            at Fn.module.exports.Page.create.goSubmitAndClose.value (  ...  /addTeamMember.page.js:111:15)
            at Object.<anonymous> (  ...  /addTeamMember.spec.js:67:12)
        From: Task: Run fit("should allow user to add a team member with limited access") in control flow
            at Array.forEach (native)
        From asynchronous test: 
        Error
            at Suite.<anonymous> (  ...  /addTeamMember.spec.js:62:5)
            at Suite.<anonymous> (  ...  /addTeamMember.spec.js:35:3)
            at Object.<anonymous> (  ...  /addTeamMember.spec.js:3:1)

**Comment by juliemr** [comment]
This is due to a change in WebDriverJS. In version 2.45, if no wait was specified, it changed from defaulting to infinity to defaulting to zero. You just need to specify a wait now (FYI, this was listed in the changelog: https://github.com/angular/protractor/blob/master/CHANGELOG.md

It was an odd change and is reverted in WebDriverJS 2.46, which we would like to upgrade to soon but are facing some issues.

**Comment by PaddyMann** [comment]
Great, thanks for the explanation and apologies for not paying enough attention to the change log!

**Comment by PaddyMann** [comment]
One common thought I've had as I've stumbled into every Protractor and Jasmine oddity - it'd be really great if there could be more warnings in the output, rather than relying on users reviewing every piece of documentation.

The issue with the documentation is it's often doesn't address all of the issues you face in the detail you need. So you end up in StackExchange or a blog that was only posted a few months ago, and you try to use their examples to make things work. Except in this example they don't work anymore.

"Warning: Using browser.wait without a explicit timeout. See https:// for more info..." could have saved an hour or two.

Thanks anyway - appreciated :)
