### ISSUE TITLE
"browser.refresh()" causes "Angular could not be found on the page" with Firefox 38.0.5

### ISSUE THREAD

**Issue by rluba** [angular/protractor#2254]
All tests that invoke `browser.refresh()` are failing with "Angular could not be found on the page" errors when using the latest Firefox (`38.0.5`) and `protractor@2.1.0` (with `selenium-webdriver@2.45.1`).

The same tests work just fine in latest Chrome (`43.0.2357.124`).

Replacing `browser.refresh()` with `get current URL then load URL` solves the problem, so we use this workaround for now:

```JavaScript
exports.config = {
    …
    onPrepare: function () {
        browser.refresh = function () {
            var self = this;
            return self.getCurrentUrl()
                .then(function (url) {
                    return self.get(url);
                });
        };
    }
};
```

**Comment by sjelin** [comment]
Good catch!  https://github.com/angular/protractor/pull/2217 should mitigate this problem, but probably the best thing to do in the long-term is for us to over-write `browser.refresh`

**Comment by cnishina** [comment]
With the latest version of protractor, `browser.refresh()` issue looks like it has been resolved and no longer reproducible.
