### ISSUE TITLE
Expecting an empty string

### ISSUE THREAD

**Issue by ksaraie** [angular/protractor#2255]
I want to assert that the initial state of an input type=text is empty. 

HTML
```
<input id="my-id" ng-model="my.model" type="text" class="form-control input-sm ng-pristine ng-valid">
```

Test code:

    expect(browser.findElement(protractor.By.id('my-id')).getAttribute('value')).toContain('');

I get a failure with the following message :( 

      Message:
        Expected '' to contain ''.
      Stack:
        Error: Failed expectation

Is it something I'm doing wrong?

**Comment by alfonso-presa** [comment]
I think you should use toBe('') instead of toContain(''). It's problably something related with the assertion library, but it has sense to say that the empty string doesn't contain anything.... not event and empty string.

**Comment by ksaraie** [comment]
toBe('') worked! Thank you!
