### ISSUE TITLE
OperaDriver does not support executing asynchronous javascript

### ISSUE THREAD

**Issue by jfroom** [angular/protractor#226]
This may not be a protractor issue, but wanted to list some findings for anyone else with same issues with sauce. 

I get failed job from an exception thrown when I run the basic protractor example:
```
./bin/protractor ./example/conf.js 
```
The config is set with my sauce id/key and with opera win7/linux capabilities. The same tests pass with chrome and same operating systems. I've got protractor 0.12.0.

I've made the test results public here:
https://saucelabs.com/tests/7f9179629bc54022b7080349b5e2f4ef
https://saucelabs.com/tests/4a2b2d4ee20046cb898ef9105a73ce35

This is the exception being thrown:
https://gist.github.com/jfroom/7322586

**Comment by juliemr** [comment]
Closing as Opera is not one of our supported browsers, and operadriver shows no signs of adding support.
