### ISSUE TITLE
Default download options for Internet explorer

### ISSUE THREAD

**Issue by YatheeshKumar** [angular/protractor#2260]
Hi,
Recently we got a new requirement in our project i.e upon clicking on a pdf link it has to download in to default location. In chrome it works fine because we have set the following configuration in the protractor conf.js file.

```js
'chromeOptions': {            
                prefs: {
                    'excludeSwitches': ['test-type','ignore-certificate-errors'],
                    'download': {
                        'prompt_for_download': false,
                        'default_directory': 'D:\\project\\downloads'
                    },
                },
}
```

but in internet explorer we are unable to do it. is there such configuration(similar to the above code) even for internet explorer. We have tried using autoit and got the solution but that autoit integration is not supported when tests executed in browserstack. so looking for other solutions. now we have solution for chrome not for Internet explorer.

Please let me know all the configurable options that protractor has for internet explorer.

Thanks,
Yatheesh.

**Comment by YatheeshKumar** [comment]
Hi,

Can any body please help me on this. At least share a relevant link. 

Thanks,
Yatheesh.

**Comment by sjelin** [comment]
Hi YatheeshKumar,

Sadly, we're not really IE experts on the protractor team.  I'd ask this question on StackOverflow.  GitHub's issues are actually a pretty poor platform for this kind of Q&A anyway (see our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md)).

Best,
Sammy

**Comment by YatheeshKumar** [comment]
thanks for your time sjelin :)
