### ISSUE TITLE
Protractor --elementExplorer not starting

### ISSUE THREAD

**Issue by aorfevre** [angular/protractor#2262]
hi everyone (and Julie ;) )

I'm having trouble trying to use elementExplorer.

First of all : 
- I'm using windows 8.1
- protractor 2.1.0

when I launch protractor --elementExplorer, It does seems that everything is started properly.
I see the chrome (or respectivly firefox if I define --browser firefox) starting and, automaticly closing.

I do not see any issues in console.
I can type for exemple TAB and see commands.
I tried defining my --baseUrl and/or --seleniumAddress; same behaviour.

I can type : browser.get("http://localhost:8080/2/webapp"), but then I got this issue : 
> browser.get('http://localhost:8080/2/webapp')
UnknownError: Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: '', ip: '169.254.80.80', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: driver.version: unknown

Here is the report from : protractor --troubleshoot --elementExplorer

C:\Users\Alexandre\git\webappangular>protractor --troubleshoot --elementExplorer
DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 2.1.0
DEBUG - Your base url for tests is undefined
DEBUG - Attempting to find the SeleniumServerJar in the default location used by webdriver-manager
DEBUG - Attempting to find the chromedriver binary in the default location used by webdriver-manager
Starting selenium standalone server...
Selenium standalone server started at http://169.254.80.80:65415/wd/hub
DEBUG - WebDriver session successfully started with capabilities { caps_:
   { applicationCacheEnabled: false,
     rotatable: false,
     mobileEmulationEnabled: false,
     chrome: { userDataDir: 'C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\scoped_dir92_20561' },
     takesHeapSnapshot: true,
     databaseEnabled: false,
     handlesAlerts: true,
     version: '43.0.2357.124',
     platform: 'WIN8_1',
     browserConnectionEnabled: false,
     nativeEvents: true,
     acceptSslCerts: true,
     'webdriver.remote.sessionid': 'a6823ef8-a832-4437-9c7d-3f20476235a1',
     locationContextEnabled: true,
     webStorageEnabled: true,
     browserName: 'chrome',
     takesScreenshot: true,
     javascriptEnabled: true,
     cssSelectorsEnabled: true } }
Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

Type <tab> to see a list of locator strategies.
Use the `list` helper function to find elements by strategy:
  e.g., list(by.binding('')) gets all bindings.
Starting debugger agent.
> Debugger listening on port 5858

Thank for support,

**Comment by ravikumars** [comment]
I came across this issue today on two different computers with fresh installs node/protractor. Happens with internet explorer and chrome and maybe other browsers.

**Comment by hankduan** [comment]
Does it work if you do `browser.get(yourUrl)` as part of a normal spec?

**Comment by aorfevre** [comment]
hankduan, I have tried to perform also withen a SPEC & within beforeEach without success.
The elementExplorer seems very usefull but so far, I'm still not able to use it on Windows 8.1

**Comment by hankduan** [comment]
So just to clarify:
1) your issue isn't with element explorer starting, but the fact that it crashes when you enter `browser.get('http://localhost:8080/2/webapp')`
2) running `browser.get('http://localhost:8080/2/webapp')` in a spec, i.e.
```javascript
describe('protractor', function() {
  it ('should get url', function() {
    browser.get('http://localhost:8080/2/webapp');
  });
});
```
does not work?

**Comment by aorfevre** [comment]
@hankduan  first of all, thx for support.

1) My issue is IMO elementExplorer crashing as if I set up the uri on explorer parameters, I see my page opening and directly closing.
No error logs available on cmd.

If I do : protractor --troubleshoot --elementExplorer


My result is the following : 
```javascript
Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

Type <tab> to see a list of locator strategies.
Use the `list` helper function to find elements by strategy:
  e.g., list(by.binding('')) gets all bindings.
Starting debugger agent.
> Debugger listening on port 5858
```


Same behaviour if I use : protractor --troubleshoot --elementExplorer --suite test

and with test Suite as : 
```javascript
describe('protractor', function() {
  it ('should get url', function() {
    browser.get('http://localhost:8080/2/webapp');
  });
});
```

**Comment by hankduan** [comment]
I don't know where you got `protractor --troubleshoot --elementExplorer --suite test` syntax from, but it's not valid. 

I didn't mean for you to run elementExplorer with a spec file. Does running a spec file alone work (i.e. does protractor work normally)? That is does `protractor conf.js` (i.e. http://angular.github.io/protractor/#/tutorial#step-0-write-a-test) work for you?

**Comment by aorfevre** [comment]
@hankduan  my protractor tests are working well so far but I discovered that elementExplorer could help me create and investigates my tests faster that how I'm doing right now.

With the following command : 
protractor --elementExplorer --baseUrl http://www.angularjs.org

I do see : 
- AngularJS Page opening
- when page is fully loaded(I assume), the explorer is automaticly closed (no error in console)
- Console shows me ```Javascript > ``` prompt.
- I type ```Javascript element(by.id('foobar')).getText() ```
- Error
```Javascript
UnknownError: Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: '*****', ip: '*****', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_31'
Driver info: driver.version: unknown
```
Extra info
```Javascript
webdriver-manager status
selenium standalone is up to date
chromedriver is up to date
IEDriver is not present
```


Thx for support

**Comment by hankduan** [comment]
Do you have a non-windows machine you could try this one? I suspect it has to do with the fact that you are on windows. 

Also, can you provide me the version of your node?

**Comment by aorfevre** [comment]
Unfortunatly I do not have a non windows machine.
Only Headless (AWS) machines that will not help me on that point.

@sjelin you tagged that issue "needs more info", what are your questions ? What info can I provide more ?

**Comment by vishalmodi** [comment]
I am also facing same issue, browser automatically get close after opening. I am using 

protractor --directConnect --elementExplorer --troubleshoot

I just install Node.js and Protractor on Windows 7, there is no issue in running the test, only elementExplorer don't work.

**Comment by hankduan** [comment]
@vishalmodi @aorfevre What version of node are you using?

**Comment by aorfevre** [comment]
Versions : 
windows 8.1
protractor 2.1.0

>node -v
v0.12.0

**Comment by hankduan** [comment]
Can you try downgrading to v0.10.30? and let me know if it works for you?

**Comment by vishalmodi** [comment]
I am using 

node v0.12.5 
Protractor 2.1.0

**Comment by PMarian0** [comment]
Does this share some similarities with #2228 ?

**Comment by juliemr** [comment]
Closing this as really out of date - please open a new issue if you are still seeing problems with the latest version of Protractor.
