### ISSUE TITLE
how to retrieve pass fail status of each test in protractor 

### ISSUE THREAD

**Issue by vishalshivnath** [angular/protractor#2270]
I need to write pass fail status into a csv file . Is there any way to check the status of each test case post execuction of test cases so that appropriate action can be taken

**Comment by smahalingam** [comment]
I think below code is what you looking for, 
jasmine.getEnv().addReporter(new function() {
    this.specDone = function(result) {
      if (result.failedExpectations.length > 0) {
       // Test FAILURE ACTION GOES HERE
     }
   };
  });

**Comment by BobyAbraham** [comment]
Hi Shanmuga,
I tried your code, and it is giving Pass|Fail status first time, but not sure in the end it is giving Pass again if it was a failed test. Is it if() block has the issue or the function getting called two times?
Here is my code -
    it("To verify, xxxx", function () {
        try{
            expect(1).toMatch(2);
            notes = "Success";
        }catch(err){
            //logger.info("catch : " + err);
            status = "Fail";
            notes = err.message;
            //logger.info(err.message);
        }finally{
            jasmine.getEnv().addReporter(new function() {
                this.specDone = function(result) {
                    //status = result.failedExpectations.length > 0 ? "Fail" : "Pass";
                    console.log('Name: ' + result.fullName);
                    if (result.failedExpectations.length > 0) {
                        console.log('I am Failed: it01');
                        status = "Fail";
                        notes = result.failedExpectations;
                    }else{
                        console.log('I am Passed: it01');
                        status = "Pass";
                        notes = "";
                    }
                };
            });
            adminPage.addTestCaseResult('"To verify, xxxx"', status, notes);
        }
    })
OUTPUT:
I am Failed: it01
.Name: To verify, xxxx.
I am Passed: it01

**Comment by smahalingam** [comment]
Can you try including the pass/fail check in the afterEach?

**Comment by BobyAbraham** [comment]
this worked for me  - http://jasmine.github.io/2.3/custom_reporter.html

**Comment by sjelin** [comment]
Sounds like everyone's problems have been sorted

**Comment by PavankumarNagaraj** [comment]
Hi, @ BobyAbraham ,

How to include the custom reporter
