### ISSUE TITLE
Click on svg element does not work

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2272]
I am trying to execute a click on a DOM element contained inside an SVG.

The code is:

```
browser.actions().mouseMove(el.getWebElement()).click().perform();
```

I saw that mouse move on the element, the click is executed, but nothing happens. After the click it should access another page, but it does not work.

Any help?

**Comment by sjelin** [comment]
Does `el.click()` work?

**Comment by bitliner** [comment]
no, it does not

**Comment by bitliner** [comment]
When are going to add support for it? Is there any plan?

**Comment by bitliner** [comment]
For now I solved it using raw Selenium, like so

```
browser.actions().click(element.all(by.css('...')).get(0).getWebElement()).perform();
```

**Comment by bytexro** [comment]
@bitliner : can we enable this again, this seems like a more common problem now. We should not fallback to selenium but have support in protractor for this.

**Comment by bitliner** [comment]
Thank you @bytexro , I think protractor have many other things that are common but that are ignored. Looking forward to see the new API in protractor.

**Comment by bitliner** [comment]
On protractor 4.0.11 looks like raw selenium does not work neither .
It might be also a problem of my svg, but the selector is correct. Quite weird :(
