### ISSUE TITLE
Help need with isPending()

### ISSUE THREAD

**Issue by cpalkar** [angular/protractor#2276]
Getting the following error.
   "Undefined is not a function"

Code 
```js
this.MyCheck = function(r) {
    var ret_val = undefined;
    var el = element(by.xpath(xp)).getText();

    el.then( function(str) {
          ret_val = str != "Happy";
    });
    
    while ( el.isPending() ) {
         console.log("x"); // debug
    }

    return ret_val;
},
```

The call to "isPending" is giving the above mentioned error.

The above code is part of generic page object. 

Any/All help is appreciated.

**Comment by sjelin** [comment]
`isPending` is a property of instances of `WebElementPromise` and `AlertPromise`, but `getText` is a regular Webdriver Promise, since it resolves to text rather than to a Web element
