### ISSUE TITLE
Selecting an option in kendo-combo-box

### ISSUE THREAD

**Issue by brandon19257** [angular/protractor#2281]
I am having trouble selecting a kendo combobox selection using angular js. The best way i can tell to change the value is to set the model.batch.type on the controller, but i don't know how to do that. I have messed around with executing a script to do it but have had no luck. Any help would be appreciated.
```html
<div class="row form-group">
    <label for="type" class="col-sm-1 k-label text-right">Type</label>
    <input id="type" class="col-sm-1 no-padding" kendo-combo-box data-ng-model="model.batch.type"
           k-data-text-field="'name'" k-data-value-field="'id'" k-data-source="model.batchTypes"/>
    <label for="size" class="col-sm-1 k-label text-right">Size</label>
    <input type="text" id="size" name="size" class="col-sm-1 k-textbox" ng-required="true" data-ng-
model="model.batch.size"/>
    <label class="col-sm-2 col-sm-offset-1 k-label">
        <input type="checkbox" data-ng-model="model.barCodePrint" checked/> Print Batch Barcode
    </label>
    <button type="button" class="btn" ng-click="cancel()">Cancel</button>
    <input type="submit" class="btn btn-primary" ng-disabled="createBatchForm.$invalid"
           value="Create"/>
</div>
```
I am trying to select an option in the second input with id='type'.

**Comment by juliemr** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
