### ISSUE TITLE
missing error stack for errors in command run in element explorer shell

### ISSUE THREAD

**Issue by Mayank1791989** [angular/protractor#2286]
currently if there is error in command it only prints error message which is very hard to debug

**Comment by juliemr** [comment]
The stack trace probably won't be very useful since there isn't actually a file which is running. The errors would just be from protractor/selenium-webdriver modules. Would those be useful to you? Could you describe a situation and what you would like to see?

**Comment by Mayank1791989** [comment]
Mostly I use element explorer to debug page objects and without stack trace it is very hard to find the exact location of error

**Comment by cnishina** [comment]
ElementExplorer is a great place to start debugging without creating a test suite. If you are bringing in a page object, my assumption is that you have already investigated a good locator strategy and this would be better as a simple Protractor test.

Also, in elementExplorer, I needed to do the following to read in a page object file.

```
> var path = require('path')
> var PageObj = require(path.resolve('path/to/page-object.js')).PageObject
> var pageObj = new PageObj();
> pageObj.clickOnButton()  // where clickOnButton does something like element(by...).click()
```

If you need stack traces, it'll be better in a simple Protractor test:

conf.js 
```
exports.config = {
  directConnect: true,
  specs: [ 'spec.js']
}
```

spec.js
```
var PageObj = require('./path/to/page-object').PageObj;
describe('test page obj', () => {
  it('should work', () => {
    var pageObj = new PageObj();
    pageObj.clickOnButton();
  });
});
```
