### ISSUE TITLE
confusion on testing for an element by ID

### ISSUE THREAD

**Issue by EMCP** [angular/protractor#2292]
I have a page in my Ionic app.. that I'd like to test.. particularly if an element is present and displaying the proper text.

protractor (webdriver) complains it cannot find the element by that ID.  I'm guessing i need to add a wait ?

```
    describe("loginpage", function () {

        it("should go to login page and have the title MYTITLE", function () {
            writeTitleToLog('Login');
            writeToLog("resizing window and going to home page");
            browser.driver.manage().window().setSize(375, 667);
            pageUtils.getPage("/");
            expect(browser.getTitle()).toBe("MYTITLE");
        });

        it("should list a terms of service, privacy policy ", function() {
            var privacyElement = element(By.id("privacyPolicy1234"));
            expect(privacyElement.getText()).toContain("Privacy Policy");
            writeToLog("saw elements");
        });

```

Snippet from page being rendered

`<a id="privacyPolicy1234" on-tap="goPrivacyPolicy()" class="disable-user-behavior">Privacy Policy</a>`

The error

```
    Message:
     NoSuchElementError: No element found using locator: By.id("privacyPolicy1234")

```

**Comment by EMCP** [comment]
adding a `browser.sleep(2000);` makes the testcase pass... is there a more proper way to test for an element by ID?

**Comment by sallojusuresh** [comment]
Use browser.wait(function(){},timout,'errormessage') rather browser.sleep() and make it wait till element present and then proceed further.  
Hope below line of code will work for you..
 
it("should list a terms of service, privacy policy ", function() {
         var privacyElement = element(By.id("privacyPolicy1234"));
          browser.wait(function(){
                privacyElement .isPresent();},
                             10000,"Element NOT found");
            expect(privacyElement.getText()).toContain("Privacy Policy");
            writeToLog("saw elements");
        });

**Comment by juliemr** [comment]
Thanks @sallojusuresh for the great answer. Closing this issue as an answered question.
