### ISSUE TITLE
How to get HTML screen shot reporter by using Parameters and page objects in conf.js file in Protractor tool

### ISSUE THREAD

**Issue by shivakumargorige** [angular/protractor#2294]
Here the code.

// An example configuration file.

exports.config = { 

directConnect: true,

// Capabilities to be passed to the webdriver instance.
  capabilities: { 
  'browserName': 'chrome'
  },
 
	baseUrl: 'http://10.10.1.52/edFusion/',

 // Spec patterns are relative to the current working directly when
 // protractor is called.

		specs: ['User.js'],

// Options to be passed to Jasmine-node.

jasmineNodeOpts: {
onComplete: null,
isVerbose: true,
showColors: true,
includeStackTrace: true,
defaultTimeoutInterval: 360000

 
},

params: {
     credentials: {
         userName: 'mathews',
         password: 'Choice#123'
}}
 
}

Note:I have created parameters and page objects and used in script file

**Comment by juliemr** [comment]
I'm not sure what the question here is. Take a look at the [faq](http://www.protractortest.org/#/faq#how-can-i-get-screenshots-of-failures-) for information about screenshotting in general. I'm closing this as it's a question, and not appropriate for our bug issue tracker.

**Comment by shivakumargorige** [comment]
Hi,
i am unable to get HTML screenshot reports when  conf.js file having defined parameters and page objects.
