### ISSUE TITLE
No way to get number of elements returned by `findElements`

### ISSUE THREAD

**Issue by stickel** [angular/protractor#23]
This issue may not be Protractor related but I'm not sure where else to look. My setup is using Protractor with jasmine-node to test an Angular front-end to a Rails app. When I try to get how many elements are found by `protractor.findElements` it always errors out.

My spec file follows the onJasmineNode example. So far I've tried the following:
- `ptor.findElements(protractor.By.css('.selector-string')).size();`: [object object] has no method size
- `ptor.findElements(protractor.By.css('.selector-string')).count();`: [object object] has no method count
- `ptor.findElements(protractor.By.css('.selector-string')).length;`: undefined is not a function

For fun I wrapped the findElements in a console.log and it returns this:

```
{ then: [Function: then],
  cancel: [Function: cancel],
  isPending: [Function: isPending] }
```

**Comment by abhisharma2** [comment]
:+1: on the count()

**Comment by EvanBurbidge** [comment]
@juliemr in your example above it returns the length, but can you also use this to be able to use the .sendKeys() function to the element? Have an element inside a tab, inside a directive and this is the only piece of code thats sent anything back from it.

**Comment by stickel** [comment]
@EvanBurbidge Yes, you should be able to do a number of things with the `element` in the example above, including `sendKeys()`.
