### ISSUE TITLE
disableEnvironmentOverrides in protractor tests

### ISSUE THREAD

**Issue by mfsiabhishek** [angular/protractor#2300]
While using SauceLabs Ondemand Jenkins plugin,if we select a browser platform combination, it propagates browser and platform details to SELENIUM_BROWSER , SELENIUM_VERSION etc. 

webdriverjs builder is made to override user provided capabilities in case SELENIUM_BROWSER env variable is found. So in this case capabilities provided in protractor config is overridden and caps like platform is lost. So test always runs with default sauce browser chrome on Linux.

Please suggest or make a way to pass disableEnvironmentOverrides() to builder.

**Comment by hankduan** [comment]
I'm not sure what exactly you are asking. In protractor you can define your browser and capability. See https://github.com/angular/protractor/blob/master/docs/referenceConf.js

You can also connect to sauce, see http://www.protractortest.org/#/server-setup#remote-selenium-server.
