### ISSUE TITLE
Can't access params from conf capabilities

### ISSUE THREAD

**Issue by gsagenjr** [angular/protractor#2302]
Hello,

I'd like to pass a param from the command line and use it to set up my conf capabilities chrome language, like so:

Command line:
```
    protractor conf.js --params.language.lang='es-419'
```

I'd love to be able to set it like this and have it use my command:
Conf.js
```
exports.config = {
...
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['lang=' + params.language.lang]
        }
    },
    params: {       
        language: {
            lang: 'en-US'
        }
    },
...
};
```

Currently this says 'params not defined' and errors out before it begins.
Similarly, this.params.laguage.lang returns the error 'cannot read property language of undefined'.

As I understand, I can't access the params until the onPrepare section, so I think I am going about it wrong trying to access it in the setup. Is there a way to access the chromeOptions after the setup, or a way to get the params available beforehand?

**Comment by eolognt** [comment]
Can't you write 
```
protractor conf.js --capabilites.chromeOptions.args.0="'lang'=es-419"
```
?

**Comment by gsagenjr** [comment]
@eolognt This seems to have no effect as far as I can tell =\

**Comment by sjelin** [comment]
You can set  properties of the config object via the command line, though I don't think you can sub-properties like that.  I'll look into it.

**Comment by sjelin** [comment]
Hey, @eolognt was basically right, but misspelled `capabilities` and had the syntax slightly off.  Try:
```js
protractor conf.js --capabilities.chromeOptions.args.0 "'lang'=es-419"
```
