### ISSUE TITLE
browser.refresh() fails on IE11 without a timeout

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2304]
Not sure if this one's known already. 

Also not sure if this relates to the Webdriver update that led to `browser.wait` needing an explicit timeout.

But have found `browser.refresh` fails on IE (tested on IE11), whereas it worked fine on Chrome and Firefox.

```
- Failed: waiting for page to load for 10ms
Wait timed out after 107ms
```

**Comment by mgiambalvo** [comment]
Confirmed we no longer see this issue on IE11 with the latest Protractor.
