### ISSUE TITLE
Is there a way to resolve the result of element() without triggering actions?

### ISSUE THREAD

**Issue by xyq117480** [angular/protractor#2305]
Hi buddy, 
I do know there is a breaking change of element() resulting that element().then() is no longer possible.

However, I would like to capture the error of element(), to customise it and write into log files, such as "no such element + customised information".

As far as I know there is a way of using control flow, and is there any other more structural 
ways to do that ?

Thanks so much for any kind of help!

**Comment by sjelin** [comment]
1. As per our [`CONTRIBUTING.md`](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask these kinds of questions on StackOverflow
2. Not sure exactly what you're asking, but you could always use [`getWebElement`](http://angular.github.io/protractor/#/api?view=ElementFinder.prototype.getWebElement) to trigger any errors you need triggered,
