### ISSUE TITLE
Can we request a kept-current doc page on protractor+require.js?

### ISSUE THREAD

**Issue by iainctduncan** [angular/protractor#2312]
I'm hoping this is an acceptable place to request this, at the moment the situation for sorting out how to use protractor with require is really difficult. Searching for it turns up old issue threads with the blind leading the blind, and as far as I can tell, this is still an issue. I've followed various suggestions and am getting the dreaded "intermittent error". My apologies if such a thing already exists, but if it does, it's not ranking well on the ol' google searches. thanks for listening.

**Comment by iainctduncan** [comment]
It would also be good to have some mention in the FAQ I think?

**Comment by juliemr** [comment]
That'd be great - if anyone wants to write one, I'd happily look at a PR.

**Comment by NickTomlin** [comment]
@juliemr I'm going to close this since we haven't seen any movement on it in a few months and It seems like the next step is a PR here from someone who uses protractor + require.js. 

Feel free to reopen and let me know if I that's the wrong call 😄

**Comment by juliemr** [comment]
sgtm thanks Nick.
