### ISSUE TITLE
element() vs browser.findElements()

### ISSUE THREAD

**Issue by justechn** [angular/protractor#2316]
I recently upgraded to protractor 2.0.0 and all my tests stopped working. I have been digging around trying to figure it out with out much success until today. I ran across a post https://github.com/angular/protractor/issues/551 that showed them using browser.findElements() instead of elements(). When I tried that it seems to be fixing things. 

Can someone tell me the difference between the two and when it is appropriate to use one over the other?

Also if I use browser.driver.findElements() it does not work, but browser.findElements() does. Why do we sometimes have to use .driver and sometimes not?

**Comment by nserebry** [comment]
browser.driver.findElements() used if you need to interact with a non-Angular page, you may access the wrapped webdriver instance directly by using ‘browser.driver’. 
You can refer to example from  [ Protractor docs ](https://github.com/angular/protractor/blob/f52438549f7d920da1600199feaf58059d6fd692/spec/withLoginConf.js/ "Protractor docs  ")

**Comment by justechn** [comment]
The page I am accessing is most definitely an angular page. So it is weird that I have to use browser.findElements()

**Comment by nserebry** [comment]
Appspector chrome extension (you can verify).
 what kind of error are you getting? do you hava a logs ?

**Comment by justechn** [comment]
nevermind I figured it out.

**Comment by brunoribeiro-beta** [comment]
@justechn could you explain what you figured out? I'm having a similar problem and can't understand why.
