### ISSUE TITLE
Ease for asserts with same setup

### ISSUE THREAD

**Issue by mjgpy3** [angular/protractor#2317]
Hello,

I understand that protractor is trying to reduce state bleed (like jasmine) by having a fresh case-run for each `it`, that's cool. I'm just curious if there is (or could be) some way for the discerning tester to specify something like "these `it`s have the same setup, and I am confident they don't mutate state".

The benefit being, then protractor could just cluster the asserts and run them all after a single state-setup, rather than navigating from the beginning of the application each time (which can be expensive if the area under test is deeply nested in the application).

Cheers

**Comment by sjelin** [comment]
Not sure what you're talking about exactly.  What state is being reset by Protractor between `it` blocks?  It shouldn't be restarting the browser or anything by default.

**Comment by mjgpy3** [comment]
Interesting. I'm talking about the state that's setup in `beforeEach` blocks. So, for example I might have:
```
...
describe('when I\'m at the last page of the app', function() {
  beforeEach(function () {
    lastPage.getHere();
  });

  it('has the correct page title', function () {
    expect(...)...
  });

  it('has expected data', function () {
    expect(...)...
  });
});
```

If I know that neither of the `it`s mutates state, and that `lastPage.getHere()` takes a long time to run, I would rather it (`lastPage.getHere();`) not be run twice.

Does that make sense?

**Comment by mjgpy3** [comment]
Perhaps my run is not properly configured, but the test cases would be run like:

> beforeEach -> first it
> beforeEach -> second it

It would be nice if I could (like jasmine's `beforeAll`) run them like:

> beforeEach -> first it -> second it

**Comment by sjelin** [comment]
You can use jasmine's `beforeAll` as long as you're using protractor with jasmine 2.x

**Comment by mjgpy3** [comment]
Cool, thank you! That must by why I don't think I have it (we're not using 2.x)
