### ISSUE TITLE
Difference / benefits using browser.setLocation ? 

### ISSUE THREAD

**Issue by nserebry** [angular/protractor#2318]
Hi , 
Currently running in some random test failures using protractor+jasmine+angular.

I was able to resolve issue using **browser.setLocation**  BeforeEach test for cases like page redirected during the test run,  instead of just **browser.driver.get** and after **browser.sleep();**

Wanted to know more about different  and usage of  the browser.setLocation ( it seems like all the page objects are loaded and saved during test). I found this on protractor API page. The code example will be good enough.

**Comment by sjelin** [comment]
`browser.setLocation()` uses Angular's `$location`.  `browser.driver.get` is like typing in a new URL into the search bar.  `browser.get`, which is what most people use, is a wrapped version of  `browser.driver.get` which waits for everything to be synced.

**Comment by nserebry** [comment]
good point I meant browser.get but still everything wasn't synced. adding browser.setLocation and browser.waitForAngular(); resolved it. 
Thank you.
