### ISSUE TITLE
Cucumber JVM

### ISSUE THREAD

**Issue by BevanR** [angular/protractor#2319]
Are there any plans to support [Cucumber-JVM](https://github.com/cucumber/cucumber-jvm) as well as Cucumber JS?

Would such a contribution be welcomed?

**Comment by sjelin** [comment]
Not sure I understand the question.  We support tests written in Cucumber.

**Comment by BevanR** [comment]
There are various implementations in different languages of tools that parse Gherkin `*.feature` files and drive browsers to execute the steps and scenarios, defined in the Gherkin `*.feature` files.  E.g.

- Cucumber (Ruby)
- Cucumber JS
- Cucumber JVM
- Behat (PHP)
- Specflow (C#)
- and more

I believe protractor only works with Cucumber JS.  Perhaps it already supports other implementations?

If not, are there any plans to support more?

**Comment by sjelin** [comment]
Actually there are plans to spin cucumber JS support out into a separate repo.  Regardless, Protractor doesn't support Java, so how could it possibly support Cucumber JVM?

**Comment by juliemr** [comment]
Closing stale issues. Please open a new issue if you feel there is still a general bug.
