### ISSUE TITLE
StaleElementReferenceError when i use click()

### ISSUE THREAD

**Issue by teo89** [angular/protractor#2322]
Hello, 
I am new in protractor and i can't understand something I have the follow code

```js
element.all(by.repeater('item in $data')).then(function(results) {
	for (i = 0; i < results.length; i++) {
		var editLink = results[i].element(by.xpath("//a[@tooltip='Edit']"));
		browser.driver.wait(protractor.until.elementIsVisible(editLink), 15000);
		expect(editLink.isPresent()).toBeTruthy();
		results[i].evaluate('item.name').then(function (nameElement) {
			if (nameElement  ==  "TEST") {
				editLink.click();
			 }
		});
	}
});
```

StaleElementReferenceError: stale element reference: element is not attached to the page document

I am sure that editLink exists in my page but click() doesn't work. 
I have the same thing in table for deleteLink and works fine. Actually what really means that error?
thanks in advanced

**Comment by jlin412** [comment]
I think that you should use element.all(by.repeater('item in $data')).each
or element.all(by.repeater('item in $data')).map

**Comment by teo89** [comment]
I did that
element.all(By.repeater('item in $data')).map(function(elm) {
				  // Get the value you are interested in finding and return the element too.
				  return {
				    name: elm.evaluate('item.name'),
				    editLink: element(by.xpath("//a[@tooltip='Edit']"))
				  };
				}).then(function(list) {
				  // Find your text here. Otherwise fail.
				  for(var i = 0; i<list.length; i++) {
				    if(list[i].name == "TEST") {
				      return list[i].editLink;
				    }
				  }
				}).then(function(link) {
				  // Perform an action on the element you found.
					link.click();
				});
			
but when i do that test nothing happens

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
