### ISSUE TITLE
Improve documentation for evaluate()

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2323]
I think this is a documentation improvement request.

The [`ElementArrayFinder.evaluate` API documentation page](http://angular.github.io/protractor/#/api?view=ElementArrayFinder.prototype.evaluate) does not provide an example on how to use `evaluate()` on a result of `element.all()`, but instead it shows how to use it on a `element()`:

    var value = element(by.id('foo')).evaluate('variableInScope');

On the other hand [`ElementFinder.evaluate`API documentation page](http://angular.github.io/protractor/#/api?view=ElementFinder.prototype.evaluate) does not have an example at all.

Thanks.

**Comment by sjelin** [comment]
I think the real issue here is that the `@see` tag doesn't provide a link
