### ISSUE TITLE
browser.getCurrentUrl() returning an object instead of URL

### ISSUE THREAD

**Issue by jkurikeshu** [angular/protractor#2324]
I am running a protractor test to test if the proper URL is being displayed. When logging the method getCurrentUrl() within browser, I receive an object. Is there something I am missing?

    describe('angularjs homepage todo list', function() {
        it('should add a todo', function() {
            browser.get('https://angularjs.org');

            console.log(browser.getCurrentUrl());
        });
    });

Here is the output with the object logged instead of URL.

![issue-url](https://cloud.githubusercontent.com/assets/8517251/8604491/d953c4be-264c-11e5-9c31-a88b1020d9fc.PNG)

**Comment by sjelin** [comment]
[`getCurrentUrl` returns a promise](http://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.getCurrentUrl)

**Comment by awarerahul** [comment]
how can i get exact URL.

**Comment by muzamilabbasi** [comment]
@awarerahul  you gotta resolve the promise liek this 

wd.getCurrentUrl().then( function( url ) {
console.log(url);
});

**Comment by shashankrshukla** [comment]
Thanks

**Comment by IlliaSmolin** [comment]
or simply "await" for the .getCurrentUrl(), then the output will be the usable string
Example:

```
async function someFunc() {
  await browser.getCurrentUrl(); //output: "http://your-current.url"
}
```
