### ISSUE TITLE
Issues with browser.actions().mouseMove() after upgrading from 1.x to 2.x

### ISSUE THREAD

**Issue by caguthrie** [angular/protractor#2330]
I'm getting this error:

`UnknownError: null`
`at new bot.Error ...`
`From: Task: ActionSequence.perform ...`

when I try to run this code:

`browser.actions().mouseMove(browser.findElement(protractor.By.css(selector))).perform();`

Worked fine in 1.x for me but now not working in 2.x.  Any ideas?

**Comment by sjelin** [comment]
Not sure.  Could you show me more of the stacktrace?  And are you sure the only difference is 1.x -> 2.x?  Are you able to create a minimal reproduction?

**Comment by bvasilchik** [comment]
does this work for you

```javascript
browser.actions().mouseMove(element(by.css(selector))).perform();
```

**Comment by caguthrie** [comment]
@bvasilchik 

That works great!  Thanks.  Looks like it just isn't supporting legacy commands anymore?

**Comment by Arav4prot** [comment]
I am using Protractor 4.0.8 and 2.5.2 Jasmine framework(Integrated with Visual Studio) however the below syntax is not working.

browser.actions().mouseMove(element(by.css('a[href*="task/search"]'))).perform();

Please can someone provide your help in making this work

**Comment by Soumya1710** [comment]
@Arav4prot Did you get solution for this?
