### ISSUE TITLE
Add programmatic API

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#2334]
Please add a programmatic API, so we can integrate Protractor more easily into our custom workflow. It looks like every plugin author (gulp, Grunt, etc.) needs to spawn a child process and pass arguments via command line to configure Protractor. This can be quite cumbersome (like passing complex arrays via command line

**Comment by sjelin** [comment]
If there's a lot of interest in this we'll look into it, but it my gut reaction is that this would be a lot of work for a small group of users who already have a viable alternative.

In the mean time, if you get sick of passing everything through the commandline, keep in mind that the config file can be any node file that exports `config` property.  So you could put logic into the config file ([example](https://github.com/angular/protractor/blob/master/spec/plugins/jasmine1PostTestConf.js)).  So if you wanted to you could always read an array from a file using `require` or even [`fs`](https://nodejs.org/api/fs.html).

**Comment by scottopherson** [comment]
+1

Something like Karma's [public API](http://karma-runner.github.io/0.13/dev/public-api.html) would be nice:

    var Launcher = require('protractor').Launcher;
    var launcher = new Launcher(configOptions, function (exitCode) {
      console.log('Protractor has exited with ' + exitCode);
      process.exit(exitCode);
    });

I looked into using [launcher.js](https://github.com/angular/protractor/blob/master/lib/launcher.js) directly and it shows promise but I'd like to be able to define my own [cleanUpAndExit](https://github.com/angular/protractor/blob/master/lib/launcher.js#L193-L206).

**Comment by donaldpipowitch** [comment]
> In the mean time, if you get sick of passing everything through the commandline, keep in mind that the config file can be any node file that exports config property.

That is true, but the config file can't contain async code: https://github.com/angular/protractor/issues/578

**Comment by juliemr** [comment]
You can do this with `require('protractor/launcher')` and then initializing it with a configuration object.
