### ISSUE TITLE
Should by.exactRepeater also split by "="?

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2335]
Following up http://stackoverflow.com/questions/31389521/protractor-by-repeater-not-finding-anything.

There is the following repeater:

    item in filteredItems = (items | filter:'abc')

Currently, it is not possible to locate it by:

    element.all(by.exactRepeater("item in filteredItems"));

We had to include everything before the pipe:

    element.all(by.exactRepeater("item in filteredItems = (items"));

This is because the [`findAllRepeaterRows()`](https://github.com/angular/protractor/blob/e7873093ada02ad6c9d6e190b7184775ab3686ce/lib/clientsidescripts.js#L168) "client side" function splits by "track by", "|" and "as" only:

    return ngRepeat.split(' track by ')[0].split(' as ')[0].split('|')[0].trim() == repeater;

Should it also split by the equal sign `=`?

Thank you.

**Comment by sjelin** [comment]
Good catch

**Comment by alecxe** [comment]
That was quick. Many thanks!
