### ISSUE TITLE
No 'ng-touched' on form items when running e2e on Travis CI

### ISSUE THREAD

**Issue by mrowles** [angular/protractor#2339]
I noticed my tests were flaky when checked form validity (i.e., show error state hit when ng-touched && ng-invalid on form inputs) and it took me a while to figure out, but it appears that 'ng-touched' is never applied to any of my form fields when tabbing or clicking through, regardless of any input. 

The protractor tests run fine locally, but when running on Travis CI (same browser and everything). We've tried alternatives such as timeouts, browser.actions rather than sendKeys and so on.

The only difference in environments I can see are OSX (local) vs Linux (Travis), the browser versions are the same (FF 39.0). Any ideas? Thanks in advance!

**Comment by juliemr** [comment]
Sorry for the delay here @mrowles - do you have a reproducible test case we can take a look at?

**Comment by juliemr** [comment]
Closing this as really out of date - please open a new issue if you are still seeing problems with the latest version of Protractor.
