### ISSUE TITLE
Protractor and https proxy

### ISSUE THREAD

**Issue by fgather** [angular/protractor#2345]
Hi,

we have to use protractor with browserstack behind a https proxy and until now a solution like this worked:
```js
process.env.http_proxy = 'https://' + config.proxy.host + ':' + config.proxy.port;
var globalTunnel = require ('global-tunnel');
globalTunnel.initialize ();
```
Unfortunately, when doing this, the communication with the proxy itself is via http, while the communication from the proxy to browserstack is via https. The proxy was recently configured to prohibit incoming http requests. We then tried to add 
```js
proxy = {
            proxyType: 'manual',
            sslProxy: config.proxy.host + ':' + config.proxy.port
        }
```
to our browser capabilities, but the proxy configuration is not forwarded towards webdriver. Furthermore, adding a new proxy config variable and adding
```js
usingWebDriverProxy(this.config_.proxy)
```
to the getNewDriver in driverProvider.js also doesn't work, and it still uses http requests. Is this a limitation of the webdriver? Or could it be fixed from within protractor?

Many Regards,
Florian

**Comment by fgather** [comment]
Hi, 

think I solved the problem. It is an issue with globaltunnel.js. 

However, the change in driverProvider.js, described above, still has to be done to support webdriver's ability for proxies. Are there any plans to integrate this feature?

**Comment by sjelin** [comment]
@hankduan weren't you doing something with proxies?

**Comment by fgather** [comment]
#2872 is merged, so this should be closed.
