### ISSUE TITLE
Improve documentation for browser.enterRepl

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2349]
Follow up to [What is the difference between pause() and enterRepl()?](http://stackoverflow.com/questions/31413300/what-is-the-difference-between-pause-and-enterrepl).

Protractor API docs for [`pause()`](http://angular.github.io/protractor/#/api?view=Protractor.prototype.pause) and [`enterRepl()`](http://angular.github.io/protractor/#/api?view=Protractor.prototype.enterRepl) are very similar and can cause confusion and questions about differences between the two.

Also, [Debugging](http://angular.github.io/protractor/#/debugging) page should probably have a note about `enterRepl()`.

Thanks!

**Comment by juliemr** [comment]
We should probably just make `enterRepl` private - I don't think there's a reason for users to use anything other than `pause`.

**Comment by mgiambalvo** [comment]
This is also relevant to the recent debugger changes.

**Comment by juliemr** [comment]
I think that this is taken care of in https://github.com/angular/protractor/pull/3828
