### ISSUE TITLE
Issue with button click and page reload

### ISSUE THREAD

**Issue by vsathyak** [angular/protractor#2353]
@juliemr , @hankduan 

In the app which I am working, after clicking on a button, its taking me to a new angular page and the dev people designed in a way that while opening the new page,angular stuff is reloaded. So for a moment protractor didn't get the angular stuff and it will throw the following error : 
Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window" .

Here is my click method.
this.openSearchedDeviceCard = function () {
        element(by.xpath("//div[@class='card card--default']/descendant::h6[1]/a")).click();
        //browser.sleep(5000);
    };

Please let me know if there is any work around other that using browser.sleep(5000);

**Comment by sjelin** [comment]
We're working on it.  Still thinking about the ideal solution tbh
