### ISSUE TITLE
Getting browser issue while using protractor"we have determined the browser you are using is not supporting the technology....."

### ISSUE THREAD

**Issue by Msubhashree** [angular/protractor#2354]
![protractor issue](https://cloud.githubusercontent.com/assets/13361507/8717285/7bc7fa8c-2b5f-11e5-8bf5-240867802774.jpg)

Protractor version:2.1.0

**Comment by sjelin** [comment]
That's not an error from us (all though we don't support all browsers).  It might be from selenium or your app.
