### ISSUE TITLE
Support Document links don't seem to work

### ISSUE THREAD

**Issue by chris31389** [angular/protractor#2362]
I'm using the protractor documentation at http://angular.github.io/protractor/#/

I've gone to "Protractor Setup" > "Choosing a Framework" (http://angular.github.io/protractor/#/frameworks)

All of the relative links fail to work and throw a 404 error.  Can someone help guide me to the actual links for those pages?  I really want to go to this link "/spec/cucumber"

Thank,
Chris

**Comment by sjelin** [comment]
The correct file is https://github.com/angular/protractor/blob/master/spec/cucumber/lib.feature.  Sorry, this will be fixed next time we update the website.  For now, if a link isn't working, you may want to check out the version of the page at https://github.com/angular/protractor/tree/master/docs
