### ISSUE TITLE
Accessibility Plugin does not reload page before running tests. 

### ISSUE THREAD

**Issue by JLLeitschuh** [angular/protractor#2363]
I have encountered cases where running the chrome accessibility tests can cause *Stale Element Reference*. See: #2331
This can happen because browser clicks can create dom elements that get removed for some reason while the chrome accessibility tests are running. A good way to mitigate this problem would be to do a `browser.refresh()` before running the accessibility tests.
This could be added as an optional parameter in the protractor config.

 - Is this something the devs also think would be helpful to add?
 - If added should it default to be enabled or disabled?

**Comment by juliemr** [comment]
Moved to https://github.com/angular/protractor-accessibility-plugin/issues/7
