### ISSUE TITLE
Problem with remote upload

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#2371]
See https://github.com/angular/protractor/issues/2153#issuecomment-123439603

**Comment by bjaanes** [comment]
Having the exact same issue.

**Comment by raghavan85** [comment]
I'd appreciate if someone can please look into this issue and see how we can fix it soon. Its also reported in here: https://github.com/angular/protractor/issues/1959

**Comment by k1ngdr3w** [comment]
Has anyone diagnosed this issue yet?

**Comment by sjelin** [comment]
It's a problem with WebDriver.  Also, it's a duplicate of #1959 probably
