### ISSUE TITLE
Element found using by.cssContainingText doesn't contain that text

### ISSUE THREAD

**Issue by Ruberik** [angular/protractor#2375]
I've encountered a problem in Chrome, Firefox and IE where some percentage of the time (maybe 10% for Chrome and FF, maybe 50% for IE) my tests fail because a selector using cssContainingText found an element, and then that element didn't contain the text.

Side-note: I'm very much a Protractor newbie, as my code will probably indicate, so I welcome messages that don't solve my problem but do give useful suggestions for improving my work. I wonder if the problem here is just that I don't understand how to make all this asynchronous stuff work in Protractor. It would be easier if I could make incorrectly-written tests fail consistently, as opposed to rarely; any tips for that would be greatly appreciated. I've tried telling my server to respond to requests really slowly, but that doesn't seem to help.

## Example 1 (fails about half the time in IE):

```
browser.get('/view_email?id=1');
var mystr = 'spooogleyoogley';
var email_body = element(by.cssContainingText('div', mystr));
expect(email_body.getText()).toContain(mystr);
```

The failure message is your basic `"expected ACTUAL_STRING to contain DESIRED_STRING"`, where `ACTUAL_STRING` contains several thousand characters of email, with the following at the end:
`Thanks.spooogleyoogle`
[note the missing 'y' at the end.]

The page in question is Angular. When a user loads the page /view_email?id=1, an $http request is issued to find the subject/body/etc. of email 1 -- the body of which ends with "Thanks.spooogleyoogley". The body is put into a div via ng-bind-html, and nothing further happens on the page. When Protractor loads the page, the same thing happens (I have a dummy DB that's reset between test cases to take and respond to requests).

I could imagine that I'm failing to wait for the right condition, except how the heck did protractor even decide which div email_body referred to if it didn't have mystr in it?

## Example 2 (fails maybe 10% of the time in Chrome/Firefox)

In this test the browser loads page A, clicks a button to open modal B, and does some more clicking. Extra details: the link in A doesn't exist until an http request is issued and comes back; same with the stuff in B that's going to get clicked on. Since there's a pause between page loads and the things I want to click being clickable, it's possible we don't make it to the modal; but I don't think that affects the problem I'll describe below.

Inside the modal, there are are several boxes containing text that looks like this:
```
Black
Selected: 20 / 30
```
```
White
Selected: 5 / 10
```
I'm trying to test that the total number of selected items is 25. To get the total number of selected items in the test, I'm using the following code fragment:
```
var total_selected = item_selection.all(by.cssContainingText('td', 'Selected:')).
    map(function(elem) {
        return elem.getText().then(function(text) {
            var match_regexp = /Selected: *(\d+) *\//;
            return parseInt(text.match(match_regexp)[1]);
        });
    }).then(function(arr) {
        return arr.reduce(function(acc, num){return acc + num});
    });
```
The failure message is `Cannot read property '1' of null`, which means the text doesn't match the pattern I expected it to match. When I throw in console.log(text), or expect(text).toBe('asdf'), so I can see what the text is, I just get the empty string.

Again I'm baffled: why was this returned by the selector if the text it contained was the empty string? Unlike in example 1 (which I've never seen fail in Chrome or Firefox), the text field could get mutated after the match happens, but it would get changed from `Selected: 10 / 10` to `Selected: 5 / 10`, which still matches.

I'm sorry to be submitting this using the "issue tracker", since this is almost certainly an issue with my code and understanding rather than an issue with Protractor, but I couldn't find anything else that looked like a support forum, so here we are. Please redirect me if appropriate.

Thanks.spooogleyoogle

**Comment by sjelin** [comment]
This is strange.  If you put in a `browser.pause()` and look at the page what does the text look like?

**Comment by Ruberik** [comment]
I couldn't get `browser.pause()` to work, so I added taking a screenshot in afterEach per #114. The results are confusing: for Example 1, IE shows a webpage from earlier in the test instead of the `show_email` page; but I strongly suspect the `show_email` page is loaded because the `expect` failure has most of the contents of the email! For Example 2, Chrome won't screenshot, but Firefox shows page A. That suggests the modal didn't open, but I'm not inclined to trust it given what happened with Example 1.

Some followups:
(1) How can I get browser.pause() to work? It's never once worked for me. Do I need to invoke protractor in some special way? Here's the modification I made to my code from above, which did nothing:
```
     return elem.getText().then(function(text) {
         var match_regexp = /Selected: *(\d+) *\//;
         if (text.match(match_regexp) === null) {
             browser.pause();
         }   
         return parseInt(text.match(match_regexp)[1]);
     }); 
```
(2) Even if the screenshot is right and the modal isn't opening, there shouldn't be *anything* that says "Selected:", so there's still something about this that doesn't make sense. We should still find out for sure whether it is.
(3) Note that taking screenshots always fails in Chrome for the reasons outlined in [chromedriver#1083](https://code.google.com/p/chromedriver/issues/detail?id=1083), which is frustrating, but at least it works in Firefox and IE (well, it produces a screenshot; it's unclear to me whether it's the right screenshot).
(4) What's the correct way to load a page, wait for it to make an http request to populate its data, and click on a button that exists after the http request is done? Here's what I've done:
```
beforeEach(function() {
    utils.resetDb();
    browser.get('/#/team/1');
});
it('should open a modal for team 1 and then select all small shirts', function() {
    $('#team_table').body.element(by.cssContainingText('button', 'View shirts')).click();
    // ... more stuff
});
```
Is that supposed to work, or should I have `wait`s and `then`s scattered about? It seems to work either all or almost all of the time; and even when I tell the server to delay 2 seconds before sending a response, so the 'View shirts' button doesn't exist for a while, it still seems to work.

**Comment by Ruberik** [comment]
I've added lots of screenshots and some logging into my code. What I've learned so far:

1. If I write my code as follows for Example 1:
```
var email_body = element(by.cssContainingText('div', mystr));
utils.takeAndSaveScreenshot('email_body-rendered');  // that string just goes in the filename
expect(email_body.getText()).toContain(mystr);
```
...then I get a nice picture of an email ending with mystr, right after the div was found *because it contained mystr*, and before the expectation fails saying that the div doesn't contain mystr.
2. I can't seem to convince Firefox to fail any tests, but Chrome is very happy to fail Example 2. I've added the following logging to the code:
```
return elem.getText().then(function(text) {
         var match_regexp = /Selected: *(\d+) *\//;
         if (text.match(match_regexp) === null) {
             console.log('null found');
         }   
         return parseInt(text.match(match_regexp)[1]);
     });
```
...and it outputs `null found` 5 times. I tried adding a screenshot, but I can't get a screenshot out of Chrome. It happens that 5 is how many times the string `Selected:` appears in the modal, which strongly suggests that the modal is in fact being opened. Will add further information about screenshots and logging to this page if I can get any more information out of them.

**Comment by Ruberik** [comment]
Another followup:
Example 1 is still, bafflingly, failing.
Example 2 I've managed to "fix" -- I still don't understand why it was giving the error it was giving, but the test is now passing, so I guess I care less. I made a few "wait" functions for myself and started using them religiously. I'll repost them here so others can use them and improve them.

```
function waitForElement(el, timeout) {
    return browser.wait(protractor.until.elementIsVisible(el), timeout);
}

function waitForClickable(el, pseudo_timeout) {
    waitForElement(el, pseudo_timeout);
    browser.wait(protractor.until.elementIsEnabled(el), pseudo_timeout);
}

function clickWhenClickable(el, pseudo_timeout) {
    waitForClickable(el, pseudo_timeout);
    return el.click();
}
```

**Comment by Ruberik** [comment]
As everyone who took one look at this thread and passed it by probably suspected, this was a PEBCAK error that is possibly too embarrassing to explain. I'll leave this thread with this code, which I think is potentially useful for other people who *need* to wait for things to happen on their pages, but should be taken with a grain of salt given the degree to which I'm still learning this framework.

```
function waitForElement(el, timeout_ms) {
    return browser.wait(protractor.ExpectedConditions.presenceOf(el), timeout_ms);
};

function waitForNoElement(el, timeout_ms) {
    return browser.wait(protractor.ExpectedConditions.not(protractor.ExpectedConditions.presenceOf(el)), timeout_ms);
};

function waitForClickable(el, timeout_ms) {
    waitForElement(el, timeout_ms);
    browser.wait(protractor.until.elementIsVisible(el), timeout_ms);
    return browser.wait(protractor.until.elementIsEnabled(el), timeout_ms);
};

function clickWhenClickable(el, timeout_ms) {
    waitForClickable(el, timeout_ms);
    return el.click();
};

// Works for non-Angular pages, such as login pages.
function clickLocatorWhenClickable(locator, timeout_ms) {
    browser.wait(protractor.until.elementLocated(locator), timeout_ms);
    var el = browser.driver.findElement(locator);
    browser.wait(protractor.until.elementIsVisible(el), timeout_ms);
    browser.wait(protractor.until.elementIsEnabled(el), timeout_ms);
    return el.click();
};
```
