### ISSUE TITLE
Specs are executed before async beforeAll completes if...

### ISSUE THREAD

**Issue by mocsharp** [angular/protractor#2378]
I opened this bug originally on https://github.com/jasmine/jasmine/issues/898 but was suggested that it is related to protractor.

```javascript
describe('test suite', function(){
   beforeAll(function(done) {
       // login logic that navigates to Windows Azure AD login page
       // then enter login on azure
      // then wait for azure to return to my app
      // then click on a button for logged-in user
      .then(function(){
          done();
       });
   }, 20000);

   describe('verify bla', function() {
          it('should bla....', function() {

         });
   });
});
```

From the sample code above, the ```it``` spec gets executed before beforeAll calls done and fails with the following message:
```- Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window"```

This used to work in protractor 1.x + jasmine 1.x and stopped working after we upgraded to jasmine v2.3.4 + protractor 2.1.
Thanks.

**Comment by mocsharp** [comment]
It looks like a chrome/chrome driver issue.  The same specs are failing with Chrome 43/44 but passing with Chrome 42.  Where should I file this bug? Thanks.

**Comment by sjelin** [comment]
Probably the [selenium github](https://github.com/SeleniumHQ/selenium).  Sorry for the slow response - hopefully the problem has since been fixed!

**Comment by dagumak** [comment]
@mocsharp Did you ever get this sorted?

**Comment by incompl** [comment]
I am seeing this issue with Chrome 50. Is there a workaround?

**Comment by matanh-tzmedical** [comment]
Seems like this can be circumvented with [browser.wait](http://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.wait)

    beforeAll(function () {
        browser.wait(doSomethingThatReturnsAPromise());
    });

**Comment by alexhalf** [comment]
jasmine 2.5.2 and 2.6.0 support asynchronous for me only with the code: 
(angular 2 + typescript)

```
describe('some test', function(){
const before = function(resolve){
   ....your async actions
  some_callback(){
    resolve()
  }
}

beforeAll(function(done){
   new Promise(before).then(done) //really work
   some_callback(){
     done() //!Does not work!
   }
})

it('',function(){....})
...
it('',function(){....})

})

```
# Why i can not easy call done?
