### ISSUE TITLE
Bug: alerts in quick succession are missed

### ISSUE THREAD

**Issue by petebacondarwin** [angular/protractor#2380]
In Angular.js, we have a test that opens an alert and then checks what is displayed in it. It runs by fine itself. But we actually run the test twice (once with jqlite and once with jquery).

It seems that because these two tests open up the alerts in quick succession Protractor (or ChromeDriver) fails to find the alert and so our second test fails.

If I put a `sleep(100)` in before accessing the alert it passes
This seems to be reliably failing both on our CI server (jenkins) and locally (edited)
Here is an example failure: https://ci.angularjs.org/view/AngularJS/job/angular.js-angular-master/4129/console

I believe that my Chrome updated shortly before the failures began, and we confirmed that our CI server is also running the latest Chrome.

Here is our workaround: https://github.com/angular/angular.js/commit/f91eb0e9ec414c094fa6a7054bfd0e6f1002f172

**Comment by petebacondarwin** [comment]
This could be related to https://github.com/angular/protractor/issues/1486

**Comment by hankduan** [comment]
I believe this is working as intended. Webdriver does not wait for an alert to open before executing the next item in the control flow, and protractor is simply deferring to the webdriver command. (i.e. Protractor only waits for Angular readiness).

I just tried this on raw webdriver with the following test, and it fails:

```javascript
var webdriver = require('selenium-webdriver');
var driver = new webdriver.Builder().
  usingServer('http://localhost:4444/wd/hub').
  withCapabilities(webdriver.Capabilities.chrome()).
  build();

driver.get('http://localhost:8081/index.html#/form');
var alertButtonLocator = webdriver.By.css('#alertbutton');
driver.findElement(alertButtonLocator).then(function(elem) {
  elem.click();
  // driver.sleep(100); // uncomment to pass the test
  var alertDialog = driver.switchTo().alert();
  alertDialog.getText().then(function(text) {
    console.log('text is: ' + text);
  });
  alertDialog.accept();
});
```

Protractor does not inherently wait for alerts, so to properly wait for alerts, you need to explicitly call it out:

```javascript
 it('should deal with alerts', function() {
    function openAndCloseAlert () {
      var alertButton = $('#alertbutton');
      alertButton.click();

      // wait for alert (comment out this and test would fail)
      browser.wait(protractor.ExpectedConditions.alertIsPresent(), 1000); 

      var alertDialog = browser.switchTo().alert();
      expect(alertDialog.getText()).toEqual('Hello');
      alertDialog.accept();
    };

    openAndCloseAlert();
    openAndCloseAlert();
    openAndCloseAlert();
  });
```

Your original example could have worked (and failed now) for a variety of reasons affecting timing.

**Comment by trupti11** [comment]
I know I am late to the party, however, I have a solution that might help make this work without the ExpectedConditions:
helpers.closeDialogWithConsectivePopups = function (handleType, title, closeWindow) {
  webdriverJS.sleep(testData.timeOuts.salesforceWindowPopupTimeout);

  var handlePromise = browser.getAllWindowHandles();
  var handleToTest = '';
  browser.ignoreSynchronization = true;
  handlePromise.then(function(handles) {
    for (var i=0; i < handles.length; i++) {
      webdriverJS.switchTo().window(handles[i]).then(function (handle) {

        webdriverJS.getCurrentUrl().then(function (url) {

          webdriverJS.getTitle().then(function (title) {
            if (/Fax/.test(title) && /verify/.test(url)) {
              handleToTest = handle;
              console.log("Title #: " + title);
              console.log("URL #: " + url);
            }
          });

          if (/print/.test(url)) {
            var body = element(by.tagName("body"));
            body.sendKeys(protractor.Key.ESCAPE);
          }

        });
      });
    }
  });
};
