### ISSUE TITLE
Issue with Protractor 2.1.0 and Cucumber. 

### ISSUE THREAD

**Issue by richmondp** [angular/protractor#2381]
Hi, 

I got the latest version of protractor (via `npm install -g protractor`) which is **2.1.0** and I am trying to run with cucumber but I am getting the following issue . 

> 'Cannot call method 'apply' of undefined'

I tracked it down to a bug in lib/frameworks/cucumber.js which looks like it has been fixed on 9th June 2015 https://github.com/angular/protractor/pull/2213 raised from this issue https://github.com/cucumber/cucumber-js/issues/342

The latest code I installed via npm still has the issue though. Should a new version be pushed out (2.1.1)? Or as per usual am I doing something stupid?

**Comment by gnikhil2** [comment]
Modify the
  cucumberOpts: {
    require: 'features/stepDefinitions.js',
    format: 'pretty'
  }

It should work now.

**Comment by richmondp** [comment]
Thanks, that will help me get past it for now.
