### ISSUE TITLE
Menu and Submenu selection issue

### ISSUE THREAD

**Issue by srivch** [angular/protractor#2382]
we are using protractor to test one of our pages and we a running into the below issue randomly.

protractor version: 2.1.0
jasmine: 2

	//main menu selection
	browser.actions().click(element(by.linkText('MainMenu'))).perform();
	//submenu selection by linktest
	browser.actions().click(element(by.linkText('SubMenu1'))).perform();
	//submenu selection by id
        //browser.actions().click(element(by.id('SubMenu1'))).perform();

Issue 1: When we use linktext option it seems to work more consistently, but when we use id for selection it works only 20% of the time.. We consistently get the error that unable to find "SubMenu1" when we locate using id.

here is the sample html

	<li class="dropdown">
		<a href="#" id="MainMenu" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false">
			MainMenu
			<span class="caret"></span>
		</a>
		<ul class="dropdown-menu">
			<li id="SubMenu1"><a href="SubMenu1.html">SubMenu1</a></li>
			<li><a href="SubMenu2.html">SubMenu2</a></li>
			<li><a href="SubMenu3.html">SubMenu3</a></li>
			<li><a href="SubMenu4.html">SubMenu4</a></li>
		</ul>
	</li>

**Comment by sjelin** [comment]
I suspect that this is a race condition, where the submenu is not being given enough time to show up.  Try using `element(...).click()` instead of `browser.actions().click(element(...)).perform()`.  This should allow Protractor the ability to synchronize your code.

**Comment by hhaamm** [comment]
@srivch You could also wait until the element you want to click is present, using browser.driver.wait.

You can create a custom wait function, check this thread:
https://github.com/angular/protractor/issues/610

Something like this should work:

    function waitElementPresent(elm) {
        return browser.driver.wait(function() {
            // Return a condition. Code will continue to run until is true 
            return elm.isPresent().then(function(url) {
                return url;
            }, function(err) {
                // errored  .. TODO: retry
                throw err;
            });
        }, timeout, 'Expectation error: Timed out');
    }

And then call a waitElementPresent(...) after every click on every element.
