### ISSUE TITLE
Error noise

### ISSUE THREAD

**Issue by selfrefactor** [angular/protractor#2384]
I just need confirmation that it is my error and no one else have experienced it.
I notice that quite often I see noise errors in the results of my Protractor tests.
I run the same tests again and 60% of the errors were no longer there.
This is not the first time.
If it is a feature to have shaky test results, then I will just deal with it and move forward.

**Comment by sjelin** [comment]
Many people have flakey tests.  This is generally a problem with the tests though, not protractor.  Often people write race conditions into their tests without noticing.  If you've found a specific protractor feature with unreliable behavior, or can think of a use case that common trips up test writers, let us know!
