### ISSUE TITLE
[FEATURE REQUEST ] Create test app for angular 2

### ISSUE THREAD

**Issue by QuantumInformation** [angular/protractor#2388]
Is there a test app for angular 2 in progress? If not, is this something that I could help with? I am waiting a nice example that I can use  my test recorder with for angular 2.

https://github.com/QuantumInformation/test-recorder/blob/master/lib/codeGenerators/

**Comment by sjelin** [comment]
We'll wait until the Angular 2 API is stable (just a few weeks at this point?) before doing this.

**Comment by juliemr** [comment]
Assigning @sjelin who has started working on a test app for ng2

**Comment by sjelin** [comment]
Oh right I forgot.  I'll finish this today probably

**Comment by sjelin** [comment]
@cnishina I've started this but you're going to pick it up on Monday.  The stuff that's left shouldn't bee too hard and I'll help you

**Comment by juliemr** [comment]
This is done!
