### ISSUE TITLE
browser console.log capture omits arguments after the first

### ISSUE THREAD

**Issue by metamatt** [angular/protractor#2390]
If I call `console.log('format a number: %d', 42)` from code in the browser, then run this in protractor and inspect the browser logs with `browser.manage().logs().get('browser')`, the log entry I get is the unformatted first argument (`format a number: %d`) and not the expected formatted result (`format a number: 42`).

More generally, if I pass multiple arguments to console.log only the first one is logged, if the first argument is a string containing string-replacement format specifiers no replacement happens, and if the first argument is an object or something other than a string it's cast to a string, as far as the protractor-side log extraction is concerned.

(Actually: this happens for all log levels except console.info. `console.info` behaves differently; the log element extracted by protractor has a `.message` property which is a JSON-encoded string representing an object with the browser-side arguments (all of them), call stack, and level; and the log element itself has level.name WARNING instead of INFO.)

Apologies if this belongs in a different place; I don't know if the bug is in protractor or webdriver or chromedriver or elsewhere but I'll start here. I also don't know what the best way is to provide a repro case but this should be easy to repro in any protractor project.

**Comment by sjelin** [comment]
Sadly, selenium's browser logs are super inconsistent and generally work poorly.
