### ISSUE TITLE
Allow CLI options to override conf.js parameters

### ISSUE THREAD

**Issue by joshmgrant** [angular/protractor#2391]
It appears that arguments used when running protractor from the command line do not override values in the conf.js file. For example, if I run the command 

    protractor --baseUrl='http://local.app' conf.js

with the conf.js file

```javascript
module.export = {
    // some other params

     capabilities: {
        'browserName': (process.env.TEST_BROWSER_NAME || 'chrome'),
        'version': (process.env.TEST_BROWSER_VERSION || 'ANY')
    },

    baseUrl: 'http://test.app'
}
````
tests will execute using the baseUrl = 'http://test.app' in the conf.js instead of 'http://local.app'.
It could be that this is a specific issue to my setup, but it'd be helpful to allow the CLI to override parameters as needed in the conf.js file.

**Comment by NickTomlin** [comment]
This is working fine for me using `2.1.0` e.g. ` ne protractor --baseUrl http://angularjs.org protractor.conf.js`. It seems like it's something external? Can you verify with a fresh setup?

**Comment by sjelin** [comment]
Confirmed that I can overwrite parts of the config file via command line.  Not sure what's wrong with your setup.

**Comment by joshmgrant** [comment]
Thanks for this. I might've not had the proper setup, or the issue resolved itself.
