### ISSUE TITLE
Add argument to webdriver-manager to allow custom selenium ***FOLDER***

### ISSUE THREAD

**Issue by LukasKraushofer** [angular/protractor#2399]
In my company we are not able to use webdriver-manager update because our proxy refuses the connection to googlecloud!
I managed to download the files more or less illegal from home, but that`s not a solution for my co-workers.

I would prefer an argument for webdriver-manger start to specify the selenium folder location which includes the selenium-server...jar, chromedriver and so on. That would make it possible for us to add the driver files and the selenium-server to SVN so every one in our company can download the files.

If some versions get updated and we need the latest files we can go to our proxy guy and he will download the files from googlecloud once.

so please change from __dirname to an variable
https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L16

**Comment by jlin412** [comment]
you can add --proxy=[your proxy server url] with webdriver-maanger

**Comment by LukasKraushofer** [comment]
as I said, I'm not allowed to connect to googlecloud where the driver files and the selenium server are hosted

**Comment by cnishina** [comment]
We had a discussion about this and this appears to not help the majority of our users. 

In your own fork you could customize the `cdn` values in `bin/webdriver-manager`. The fix would be to change the 'https://selenium-release.storage.googleapis.com/' and 'https://chromedriver.storage.googleapis.com/' cdn values to download from a local server.

**Comment by cnishina** [comment]
This might be usefule: it appears that there is an `alternative_cdn` option. See ef6a09d798fd04124224f6ca48eb64d13eb01eff
