### ISSUE TITLE
IEDriver -  Page reload detected during async script

### ISSUE THREAD

**Issue by penfold** [angular/protractor#240]
The same config and scripts work okay with Chrome & Firefox but when using IE, I get the following failure...

Selenium output:

19:34:12.396 INFO - Executing: [new session: {browserName=ie}] at URL: /session)

19:34:12.398 INFO - Creating a new session for Capabilities [{browserName=ie}]
Started InternetExplorerDriver server (32-bit)
2.37.0.0
Listening on port 23442
19:34:15.099 INFO - I/O exception (java.net.SocketException) caught when processing request: Software caused connection abort: recv failed
19:34:15.100 INFO - Retrying request
19:34:15.112 INFO - Done: /session
19:34:15.133 INFO - Executing: [set script timeoutt: 11000] at URL: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/timeouts/async_script)
19:34:15.148 INFO - Done: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/timeouts
/async_script
19:34:15.236 INFO - Executing: [get: about:blank] at URL: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/url)
19:34:15.467 INFO - Done: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/url
19:34:15.486 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.href = "http://mywebsite.com/#/login", []] at URL: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/execute)
19:34:15.580 INFO - Done: /session/95af03d8-7d33-459f-9a8d-2042dab2550d/execute
19:34:15.599 INFO - Executing: [execute async script: return (function () {
  var attempts = arguments[0];
  var callback = arguments[arguments.length - 1];
  var check = function(n) {
    if (window.angular && window.angular.resumeBootstrap) {
      callback(true);
    } else if (n < 1) {
      callback(false);
    } else {
      window.setTimeout(function() {check(n - 1)}, 1000);
    }
  };
  check(attempts);
}).apply(null, arguments);, [10]] at URL: /session/95af03d8-7d33-459f-9a8d-2042d
ab2550d/execute_async)
19:34:17.225 WARN - Exception thrown
org.openqa.selenium.WebDriverException: Page reload detected during async script
 (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.08 seconds
Build info: version: '2.37.0', revision: 'a7c61cb', time: '2013-10-18 17:14:00'
System info: host: '##########', ip: '#########', os.name: 'Windows 7', os
.arch: 'x86', os.version: '6.1', java.version: '1.7.0_45'

---

Do you have any suggestions where I can start looking for a solution?

I'm using Protractor 0.12.0. The latest Selenium and IEDriver.

Thanks,
P

**Comment by RajEtamsetti** [comment]
@penfold , What is that you exactly did to get rid of this issue? IEDriver - Page reload detected during async script
