### ISSUE TITLE
 browser.takeScreenshot() dimensions do not match browser dimensions, why?

### ISSUE THREAD

**Issue by EMCP** [angular/protractor#2400]
Hi protractor team, I have a question on the ` browser.takeScreenshot()` functionality.

It seems I can set the window/browser size.. via a call such as 

```
    describe("login", function () {

        it("should go to login page", function () {
            browser.driver.manage().window().setSize(width, height);
            browser.get('/');
            expect(browser.getTitle()).toEqual("MyTitle");
            browser.takeScreenshot().then(function(png) {
                var stream = fs.createWriteStream("somepathandfilename");
                stream.write(new Buffer(png, 'base64'));
                stream.end();
           });
        });

```

The result of this process isn't matching the browser drivers dimensions.. I can work around this but just wondering, why?

Resulting image in the case of a width x height = `367 x 667` , was turned into `800x1190`

**Comment by sjelin** [comment]
What an interesting thing.  It's part of selenium, so you'd have to ask them.

**Comment by EMCP** [comment]
oh I understand I'll move this to there, thank you
