### ISSUE TITLE
Confusing error when chromedriver.exe is not present

### ISSUE THREAD

**Issue by hippich** [angular/protractor#2403]
[launcher] Error: Error: Could not find chromedriver at /proj/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver.exe

Running this in Ubuntu make it really confusing on why protractor would try to load windows executable. While in reality it simply could not find originally specified file and just added '.exe' to the end:

https://github.com/angular/protractor/blob/master/lib/driverProviders/direct.js#L62

I think it should explain better that it looked at both files with .exe and without one. Even more - never make it look for .exe file if it is not Windows OS.

**Comment by NickTomlin** [comment]
Closing as we now check for windows before looking for `.exe` (https://github.com/angular/protractor/commit/f533341085921409d16d577e38ba1745c37a17b7)
