### ISSUE TITLE
browser.wait execute functions in wrong context?

### ISSUE THREAD

**Issue by mohsen1** [angular/protractor#2404]
This will not work:

```js
browser.wait($('.error-presenter').isPresent, 3000);
```

But this will work:

```js
browser.wait(function () {
      return $('.error-presenter').isPresent();
}, 3000);
```

Shouldn't `isPresent` and all other checker functions be context independent or shouldn't `browser.wait` invoke it's function in correct context so the shorter version of snippet work?

**Comment by sjelin** [comment]
`isPresent` won't know what to wait for if it is out of context.
