### ISSUE TITLE
BrowserSync server Error while running testForAngular

### ISSUE THREAD

**Issue by mikehaas763** [angular/protractor#2408]
I've found quite a bit of information on the time out issues and synchronization issues people have had in the past but none of them have helped me solve my problem yet.

When I run protractor, I get this error: 
> Error while running testForAngular: asynchronous script timeout: result was not received in 5 seconds

I'm using BrowserSync for my dev server. It took me quite a while to figure out that it was the server that was causing my synchronization issues. If you're not familiar, BrowserSync uses websockets to notify your browser to reload. I believe this is what is causing protractor to time. However, all the documentation says $timeout and $http causes protractor to hang. Can native browser systems cause protractor to hang also?

**Comment by sjelin** [comment]
Yes.  This is a different sort of timeout.  However, it looks like your problem is that you're trying to access a non-angular page while ignoreSynchronization is off?

**Comment by mikehaas763** [comment]
No it is an angular page. I haven't looked into the issue in a while so that's all the info I have for now.

**Comment by sjelin** [comment]
Well, this particular timeout is about Protractor not being able to find Angular in 5 seconds, not about some command failing to finish in 5 seconds.

**Comment by juliemr** [comment]
It's likely that BrowserSync is causing a browser reload while Protractor is trying to run a script on your page. We haven't tested with it, so can't speak to specific issues. We'd welcome specific suggestions for fixes that would help, but I think for now your best bet is to turn synchronization off while loading the page.
