### ISSUE TITLE
Test e2e protractor Chrome error but Firefox not error

### ISSUE THREAD

**Issue by newnewnet** [angular/protractor#2409]
describe('information', function() {
  afterEach(function () {
    browser.ignoreSynchronization = false;
  });
  beforeEach(function() {
    browser.get('#/profile/information/view');
    browser.ignoreSynchronization = true;
  });

  it('should is title test', function() {
      expect(element(by.css('#newtext')).getText()).toEqual('ข้อมูลทั่วไป');
  });

});

Chrome :error   NoSuchElementError;
Firefox :success

**Comment by sallojusuresh** [comment]
Chrome is faster than Firefox, so you may have to introduce browser.wait() function.

**Comment by sjelin** [comment]
This looks like a race condition.  Probably the element just hasn't loaded yet in chrome
