### ISSUE TITLE
xpath not working in protractor

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2410]
xpath not working in protractor.I ahve cretaed xpath using firebug.When I identify the xpath using IDE,it is working fine.However when I use the same xpath in protractor,it is not working.My element does not have id or name.So here i can use only xpath option.

Please find the below image for reference.
Here I need to verify whether that particular element has "IRCTC Attractions" text.
Could you please help me?

HTML code:

//div style="width:100%;" class="g_hedtext">IRCTC Attractions /div

![untitled](https://cloud.githubusercontent.com/assets/13692001/9132406/ef9f210c-3d10-11e5-8cd2-17cc2ee32728.png)

**Comment by chrisguerra** [comment]
Probably this element does not present in DOM when you use, I like a lot xpath, if you change for ('//div[text()= "IRCTC Attractions"]') in my mind it's more clean and understandable. After this in you code you can insert a browser.wait

Code: 
var expectedConditions = protractor.ExpectedConditions;
browser.wait(expectedConditions.textToBePresentInElement(element, 'IRCTC Attractions'), 5000).then(function{YOUR CODE HERE});

"HTML code:
//div style="width:100%;" class="g_hedtext">IRCTC Attractions /div"
It's very sensitive code.

I hope to have help you.

**Comment by manojtdm** [comment]
@chrisguerra Hi Chris..Thank you..What is the right xpath I need to use in protractor?
Because I have tried with the xpath which is created using firbug.But it could not worked for me in my protractor code. html/body/div[1]/div/div[12]/div/div[1]/div this is the xpath I have tried in my application.
Thanks in advance.

**Comment by manojtdm** [comment]
I have used the xpath expression which is identified by firebug in firefox.
When I identify the element using the xpath expression via firebug or IDE,it is working fine.
But when we use same xpath in protractor it is throwing error as "Unexpected Identifier"
IDE element highlighted,it is attached for reference.

![untitled](https://cloud.githubusercontent.com/assets/13692001/9194877/19844118-403c-11e5-85d7-dbc7cc4bdd0d.jpg)

**Comment by chrisguerra** [comment]
Hi @manojtdm, I'm sorry for daley

There is not right xpath, but your xpath is very hardcode, I don't recomend you, try to change it if you want more flexible, I think the DOM does not load when you start by protractor, could you show us your protractor code?

**Comment by manojtdm** [comment]
Thanks for the reply @chrisguerra .

Please find below for the code:

var Someoption = element(by.xpath('//*[@id="option-item-1"]/div/div[2]/span'));

function Stopclock-Validation()
{
expect(Someoption.getText()).toEqual('vibrant');	
};

When I execute this, in the command window protractor saying "Unexpected Identifier".My application does not have ID,name.So I can go only with xpath. Even I tried with following xpaths too.For all the below things I am getting error as "Unexpected Identifier"

xpath:/html/body/div/div/div[3]/div/div[1]/div/div/div/div/div[2]/div/div/div/div[2]/div[1]/div/div[2]/span
xpath://span[contains(@class,'ng-binding option-description-text')]

Thanks for your time and help.

**Comment by chrisguerra** [comment]
Try to insert a browser.wait before expect.

Like this:
function Stopclock-Validation(){
browser.wait(protractor.ExpectedConditions.textToBePresent(Someoption, 'vibrant'), 5000).then(function(){
return expect(Someoption.getText()).toEqual('vibrant');
});
}

or browser.sleep(timeToWaitInMilliseconds)


I hope to have help you.

**Comment by manojtdm** [comment]
Hi @chrisguerra ..I have tried as you said.However still I am facing the same issue.

var disclaimermessage = element(by.xpath('//*[@id='disclaimer-message']'));

it('testscenario', function()

{
browser.sleep(5000);
//browser.wait(protractor.ExpectedConditions.textToBePresent(disclaimermessage);
expect(element(disclaimermessage).isPresent).toBeTruthy();
}

Following is the error I am getting:

Failures:

  1) Exception loading: C:\Users\XXXX\AppData\Roaming\npm\TC_model2.js Error
   Message:
     SyntaxError: C:\Users\XXXX\AppData\Roaming\npm\TC_model2.js:7
   var disclaimermessage = element(by.xpath('//*[@id='disclaimer-message']'));
                                                      ^^^^^^^^^^
Unexpected identifier
   Stacktrace:
     C:\Users\XXXX\AppData\Roaming\npm\TC_model2.js:7
   var disclaimermessage = element(by.xpath('//*[@id='disclaimer-message']'));
                                                      ^^^^^^^^^^
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:73:16)
    at require (module.js:384:17)
    at Object.exports.executeSpecs (C:\Users\XXXXX\AppData\Roaming\npm\node_mod
ules\protractor\node_modules\minijasminenode\lib\index.js:130:7)
    at C:\Users\XXXXX\AppData\Roaming\npm\node_modules\protractor\lib\framework
s\jasmine.js:86:14
    at Function.promise (C:\Users\XXXXX\AppData\Roaming\npm\node_modules\protra
ctor\node_modules\q\q.js:650:9)

Finished in 0 seconds

**Comment by chrisguerra** [comment]
I think your mistake is 'disclaimer-message', try "disclaimer-message"

like this: *var disclaimermessage = element(by.xpath('//*[@id
<https://github.com/id>="disclaimer-message"]'));

Christiano G. Guerra
Test Engineer
(+5581)994400019
(+5581)30402945

2015-08-11 11:26 GMT-03:00 manojtdm <notifications@github.com>:

**Comment by manojtdm** [comment]
@chrisguerra Thanks chris.

Relative xpath things are not working in protractor.Selenium we can create xpath using contains method.Using this contains xpath we can identify objects in the selenium webdriver.When we use the same xpath in protractor it is throwing error as
 "NoSuchElementError: No element found using locator: By.xpath(xpath=//img[contains(@src,"images/splash-you-text.png")]).

When I use the same xpath in IDE,it is working fine.Please let me know your comments.comments. Attached screenshot for reference.
![xpath prob](https://cloud.githubusercontent.com/assets/13692001/9244122/d859c246-41b5-11e5-9f3f-c4dde62c8449.png)

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
