### ISSUE TITLE
PhantomJS browser should surface errors so automated tests can reveal root cause

### ISSUE THREAD

**Issue by btmurrell** [angular/protractor#2411]
**Expected behavior:** when there is a resource error running a test under PhantomJS, that error should be surfaced to Protractor output in addition to the timeout message.

**Actual behavior:** If there is an error such as SSL Handshake, the Protractor test will simply wait until the specified timeout.  With the timeout error, we see no other information.

Even though PhatomJS is not fully supported, hopefully it is considered in "preview" mode and will become supported... clearly there is some doc and code to partially support it. To make it better:

When Protractor launches test in PhantomJS, it should do so with a PhantomJS script that can report back any errors encountered back to Protractor.. This will surface root causes in automated build systems such as Jenkins.  PhantomJS has a number of error handlers on the [`page`](http://phantomjs.org/api/webpage/) object namely 

* `onResourceError`
* `onResourceReceived`
* `onResourceTimeout`

that the Protractor-launched phantom script should implement so that they can be surfaced to script automation to identify root cause.  

A simple script that can be used in the mean time to manually troubleshoot is seen in [this Gist] (https://gist.github.com/btmurrell/d853ed8f9cda6aee86ee).

Also, configuring PhantomJS flags is tricky due to janky doc, so [this post](https://github.com/angular/protractor/issues/150#issuecomment-128109354) may be helpful to others in troubleshooting.

**Comment by sjelin** [comment]
Phantom JS is maintained by the community, not really the core team.  If you want to make these changes yourself, that'd be great!  Otherwise they probably won't happen :(

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this because we haven't seen any movement on this and Phantomjs has also undergone a major version upgrade which may/not have improved the situation.

PRs to improve phantom support are still always will be welcome 😄
