### ISSUE TITLE
protractor.promise to use q

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2412]
Would it make sense to replace `protractor.promise` with `q` in order to get access to the syntactic sugar `q` provides? For instance, the `spread()` method ([example use case](http://stackoverflow.com/questions/31887795/spreading-promises-in-protractor?noredirect=1#comment51701254_31887795)). 

What I mean is to have something like this in `onPrepare()`:

    protractor.promise = require("q");

so that every call to `protractor.promise` would be a call to `q`.

Or, should I just use the `q` directly? 

Thanks!

**Comment by NickTomlin** [comment]
Protractor uses webdriver's [Promise implementation](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/promise.js#L336) underneath the hood, so I think this might be an issue better raised on that project. Webdriver promises are tied pretty tightly to the control flow; I'm not sure how easy to have protractor substitute another implementation, but that might be worth a try.

If you are able to use es6 (or 2015 or whatever we are calling it these days) the example would destructure nicely to: 

```
protractor.promise.all([
    elm.getId(),
    browser.driver.switchTo().activeElement().getId()
]).then(function ([currentElementID, activeElementID]) {
    return jasmine.matchersUtil.equals(currentElementID, activeElementID);
})
```
Without the need for `spread`.

**Comment by alecxe** [comment]
@NickTomlin thanks for the insight!

You know what, `protractor.promise = require("q");` actually worked for me. Nothing broke so far and I'm able to use `spread()` with `protractor.promise`. Still not sure what can go wrong with this approach tough.

**Comment by NickTomlin** [comment]
@alecxe ah, very interesting! Awesome find. Perhaps it is as simple as adding a `thenable`. I've gone ahead and :+1: your answer in SO and I'll keep on eye peeled there to see if you run into anything strange (hopefully you don't :smile:).

If it's a change one can make at runtime, it seems like leaving things up to the user is a good solution. I'd be interested to see what the maintainers think.

**Comment by sjelin** [comment]
`protractor.promise` needs to be WebDriver promises in order to be consistent with the idea that the `protractor` object is an extension of the `webdriver` object.  That said, `protractor.promise = require("q");` should not introduce any problems in your code.  It's just not something we're going to do by default
