### ISSUE TITLE
Unable to run single scenario by passing line number and spec (or feature) file name

### ISSUE THREAD

**Issue by karthiktv006** [angular/protractor#2413]
In cucumber framework, a particular scenario can be executed by passing the line number and feature file name. like this
>cucumber features/smoke.feature:4

So, only the scenario at line number 4 gets executed. When cucumber framework is used with protractor it throws error saying no file pattern matched since the line number was not stripped out while looking for the existence of the spec file.
Error:
WARNING - pattern test/e2e/features/smoke.feature:4 did not match any files.

**Comment by hankduan** [comment]
See https://github.com/angular/protractor/pull/2445

**Comment by Galileo1** [comment]
@karthiktv006 @hankduan @darrinholst @marcenuc @stickel hey Guys, this seems to be a closed issue but I am still getting warning -  W/configParser - pattern e2e-tests\features\**\Feature Editor.feature:12 did not match any file. 

Can you please help?

**Comment by darrinholst** [comment]
@Galileo1 you can't combine glob features...the `**`...with line numbers. It has to be a real path. Try 

    protractor --specs "e2e-tests\features\Feature Editor.feature:12"
