### ISSUE TITLE
How to debug failed test steps in protractor?

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2414]
How to debug failed test steps in protractor?

Following is my test case.

it('Testcase-TC_BY_09 , Case 2: User Selects NO option', function() {
   //Execution Steps 
  Login();//Calling Login Function
//options Click	
	//book_typeValidation();
	book_type.click();
	expect(Nextbtn.isEnabled()).toBe(true);
	Nextbtn.click();
	
	//True_pages _Validation();
	True_pagesoption.click();
	expect(Nextbtn.isEnabled()).toBe(true);
	Nextbtn.click();
	
	expect(Nextbtn.isEnabled()).toBe(true);
	Nextbtn.click();

	expect(Nextbtn.isEnabled()).toBe(true);
	Nextbtn.click();
	Poles_Nooption.click();	   
    expect(Nextbtn.isEnabled()).toBe(true);	 	
	Nextbtn.click();
	  });

Lets say this test case have 10 test steps.When we execute this test case,if it fails in 5th step how to find tat failed step in protractor?

Right now how it is working is it will show the test case failed in console.But it is not showing which steps it has failed?

Please give your suggestion to find out failed step in protractor.

Thanks in advance.

**Comment by NickTomlin** [comment]
Hi there! Your question is better suited by asking on StackOverflow per the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I (and others) would be more than happy to help answer your question on StackOverflow if you post a link to it here and close this issue. Thanks!
