### ISSUE TITLE
Error needed for selection of non-existing files

### ISSUE THREAD

**Issue by marcoliceti** [angular/protractor#2416]
Hi, I'm testing a couple of AngularJS directives dealing with file uploads.

I've read the [example in the F.A.Q.](http://stackoverflow.com/questions/21305298/how-to-upload-file-in-angularjs-e2e-protractor-testing/21314337#21314337) and I've managed to make my tests work.

Only one problem: they work even with non-existing files!

It seems that, regardless of my file system's content, anything like `/path/to/foo.txt` will result in a dummy file named `foo.txt` passed to the `input[type="file"]`.

Is this behavior intended?

**Comment by sjelin** [comment]
Could you provide a minimal example of your problem?

**Comment by marcoliceti** [comment]
Ok, I've tried to reproduce the problem.

I wrote a test containing 2 specs, each one loading a file, but the second spec should fail because it loads a missing file. When I run this test, both specs succeed.

I think that the missing file gets somehow replaced with a dummy, empty file with the same name of the missing file.

I think this is a strange behavior that makes upload tests more error-prone.

Also, this behavior originally led me to think that _even_ existing files are ignored (and replaced with dummy files), but I still couldn't prove this (and maybe I'm wrong).

I'll try to write another test.

Meanwhile, [here is](https://github.com/marcoliceti/protractor-issue) the one I've described above.

**Comment by marcoliceti** [comment]
Update: I wrote another test (available inside the [same repository](https://github.com/marcoliceti/protractor-issue)).

I was wrong: existing files are properly passed to the tested page.

Still, non-existing files are replaced with dummy, empty files (i.e. `content === ''`).

**Comment by sjelin** [comment]
What if you type a bogus URL into a `<input[type="file"]>`?  Do you also get a blank file?

**Comment by marcoliceti** [comment]
I don't know if it's even possibile. I'm using a Mac and the dialog for file selection doesn't seem to have controls for file selection through a URL.

Maybe you mean a bogus URL _inside the test code_? I've tried: `sendKeys` doesn't accept URLs.

**Comment by sjelin** [comment]
Can't you just set the `value` property of the input or something via the javascript console?

**Comment by marcoliceti** [comment]
That can't be done. You can set `value` to an empty string, but if you try with an URL a `DOMException` will be thrown.

**Comment by marcoliceti** [comment]
**Note:** I've changed the title of this issue. The point is: even if a human user can't select a non-existing file, protractor tests _can_. The test developer may unintentionally supply a wrong path. This should be handled with an error / exception, not with an empty file.

**Comment by sjelin** [comment]
Yeah, I'm just trying to figure out if the `content=""` is something being done by the browser or by WebDriver or by Protractor.  Presumably it's done by the browser but I guess I'll have to investigate.

**Comment by juliemr** [comment]
This seems to be the intended behavior for the selenium-webdriver module. See the code at https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/remote/index.js#L363 - if a file cannot be found, it returns the filepath instead of throwing an error.

File uploading is not yet part of the webdriver official spec, so its behavior may still be in flux until it's nailed down. For now, I'd say this is intended behavior. Please open up an issue with [Selenium](https://github.com/SeleniumHQ/selenium/issues) if you think this needs changing. Thanks!
