### ISSUE TITLE
Protractor - getText() when there is still no value inside

### ISSUE THREAD

**Issue by moshicn** [angular/protractor#2418]
Hi
I have some list that gets filled with rows by ajax call, 
above it I have an itemCount span - to show how many rows we have. 
After the table is filled by rows (using ajax), the itemCount span value is updated. 
what I try to do is to copy this itemCount value, to add a new item to the list and then to test that the new itemCount value is bigger by 1 than the old one. 
The problem, I think, is that when I take the first value from the itemCount span, it is still empty. 
Of course I'll face the same problem after I'll update the list - I'll have to wait a bit till the list 
will get updated and then to copy the itemCount value again...
I tried to add browser.waitForAngular();, etc, but the value is still empty:
here is my code:

var Items_1_Count = element(by.id('itemsCount')).getText().then(function(val_1){
            console.log('************' + val_1); // *********
});
/----- opening here a modal window to add a new record... ------/
/------  after a few activities, I'm able to see the right value of itemCount : -------/

var items_2_Count = element(by.id('itemsCount')).getText().then(function(val_2){
       console.log('************' + val_2);   // ************** 7
});
/----------- now I'm saving my new records, and getting back to list while refreshing it. 
(all done by click 'save') : --------/

element(by.id('save')).click();

browser.sleep(5000); /------ doesn't solve it..... ------/

/------ now I try to take the new value: ---------/
var item_3_count = element(by.id('itemsCount')).getText().then(function(val_3){
     console.log('************' + val_3); //*********** 7
});
/-------- and I still get the old one... ---------/

Thanks for any help !!!!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
