### ISSUE TITLE
how change chrome driver to firefox driver in protractor

### ISSUE THREAD

**Issue by jabap4** [angular/protractor#2421]
I have problem with firefox . my test case passed with chrome and failed with firefox browser .so when i was updating my selenium standalone server using command " webdriver-manager update " chrome driver is updated but not firefox can you let me now the process that will update firefox driver

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
FireFox driver is packaged with the selenium standalone jar, so it does not need to be updated with a separate command.
