### ISSUE TITLE
How to set CWD for my spec files?

### ISSUE THREAD

**Issue by plato-cambrian** [angular/protractor#2422]
I'm refactoring my code and I moved `src/chat/tests` to `src/tests`. If I invoke `npm run acceptance` from `src/chat` then the tests run with `src/chat` as the CWD, which is fine.

However while debugging another issue I ran `protractor protractor.conf.js` from `src/tests/acceptance`. I found that some tests broke because they were assuming CWD was `src/chat` and it was actually the folder where I invoked protractor.

Can I define a CWD for my test files, overrriding the invocation method?

**Comment by NickTomlin** [comment]
I'm not sure what the use case is here without some example code, but It seems like this could be solved by just using globals like `__dirname` to ensure your paths are always correct.

**Comment by plato-cambrian** [comment]
Thanks @NickTomlin, that is my current workaround. I'm hoping that there's a config flag that lets me set the relative path for `require(../foo)` but I've never found any docs for the protractor configuration file so I don't know where to look. If this flag doesn't exist, go ahead and close the issue

**Comment by NickTomlin** [comment]
I apologize for the late reply, I was out of town at a conference. Unfortunately I don't have the ability to close this issue. `require` should always be relative to the module requiring the file doing the `require`. 

I'd suggest closing the issue and opening one on StackOverflow with some example code i'd be happy to help there :)

**Comment by juliemr** [comment]
Thanks @NickTomlin for the good answers. There's no way to change the current working directory, but using `__dirname` is a good solution.

For reference, docs on the configuration file are here: https://github.com/angular/protractor/blob/master/docs/referenceConf.js - which is linked from protractortest.org under 'reference'.
