### ISSUE TITLE
Pressing `c` to step debugger does not work

### ISSUE THREAD

**Issue by cesarvarela** [angular/protractor#2423]
![image](https://cloud.githubusercontent.com/assets/1172479/9233843/b439364e-410b-11e5-9f11-2cbdf2354d97.png)

I'm on Yosemite 10.10.4, node 0.12.2 and Protractor ^2.0.0

Any ideas?

**Comment by eolognt** [comment]
That have happened for me as well. I think it's just the output that isn't written, because the commands are being executed.

**Comment by cesarvarela** [comment]
That isn't my case, no action takes place after entering  'c' or whatever.

Is there any way I can help with this?

**Comment by juliemr** [comment]
Does it happen all the time, no matter where the debugger is, or only in one situation? If the latter, can you provide more context?

**Comment by juliemr** [comment]
Closing as stale.
