### ISSUE TITLE
Support Sauce Labs competitors (BrowserStack, CBT, TestingBot, more?)

### ISSUE THREAD

**Issue by kylecordes** [angular/protractor#2425]
Currently, Protractor has support for Sauce Labs in the box. Sauce is a good service, very helpful for testing on a wider variety of browsers than can conveniently be run locally. As I understand, many Protractor users are also Sauce customers. However, Sauce Labs is *not* the only vendor offering posted selenium browsers, and their offerings can involve a significant amount of money if, for example, running automated tests on many browsers daily.

Therefore, to support healthy competition in this market, ideally Protractor would include support for Sauce's competitors. They include at least the following:

https://www.browserstack.com/

http://crossbrowsertesting.com/

http://testingbot.com/

I have investigated this integration briefly. There is more to it than just setting the right Selenium URL. The Sauce support already in Protractor shows an example of this, using a bit of Sauce-specific API to tell Sauce about test success for example. So this feature request is to implement something comparable for the other remote-browser-testing vendors.

There is a related issue already for BrowserStack, but it addresses only the selenium part and not the other aspects.

https://github.com/angular/protractor/issues/1013

**Comment by juliemr** [comment]
BrowserStack support is now added, and it's possible to use others via `seleniumAddress`. I'd be happy to take a look at another specific PR, but for the sake of cleanup I'm going to close this general one.

**Comment by Dgiordano33** [comment]
CrossBrowserTesting support has also been added since this original PR. You can see an example [here](https://github.com/crossbrowsertesting/selenium-protractor).
