### ISSUE TITLE
Webdriver-manager should fix corrupted jar files

### ISSUE THREAD

**Issue by jeffbcross** [angular/protractor#2428]
The Jenkins job for angularjs.org started failing after webdriver-manager update apparently caused seleniumServer.jar to be corrupted. See an [example failure](https://ci.angularjs.org/job/angularjs.org/9364/console), and see the [job](https://ci.angularjs.org/job/angularjs.org/9349/) where it started failing. 

I ran `webdriver-manager start` manually before fixing the issue, and saw a helpful error message about the jar being corrupted:

```
seleniumProcess.pid: 53981
Error: Invalid or corrupt jarfile 
workspace/angularjs.org/node_modules/protractor/selenium/selenium-server-standalone-2.44.0.jar
Selenium Standalone has exited with code 1
```

It would be nice if protractor/webdriver-manager could remove the corrupted jar and re-run update in this case.

**Comment by hankduan** [comment]
dup of https://github.com/angular/protractor/issues/1857
