### ISSUE TITLE
Reg: Protractor Start time and End time for the test case/cases

### ISSUE THREAD

**Issue by csharsha** [angular/protractor#2430]
Hi All,
Protractor is a great browser automation tool with some limitations existing still. Can I know how to get start time and end time for the test case or if I execute the test cases in batch. If at all I need to include some javascript where and how to do it?

**Comment by hankduan** [comment]
You can add a simple jasmine reporter (assuming you're using jasmine) that tracks the time.

This is how you write a reporter: http://jasmine.github.io/2.1/custom_reporter.html
This is how you include it: `jasmine.getEnv().addReporter(junitReporter);`

For further questions, please use stackoverflow
