### ISSUE TITLE
Find elements inside map function

### ISSUE THREAD

**Issue by nervgh** [angular/protractor#2432]
Then I execute this code
```js
element
    .all(by.repeater('field in app.category.fields'))
    .map(function(element) {
        return element.element(by.css('[ng-switch-when]'));
        // element.$('[ng-switch-when]');
    });
```
protractor not goes after it and browser waits....

How I can fix it?

**Comment by NickTomlin** [comment]
This looks like a duplicate of #2427 please consider closing this issue and commenting there.

**Comment by nervgh** [comment]
@NickTomlin , thanks for comment.
