### ISSUE TITLE
by.exactRepeater with one-time data binding

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2434]
Can we make `by.exactRepeater()` match repeaters with one time data-binding:

```
ng-repeat="gridColumn in ::panelGrid.columnDefs"
```

In this case would be good to have `element.all(by.repeater("gridColumn in panelGrid.columnDefs"))` locate the repeater.

Also, `by.exactBinding()` may have a similar issue (haven't checked).

Thanks.

**Comment by hankduan** [comment]
I don't think we should get into the business of syntax parsing for Angular, as it'll be a maintainability nightmare. Is there a reason why this is useful? (i.e. instead of `element.all(by.repeater("gridColumn in ::panelGrid.columnDefs")`)

**Comment by juliemr** [comment]
Agree with @hankduan here - closing for now.
