### ISSUE TITLE
loggingPrefs not respected - always INFO logging

### ISSUE THREAD

**Issue by joeltine** [angular/protractor#2436]
I'm starting protractor with the [following config](https://github.com/google/closure-library/pull/528/files#diff-e6e3c226ff257580ddb9450b08a7a1ab). Specifically, these capabilities:

````
  capabilities: {
    'browserName': 'firefox',

    'loggingPrefs': {
      'driver': 'WARNING',
      'server': 'WARNING',
      'browser': 'WARNING'
    }
  },
```

Yet, when I run my tests, I'm still getting a ton of INFO logs ([log dump](https://s3.amazonaws.com/archive.travis-ci.org/jobs/76008995/log.txt)). Specifically, the most verbose logs are from an [executeScript](http://angular.github.io/protractor/#/api?view=webdriver.WebDriver.prototype.executeScript) call.

When I start using `./node_modules/.bin/protractor --troubleshoot`, I see the following in the output:

```
DEBUG - WebDriver session successfully started with capabilities { caps_: 
   { applicationCacheEnabled: true,
     rotatable: false,
     handlesAlerts: true,
     databaseEnabled: true,
     version: '40.0',
     platform: 'LINUX',
     nativeEvents: false,
     acceptSslCerts: true,
     'webdriver.remote.sessionid': '49993575-e0ba-4e87-b93b-e5ae8371d3b3',
     webStorageEnabled: true,
     locationContextEnabled: true,
     browserName: 'firefox',
     takesScreenshot: true,
     javascriptEnabled: true,
     cssSelectorsEnabled: true } }
```

Note, there's no `loggingPrefs` object.

Someone opened a similar issue in https://github.com/angular/protractor/issues/2315, and from what I can tell, they were also using some variant of `executeScript`.

This is currently making it very difficult to debug Travis failures as my logs are exceeding 4MB (the limit).

**Comment by jeffbcross** [comment]
@sjelin would you mind chiming in?

**Comment by sjelin** [comment]
If on [this line](https://github.com/angular/protractor/blob/master/lib/driverProviders/driverProvider.js#L35) you add `console.log(this.config_.capabilities);`, what do you see?

**Comment by sjelin** [comment]
Got curious, looks like an external bug.  Filed one myself: https://github.com/SeleniumHQ/selenium/issues/983

Will keep working on a work-around.

**Comment by sjelin** [comment]
Tried to solve the problem with a firefox profile but it didn't work.  I might be misusing the feature though - I'm not sure.

**Comment by joeltine** [comment]
Per https://github.com/SeleniumHQ/selenium/issues/983 it sounds like the issue is in protractor. Is that correct? If so, any ETA on a fix?

**Comment by sjelin** [comment]
If you're using `webdriver-manager` to spawn your selenium server than it is indeed a Protractor issue.  For a work-around, I'd suggest adding
```js
args.push(-Djava.util.logging.config.file="logging.properties");
```
right above [this line](https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L283), where `logging.properties` is a file that contains:
```
.level = WARNING
```

**Comment by theking-laptop** [comment]
@sjelin I think you should provide a convenient way to pass 'logging.properties' file, e.g. via configuration file instead of hard-coding in 'webdriver-manager' code.

**Comment by sjelin** [comment]
Yeah, I mean, currently webdriver-manager doesn't allow for config files.  And the config file you pass to protractor can't communicate to webdriver-manager.  So it's unclear exactly how this feature should look.  But there should definitely be something.

**Comment by JessicaSachs** [comment]
Just to make sure I understand this correctly... After this is fixed, will the `[launcher]` logging go away?

<img width="514" alt="screen shot 2016-04-11 at 11 14 22 pm" src="https://cloud.githubusercontent.com/assets/2801156/14448917/5d8eb16c-003b-11e6-935b-fc925a0aea25.png">

**Comment by henrahmagix** [comment]
> right above this line, where logging.properties is a file that contains:

@sjelin Did you mean [this line](https://github.com/angular/protractor/blob/c989a7eeed5a0a55d2fbd37dc7278a7967889852/bin/webdriver-manager#L283)? When I followed your link, I got [this line](https://github.com/angular/protractor/blob/bf603f50dfd48b63bfdef50508c1e8f95b2553da/bin/webdriver-manager#L283) (from the `master` branch at time of writing).

If so, can you edit your comment please? For more info, see `y` here: https://help.github.com/articles/using-keyboard-shortcuts/#source-code-browsing

**Comment by henrahmagix** [comment]
@sjelin Your link in https://github.com/angular/protractor/issues/2436#issuecomment-135688608 is also broken for the same reason: it's referencing `master`, not a commit hash of the time

**Comment by juliemr** [comment]
Moved to https://github.com/angular/webdriver-manager/issues/61

**Comment by andriyze** [comment]
is this fixed? I can't change logging level for my protractor tests. It is always INFO. I use jasmine, chrome as a browser and webdriver-manager.

**Comment by trevor92** [comment]
Could someone provide an example of how to implement this?

**Comment by darrinholst** [comment]
This worked for me...

`webdriver-manager start --logging /absolute/path/to/logging.properties`

logging.properties looked like...

``` properties
handlers=java.util.logging.ConsoleHandler
org.level=WARNING
```

I couldn't figure out what class names all the logging was coming from so I just applied it to all `org.*` classes.

**Comment by anthonydinh** [comment]
@darrinholst 

I tried your solution with org.level=ALL and got the below output when restarting webdriver-manager, so I'm assuming it was correctly started with the configured log level?

when I run my test suite (protractor protractor.conf.modular.js --suite=e2e), the console output and spec/results.xml log output still look the same as before, so doesn't look like the log level changed.

how do I know if the configured log level really took affect, where do I need to look/check?

thanks in advance!


sudo webdriver-manager start --logging ~/projects/web_static/automation.log-level 
[09:35:29] I/start - java -Djava.util.logging.config.file=/Users/user/projects/web_static/automation.log-level -Dwebdriver.gecko.driver=/Users/user/.nvm/versions/node/v6.9.4/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.20.1 -Dwebdriver.chrome.driver=/Users/user/.nvm/versions/node/v6.9.4/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.38 -jar /Users/user/.nvm/versions/node/v6.9.4/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.11.0.jar -port 4444
[09:35:29] I/start - seleniumProcess.pid: 24416
09:35:30.300 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.11.0', revision: 'e59cfb3'
09:35:30.303 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
2018-05-01 09:35:30.471:INFO::main: Logging initialized @521ms to org.seleniumhq.jetty9.util.log.StdErrLog
09:35:30.664 INFO [SeleniumServer.boot] - Welcome to Selenium for Workgroups....
09:35:30.665 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 444

**Comment by subramani-r-0595** [comment]
Any update on the fix?
