### ISSUE TITLE
directConnect - any known performance gain/loss?

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2438]
In Chrome and Firefox I can use `directConnect: true` and it'll connect directly to the Chrome/Firefox driver (so I don't need to call `webdriver-manager start`)

Is there any performance benefit (or loss) when using `directConnect`? Or is it just for convenience?

Raising it as an issue as the documentation left me confused as to why I'd want to use it (or not).

**Comment by NickTomlin** [comment]
The benefit (as I understand it) is not needing to spin up a selenium server to run your tests. That means anywhere from a 10 to 40 second savings for me depending on the machine. I think it shines for quick local testing. Feel free to open a PR with clarification in the documentation if you want.

**Comment by PaddyMann** [comment]
Thanks @NickTomlin - appreciate the input.

Locally, `webdriver-manager start` seems to get Selenium server up and running in less than a couple of seconds, so less of an impact for me :)

I'm wondering if there's any speed benefit while running the tests, but I'm guessing it's so-small-it's-insignificant if there's any at all.

**Comment by Callmenorm** [comment]
I think related to the performance gains of running tests is reliability. Do we gain or lose reliability by using directConnect? If you save seconds on successful runs but lose minutes on failures, then failures have to be rare for the success savings to be worth it. 

I'd gladly use the slightly slower method if it meant a huge boost in reliability.

**Comment by hankduan** [comment]
It's all described here http://www.protractortest.org/#/server-setup. 

Specifically the last line says: "The advantage of directly connecting to browser drivers is that your test scripts may start up and run faster."

This means if the standalone server starts very quickly for you, and you don't mind running another command before protractor, then there is no difference. 
On the other hand, if you need to run Protractor tests multiple times, it might be better to have a standalone server running in the background already so it doesn't need to load with every test run. Against the difference is trivial. Hope that helps.

**Comment by PaddyMann** [comment]
Thanks @hankduan 

Would be nice to include a note in the example config file which is where I'd looked for info.
