### ISSUE TITLE
multiCapabilities throwing error in protractor

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2439]
need to run my tests in chrome,FF and IE. When I use following comments my execution working fine.

capabilities: { 'browserName': 'chrome' },

However when I use following comment protractor throwing error.

multiCapabilities: [{ 'browserName': 'chrome' }, { 'browserName': 'firefox' }],

ERROR - failed loading configuration file TC3conf.js

Could you please what is the problem here?

**Comment by NickTomlin** [comment]
It looks like you have a [StackOverflow](http://stackoverflow.com/questions/32096575/multicapabilities-function-throwing-error-in-protractor) question that covers this. Could you consider closing this issue?
