### ISSUE TITLE
jasmine2, element().getText() does not work well (not deterministic)

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2440]
Hello,

my protractor test, that 

* uses jasmine2
* uses protractor v2.1.0
* uses chrome driver

returns always a not consistent result. 

Specifically, I run a check on the text of span elements, `expect(element(...).getText()).toBe('...')` but sometimes the result of getText() is empty string.

The test is made on 6 strings, sometimes 4 are empty string, some other times only 3 of them are empty strings.
But none of them is empty.

**Comment by NickTomlin** [comment]
Do you have an isolated test case where this is happening? I haven't been able to reproduce the inconsistency locally. 

Could it possibly be the page itself and not protractor? Does firefox produce the same results?

**Comment by hankduan** [comment]
My guess is that you're running into some kind of race condition. Please open another issue when you have an isolated test case.

**Comment by bitliner** [comment]
What you mean by *race condition* ?

Do you mean that Protractor/Selenium  struggles to handle asynchronous code well?

**Comment by hankduan** [comment]
No, I meant your app might be changing the text (i.e. populating it) via a method not known by Angular (i.e. via setTimeout or something). 

However, this is a totally wild guess. Please open a new issue with an isolated case like @NickTomlin mentioned.

**Comment by bitliner** [comment]
It is my $http wrapper that uses websocket I think. Maybe the timeout (2seconds) was not enough.
