### ISSUE TITLE
Protractor not working with Firefox 40.0.2

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2441]
Protractor not working with Firefox 40.0.2.

Earlier it was working fine with Firefox 33.0. Recently I have updated into FF 40.0 and I am facing this issue.Any work around for this issue?

Following is the error:

<i>UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. F
irefox console output:
2450}},"app-global":{"{972ce4c6-7e08-4474-a285-3208198ce6fd}":{"d":"C:\\Program
Files (x86)\\Mozilla Firefox\\browser\\extensions\\{972ce4c6-7e08-4474-a285-3208
198ce6fd}","e":true,"v":"40.0.2","st":1439822857275,"mt":1439428033000}}}
1439993746971   addons.xpi      DEBUG   getModTime: Recursive scan of fxdriver@g
ooglecode.com
imentProvider
JavaScript error: file:///C:/Users/u27781/AppData/Local/Temp/anonymous8237795357
242995769webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-
component.js, line 11487: TypeError: this.server_ is undefined
JavaScript error: chrome://fxdriver/content/server.js, line 38: NS_ERROR_XPC_CI_
RETURNED_FAILURE: Component returned failure code: 0x80570015 (NS_ERROR_XPC_CI_R
ETURNED_FAILURE) [nsIJSCID.createInstance]</i>

**Comment by eolognt** [comment]
Seems to be a Selenium issue: https://github.com/SeleniumHQ/selenium/issues/944

**Comment by manojtdm** [comment]
So what is the solution for this?

Do i need to update selenium server stand alone?
Which version of selenium I need use? Please provide the download link.

**Comment by manojtdm** [comment]
By using selenium webdriver 2.47.1 we can use firefox 40.0.2
