### ISSUE TITLE
Advice on Debugging

### ISSUE THREAD

**Issue by aedenj** [angular/protractor#2442]
I'm getting the following error,

    Uncaught exception: Timed out waiting for Protractor to synchronize with the page after 11 seconds. 
    Please see https://github.com/angular/protractor/blob/master/docs/faq.md

I've looked for any polling done by `$http` or `$timeout`. I would love any tips any of you have for identifying what is causing this. What is odd is that if I press keys or click around the test will continue on to the next step. Thanks for your time.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
