### ISSUE TITLE
UnknownError: Unable to find executable for: taskkill

### ISSUE THREAD

**Issue by Utkarsh6793** [angular/protractor#2443]
//config.js 
exports.config = {
  
  seleniumServerJar: 'D:/utkmishra/Protractor/selenium-server-standalone-2.47.1.jar',
  specs: ['D:/utkmishra/Protractor/spec.js'],
seleniumArgs: ['-browserTimeout=60'],
capabilities: {
'browserName': 'firefox'
},

baseUrl: 'http://localhost:8000',
allScriptsTimeout:30000
}

// spec.js
describe('Protractor Demo App', function() {
  it('should have a title', function() {
    browser.get('http://juliemr.github.io/protractor-demo/');

    expect(browser.getTitle()).toEqual('Super Calculator');
    element(by.model('first')).sendKeys(1);
    element(by.model('second')).sendKeys(2);

    element(by.id('gobutton')).click();

    expect(element(by.binding('latest')).getText()).
        toEqual('3'); // This is wrong!

//browser.close();
 });
});

This is a simple test case with which I was trying to test the protractor. But after performing all steps (mentioned in the spec file) on the browser, it throws an error

D:\Users\850014931\AppData\Roaming\npm>protractor D:/utkmishra/Protractor/test_case1/config.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.101.0.197:54806/wd/hub
.

Finished in 4.27 seconds
1 test, 2 assertions, 0 failures

D:\Users\850014931\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\at
oms\error.js:113
  var template = new Error(this.message);
                 ^
UnknownError: Unable to find executable for: taskkill
    at new bot.Error (D:\Users\850014931\AppData\Roaming\npm\node_modules\protractor\node_modules\sel
enium-webdriver\lib\atoms\error.js:113:18)
    at Object.bot.response.checkResponse (D:\Users\850014931\AppData\Roaming\npm\node_modules\protrac
tor\node_modules\selenium-webdriver\lib\atoms\response.js:106:9)
    at D:\Users\850014931\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver
\lib\webdriver\webdriver.js:377:20
    at [object Object].promise.ControlFlow.runInFrame_ (D:\Users\850014931\AppData\Roaming\npm\node_m
odules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)
    at [object Object].promise.Callback_.goog.defineClass.notify (D:\Users\850014931\AppData\Roaming\
npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:2464:25)
    at [object Object].promise.Promise.notify_ (D:\Users\850014931\AppData\Roaming\npm\node_modules\p
rotractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:563:12)
    at Array.forEach (native)
    at Object.goog.array.forEach (D:\Users\850014931\AppData\Roaming\npm\node_modules\protractor\node
_modules\selenium-webdriver\lib\goog\array\array.js:203:43)
    at [object Object].promise.Promise.notifyAll_ (D:\Users\850014931\AppData\Roaming\npm\node_module
s\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:552:16)
    at goog.async.run.processWorkQueue (D:\Users\850014931\AppData\Roaming\npm\node_modules\protracto
r\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
[launcher] Process exited with error code 1

Node Version v0.12.7
NPM version 2.11.3
Protractor Version 2.1.0
System: Windows 7 32 bit

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by hankduan** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
