### ISSUE TITLE
Feature request: List out specs and instances at start of run

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2444]
When I run a set of Protractor tests, it would be great to see a list of which files will run, and which instances they will run on.

e.g. 

```
protractor myconf.conf.js
Using the selenium server at http://127.0.0.1:4444/wd/hub
[launcher] 11 specs found
app/module1/spec1.spec.js
app/module1/spec2.spec.js
app/module1/spec3.spec.js
app/module1/spec4.spec.js
app/module2/spec1.spec.js
app/module2/spec2.spec.js
app/module3/spec1.spec.js
app/module3/spec2.spec.js
app/module3/spec3.spec.js
app/module4/spec1.spec.js
app/module5/spec1.spec.js

[launcher] Preparing 6 instances of WebDriver
Instance 1: app/module1/spec1.spec.js
Instance 2: app/module1/spec2.spec.js
Instance 3: app/module1/spec3.spec.js
Instance 4: app/module1/spec4.spec.js
Instance 5: app/module2/spec1.spec.js
Instance 6: app/module2/spec2.spec.js

...

[launcher] 6 instance(s) of WebDriver still running
Instance 1: app/module3/spec1.spec.js
Instance 2: app/module1/spec2.spec.js
Instance 3: app/module1/spec3.spec.js
Instance 4: app/module1/spec4.spec.js
Instance 5: app/module2/spec1.spec.js
Instance 6: app/module2/spec2.spec.js
```

Optionally, you could allow users to configure it with a `verboseLauncherOutput` flag or similar.

How this would help:

1. The initial output (a list of files to run specs against) would help when checking that the specs you're expecting to run are all queued up. This is particularly useful in large projects with a lot of specs and different modules potentially targeted by different config files (it's easy to assume that a spec is included and not realize it isn't being run).

2. We would be able to quickly and easily identify any that fail to run (e.g.) because Protractor hangs. This would be an enormous help until #2419 is fixed.

Feel free to point me to the code where I can try to make these tweaks myself :)

**Comment by hankduan** [comment]
Unfortunately this change isn't possible. Protractor depends on Jasmine/mocha/etc to run the tests, so this is something you would need to implement with the runner directly
