### ISSUE TITLE
How to view the test by test result in the console

### ISSUE THREAD

**Issue by ahmed-isam** [angular/protractor#2446]
Hi,

We've recently updated protractor, and it doesn't seem to log the red/green test case results for the scenarios

Thanks

**Comment by NickTomlin** [comment]
Can you give a sample of the output you are seeing versus what you expect? I haven't noticed a change in the protractor output running with a recent version.

**Comment by bvasilchik** [comment]
Are you using any specific reporter? for example I'm using https://github.com/bcaudan/jasmine-spec-reporter and i'm on protractor 2.1 and that specific reporter works fine with the latest version of protractor. I know protractor updated jasmine dependency to 2.3.1

**Comment by hankduan** [comment]
Please read the [contributing guidelines](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions); these types of questions are ill-suited for GitHub. Thanks!
