### ISSUE TITLE
How to run safari 5.1.7 browser(windows machine) in protractor using selenium 2.47.1 jar?

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2449]
How to run safari 5.1.7 browser(windows machine) in protractor using selenium 2.47.1 jar?

I need to run safari 5.1.7 browser(windows machine) in protractor using selenium 2.47.1 jar.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
