### ISSUE TITLE
Internet Explorer11 working too slow with protractor

### ISSUE THREAD

**Issue by manojtdm** [angular/protractor#2451]
I need to run my test cases in internet explorer 11 using protractor.When I execute test case,s it is consume much time when compare to Firefox and Chrome. Even to enter the "Hello" text in text box it is taking 20 secs approximately.

Is there anyway to increase the execution speed in internet explorer 11?

Following are my protractor details: 
Selenium standalone server-2.47.1 
Node JS-0.12.7 
IE driver version-IEDriverServer_x64_2.45.0

Please provide the details and links if we have something to increase the speed. 
Thanks much.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by hankduan** [comment]
@manojtdm I haven't tested this in IE11, but could it be related to https://github.com/angular/protractor/pull/2406? Can you try using ie32 and see if it helps?

**Comment by juliemr** [comment]
Closing as stale, and possibly addressed by #2406.
