### ISSUE TITLE
Protractor Tests are not executed with browser IE11

### ISSUE THREAD

**Issue by pavangkumar** [angular/protractor#2452]
no such window Error, Unable to get Browser

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by hankduan** [comment]
Thanks @NickTomlin. Yes please use Stackoverflow for this.
