### ISSUE TITLE
by.exactRepeater() not working on 2.2.0

### ISSUE THREAD

**Issue by williamboman** [angular/protractor#2453]
`by.exactRepeater` is not finding any elements on `protractor@2.2.0`. It works perfectly fine on `protractor@2.1.0`.

**Comment by williamboman** [comment]
This is due to #2335, also mentioned [here](https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes) :see_no_evil:. I had included `=` in my repeat descriptors. Editing those fixes this. I'll leave this open for future travelers.

**Comment by NickTomlin** [comment]
@williamboman could you actually close the issue? That will make it easier for the maintainers to sift through issues; the solution will still be here for anyone searching for the problem.

**Comment by williamboman** [comment]
@NickTomlin I think it's worth having this issue open for a few more days to avoid any duplicates. Feel free to add any labels or close this issue (I'll otherwise close it soon).

This change should've kept backwards-compatibility IMO (due to the versioning), or at least included a deprecation notice for previously semantically valid, albeit syntactically invalid, descriptors.

<sup>assuming protractor follows semver</sup>

**Comment by hankduan** [comment]
@williamboman Sorry about the breaking change. We did not increase the major version since this was considered a fix to a previously bug. But I agree, we should be more careful of these types of pushes in the future. 

Let's keep this open for a week, and close it then (it'll still be searchable)

**Comment by williamboman** [comment]
One GitHub-week later.
