### ISSUE TITLE
Conf file for Protractor POM

### ISSUE THREAD

**Issue by iPraetorian** [angular/protractor#2458]
I have created a script trying to use POM based on the example shown and I'm a little confused by the config settings. I have 2 files, one is the POM file, the other is actual spec that should call the POM file. I'm not following how to get the test to run using protractor conf.js --suite OBBLoin so I'm guessing my conf file isn't set up correctly. I get the error: Error: Unknown test suite: OBBLogin. Below is the information.
PageObjectSpec:

var OBBLOGIN = function() {
    var emailInput = element(by.id('signInForm_email'));
    var pwInput = element(by.id('signInForm_password'));

    this.get = function() {
        browser.get('https://staging.openbookben.com');
    };

    this.setName = function(email) {
        emailInput.sendKeys(email);
    };

    this.setName = function(password) {
        pwInput.sendKeys(password);
    };
}

OBBLoginSpec:
'use strict';

describe('OBB Login', function() {
    it('should let user log in', function () {
        var login = new OBBLOGIN();
        login.get();

        login.setName('drew@openbookben.com');
        login.setName('password');
    })
});

CONF file:
exports.config = {
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

    capabilities: {
        'browserName': 'chrome'
    },

    suites: {
        login: '**/OBBLoginSpec.js'

    }

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
