### ISSUE TITLE
Using ES2015 in protractor.conf.js

### ISSUE THREAD

**Issue by scottohara** [angular/protractor#2463]
##### Proposal:
I would like to use ES2015 syntax in my `protractor.conf.js` file.

##### Example:

```
// ES5
module.exports.config = {
  ...
  onPrepare: function() {    // <- old school function expression
    var foo = 'a',           // <- old school vars
        bar = foo + 'b';     // <- old school string concatenation

    // do some work
  }
  ...
}

// ES2015
module.exports.config = {
  ...
  onPrepare: () => {          // <- arrow function
    const foo = 'a';          // <- consts
    let bar = `${foo}b`;      // <- let & template strings

    // do some work
  }
  ...
}
```

##### Prior art:
Gulp allows ES2015 to be used in its `gulpfile.js` by using [Liftoff](https://github.com/tkellen/js-liftoff) + [interpret](https://github.com/tkellen/js-interpret).

By renaming `gulpfile.js` to `gulpfile.babel.js`; the `interpret` package will automatically process the file using [babel](https://babeljs.io) on load (note: requires a locally installed `babel` or `babel-core`).

##### Other notes:
I'm currently using ES2015 in my protractor specs; enabled by a `require('babel-core/register')` at the top of my `protractor.conf.js` file  ([source](https://github.com/angular/protractor/issues/2049#issuecomment-100467279)).

Unfortunately, even with this required, I can't use ES2015 for the protractor config itself.

The `protractor.conf.js` file is the *last* remaining file in my project that requires ES5 syntax.

**Comment by stalniy** [comment]
just use Nodejs4+. There are a lot of ES6 features there

**Comment by scottohara** [comment]
Confirming that Nodejs4+ works (for my use case at least).

I still need the `require('babel-core/register')` in my `protractor.conf.js`, as some of my tests use the ES2015 Reflect API (which is polyfilled by babel).

But I'm happy to say that my `protractor.conf.js` itself uses ES2015 without any problems.

Closing.

**Comment by NickTomlin** [comment]
@scottohara awesome. Thanks for updating and closing :)

**Comment by dfguo** [comment]
@scottohara did you manage to get right line number in stacktrace when an error happens?
