### ISSUE TITLE
No API for getting HTTP status code

### ISSUE THREAD

**Issue by hassankaz** [angular/protractor#2466]
I need an API to return http status code for a site. Is it possible? Thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by NickTomlin** [comment]
A quick google search revealed that this is probably [not possible](http://stackoverflow.com/a/14547168)

**Comment by Droogans** [comment]
@hassankaz Protractor tests are just node. You can use https://www.npmjs.com/package/restling directly in your tests (or build some helpers) to assert that your API is giving you back good status codes during your Selenium tests (though I wouldn't recommend it -- you'd be mixing API testing with functional, browser-based behavior testing).

**Comment by juliemr** [comment]
Closing this as answered well, thanks @NickTomlin and @Droogans.
