### ISSUE TITLE
css properties validation/testing using protractor 

### ISSUE THREAD

**Issue by jabap4** [angular/protractor#2468]
i am developed one angularjs app and  i want test my css properties in protractor is there any way  to test the css properties please share to me or any other way to test css properties using protractor ?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
Agreed, please ask this in SO. In general, you probably want to use http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.getCssValue
