### ISSUE TITLE
browser.getCurrentUrl() returns 'data:text/html,chromewebdata' instead of actual url

### ISSUE THREAD

**Issue by vikasalva** [angular/protractor#2472]

**Comment by NickTomlin** [comment]
Interesting. I haven't seen this issue with `getCurrentUrl` before.

`data:text/html,chromewebdata` is the default url for a new session opened by protractor. This seems like a race condition or just a failed page load. That said, It's difficult to troubleshoot without any information. Could you provide some more details about the issue?

- Your operating system
- Your version of node
- Your version of Protractor
- Your version of angular
- Any relevant configuration
- An example spec

An isolated reproduction that would be of great help as well. It seems like there are some environmental issues at work here.

**Comment by sewellj3** [comment]
I have seen this too. In my case it was coming up on a web page that had windows authentication upon opening the page. It got blocked on my MAC somehow, and I got the above results

**Comment by vikasalva** [comment]
Thanks Nick. The actual problem was page loading.

**Comment by NickTomlin** [comment]
@vikasalva glad that you sorted the issue :) Would you mind closing this one? (I'm not a project maintainer, just someone interested in Protractor).

**Comment by vikasalva** [comment]
Thank You

**Comment by kenorb** [comment]
Related: [ChromeDriver bug #1272](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1272)

**Comment by adithnaveen** [comment]
I've the same issue with Protractor: Version 5.2.0, and Version 62.0.3202.94, even the simple application, does take over 70 Seconds to load...
