### ISSUE TITLE
What is the best way to manage dropped file from explorer ?

### ISSUE THREAD

**Issue by mathilde-pellerin** [angular/protractor#2474]
Hi all,

It's not a protractor issue, but a question for protractor and e2e experts.
I try to test an angular application on which adding data can only be done by files drag and drop from OS explorer. I understand that files drag and drop can't be directly test by webdriver because explorer is not a part of browser.

Anyway, I find a way to adding some data to my app to test it. I thought of different approaches. 
The first one was to directly call my backend REST API to add the data. I tried this approache by following this blog post (http://squirrel.pl/blog/2014/01/15/direct-server-http-calls-in-protractor/) and I can send data to the server. But many checks and transformation on the data are done by my front-end app on drop, before to send data to server, and with this approache I can't use them. These checks and transformations are already tests in Unit Test, but it is a little bit frustrating to have to rewrite these in my test to manage my data files...

**So, I thought that it would be great if I can use my validation files directly by calling controller function which handle dropped files. With this approache, I skip only the drag and drop part but I test with e2e all process which are made after drop.** It would be really nice, but I can't figure out how to do this... I don't even know if it's possible to do something like that...

Any advice would be great :)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by mathilde-pellerin** [comment]
Yeah I thought about that after posting here, sorry.
This question is on stackoverflow now: http://stackoverflow.com/questions/32395000/protractor-what-is-the-best-way-to-manage-dropped-file-from-explorer
