### ISSUE TITLE
jasmine2 framework configuration issue

### ISSUE THREAD

**Issue by akoval** [angular/protractor#2475]
I upgraded jasmine library to 2.3 version. Updated all tests according jasmine 2.3 documentation.

When I use following config

```
exports.config = {
    framework: 'jasmine2',
```

I have issues: 
 Message:
    Failed: Object #<Object> has no method 'addMatchers'
  Stack:
    TypeError: Object #<Object> has no method 'addMatchers'

When I use config without framework property it works well all tests are fired.

**Comment by akoval** [comment]
Replaced this.addMatcher inot jasmine.addMatcher.It works with jasmine2 framework settings.

should I write everywhere jasmine.addMatchers?

**Comment by DorianGrey** [comment]
If you're trying to use jasmine2, your code should be adopted to the corresponding API-changes. A full upgrade guide can be found [here](http://jasmine.github.io/2.3/upgrading.html). The custom matchers are listed first.

**Comment by akoval** [comment]
all tests use new API, custom matcher are adopted too.

in protractor instead of jasmine.* I always wrote this.*

But when I use jasmine2 in configuration `this.addMatcher` doesn't work as it worked before

**Comment by DorianGrey** [comment]
As I've mentioned, please read the jasmine2 upgrade guide (referenced above):
>The addMatchers function is no longer on the spec (this) it is now on the global jasmine object.

Also note that `jasmine.addMatchers` requires a spec context - I'd suggest to call it in `beforeAll` definitions.

**Comment by akoval** [comment]
thanks
