### ISSUE TITLE
Why protractor is named "Protractor"?

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2476]
Hi guys,

Sorry for the odd issue but I really want to know why Angular team called their testing framework "Protractor".

Could somebody please tell some kind of story?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or the [angular discussion group](https://groups.google.com/forum/?fromgroups#!forum/angular). Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by bmsoko** [comment]
Angular --> https://en.wikipedia.org/wiki/File:Angular_dia_formula.JPG and you use a Protractor to measure---> http://nc5thgrademath.weebly.com/uploads/4/5/0/5/4505897/__4602089.gif?349

**Comment by juliemr** [comment]
Bingo @bmsoko
