### ISSUE TITLE
hangs on input in Chrome 45

### ISSUE THREAD

**Issue by yoorek** [angular/protractor#2477]
I have simple form with 2 inputs - username and password and button to login.
Everything works perfectly but protractor test hangs after filling first input in Chrome on Mac (it works in Firefox on Mac).
What is weird sometimes it fills both of them but hangs on clicking on the button.
After timeout I get 'Timed out waiting for Protractor to synchronize with the page after 11 seconds.'

Chrome 45 on Mac, Protractor 2.2.2

What is the cause of it?

Here is HTML:

    <input type="text" 
           name="username"
           ng-enter="ctrl.login(ctrl.username, ctrl.password)"
           ng-model="ctrl.username">
            
    <input type="password"
           name="password"
           ng-enter="ctrl.login(ctrl.username, ctrl.password)"
           ng-model="ctrl.password">
    
    <a href="" class="btn btn-login btn-danger btn-float no-waves"
               ng-click="ctrl.login(ctrl.username, ctrl.password)">
    </a>

Protractor test:

    describe('basic', function () {
    
        it('should login to application', function () {
    
            browser.get('lib/iqsec/ui/src/index.html#/?redirect_url=http://localhost:3000/dist/index.html');
    
            browser.sleep(1000);
    
            expect(browser.getTitle()).toBe('Logowanie');
    
            element(by.css('input[name="username"]')).sendKeys('user');
            element(by.css('input[name="password"]')).sendKeys('user');
            element(by.css('a.btn-login')).click();
    
            browser.sleep(1000);
    
            expect(browser.getTitle()).toBe('IMPAQ Alerter');
        });
    });

**Comment by Luisangonzalez** [comment]
Yes,

I have same issue.

Run on:
* Ubuntu 14.04 -  Chrome 44
* Ubuntu 14.04 - Firefox 40

* Windows 7 -  Chrome 44
* Windows 7 - Firefox 40

* MAC OX Yosemite - Firefox

And **not run** on:
* MAC OX Yosemite - Chrome 45

Only run on MAC - Chrome 45 if use ```browser.ignoreSynchronization = true```  in beforeEach it OK:

```
   beforeEach(function() {

      browser.waitForAngular();
      // Ignore sync (not angular page)
      browser.ignoreSynchronization = true;

   });

```

But it is not OK becuase I use Angularjs in this page.

**Comment by DanEEStar** [comment]
I have similar problems with Chrome on Mac...

**Comment by juliemr** [comment]
Should be fixed with updates in 2.4.0

**Comment by langerc** [comment]
Any update on this?

I`ve been searching for hours turns out that my test is fine (runs on firefox)

chrome 46.0.2490.86 on a mac
protractor 2.5.1

Problem: Test gets stuck after entering data in the first input field.
page.city.clear().sendKeys(city)
if i attach a promise to this function it gets resolved but no other sendkeys after the first one are working.

**Comment by DanEEStar** [comment]
The problem also still remains on my system.
I use
protractor 2.5.1
chrome Version 46.0.2490.86 (64-bit)
on Mac Version 10.11.1 (15B42)

The test just stucks on the first input field.
The strange thing is, that when I manually and randomly click inside of the Chrome window where the tests run it gets unstuck and slowly gets further to the next input fields until I stop clicking randomly and it will eventually time out and abort.

The tests run fine with Firefox on the same system.

**Comment by paqman** [comment]
I had the same issue, bypassing the animations didi the trick for me.

See http://stackoverflow.com/questions/26584451/how-to-disable-animations-in-protractor-for-angular-js-appliction for more information how to do it.

**Comment by langerc** [comment]
This did the trick for me. The test is working on the latest chrome (46.0.2490.86) on my mac now.
