### ISSUE TITLE
I've tried a small program on gmail to login and logout with protractor tool, but unsuccessful as unable to move to password filed

### ISSUE THREAD

**Issue by AR-Lenin** [angular/protractor#2478]

**Comment by AR-Lenin** [comment]
describe('Gmail', function() {
beforeEach(function(){
browser.driver.ignoreSynchronization = true;
}); 
  
 it('NavGmail', function() {
	
	browser.driver.get('http://gmail.com');
	browser.driver.findElement(by.id('Email')).sendKeys('anandrajan143');
	browser.driver.findElement(by.id('next')).click();
	browser.driver.findElement(by.id('Passwd')).sendKeys('9441415941');
	browser.driver.findElement(by.id('signIn')).click();

});
});

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by AR-Lenin** [comment]
Hi Nick,

Thanks!
