### ISSUE TITLE
Protractor tests run slow on selenium grid which has version 2.43

### ISSUE THREAD

**Issue by sri85** [angular/protractor#2484]
Recently i started to use protractor and we have a internal selenium grid which uses 2.43 version, there are a bunch of other clients like C# , python selenium frameworks which use the grid and all the tests run pretty fast.

But when it comes to protractor the tests take really long time and sometimes even timeout . Some say 2.45 version would make protractor tests run faster. Well i am not totally convinced with this statement , can some one confirm this?

**Comment by sri85** [comment]
Closing this issue since this is mostly like a support request http://stackoverflow.com/questions/32500695/protractor-tests-run-slow-on-selenium-grid-which-has-version-2-43

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sri85** [comment]
Done!
