### ISSUE TITLE
Interaction between shardTestFiles and grep

### ISSUE THREAD

**Issue by scriby** [angular/protractor#2485]
Hi,

If I attempt to run a subset of tests using grep while sharding test files, protractor ends up opening a browser window for test files which had no matching tests. We have so many test files that it makes it impractical to even try to use grep (and we do need to use sharding to speed up the execution).

The end goal is to be able to run subsets of the tests. I can handle some use cases with suites that run particular file patterns, but I also have a need to run test subsets spanning multiple files, and parallel execution is a must.

Is this something that is likely to be supported by protractor?

**Comment by sjelin** [comment]
Sorry for the slow response - what exactly is your feature request?

**Comment by sjelin** [comment]
Closing since there was no update
