### ISSUE TITLE
Documentation display errors

### ISSUE THREAD

**Issue by baweaver** [angular/protractor#2486]
![screen shot 2015-09-10 at 8 40 41 pm](https://cloud.githubusercontent.com/assets/979723/9806635/de65db50-57fb-11e5-84be-04c6946d3891.png)

For some reason there seem to be a lot of dead tags floating around in the docs. Almost looks like it's not rendering fully.

Google Chrome Version 45.0.2454.85 (64-bit) on Mac OSX

**Comment by NickTomlin** [comment]
I'm seeing this as well. I wonder if something shifted in a dependency of [dgeni](https://github.com/angular/dgeni)?

**Comment by NickTomlin** [comment]
Hmm, i'm seeing the following when running the website locally, perhaps this is an issue with webdriver's doc comments?

```shell 
warn:    Invalid tags found - doc (js)  - from file "node_modules/selenium-webdriver/lib/webdriver/we
bdriver.js" - starting at line 1782, ending at line 1787
Line: 1785: @package ...

warn:    Invalid tags found - doc (js)  - from file "node_modules/selenium-webdriver/lib/webdriver/we
bdriver.js" - starting at line 2481, ending at line 2495
Line: 2493: @package ...
```
I'm not familiar with the documentation system, but I'd be happy to help investigate if someone wants to give me a few pointers.

**Comment by juliemr** [comment]
@sjelin could you take a look at this?

**Comment by sjelin** [comment]
Ugh, yeah, I noticed this but didn't want to fix it.  But it looks like a fairly easy problem to solve though
