### ISSUE TITLE
Using protractor on non angular page (during testcase)

### ISSUE THREAD

**Issue by butzelbovat** [angular/protractor#2487]
Hi all,

ich have written a protractor test on a angular web page with use case is to buy a product. After the checkout i will be redirected to an external, non angular page to enter my credit card data. Afterwards i will be redirected to the last page (angular) with the order confirmation.
Problem/Issue:
Message:
    Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window"

code:
 it('fills out the form', function () {
        browser.driver.getCurrentUrl();
        browser.ignoreSynchronization = true;
        browser.driver.findElement(by.xpath('//*[@id="cardnumber"]')).sendKeys("xxx");
        browser.driver.findElement(by.xpath('//*[@id="expmonth"]')).sendKeys("xx");
        browser.driver.findElement(by.xpath('//*[@id="expyear"]')).sendKeys("xxxx");
        browser.driver.findElement(by.xpath('//*[@id="cvm"]')).sendKeys("000");
        browser.driver.findElement(by.xpath('//*[@id="next"]')).click();
    });

How can i fix this? It seems to be working when i run the test on my local machine and watch it. But i still receive the error...

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
