### ISSUE TITLE
Unable to install Protractor in Mac OS X

### ISSUE THREAD

**Issue by manoj9788** [angular/protractor#2489]
Hi Guys,
npm install -g protractor on my terminal throws these error as below,

Java 1.7
OS: Mac OSX Yosemite

Am I doing something wrong ?

Edited: Removed the full log and pasted here, as it was too long.
https://gist.github.com/manoj9788/e6f25075b02c34aa2295

**Comment by NickTomlin** [comment]
I'm seeing this as well, looks like an incompatibility with node 4 and building some of webdriver's dependencies. Switching to an earlier version of node should resolve for the short term.

**Comment by manoj9788** [comment]
I see, okay let me try with lower version and shall post here.

**Comment by donaldpipowitch** [comment]
This should be fixed if we update `selenium-webdriver`: https://github.com/angular/protractor/pull/2510

**Comment by HerrmannHinz** [comment]
installed node v0.12.7 and it works now. let us know when selenium-webdriver update is done.

**Comment by juliemr** [comment]
Note that it will actually still work with node 4.1.1, it just complains a lot. But all the functionality should be there.

**Comment by juliemr** [comment]
Proof of Protractor working with 4.1.1: https://travis-ci.org/angular/protractor/jobs/82026554

We're working to get `selenium-webdriver` updated so that you don't have to see errors, but that may introduce [subtle bugs](https://github.com/angular/protractor/pull/2263) that we want to make sure are documented.

**Comment by donaldpipowitch** [comment]
Installation "should" work with Node 4.1, but not for us. I think this is an already reported issue from npm.

**Comment by juliemr** [comment]
Should be fixed with 2.4.0 release.

**Comment by Deetrixx** [comment]
**Am unable to view the protractor or webdriver-manager on my machine**

I have installed the protractor well on my machine, however am unable to view the version of the protractor app and unable to use webdriver-manager as well. I keep getting error "**command not found**" for protractor and webdriver-manager
Please assist on way forward.
**AttachedScreenshot**
![Screen Shot 2019-05-29 at 5 47 52 PM](https://user-images.githubusercontent.com/17590912/58566828-f6fc7e00-8239-11e9-91db-c8a0cfae2d1c.png)
