### ISSUE TITLE
Protractor : Process exited with Error Code 100 

### ISSUE THREAD

**Issue by hari9946** [angular/protractor#2490]
Hi, 
I'm new to Protractor and i just ran Script which is ending up in error "100" below is the Script 
describe ("Login Test Scenario Done on Maine Project", Function(){
  it('should greet the named user', function() {
  browser.ignoresynchronization=true;
    browser.get('url');

    element(by.id('txtusername')).sendKeys('mathews');
    element(by.id('txtpassword')).sendKeys('Choice#123');	
    element(by.id('login1')).click();
	browser.sleep(10000);
 element(by.id('lbllogout')).click();
  });
};
and After i ran the Script i got the below Error 
"[Launcher] Process Exited with Error Code 100"

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
