### ISSUE TITLE
XML report link broken in FAQ page in doc folder

### ISSUE THREAD

**Issue by 61ue5peed** [angular/protractor#2491]
https://github.com/angular/protractor/blob/master/spec/junitOutputConf.js

^^^ this link is broken ;(

**Comment by 61ue5peed** [comment]
How do I produce an XML report of my test results?

You can use the npm package jasmine-reporters@1.0.0 and add a JUnit XML Reporter. Check out this example (junitOutputConf.js). Make sure that you are using the correct version of jasmine-reporters for your version of Jasmine.

^^^ this area ^^^^

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by NickTomlin** [comment]
Where is this link coming from?

**Comment by smartxp** [comment]
any news on this?
@NickTomlin the dead link mentioned by 61ue5peed is exactly on the faq you list:
https://angular.github.io/protractor/#/faq#how-do-i-produce-an-xml-report-of-my-test-results- 
Check the "example (junitOutputConf.js)." link, it shows up a 404.

**Comment by 61ue5peed** [comment]
var jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: 'testresults',
            filePrefix: 'reportXMLoutput'
        }));

**Comment by NickTomlin** [comment]
Perhaps we can just include this in a comment in the [reference config](https://github.com/angular/protractor/blob/673d416b7ef5abd0953da940cfa8cf2a59650df4/docs/referenceConf.js#L204) and change the link to point to that? Otherwise I don't see anything wrong with including this inline in the FAQ.
