### ISSUE TITLE
Add multiple mock modules in one test with 'addMockModule'

### ISSUE THREAD

**Issue by zalow517** [angular/protractor#2492]
Posting here after posting on StackOverflow with no success, link: http://stackoverflow.com/questions/32439856/add-multiple-mock-modules-in-one-test-with-addmockmodule

Can't really believe that no one has faced this issue before. How are you guys dealing modularly with multiple mocks?

**Comment by juliemr** [comment]
Answered on SO.

**Comment by zalow517** [comment]
Can someone please have a look at this? I replied on SO but no response. Now I also tried just using the raw browser.addMockModule implementation instead of the modular way. The below code is just adding three mock modules with different names and different JSON data. Only the last JSON data is being returned, the rest show as undefined. The last module which is passing through all other requests is working though.

var json1 = require('../../../../../../workspace/Valkyrie/mock-data/config-json1.json');
var json2 = require('../../../../../../workspace/Valkyrie/mock-data/config-json2.json');
var json3 = require('../../../../../../workspace/Valkyrie/mock-data/config-json3.json');

browser.addMockModule('mock1', function() {

    function runBlock($httpBackend, data) {

        $httpBackend.whenGET(/cfg-en-test-json1.js/).respond(function() {
            console.info('Mocking::json1');
            console.info(data.mockData.json1);
            return [200, data.mockData.json1];
        });
    }

    angular.module('mock1', ['ngMockE2E', 'my-app'])
        .value('data', {
            'mockData': arguments[0],
        })
        .run(runBlock);
    runBlock.$inject = ['$httpBackend', 'data'];
}, {
    json1: json1
});

browser.addMockModule('mock2', function() {

    function runBlock($httpBackend, data) {

        $httpBackend.whenGET(/cfg-en-test-json2.js/).respond(function() {
            console.info('Mocking::json2');
            console.info(data.mockData.json2);
            return [200, data.mockData.json2];
        });
    }

    angular.module('mock2', ['ngMockE2E', 'my-app'])
        .value('data', {
            'mockData': arguments[0],
        })
        .run(runBlock);
    runBlock.$inject = ['$httpBackend', 'data'];
}, {
    json2: json2
});

browser.addMockModule('mock3', function() {

    function runBlock($httpBackend, data) {

        $httpBackend.whenGET(/cfg-en-test-json3.js/).respond(function() {
            console.info('Mocking::json3');
            console.info(data.mockData.json3);
            return [200, data.mockData.json3];
        });
    }

    angular.module('mock3', ['ngMockE2E', 'my-app'])
        .value('data', {
            'mockData': arguments[0],
        })
        .run(runBlock);
    runBlock.$inject = ['$httpBackend', 'data'];
}, {
    json3: json3
});

browser.addMockModule('pass', function() {

    function runBlock($httpBackend) {

        $httpBackend.whenGET(/.*/).passThrough();
        $httpBackend.whenPOST(/.*/).passThrough();
    }

    angular.module('pass', ['ngMockE2E', 'my-app'])
        .run(runBlock);
    runBlock.$inject = ['$httpBackend'];
});
