### ISSUE TITLE
Protractor with For Loop not able to understand logic:

### ISSUE THREAD

**Issue by anuvratashu** [angular/protractor#2494]
what i need to do is that i have to click some images and with that the text is changing in another element. I am using For Loop with promises , so i am able to successfully click on images 1 by 1 but the text is not getting displayed . its displaying the last text 5 times . please help

element.all(by.xpath(".//*[@ng-repeat='num in facesGrid[$index]']")).then(function(faces){

        for(var i=0;i<faces.length;i++)
        {
            element(by.model('currentTestimonialIndex')).getText().then(function(Index){
            console.log(Index);
            });
            faces[i].click();

    }

        });

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by xyq117480** [comment]
Maybe you need a chain of then().
