### ISSUE TITLE
ElementArrayFinder#last wrong behavior

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2495]
Pre conditions:
at least 2 items are found by `element.all`

Steps to reproduce:
* `var lastItem = element.all(by.repeater('item in items')).last()`
* `page.remove(lastItem)`
* `lastItem.isPresent()// true` 

Expected: `lastItem.isPresent()// false`

**Comment by sjelin** [comment]
This is not a bug.  ElementArrayFinder#last doesn't actually retrieve a specific element.  Instead, it just directs all commands you sent to it to the last element in the set.  So let's your `'item in items'` maps to

* `<div>1</div>`
* `<div>2</div>`
* `<div>3</div>`

Right now `lastItem` points to `<div>3</div>`.  But if you remove `<div>3</div>`, `lastItem` will point to `<div>2</div>`.  So `lastItem.isPresent()` should still be true.

**Comment by stalniy** [comment]
So, imagine the similar case with array. 
```js
var array =[1,2,3];
var lastItem = _.last(array); // I'm cached the last item reference
// and it's expected that reference to it is the same
array.pop()
// lastItem variable contains reference to the same element
// however similar example with last() in elementarrayfinder doesn't work and it's not obvious why
```
So, then how can I check that the last element is removed?

**Comment by hhaamm** [comment]
@stalniy You can checkit with count() method.

If that's not enought you could try to select the elements again and check by text (or any way to know that your element was removed):

```javascript
var removedText = "dasfdasdf";

// remove element ....

element.all(by.repeater('item in items')).then(function(elements) {   
    elements.forEach(function(el) {
        expect(el.getText()).not.toBe(removedText);
    }
});
```

If you can't identify the elements becase are all equals then you can use count() method.
