### ISSUE TITLE
Not able to perform click event on iframe anchor tag, not displaying result

### ISSUE THREAD

**Issue by krishnaJuliemr** [angular/protractor#2499]
Hi Juliemr, i am performing the tes case on iframe but the click event not displaying the result. please give your suggestions 

My html code inside iframe:
```html
<ul id="leftCol">
<li><a id="category_link_MLAceServers" class="icon-arrow">ProLiant ML Servers</a></li>
<li><a id="category_link_cClassAceEnclosures" class="icon-arrow">c-Class Enclosures</a></li>
<li><a id="category_link_DLAceServers" class="icon-arrow">ProLiant DL Servers</a></li>
</ul>
```
```js
describe('Protractor iframe Test', function(){

	beforeEach(function(){
		browser.get('my url');
	});

	it('should test the iframe', function(){
		//browser.switchTo().frame(0);
browser.driver.switchTo().frame(browser.driver.findElement(protractor.By.xpath('//*[@id="right_frame_h"]')));

		// Test iframe with driver
var blLink = browser.driver.findElement(protractor.By.xpath('//*[@id="category_link_BLAceServers"]'));

		browser.driver.findElement(by.id("category_link_MLAceServers")).click(); // this click is not displaying out put.
	
		expect(blLink.getText()).toEqual('ProLiant BL Servers'); // giving result successfully 
	});

});
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by krishnaJuliemr** [comment]
This is not Support quesion @NickTomlin , i am using Protactor to test angular applications, I posted there also but i dont get any response.. So I pasted here, if you know how to perfrom click event in the iframe using protractor (Angular js).

**Comment by sjelin** [comment]
Cannot reproduce.  Not sure what's wrong but it's an issue with your app and not with Protractor.
