### ISSUE TITLE
verbose and stackTrace options

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2503]
Since `isVerbose` and `includeStackTrace` has no effect anymore (after changing the jasmine runner), does it make sense to keep `--verbose` and `--stackTrace` cli arguments? ([source](https://github.com/angular/protractor/blob/master/lib/cli.js#L62-L63)) 

Thanks.

**Comment by sjelin** [comment]
Probably not

**Comment by moneytree-doug** [comment]
I upgraded and didn't realize it would have an effect on those options. Why is it? What can I do to re-add back the functionality?

**Comment by sjelin** [comment]
I believe it has something to do with the jasmine team but I'm not totally sure

**Comment by hankduan** [comment]
1) I opened #2644 to add verbose back. Please comment there.
2) Regarding those two options, those two options are for jasmine1. They will be removed once #2645 is resolved

Closing this issue. Please comment in the appropriate issue mentioned above.
