### ISSUE TITLE
Add chat via gitter or slack

### ISSUE THREAD

**Issue by NickTomlin** [angular/protractor#2504]
I've found that [gitter](https://gitter.im/) and [slack via slackin](http://rauchg.com/slackin/) are great resources for helping people with hard to describe issues (e.g. almost all the troubleshooting requests in the issues queue). Implementing this for protractor would make it easier to shift issues to SO or Gitter/Slack and close them immediately; it would also hopefully reduce the clutter on issue threads while we are trying to get some basic information on the issue.

I'd be happy to help moderate the channel and assist someone with contributor access in setting it up.

**Comment by juliemr** [comment]
It looks like angular.js is using Gitter, so it would be great to follow precedent there and set one up for Protractor as well. Let me look into it, check on access stuff and get back to you.

**Comment by ericmartinezr** [comment]
+1 for gitter. If you have a github account (we participate in github, so yeah...) it is as easy as 'log in using your github account'. Slack needs you to register for every channel you want to enter. Also gitter is more user friendly, just my opinion.

**Comment by juliemr** [comment]
OK, made it so: https://gitter.im/angular/protractor

Go wild!

**Comment by juliemr** [comment]
I'll be adding links from the FAQ and CONTRIBUTORS shortly.

**Comment by juliemr** [comment]
Done with 546f16335714309709566b828f46a60eb9fe6ee3

Thanks for the suggestion!
