### ISSUE TITLE
Cache drivers

### ISSUE THREAD

**Issue by blabno** [angular/protractor#2507]
I'm required to run 
```
webdriver-manager update --standalone
```
each time I remove node_modules and install them back again. Most of the content of `node_modules` is nicely cached by `npm` but the drivers are not. This is real PITA, especially for CI, which always wipes out workspace, clones repo and runs `npm install` and `webdirver-manager update --standalone`.

So my very humble request is: make webdriver-manager cache the chrome drivers somewhere locally (not inside cwd, but in some configurable dir with default to user's home dir). I'm willing to pay for this feature.

**Comment by blabno** [comment]
Pull requested: https://github.com/angular/protractor/pull/2508

**Comment by aniaw** [comment]
+1

**Comment by FredZgred** [comment]
+1

**Comment by Kronos66** [comment]
+1

**Comment by Nigatsu** [comment]
+1

**Comment by kbuchacz** [comment]
+1

**Comment by blabno** [comment]
Ok, since #2555 got closed, could we decide here if existing files should be removed or not?

**Comment by juliemr** [comment]
Done with webdriver-manager - you can choose an output dir there.
