### ISSUE TITLE
restartBrowserBetweenTests=True does not work correctly between multiple suites

### ISSUE THREAD

**Issue by badrisugavanam** [angular/protractor#2509]
I had a protractor.conf which has the following 
              - Suite A - two specs 
              - Suite B - two specs 

there is an error when Suite B is launched 

    "Failed: This driver instance does not have a valid session ID (did you call
WebDriver.quit()?) and may no longer be used."

**Comment by badrisugavanam** [comment]
this is really a pain . We should get it fixed in protractor

**Comment by sjelin** [comment]
Cannot reproduce.  Do you have a minimal example?

**Comment by juliemr** [comment]
I'm closing issues as stale. If there is still a reproducible problem, please open a new issue!
