### ISSUE TITLE
update deps to selenium 2.47.0

### ISSUE THREAD

**Issue by nschloe** [angular/protractor#2512]
Selenium 2.47.0 [introduces support for Node.js 4.0.0](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md). Please bump the dependency in protractor.

**Comment by NickTomlin** [comment]
This is covered in https://github.com/angular/protractor/pull/2510

**Comment by nschloe** [comment]
Thanks. Closing in favor of #2510.
