### ISSUE TITLE
Possible to use Jasmine2 on mode ElementExplorer?

### ISSUE THREAD

**Issue by machei** [angular/protractor#2515]
Example code but with failling error:
```
vagrant@vagrant-ubuntu-trusty-64:~$ protractor p.conf --elementExplorer
Using the selenium server at http://192.168.1.2:4444/wd/hub
Starting WebDriver debugger in a child process. Pause is still beta, please report issues at github.com/angular/protractor

Type <tab> to see a list of locator strategies.
Use the `list` helper function to find elements by strategy:
  e.g., list(by.binding('')) gets all bindings.
Starting debugger agent.
> Debugger listening on port 5858

>
element(by.id(''))         element(by.css(''))        element(by.name(''))       element(by.binding(''))
element(by.xpath(''))      element(by.tagName(''))    element(by.className(''))

> expect
ReferenceError: evalmachine.<anonymous>:1
expect
^
expect is not defined
>
```

Also i am beginner of jasmine, i wanted to learn how to use them by using like console for communicating over webdriver.

**Comment by juliemr** [comment]
No test framework is available from element explorer - it's intended for trying out locators, but not running a full test. `expect` doesn't really make sense outside of the context of a running test suite (what would a failure look like? printing one test to the console?), so this would be a significant change and is not in our near road map.

I'd encourage you to use element explorer to play with the `browser` and `element` commands, and use a small script to learn more about Jasmine.
