### ISSUE TITLE
tests fail in background

### ISSUE THREAD

**Issue by surfjedi** [angular/protractor#2518]
what would cause tests to fail if the browser windows opened by protractor are in background? 

We have tests that pass but if we switch to look at another program while the tests are running half will fail or more?

**Comment by juliemr** [comment]
I've seen browsers behave differently in how they select menus when they are not the focused application, and also sometimes browser throttle requests when not focused so things slow down. Other than that, it's hard to say without knowing more about what the test script is doing. I hope that gets you started!

**Comment by hhaamm** [comment]
@surfjedi If you are using Linux, you can use Xvfb to execute protractor (and Selenium) in a virtual frame.
