### ISSUE TITLE
Protractor and $q.defer actions

### ISSUE THREAD

**Issue by vzamishlyaev** [angular/protractor#2519]
Hello, I have angular code like this:
```
$scope.logout = function() {
    console.log(1);
    clearCookies().then(function() {
        console.log(2);
        $state.go('loginScreen');
   });
};

function clearCookies() {
    var defer = $q.defer();
    if(something) {
       sendSomeRequest().then(function() {
           defer.resolve();
       });
    } else {
        defer.resolve();
    }
    return defer;
}
```

$scope.logout function is calling on element's ng-click.
And I have test:
```
element(by.css('[class="logout-button"]')).click();
```

I'll never see "2" in console, through I think "then" callback is never triggered when it's triggered by protractor. And it's just never make "$state.go" action.
Maybe I missed something? Thank you for any help.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
