### ISSUE TITLE
getInnerHtml does not work as expected within "expect"

### ISSUE THREAD

**Issue by GarySze** [angular/protractor#2529]
Hi,

  I encounter some weird behaviour that i did't get the result i expected by using getInnerHtml within "expect" for the FIRST time, but it works if i call it again. Below is my code:

	var getAutoSuggestTarget = function() {
		return element.all(by.tagName('span')).filter(function(elem, index) {
			return elem.getInnerHtml().then(function(text) {
				return text === 'METALS';
			});
		});
	};
	
	browser.wait(function() {
		var targetEle = getAutoSuggestTarget();
		return typeof(targetEle) !== 'undefined';
	}, 5000).then(function() {
		var targetEle = getAutoSuggestTarget();
		expect(targetEle.getInnerHtml()).toMatch("METALS"); //this line triggers error (please see below)
		expect(targetEle.getInnerHtml()).toMatch("METALS"); // this line works as expected		
		targetEle.click();
	});

  Message:
    Expected [  ] to match 'METALS'.
  Stack:
    Error: Failed expectation
        at C:\NP3 Web Test\spec.js:59:36
        at [object Object].promise.ControlFlow.runInFrame_ (C:\Users\UC144410\Ap
pData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\we
bdriver\promise.js:1877:20)
        at [object Object].promise.Callback_.goog.defineClass.notify (C:\Users\U
C144410\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdri
ver\lib\webdriver\promise.js:2464:25)
        at [object Object].promise.Promise.notify_ (C:\Users\UC144410\AppData\Ro
aming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\
promise.js:563:12)
        at Array.forEach (native)
        at Object.goog.array.forEach (C:\Users\UC144410\AppData\Roaming\npm\node
_modules\protractor\node_modules\selenium-webdriver\lib\goog\array\array.js:203:
43)
        at [object Object].promise.Promise.notifyAll_ (C:\Users\UC144410\AppData
\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriv
er\promise.js:552:16)
        at goog.async.run.processWorkQueue (C:\Users\UC144410\AppData\Roaming\np
m\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:
125:21)
        at process._tickCallback (node.js:356:9)

I have already ensured the element with innterHTML === 'METALS" exists with browser.wait before calling "expect", not sure why this is happening. Could anyone help?

Many Thanks!!
Gary

**Comment by stalniy** [comment]
This is odd:
```js
browser.wait(function() {
    var targetEle = getAutoSuggestTarget();
    return typeof(targetEle) !== 'undefined';
}, 5000)
```
as `getAutoSuggestTarget` always returns instance of `ElementArrayFinder` and will never be `undefined`.

`targetEle.getInnerHtml()` always returns an array containing innerHTMLs of all items that satisfy filter condition (array of strings).
 
`toMatch` is for regular expressions only, don't know how you use it for arrays (https://github.com/jasmine/jasmine/blob/master/src/core/matchers/toMatch.js)

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
