### ISSUE TITLE
protractor-2.2.0 not working with chrome versions greater than 41 

### ISSUE THREAD

**Issue by sreenigudugunta** [angular/protractor#2530]
I am working on CentOS 6.6
I observed that Protractor 2.2.0 is not working with any chrome version greater than 41.

Log shows ...

java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50'
System info: host: 'N/A', ip: 'N/A', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-573.3.1.el6.x86_64', java.version: '1.6.0_30'
Driver info: driver.version: unknown

Are you aware of this issue? 
If so, please let me know how to fix it.

**Comment by juliemr** [comment]
This is fixed in master, with an upgrade to selenium, and will be released shortly once other versioning is resolved.

**Comment by juliemr** [comment]
2.3 is out, which fixes this issue.
