### ISSUE TITLE
Strange behavior of ElementArrayFinder#isDisplayed

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2532]
If I want to prevent a promise rejection I can't just write `thenCatch` as ElementArrayFinder doesn't have `thenCatch` or `thenFinally` as it actually is not a promise but promise-like:
```js
element.all(by.repeater('item in items')).isDisplayed().thenCatch(function() {
   return false;
});
// throws exception
```
Instead I'm forced to write:
```js
element.all(by.repeater('item in items')).isDisplayed().then(null, function() {
   return false;
});

// or
element.all(by.repeater('item in items')).isDisplayed().then().thenCatch(function() {
   return false;
});
```
The same behavior with all methods 
```js
var WEB_ELEMENT_FUNCTIONS = [
  'click', 'sendKeys', 'getTagName', 'getCssValue', 'getAttribute', 'getText',
  'getSize', 'getLocation', 'isEnabled', 'isSelected', 'submit', 'clear',
  'isDisplayed', 'getOuterHtml', 'getInnerHtml', 'getId', 'getRawId'];
```
the same with `evaluate`. All these methods return promise of primitive value, wrapping them into `ElementArrayFinder` looks incorrect

**Comment by juliemr** [comment]
The reason that they're wrapped into an `ElementArrayFinder` is so that they can continue to be chained, e.g.

`element(by.stuff).click().getText().getAttribute()`

We could consider adding the `thenCatch` and `thenFail` functions.

**Comment by stalniy** [comment]
As for me it looks a bit as overhead which leads to long not really clear and readable code. Also I believe this leads to code which breaks single responsibility principle. 

The convinience out of this is not so big and probably can be only used with smth like sendKeys and click but not with others like isDisplayed. That behavior,  is really strange and unexpected for me.

Also because of that you have constructor for elementfinder which is overloaded by arguments. 

Instead I suggest to return just a promise or DeferredValue with methods like primitives have so that devs can write more readable and straightforward tests what is the number 1 priority
```js
It("replaces text", => {
  expect(element.getText().replace(/[\n\r]+/, "")).to.equal("test")
})

// instead of
It("replaces text", => {
  element.getText().then((text)=>{
       expect(text.replace(/[\n\r]+/, "")).to.equal("test")
  })
})
```
This is what I've done for my project. 1 option is much more straightforward than 2. And this is because getText returns aka deferred primitive value

**Comment by stalniy** [comment]
By the way I can create suggested PR or describe in details my solution. Because it's smth that can be in core

**Comment by juliemr** [comment]
I'm not sure how you propose to achieve option 1. `getText` is performed asynchronously, so there's no way it can return a primitive value.

I don't like the idea of having some commands return promises and some return ElementFinders. Things should be consistent.

**Comment by stalniy** [comment]
Consistency is good but not everywhere. As an example:
```js
[1,2,3].reduce(function(sum, i) { return sum + i; }) // returns int not array
[1,2,3].map(function(i) { return i * 2 }); // returns array
[1,2,3].filter(function(i) { return i * 2 }); // returns array
[1,2,3].every(function(i) { return i }); // returns boolean
```
So what is the root cause of the issue:
I use `chai` and `chai-as-promised`. Last one provides extra flag `eventually`, so you can write:
```js
expect(element.getText()).to.eventually.equal('test');
```
However in env where everything is a promise it's ridiculous to write `eventually` for every `expect`. So, I created custom `expect` function which checks if the value is promise then add `eventually` (`eventually` extracts underlying value of the promise and check it with expected result).

**And here is the problem!**
I don't want to add `eventually` to element finders because in cases when element is not exist method `then` of elementFinder will call `getWebElements` which throws exception if element is not exist.
So, I added check if promise is an instance of element finders (both array and element) do not add `eventually` flag.

And then I found out that `isDisplayed` returns `ElementArrayFinder`. But for `isDisplayed` promise I want to add `eventually` and here I'm stuck. Case like this is not possible:
```js
global.expect = function(value) {
  var expectation = chai.expect.apply(chai, arguments);
  var isElementFinder = value instanceof protractor.ElementFinder || value instanceof protractor.ElementArrayFinder;
  var isPromise = value && typeof value.then === 'function' && !isElementFinder;

  return isPromise ? expectation.eventually : expectation;
};

expect(element.isDisplayed()).to.be.true; // doesn't work as eventually is not added as `isDisplayed` returns ElementFinder instead of just a promise
```

Any suggestions on this?

**PS**: sorry for long comments but it's really important for me! Thanks for your attention

**Comment by stalniy** [comment]
**About DeferredValue**:
You are right there is no way `getText` to return primitive but you can create API that it looks like as it's a primitive ("primitive" promise value in async world).
Here is a real test example written on `Protractor` with suggested solution:
```js
  it('shows 2 channels per tap', function() {
    var counts = subject().channels.countBy('tapName').values();

    expect(counts).to.have.members([ 2, 2 ]);
  });
```

**PS**: I have a rule of thumb:
no `then` inside tests.
Why? Because that's way tests are more straightforward and clear, easy to support, easy to understand, easy to extend.

**Comment by sjelin** [comment]
Protractor will automatically resolve webdriver promises received by an `expect()` command.  So feel free to write
```js
expect(element.getText()).toBe('test');
```
instead of
```js
expect(element.getText()).to.eventually.equal('test');
```

**Comment by stalniy** [comment]
@sjelin you are talking about jasmine but I use `chai.js`

**Comment by stalniy** [comment]
One more thought about consistency. You can consider `jQuery` as the most chainable library and even they have methods that return primitive: `val`, `prop`, `data`, `is(':visible')`, etc

**Comment by hhaamm** [comment]
What would be the alternative to a primitive type for val() in jQuery? In the end you need a primitive value somewhere... that doesn't seem to be a jQuery inconsistency to me.

**Comment by stalniy** [comment]
a primitive value is promise in our case. It's enough for start.

If we want to go further we can create extra abstraction for real primitive async value. I mean custom promise implementation with extra methods like: `replace`, `add`, `substract`, `multiply`, etc. For example, test for adding element into list may look like this with custom primitive value promise (I call it `DeferredValue`).
```js
it('adds item to the list', function() {
  var items = element.all(by.repeater('item in items'));
  var initialCount = items.count();

  element(by.id('add-btn')).click();

  expect(items.count()).to.equal(initialCount.add(1))
})
```

**Comment by sjelin** [comment]
Ok, we get it.  It would be *great* if we could return primitives but we can't.  Implementing all these methods onto our promises looks like a huge pile of work but we'll do it if enough people want it.

**Comment by stalniy** [comment]
@sjelin Got it, thanks! This is just one possible consequence of returning something except ElementFinder.

But what's about `isDisplayed` etc methods? Do you plan to change the API so that regular promise is returned instead of ElementFinder?

**Comment by Todmy** [comment]
I absolutely agree with @stalniy. I think it will be useful feature.

**Comment by sjelin** [comment]
It's extremely unlikely that we'll be returning regular promises.  If you want you can always use `q` or `webdriver.promise` to make a promise out of our promise-like.

**Comment by stalniy** [comment]
@sjelin What is the reason of such decision?

**Comment by hankduan** [comment]
Let's recap what's going on here:

1) ElementFinder should have a `thenCatch` and `thenFinally` method so that it is possible to do this:
```javascript
element.all(by.repeater('item in items')).isDisplayed().thenCatch(function() {
   return false;
});
```
As @juliemr mentioned, yes we should do this.

2) Making a custom promise that include 'add', 'subtract', etc. This would mean protractor needs to create wrappers for all of number operator, string operators, etc. 
I don't think this should be done on two grounds:
1) it is a ton of work for very little gain (i.e. you avoid a `then`)
2) it makes development harder as now you need to look up these APIs instead of using native APIs
instead of 
```javascript
elem.getText().then(function(text) { var res = text.replace(...).length + 1; return Math.pow(res, 3); })
```
you have:
```javascript
elem.getText().substring(...).replace(...).length().add(1).pow(3);
```

Sure, it's shorter, but it's means people need to look up APIs for all primitive operations. 

3) All elementFinder actions should return promises. The only downside to this is you can't chain actions. 
Sure that isn't a big deal as people can just put them into different lines. However, this would be a huge breaking change for many users, for what I feel is minimal benefit -- i.e. very unlikely we would do this unless there are good reasons to introduce this change. 

I think the above 3 are all the points covered in this issue, and only #1 is actionable at the moment. Let me know if you disagree.

**Comment by stalniy** [comment]
@hankduan the wierd thing is that isDisplayed returns an ElementFinder instance. 

It's ok if procedure returns finder(click, sendKeys, etc) but it's not ok when function(isDisplayed, isPresent, etc) does this. 

So, I don't believe that somebody write smth like this:
```js
element(by.id).isDisplayed().click()
```
As it has no sense. So, instead of adding theCatch/thenFinally just return a promise for function-like methods. For procedures - return the same because this is logical:
```js
element(by.id).click().element(bi.xpath).sendKeys()
```
As a result there is a really low likelihood that this will break somebodies code. 

Does it make sense?

**Comment by juliemr** [comment]
If we add `thenCatch` and `thenFinally`, then there's no harm in having `isDisplayed` return an `ElementFinder`. Would there be any need for it to be a pure promise? I think that if we solve 1 on Hank's list there's no more issues.

**Comment by stalniy** [comment]
@juliemr that won't fix the weird thing :) it's like when you need to return `true` you return any number except 0 and for `false` return 0. 

You can do that but it's weird, code smells.

**Comment by hankduan** [comment]
The main thing regarding the consistency note is that people should be able to chain everything the same way.

No one would do `element(by.id).isDisplayed().click()`, but they would do `element(by.id).isDisplayed().then(function...)`. 
So if `element(by.id).isDisplayed()` returns a promise, while `element(by.id).click()` returns an element finder, it would be a potential source of confusion as people chain from them (i.e. chaining `then` is also considered chaining and it's a very typical use case).

**Comment by stalniy** [comment]
@hankduan probably I don't see the obvious thing... 

So, let's do this:
# Could you please provide an example of confusion which you are talking about?
# What is the Single Responsibility of ElementFinder? If it's "element search" why does it may contain anything else except WebElement?
# Why will the proposed behavior confuse somebody at the same time when WebElement#isDisplayed doesn't (it returns a Promise and not a WebElement)?

**Comment by Visya** [comment]
I support this feature request.
It's a more straightforward approach to return "primitive" promises from operations that should logically return primitive in non-promise version.
It seems counterintuitive to be able to chain other ElementArrayFinder methods after isDisplayed.

I think, this will improve readability and eliminate confusion, not add to it.

**Comment by hankduan** [comment]
@stalniy ElementFinder contains a number of (related) responsibilities:
1) It must be able to find an element, including nested elements like `element(by.css('foo')).all(by.class('bar')).filter(fn).first()`
2) It must allow users to perform an action on the element (you can argue whether chaining can be allowed once you perform an action -- I'm not sure about this). However, it must sync with Angular before performing an action
3) It should usable within a page object, that is, no request should be fired until user actually performs an action. 

These are some of the reasons why ElementFinder isn't just a simple webelement. 

Now, you may request that ElementFinder.action should return a plain promise, so that instead of:
```javascript
$('foo').clear().sendKeys('bar'); // This is an ElementFinder
```
You should do:
```javascript
var foo = $('foo'); // This is an ElementFinder
foo.clear(); // This is a Promise
foo.sendKeys('bar'); // This is a Promise
```

This is up for discussion, but I feel like most people would prefer the first example. I could be wrong, so I've changed the label of this issue to 'type: discussion'

**Comment by stalniy** [comment]
@hankduan I totally agree with you.

And the only thing which I suggest to change is the return value for methods like: isPresent, isDisplayed, evaluate, similar. These methods return action result.

 Current implementation holds action result in an ElementFinder instance which seems incorrect as ElementFinder doesn't provide methods for working with this action result. If so, why is action result wrapped in ElementFinder?

So, let's leave methods like sendKeys, click, element, similar (which return webElements) as they are and change return value of methods like isPresent, isDisplayed, simlar (which return action result) to be plain promise. 

Does it sound reasonable? If not, where do you see the problem?

Thanks

**Comment by hankduan** [comment]
This is where I see the problem -- the inconsistency. 
1) Talking about missing methods (i.e. `thenFinally`)
Users would encounter the issue where `el.isPresent().thenFinally(...)` works, while `el.click().thenFinally(...)` doesn't. In other words, because they return _very_similar_ results (element finder which is promise like, vs a promise), I believe users _could_ be confused. 
2) Alright, now if say we implement all the promise methods for element finder, so #1 doesn't happen, there will still be compatibility issues. Where people will inevitably mix them. i.e. 
```javascript
el.click().then(function() {
  return el.isPresent().then(function(res) {
    return res;
  });
});
```
This is a very simplistic case, but as people mix two types of promise-systems, very hard to debug problems will ~~definitely~~ very likely come up.

**Comment by stalniy** [comment]
@hankduan 

1. I agree
2. Why do we care if promise implementations are mixed? In this case user will receive an expected result as if either he writes this:
```js
el.isPresent().then(function() {
  return el.click();
}).then(function() {
   console.log('element is clicked');
});
```
or this:
```js
el.isPresent().then(function() {
  return el.click().then(function() {
     console.log('element is clicked');
  });
});
```
The result is the same because the implementation relies on `then`-able interface. Nobody will write this:
```js
el.isDisplayed().click(); // which also may produce unexpected behavior
```
as this has no sense. But
```js
el.click().isPresent()
```
still will work.

So, the possible fix is:
* Change methods which produce "action result" to return a regular promise (we won't confuse libraries which rely on code like `result instanceof ElementFinder` - otherwise how can they check if `result` contains a real element finder or an action result?)
* Add `thenCatch` and `thenFinally` to `ElementFinder`-s (we won't confuse people who write `isDisplayed().thenCatch`)

**Comment by juliemr** [comment]
Hi folks. I'm going to close this discussion - thank you for participating. I think that this was helpful to think about, but I don't think it's providing any value to leave open. We value the consistency of having the return always be an ElementFinder.
