### ISSUE TITLE
Use Array#map instead of Array#forEach

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2533]
Lines:
- https://github.com/angular/protractor/blob/master/lib/element.js#L146
- https://github.com/angular/protractor/blob/master/lib/element.js#L159
- https://github.com/angular/protractor/blob/master/lib/element.js#L206
- https://github.com/angular/protractor/blob/master/lib/element.js#L214
- https://github.com/angular/protractor/blob/master/lib/element.js#L395
- https://github.com/angular/protractor/blob/master/lib/element.js#L416
- https://github.com/angular/protractor/blob/master/lib/element.js#L517
- probably in other files

use `forEach` where should be used `map`. The main benefit is that code will look simpler or more readable. If you are ok with this I can create a pull request

**Comment by juliemr** [comment]
Sure, seems reasonable. Go ahead and make a PR.
