### ISSUE TITLE
ElementArrayFinder#reduce is inconsistent with Array#reduce

### ISSUE THREAD

**Issue by stalniy** [angular/protractor#2534]
In case when `initialValue` is not provided `Array#reduce` uses first value as first argument in reduce callback and `ElementArrayFinder#reduce` just fails with runtime exception.

```js
var sum = [ 1, 2, 4 ].reduce(function(sum, item) {
   return sum + item;
}); //7

element.all(by.repeater('item in items')).reduce(function(first, second) {
   // first is undefined. runtime exception
});
```
And I believe https://github.com/angular/protractor/blob/master/lib/element.js#L560 should use `reduce` instead of `forEach`.

**Comment by juliemr** [comment]
Yeah, we should fix that inconsistency.

**Comment by hankduan** [comment]
I wouldn't call this a bug. Consider the typical use case:

```javascript
var value = element.all(by.css('.items li')).reduce(function(acc, elem) {
  return elem.getText().then(function(text) {
    return acc + text + ' ';
  });
}, '');

// value is now a promise resolving to 'First Second Third '
```

Now, if you don't pass the initial value, it makes little sense to use the first element in the elementArrayFinder (which is an element finder) as the initial value. 

I don't even know how to use reduce if acc took the initial value as an element finder:

```javascript
var value = element.all(by.css('.items li')).reduce(function(acc, elem, index) {
  // acc could be an elementfinder or a promise of a value  
  if (index == 0) {
    ?? // acc is an elementFinder
  } else {
    ?? // acc is a promise of the previously return value
  }
});
```

**Comment by stalniy** [comment]
The only when this can be useful is when resulting promise resolves to ElementFinder (e.g. `sort` or another kind of comparison)
```js
sortedItems = element.all().reduce(function(first, second){
  return promise.all([ first.getText(), second.getText() ]).then(function(texts) {
   return texts[0] > texts[1] ? first : second;
})
})
```

**Comment by hankduan** [comment]
I'm not convinced this is actually useful (given the reasons I gave above), and I'm worried about people forgetting the initial value and getting weird results. 

I'll leave this issue open for now and see if anyone else wants this behavior. For now I've fixed the docs to be correct: https://github.com/angular/protractor/commit/d7bb003062077833c491820ec39cf73592bc6c13

**Comment by stalniy** [comment]
@hankduan currently user also may forget to pass initial value and  receives runtime error or weird result

I believe  underscorejs is popular enough and that `_.reduce` is one of the most used functions, don't believe somebody won't see if forgets accumulator. So, please read their description http://underscorejs.org/#reduce

**Comment by juliemr** [comment]
Sorry for the slow responses - I agree with Hank here, the best way to avoid anyone shooting themselves in the foot is to require an initial value. Thanks for the discussion!
