### ISSUE TITLE
Testing for correct page transition

### ISSUE THREAD

**Issue by zawarq** [angular/protractor#2539]
Hi

I have a small script that should test for the page to transition to another page upon button click. Here is the code:

    'use strict';

    var Util = require('./util.js');

    describe('My web application', function() {
      var hostName = 'hostname';
      var landingPage = 'https://user:pass@' + hostName + '/webapp/#/welcome';
      var applyPage = '';
      var util = new Util();

      it('should detect a wrong password', function() {
        var errStr = 'Sorry, the code you entered was not valid. Please check it and try again.';
        var txtPass = element(by.model('password'));
        var btnSubmit = element(by.css('div.landing--login button'));
        var dvErrMsg = element(by.css('div.form-group div.ng-scope'));
    
        browser.get(landingPage);

        txtPass.sendKeys('pass-word'); //this password is correct
        btnSubmit.click(); //with a correct password, the web app navigates to another page
      });
    });

And the contents of util.js are:

     'use strict';

    (function() {

    var Util = function() {
        var u = this;
        u.isSameURL = function(url)
        {            
            browser.wait(function() {
              return browser.getCurrentUrl().then(function(surl) {
                expect(surl).toEqual(encodeURI(url));
              });
            }, 10000, "URL hasn't changed");
        }
    };
    
    module.exports = function() {
        return new Util();
    };
    }());

This code gives me an error:

UnknownError: javascript error: document unloaded while waiting for result
....
From: Task: URL hasn't changed
    at [object Object].u.isSameURL (/Users/mahrukhali/dev/covermenow/protractor/util.js:9:21)

Note that line 9 of util.js corresponds to the browser.wait call

I have tried to implement the above code based on a solution provided here:
http://stackoverflow.com/questions/29129186/how-to-use-browser-getcurrenturl-in-a-protractor-test

 (I don't quite understand whether a return is needed here: return browser.getCurrentUrl()....)

Any help will be greatly appreciated.

Regards
Zawar

**Comment by sjelin** [comment]
As per our [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md), please ask questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) (StackOverflow is your best bet though).

That said, you probably want
```js
return surl != encodeURI(url);
```
instead of
```js
expect(surl).toEqual(encodeURI(url));
```

Also, it doesn't seem like you call `isSameURL` anywhere?  Not sure exactly what it's supposed to do tbh
