### ISSUE TITLE
Failed: java.lang.String cannot be cast to java.lang.Number

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2546]
Suddenly a test started to fail with this exception

```
 Message:
    Failed: java.lang.String cannot be cast to java.lang.Number
  Stack:
    UnknownError: java.lang.String cannot be cast to java.lang.Number
        at Array.forEach (native)
    From: Task: Run beforeEach in control flow
        at Array.forEach (native)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/usr/src/app/test-e2e/spec/reviews.js:63:2)
        at Object.<anonymous> (/usr/src/app/test-e2e/spec/reviews.js:12:1)
```

**Comment by bitliner** [comment]
I think the stacktrace should provide some more information too.

No easy to debug it in this way.

**Comment by bitliner** [comment]
It looks like the error is inside a beforeEach. But nobody tried to convert String to Number, and all the invoked functions take as input the proper type.

**Comment by juliemr** [comment]
Huh, that's a very odd situation. Can you provide us with a reproducible example? Can you provide the output of running with `--troubleshoot`?

**Comment by bitliner** [comment]
I was not able to run it with that option yet, it is completely not deterministic :-(
I am running it multiple times until I get the error...

**Comment by bitliner** [comment]
Basically, my `describe` func contains 2 `it` test.

If I run both the `it`, then the second fails. If I run only the second, it has success.

Below the error message that I posted above, there is another error message that is

```
Message:
    Failed: Element is no longer attached to the DOM
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/stale_element_reference.html
    Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
    System info: host: 'ffb8640c43fe', ip: '172.17.0.65', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-37-generic', java.version: '1.7.0_79'
    Driver info: driver.version: unknown
```

I am going to look if it manages some element that is removed from the DOM.

**Comment by bitliner** [comment]
I have 1 `describe` containing 2 `it`.

If I run it with both `it`s, the second `it` fails.
If I run only the first `it`, then it has success.

The error is in the `beforeEach`, ma it occurs only when it is executed on the second time, just before the second `it`.

Going to investigate more...

**Comment by bitliner** [comment]
The error is coming because I am running selenium inside a docker container - using `selenium/standalone-firefox:2.45.0`. 

If I use selenium outside the container everything works fine.

**Comment by hankduan** [comment]
Closing stale issues. Can you open a new issue with a reproducible test case if this is still a problem? Thanks!
