### ISSUE TITLE
Protractor does now invoke $http.post

### ISSUE THREAD

**Issue by Rapso** [angular/protractor#2547]
I'm trying to write a test which will check if i can add "conversation" to db here is what i have 
```javascript
describe('New Survey:', function() {
  it('Adding the survey', function() {
    browser.get('http://127.0.0.1:8090/#/newConversation');
    expect(browser.getLocationAbsUrl()).toMatch('/newConversation');
//here i'm filling conversation form
    element.all(by.css('.form-control')).get(5).click();
    element(by.model('vm.user')).sendKeys('TestUser');
    element(by.repeater('user in vm.users').row(6)).click();
    var inputs = element.all(by.css('.form-control.validated')).each(function(element,index){
        element.sendKeys('Test answer');
      });
//click submit
    element(by.id('submit')).click().then(function(){
//confirm sweetalert
          expect(element(by.css('.confirm')).getText()).toMatch('add');
          element(by.css('.confirm')).click().then(function(){
          //$http.post shoudl be called after confirming
        });
      });
  });
});
```
after confirming sweetalert this function shoudl be called
```javascript
this.saveConv = function(conv) {
			return $http.post('/conv', conv);
		};
```
but it looks like its not being called, test just ends and thats all, but if i add browser.pause before clicking on '.confirm' button $http.post is being called and i can see confirmation sweetalert that conversation has been added, how to fore protractor to invoke my $http.post?

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
