### ISSUE TITLE
Cannot read property 'split' of undefined even if the test pass

### ISSUE THREAD

**Issue by alecha** [angular/protractor#2549]
I've a simple test:

    it('should see an error when you visit the page with an invalid request id', function() {
        browser.get('my_url);
        expect(element(by.id('alert-error')).isPresent()).toEqual(true);
        expect(element(by.id('alert-ok')).isPresent()).toEqual(false);
    });

The error I get is the following one:
`Cannot read property \'split\' of undefined`

when I call `isPresent()`

Any of you had the same issue? The test is running fine (I mean that the result is the expected one) but this error should not occurr.

Some other info: in the page I'm using Angular JS and on the viewContentLoaded I made an async call that will show one of the two elements I'm testing.

**Comment by sjelin** [comment]
Is there a stacktrace?

**Comment by alecha** [comment]
Nope, the exception's cause is "undefined", I've also tried to pause the browser but in the console any errors is shown

**Comment by alecha** [comment]
I've found the issue, it was an external library that causes the error, it wasn't a protactor issue : I'll close the issue, thanks!
