### ISSUE TITLE
Protractor is not going inside then function when UI has more than one element with same text.

### ISSUE THREAD

**Issue by AkshayNepalia** [angular/protractor#2552]
element.all((by.xpath("//*[contains(text(),'some text')]"))).then(function(arr) {
           arr[0].click();
        })

I am trying to access 1st array element with text 'some text'

But it looks like protractor is not going inside then function loop.

I am trying to click on highlighted tr.
There are more than 90 tr and not sure how to access and click a tr at array index 30.

Tried using text() method but it looks like protractor is not going inside then function for text() method.
element.all((by.xpath("//*[contains(text(),'some text')]"))).then(function(arr) {
arr[0].click();
})

![](https://cloud.githubusercontent.com/assets/13796495/10155548/5fea167c-6694-11e5-9b18-bc3761fc4688.png)
<img width="924" alt="screen shot 2015-09-29 at 10 24 26 am" src="https://cloud.githubusercontent.com/assets/13796495/10155612/047ded44-6695-11e5-9f4b-7ba83b5baca2.png">

**Comment by AkshayNepalia** [comment]
<img width="924" alt="screen shot 2015-09-29 at 10 24 26 am" src="https://cloud.githubusercontent.com/assets/13796495/10155548/5fea167c-6694-11e5-9b18-bc3761fc4688.png">

I am trying to click on highlighted <tr>
There are more than 90 <tr> and not sure how to access and click a <tr> at array index 30.

Tried using text() method but it looks like protractor is not going inside then function for text() menthod.
element.all((by.xpath("//*[contains(text(),'some text')]"))).then(function(arr) {
arr[0].click();
})

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
