### ISSUE TITLE
Feature Request: Modularize webdriver-manager

### ISSUE THREAD

**Issue by donaldpipowitch** [angular/protractor#2556]
It would be really nice if `webdriver-manager` could be its own module. It is useful for any framework using `selenium-webdriver` or if you use `selenium-webdriver` without any framework.

**Comment by NickTomlin** [comment]
This is a great suggestion! I'm going to go ahead and close this so can consolidate efforts at #607. Please re-open if you feel that doesn't quite cover your suggestion. Thanks!
