### ISSUE TITLE
How can i call the "it" function of one file from another file

### ISSUE THREAD

**Issue by anuvratashu** [angular/protractor#2557]
there are some methods written in 1 file which needs to run after few functions of another file is executed. 
How this can be achieved?

Is there any way i can call the "It" function of say file "A" from file "B" ??

**Comment by juliemr** [comment]
You can't call an `it` function from another file, but you can split it into a helper file. Protractor test scripts are run with node, so then just `require('my-helper-file.js')`.


Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
