### ISSUE TITLE
Interactive Tests via client sometimes hang after webdriverjs 2.47.1

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2560]
Update to selenium-webdriver 2.47.1 occasionally causes elementexplorer to crash when tested with the client (e.g. interactive tests):

```
> node scripts/interactive_tests/interactive_test.js

/Users/ralphj/protractor/node_modules/q/q.js:126
                    throw e;
                    ^
Command <"browser.get(\"http://localhost:8081\")"> did not receive a response in 10s.
```

I am unable to reproduce when running with element explorer manually, so I do not believe this should be an issue for users. 

@hankduan ccing in case you have any ideas.

**Comment by al0p** [comment]
Hey Julie. 

My apologies to use this channel to contact you, but i don't find your e-mail.

I would love to contribute to Protractor. I'm an product designer and o think i can build an very nice new website for the Protractor. :)

What do you think? How could I help?

Thank you.  :)

**Comment by hankduan** [comment]
Can you see if 2.48.x fixes it for you? I ran `npm test` a few times and never encountered this.

**Comment by juliemr** [comment]
Yup, as far as I can tell it's fixed. Closing.
