### ISSUE TITLE
Unable to pass '--specs' argument to the command line

### ISSUE THREAD

**Issue by Alexa905** [angular/protractor#2572]
This issue is related to https://github.com/angular/protractor/issues/2413
I need to pass 'specs' array using grunt-protractor-runner. It looks like 
```javascript
    grunt.config('protractor', {
        options: {
            configFile: './resources/protractor.conf.js',
            keepAlive: false,
            noColor: false,
            webdriverManagerUpdate:true
        },
        test: {
            options: {
                args: {
                    specs:[ 'src/**/*.e2e.js' ]
                }
            }
        }
    });
```
But I have an error: 
```javascript
WARNING - pattern D:\projects\assets\src\**\*.e2e.js did not match any files.
D:\projects\assets\node_modules\grunt-protractor-runner\node_modules\protractor\node_modules\q\q.js:126
[launcher] Process exited with error code 1
                    throw e;
                          ^
Error: Spec patterns did not match any files.
    at Runner.run (D:\projects\assets\node_modules\grunt-protractor-runner\node_modules\protractor\lib\runner.js:249:11)
```
But the pattern is correct, it works good in protractor.config.js. 
Debugging I found that in cli.js `processFilePatterns_` method make concatenation the pattern with process.cwd() (I get 'D:\projects\assets\src\**\*.e2e.js') and after that ` ConfigParser.resolveFilePatterns`  make wrong parse string `fileName = patterns[i].split(':')[0]` 
And I get this: `fileName = D;
lineNumber = \projects\assets\src\**\*.e2e.js;
matches = [];`

**Comment by NickTomlin** [comment]
This is because of [2551](https://github.com/angular/protractor/issues/2551). I have a fix pr'd [here](https://github.com/angular/protractor/pull/2564); since you are the actual use case it would be wonderful if you'd try it out to make sure it is working for you.

**Comment by Alexa905** [comment]
I tried it on Windows and I confirm that this fix works, thank you! Maybe do you know how soon is possible to view this fix on release?

**Comment by juliemr** [comment]
It'll be out in our next release - you can check the 2.5 milestone https://github.com/angular/protractor/milestones/2.5 for our progress on that!
