### ISSUE TITLE
restartBrowserBetweenTests not working on iOS 9.0.2

### ISSUE THREAD

**Issue by dpalou** [angular/protractor#2573]
I'm using Appium and Protractor to implement e2e testing of a hybrid app. It works great in Android, but when I tried to test it in an iPad with iOS 9.0.2 I found out that the setting restartBrowserBetweenTests did nothing.

We want to restart the browser between tests to get rid of all the changes performed during the test. This bool works great on Android, but in iOS 9.0.2 all the data is still there (WebSQL).

This is my config file:

> exports.config = {
>     "framework":"jasmine2",
>     "specs":["../../e2e/_.js","../../www/__/e2e/_.spec.js"],
>     "capabilities":{
>         "app":"{SOME PATH}/MyApp.ipa",
>         "browserName":"iOS",
>         "platformName":"iOS",
>         "platformVersion":"9.0.2",
>         "deviceName":"iOS Device",
>        "udid":"{iPad UUID}",
>         "autoWebview":true,
>         "autoWebviewTimeout":10000
>     },
>     "restartBrowserBetweenTests":true,
>     "onPrepare":function(){
>         var wd = require('wd'),
>         protractor = require('protractor'),
>         wdBridge = require('wd-bridge')(protractor, wd);
>         wdBridge.initFromProtractor(exports.config);
>   },
>   "plugins":[{
>         "path":"../../e2e/plugins/wait_for_transitions.js"
>     }],
>     "seleniumAddress":"http://127.0.0.1:4723/wd/hub"
> };

**Comment by szikszail** [comment]
Hi,

I think my experience could be the same issue.
I am using the restartBrowserBetweenTests:true configuration to restart the browser between features, the browser window is closing but won't open again.

I am using Win7, Cucumber with Chrome and IE, both the same. The IEDriverServer process ends, but no new process starts.

**Comment by szikszail** [comment]
Hi

It works for me now ;)

**Comment by mgiambalvo** [comment]
Closing as obsolete. We did have some issues with restartBrowserBetweenTests this year, but everything should be fine in the latest Protractor 4.x
