### ISSUE TITLE
Suggestions on a test framework/runner for Angularjs protractor test with API tests 

### ISSUE THREAD

**Issue by testtolearn1** [angular/protractor#2580]
Hi I am writing testcases to test a website built in angularjs .I want to test frontend as well as API endpoints . I am using protractor to test the angularjs based frontend  and have given a  try on frisby which is a REST API testing framework built on node.js and jasmine. 

Can protractor suggest me a system /test framework / runner which would help me to manage the testsuites (group wise or dependency wise ) and run both protractor + frisby tests using the same CLI

**Comment by sjelin** [comment]
Sorry, we don't have any suggestions.  Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions
