### ISSUE TITLE
thenCatch is not available on promise of an element click

### ISSUE THREAD

**Issue by ZolSzi** [angular/protractor#2582]
It used to be available after calling click on an element until the March 16th commit (34f0eebd7e73b10e9b990caa06b63b6fd22b2589)

It is part of the webdriver Promise API, so I think it should still be available.

It used to work like this:
<code>
element(by.id("id1")).click().thenCatch(function(){
    ...
});
</code>

**Comment by sjelin** [comment]
@juliemr This is also you

**Comment by ZolSzi** [comment]
May I ask why this is flagged as a feature request? This is something that used to work and then it broke: backward compatibility was not kept between the changes. Sounds more like a bug to me.

**Comment by juliemr** [comment]
@ZolSzi sure - I categorize this as a feature request because `thenCatch` was never documented in our API or captured in our tests. This is distinct from `ElementFinder.prototype.then` which has always had docs and tests.

**Comment by ZolSzi** [comment]
@juliemr Fair enough, thanks!

**Comment by stalniy** [comment]
the same issue described in #2532

**Comment by juliemr** [comment]
`thenCatch` is deprecated from selenium-webdriver, closing this as stale. https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md

**Comment by caseyhoward** [comment]
The type definitions seem to be out of date, so I can't use this with typescript without doing something terrible like casting to <any>. Do I have to use typings instead of tsd? Is there some other way to use this that I don't know about.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/selenium-webdriver/selenium-webdriver.d.ts#L1226

**Comment by juliemr** [comment]
We're in the process of trying to update the typings - see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11233
