### ISSUE TITLE
Jasmine custom matchers with a Protractor/WebDriverJS element

### ISSUE THREAD

**Issue by prbaron** [angular/protractor#2584]
Hello fellow developers,

I would like to create my own custom matcher based on a Protractor/WebDriverJS element. Is anybody able to improve my current code ?

Here is what I would like to write in the specs files
```
var button = element(by.tagName('button'))
expect(button).toBeEnabled();
```

So here is my custom Jasmine matcher : 
```
'use strict';

function matcher(util, customEqualityTesters) {
  return {
    compare : function (actual, expected) {
      var result = {};
      
      expect(actual.isEnabled()).toBeTruthy()

      result.pass = true;

      if (result.pass) {
        result.message = 'Expected element to be disabled';
      }
      else {
        result.message = 'Expected element to be enabled';
      }

      return result;
    }
  };
}
module.exports = matcher;
```
Is there a better way to write it ? Because at the moment, if I have an error, I have the following message : `Expected false to be true`. However I would like to get `Expected element to be enabled`.

Thank you for your help.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
