### ISSUE TITLE
navigate().back() ---iteration

### ISSUE THREAD

**Issue by Ravi220** [angular/protractor#2585]
Protractor tool is new to me, could you please help me with the following.

How to iterate through browser.navigate().back()??

I have a page to automate where I need to click on all the links in home page, and then go back to the home page to click on the remaining links.

For time being I derived like the following:

HomePage.HomegMenuItem.click();
HomePage.reference.click();
browser.navigate().back();
HomePage.machine.click();
browser.navigate().back();
HomePage.connectivity.click();
browser.navigate().back();

Homepage and other var's are declared in page objects.

Thanks!!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
