### ISSUE TITLE
webdriver-manager update browser options don't work with "false"

### ISSUE THREAD

**Issue by bgrohman** [angular/protractor#2587]
If you want to turn off the update for one of the drivers (e.g. "chrome"), you can't pass "false" for the command line option. The reason can be seen here: https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L315.

The if statements checking for the driver options don't handle the case when the option value is the string "false". Since "false" is truthy, it treats it as though it's being explicitly turned on.

So this command works for turning off chrome:

```
webdriver-manager update --chrome=0
```

but this command does not:

```
webdriver-manager update --chrome=false
```

It seems like setting an option to "false" should be treated as turning it off, especially given that the CLI help message says the defaults for those options are either "true" or "false" respectively.

**Comment by juliemr** [comment]
This is the way that the `optimist` package parses command line args. I agree that it's somewhat annoying, but I think it's better to go with the standard than implementing our own custom logic here. We can fix the CLI help message though.

**Comment by bgrohman** [comment]
Ok, thanks. FYI, the Optimist docs claim to support booleans: https://github.com/substack/node-optimist#and-booleans-both-long-and-short-and-grouped.

**Comment by juliemr** [comment]
Optimist supports booleans, but not with the string 'false'. See https://github.com/substack/node-optimist#negate-fields and https://github.com/substack/node-optimist#booleankey

**Comment by bgrohman** [comment]
Ok, cool. The option from your first link seems like it would work nicely here.

**Comment by hankduan** [comment]
doc is added: https://github.com/angular/protractor/commit/502eb4f2b986772260c2d81bbe4f89b560c0598e
