### ISSUE TITLE
Latest release requires node v0.12 with 'no method 'parse''

### ISSUE THREAD

**Issue by scriby** [angular/protractor#2588]
The latest release (2.5.0) calls path.parse in configParser.js and that function does not exist in node versions prior to v0.12.

I don't see anything that indicates protractor requires v0.12, so I'm wondering if this was just an accident.

**Comment by hughes** [comment]
That would explain this...

```
TypeError: Object #<Object> has no method 'parse'
    at Function.ConfigParser.resolveFilePatterns (/path/node_modules/protractor/lib/configParser.js:102:29)
```

**Comment by hughes** [comment]
I guess one could argue that node < 0.12 hasn't been supported since [1.8.0](https://github.com/angular/protractor/commit/e6896138c58fc1096baf942bd2f1d67568442967)

**Comment by scriby** [comment]
I think if they wanted to make a version requirement explicit it would be set as the engine in package.json

**Comment by sjelin** [comment]
Working on this now

**Comment by NickTomlin** [comment]
Apologies for introducing this and not testing against 10.x, thanks for the fix @sjelin!

**Comment by forbesjo** [comment]
Nice to see that this is already being worked on!

**Comment by hughes** [comment]
Any chance in 0.10 being re-added to the travis build targets? Would help safeguard against this.

**Comment by juliemr** [comment]
@hughes that's done in https://github.com/angular/protractor/pull/2591/files
