### ISSUE TITLE
   Failed: Cannot read property 'RETURN' of undefined

### ISSUE THREAD

**Issue by testtolearn1** [angular/protractor#2593]
I have a ajax dropdown list from which I have to select a option , I used following peice of code.
The error coming is :    Failed: Cannot read property 'RETURN' of undefined
I also tried ENTER in place of RETURN 

var item = element(By.css('ul.dropdown-menu > li:nth-child(3)'));
                    item.sendKeys(protractor.key.RETURN).then(function () {

**Comment by juliemr** [comment]
You want `Key` with a capital.
