### ISSUE TITLE
How to make Nodemailer work??

### ISSUE THREAD

**Issue by anuvratashu** [angular/protractor#2595]
I cannot figure out how to get nodemailer to work, I have inserted my credentials for gmail too and tried sending an email to myself but it did not send me anything and it did not err, so I am confused. It is possible that I am missing stuff from my code..

this is written in the Conf file of protractor

 onComplete: function () {
        var nodemailer = require("nodemailer");
        
        var smtpTransport = nodemailer.createTransport("SMTP", {
            host: 'smtp.companyemail.com',
            port: '110',
            auth: { user: 'anuvrat.singh@companyemail.com', pass: 'Systems@2015' },
            secureConnection: 'false',
            tls: { ciphers: 'SSLv3' }
        });

        console.log("SMTP Configured");

        smtpTransport.sendMail({
            from: "My Name <me@example.com>", // sender address
            to: "Your Name <you@example.com>", // comma separated list of receivers
            subject: "Hello ✔", // Subject line
            text: "Hello world ✔" // plaintext body
        }, function (error, response) {
           
            if (error) {
                console.log(error);
            } else {
                console.log("Message sent: " + response.message);
            }
        });

    },

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
Additionally, it sounds like this is a question for NodeMailer, not Protractor.
