### ISSUE TITLE
Changing the driver context to 'WEBVIEW'

### ISSUE THREAD

**Issue by jskrepnek** [angular/protractor#2601]
Hi,

I'm having trouble with the 'autowebview' appium capability.  I suspect it is a race condition between a slow emulator changing contexts and protractor sending commands only supported by a webview context.

What I'd like to do is manually set the context to WEBVIEW, in Protractor's onPrepare callback.

There are code snippets out there like the following:

````
    onPrepare: function () {
        var wd = require('wd'),
              wdBridge = require('wd-bridge')(protractor, wd),
               _ = require('underscore');
        
        wdBridge.initFromProtractor(exports.config);
        
        return wdBrowser.contexts().then(function (ctxs) {
            var webCtx = _(ctxs).find(function (ctx) {
                return ctx.match(/WEBVIEW/);
            });
            return wdBrowser.context(webCtx)
        });
    }
````

However, in my case 'wdBrowser.contexts' is undefined.  I've snooped around and can't find a reference to that function.  I see that it is a [https://github.com/admc/wd/blob/8058f745e273693ec12a6b81f54bb501c38261a4/lib/commands.js#L313](defined command in wd).

It's clearly defined by WebdriverIO, in it's [http://webdriver.io/api/appium/contexts.html](appium section).

Thanks for any help.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by jskrepnek** [comment]
Will do, thanks.
