### ISSUE TITLE
Unable to get browser logs from IE and chrome

### ISSUE THREAD

**Issue by axelssonHakan** [angular/protractor#2602]
Protractor: 2.2.0
Selenium: 2.47.1
InternetExplorerDriver (IA32): 2.47.0.0
ChromeDriver: 2.18

I'm running into problem when I try to get the browser logs using Selenium.

#### IE is crashing on the commands:
* browser.driver.manage().logs().getAvailableLogTypes()
* browser.driver.manage().logs().get( "browser" )

Error:
...\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:113
var template = new Error(this.message)

#### Chrome is returning an empty array for:
* browser.driver.manage().logs().get( "browser" )

**Comment by sjelin** [comment]
In terms of IE, can you give a longer stack trace?

In terms of chrome, I don't know what your problem is.  We use exactly the same command in our [console plugin](https://github.com/angular/protractor/blob/master/plugins/console/index.js#L28) and it works fine.

**Comment by axelssonHakan** [comment]
Tried with some more testing and had some progress :)

spec-file
```
describe("protractor/webdriver", function() {
	it("should be able to get browser logs", function() {
		browser.get("https://angularjs.org");

		browser.executeScript("console.log('Nothing to see here - move along.')");
		browser.executeScript("console.warn('This is your first warning!')");
		browser.executeScript("console.error('This is serious!!!')");

		browser.driver.manage().logs().get( "browser" ).then(function( log ) {
			console.log( log );
		});

	});
});
```

protractor conf
```
exports.config = {
  seleniumAddress: "http://localhost:8999/wd/hub",
  specs: ["logs.spec.js"],
	multiCapabilities: [{
		"browserName": "chrome",
		"loggingPrefs": {"browser": "SEVERE"}	//OFF, SEVERE, WARNING, INFO, DEBUG, ALL
	}, {
		"browserName": "firefox",
		"loggingPrefs": {"browser": "SEVERE"}	//OFF, SEVERE, WARNING, INFO, DEBUG, ALL
	}, {
		"browserName": "internet explorer"
		// "level": "INFO",
		// "loggingPrefs": {"browser": "ALL"}
	}]
};
```

### Result:
* INTERNET EXPLORER - Failing directly (how should the log level be set for IE?)
* CHROME - getting the errors nicely
* FIREFOX - returns an empty array

If I change log level for Firefox to WARNING I'm getting a lot of WARNING but NO SEVERE
If I change log level for Firefox to ERROR I'm getting the same error as for IE

**Comment by sjelin** [comment]
Tbh these are features made by the selenium team directly and you'd be best off asking them

**Comment by axelssonHakan** [comment]
Feedback from selenium team:
https://github.com/SeleniumHQ/selenium/issues/468

The IE driver does not support getting logs of any kind. Those commands have not been implemented. They will be implemented only when the server-side API is properly specified.
