### ISSUE TITLE
Any upcoming changes to protractor?

### ISSUE THREAD

**Issue by illninofan** [angular/protractor#2604]
Hi @juliemr 

Hope your doing well

Sorry if i've posted this in the wrong section, as it's not really an issues, more of an enquiry really.

Are there any upcoming changes to Protractor, that need to be aware of such as changes to internal methods, such as element(by.click(...)) being deprecated and the ptor object now deprecated in favour of the browser object instead.

Is there any way to keep up to date with any changes with methods etc, so we can stay one step ahead in our automated tests

Thanks

Umar

**Comment by NickTomlin** [comment]
Hi there, 

The issues queue is for issues, so this question is a better fit for the [gitter](https://gitter.im/angular/protractor) channel or the angular google group. 

The [CHANGELOG](https://github.com/angular/protractor/blob/master/CHANGELOG.md) is the best source of information regarding changes. As for upcoming issues you could peruse the issues queue for issues with the [feature-request](https://github.com/angular/protractor/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature+request%22) label and see which ones have been road mapped.

**Comment by sjelin** [comment]
In addition to Nick's advice, I'd like to say that we try to avoid changes that will break many users' tests, and if we do we'll update the major version number (e.g. 2.x -> 3.x).  Even if a change breaks a small number of users, we might postpone it until a major version change (or at the very least update the minor version, 2.4.x -> 2.5.x).
