### ISSUE TITLE
When using seleniumServerJar option to run server, server runs on explicit ip address instead of localhost

### ISSUE THREAD

**Issue by cdanielsen** [angular/protractor#2605]
(Using protractor version 1.6.1)

When I launch a standalone selenium server on my local machine with webdriver-manager, it does so at the address `http://localhost:4444/wd/hub` and my tests run fine. If I elect to have protractor launch and teardown the server by specifying the seleniumServerJar property in my config file, my tests timeout:
```
Error: Timed out waiting for the WebDriver server at http://<explicit ip address>:4443/wd/hub
    at Error (native)
    at onResponse (C:\Code\e2e-test-framework\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:87:66)
    at C:\Code\e2e-test-framework\node_modules\protractor\node_modules\selenium-webdriver\http\util.js:42:21
    at C:\Code\e2e-test-framework\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\http\http.js:96:5
    at ClientRequest.<anonymous> (C:\Code\e2e-test-framework\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:145:7)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)
```
I believe this timeout is due to firewall restrictions in my local setup, which I could investigate, but I'm wondering why protractor doesn't also use localhost as the selenium server address? Are there good reasons for the discrepancy?

**Comment by sjelin** [comment]
We use [an API](https://github.com/angular/protractor/blob/6ebc4c3f8b557a56e53e0a1622d1b44b59f5bc04/lib/driverProviders/local.js#L80) made my the [selenium team](https://github.com/SeleniumHQ/selenium), so you'd have to ask them.

**Comment by cdanielsen** [comment]
Fair enough; I guess I'm just confused as to why having protractor run the server versus running it manually with webdriver-manager results in different host addresses. Do they not do the same thing/use the same code?

**Comment by sjelin** [comment]
No, webdriver-manager starts the server by [executing a shell command](https://github.com/angular/protractor/blob/master/bin/webdriver-manager#L283), where as using the `seleniumServerJar` property uses [new require('selenium-webdriver/remote').SeleniumServer(...)](https://github.com/angular/protractor/blob/6ebc4c3f8b557a56e53e0a1622d1b44b59f5bc04/lib/driverProviders/local.js#L80)
