### ISSUE TITLE
Element is not clickable at point (x,y) other element would receive the click

### ISSUE THREAD

**Issue by moshicn** [angular/protractor#2606]
Hi
I have a protractor issue in which I try to click on a button and get the error of :
"Element is not clickable at point (x,y) other element would receive the click".
I have some css animation which makes slide-in and slide-out, so I guess that it tries to 
click on the div that didn't finish the slide-out, instead of clicking on the button.
I saw the same issue resolved on: https://github.com/angular/protractor/issues/1557,
I did the same, and even check isDisplayed before that, but I still get errors inconsistency - some times
it pass and some times it fails:

browser.wait(function() {
                return element(by.id('save')).isDisplayed();
            }, 10000).
            then(function() {
                var EC = protractor.ExpectedConditions;
                var button = element(by.id('save'));
                var isClickable = EC.elementToBeClickable(button);
                browser.wait(isClickable, 5000). //wait for an element to become clickable
                then(function() {
                        button.click();
                });
            });

I'll appreciate any help,
Thanks in advance !

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

As an aside, please properly format your code on issues, it makes it much easier to read and help :)

**Comment by moshicn** [comment]
OK, sorry, I removed.
Thanks.
