### ISSUE TITLE
.count() does not work after .map()

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2607]
It throws an exception `function is undefined` if I run following code:

```
elemnt.all('...).map().count()'
```

and it refers to count function.

I guess this is not the expected behaviour.

**Comment by konrad-garus** [comment]
I believe `map` returns a promise of an array (implemented with `webdriver.promise.all(list);`). That probably means you have to do something like:

```
element.all(...).map(...).then(function (mapped) {
    return mapped.length;
})
```

I haven't actually tested it, just typing off the top of my head.

By the way it sounds odd to need the combination in the first place. Why do you need it? Can you post more code? Maybe there is a better way to solve your case.

**Comment by sjelin** [comment]
Konrad is correct
