### ISSUE TITLE
Pass parameters from commandline while executing protractor test

### ISSUE THREAD

**Issue by sachin-qe** [angular/protractor#2608]
I want to execute the test where I can specify the browsername, environement name, suite name in execution command as follows
protractor conf.js browser=chrome env=staging suite=smoke

    Is that possible with Jasmine and Protractor and
    Can any one show me how to achieve that?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
