### ISSUE TITLE
Error while waiting for Protractor to sync with the page

### ISSUE THREAD

**Issue by Karpo72** [angular/protractor#2609]
Well I tried to get protractor run within my project, but what ever I do it seems not to work.
I have my ng-app attribute on the body element. I tried to set the rootElement in the config or within the test. As soon I run the a simple example test if fails (latest webdriver and protractor version):

essage:
```
[chrome #2]     Failed: Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.4.7/ng/test"
[chrome #2]   Stack:
[chrome #2]     Error: Failed: Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.4.7/ng/test"
[chrome #2]         at stack (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1482:17)
[chrome #2]         at buildExpectationResult (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1452:14)
[chrome #2]         at Spec.Env.expectationResultFactory (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:583:18)
[chrome #2]         at Spec.addExpectationResult (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:324:34)
[chrome #2]         at Env.fail (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:894:25)
[chrome #2]         at Function.next.fail (c:\Program Files\nodejs\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1806:19)
[chrome #2]         at c:\Program Files\nodejs\node_modules\protractor\node_modules\jasminewd2\index.js:101:16
[chrome #2]         at [object Object].promise.ControlFlow.runInFrame_ (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1877:20)
[chrome #2]         at [object Object].promise.Callback_.goog.defineClass.notify (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:2464:25)
[chrome #2]         at [object Object].promise.Promise.notify_ (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:563:12)
[chrome #2]         at Array.forEach (native)
[chrome #2]         at Object.goog.array.forEach (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\array\array.js:203:43)
[chrome #2]         at [object Object].promise.Promise.notifyAll_ (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:552:16)
[chrome #2]         at goog.async.run.processWorkQueue (c:\Program Files\nodejs\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:125:21)
[chrome #2]         at process._tickCallback (node.js:356:9)
```
This is my config:
```javascript

exports.config = {
  allScriptsTimeout: 11000,

  specs: [
    '*.js'
  ],

  capabilities: {
    'browserName': 'chrome'
  },
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  baseUrl: 'http://localhost:80/',



  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};

```
This is my simple test:
```javascript
describe('first test', function() {

    beforeEach(function() {
        browser.get('e2eTest.html#/hotelbooking');
        browser.sleep(10000);
    });


    it('Are advanced options available?', function() {

        expect(element(by.id('advanced-search-box')).isDisplayed()).toBeTruthy();
        element(by.id('advanced-search-box')).click();



    });
});

```

And this is my html:

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="initial-scale=1, maximum-scale=1">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta name="description" content="">
		<meta name="author" content="">
		<title></title>
		<script>
			var PROTELWBE5 = {
			settings: {
			   skin: 'skin-default-light',
			   type: 'wbe5', 
			   apiKey: '4008771f-5fb9-4c2d-90d7-6b9a7519c277',
			   apiPath: 'https://connect.protel.net',
			   apiVersion: '/wbe/1/',
			   elementIdToRenderApp: "bodycontainer",
			}
		 };
		</script>


		<script  src="https://connect.protel.net/files/source/wbe5/apps/wbe5/app.min.js"></script>

	</head>
	<body id="bodycontainer" ng-app="WBE5App" ng-view="WBE5App" >

	</body>
 </html>

```

**Comment by NickTomlin** [comment]
This question might be a better fit for StackOverflow unless we can get a generic reproducible case (I can't run your application in order to test this).

That said, here are a few things to try that may help troubleshoot: 

- Move your `sleep` or wait inside the `it` block
- Use `browser.wait` with a condition instead of `browser.sleep`
- Bump the timeout for `getPageTimeout` in your protractor config
- Place `ng-view` on a child element body (having `ng-view` and `ng-app` on the same element can sometimes lead to strange behavior)

If you can't reproduce with an isolated example, e.g. modifying [example spec](https://github.com/angular/protractor/blob/master/example/example_spec.js), please consider closing this issue and referring to the  [Gitter Channel](https://gitter.im/angular/protractor) or [StackOverflow](http://stackoverflow.com/questions/ask?tags=protractor) to get debugging help.

**Comment by sjelin** [comment]
I'm confused.  Where is angular being loaded into your page?  It doesn't seem like `script  src="https://connect.protel.net/files/source/wbe5/apps/wbe5/app.min.js"></script>` contains angular

**Comment by NickTomlin** [comment]
Great question @sjelin.  It looks like there's `protelAngularModuleLoader.js` that gets appended from within `app.min.js` but I can't verify if it actually does anything :|

**Comment by Karpo72** [comment]
@sjelin @NickTomlin  The app.min contains a preloader script which loads the main script. This is because I've to do some API Requests, before the app gets initialized by angular. The app.min loads a app.Content.min. The app.content.min contains angualr and all other used angular resources.

**Comment by Karpo72** [comment]
In one chrome plugin for example I can see that it is calling angular.element(document.querySelector('[ng-app],[data-ng-app]')).injector().get. Does protractor use the same mechanism? in case of the plugin this line get's executed before angular is loaded. Might it be that protracor has a similar problem? But the time out within the protractor.conf should work in this case.

**Comment by Karpo72** [comment]
@sjelin  @NickTomlin  Ok..I'll close that now because found the reason. My app includes a angular module which is calle angular-facebook. It implements the Facebook API. This module loads the facebook sdk and create a fb_root element, which is a div within the ng-app container. it seems the protractor sync was failing because of that issues.

From my point of view as a developer I have to say that it would be great if protractor in future could raise errors that are more detailed to find this kind of issues. Especially if a app includes other 3rd party SDK's it might be that some DOM Elements get manipulated or changed. This should'nt break any Tests. Todays apps may contain 3rd party content. This content isn't part of the tests, but it get's loaded in a final app.

**Comment by NickTomlin** [comment]
@Karpo72 Thanks for updating; that's an interesting issue. A PR with changes to improve error handling would be very welcome!

**Comment by reddynr** [comment]
@ NickTomlin,

I am running a example on protractor getting below error. Could you please advice. Thank you

error:

goog.global.setTimeout(function() { throw exception; }, 0);
^
Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.4.7/ng/test"

here is my code

describe('My App testing', function() {

      browser.get('http://localhost:port/integrated/myWeb.html').then(function() {


    browser.wait(function() {
        return browser.getCurrentUrl().then(function(url) {
            return 'http://localhost:port/integrated/myWeb.html';

            element(by.model('ctrl.formData.emailAddress')).sendKeys('').clear();
            element(by.model('ctrl.formData.emailAddress')).sendKeys('reddynr@abc.com');
            element(by.model('ctrl.formData.emailAddress')).getAttribute('value').then(function (value) {
                expect(value).toEqual('nancy@abc.com');
            });

        });
    }, 10000);
});

**Comment by reddynr** [comment]
@ NickTomlin,

Thank you so  much.

My problem solved by adding ng-app tag in html main page.
