### ISSUE TITLE
run the same suite 2 times with different params

### ISSUE THREAD

**Issue by NourSammour** [angular/protractor#2612]
is there way to merge 2 commands into 1 command
- `protractor protractor.conf --suite create_buyer --params.buyerName=Buyer1`
- `protractor protractor.conf --suite create_buyer --params.buyerName=Buyer2`

like

- `protractor protractor.conf --suite create_buyer,create_buyer --params.suites[0].buyerName=Buyer1 --params.suites[1].buyerName=Buyer2`

to make this commad work i need to know the current suite index
is it possible?
may there is better way!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

The parsing of `--params` is very simplistic; you are just going to get a stringified version of whatever you pass in, so references to other elements in your params will need to parsed elsewhere (someone with more knowledge correct me if I am wrong). This seems like something that should either be handled at the shell level (in bash/PowerShell) or in the `onPrepare` block of your tests.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Params parsing is very simplistic, you are going to get a stringified version of whatever value you pass in. It seems like what you want to accomplish is better handled at the shell level or in in the `onPrepare` block of your config.
