### ISSUE TITLE
Mixing non angular and angular pages using protractor

### ISSUE THREAD

**Issue by seanryano** [angular/protractor#2614]
Hi,

  I am getting an error:

    Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window"

We have an application that uses both non angular pages (which I use selenium to get elements) and angular pages.

The following is my code.

conf.js

exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['test/testAngularJS.js']
} 

testAngularJS.js

describe('None Angular Page 1', function() {
    it('should add one and two', function() {
        browser.ignoreSynchronization = true;

        // I would have the url of test application here
        browser.get('http://**************************:8080/h2/index.do');
        // I would have my login details here
        element(by.id('username')).sendKeys('****************');
        element(by.id('password')).sendKeys('*****************');
        element(by.id('button_loginpage.button.login')).click();

        //expect(element(by.binding('latest')).getText()).
        //    toEqual('3'); // This is wrong!
    });
});

describe('None Angular Page 2', function() {
    it('should add one and two', function() {
        browser.executeScript("mainwindow.handle_action(\"ICENTER.showDemandProfile._._\");void(1)");
        browser.ignoreSynchronization = false;
    });
});

describe('Angular Page', function() {
    it('should add one and two', function() {
        element(by.model('filter.website')).sendKeys('Auto');

        element(by.buttonText("Filter")).click();
    });
});

The code fails in Angular Page function, I'm not sure its because I need to use a wait function for the angular page to be loaded or that it can't recognise angular.

I think also "browser.ignoreSynchronization = true;" might also have a effect.

Any help would be appreciated,

Sean

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Also, please properly format your code in issues to allow others to help you better. 

The official position on this is to use methods off `browser.driver` (stated in [this](https://github.com/angular/protractor/issues/51)) answer. These will avoid attempting to sync with angular before executing webdriver commands.

I've also had success transitioning from an angular to a non-angular page and back by using
 ```
// non-angular test code where ignoreSynchornization = true
browser
   .waitForAngular()
   .then(function () {
     // my angular test code
   });
```

**Comment by veerababu123** [comment]
Hai,This is my code:
describe('Protractor Demo App', function() {
 it('epicbeat sample test', function() {
       browser.ignoreSynchronization = true;
       browser.get('http://platepicbeat.staging.wpengine.com/epicbeat/explore');
       element(by.css('.e-login-btn')).click();
       element(by.id('e-open-email-auth')).click();
       element(by.id('email-sign-in')).sendKeys('test_track');
       element(by.id('password-sign-in')).sendKeys('pass@123');
       var input = $('.js-redirect');
       input.click();
       element(by.id('e-search-field')).click();
       element(by.id('e-search-field')).sendKeys('content marketing');
       element(by.id('submit')).click();
      });
    });
In that i am trying login and search something.
login page is non-angular page and after click the login,next page is angular
I am getting this error:window.angular is not defined
after click the login button suddenly close the window please help this issue

**Comment by krishaltruist** [comment]
Might be you have to check the synchronization

browser.ignoreSynchronization = false; needs to be included once the angular page included. 
That might help you.

**Comment by veerababu123** [comment]
these will be not working again showing same error

**Comment by junejie** [comment]
I have same problem. i dont know the solution. have you solved it?
