### ISSUE TITLE
How to run protractor tests using groups and tags

### ISSUE THREAD

**Issue by testtolearn1** [angular/protractor#2616]
Hi,

Please suggest how can I run protractor tests using groups and tags apart from suites.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
