### ISSUE TITLE
Update console plugin to optionally not print out warnings

### ISSUE THREAD

**Issue by paraplexed** [angular/protractor#2619]
In my setup we run 3 different browsers during CI, generally speaking each of them will print out separate errors. Instead of filling up the excludes array with errors I know are happening and not going to fix in the near future, I would rather just disable the logging of warnings during the build pipeline. This makes skimming through the already large logs somewhat easier.

I created a PR for it already here: #2618 

Thanks!

**Comment by hankduan** [comment]
Looks like it's already merged: https://github.com/angular/protractor/pull/2618
Closing..
