### ISSUE TITLE
Protractor in directConnect mode returns not null promise argument after click when use firefox browser

### ISSUE THREAD

**Issue by forward1387** [angular/protractor#2620]
**Version:**
```
npm ls protractor
└── protractor@2.5.1
```

In case of configuration 
```
directConnect: true,
capabilities: {
        'browserName': 'firefox'
}
```
 click for firefox browser(ex: element(by.css('any')).click();) returns promise which contains not null argument(callback).

**Note:** When use selenium standalone server, issue does not reproduced for firefox browser.

**Comment by hankduan** [comment]
Sorry can you clarify what this means?

`element(by.css(...)).click()` should be a promise which resolves when the element is clicked. What behavior are you seeing?

**Comment by juliemr** [comment]
I'm closing issues as stale. If there is still a reproducible problem, please open a new issue!
