### ISSUE TITLE
Is there a way to select textarea by its value? a sort of by.cssContainingText()

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2621]
Is there a way to select textarea by its value? 

A sort of `by.cssContainingText()`

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I haven't actually done this, but i'm surprised that `cssContainingText` does not actually work. You can always write a custom filter for your elements: 

```
element.all(by.css('textarea')).filter(function(elem, index) {
  return elem.getText().then(function(text) {
    return text === 'My text';
  });
}).then(function(filtered) {
  filtered[0].click();
});
```
