### ISSUE TITLE
Make decoration of $timeout optional

### ISSUE THREAD

**Issue by infinityfarm** [angular/protractor#2622]
Looks like commit https://github.com/angular/protractor/commit/6c10378b9a4e7cae9ba491a63ae11f942c833100 has protractor decorating $timeout.. however this breaks all of my tests if I also am decorating $timeout in my application.

**Comment by sjelin** [comment]
@juliemr @hankduan thoughts?

**Comment by juliemr** [comment]
@hankduan we should probably offer an option to turn this off. Leave it on by default, it will just work for most projects and make debugging much better.

**Comment by hankduan** [comment]
@infinityfarm Can you paste the error you see?

**Comment by hankduan** [comment]
See https://github.com/angular/protractor/pull/2624

**Comment by infinityfarm** [comment]
thanks @hankduan, @juliemr!

**Comment by hankduan** [comment]
@infinityfarm Can you do me a favor and patch the PR and see if it works for you? Also, can you paste the error you see. I want to update the FAQ so people know to use this flag.

**Comment by infinityfarm** [comment]
@hankduan The error I got was:
```bash 
TypeError: $timeout.opt is not a function
 ```
where 
```
$timeout.opt
``` 
is an extra method that I decorated $timeout with, and am using throughout my application.

I can confirm that the issue is solved by your PR https://github.com/hankduan/protractor/commit/c27a32e042841289bfeff30de1ef8aef9cea42fc, and adding 
```javascript
, untrackOutstandingTimeouts: true
```

to my protractor config.

**Comment by hankduan** [comment]
Thanks @infinityfarm. Added a comment about this in the FAQ in the PR.

**Comment by hankduan** [comment]
Will be released with next version!

**Comment by stalniy** [comment]
@hankduan  just a thought:
May something like `trackServices: [ '$http', '$timeout' ]` be more useful?

And in case of @infinityfarm he will just say `trackServices: [ '$http' ]`
