### ISSUE TITLE
Object has no method 'toEqual' 

### ISSUE THREAD

**Issue by smartdevj** [angular/protractor#2623]
Below is the following code that gets the text of the element and tries to compare it 

 element(by.css('a[href*="/resources"]')).getWebElement().then(function () {
            ResourcesTitle = element(by.css('a[href*="/resources"]')).getText();
            console.log(ResourcesTitle);
        });
  element(by.css('a[href*="/resources"]')).isPresent().then(function () {
            console.log('>>>>>>Text is in English');
            expect(ResourcesTitle.getText()).toEqual('Resources');

I get an error: TypeError: Object #<Assertion> has no method 'toEqual'

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Also, please format your code properly. It makes it a lot easier for others to help!
