### ISSUE TITLE
then is not available on promise of an element

### ISSUE THREAD

**Issue by mbarker62** [angular/protractor#2625]
I recently upgraded from protractor 1.6 to 2.5.1.  There is one construct in my existing code that isn't working.  It seems that you can't locate an element and immediately call ".then()".  The error is "undefined is not a function".  You can getText() of element and then call ".then()", but I want to pass the element into then(function(elem)).

If the option exists, then I want to select it and hit an add button, otherwise, do something else.  Is there a better way to do it now?  Is it a bug?

```javascript
element(by.id('userList')).all(by.tagName('option')).first().then(function(option) {
    option.click()   // select option
    element(by.id('addLdapUsers')).click();  // add selected option
    expect(element(by.id('notificationPanel')).getText()).toContain("1 user(s) scheduled for addition to the domain");
}, function(err) {
    console.log("No users found using " + wildcardUsername);
    // do something else
});
```

**Comment by sjelin** [comment]
It's true, `<element>.then` was removed in https://github.com/angular/protractor/commit/34f0eebd7e73b10e9b990caa06b63b6fd22b2589.  I believe, though I am occasionally confused about this one, that what you're looking for is [`<element>.isPresent`](http://www.protractortest.org/#/api?view=ElementFinder.prototype.isPresent)
