### ISSUE TITLE
Execution of test is not deterministic

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2632]
I have 2 test.

If I run only the second one, it passes successfully.

If I run them together, the second test fails.

I don't have a code to replicate it.

The second test clicks on an SVG. Basically where it fails is that the click on the SVG does not happen

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
