### ISSUE TITLE
Cucumber Support Broken

### ISSUE THREAD

**Issue by ayush** [angular/protractor#2634]
`lib/frameworks/cucumber.js` [references getFormatter()](https://github.com/angular/protractor/blob/0262268fa43b9eefac815d986740efa07bb15818/lib/frameworks/cucumber.js#L150) which seems to have been [removed from cucumber.js](https://github.com/cucumber/cucumber-js/commit/e4023994fcbfbcfb8c488570eeeaa9719669b7ab#diff-6df9c122966f15013b3c860ba9584a8eL8) and this results in protractor not working with latest (0.8.0+) cucumber.js

**Comment by NickTomlin** [comment]
I believe this is PR'd in [#2630](https://github.com/angular/protractor/pull/2630). As a cucumber user, your feedback would be very valuable on that PR.

**Comment by bmsoko** [comment]
@NickTomlin @ayush I've replaced the PR'd code into my local cucumber.js library, and seems that it's not working, I can see this:
![pr2630](https://cloud.githubusercontent.com/assets/3765964/10734255/13655b7e-7be1-11e5-9566-b0e2932cf0bc.png)

I've replaced the whole file! do I need to do something else?

Thanks!!

**Comment by darrinholst** [comment]
Can you try pulling in my revision locally instead of patching the file manually. From the stacktrace it appears that it's still picking up the old version of protractor.

``` package.json
  "protractor": "darrinholst/protractor#c437d756",
```

**Comment by Selenium-hari** [comment]
Hi,

I am also facing the same issue, below are the details
protractor ~2.5.1
cucumber ~ 0.9

exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',

    framework: 'cucumber',
    specs: [
        '/features/*.feature'
    ],

    cucumberOpts: {

        require: '/features/step_definitions/*.js',
        format: 'pretty'
    },
    capabilities: {
        'browserName': 'chrome'
    },

    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000
    }


};

Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
[launcher] Error: TypeError: undefined is not a function
    at /usr/local/lib/node_modules/protractor/lib/frameworks/cucumber.js:150:36
    at Function.promise (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:650:9)
    at /usr/local/lib/node_modules/protractor/lib/frameworks/cucumber.js:147:14
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)



Can some help be provided please

**Comment by darrinholst** [comment]
Yep, protractor support broke with [this commit](https://github.com/cucumber/cucumber-js/commit/c37d1ce98d43c43635d9898a90d9b72fe95189a4).

Also, there hasn't been a protractor release since the support was added for cucumber 0.8.0. So with protractor `~2.5.1` you'll need to use cucumber `~0.7.0`.

**Comment by sjelin** [comment]
We'll be releasing a separate npm module for cucumber support in 8.x soon, and you guys will be able to use that.

**Comment by ocrosby** [comment]
Can someone direct me to some information about how to get protractor working with cucumber since the removal of cucumber support in protractor?  It would be greatly appreciated.

**Comment by wlsf82** [comment]
Have you looked to the this documentation? https://github.com/mattfritz/protractor-cucumber-framework

**Comment by ocrosby** [comment]
Thank you, that's exactly what I was looking for. :D

**Comment by wlsf82** [comment]
;) https://github.com/mattfritz/protractor-cucumber-framework

**Comment by Sane-Joker** [comment]
I was able to fix the issue using a downgraded version of cucumber
