### ISSUE TITLE
element.click() randomly breaks, depending on what is queued to happen later

### ISSUE THREAD

**Issue by jonrimmer** [angular/protractor#2639]
I am very confused. I have a spec with code equivalent to:

```js
browser.setLocation('#/page1');
$('.project').click();
$('.module').click();

... lots more things
```

The second click call keeps failing, with Protractor saying the element ```.module``` element wasn't found. If I slow things down with ```sleep``` calls, the problem seems to be that the click on ```.project``` never happens, despite the element being present in the DOM.

If change it to the following...

```js
browser.setLocation('#/page1').then(() => {
  console.log('Navigated');
  return $('.project').click();
}).then(() => {
  console.log('Clicked');
  return $('.module').click();
});

... lots more things
```

...then ```Navigated``` is logged to the console, but ```Clicked``` isn't, and the test just waits, doing nothing until it times out. The ```click()``` call isn't erroring, it's just not happening, and never resolving its promise.

What is really weird is that if I alter the steps that come later, such as adding a ```browser.pause()``` right at the end of the spec, or commenting out random lines, then it starts working. But then when I add things back, or move them around, it stops working again. There doesn't seem to be any logic to what causes it to work or not.

Does anybody have any idea what would cause this insanity? I am absolutely at a loss to see why tasks queued to execute later in the control flow would cause ones earlier in it to start (or stop) working.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by jonrimmer** [comment]
@NickTomlin Is it? If a later step randomly breaks an earlier one, that seems like a bug, right?

**Comment by NickTomlin** [comment]
Without having something clearly reproducible this isn't an actionable issue. There could be any number of things going on in your application that could cause this. I'd prefer to do that troubleshooting in a medium that suits it (e.g. via chat or on SO). Once we've figure out that it definitely _is_ protractor and not a race condition or weird state in your application it's a great fit for an issue. 

I don't mean to be dismissive at all; it's just that i've encountered issues like this in my own applications and they are typically due to something unrelated to protractor. 

I see that you posted in Gitter; let's try to continue the discussion there and hone this down into an issue. Thanks!

**Comment by hankduan** [comment]
@jonrimmer I agree with @NickTomlin here.
I've never seen this behavior before. While it could possibly be a protractor issue, there is no way for me to reproduce this at the moment. Can you host your app or (preferably) a stripped down app that showcases this issue, or put it in a repo, and then open another issue with steps to reproduce this? Thanks!

**Comment by jonrimmer** [comment]
@NickTomlin @hankduan 

I have managed to create a simplified testcase that produces the problem, at least on my hardware:

https://github.com/jonrimmer/protractor-bug

Other members of my team have also apparently been experiencing the same problem while running tests. They are running Chrome and Firefox on Linux, rather than OS X, which suggests at the very least it isn't specific to the OS or browser version.
