### ISSUE TITLE
Test are not being shared between browsers in multicapabilities

### ISSUE THREAD

**Issue by spatchamatla** [angular/protractor#2640]
I got a test file which logs in as teacher and Student
```
describe('LoginTest :: User', function () {
    //For non angular websites
    var defaultSyncStatus = browser.ignoreSynchronization;
    //Navigate to Impersonate Page
    beforeEach(function () {
        browser.driver.manage().deleteAllCookies();
    });
    it('should be able to login as Teacher', function () {
        //for non angular Pages
        browser.ignoreSynchronization = true;
         //Login as Teacher
         loginPage.loginAsTeacher();
    });
    it('should be able to login as Student', function () {
        //for non angular Pages
        browser.ignoreSynchronization = true;
            //login as Student
            loginPage.loginAsStudent();
    });
})

```
and i got the config set as
```
  multiCapabilities : [
        {
            browserName : 'chrome',
            shardTestFiles: true,
            maxInstances: 2,
            //set the window size
            chromeOptions : {
                args : ['--lang=en', '--window-size=1024,768']
            }
        },
        {
            browserName : 'chrome',
            shardTestFiles: true,
            maxInstances: 2,
            //set the window size
            chromeOptions : {
                args : ['--lang=en', '--window-size=1024,768']
            }
        }
    ]
and 
 //To run Suites
    suites : {
        LoginTest : ['../test/e2e/loginPage/loginPage.spec.js'],
    },

```
Now when i run, instead of running two Tests in individual browsers both are being run on two browsers even if i set ``` shardTestFiles: true```

**Comment by NickTomlin** [comment]
I don't quite understand what you are trying to achieve here. You are setting chrome capabilities twice; which will cause your specs to be run twice. 

`shardTestFiles` shards the files for config, not individual tests within a file. To see sharding work properly you'll need to add another spec file to your `LoginTest` array.

Also, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by spatchamatla** [comment]
So, if the test wants share, they need to be separate spec?

**Comment by NickTomlin** [comment]
Let's continue this discussion via one of the mediums I listed earlier. It'd be great if you closed this issue as well.
