### ISSUE TITLE
Protractor 2.5.1 hangs when sending interaction to browser

### ISSUE THREAD

**Issue by mmmpie** [angular/protractor#2642]
This test runs in protractor 0.22 and angular 1.3,
protractor 2.5.1 and angular 1.3.18,
but not protractor 2.5.1 and angular 1.4.7.
Downgrading to protractor 2.4.0 works.

The test runs with `enableSynchronization = true`.

Protractor hangs when it gets to the `.click()` or the `.sendKeys()`.

```js
// It will fill the filter text box using model element.
elementUtility.model = function(modelName, inputValue) {
  return browser.wait(function() {
    return element(by.model(modelName));
  }, 2000)
  .then(function(modelInput) {
    modelInput.clear();
    return modelInput.sendKeys(inputValue);
  });
};
```

**Comment by hankduan** [comment]
`browser.wait` takes a function which returns true/false. `element(by.model(...))` should always be truthy, so your wait statement doesn't actually do anything. 

I think just
```javascript
var modelInput = element(by.model(modelName));
modelInput.clear();
modelInput.sendKeys(inputValue);
```
would suffice. 

Please follow up on stackoverflow as we would like to keep github for issues and bugs.
