### ISSUE TITLE
Remove jasmine1 for Protractor

### ISSUE THREAD

**Issue by hankduan** [angular/protractor#2645]
There is starting to be some confusion for users of Protractor with regard to jasmine1 and jasmine2. Let's just remove jasmine1 as an option for Protractor. This is a breaking change though, so opening this issue as a fyi that this is about to happen so people move off of jasmine1, and when we plan for the next breaking change (i.e. major version upgrade), we will remove jasmine1.

**Comment by sjelin** [comment]
+1

**Comment by juliemr** [comment]
Done now that 3.0 is out.
