### ISSUE TITLE
How to perform parallel testing in Protractor on Mobile devices

### ISSUE THREAD

**Issue by premkh9** [angular/protractor#2647]
How to perform parallel testing in Protractor on Mobile devices - 

Hi Team,

Currently I am using appium to execute my protractor tests in android device. I am not sure how to execute multiple instances in mobile devices. Can someone help me on that

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sjelin** [comment]
Also see http://www.protractortest.org/#/mobile-setup
