### ISSUE TITLE
Window offset can get information

### ISSUE THREAD

**Issue by ryanbowden** [angular/protractor#2649]
I am running a test where i click some navigation button,

I need to check the page scrolls down correctly. 

But i can get protractor to use the native window offset where you can see if a page has been scrolled.

Has anyway got an idea on how to do this?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
