### ISSUE TITLE
Upgrade to selenium-webdriver 2.48.1

### ISSUE THREAD

**Issue by jonrimmer** [angular/protractor#2651]
So, the problems I was describing in issue #2639 seemed to be a result of control flow bugs in selenium-webdriver. And the [changes from the latest 2.48.0 release](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md) mention a number of fixes related to Promises/A+ compliance and consistent execution order of the control flow:

> * FIXED: (Promise/A+ compliance) When a promise is rejected with a thenable, the promise adopts the thenable as its rejection reason instead of waiting for it to settle. The previous (incorrect) behavior was hidden by bugs in the promises-aplus-tests compliance test suite that were fixed in version 2.1.1.
>
> * FIXED: the webdriver.promise.ControlFlow now has a consistent execution order for tasks/callbacks scheduled in different turns of the JS event loop. Refer to the webdriver.promise documentation for more details.

I tested this theory by upgrading a local fork of Protractor to depend on 2.48.0 and trying my problematic tests. Sure enough, they ran without any problem.

I had hoped to submit a PR with the upgrade, but unfortunately, Protractor seems to have some compatibility issues with 2.48.0 when using the local Selenium driver. Running using the hosted or direct driver works fine for me, but the local driver exits immediately with:

```
[launcher] BUG: launcher exited with 1 tasks remaining
```

I've tried to work out what's going wrong, but I can't see anything obviously amiss. I'm hoping whatever is wrong might be more obvious to someone more familiar with node/protractor/selenium-webdriver?

**Comment by juliemr** [comment]
Yup, we need to do this upgrade - it will probably involve some pain and may involve incompatible changes to certain tests due to that second bullet point.

**Comment by NickTomlin** [comment]
@jonrimmer thanks for all your work investigating this! 
@hankduan Is there a way that I or others can help with the move to 2.48.0?

**Comment by hankduan** [comment]
Side note, should this really be 2.6 instead of 3.0? There will be breaking changes, and 2.48 no longer supports node 0.x.x

**Comment by hankduan** [comment]
Thanks @jonrimmer for looking into the root case!
@NickTomlin Thanks! I'll take a quick look at what's needed, but extra help is certainly appreciated to get Protractor compatible with 2.48.

**Comment by juliemr** [comment]
Feel free to bump to 3.0 if it's breaking changes (which it looks like it will be). We can kill Jasmine1 at the same time :)

**Comment by hankduan** [comment]
Alright, made a simple repo cases here: https://github.com/SeleniumHQ/selenium/issues/1207, which should be related to what we're seeing here with regard to Protractor getting stuck.

**Comment by hankduan** [comment]
@jonrimmer: side now...I haven't seen "[launcher] BUG: launcher exited with 1 tasks remaining" with webdriver 2.48, but I've encountered numerous test cases where they would get stuck

**Comment by jonrimmer** [comment]
@hankduan Weird. Are you definitely letting protractor start your selenium server within the test, rather than starting it manually via webdriver-manager? Also, I'm using node 4.1.2, in case that makes a difference.

**Comment by hankduan** [comment]
@jonrimmer: you're right. I was using a local server, so the problem never came up. 

-------
Summary: There are 2 issues with upgrading to webdriver 2.48
1) Control flow gets stuck in some very basic use cases (see https://github.com/SeleniumHQ/selenium/issues/1215). This is fixed and I've verified 2.48.1 does indeed solve this problem. 
2) Running a local server results in "[launcher] BUG: launcher exited with 1 tasks remaining". Root cause is described here: https://github.com/SeleniumHQ/selenium/issues/1215. Pending fix (Note, since the issue is with Selenium's remote server, everything works with directConnect and standalone/hosted server.)

Those are the only issues I saw so far, so we should be able to Protractor working with Selenium 2.48.x soon (fingers crossed)

**Comment by hankduan** [comment]
Update: I've applied the commit from https://github.com/SeleniumHQ/selenium/issues/1215#issuecomment-153251826, and this fixes issue 2, so webdriver 2.48.x is unblocked. Just pending for https://github.com/SeleniumHQ/selenium/issues/1215#issuecomment-153251826 to get into a release.

**Comment by hankduan** [comment]
https://github.com/angular/protractor/pull/2663

**Comment by juliemr** [comment]
Done now that 3.0 is out.
