### ISSUE TITLE
running protractor on Mac OS X El Capitan 

### ISSUE THREAD

**Issue by ramanbhati** [angular/protractor#2653]
I am having issues running protractor on Mac OS X El Capitan. I have installed selenium webdriver.

webdriver-manager update
webdriver-manager start
And I have already installed protractor globally and locally:

sudo npm install -g protractor

sudo npm install protractor

Selenium server is running already:

webdriver-manager start

When I run "protractor conf.js" I get tests failure.

Output:

Using the selenium server at http://localhost:4444/wd/hub [launcher] Running 1 instances of WebDriver

1) segment page encountered a declaration exception
Message:
TypeError: protractor.getInstance is not a function TypeError: browser.getInstance is not a function

2) page encountered a declaration exception Message: TypeError: by.selectedOption is not a function

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I believe you have already asked a [question](http://stackoverflow.com/q/33456000) on StackOverlow which has received some comments. Please continue the conversation there. Thanks!

**Comment by ramanbhati** [comment]
Thanks I am now able to run tests.
