### ISSUE TITLE
Custom matcher fails if used on a not-present element, more than two times (with failing specs)

### ISSUE THREAD

**Issue by tepez** [angular/protractor#2655]
I'm using custom matchers for my e2e specs, just like the [`toHaveText`](https://github.com/angular/protractor/blob/master/spec/basic/locators_spec.js#L15) matcher from protracor's specs.

I recently upgrades from 2.2.0 to 2.5.1 and many of my specs started failing. I also tried 2.5.0 and 2.4.0 but 2.3.0 is the latest version that works.

I've reduce the issue to a simple rule: If custom matchers are used on elements that not present, but only more than 2 times there will be a error.

I've created a failing spec here https://github.com/angular/protractor/pull/2654.

For example:

This works:
```js
it('should initialize with defaults', function() {
  // click a button to that opens a modal dialog, el1, el2 and el3 are not present 
  // until the modal is opened
    var modalPage = openModal();
    expect(modalPage.el1()).toHaveExactText('value 1');
    expect(modalPage.el2()).toHaveExactText('value 2');
  });
```

This also works:
```js
it('should initialize with defaults', function() {
    var modalPage = openModal();
    expect(modalPage.el2()).toHaveExactText('value 2');
    expect(modalPage.el3()).toHaveExactText('value 3');
  });
```

But this will not work:
```js
it('should initialize with defaults', function() {
    var modalPage = openModal();
    expect(modalPage.el2()).toHaveExactText('value 1');
    expect(modalPage.el2()).toHaveExactText('value 2');
    expect(modalPage.el3()).toHaveExactText('value 3');
  });
```

**Comment by juliemr** [comment]
Conversation is at https://github.com/angular/protractor/pull/2654. This appears to no longer be an issue with the latest master.
