### ISSUE TITLE
Protractor fails on non-existent test when using Mocha

### ISSUE THREAD

**Issue by joemckie** [angular/protractor#2656]
When running specs using Mocha, protractor is failing on a non-existent "after all" test.

```
Server
    #flux
      ✓ should make the ReactDOM attribute accessible to the window object
      ✓ should make the App attribute accessible to the window object
    1) "after all" hook for "should make the App attribute accessible to the window object"


  2 passing (3s)
  1 failing

  1) Server "after all" hook for "should make the App attribute accessible to the window object":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

#### Particulars:
- [flux_spec.js](https://gist.github.com/joemckie/f894aa7c15f98b121aef)
- [protractor.conf.js](https://gist.github.com/joemckie/fb922464b23eaa8b2195)
- [protractor_output.json](https://gist.github.com/joemckie/3dee6dd69a5e0aaa4738)

#### Versions:

- mocha: `2.3.3`
- protractor: `2.5.1`
- gulp-protractor: `1.0.0`
- node: `5.0.0`
- npm: `3.3.6`

I'm running the tests via gulp using `gulp-protractor`, but the same problem occurs when running via the command line.

**Comment by joemckie** [comment]
Just to update, I tried switching test frameworks and ended up coming back to protractor... Well, I've obviously set something up differently because now it works perfectly.

I'm going to close this for now, if it creeps up again, I'll re-open.

**Comment by NickTomlin** [comment]
@joemckie glad it worked out. Thanks for the update!
