### ISSUE TITLE
protractor ElementNotVisibleError

### ISSUE THREAD

**Issue by dotjose** [angular/protractor#2658]
Hi there, I've been working on a protractor and It really makes me crazy by finding this bug 'Error: ElementNotVisibleError' I used different syntax to locate the element and manipulate a click event but unfortunately none of them doesn't work. Here are the syntax I used and the html element that I need to refer.

[Uploading asshole.doc…]()

I used this different syntax to refer the above element
```js
 var btn = element(by.css('button.button.back-button.buttons.button- clear.header-item'));

btn.click(then(function(){


  // I do something with it here
});
```
```js
var btn = element(by.css('.back-button'));

btn.click(then(function(){
// Do something
});
```
```js
var btn=element(by.tagName('button'));
btn.click.then(function(){
 //do something...
});
```
I used this all but none of the works and raise the same problem ElementNotVisible Error but I see the element on the browser. Can anybody help me?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sjelin** [comment]
You haven't
