### ISSUE TITLE
Protractor returning wrong Platform/OS name when executed from local machine

### ISSUE THREAD

**Issue by YatheeshKumar** [angular/protractor#2669]
Hi,

To display the os name(on which test executes) in the final report we have used the following code in the Jasmine configuration file 
```js
var capsPromise = browser.getCapabilities();
capsPromise.then(function (caps) {          
            var osName = caps.caps_.platform;
            console.log(osName);
}
```
When the above code executes 
- OS is displayed as ‘XP’ when script runs in Chrome browser on Win 7 desktop
- OS is displayed as ‘Windows’ when script runs in Firefox browser on Win 7 desktop

Please let us know if we can do something to get the correct platform/os name. 

Thanks,
Yatheesh.

**Comment by sjelin** [comment]
I don't think there's anything you can do.  This looks like a selenium bug though, so I'd suggest making an issue on https://github.com/SeleniumHQ/selenium
