### ISSUE TITLE
Slim down repo size

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2674]
Low-hanging fruit:

 - don't include testapp in distribution
 - See if we can remove 'request'

**Comment by sjelin** [comment]
Other possibilities:

- Split plugins into separate repos
- Split frameworks separate repos

**Comment by sjelin** [comment]
Updates:

* testapp will be removed pending https://github.com/angular/protractor/pull/2687
* `request` will only be inside `webdriver-manager` pending https://github.com/angular/protractor/pull/2686.  At that point you'll probably be best suited to removed it from the package.
* Plugins have been made into separate repos and will be removed from Protractor core in https://github.com/angular/protractor/pull/2686
* I'll get cucumber into a separate repo eventually :stuck_out_tongue:

**Comment by juliemr** [comment]
Most of the work here is done, so I'm going to close this. Remaining big task: better way to cache the selenium jars. Let's follow that in https://github.com/angular/protractor/issues/2507
