### ISSUE TITLE
getCssValue doesn't return computed values for pseudo-elements

### ISSUE THREAD

**Issue by leonardoanalista** [angular/protractor#2675]
WebElement.prototype.getCssValue doesn't return computed values for pseudo-elements. 

HTML:
```
<span class="item">22.00</span>
```

CSS:
```
.item:before
  font-size: 12px
  content: '€'
```

Then look up on tests:
```
element.all(by.css('.item)).getCssValue('before')
```

- expected result: '€'
- actual result: always empty string.

Btw this `element.all(by.css('.item)).getCssValue('font-size')` works.

reference docs: http://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.getCssValue

**Comment by sjelin** [comment]
The issue is that `:before` is not a css property of `.item`, it's its own element.  What you'd need to do is select `.item:before` (not possible via webdriver) and look at the `content` property.

**Comment by leonardoanalista** [comment]
I got is done like this:
```
window.getComputedStyle( document.getElementsByClassName("item")[0] , ":before")
```
Thanks anyway

**Comment by manoj9788** [comment]
What do you get when you use element.all(by.css('.item)).getCssValue('content') ?

**Comment by leonardoanalista** [comment]
i get: 'none'

On 5 November 2015 at 12:46, Manoj Kumar <notifications@github.com> wrote:

> What do you get when you use
> element.all(by.css('.item)).getCssValue('content') ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/protractor/issues/2675#issuecomment-153927535>
> .
>



-- 


Leonardo Correa

**Comment by leonardoanalista** [comment]
`window.getComputedStyle` does return "computed style".

Maybe remove from documentation "computed style" as pseudo-elements are specified on stylesheets.

reference docs: http://angular.github.io/protractor/#/api?view=webdriver.WebElement.prototype.getCssValue

**Comment by manoj9788** [comment]
Sorry I deleted my question, since this was closed.
@sjelin  is right.

With WebDriver I have done like this before.
String script = "return window.getComputedStyle(document.querySelector('#validationError'),':before').getPropertyValue('content')";
JavascriptExecutor js = (JavascriptExecutor)driver;
String content = (String) js.executeScript(script); 

Print content or use where ever you want.

**Comment by leonardoanalista** [comment]
Thank you @manoj9788 I did similar way
cheers
Leonardo Correa

**Comment by manoj9788** [comment]
cheers!
