### ISSUE TITLE
Unable to configure webdriver-manager driver versions

### ISSUE THREAD

**Issue by OrsKardos** [angular/protractor#2679]
Hi there!

We would like to specify the driver version to the webdriver-manager as the browser type can be configured, so that we can run our tests with an older version if needed.
It seems that currently only the browsers are configurable from outside.

Code from the webdriver_update function of the webdriver-manager file:
```
if (options) {
        if (options.browsers) {
                options.browsers.forEach(function(element, index, array) {
                        args.push("--" + element);
                });
        }
}	
```

As observed the versions are taken from config.json of protractor's base directory
```
var versions = require('../config.json').webdriverVersions;
```

Is there a way or even a workaround to specify a version other than the newest, defined in this file?

Another problem we encountered: Currently the ie driver type (whether is Win32 or 64) is only based on the operating system on which the tests are running. It would be helpful to be able to download a 32-bit version of the IE driver on a 64-bit machine, since the 64-bit version is really slow compared with the 32-bit version. Is there any solution to this?

Thank you in advance for the answers!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I don't know of a way to manage versions as you want them. You should be able to download a 32 bit version of ie regardless of the os with the `--ie32` switch. Let's explore these more one of the mediums listed above. Thanks!
