### ISSUE TITLE
how to enable jasmine xml junit reports?

### ISSUE THREAD

**Issue by csarnevesht** [angular/protractor#268]
Hi there,

I'm trying to enable the jasmine xml junit reports.

I've seen that I can use the following in protractorConf.js:
  onPrepare: function() {
       jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter(
            'target/failsafe-reports', true, true));
  },

However, I'm getting an error indicating what appears to be jasmine being null?
Do i need to create a jasmine variable somewhere?  where?

**Comment by clexit** [comment]
The latest commit from this ticket seems to be on production, but the URL goes to 404 now.
