### ISSUE TITLE
How To Get Value of Select Element?

### ISSUE THREAD

**Issue by jasteph** [angular/protractor#2681]
I am trying to get the value of a select element.

I have tried element(by.id('select_id').$('option:selected').getText(), but I am getting an error that 'option:selected' is not a supported selector.

Thanks in advance!

**Comment by NickTomlin** [comment]
You should be able to use `option:checked`. 

That said, your question is better suited for StackOverflow or Gitter. If that does not help, lease [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor).

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by laughin1** [comment]
Ok thanks @NickTomlin very helpful! I apologize for not directing my question to the appropriate forum.

**Comment by jasteph** [comment]
Ok thanks @NickTomlin very helpful! I apologize for not directing my question to the appropriate forum.

**Comment by NickTomlin** [comment]
Not a problem at all :) just trying to keep the issue queue clean. If you wouldn't mind closing the issue that would be lovely. Thanks!

**Comment by pnstickne** [comment]
`option:checked` will not work in PhantomJS, as it is missing support for the `:checked` selector. However, what will work (fsvo) is:

```
var select = element(by.id('select_id'));
return select.getAttribute('value')
  .then(function (i) {
    return select.element(by.css('option[value="' + i + '"]')).getText();
});
