### ISSUE TITLE
protractor unable to locate element on non angular page

### ISSUE THREAD

**Issue by ProtHelp** [angular/protractor#2682]
describe('cct homepage',function(){
	it('should open the page with title',function()
	{ 
			browser.manage().timeouts().setScriptTimeout(60000);
			browser.pause(5000);
		    browser.ignoreSynchronization=true;
			browser.get("http://google.com",400000);
			browser.sleep(2000);
			element(by.id('q')).sendKeys('hi');
	});

protractor is unable to identify the element, can you help me and let me know what is the issue with my code

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
