### ISSUE TITLE
Finding array of elements from ui-grid fetch just visible rows

### ISSUE THREAD

**Issue by lisandro** [angular/protractor#2684]
Hello, I've worked with some tests that have to manage larger data (+60 rows) on a ui-grid. I have two ui-grid tables, one of them have infinite scroll and the other load all rows at the beginning.

I detected an issue present on getting *all* rows as an array of elements using _repeater_ as all locator, it's fetching just visible rows and some of hidden rows of current scroll view of list. 

I've modified the height of div that contains the rows and when we have more space and more rows are displayed, Protractor is getting more elements than before with less height.

Defect can be reproduced in this web http://ui-grid.info/docs/#/tutorial/190_large_dataset , with the following code : 

```
browser.get('http://ui-grid.info/docs/#/tutorial/190_large_dataset');

var rows = element.all(by.repeater('(rowRenderIndex, row) in rowContainer.renderedRows track by $index'));

rows.count().then(console.log);

rows.each(function(element, index) {
    element.getText().then(function (text) {
        console.log(index, text);
    });
});

```

Count: 18 rows
Display names until : Ann James

Protractor version : 2.5.1

Please let me know if someone can reproduce the same behavior. Thanks. 

Regards,

**Comment by NickTomlin** [comment]
I'm not very familiar with UI grid, but I believe it only renders enough items to fit within the grid container. If you inspect the demo you gave in your devtools you'll see a that the `.ui-grid-canvas` only has 18 child elements (until you start scrolling within it, which will pre-fetch some more slightly below the visible area of the container). 

I think Protractor/Webdriver are behaving as expected here; let us know if that is not the case.

**Comment by sjelin** [comment]
Yeah, this is working as it's supposed to.  There are 18 elements matched by that locator

**Comment by lisandro** [comment]
Yes, thank guys!. When you scroll down a bit more elements are added but then ui-grid just kept a static number of rows and it updates the values of bindings.

We should consider this issue with ui-grid library.

Regards

**Comment by Vovanchik** [comment]
Hello,

Do you have a solution how to fetch all data from ui-grid, because I have similar problem, but I don't know how to resolve it.

**Comment by rahulmr** [comment]
I am also having same issue where I want to validate the contents of all the rows. Does anyone know the solution or approach that should be followed?

**Comment by STProtractor** [comment]
Did Anyone get a solution to this issue? I am also facing the same thing, even though my grid has multiple elements on multiple pages, my protractor test just fetches the elements on the 1st page, does not take into consideration other pages of grid. Appreciate a help
