### ISSUE TITLE
Release new minor version

### ISSUE THREAD

**Issue by mattfritz** [angular/protractor#2689]
When is the next minor release scheduled? The current latest npm package does not support the latest cucumber.js (8.x) because report formatters are broken with their change to the cucumberOpts API.

I see there are potentially breaking changes with the removal of Jasmine 1.x support in master, but is there anything else preventing a minor release? Are we waiting on more issues to be fixed? I'd be glad to help with anything that is slated for the next release that is not yet completed.

**Comment by sjelin** [comment]
A minor release is possible, but currently `master` has already hit the breaking change that makes us want to switch to `3.x`.  Could you point to the commit you'd like a minor release at?

Also, we'll be splitting cucumber into a separate project soon, so that should help with these kinds of problems.

**Comment by mattfritz** [comment]
This is the commit that is critical to current cucumber functionality: https://github.com/angular/protractor/commit/451aa8869a1341d19b6f59326fa5fc3705c00385

Looks like it was merged before Jasmine 1.x removal. I'll take a look at the cucumber breakout ticket and see what I can contribute. Thanks!

**Comment by sjelin** [comment]
It looks like we're going to have to change the way the runner works to split cucumber out, so if someone wants to use Protractor 2.x and cucumber 8.x we'll need to do a minor version.  @juliemr, thoughts?

**Comment by juliemr** [comment]
To clarify: would a minor release of the repo at 451aa88 fix the cucumber issue? It looks like it's testing with cucumber 0.8.x at that point. Are there further issues?

**Comment by sjelin** [comment]
Yeah, a release there would fix the cucumber issue.

**Comment by juliemr** [comment]
Ok. We could cut a minor release at https://github.com/angular/protractor/commit/31d1b72aba8ec809195c12cb7cff3d3472c07ad1. (I don't think any of the features there warrant 2.6, let's do 2.5.2). 

@sjelin do you want to be release master?

**Comment by sjelin** [comment]
Actually, never mind.  Following up from your comment on https://github.com/angular/protractor/pull/2691/files#r44419463, we can remove the dependency on `ConfigParser` without changing the runner, so people who want to use cucumber 8.x with Protractor 2.x can just use the cucumber npm module (once we release it).  So a minor version isn't necessary
