### ISSUE TITLE
Protractor still hanging on "[launcher] Running 1 instances of WebDriver" (with xvfb)

### ISSUE THREAD

**Issue by PaddyMann** [angular/protractor#2697]
The issue #2419 still persists. I suggest reopening that issue to make it easy to review the comments.

**Comment by juliemr** [comment]
Just to be clear - @PaddyMann is this still when using xvfb?

**Comment by PaddyMann** [comment]
Yes - apologies for the missing detail @juliemr

**Comment by juliemr** [comment]
OK, reopening the old issue since it's still descriptive.
