### ISSUE TITLE
Size of screen

### ISSUE THREAD

**Issue by JohnnyEvo** [angular/protractor#2699]
I use this property to define the width and height's screen: 

        var width = 1280;
        var height = 600;
        browser.driver.manage().window().setSize(width, height);

In the method onPrepare() but this code is functional for somes tests, not for all of them. Why is that? I don't redefine the screen's size in my tests.

Regards,
Johnny

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by JohnnyEvo** [comment]
It's Ok, thank you :) 

http://stackoverflow.com/questions/33677458/protractor-size-of-screen
