### ISSUE TITLE
Restangular calls not working with Protractor? 

### ISSUE THREAD

**Issue by BaggioWong** [angular/protractor#2700]
I'm not entirely sure what's causing the issue, but it seems like Restangular calls aren't executing on the test server. 

What's strange is that a week ago, I wrote two tests and they were working just fine (I was on Yosemite on a Mac), but after upgrading to El Capitan, strange things happened. Long story short, they stopped working. 

Specifically, using the first test as an example, it's supposed to test the login feature. Everything worked fine up till the point when the submit button is supposed to be clicked. I tried manually clicking the button after browser.pause() (to keep the browser open), to no avail - this is the basis of me determining that Restangular calls are not executing properly. 

To add additional information about the environment, I'm using a proxy because services like Facebook are blocked here. 

Won't add specs here because I don't think it's something to do with the test specs, but will do so if further info is needed. 

Here's the code for the first test:

```javascript
  it("should log in", function() {
  	//	common variables
  	var expectedConditions = protractor.ExpectedConditions;

  	//	nav to homepage
    browser.get('http://127.0.0.1:9031/home');

    //	logs user out by default (this is implemented with local storage)
    browser.executeScript('window.sessionStorage.clear();');
    browser.executeScript('window.localStorage.clear();');

    //	logs in with test user account (without remember me)
    var testTeacherId = 163abji;
    var testUsername = testTeacherId@test.com; 
    var testPassword = "abcdef";

    //	wait until home page has loaded
    var signinButton = element(by.css('a.btn.btn-outline.btn-login[ui-sref=signin]'));
    browser.wait(expectedConditions.visibilityOf(signinButton), 5000);	
    	
    element(by.css('a.btn.btn-outline.btn-login[ui-sref=signin]')).click();	//	signin button
    
    //	wait until the signin page has loaded
    var usernameField = element(by.model('user.LOGIN_PA_USERNAME'));		//	username field
    var passwordField = element(by.model('user.LOGIN_PA_PASSWORD'));		//	password field
    var submitButton = element(by.css('button[type=submit]'));				//	submit button
    browser.wait(expectedConditions.visibilityOf(usernameField), 5000);		

    //  log in
    usernameField.sendKeys(testUsername);
    passwordField.sendKeys(testPassword);

    submitButton.click();

    //	wait until the dashboard page has loaded
    var avatarImg = element(by.css('img.mute.rounded'));
    browser.wait(expectedConditions.visibilityOf(avatarImg), 5000);
  });
```

The login service code is pretty straightforward - in the controller:

```javascript
.controller('AccountSigninCtrl', function ($scope, LoginService) {
    //  omitted for brevity
    $scope.login = function () {
      return LoginService.login($scope);
    }
    //  omitted for brevity
  })
```
And the login service

```javascript
  .service('LoginService', function ($rootScope, $modal, $state, $interval, $log, $q, Facebook, FBError,
                                     FacebookLoginNOEmailModal, FacebookLoginHasEmailModal, Account, UserService) {
    //  omitted for brevity
    this.login = function (ctrlScope) {
      ctrlScope.error = null;
      return UserService.login(ctrlScope.user, function (error) {
        ctrlScope.error = error;
      }, ctrlScope.curState).then(function (result) {
        if (result.curState) {
          ctrlScope.$close();
        }
        return result;
      }, function (error) {
        return error;
      });
    }
});
```

And in the UserService service

```javascript
.service('UserService', function ($rootScope, FullRestangular, $q, $state, $log, localStorageService, Finance) {
    //  omitted for brevity
this.login = function (user, errorCallback, curState) {
      /**
       *  Check if the "Remember Me" checkbox is checked, calculate the expiry date and
       *  save in LocalStorage.
       *
       *  If checked, expiry date = current time + 7 days
       *  If not, expiry date = current time + 1 day
       */
      var rememberMe = !!user["rememberMe"],
        expiryDate = new Date().getTime(),
        dayInMilliseconds = 1 * 24 * 60 * 60 * 1000;

      if (rememberMe) {
        expiryDate += (dayInMilliseconds * 7);
      }
      else {
        expiryDate += (dayInMilliseconds * 1);
      }

      localStorageService.set(KP.SERIALIZE.EXPIRY_DATE, expiryDate);
      return API.post(user).then(function (result) {
        result.curState = curState;
        _handlerResult(result);
        return result;
      }, function (error) {
        $log.debug('[user service] login fail', error);
        $rootScope.$broadcast('kp_account_login_fail', error);
        isFunction(errorCallback) ? errorCallback(error) : angular.noop();
        return error;
      });
    }
    //  omitted for brevity
});
```

For the second test, it's supposed to navigate to a page where a list of names are to be fetched and displayed, and to test that the returned array's length is 0. After loading the page, however, again on browser.pause(), it doesn't fetch anything. 

```javascript
describe("teacher list", function () {
  beforeEach(function () {
    browser.get('http://127.0.0.1:9031/teachers');
  });
  it("has teacher", function () {
    var teachers = element.all(by.repeater("teacher in items track by $index"));
    expect(teachers.count()).toBe(20);
    //teachers.first().then(function (teacher) {
    //  expect(teacher).not.toBeUndefined();
    //});

    browser.pause();
  })
});
```

(I'll omit the code for the second example for now since it's pretty much a Restangular call.)

If this was a generic angular issue, I imagine the console would have outputted "angular not found", but this doesn't seem to be the case here. 

Has anyone experienced a similar issue? And if you have, what's the possible causes and how did you resolve it? 

I'm almost wanted to shy away from posting it here, because Restangular is a popular module and I would think that someone must have already experienced this, but I didn't come up with a solution on a Google search. 

Any suggestions really appreciated - thanks!

**Comment by BaggioWong** [comment]
Google came up with a similar thread here, but with no responses: https://www.reddit.com/r/angularjs/comments/2ms018/how_to_use_restangular_in_protractor_for_e2e/. That's all I could find for now.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Also, when posting, please include what's actually going wrong - I can't tell from your post what the exact problem you're encountering is and what the expected behavior is.

**Comment by BaggioWong** [comment]
I understand - I'll update the question with clearer details. Thanks.

**Comment by BaggioWong** [comment]
Redirect to here: http://stackoverflow.com/questions/33822314/protractor-functions-not-running-ive-looked-through-configs-logs-etc.
