### ISSUE TITLE
How to handle Exceptions in protractor

### ISSUE THREAD

**Issue by Kothajagadeesh** [angular/protractor#2701]
Hi Julie,

I'm new to protractor, i've seen #543 and implemented the same in my framework. However, i'm seeing exception is thrown instead handle

Could you please tell me where i did wrong

this.safeType = function(locator,text,timeout){
    
   return browser.driver.controlFlow().execute(function(){
    return browser.driver.findElement(locator).then(function(ele){
      return ele.isDisplayed().then(function(yes){ 
        if (yes){
              ele.clear();
              ele.sendKeys(text);
              return true;
        }  else{ 
              return false;
        }
      },function(err){ //Exception promise
        return false;
      });  
    });
   }); 
 };

@juliemr

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
