### ISSUE TITLE
RFE: support local file paths in browser.get

### ISSUE THREAD

**Issue by radek-holy** [angular/protractor#2702]
There are JavaScript applications that does not require a web server to work. It would be nice if you could support opening files specified by their file names. As a workaround, one can convert file names to file:// URLs but AFAIK there is no reliable cross-platform library which is able to do that. And since it seems that all the major browsers are able to accept just file names, we can avoid the need to write such a library.

**Comment by NickTomlin** [comment]
This sounds like something that would be a great fit for a separate module or protractor plugin, but not for protractor core.

**Comment by juliemr** [comment]
Agreed - I think having a good library to convert to file:// urls is the right thing to do here, and that doesn't fit with Protractor's scope. Someone should do it though :)
