### ISSUE TITLE
Pass in implicit wait to expected conditions like stalenessOf?

### ISSUE THREAD

**Issue by gsagenjr** [angular/protractor#2703]
We can pass in a timeout for a failing expected condition:

    browser.wait(EC.stalenessOf(elementThatIsNotStale), 3000, 'Error: Element was found in the dom');

Can we pass in a value to override the implicit timeout that is currently being used <b>on success</b>?
I.e., I would like to make sure an element is not attached to the dom, but I would not like to wait for the 30s that our implicit timeout is set to. I would like too pass in both the fail and the pass timer:

    browser.wait(EC.stalenessOf(elementThatIsStale), 3000, 3000, 'Error: Element was found in the dom');

This way it only checks for 3 seconds, regardless of pass or fail, before returning the results.

Is there a way to pass in an implicit timeout override?

Edit:
Expected conditions also do not work with element.all.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by gsagenjr** [comment]
Thanks, I will go ahead and do that. Reading through the code, it appears that is not built in to protractor, so I meant for this to be a bit of a feature request if it didn't exist.

**Comment by juliemr** [comment]
If this is a case where there really is something special about the 3 second timing, it may be appropriate to use `browser.sleep(3000)` here instead of `browser.wait`. In any case, closing issue as a question, thanks!
