### ISSUE TITLE
RFE: a way to test <noscript>

### ISSUE THREAD

**Issue by radek-holy** [angular/protractor#2704]
I believe that it's a good practice to place a <noscript> fallback on JavaScript-based pages. It would be nice to have a possibility to test this aspect of the page as well.

**Comment by NickTomlin** [comment]
You can use selenium/protractor to ensure that there's a no-script element on the page (and test its contents).

**Comment by radek-holy** [comment]
I can test whether my HTML source code contains particular elements and particular content but this is not end-to-end testing. IIUIC, end-to-end testing (in context of web applications) is testing of the application behaviour in a particular browser. Protractor is designed to be an end-to-end testing framework, right?

AFAIK, the `noscript` element represents a content that should be shown when scripting is disabled. So, to test an application using a `noscript` element, one has to test whether the content is *shown* with scripting disabled and *not shown* with scripting enabled. Am I right?

So, I guess that I am looking for a Protractor API to disable scripting. The other bits are there already. But actually, it does not matter to me *how* I will do the test. I leave the decision up to you. Whether there will be a method to disable scripting or something else, it does not matter. I just wish there was a way to test this particular behaviour of an Angular application.

**Comment by NickTomlin** [comment]
You can disable JavaScript through a selenium profile (an example [here](http://stackoverflow.com/q/27099250/1048479)). Personally, this is a bit of a gray area of testing since your application has no control over whether `<noscript>` is shown or not because the browser handles that; I typically like to avoid testing the browser. However, I understand wanting to ensure that you aren't accidentally hiding it (or that other content isn't showing up).

For further help, please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

**Comment by radek-holy** [comment]
I am sorry, I forgot to mention that I am looking for a solution that works with any browser. Can you implement one (sometime in the future) if you consider this use case valid for Protractor?

> Personally, this is a bit of a gray area of testing since your application has no control over whether `<noscript>` is shown or not because the browser handles that; I typically like to avoid testing the browser.
Right. That's how I understand e2e testing. The (source) files on one end and the rendered page on the other end. This includes the the behaviour of the browser. If any piece is missing, I consider it an integration test. But I may be wrong.

**Comment by juliemr** [comment]
There is no generic way to disable javascript, it would depend on the browser. We could consider adding a wrapper around the ways to turn it off in the configuration, but Protractor has not been in the business of editing the setup capabilities for browsers to make them generic, and we'd need to think carefully before adding that complexity.

**Comment by juliemr** [comment]
Since our focus is on Angular.js applications, which overwhelming need script enabled, and there are already solutions (as mentioned above) for individual browsers, I don't it's worth the complexity to implement this.
