### ISSUE TITLE
RFE: a way to run a test just before Angular loads

### ISSUE THREAD

**Issue by radek-holy** [angular/protractor#2705]
I believe that it's a good practice to inform users that the Angular-based application is loading. I mean, in case of Angular 2, it's e.g. `<view>Loading...</view>`. It would be nice to have a possibility to test this aspect of the page by running a test just BEFORE Angular (or maybe any particular script) loads.

**Comment by NickTomlin** [comment]
I don't see how this has anything to do with Protractor. There's nothing preventing you from using selenium to test that a loader / message exists on the page.

**Comment by radek-holy** [comment]
The description says "Protractor is an end-to-end test framework for AngularJS applications.". Since I am seeking for a way to test a particular aspect of an AngularJS application, I guess it fits the purpose of Protractor...

Would you be so kind to give me some more hints? You meant some `browser.driver` methods? Do you know off head what method can help me make sure that Angular won't be loaded before the test finishes?

**Comment by NickTomlin** [comment]
Certainly (and other Protactor users) would be happy to help you on StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by radek-holy** [comment]
Great to hear that. Thank you.
For those who come across this thread: http://stackoverflow.com/q/33732320/5566882

**Comment by juliemr** [comment]
Unfortunately, this is impossible to do with WebDriver - once requested, you can't generically pause a page during its load. Protractor _does_ ask Angular to wait to bootstrap while it is loading to insert more modules - you could potentially piggy-back off of this to run a check between when the page is loading and when angular bootstraps. I don't think that this is a common use case so I doubt we'll add an official way of doing this, but I can reopen.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since if it's not something we are likely to implement and we haven't had any movement on it for a few months. I think [alexce's](http://stackoverflow.com/a/33745759/1048479) SO answer provides a decent approach to testing around this. 

Please feel free to re-open if that's a wrong way to think about it :smile:

**Comment by radek-holy** [comment]
Does alexce's approach guarantee that Angular is not loaded before the test ends? Otherwise I have trouble to understand how that can be *a decent approach*.
