### ISSUE TITLE
Protractor is unable to navigate to the application

### ISSUE THREAD

**Issue by Kothajagadeesh** [angular/protractor#2707]
HI,

I've a scenario, where clicking on a button in the pop-up, it will navigate to user to the other page.

From there i'm navigating to other page with driver.get(). However, i'm getting the below error

Failed: Failed to navigate to url. This usually means that a call to the COM method IWebBrowser2::Navigate2() failed. (WARNING: The server did not provide any stacktrace information)

I've used both sleep() and browser.wait() but no luck 

Does any one has solution?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
