### ISSUE TITLE
Unable to install protractor

### ISSUE THREAD

**Issue by SwatiKhandelwal** [angular/protractor#2708]
I have installed NodeJS in my C drive. Now, when I am trying to execute the following command:
npm install -g protractor

I am getting the following error:

![untitled](https://cloud.githubusercontent.com/assets/9655076/11182490/4199bc2c-8c91-11e5-871f-1b7c479eb0fb.jpg)

Please help me in this regard.

Thanks in advance!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I am not very familiar with windows, but the error output points to a permissions error. I would ensure you have write permissions before installing. If that does not work let's continue the discussion on one of the mediums above. 

Thanks!

**Comment by SwatiKhandelwal** [comment]
Thanks a lot Nick!
