### ISSUE TITLE
Protractor When sendKeys meet issue 'cannot focus element'

### ISSUE THREAD

**Issue by mayzhou** [angular/protractor#2714]
I am not sure if Protractor can sendKeys to a div.

My code is 
element(by.css('.create-api-schema-editor .CodeMirror .CodeMirror-lines .CodeMirror-code .CodeMirror-line')).sendKeys(content);

HTML is:
![20151117170604](https://cloud.githubusercontent.com/assets/8501053/11207012/a12ad9e8-8d4d-11e5-935b-ce5145362d0d.jpg)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm surprised this does not work. Let's try to figure it out in one of the channels mentioned above.

**Comment by nickiannone** [comment]
I'm actually working on a similar problem; the textarea used by CodeMirror is hidden and replaced with the divs that build out the display, so you will have to fire off key events without focusing the element. I'll comment here when I figure out how.
