### ISSUE TITLE
Unable to generate xml reports using JUnitXmlReporter 

### ISSUE THREAD

**Issue by SwatiKhandelwal** [angular/protractor#2716]
When I am trying to generate xml output files using JUnitXmlReporter, the test run is successful, but no XML reports are generated, I only see results in console where I run the tests. Below is the conf.js file that I used:

    exports.config = {
	          seleniumAddress: 'http://localhost:4444/wd/hub',

	capabilities: {
		'browserName': 'firefox'
	},

	specs: ['spec1.js'],

	jasmineNodeOpts: {
	  onComplete: null,
      isVerbose: true,
      showColors: true,
      includeStackTrace: true
	},
    onPrepare: function() {
	    var jasmineReporters = require('C:/Users/swati.m.khandelwal/node_modules/jasmine-reporters');
    jasmine.getEnv().addReporter(
    new jasmineReporters.JUnitXmlReporter('./output', true, true)
    );
        }
    };

Please help me in this regard.

Thanks in advance!

**Comment by SwatiKhandelwal** [comment]
I am successfully able to generate HTML reports (using 'protractor-html-screenshot-reporter') but not XML reports anyhow.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
