### ISSUE TITLE
Any system independent path for 'protractor-html-screenshot-reporter'?

### ISSUE THREAD

**Issue by SwatiKhandelwal** [angular/protractor#2717]
In my conf.js file, the path to 'protractor-html-screenshot-reporter' mentioned is:
C:/Users/swati.m.khandelwal/node_modules/protractor-html-screenshot-reporter

Now, I want the conf.js file to run in some other system which has some other username. So, is there any way with the help of which my conf.js file runs independently without making any path changes?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
