### ISSUE TITLE
expect(p) ignored when p is a long-delayed promise

### ISSUE THREAD

**Issue by bblack** [angular/protractor#2718]
I'm using bluebird 2.10.0, and protractor 2.5.1.

If I pass a quickly-resolved promise to `expect()`:

```js
it('should redirect / to /login when not authd', function () {
  var getUrlAfterLogin = Promise.resolve().delay(0);
  expect(getUrlAfterLogin).toEqual('/this_should_fail');
});
```

This fails, as expected:

```
Failures:

  1) drive should redirect / to /login when not authd
   Message:
     Expected undefined to equal '/this_should_fail'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/Users/bblack/work/drive/test/e2e/index.js:61:34)

Finished in 0.019 seconds
1 test, 1 assertion, 1 failure
```

However, if the promise takes a long time to resolve (the diff here is the arg to `delay()`):

```js
it('should redirect / to /login when not authd', function () {
  var getUrlAfterLogin = Promise.resolve().delay(1000);
  expect(getUrlAfterLogin).toEqual('/this_should_fail');
});
```

then protractor ignores the `expect` entirely:

```
Finished in 0.015 seconds
1 test, 0 assertions, 0 failures
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by hankduan** [comment]
`expect` wraps around webdriver's promise. It does not understand bluebird. 
It would be best if you do not mix webdriver promise with bluebird. If you really have to use bluebird, I suggest resolving the promise normally using `then` and putting the expect into that. You'd also need to use the asynchronous version of the jasmine `it`. 

But like @NickTomlin said, please ask questions on stackoverflow
