### ISSUE TITLE
Get the text of an anchor which contains several i tags

### ISSUE THREAD

**Issue by hoigo** [angular/protractor#2721]
In a test case I would like to compare the text of an anchor with an expected one, but the anchor also contains i tags. Do you have a hint on how to do it?

E.g. (how to get the name of the selected language):
```<a class="dropdown-button btn" href="#" data-activates="languageDropdown">
	<i class="material-icons">language</i>{{selectedLanguage.name}}<i class="material-icons">arrow_drop_down</i>
</a>```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

You should be able to use `getText` and retrieve all the text in the element. If that is not working let's solve this in one of the channels listed above.
