### ISSUE TITLE
@see comments in docs should be parsed as links on the website

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2723]

**Comment by sjelin** [comment]
Is this not what happens?  See: http://www.protractortest.org/#/api?view=ElementFinder.prototype.locator

**Comment by sjelin** [comment]
I believe they're only not links if we don't have docs for them

**Comment by juliemr** [comment]
This is the one that I was looking at which isn't linking: http://www.protractortest.org/#/api?view=ElementFinder.prototype.evaluate

**Comment by sjelin** [comment]
That's because the comment should say `@see ElementArrayFinder.prototype.evaluate`.  There is no `ElementArrayFinder.evaluate`.  I could have it check both or we could just fix the comment.

**Comment by juliemr** [comment]
Ah, OK, let's just change the comment then.
