### ISSUE TITLE
Protractor and selenium crashes when used with an Angular project

### ISSUE THREAD

**Issue by tirithen** [angular/protractor#2729]
I cannot get protractor working with an angular project, the project it self works fine when I visit the pages but with protractor I get the following, is it broken or am I doing something wrong here?

This is the protractor output:

    $ protractor protractor.conf.js
    Using the selenium server at http://localhost:4444/wd/hub
    [launcher] Running 1 instances of WebDriver
    Started
    .

    1 spec, 0 failures
    Finished in 0.906 seconds
    [launcher] 0 instance(s) of WebDriver still running
    [launcher] chrome #1 passed

This is the selenium output:

    $ webdriver-manager start
    seleniumProcess.pid: 8950
    12:44:47.216 INFO - Launching a standalone Selenium Server
    Setting system property webdriver.chrome.driver to /home/fredrik/node_modules/protractor/selenium/chromedriver
    12:44:47.249 INFO - Java: Oracle Corporation 24.91-b01
    12:44:47.249 INFO - OS: Linux 4.2.5-1-ARCH amd64
    12:44:47.263 INFO - v2.48.0, with Core v2.48.0. Built from revision 41bccdd
    12:44:47.327 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
    registration capabilities Capabilities [{platform=WINDOWS, ensureCleanSession=true, browserName=internet explorer, version=}] does not match the current platform LINUX
    12:44:47.327 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
    registration capabilities Capabilities [{platform=WINDOWS, browserName=MicrosoftEdge, version=}] does not match the current platform LINUX
    12:44:47.327 INFO - Driver class not found: com.opera.core.systems.OperaDriver
    12:44:47.328 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
    12:44:47.400 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4444/wd/hub
    12:44:47.400 INFO - Selenium Server is up and running
    12:44:54.005 INFO - Executing: [new session: Capabilities [{count=1, browserName=chrome}]])
    12:44:54.037 INFO - Creating a new session for Capabilities [{count=1, browserName=chrome}]
    Starting ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b) on port 27417
    Only local connections are allowed.
    12:44:55.305 INFO - Done: [new session: Capabilities [{count=1, browserName=chrome}]]
    12:44:55.326 INFO - Executing: [set script timeout: 11000])
    12:44:55.334 INFO - Done: [set script timeout: 11000]
    12:44:55.396 INFO - Executing: [get: data:text/html,<html></html>])
    12:44:55.437 INFO - Done: [get: data:text/html,<html></html>]
    12:44:55.448 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://example.com/dashboard//#/login");, []])
    12:44:55.655 INFO - Done: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://example.com/dashboard//#/login");, []]
    12:44:55.664 INFO - Executing: [execute script: return window.location.href;, []])
    12:44:55.671 INFO - Done: [execute script: return window.location.href;, []]
    12:44:55.679 INFO - Executing: [execute async script: try { return (function (attempts, asyncCallback) {
      var callback = function(args) {
        setTimeout(function() {
          asyncCallback(args);
        }, 0);
      };
      var check = function(n) {
        try {
          if (window.getAllAngularTestabilities) {
            callback({ver: 2});
          } else if (window.angular && window.angular.resumeBootstrap) {
            callback({ver: 1});
          } else if (n < 1) {
            if (window.angular) {
              callback({message: 'angular never provided resumeBootstrap'});
            } else {
              callback({message: 'retries looking for angular exceeded'});
            }
          } else {
            window.setTimeout(function() {check(n - 1);}, 1000);
          }
        } catch (e) {
          callback({message: e});
        }
      };
      check(attempts);
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [10]])
    12:44:55.792 INFO - Done: [execute async script: try { return (function (attempts, asyncCallback) {
      var callback = function(args) {
        setTimeout(function() {
          asyncCallback(args);
        }, 0);
      };
      var check = function(n) {
        try {
          if (window.getAllAngularTestabilities) {
            callback({ver: 2});
          } else if (window.angular && window.angular.resumeBootstrap) {
            callback({ver: 1});
          } else if (n < 1) {
            if (window.angular) {
              callback({message: 'angular never provided resumeBootstrap'});
            } else {
              callback({message: 'retries looking for angular exceeded'});
            }
          } else {
            window.setTimeout(function() {check(n - 1);}, 1000);
          }
        } catch (e) {
          callback({message: e});
        }
      };
      check(attempts);
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [10]]
    12:44:55.798 INFO - Executing: [execute script: return (function (trackOutstandingTimeouts) {
        var ngMod = angular.module('protractorBaseModule_', []).
            config(['$compileProvider', function($compileProvider) {
              if ($compileProvider.debugInfoEnabled) {
                $compileProvider.debugInfoEnabled(true);
              }
            }]);
        if (trackOutstandingTimeouts) {
          ngMod.config(['$provide', function($provide) {
              $provide.decorator('$timeout', ['$delegate', function($delegate) {
                var $timeout = $delegate;

                var taskId = 0;
                if (!window.NG_PENDING_TIMEOUTS) {
                  window.NG_PENDING_TIMEOUTS = {};
                }
                  
                var extendedTimeout = function() {
                  var args = Array.prototype.slice.call(arguments);
                  if (typeof(args[0]) !== 'function') {
                    return $timeout.apply(null, args);
                  }

                  taskId++;
                  var fn = args[0];
                  window.NG_PENDING_TIMEOUTS[taskId] = fn.toString();
                  var wrappedFn = (function(taskId_) {
                    return function() {
                      delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                      return fn.apply(null, arguments);
                    };
                  })(taskId);
                  args[0] = wrappedFn;
                  
                  var promise = $timeout.apply(null, args);
                  promise.ptorTaskId_ = taskId;
                  return promise;
                };

                extendedTimeout.cancel = function() {
                  var taskId_ = arguments[0] && arguments[0].ptorTaskId_;
                  if (taskId_) {
                    delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                  }
                  return $timeout.cancel.apply($timeout, arguments);
                };
                 
                return extendedTimeout;
              }]);
            }]);
        }   
      }).apply(null, arguments);, [true]])
    12:44:55.805 INFO - Done: [execute script: return (function (trackOutstandingTimeouts) {
        var ngMod = angular.module('protractorBaseModule_', []).
            config(['$compileProvider', function($compileProvider) {
              if ($compileProvider.debugInfoEnabled) {
                $compileProvider.debugInfoEnabled(true);
              }
            }]);
        if (trackOutstandingTimeouts) {
          ngMod.config(['$provide', function($provide) {
              $provide.decorator('$timeout', ['$delegate', function($delegate) {
                var $timeout = $delegate;

                var taskId = 0;
                if (!window.NG_PENDING_TIMEOUTS) {
                  window.NG_PENDING_TIMEOUTS = {};
                }
                  
                var extendedTimeout = function() {
                  var args = Array.prototype.slice.call(arguments);
                  if (typeof(args[0]) !== 'function') {
                    return $timeout.apply(null, args);
                  }

                  taskId++;
                  var fn = args[0];
                  window.NG_PENDING_TIMEOUTS[taskId] = fn.toString();
                  var wrappedFn = (function(taskId_) {
                    return function() {
                      delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                      return fn.apply(null, arguments);
                    };
                  })(taskId);
                  args[0] = wrappedFn;
                  
                  var promise = $timeout.apply(null, args);
                  promise.ptorTaskId_ = taskId;
                  return promise;
                };

                extendedTimeout.cancel = function() {
                  var taskId_ = arguments[0] && arguments[0].ptorTaskId_;
                  if (taskId_) {
                    delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                  }
                  return $timeout.cancel.apply($timeout, arguments);
                };
                 
                return extendedTimeout;
              }]);
            }]);
        }   
      }).apply(null, arguments);, [true]]
    12:44:55.811 INFO - Executing: [execute script: angular.resumeBootstrap(arguments[0]);, [[protractorBaseModule_]]])
    12:44:55.908 INFO - Done: [execute script: angular.resumeBootstrap(arguments[0]);, [[protractorBaseModule_]]]
    12:44:55.917 INFO - Executing: [execute script: return window.location.href, []])
    12:44:55.925 INFO - Done: [execute script: return window.location.href, []]
    12:44:55.934 INFO - Executing: [get: data:text/html,<html></html>])
    12:44:55.957 INFO - Done: [get: data:text/html,<html></html>]
    12:44:55.963 INFO - Executing: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://example.com/dashboard//#/login");, []])
    12:44:56.101 INFO - Done: [execute script: window.name = "NG_DEFER_BOOTSTRAP!" + window.name;window.location.replace("http://example.com/dashboard//#/login");, []]
    12:44:56.110 INFO - Executing: [execute script: return window.location.href;, []])
    12:44:56.121 INFO - Done: [execute script: return window.location.href;, []]
    12:44:56.134 INFO - Executing: [execute async script: try { return (function (attempts, asyncCallback) {
      var callback = function(args) {
        setTimeout(function() {
          asyncCallback(args);
        }, 0);
      };
      var check = function(n) {
        try {
          if (window.getAllAngularTestabilities) {
            callback({ver: 2});
          } else if (window.angular && window.angular.resumeBootstrap) {
            callback({ver: 1});
          } else if (n < 1) {
            if (window.angular) {
              callback({message: 'angular never provided resumeBootstrap'});
            } else {
              callback({message: 'retries looking for angular exceeded'});
            }
          } else {
            window.setTimeout(function() {check(n - 1);}, 1000);
          }
        } catch (e) {
          callback({message: e});
        }
      };
      check(attempts);
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [10]])
    12:44:56.147 INFO - Done: [execute async script: try { return (function (attempts, asyncCallback) {
      var callback = function(args) {
        setTimeout(function() {
          asyncCallback(args);
        }, 0);
      };
      var check = function(n) {
        try {
          if (window.getAllAngularTestabilities) {
            callback({ver: 2});
          } else if (window.angular && window.angular.resumeBootstrap) {
            callback({ver: 1});
          } else if (n < 1) {
            if (window.angular) {
              callback({message: 'angular never provided resumeBootstrap'});
            } else {
              callback({message: 'retries looking for angular exceeded'});
            }
          } else {
            window.setTimeout(function() {check(n - 1);}, 1000);
          }
        } catch (e) {
          callback({message: e});
        }
      };
      check(attempts);
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [10]]
    12:44:56.156 INFO - Executing: [execute script: return (function (trackOutstandingTimeouts) {
        var ngMod = angular.module('protractorBaseModule_', []).
            config(['$compileProvider', function($compileProvider) {
              if ($compileProvider.debugInfoEnabled) {
                $compileProvider.debugInfoEnabled(true);
              }
            }]);
        if (trackOutstandingTimeouts) {
          ngMod.config(['$provide', function($provide) {
              $provide.decorator('$timeout', ['$delegate', function($delegate) {
                var $timeout = $delegate;

                var taskId = 0;
                if (!window.NG_PENDING_TIMEOUTS) {
                  window.NG_PENDING_TIMEOUTS = {};
                }
                  
                var extendedTimeout = function() {
                  var args = Array.prototype.slice.call(arguments);
                  if (typeof(args[0]) !== 'function') {
                    return $timeout.apply(null, args);
                  }

                  taskId++;
                  var fn = args[0];
                  window.NG_PENDING_TIMEOUTS[taskId] = fn.toString();
                  var wrappedFn = (function(taskId_) {
                    return function() {
                      delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                      return fn.apply(null, arguments);
                    };
                  })(taskId);
                  args[0] = wrappedFn;
                  
                  var promise = $timeout.apply(null, args);
                  promise.ptorTaskId_ = taskId;
                  return promise;
                };

                extendedTimeout.cancel = function() {
                  var taskId_ = arguments[0] && arguments[0].ptorTaskId_;
                  if (taskId_) {
                    delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                  }
                  return $timeout.cancel.apply($timeout, arguments);
                };
                 
                return extendedTimeout;
              }]);
            }]);
        }   
      }).apply(null, arguments);, [true]])
    12:44:56.167 INFO - Done: [execute script: return (function (trackOutstandingTimeouts) {
        var ngMod = angular.module('protractorBaseModule_', []).
            config(['$compileProvider', function($compileProvider) {
              if ($compileProvider.debugInfoEnabled) {
                $compileProvider.debugInfoEnabled(true);
              }
            }]);
        if (trackOutstandingTimeouts) {
          ngMod.config(['$provide', function($provide) {
              $provide.decorator('$timeout', ['$delegate', function($delegate) {
                var $timeout = $delegate;

                var taskId = 0;
                if (!window.NG_PENDING_TIMEOUTS) {
                  window.NG_PENDING_TIMEOUTS = {};
                }
                  
                var extendedTimeout = function() {
                  var args = Array.prototype.slice.call(arguments);
                  if (typeof(args[0]) !== 'function') {
                    return $timeout.apply(null, args);
                  }

                  taskId++;
                  var fn = args[0];
                  window.NG_PENDING_TIMEOUTS[taskId] = fn.toString();
                  var wrappedFn = (function(taskId_) {
                    return function() {
                      delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                      return fn.apply(null, arguments);
                    };
                  })(taskId);
                  args[0] = wrappedFn;
                  
                  var promise = $timeout.apply(null, args);
                  promise.ptorTaskId_ = taskId;
                  return promise;
                };

                extendedTimeout.cancel = function() {
                  var taskId_ = arguments[0] && arguments[0].ptorTaskId_;
                  if (taskId_) {
                    delete window.NG_PENDING_TIMEOUTS[taskId_]; 
                  }
                  return $timeout.cancel.apply($timeout, arguments);
                };
                 
                return extendedTimeout;
              }]);
            }]);
        }   
      }).apply(null, arguments);, [true]]
    12:44:56.172 INFO - Executing: [execute script: angular.resumeBootstrap(arguments[0]);, [[protractorBaseModule_]]])
    12:44:56.249 INFO - Done: [execute script: angular.resumeBootstrap(arguments[0]);, [[protractorBaseModule_]]]
    12:44:56.263 INFO - Executing: [execute async script: try { return (function (rootSelector, callback) {
      var el = document.querySelector(rootSelector);

      try {
        if (window.getAngularTestability) {
          window.getAngularTestability(el).whenStable(callback);
          return;
        }
        if (!window.angular) {
          throw new Error('window.angular is undefined.  This could be either ' +
              'because this is a non-angular page or because your test involves ' +
              'client-side navigation, which can interfere with Protractor\'s ' +
              'bootstrapping.  See http://git.io/v4gXM for details');
        }
        if (angular.getTestability) {
          angular.getTestability(el).whenStable(callback);
        } else {
          if (!angular.element(el).injector()) {
            throw new Error('root element (' + rootSelector + ') has no injector.' +
               ' this may mean it is not inside ng-app.');
          }
          angular.element(el).injector().get('$browser').
              notifyWhenNoOutstandingRequests(callback);
        }
      } catch (err) {
        callback(err.message);
      }
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [html]])
    12:44:56.271 INFO - Done: [execute async script: try { return (function (rootSelector, callback) {
      var el = document.querySelector(rootSelector);

      try {
        if (window.getAngularTestability) {
          window.getAngularTestability(el).whenStable(callback);
          return;
        }
        if (!window.angular) {
          throw new Error('window.angular is undefined.  This could be either ' +
              'because this is a non-angular page or because your test involves ' +
              'client-side navigation, which can interfere with Protractor\'s ' +
              'bootstrapping.  See http://git.io/v4gXM for details');
        }
        if (angular.getTestability) {
          angular.getTestability(el).whenStable(callback);
        } else {
          if (!angular.element(el).injector()) {
            throw new Error('root element (' + rootSelector + ') has no injector.' +
               ' this may mean it is not inside ng-app.');
          }
          angular.element(el).injector().get('$browser').
              notifyWhenNoOutstandingRequests(callback);
        }
      } catch (err) {
        callback(err.message);
      }
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [html]]
    12:44:56.280 INFO - Executing: [execute script: try { return (function (selector) {
      var el = document.querySelector(selector);
      if (angular.getTestability) {
        return angular.getTestability(el).
            getLocation();
      }
      return angular.element(el).injector().get('$location').absUrl();
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [html]])
    12:44:56.285 INFO - Done: [execute script: try { return (function (selector) {
      var el = document.querySelector(selector);
      if (angular.getTestability) {
        return angular.getTestability(el).
            getLocation();
      }
      return angular.element(el).injector().get('$location').absUrl();
    }).apply(this, arguments); }
    catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [html]]
    12:44:56.297 INFO - Executing: [delete session: f7e07d8d-b622-4f75-b75b-e42d6ce56ae2])
    12:44:56.855 INFO - Done: [delete session: f7e07d8d-b622-4f75-b75b-e42d6ce56ae2]

This is the configuration (protractor.conf.js):

    exports.config = {
      seleniumAddress: 'http://localhost:4444/wd/hub',

      capabilities: {
        browserName: 'chrome'
      },

      rootElement: 'html',

      onPrepare: function() {
      },

      specs: [
        'spec/**/*.js'
      ],

      jasmineNodeOpts: {
        showColors: true,
        isVerbose: true
      },

      params: {
        baseUrl: 'http://example.com/dashboard/',
        invalidUser: {
          username: 'invalidUser',
          password: 'invalidPassword'
        },
        validUser: {
          username: 'administrator',
          password: '1234'
        }
      }
    };

This is the spec (spec/login-spec.js):

    describe('Login Page: ', function() {
      var url = browser.params.baseUrl + '/#/login';

      beforeEach(function() {
        browser.get(url);
        browser.refresh();
      });

      it('should go to the login page', function() {
        expect(browser.getLocationAbsUrl()).toEqual(url);
      });
    });

I'm basically following the steps from varius guides like https://angular.github.io/protractor/#/tutorial and others but it's still not working. It might be related to other issues as https://github.com/angular/protractor/issues/2643 ?

**Comment by elgalu** [comment]
I don't see the error, can you clarify?

```
1 spec, 0 failures
Finished in 0.906 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

**Comment by tirithen** [comment]
Yes you are actually right, I seem to have solved the issue wherever it is when I created the simplified setup for reporting about this issue, the error must be in your more extensive test code. Thanks for pointing out what should have been obvious for us from the start and thanks for a good and usable tool. :)

I'm closing this issue

**Comment by elgalu** [comment]
:D
