### ISSUE TITLE
Issue with my protractor tests using version 2.5.1 of protractor: Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL

### ISSUE THREAD

**Issue by balteo** [angular/protractor#2733]
Hello,
I am running into the following issue: `Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL` with version 2.5.1 of protractor.

I have opened a post on SO here: http://stackoverflow.com/questions/33858854

It seems to be a bug.

Can someone please suggest a workaround?

**Comment by sjelin** [comment]
Looks like the issue was that the email was never sent
