### ISSUE TITLE
Firefox throws Error while waiting for Protractor to sync with the page: "angular could not be found on the window" even though the Tests run fine

### ISSUE THREAD

**Issue by NisStrom** [angular/protractor#2734]
Hi,

We are using Protractor with the new Restart functionality from 97e6703. Now our Login Page is not Angular so we have a doLogin function which is called in OnPrepare and after each restart. In there we set ignoreSynchronization to true and afer waiting for the page and angular to load we set ignoreSynchronization to false. 
We are testing with IE and FF and in IE 10/11 everything works. But in FF every second execution we get **Failed: Error while waiting for Protractor to sync with the page: "angular could not be found on the window"** even though the Tests behave as expected in the Browser.

My question is why does browser.restart() go to the login page again but does not execute OnPrepare? The property restartBrowserBetweenTests did it in the older version correctly but as it restarts the Browser between each it() it is not suitable for us.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sjelin** [comment]
Please ask on Stackoverflow so it will be easy to keep track of.  This is a new feature and there might be a bug.

**Comment by juliemr** [comment]
This is working as intended - `onPrepare` is called once per test runner instance, not once per browser. You'll need to manage your own per-browser-instance setup.
