### ISSUE TITLE
Chrome - Preserve logs upon navigation

### ISSUE THREAD

**Issue by danielagreen** [angular/protractor#2737]
How to capture browser logs after a page navigation? 

The test:
Click button trigger writing to browser console + does page navigation  

In chrome, there is the option in the Dev Tools: Preserve log upon navigation

![screen shot 2015-11-24 at 5 42 55 pm](https://cloud.githubusercontent.com/assets/8258044/11371773/e6258d38-92d2-11e5-9bba-bc28bbac7025.png)

How to do it in an automation tests with chrome and protractor?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sjelin** [comment]
You should be able to use something with [`chromeOptions`](https://sites.google.com/a/chromium.org/chromedriver/capabilities) using `perfs`.  Not sure exactly what property you need though, StackOverflow is definitely a great channel to ask on.

**Comment by danielagreen** [comment]
Didnt find any configuration that suites in  chromeOptions using perfs.
