### ISSUE TITLE
config.suites should accept `undefined` key

### ISSUE THREAD

**Issue by Droogans** [angular/protractor#2739]
I would appreciate being able to over ride the default behavior of running all tests when leaving off a suite at the command line. I'd rather it run just the tests I want it to.

```js
suites: {
    undefined: '../stories/fast/*.js',
    slowOnly: '../stories/slow/*.js',
    all: '../stories/**/*.js'
},
```

Something like this might work.

```js
ConfigParser.getSpecs = function(config) {
  if (config.suites && config.suite === undefined) {
      return makeArray(config.suites[undefined]);
  }

  var specs = [];
  if (config.suite) {
    // ...
  }
```

Although this may seem confusing at first, I think it'd be nice to leave off any suite and catch that edge case inside my configuration file, and explicitly handle users wanting to run all the tests myself as well.

**Comment by Droogans** [comment]
I put together a rough idea of how to implement it at https://github.com/Droogans/protractor/commit/a636f29af582d2765ddb25558068f59365acd824, though it's likely a little rough with the testing and documentation updates.

**Comment by sjelin** [comment]
@juliemr @hankduan thoughts?

**Comment by hankduan** [comment]
I guess this is okay
...although if we do this I prefer having another option called 'defaultSuite' instead of using undefined as the key which is really not clear.

i.e.
```javascript
suites: {
    fastOnly: '../stories/fast/*.js',
    slowOnly: '../stories/slow/*.js',
    all: '../stories/**/*.js'
},
defaultSuite: 'fastOnly'
```

And if you don't define a defaultSuite, it would run all the suites like it was before.

**Comment by juliemr** [comment]
Agreed that the undefined key is very unclear - if we must, I'd prefer Hank's suggestion.

**Comment by Droogans** [comment]
Here's https://github.com/Droogans/protractor/commit/d3bd8b91d092dcec5470afcc4b8e4d68fd85c6fb -- I don't want to go through with full docs updates until this is signed off on.

**Comment by sjelin** [comment]
What's the difference between implementing this new `defaultSuite` option and the old `suite` option?  Surely because the `suite` you specified was the default one, and you could overwrite it from the command line.

**Comment by juliemr** [comment]
Good point @sjelin . The `suite` option should already do everything we want - @Droogans am I missing something?

**Comment by Droogans** [comment]
I don't like that transitioning from specs into suites forces you to use a flag everywhere. I feel I shouldn't need to use a flag to take advantage of suites.

We're going to be switching away from specs to use suites, and this will avoid me lots of work in retraining my team mates to always tack `--suite foo` on their local test runs, as well as many updates to our various CI jobs.

**Comment by sjelin** [comment]
Couldn't you put `suite: 'foo'` in your config file though?

**Comment by Droogans** [comment]
That's not in the [referenceConf](https://github.com/angular/protractor/blob/master/docs/referenceConf.js) :cry:.

**Comment by sjelin** [comment]
It's not how the feature was designed to be used.  I'll stick it in the referenceConf :smile:

**Comment by juliemr** [comment]
Thanks @sjelin!
