### ISSUE TITLE
browser.addMockModule(...) never executed

### ISSUE THREAD

**Issue by jechazelle** [angular/protractor#2743]
Hi !
What is the best way to use browser.addMockModule ?

I tried this :
```js
browser.addMockModule('modName', function() {

    browser.executeScript(function() {console.log('mockModule!')});

    angular.module('modName', []).value('foo', 'bar').run(function ($httpBackend) {
    $httpBackend.whenPOST('http://api.webapp.net/app_dev.php/module/search?direction=asc&page=1').respond('repsond');

    browser.executeScript(function() {console.log('enter mockModule!')});
    });
});
```
but my function is never executed. I never see 'mockModule' in my console, and my mock doesn't work.

My code is here :
http://stackoverflow.com/questions/33894358/use-mock-http-with-protractor-and-jasmine

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sjelin** [comment]
Yeah, the stackoverflow thread seems to be producing discussion, so I'm closing this.

Also, you shouldn't put `browser.executeScript` inside your `browser.addMockModule` function.  The code in your `browser.executeScript` function is being executed client side, but the `browser` object is only available server side

**Comment by Roaders** [comment]
A link to the SO discussion would have been useful...

**Comment by jechazelle** [comment]
@Roaders the SO discussion is [here](http://stackoverflow.com/questions/33894358/use-mock-http-with-protractor-and-jasmine)
