### ISSUE TITLE
ExecuteScript fails with 'Maximum call stack size exceeded' on Angular 1.4

### ISSUE THREAD

**Issue by andriikobtsev** [angular/protractor#2744]
Hello,
the following error occurs when script return object from angular:
> WARN - Exception: unknown error: Maximum call stack size exceeded
  (Session info: chrome=43.0.2357.125)
  (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-37-generic x86_64) (WARNING: The server did not provide any stacktrace information)

Function returns some form:
*return angular.element(document.getElementById(formId)).scope().Form*

Error occurs even if form has only 1 field.
Checked with firefoxdriver, chromedriver, phantomjs.

Works with angular 1.3.

**Comment by NickTomlin** [comment]
Interesting, can you provide us with some more details? 

1. Your protractor configuration
2. The test code where you rexperience the issue
3. The Version of Protractor/Node you are using
4. Your operating system

**Comment by andriikobtsev** [comment]
@NickTomlin 

'1.
 ```javascript
 'use strict';
   exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['./specs/test.js'],
    multiCapabilities: [
        {
            browserName: 'chrome',
            shardTestFiles: true,
            maxInstances: 2,
        }
    ],
    resultJsonOutputFile: 'result',
    keepAlive: true,
    maxSessions: 4,

    onPrepare: function () {
        browser.ignoreSynchronization = true;
        global.EC = protractor.ExpectedConditions;
    }
 ```

'2. 
```javascript
let getForm = function(formId){
    return browser.executeScript(function (formId) {
        return angular.element(document.getElementById(formId)).scope().Form;
```

'3. Protractor Version 2.5.1 / Node v4.2.2 
'4. Linux Mint 17.1 Cinnamon 64-bit

**Comment by andriikobtsev** [comment]
Is there any progress on this?

**Comment by NickTomlin** [comment]
@andriikobtsev I have not been able to reproduce this locally. Could I get you to publish an example repo?

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this. @andriikobtsev please feel free to re-open with a reproducible example (ideally a gist/repo with markup and test file) or ask a question on StackOverflow or gitter. Thanks!
