### ISSUE TITLE
Support client-side redirects

### ISSUE THREAD

**Issue by kiraLinden** [angular/protractor#2745]
This is related to https://github.com/angular/protractor/issues/2643 it would be nice if client-side redirects were actually supported.

**Comment by sjelin** [comment]
We are working on this.  @hankduan has this PR: https://github.com/angular/protractor/pull/1155.  It requires a small change from the angular team, and we lost track of it, but we've decided to make it a priority again.  Both Hank and the Angular team are very busy right now though, so it might be a couple weeks.
