### ISSUE TITLE
Error: Protractor ng-app no injector for element argument found

### ISSUE THREAD

**Issue by Miro-H** [angular/protractor#2747]
Hi everyone,

A few weeks ago I asked on stackoverflow for help on this issue (please read there):
http://stackoverflow.com/questions/33502883/error-protractor-ng-app-no-injector-for-element-argument-found-set-rootelemen
But until now nobody has answered. Has nobody here had the same problem? Or can somebody help?

I'm thankful for any input or answers.

Greetings,
Miro

**Comment by NickTomlin** [comment]
Hi there, 

GH issues is still not the best place for this, unfortunately, since this deals with usage and debugging, not an issue with protractor core. I've just responded with a comment on the StackOverflow question. Let's try to sort things out there or on Gitter.

Thanks!
