### ISSUE TITLE
'by' is a reserved word in Coffeescript

### ISSUE THREAD

**Issue by Elexy** [angular/protractor#275]
I Write my tests in CoffeeScript and noticed that Protractor.By. has been replaced by just 'by'. This causes the coffeescript compiler to choke.

http://coffeescript.org/documentation/docs/lexer.html#section-66

```
By = protractor.By

describe "app entry page", ->

  it "should login", ->
    browser.get '/login'
    element(By.input("user.email")).sendKeys "admin@example.com"
    # FAILS: element(by.input("user.email")).sendKeys "admin@example.com"
```

This is an easy workaround and not too invasive, but I would like to put this on the list.

**Comment by armw4** [comment]
:+1:
