### ISSUE TITLE
Is it possible to read the values of multiCapabilities on beforeEach?

### ISSUE THREAD

**Issue by digicom1978** [angular/protractor#2752]
I am trying to launch several proxies corresponding to the port value of multiCapabilities.

For example, if _conf.js file has two multiCapabiilities set, then two proxies should be launched with different port value.

In _conf.js, I set below information,
-----------------------------------------------------------------------------------------------------------
exports.config = {
                ...
		multiCapabilities: [
                {    'browserName': 'chrome',
                      'proxy': { 'httpProxy': 'localhost:8889' },
                      'count': '1' },
                {    'browserName': 'firefox',
                      'proxy': { 'httpProxy': 'localhost:9001' },
                      'count': '1' },

Expectation : Two instances, one whose browser is chrome has a proxy with port 8889, 
                                              the other has firefox as its browser and a proxy with port 9001.

For this, I tried to use "browser.getProcessedConfig().then(" at beforeEach function in spec.js file.
However, I can't get values before launching proxies.

In _spec.js file, I am trying to read the "httpProxy" value before launching proxies in this way.
-----------------------------------------------------------------------------------------------------------
var Proxy = require('browsermob-proxy').Proxy;

describe('stress testing-' + dateone.curdate2Sec, function() {
    var curport = 0;
    beforeEach(function (done) {
        // READ HTTPPROXY TO PASS AS A PORT NUMBER FOR PROXY
        browser.getProcessedConfig().then(function(config) { 
	    curport = config.capabilities.proxy.httpProxy.split(':')[1];
	});

    /*  Proxy Part */		
    var proxy = new Proxy();
    return Q.ninvoke(proxy, 'start', curport) 
        .then(
            function (data) {
                console.log('data', data);
                console.log('arguments', arguments);
                browser.params.proxy = proxy;
                browser.params.proxyData = data;
                return data;
            }, 
            function () {
                console.log('start failed');
            })
        .then(
            function() {
                browser.params.proxy.startHAR(browser.params.proxyData.port, 'test', done);
            }
        );
});

But, protractor instance runs " return Q.ninvoke(proxy, 'start', curport) " first, then resolves "getProcessedConfig", which means after launching proxies.

So, I tried to insert  /*  Proxy Part */ into "browser.getProcessedConfig().then(...)",
but still it does not work.

So, is there any way that I can read the specific value of multiCapabilities immediately on beforeEach instead of waiting by .then()?
or any ways would be appreciated.

If my description is not clear, please let me know.

Thanks in advance.

** Main reference : https://github.com/afternoon/protractor-browsermob-test

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by digicom1978** [comment]
Thanks!

**Comment by digicom1978** [comment]
I'll use another ways you  told me. Thanks!
