### ISSUE TITLE
call config from test 

### ISSUE THREAD

**Issue by zorla** [angular/protractor#2755]
Hi,
need to read the property default_directory

            args: ['--no-sandbox', '--test-type=browser'],
            prefs: {
                'download': {
                    'prompt_for_download': false,
                    'default_directory': 'xyz'

in test.

tried 
browser.driver.getCapabilities();
but not found.

how to call config in tests?

thx!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
It also looks like you're using a wrapper around Protractor, please include more information about your setup when posting your question so that people can answer better. Thanks!
