### ISSUE TITLE
mouseMove() and doubleClick() not working on Firefox

### ISSUE THREAD

**Issue by defra91** [angular/protractor#2756]
I wrote an e2e test and I need to double click on an element, in order to select the word of a paragraph. I wrote the following code and it work correctly on chrome, but it's not working on firefox. Apparently it fails on both steps.

```
var paragraph = element(by.css('.BVRRReviewTextFirstParagraph'));
expect(paragraph.isDisplayed()).toBe(true);
browser.actions()
.mouseMove(paragraph.getWebElement(), {x:10,y:10})
.doubleClick()
.perform();
```

More info:

- Firefox 40.0.3
- Ubuntu 15.04
- Protractor 2.5.1

**Comment by juliemr** [comment]
Can you add some more info:

Version of firefox, OS, and Protractor?
How does it fail?
Does it fail on the mouseMove step, the doubleClick step, or both?

**Comment by defra91** [comment]
Updated

**Comment by juliemr** [comment]
Sorry for the slow response here - I'm unable to reproduce this problem with the latest firefox (45) and webdriver. Please open up a new issue if there is still a problem with the latest versions. (Note that we support the latest two versions of browsers). 

Here's my test: https://github.com/juliemr/webdriver-bugs/commit/ec68754f5f71db24edbfb5746fdbc0823f1c00ec (I also tried with paragraphs, and it does indeed select text).
