### ISSUE TITLE
Disable exit error code 1 when any protractor test fails

### ISSUE THREAD

**Issue by raviviswanathan** [angular/protractor#2757]
Hi,

I am invoking the protractor command from maven pom.xml, as i want to call another command to invoke custom reporter after protractor tests have run. But when the test case fails, it makes the entire build as failed (Reason : [launcher] Process exited with error code 1)

Failure log
====================================================================
Executed 26 of 26 specs (1 FAILED) in 50 secs.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.922 s
[INFO] Finished at: 2015-12-01T16:16:29-05:00
[INFO] Final Memory: 9M/310M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2:exec (exec-protractor) on project protractor-sample: Command execution failed. Process exited with an error: 1(Exit value: 1) -> [Help 1]

========================================================

Here is my pom.xml

&lt;plugin&gt;
                &lt;groupId&gt;org.codehaus.mojo&lt;/groupId&gt;
                &lt;artifactId&gt;exec-maven-plugin&lt;/artifactId&gt;
                &lt;version&gt;1.2&lt;/version&gt;
                &lt;executions&gt;
                    &lt;execution&gt;
                        &lt;id&gt;exec-protractor&lt;/id&gt;
                        &lt;phase&gt;generate-sources&lt;/phase&gt;
                        &lt;configuration&gt;
                            &lt;executable&gt;./node_modules/.bin/protractor&lt;/executable&gt;
                            &lt;arguments&gt;
                                &lt;argument&gt;config/config.js&lt;/argument&gt;
                            &lt;/arguments&gt;
                        &lt;/configuration&gt;
                        &lt;goals&gt;
                            &lt;goal&gt;exec&lt;/goal&gt;
                        &lt;/goals&gt;
                    &lt;/execution&gt;
                &lt;/executions&gt;
            &lt;/plugin&gt;

**Comment by juliemr** [comment]
I think this is a question about your maven set up. Protractor will (and should) exit with error code 1 when a test fails. You should catch this if you would like to do something else.

Closing as a question. Please see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

**Comment by vitaliusvs** [comment]
Actually I'd like to have possibility to suppress exit code on failed tests as well
--exit_code_on_failed_tests=0

**Comment by varunsufi** [comment]
I would also like to have the same feature to suppress the exit code
I am running the test in a jenkins job and due to exit code it fails the complete job.
But what i would like to is check how many tests passed and if one test failed i would want to continue my job and use that release.

**Comment by djom20** [comment]
I have the same problem, does exists any option like "--exit_code_on_failed_tests=0" ?

**Comment by wswebcreation** [comment]
There is no option like this in Protractor. Please use a separate node process / script to catch the error and do with it what you want. You could do this by running Protractor from a different script that catches the error code so you can do with it what you want. 

An example can be how [protractor-flake](https://github.com/NickTomlin/protractor-flake/blob/master/src/index.js) does it. This is a kind of wrapper around protractor and will check the exit code. If the exit code is 1 it will parse the logging to rerun tests. You can build the same logic and do your stuff you need to do in your own script.

**Comment by kentonbmax** [comment]
The most common DevOP's workflow today with modern CI pipelines is to run all tests and generate a report about the test run. Allowing the user to set args directly when calling protractor would always be preferable and better for passing arg values on the fly vs increased maintenance costs of a wrapper script.

**Comment by brenuart** [comment]
> There is no option like this in Protractor. Please use a separate node process / script to catch the error and do with it what you want.

@wswebcreation How can I make the distinction between a _failed test_ and _failure to execute tests_ (because of missing dependency or configuration issue) if both return the same exit code?
