### ISSUE TITLE
Protractor test appears to run but actions are not visible on the screen.

### ISSUE THREAD

**Issue by kpalusa** [angular/protractor#2758]
Protractor v1.7.0, Jasmine 1.3.1
In my test suite, I have the below tests
it1 : logs in user1 in to the application
it2: user1 does some actions
it3: logs off user1  (FYI..logoff redirects us back to login page)
(until this point we can see the test running with all actions visible to us on the screen)
it4: Again does a browser.get('login page url') & logs user2 in
and so on...

But from it4 the actions are not visible to us on the screen but the test appears to be working as per code in it blocks. When I just minimize & maximize the browser, I could see the actions visible to me. If we don't do it continues to run till the last test suite specified in conf file but actions are not visible on the screen.

Though it3 redirects us back to login page on log off, we do the same again in it4 to skip an issue currently we have with redirection to login page. 

Sounds like a weird issue, but just want to check if anybody has seen similar thing.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

Also, you might try upgrading - you're using a rather old version of Protractor.
