### ISSUE TITLE
Error: Wait timed out after 3005ms. 

### ISSUE THREAD

**Issue by rahul-wenable** [angular/protractor#2761]
Is multiple ` browser.wait ` causing error?
The application logins, but then it exits with the error above.

The code is as follows:

describe('driven application', function() {
  it('should login', function() {
    var address = browser.get('http://hostname#/signin');
    element(by.model('username')).clear().sendKeys("xyz");
    element(by.model('password')).sendKeys("zyx");
    element(by.id('protractor-loginbutton')).click();

        expect(browser.getCurrentUrl()).toMatch('http://hostname/#/dashboard');
        browser.wait(function() {
          browser.executeScript('window.scrollTo(0,200);').then(function () {
          })
        }, 3000);
        browser.wait(function() {
          browser.executeScript('window.scrollTo(0,-200);').then(function () {
          })
        }, 10000);
});

Any other alternate way to do the same?

**Comment by NickTomlin** [comment]
`Browser.wait` evaluates a function or promise that resolves to a boolean; neither of your wait invocations are returning something that resolves to a boolean value, so I believe this is expected (someone please correct me if I am wrong).

That said, Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by rahul-wenable** [comment]
Thank you @NickTomlin 
The following code I used to solve my issue.

var elm = element.all(by.css('.your-css')).get(0);
browser.executeScript("arguments[0].scrollIntoView();", elm.getWebElement());
elm.click();

Now, please tell whether is that a good approach or a temporary fix.

**Comment by juliemr** [comment]
Closing as a question. Thanks!
