### ISSUE TITLE
No way to load polyfills for PhantomJS

### ISSUE THREAD

**Issue by noahmonster** [angular/protractor#2762]
I'm trying to use the [PhantomJS Bind Polyfill](https://github.com/conversocial/phantomjs-polyfill) with Protractor.  Unfortunately, there does not appear to be a way to load this in to Protractor's context.  It would be nice if Protractor allowed for this, similar to how Karma does it: 

```
...
files: [
  './node_modules/phantomjs-polyfill/bind-polyfill.js',
  ...
]
...
```

In the meantime, I'm stuck with a failing test because my source uses `bind`.

**Comment by NickTomlin** [comment]
Phantomjs support in is not actively maintained and is also not [recommended](https://github.com/angular/protractor/blob/673d416b7ef5abd0953da940cfa8cf2a59650df4/docs/browser-support.md) for reasons just like this one. 

To explore some workarounds please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
