### ISSUE TITLE
keyDown does not work with IE9

### ISSUE THREAD

**Issue by Miro-H** [angular/protractor#2764]
With IE9, keyDown() does not work. I am trying to select multiple items, holding the command key. With Chrome and Firefox everything works fine, but the internet explorer first selects the first item and then the other one (= the cmd key isn't hold down)

```javascript
browser.actions()
    .keyDown(protractor.Key.COMMAND)
    .click(element(by.id(...)))
    .click(element(by.id(...)))
    .keyUp(protractor.Key.COMMAND)
.perform();
```
Tell me if I have overlooked a solution for this problem. But in the hours I googled this problem I neither found many others having the same issue nor a good solution/workaround for it.

Best regards
Miro

**Comment by NickTomlin** [comment]
This sounds more like a Selenium issue than one with Protractor core. I would suggest asking a StackOverflow question or opening an issue at the [Selenium project](https://github.com/SeleniumHQ/selenium/issues).

**Comment by Miro-H** [comment]
Thank you for your suggestion, I took your advice and [created an issue](https://github.com/SeleniumHQ/selenium/issues/1351) in the Selenium project. 

They looked at it, but weren't able to reproduce it. Maybe the bug is after all not on their side?  Because they used a different setup (C# and NUnit), with which it worked.

**Comment by juliemr** [comment]
I'm going to close this because we only support the latest two versions of browsers, which means IE 10 and IE 11. See http://www.protractortest.org/#/browser-support
