### ISSUE TITLE
Deeper options passed through the command-line arguments are handled wrongly

### ISSUE THREAD

**Issue by andreev-artem** [angular/protractor#2765]
For the following command-line argument:
```
--capabilities.chromeOptions.binary <some_path>
```

```configParser.getConfig()``` output will be:

```
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      args: [
        Object
      ]
    },
    'chromeOptions.binary': '<some_path>'
  },
```

And binary will not be used by chromeDriver.

**Comment by juliemr** [comment]
This is intentional, because capabilities requires options to be set this way. Weird, but true. See comment at https://github.com/angular/protractor/blob/master/lib/cli.js#L84.

**Comment by andreev-artem** [comment]
What is intentional? That we can't use
```
--capabilities.chromeOptions.binary <some_path>
```
command line argument? And have to pass such options only through the ```exports.config.capabilities.chromeOptions.binary``` from ```protractor.conf.js```?
