### ISSUE TITLE
no colors using mocha versior 2.1 or high

### ISSUE THREAD

**Issue by nestorneto** [angular/protractor#2766]
I would not found anything about how to fix this issue. Anyone know anything about it?

**Comment by NickTomlin** [comment]
Interesting. Could I get some more information from you?

- The versions of Node, Protractor, and Mocha you are using
- Your operating System and version

If you could also provide a small example repo that would help immensely in verifying and investigating this.

**Comment by nestorneto** [comment]
https://github.com/nestorneto/protractor-mocha
npm install && grunt

**Comment by NickTomlin** [comment]
I believe this is an issue with grunt-protractor-runner and not protractor. 

Output with grunt:

![screen shot 2015-12-04 at 10 14 52 am](https://cloud.githubusercontent.com/assets/1290336/11594499/0347320a-9a70-11e5-8ee8-7bd19e29fcd1.png)

Output manually running protractor: 

![screen shot 2015-12-04 at 10 15 02 am](https://cloud.githubusercontent.com/assets/1290336/11594507/0ba78fda-9a70-11e5-9093-140435e8a48b.png)

If you could close this and raise an issue on that project that would be great. Feel free to reopen if it is indeed a problem with protractor.

**Comment by nestorneto** [comment]
ouch. yea wrong place. thanks for your help.
