### ISSUE TITLE
angular-material is extremely slow with protractor

### ISSUE THREAD

**Issue by ashaffer** [angular/protractor#2767]
Just cross-posting this so people who are wondering why their tests are so slow can find this:

https://github.com/angular/material/issues/6090

Sorry if that's frowned upon you can close this.

**Comment by NickTomlin** [comment]
I'm not a huge fan of cross posting, since there's nothing actionable for Protractor here IMHO. A PR to the FAQ for the `$timeout` might be helpful? It seems like this is an isolated issue that should be handled by whoever is testing the material app. 

What do others think?

**Comment by sjelin** [comment]
We could write some sort of feature to turn off this wait, but I think the right thing is for people to just use their `onPrepare`

**Comment by NickTomlin** [comment]
@ashaffer I'm going to go ahead and close this issue since it should be handled on the angular-material side (probably just through documentation of the fix you mentioned in https://github.com/angular/material/issues/6090). Thanks!
