### ISSUE TITLE
Protractor: chrome not load data from server

### ISSUE THREAD

**Issue by runyasak** [angular/protractor#2768]
Hi, I have a problem when using protractor to test with chrome.

My chrome can work properly when I work at my university.
But perhaps at my house, chrome doesn't wait to load data. Sometimes it works when reload page.
The server is on Digitalocean.

I've tried to update webdriver and Protractor already but still useless.
Please, give me some suggestion or any advice.

Thank you.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by runyasak** [comment]
Thank you, Nick

I'll post in the Gitter now.

Sorry for my mistake, I'm just beginner for posting support.

**Comment by NickTomlin** [comment]
@runyasak Not a problem! Thanks :)
