### ISSUE TITLE
 Error: Step timed out after X milliseconds at Timer.listOnTimeout (timers.js:92:15)

### ISSUE THREAD

**Issue by dannypk** [angular/protractor#2769]
Hey guys, I am running in a very big problem. I am using protractor 3.0 with latest versions of everything (node, cucumber-framework, chrome-driver, etc). On Windows and Ubuntu machine, the tests are running quite ok. On Debian machine, build by a task scheduler in Jenkins, 80% of cases, only one feature fails, and turns my test in red. making this unreliable. I am running multicapabilities, 5 features (because i cannot clear session from the browser with any kind of script .... and i need new sessions for each test), but setting max session to 1, otherwise the protractor tests just dies. I tried changing the miliseconds time, right now is at 30.000 milisecons and still not helping. I am having this issue from a previous version of protractor also (2.2.0, 2.3.0, 2.5.1). Sometimes, after a restart of jenkins machine, the tests are just green.. sometimes, just red. Again, is about only one single test that's failing, and makes no sense sometimes to run and sometimes not to. The webpage i am testing is SPA.

Thanks!

Error:

[chrome #1]     [31mGiven I go to start page  [90m# features/steps/xstep.js/ [31m[39m
[chrome #1]       Error: Step timed out after 30000 milliseconds
[chrome #1]           at Timer.listOnTimeout (timers.js:92:15)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
