### ISSUE TITLE
clicked a button from modal, but callback not work

### ISSUE THREAD

**Issue by wubin1989** [angular/protractor#2770]
Using protractor clicked a button from modal, but callback not work. The modal is a alert by jQuery plugin SweetAlert, after clicked the confirm button, the modal disappeared, it should call the callback function, but it didn't. I have checked many times, the button element selected by $$ is correct.
Someone can help me?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
