### ISSUE TITLE
Chrome doesn't update UI when in background on other virtual desktop

### ISSUE THREAD

**Issue by dnjstrom** [angular/protractor#2771]
OS: OS X Yosemite 10.10.5
Browser: Chrome 47.0.2526.73 (64-bit)
Protractor: Version 3.0.0

As I was testing while doing other things on my desktop I happened to put the chrome instance that I was testing on in the background and switched to a different virtual desktop. This resulted in chrome not updating its UI leading to some pretty confusing timeout errors.

I have an overlay for logging in the user and it covers the entire UI. The following steps will cause the overlay to stay visible - blocking any further interactions to the page:

1. Run protractor
2. When the chrome instance opens, click a different window on the same screen (putting chrome in the background and unfocused)
3. Switch virtual desktops so that chrome is no longer visible.
4. Wait for your tests to timeout, or clicks to fail since the overlay is in the way

In my test the following code doesn't terminate until I give back focus to the chrome instance running the test:

```javascript
function logInAs (name) {
    return element.all(by.cssContainingText('.profiles .profile', name)).first().click().then(function () {
        // The following command timesout if chrome isn't given focus within 10s.
        return browser.wait(protractor.ExpectedConditions.invisibilityOf($('.overlay')), 10000);
    });
}
```

I might have missed it reading through the documentation, but in case it really isn't in there, it seems like "The browser must be visible during the testing" should be prominently displayed somewhere - for instance in the intro tutorial. Please correct me if I just missed it. :)

**Comment by sjelin** [comment]
I suspect that this is some chrome optimization, and there is nothing we can do (except documentation, as you suggest), but I'll investigate.

**Comment by juliemr** [comment]
This is just kind of the way webdriver works - see http://makandracards.com/makandra/12661-how-to-solve-selenium-focus-issues. We could maybe improve documentation (although really, this is a general WebDriver thing, nothing specific about Protractor), do you have a suggestion of what would be useful and not clutter our intro docs?

**Comment by scottopherson** [comment]
This bit me once before as well but it didn't take too long to figure out what was going on. Perhaps sticking something in FAQs that includes a link to that article would suffice.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since we haven't seen any activity on it and the actionable item needs discussion. @scottopherson @dnjstrom feel free to submit a PR for documentation if you think it would be helpful.
