### ISSUE TITLE
How to execute protractor JS files in Jasmine framework with java?

### ISSUE THREAD

**Issue by gauravAuto** [angular/protractor#2772]
I am new to protractor and want to execute javascript files of protractor which are in Jasmine framework from java. Is there any way to do that? Kindly help if anyone knows.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Besides creating a new process and running protractor I don't know how to accomplish this. Let's try to find a solution on one of the mediums mentioned above.
