### ISSUE TITLE
Unexpected alert open: It occurs only when I run the test together with other test

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2773]
A feature of my app includes opening an alert.

So the related protractor test handles the alert with

```
...
                       .then(function() {
				return browser1.switchTo().alert();
			}).then(function(confirmDialog){
				confirmDialog.accept();
...
```

This test is successful only when I run it alone using `fit` Jasmine's statement).

If I run the test together with an other test, then it fails.

**Comment by bitliner** [comment]
I think it is fixed (not sure, protractor is not so deterministic usually).

Maybe the reason it was failing was because the previous test was testing the text of an alert box, without calling .accept() method after the expectation.

This was causing in the next test the error `unexpected alert open`

**Comment by NickTomlin** [comment]
Glad you figured it out! Would you mind closing this issue?
