### ISSUE TITLE
Reporting in Protractor (Other than Html Reporter)

### ISSUE THREAD

**Issue by Lmahalin** [angular/protractor#2779]
hi,
 Can u people help me in finding the reporter for Protractor other than NPM Html Reporter or Npm Html Screenshot reporter or can u help me in customizing the Npm Html Reporter. I want to handle the reporting and screenshots in scripts. Please advice which is the best solution for this. As of now im using the npm html reporter
![2015-12-11 17_28_43-htmlreport html](https://cloud.githubusercontent.com/assets/15028146/11743779/3edff746-a030-11e5-8af8-0ee21dbf8ee8.jpg)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
