### ISSUE TITLE
element.all locator is not printing length / count

### ISSUE THREAD

**Issue by pgonaguntla** [angular/protractor#2780]
Hi,

I'm new to Protractor and currently in learning phase. We are looking to use this in the next project. In learning, I'm trying to print length and count for element.all  but unfortunately runner is showing error. Could you please help me where I'm missing if any. Thank you for your support.

Code:
//
var angjspage_Basicssec = require('../page/basicssection_page.js');
var angjspage_Todolist = require('../page/todosection_object.js');
describe("AngularJS Page automation",function(){	
	beforeEach(function(){
		browser.get("http://angularjs.org");		
	});

it("Verify Todo section and add Task function",function(){
		var strtodoitem = 'Angular test2';
		
		//browser.waitForAngular();
		console.log(element.all(by.css("[ng-repeat = 'todo in todoList.todos']")).count());
		console.log(element.all(by.repeater("todo in todoList.todos")).length);
	});
});

Error: 
[launcher] Running 1 instances of WebDriver
Object {
  closure_uid_696411893: 356,
  flow_:
   Object {
     events_: Object {},
     closure_uid_696411893: 1,
     activeFrame_:
      Object {
        events_: Object {},
        closure_uid_696411893: 335,
        flow_: [Circular],
        parent_: [Object],
        children_: [Object],
        lastInsertedChild_: [Object],
        pendingTask_: null,
        isLocked_: false,
        isBlocked_: false,
        pendingCallback: false,
        pendingRejection: false,
        cancellationError_: null },
     runningFrame_:
      Object {
        events_: Object {},
        closure_uid_696411893: 335,
        flow_: [Circular],
        parent_: [Object],
        children_: [Object],
        lastInsertedChild_: [Object],
        pendingTask_: null,
        isLocked_: false,
        isBlocked_: false,
        pendingCallback: false,
        pendingRejection: false,
        cancellationError_: null },
     schedulingFrame_:
      Object {
        events_: Object {},
        closure_uid_696411893: 335,
        flow_: [Circular],
        parent_: [Object],
        children_: [Object],
        lastInsertedChild_: [Object],
        pendingTask_: null,
        isLocked_: false,
        isBlocked_: false,
        pendingCallback: false,
        pendingRejection: false,
        cancellationError_: null },
     shutdownTask_: null,
     eventLoopTask_: null,
     hold_:
      { _called: false,
        _idleTimeout: 2147483647,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 8217,
        _onTimeout: [Function: wrapper],
        _repeat: [Function] },
     yieldCount_: 2 },
  stack_: null,
  parent_:
   Object {
     closure_uid_696411893: 354,
     flow_:
      Object {
        events_: Object {},
        closure_uid_696411893: 1,
        activeFrame_: [Object],
        runningFrame_: [Object],
        schedulingFrame_: [Object],
        shutdownTask_: null,
        eventLoopTask_: null,
        hold_: [Object],
        yieldCount_: 2 },
     stack_: null,
     parent_:
      Object {
        closure_uid_696411893: 352,
        flow_: [Object],
        stack_: null,
        parent_: [Object],
        callbacks_: [Object],
        state_: 'pending',
        handled_: true,
        pendingNotifications_: false,
        value_: undefined },
     callbacks_: [ [Object] ],
     state_: 'pending',
     handled_: true,
     pendingNotifications_: false,
     value_: undefined },
  callbacks_: null,
  state_: 'pending',
  handled_: false,
  pendingNotifications_: false,
  value_: undefined }

**Comment by NickTomlin** [comment]
`count()` returns a promise (you are seeing the promise object logged out), so you will need to `count().then(console.log)` to get the resolved value of the promise.

With that said, your question is better suited for StackOverflow or Gitter. In the future, Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
