### ISSUE TITLE
How to incorporate Java script methods in protractor jasmine tests

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#2785]
Do we need to use browser.executeScript?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm not sure what you mean by incorporate JavaScript methods in protractor jasmine tests. If you want to execute client side JavaScript and evaluate that in your tests then yes, you will need to use `browser.executeScript`

**Comment by vivekbrahmadandi** [comment]
Thanks @NickTomlin
