### ISSUE TITLE
Callback functions in `browser.wait` may want `browser.ignoreSynchronization = true`

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#2787]
A few people have run into problems around synchronization and `browser.wait`.  For instance, if you have some element `#elem` that appears in 2 seconds and then disappears 5 seconds later, and you write

``` js
browser.wait(protractor.ExpectedConditions.presenceOf(by.id('#elem')), 100);
```

Then your script will hang because `ExpectedConditions` waits for all timeouts to be resolved, which means that you'll wait until after the element disappears before the first check happens.  The solution here would be to do something like:

``` js
browser.wait(function() {
  browser.ignoreSynchronization = true;
  var ret = protractor.ExpectedConditions.presenceOf(by.id('#elem'))();
  browser.ignoreSynchronization = false;
  return ret;
}, 100);
```

Which is ugly but works.

We're not interested in changing the default behavior of `browser.wait` to automatically disable synchronization in callbacks, since some people want synchronization and turning it off would be confusing.  We're open to suggestions if a lot of people are having this problem though.

**Comment by juliemr** [comment]
I think this will just go away when ignoreSynchronization API is changed and converted into a method call with blocking proxy. The really confusing bit is that `ignoreSynchronization` is changed synchronously, but the commands inside `browser.wait` execute later (so they use the value of `browser.ignoreSynchronization` from the end of the test.

I don't think this is worth spending a ton of time on before blocking proxy.

**Comment by konrad-garus** [comment]
Something is still wrong. With Protractor 5.1, I have code like this:

```
// Gonna navigate away for OAuth login, disable synchronization
browser.ignoreSynchronization = true;
element(by.css('.sign-in-button')).click();

// Wait for the OAuth login page
browser.wait(ExpectedConditions.visibilityOf(element(by.id('Email'))));
```

It crashes since it cannot find Angular on the page while handling the `wait`.

Changing this code like so:

```
browser.ignoreSynchronization = true;
element(by.css('.sign-in-button')).click();

browser.wait(
      () => {
        console.log('WELL?', browser.ignoreSynchronization);
        browser.ignoreSynchronization = true;
        return ExpectedConditions.visibilityOf(element(by.id('Email')));
      }
      , 10000);
```

... I can see that "false" is printed to the console. Re-setting that to `true` makes the test proceed without an error.
