### ISSUE TITLE
feat(poll angular $digest) waitForAngular insufficient for complex apps

### ISSUE THREAD

**Issue by eahutchins** [angular/protractor#279]
I have an [open issue on ngScenario](https://github.com/angular/angular.js/issues/4814) which I think applies to protractor as well. Our app has a lot of asynchronous processing (via socket.io) and lazy-loaded states/code via ui-router, as far as I can tell `waitForAngular()` really only waits for angular processing and `$http` requests to idle. At least when I try to test our login (which works under karma/ngScenario with the polling function I implemented in the pull request) it sporadically fails under protractor:

``` javascript
// from our testing library:
module.exports.login = function login(username, password, expectFail) {

   var ptor = protractor.getInstance();

   it('should ' + (expectFail ? 'not ' : '') + 'log in', function() {
      console.log('login', username + '/' + (password || "''"));

      // navigate to '/' and wait for the login 
      ptor.get('/');

      ptor.waitForAngular();

      element(by.model('user.name')).sendKeys(username);
      if (password) element(by.model('user.password')).sendKeys(password);

      element(by.id('login-button')).click();

      ptor.waitForAngular();

      if (expectFail) {
         expect(element(by.id('login-failed-alert')).getText()).toBeTruthy();
      } else {
         expect(element(by.xpath('//div[@wt-embed="AppLauncher"]'))).toBeTruthy();
         expect(element(by.id('logout-menu-item'))).toBeTruthy();
      }
   });
}
```

With the `ptor.waitForAngular()` calls I can get the logins to pass 2/3rds of the time, without them it seldom passes.

For complex cases like this I think polling on `$digest` with positive success and failure cases and a timeout is probably the best way to go (though I'd be glad to hear of a simpler solution). How hard would this be to add to protractor?

**Comment by bvaughn** [comment]
Ping. Running into a similar issue as described in this ticket. Doesn't seem to have gotten any follow up to @yxh10 's question in September. Any word?

**Comment by yxh10** [comment]
@bvaughn Hi Brian. I have been following ng-conf. Seems that zone.js is gonna be used in Angular 2. It looks really awesome. I assume it has not been updated because it is ready for production, and Angular team may not see the need to add more features for @btford. But that is just my guess. :)

**Comment by bvaughn** [comment]
Thanks for the updated info.

**Comment by yxh10** [comment]
You are welcome! :) @bvaughn
