### ISSUE TITLE
Protractor failure when calling .toEqual

### ISSUE THREAD

**Issue by kenteroo** [angular/protractor#2794]
I have a very simple test I am using to get a Docker container working for me (turns out the container is fine). The code looks like this:

    describe('Quick test', function() {
      it('Should do something', function() {
        
        browser.get('https://app.hoopla.net/login');
        element(by.model('user.username')).sendKeys('username');
        element(by.model('user.password')).sendKeys('password');
        element(by.xpath("//button[text()='Log In']")).click();
        browser.sleep(3000);
        
        expect (element(by.xpath("//ui-view/div/div[2]/div[1]/a/div/p"))).toEqual("Manage users and teams.");
        expect(element(by.xpath("//ui-view/div/div[2]/div[2]/a/div/p"))).toEqual("Define metrics that drive your business.");
        expect(element(by.xpath("//ui-view/div/div[2]/div[3]/a/div/p"))).toEqual("Create and modify leaderboards that display metrics.");
        
      });
    });

Here's the massive error:

```Expected ({ ptor_: ({ controlFlow: Function, schedule: Function, setFileDetector: Function, getSession: Function, getCapabilities: Function, quit: Function, actions: Function, touchActions: Function, executeScript: Function, executeAsyncScript: Function, call: Function, wait: Function, sleep: Function, getWindowHandle: Function, getAllWindowHandles: Function, getPageSource: Function, close: Function, getCurrentUrl: Function, getTitle: Function, findElementInternal_: Function, findDomElement_: Function, findElementsInternal_: Function, takeScreenshot: Function, manage: Function, switchTo: Function, driver: ({ session_: ({ closure_uid_226239213: 4, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: Task: WebDriver.createSession(), parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: ({ id_: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', caps_: ({ caps_: Object({ applicationCacheEnabled: false, rotatable: false, mobileEmulationEnabled: false, chrome: Object({ userDataDir: '/var/folders/kc/d6673dzj1h74ps5nr18jqfdm0000gn/T/.org.chromium.Chromium.mxchQp' }), takesHeapSnapshot: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, version: '47.0.2526.106', platform: 'MAC', browserConnectionEnabled: false, nativeEvents: true, acceptSslCerts: true, webdriver.remote.sessionid: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', locationContextEnabled: true, webStorageEnabled: true, browserName: 'chrome', takesScreenshot: true, javascriptEnabled: true, cssSelectorsEnabled: true }) }) }), queue_: null }), executor_: ({ execute: Function }), flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), fileDetector_: null }), element: Function, $: Function, $$: Function, baseUrl: '', rootEl: 'body', ignoreSynchronization: false, getPageTimeout: 10000, params: Object({  }), ready: ({ closure_uid_226239213: 12, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: null, parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: null, queue_: null }), plugins_: ({ pluginConfs: [  ], pluginObjs: [  ], assertions: Object({  }), resultsReported: false }), resetUrl: 'data:text/html,<html></html>', trackOutstandingTimeouts_: true, mockModules_: [ Object({ name: 'protractorBaseModule_', script: Function, args: [ true ] }) ], allScriptsTimeout: 11000, getProcessedConfig: Function, forkNewDriverInstance: Function, restart: Function }), parentElementArrayFinder: ({ ptor_: ({ controlFlow: Function, schedule: Function, setFileDetector: Function, getSession: Function, getCapabilities: Function, quit: Function, actions: Function, touchActions: Function, executeScript: Function, executeAsyncScript: Function, call: Function, wait: Function, sleep: Function, getWindowHandle: Function, getAllWindowHandles: Function, getPageSource: Function, close: Function, getCurrentUrl: Function, getTitle: Function, findElementInternal_: Function, findDomElement_: Function, findElementsInternal_: Function, takeScreenshot: Function, manage: Function, switchTo: Function, driver: ({ session_: ({ closure_uid_226239213: 4, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: Task: WebDriver.createSession(), parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: ({ id_: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', caps_: ({ caps_: Object({ applicationCacheEnabled: false, rotatable: false, mobileEmulationEnabled: false, chrome: Object({ userDataDir: '/var/folders/kc/d6673dzj1h74ps5nr18jqfdm0000gn/T/.org.chromium.Chromium.mxchQp' }), takesHeapSnapshot: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, version: '47.0.2526.106', platform: 'MAC', browserConnectionEnabled: false, nativeEvents: true, acceptSslCerts: true, webdriver.remote.sessionid: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', locationContextEnabled: true, webStorageEnabled: true, browserName: 'chrome', takesScreenshot: true, javascriptEnabled: true, cssSelectorsEnabled: true }) }) }), queue_: null }), executor_: ({ execute: Function }), flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), fileDetector_: null }), element: Function, $: Function, $$: Function, baseUrl: '', rootEl: 'body', ignoreSynchronization: false, getPageTimeout: 10000, params: Object({  }), ready: ({ closure_uid_226239213: 12, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: null, parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: null, queue_: null }), plugins_: ({ pluginConfs: [  ], pluginObjs: [  ], assertions: Object({  }), resultsReported: false }), resetUrl: 'data:text/html,<html></html>', trackOutstandingTimeouts_: true, mockModules_: [ Object({ name: 'protractorBaseModule_', script: Function, args: [ true ] }) ], allScriptsTimeout: 11000, getProcessedConfig: Function, forkNewDriverInstance: Function, restart: Function }), getWebElements: Function, actionResults_: undefined, locator_: ({ using: 'xpath', value: '//ui-view/div/div[2]/div[1]/a/div/p' }) }), elementArrayFinder_: ({ ptor_: ({ controlFlow: Function, schedule: Function, setFileDetector: Function, getSession: Function, getCapabilities: Function, quit: Function, actions: Function, touchActions: Function, executeScript: Function, executeAsyncScript: Function, call: Function, wait: Function, sleep: Function, getWindowHandle: Function, getAllWindowHandles: Function, getPageSource: Function, close: Function, getCurrentUrl: Function, getTitle: Function, findElementInternal_: Function, findDomElement_: Function, findElementsInternal_: Function, takeScreenshot: Function, manage: Function, switchTo: Function, driver: ({ session_: ({ closure_uid_226239213: 4, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: Task: WebDriver.createSession(), parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: ({ id_: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', caps_: ({ caps_: Object({ applicationCacheEnabled: false, rotatable: false, mobileEmulationEnabled: false, chrome: Object({ userDataDir: '/var/folders/kc/d6673dzj1h74ps5nr18jqfdm0000gn/T/.org.chromium.Chromium.mxchQp' }), takesHeapSnapshot: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, version: '47.0.2526.106', platform: 'MAC', browserConnectionEnabled: false, nativeEvents: true, acceptSslCerts: true, webdriver.remote.sessionid: '8a0481c2-7732-4d1a-a4ca-7e64661b04c4', locationContextEnabled: true, webStorageEnabled: true, browserName: 'chrome', takesScreenshot: true, javascriptEnabled: true, cssSelectorsEnabled: true }) }) }), queue_: null }), executor_: ({ execute: Function }), flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), fileDetector_: null }), element: Function, $: Function, $$: Function, baseUrl: '', rootEl: 'body', ignoreSynchronization: false, getPageTimeout: 10000, params: Object({  }), ready: ({ closure_uid_226239213: 12, flow_: ({ events_: Object({  }), propagateUnhandledRejections_: true, activeQueue_: ({ events_: Object({ end: [ Object({ fn: Function, scope: undefined, oneshot: true }) ], error: [ Object({ fn: Function, scope: undefined, oneshot: true }) ] }), closure_uid_226239213: 803, name_: 'TaskQueue::803', flow_: <circular reference: Object>, tasks_: [  ], interrupts_: null, pending_: null, state_: 'new', unhandledRejections_: [object Set] }), taskQueues_: [object Set], shutdownTask_: null, hold_: ({ _called: false, _idleTimeout: 2147483647, _idlePrev: [object Timer], _idleNext: [object Timer], _idleStart: 1583, _onTimeout: Function, _repeat: Function }), closure_uid_226239213: undefined }), stack_: null, parent_: null, callbacks_: null, state_: 'fulfilled', handled_: true, value_: null, queue_: null }), plugins_: ({ pluginConfs: [  ], pluginObjs: [  ], assertions: Object({  }), resultsReported: false }), resetUrl: 'data:text/html,<html></html>', trackOutstandingTimeouts_: true, mockModules_: [ Object({ name: 'protractorBaseModule_', script: Function, args: [ true ] }) ], allScriptsTimeout: 11000, getProcessedConfig: Function, forkNewDriverInstance: Function, restart: Function }), getWebElements: Function, actionResults_: undefined, locator_: ({ using: 'xpath', value: '//ui-view/div/div[2]/div[1]/a/div/p' }) }) }) to equal 'Manage users and teams.'.```

    Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/kentjohnson/test.js:9:71)
        at process._tickCallback (node.js:382:9)

This code should work fine (with valid credentials). I have new installs of nodejs, jasmine, and protractor on El Capitan and I'm wondering what has changed?

**Comment by NickTomlin** [comment]
The stacktrace is quite ugly but it is actually right in this case, `element` returns a promise object so what you are actually doing by: 

```
expect (element(by.xpath("//ui-view/div/div[2]/div[1]/a/div/p"))).toEqual("Manage users and teams.");
```

is comparing that object to the string `"Manage users and teams."`. What you'll need to do is call the `getText` method on the returned element, which will resolve to a string to make your comparison: 

```
 expect (element(by.xpath("//ui-view/div/div[2]/div[1]/a/div/p")).getText()).toEqual("Manage users and teams.");
```

Or a little cleaner:

```
 let paragraph = element(by.xpath("//ui-view/div/div[2]/div[1]/a/div/p"));
 expect (paragraph.getText()).toEqual("Manage users and teams.");
```

Under the hood protractor has patched `expect` to wait for any promises it is passed and then compare the result.

---

Since this is a usage question, in the future  please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
