### ISSUE TITLE
element.click() in Firefox doesn't work when element is outside of viewport

### ISSUE THREAD

**Issue by szimek** [angular/protractor#2800]
Till now protractor 2.x.x Firefox, unlike Chrome, could find and click elements that were outside of the viewport, which was a huge advantage over Chrome. However, after upgrading to 3.0.0 it's no longer the case. Additionally, unlike Chrome, it doesn't raise any error when I call `element.click()` on an element that is outside of the viewport, it just doesn't do anything. I need to add `element.scrollIntoView()` before every `element.click()` call, but it gets more complicated if I e.g. have any element with position fixed at the top, as it can cover the element I tried to scroll to and it won't work anyway.

I'm not sure if this change was introduced in Protractor 3.0.0 itself or in the new webdriver 2.48.2.

**Comment by sjelin** [comment]
It's gotta be the new version of webdriver.  You'll have to talk to them
