### ISSUE TITLE
Upgrade lodash?

### ISSUE THREAD

**Issue by anselmbradford** [angular/protractor#2801]
Getting this warning on install:

`npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0`

**Comment by NickTomlin** [comment]
I don't see this message when installing protractor (it is at `2.x` and so are it's deps). Are you sure this is protractor and not another dependency?

**Comment by anselmbradford** [comment]
Ah, yup! Sorry it is another dependency. But regardless it sounds like the project is using a deprecated lodash version that should be upgraded at some point.

Perhaps this would help https://www.npmjs.com/package/lodash-migrate

Close this issue at will. Thanks for the quick response!

**Comment by sjelin** [comment]
Instead I removed lodash: https://github.com/angular/protractor/pull/2812

**Comment by anselmbradford** [comment]
:100:
