### ISSUE TITLE
by.repeater to match virtual repeaters

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2804]
Referencing [Virtual Repeater and Protractor](http://stackoverflow.com/questions/34443987/virtual-repeater-and-protractor) SO post, can we improve `by.repeater()` locator to also match Angular material design [virtual repeaters](https://material.angularjs.org/latest/api/directive/mdVirtualRepeat)?

Since virtual repeaters don't support tracking, aliasing and other repeater micro-syntax, I think there is no harm to this improvement. From what I understand, the change should be in only adding a `md-virtual` prefix to `findRepeaterRows()` client side script function..

On the other hand, we might argue if other material design elements/features should be supported by Protractor in general.

Thank you.

**Comment by sjelin** [comment]
I think maybe a separate repeater is in order.

Also, it might be good if there was an easy way to just add locators for arbitrary properties.  Something like `by.addSimpleLocator('virtualRepeater', 'md-virtual-repeat')`.

@juliemr, thoughts?

**Comment by juliemr** [comment]
Sorry, I hadn't read this fully. I don't think we should support md-specific things - ideally, material design (or other libraries) would export page objects for dealing with their directives/components.

**Comment by alecxe** [comment]
Okay, sure, thanks for getting back to this!
