### ISSUE TITLE
error: ECONNRESET while running protractor tests

### ISSUE THREAD

**Issue by benbracha** [angular/protractor#2810]
Hi,

We recently started to see the following error while running protractor tests:
```
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
Fatal error: protractor exited with code: 1
```

We tried to narrow down possible related changes in our environment, product versions etc - and couldn't see any correlation to the failures. It seems it just started to happen few days ago, and reproduced randomly.

Each of our tests is divided into two parts: setup, where we invoke some REST API in order to prepare the test data, and run - when we do regular selenium coding.

One thing that makes debugging hard here is that we are not sure what is the exact call protractor gets a TCP connection reset on (is it during selenium work? setup work?) The stack trace is very partial.
Is there a way to get more information here? (from protractor, nodeJS etc)?
Running protractor in verbose mode didn't help as well.

We are using the following components versions:
grunt-protractor-runner@1.1.4
grunt-protractor-webdriver@0.1.9
protractor@1.4.0

Thanks

**Comment by sjelin** [comment]
I have no idea.  I'd ask this question of stackoverflow where you're likely to find people with more TCP/REST/web knowledge.  The issue tracker on GitHub is really only for bug reports/feature requests anyway.
