### ISSUE TITLE
Protractor snippets

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2813]
While answering and asking questions on SO, I've seen and created multiple short snippets for various tasks. For example:

 * http://stackoverflow.com/a/34502670/771848
 * http://stackoverflow.com/a/27908252/771848
 * http://stackoverflow.com/a/21994788/771848
 * etc

Do you think it would be a good idea to have something like a `Snippets` page on http://angular.github.io/protractor/#/ where we can add some code samples for common/popular tasks? 

I really think real-world examples is something we are missing documentation-wise. Thanks.

**Comment by sjelin** [comment]
Sure, I think that's reasonable.  Just add a file at 'docs/snippets.md` and a link to it around [here](https://github.com/angular/protractor/blob/master/website/index.html#L80).  The website generation script will take care of the rest.

**Comment by NickTomlin** [comment]
I think this is a great idea (it would help with a lot of common questions).

**Comment by chrisjlee** [comment]
This is awesome! We need more examples

**Comment by zalow517** [comment]
+1

**Comment by jags14385** [comment]
What kind of Snippets are expecting here? Depending on which snippets , i would create a PR around it.

**Comment by chrisjlee** [comment]
@jags14385 Probably any repetitive modular tasks one would do frequently. Login, click a button, select an iframe, scroll, etc.

**Comment by jags14385** [comment]
All right, That helps. Will add those.

**Comment by juliemr** [comment]
Closing in favor of https://github.com/angular/protractor/issues/3376
