### ISSUE TITLE
multiCapabilities and jasmine focused tests

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2814]
Referencing [multiCapabilities and jasmine focused tests](http://stackoverflow.com/questions/34366223/multicapabilities-and-jasmine-focused-tests).

Is it possible to tell protractor/jasmine to only run capabilities having [focused tests](http://jasmine.github.io/2.1/focused_specs.html) in `specs`? Thank you.

**Comment by sjelin** [comment]
I don't think so.
