### ISSUE TITLE
How to get Safari working with Protractor

### ISSUE THREAD

**Issue by roshanhadal** [angular/protractor#2816]
I did lot of research and debugging but couldn't get the Safari browser working with my Protractor tests. I get the below error message. I was not able to get help online. Most of the docs hint that Safari should work automatically as it is built in. Not sure what I am missing. I have installed the Safari 2.48.0 browser extension. Is there any protractor config that needs to be done?

<img width="1253" alt="screen shot 2015-12-30 at 6 06 00 pm" src="https://cloud.githubusercontent.com/assets/8522615/12050854/cf6ad5c0-af20-11e5-8e9c-87c10512abac.png">

**Comment by NickTomlin** [comment]
This is an issue with selenium and SafariDriver. I was able to resolve this by disabling and then re-enabling the extension and restarting closing safari. My gut is that there is some issue with "trusting" the extension to make external connections but i'm not sure if that's exactly it.

The relevant issues are [selenium/1313](https://github.com/SeleniumHQ/selenium/issues/1313) (which is closed but should probably be re-opened) and [selenium/1185](https://github.com/SeleniumHQ/selenium/issues/1185)

**Comment by ukyomatterport** [comment]
I have the same problem.  Latest version of everything Protractor 2.1.0, MAC, Yosemite 10.10.5, Safari 9.0.2, selenium_standalone_server_2.48.2, webdriver extension for Safari 2.48.   I reinstall, close, clear history&cache, and reboot system, too.  Protractor still cannot launch Safari.

**Comment by NickTomlin** [comment]
@ukyomatterport please see the selenium issues referenced or ask a question on StackOverflow. Thanks!
