### ISSUE TITLE
by locator for ng-data-message directive

### ISSUE THREAD

**Issue by ashishbmehta** [angular/protractor#2817]
Hello everyone,

Need help with accessing the ng-data-message directive through protractor. Code is something like...
`<div id="name_error"...>
     <div data-ng-message="required"> Name is a required field </div>
</div>`
How to I access this message through protractor code?

Thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

That said, you can use a simple attribute selector, `element('[data-ng-message="required"]')` or [`cssContainingText`](https://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.cssContainingText): 
`element(by.cssContainingText(['div',  'Name is a required field'));`

**Comment by ashishbmehta** [comment]
Thank you..still holding a learner's permit :-)
