### ISSUE TITLE
Is there a way to stop protractor after it throws a timeout exception?

### ISSUE THREAD

**Issue by bitliner** [angular/protractor#2819]
As I also published [here](http://stackoverflow.com/questions/34603162/is-there-a-way-to-stop-protractor-after-it-throws-a-timeout-exception),

is there anyway to prevent protractor continue running test after a timeout exception?

Otherwise it is very difficult to understand why or where a test spec timed out.

As an example, it is impossible to get some insights from the logs on where a spec timed out.

If protractor would stop just after a timeout exception then looking at the logs would help to understand the problem in a much easier way.

Handling a timeout exception at every promise is also quite horrible to do.

**Comment by sjelin** [comment]
Nope.  Why not use `fit` or something like it to rerun just the test which timed out?

**Comment by bitliner** [comment]
I will test [this solution](https://github.com/Updater/jasmine-fail-fast).

Why not doing that? Because it would be a worst UX, because the solution you propose requires more time, and it is not guaranteed that using `fit` I can replicate the timeout.

If you would use protractor you would realize how much painful it is using just `fit` or `fdescribe`

**Comment by sjelin** [comment]
Man, I was just asking a follow up question to figure out if this needed to be a feature request.  Anyway, sounds like you found a solution.
