### ISSUE TITLE
Pause is in beta; what could be another way of debugging protractor scripts?

### ISSUE THREAD

**Issue by mmorenoivy** [angular/protractor#2824]
I am still new to protractor and angularjs. I am trying to debug my script and used browser.pause(), though it gave me an error message: 
"Starting webdriver debugger in a child process. Pause is still in beta, please report issues at github.com/angular/protractor"
Thanks for your response in advance.

**Comment by sjelin** [comment]
That's not an error message.  That's just some information

**Comment by faminram** [comment]
For me after that message, it still continues but the test goes past the pause, finishing the test and closing the browser.

it's broken after I updated to latest protractor configuration. (not sure if this is actually the reason but previously it was working for me.)

I did try by using the different port no but no success. Any idea?
