### ISSUE TITLE
How to test for an element inside a directive

### ISSUE THREAD

**Issue by ryan-wong** [angular/protractor#2827]
How would I be able to access an element by id or by css inside a directive? Every tutorial seems to dodge the question with no solution to do this.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


There's no magical way to do this, you'll just need to identify the structure of your directive (does it have a css class that is unique to it?) and select it through the normal means.
