### ISSUE TITLE
Protractor - Applitools Tests in Mac Giving Error - result was not received in 10 seconds

### ISSUE THREAD

**Issue by manoj00097** [angular/protractor#2829]
Our CI runs protractor - applitools tests on Mac machine (Chrome browser). The script is hosted in a test machine which triggers the suite to run on a remote Mac. The Mac runs a selenium server which handles selenium requests. Off late, some of the tests have been failing with error 'unknown error: result was not received in 10 seconds'. This has come up only recently. Tests work fine on Windows and iOS.

Details of the error:

Failures:
Message:
[31m Failed: unknown error: result was not received in 10 seconds
(Session info: chrome=46.0.2490.80)
(Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 20.12 seconds Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50' System info: host: 'lab-imac.local', ip: '10.70.210.97', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_65' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/sc/9n_x6lvs7mb0cvx22znsy86w0000gn/T/.org.chromium.Chromium.tVh2Ny}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=46.0.2490.80, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 13bd640cff1fe4c6ca2083526cf92579[0m Stack: UnknownError: unknown error: result was not received in 10 seconds (Session info: chrome=46.0.2490.80) (Driver info: chromedriver=2.15.322455 (ae8db840dac8d0c453355d3d922c91adfb61df8f),platform=Mac OS X 10.11.1 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration or timeout: 20.12 seconds Build info: version: '2.45.0', revision: '5017cb8', time: '2015-02-26 23:59:50' System info: host: 'lab-imac.local', ip: '10.70.210.97', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.1', java.version: '1.8.0_65' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={userDataDir=/var/folders/sc/9n_x6lvs7mb0cvx22znsy86w0000gn/T/.org.chromium.Chromium.tVh2Ny}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, version=46.0.2490.80, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}] Session ID: 13bd640cff1fe4c6ca2083526cf92579 at new bot.Error (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108:18) at Object.bot.response.checkResponse (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\response.js:109:9) at D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:379:20 at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) at process._tickCallback (node.js:368:9) From: Task: at PromiseFactory._promiseFactoryFunc (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:73:25) at PromiseFactory.makePromise (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.utils\src\PromiseFactory.js:36:25) at Object.ViewportSize.setViewportSize (D:\Users\Administrator\node_modules\eyes.protractor\src\ViewportSize.js:118:31) at Eyes.setViewportSize (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:333:29) at Eyes. (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.sdk\src\EyesBase.js:704:32) at D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:75:17 at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) at process._tickCallback (node.js:368:9) From: Task: at PromiseFactory._promiseFactoryFunc (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:73:25) at PromiseFactory.makePromise (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.utils\src\PromiseFactory.js:36:25) at EyesBase.startSession (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.sdk\src\EyesBase.js:693:37) at Eyes. (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.sdk\src\EyesBase.js:595:25) at D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:75:17 at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) at process._tickCallback (node.js:368:9) From: Task: at PromiseFactory._promiseFactoryFunc (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:73:25) at PromiseFactory.makePromise (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.utils\src\PromiseFactory.js:36:25) at EyesBase.checkWindow (D:\Users\Administrator\node_modules\eyes.protractor\node_modules\eyes.sdk\src\EyesBase.js:580:37) at callCheckWindowBase (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:179:47) at D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:198:20 at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) at process._tickCallback (node.js:368:9) From: Task: at Eyes.checkWindow (D:\Users\Administrator\node_modules\eyes.protractor\src\Eyes.js:197:27) at Object. (D:\Users\Administrator\CI\Perforce\verification\Elements\specs\Test\test-spec.js:52:14) at D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:96:23 at new wrappedCtr (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:2468:26) at controlFlowExecute (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:82:18) at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) at process._tickCallback (node.js:368:9) From: Task: Run it("load page") in control flow at Object. (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:81:14) at attemptAsync (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1819:24) at QueueRunner.run (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1774:9) at D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1801:16 at D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1745:9 at D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:18:5 at goog.async.run.processWorkQueue (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:124:15) From asynchronous test: Error at Suite. (D:\Users\Administrator\CI\Perforce\verification\Elements\specs\Test\test-spec.js:47:5) at addSpecsToSuite (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:743:25) at Env.describe (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:713:7) at jasmineInterface.describe (D:\Users\Administrator\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:3219:18) at Object. (D:\Users\Administrator\CI\Perforce\verification\Elements\specs\Test\test-spec.js:18:1)

**Comment by NickTomlin** [comment]
Hi there! Sorry to hear you are experiencing issues with your integration tests.

Unfortunately timeouts like this are extremely common in the selenium world. As such, there's nothing we  can do to investigate the your protractor setup with a third party provider from the stacktrace you've given. To debug the real issue, please [ask a question on StackOverflow with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help (i'd also suggest reaching out to aplitools support, it sounds like something may be wrong there). 

If that search reveals an issue with Protractor please re-open an issue or PR with a reproducible test case. Thanks!

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
