### ISSUE TITLE
Capture Text from Promise to use in sendKeys

### ISSUE THREAD

**Issue by scruffymarc** [angular/protractor#2830]
Hello,

I'm using the following code to capture a value from an element and use that element in a sendKeys command later on in the code.

```
getPort = function(){
	$('#Window').element(by.id('Port')).getAttribute('value').then(function(text){
			console.log(text);
			return text;
		});
		};
var port = getPort();
```

I later on (in the same "it" block) try and call a sendKeys

```
$('#Window').element(by.id('LinkedIPAddress')).sendKeys('website:' +port);
```

However the sendKeys command always says the variable port is an undefined value, the console log from the function displays the correct information so I know it is capturing the correct info.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Promises are asynchronous, so you will need to make your subsequent call within the block of your function that retrieves the port to be able to use the value.
