### ISSUE TITLE
Protractor 3.0.0 does not find angularTestResult.ver for Angular 1.3.8?

### ISSUE THREAD

**Issue by Tsux** [angular/protractor#2832]
I read in a previous issue and FAQs, protractor supossed to have support for Angular 1.0.6/1.1.4 an higher versions. 
I 'm using protractor 3.0.0, trying to test AngularJS v1.3.8 app that lives in html tag seems Protractor cannot find Angular version inside angularTestResult protractor object.
Since I read protractor team was about to add some special capabilities to get this working on Angular 2, I'm wondering if these new capabilities could be causing conflicts with angular 1.x.x versions. Any info about it?
OS: Windows 10
Browser: Chrome
Tried to run tests with Selenium: webdriver-manager, selenium standalone server 2.48, Chromedriver. Problem persists.
I'm printing the follwing error from protractor:
 Failed: Angular could not be found on the page http://localhost:3000/#/login : angular never provided resumeBootstrap 
Looking for Ng App at html. Mean Reason is Angular Version obtained:  undefined

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
@Tsux there should be no issues with angular 1.3 apps - we've added capabilities for Angular2, but those are in addition to still working with angular 1.3. The important error message is that "angular never provided resumeBootstrap" - I'm not sure where the "Mean Reason" error message is coming from. That looks like it may be from some framework you're using on top of Protractor?

Please post a link to your question on SO or Gitter and we'll take a look there.
