### ISSUE TITLE
Error while sending long string (155+ characters) to textarea field using sendKeys()

### ISSUE THREAD

**Issue by bhaskarpare** [angular/protractor#2833]
I am getting similar to below error when I enter long text using sendKeys in text area.. any idea what I might be doing wrong or is it some kind of limitation?

[10656:4184:0112/173940:ERROR:latency_info.cc(157)] RenderWidgetHostImpl::OnSwap
CompositorFrame, LatencyInfo vector size 107 is too big.

Please note, the text is getting entered in the fields, its just this error which shows up on command prompt which is bothering me

Thanks for your help!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by juliemr** [comment]
Looks like an issue coming from Chrome (https://src.chromium.org/viewvc/chrome/trunk/src/content/browser/renderer_host/render_widget_host_impl.cc). I can't reproduce it - I tried with strings up to length 10,000. At 20,000 my test timed out, but no error like yours.

Please make sure your chrome version is up to date, and if things continue to fail, post an issue to [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/help).
