### ISSUE TITLE
[Question] Has Anyone figured out a way to log chromedriver in protractor?

### ISSUE THREAD

**Issue by g0rd** [angular/protractor#2837]
Since there is no love for protractor on StackOverFlow. I thought I might try here.

These solutions don't cut it for me: 
http://stackoverflow.com/questions/31662828/how-to-access-chromedriver-logs-for-protractor-test/31662935

I am trying a lot of things. Any help would be appreciated!

**Comment by juliemr** [comment]
This is a feature request: https://github.com/angular/protractor/issues/2402

I've also posted an additional answer on SO for how to do this right now.
