### ISSUE TITLE
How to properly mock backend with protractor ?

### ISSUE THREAD

**Issue by sboudouk** [angular/protractor#2839]
Hi, i'm totally new to protractor and AngularJS in general. I searched similar issues, but i still have some questions. Is there a clean way to mock backend with protractor ? What do you guy using, and what's considered as "Good Practice" ? I had read that @juliemr said in a similar issues that protractor is made to work with a real backend. ('a hooked backend' like she said.)

I need to mock up a simple server that answer with json + an upload server. How do you guys manage that ? I don't know if this is a real issues but I did not found anything similar to this explained with clarity.

Thanks for future answers. (Don't know if this is important, but i'm using protractor with gulp yeoman.).

**Comment by NickTomlin** [comment]
Hi there and welcome :smile: 

 You normally would _not_ mock a backend for integration tests. That sort of mocking is better handled at the unit level with something like `$httpBackend` in your unit tests.

That said, it is better to explore this question on a medium devoted to debugging/usage like StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help. This helps us keep the issue queue focused on bugs and features and should get you your answer faster.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by sboudouk** [comment]
Thanks for your answer Nick, i'm closing this.
