### ISSUE TITLE
No CLI argument for no colors

### ISSUE THREAD

**Issue by Guuz** [angular/protractor#284]
Hello,

There is an option in the conf file to not show colors in the output. However I can't seem to enable this with a command line argument.
Looking at https://github.com/angular/protractor/blob/master/lib/cli.js I don't think this is possible at the moment.

If this is fixed we need to enable this in https://github.com/teerapap/grunt-protractor-runner and then the world is a better place :)

Thanks!

**Comment by ORESoftware** [comment]
need an environment variable for this instead of command line arg, would be much better, child processes also need no colors, so env var is much more convenient.

anyone? thx
