### ISSUE TITLE
Where is the Accessibility plugging in Protractor 3.0

### ISSUE THREAD

**Issue by FJLopezGarcia** [angular/protractor#2841]
Hi all, 
Where is the Accessibility plugging (and others) in Protractor 3.0 version? 
They should be under node_modules/protractor/plugins path

Protractor 2.5.1 version is the last one with the plugins folder.

Regards
Javi

**Comment by juliemr** [comment]
As mentioned in our changelog, https://github.com/angular/protractor/blob/master/CHANGELOG.md#breaking-changes, plugins have been moved to their own repos.

**Comment by FJLopezGarcia** [comment]
Great, Thanks a lot!!
