### ISSUE TITLE
finding element/attributes with : (colon) in the name

### ISSUE THREAD

**Issue by GlennQuirynen** [angular/protractor#2842]
Hi,

please find below a sample of an html element which is generated.
```javascript
<li ex:tab-context-id="portfolio" ng-class="['ApplicationTab', { 'ApplicationTab--isActive': exTabBarTabCtrl.active }]" ng-show="tab.visible" ng-repeat="tab in exTabBarCtrl.tabs track by tab.tabUrlId" ex:tabbar-tab-config="tab" ex:tabbar-tab-closable="true" class="ng-isolate-scope ApplicationTab ApplicationTab--isActive   Hover">
<a class="ApplicationTab__link ng-scope" ui-sref="portfolio({&quot;pctx&quot;:&quot;wDgys6G1ckOQi1H9OMK0PgEAAAA=&quot;})" href="#/portfolio/wDgys6G1ckOQi1H9OMK0PgEAAAA%3D"><span class="TabContext ng-binding" ng-bind="exTabBarTabCtrl.tabLabel.nameId | translate">Portfolio</span><!-- ngRepeat: detail in exTabBarTabCtrl.tabLabel.details | orderBy:'order' --><span class="ApplicationTab__detail TabContextDetail ng-binding ng-scope" ng-repeat="detail in exTabBarTabCtrl.tabLabel.details | orderBy:'order'" ng-bind="detail.value | translate">000605</span><!-- end ngRepeat: detail in exTabBarTabCtrl.tabLabel.details | orderBy:'order' --></a><a class="ApplicationTab__closeIcon ng-scope" ng-click="exTabBarTabCtrl.closeTab()"><div class="Icon"><svg class="Icon__svg"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#Icon__cross"></use></svg></div></a></li>
```
I would like to select in the li element the attribute value of ex:tab-context-id, being portfolio.
I have a reference in code to the li element.

but if I then use eg getAttribute("ex:tab-context-id"), the code returns null.

It seems like the ex: is not supported.

Is there a way to get this attribute value returned?

**Comment by juliemr** [comment]
This is a chromedriver bug - https://bugs.chromium.org/p/chromedriver/issues/detail?id=474

It has been fixed but is not yet in the latest release of chromedriver. The fix will be in Protractor once we release a version that uses chromedriver 2.21, whenever it's available.

**Comment by GlennQuirynen** [comment]
Hi,

thanks for your quick and clear reply.
We will follow closely the release of Chromedriver 2.21.

Is the presence of a colon in the elementName/Tagname not supported as well?
Taking following example of an htmlElement

```javascript
<ex:tabbar class="ng-isolate-scope"><div id="tabBar" class="ApplicationTabsBar">/div></ex:tabbar>
```

using element(by.tagName("ex:tabbar")) is working fine, but ofcourse doet not allow me to specify further selection criteria (like classname or other attributes)

using element(by.css("ex:tabbar")) does not work.
using element(by.xpath("//ex:tabbar")) does not work either.

In both cases, following error is thrown: "An invalid or illegal selector was specified is the error."

Thanks,

**Comment by GlennQuirynen** [comment]
Hi,

I found a solution for the problem with the colon (:) in the elementName, when using element(by.css("ex:tabbar"))

You can escape the colon (:), with 2 backslashes.

using element(by.css("ex\\:tabbar")) works fine.

**Comment by nathan-grant** [comment]
ChromeDriver 2.21 is out now (as of 01-28-16) which includes the fix for 474. It also has some others fixes I am interested in.  Is moving forward in version an official capacity or can we submit a PR for that?

**Comment by juliemr** [comment]
We always update our dependency versions before the next release. Expect
that coming soon!

**Comment by juliemr** [comment]
Protractor 3.1.0 with ChromeDriver 2.21 is now released.
