### ISSUE TITLE
No element found using a locator when extracting inner value from span

### ISSUE THREAD

**Issue by mmorenoivy** [angular/protractor#2844]
Hi Everyone,
I am very new to Protractor and building an automation script from scratch. I am currently testing a non Angular app, and this is the HTML:

<div class = "topNavRight">
<span id= "welcome">
 <em>Hi</em>
","
<strong>
<span id="user"> MyName </span>
</strong>
"|"
//there's more HTML here
</div>

My protractor code is:
var greet = element(by.id('user'));
expect(greet.getText()).toBe('MyName');

I have already done this code:
var greet = element(by.id('welcome')).element(by.id('user'));
expect(greet.getText()).toBe('Hi, MyName'); // or toEqual("Hi, MyName");

But I am still getting an error message saying Failed: No element found using locator: by.id("welcome")
or
Failed: No element found using locator: by.id("user")

Hoping to hear from all of the experienced protractor testers. Thanks in advance!

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
