### ISSUE TITLE
when using hamburger.click(), there doesn't seem to be an extension for hamburger.chomp()

### ISSUE THREAD

**Issue by jonzfisher** [angular/protractor#2847]
Yes, hi; I've been using protractor for a project of mine recently, and it's been wonderful! I think it be much more enjoyable for the developer to have custom extensions of the .click() action method such as .chomp(), .tinyBiteBecauseYoureOnADiet(), .tap(), .sendBackBecauseYouOrderedWellDone, .removeUnwantedToppingYouSpecificallyRequestedTheWaiterToLeaveOff 

Thank you! And thanks for you hard work!

**Comment by NickTomlin** [comment]
Hi there, glad you've been enjoying Protractor :smile: 

I'm having a bit hard time understanding your request, specifically how these custom extensions would function. Could you reword with more generic language and then provide a specific example with some more supporting code?

What i'll assume you are asking is to add some custom methods to the [`ElementArrayFinder`](https://angular.github.io/protractor/#/api?view=ElementArrayFinder) to make it more natural to write tests. 

I think this is an interesting idea, but I might suggesting using [page objects](https://github.com/angular/protractor/blob/master/docs/page-objects.md) to "bundle" functionality together instead. That way you can write things in a more declarative way without monkey patching the framework itself. E.g.

```
let BurgerPage = require(./page-objects/burger-page')

describe('Burger Page', () => {
  it('allows users to eat a burger', () => {
    BurgerPage.get()
    // perform whatever test/page specific actions necessary
    BurgerPage.chomp()
  })
})
```

**Comment by jonzfisher** [comment]
Thank you! So helpful!

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
