### ISSUE TITLE
Protractor Error cannot find module

### ISSUE THREAD

**Issue by brobee** [angular/protractor#2851]
Hi,

I know that, it would be a duplicate issue but I still cannot solve this problem...

I installed every properly, e.g. npm install -g protractor. My tests are run fluently, but when I want to use page object, I got the cannot find module problem.

My system variables: 
path contains the following: C:\Users\XXX\AppData\Roaming\npm

ANy advice would be appreciated!

Thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
