### ISSUE TITLE
Element not visible even after using browser.wait()

### ISSUE THREAD

**Issue by Leo-G** [angular/protractor#2852]
I am using ng-hide and ng-show for my login page. While testing I get element not visible, I tried browser.wait() but it says mulitple elements found.

My code is available at 

https://github.com/Leo-G/Flask-Scaffold/blob/develop/app/templates/login.html

Any help will much appreciated.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
