### ISSUE TITLE
Add $x shortcut for element(by.xpath())

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#2855]
Similarly to the `$` which is used for `element(by.css())` and `$$` for `element.all(by.css())`, please consider adding shortcuts for the `by.xpath()` locators (similar to what we have on the Chrome Dev Tools console):

    $x -> element(by.xpath())
    $$x -> element.all(by.xpath())

Thank you.

**Comment by NickTomlin** [comment]
Great suggestion! The devtools only has [`$x` ](https://developer.chrome.com/devtools/docs/commandline-api#xpath) (at least that I can see).  Are you suggesting we do something akin to making `$$x` function like `element.all(by.xpath()).first()`?

**Comment by alecxe** [comment]
@NickTomlin `$x` for the `element(by.xpath())`, `$$` for the `element.all(by.xpath())` similar to what we have for the CSS: `$` and `$$`. Thanks.

**Comment by NickTomlin** [comment]
@alecxe ah :facepalm:, makes complete sense. I was hung up on the Dev Tools implementation and not the selenium one.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this per the discussion in https://github.com/angular/protractor/pull/2889.

**Comment by alecxe** [comment]
@NickTomlin would be nice to have, but, I agree, that is controversial. Thank you!
