### ISSUE TITLE
How to debug with node-inspector using breakpoints in Chrome DevloperTool

### ISSUE THREAD

**Issue by vinaykumarkonda** [angular/protractor#2856]
Not worked with below one
$ npm install -g node-inspector
$ node --debug-brk node_modules/protractor/lib/cli.js protractor.conf.js

# Open a new terminal and run the node inspector:
$ node-inspector

# Open your browser with this url: http://127.0.0.1:8080/debug?port=5858

I can set breakpoints in cli.js and test it using step-over, step-in & step-out options. But in spec.js can't
Also, in WebStrom ide the same i can't debug spec.js

When i do so, browser will hang.

Can you please suggest me how to debug without using pause()/debugger()

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
