### ISSUE TITLE
Protractor Times Out On Very Long Tests

### ISSUE THREAD

**Issue by kariasbolster** [angular/protractor#2865]
Hi, I have encountered a problem and I'm not sure if this is related to protractor or not and I don't know if its okay for me to post it here. Anyway I will be asking it here maybe I can find some answers. So, I am running very long tests which usually takes 30 to 40 mins long. Sometimes between the 30th and 40th minute, during an API request, the API won't return a response. However when I resend the request in the front-end (by this point the test is already failed) the API responded. At first I was thinking it was a backend performance issue, but when I resend the request in the front-end the API returns fine which leaves me asking if this is a protractor issue, or memory in my machine issue. I hope I can gain some positive answers. Thank you.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by pedrro** [comment]
I had a similar error in my project too, my tests are not so long, it's just 2 or 3 minutes to run a E2E test, but with some assertions, sometimes the protractor/jasmine give me the error     ```    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL. ``` I fixed it splitting the test

**Comment by sjelin** [comment]
You can also adjust the timeout length in the config file
