### ISSUE TITLE
Alt attribute in image tags in protractor

### ISSUE THREAD

**Issue by patproc** [angular/protractor#2870]
hi, i am new to protractor and need some help. i have a scenario where i need to assert if image have alt attribute. please see the following eg:

(tag)img class="img-responsive" itemprop="logo" src="/1.5.19.0-SNAPSHOT/assets/ch-logo.png" alt="CHI">

expect(element(by.css(a.brand-logo img.img-responsive))).toBe(true);

(tag)img src="/1.5.19.0-SNAPSHOT/assets/cp-logo-small.png">

expect(element(by.css(img[src="/1.5.19.0-SNAPSHOT/assets/cp-logo-small.png"]))).toBe(true);

when i run the above two assertions they both are passing, but i want first to be pass and second to be fail as there is no alt attribute.

my aim is to get the all <img tags on webpage and assert that they must have alt attribute (no matter what text in it or empty)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
