### ISSUE TITLE
Visible mention of Selenium Docker images

### ISSUE THREAD

**Issue by alexntt** [angular/protractor#2876]
Hi,

I think it'd be nice to have some very visible reference to https://hub.docker.com/r/selenium/ somewhere in the "getting started"-type docs- and any other easy ways to avoid having to set up manually Selenium + browsers, which can be intimidating if you are getting started with browser testing.

Cheers,

Álex

**Comment by NickTomlin** [comment]
I don't personally use docker with Protractor, but this sounds like something that would be a good fit for either the [getting started](https://github.com/angular/protractor/blob/master/docs/getting-started.md) or [FAQ](https://github.com/angular/protractor/blob/master/docs/faq.md) docs. Perhaps a small blurb that essentially says "If you are manually configuring selenium through Docker you will find the Selenium Docker images helpful". My gut is that this is a less than typical flow for most users, so I'd want to make sure it doesn't break the flow of the getting started documentation too much.

Would you be up for submitting a PR?

**Comment by alexpdp7** [comment]
Meh, after coming home and trying to write the PR, I'm not so sure that the Protractor documentation really needs this (after all, dockerized Selenium's real use case is continuous integration servers). I'd take this to the Selenium guys who should really feature the Docker images more prominently.

Feel free to close this.

**Comment by NickTomlin** [comment]
Gotcha. I think that makes a lot of sense. Thanks for your work investigating!

**Comment by alexpdp7** [comment]
Yes, alexntt = alexpdp7, sorry!
