### ISSUE TITLE
Tests passing with expect statements asserting nonexistent element to be defined 

### ISSUE THREAD

**Issue by realisation** [angular/protractor#2878]
I have a test that is passing even though I am asserting that a nonexistent element like A^d><E$xC#@ should be defined by css. 

Troubling!

**Comment by sjelin** [comment]
Please show us the test/config file

**Comment by realisation** [comment]
Turns out it was expecting elements on the dom `toBeDefined`. Didn't know what that was, evidently it will return true no matter what. 

Instead, use `.isPresent()).toBe(true)`
