### ISSUE TITLE
Local webdriver-manager update required for npm test

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#2883]
In order to run `npm test`, the local package of `webdriver-manager` needs to be updated to download `selenium/chromedriver` for the direct connect test. A possible solution: `test.js` should call the local `webdriver-manager` to update itself right before running the test.

**Comment by cnishina** [comment]
Or it could be added to the pretest script in the `package.json`...

**Comment by NickTomlin** [comment]
I usually do this in `test` or `pretest`, since there's no noticeable slowdown if the binaries are already there and it's less overhead for contributors to my projects. I'm :+1: on doing it in `pretest` unless there's a reason that is a bad thing.

**Comment by cnishina** [comment]
In addition, lodash and marked are also required for the unit tests. I'll see if I can `npm install` the `website/package.json` in the pretest.

**Comment by sjelin** [comment]
Why not just add them as devDependencies?

**Comment by cnishina** [comment]
Running the `npm install` for the `website/package.json` would avoid maintaining two places of lodash and marked versions.

**Comment by sjelin** [comment]
As per discussion offline, devDependencies is still the right idea

**Comment by cnishina** [comment]
Done with 4b792280cc4c7f11b652e67123610c2b1880acf5.

**Comment by cnishina** [comment]
I need to change this... somehow my commit did not have the changes @sjelin and I discussed.

**Comment by cnishina** [comment]
Done with 7ce4919.
