### ISSUE TITLE
Protractor sends out the event locationChangeSuccess

### ISSUE THREAD

**Issue by Tiagojdferreira** [angular/protractor#2891]
I am trying to test a modal that close on '$locationChangeSuccess'. The problem is, when I use functions like browser.wait they close my modal. I suppose they communicate using the same event or they somehow cause it to de sent.

My test case:
````
describe('ngDialog open', function() {
  beforeEach(function() {
    browser.get('http://localhost:3000/example/index.html');
  });

  it('should open from functions', function() {
    element(by.css('#via-service')).click();

    var EC = protractor.ExpectedConditions;
    browser.wait(EC.visibilityOf(element(by.css('.ngdialog'))), 5000);

    element(by.css('.data-passed-through')).getText()
      .then(function(text) {
        expect(text).toBe('Data passed through: from a service');
      });
  });
});

````

**Comment by NickTomlin** [comment]
I'm not quite sure what the issue is from the example you've given. `browser.wait` should not affect the state of your application, so I suspect there's something more going on here. It's going to be hard to debug without more context on your application. Could you provide a standalone example (either in a repo or a gist) that I can use to reproduce this?

Thanks!

**Comment by Tiagojdferreira** [comment]
Clone ngDialog, and in the file:
https://github.com/likeastore/ngDialog/blob/master/example/index.html#L164
Add:
````
closeByNavigation: true,
````
Then do:
````
npm install
node server
npm run protractor
````

**Comment by Tiagojdferreira** [comment]
closeByNavigation uses getRouterLocationEventName which makes the modal listen to either ```' $stateChangeSuccess' ``` or ```'$locationChangeSuccess'```. If you comment out the line of locationChangeSuccess the popin no longer closes in protractor (but it also no longer supports the old angular router).
https://github.com/likeastore/ngDialog/blob/ebd60f05dce748451940613b965c76bf206c70e2/js/ngDialog.js#L442

**Comment by NickTomlin** [comment]
Thanks for the example! 

Hmm, I still don't see what `browser.wait` has to do with this. My suspicion is that it is some race condition or another element of your application (like [this](https://github.com/likeastore/ngDialog/blob/master/example/index.html#L364) timeout that closes the dialog after a few seconds?).

For helping debugging, please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor).

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by Tiagojdferreira** [comment]
If that was the case, setting the variable closeByNavigation to true would
have no impact. In fact, just commenting out the $locationChangeSuccess
sufices to prevent the popin to automatically close  (that's why I think
the problem comes from something that dispatches that event)

**Comment by Tiagojdferreira** [comment]
And I did not have this kind of problems opening the example and navîgating around, so I suspect it must be something related to protractor that causes it. I'll try to look at it again in more detail during this week. Thanks for your fast response :)

**Comment by NickTomlin** [comment]
Yeah this is definitely interesting! This _could_ be an issue with the way we decorate [`$timeout`](https://github.com/angular/protractor/blob/master/lib/protractor.js#L554) but it's hard to say for sure. I think focusing the debugging on Gitter/SO is the most effective route. Once that's done (and if we've figured out it is an issue with protractor core) we can re-open this issue or create a PR to solve it. Does that sound good to you? :smile:

**Comment by Tiagojdferreira** [comment]
:+1:
