### ISSUE TITLE
Tests fail on upgrading to Protractor 3.0.0

### ISSUE THREAD

**Issue by manoj9788** [angular/protractor#2897]
I have been using version 2.5.1 until now and upgraded to 3.0.0 and noticing that my tests fails. Did anyone face the same ?
I get a - Failed: Cannot read property 'click' of undefined error - and that's my first user operation via Protractor API.
I have done nothing to my test setup except changing my package.json file for Protractor version.

I have raised this on Gitter, have got no comments hence raising here as an issue.

**Comment by cnishina** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by manoj9788** [comment]
If you could read the last line, I have done what you have mentioned.
