### ISSUE TITLE
Does protractor have support to tap or click on invisible elements on native apps?

### ISSUE THREAD

**Issue by sridevi-15** [angular/protractor#2901]
Hi, 
I am able to run protractor test against ios simulator and ios device on native app, but I have issues with identifying invisible elements i.e the element is false when I check xpath in appium inspector. Can Protractor coders help if you have any API to identify invisible elements. Can I use something like 'mobile: tap' in protractor. It worked with 'mobile: tap' with java  code in selenium+ APPIUM+ java framework. It will be great if you can provide information whether protractor has support for this. Also can you please let me know if protractor has full support for native app testing both on simulator and device

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
