### ISSUE TITLE
Protractor/Grunt: Sauce labs proxy with grunt-sauce-connect-launcher

### ISSUE THREAD

**Issue by chitwant82** [angular/protractor#2903]
If I use Sauce labs sauce-connect script, before running scripts I am able to run localhost url on Sauce lab machine

Successful case Logs:

23:48:48.669 INFO - Launching a standalone server
Setting system property webdriver.firefox.logfile to c:\log\firefox.log
Setting system property webdriver.server.session.timeout to 0
Setting system property http.proxyHost to maki79213.miso
Setting system property http.proxyPort to 33128
Setting system property http.nonProxyHosts to "localhost|127.0.0.1"
Setting system property https.proxyHost to maki79213.miso
Setting system property https.proxyPort to 33128
Setting system property https.nonProxyHosts to "localhost|127.0.0.1"
23:48:48.887 INFO - Java: Oracle Corporation 25.65-b01
23:48:48.887 INFO - OS: Windows Server 2008 R2 6.1 x86
23:48:48.908 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
23:48:49.153 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4443/wd/hub
23:48:49.155 INFO - Version Jetty/5.1.x
23:48:49.158 INFO - Started HttpContext[/selenium-server,/selenium-server]
23:48:49.254 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@c6a292
23:48:49.254 INFO - Started HttpContext[/wd,/wd]
23:48:49.254 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
23:48:49.254 INFO - Started HttpContext[/,/]
23:48:49.260 INFO - Started SocketListener on 0.0.0.0:4443
23:48:49.260 INFO - Started org.openqa.jetty.jetty.Server@11bc7ed
23:48:49.791 INFO - Executing: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]])
23:48:49.828 INFO - Creating a new session for Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]
23:48:53.236 INFO - Done: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]]

However, I use 'grunt-sauce-connect-launcher' which successfully launches a tunnel, but localhost url does not get accessible on Sauce lab machine

Failure case logs:

3:41:30.415 INFO - Launching a standalone server
Setting system property webdriver.firefox.logfile to c:\log\firefox.log
Setting system property webdriver.server.session.timeout to 0
23:41:30.556 INFO - Java: Oracle Corporation 25.65-b01
23:41:30.556 INFO - OS: Windows Server 2008 R2 6.1 x86
23:41:30.578 INFO - v2.45.0, with Core v2.45.0. Built from revision 5017cb8
23:41:30.918 INFO - RemoteWebDriver instances should connect to: http://127.0.0.1:4443/wd/hub
23:41:30.920 INFO - Version Jetty/5.1.x
23:41:30.923 INFO - Started HttpContext[/selenium-server,/selenium-server]
23:41:31.027 INFO - Started org.openqa.jetty.jetty.servlet.ServletHandler@c6a292
23:41:31.027 INFO - Started HttpContext[/wd,/wd]
23:41:31.027 INFO - Started HttpContext[/selenium-server/driver,/selenium-server/driver]
23:41:31.027 INFO - Started HttpContext[/,/]
23:41:31.034 INFO - Started SocketListener on 0.0.0.0:4443
23:41:31.034 INFO - Started org.openqa.jetty.jetty.Server@11bc7ed
23:41:31.648 INFO - Executing: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]])
23:41:31.685 INFO - Creating a new session for Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]
23:41:35.067 INFO - Done: [new session: Capabilities [{proxy={proxyAutoconfigUrl=http://127.0.0.1:19876/pac.js, proxyType=PAC}, count=1, webdriver.remote.quietExceptions=true, browserName=firefox}]]

Haven't been able to successfully configure proxy from protractor conf or 'grunt-sauce-connect-launcher' config

capabilities: {
//username: process.env.SAUCE_USERNAME,
//accessKey: process.env.SAUCE_ACCESS_KEY,
proxy: {
proxyType: 'manual',
httpProxy: 'http://.miso:33128',
httpsProxy: 'http://.miso:33128'
//proxyAutoconfigUrl: 'http://127.0.0.1:19876/pac.js',
//proxyType: 'PAC'
},
browserName: 'firefox',
version: '37.0',
platform: 'Windows 7',
},

**Comment by cnishina** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Your question is better suited for [StackOverflow with the 'protractor' tag](http://stackoverflow.com/questions/tagged/protractor) or the [Gitter channel](https://gitter.im/angular/protractor).

Thanks!
