### ISSUE TITLE
Asynchronous expect does not execute

### ISSUE THREAD

**Issue by bhelzer** [angular/protractor#2904]
Unfortunately, I don't have good recreation steps. This only happens on my computer. 

Some of my tests seem to run just fine, but none of the expect actually execute. With other test the browser comes up and goes down before loading the page. Might be the same issue.

I have a test with:  

```javascript
expect(page.courseTitle.getText()).toBe 'Symphony'
expect(page.courseTitle.getText()).toBe 'garbage'
```

I expect this to fail, but it does not. If I add the line:
```javascript
expect(true).toBe false
```

The test fails with both errors. If I add the line:
```javascript
expect(true).toBe true
```
the test does not fail at all.

**Comment by cnishina** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Your question is better suited for [StackOverflow with the 'protractor' tag](http://stackoverflow.com/questions/tagged/protractor) or the [Gitter channel](https://gitter.im/angular/protractor).

Thanks!

**Comment by cnishina** [comment]
Taking another look at this, the syntax is incorrect.

Potential fix:  `expect(page.courseTitle.getText()).toBe 'garbage'` to look like this: `expect(page.courseTitle.getText()).toBe('garbage')`. If that doesn't work, please try our Gitter channel.

Thanks!

**Comment by bhelzer** [comment]
Thanks for looking at it. Syntax is fine (CoffeeScript). Moving to StackOverflow.
http://stackoverflow.com/questions/35192074/jasmine-expect-statement-does-not-execute-in-protractor-scenario
