### ISSUE TITLE
with Protractor, Controller setTimeout function not run 

### ISSUE THREAD

**Issue by ice0526** [angular/protractor#2905]
1. In My Controller , when test with  Protractor,interval or setTimeout function not to be invoke
$interval(function(){
            console.log("aaaaa");
   },100,1);

**Comment by cnishina** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Your question is better suited for [StackOverflow with the 'protractor' tag](http://stackoverflow.com/questions/tagged/protractor) or the [Gitter channel](https://gitter.im/angular/protractor).

Thanks!
