### ISSUE TITLE
Feature Request: Meaningfully getting the browser name for exporting tests.

### ISSUE THREAD

**Issue by excenter** [angular/protractor#2906]
While running a test with multiCapabilities, when they each have generated reports they write on top of eachother, with the last to write winning. 
I want to have a simple string referencing the browserName declared above. So that Chrome tests go with Chrome tests, and Firefox tests go with Firefox tests. 

```
multicapabilities:[
    {'browserName': 'chrome'},
    {'browserName': 'firefox'},
]
```

All the SO answers involve `.capabilities` or `.caps_.browserName` which, as of Protractor 3 and the latest Angular return undefined.

**Comment by excenter** [comment]
I'm about to have to write a grossly inelegant solution where I grab the userAgent, write a regex parser, and generate a string based on that. 
That is, to borrow from community, the darkest timeline.

**Comment by sjelin** [comment]
Glad you asked on SO first, shame they didn't have the answer.  Have you tried using [getProcessedConfig](http://www.protractortest.org/#/api?view=Protractor.prototype.getProcessedConfig)?

**Comment by juliemr** [comment]
I believe that `getProcessedConfig` will solve this issue - and since we haven't heard an update, I'm going to optimistically close this as solved. Please open up a new feature request if there's still something you need.
