### ISSUE TITLE
Protractor: Change style of a column header

### ISSUE THREAD

**Issue by fabriciosomini** [angular/protractor#2907]
Hello, I'm here to ask you guys if there's anyway to change the property of a column header to be visible.
Here is the code I am using, but the only thing I get is:

> column.getWebElement is not a function. 

And if I don't use .getWebElement() :

> Maximum Call Stack Size Exceeded

```
var column = element.all(by.repeater('col in vm.wijmoConfig.columns').row(2));
browser.executeScript('arguments[0].style = {};', column.getWebElement());
```
I'm so lost, please someone help me.

Thank you very much!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
