### ISSUE TITLE
Execute Jasmine Tests in Parallel

### ISSUE THREAD

**Issue by muhilr** [angular/protractor#2909]
I have a single spec file with four jasmine tests, like below

```
describe("A suite", function() {
  it("Test1", function() {
describe("A suite", function() {
  it("Test2", function() {
describe("A suite", function() {
  it("Test3", function() {
```

I have a requirement to execute the tests(within a single file) in parallel, to minimize the execution time. 
I tried  specifying the capability like below:

```
  multiCapabilities: {
    split: true,
    maxSessions : 2,
    capabilities: [{
      browserName: 'firefox',
      count: 2
    }]
}
```

but it doesn't workout. Do we have any option to share the tests within a spec file...
like `shardSpecTests`?

**Comment by NickTomlin** [comment]
This is not possible at the individual test level currently. We can add a feature request for this but i'm not sure of the timeline.

**Comment by NickTomlin** [comment]
There hasn't been any more activity on this so going to go ahead and close. Feel free to submit a PR or a feature request! :smile:

**Comment by muhilr** [comment]
Thank you ...will wait for the feature to be added

**Comment by twomarktwo** [comment]
@NickTomlin Is there a link to the feature request you put in for this?
