### ISSUE TITLE
Upload file using protractor

### ISSUE THREAD

**Issue by NareshKumar1800** [angular/protractor#2911]
Hi @juliemr ,

Need some info, i need to upload a file using protractor below is the screenshot of the app
Now when i click on the Select File it shows browse button, can i automate the fileupload window of browser. If yes can you provide me with  example.
![image](https://cloud.githubusercontent.com/assets/15671657/12864996/8821fc3a-ccc5-11e5-9cda-8fbf88ae9371.png)

Hoping for reply.

Thanks,
Naresh Kumar

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. There is already an [answer](http://stackoverflow.com/a/21314337/1048479) on StackOverflow for your question. If that does not resolve your problem, please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by NareshKumar1800** [comment]
Hi,

i have checked in StackOverflow but couldnot figure it out. so posted over her...
can you provide me with some links... that would be helpful.
