### ISSUE TITLE
Is there any planned date when we can expect Protractor to be integrated with Java

### ISSUE THREAD

**Issue by VanshdeepKewlani** [angular/protractor#2913]
Hi,

I am working on Automation Testing for my project since 4-5 months where one of the site is built on AngularJS. I have written my scripts using Selenium Java WebDriver and have executed them in BroweserStack's environment. Most of the times they ran fine but recently I have faced StaleElementReferenceException a lot of times in my Angular project. My code used to execute perfectly continously for 4-5 times but suddenly this exception appears and I get stuck as there was no specific statement in code where it occurred, it could be any random statement. 

I tried different mechanisms to handle this be it implementing with different Wait tactics or using conditional wait in a control flow where I tried to fetch the element again & again in case of StaleElementReferenceException but to no avail. Then, I got some information from Google Search regarding your Protractor framework as in how it handles as per the changes in Angular and it seems it can solve my problem.

Unfortunately, Protractor by default runs on Jasmine and JavaScript not Java and it seems both JProtractor or Protractor-JVM are not yet ready to be implemented. It will be great thing for people like us who have already written their code in a specific language supported by WebDriver if they don't have to migrate to another language as otherwise it will be a kind of re-work. 

I am eagerly waiting for the day Protractor can be used with Java so that I can implement it in my project. Meanwhile it seems the only option left is to implement Protractor directly with Jasmine. Please let us know by when we can expect JProtractor to be ready for use.

**Comment by NickTomlin** [comment]
I do not think there are any plans to create a Java version of Protractor. I don't think there's anything stopping you from creating your own if that meets a need :smile:
