### ISSUE TITLE
Write data to json file using Protractor

### ISSUE THREAD

**Issue by bhamaresanket** [angular/protractor#2921]
Hi,
The solution  #978 worked to read data from json file using Protractor.
Next thing I need to try is write some text using protractor to the json file from which we read the values.
e.g. 
If the original json file is this:
{
"user1":"email@email.com",
"user2":"email2@email.com"
}

I want to add an extra field through protractor code to json file. So the file should be like.
{
"user1":"email@email.com",
"user2":"email2@email.com",
"user3":"email3@email.com"
}

Please help.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
