### ISSUE TITLE
How to retreive text or inner text of an element using by.repeater

### ISSUE THREAD

**Issue by VanshdeepKewlani** [angular/protractor#2922]
I am having a list of elements on page with ng-repeat set to "listing in policy". I want to retrieve text of a descending element present in individual listing element.

It seems I am able to retrieve element but not able to retrieve text

Sample code:
describe (...{
It(.....){
console.log(element(by.repeater('listing in policy')).element(by.xpath('descending::div[@id=\'policytype\']').getText();
});
});

It seems I am able to retrieve element as the command prompt displays some info related to locator used but no text is displayed. I also tried using getAttribute('innerText') but got error that it's not supported which is strange as it belongs to Webdriver

P.S Please ignore the syntax

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
