### ISSUE TITLE
unable to switch control iframe elements - Maximum call stack size exceeded message is displayed

### ISSUE THREAD

**Issue by chennaipaiyen** [angular/protractor#2923]
Below is the code:

var framename = element(by.css('[ng-class = "homePageScrolledDown?"]'));
browser.switchTo().frame(framename);

when i execute the code the below error message is displayed, not able to proceed further

Failures:
1) to test paytm website open webpage
  Message:
    Failed: Maximum call stack size exceeded
  Stack:
    RangeError: Maximum call stack size exceeded

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
