### ISSUE TITLE
How to retrieve text for elements in Protractor

### ISSUE THREAD

**Issue by VanshdeepKewlani** [angular/protractor#2924]
Hi,

I am new to Protractor and facing lot of issues when trying to retrieve text of element. I have tried all these options but could not extract text from the element:-

getText(), getAttribute('innerText'), getAttribute('innerHTML'), getAttribute('value')

Also, I tried to execute with Javascript :- element.evaluate('value')
and with JQuery:- 
$('.status').val() 
$('.status').text() 
    where status is classname 

In case of JQuery, I got message like:-  $(...).text is not a function

Only in 1 case I was able to capture text of an element, in rest of the cases I was unable to do so.

**Comment by Harsha509** [comment]
write it as 

$('.Status').getText().then(function(text){
console.log(text);
});

**Comment by VanshdeepKewlani** [comment]
Thanks, it worked.

**Comment by Harsha509** [comment]
Anytime. Please close the issue.

**Comment by NickTomlin** [comment]
Also, In the future, please direct requests like this to StackOverflow or Gitter. 

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
