### ISSUE TITLE
@3.1.1 - Suites are loaded in alphabetical order instead of as described

### ISSUE THREAD

**Issue by popescunsergiu** [angular/protractor#2928]
suites: {
        b                 : [],
        c    : [],
        aa                : [],
        a           : [],
        d                    : []
}

These suites are ran in the following order: a > aa > b > c > d
I would like to run these suites as in protractor 3.0.0 (the order in list): b > c > aa > a > d

**Comment by NickTomlin** [comment]
This would be because of the [sort] [here](https://github.com/angular/protractor/commit/edfb52fadccf10c34d885c37e990dea0efbb0081#diff-5e5e3eb8e4137fbd8fba49f71f579ac4R154). I think it makes sense to restore this to the way it functioned.
