### ISSUE TITLE
How to use same data provider for different test cases requiring different data.

### ISSUE THREAD

**Issue by Saurabh06** [angular/protractor#2933]
Their is data-provider in test- ng, which provides the method name through reflection as a parameter to the data-provider, so that we can use same data-provider for different test cases requiring different data as per the method name. Is their is any similar data-provider present in protractor so that we can pass different data to different method as per method name. Thanks in Advance

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
