### ISSUE TITLE
protractor-angular-screenshot-reporter compatibility with jasmine2 

### ISSUE THREAD

**Issue by harindu61** [angular/protractor#2936]
https://github.com/bcole/protractor-angular-screenshot-reporter

I tried to use this with protractor to generate reports, but the reports did not generate in the defined location. I am using jasmine 2. 
Is there a way to use this reporter with with jasmine 2?

**Comment by gumallett** [comment]
Not that I'm aware, we had to switch to [protractor-jasmine2-screenshot-reporter](https://github.com/mlison/protractor-jasmine2-screenshot-reporter)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
