### ISSUE TITLE
Changing of rootElement in protractor 3

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#2940]
I've a use case where it is to be automate two different apps interaction in a jasmine suite. So two different apps there would be different rootElement for two apps. How should we manage this rootElement. I've tried one setting in config.js and i can interact with first app url and then chnaged browser.rootEl = '[ng-app="muiApp"]';to interact second app but it is not working .

Getting error:

    Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

**Comment by vivekbrahmadandi** [comment]
http://stackoverflow.com/q/35410887/5846428

**Comment by NickTomlin** [comment]
Thanks for asking this on StackOverflow. Looks like there's conversation on this in comments on the SO thread. I'm going to go ahead and close this.

**Comment by vivekbrahmadandi** [comment]
@NickTomlin  could you comment out the solution in stackoverflow.

**Comment by vivekbrahmadandi** [comment]
how to handle multiple ng-apps in one project #1056

**Comment by vivekbrahmadandi** [comment]
Can we change rootElement through jasmine spec. As per juliemr  commented on the issue #1056 

You can specify which element to use angular from using rootElement in the config, but there's currently no way to change this part way through a test. I can't tell from your description if that's what you want to do or not, but if you just need to test one part of the app then just use rootElement set to an appropriate selector.
