### ISSUE TITLE
Error while selecting radio button option using protractor and cucumberjs

### ISSUE THREAD

**Issue by kary-ajrj** [angular/protractor#2942]
I am new to the world of automating tests on angular pages. The framework I am using is protractor, but I am clubbing it with cucumberjs.

I am trying to click on a radio button. This is how the element looks like in the DOM :-

```
<div>
<input class="ng-pristine ng-untouched ng-valid" type="radio" ng-click="setTestOrValid(p)" value="Valid" ng-model="p.testOrValidDisplay" name="341">
Valid
<input class="ng-pristine ng-untouched ng-valid" type="radio" ng-click="setTestOrValid(p)" value="Invalid" ng-model="p.testOrValidDisplay" name="342">
Invalid (Test/Junk)
</div>
```

Following is the function which I have written to be able to click on it :-
```
    sut.browser.findElements(sut.by.css('[ng-click="setTestOrValid(p)"]')).then(function(elements){
      for (i=0; i < elements.length; i++){
        elements[i].getAttribute('value').then(function(value){
          if (value == 'Invalid') {
            elements[i].click();
          }
        })
      }
    })
```

The code above throws an error :-
```
 TypeError: Cannot read property 'click' of undefined
```

Would you please help me with this?

**Comment by szikszail** [comment]
I think the problem is not with protractor, you mixed sync/async behaviour. When the `elements[i].click();` is execute, the for-loop is already done, `i` will be `elements.length`, so... :)

**Comment by kary-ajrj** [comment]
Yes, this works when I replace "i" with the expected index value. I do not think hard coding will be a good idea. Any suggestions for its resolution? :)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
