### ISSUE TITLE
Changing of rootElement in protractor 3

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#2943]
#2940

**Comment by NickTomlin** [comment]
Please continue this discussion on the StackOverflow question you've already asked. You'll need to provide more detail besides two isolated code snippets to get more help. I'm going to close this as debugging/troubleshooting is better done on SO or Gitter per the [README](https://github.com/angular/protractor#getting-help):

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
