### ISSUE TITLE
feat(plugins): onPageUnload

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#2951]
Basically give a plugin a chance to run some stuff right before a page is unloaded.  This is would be helpful for the a11y plugin, so that it could gather a11y data on all pages instead of just the last page tested.  It's not strictly necessary though since we could probably just gather the data when the page first loads using `onPageLoad` and `onPageStable`.

Thoughts @juliemr @cnishina @mgiambalvo?

**Comment by juliemr** [comment]
Not possible, I think.

You can hook in to the `beforeunload` event but the page will still unload - you can't pause it without that popup "are you sure" dialog for the user. Unless something has changed since I last looked into this.

**Comment by sjelin** [comment]
We would just call the hook at the start of a `browser.get`

**Comment by juliemr** [comment]
Ah, I see. Wouldn't work for the last page, then... if we did do something like this, I'd suggest a different name.

I'm leaning towards your suggestion of just using `onPageLoad` and `onPageStable`, though. I'm having a hard time thinking of a use case for this that isn't better accomplished with those.

**Comment by sjelin** [comment]
Well, if someone needs to wait for content to load (e.g. most Angular apps), then `onPageLoad` will miss a bunch of stuff.  And if they disable synchronization, then `onPageStable` isn't run at all.  The worst case would be if they needed to click a few buttons before the content they wanted loaded.

**Comment by FJLopezGarcia** [comment]
What is the way to run the audit from onPageStable? do you have and example?

**Comment by sjelin** [comment]
We'd have to edit the plugin

**Comment by sjelin** [comment]
I still like this idea but no one else does so I'll close this.
