### ISSUE TITLE
Web Driver Manager client timeout

### ISSUE THREAD

**Issue by mogmog** [angular/protractor#2958]
My e2e tests take quite a long time to run. This means that sometimes I get the following message in the web driver manager console output;

Session 91d7a988-c087-4d40-a125-9311669071fa deleted due to client timeout

This stops the tests running. 

Is it possible to increase the Web Driver client timeout limit?

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

All that said, you probably want to check out the timeout related configuration options in [the reference config](https://github.com/angular/protractor/blob/master/docs/referenceConf.js).
