### ISSUE TITLE
Element chaining doesn't confine search to parent element

### ISSUE THREAD

**Issue by csalces** [angular/protractor#2962]
I have something like this
```sh
<div class="parent1">
  <h2>Parent 1</h2>
</div>
<div class="parent2">
  <h2>Parent 2</h2>
</div>
```

when I have a call
```javascript
element(by.css('.parent1')).element(by.xpath('//h2')).getText()
```

I expected the result of `getText()` will be `Parent 2`
but the result was `Parent 1`

**Comment by NickTomlin** [comment]
XPath does not respect chaining unless you explicitly tell it to, so `//h2` is going to look for the first h2 in the document, not the first h2 that is a child of `.parent1`. You can use `.//h2` to respect the context.

from the [docs](https://angular.github.io/protractor/#/api?view=webdriver.By.xpath): 

> Care should be taken when using an XPath selector with a webdriver.WebElement as WebDriver will respect the context in the specified in the selector. For example, given the selector `..//` WebDriver will search from the document root regardless of whether the locator was used with a WebElement.
