### ISSUE TITLE
Using `browser.ignoreSynchronization = false`, still results in timed out syncing with page.

### ISSUE THREAD

**Issue by v--b** [angular/protractor#2967]
In my test under of the tabs (A) I need to click button and then navigate to another tab (B).

when I go to Tab A in the console of the  browser I see, 
1. a 404 error on one of the http get request, and 
2. TypeError: i.match is not a function

Not sure, but maybe because of this I have to use. 
browser.ignoreSynchronization = True;   (will time out if I don't use this, sleep or wait don't help)
button.click();
Tab_B.click();

After doing this when I go to Tab B or any other page and try to use `browser.ignoreSynchronization = false`, The test still fails saying timed out trying to sync with page after 11 sec.

If I don't go to Tab A, then the test runs fine, without having to deal with `browser.ignoreSynchronization.`

question: Why am I not able to do `browser.ignoreSynchronization = false` after I am done with the page that's causing an issue?
I have read a lot about protractor waiting on $timeout and $http, Is there a way to find this out in browser's console?
I am using Angular 1.0.7. Does the version has to do anything with my protractor tests?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
