### ISSUE TITLE
Appium: can't call setNetworkConnection

### ISSUE THREAD

**Issue by rolandoldengarm** [angular/protractor#2969]
I've set up my environment with Protractor + Appium + Jasmine to run my JavaScript based tests, followed [this guide](https://github.com/angular/protractor/blob/master/docs/mobile-setup.md). This is working OK, but I cannot call the network API available in Appium:

https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/network_connection.md

browser.driver does not have a method call "setNetworkConnection".

I guess it's Protractor related? I'm using TypeScript, and setNetworkConnection is not available in the TSD. I've also tried to cast browser.driver to any and then call this method, but then I get an error.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by sjelin** [comment]
Ok, so the problem here is that `browser.driver` is an instance of [`WebDriver/webdriver`](https://github.com/SeleniumHQ/selenium/blob/master/javascript/webdriver/webdriver.js), and that implementation doesn't have `setNetworkConnection` or any analogous commands.  It may have such a command in the future though, since the java and python clients do have the command.

**Comment by rolandoldengarm** [comment]
So @NickTomlin  this is not a support question. It's a missing feature... I think this issue should be reopened.

**Comment by juliemr** [comment]
@rolandoldengarm you're right - follow along with https://github.com/angular/protractor/issues/1940 for updates on the feature.

**Comment by sjelin** [comment]
Opening because this is a missing feature, closing because it's a duplicate :wink: 

Also, to Nick's credit, we get a lot of support questions and this sounded a lot like one

**Comment by NickTomlin** [comment]
@rolandoldengarm sorry I totally mistook this question. Thanks for picking this up @sjelin and @juliemr :smile:

**Comment by toddhalfpenny** [comment]
Hi. Not wanting to be a pain, sorry if I am. I'm just wondering if this feature is something that is likely to be included in the future? I see this is closed as is #1940 and so I'm uncertain - perhaps there's an alternative method that I've missed.

**Comment by sjelin** [comment]
It is likely to be included in the future, stay tuned!
