### ISSUE TITLE
Upgrade test app to latest Angular

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#2970]
Our versions (0.12, 0.13) are getting pretty old. We should probably be testing against 2 latest.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this as it seems like this was done in https://github.com/angular/protractor/commit/6f7140aeead3715dd0dd365921fb886f58c6fbda That doesn't cover running against the 2 latest but we can open another issue if we want to do that? 

Feel free to reopen if need be.

**Comment by juliemr** [comment]
Yes! Thank you.
