### ISSUE TITLE
Can protractor works with Angularjs2?

### ISSUE THREAD

**Issue by junjunruan** [angular/protractor#2971]
Can protractor works with Angularjs2? I'm currently using Jasmine to test Angular2 code, but have problems regarding to mouse event, it seems protractor can make it easy.

**Comment by sjelin** [comment]
Basic Angular 2 support exists.  We're working on making it better.  See our tests for examples

**Comment by junjunruan** [comment]
Could you please where can I find the examples?

**Comment by sjelin** [comment]
https://github.com/angular/protractor/blob/master/spec/angular2Conf.js
