### ISSUE TITLE
Drag and Drop

### ISSUE THREAD

**Issue by lauraerinmann** [angular/protractor#2974]
I've used a large number of listed solutions, but I can't get a drag and drop like functionality to work with protractor.  I see a number of open issues here that are related to this, but no definitive answer.  I've tried: browser.actions().dragAndDrop(elem,target).mouseUp().perform(); (many variety's of this solution browser.actions().mouseDown(treeElement1.getWebElement(), {x:0, y:1000}).perform();, adriver.actions().mouseDown(treeElement2).mouseMove(treeElement1).mouseUp().perform(); and many other solutions posted here and across the internet.  Protractor picks up and moves the element, but it never sticks.  Also, is there any way to slow down the actions to debug?

**Comment by NickTomlin** [comment]
Hi there, 

Drag and drop and selenium is pretty tricky :smile:  You can use `browser.pause` to help debug things "live" more in the [debugging](https://github.com/angular/protractor/blob/master/docs/debugging.md#pausing-to-debug) document. 



That said, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


If you do find there is an issue with protractor, please submit a new issue with more details on how to reproduce a bug.

Thanks!

**Comment by philoniare** [comment]
@lauraerinmann I've had the same issue. Not sure if this will help but I've added the target element to mouseUp and my drag and drop tests started working. 

`browser.actions().mouseDown(dragElement).mouseMove(targetElem).mouseUp(targetElem).perform()`
