### ISSUE TITLE
Getting unable to establish connection with SafariDriver Extension error on try to run script from server machine

### ISSUE THREAD

**Issue by SuatMcafee** [angular/protractor#2976]
Hi,

I am using Mac OS X.
Safari Version: 9.0.3
Selenium :2.48.0
Webdriver: 2.45.0
Standalone server: Selenium-standalone-server.2.42.2.jar 

When I try to run my scripts locally means on same machine, it's working fine.
The issue is when I triggered my script from other machine, it's launching safari and showing below message. When I check the Safari preferences, Extesnions list is blank. not showing "webDriver" extension. 
"I am getting "Unable to establish connection with safariDriver extension"

I tried with many combinations. standalone server 2.48, Safari driver 2.48,  selenium 2.42.0 etc.

Can someone help me. what exactly the issue is?

![screen shot 2016-02-25 at 11 33 18 am](https://cloud.githubusercontent.com/assets/17451113/13311361/eaaf3a6e-dbb3-11e5-83c1-3dec3f8720ca.png)

**Comment by sjelin** [comment]
This seems like a webdriver bug or a support question.  You should ask them.
