### ISSUE TITLE
spawn cmd ENOENT error when issue we run the "webdriver-manager start" command on Windows7

### ISSUE THREAD

**Issue by SekharIcann1** [angular/protractor#2978]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing)
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Fill in the information that corresponds to your type of issue below
4. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)

Bug report
---

- Node Version: `v4.3.1`
- Protractor Version: `3.1.1`
- Browser(s): Chrome``
- Operating System and Version `Windows7 Ultimate`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
1. Installed Java
2. Installed NodeJS
3. Verified versions of Node, NPM - success
4. Ran 'npm install -g protractor' command.
5. Verified version - success
6. Ran command - 'webdriver-manager update'  -success.
7. Ran command 'webdriver-manager start' , observed that spawn cmd ENOENT error.

Also please check my ENV variable for PATH.
C:\Program Files (x86);C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Java\jdk1.7.0\bin;C:\Program Files (x86)\nodejs;C:\Users\Administrator\AppData\Roaming\npm

 Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)
![spamwn](https://cloud.githubusercontent.com/assets/16821683/13345252/723556a6-dc83-11e5-99b6-364248f45f1f.PNG)

**Comment by SekharIcann1** [comment]
Issue resolved after adding "C:\Windows\System32\" to your PATHs. On windows, right-click My Computer -> Properties -> Advanced system settings -> Environment Variables -> Edit... PATH and add "C:\Windows\System32\" to the end (with a semi-colon separating each variable).

**Comment by NickTomlin** [comment]
Thanks for reporting back that this is solved.

**Comment by saipruthvi47** [comment]
hi sekharlcann1 sir,

iam sai pruthvi i too got the same error and i changed my path by adding C:\Windows\System32\ still aim getting same error when i start webdriver manager please guideme

**Comment by larry-dalmeida** [comment]
@saipruthvi47 The solution above did not work for me either, please let me know if you found an alternative

**Comment by Kalpesh1650** [comment]
@larry-dalmeida you got any solution for this issue. If yes please let me know, coz i stuck at the same point.
Thanks.

**Comment by Kalpesh1650** [comment]
@larry-dalmeida my issue resolved now by restarting CMD after updating PATH variable

**Comment by syartinaelfarika** [comment]
> Issue resolved after adding "C:\Windows\System32" to your PATHs. On windows, right-click My Computer -> Properties -> Advanced system settings -> Environment Variables -> Edit... PATH and add "C:\Windows\System32" to the end (with a semi-colon separating each variable).
 
Thanks.. this is worked for me

**Comment by EmmanuelN1** [comment]
This worked for me.. Thanks man this is great
