### ISSUE TITLE
protractor 2 needs a newer version of selenium standalone to support latest Firefox

### ISSUE THREAD

**Issue by elesueur** [angular/protractor#2980]
Latest version of Firefox (at time of writing is 44.0.2) and it refuses to load the webdriver due to a signing issue.

Updating selenium standalone to 2.52.0 solves the problem and protractor is able to run against Firefox  44.

If there is a way to force a particular version of selenium when running webdriver-manager update, I could work around this issue, but it appears the version is hard-coded in config.json. Can we update the version that protractor uses? 

Bug report
---

- Node Version: `0.12.7`
- Protractor Version: `2.5.1`
- Browser(s): `firefox`
- Operating System and Version `Mac OS X 10.11`

- Output from running the test

UnknownError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.

- Steps to reproduce the bug

 Simply try to run any test against firefox

**Comment by juliemr** [comment]
We upgrade to the latest version of selenium standalone whenever we do a release, so this will be done in version 3.2.0.

**Comment by elesueur** [comment]
But if I am stuck on an older version of node, (0.12) isn't only protractor 2 supported?

**Comment by juliemr** [comment]
Sorry, we don't do patches to older versions of Protractor. Your best bet, if you still have to use node 0.12, is to manually change `config.json` (we made it a separate file so it's easy to change).
