### ISSUE TITLE
Compatibility issues with Mozilla Firefox 44.0.2

### ISSUE THREAD

**Issue by pro1oh1** [angular/protractor#2984]
Bug report
---

- Node Version: `v5.6.0`  
- Protractor Version: `3.1.1`
- Browser(s): `Firefox 44.0.2`
- Operating System and Version `Ubuntu 14.04.4`

- A relevant example test
    element.all(by.repeater('tab in $mdTabsCtrl.tabs')).get(1).click();
    element.all(by.model('mode')).get(1).sendKeys('Python');

- Output from running the test
    Failed: Element is not currently visible and so may not be interacted with

- Steps to reproduce the bug
    Set up a simple html - angularjs app try to switch between tabs with protractor test.

- Expected Behavior -
    element.all(by.repeater('tab in $mdTabsCtrl.tabs')).get(1).click()

    Should change to tab a position 1.
    Works fine in chrome.

- Actual Behavior -
    Nothing happens, and no error is displayed. Tests just move on to whatever comes next.

    Everything appears to be working fine, until we try to interact with elements that should be visible, the tests fail with the error 'Element is not currently visible and so may not be interacted with'.

**Comment by cnishina** [comment]
In addition to your relevant example for `element.all` please provide config file, either the website that you are referring to or a sample html file. This will help us investigate the problem.

**Comment by NickTomlin** [comment]
Also, could you format your example code with (either by indenting it or using backticks `` ` ``)

**Comment by divmgl** [comment]
Having some major issues even launching Firefox. 

```
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
```

**Comment by NickTomlin** [comment]
@divmgl sounds like a different problem. Could you open up a new issue?

**Comment by divmgl** [comment]
#2997

**Comment by juliemr** [comment]
Closing stale issues.
