### ISSUE TITLE
Output buffering when using multiCapabilities

### ISSUE THREAD

**Issue by jendagroovy** [angular/protractor#2985]
Hi,

When using multiCapabilities, the protractor process gets forked and the output of the subprocesses is buffered. The buffer is flushed to terminal only after an error or after the task finishes.

I didn't really like this, as I wanted to monitor the test execution in my test automation in real time, so I hacked my protractor to flush buffers immediately after every output.

Would you consider it a good idea to make something like this into a proper, configurable feature of protractor?

Best regards,
Jan

**Comment by NickTomlin** [comment]
Hi Jan, 

Could you please update your issue to follow the format of the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE)? Also, if you could add more description of how you'd like feature to function (input/output examples would be great). Thanks!

**Comment by mgiambalvo** [comment]
4.1.0 will add the --verboseMultiSessions flag, let me know how that works for you.
