### ISSUE TITLE
doubleClick() not working on Chrome

### ISSUE THREAD

**Issue by Reyona** [angular/protractor#2989]
I wrote an e2e test and I need to double click on an element. The following codes work correctly on Firefox(38.4.0), but it does not work on Google Chrome(48.0.2564.97 m). 

```
browser.actions()
.doubleClick(element.all(by.css('[ng-dblclick="vm.onGroupedCollaborationSelect(key)"]')).get(3))
.perform();

```
Version:
- Microsoft Windows 7 Professional SP 1
- Protractor 3.1.1
- Firefox 38.4.0
- Google Chrome 48.0.2564.97 m

**Comment by cnishina** [comment]
I'll take a better look at this tomorrow; however, a quick solution would be to just click it twice? Let me know if that works.

`element.all(by.css('[ng-dblclick="vm.onGroupedCollaborationSelect(key)"]')).get(3).click().click()`

**Comment by Reyona** [comment]
> I'll take a better look at this tomorrow; however, a quick solution would be to just click it twice? Let me know if that works.
> 
> element.all(by.css('[ng-dblclick="vm.onGroupedCollaborationSelect(key)"]')).get(3).click().click()

I tried, but sorry, it doesn't work.

**Comment by cnishina** [comment]
Still cannot get the doubleClick method to work. Here is my sample spec that will press the first button.

```
describe('clicking twice', function() {

  beforeAll(function() {
    browser.ignoreSynchronization = true;
  });

  it('a few ways to double click', function() {
    var URL = 'http://www.the-art-of-web.com/javascript/doublesubmit/';
    browser.get(URL);

    // does not work
    browser.actions()
      .doubleClick(element.all(by.name('myButton')).get(0))
      .perform();

    // works!
    browser.actions()
      .click(element.all(by.name('myButton')).get(0))
      .click(element.all(by.name('myButton')).get(0))
      .perform();

    // default: selects the first one and click it twice
    element(by.name('myButton')).click().click();

    // select the first item from the elements and click it twice
    element.all(by.name('myButton')).get(0).click().click();

    // visual inspection will show the 7 button presses.
    browser.sleep(5000);

  });
});
```

Works for both Chrome and Firefox.

**Comment by cnishina** [comment]
@Reyona  please let me know if the above works for you.

**Comment by Reyona** [comment]
@cnishina Very sorry for being out for a few days. I tried as soon as I'm back, but it's confusing that this command is still not work for me, neither on firefox nor on chrome.
```
browser.actions()
      .click(element.all(by.name('myButton')).get(0))
      .click(element.all(by.name('myButton')).get(0))
      .perform();
```

**Comment by cnishina** [comment]
This bug has been on my plate and I haven't had time yet. This is either a problem with selecting the elements of interest or the action button to do a click.

```
element.all(by.name('myButton')).then(function(items){
  // log the text of the button
  items.get(0).getText().then(function(text) {
    console.log(text);
  });
  // do a single click
  items.get(0).click();
});
```

**Comment by cnishina** [comment]
Closing since bug is stale. Referencing a somewhat similar issue with actions() that does not work #3289.

**Comment by dremie** [comment]
If it helps, I've managed to resolve a doubleClick() usecase in a sketchy way as described below:

**Not working**
`var button = element(by.css('button')),
  hiddenElement = element(by.css('#iamhidden'));

// double-clicking should make hiddenElement visible
browser.actions().doubleClick( button ).perform();
expect(hiddenElement.isDisplayed()).toBe(true); // fails

// also fails (without immediate perform() ):
browser.actions().doubleClick( button );
expect(hiddenElement.isDisplayed()).toBe(true); // fails
`

**Working**
`var button = element(by.css('button')),
  hiddenElement = element(by.css('#iamhidden'));

// double-clicking should make hiddenElement visible
browser.actions().doubleClick( button ).perform().then(function () {
  expect(hiddenElement.isDisplayed()).toBe(true); // OK
});
`

Please let me know if it resolved anything related to your use case(s)
