### ISSUE TITLE
browser.takeScreenshot() throwing error in Mac OS X, not creating screenshot

### ISSUE THREAD

**Issue by ShobanaV** [angular/protractor#2990]
Hi,

Taking screenshot using browser.takeScreenshot() from protractor tests throwing error in Mac OS X v10.8.5. The error message from webdriver is as follows.

{
message: 'unknown error: cannot get automation extension\nfrom unknown error: page could not be found: chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/_generated_background_page.html\n  (Session info: content shell=)\n  (Driver info: chromedriver=2.10.290379,platform=Mac OS X 10.8.5 x86_64) (WARNING: The server did not provide any stacktrace information)',
}

And a .png file of zero bytes is getting created.

- Node Version: `0.10.33`
- Protractor Version: `1.0.0-rc4`
- Browser(s): `node-webkit`
- Operating System and Version `Mac OS X 10.8.5`

This may be related with the issue in this link - [https://bugs.chromium.org/p/chromedriver/issues/detail?id=1083]

**Comment by NickTomlin** [comment]
Can you share your protractor config?

**Comment by ShobanaV** [comment]
// conf.js

exports.config = {
	specs: ['./x/e2e.y page.js'],

	framework: 'mocha',

	mochaOpts: {
		reporter: "spec-xunit-file",
		slow: 2000
	},
	   
	chromeDriver: function() {
			    return '../../../source/chromedriver';
	}(),
	
	seleniumServerJar: function() {
		return '../../../source/selenium-server-standalone-2.42.2.jar';
	}(),

    seleniumPort: 4444
	
};

The version I am using 1.0.0-rc4 only. Because, I started writing e2e tests for my project in August 2015. At that time, this was the latest version available. It works fine in Windows. Now only, I am trying in Mac. It is not working.

**Comment by juliemr** [comment]
I'm sorry, we're unable to provide support for very old versions of Protractor. Please update to a later version. Node-webkit is also not a supported browser, see http://www.protractortest.org/#/browser-support

**Comment by olga-nov** [comment]
Hi. I have this error with 5th protractor.
