### ISSUE TITLE
Select :input elements

### ISSUE THREAD

**Issue by rdev5** [angular/protractor#2992]
The following fails with `Failed: invalid selector: An invalid or illegal selector was specified`.
```
it('should contain exactly 4 input elements of any kind', function() {
  expect(element.all(by.css(':input')).count()).toBe(4);
});
```

So...any chance of supporting an `:input` selector as does [jQuery](https://api.jquery.com/input-selector/)?

In jQuery, the `:input` selector is a shortcut that will also match `textarea`, `select` and `button` elements. This would be useful in scenarios where we want to assert anything having to do with the testing the input "class" of elements being used, including:

- Count total number of input elements
- Differentiate between `<input type="submit" name="action" ../>` vs. `<button type="submit" n-me="action" .../>`
- Index input elements by type, for caching, etc.

I don't see this as introducing any breaking changes (i.e. non-existent).

- Node Version: `4.3.1`
- Protractor Version: `3.1.1`
- Browser(s): `Chrome 48.0.2564.116 m`
- Operating System and Version `Windows 7`

**Comment by NickTomlin** [comment]
This sounds like a feature request, could you update your issue with the items from the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE#L27).

Personally I don't see a huge win over being more explicit with your selectors but maybe that's just me :smile:

**Comment by rdev5** [comment]
Updated.

**Comment by rdev5** [comment]
Nevermind, I figured it out:

```
// Equivalent to $(':input')
// Reference: https://api.jquery.com/input-selector/

var allInputs = function() {
  return element.all(by.deepCss('input,textarea,button,select'));
}

it('should contain :input elements', function() {
  expect(allInputs().count()).toBe(4);
});
```

**Comment by NickTomlin** [comment]
Sounds like a great solution. Thanks for checking back in!
