### ISSUE TITLE
How to clean localstorage and sessionstorage on phantom?

### ISSUE THREAD

**Issue by skarensmoll** [angular/protractor#2995]
Hi there!
I'm using protractor and phantom and I would like to clear LocalStorage and SessionStorage before start all the sets of e2e tests. 

I tried to do it on my protractor.config file 
` 
onPrepare: function () {
        browser.executeScript("return window.localStorage.clear();"); }`

However , It didn't work , instead of that I got this error
`

 C:\Users\KarenN\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108
>>   var template = new Error(this.message);
>>                  ^
>> UnknownError: {"errorMessage":"SecurityError: DOM Exception 18","request":{"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"58","Content-Type":"application/json; charset=utf-8","Host":"localhost:9781","User-Agent":"Apac
he-HttpClient/4.5.1 (Java/1.7.0_79)"},"httpVersion":"1.1","method":"POST","post":"{\"script\":\"return window.localStorage.clear();\",\"args\":[]}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative
":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/dc9ce280-e15f-11e5-911a-4b92e3de49f0/execute"}}
>> Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
>> Driver info: driver.version: unknown

`

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
