### ISSUE TITLE
Firefox 44.0.2 does not launch on OSX unless directConnect: true is set

### ISSUE THREAD

**Issue by divmgl** [angular/protractor#2997]
Latest version of Protractor with Firefox 44.0.2. Attempting to launch the test suite with Firefox gives me this:

```
/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: Cannot find firefox binary in PATH. Make sure firefox is installed. OS appears to be: MAC
Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
```

Firefox is installed and its directory is set in `PATH`. I am able to access Firefox through bash.

This problem is fixed when setting `directConnect: true` in configuration.

---

- Node Version: `v5.6.0`
- Protractor Version: `2.5.1`
- Browser(s): `Firefox`
- Operating System and Version `Mac OSX El Capitan 10.11.3`

**Comment by NickTomlin** [comment]
Hi there, 

Please update your question to conform to the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE). Thanks!

This looks like an issue with Selenium and _not_ protractor. Where is firefox actually installed?

**Comment by divmgl** [comment]
```
$ which firefox
/Applications/Firefox.app/Contents/MacOS/firefox
```

**Comment by cnishina** [comment]
I was able to reproduce this issue where on Firefox 44.0.2 that Protractor v2.5.1 does not work. Protractor v2.5.1 uses selenium-webdriver@2.47.0. 

Using the most recent version of Protractor, v3.1.1, I was able to run tests on Firefox v44.0.2. Protractor 3.1.1 uses selenium-webdriver v2.48.2. It looks like [Selenium change log](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md) may have had some fixes for related to recent releases of Firefox.

Please upgrade your protractor to the latest.
