### ISSUE TITLE
How to by pass model dialog in protractor with jasmine

### ISSUE THREAD

**Issue by Kothajagadeesh** [angular/protractor#3005]
I'm working with protractor with jasmine for a non-angular js application in IE.

My scenario is to get the text present in the alert and accept/dismiss the alert.

Alert getText() and accept()/dismiss() are working fine if i write both setps in a single it(). however, if i move the accept()/dismiss() function to another it(), then my script fails with following Error:

**UnexpectedAlertError: Modal dialog present**, is there any way that i can skip the alert verification by jasmine with a flag

Thanks
Jag

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
