### ISSUE TITLE
Clicking on the WebElement

### ISSUE THREAD

**Issue by srinivasgunda** [angular/protractor#3006]
I want to click on the web element which has the following DOM

span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName" title="All Cases (1)">                     All Cases (1)                 </span

I tried with css and class name but didn't work. Could you please help me in locating the element?

Thanks,
Srinivas

**Comment by Kothajagadeesh** [comment]
Please post the locators you've used  and full dom

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
