### ISSUE TITLE
WebElement.clear() Does Not Update Model

### ISSUE THREAD

**Issue by willread** [angular/protractor#301]
Calling WebElement.clear() on an input element does not appear to update the associated model.

**View:**

```
<input ng-model="foo">
<div>{{foo}}</div>
```

**Spec:**

```
it("should update the model", function(){
    var input = element(by.css("input"));
    input.sendKeys("bar");
    input.clear();
    expect(element(by.css("div")).getInnerHtml()).toBe(""); // Fails, because it's still "bar"
});
```

**Comment by satieh** [comment]
@wlingke  thank you you are genius

**Comment by EugeneSnihovsky** [comment]
@wlingke thanks from 2017. I still have this issue on angular 2.

**Comment by kenborge** [comment]
@EugeneSnihovsky Are you having problems with clear in a pure angular 2 application? I am having issues in a hybrid app with validation not triggering when using clear but wasn't sure if i have broken something or if it was related to hybrid application.

**Comment by vlio20** [comment]
me too! on ng2

**Comment by martinstark** [comment]
Still having this issue in 2017. On an input containing 'abc', .clear() followed by .sendKeys('d') on the empty input field and results in 'abcd' in angular's model using reactive forms.

**Comment by tiboprea** [comment]
@wlingke thanks from 2018, lol. Still having this problem on Angular 5 when I try doing:

```
field.clear() // works
field.sendKeys() //works
field.clear() // doesn't update my reactive form
```

**Comment by evanjmg** [comment]
backspace issue with clear throws a WebDriverError: java.net.SocketException: Connection reset by peer error

**Comment by evanjmg** [comment]
Ok I've had to resort to a more complex workaround, but it's a lot more reliable. I've had no false test failures with this.
```
const mapSerial = (fn: Function, list: any[]) => list.map(x => fn(x)).reduce((p, next) => p.then(next), Promise.resolve())

const clearInput = (name: string) => {
  const el = element(by.css('input[name=' + name + ']'))
  return visibilityOf(el)
   .then(() => el.getAttribute('value'))
   .then((text) => {
      const keysArray = text.replace(/ /g, '').split('')
      keysArray.push('')
      return mapSerial((key: string) => setTimeout(() => el.sendKeys(Key.BACK_SPACE), 0), keysArray)
    })
   .then(() => browser.wait(() => el.getAttribute('value').then(text => text.length === 0), 12000))
   .then(() => el)
}
```

**Comment by maximelafarie** [comment]
I tried your solution @evanjmg and I'm still stuck with the focused input. Not cleared, no new content append.

**Comment by sebastianhaas** [comment]
I can confirm this is still an issue with Angular 7.2.3 and Protractor 5.4.0 on 73.0.3683.103.

**Comment by manialpha** [comment]
@wlingke thanks much, your solution worked for me too.

**Comment by guillermosnipe** [comment]
Hi @juliemr I can confirm, that .clear() is still not working fine. I'm testing a form and the only way of making the test to work is doing this:

`    it('should run validations', async function () {
      await browser.get('/#/login');
      await password.sendKeys('a');
      await password.sendKeys(protractor.Key.BACK_SPACE);
      await username.click()
      expect(await passwordError.getText()).toMatch('Pedo');
    });`

**Comment by guillermosnipe** [comment]
> I had a similar issue with a directive I was using and sendKeys not updating the model. This solution worked for me though I am not sure if it will work for you all:
> 
> ```
> field.sendKeys(protractor.Key.chord(protractor.Key.CONTROL, "a"));
> field.sendKeys(protractor.Key.BACK_SPACE);
> field.clear();
> ```

Thanks a lot! 2019 and this is still the way to go :)

**Comment by vsravuri** [comment]
I had a similar issue recently. The workaround is to select all the existing text, use backspace to clear the text

**Comment by BalaSudheer** [comment]
Guys.. If the above solutions does not work for you, then try below. It works..
send empty string with single space.
`field.sendKeys(' ');`

**Comment by Kungfoowiz** [comment]
Noticed this problem when we tried to test some validation. It all works manually but using setKeys and clear doesn't seem to affect Angular to mark the input as touched or dirty. 

I wonder if there validation component we are using is loaded too slowly and isn't actually loaded by the time the test has filled out the form, it's only 2 inputs in my case. I'll run a delay test tomorrow and see if that fixes it.
