### ISSUE TITLE
Clicking on the WebElement 

### ISSUE THREAD

**Issue by srinivasgunda** [angular/protractor#3010]
I want to click on the web element 'All Cases' on the UI

I tried with the following locators but didn't work. Could you please help me in locating the element?

element(by.className('organizer-text')).click();
element(by.css('.organizer-text.ng-binding')).click();
element(by.xpath('html/body/div[1]/div/div[2]/div[1]/div/div/div[1]/div/div[1]/div[1]/span/span[4]')).click();

Attaching the complete DOM as inline only (please edit the comment below to see the DOM) because the file is not getting uploaded here

Thanks,
Srinivas

**Comment by srinivasgunda** [comment]
<document>
<html class="ng-scope" xmlns="http://www.w3.org/1999/xhtml" ng-app="omnyxWebApp" style="">
<head>
<body>

<div class="ng-scope ng-isolate-scope" version="2.0.0.57" ng-view="">
<div class="case-list-page ng-scope">
<div class="account-container" context-help="ChangePassword">
<div class="zoomable-area">
<div class="case-list-organizer ng-isolate-scope" edit-sets-enabled="editSetsEnabled" selected-worklist="selectedWorklist">
<script id="organizer_tree_renderer.html" type="text/ng-template">         <div class="organizer-node-box folder-entry"               context-menu data-target="menu-{{node.id}}">             <span ng-drop ng-drop-context="node.id"                   ng-drop-event-type="CaseDrag"                   ng-drop-action="folderDrop"                   ng-drop-prevent="node.type != 'Folder'">                 <span class="icon-plus set-edit-icon icon-left"                       ng-show="showAddSetButton(node)"                       ng-click="showNewSetForm($event, node)"                       context-help="Create Folder"></span>                 <span class="icon-share set-edit-icon icon-left"                       ng-class="{'icon-shared-folder': node.isShared}"                       ng-show="showShareSetButton(node)"                       ng-click="showShareDialog($event, node)"                       context-help="Share Folder"></span>                 <span class="organizer-icon"                       ng-click="onFolderClick($event, node)"                       ng-class="{'{{openicon}}' : showOpenIcon(node), '{{childicon}}' : showChildIcon(node), '{{parenticon}}' : showParentIcon(node), 'folder-selected' : isSelected(node) }"                       data-folderid="{{node.id}}">                 </span>                                  <span class="organizer-text" ng-show="!node.showEditName"                       ng-class="{'folder-selected' : isSelected(node)}"                       ng-click="onLabelClick($event, node)"                       tooltip="buildLabel(node.name, node.totalCases)">                     {{buildLabel(node.name, node.totalCases)}}                 </span>                 <input name="editFolderName" class="organizer-text" ng-show="node.showEditName" ng-keyup="saveNameChange($event, node)" focus-on="focusMe" ng-model="node.editName" ng-blur="saveNameChange($event, node)" ng-required="true" maxlength="50" placeholder="{{'Edit Folder Name' | translate}}" />                 <span class="icon-closedelete set-edit-icon icon-right" ng-show="showDeleteSetButton(node)" ng-click="deleteSet($event, node)" context-help="Delete Folder"></span>             </span>         </div>         <div ng-show="isExportEnabled()" omx-hide>             <div class="organizer-menu" id="menu-{{node.id}}">                 <ul class="dropdown-menu" role="menu">                     <li ng-show="isExportableFolder(node)">                         <a ng-mousedown="exportFolder($event, node)">Export</a>                     </li>                 </ul>             </div>         </div>         <div ng-show="node.addingFolder" class="organizer-node organizer-node-box folder-entry" ng-form name="newFolderForm" context-help="Create Folder">             <span class="organizer-icon icon-createfolder"></span>             <input name="folderName" type="text" focus-on="focusMe" class="organizer-text" ng-keyup="addSet($event, node)" select-text ng-model="newFolder.name" ng-blur="addSet($event, node)" maxlength="50" ng-required="true" placeholder="{{'Enter New Folder Name'| translate}}" />         </div>         <div ng-show="node.expando">             <div ng-repeat="node in node.children | orderBy:'id':true" class="organizer-node" ng-include="'organizer_tree_renderer.html'"></div>         </div>     </script>
<share-folder class="ng-isolate-scope" show-folder-share-dialog="showFolderShareDialog">
<div class="organizer" ng-show="worklists != null">
<div class="organizer-container">
<div class="organizer-box" context-help="Worklists">
<div class="organizer-inner-box">


<div class="organizer-root ng-scope" ng-init="childicon='icon-list'; parenticon='icon-parentlist'; openicon='icon-openlist';" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in worklists track by node.id">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-2" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-parentlist" data-folderid="2" ng-class="{'icon-openlist' : showOpenIcon(node), 'icon-list' : showChildIcon(node), 'icon-parentlist' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName" title="All Cases (1)">                     All Cases (1)                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">


<div class="organizer-node ng-scope" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in node.children | orderBy:'id':true">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-126" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-list" data-folderid="126" ng-class="{'icon-openlist' : showOpenIcon(node), 'icon-list' : showChildIcon(node), 'icon-parentlist' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName">                     40x                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">
</div>

</div>
</div>


<div class="organizer-root ng-scope" ng-init="childicon='icon-list'; parenticon='icon-parentlist'; openicon='icon-openlist';" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in worklists track by node.id">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-3" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-list folder-selected" data-folderid="3" ng-class="{'icon-openlist' : showOpenIcon(node), 'icon-list' : showChildIcon(node), 'icon-parentlist' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding folder-selected" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName" title="My WorkList (0)">                     My WorkList (0)                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">
</div>

</div>
</div>
<div class="organizer-box" context-help="Folders">
<div class="organizer-inner-box">


<div class="organizer-root ng-scope" ng-init="childicon='icon-folder'; parenticon='icon-parentfolder'; openicon='icon-openfolder';" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in folders track by node.id">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-125" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-folder" data-folderid="125" ng-class="{'icon-openfolder' : showOpenIcon(node), 'icon-folder' : showChildIcon(node), 'icon-parentfolder' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName">                     test (1)                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">
</div>


<div class="organizer-root ng-scope" ng-init="childicon='icon-folder'; parenticon='icon-parentfolder'; openicon='icon-openfolder';" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in folders track by node.id">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-127" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left icon-shared-folder ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-parentfolder" data-folderid="127" ng-class="{'icon-openfolder' : showOpenIcon(node), 'icon-folder' : showChildIcon(node), 'icon-parentfolder' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName">                     static1 (0)                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">


<div class="organizer-node ng-scope" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in node.children | orderBy:'id':true">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu-128" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left icon-shared-folder ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-folder" data-folderid="128" ng-class="{'icon-openfolder' : showOpenIcon(node), 'icon-folder' : showChildIcon(node), 'icon-parentfolder' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName">                     Nested1 (0)                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">
</div>

</div>
</div>

<div class="organizer-root folder-entry ng-pristine ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" name="createRootFolderForm" ng-form="" ng-show="editSetsEnabled && editSetButtonsEnabled">
<div class="organizer-node-box ng-hide" ng-show="folders.length == 0 && !editSetsEnabled">
</div>
</div>
<div class="organizer-box" context-help="SharedFolders">
<div class="organizer-inner-box">


<div class="organizer-root ng-scope" ng-init="childicon='icon-folder'; parenticon='icon-parentfolder'; openicon='icon-openfolder';" ng-include="'organizer_tree_renderer.html'" ng-repeat="node in sharedFolders track by node.id">
<div class="organizer-node-box folder-entry ng-scope ng-isolate-scope" data-target="menu--1" context-menu="">
<span class="ng-isolate-scope" ng-drop-prevent="node.type != 'Folder'" ng-drop-action="folderDrop" ng-drop-event-type="CaseDrag" ng-drop-context="node.id" ng-drop="">
<span class="icon-plus set-edit-icon icon-left ng-hide" context-help="Create Folder" ng-click="showNewSetForm($event, node)" ng-show="showAddSetButton(node)"/>
<span class="icon-share set-edit-icon icon-left ng-hide" context-help="Share Folder" ng-click="showShareDialog($event, node)" ng-show="showShareSetButton(node)" ng-class="{'icon-shared-folder': node.isShared}"/>
<span class="organizer-icon icon-folder" data-folderid="-1" ng-class="{'icon-openfolder' : showOpenIcon(node), 'icon-folder' : showChildIcon(node), 'icon-parentfolder' : showParentIcon(node), 'folder-selected' : isSelected(node) }" ng-click="onFolderClick($event, node)"/>

<span class="organizer-text ng-binding" tooltip="buildLabel(node.name, node.totalCases)" ng-click="onLabelClick($event, node)" ng-class="{'folder-selected' : isSelected(node)}" ng-show="!node.showEditName" title="Shared Folders">                     Shared Folders                 </span>
<input class="organizer-text ng-pristine ng-untouched ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" placeholder="Edit Folder Name" maxlength="50" ng-required="true" ng-blur="saveNameChange($event, node)" ng-model="node.editName" focus-on="focusMe" ng-keyup="saveNameChange($event, node)" ng-show="node.showEditName" name="editFolderName" required="required"/>
<span class="icon-closedelete set-edit-icon icon-right ng-hide" context-help="Delete Folder" ng-click="deleteSet($event, node)" ng-show="showDeleteSetButton(node)"/>
</span>
</div>
<div class="ng-scope ng-isolate-scope ng-hide" omx-hide="" ng-show="isExportEnabled()">
<div class="organizer-node organizer-node-box folder-entry ng-pristine ng-scope ng-invalid ng-invalid-required ng-valid-maxlength ng-hide" context-help="Create Folder" name="newFolderForm" ng-form="" ng-show="node.addingFolder">
<div class="ng-scope ng-hide" ng-show="node.expando">
</div>

</div>
</div>
<button class="btn organizer-button" tooltip="folderToolTip" context-help="Create Folder" ng-click="toggleEditMode()">
</div>
</div>
</div>
<div class="case-list-container">
</div>
</div>
</div>
<div class="help help-maximized ng-hide" ng-show="state.isEnabled && !state.isOpenInAnotherWindow && isAuxWindowOrSingleScreen()" ng-class="{'help-minimized': state.isMinimized, 'help-maximized': !state.isMinimized}">
<rtv-widget class="ng-isolate-scope" show-real-time-viewing-widget="showRealTimeViewingWidget">
<div class="notification-layer"/>
<div class="cfp-hotkeys-container fade ng-scope" style="display: none;" ng-class="{in: helpVisible}">
</body>
</html>
</document>

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

As a side note, please properly format your code using backticks instead of including raw html.

Thanks!
