### ISSUE TITLE
Not able to access https://blob data 

### ISSUE THREAD

**Issue by an123** [angular/protractor#3012]
Could anyone please tell me how to get content from a blob in a protractor script.   The webpage I am trying to test opens up this page/blob in a new tab which has XML text. 
I am able to switch window to this new tab but not able to access any data, I get timeout error.
Thanks for you help in advance!

**Comment by juliemr** [comment]
Any questions posted to Protractor's Github Issues will be closed with this note:

Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
