### ISSUE TITLE
Website does not find selenium-webdriver@2.52.0 upgrade

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3014]
The website uses the following files listed in `website/docgen/dgeni-config.js`:
```
    {include: 'node_modules/selenium-webdriver/lib/**/locators.js'},
    {include: 'node_modules/selenium-webdriver/lib/webdriver/webdriver.js'},
    {include: 'node_modules/selenium-webdriver/lib/webdriver/key.js'},
    {include: 'node_modules/selenium-webdriver/lib/webdriver/promise.js'}
```

Selenium-webdriver @ 2.52.0 files have been changed to es6 and are no longer being picked up by dgeni and no longer appear when building the website.

**Comment by juliemr** [comment]
Offline, we discussed two options
 - we can modify dgeni to work properly with the new es6 files
 - we can scrap our process of mining selenium-webdriver for docs, and instead just write our own for those functions. This has a big pro in that we can write our own examples using Protractor syntax. The con is maintenance cost.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/issues/3107 for the followup plan.
