### ISSUE TITLE
Allow suites to be declared at a capability level

### ISSUE THREAD

**Issue by andrewowen** [angular/protractor#3027]
Like specs, it'd be nice to be able to configure suites at a capability level so that suites can be run against specific browser sessions as opposed to its current behavior where suites are declared globally and forced to run across all browser sessions.

I don't imagine this will break anything

**Comment by juliemr** [comment]
Eeeeerm I am very cautious about adding more complexity to our capability configuration in this way. It's already a crazy matrix of different options. Can you provide a compelling use case that can't be solved with the existing tools?

**Comment by juliemr** [comment]
Although, thinking about this more, the suites vs specs for an individual capability doesn't affect much else. @sjelin arbitrarily assigning you.

**Comment by sjelin** [comment]
After digging into this for a while, we ended up deciding that it would add more complexity than it was worth.  If this is important to you, please open up a new issue (comments on old issues are liable to be ignored) pointing back to this one.  In your new issue, please provide example use cases.  If you an others are interested we may add the feature after all!
