### ISSUE TITLE
Is there a way to Open 2 chrome browsers side by side, instead of overlapping one another

### ISSUE THREAD

**Issue by adokania** [angular/protractor#3030]
Currently I am using the ShardTestfile feature mentioned here -http://blog.yodersolutions.com/run-protractor-tests-in-parallel/

Along with this I am using the html-screenshot-reporter and when the browsers overlap the screenshot reporting fails. 

It would be great if I can open the multiple instances of chrome next to one another as opposed to stacking them one on top of the other. Is there an option currently?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by mgiambalvo** [comment]
You could probably set the browser position and size, as discussed here: http://stackoverflow.com/questions/20023567/how-to-set-default-browser-window-size-in-protractor-webdriverjs
