### ISSUE TITLE
Included test data being written as undefined

### ISSUE THREAD

**Issue by fatmanmclone90** [angular/protractor#3043]
I am trying to reference test data using a JSON but it appears as undefined.  I am trying to use a Page Object Model and reference external test data.  When referencing the values in my test data and passing into a function they are appearing as 'undefined'

I have a simple JSON like:

    [{
			"userNameValue": "mrUserUser",
			"passwordValue": "i_am_correct"
}]

My tests then look like:

'use strict';
var testData = require('./testData/testData.json');
var AngularPage = require('./pages/logon.page.js');

describe('travel portal logon page', function () {
  var logonPage;

beforeEach(function () {
  logonPage = new AngularPage();
});
  it('should fail to logon', function() {
logonPage.loginToSite(testData.userNameValue, testData.passwordValue);
expect(logonPage.errorMessageText).toEqual('Invalid Login');
});
});

Both estData.userNameValue and testData.passwordValue are being written as 'undefined'.  I have also tried referencing using the other format of testData['userNameValue'].

Am I missing something?

Please help, thanks

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
