### ISSUE TITLE
webdriver-manager ignores NO_PROXY

### ISSUE THREAD

**Issue by dsebastien** [angular/protractor#3046]
Bug report
---

- Node Version: `4.2.4`
- Protractor Version: `3.2.0`
- Operating System and Version `Windows 10 x64`
- Configured environment variables: 
* HTTP_PROXY
* HTTPS_PROXY
* NO_PROXY

We have put ChromeDriver and Selenium jar files on a local server in our enterprise and we've used the `--alternate_cdn` argument to specify where webdriver-manager should go grab the files

- Steps to reproduce the bug

Execute `webdriver-manager update --alternate_cdn=...`
Expected behavior: successful download of selenium-server-standalone--xxx.jar, chrome driver zip, etc.

Result:
401 errors because webdriver-manager issues requests against our corporate proxy instead of going directly to the alternate_cdn.

The issue lies in the `resolveProxy` function which should check if the `NO_PROXY` environment variable is defined and if the provided fileUrl does not match against the one of the NO_PROXY values.

For example, assuming that I have the following value for NO_PROXY, then the resolveProxy function should probably return null (assuming that the request library supports that): `NO_PROXY='localhost,127.0.0.1,.local'

**Comment by cnishina** [comment]
When setting the `alternative_cdn` option, the `fileUrl` passed into the `resolveProxy` method is the alternative cdn host with the path to download the file. So digging into this method with the `proxy` option:

* it would return proxy value set on the command line
* if the proxy option was not used, it would defer to an environment variable set
* if no environment variable is set, it should return undefined

It could be that your proxy server does not know how to route to your endpoint. I would make a curl call to your sever to make sure it is reachable.

This request and #3035 are requests to change webdriver-manager that appear very specific around your corporate proxy. What you could do instead, is just run selenium standalone server. The webdriver-manager is only a simple download and start node application and could easily be replaced with a script:

download from your file server:
```
wget http://somefile
```

run the selenium server:
```
java -jar <selenium-server.jar> -port 4444 -Dwebdriver.chrome.driver=<chromedriver.exe> -Dwebdriver.ie.driver=<iedriver.exe>
```

**Comment by dsebastien** [comment]
Hi @cnishina,

Indeed this is specific to our proxy configuration. Basically it can only be used when going towards the Web. In this case, the server is on our internal network so the NO_PROXY environment variable is important to respect.

As you mention, we could probably work around this issue with a script, but it's probably as easy to add support for NO_PROXY in webdriver-manager :)

I'll try to submit a PR
