### ISSUE TITLE
sendKeys missing "code" and "key" properties for Angular 2 KeyboardEvent

### ISSUE THREAD

**Issue by alindsay55661** [angular/protractor#3067]
## Bug report
- Node Version: `4.2.4`
- Protractor Version: `3.2.2`
- Browser(s): `Chrome 49.0.2623.87`
- Operating System and Version `OSX 10.10.5`
- A relevant example test

``` javascript
it('should close when the escape key is pressed', () => {
    element(by.css('body')).sendKeys(protractor.Key.ESCAPE)
    browser.sleep(90000) // time for inspection
  })
```
- Output from running the test:

Inspect the `KeyboardEvent` in the console and note that 1) `code` is a blank string and 2) `key` is not a property. When sending the same key directly from a real keyboard (even in the window protractor is running) Angular 2 KeyboardEvent includes `code: "Escape"` and `key: "Escape"`.

**Comment by juliemr** [comment]
See https://github.com/angular/angular/issues/9419 and https://bugs.chromium.org/p/chromedriver/issues/detail?id=1411

- this is a ChromeDriver issue.

**Comment by juliemr** [comment]
Fixed in ChromeDriver. Yay!
