### ISSUE TITLE
.column() chainned method of by.repeater is not working 

### ISSUE THREAD

**Issue by wgaldino** [angular/protractor#3071]
Bug report
---

- Node Version: `5.9.0`
- Protractor Version: `3.2.0`
- Browser(s): `49.0.2623.87`
- Operating System and Version `OSX 10.11.3`
- Your protractor configuration file
```
config = {
    directConnect: true,
    // Override the timeout for webdriver to 90 seconds.
    allScriptsTimeout: 90000,
    seleniumAddress: 'http://localhost:4444/wd/hub',
    capabilities: {
        'browserName': 'chrome'
    },
    baseUrl: 'http://localhost:8080/',
    rootElement: '...',
    suites: {
      all: ['signin/*.spec.js','policy/*.spec.js','**/*.spec.js'],
      signin: ['signin/*.spec.js','policy/*.spec.js'],
      group: 'group/*.spec.js'
    },
    framework: 'jasmine2',
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 90000
    },
    //Global variables
    params: {
        //window size
        windowWidth: 1024,
        windowHeight: 768,
    },
}
```
- A relevant example test
``` javascript
it('should find the last group created', function() {
    var filteredGroupText = element(by.repeater("item in filtered_items").row(0).column('item.name'));
    expect(filteredGroupText.getText()).toEqual(groupName);
  });//end
```
- Output from running the test
```
1) test cases of group creation should find the last group created
  Message:
    Failed: unknown error: [ng:test] http://errors.angularjs.org/1.4.7/ng/test
      (Session info: chrome=49.0.2623.87)
      (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.3 x86_64)

```
After investigate a little bit on the source code and try another approaches, I end up with the same issue when I was trying to locate an element via by.binding locator. Seems to me that maybe the root cause of this odd behaviour is in the locator itself, not in the column method.

Another way to face the same issue:
``` javascript
it('should find the last group created', function() {
    var filteredGroupText = element(by.repeater("item in filtered_items").row(0)).element(by.binding('item.name'));
    expect(filteredGroupText.getText()).toEqual(groupName);
  });//end
```
In order to have the same functionality, I had to use the approach bellow. Doing that, I was able to find and assert the info that I needed.
``` javascript
it('should find the last group created', function() {
    var filteredGroupText = element.all(by.repeater("item in filtered_items")).get(rowNumber).element(by.id(columnId));
    expect(filteredGroupText.getText()).toEqual(groupName);
  });//end
```
Yes... As you can see I had to add an ID attribute to the html tag in order to avoid the usage of by.binding.

**Comment by juliemr** [comment]
Are you able to use `by.binding` at all in your code, even without chaining? I wonder if the `rootEl` in your configuration file is not part of your angular application.

**Comment by wgaldino** [comment]
Hi Julie. No I can't. Whenever I tried to use `by.binding` or even `by.model` I faced the same issue. Well, in this case the `rootEl` is the css class name of the element where I am using the ng-app directive.

**Comment by juliemr** [comment]
I suspect something is wrong with `rootEl` then. Can you do `querySelector('<your rootEl string'>)` in your browser and confirm that it actually works to find an element inside your angular application?

**Comment by wgaldino** [comment]
Hello Julie.

First of all, thanks for your patience and attention. You were right! I ran some tests this weekend on different instances of our app and I couldn't find the `rootElement`. Today I opened the source code and for my surprise the `ng-app` directive was removed and now we are using the manual alternative to bootstrap the AngularJS.

After remove the `rootElement` from the config object, I could normally use the locators `by.binding` and `by.model`. Just to give you more context, as it was an old e2e structure and at this sprint I needed to refactor and make it run in order to _revive_ our front-end set of test cases to help the QA team during the regression phase, I forgot to assess if all those settings made sense. 😄

**Suggestion**: I don't know if many people faced the same issue, but would be nice to advert on `by.model` and `by.binding` pages at documentation that in order to use these locators the user needs to point to the right element inside the config file or let the protractor uses the default element `body`. If possible/necessary I can insert this info.

Please close this issue, because it is _working as designed_.

**Comment by juliemr** [comment]
Glad it's working now! I'd be happy to look at a PR with documentation updates, feel free to add something.
