### ISSUE TITLE
Hi, I am new to this Java script, i have to work on Jasmine framework. I want to clear an element before entering a value in it, i cannot figure out how to do it ?

### ISSUE THREAD

**Issue by kanchanDM** [angular/protractor#3075]
Hi, I am new to this Java script, i have to work on Jasmine framework. I want to clear an element before entering a value in it, i cannot figure out how to do it ?

**Comment by kanchanDM** [comment]
Also Can someone tell me what is the best tool editor to work this with ?
Currently using Notepad++ to write the program and run in cmd prompt.
Wanna use some better tool.

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
