### ISSUE TITLE
addLocator Example is broken

### ISSUE THREAD

**Issue by lrajlich** [angular/protractor#3076]
> element(by.buttonTextSimple('Sign In')).isDisplayed();
WebDriverError: unknown error: Cannot read property 'querySelectorAll' of null
  (Session info: chrome=49.0.2623.110)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
....

The root issue can be solved by changing this line:
`var using = opt_parentElement,` to `var using = opt_parentElement || document,`

**Comment by NickTomlin** [comment]
Just for clarification, you are talking about [this](https://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.addLocator) page in the docs?

**Comment by lrajlich** [comment]
yes, that's the one

**Comment by cnishina** [comment]
In the example, it appears that the `querySelectorAll` of undefined `opt_parentElement` should default to the document.

@lrajlich you could make a pull request with the fix. Here's the file where the documents are being generated from. https://github.com/angular/protractor/blob/673d416b7ef5abd0953da940cfa8cf2a59650df4/lib/locators.js#L37

**Comment by lrajlich** [comment]
yes, I was able to figure out the right behavior locating and reading through the built in locator code. PR: https://github.com/angular/protractor/pull/3084
