### ISSUE TITLE
Cannot add test (describe/it) async

### ISSUE THREAD

**Issue by llafuente** [angular/protractor#3078]
- Node Version: `4.4.0`
- Protractor Version: `3.2.2`
- Browser(s): `chrome`
- Operating System and Version `Linux luis-dev 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

- A relevant example test
```js
'use strict';

describe("describe 1", function() {
  console.log("describe 1");
  it("it 1", function() {
    console.log("it 1");

    describe("describe 2", function() {
      console.log("describe 2");
      it("it 2", function() {
        console.log("it 2");
      });
    });

  });
});

```
- Output from running the test
```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
describe 1
Started
it 1
describe 2
.


1 spec, 0 failures
Finished in 0.011 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 passed
```
Expected to see `it 2` after `describe 2`

**Comment by NickTomlin** [comment]
I don't think this is a bug, this is the way that Jasmine/BDD frameworks function. You shouldn't be nesting `describe` blocks within `it` blocks. `it` is for a single test case and `describe` is for grouping those individual test cases. 

Does that make sense? Or is there something i'm missing :)

**Comment by cnishina** [comment]
This does not appear to be an issue with Protractor. I do agree with @NickTomlin that `describe` blocks within `it` blocks is probably not how Jasmine wants you to write tests. If you feel that this is a bug, then it should be for the [Jasmine project](https://github.com/jasmine/jasmine/issues).

**Comment by llafuente** [comment]
there is a test in jasmine documentation exactly doing that.

so it's a bug...

**Comment by NickTomlin** [comment]
The output you receive is exactly what I receive from running your test suite through the latest version of Jasmine. If this is a bug you should bring this up with the Jasmine team. Thanks! 😄

**Comment by cnishina** [comment]
@llafuente Could you copy and paste and reference this? I did not see anything on the jasmine documentation page that shows this. I also agree that you should open an issue with Jasmine if you believe this should work.

**Comment by llafuente** [comment]
sry. my bad...

Inside `describe` you can nest another. but not inside `it`, don't know why but I will report it to jamine.

this works.
```
'use strict';

describe("describe 1", function() {
  console.log("describe 1");
  it("it 1", function() {
    console.log("it 1");
  });

  describe("describe 2", function() {
    console.log("describe 2");
    it("it 2", function() {
      console.log("it 2");
    });
  });

});
```

From the docs: http://jasmine.github.io/2.0/introduction.html
```
Nesting describe Blocks

Calls to describe can be nested, with specs defined at any level. This allows a suite to be composed as a tree of functions. Before a spec is executed, Jasmine walks down the tree executing each beforeEach function in order. After the spec is executed, Jasmine walks through the afterEach functions similarly.
```
