### ISSUE TITLE
UnexpectedAlertOpenError

### ISSUE THREAD

**Issue by mvolkmann** [angular/protractor#308]
My web app calls alert on startup if the user is using an old version of IE such as IE8. I need my Protractor test to dismiss that alert. Just attempting to access it throws an UnexpectedAlertOpenError. Here is the line of code.

var dialog = ptor.switchTo().alert();

I was hoping after getting a reference to it, I could close it.

**Comment by vikasgahlaut** [comment]
I am still unable to use browser.switchTo().alert();  

Tried everything and it is not related to chrome driver issue as same is working fine with webdriver-java  native APIs. This is blocking usage of protractor and I am afraid I need to revert to webdriver - java API. Please update any luck on this??

**Comment by skidvd** [comment]
Having the same issue here.  

Hacky workaround: 
```
browser.executeScript("window.onbeforeunload = function(){};");
```

Above will close the onbeforenload created dialog, but obviously precludes the ability to test any associated logic and/or behavior related to it.  Are there any updates on this issue or if/when it will be resolved?

**Comment by ramdog** [comment]
Unfortunately, the hack above in https://github.com/angular/protractor/issues/308#issuecomment-91562827 is not working for me.  I have another hack that seems to be working:

```js
browser.executeScript( "window.angular.element(window).off('beforeunload');" );
```

**Comment by fyodorvi** [comment]
For anyone how's still struggling, this seems to be a proper solution:

```javascript
browser.get(url).catch(function () {

    return browser.switchTo().alert().then(function (alert) {
    
        alert.accept();
        return browser.get(url);
    
    });

});
```

**Comment by tepez** [comment]
Thanks @fyodorvi ! Your solution works.
I just had to change `.catch(...)` with `.then(null, ...)`. Probably `.catch` is only available in newer version (i use 3.0.0)

**Comment by inthegarage** [comment]
I can confirm @fyodorvi solution works. This ticket should be closed. 
My exact code for reference:

```
        browser.getCurrentUrl().then(function(url) {
            browser.navigate().refresh().catch(function() {
                return browser.switchTo().alert().then(function (alert) {
                    alert.accept();
                    return browser.get(url);
                });
            });

        });
```

**Comment by Sankannavar** [comment]
How to handle alerts in the application when we are not sure when alerts will come, for intermittent errors/alerts.

**Comment by inthegarage** [comment]
@Sankannavar that's really the point of testing though is that these are known routes with set-out test criteria that gives expected and predictable results. If your application is throwing up a whole bunch of "random" alerts your application isn't working correctly.
You need to keep each test simple and perform a single operation, which either does or doesn't give an error alert.

**Comment by Sankannavar** [comment]
@inthegarage Thanks for information.

**Comment by twaraich** [comment]
For anyone who's still struggling, I have another solution which worked for me 
`browser
        .switchTo().window(windowHandle).then(() => {
          browser.refresh().then(() => {
            console.log("success referesh");
            })
            .catch(err => {
                  browser.switchTo().alert().then(alert => {
                  browser.sleep(200);
                  alert.accept();
                  browser.sleep(200);
                });
            });
        });
    });`
