### ISSUE TITLE
Mocking data with protractor for angular2 application

### ISSUE THREAD

**Issue by Mandersen21** [angular/protractor#3082]
Hi,

I'm trying to mock data when my application makes a GET request to the api. I want to control the response, which should be a json file i create myself. 

I have found alot using the $HttpBackend which is only used together with angularjs (angular 1.xx).

Hope someone have some ideas.

**Comment by NickTomlin** [comment]
Hi there!

It looks like you want [MockBackend](https://angular.io/docs/js/latest/api/http/testing/MockBackend-class.html). That said, you probably shouldn't be mocking out an API in integration tests.

Your question is better suited for StackOverflow or an Angular 2 specific channel. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask).

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
