### ISSUE TITLE
'lib' folder not downloaded with npm install

### ISSUE THREAD

**Issue by tanneerumahesh** [angular/protractor#3089]
Hi, i installed protractor from npm using "npm install protractor" but for some reason it is not downloading lib folder and i need to use cli.js from lib folder to run my tests from ide. any idea on this?

**Comment by NickTomlin** [comment]
The built protractor files now reside in the `built` directory of the package. You should just be able to direct your IDE to `built/cli.js`

**Comment by tanneerumahesh** [comment]
Thanks Nick

**Comment by csqa** [comment]
Thank you

**Comment by kmurthyece** [comment]
@NickTomlin, @tanneerumahesh  : i tried to use cli.js from built in webstorm editor but when i am trying run the conf.js file i am getting "Process finished with exit code 0" could you please help me in fixing this issue.

**Comment by rohitnirantar** [comment]
@NickTomlin It worked thanks.
