### ISSUE TITLE
getCapabilities()

### ISSUE THREAD

**Issue by msviha** [angular/protractor#3091]
Bug report
---
- Node Version: `4.2.6`
- Protractor Version: `3.2.2`

used default config and test `angularjs homepage todo list`

added into test
```
browser.getCapabilities().then(function (x) {
        console.log(x.caps_.browserName)
    })
```
cause **Cannot read property 'browserName' of undefined**

since capabilities by getProcessedConfig() working

**Comment by cnishina** [comment]
Hi, something like this will get your capabilities for browser name:
```
describe('specs loaded to selenium', function() {
  it('should have the right capabilities', function() {
    browser.get(browser.baseUrl);
    browser.getCapabilities().then(function(capabilities) {
      console.log('browserName:', capabilities.get('browserName'));
    });
  });
});
```
This looks like a support question. Please ask further support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
