### ISSUE TITLE
HTTP/AJAX Mocking and assertions

### ISSUE THREAD

**Issue by appleton** [angular/protractor#31]
Currently I'm running my tests against a server which responds to my AJAX requests with canned chunks of JSON. It would be great to be able to make assertions against these requests in a similar way to karma

``` JS
$httpBackend.expectGET('some/url').respond({some: 'JSON'});
```

The only solution I have right now is to run protractor and my connect server in the same process and then write an interface a bit like this manually.

I'd love to get a discussion going about plans to deal with this in protractor.

**Comment by AQadeer** [comment]
i think this can be the good solution. Which i am using right now.
http://stackoverflow.com/a/34610987/3840665
