### ISSUE TITLE
module is not a function on using Firefox; chrome not reachable on using chrome.

### ISSUE THREAD

**Issue by AngJSofJJ** [angular/protractor#3102]
**$ protractor protractor.conf.js
**DEBUG - Running with --troubleshoot
DEBUG - Protractor version: 3.2.2
DEBUG - Your base url for tests is http://localhost:9000
Using FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver
DEBUG - WebDriver session successfully started with capabilities Capabilities {
  'cssSelectorsEnabled' => true,
  'browserName' => 'firefox',
  'handlesAlerts' => true,
  'javascriptEnabled' => true,
  'nativeEvents' => false,
  'platform' => 'WINDOWS',
  'rotatable' => false,
  'takesScreenshot' => true,
  'version' => '45.0.1',
  'webStorageEnabled' => true,
  'applicationCacheEnabled' => true,
  'databaseEnabled' => true,
  'locationContextEnabled' => true,
  'acceptSslCerts' => true }
DEBUG - Running with spec files C:\yoprojects\productsarchive\test\spec\controllers\main.js
Started
F

Failures:
1) Controller: MainCtrl encountered a declaration exception
  Message:
    TypeError: module is not a function
  Stack:
    TypeError: module is not a function
        at Suite.<anonymous> (C:\yoprojects\productsarchive\test\spec\controllers\main.js:7:14)
        at Object.<anonymous> (C:\yoprojects\productsarchive\test\spec\controllers\main.js:3:1)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)

1 spec, 1 failure
Finished in 0.014 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

**Comment by NickTomlin** [comment]
Please follow the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening support requests.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this because there hasn't been any movement. If this is still an issue please open up a new issue and follow the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE).
