### ISSUE TITLE
Website should link to selenium-webdriver docs for lesser-used features

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3107]
Now that we've added custom docs for everything that's used differently in protractor, we should link to the selenium-webdriver docs for advanced usage.

Instead of listing everything on the side bar, we should have the `webdriver` section link to a page explaining that everything available with `require('selenium-webdriver')` in their docs is available on the `protractor` global. (This page should include a few examples). Then just link to their site. Unfortunately, the site is not versioned, but we should be keeping up with the latest version of selenium-webdriver closely.

Their site: http://seleniumhq.github.io/selenium/docs/api/javascript/

cc @sjelin @cnishina

**Comment by sjelin** [comment]
Right back at you Julie :wink:

**Comment by juliemr** [comment]
See 47b8310bae827bb032fac849939a7b9bfccc2367
