### ISSUE TITLE
 Angular could not be found on the page 

### ISSUE THREAD

**Issue by spengilley** [angular/protractor#3118]
Bug report
---

Running the most basic of protractor tests and getting;

> Angular could not be found on the page http://localhost:63342/protractor_basic/index.html : angular never provided resumeBootstrap

- Node Version: `5.1.0`
- Angularjs Version: '1.2.29'
- Protractor Version: `3.2.2`
- Browser(s): `Chrome 49.0.2623.110`
- Operating System and Version `OSX El Capitan`

**protractor conf.js**
`exports.config = {
    framework: 'jasmine',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['*spec.js']
}
`

**spec.js**
`describe('foo page', function() {

    it('Should find foo on page', function() {

        browser.get('http://localhost:63342/protractor_basic/index.html');
        expect(element(by.id('foo')).getText())
            .toContain('foo');

    });

});
`
**Output from running the test**
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Started
F

Failures:
1) foo page Should find foo on page
  Message:
    Failed: Angular could not be found on the page http://localhost:63342/protractor_basic/index.html : angular never provided resumeBootstrap
  Stack:
    Error: Angular could not be found on the page http://localhost:63342/protractor_basic/index.html : angular never provided resumeBootstrap
        at /usr/local/lib/node_modules/protractor/built/protractor.js:680:17
        at Promise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
        at process._tickCallback (node.js:379:9)
    From: Task: Run it("Should find foo on page") in control flow
        at Object.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:81:14)
    From asynchronous test: 
    Error
        at Suite.<anonymous> (/Users/stephen/Development/playtime/protractor_basic/spec.js:3:5)
        at Object.<anonymous> (/Users/stephen/Development/playtime/protractor_basic/spec.js:1:1)
        at Module._compile (module.js:425:26)
        at Object.Module._extensions..js (module.js:432:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)

1 spec, 1 failure
Finished in 10.368 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #01 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

**[EDIT]**
If I upgrade angularjs to 1.3.x it works fine. Do I then need to downgrade something else to get this to work?

**Comment by spengilley** [comment]
[EDIT]
I am currently running Angularjs version 1.2.29 (need to support IE8)

If I upgrade angulate to 1.3.x the tests run fine.

**Comment by spengilley** [comment]
I fixed this by downgrading protractor to version 2

**Comment by santosh0503** [comment]
Hi I am facing same issues.
14:41:19 [31mF[0m[09:11:19] E/protractor - Could not find Angular on page http://localhost:3000/index.html : retries looking for angular exceeded
14:41:30 [31mF[0m[09:11:30] E/protractor - Could not find Angular on page http://localhost:3000/index.html : retries looking for angular exceeded
14:41:40 [31mF[0m[09:11:40] E/protractor - Could not find Angular on page http://localhost:3000/index.html : retries looking for angular exceeded
14:41:50 [31mF[0m[09:11:50] E/protractor - Could not find Angular on page http://localhost:3000/index.html : retries looking for angular exceeded

**Comment by Nesreenmoh** [comment]
Have you found a solution for this problem?  I am facing the same thing?
