### ISSUE TITLE
Protractor exits on failure with exit status 1 and rest of the test cases will not execute

### ISSUE THREAD

**Issue by Vinayak123Kalyani** [angular/protractor#3119]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

  I have bunch of test cases in protrcator config file, but protractor execution stops if there is any functional issue, and am using cucumber with protractor, Can anyone help me onto this

Thanks,
Vinayak
Bug report
---

- Node Version: 4.2.1`
- Protractor Versin: `2.3.0`
- Browser(s): `chrome`
- Operating System and Version ` windows 8.1`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by smalldragonvt** [comment]
I think you should edit the runner.js of Protractor like this : 

Change the line 

require('source-map-support').install();
 to 
require('source-map-support').install({
	  handleUncaughtExceptions: false
  }); 

This will solve your problem. Please refer this for more information : 
https://github.com/angular/protractor/issues/876
