### ISSUE TITLE
@onComplete / onCleanUp function, I am unable to read json file generated from resultJsonOutputfile

### ISSUE THREAD

**Issue by nsainathuni** [angular/protractor#3126]
Hi there!

- Node Version: `4.2.3`
- Protractor Version: `3.1.1`
- Browser(s): `Chrome`
- Operating System and Version `Windows 7`

I see that json file is not yet created even after control is at onComplete / onCleanUp. Let me know if I am doing it incorrectly.

**Comment by mgiambalvo** [comment]
Could you share your config file and maybe an example path? Are you sure that path you've set in resultJsonOutputFile is correct?

**Comment by nsainathuni** [comment]
Here is the config file path for json & html

exports.config = {
..........
..........
getExecutionTime = 'A function which returns datetime format'

 resultJsonOutputFile: path.join(process.cwd(), 'Execution' , 'ExecutionResults' , getExecutionTime + 'ExecutionReport.json'),
...............
onCleanUp: function (exitCode) {
var jsonreport = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'Execution' , 'ExecutionResults' , getExecutionTime + 'ExecutionReport.json');

}
.......
}

**Comment by nsainathuni** [comment]
Before I added onCleanUp function, I used to get execution report in json format as per the resultJsonOutputFile. Once I have added onCleanUp function, It errors out at "var jsonreport = JSON.parse" stating that it could not find the file mentioned in the path.

Perhaps I believe protractor generates json file after onCleanUp function is completed. Can someone throw light on the control flow execution of Protractor in this case ?

From reference file, I understand test case execution is completed when onCleanUp function is called, but it was not mentioned whether result file {in json format} would have been created by then.

**Comment by mgiambalvo** [comment]
Ah, I see what you mean now. Yes, the json result file isn't written until after all the tests have finished running, which means it won't be present when onCleanUp is called. Here's where it gets written: https://github.com/angular/protractor/blob/master/lib/launcher.js#L247

**Comment by nsainathuni** [comment]
thank you @mgiambalvo

**Comment by nsainathuni** [comment]
Alternative is to use the same code in afterLaunch: function (exitcode) {
}
this worked for me.
