### ISSUE TITLE
Marionette driver with protractor

### ISSUE THREAD

**Issue by smhc** [angular/protractor#3134]
Due to click handling regressions in the firefox driver included with Selenium 2.53 I have been trying to use the new marionette driver instead but with limited success. Firefox opens the base URL but doesn't appear to bootstrap angular and doesn't run any tests. (Firefox 45.0.2). There are no errors to the console.log.

It is possibly due to the errors:
Error: Permission denied to access property "href"
Error: Permission denied to access propernty "tag"

I have attached the selenium log:
[selenium.txt](https://github.com/angular/protractor/files/222907/selenium.txt)

I suspect this is probably a selenium/marionette/firefox problem rather than protractor however I'm curious if anyone else has managed to get it working. There hasn't been any mention of it through protractor issues or the repo. There has been a few issues raised with selenium relating to the sandboxing of executescript that may be related.

Are there any changes required to protractor or my setup to get it working? Is the marionette driver expected to be working at this point?

**Comment by smhc** [comment]
After some further investigation this issue [https://github.com/jgraham/wires/issues/15] appears to be the most likely cause of the problem.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this because it seems like it's an external issue that isn't actionable on our part. Feel free to open an additional issue if there's something broken in Protractor itself.
