### ISSUE TITLE
Unable to Handle model dialog in two different it().

### ISSUE THREAD

**Issue by Kothajagadeesh** [angular/protractor#3137]
Hi,

I've a scenario where clicking on a button will cause alert pop-up for a non-angular js app
![alert](https://cloud.githubusercontent.com/assets/10230839/14643935/f12cca66-066d-11e6-8b71-c1f9c14aa1c3.JPG)
![alerterror](https://cloud.githubusercontent.com/assets/10230839/14643936/f143ed5e-066d-11e6-8161-b470076f72fd.JPG)

. I need to read the text inside the alert (alert.getText() is working) and then accept it(alert.accpet() working also). However, when i split alert.getText() and alert.accept() to two different its() the script is failing with Model dialog present

i Need to alert.getText() and alert.accept() in two different its(). Could some one please let me know if that is possible?

ENV:
Protractor 3.0.0.
IE 9.0
jasmine 2.x

Regards,
Jagadeesh

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
