### ISSUE TITLE
Unable to display stack trace when test fails

### ISSUE THREAD

**Issue by isian8814** [angular/protractor#3140]
I've run the protractor test with latest version 3.2.2
```
And the follwing are the chromewebdriver version.
-rw-r--r--  1 root  staff   3.6M Apr 20 16:42 chromedriver_2.21mac32.zip
-rwxr-xr-x  1 root  staff    11M Apr 20 16:42 chromedriver_2.21*
-rw-r--r--  1 root  staff    30M Apr 20 16:42 selenium-server-standalone-2.52.0.jar
```

When test fails, it won't give the stack trace, which is really hard to debug the code.

Here is what I got
`Message:
    Failed: unknown error: Element is not clickable at point (407, 409). Other element would receive the click: <div id="addDomainModal" class="mod-modal ui-dialog-content ui-widget-content" scrolltop="0" scrollleft="0" style="display: block; width: auto; min-height: 0px; height: 347px;">...</div>
      (Session info: chrome=49.0.2623.112)
      (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Mac OS X 10.11.4 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 26 milliseconds
    Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
    System info: host: 'Mins-MacBook-Pro.local', ip: '10.33.203.248', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.4', java.version: '1.8.0_73'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, chrome={chromedriverVersion=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4), userDataDir=/var/folders/ds/ybsh745j3qj5xm3_yc1956r80000gn/T/.org.chromium.Chromium.o155pw}, takesHeapSnapshot=true, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=49.0.2623.112, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
    Session ID: 9612885f1a396ff57de96f286ddafdaf`

Could anyone help me with this?

**Comment by NickTomlin** [comment]
The stack trace contains the following: 

```
Element is not clickable at point (407, 409). Other element would receive the click: <div id="addDomainModal" class="mod-modal ui-dialog-content ui-widget-content" scrolltop="0" scrollleft="0" style="display: block; width: auto; min-height: 0px; height: 347px;">
```

Which, unless there is something else strange going on, means that the `addDomainModal` is probably positioned over the element you are trying to click.

Additionally your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks! 😄
