### ISSUE TITLE
How can we assign the result of asynchronous method result value to global scope in protractor 

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3145]
I have a use case where i need to get the value from the database and that value has to be used many times in a jasmine test .

So , my question do we need to assign in global scope or use flow,execute() method .
Can i know which one should I use.

 describe('Testing suite', function() {
    it('testing spec', function() {
        browser.get(browser.baseUrl);
        var number;
        database.generateMobileNumber().then(function(mobileNumber) {
            console.log(mobileNumber);
            number = mobileNumber;
            console.log(number);
        });
        console.log(number);
    });
});

**Comment by Xotabu4** [comment]
@vivekbrahmadandi 
Hi, i think you might find this useful - https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L239
so in your protractor.config
```javascript
// onPrepare can optionally return a promise, which Protractor will wait for
  // before continuing execution. This can be used if the preparation involves
  // any asynchronous calls, e.g. interacting with the browser. Otherwise
  // Protractor cannot guarantee order of execution and may start the tests
  // before preparation finishes.

  onPrepare: function() {
    return database.generateMobileNumber().then(function(mobileNumber) {
    console.log(mobileNumber);
    global.mobileNumber = mobileNumber;
});

```

So idea is to return promise in onPrepare() and protractor will wait for it.
But adding such globals might be unsafe. Or you can try to play with browser.wait()

**Comment by vivekbrahmadandi** [comment]
Firstly thanks for your reply, I want to assing in jasmine test file scope. when I assign it is show as lib$es6$promise$promise$$Promise {
  _id: 9,
  _state: undefined,
  _result: undefined,
  _subscribers: [] }


But I need a value

**Comment by vivekbrahmadandi** [comment]
I have to call for each jasmine suite file that function

**Comment by Xotabu4** [comment]
@vivekbrahmadandi 
Also you can try generate many numbers - 1000, 2000 and put them into global array in onPrepare
Then in your test - just .pop() number each time you need it.

Or you can try to play with browser.wait()

```javascript
database.generateMobileNumber()

```

**Comment by NickTomlin** [comment]
Thanks for helping out @Xotabu4!

@vivekbrahmadandi i'm going to close this issue because it falls under the usage/debugging category listed in the issue template and contributing document. Please direct these sorts of questions to SO or gitter in the future. Thanks! 😄 


> Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
