### ISSUE TITLE
by.binding() doesn't find double curly braces bindings

### ISSUE THREAD

**Issue by jfranki** [angular/protractor#3147]
When testing with Protractor (v3.2.2) a very simple angular (v1.5.3) app, `by.binding()` locator does not find any element when I am searching for an object's value referenced by double curly braces inside an `ng-repeat` block, like so:

```
firstComment = element.all(by.repeater('comment in comments')).first();
...
var commentLikes = firstComment.element(by.binding('comment.likes'));
expect(commentLikes.getText()).toBe(1);
```

HTML:
```
<li ng-repeat="comment in comments">
	{{comment.value}}
	<button type="button" ng-click="like(comment)">like</button>
	{{comment.likes}}
</li>
```
Output: 

> Failed: No element found using locator: by.binding("comment.likes")

If I try the same test but with actual `ng-binding` directive:
```
<li ng-repeat="comment in comments">
	<span ng-bind="comment.value"></span>
	<button type="button" ng-click="like(comment)">like</button>
	<span ng-bind="comment.likes"></span>
</li>
```
the binding is found BUT in string mode. Output:

> Expected '1' to be 1.

I am new to e2e testing and testing in general, is this normal? I have checked the [documentation](http://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.binding) but everything seems right.

**Comment by barinali** [comment]
If I don't know wrong this, it's very normal. There is a note in that [docs page](http://www.protractortest.org/#/api?view=ProtractorBy.prototype.binding). 

> Note: For AngularJS version 1.2, the interpolation brackets, (usually {{}}), are optionally allowed in the binding description string. For Angular version 1.3+, they are not allowed, and no elements will be found if they are used.

**Comment by jfranki** [comment]
@barinali I am not using the interpolation brackets in the binding description string, as shown in the docs:
```
// This works for sites using Angular 1.2 but NOT 1.3
var deprecatedSyntax = element(by.binding('{{person.name}}'));
```
I am referencing it like this:
`var commentLikes = firstComment.element(by.binding('comment.likes'));`
As you can see I am ommitting the brackets.

**Comment by sjelin** [comment]
If you switch to

```js
<li ng-repeat="comment in comments">
    {{comment.value}}
    <button type="button" ng-click="like(comment)">like</button>
    <span>{{comment.likes}}</span>
</li>
```

Does that help?

**Comment by jfranki** [comment]
@sjelin When trying your suggestion and putting the binding between span tags the test passes, BUT it happens the same thing that happens if I would use the `ng-bind` directive:

> Expected '1' to be 1.

I don't know why the value is converted to String and eventually the test fails... I tried putting it inside an empty div with the same results.

**Comment by NickTomlin** [comment]
@jfranki why do you expect it to be a `Number`?  `getText` returns a string, why not just compare it to a string?

**Comment by juliemr** [comment]
The problem is that you're trying to find a child element of the `<li>`, but it has no child element with that binding (only text nodes). This is working as intended.

As for the number vs string, Nick is right, `getText` always returns a string. This is also intended behavior.
