### ISSUE TITLE
document unloaded while waiting for result (public version of our angular js in login and actual angular after login)

### ISSUE THREAD

**Issue by hanssgo** [angular/protractor#315]
So our login has a public version of our angular app and after login, we have the actual angular app. 

After login, it never syncs and gives this error 
UnknownError: javascript error: document unloaded while waiting for result

So my tests after login works with browser.ignoreSynchronization = true;

However, I want to be able to run the tests with synchronization so I do not have to put so many waits. Is there a way around this? Is my suspicion that the reason for my problem is because the public version of our js gets unloaded after login and loads the main app's js?

**Comment by malisanjay5433** [comment]
Error after calling the plugin method. 

```
 await driver.switchToWebContext();
 await driver.pluginMethod(
      'switch',
      'switchServer()',
    );
```
javascript error: document unloaded while waiting for result
  (Session info: chrome=103.0.5060.71)

ERROR webdriver: Request failed with status 500 due to javascript error: javascript error: document unloaded while waiting for result
