### ISSUE TITLE
Get selenium node host name 

### ISSUE THREAD

**Issue by angelblade27** [angular/protractor#3158]
I have been trying to figure out how to grab the selenium node hostname on which a test is running against.  I came across this solution http://stackoverflow.com/questions/6898735/selenium-2-grid-knowing-which-node-your-test-is-using and was trying to port it over to javascript. However it seems that the browser session ID isn't giving me the session id from the hub.

```
browser.getSession().then(function (session) {
    var hub = "http://localhost:4444"; //IP or hostname of GRID

    var url = hub + "/grid/api/testsession?session=" + session.getId();
    console.log(url);
});
```
When I query the url outputted I get 
```{"success":false,"msg":"Cannot find test slot running session 8ca57382-d7d8-44ae-b3bc-8c1223c86805 in the registry."}```
I also tried using browser.getCapabilties as well but it returns the same session id. 

Bug report
---

- Node Version: `v0.12.7`
- Protractor Version: `~2.5`
- Browser(s): `Chrome`
- Operating System and Version `MAC OS `

- Steps to reproduce the bug

**Comment by juliemr** [comment]
Are you sure the session has not already completed by the time you query it? Your method looks right.

**Comment by angelblade27** [comment]
Yup that was it
