### ISSUE TITLE
[Feature Request] Add to Protractor a run plan that runs tests multiple times

### ISSUE THREAD

**Issue by exbuddha** [angular/protractor#3161]
Feature Request
---

I am not sure if this has already been discussed/addressed but wouldn't it be desirable to give Protractor users the ability to run a single spec multiple times (back-to-back) at the code level rather than the process level?

What I mean by that is that, I am encountering many automated UI tests that fail randomly due to errors that are usually outside of the scope of Protractor framework itself and are caused by other parts of the solution (Selenium for instance). These errors have been a pain point in the past, have proven to be completely random, and are my number one enemy as an automation/CI engineer.

One solution would be to devise an execution plan that runs each spec multiple times until it passes just once. This way the tester will have a better chance of handling these false alarms that would otherwise be counted as failures and he/she doesn't have to write a wrapper tool around protractor to create this execution plan.

Something similar to:

    var maxRuns = 100;
    var passThreshold = 1;
    describe ('shaky test suite', function() {
        it('this test runs at most 100 times until it passes once', function() {
            // ...
        }, timeout, maxRuns, passThreshold);
    });

**Comment by NickTomlin** [comment]
I believe this is covered by https://github.com/angular/protractor/issues/1190. There are a few different solutions to the flakey test issue in that thread but it's definitely an ongoing conversation. 

I'm going to go ahead and close this for now. Please let me know if that doesn't express your issue 😄
