### ISSUE TITLE
Website API docs should be organized by global variable

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3163]
Instead of filename (useless to users), we should organize the docs by global variable:

```
browser
element
$/$$
by
protractor
```

And we should provide some sort of zippy or top-level links to make seeing these in the sidebar easier.

**Comment by juliemr** [comment]
cc @andresdominguez

**Comment by andresdominguez** [comment]
I will work on this one. Will send a PR

**Comment by juliemr** [comment]
Done! Huzzah.
