### ISSUE TITLE
Deps - upgrade selenium-webdriver + friends to 2.53

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3167]
selenium-webdriver now has v2.53.1

And selenium standalone + IE driver have v 2.53.0.

**Comment by cnishina** [comment]
selenium standalone = 2.53.0 and iedriver = 2.53.1.

**Comment by juliemr** [comment]
Ah thanks!

**Comment by cnishina** [comment]
selenium webdriver 2.53.2 is released. Time to upgrade the `package.json`.
