### ISSUE TITLE
Export TS Typings

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3169]
Now that Protractor is written in TS, we should consolidate and export typings via npm - see http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by Meligy** [comment]
Is that a matter of just adding this line to the packages.json file?

```
{
    ...
    "typings": "./lib/globals.d.ts"
    ...
}
```

Is there anything special with being globals or so?

**Comment by cnishina** [comment]
I'm currently working on this... this will be broken down into several steps:

- Move protractor.ts to browser.ts to clean up the namespaces that are exported
  - Fix selenium webdriver api's that have changed
  - Fix *.prototype in the code base
- Create a protractor.d.ts file. Add a build rule to concat the *.d.ts file under the protractor namespace
- Create an example that uses the protractor.d.ts file and look for issues on typings that are missing
- Fix definitely typed selenium webdriver to remove the webdriver namespace from global.d.ts

**Comment by cnishina** [comment]
Adding PRs that got us here: #2902, #2919, #2948, #2965, #3114, #3138, #3141, #3142, #3143, #3148, #3149, #3151, #3152, #3153, #3156, #3214, #3271, #3279, #3281, #3288, #3307

**Comment by cnishina** [comment]
@Meligy Added typings to package.json (pr #3298)

package.json:
```
{
  ...
  "typings": "built/index.d.ts",
  ...
}
```

**Comment by hawkerm** [comment]
Are there any examples yet of what a TS version of the config file and a test suite look like?

**Comment by igniteram** [comment]
@hawkerm you can find them here : https://github.com/angular/protractor/tree/master/exampleTypescript

**Comment by juliemr** [comment]
Done!
