### ISSUE TITLE
website "view code" links return 404

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3170]
(will provide an example)

**Comment by cnishina** [comment]
ExpectedConditions.and `View code`

View code links to https://github.com/angular/protractor/blob/3.3.0/lib/expectedConditions.js

It should link to https://github.com/angular/protractor/blob/3.3.0/lib/expectedConditions.ts

**Comment by Xotabu4** [comment]
Could it be possible to also return protractor.promise API to website documentation (protractor.promise.all, protractor.promise.defer and other) used it a lot, but with last documentation website version they disappeared.
