### ISSUE TITLE
shardTestFiles launching multiple instances of chrome but tests only execute on one

### ISSUE THREAD

**Issue by amcinerney** [angular/protractor#3171]
## Bug report
- Node Version: `v4.2.1`
- Protractor Version: `v3.1.1`
- Browser(s): `chrome 49`
- Operating System and Version `windows 8.1`

My protractor config has the following multiCapabilities set in it

`maxSessions: 5,
    multiCapabilities: [{
        'browserName': 'chrome',
        'shardTestFiles': true,
        'maxInstances': 3
    },{
        'browserName' : 'firefox',
        'shardTestFiles': true,
        'maxInstances': 3
    }]`

This seems to work as expected with firefox (3 instances of firefox are launched and tests execute on all 3). However in chrome 3 instances are launched but tests only execute on one of the instances. I can't find any explanation why and there aren't any errors output the the console. The website URL remains `data:,` the entire time. When the running instance of chrome finishes executing the spec the instance closes and opens a new instance for the next spec but the other two inactive browser windows remain inactive.

**Comment by amcinerney** [comment]
Has anyone had a chance to investigate this?

**Comment by Anthonyo2015** [comment]
I'm not certain if this is related, but I have noticed when I have say 15 spec files to run, and I shard these tests with a max of 5 instances, 5 browsers open up and begin to run 1 full spec each. All close afterwards except for one browser instance. This final instance then runs all of the remaining tests. Basically 4 browsers run one spec and the fifth runs all the rest. I assumed the browsers would share the test among the max instances until all spec files have been completed. Is this correct behavior?

**Comment by juliemr** [comment]
I cannot reproduce this with the latest version of Protractor. It's worth noting that Protractor shards tests by file, not by test case, so if you have only one file only one instance of chrome will run.
