### ISSUE TITLE
Feature Request: add "directConnect" config option to CLI

### ISSUE THREAD

**Issue by xiehan** [angular/protractor#3175]
Feature Request
---

- **Reasons for adopting new feature:** We have a server which periodically executes the end-to-end tests (powered by Jenkins), but also run the tests locally from time to time (particularly when adding or updating tests) when the `directConnect` option is a nice, time-saving feature; it'd be wonderful to be able to do e.g. `npm run e2e -- --directConnect=true` or just `npm run e2e -- --directConnect` rather than having to edit protractor.conf.js or juggling multiple config files.
- **Is this a breaking change?** Nope! Existing functionality should not be affected.

**Comment by juliemr** [comment]
You can already do this:

```
protractor my-conf.js --directConnect
```

Please open up a new bug report if this isn't working for you for some reason.

**Comment by pakhuta** [comment]
What about --directConnect=false? It doesn't work, because config.directConnect === 'false'. So, it always will be `true`. Please fix it https://github.com/angular/protractor/blob/master/lib/driverProviders/index.ts#L32
