### ISSUE TITLE
--allow-unchecked-dangerous-downloads being Ignored?

### ISSUE THREAD

**Issue by equilerex** [angular/protractor#3177]
args for download handling in the conf file seem to be ignored... been googling the hell out of it and seems like lots of people have the issue but no answers anywhere...

cant test download functionality since it just results in chrome asking if you want to keep the file or not with "This type of file can harm your computer. Do you want to keep xmldata.xml anyway" 

as i understand, --allow-unchecked-dangerous-downloads and --safebrowsing-disable-extension-blacklist should take care of it but its not happening... any ideas on a solution?  

 `capabilities: {
            browserName: 'chrome',
            chromeOptions: {
                args: ['--allow-unchecked-dangerous-downloads="true"', '--safebrowsing-disable-extension-blacklist="true"'],
                prefs: {
                    download: {
                        prompt_for_download: false,
                        directory_upgrade: true,
                        default_directory: 'C:/tmp/downloads'
                    }

                }
            } 
        },`

**Comment by cnishina** [comment]
This appears to be a support question about chromedriver and not a bug or feature for protractor.

For chromedriver capabilities and chromeOptions: https://sites.google.com/a/chromium.org/chromedriver/capabilities

For the full list of chromeOption args: http://peter.sh/experiments/chromium-command-line-switches/#condition-3
