### ISSUE TITLE
[feature] Enable using marionette driver with later versions of Firefox (v45+) in directConnect mode

### ISSUE THREAD

**Issue by jrharshath** [angular/protractor#3182]
Hi all,

I'm running protractor version 3.0.0 against Firefox 46.0 with direct connect enabled. However, I see that even after firefox starts, protractor is unable to connect to it. The error trace I get is this:

```
/opt/noarch/npm/node_modules/selenium-webdriver/http/util.js:89
          Error('Timed out waiting for the WebDriver server at ' + url));
          ^
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:33459/hub
    at Error (native)
    at onResponse (/opt/noarch/npm/node_modules/selenium-webdriver/http/util.js:89:11)
    at /opt/noarch/npm/node_modules/selenium-webdriver/http/util.js:44:21
    at /opt/noarch/npm/node_modules/selenium-webdriver/lib/webdriver/http/http.js:140:5
    at ClientRequest.<anonymous> (/opt/noarch/npm/node_modules/selenium-webdriver/http/index.js:174:7)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:265:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/opt/noarch/npm/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/opt/noarch/npm/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at new Driver (/opt/noarch/npm/node_modules/selenium-webdriver/firefox/index.js:278:36)
    at [object Object].DirectDriverProvider.getNewDriver (/opt/noarch/npm/node_modules/protractor/lib/driverProviders/direct.js:75:16)
    at [object Object].Runner.createBrowser (/opt/noarch/npm/node_modules/protractor/lib/runner.js:186:37)
    at /opt/noarch/npm/node_modules/protractor/lib/runner.js:276:21
    at _fulfilled (/opt/noarch/npm/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/opt/noarch/npm/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/opt/noarch/npm/node_modules/protractor/node_modules/q/q.js:759:13)
    at /opt/noarch/npm/node_modules/protractor/node_modules/q/q.js:525:49
```

I'm unable to reproduce the same error on other servers that I have though - firefox works fine on them.

The error occurs regardless of whether I use Xvfb as the display or a VNC created X display. I used a VNC client to connect to the display and ensure that firefox actually comes up.

Any ideas what could be causing this error?

**Comment by T3KT4K** [comment]
Could you post your config file please?

**Comment by sahitindra** [comment]
Hi,
Any resolution for this?

**Comment by jrharshath** [comment]
The issue seems to be that we're using Firefox v46, and the default FirefoxDriver has problems with it.

https://github.com/eviltester/startUsingSeleniumWebDriver

I'll attempt to use the new Marionette driver and post my findings.

**Comment by jrharshath** [comment]
After going through Mozilla's own [documentation about Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver), and trying out another [how-to](http://seleniumsimplified.com/2016/04/how-to-use-the-firefox-marionette-driver/), I realize that these are methods to instruct Selenium to use the marionette driver when communicating with Firefox.

Now this is a question to the protractor experts: Is there a way we instruct protractor to use the new driver when running it in `directConnect` mode?

**Comment by jrharshath** [comment]
I did some more testing with `directConnect` enabled with different versions of firefox. Both versions 46.x and 45.x run into the timeout problem that I mentioned. v44 works fine though.

**Comment by soniassharma** [comment]
I am also facing same issue with Firefox 46 and even with Firefox v44.0, with Firefox v44.0.2 it works.
any idea if this is getting fixed from protractor side?

**Comment by aullman** [comment]
Any word on this? Firefox 47 has just come out and it only works with Marionette now. 
https://www.mozilla.org/en-US/firefox/47.0/releasenotes/

How am I supposed to get Firefox to work with Protractor now?

**Comment by jrharshath** [comment]
@aullman are you also using Firefox in directConnect mode?

**Comment by aullman** [comment]
@jrharshath yes, I'm using it with directConnect.

**Comment by jrharshath** [comment]
Okay. Thanks for updating this thread. Since we've found this problem, we're still using the latest version of FF that supports FirefoxDriver (v38.7). We've been unable to upgrade since we're waiting for support for Marionnette to come to protractor as well.

**Comment by cnishina** [comment]
Although this issue is about `directConnect`, tagging a `webdriver-manager` issue. Has anyone got marionette working with Protractor yet?

https://github.com/angular/webdriver-manager/issues/52

**Comment by cnishina** [comment]
The latest Firefox appears to work with Protractor (47.0.1). Firefox versions that work with Protractor: versions up to 44.x.x and versions 47.0.1+.

I am closing this issue in favor of keeping track of this in angular/webdriver-manager#52.
