### ISSUE TITLE
`getLocationAbsUrl()` does not (always) return `$location.absUrl()`

### ISSUE THREAD

**Issue by gkalpak** [angular/protractor#3185]
## Bug report
- Protractor Version: `3.3.0`
- A relevant example test
  
  ``` js
  browser.get('http://angular.github.io/protractor/#/api');
  expect(browser.getLocationAbsUrl()).toBe('http://angular.github.io/protractor/#/api');
  ```
- Output from running the test
  
  > Expected `/api` to equal `'http://angular.github.io/protractor/#/api'`.

As seen in [protractor.ts#L864-L869](https://github.com/angular/protractor/blob/7b0302c952f200231957c3857050e0fa8d5b09d3/lib/protractor.ts#L864-L869) and [clientsidescripts.js#L651-L658](https://github.com/angular/protractor/blob/7b0302c952f200231957c3857050e0fa8d5b09d3/lib/clientsidescripts.js#L651-L658), the return value of `getLocationAbsUrl()` is different when `angular.getTestability` is available and most importantly it is not the `absUrl` (in the `$location` sense).

Basically, when `angular.getTestability` is not available, `$location.absUrl()` is returned (which is the expected behavior). But when `angular.getTestability` is available (i.e. since AngularJS v1.3.0-rc.0 - see [angular.js#85880a6](https://github.com/angular/angular.js/commit/85880a64900fa22a61feb926bf52de0965332ca5)), `$location.url()` is returned instead (because that is what `$$testability` returns).

This is the case since at least Protractor v1.1.1 (see 0e9c2f4).
## 

Returning `$location.url()` from a function named `getLocationAbsUrl()` isn't very intuitive, but this has been the case for a long time. For the next breaking release, it might be a good idea to expose two methods (on Protractor _and_ `$$testability`) to retrieve both the `.url()` and the `.absUrl()`, e.g. `getLocationUrl()` and `getLocationAbsUrl()`.

**Comment by juliemr** [comment]
Yeah, this one's got an ugly history. See https://github.com/angular/protractor/issues/3097 and https://github.com/angular/protractor/issues/778

Is there a reason you can't use `getCurrentUrl`? We should really be discouraging `getLocationAbsUrl`.

Agree with potentially breaking for sanity at next breaking release.

**Comment by gkalpak** [comment]
No reason I can't use `getCurrentUrl` (except I am not sure it works on IE).

Basically, I think that (for Angular pages) `getLocationUrl()` (returning `$location.url()`) would be the most useful one (and in fact _that_ is what `getLocationAbsUrl()` currently returns).

I reported this mostly because (1) the documentation is wrong and/or (2) the behavior is unexpected (i.e. the returned value doesn't match the name). I wasn't sure though how it should be best handled.

**Comment by bbaia** [comment]
Introduced by commit 0e9c2f49dbe8cdbe56a2ce270f504e26cea0a111, why don't you remove the lines  added in `getLocationAbsUrl` until it's supported in `$$testability` ?

**Comment by gkalpak** [comment]
@bbaia, the problem is not with fixing this (it's easy to change `$$testability`) - the problem is that it's a breaking change (i.e. people will have to update their currently working tests).

**Comment by sjelin** [comment]
I say we deprecate it: add a `logger.warn` and some scary comments in the docs.
