### ISSUE TITLE
Find elements will auto scroll them into my headerbar.

### ISSUE THREAD

**Issue by chrismatheson** [angular/protractor#319]
Hi,

Im having a problem with my tests just now and im not sure how to go abotu fixing it. This may be awebdriver problem rather than a protractor one, im no sure.

My site has a fixed nav bar at the top, and on some elements when i use ```findElement()``` it will scroll them to the "top" of the page, which is underneath my header bar so when i try to ```click()``` them i get the following error

> UnknownError: unknown error: Element is not clickable at point (728, 7). Other element would receive the click: <div class="navbar-collapse collapse" collapse="!isCollapsed" style="height: 0px;">...</div>

i was wondering if there is a way to specify the "padding" space my site requires or do i need to manually scroll after every ```findElement()``` ??

Any help or pointers to other reading material would be fantastic.

P.S when i finally solve this i intend to raise a PR adding to FAQ's for the next poor fellow :)

**Comment by msafi** [comment]
As a current workaround, I get Protractor to execute this script when it loads the page to unfix the nav bar just for the tests:

```js
browser.executeScript("document.querySelector('.header').style.position = 'absolute'")
```

**Comment by juliemr** [comment]
Closing this - I'm cleaning up old issues, and the external bug here has been closed as working as intended.
