### ISSUE TITLE
protractor issues with sweetAlert 

### ISSUE THREAD

**Issue by vivekbrahmadandi** [angular/protractor#3190]
In the application, there is a alert box  of confirming an operation (they used sweetalert).
Through Protractor it can not click the element and it is throwing  the exception.

  Failed: Element is not currently visible and so may not be interacted with

And also its throwing another exception saying 
 Failed: Element is not clickable at point (1304.8499755859375, 45). Other element would receive the click: <div style="opacity: 1.46; display: block;" class="sweet-overlay" tabindex="-1"></div>

**Comment by vivekbrahmadandi** [comment]
Posted in so:
here is the link:
http://stackoverflow.com/questions/36984725/will-protractor-support-sweetalert-that-is-present-on-angular-js-apps

**Comment by NickTomlin** [comment]
Thanks for posting on SO! Since this is a usage/debugging question (and should be handled on SO) i'm going to go ahead and close this issue.
