### ISSUE TITLE
Configuration option getMultiCapabilities does not resolve when configured as a promise.

### ISSUE THREAD

**Issue by mdasberg** [angular/protractor#3191]
As of version 3.3.0 the option getMultiCapabilities when configured as a promise, does not resolve anymore and shuts down immediately, without running any tests.

When for instance using the following configuration:
```js
getMultiCapabilities: function () {
   return require('q').when([{
      'browserName': 'chrome',
      'shardTestFiles': true,
      'maxInstances': 10
   }]);
},
```

**Comment by Remco75** [comment]
same issue here, PR seems to fix the problem

**Comment by juliemr** [comment]
You're right - we didn't notice because our test for this (https://github.com/angular/protractor/blob/master/spec/getCapabilitiesConf.js) is happily doing nothing and exiting immediately.
