### ISSUE TITLE
protractor-cucumber HTML reporting feature request

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3199]
I have been using the "resultJsonOutputFile" which generates an Json file which has to be converted to xml format which could be then displayed as HTML report. can we have protractor to generate html reports or support at least cucumber-html-report plugin in cucumberOptions?? are there any PR's raised for this?
Note: I am aware that there is a work around by installing node-module called cucumber-html report which uses mustache to convert json files to html reports.

**Comment by juliemr** [comment]
You might want to raise this at https://github.com/mattfritz/protractor-cucumber-framework instead.

**Comment by igniteram** [comment]
@juliemr Thanks Julie, I raised it in the above said repo.

**Comment by NickTomlin** [comment]
@igniteram awesome, thanks for doing that 😄  I'm going to go ahead and close this issue since all the action will be on https://github.com/mattfritz/protractor-cucumber-framework/issues/31
