### ISSUE TITLE
Allow for custom configuration in the test

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#32]
Folks may want to introduce most custom configuration via the command line than just the baseUrl. Should allow for this.

**Comment by diogoviannaaraujo** [comment]
that would be awesome

**Comment by nvega-ms** [comment]
Can I remove a parameter byu command line?

**Comment by orgimeno** [comment]
Hi, i have two question.
```javascript
// conf.js
exports.config = {
	framework: 'jasmine',
	seleniumAddress: 'http://localhost:4444/wd/hub',
	specs: [],
	multiCapabilities: [{
		'browserName': 'chrome',
		'specs': ['protractor-spec.js'],
		'count': 5, //number of instances
		'shardTestFiles': true, //execute instances of browser simultaneously
	},
	],
	params: {
		answers: {
			max:10,
			min:1,
		}
	},
}
```
* I have this configuration and i want change **count** value in multiCapabilities via command line. its that possible?
* Can i run different instances of webDriver i the same browser but different tabs?

**Comment by felippenardi** [comment]
Just for the records, the way to do it is:

`protractor --params.login.user 'Joe' --params.login.password 'abc'`

As in https://github.com/angular/protractor/commit/02cb8199d89c6645d0bc9dbb39e5cb27517bfaf3

**Comment by djom20** [comment]
Can I use it for pass to config.js file the tags that I would like run?. For example: 

`protractor --params.tags '@issues, @results, ~@todo'`

In my config.js file:

```
exports.config = {
    framework: 'jasmine',
    specs: [],
    multiCapabilities: [{
        'browserName': 'chrome',
        'specs': ['features/*.feature'],
        'shardTestFiles': true, //execute instances of browser simultaneously
    }],
    cucumberOpts: {
        require: ['step_definitions/**/*_steps.js'],
        format: 'pretty',
        tags: config.tags,
        keepAlive: false
    },
    params: {
        tags: "@complete"
    },
}
```
