### ISSUE TITLE
How to use TeamCity Reporter? 

### ISSUE THREAD

**Issue by hanssgo** [angular/protractor#320]
jasmine.getEnv().addReporter(new jasmine.TeamcityReporter()); 

just gives an error. How do I use teamcity reporter? 

Thanks!

**Comment by cscleison** [comment]
I was getting case sensitive problems. Try ```new jasmineReporters.TeamCityReporter()```

**Comment by yaroslavya** [comment]
@cscleison It depends on the version, in Jasmine 1.x its `new jasmine.TeamcityReporter()`,
in Jasmine 2.x its `new jasmineReporters.TeamCityReporter()`.
See here for more details: https://github.com/larrymyers/jasmine-reporters

**Comment by aniltomar10** [comment]
this worked for me.
onPrepare() {
    var jasmineReporters = require('jasmine-reporters');
      jasmine.getEnv().addReporter(new jasmineReporters.TeamCityReporter());
  }
