### ISSUE TITLE
WebElementCondition did not resolve to a WebElement

### ISSUE THREAD

**Issue by coreystinson2** [angular/protractor#3201]
Running a fresh installation of NPM and receiving this error that is not occurring on my main development box, I have followed all installation steps and cannot reproduce on my main box.
suite is failing with the following error

`Failed: WebElementCondition did not resolve to a WebElement: [object Object]`
`at /Users/corey/.npm-packages/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:698:17`

I have identified the error being raised on all of the following commands throughout my suite, and without them the suite passes:
`browser.driver.wait(protractor.until.ableToSwitchToFrame(frame))`
`browser.driver.wait(protractor.until.elementTextIs(element, text))`

**Comment by aheys** [comment]
Just to add onto to this I was having the same problem with:
`browser.driver.wait(protractor.until.elementIsVisible(element(by.css('h1'))));`

This line would cause every following expect condition to fail.

**Comment by ajoslin103** [comment]
+1

**Comment by SomeshKumarN** [comment]
what is the solution for this issue? i am being facing this issue due to this, all my scripts are getting failed.. could you please tell me what is the solution for this....

**Comment by ajoslin103** [comment]
these are what works for me now 
(was very helpful --> http://www.protractortest.org/#/api)
```
function waitForElement ( _element ) {
	var EC = protractor.ExpectedConditions;
	return browser.wait(EC.presenceOf(_element));
};

function waitForNotElement ( _element ) {
	var EC = protractor.ExpectedConditions;
	return browser.wait(EC.not(EC.presenceOf(_element)));
};

function shouldHaveTextInElement ( _msg, _element, _text, _howLong ) {
	var EC = protractor.ExpectedConditions;
	it(_msg, function() {
		expect(browser.wait(EC.textToBePresentInElement(_element,_text)),_howLong).toBe(true);
	});
};
```

**Comment by coreystinson2** [comment]
I should've noted down my solution prior to closing the issue, my apologies.
I believe dropping a version of either selenium or protractor - can't remember which one. These are the specs i'm running with atm and this problem is not occuring.
selenium-webdriver@2.52.0
protractor@3.3.0

Hope that helps

**Comment by prasikumbhare** [comment]
i had the same issue.. problem seems to be with selenium-webdriver. Just 

<p>**replace**
`protractor.until`
<p>**with**
`webdriver.until`

Works for me ..Cheers :)

**Comment by tbosch** [comment]
`webdriver.until` is not a real replacement as it expects an already found `WebElement`, and not just a `WebElementFinder`. A better solution is this:

```
const selector = element(by.css('some-selector'));
browser.wait(protractor.ExpectedConditions.textToBePresentInElement(selector, 'someValue'), 1000)
```

@juliemr I also stumbled over this issue when upgrading angular to use protractor@4.x. `protractor.until.elementTextIs` seems to be broken for protractor. Could you have a look?
