### ISSUE TITLE
start protractor test parallel with different logins

### ISSUE THREAD

**Issue by beyaban** [angular/protractor#3207]
is it possible to start more than one browser with different logins?

For example: 
start 5 chrome instanses with count: 5 and shardTestFile:true in config file
each chrome instance should have different username and passwort for the login mask

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
