### ISSUE TITLE
by.model should not be restricted to 'input' elements

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#321]
At the moment, `by.model` matches `input` elements with `ng-model`, but nothing else using `ng-model`. It makes more sense semantically to match anything. The potential downside is that if you have an input and (e.g.) select with the same model, `by.model` becomes ambiguous. Is this an important distinction for anyone?

**Comment by manojkumarvizury** [comment]
element(by.model('mymodel')).getText()  for a textarea returns empty string whereas
element(by.model('mymodel')).getAttribute('value') returns the text inside a textarea.
why is that?
