### ISSUE TITLE
Cannot access variables outside scope in browser context

### ISSUE THREAD

**Issue by shlomogoldstein** [angular/protractor#3210]
Please see the problem on here. How can I access variables in my module after adding it with addMockModule()?

http://stackoverflow.com/questions/37164067/cannot-access-variables-outside-scope-in-browser-context

**Comment by mgiambalvo** [comment]
Hi there!

Thanks for directing your question to StackOverflow! If you need additional help, you can also post in the [Gitter Channel](https://gitter.im/angular/protractor). Please don't use GitHub Issues for support questions - we prefer to keep it to just bugs and feature requests.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'll try to take a look at your StackOverflow question, but you might find help sooner by asking your question on Gitter. Thanks!
