### ISSUE TITLE
Override the capabilities.shardTestFiles on the commandline

### ISSUE THREAD

**Issue by stevenmccord** [angular/protractor#3211]
Bug report
---

- Node Version: `v4.4.3`
- Protractor Version: `3.2.2`
- Browser(s): `Firefox`
- Operating System and Version `Linux`

I have been trying to look this up and haven't found the answer quite yet.  I am trying to override the capabilities.shardTestFiles on the command line, and here is what I am doing:

`protractor --capabilities.shardTestFiles=false conf.js`

However, it doesn't appear to override the object.  Any thoughts?  Thanks!

Steven

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

That said, you might want to verify that your config file doesn't have `multiCapabilities` set, since that will take precedence over the capabilities you set on the command line.

**Comment by stevenmccord** [comment]
@mgiambalvo that is what I have already done.  I was actually wondering if this is a bug.  Is there documentation for this CLI feature as well?

**Comment by stevenmccord** [comment]
@mgiambalvo I don't have a multiCapabilities object in my conf FYI as well.

**Comment by mgiambalvo** [comment]
Sorry, the documentation around this could be better, but that is the correct way to set capabilities on the command line. I've tried running that command, and can verify that it does override shardTestFiles if it's set in the config file. 

I'm doing this on Protractor 3.3.0, but I don't see any bugs that were fixed since 3.2.2 that would relate to your problem. Still, I'd suggest upgrading just in case. In any event, I'm not able to replicate the issue, so I don't think it's a bug.

**Comment by stevenmccord** [comment]
@mgiambalvo so something I noticed is that I can actually set other values in the capabilities object is there a special way that you have your conf.js file to override it?  Here is my capabilities object:

```
	capabilities: {
		name: 'functional-tests',
	    browserName: 'firefox',
	    shardTestFiles: false,
	    maxInstances: 10
	},
```

Sorry for the trouble, just can't seem to override the shardTestFiles, maybe something with passing a boolean on the cli?  I can override the maxInstances though.  

Thanks again!

**Comment by mgiambalvo** [comment]
Sorry, I'm not sure what your issue could be. I'm doing
```
protractor protractor.config.js --capabilities.shardTestFiles=false
```
and it does override the shardTestFiles I've defined in protractor.config.js, similar to yours. It might be an issue with your shell, or perhaps something else, but it's not a bug in protractor.

**Comment by stevenmccord** [comment]
Appreciate your time on this one, a little more information just to make sure it might be doing what it is for you as well.  When I run the following command:

`protractor --capbilities.shardTestFiles=false --capabilities.maxInstances=1 tests/functional/conf.js --cucumberOpts.tags=@smoke`

I essentially get 1 instance, but it iterates through all of the files in the features (without opening a browser) but tells me there is no steps, ideally it would just run it like shardTestFiles was false.  Just wanted to verify we were seeing the same thing or if you were seeing something differently.  I did upgrade to the latest version as well.

**Comment by mgiambalvo** [comment]
Is that a direct copy and paste? There's a typo in that invocation - "capbilities" instead of "capabilities" in the first option.

It's really easy to get typos in these long options - we should probably add a feature to throw an error if you set an unknown flag.

**Comment by stevenmccord** [comment]
Sorry about that, it was a typo on my part, I copied/pasted the command there now.  It will actually start a browser and shut it down for each file, but it is overriding the maxInstances but not the shardTestFiles.  More parts of my conf.js file FYI:

```
exports.config = {
	baseUrl: "https://base_url",
	framework: 'custom',
	frameworkPath: '/usr/lib/node_modules/protractor-cucumber-framework',
	seleniumAddress: "http://" + process.env.SELENIUM_MASTER_SERVICE_HOST + ":" + process.env.SELENIUM_MASTER_SERVICE_PORT + "/wd/hub",
	onPrepare: function () {
		var fs = require('fs');
		var dir = './.artifacts';
		if(!fs.existsSync(dir)){
			fs.mkdirSync(dir);
		};
		common = require('./features/support/helpers/common.js');
		auth = require('./features/support/helpers/auth.js');
		schema = require('./features/support/helpers/schemaForm.js');
		expectedCondition = require('./features/support/helpers/expectedConditions.js');
		browser.driver.manage().timeouts().implicitlyWait(5000);
	},
	capabilities: {
		name: 'functional-tests',
	    browserName: 'firefox',
	    shardTestFiles: true,
	    maxInstances: 10
	},
	specs: [
		'features/product/**/*.feature'],
	suites: {
		registration: [
			'features/product/registration/register.feature',
			'features/product/registration/denypermissions.feature'
		],
		profile: [
			'features/product/profile/profile.feature',
			'features/product/profile/signout.feature',
		],
		distribution: [
			'features/product/distribution/distribution_cloud.feature',
			'features/product/distribution/distribution_cloud_no_files.feature',
			'features/product/distribution/distribution_content_upload.feature',
			'features/product/distribution/distribution_goal.feature',
			'features/product/distribution/distribution_metadata.feature'
		]
	},
    resultJsonOutputFile: './.artifacts/functional_tests.cucumber',
	cucumberOpts: {
		require: [
			'features/step_definitions/**/*.js',
			'features/support/'
		],
		format: [
			'pretty',
			'json:/home/ubuntu/stymie-ui/.artifacts/functional_tests.json'
		],
		showColors: true,
		tags: '@test'
	}
};
```

**Comment by stevenmccord** [comment]
OK, so this was weird, but I started diving deeper in the shell issue and when it looks like in order to do this for me at least I had to do the following to set it to false, assuming I have true set in the conf.js:

`protractor --capabilities.shardTestFiles=0 tests/functional/conf.js --cucumberOpts.tags=@smoke`

If I have false set in the conf.js then I can do the following to set it to true:

`protractor --capabilities.shardTestFiles=1 tests/functional/conf.js --cucumberOpts.tags=@smoke`

@mgiambalvo thanks for the help here, really appreciate it!

**Comment by cnishina** [comment]
Chiming in real quick on this issue. Selenium webdriver was skipping over capabilities set to false. The following is the fix for it: https://github.com/SeleniumHQ/selenium/commit/64359862e88fb3715c2064cfebf18919c6743c71. They did just release 2.53.2 to npmjs so I'll see if I can update protractor to use that version of webdriver that has this fix in it.
