### ISSUE TITLE
Throw an error in the launcher if the user sets an unknown flag

### ISSUE THREAD

**Issue by mgiambalvo** [angular/protractor#3216]
Some of our flags are very easy to mistype. Rather than silently ignoring unknown flags, we should at least show a warning and probably exit with an error if a user invokes Protractor with an unknown flag.

**Comment by juliemr** [comment]
Hm, but users might be processing args themselves

**Comment by cnishina** [comment]
Instead of throwing an error, should we warn the user that we encountered something unexpected?
