### ISSUE TITLE
Firefox no longer launches using directConnect in Protractor 3.3.0

### ISSUE THREAD

**Issue by aullman** [angular/protractor#3218]
Bug report
---

- Node Version: `4.2.2`
- Protractor Version: `3.3.0`
- Browser(s): `Firefox 46`
- Operating System and Version `Linux and OSX`
- Your protractor configuration file: https://github.com/aullman/opentok-meet/blob/master/tests/protractor.conf.js
- Output from running the test

When I run the tests locally or on Travis using Protractor 3.3.0 I get no output whatsoever. When I install 3.2.2 then the tests run and I get output as expected. Here is an excerpt from my terminal. Notice that the first run of protractor does nothing.
```
$ node_modules/.bin/protractor --version
Version 3.3.0
$ node_modules/.bin/protractor tests/protractor.conf.js 
$ npm install protractor@3.2.2
...
$ node_modules/.bin/protractor tests/protractor.conf.js 
Using FirefoxDriver directly...
[launcher] Running 1 instances of WebDriver
Started
.


Ran 1 of 43 specs
1 spec, 0 failures
Finished in 7.066 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] firefox #01 passed
```

You can also see the Travis job where it did not run the protractor tests using Protractor 3.3.0 and ran the tests using Protractor 3.2.2.
Protractor 3.2.2 - https://travis-ci.org/aullman/opentok-meet/jobs/129877501#L707
Protractor 3.3.0 - https://travis-ci.org/aullman/opentok-meet/jobs/125733427#L699

- Steps to reproduce the bug

1. Install protractor 3.3.0 and try to launch Firefox using direct connect.

Result: Nothing happens
Expected Result: Firefox launches and your tests run.

**Comment by mgiambalvo** [comment]
We broke resolving the promise for getMultiCapabilities in the switchover to TypeScript. #3195 fixes the issue and will be included in the next version.
