### ISSUE TITLE
Selenium WebDriver Not able to select DoJo dropdown

### ISSUE THREAD

**Issue by mandardjoshi** [angular/protractor#3219]
Hi there!

I am trying to select a dropdown which is designed in the DOJO Html and when i am performing the "Select" function on this then it is not able to Click on the dropdown nor it is able to select the value from it.Is it the bug in the WebDriver that it is not able to select the value.

Please find the Html code for dropdown below -

[Dropdown_Issue.docx](https://github.com/angular/protractor/files/263366/Dropdown_Issue.docx)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by mandardjoshi** [comment]
The temporary solution here is to first click on the dropdown and to next provide the xpath for the element which is present on that dropdown and then perform the Click option.
But if you refer the code above then there is same class name for both the droopdowns so if we are planning to use this property then xpath will be same for both of them and selenium is getting confused and getting an error as "Element Not Found".

Please provide any other solution if someone knows about it . Thanks in advance.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by mandardjoshi** [comment]
Ok Nick..Thanks !!!
