### ISSUE TITLE
Break statement is not working in protractor

### ISSUE THREAD

**Issue by mcarkv** [angular/protractor#3220]
Hi All,
I am not able to use the Break statement to break the for/while loop.
It display the illegal statement.

Please suggest it is bug, please find below code:-
checkGridString: function () {				
		var cells = element.all(by.css('.ui-grid-canvas .ui-grid-cell-contents'));
		cells.then(function(items){
			var len = items.length;
			console.log('length of upper level element=' + len);			
			for (var i = 0; i < len; i++){
				(function(i){
					items[i].getText().then(function(text){						
						 if (text == "xxx"){
						 console.log('Found the Item.');
						 Break;
						 } 						

					});

				})(i);
			}
		});
	}

**Comment by NickTomlin** [comment]
Hi there!

This shouldn't have anything to do with protractor. It's `break` with a lowercase `b` and not `Break`.
If you have additional issues, please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by mcarkv** [comment]
Hi Nick,
Sorry for late reply, Its Typo mistake, i have used the break; keyword. The Protractor display an error say 'Illegal break statement'.
