### ISSUE TITLE
Require documentation for protractor with Jasmine/cucumber

### ISSUE THREAD

**Issue by SomeshKumarN** [angular/protractor#3227]
Hi there!

I wanted to create a testing framework with jasmine and cucumber, can you please let m know if you have any documentation link, that would really be a greate.

Thanks 
somesh

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
