### ISSUE TITLE
Unable to locate element on Non angular page with Browser.driver

### ISSUE THREAD

**Issue by DaisyCompsci** [angular/protractor#3231]
This way works on a different non-angular page for me before without any wait or sleep.

Basically I have some code looks like this:

                var driver=browser.driver;
                // maximize window 
                driver.manage().window().maximize();
		// log in
		browser.get('https://www.qa.dealertrack.com/default1.aspx');
		driver.findElement(by.name('username')).sendKeys(id);
		driver.findElement(by.name('password')).sendKeys(password);
		driver.findElement(by.name('login')).click();

		browser.driver.wait(function() {
							return browser.driver.getCurrentUrl().then(function(url) {
												expect(url).toEqual(
														'https://www.qa.dealertrack.com/default1.aspx');
												console.log('Successfully loged into '
																+ url);
												return url;
											});
						}, timeOut,
						'Expectation error: Timed out waiting for current url');
                 driver.findElement(by.id('AppSub')).click();

Element in the last line could not be found. I double checked and I am sure the locator is not wrong.
I have used some way to test other non angular page, everything went smoothly. I don't understand why it does not work on this site.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
