### ISSUE TITLE
ElementFinder documentation mistype

### ISSUE THREAD

**Issue by bcoble** [angular/protractor#3233]
Hello!

I was going over some documentation for the [ElementFinder](http://www.protractortest.org/#/api?view=ElementFinder) and I think you have an incomplete description for the **getText** function.

<img width="411" alt="screen shot 2016-05-20 at 10 40 51 am" src="https://cloud.githubusercontent.com/assets/4602385/15433415/e5ac5c0c-1e77-11e6-8398-ce687bf580c2.png">

Thanks.
-Ben

**Comment by juliemr** [comment]
Huh - it works when you click through to the full function. Something in our website parser might be acting funny.

**Comment by cnishina** [comment]
Looking into this: We are using a shortDescription by looking for when a sentence ends. The easy fix is to change the `getText` JSDoc.

https://github.com/angular/protractor/blob/9177dca445e8a16363a7df5328886688b7027180/website/js/api-controller.js#L142
