### ISSUE TITLE
How to click all elements with a particular locator through protractor one by one?

### ISSUE THREAD

**Issue by allaboutapis** [angular/protractor#3235]
This is what I am trying to do - I am trying to click on an element with a locator and on clicking that element, 2 more links are displayed. I want to individually click on those 2 links and then do an assertion. 

However, the code clicks first element and then stops. This is my code - 

self.expandHierarchy = function() {
        var hrchy = element.all(by.css('.ng-binding.CanExpand'));
        hrchy.each(function (elem) {
            elem.click();
        });
    };

How can I do the same through protractor?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
