### ISSUE TITLE
When protractor config.js browser was opened but not "alert"

### ISSUE THREAD

**Issue by mqliutie** [angular/protractor#3236]
Exactly, when I executed `protractor config.js` via bash chrome was **'alert'**.

When I executed `protractor config.js` in WebStrom the chrom was opened but not **'alert'**.

It was leaded by protractor or WebStorm?

Thanks

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
