### ISSUE TITLE
Protractor E2E tests time out with NG1-NG2 hybrid bootstrapped application

### ISSUE THREAD

**Issue by bringking** [angular/protractor#3238]
**Steps to reproduce and a minimal demo of the problem**
Setup a basic NG1 -> NG2 hybrid application and run E2E tests with protractor

#### Main entry point
```typescript
  upgradeAdapter.addProvider([...PROVIDERS, ...ENV_PROVIDERS, ...DIRECTIVES, ...PIPES]);

  return upgradeAdapter.bootstrap(document.documentElement,
    ['app'], {strictDi: true});
```
#### Protractor config
```js
const defaultConfig = {
  multiCapabilities: [
    {
      browserName: 'chrome', true, maxInstances: 6,
      chromeOptions: { args: ['--lang=en', '--window-size=360,600'] }
    }
  ],
  getPageTimeout: 10000, // How long to wait for a page to load in ms.
  allScriptsTimeout: 22000,
  baseUrl: 'http://localhost:3001',
  specs: `${__dirname}/../test/e2e/*.spec.js`,
  jasmineNodeOpts: {
    // If true, print colors to the terminal.
    showColors: true,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 30000
  }
};

module.exports = { config: defaultConfig };

```
#### Sample test
```js
const LoginPage = require('./page-objects/login.page');
const NavPage = require('./page-objects/nav.page');
const LogHelpers = require('./helpers/log.helper');

describe('login', () => {
  const loginPage = new LoginPage();
  const navPage = new NavPage();
  const logHelpers = new LogHelpers();

  beforeEach(() => {
    browser.get('login');
  });

  afterEach(() => {
    logHelpers.expectNoErrors();
  });

  describe('when valid credentials are given', () => {
    it('takes user to home', () => {
      expect(loginPage.submit.isEnabled()).toBe(false);
      loginPage.loginUser().then(() => {
        return navPage.logout.click();
      }).then(() => {
        return expect(browser.getCurrentUrl()).toMatch(/home/);
      });
    });
  });
});

```

**Current behavior**

Protractor throws the following error, no matter the timeout- 

```bash
[chrome #1-10]   Message:
[chrome #1-10]     Failed: Timed out waiting for Protractor to synchronize with the page after 22 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
```

[UPDATE] - 
I have tracked down the behavior to timeout when trying to use the `getCurrentUrl` method. 

```js

this.loginUser = () => {
    return this.username.sendKeys('test').then(() => { // this succeeds
      return this.password.sendKeys('test'); // this succeeds
    }).then(() => {
      return this.submit.click(); // this succeeds
    }).then(() => {
      expect(browser.getCurrentUrl()).not.toMatch(/login/); // this times out
    });
  };

```
**Expected/desired behavior**

A successful test

**Other information**

Angular 1.x Version = 1.5.3
Angular 2.x Version = 2.0.0-rc.1
Protractor Version = 3.3.0

Possibly related to this PR - https://github.com/angular/angular/pull/7603

**Comment by bringking** [comment]
This could be related to https://github.com/angular/protractor/issues/2944, however I am using the RC version of NG2

**Comment by xxshadowfang** [comment]
I'm having a similar Issue that arrived when switching to a 1+2 app. Prior to the switch the tests ran synchronously. Now they will only run async but not well. There isn't a problem with constant polling of http or timeouts. Maybe some of my digging will help get the issue a solution or resolved.

Things I know:
-Elements are present and displayed
-There arent any polls to make protractor think the page is unstable
-All hangs occur on promises. ( ex exisitingPageElement.getText().then(...)   The .then never occurs because the getText

**Comment by juliemr** [comment]
See https://github.com/angular/angular/issues/9407

**Comment by dparish** [comment]
I can't find a definitive guide on how to get a hybrid app working with RC5 and the latest protractor.

It looks like you are not supposed to use useAllAngular2AppRoots: true but perhaps you should set rootElement? If so, what should it be set to?

I can't seem to get any of my protractor tests to work in my hybrid app.

**Comment by sjelin** [comment]
You should definitely set a root element - to the root of your ng1 app.

Also, this issue was resolved
