### ISSUE TITLE
protractor v3.3 doesnt run with firefox with profile

### ISSUE THREAD

**Issue by holdfenytolvaj** [angular/protractor#3239]
It seems version v3.3 doesn't run tests with Firefox (no output at all, just returns), Chrome is fine on Linux (Ubuntu), on the other hand v3.2.2 runs perfectly. Tried on two machines with the same result. 
When running v3.3 tried to add all debug flags but still no output at all, just returns immediately. Also tried with different selenium versions 53/52 still the same result.
Anyone else have experienced this?

**Comment by holdfenytolvaj** [comment]
Ok this is something to do with the new version + the firefox-profile module I've used, I will check then, sorry.

**Comment by holdfenytolvaj** [comment]
Finally found it connected with the getMultiCapabilities. There was a bug in the refactoring of the built/launcher.js


```
 helper.runFilenameOrFn_(config.configDir, config.beforeLaunch)
        [...]
                // If getMultiCapabilities is defined and a function, use this.
                q.when(config.getMultiCapabilities(), function (multiCapabilities) {
                    config.multiCapabilities = multiCapabilities;
                    config.capabilities = null;
                }).then(**function (resolve) { }**);
```
            

has to be changed back to 

```
    helper.runFilenameOrFn_(config.configDir, config.beforeLaunch)
        [...]
                // If getMultiCapabilities is defined and a function, use this.
                q.when(config.getMultiCapabilities(), function (multiCapabilities) {
                    config.multiCapabilities = multiCapabilities;
                    config.capabilities = null;
                }).then(**resolve**);
            
```

This can be used for test:
https://github.com/juliemr/protractor-demo/tree/master/howtos/setFirefoxProfile

**Comment by juliemr** [comment]
This has been fixed with https://github.com/angular/protractor/commit/f2055181e60fd358c1764fe716af3d64fc64810b and will be out in the next release. Hold tight!

**Comment by holdfenytolvaj** [comment]
Sounds cool! Then next time I will be even lazier :D
Keep up with the good work! Thanks!

**Comment by evilaliv3** [comment]
is there an ETA for this?

**Comment by lalau** [comment]
Can we do a a bug fix release for this?

**Comment by westy92** [comment]
Version 4.0.0 was released 2 hours ago.
https://www.npmjs.com/package/protractor

**Comment by lalau** [comment]
I think what I really mean is that why we waited for almost 2 months to release a bug fix for things that were working before. Plus now we are releasing the bug fix together with other breaking changes, leaving 3.3.x in a broken state unless locking down to 3.2.x, or being forced to upgrade to 4.

**Comment by juliemr** [comment]
I'm closing this issue as it's fixed in v4.

The breaking changes for v4 should affect very few users, unless you're actively reaching in to protractor internals. For most users, it'll just be running `webdriver-manager update` again. Because there are so many moving dependencies for Protractor (browsers and webdriver, primarily) it's not practical for us to maintain older branches.
