### ISSUE TITLE
Validation of protractor tool

### ISSUE THREAD

**Issue by jitendrasbhati** [angular/protractor#3241]
Hi,

My requirement is to validate protractor framework itself i.e. Protractor's intended use i.e. end to end or integration testing.
How do I automate the validation of protractor framework?

**Comment by juliemr** [comment]
I don't understand exactly what you need to do. Protractor runs its own suite of tests - you can see those at https://travis-ci.org/angular/protractor. Start there, and take a look at another script that we run before releases, https://github.com/angular/protractor/blob/master/scripts/test.js.

Let me know if that doesn't get you started.

**Comment by juliemr** [comment]
And per our policy that the issue tracker is for bugs and feature requests, I'll be closing this.
