### ISSUE TITLE
API view code links broken

### ISSUE THREAD

**Issue by faredis** [angular/protractor#3242]
The view code links on the protractor website are broken since moving to typescript.

**Comment by NickTomlin** [comment]
This is a duplicate of https://github.com/angular/protractor/issues/3170 (which _should_ be fixed on master).

@cnishina would it be possible to publish the website to incorporate the new fixes?

**Comment by cnishina** [comment]
@NickTomlin Getting pretty close to the next release. I think we'll update the website then.

**Comment by juliemr** [comment]
fixed now! Huzzah!
