### ISSUE TITLE
Build number not send to saucelabs after upgrading to 3.3.0

### ISSUE THREAD

**Issue by rreitmann** [angular/protractor#3257]
Since we have upgraded from protractor 3.2.2 to 3.3.0 saucelabs does not receive the build number anymore which causes that the current test status cannot be displayed in their badges anymore. Here is how we configure the build number:
```javascript
multiCapabilities: [{
    'name': 'Win8.1/Chrome',
    'platform': 'Windows 8.1',
    'browserName': 'chrome',
    'build': process.env.TRAVIS_BUILD_NUMBER
  }, {
    'name': 'Win8.1/Firefox',
    'platform': 'Windows 8.1',
    'browserName': 'firefox',
    'build': process.env.TRAVIS_BUILD_NUMBER
  }, {
    'name': 'Win8.1/IE11',
    'platform': 'Windows 8.1',
    'browserName': 'internet explorer',
    'version': '11.0',
    'build': process.env.TRAVIS_BUILD_NUMBER
  }],
```
Here is the result: https://saucelabs.com/u/rreitmann

Have there been any changes on how we have to configure this attribute?

**Comment by cnishina** [comment]
Per 582411b7ad6c0f9176b231dc51dc328b98affbdf, the reference doc shows that you should use the sauceBuild. However if sauceBuild is not there, it might be overriding your build number set in the multiCapabilities. Try it out and let me know. We might need to fix this: https://github.com/angular/protractor/commit/582411b7ad6c0f9176b231dc51dc328b98affbdf#diff-b7b628ea512e37f59b8b06df304f2f6bR64

**Comment by rreitmann** [comment]
Using sauceBuild solved our issue. Thanks for your help!

**Comment by NickTomlin** [comment]
Glad that resolved the issue! I'll go ahead and close this.
