### ISSUE TITLE
Documentation: sendKeys() imprecision

### ISSUE THREAD

**Issue by tkrotoff** [angular/protractor#3258]
[Tutorial](https://github.com/angular/protractor/blob/3.3.0/docs/tutorial.md) explains:

```JavaScript
[...].sendKeys(1);
[...].sendKeys(2);
```

While [API documentation](http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.sendKeys):

```
Param       Type
var_args	...(string|!webdriver.promise.Promise<string>)
```

So is **number** officially supported in addition to **string**?

Sorry to be picky, it's for the [TypeScript definition file for Protractor](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/473232e5dbd179e9ee682fab12f796720f37b118/angular-protractor/angular-protractor.d.ts#L1221).

**Comment by cnishina** [comment]
This is not an issue. The parameters in our documentation reflects the javadocs for the selenium-webdriver.

[webdriver.js](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js):
```
   * @param {...(string|!promise.Promise<string>)} var_args The
   *     sequence of keys to type. All arguments will be joined into a single
   *     sequence.
   * @return {!promise.Promise<void>} A promise that will be resolved
   *     when all keys have been typed.
   */
  sendKeys(var_args) {
```

In the end, the typescript is transpiled to javascript and the javascript does not type check that it is a number or a string. This will eventually become more important when we have our own type declarations file that defines `sendKeys` and users are writing their tests in typescript.

For the DefinitelyTyped file, if users are writing their test in typescript, someone should probably update it so it is `string|number`.

**Comment by tkrotoff** [comment]
@cnishina Selenium `sendKeys()` now officially accepts number: https://github.com/SeleniumHQ/selenium/commit/1dddaef3c8fe8d2974747e4a94b370982939139a

**Comment by tkrotoff** [comment]
ping @cnishina, this is still not fixed: http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.sendKeys
