### ISSUE TITLE
Customizing XML reports in protractor

### ISSUE THREAD

**Issue by vikas2future** [angular/protractor#3270]
I have been using jasmine-reporters to generate XML reports as part of our protractor project.

However i would like to customize the XML that gets generated by adding few more parameters as part of every test case. These new parameters would be elements/attribute within the testcase element.

This customization of XML reports is required because i need to update the results back to MTM(Microsoft Test Manager)

Any help would be greatly appreciated. I am ok to use any other node modules other than jasmine reporters if it fits my bill.

I am using the below framework.
Jasmine 2.X
NodeJs 6.2.0
Protractor 3.2.2

**Comment by sjelin** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
