### ISSUE TITLE
Enable "Activity" integration in protractor gitter group !

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3286]
Are the Activities integrated in this group? or I am not seeing them? because I could see in other groups the Activities feature of gitter enabled.

<img width="1440" alt="screen shot 2016-06-20 at 9 00 14 pm" src="https://cloud.githubusercontent.com/assets/15998104/16200353/9cb3539a-372a-11e6-9bfd-4fc66e211ab4.png">

**Comment by cnishina** [comment]
Added the Activity integration for Gitter.

**Comment by igniteram** [comment]
@cnishina  Awesome! 😃  thanks 👍
