### ISSUE TITLE
using browser.actions() to simulate drag & drop does not work

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3289]
Bug report
I use browser.actions() to simulate drag and drop in such a way:

    `let dragElement = element.all(by.className('layer')).get(0).getWebElement();`
    `let dropElement = element.all(by.className('layer')).get(1).getWebElement();`
    `browser.actions()`
    `.mouseDown(dragElement)`
    `.mouseMove(dropElement)`
    `.mouseUp()`
    `.perform`

The action of drag and drop is not happening. I know the elements are found, because when executing:

`browser.actions().mouseDown(dragElement).perform()`

I can see that the mouse button is pressed on the control.

- Node Version: `5.10.1`
- Protractor Version: `3.3.0`
- Browser(s): `chrome`
- Operating System and Version `windows 7 x64`
- Your protractor configuration file
- A relevant example test: as upper
- Output from running the test: it just fails on expect
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant): not relevant

**Comment by cnishina** [comment]
This is a known external issue. Please see #583 and https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/3604.
