### ISSUE TITLE
Update ng2 test app to Angular RC version

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3295]

**Comment by cnishina** [comment]
Plan:
1. Using `testapp/package.json` to install node_modules (https://github.com/angular/protractor/pull/3302)
2. Upgrade to angular 2 rc 3

**Comment by cnishina** [comment]
Note: Looks like commit 248ed9974bc32a46077fe84a66bc674caa842899 downgraded to beta.0 which is currently failing the hybrid test.

**Comment by juliemr** [comment]
This is done!
