### ISSUE TITLE
run protructor

### ISSUE THREAD

**Issue by ig0r081** [angular/protractor#3306]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Git\\angular-phonecat\\node.exe',
1 verbose cli   'E:\\Git\\angular-phonecat\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose stack Error: missing script: package
4 verbose stack     at run (E:\Git\angular-phonecat\node_modules\npm\lib\run-script.js:142:19)
4 verbose stack     at E:\Git\angular-phonecat\node_modules\npm\lib\run-script.js:58:5
4 verbose stack     at E:\Git\angular-phonecat\node_modules\npm\node_modules\read-package-json\read-json.js:356:5
4 verbose stack     at checkBinReferences_ (E:\Git\angular-phonecat\node_modules\npm\node_modules\read-package-json\read-json.js:320:45)
4 verbose stack     at final (E:\Git\angular-phonecat\node_modules\npm\node_modules\read-package-json\read-json.js:354:3)
4 verbose stack     at then (E:\Git\angular-phonecat\node_modules\npm\node_modules\read-package-json\read-json.js:124:5)
4 verbose stack     at E:\Git\angular-phonecat\node_modules\npm\node_modules\read-package-json\read-json.js:243:12
4 verbose stack     at E:\Git\angular-phonecat\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
5 verbose cwd E:\Git\angular-phonecat
6 error Windows_NT 5.1.2600
7 error argv "E:\\Git\\angular-phonecat\\node.exe" "E:\\Git\\angular-phonecat\\node_modules\\npm\\bin\\npm-cli.js" "run" "package"
8 error node v4.4.5
9 error npm  v2.15.5
10 error missing script: package
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

**Comment by cnishina** [comment]
This does not look like there is a call to protractor. If you feel that this is an issue, feel free to open a new issue with additional information (please read the issue template for the items needed).

Thanks.
