### ISSUE TITLE
seleniumArgs is not available in v3.3.0

### ISSUE THREAD

**Issue by NadinFarbman** [angular/protractor#3308]
Hi there!

I use protractor v3.3.0, 
The list of protrator's options of command line does not contain --seleniumArgs.
Is it OK?
It could affect running test against IE?

Thanks in advance.

**Comment by cnishina** [comment]
`seleniumArgs` has been deprecated. Please see [referenceConf.js](https://github.com/angular/protractor/blob/master/docs/referenceConf.js#L37). For more information, please see commit https://github.com/angular/protractor/commit/261b49e1129e0288215d865d5953872c4839877a
