### ISSUE TITLE
addMockModule does not execute script in browser

### ISSUE THREAD

**Issue by bgever** [angular/protractor#3311]
Bug report
---

- Angular Version: `1.4.1`
- Node Version: `4.4.5`
- Protractor Version: `3.3.0`
- Browser(s): `Chrome 51.0.2704.106 m (64-bit)`
- Operating System and Version `Windows 10 1511`

After upgrading from Protractor 1.8, the `protractor.addMockModule` is no longer working. After debugging it more with both Chrome and PhantomJS 2.1, I found that the function that is passed along isn't executed in the browser.

Even the following simple test is not rendering any results.
```js
// Set the mock module (should execute the script in the browser).
browser.addMockModule('app', 'console.log("HELLO_WORLD");');
// Call the Angular page, which uses the mock module after all other modules are loaded.
browser.get(browser.params.appUrl);
// Show the output in console.
browser.manage().logs().get('browser').then(
   function(logs){ console.log('LOG: ' + util.inspect(logs)); }
);
```

The actual thing we want to mock (and worked in 1.8):
```js
window.angular.module('app').decorator('service', function($delegate, $q) {
  $delegate.doAsync = function(){ return $q.reject(); };
  $delegate.update('foo');
  return $delegate;
});
```
After the page is loaded, nothing is logged in the browser console.

At first I thought it had to do with ChromeDriver, as Protractor 3.3.0 ships with 2.21, and the [changelog for 2.22 includes](https://chromedriver.storage.googleapis.com/2.22/notes.txt):
```
Resolved issue 1339: Failure when executing JS in a content script context [['OS-All', 'Pri-1']]
```
I've manually set the version in `config.json` to 2.22 and ran `webdriver-manager update`. In the output logs Protractor shows it's using the 2.22 version, but the same issue happens.
Because PhantomJS is affected with the same issue, I suspect it lies with Protractor or down the pipeline.

Or could it not work because of our old Angular version?

Please let me know how I can provide any more logs or information, as I couldn't find a way to access webdriver logs to see whether the actual script registration happens.

**Comment by jlin412** [comment]
There is another bug of adding mock and it seems to still work on 3.1.1.
Would you like to downgrade and try to see if it works for you at 3.1.1 as
a workaround?

**Comment by bgever** [comment]
I think I've tried that version, as I was trying almost all the latest fix versions of each minor version going down. Will give 3.1.1 another shot tomorrow, thanks!

**Comment by bgever** [comment]
I've tried with 3.1.1, and also with Chrome versions 51, 49 and 48, but all are not able to confirm the log entries. However, if I execute the following: 
```ts
var util = require('util');

browser.executeScript('console.log(angular.version); return angular.version;').then(
  result => console.log('RESULT: ' + util.inspect(result)),
  error => console.log('RESULT ERROR: ' + util.inspect(error))
);

browser.manage().logs().get('browser').then(
  (logs) => console.log('LOG: ' + util.inspect(logs))
);
```

Then I do get the angular version, but `browser.manage().logs().get('browser')` returns an empty array. I am aware of the [bug that repeated calls would return an empty response](https://github.com/SeleniumHQ/selenium/issues/1914), but this is the first and only call.

Is there a way to see logs about what is sent via the webdriver?

**Comment by bgever** [comment]
Just tried with PhantomJS (2.1) on 3.1.1, and for the very first time I've been able to get the console log from PhantomJS.

So the below `console.log` does execute and show with `executeScript`, but not with `addMockModule`.

```ts
browser.addMockModule('tiApp', 'console.log("HELLO_WORLD");');
browser.get(browser.params.appUrl);
var util = require('util');
browser.executeScript('console.log(JSON.stringify(angular.version)); return angular.version;').then(
  result => console.log('RESULT: ' + util.inspect(result))
);
browser.manage().logs().get('browser').then(
  (logs) => console.log('LOG: ' + util.inspect(logs))
);
```
Output:
```
RESULT: { dot: 1,
  codeName: 'hyperionic-illumination',
  major: 1,
  minor: 4,
  full: '1.4.1' }
LOG: [ Entry {
    level: Level { name_: 'INFO', value_: 800 },
    message: '{"full":"1.4.1","major":1,"minor":4,"dot":1,"codeName":"hyperionic-illumination"} (:)',
    timestamp: 1467181612500,
    type: '' } ]
```

**Comment by bgever** [comment]
I've tried to reproduce the error on my Mac as well, and in doing so, I found that with a basic test setup, addMockModule works as expected on both my Mac and Win10 machines with v3.3.0 and Chrome:

https://github.com/bgever/Protractor-addMockModule-tests

Will need to dig deeper why in our application tests it's not working. Might have to do with that we're using Mocha, Grunt, and something to spin up the WebDriver-Manager automatically.

**Comment by juliemr** [comment]
Great, sounds like this is largely resolved for now. Please open a new issue if you can create a reproducible test case which you think is a general bug and not just your setup. Thanks!

**Comment by bgever** [comment]
I've finally found the issue to be in our application code. It's the confusing way how Protractor handles promises and therefore the execution order. My mistake was to believe that `addMockModule` and `clearMockModules` schedule on the WebDriver execution stack, whereas in fact they are executed straight away, and only then the promises get resolved. Meaning, that if you place a `clearMockModules` in the same test body, after any promises that get scheduled, it will have already cleared it before the page had loaded.

This is the full test (Mocha/Chai):
```ts
browser.addMockModule('app', mockAuth);
// Reload the page with the mock module, so that it should automatically log out once loaded.
browser.get(browser.params.appUrl);
// Clear the mock module so it doesn't enable on following tests.
browser.clearMockModules();
expect(loginPage.pageHeading.getText()).to.eventually.equal('Log in');
```
Whereas it should have been:
```ts
browser.addMockModule('app', mockAuth);
// Reload the page with the mock module, so that it should automatically log out once loaded.
browser.get(browser.params.appUrl).then(
    () => {
      // Clear the mock module so it doesn't enable on following tests.
      browser.clearMockModules();
    });
expect(loginPage.pageHeading.getText()).to.eventually.equal('Log in');
```

@juliemr I don't think it will be necessary to schedule a new bug, but I think it would help a lot if the [documentation for `clearMockModule`](http://www.protractortest.org/#/api?view=Protractor.prototype.clearMockModules) would explain this potential issue. This took a long time to discover and the behavior is not obvious.

So what happened is that when the `browser.get` call is initiated, it will take a while for the page to load. Meanwhile, the `browser.clearMockModules` is executed, and clears the mock modules queue. Then when angular is loaded and waiting for the bootstrap call, it doesn't find any mock modules because they have been cleared, and continues without any mocks.

The other option would be to schedule the `addMockModules` and `clearMockModules` to synchronize with the WebDriver execution stack.

**Comment by thirtysixthspan** [comment]
Thanks @bgever for the report and followup. I ran into this exact problem and your clear explanation helped me understand the situation and work a solution.
