### ISSUE TITLE
browser.manage().logs().get('browser') is not retrieving any browserlogs

### ISSUE THREAD

**Issue by premkh9** [angular/protractor#3317]
Hi Team,

I am using browser.manage().logs().get('browser') in after each function. But when test case fails , I am not seeing any logs under console 

	afterEach(function() {
		browser.manage().logs().get('browser').then(function(browserLog) {
			console.log('log: ' + require('util').inspect(browserLog));
		});
	});

I am using chrome browser and below capabilities

        'browserName': 'chrome',
        loggingPrefs: { "driver": "INFO", "browser": "INFO" },

installed protractor-console-plugin@0.1.1 node_modules\protractor-console-plugin as well

Other details - 
Protractor version - 3.1.1
selenium-server-standalone-2.51.0
chromedriver_2.21

Please guide me

**Comment by Emilemuny** [comment]
browser.manage().logs().get('browser').then .... works for me :) You may need to make sure you do actually have logs manually in the chrome dev console before using the command above.
Also i recommend using Protractor elementExplorer to further troubleshoot the issue.

**Comment by premkh9** [comment]
Sorry, I didnt get that

**Comment by juliemr** [comment]
This looks like it's not a bug, but an issue with your specific setup. 

Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
