### ISSUE TITLE
browser.driver.wait(EC.presenceOf($('css_path')) still call waitForAngular

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#3327]
Node 4, Protractor 3.1.1

When I call browser.driver.wait(EC.presenceOf($('css_path'));  WaitForAngular function will still run runWaitForAngularScript script.  Is this a bug?  I am assuming that it should get out from ignoreSynchronization=true flow: 

```
Protractor.prototype.waitForAngular = function(opt_description) {
  var description = opt_description ? ' - ' + opt_description : '';
  var self = this;
  if (this.ignoreSynchronization) {
    return self.driver.controlFlow().execute(function() {
      return true;
    }, 'Ignore Synchronization Protractor.waitForAngular()');
  }
```

**Comment by Xotabu4** [comment]
EC.presenceOf(...) is also calling .waitForAngular() internally.

**Comment by jlin412** [comment]
We use browser.driver.wait so we don't have to set ignoreSynchronization=true explicitly.  Maybe we should not call waitForAngular when browser.driver.wait is called or we should have a ExpectedCondition implementation that is not bound to detect angular.

**Comment by mgiambalvo** [comment]
Xotabu4 is correct that EC.presencesOf() is implicitly calling waitForAngular. You could use the ExpectedCondition from WebDriver (instead of our wrapped version). You could also do something like this:

```
var el = $('css_path');
browser.driver.wait(() => {
  return el.isPresent();
}).then(() => {
  done();
});
```

This kind of question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get further help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by jlin412** [comment]
@mgiambalvo Thanks for clarification. So el.isPresent() won't call waitForAngular()?  Why not?  el is still elementFinder object so it should call waitForAngular, no?

Nevertheless, I do think that it is a bug or feature improvement that ExpectedCondition shouldn't call waitForAngular anymore when browser.driver.wait is used to make it easier.

**Comment by mgiambalvo** [comment]
You're right, my example will end up calling waitForAngular. You'd have to do something like this.

```
    browser.driver.wait(() => { 
      return browser.driver.findElement(by.css(".slow"))
        .then(() => { return true; }, () => { return false; });
    }).then(done);
```

I do see your point, it is kind of counter intuitive. Perhaps in your case, just using browser.ignoreSynchronization might be a better option? You could even create a helper like this

```
function ignoreSynchronization(callback) {
  return () => {
    browser.ignoreSynchronization = true;
    var res = callback();
    browser.ignoreSynchronization = false; 
    return res;
  }
}

browser.driver.wait(ignoreSynchronization(EC.presenceOf($('.slow'))))
  .then(done);
```
