### ISSUE TITLE
The navigation hangs at data:text/html,<html></html> when using localhost but works when using a deployed version

### ISSUE THREAD

**Issue by adokania** [angular/protractor#3331]
Hi, 
I am on protractor version 3.3 and running into the issue where my test logs in and opens up the landing page but when I navigate to a new page it hangs at _data:text/html,<html></html>_ in the browser. This only happens with localhost and doesn't happen when i use the deployed version. 

I am using Chromedriver 2.21 and selenium jar 2.52..I tried with directConnect and by providing the seleniumAddress and both run into the same issue.

**Comment by cnishina** [comment]
Hi! This looks like a setup support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
