### ISSUE TITLE
Occasionally Protractor fails to execute test with EADDRINUSE 127.0.0.1:4444 error

### ISSUE THREAD

**Issue by andyman09** [angular/protractor#3332]
I was using protactor 1.8 using multiCapabilities with 7 chrome browser instances running parallel. I was always able to run my test suit successfully. I recently updated my protractor to version 3.2.2. My test suit started to intermittently return the following error message. 

`Error: EADDRINUSE connect EADDRINUSE 127.0.0.1:4444
    [chrome #31]     at ClientRequest.<anonymous> (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:365:15)
    [chrome #31]     at emitOne (events.js:77:13)
    [chrome #31]     at ClientRequest.emit (events.js:169:7)
    [chrome #31]     at Socket.socketErrorListener (_http_client.js:267:9)
    [chrome #31]     at emitOne (events.js:77:13)
    [chrome #31]     at Socket.emit (events.js:169:7)
    [chrome #31]     at emitErrorNT (net.js:1253:8)
    [chrome #31]     at nextTickCallbackWith2Args (node.js:442:9)
    [chrome #31]     at process._tickCallback (node.js:356:17)
    [chrome #31] From: Task: WebElement.isSelected()
    [chrome #31]     at WebDriver.schedule (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:344:17)
    [chrome #31]     at WebElement.schedule_ (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1712:25)
    [chrome #31]     at WebElement.isSelected (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:2023:17)
    [chrome #31]     at actionFn (C:\myAppe2e\node_modules\protractor\built\element.js:82:76)
    [chrome #31]     at Array.map (native)
    [chrome #31]     at C:\myAppe2e\node_modules\protractor\built\element.js:374:46
    [chrome #31]     at Promise.invokeCallback_ (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1329:14)
    [chrome #31]     at TaskQueue.execute_ (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    [chrome #31]     at TaskQueue.executeNext_ (C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    [chrome #31]     at C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    [chrome #31]     at C:\myAppe2e\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    [chrome #31]     at process._tickCallback (node.js:369:9)
    [chrome #31] Error
    [chrome #31]     at ElementArrayFinder.applyAction_ (C:\myAppe2e\node_modules\protractor\built\element.js:371:27)
    [chrome #31]     at ElementArrayFinder._this.(anonymous function) [as isSelected] (C:\myAppe2e\node_modules\protractor\built\element.js:83:30)
    [chrome #31]     at ElementFinder._this.(anonymous function) [as isSelected] (C:\myAppe2e\node_modules\protractor\built\element.js:685:22)
`

It looks like there are some running process that got created by the webdriver-manager did not exist correctly. Have anyone seen this issue?

**Comment by cnishina** [comment]
Could you provide the configuration file for your Protractor test? Also are you using gulp or grunt to run webdriver-manager?

**Comment by andyman09** [comment]
Hi cnishina,

Here is an example of my config file. I am not using gulp. I have my test setup to run on a Teamcity build agent. I manually start the webdriver-manager on the build agent and configure my test to point to the local webdriver-manger address "http://localhost:4444/wd/hub".

`var os = require('os')
    , isWin = /^win32/.test(os.platform());

var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
// A reference configuration file.
exports.config = {
    // ----- How to setup Selenium -----
    //
    // There are three ways to specify how to use Selenium. Specify one of the
    // following:
    //
    // 1. seleniumServerJar - to start Selenium Standalone locally.
    // 2. seleniumAddress - to connect to a Selenium server which is already
    //    running.
    // 3. sauceUser/sauceKey - to use remote Selenium servers via SauceLabs.

    //Protractor can test directly against Chrome and Firefox without using a Selenium Server. To use this, in your config file set
    directConnect: false,

    // The location of the selenium standalone server .jar file.
    // http://docs.seleniumhq.org/download/
    //seleniumServerJar: './scripts/selenium-server-standalone-2.39.0.jar',
    // The port to start the selenium server on, or null if the server should
    // find its own unused port.
    // seleniumPort: 4444,
    // https://npmjs.org/package/protractor
    seleniumAddress: "http://localhost:4444/wd/hub",
    // Chromedriver location is used to help the selenium standalone server
    // find chromedriver. This will be passed to the selenium jar as
    // the system property webdriver.chrome.driver. If null, selenium will
    // attempt to find chromedriver using PATH.
//  chromeDriver: isWin ? './scripts/Chromedriver.exe' : './scripts/Chromedriver',
    // Additional command line options to pass to selenium. For example,
    // if you need to change the browser timeout, use
    // seleniumArgs: ['-browserTimeout=60'],
    seleniumArgs: ['-Dwebdriver.ie.driver=./node_modules/protractor/selenium/IEDriverServer.exe'],


    // If sauceUser and sauceKey are specified, seleniumServerJar will be ignored.
    // The tests will be run remotely using SauceLabs.
    sauceUser: null,
    sauceKey: null,
    framework: 'jasmine2',

    // ----- What tests to run -----
    //
    // Spec patterns are relative to the location of this config.
    specs: "",

    maxSessions: 7,
    // ----- Capabilities to be passed to the webdriver instance ----
    //
    // For a full list of available capabilities, see
    // https://code.google.com/p/selenium/wiki/DesiredCapabilities
    // and
    // https://code.google.com/p/selenium/source/browse/javascript/webdriver/capabilities.js
    multiCapabilities: [
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/home-page/*",
                "./testcases/header-and-footer/*",
                "./testcases/login/*",
                "./testcases/registry/*",
                "./testcases/registry/navigate/*",
                "./testcases/registry/test2/*",
                "./testcases/search_test/*",
                "./testcases/delete/*",
                "./testcases/detail-page/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test2/*",
                "./testcases/test3/*",
                "./testcases/test4/*",
                "./testcases/test5/*",
                "./testcases/test6/*",
                "./testcases/test7/*",
                "./testcases/test8/*",
                "./testcases/test9/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test12/*",
                "./testcases/test13/*",
                "./testcases/test14/*",
                "./testcases/test15/*",
                "./testcases/test16/*",
                "./testcases/test17/*",
                "./testcases/test18/*",
                "./testcases/test19/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test112/*",
                "./testcases/test113/*",
                "./testcases/test114/*",
                "./testcases/test115/*",
                "./testcases/test116/*",
                "./testcases/test117/*",
                "./testcases/test118/*",
                "./testcases/test119/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test212/*",
                "./testcases/test23/*",
                "./testcases/test24/*",
                "./testcases/test25/*",
                "./testcases/test26/*",
                "./testcases/test27/*",
                "./testcases/test28/*",
                "./testcases/test29/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test212/*",
                "./testcases/test413/*",
                "./testcases/test314/*",
                "./testcases/test315/*",
                "./testcases/test316/*",
                "./testcases/test317/*",
                "./testcases/test318/*",
                "./testcases/test319/*"
            ],
            "count": 1
        },
        {
            "browserName": "chrome",
            "chromeOptions": {
                "args": [
                    "allow-running-insecure-content",
                    "ignore-certificate-errors"
                ]
            },
            "prefs": {
                "download": {
                    "prompt_for_download": false,
                    "default_directory": "./"
                }
            },
            "specs": [
                "./testcases/test122/*",
                "./testcases/test133/*",
                "./testcases/test144/*",
                "./testcases/test145/*",
                "./testcases/test146/*",
                "./testcases/test147/*",
                "./testcases/test158/*",
                "./testcases/test159/*"
            ],
            "count": 1
        }],

    //single browser support
    /* capabilities: {
     'browserName': HadeanConfig.defaultSetting.browserName
     },*/

    /*
     Example config for PhantomJS

     1. You need to download manually PhantomJS just put in test dir.
     http://phantomjs.org/download.html

     2. You also need to apply this patch to fix a known bug.
     https://github.com/vrtdev/protractor/commit/2f18b01378e4f054331df23ce536e4081ee1ccf0
     */
    // capabilities: {
    //   'browserName': 'phantomjs',
    //   'phantomjs.binary.path': './node_modules/phantom/bin/phantomjs'
    // },

    // A base URL for your application under test. Calls to protractor.get()
    // with relative paths will be prepended with this.
    // If you change your dev server port this will need to match. - default 'http://127.0.0.1:9000'
    baseUrl: "https://example.com/home",

    // Selector for the element housing the angular app - this defaults to
    // body, but is necessary if ng-app is on a descendant of <body>
    rootElement: 'body',

    // Options to be passed to Jasmine-node.
    onPrepare: function () {
        if (process.env.TEAMCITY_VERSION) {
            var reporters = require('jasmine-reporters');
            jasmine.getEnv().addReporter(new reporters.TeamCityReporter());
        }
        
    },

    allScriptsTimeout: 240000,
    getPageTimeout: 180000,
    // ----- Options to be passed to minijasminenode -----
    jasmineNodeOpts: {
        // onComplete will be called just before the driver quits.
        onComplete: null,
        // If true, display spec names.
        isVerbose: false,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 240000
    }
};
`

**Comment by cnishina** [comment]
Since your job is also starting webdriver-manager, there is a chance that you could have multiple Teamcity jobs running in parallel that are trying to open up the same port number for selenium server. I believe this is why you are receiving the error message EADDRINUSE. 

A better way to do this is to have a single instance of webdriver-manager running in the background. Another way to do this is to start up webdriver-manager on a unique port number. `webdriver-manager start --seleniumPort <some port number>`.

**Comment by andyman09** [comment]
My Teamcity build agents are running on different servers and I manually start the webdriver-manager on each of build agent using webdriver-manger start. I verified that 4444 port is not being using by any server.

**Comment by cnishina** [comment]
There are a lot of things that have changed since 1.8 to version 3.2.2. I would also review the [changelog](https://github.com/angular/protractor/blob/master/CHANGELOG.md).

Also, I'm curious a few more items of your setup:

* Your chrome version
* Your output from `webdriver-manager status`
* Your global protractor version

**Comment by CAPie** [comment]
Hi All!

I've got the same issue on my CI machine (Jenkins) =(
Does anybody know how to fix it

cnishina, in my case
- chromedriver: 2.25
- webdriver-manager status:
`I/status - selenium standalone version available: 2.53.1 [default]`
`I/status - chromedriver version available: 2.25 [default]`
`I/status - geckodriver version available: v0.9.0 [default]`
`I/status - IEDriverServer is not present`
`I/status - android-sdk is not present`
`I/status - appium is not present`

- protractor: protractor@4.0.10
