### ISSUE TITLE
browser.element.all not available in multi-browser tests?

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#3350]
Assume a test utilising several browsers, for example one verifying interaction between chat clients.

[The docs say](https://github.com/angular/protractor/blob/master/docs/browser-setup.md#using-multiple-browsers-in-the-same-test) that in order to get hold of the `element` function, one can use the `element` property of the `browser` object:

```javascript
var browser2 = browser.forkNewDriverInstance();
var element2 = browser2.element;
```

To my current understanding, the difference between the global `element` helper and `browser.element` is that the former is an instance of `protractor.Element` while the latter is a `protractor.ElementFinder`.

I'm not sure if this differentiation is intentional or if it's a bug?

The effect of it is that in a Typescript test, one can't simply refer to the `.all` helper using:
```typescript
browser.element.all(...)
```
but instead has to do this to make the transpiler happy:
```typescript
(<any> browser.element).all(...)
```

Shouldn't the `element` field of the `browser` object be of type `protractor.Element` instead of `protractor.ElementFinder`?

Thanks,
Jan

**Comment by cnishina** [comment]
This is not a bug. Hopefully this will help clarify the types for the items in question:

* the property `element` in the global namespace is of type ElementHelper
* `browser.element` is of type ElementHelper
* `element(...)` returns a type of ElementFinder
* `browser.element.all(...)` returns a type of ElementArrayFinder

when forking a new driver instance:

```
let browser2 = browser.forkNewDriverInstance();   // this is of type Browser
let element2 = browser2.element;                  // this is an ElementHelper
let foo = element2(by.css('foo'))                 // by.css(...) returns a Locator, element2(...) returns an ElementFinder
```

Also, there is no type Element. Are you getting the typings off of master? How are you getting your global imports? Have you tried the [example for typescript](https://github.com/angular/protractor/tree/master/exampleTypescript)?

**Comment by jan-molak** [comment]
Hey Craig and thanks for the quick response!

I think I see what's happening:
- I'm using Protractor 3.3.0 from npm (according to NPM it's been published 3 months ago)
<img width="349" alt="screen shot 2016-07-11 at 19 21 41" src="https://cloud.githubusercontent.com/assets/1089173/16741783/c1da3c92-479c-11e6-9a24-9a863901bf0a.png">

- since Protractor 3.3.0's `package.json` [does not specify](https://github.com/angular/protractor/blob/3.3.0/package.json) the `typings` key, TypeScript can't find them (I see that this has been fixed since then and the `typings` key is present as of [20 days ago](https://github.com/angular/protractor/pull/3298/files))

- because TypeScript couldn't find the typings, I installed them using the [Typings npm module](https://www.npmjs.com/package/typings), and those appear to be [pretty old](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f2459c9af89b5221714d367432b615c6ad0970d/angular-protractor/angular-protractor.d.ts) and incompatible with Protractor 3.3.0.

Given the above, could you please advise when is the `package.json` fix going to make it to the npm?

Many thanks,
Jan

**Comment by cnishina** [comment]
It will happen soon! Possibly today.

**Comment by jan-molak** [comment]
Sweet! Much appreciated 👍

**Comment by jan-molak** [comment]
Thanks for the 4.0.0, Craig! It's a huge improvement. The only thing that's now gone missing from the `built/index.d.ts` typings is the `ProtractorPlugin` class definition. I'll raise a separate ticket for that.

**Comment by cnishina** [comment]
ProtractorPlugins are now part of typings. This will be addressed in the next hot fix.

**Comment by jan-molak** [comment]
Great stuff, looking forward to the release!
