### ISSUE TITLE
Shard by test instead of by file

### ISSUE THREAD

**Issue by RandomSeeded** [angular/protractor#3354]
## Feature Request
---

Shard by individual test instead of by file.

- Rationale: when sharding by file, frequently there are tests remaining to be run, and browser instances available to run them (currently running instances < maxInstances), but these to-be-run tests are not run by the available instances. If sharding by individual test (instead of by file) was available, we would be able to complete the test suite more quickly.
- This is not a breaking change; sharding by test would be done in addition (not instead) of sharding by file. Existing functionality would be unaffected.

Thoughts? Is there was a PR for this functionality would it be considered?

**Comment by Fowowski** [comment]
@RandomSeeded does this PR covers what you need https://github.com/angular/protractor/pull/2633 ? I'm also very interested in sharding test suites because of the type of application that I need to test so hopefully that gonna be introduced in future.

**Comment by RandomSeeded** [comment]
I think actually sharding by suite would be insufficient for my goal (and have reflected my post accordingly). 

Your PR allows you to run two suites of tests simultaneously, where the tests are dependent but the suites are not. In my situation, my tests are all already fully independent, and so shardTestFiles already works for me. I just want to improve efficiency.

**Comment by juliemr** [comment]
Sharding by test would need to be done at the framework level (e.g. Jasmine, Mocha, etc), so we've decided this is out of scope for Protractor. Protractor itself has no idea before they are run what tests are pending - all we can control is which files are loaded.

I can suggest nothing other than splitting up your files :)
