### ISSUE TITLE
Typings for ProtractorPlugin missing from index.d.ts in Protractor 4.0.0

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#3365]
Hi there,

It seems like the definition of the `ProtractorPlugin` is no longer accessible to plugin developers.

This definition used to be available from the `protractor/built/plugins` package as per the [docs here](https://github.com/angular/protractor/blob/master/docs/plugins.md#writing-plugins-in-typescript):

```typescript
import {ProtractorPlugin} from 'protractor/built/plugins';
```

but as Protractor 4.0.0 does not include this definition in the main `built/index.d.ts` nor does it provide definitions at `protractor/built/plugins/`, the class is beyond reach.

Could you please expose it in the main definitions file please?

Many thanks,
Jan

**Comment by juliemr** [comment]
We just need to add this to our output files.

**Comment by jan-molak** [comment]
Thanks Julie, that would be great 👍
