### ISSUE TITLE
Typings for 'switchTo()' missing on Browser in index.d.ts in Protractor 4.0.0

### ISSUE THREAD

**Issue by niieani** [angular/protractor#3366]
`switchTo()` is present on the global: `browser`, but is not declared in `index.d.ts`.

**Comment by cnishina** [comment]
This is being closed because `switchTo` is not exported on browser.

`browser.driver.switchTo` should exist as a function. `switchTo` is part of `selenium-webdriver` and is not currently exported as part of our typings. We will be adding `selenium-webdriver` typings to Protractor soon.

**Comment by niieani** [comment]
Sounds good @cnishina. Which issue can I track to get notified about selenium typings?
