### ISSUE TITLE
Does protractor support manually failing a test?

### ISSUE THREAD

**Issue by zero298** [angular/protractor#3369]
Does protractor support manually failing a test?  I'm running into issues using `fail()` and figured it would be similar to how [Jasmine supports it](http://jasmine.github.io/2.4/introduction.html#section-Manually_failing_a_spec_with_<code>fail</code>).

**Comment by juliemr** [comment]
It is supported, and should just work. What sort of problems are you seeing?

Keep in mind that `fail` only works synchronously - if you are trying to do something within a promise or something, you'll need to use `done.fail`.

**Comment by zero298** [comment]
I'm trying both `fail` and `done.fail` but receiving `ReferenceError: fail is not defined` and ` TypeError: done.fail is not a function`.

Here are my tests:

```
"use strict";

var SearchPage = require("../pages/search");

describe("Search Page", function () {
    it("should fail hard", function () {
        fail();
    });

    it("should fail hard async", function (done) {
        done.fail();
    });
});
```

and here is the config:

```
exports.config = {
    allScriptsTimeout: 11000,
    baseUrl: "http://localhost:4400",
    framework: "jasmine",
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000
    },
    suites: {
        search: "e2e/search/**/*.js"
    },
    suite: "search",
    multiCapabilities: [
        {
            browserName: "chrome"
        }
    ]
};
```

**Comment by NickTomlin** [comment]
`fail` and `done.fail` are both working for me in Protractor `4.0.4` and `3.3.0`. I would ensure you are using a recent version of Protractor

I'm going to go ahead and close this issue. Thanks 😄 !

**Comment by zero298** [comment]
I'm sorry.  Yes, I had tried using the `fail` and `done.fail` and both were working correctly.  I had been using them incorrectly.  Thanks.
