### ISSUE TITLE
Cannot read property 'prototype' of undefined (Protractor 4 upgrade problem)

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#3377]
After upgrading to Protractor 4.0.0, we are starting to see out tests failing immediately in `onPrepare()` with:

> Error: TypeError: Cannot read property 'prototype' of undefined

failing on the following line:

```js
protractor.ElementArrayFinder.prototype.takewhile = function(whileFn) {
   // ...
};
```
(here we are adding `takewhile` - linking https://github.com/angular/protractor/issues/2521) 

Looks like `ElementArrayFinder` is no longer exposed on the `protractor` global object.

How can we extend `ElementArrayFinder` in Protractor 4? Thanks!

SO reference: http://stackoverflow.com/questions/38380465/cannot-read-property-prototype-of-undefined-after-upgrading-to-protractor-4.

**Comment by juliemr** [comment]
You can access it via `protractor/built/element`.

@cnishina thoughts on whether this should be re-introduced to the protractor namespace?

**Comment by Droogans** [comment]
@alecxe I've had some good success with this approach: https://github.com/angular/protractor/issues/3359#issuecomment-232530006

**Comment by cnishina** [comment]
I think we could reintroduce similar to the suggestion / how we export selenium-webdriver stuff: 

```
  // Export the protractor classes
  export let Browser = require('./browser').Browser;
  export let ElementFinder = require('./element').ElementFinder;
  export let ElementArrayFinder = require('./element').ElementArrayFinder;
  export let ElementHelper = require('./browser').ElementHelper;
  export let ProtractorBy = require('./locators').ProtractorBy;
  export let ProtractorExpectedConditions = require('./expectedConditions').ProtractorExpectedConditions;
```

**Comment by philjones88** [comment]
@cnishina thanks for putting that PR in. Suffering the same issue here failing 7 of our protractor tests, upgraded from 3.3.0 but don't really want to revert, are there plans for a 4.0.1 release that this change will be in?
