### ISSUE TITLE
After it passed first time, it won't fulfill email form second time

### ISSUE THREAD

**Issue by sasafister** [angular/protractor#3383]
I have two tests. First is truthy if login credentials is wrong. Works fine, and then second test in same file won't fulfill email form, but it fulfill password form. Any ideas why?

```
describe('Login: ', function() {

  beforeEach(function() {
    browser.driver.get(browser.params.baseUrl);
  });

describe('When clicking on login with bad credentials', function() {
    it('Should login to dashboard', function() {
      browser.driver.findElement(by.id('email')).sendKeys('wrong@example.com');
      browser.driver.findElement(by.id('password')).sendKeys('Pass123@@@');
      element(by.id('login')).click().then(function() {
        expect(element(by.id('main-logo')).isPresent()).toBe(false);
      });
      browser.driver.findElement(by.id('email')).clear();
    });
  });

  describe('When clicking on login with good credentials', function() {
    it('Should login to dashboard', function() {
      browser.driver.findElement(by.id('email')).sendKeys('right@emaple.com');
      browser.driver.findElement(by.id('password')).sendKeys('Pass123@@@');
      element(by.id('login')).click().then(function() {
        expect(element(by.id('main-logo')).isPresent()).toBe(true);
      });
    });
  });
});

```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
