### ISSUE TITLE
require('protractor') resolves to the wrong js file

### ISSUE THREAD

**Issue by rayrapetyan** [angular/protractor#3395]
Bug report
---

- Node Version: `v4.4.7`
- Protractor Version: `4.0.0`
- Operating System and Version `FreeBSD 10.3 (but also reproduced in Centos 6)`
- Steps to reproduce the bug:

1.
`npm install protractor`

2.
`node`

`> console.log(require.resolve('protractor'));`

Expected:

`node_modules/protractor/built/protractor.js`

Actual:

`node_modules/protractor/built/browser.js`

**Comment by cnishina** [comment]
Please look at the CHANGELOG.md, protractor was renamed to browser and wrap driver method was brought into browser as a static method.

**Comment by cnishina** [comment]
On second thought,

**Comment by cnishina** [comment]
Looking at the issue referenced:

require('protractor').wrapDriver should work. This will be addressed.

**Comment by cnishina** [comment]
This is done with 2a3a0dc80edccbb72e6b2ca8c487b1eaacf15a20.
