### ISSUE TITLE
ProtractorBy.prototype.cssContainingText returns object

### ISSUE THREAD

**Issue by ingoe** [angular/protractor#3396]
Please change `ProtractorBy.prototype.cssContainingText` to return an instance of `webdriver.Locator`

As documented this function should return webdriver.Locator but returns a simple object.
Therefore` webdriver.Locator.checkLocator` currently fails when trying to use the until module. E.g. `until.elementLocated(by.cssContainingText('.some_class', 'some text'))` fails

**Comment by juliemr** [comment]
See also https://github.com/angular/protractor/issues/3221

**Comment by cnishina** [comment]
Hmmm... so there's some clarification here:

* we are mislabeling our interface `Locator` as a `webdriver.Locator`. This is probably causing some confusion. The locator is the object we are passing to element or element.all. Then element(locator) uses the `findElementsOverride` to find the web element.
* `webdriver.Locator` no longer exists and has been changed to `webdriver.By` and `checkLocator` has been renamed changed to `check`. 

So, should `util.elementLocated` work? My conclusion is no. This probably did not work prior to the TypeScript change in 4.0.0.
