### ISSUE TITLE
Chrome failed to start: crashed -----------for electron app

### ISSUE THREAD

**Issue by manju22** [angular/protractor#3401]
We are using Electron app, its an standalone app which uses chromium engine inside to render pages, we got interesting issue here , we getting error chrome browser crashed when we are trying to launch app, please let us know if you have any solution.

Below is Error trace.
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 10911
Only local connections are allowed.
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Windows NT 6.1 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61.26 seconds
Build info: version: '2.52.0', revision: '4c2593cfc3689a7fcd7be52549167e5ccc93ad28', time: '2016-02-11 11:22:43'
System info: host: 'PTS-LDR-KRISHN7', ip: '10.237.120.185', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_73'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

Thank you in advance.

**Comment by NickTomlin** [comment]
Hi there,

Please update your question following the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

Thanks!
Nick

**Comment by cnishina** [comment]
Closing this issue since there has been no response.
