### ISSUE TITLE
afterAll not invoked after completing a test suite in protractor

### ISSUE THREAD

**Issue by rajashreekm** [angular/protractor#3408]
I am using protractor(3.2.2) with jasmine (2.4)
When invoking protractor tests sequentially the afterAll() function is not invoked after a test suite (describe).I see it being called after the first test in the second suite.I have the logout function on afterAll() and this causes all subsequent tests to fail.

This is how my conf.js looks like

  suites: {

```
   regression :[
          'specs/first.test.js',
          'specs/second.test.js',
          'specs/third.test.js',
          'specs/fourth.test.js'
        ]
},
```

Only the first test suite is successful.

The afterAll gets called in the first test of second.test.js and all tests start failing

This is the setup and teardown in each test suite
beforeAll(function () {
        loginPage.login();
        browser.waitForAngular();
    });

```
afterAll(function () {
   logout();
});
```

**Comment by cnishina** [comment]
This issue (sounds like a support question) but to get more clarity, more information is required:

* In your test suites, it is unclear if afterAll appears in each javascript file
* It is unclear what your configuration file looks like (please see the issue template)
* Are you doing something asynchronous in this logout method? What is actually happening in this logout method?
* Are there any appropriate logs that could be provided?

**Comment by rajashreekm** [comment]
Yes each javascript file has setup and tear down (beforeAll and afterAll)

conf.js looks like this
var Jasmine2HtmlReporter = require( 'protractor-jasmine2-html-reporter' );
var jasmine2SpecReporter = require( 'jasmine-spec-reporter' );
var d = new Date();

var testOutput = new Jasmine2HtmlReporter( {
    savePath: 'test-output',
    filePrefix: d.getFullYear() + '_' + (d.getMonth() + 1) + '_' + d.getDate() + "Test_Report.html",
    takeScreenshots: false,
    takeScreenshotsOnlyOnFailures: true,
    fixedScreenshotName: false,
    consolidate: true,
    consolidateAll: true
} );

//------------------Platform connections ----------------------------------------------------------
// Letting Protractor know how to connect to drivers for the browser through Selenium Server

exports.config = {
    seleniumAddress: 'http://127.0.0.1:4444/wd/hub',


//-------------------Tests to run ------------------------------------------------------------------

    // specs: [
    //     'specs/*.js'
    // ],

//------------------ Patterns to exclude ----------------------------------------------------
    exclude: [],

    suites: {
       regression :[
          'specs/first.test.js',
          'specs/second.test.js',
          'specs/third.test.js',
          'specs/fourth.test.js'
        ]
    },

//--------------------------- Setting up Browser---------------------------------------------

    capabilities: {
        'shardTestFiles': true,
        'maxInstances': 1,
        'browserName': 'chrome',
        'chromeOptions': {
            'args': ['disable-extensions', 'start-maximized']
        }
    },
//-------------------Global test information-------------------------------------------------
    //-------------------- Timeout in milliseconds for each script run ----------------------
    allScriptsTimeout: 11000,

    //----------------------Page wait time ---------------------------------------------------
    getPageTimout: 10000,

    //------ This if true will restart browser between tests----------------------
    restartBrowserBetweenTests: false,

    //---------------Test framework---------------------------------------------------------
    framework: 'jasmine2',
    jasmineNodeOpts: {
        onComplete: null,
        isVerbose: true,
        showColors: true, // is True, prints colors to terminal
        includeStackTrace: true,
        defaultTimeoutInterval: 30000, // wait time in ms before test fails
        print: function () {} // to print Jasmine results
    },

    //----------------------Settings before tetscases to be executed-------------------------
    onPrepare: function () {
       
        browser.get(baseURL );

        // Add HTML Reporter
        jasmine.getEnv().addReporter( new jasmine2SpecReporter( {displayStacktrace: 'all'} ) );
        //  jasEnv = jasmine.getEnv();

        jasmine.getEnv().addReporter( testOutput );

    }

};

==================
afterAll and beforeAll looks like this

beforeAll(function () {
        loginPage.login(username,password);
        browser.waitForAngular();
    });

    afterAll(function () {
        LogoutFn.logout();
    });


logout.js is like this
var LogoutFn = function(){
    this.userPanel = element(by.id('userpanel');
    this.logout = element(by.id(logout()));
    this.okBtn =element(by.id('okbtn');
    this.cancelBtn = element(by.id('canel');

    this.logout = function(){
        this.userPanel.click();
        this.logout.click();
        this.okBtn.click();
    }
};
module.exports = new LogoutFn;

In each javascript test file i import var LogoutFn = require("../commons/logout.js");

**Comment by rajashreekm** [comment]
Any updates on this

**Comment by cnishina** [comment]
The only thing that looks unusual is

```
capabilities: {
    'shardTestFiles': true,
    'maxInstances': 1,
    'browserName': 'chrome',
    'chromeOptions': {
        'args': ['disable-extensions', 'start-maximized']
    }
},
```

So you are sharding the test files but you want it to logout before the next file starts? This would be my guess.

**Comment by rajashreekm** [comment]
I corrected it and took that out of conf.js but still don't see the logout happening

**Comment by aapetrov** [comment]
Any updates? It seems that I've faced with the same problem. Logout in the afterAll doesn't invoked. However beforeAll is invoked, and since in the beforeAll I have login all tests except first are failed.

**Comment by rajashreekm** [comment]
afterAll was invoked correct.The locators had changed in my case.Hence closing this.

**Comment by aswinrajen** [comment]
The same issue i am facing afterAll logout is not invoked but instead if i use afterEach the logut invokes . Can u pls suggest me
