### ISSUE TITLE
Having trouble adding cookies...

### ISSUE THREAD

**Issue by wlingke** [angular/protractor#341]
Hello, I am trying to do a very simple add and retrieve cookie test:

```
describe("Homepage", function () {
    var ptor;

    beforeEach(function () {
        ptor = protractor.getInstance();
        browser.get('/');
        ptor.manage().addCookie("test", "value");
    });


    it('should have cookie named test', function () {
        cookies = ptor.manage().getCookie("test").then(function(data){
            console.log(data);
        });
    });
});

```

The console prints out `null` and I can't figure out why... I would really appreciate any help on this.

**Comment by sssalib42** [comment]
Just a quick update:
the link to https://github.com/angular/protractor/blob/master/spec/login/viaTestSpec.js is 404 not found. I believe that the file was renamed and here is what the folder includes now:
https://github.com/angular/protractor/blob/master/spec/login/login_spec.js
