### ISSUE TITLE
verbose isn't repsonsive with jasmine

### ISSUE THREAD

**Issue by noor92** [angular/protractor#3413]
I am using protractor version:  4.0.0 
and Karma-jasmine version: 1.0.2

even though it's set to true:

> jasmineNodeOpts: {
>             isVerbose: true,
>         },

![capture](https://cloud.githubusercontent.com/assets/14199626/17134013/0203cbd4-535b-11e6-9268-1c4c4acc8dc0.PNG)

**Comment by cnishina** [comment]
Similar issue due to the jasmine2 upgrade. Please see: https://github.com/angular/protractor/issues/1716
