### ISSUE TITLE
Getter for private property ElementFinder.browser_ is needed

### ISSUE THREAD

**Issue by Irynn** [angular/protractor#3414]
Feature request: getter for private property ElementFinder.browser_

Main issue here is that we use several browsers, and we need to get the origin of where the element came from. On previous versions we were using simply elementFinder.browser_ in our code, but here it is marked as private and unaccessible anymore.

- A relevant example test
``` 
class PlSwitch  {
    constructor(switchElement) {
       this.switchElement = switchElement;
        this.toggle = switchElement.$('.plswitch');
    }

    waitForToggleAnimation(){
        //Using internal reference to protractor instance to be sure that correct browser will be used.
        this.switchElement.browser_.wait(protractor.ExpectedConditions.stalenessOf(this.switchElement.$('div[data-ng-animate="1"]')),
            2000, "Animation of toggle is not over for 2 sec");
    }
}
```
Here we need to take a .browser_ property to make proper browser to wait since these elements can come from different browser instances.

As a possible solution would be creating a getter for this property

**Comment by Xotabu4** [comment]
We are with @Irynn working on same project.
TypeScript compiler  spams with errors that private variable is tried to be used. For us that is not cool at all to lose reference to internal reference to browser for element. In our plans to have tests for 5-10-20 users, and building a wrappers for elements is really painful without such reference.

Simple getter for this property, or making it public will solve our issue.

**Comment by cnishina** [comment]
Easy fix: Changed the constructor for private variables to be public... if there are future issues with accessibility to variables let me know.
