### ISSUE TITLE
Not able to execute protractor test through eclipse

### ISSUE THREAD

**Issue by jagadishchandran** [angular/protractor#3418]
Hi Team,

While trying to execute protractor test through eclipse, I am getting the below error -

Protractor failed

Reason: Error while launching client file 
(Error while launching client file
org.eclipse.core.runtime.CoreException: The file does not exist for the external tool named Protractor for _protest_src_conf.js.)

![image](https://cloud.githubusercontent.com/assets/5500385/17164825/67d9b96c-53e9-11e6-9e29-9f547d4122ec.png)

I have made all possible configuration like below -

1. Installed Tern for eclipse
2. Installed AngularJS for eclipse
3. Converted the project to tern project.
4. Added AngularJs, Browser & Protractor as modules in Tern.
5. Configured cli.js file as protractor client file.

Please help me to resolve the issue.

Thanks,
Jagadish

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
