### ISSUE TITLE
Protractor, jasmine : How to print current page URL on console

### ISSUE THREAD

**Issue by kumarvishalvishnoi** [angular/protractor#3421]
My requirement is to print Current page url on console.
I tried with console.log('URL is= '+driver.browser.getCurrentUrl());

Getting below error on console
 **Failed: driver is not defined**

**Comment by mgiambalvo** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
