### ISSUE TITLE
Unable to debug protractor scripts using browser.debugger()

### ISSUE THREAD

**Issue by prashanth-sams** [angular/protractor#3429]
I use terminal for execution & debugging scripts; Actually I am unable to debug through browser.debugger(); but the same is achieved through `browser.pause();`

I entered below cmd for execution followed by '`repl`' and then tried to enter protractor cmds but it fail to work :(

`protractor debug protractor-config.js;`

**Note:** the execution actually pause on breakpoint but unable to debug it like what we do on `browser.pause()`

Is this a better approach to debug through `browser.debugger() `or any other ways to achieve it..

![](http://i.stack.imgur.com/nGv8x.png)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
