### ISSUE TITLE
Trouble selecting elements that have been transcluded

### ISSUE THREAD

**Issue by AnbuItachi** [angular/protractor#3432]
I have elements that are being transcluded into a component. These elements are clickable icons with functions attached. Writing my test using page object I am unable to select these icon elements even though when viewing them through the browser developer tools, they do exist. I have tried every selector possible to attach to these elements but it always returns undefined. Currently I'm attempting to attach to the ng-click function, but for some reason I cannot affect these elements.

**Comment by sjelin** [comment]
Hi!

This looks like a support question. Please ask your support questions on StackOverflow, Google Group discussion list, or Gitter. For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions.  If you feel strongly that this is a bug, please file a new issue filling out our bug reporting form.

Thank you!
