### ISSUE TITLE
Not possible to use IE32 on x64 with Protractor 4.x

### ISSUE THREAD

**Issue by lufecir** [angular/protractor#3441]
Hi,

Since version 4.x it is no longer possible to use IE32 browser on a 64bit machine.
'webdriver-manager start' used to take the flag --ie32 into account to decide whether to use IE32 or IE64. Now it uses only the architecture information Node.js provides and so it always starts IE64 driver on an x64 machine. 

So if you specified the --ie32 flag also for 'webdriver-manager update' then that driver is not available and running the Protractor tests fails. And I don't want to use the IE64 driver since it is too slow.

Are there any plans of providing a way to enforce the use or IE32?

Thanks.

Luc

**Comment by juliemr** [comment]
`--ie32` should still work, but we may have a bug somewhere. What other flags are you using? @cnishina can you take a look?

**Comment by lufecir** [comment]
These are the flags I'm using with 'webdriver-manager-update':

`webdriver-manager update --standalone --chrome --ie32`

They are all taken into account and the correct versions of the drivers are downloaded.

The flags used for 'webdriver-manager-start' are:

`webdriver-manager start --ie32`

And here the ie32 flag seems to be ignored. I also looked into the code and as far as I can see the constant representing the 'ie32' flag is only used for the 'update'. The code for the 'start' only uses 'process.arch' to determine which version of IE to use.

**Comment by cnishina** [comment]
confirmed.

**Comment by cnishina** [comment]
https://github.com/angular/webdriver-manager/issues/68

**Comment by cnishina** [comment]
Closed with https://github.com/angular/webdriver-manager/commit/8b61b71410dbca6e205fbc599b954fe61a8ee937
