### ISSUE TITLE
Using element(by.xpath) and js scrollIntoView-> is causing FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by kajaleprashant24** [angular/protractor#3443]
Using element(by.xpath) and js scrollIntoView-> is causing FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
E.g:-
```
var el=element(by.xpath("//tcc-banner//div[@class='banner-right']//div[text()='NEW QORDERI2 CASE']"));

this.scrollAndClick = function(element) {
		browser.executeScript(arguments[0].scrollIntoView(), element);
		element.click();
	};

```
so calling:-
`**scrollAndClick(el);** `

If I use browser.findElement(by.xpath()); it works.

Exceptions:-
Started

<--- Last few GCs --->

  113789 ms: Mark-sweep 1325.3 (1456.9) -> 1329.5 (1456.9) MB, 3702.4 / 0 ms [allocation failure] [GC in old space requested].
  117537 ms: Mark-sweep 1329.5 (1456.9) -> 1329.5 (1456.9) MB, 3747.9 / 0 ms [allocation failure] [GC in old space requested].
  121527 ms: Mark-sweep 1329.5 (1456.9) -> 1325.3 (1456.9) MB, 3988.4 / 0 ms [last resort gc].
  125012 ms: Mark-sweep 1325.3 (1456.9) -> 1325.3 (1456.9) MB, 3484.2 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001E8ABBB4639 <JS Object>
    3: addCallback_ [C:\Users\pkajale\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:~1278] [pc=000000293803D99B] (this=0000008E6D24F199 <a Promise with map 0000003BDF2C5CF1>,callback=0000031C0CEF2CE1 <JS Function toWireValue (SharedFunctionInfo 00000235E9E55919)>,errback=000001E8ABB041B9 <undefined>,name=000001E8ABB671F9 <String[4]: then>,fn=000002...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory.

This was working till last week. Not sure what changed causing this to fail.

**Comment by NickTomlin** [comment]
This seems like it is probably related to https://github.com/angular/protractor/issues/3442. I'm going to go ahead and close this. If you feel that it is a distinct issue, please create a new issue that follows the  [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) and gives us enough information to differentiate it. Thanks! 😄
