### ISSUE TITLE
Is their anyway to pass parameter from console to plugin attribute of conf file

### ISSUE THREAD

**Issue by Saurabh06** [angular/protractor#3449]
i have used plugin for report inside the conf file but i am not able to pass the screenshotPath from console. i want to change hardcoded path to command line provided path.
exports.config = {
plugins: [{
       package: 'jasmine2-protractor-utils',
       disableHTMLReport: false,
       disableScreenshot: false,
       screenshotPath: '**reports/screenshots**',  /* i have to give path from command line instead of hardcoded path*/
       screenshotOnExpectFailure:true,
       screenshotOnSpecFailure:true,
       clearFoldersBeforeTest: true,
       htmlReportDir: '**reports/htmlreports**'
       }]
}

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
