### ISSUE TITLE
Failed: Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.5.6/ng/test"

### ISSUE THREAD

**Issue by hima65** [angular/protractor#3455]
Hi,
Protractor v3.3.0
Platform : Windows 7
Browser : Chrome

while running tests on chrome and I'm seeing the below error

Message:
Failed: Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.5.6/ng/test"
   Stacktrace:
     undefined

i am seeing the above error **on** and **off**. I have gone through a similar issue in a post, placing **rootElement :"[ng-app="text"]"** didn't solved my issue am still getting error.

**Comment by NickTomlin** [comment]
Hi 😄 

It's going to be very hard to figure out what is wrong without a reproducible test case. Can you share example code and config that can help us reproduce this?

- Your Angular Version
- Your Node Version

Unless we can iron down some specifics, I think this is better handled on StackOverflow or Gitter.

Thanks!

**Comment by juliemr** [comment]
Closing as a support issue with no updates.

**Comment by Harsha509** [comment]
HI There,

Sorry for the delay. Am able to still reproduce this issue in my project. Please find the below details.
Node Version: 4.4.7
Angular Version:1.3.11

Thanks!
