### ISSUE TITLE
Error when updating webdriver - unable to get local issuer certificate

### ISSUE THREAD

**Issue by el-davo** [angular/protractor#3457]
- Node Version: 5.12.0
- Protractor Version: 4.0.0
- Operating System and Version: Windows 7 Enterprise

We get an error when updating webdriver with command

```
node ./node_modules/protractor/bin/webdriver-manager update --ignore_ssl=true
```
error
```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
```

Any help appreciated

**Comment by NickTomlin** [comment]
I'm not able to reproduce this on a Windows 7 VM Running `4.0.0`. Can you provide some more details on your networking setup? Why are you using `--ignore_ssl` if you are not using a proxy or a cdn?

**Comment by cnishina** [comment]
I am tried this out and was unable to reproduce this. I'm curious too if there is a proxy or an alternative download site that is being used that is causing this error. Please provide more information.

**Comment by manoj9788** [comment]
I had this error before, and this is something related to my company proxy after adding a --proxy command line args it worked fine.

**Comment by el-davo** [comment]
The same command was working for months about a week ago and we never had the need to proxy anything. This is a big company and i dont have control of the network, but i can look into any recent changes, Thanks

**Comment by el-davo** [comment]
Just tried it again today. The command is now working. I guess it could have been an issue with the network in our organization. Please feel to close this

**Comment by NickTomlin** [comment]
@el-davo Glad it's sorted. Thanks for letting us know!

**Comment by MaximVer** [comment]
@NickTomlin, i am having the same issue, when i am using it in the Companies network. Do you know specific links that is webdriver-manager is trying to access?

**Comment by kimtuck** [comment]
Had the same issue on MAX OSX -- adding the --ignore_ssl=true fixed it for me.

**Comment by postmeback** [comment]
I am also facing the same issue, i cannot modify the network...Can anyone provide any solution to me?

**Comment by postmeback** [comment]
![untitled](https://user-images.githubusercontent.com/14862687/37018608-fd6b05ec-213a-11e8-8cfb-64bed0087648.png)

**Comment by postmeback** [comment]
I did this 

**Call
./node_modules/.bin/webdriver-manager update --ignore_ssl
inside the project repo and after that:
ng e2e
works.**

Source: https://github.com/angular/angular-cli/issues/7690

**Comment by Umesh2Patel** [comment]
Thanks @kimtuck  After adding the --ignore_ssl=true it worked.

**Comment by skAutomation12** [comment]
webdriver-manager start --ignore_ssl

Should work.
