### ISSUE TITLE
In Angular 2, by.model, by.binding and by.repeater

### ISSUE THREAD

**Issue by jlin412** [angular/protractor#3459]
I was told by.model, by.binding and by.repeater won't work in angular 2.  Is that true?  What is alternative?  See the below link:

http://stackoverflow.com/questions/34220948/cant-run-selenium-via-protractor-on-firefox-after-update-to-angular-2

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
