### ISSUE TITLE
After a pop-up disappears, protractor crashes 

### ISSUE THREAD

**Issue by teddylo57** [angular/protractor#3462]
I'm writing a protractor test for fb connect popup, after entering the proper information and proceeding, protractor crashes. I think perhaps because the fb popup closes and the window handler is unable to return to the main angular window.

Here is my code below:

		'landingPage.fbConnectButton.click().then(function (){
			browser.getAllWindowHandles().then(function (handles){
				browser.switchTo().window(handles[1]);
			})
		}).then(function (){
			landingPage.setIsNotAngularPage();
		}).then(function (){
			landingPage.enterFBEmail(email);
			landingPage.enterFBPassword(password);
		}).then(function (){
			landingPage.popupLoginButton.click();
		}).then(function (){
			landingPage.waitFBPermissions();
		}).then(function (){
			landingPage.popupConfirmPermissions.click();
		}).then(function (){
			landingPage.setIsAngularPage();
		}).then(function (){
			browser.getAllWindowHandles().then(function (handles){
				browser.switchTo().window(handles[0]);
			})
		}).then(function (){
			browsePage.waitForAngular();
		}).then(function (){
			browsePage.waitForBrowse();
		})'

I've tried many variations but it seems that no matter what the error is always 

  - Failed: no such window: target window already closed
from unknown error: web view not found

Is there an issue because the fb popup closes by itself and protractor returns to the main angular window. perhaps the error is because protractor still expects the handler[1] to still exist?

- Node Version: `4.4.4`
- Protractor Version: `4.0.2`
- Browser(s): `chrome 52/firefox`
- Operating System and Version `os x el capitan`

**Comment by sjelin** [comment]
A few things:

1.  I have verified that there is not a problem with `switchTo` in the following test:

  ```js
  describe('d', function() {
    it('t', function(done) {
      browser.ignoreSynchronization = true;
      browser.get('http://localhost:3333');
      var open = element(by.tagName('a'));
      open.click();
      browser.getAllWindowHandles().then((handles) => {
        browser.switchTo().window(handles[1]);
        var close = element(by.tagName('a'));
        browser.sleep(2000);
        close.click();
        browser.switchTo().window(handles[0]);
        browser.sleep(2000);
        expect(open.getText()).toEqual('open');
        done();
      });
    });
  });
  ```

2. I suspect that the first element of the array returned by `getAllWindowHandles()` is always the current window, so `browser.switchTo().window(handles[0]);` switches to the current window, which is closed, hence the error.  See my above example for a better switching strategy.
3. You are not returning at the end of each `then({..})` block, so you aren't getting the kind of synchronization you're expecting.  See my above example for a better synchronization strategy.
