### ISSUE TITLE
How to switch between ports to connect to browsers ,in spec file using protractor

### ISSUE THREAD

**Issue by cboddu** [angular/protractor#3475]
Hi !

I am automating custom browser, that is inside desktop application using protractor. Initially I have to connect to some port, and then later I have to switch to a custom browser running at another port in between script (spec file).

For initial connection I am mentioning the port in capabilities:

capabilities : {
        'browserName': 'chrome',
        'chromeOptions': {'debuggerAddress': '127.0.0.1:8088'}

    },
Is there a way to switch the port in between the script execution?

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
