### ISSUE TITLE
Property 'manage' doesn't exist on type 'ProtractorBrowser'

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3477]
I am trying to use `browser.manage().window().maximize()` in my config and specs, The typescript compiler throws the above error. I think the method is not yet exported! Similar case is for `browser.switchTo().alert()` few of the properties are still not exported!

- Protractor Version: `4.0.3`

**Comment by cnishina** [comment]
This is an issue. For now, could you use `browser.driver.manage` and `browser.driver.switchTo`?

**Comment by igniteram** [comment]
Yup, using `browser.driver` as a workaround !
Also Craig I have one other issue which i commented here https://github.com/angular/protractor/issues/3431 .Its kinda blocker when using `onPrepare` function in `config.ts`.
