### ISSUE TITLE
Using getMultiCapabilities() does not start tests with provided config

### ISSUE THREAD

**Issue by Xotabu4** [angular/protractor#3481]
Bug report
---

- Node Version: `6.2.1`
- Protractor Version: `3.3.0`
- Browser(s): `chrome`
- Operating System and Version `Mac OS`
- Your protractor configuration file:

```javascript
getMultiCapabilities: function () {
//Example is simplified, but still does not work.
let cap = {
            'browserName': 'chrome',
            'chromeOptions': {
                // Allowing unsecure HTTPS connections.
                'args': ['disable-web-security', 'use-fake-device-for-media-stream', 'use-fake-ui-for-media-stream'],
                // Allowing all browser notifications by default - http://goo.gl/RM1Q3n
                prefs: {'profile.managed_default_content_settings.notifications': 1}
            },
            prefs: {
                'VideoCaptureAllowedUrls': ['url']
            },
            maxDuration: 3600,
};
return [cap]
},
```
- A relevant example test
Any, tests does not start at all.

- Output from running the test:
```
**************************************************   
Process finished with exit code 0
```
- Steps to reproduce the bug
Just try to use getMultiCapabilities in you protractor conf file

Hi! Trying to use getMultiCapabilities() function to provide customized multicapabilites, but it seems like protractor does not accepts capabilites from this function.

Tried a lot - to return array with capability, to return promise resolved to array of capabilities, no luck. Browser does not starts at all. Can someone please check if this function is still works?

**Comment by Xotabu4** [comment]
Updated to protractor 4.0.3 - and it works there
Should i close it now?

**Comment by cnishina** [comment]
Since it works on the recent release of Protractor, closing this issue. Thanks for doing the investigation.
