### ISSUE TITLE
not able to use browser functions inside a function where a callback is called

### ISSUE THREAD

**Issue by rojosa** [angular/protractor#3482]
I have been working on protractor for over two weeks now and have taken a liking towards it, but there's a certain problem that's been bugging me for a while:

What I want to do is: fetch values from database and use it in my tests, so I have been doing the following:

var test=function(callback)
{
//connection made;
//select query fired;

connection.query('select * from mytable', function(rows,error){

var result={};

for(int i=0;i<rows.length;i++)
{
result.first=rows[i].col1;
result.sec=rows[i].col2;
result.third=rows[i].col3;

callback(result);
}

});

} 

//and then I use the return values as:

test(function(data){

var value1;
var value2;
value1=data.first;
value2=data.sec;
// i am able to print value1 and value2, the real problem is below:

browser.get(value1);//the browser function wont work!!

});
the spec passes with no failures, I can print the values from the database but I am not able to use the browser functions.

Kindly help!!
I am using jasmine framework.

**Comment by cnishina** [comment]
Hi! This issue appears to not have enough information to figure out how protractor is starting, what your config looks like, and what your spec file looks like. This also appears to be a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

Future reference, please use markdown. It is easier to read.
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
