### ISSUE TITLE
Priority of using .then() when I try to Get Text of web element  

### ISSUE THREAD

**Issue by mohamedMahran** [angular/protractor#3488]
Hi All,  
when I try to Get Text of web element , I made it in 2 technique . one of those style with .then() like below 

**firstApproach**
let expecttedHeaderH1=element(by.css(''locator')).getText();
let actualText="Actual text";
expectedHeaderH1.then(function(expectedText){
expect(expectedText).toequal(actualText);
});

**secondApproach**
let expecttedHeaderH1=element(by.css(''locator')).getText()
let actualText="Actual text";
expect(expectedText).toequal(actualText);

and other Approach I made it without using promises.then and also works fine ! I wonder from this technique because as I know that protractor make webdriverJs uses an object called the ControlFlow, which coordinates the scheduling and execution of commands operating on a queue and each call that interacts with the browser, such as get(), findElement(), sendKeys(), and click(), is being scheduled and pushed onto the WebDriver ControlFlow, allowing us to not have to worry about using .then() on the resulting promises. 

Please Advice when I should .then() in a Protractor

**Comment by NickTomlin** [comment]
`getText` returns a promise, so you should always use `then` to reliably resolve that call to a value.
Hi there!

Additionally, your question is better suited for StackOverflow or Gitter. In the future, please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
