### ISSUE TITLE
Test case stops working as expected when used with socket.io

### ISSUE THREAD

**Issue by ranakrunal9** [angular/protractor#3489]
Hi there!

I have written e2e test case for different functionality for the application which is in [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) in which i have used [socket.io](http://socket.io). After user login i am connecting to socket server and if connection is successful then all test case are failing and giving different error for different test case and if socket is not connected then all test case works fine with no error.

what i think is this issue is because socket connection is remain open after connection to server is done and protractor is waiting to complete the angular process because of browser.ignoreSynchronization or browser.waitForAngular.

I have already asked my question on [stackoverflow](http://stackoverflow.com/questions/38930272/angular2-e2e-test-case-with-protractor-throwing-error) but i am not able to find any solution for it and because of it i am adding the same at here to know if some one also facing the same issue and found any solution for it or not.

**Comment by NickTomlin** [comment]
Hi there!

I'm sorry that you haven't found any answers, but your question is still better suited for StackOverflow or Gitter. 

If you find that your question is not receiving any answers, you may want to refine it by isolating your problem to a [minimal, complete, verifiable example](http://stackoverflow.com/help/mcve) or adding more detail.

Hopefully that makes sense, good luck! 😄 

Thanks!

**Comment by pstephenwille** [comment]
Same here.  The socket stays open and prevents NG2 tests from ever running.  I can use...
`        browser.waitForAngularEnabled(false);
        browser.wait`

...but I need to find the correct way to accommodate web sockets in the tests.

**Comment by demonintherough** [comment]
So i just wanted to reference a solution found on a different issue which solves this issue here: https://github.com/angular/angular/issues/11853#issuecomment-277185526.
