### ISSUE TITLE
Bundled Protractor Binary Not Working in 4.0.3

### ISSUE THREAD

**Issue by joshmgrant** [angular/protractor#3495]
Using a Windows 10 machine with Node v4.4.4, I recently updated our Protractor test project from protractor v3.3.0 to v4.0.3. Now, when I run a globally installed instance of protractor

```bash
protractor my.conf.js
```
everything works as before. When I run the protractor binary installed as part of the project

```bash
cd myproj
npm install
my_project/node_modules/.bin/protractor my.conf.js 
```
I get strange behaviour. Either the test run crashes with an error 100 or all tests pass but run nearly instantly and protractor finishes with an error 100. ![protractor_issue](https://cloud.githubusercontent.com/assets/702729/17943508/b3207c5e-6a09-11e6-81b3-ac66f321d176.PNG) 

Both protractor binaries are v4.0.3.

This behaviour did not happen with protractor v3.3.0. This occurs when using Chrome and running against an instance either on a Selenium Grid or a local instance.

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
