### ISSUE TITLE
 optional class members in protractor using typescript

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3500]
Optional class members were introduced in `TypeScript 2.0` as a result older typescript `versions(1.8)` using new `Protractor 4.0.4` version would throw an compilation error : 
```
node_modules/protractor/built/index.d.ts(516,13): error TS1112: A class member cannot be declared optional.
```
due to this declaration in `index.d.ts` : 

![screen shot 2016-08-27 at 9 32 33 pm](https://cloud.githubusercontent.com/assets/15998104/18028470/00d3cf96-6c9e-11e6-83d8-b1ba73a578fa.png)

Suggestions:

* Either officially support protractor with typescript 2.0  'or'
* Switch to Interfaces having optional members rather than classes which would promote backward compatibility.

Any thoughts?

**Comment by cnishina** [comment]
This has been addressed. Resulting index.d.ts:

```
export  class ElementArrayFinder extends WebdriverWebElement {
    browser_: ProtractorBrowser;
    getWebElements: () => promise.Promise<WebElement[]>;
    locator_: any;
    actionResults_: promise.Promise<any>;
    constructor(browser_: ProtractorBrowser, getWebElements?: () => promise.Promise<WebElement[]>, locator_?: any, actionResults_?: promise.Promise<any>);
```
