### ISSUE TITLE
Multiple uses of browser.pause() cause protractor to exit

### ISSUE THREAD

**Issue by mgiambalvo** [angular/protractor#3501]
For example, if we add two browser.pause() statements to the following test

```
  fit('should wait to grab the WebElement until a method is called', function() {
    // These should throw no error before a page is loaded.
    var usernameInput = element(by.model('username'));
    var name = element(by.binding('username'));

    browser.get('index.html#/form');

    expect(name.getText()).toEqual('Anon');

    browser.pause();
    usernameInput.clear();
    usernameInput.sendKeys('Jane');
    browser.pause();
    expect(name.getText()).toEqual('Jane');
  });
```

If we run the test and then either step through or exit the debugger, protractor exits claiming that the debug port is already in use. This is because the debug process is still running.

Protractor should ignore browser.pause() calls if the debugger is already running. It should also wait for the previous browser process to exit before trying to start a new one. Unfortunately, I don't know how to distinguish between the debugger stepping over a browser.pause() call manually.

**Comment by igniteram** [comment]
+1 , I observed the same issue sometime while ago but ignored it by changing the port no. in the second  pause `browser.pause(5959);`  as 5858 is the default port, It would be a good feature to use the same port again!

**Comment by mgiambalvo** [comment]
I do have a fix for this, I'll be putting out a PR soon.
