### ISSUE TITLE
TypeScript/Typings: Locator interface is missing the "value" property

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#3508]
Hi there,

Looks like in Protractor 4.0.4, the [`Locator` interface](https://github.com/angular/protractor/blob/b627efd1b4869417009195b12f2302c51c82da68/lib/locators.ts#L20) is missing the public `value: string` property, which [is available](https://github.com/SeleniumHQ/selenium/blob/c10e8a955883f004452cdde18096d70738397788/javascript/node/selenium-webdriver/lib/by.js#L126) on every `webdriver.By`. Probably just an accidental omission?

Thanks,
Jan

**Comment by cnishina** [comment]
Currently the `Locator` interface is not the same as the webdriver.By object. Therefore there should not be a `value: string` on `Locator`.

**Comment by jan-molak** [comment]
Thanks for the quick reply @cnishina, that's interesting!

When the `Locator` object is derived from a `webdriver.By`, [it has a value](https://github.com/angular/protractor/blob/b627efd1b4869417009195b12f2302c51c82da68/lib/locators.ts#L5) (which is missing from the interface, so in the worst case it probably should be defined as optional perhaps?):

```typescript
// Explicitly define webdriver.By.
export class WebdriverBy {
  className: (className: string) => Locator = webdriver.By.className;
  css: (css: string) => Locator = webdriver.By.css;
  id: (id: string) => Locator = webdriver.By.id;
  linkText: (linkText: string) => Locator = webdriver.By.linkText;
  js: (js: string) => Locator = webdriver.By.js;
  name: (name: string) => Locator = webdriver.By.name;
  partialLinkText:
      (partialText: string) => Locator = webdriver.By.partialLinkText;
  tagName: (tagName: string) => Locator = webdriver.By.tagName;
  xpath: (xpath: string) => Locator = webdriver.By.xpath;
```

And when a locator is one of the [anonymous products](https://github.com/angular/protractor/blob/b627efd1b4869417009195b12f2302c51c82da68/lib/locators.ts#L187) of the `ProtractorBy`:

```typescript
  model(model: string): Locator {
    return {
      findElementsOverride: function(driver, using, rootSelector) {
        return driver.findElements(webdriver.By.js(
            clientSideScripts.findByModel, model, using, rootSelector));
      },
      toString: function toString() { return 'by.model("' + model + '")'; }
    };
  };
```

it _could_ also have a value, since it's really just using webdriver.By.js under the hood.

Is there any reason why:
- the `Locator` interface could not define an optional `value` property?
- the anonymous protractor locator could not be compatible with webdriver locator in terms of the public API, for example `value` and `using` properties?

Thanks for your time!
J
