### ISSUE TITLE
Question -  Working with typescript

### ISSUE THREAD

**Issue by Martin-Andersen** [angular/protractor#3514]
As I understand it you have added support for typescript since version 4.0

But before version 4.0 there was *.d.ts files for protractor so what is new? I can see that you include a lot in the node packages folder, including ts examples and *.d.ts files.

Should I use the *.d.ts files in the node folder instead of what I can find using typing?
Sorry I am confused

**Comment by cnishina** [comment]
In version 4, the package.json uses the typings field. The d.ts file did exist prior to version 4 but not all the APIs were supported. Please see the exampleTypescript folder for an example
