### ISSUE TITLE
Css selector $ conflicting jQuery selector

### ISSUE THREAD

**Issue by rafakwolf** [angular/protractor#3516]
Hi, the css selector " $ " on typings for protractor is conflicting with the " $ " on jQuery typings , any solution ??

**Comment by cnishina** [comment]
Take a look at the noGlobals option for your config. That should solve your jQuery issue. Please ask support questions on Gitter. Thanks!

**Comment by rafakwolf** [comment]
@cnishina  Questions on Gitter are no answered, but ok, i'll try "noGlobals".
Thanks
