### ISSUE TITLE
A suddenly error!

### ISSUE THREAD

**Issue by fancyhejianyang** [angular/protractor#3521]
Hi there!
recently I has found a error with run protractor.
the files in dir-specs run test ok one by one ,but if it works like below will wrong.
protractor-config.js
exports.config={
  specs:[
 'e2e/testjs/*.js'
]
}
in the case,when the file which name start with 'T' will stop and page does not close utill I rename the filename does not inclue 'T' letter.
- Node Version: `4.2.6`
- Protractor Version: `1.0.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows_NT 6.1.7601`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---
for replay

**Comment by fancyhejianyang** [comment]
[chrome #2] PID: 34348
[chrome #2] (node) util.puts is deprecated. Use console.log instead.
[chrome #2] Starting selenium standalone server...
[chrome #2] Selenium standalone server started at http://10.43.153.29:4467/wd/hub
[chrome #2] .........F.F.........TypeError: first._onTimeout is not a function
[chrome #2]     at Timer.listOnTimeout (timers.js:92:15)

**Comment by fancyhejianyang** [comment]
[chrome #2] PID: 34348
[chrome #2] (node) util.puts is deprecated. Use console.log instead.
[chrome #2] Starting selenium standalone server...
[chrome #2] Selenium standalone server started at http://10.43.153.29:4467/wd/hub
[chrome #2] .........F.F.........TypeError: first._onTimeout is not a function
[chrome #2]     at Timer.listOnTimeout (timers.js:92:15)

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
