### ISSUE TITLE
Is troubleshoot flag still working?

### ISSUE THREAD

**Issue by alecxe** [angular/protractor#3522]
Apologize if there is an issue about that, but, according to my experiments `--troubleshoot` command-line argument or `troubleshoot` configuration option does not change the log level since protractor@3.2.1? (works in 3.2.1 but does not in 3.3.0 and 4) 

Could you please confirm if this is a bug, or am I missing something? Thanks so much!

**Comment by alecxe** [comment]
I think we've introduced a problem while migrating launcher.js to launcher.ts - see [how we called `log.set(config)` in launcher.js](https://github.com/angular/protractor/commit/47f54add20fd2084a309c332798561fa58a8395b#diff-ff5050d3c7f51fca90c4691a4599e852L109) and [missing it launcher.ts](https://github.com/angular/protractor/commit/47f54add20fd2084a309c332798561fa58a8395b#diff-3bc02f009455680daa7a67214c66ffd7R105).

**Comment by mgiambalvo** [comment]
Thanks for spotting that! I think you're right. We're about to do a release - I'll try to squeeze the fix for this in.

**Comment by alecxe** [comment]
@mgiambalvo thanks so much for a quick fix!
