### ISSUE TITLE
'types/node' dependancy breaking the build

### ISSUE THREAD

**Issue by oguzgelal** [angular/protractor#3529]
Hello,

We're using protractor in our project, but lately the build started to break because of the dependancy `types/node`, apparently its not in the npm registry anymore. Here is the actual message:

```
-npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'types/node' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'protractor'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.2.0-42-generic
npm ERR! command "/home/rof/.nvm/v0.10.32/bin/node" "/home/rof/.nvm/v0.10.32/bin/npm" "install"
npm ERR! cwd /home/rof/src/github.com/marketmuse/marketmuse-ui
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0
```
In our package.json, protractor appears like this:
```
"devDependencies": {
     ...
    "protractor": "latest",
     ...
  },
```
so we are using the latest version.

**Comment by oguzgelal** [comment]
Solved this by decreasing the version from `4.0.5` to `4.0.4`. 

The last version bump (from the release notes: `chore(release): Version bump and changelog for 4.0.5 (#3524)`) might have broken something.

**Comment by gumallett** [comment]
We also experienced this issue this morning and rolled back to 4.0.4.

**Comment by mgiambalvo** [comment]
Sorry about that! Protractor only supports Node 4 and higher. From your error, it looks like you're on Node 0.10.32. We recommend updating to Node 4 (the long-term supported version) or, if that's not possible, staying on Protractor 2. We'll be introducing more changes that break on earlier versions of Node over time, so you're likely to see more odd issues if you stay on an older Node version.

**Comment by gordonkeenan** [comment]
I am seeing this issue with Node v4.5.0. Can this be reopened?

**Comment by cnishina** [comment]
The changelog has been updated and also a hot fix will be out for this next week. This should be resolved soon.

**Comment by Galileo1** [comment]
Hey @cnishina , has this been fixed I am seeing the same error while upgrading protractor to v4.0.11 and node@ 4.5.0.

**Comment by mgiambalvo** [comment]
You're using an outdated version of NPM (1.4.28). We require npm v3 or higher, which supports organization packages like `@types/node`, which is the new way of installing type definitions using npm.
