### ISSUE TITLE
Reference Path not recognized in latest 4.0.5 version

### ISSUE THREAD

**Issue by igniteram** [angular/protractor#3533]
In the latest release @types have been included . but the reference path in `built/index.d.ts` is not correct which causes the below error on compiling -

```
error TS6053: File '/Users/pasalar/Documents/coding/testtypescript/node_modules/@types/node/index.d.ts' not found.
error TS6053: File '/Users/pasalar/Documents/coding/testtypescript/node_modules/@types/jasmine/index.d.ts' not found.
```

I fixed it by changing the reference path to- 

```
/// <reference path="../node_modules/@types/node/index.d.ts" />
/// <reference path="../node_modules/@types/jasmine/index.d.ts" />
```

**Comment by cnishina** [comment]
Yup, this is due to the non deterministic installation of node modules. This has been addressed in:

https://github.com/angular/protractor/pull/3520
