### ISSUE TITLE
Investigate Jasmine 2.5.x upgrade

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3541]
Protractor's upgrade to Jasmine 2.5 removed individual test logging (pass or fail) and stack traces.

Related: https://github.com/angular/jasminewd/issues/54

**Comment by juliemr** [comment]
Labeling as a bug because users of previous versions who upgrade to Jasmine 2.5 may see issues.

**Comment by juliemr** [comment]
Will be fixed by #2895, and users who update to latest will now see the right behavior. I think this is OK to close.
