### ISSUE TITLE
Comparability with typescript to in es6 mode

### ISSUE THREAD

**Issue by KrauseStefan** [angular/protractor#3545]
- Node Version: `6.5.0`
- Typescript: 2.0.2 RC
- Protractor Version: `4.0.7`
- Browser(s): `Chrome`
- Operating System and Version `Ubuntu-Gnome`
- Protractor configuration file: 
https://github.com/KrauseStefan/NavitasFitness/blob/protractor-issue/e2e/protractor.conf.ts
- typescript configuration file: 
https://github.com/KrauseStefan/NavitasFitness/blob/protractor-issue/e2e/tsconfig.json

- Output from running the test 
`node_modules/protractor/built/globals.d.ts(38,28): error TS2403: Subsequent variable declarations must have the same type.  Variable 'startsWith' must be of type 'boolean', but here has type 'Function'.`

- Steps to reproduce the bug
Run protractor in a typescript environment configured to output es6 code (which is what new version of node are built to run)

The line that is flagged with the error: `node_modules/protractor/built/globals.d.ts:38`

```typescript
declare interface String { startsWith: Function; }
```

The conflicting definition in the lib.es6.d.ts form Typescript 2.0.2 RC
```typescript
interface String {
  // ...
  startsWith(searchString: string, position?: number): boolean;
  // ...
}
```

I recommend just removing the typing since it should be provided by typescript if run in es6 mode or included from an es6 shim typing like https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/es6-shim

There is no need to put it in a global.d.ts file, It should be possible to import it from the `tsconfig.json` file and thereby not leak to users of protractor :)

As a work around I now use es5 as output, I see this as a minor issue

**Comment by juliemr** [comment]
This is being removed as part of https://github.com/angular/protractor/pull/3546

**Comment by cnishina** [comment]
Merged. Closing this issue.
