### ISSUE TITLE
Using C# with Selenium and Integrating Protractor to it 

### ISSUE THREAD

**Issue by RasikaShete** [angular/protractor#3552]
Hi there!
My issue might be simple for u all , but since I am a beginner , I am using C# with Selenium and integrated the Protractor package to it .

Please find the below Angularjs code , I am trying to locate the button , but the "By " provides Selenium locators and "NgBy" provides Protractor locators , and these are very limited , I am not able to use NgBy.PartialButtonText in this.

When I used the same in pure Protractor +JavaScript I was able to do it , but the demand here is with C# and with C# it's not working , can anyone help  

Angular js code:
<button data-ng-click="vm.cancelInterval();navigate('/home/solutions/create')" class="btn-default ng-binding">+ Create new Solution</button>

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
