### ISSUE TITLE
Firefox test not running with v48

### ISSUE THREAD

**Issue by NewWorldAnks** [angular/protractor#3556]
Hi,

Can someone please provide an update if protractor is updated to include marionette driver? I heard that Selenium 3 have addressed this issue but not sure when this will be packaged? I am looking for a sample Conf.js which uses marionette driver but not able to find one. Can someone please provide an update on this?
Error('Timed out waiting for the WebDriver server at ' + url));                                                                    
          ^                                                                                                                                  
Error: Timed out waiting for the WebDriver server at http://127.0.0.1:50571/hub                                                              
    at Error (native)                                                                                                                        
    at onError (/Users/akuchhal/Sandbox/Demo/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:83:11)             

Node Version: v6.5
Firefox version: v48.01
protractor version: c4.0.7

**Comment by cnishina** [comment]
We are aware of the issue around Firefox 48. Please use Firefox 47.0.1.

**Comment by NewWorldAnks** [comment]
Do we know when it will be resolved? My project requirements want me to test in latest browser?

**Comment by mgiambalvo** [comment]
Protractor does include the marionette driver, but you need to specify it in your capabilities. Add "marionette: true" and you should be fine. Also, you'll need to make sure webdriver-manager is using the latest geckodriver. It doesn't autoupdate yet, so you'll probably need to check that you're downloading the latest version (0.10.0 as of this post). See [the webdriver-manager issue](https://github.com/angular/webdriver-manager/issues/52) for more details.

**Comment by mgiambalvo** [comment]
See also #3626. Going to close this since there's nothing we can do about it for now. We'll revisit when [FF 50](https://developer.mozilla.org/en-US/Firefox/Releases/50) ships.
