### ISSUE TITLE
documentation - is typings.json missing?

### ISSUE THREAD

**Issue by skywalker5727** [angular/protractor#3561]
Bug report
---

I am looking in protractor/exampleTypescript and do not see a typings.json file.  I think there used to be one, and the ReadMe below references it a few times.  Has it been removed by mistake?

**Comment by juliemr** [comment]
This is due to the update to TS 2.0 - I'll update the README.

**Comment by juliemr** [comment]
See https://github.com/angular/protractor/pull/3562

**Comment by juliemr** [comment]
Docs fixed with 3562
