### ISSUE TITLE
TypeScript changes - change the `protractor/globals` import to just `protractor`

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#3564]
As discussed offline:

To simplify the story for TypeScript users and eliminate confusion about globals, export global singletons from `protractor` instead of `protractor/globals`.

Before:

```ts
import {browser, element} from 'protractor/globals';
import {ElementFinder} from 'protractor';

describe('my app', () => {
  myElement: ElementFinder;

  beforeEach(() => {
    browser.get('example.com');
    myElement = element(by.css('foo'));
  });
});
``` 

After

```ts
import {browser, element, ElementFinder} from 'protractor';

describe('my app', () => {
  myElement: ElementFinder;

  beforeEach(() => {
    browser.get('example.com');
    myElement = element(by.css('foo'));
  });
});
``` 

The configuration option `noGlobals` will continue to do the same thing - if `true`, Protractor will only define `global.protractor`, otherwise, it will define all of `global.protractor, global.browser, global.element, global.by, global.$, global.$$`. Whether it is enabled or not should have no effect on TS users.

**Comment by thorn0** [comment]
Why not make `browser`, `element`, etc global in TS as well?

**Comment by Harshaec021** [comment]
@thorn0 I think you can do so by using typings. I mean by installing type script definitons

**Comment by djom20** [comment]
Hi @juliemr, I'd like to know how I can define those globals vars on protractor with typescript, do you have any guide fo that? since right now I'm facing this issue: `[ts] Property 'appId' does not exist on type 'Global'. [2339]`

My code:
`global.appId = null`
