### ISSUE TITLE
Hover with anchor tag is not persisted.

### ISSUE THREAD

**Issue by csanthoshi** [angular/protractor#3566]
When I try to hover a hyperlink- ( anchor tag ) through automation using protractor in Chrome, I observed that hovering is not persisted. I can see the mouse over event but then it immediately stops and  it is not waiting until the next action to perform because after hovering I need to verify a tool tip. As mouse over is not waiting for the next action, as a result I can not able to verify the tool tip. I can able to click the anchor tag but facing issue with hovering.

The code snippet that I used is

browser.sleep( 5000 );
var ele = element( by.xpath( '//tf-infobox//[normalize-space(.)="Error 1"]/following-sibling:://a' ) );
browser.actions().mouseMove( ele ).perform();
browser.sleep( 5000 );

Node Version: 4.2.2
Protractor Version: 2.14
Chrome Version: 52.0
Chrome driver version: 2.21

Additional Info: Hovering issue is seen only for hyperlink - anchor tag but not for the other elements.

Can someone help me out to solve my problem.

Thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
