### ISSUE TITLE
Using Protractor with angular2 reactive forms

### ISSUE THREAD

**Issue by abhibly** [angular/protractor#3567]
Hello.How can i use Protractor with Reactive Forms in angular2? I have a form control something like this 
```
input type="text" [formControl]="name" />
```
 How can i use this with protractor?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by abhibly** [comment]
@NickTomlin I just wanted to know whether protractor works with Reactive Forms? I have already asked a question on StackOverFlow,and i didn't get any answer,so i wanted to know whether protractor supports Forms presently or not from you guys... Thanks

**Comment by abhibly** [comment]
Not yet. Currently we have not writing tests for our app
