### ISSUE TITLE
GeckoDriver support for protractor to execute latest FF versions

### ISSUE THREAD

**Issue by prashanth-sams** [angular/protractor#3568]
As we know, `Selenium Webdriver 2.53.1` is limited to `Firefox browser 45|46` and its below versions.

Selenium 3 was launched by removing entire `Selenium RC Core` along with additional support on latest browsers recently. It uses GeckoDriver to drive the latest Firefox browsers.

However, is there any implementation of Protractor to support the latest Selenium 3 and GeckoDriver driven tests to handle latest FF versions.

[![enter image description here][1]][1]

Does Protractor tests are limited to FF45|FF46?

When I launch `firefox 48.0.1` with `Selenium 2.53.1` through `browser.get("http://xyz.com")`, the browser is opened as usual but not the url as shown below,

      capabilities: {
        browserName: 'firefox',
      },

[![enter image description here][2]][2]

  [1]: http://i.stack.imgur.com/q5lU1.png
  [2]: http://i.stack.imgur.com/EkqwV.png

Note: As far as I know, the latest Firefox versions have inbuilt algorithms to handle GeckoDriver and selenium 3 APIs, cos, the FF terms are made strict to avoid external breaches. FF 47+ versions are Gecko-based browsers.

> Prashanth Sams
> The Author, Selenium Essentials

**Comment by cnishina** [comment]
duplicate issue. https://github.com/angular/protractor/issues/3556
