### ISSUE TITLE
  Message:     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.   Stack:     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.

### ISSUE THREAD

**Issue by prakash-mannikeri** [angular/protractor#3575]
//conf.js

exports.config = {
seleniumAddress: 'http://localhost:4444/wd/hub',
   specs:['spec.js'],
	useAllAngular2AppRoots: 'true',
	useAllAngular2AppRoots: 'true',
    autoWebview: 'true',
   ignoreSynchronization: 'true',
   jasmineNodeOpts: {
defaultTimeoutInterval: 2500000
}
};

//spec.js
describe('Receiving home page', function() {
 it('should enter manualInput ', function() {
      //browser.ignoreSynchronization = false;
 browser.get('http://localhost:8000/');
 console.log("start");
 //browser.waitForAngular();
 // browser.sleep(10000);
 browser.wait(function(){
       return browser.isElementPresent(by.xpath("//*[contains(@id,input-section)]/input"));
      
 }).then(function(){
      var input=element(by.xpath("//*[contains(@id,input-section)]/input"));
     if (browser.isElementPresent(input)) {
         input.sendKeys('98511111');
         //browser.findElement(by.className('btn-orange-background')).click();
         browser.wait(function() {
             return browser.isElementPresent(by.className('btn waves-effect waves-orange search-button'));
            }).then(function() {
                //var button = element(by.name('Enter'))
             var button= element(by.className('btn waves-effect waves-orange search-button'));
             if(browser.isElementPresent(button)){
                     button.click(); 
             browser.wait(function() {
                 return browser.isElementPresent(by.className('exclamatoryimage'));
                }).then(function() {
         }) ; 
     }
 
      
 });

 }
});
 });
});
beforeEach(() => {
   browser.ignoreSynchronization = true;
   jasmineNodeOpts: {
defaultTimeoutInterval: 2500000
}
});

afterEach(function () {
   console.log('after spec finished!\n');
   browser.ignoreSynchronization = true;
     jasmineNodeOpts: {
defaultTimeoutInterval: 2500000
}
});

Please help me to resolve this timeout error(Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.   Stack:     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL), I tried all the possibilities, please somebody help me here to fix this

**Comment by cnishina** [comment]
For timeouts, please see documentation: http://www.protractortest.org/#/timeouts.

Please use markdown: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code

Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by oujieying** [comment]
use jest to run test units.
i use setTimeout but got this error
`Error: Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.
      
      at node_modules/jest-jasmine2/build/queue_runner.js:72:21
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:592:19)
