### ISSUE TITLE
Console output is not captured with phantomJS driver

### ISSUE THREAD

**Issue by tprupsys** [angular/protractor#3576]
Hi,

So I have a test which is supposed to fail on my page (I can see error log when I open it manually):
```
return browser.manage().logs().get('browser').then(function(logs) {
            expect(logs.length).toBe(0);
});
```

When I run protractor with chrome, the test fails as supposed, but when I change the browserName to phantomjs - logs are not captured. What might be wrong?

Bug report
---
- Node Version: `5.4.1`
- Protractor Version: `4.0.8`
- Browser(s): `PhantomJS`
- Operating System and Version `OS X and Red Hat 6 (doesn't matter)`
- Your protractor configuration file

> browserName: 'phantomjs',
>         'phantomjs.binary.path': require('phantomjs').path,
>         'phantomjs.ghostdriver.cli.args': ['--debug=true', '--webdriver', '--webdriver-loglevel=SEVERE'],
>         version: '',
>         platform: 'ANY',
>         level: 'SEVERE',
>         loggingPrefs: {
>             browser: 'SEVERE'
>         },

- A relevant example test
```
return browser.manage().logs().get('browser').then(function(logs) {
   expect(logs.length).toBe(0);
});
```

- Output from running the test
Logs are empty, whereas when I set browserName to 'chrome' it's all fine, there are logs, just as expected

**Comment by juliemr** [comment]
We do not recommend using phantomjs, as there are a number of known cases where it doesn't perform like real browsers. See http://www.protractortest.org/#/browser-support.

I'll leave this open for a bit in case anyone familiar with phantomjs knows, though.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since we haven't had any activity on it and phantomjs is not recommended or officially supported.
