### ISSUE TITLE
by.repeater().column throws 'unknown error'

### ISSUE THREAD

**Issue by zalayeto** [angular/protractor#3579]
Hi,

Any reason why this code throws 'unknown error'? does column method work with object property iteration in a ng-repeat?

`.all( by.repeater('(rowRenderIndex, row) in rowContainer.renderedRows').column(  'row.entity.id'  ) )`

I'm using protractor 4.0.2 with Angular 1.5.7.

Thanks,

David.

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
