### ISSUE TITLE
sendKeys(K.ENTER) does not wait for ng-submit

### ISSUE THREAD

**Issue by darabos** [angular/protractor#3580]
- Node Version: `4.2.6`
- Protractor Version: `4.0.8`
- Browser: `Chrome 54`
- Operating System and Version `Ubuntu 16.04`
- Your protractor configuration file: `directConnect: true, chromeDriver: 'chromedriver_2.24'`

For a simple repro the HTML is like:

```
<form ng-submit="foo()">
  <input id="i">
</form>
```

Angular:

```
scope.foo = function() {
  $timeout(function() {}, 10000);
}
```

Protractor:

```
$('#i').sendKeys(K.ENTER); // Does not wait. (This is the bug.)
```

In a more realistic case the `ng-submit` has an effect, and the test expects the effect after `sendKeys(K.ENTER)`. Such a test will be flaky. Changing the test to use `$('#i').submit()` fixes the issue as `submit()` will correctly wait for `ng-submit`. But it would be great if the `sendKeys()` behavior could be fixed, as this is an easy mistake to make and annoying to debug.

**Comment by juliemr** [comment]
Very strange - could you share the version of Angular that you're using?

**Comment by darabos** [comment]
> Very strange - could you share the version of Angular that you're using?

Oh no! I did not think to upgrade Angular. We are on 1.4.4. I will try with 1.5.8 and report back. Thanks.

**Comment by juliemr** [comment]
Both Angular versions should work. We'll take a look.

**Comment by juliemr** [comment]
Hmm, possibly related to https://github.com/angular/protractor/issues/3456

**Comment by juliemr** [comment]
I'm unable to reproduce this - I see the test wait properly with either `sendKeys(ENTER)` or `submit()`. @darabos could you set up a repository showing a minimal example? For reference, here's how I tested it: https://github.com/juliemr/protractor/commit/fa3b4a7fdd014b8c1c4e699ebf110bc2ca7a776a

**Comment by darabos** [comment]
> Oh no! I did not think to upgrade Angular. We are on 1.4.4. I will try with 1.5.8 and report back. Thanks.

I get the same with 1.5.8.

> I'm unable to reproduce this - I see the test wait properly with either `sendKeys(ENTER)` or `submit()`. @darabos could you set up a repository showing a minimal example? For reference, here's how I tested it: juliemr@fa3b4a7

I will try to create a minimal example. (Of course my repro is in the middle of a big application...) Thanks for the example example!

**Comment by darabos** [comment]
> I will try to create a minimal example. (Of course my repro is in the middle of a big application...) Thanks for the example example!

I'm failing pretty badly with a self-contained example so far. I have some partial results that may help.

My complex repro is not 100% sure. Around 10-20% of the time it does wait for the timeout. This makes experiments misleading sometimes.

My `<input>` has an `ng-model` attribute. Removing this seems to fix the issue. But if `ng-model` is present with any value, I get the issue. (So it seems not related to specific code for that scope variable.) Adding `ng-model` to your example does not reproduce the issue.

`sendKeys()` does not wait for the timeout. If I put `browser.pause()` as the next operation, the debugger starts before the timeout finishes. This is easy to reproduce in a minimal example. But I guess this is not a problem? `getText()` is supposed to wait for the timeout?

Actually if I use `getText()` on some element after `sendKeys()` the issue goes away. But with the actual test I get the issue:

    expect($('#foo').isPresent()).toBe(false);

This test just fails right away, without waiting for the timeout. But doing the same thing in the minimal example still does not reproduce the issue.

My mental model now is that since `sendKeys()` does not wait, it is possible that the next operation starts before the timeout is even registered. Then this second step has no reason to wait. How this race turns out is influenced by the state of the universe (e.g. `ng-model`, `isPresent()` vs `getText()`). If this mental model is correct, it is mostly a waste of time mapping out the exact conditions which influence the race, and `sendKeys()` should just be made to wait before continuing to the next operation. It is just an uneducated guess of course. If it does not hold any merit, I will try again with the repro tomorrow.

**Comment by juliemr** [comment]
`sendKeys` doesn't wait for the timeout because it causes it, but the next operation generally should. (You're right that `browser.pause` won't, because we want to get you debugging ASAP, but other operations on an ElementFinder like the next `getText` and `isPresent` will). So, in our model, the onus of waiting is not on what causes the action, but on the next thing that responds to it. 

I have no idea why ng-model would affect this - that's on the browser side. So having a repro would still be helpful.

Thanks for the update!

**Comment by juliemr** [comment]
I'm cleaning up older issues and closing this as I haven't heard back - please open a new issue if find a repro. Thanks!
