### ISSUE TITLE
clean up: repetitive code in index.ts and ptor.ts

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3585]
Due to https://github.com/angular/protractor/pull/3583

**Comment by juliemr** [comment]
Further detail - a lot of this is due to preserving the old behavior for the small set of users who are using `require(protractor)`. We will probably release a breaking change at some point that rethinks exactly what is exported there, and brings it in line with TypeScript.

**Comment by sjelin** [comment]
Should this be in the beta branch?

**Comment by cnishina** [comment]
## Item to fix:

```
export let utils = {
  firefox: require('selenium-webdriver/firefox'),
  http: require('selenium-webdriver/http'),
  remote: require('selenium-webdriver/remote')
};

export let Command = require('selenium-webdriver/lib/command').Command;
export let CommandName = require('selenium-webdriver/lib/command').Name;
```

Maybe this should be:
```
export let utils = Ptor.utils;
export let Command = Ptor.Command;
export let CommandName = Ptor.CommandName;
```

## Why we are currently exporting items twice

I needed to remind myself why we exported at index.ts and also at ptor. Requiring protractor in JavaScript and importing the object protractor in TypeScript are different. In this situation, the definition of 'Key' is on lib/index.ts:

```
var protractor = require('protractor');
var browser = protractor.browser;
browser.sendKeys(protractor.Key.BACK_SPACE);
```

```
import * as protractor from 'protractor';
let browser = protractor.browser;
browser.sendKeys(protractor.Key.BACK_SPACE);
```

Key also exists on the global protractor object (defined in lib/ptor.ts):
```
var protractor = require('protractor').protractor;
var browser = require('protractor').browser;
browser.sendKeys(protractor.Key.BACK_SPACE);
```
```
import {browser, protractor} from 'protractor';
browser.sendKeys(protractor.Key.BACK_SPACE);

```

## Possibly a reason to change this:

We should export selenium types once under Ptor.

- This would provide a single place for maintenance.
- Provide a single way to get to exported selenium-webdriver definitions

So if we decide to reduce the number of places we export selenium-webdriver, we should consider it a breaking change and do this in the beta branch.

**Comment by cnishina** [comment]
Looking at this again. utils = Ptor.utils won't work since it is not static.

Also, per in person discussion with Julie, removing stuff from index.ts will cause issues for JavaScript users and we should not do this.
