### ISSUE TITLE
Unable to click the links which are associated with $timeout

### ISSUE THREAD

**Issue by Shivaraj05** [angular/protractor#3586]
Hi,

I am trying to click a link which is associated with $timeout, which will be displayed only for few seconds. After clicking navigate to the new page and verify some text.

But as i went through https://github.com/angular/protractor/issues/169 , it says protractor waits for $timeout to finish. So can anyone help me to resolve this issue.

And the following information tells about the version i am using,
Bug report
- Node Version: `6.2.0`
- Protractor Version: `4.0.7`
- Browser(s): Chrome
- Operating System and Version : Ubuntu

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by Shivaraj05** [comment]
Hi,

I have checked StackOverflow or Gitter, but there are no any clear answers for this.

So please can you take this as a new requirement. Because there are scenarios where we need to have e2e tests for validating broadcasting many events after clicking some link which is visible only for few seconds.

And people have suggested for browser.ignoreSynchronization = true; But this doesn't work when we have scenarios as mentioned above.

So i think, this feature can add some good value to Protractor.

**Comment by NickTomlin** [comment]
@Shivaraj05 this still seems like a usage/debugging issue. If this is a feature request, please open up a new issue with an example use case (a repository would be very helpful!), otherwise it's difficult to understand what actually needs to be done.

Thanks!

**Comment by Shivaraj05** [comment]
Ok, i will create a issue with the actual scenario.
