### ISSUE TITLE
Protractor can't find an element which can be easily found by Chrome

### ISSUE THREAD

**Issue by kotvertolet** [angular/protractor#3587]
I have a strange issue, there is an element that can be found by css and xpath locators in chrome:
http://prntscr.com/ck5t70
http://prntscr.com/ck5tqb
but it doesn't work with protractor:
```
this.ui.contactsList = $(by.xpath("//div[@class='list-group ng-scope']"));
this.ui.contactsList = $("div.list-group");
```
Output:

> NoSuchElementError: No element found using locator: By(xpath, //div[@class='list-group ng-scope'])
> NoSuchElementError: No element found using locator: By(css selector, div.list-group)

**Comment by Shivaraj05** [comment]
Can you please check is it in some iframe, if so then you need to switch to iframe and then perform actions.

**Comment by kotvertolet** [comment]
There is no iframe on the page

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
