### ISSUE TITLE
Protractor is not able to handle broadcast events and the clicking operation for elements with $timeout

### ISSUE THREAD

**Issue by Shivaraj05** [angular/protractor#3589]
Hi,

Please consider the below sample scenario,

1)  Fill the fields and submit some form, which will broadcast multiple events like 
     * status message link, which is attached with $timeout and visible for only few seconds
     * a new message gets added to the message list in different widget
2)  Next when you click the status message link, then it should open the message as pop up with details

So when we are trying to automate the scenario, we are able to submit the form. But when we are trying to click the status message link, we need to have browser.ignoreSynchronization = true; because link is attached to $timeout. 

The link is clickable, but a message opening as a pop up is not working.

When i checked in Stackoverflow and some google answers, i got to know that it is because of the $timeout. So i checked by removing $timeout for element, now it works properly.

So my request is everytime we cant have a element without $timeout. So please consider the above scenario and have a new feature where protractor can ignore waiting for $timeout.

**Comment by juliemr** [comment]
You've pretty much found it, you want to set `ignoreSynchronization = true` for cases like this. We would like to improve ease of use and docs around that, see https://github.com/angular/protractor/issues/1939
