### ISSUE TITLE
Retrieving Label values to verify text later

### ISSUE THREAD

**Issue by mohit-excelindia** [angular/protractor#359]
Hi All,

I have some problem in verifying the text and values of labels and text fields.
I know value of a label can be retrieved using following

prot.findElement(By.id('element')).getText().then(function(text){
console.log(text)
});

but if I tries to access the value retrieved outside the promise, then I am not able to do this.
Is there a way I can access the value of the text outside the promise function and use the retrieved value to verify or assert with some other values??

Thanks

**Comment by reddynr** [comment]
Hi All,

I am using protractor trying to capture a label value from html page  shows null . Please advice. Thanks

error :Expected null to equal 'xyz'.

Code :         element(by.binding('ctrl.formData.branchAddressLine1')).getAttribute('value').then(function (value) {
            expect(value).toEqual('xyz');
        });
