### ISSUE TITLE
Tab key shows node commands instead of protractor commands

### ISSUE THREAD

**Issue by ajklotz** [angular/protractor#3594]
## Bug report
- Node Version: `v6.6.0`
- Protractor Version: `4.0.2`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10 Pro`
- Steps to reproduce

`1. Have Selenium Server running somewhere`
`2. Launch elementExplorer via CLI: protractor --elementExplorer --baseUrl http://someserver/site`
`3. Press the tab key to see a list of locator strategies.`
`4. Observe that the output displays`
- Notes

`This problem seems to have started when I upgrade to NodeJS 6.6.0 from v5.`

**Comment by NickTomlin** [comment]
Interesting; i'm not quite sure this is something under our control (I don't use this functionality or windows though). Can you clarify what you mean by "list of locator strategies"? 

Also, have you installed any autocomplete functionality into the shell you are using? (Are you using powershell, git bash, or something else?)

**Comment by ajklotz** [comment]
Hey Nick, when I launch protractor with the elementorExplorer option, the console window outputs some help information about how to use elementExplorer. Here is the output after launching elementExplorer:

> C:\project\Test\protractor\tools>protractor --elementExplorer --baseUrl http://server/site
> [09:00:41] I/local - Starting selenium standalone server...
> [09:00:43] I/local - Selenium standalone server started at http://xxx.xxx.xxx.xx:xxxx/wd/hub
> [09:01:05] I/protractor -
> [09:01:05] I/protractor - ------- Element Explorer -------
> [09:01:05] I/protractor - Starting WebDriver debugger in a child process. Element Explorer is still beta, please report issues at github.com/angular/protractor
> [09:01:05] I/protractor -
> [09:01:06] I/protractor - **Type <tab> to see a list of locator strategies**.
> [09:01:06] I/protractor - Use the list helper function to find elements by strategy:
> [09:01:06] I/protractor -   e.g., list(by.binding('')) gets all bindings.
> [09:01:06] I/protractor -
> Starting debugger agent.
> Debugger listening on [::]:5858

**Comment by mgiambalvo** [comment]
Julie is redoing the debugger for Selenium 3.0 (which also handles the upgrade to Node v6). This may no longer be relevant.

**Comment by juliemr** [comment]
Right, this should be fixed after https://github.com/angular/protractor/pull/3828

**Comment by NickTomlin** [comment]
I believe this was fixed by https://github.com/angular/protractor/commit/cb38ed0a8aae2cb862001e0b6f076aa9972f4489 going to go ahead and close
