### ISSUE TITLE
Exception [This driver instance does not have a valid session ID] Thrown After Browser.Restart() OR RestartBrowserBetweenTests Protractor

### ISSUE THREAD

**Issue by bhreinb** [angular/protractor#3595]
Hi There,

I came across this github link 

https://github.com/angular/protractor/issues/2001

I see it was closed three days ago. It is to do with using protractor again after a "browser.restart()" in an after hook step (cucumber js) or setting "restartBrowserBetweenTests: true" in protractor config. I have upgraded to the latest protractor instance v4.0.9 and it's still not fixed unfortunately. Btw I'm using cucumberjs as my test framework.

Been able to restart the browser is an important piece of functionality especially in the context after a scenario failure (as the previous test scenario failure could leave the browser in a unknown state thus meaning any remaining test scenarios won't run all that well after the failed scenario). Given that context I would be using "browser.restart()" more so than "restartBrowserBetweenTests: true" as it isn't a necessity for me to restart the browser after each scenario only in the case of a failure. In any case both ways throw the exception below

Bug report
---

- Node Version: `v5.4.1`
- Protractor Version: `v4.0.9`
- Angular Version: `v1.5.7`
- Browser(s): `IE, CHROME & FIREFOX`
- Operating System and Version `WIN7 Enterprise SP1`

` Step Definition: StepDefinitions\Background_steps.js:13
   Message:
     NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
         at WebDriverError (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:26:26)
         at NoSuchSessionError (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:169:26)
         at checkHasNotQuit (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:395:15)
         at WebDriver.schedule (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:356:5)
         at ProtractorBrowser.executeAsyncScript_ (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\browser.js:236:28)
         at runWaitForAngularScript (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\browser.js:264:30)
         at ProtractorBrowser.waitForAngular (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\browser.js:270:16)
         at ElementArrayFinder.getWebElements (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\element.js:155:29)
         at ElementArrayFinder.ElementFinder.getWebElements (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\element.js:717:39)
         at ElementArrayFinder.applyAction_ (C:\Users\bxb145\WebstormProjects\System_Test_Project\node_modules\protractor\built\element.js:407:34)`

I will update this when i get a minimal set of steps to reproduce this use case.

#https://github.com/angular/protractor/commit/3844eadaa1bba19d08133d613574c4fa730d1976

**Comment by bhreinb** [comment]
Apologies this is not a protractor issue but rather was an issue to how I'm using a page object pattern with protractor. This is no longer an issue and can be closed. Sorry for the bother :+1:

**Comment by randy5235** [comment]
@bhreinb do you think you could provide a bit more details, I am facing a similar issue using protractor 4.0.14 and node 6.9.1 on osx El Capitan. I suspect it may just be an issue in my end.v

**Comment by bhreinb** [comment]
Hey @randy5235 

Sorry about the delay responding. Are you using a page object model to store controls etc?

For me the problem was using a stale control on the page (as it was no longer valid after a browser restart). Typically, I'd restart a browser after a failed test scenario. So basically I followed a pattern as per this sample project https://github.com/qualityshepherd/protractor-example

I implemented a base page like this 
https://github.com/qualityshepherd/protractor-example/blob/master/pages/basePage.js

and each page derived from the base page just like in this example
https://github.com/qualityshepherd/protractor-example/blob/master/pages/friendPage.js

I put common controls that were accessible from **_every page_** in the base page. All pages are initialised within the world object. The world object is a cucumberJs specific (not sure you are using that).

However, the way the page object model is done in that sample doesn't support having common controls in the base page. Namely, this code block is only executed once

`FriendsPage.prototype = basePage;`
`module.exports = new FriendsPage();`

hence after a restart and when protractor comes around to use that control that is declared in the base page (it crashes as the control is stale) in that it's using an old driver instance.

So I changed the way I extend the base page and put it in the world file and now it is like so

 FriendsPage.__proto__ = new (require('../PageObject/Base_Page.js'));

this is what should exist in the page object from now on
module.exports = FriendsPage;

Hope all of the above makes sense & all the best.

**Comment by SamFarrington** [comment]
Thanks for posting that explanation!

Having similar issues and after reading the above comment I managed to work around them.

Long story short it's a case of need to re-initialise page-objects after restarting the browser :smiley:

**Comment by bhreinb** [comment]
Hey no bother your very welcome. Glad to help :+1:

**Comment by schwarcu** [comment]
How do I re-initialise page-objects after restarting browser????

**Comment by bhreinb** [comment]
using this snippet of code

`FriendsPage.proto = new (require('../PageObject/Base_Page.js'));`

although the above explanation refers more so reinitializing the base page which is inherited by each page object.
