### ISSUE TITLE
Webdriver-manager doesn't pick up latest chromedriver jar; only updates up to v2.22

### ISSUE THREAD

**Issue by Joel-fogue** [angular/protractor#3598]
Bug report
---

- Node Version: `v4.4.7`
- Protractor Version: `4.0.9`
- CucumberJs: `1.3.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`
- Steps to reproduce the bug

 To reproduce this bug, just try to update your chromedriver to latest version by running: `webdriver-manager update` OR `webdriver-manager update --chrome`  and you'll notice that it only updates the chromedriver up to v2.22 instead of the latest which is chromedriver v2.24

Thanks for looking into this!

**Comment by NickTomlin** [comment]
The latest Webdriver-manager `10.2.3`is still pointing to [`2.2.3`](https://github.com/angular/webdriver-manager/blob/10.2.3/config.json#L4). 
You can specify a chrome version with the `--versions.chrome` flag. I'm going to go ahead and close this issue. Feel free to open another issue at the webdriver manager repo.

**Comment by Joel-fogue** [comment]
@NickTomlin Did you mean to say that the latest webdriver-manager is still pointing to `2.22` and not `2.23` right?
And I tried running this command to avail: `webdriver-manager install --version.chrome 2.24`

_**Could you please write out the full command that gets you to install chromedriver v2.24?**_

**Comment by NickTomlin** [comment]
@Joel-fogue I think you've mispelled the command it's  `versions.chrome` not `version.chrome` e.g.`webdriver-manager update --versions.chrome 2.24`

**Comment by Joel-fogue** [comment]
@NickTomlin Beautiful, my fault! Thanks
