### ISSUE TITLE
Exception while execution example_spec.js

### ISSUE THREAD

**Issue by rmallela** [angular/protractor#3599]
Hi I am trying to run the default example: 
C:\Users\rmallela\AppData\Roaming\npm\node_modules\protractor\example>protractor conf.js
I see the exception : [11852:6504:0925/194546:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
Given details below: 

- Node Version: `v4.5.0`
- Protractor Version: `Version 4.0.9`
- Browser(s): `chrome and firefox`
- Operating System and Version `windows 7 Enterprise`
- Your protractor configuration file : 

```javascript
//C:\Users\rmallela\AppData\Roaming\npm\node_modules\protractor\example\conf.js
// An example configuration file.
exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Framework to use. Jasmine is recommended.
  framework: 'jasmine',

  // Spec patterns are relative to the current working directory when
  // protractor is called.
  specs: ['example_spec.js'],

  // Options to be passed to Jasmine.
  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }
};
``` 
- Output from running the test : 

```
C:\Users\rmallela\AppData\Roaming\npm\node_modules\protractor\example>protractor conf.js
[19:45:38] I/direct - Using ChromeDriver directly...
[19:45:38] I/launcher - Running 1 instances of WebDriver
Started
[11852:6504:0925/194546:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194548:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
.[11852:6504:0925/194551:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194551:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194551:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194551:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
.[11852:6504:0925/194552:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194552:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101
[11852:6504:0925/194553:ERROR:ssl_client_socket_impl.cc(1141)] handshake failed; returned -1, SSL error code 1, net_error -101

3 specs, 0 failures
Finished in 14.269 seconds

[19:45:54] I/launcher - 0 instance(s) of WebDriver still running
[19:45:54] I/launcher - chrome #01 passed
```

- Steps to reproduce the bug :
 `run #C:\Users\rmallela\AppData\Roaming\npm\node_modules\protractor\example>protractor conf.js`

- The URL you are running your tests against (if relevant): `http://www.angularjs.org`

**Comment by NickTomlin** [comment]
I am not seeing this on windows 7 using the latest protractor. My guess is that this is due to something environmental. 

Because it will require troubleshooting and fixes that are probably particular to your environment, your question is better suited to  StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by SimonSchick** [comment]
Hey @rmallela I'm having the same issue, did you ever find the source of the problem?

**Comment by rekhubs** [comment]
I had the same issue, after searching around, I read somewhere says, `ng e2e` is using `serve` options in `angular.json`, so here's how I fixed it in my environment:
1. make sure `ng serve --ssl` work, app can be served with https;
2. set `ssl` as `true` in `angular.json` `serve` options:

```
"serve": {
          "options": {
            "browserTarget": "frontend:build",
            "proxyConfig": "proxy-conf.json",
            "ssl": true
          },
    .....
        },
```
