### ISSUE TITLE
Test on Android Native App(calculator) with Protractor throwing "WebDriverError: Method has not yet been implemented" 

### ISSUE THREAD

**Issue by yatheeshAtzenq** [angular/protractor#3601]
Hi, 

i wanted to automate a native app(calculator app) on the android mobile using protractor, when tried with the following configuration i'm getting "WebDriverError: Method has not yet been implemented" after app got launched and closed. 

- Node Version: `v4.4.0`
- Protractor Version: `4.0.9`
- Operating System and Version `windows 7`

    exports.config = {
    seleniumAddress: 'http://localhost:4723/wd/hub',

    specs: ['spec.js'],
    capabilities:{
        'appium-version': '1.5.3',
         platformName: 'Android',
         platformVersion: '5.1.1',
         deviceName: 'Nexus 5',
         browserName: "android",         
         appPackage: 'com.android.calculator2',
         appActivity: '.Calculator',
         newCommandTimeout: 6000,        
         fulReset: true
    }
    onPrepare: function () {
        var wd = require('wd'),
            protractor = require('protractor'),
            wdBridge = require('wd-bridge')(protractor, wd);
        wdBridge.initFromProtractor(exports.config);
    }
    };

    it("",function(){
       element(by.id('com.android.calculator2:id/digit_7')).click();
        element(by.name('minus')).click();
        element(by.id('com.android.calculator2:id/digit_3')).click();
        element(by.name('equals')).click();
    });

Is there solution for this? Thank in advance.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by wswebcreation** [comment]
As far as I know Protractor can only automate Hybrid apps with a webview. Native apps without a webview are not possible because of the first async-call done by Protractor.

**Comment by yatheeshAtzenq** [comment]
Thank You

**Comment by aniket-21** [comment]
How about hybrid app, which starts with a native activity but has angular webview in next activities? Can we make protractor not inject javascript at start but wait till webview is switched to?

**Comment by joeskeen** [comment]
> Native apps without a webview are not possible because of the first async-call done by Protractor.

@wswebcreation could you please elaborate on this? I would like to understand this so that I can help contribute to #3699 as Appium support improves.

Also, what layer is the `'Method has not yet been implemented'` message coming from?  I do know that Appium supports native apps without a webview, so it would be great to find a way to make this work.
