### ISSUE TITLE
Does Protractor support Angular 2 ?

### ISSUE THREAD

**Issue by LeninChristopher** [angular/protractor#3602]
Hi ,

There are lot of changes i can see in angular 2 as compared to angular 1 
Eg. Angular 1 -  **element.all(by.repeater('post in posts'));**
but in Angular 2 the repeater has been replaced by - ***ngFor="#post in posts">** 

How to handle such scenarios .. do we need to wait for official Protractor complete support for angular 2 just like Angular 1

**Comment by NickTomlin** [comment]
Yes, with some caveats. From the [README](https://github.com/angular/protractor#compatibility)

> Protractor work with Angular versions greater than 1.0.6/1.1.4, and is compatible with Angular 2 applications. Note that for Angular 2 apps, the binding and model locators are not supported. We recommend using by.css.

If you need help testing an NG2 app please ask a question on Stackoverflow or Gitter.

Thanks!

**Comment by LeninChristopher** [comment]
Hi Nick.. Thanks for the response
Caveats ? so it wont support in all the scenarios ..any fixed date we can expect the perfect version of protractor to support binding & model.

**Comment by philjones88** [comment]
@NickTomlin 

This seems a real shame, moving pages to NG2 and all our tests are now dead. What E2E tool have people moved to with NG2 then?

Take for example this function we use, I have no idea if we can do anything like this with NG2:

```
    allByName: function (name) {
        return element.all(by.repeater('foo of foos'))
            .filter(function (elm) {
                return elm.evaluate('foo.name === "' + name + '"');
            });
    }
```

Is there a definitive list of what works and what doesn't? I suspect from what you said, `evaluate` won't work, how about `by.binding`?
