### ISSUE TITLE
TypeScript import statements after 4.0.9

### ISSUE THREAD

**Issue by christiandreher** [angular/protractor#3603]
Bug report
---

- Node Version: `6.3.1`
- Protractor Version: `4.0.9`
- Angular Version: `2.0.1`
- TypeScript: `2.0.3`
- Browser(s): `any`
- Operating System and Version: `Ubuntu 16.04`

I am using `angular-cli@1.0.0-beta.15`. I tried to update my dependencies, including protractor from `4.0.8` to `4.0.9`. I have read the changelog, that it is not possible anymore to inlcude from `protractor/globals`, and that one should use `protractor` instead.

**Version 4.0.8 (protractor/globals)**

```ts
import { browser, element, by, protractor } from 'protractor/globals';
```
Result: As expected, no error

**Version 4.0.9 (protractor/globals)**

```ts
import { browser, element, by, protractor } from 'protractor/globals';
```
Result: As expected, an error:

```
Error: Cannot find module 'protractor/globals'
```

**Version 4.0.9 (protractor)**

```ts
import { browser, element, by, protractor } from 'protractor`;
```
Result: Error, does not work. Output in terminal:

```
e2e/app.e2e-spec.ts (18,10): Module ''protractor'' has no exported member 'browser'. (2305)                                                                
e2e/app.e2e-spec.ts (18,19): Module ''protractor'' has no exported member 'element'. (2305)                                                                
e2e/app.e2e-spec.ts (18,28): Module ''protractor'' has no exported member 'by'. (2305)                                                                     
e2e/app.e2e-spec.ts (18,32): Module ''protractor'' has no exported member 'protractor'. (2305)
```

To get it to work, I had to do the following, which seems to be a rough hack:

**Version 4.0.9 (protractor/built)**

```ts
import { browser, element, by, protractor } from 'protractor/built`;
```
Result: No error, does work, however the output is kind of strange:

```
Spec started                                                                                                                                               
.
  app
    ✓ should load
.   ✓ should have ...
.    ✓ should do ...
.    ✓ should work ...
```

As you can see, there are some weird dots before some lines...

Here are some things that I've done and tried:

1.) Output of `ls -la ./node_modules/protractor/`:

```
me@my-machine:~/workspace/app$ ls -la ./node_modules/protractor/
total 232
drwxrwxr-x    7 me me   4096 Sep 27 00:16 .
drwxrwxr-x 1030 me me  36864 Sep 27 00:16 ..
drwxrwxr-x    2 me me   4096 Sep 27 00:16 bin
drwxrwxr-x    6 me me   4096 Sep 27 00:16 built
-rw-rw-r--    1 me me 139165 Sep 21 22:26 CHANGELOG.md
-rw-rw-r--    1 me me     72 Sep 21 22:26 .clang-format
-rw-rw-r--    1 me me   3469 Sep 21 22:26 CONTRIBUTING.md
drwxrwxr-x    2 me me   4096 Sep 27 00:16 example
drwxrwxr-x    3 me me   4096 Sep 27 00:16 exampleTypescript
-rw-rw-r--    1 me me   2846 Sep 21 22:26 gulpfile.js
-rw-rw-r--    1 me me   1079 Sep 21 22:26 LICENSE
drwxrwxr-x   12 me me   4096 Sep 27 00:16 node_modules
-rw-rw-r--    1 me me   4232 Sep 27 00:16 package.json
-rw-rw-r--    1 me me   3320 Sep 21 22:26 README.md
-rw-rw-r--    1 me me    517 Sep 21 22:26 tsconfig.json
```

I would expect that there is a `index` file, but there is none.

2.) `rm -rf ./node_modules/protractor && npm install` did not help

3.) `./node_modules/.bin/protractor --version` returns `Version 4.0.9`, so I don't think that there's some kind of version clash

**Comment by cnishina** [comment]
I was not able to reproduce this with https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript. Could you tell me more about your setup? I'm interested in the typescript version you have in your package.json and globally and also how you are calling `tsc`. Are you using the global `tsc`?

**Comment by christiandreher** [comment]
Like I already mentioned in the OP: I use `typescript@2.0.3` and the latest angular-cli. So I don't use `tsc` at all, but `ng e2e`. Apart from `ng`, I don't have anything globally installed. I will provide my full `package.json`, maybe this helps better:

```js
{
    // ...
    "dependencies": {
        "@angular/common": "2.0.1",
        "@angular/compiler": "2.0.1",
        "@angular/compiler-cli": "0.6.3",
        "@angular/core": "2.0.1",
        "@angular/forms": "2.0.1",
        "@angular/http": "2.0.1",
        "@angular/platform-browser": "2.0.1",
        "@angular/platform-browser-dynamic": "2.0.1",
        "@angular/router": "3.0.1",
        "@angular2-material/button": "2.0.0-alpha.8-2",
        "@angular2-material/card": "2.0.0-alpha.8-2",
        "@angular2-material/core": "2.0.0-alpha.8-2",
        "@angular2-material/grid-list": "2.0.0-alpha.8-2",
        "@angular2-material/list": "2.0.0-alpha.8-2",
        "@angular2-material/menu": "2.0.0-alpha.8-2",
        "@angular2-material/toolbar": "2.0.0-alpha.8-2",
        "angular2-moment": "1.0.0-beta.1",
        "core-js": "2.4.1",
        "moment": "2.15.1",
        "rxjs": "5.0.0-beta.12",
        "ts-helpers": "1.1.1",
        "zone.js": "0.6.25"
    },
    "devDependencies": {
        "@types/hammerjs": "2.0.33",
        "@types/jasmine": "2.2.34",
        "@types/protractor": "1.5.20",
        "angular-cli": "1.0.0-beta.15",
        "codelyzer": "1.0.0-beta.0",
        "gulp": "3.9.1",
        "gulp-task-doc": "1.0.11",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.7.0",
        "karma": "1.3.0",
        "karma-chrome-launcher": "2.0.0",
        "karma-cli": "1.0.1",
        "karma-firefox-launcher": "1.0.0",
        "karma-jasmine": "1.0.2",
        "karma-remap-istanbul": "0.2.1",
        "protractor": "4.0.9",
        "require-dir": "0.3.0",
        "ts-node": "1.3.0",
        "tslint": "3.15.1",
        "typescript": "2.0.3"
    }
}
```

**Comment by abierbaum** [comment]
@christiandreher I ran into the same issue.  I had to change my import to 'protractor/built' as you suggested.  Not pretty, but it works for now.  Thanks for the workaround.

**Comment by christiandreher** [comment]
Today I tried to create a MWE. I found out, that the error indeed is not reproducable.
I then decided to fully wipe my `node_modules` and reinstall everything with `npm i`. 
After that it did work, but I still don't know what could have caused this issue. I still have my original `node_modules` folder (the one which produced the error). I will investigate if the md5 sums of both the reinstalled files and the original files match. If I can't find any differences, I have to assume that the error was not related to protractor and will close this issue.

@abierbaum could you also try to fully wipe your `node_modules` folder and reinstall everything to confirm this fix?

**Comment by faminram** [comment]
import { Locator } from 'protractor`;
Result: Error, does not work. Output in terminal:

e2e/app.e2e-spec.ts (18,10): Module ''protractor'' has no exported member 'Locator'. (2305)        

any idea how can I import Locator?

**Comment by cnishina** [comment]
The interface for `Locator` is not exported. However, if you need access to it, you should be able to get to it via:

`import {Locator} from 'protractor/built/locator';`

This interface will probably change in the future.

**Comment by faminram** [comment]
Thanks. It works. Anyway a bit typo instead of "locator" it will be "locators".

import {Locator} from 'protractor/built/locators';
