### ISSUE TITLE
appium?

### ISSUE THREAD

**Issue by laurelnaiad** [angular/protractor#361]
Hi,

I'm new to protractor and interested in testing a phonegap/angular app on emulators. From what I've read appium can drive the emulators and exposes itself via Webdriver JSON protocol. Does that mean I should be able to use protractor with appium to get the job done? I'm not 100% clear on how all of the moving parts would fit together but it seems like I might be able to tell protractor to use an appium server instead of a selenium server? Is this at all true? Any tips or advice? Am I nuts?

**Comment by bmsoko** [comment]
Hello! is there any update on this?? I'm really looking fw to try to test against web-mobile... but I'm keep getting `Async Callbacks` for safari and `Error while running testForAngular: This is feature will be implemented soon!` for android
Also, I've tried to look at what @juliemr suggested on her first post, but I'm getting a 404.
https://github.com/appium/appium/blob/master/docs/caps.md

Was anyone been successful on this?

Thanks

**Comment by bmsoko** [comment]
@PraveenJagarlamudi  can you share your project? or how where you able to configure it?
It'll be much appreciated!!!! 

Thanks

**Comment by PraveenJagarlamudi** [comment]
@bmsoko 
I was able to test against mobile web by making these changes to the configuration file.
1. seleniumAddress: 'http://127.0.0.1:4723/wd/hub',   ( by default appium server listens to 4723 port)
2. capabilities: {
    'browserName' : 'chrome',
    'deviceName' : 'Android Emulator'
}
