### ISSUE TITLE
Type definition of protractor's promise is unclear

### ISSUE THREAD

**Issue by Foxeye-Rinx** [angular/protractor#3610]
Hi, I am using protractor 4.0.9 in TypeScript.
`import { protractor } from 'protractor';`
and `protractor.promise.defer()` return an object which has type of "any".
It's would be better if the protractor.promise.defer() return an specified type instead of "any"

- Protractor Version: `4.0.9`

**Comment by cnishina** [comment]
`promise.defer` comes from the DefinitelyTyped `@types/selenium-webdriver`. I have created an external issue to keep track of this:

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11629
