### ISSUE TITLE
Random timeouts in protractor in IE11

### ISSUE THREAD

**Issue by saifcoding** [angular/protractor#3613]
Hi guys, I am having problem with protractor.

My tests failing for 'Async callback was not invoked within timeout', the tests that failing for this timeouts is random, I didn't find a pattern, its random.

I already did specifiy 'AllScriptsTimeout' for 2 minutes in the conf.js.

I must run my tests on IE11, when I run them on chrome everything working.

Can you help me find a solution? Thank you.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
