### ISSUE TITLE
webdriver.getAttribute documentation: Missing quotes around class parameter can be confusing

### ISSUE THREAD

**Issue by thecuriousnoob** [angular/protractor#3619]
Hello everyone !

I am not much experienced with protractor and needed to use `getAttribute` function to check for a `class` attribute.

Reading the documentation helped me implement it but I just couldn't make it work because I got confused by some missing quotes around `class` parameter which is a `string`.

Here is the documentation extract at `lib/selenium-webdriver/webdriver.js:556` : `expect(foo.getAttribute(class))...`

I am going to reference a PR where I added quotes around the class word showing the paramater is a string and not a variable.

Thank you for your work ! :-)

**Comment by mgiambalvo** [comment]
Thanks for the PR! Documentation fixes are always welcome!
