### ISSUE TITLE
Jasmine 2.0 is out, explore updating to that

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#362]

**Comment by nishakchaudhari** [comment]
So timeout for individual test has been fixed? I tried running my test with jasmine2. It gives me timeout error.

**Comment by hankduan** [comment]
I'm not sure what is your question. Jasmine2 doesn't make timeouts all magically disappear. If your test doesn't finish without a specified time, or your app isn't load, etc, your test will still time out. See https://github.com/angular/protractor/blob/master/docs/timeouts.md

**Comment by nishakchaudhari** [comment]
So I want to know how to setup timeout for individual test with jasmine2.
Before I was doing it in this way : it(description, testFn, timeout_in_millis). And it worked when my jasmine version was <2.
I upgraded jasmine version and now I get following error:
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL

**Comment by vsathyak** [comment]
@nishakchaudhari  : I started using protractor and jasmine 2 and I am also facing the same issue. Any work around for this??

**Comment by nishakchaudhari** [comment]
upgrade jasmine version to 2.3.1 . jasmine 2.3.1 supports timeout for individual test .

**Comment by srajwadi** [comment]
How to update jasmine version. I am currently using 1.3.1 and protractor version is 2.1.0. Can anyone say that how to update jasmine version. I am new to this.
Thanks..

**Comment by hankduan** [comment]
http://www.protractortest.org/#/jasmine-upgrade

**Comment by mocsharp** [comment]
how can I have beforeAll wait for async calls in Jasmine 2.0? Thanks.
