### ISSUE TITLE
ShardTestFiles not working with Gulp

### ISSUE THREAD

**Issue by NewWorldAnks** [angular/protractor#3624]
Bug report
---

- Node Version: `v6.6.0`
- Protractor Version: `v4.0.9`
- Browser(s): `chrome`
- Operating System and Version `Windows 10`

I am using gulp wrapper for protractor for my tests. I am finding issue using ShardTestFiles option of protractor as it is not working for me and I want to run my tests in parallel. I am using protractor version 4.0.9. Below is how my conf file is set-up.
```
exports.config = new ProtractorConfig({
  suites: SuiteNames.registry,
    capabilities: {
    browserName: 'chrome',
    shardTestFiles: true,
    maxInstances: 5
  },
  isAngular: true,
  params: require('./params'),
   jasmineNodeOpts: {
    defaultTimeoutInterval: 500000,
  }
});
```

Below is how my gulp file is structured:
```
var async = require('async');
var env = require('envalid');
var glob = require('glob');
var gulp = require('gulp');
var moment = require('moment');
var path = require('path');
var util = require('gulp-util');
var simpleCommand = require('simple-command');
var binPath = './node_modules/.bin/';
var envURL = util.env.environment;
gulp.task('test-all', function(cb) {
  async.eachSeries(glob.sync('sites/*'), testSite, cb);
});
gulp.task('test', function(cb) {
  env.validate(util.env, {
    site: {
      required: true,
      },
    useSelenium: {
      required: false,
      },
    params: {
      required: false,
      help: 'Other optional parameters to pass into Protractor'
    }
  });
  testSite('sites/' + util.env.site, cb);
});
gulp.task('explorers', function(cb) {
  runProtractor(['--elementExplorer', '--directConnect'], cb);
});
gulp.task('serve', function(cb) {
  runModule('webdriver-manager', ['start'], cb);
});

gulp.task('update', function(cb) {
  runModule('./node_modules/.bin/webdriver-manager', ['update'], cb);
});
gulp.task('default', ['test']);
function runModule(name, params, cb) {
  new simpleCommand(path.join(binPath, name), params, process.cwd()).run(cb);
}
function runProtractor(params, cb) {
  runModule('protractor', params, cb);
}
function testSite(site, cb) {
 var params = [
    site + '/protractor.conf.js','--params.baseUrl='+envURL, '--suite='+util.env.suite, '--params.siteName='+util.env.site, 
    '--params.timestamp=' + timestamp
  ];
  if (!util.env.useSelenium) {
    params.push('--directConnect');
  }
  if (util.env.params) {
    params.push(util.env.params.replace(/(^['"]|['"]$)/g, '').trim());
  }

  util.log('Testing ' + site);
  runProtractor(params, function(err) {
    if (err) {
      util.log(err);
    }
    cb();
  });
}

```
I am not sure why shardTestFiles option is not working for me.

**Comment by NickTomlin** [comment]
Hi there!

Because it involves using a third party tool (in this case, Gulp) your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by NewWorldAnks** [comment]
@NickTomlin This is an issue with protractor as it is not working with Gulp. Is it possible for someone here to look in it as i am not getting any help in stackoverflow?

**Comment by NickTomlin** [comment]
I just added a comment to your stackoverflow question. The issue queue is not for usage/debugging so we should keep the conversation on SO.
