### ISSUE TITLE
Protractor script fail to run in FF 49.0.1

### ISSUE THREAD

**Issue by shimpy25** [angular/protractor#3626]
Hi there!

I recently updated FF version to 49.0.1 & my protractor scripts are failing with this error.

16:46:23] I/testLogger - [firefox #11] PID: 29456
[firefox #11] Specs: /Users/shimpy/test-protractor/src/tests/test.js
[firefox #11] 
[firefox #11] [16:45:34] I/local - Starting selenium standalone server...
[firefox #11] [16:45:36] I/local - Selenium standalone server started at http://169.254.217.200:58469/wd/hub
[firefox #11] 
[firefox #11] /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:26
[firefox #11]   constructor(opt_error) {
[firefox #11]                          ^
[firefox #11] WebDriverError: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
[firefox #11] 08198ce6fd}","syncGUID":"sk34L77TKrsn","location":"app-global","version":"49.0.1","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/Applications/Firefox.app/Contents/Resources/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1475754836000,"updateDate":1475754836000,"applyBackgroundUpdates":1,"skinnable":true,"size":7140,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"49.0.1","maxVersion":"49.0.1"}],"targetPlatforms":[],"seen":true}
[firefox #11] 1475838939271	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}
[firefox #11] 1475838939273	DeferredSave.extensions.json	DEBUG	Save changes
[firefox #11] 1475838939273	addons.xpi	DEBUG	Updating database with changes to installed add-ons
[firefox #11] 1475838939273	addons.xpi-utils	DEBUG	Updating add-on states
[firefox #11] 1475838939274	addons.xpi-utils	DEBUG	Writing add-ons list
[firefox #11] 1475838939276	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/e10srollout@mozilla.org.xpi
[firefox #11] 1475838939276	addons.xpi	DEBUG	Calling bootstrap method startup on e10srollout@mozilla.org version 1.2
[firefox #11] 1475838939276	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/firefox@getpocket.com.xpi
[firefox #11] 1475838939277	addons.xpi	DEBUG	Calling bootstrap method startup on firefox@getpocket.com version 1.0.4
[firefox #11] 1475838939278	addons.xpi	DEBUG	Registering manifest for /Applications/Firefox.app/Contents/Resources/browser/features/webcompat@mozilla.org.xpi
[firefox #11] 1475838939280	addons.xpi	DEBUG	Calling bootstrap method startup on webcompat@mozilla.org version 1.0
[firefox #11] 1475838939287	addons.manager	DEBUG	Registering shutdown blocker for XPIProvider
[firefox #11] 1475838939288	addons.manager	DEBUG	Provider finished startup: XPIProvider
[firefox #11] 1475838939288	addons.manager	DEBUG	Starting provider: LightweightThemeManager
[firefox #11] 1475838939288	addons.manager	DEBUG	Registering shutdown blocker for LightweightThemeManager
[firefox #11] 1475838939289	addons.manager	DEBUG	Provider finished startup: LightweightThemeManager
[firefox #11] 1475838939290	addons.manager	DEBUG	Starting provider: GMPProvider
[firefox #11] 1475838939304	addons.manager	DEBUG	Registering shutdown blocker for GMPProvider
[firefox #11] 1475838939304	addons.manager	DEBUG	Provider finished startup: GMPProvider
[firefox #11] 1475838939304	addons.manager	DEBUG	Starting provider: PluginProvider
[firefox #11] 1475838939305	addons.manager	DEBUG	Registering shutdown blocker for PluginProvider
[firefox #11] 1475838939305	addons.manager	DEBUG	Provider finished startup: PluginProvider
[firefox #11] 1475838939306	addons.manager	DEBUG	Completed startup sequence
[firefox #11] 1475838940243	DeferredSave.extensions.json	DEBUG	Starting write
[firefox #11] 1475838940271	addons.manager	DEBUG	Starting provider: <unnamed-provider>
[firefox #11] 1475838940271	addons.manager	DEBUG	Registering shutdown blocker for <unnamed-provider>
[firefox #11] 1475838940274	addons.manager	DEBUG	Provider finished startup: <unnamed-provider>
[firefox #11] 1475838940544	addons.repository	DEBUG	No addons.json found.
[firefox #11] 1475838940544	DeferredSave.addons.json	DEBUG	Save changes
[firefox #11] 1475838940553	DeferredSave.addons.json	DEBUG	Starting timer
[firefox #11] 1475838940609	addons.manager	DEBUG	Starting provider: PreviousExperimentProvider
[firefox #11] 1475838940609	addons.manager	DEBUG	Registering shutdown blocker for PreviousExperimentProvider
[firefox #11] 1475838940610	addons.manager	DEBUG	Provider finished startup: PreviousExperimentProvider
[firefox #11] 1475838940621	DeferredSave.extensions.json	DEBUG	Write succeeded
[firefox #11] 1475838940621	addons.xpi-utils	DEBUG	XPI Database saved, setting schema version preference to 17
[firefox #11] 1475838940624	DeferredSave.addons.json	DEBUG	Starting write
[firefox #11] 1475838940667	DeferredSave.addons.json	DEBUG	Write succeeded
[firefox #11] 
[firefox #11]     at WebDriverError (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:26:26)
[firefox #11]     at Object.checkLegacyResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:639:15)
[firefox #11]     at parseHttpResponse (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:538:13)
[firefox #11]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:472:11
[firefox #11]     at ManagedPromise.invokeCallback_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1379:14)
[firefox #11]     at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2913:14)
[firefox #11]     at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2896:21)
[firefox #11]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2820:25
[firefox #11]     at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
[firefox #11]     at process._tickCallback (node.js:406:9)
[firefox #11] From: Task: WebDriver.createSession()
[firefox #11]     at Function.createSession (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
[firefox #11]     at Builder.build (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/builder.js:458:24)
[firefox #11]     at Local.DriverProvider.getNewDriver (/usr/local/lib/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
[firefox #11]     at Runner.createBrowser (/usr/local/lib/node_modules/protractor/built/runner.js:190:43)
[firefox #11]     at /usr/local/lib/node_modules/protractor/built/runner.js:264:30
[firefox #11]     at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:834:54)
[firefox #11]     at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:863:30)
[firefox #11]     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:796:13)
[firefox #11]     at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:604:44
[firefox #11]     at runSingle (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:137:13)

I will need to downgrade FF version if it fails in newer version.

**Comment by mgiambalvo** [comment]
Firefox 49 has a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1297551) that blocks testing with Protractor. Please downgrade to 47. We're expecting that this issue will be fixed in Firefox 50.

Also, note that you'll need to add 'marionette: true' to your capabilities in order to test on Firefox in the future.
