### ISSUE TITLE
Including protractor in a protractor.conf.ts file breaks using importing protractor.browser and more

### ISSUE THREAD

**Issue by KrauseStefan** [angular/protractor#3627]
Bug report
---

- Node Version: `6.7.0`
- Protractor Version: `4.0.9`
- Operating System and Version `Win 8.1`

Output from running the test
```
[14:04:55] I/direct - Using ChromeDriver directly...                                                                
[14:04:55] I/launcher - Running 1 instances of WebDriver                                                            
[14:04:57] E/launcher - Error: TypeError: Cannot read property 'manage' of undefined                                
    at onPrepare (D:\git\hq\SitaWareWeb\client\src\main\client_integration_test\protractor.conf.ts:64:12)           
    at D:\git\hq\SitaWareWeb\client\src\main\node_modules\protractor\built\util.js:48:49                            
    at Function.promise (D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:682:9)                           
    at Object.runFilenameOrFn_ (D:\git\hq\SitaWareWeb\client\src\main\node_modules\protractor\built\util.js:38:16)  
    at D:\git\hq\SitaWareWeb\client\src\main\node_modules\protractor\built\runner.js:93:27                          
    at _fulfilled (D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:834:54)                                
    at self.promiseDispatch.done (D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:863:30)                 
    at Promise.promise.promiseDispatch (D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:796:13)           
    at D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:556:49                                             
    at runSingle (D:\git\hq\SitaWareWeb\client\src\main\node_modules\q\q.js:137:13)                                 
[14:04:57] E/launcher - Process exited with error code 100                                                          
```

Protractor.conf.ts
```typescript
import {UtilityFunctions as util} from './UtilityFunctions';
//import * as protractor from 'protractor';
import {browser, Config} from 'protractor';

const driverInfo = util.getDriverInfo(protractorVersion);

export const config: Config = {

  specs: [
    'client_integration_test/build/**/test/ui/**/*.test.js'
  ],
  framework: 'jasmine',

  beforeLaunch: () => {
    launchWebServer();
  },

  onPrepare: () => {
   // patchProtractorObject();

    browser.manage().window().maximize();
    browser.addMockModule('FakeDataDummyModule', MockServiceLoader.getMockData());
  },
  seleniumArgs: ['-Dwebdriver.ie.driver=' + driverInfo.IEDriverServer_exe],
  seleniumServerJar: driverInfo.seleniumServer_jar,

  jasmineNodeOpts: {defaultTimeoutInterval: 120000},
  multiCapabilities: [{
    'browserName': 'chrome',
  }]
}
```

My current work around it commenting in the code that has been commented out above and add the below snippet
```typescript
function patchProtractorObject() {
  let unsafeProtractor: any = protractor;
  unsafeProtractor.protractor = global['protractor'];
  unsafeProtractor.browser = unsafeProtractor.protractor.browser;
  unsafeProtractor.$ = unsafeProtractor.protractor.$;
  unsafeProtractor.$$ = unsafeProtractor.protractor.$$;
  unsafeProtractor.element = unsafeProtractor.protractor.element;
  unsafeProtractor.By = unsafeProtractor.protractor.By;
  unsafeProtractor.by = unsafeProtractor.protractor.by;
  unsafeProtractor.ExpectedConditions = unsafeProtractor.protractor.ExpectedConditions;
}
```

I guess my issue happens because at the time I'm requiring/importing the protractor module the dependencies are not available. I haven't exactly found where fx browser is added to the `global` object.
But it happens because this code from `lib/index.ts` only gets evaluated once (that is just how node modules work)
```typescript
export let protractor: Ptor = (global as any)['protractor'];
export let browser: ProtractorBrowser =
    protractor ? protractor.browser : undefined;
export let $: (search: string) => ElementFinder =
    protractor ? protractor.$ : undefined;
export let $$: (search: string) => ElementArrayFinder =
    protractor ? protractor.$$ : undefined;
export let element: ElementHelper = protractor ? protractor.element : undefined;
export let By: ProtractorBy = protractor ? protractor.By : undefined;
export let by: ProtractorBy = protractor ? protractor.by : undefined;
export let ExpectedConditions: ProtractorExpectedConditions =
    protractor ? protractor.ExpectedConditions : undefined;
```

Hope you can come up with a more appropriate solution than mine :)

**Comment by KrauseStefan** [comment]
I've simplified the configuration file a bit, if you need more please ask.

**Comment by mgiambalvo** [comment]
Although we support writing specs in TypeScript, we don't support configuration files written in TS, pretty much because of this exact issue. Sorry, you'll probably either need to keep your workaround, or write your config in JS.

Assigning to @cnishina in case he has a better answer.

**Comment by igniteram** [comment]
@KrauseStefan You might wanna check out currently how `onPrepare()` works with typescript. Please check https://github.com/angular/protractor/issues/3629 and the [protractor-cookbook-onPrepare] (https://github.com/angular/protractor-cookbook/blob/master/protractor-typescript/example-on-prepare/config.ts) example!

**Comment by KrauseStefan** [comment]
Okay I see, I didn't mean to create a duplicate issue of the other one.

I couldn't initially see why the example in to cook-book worked, but apparently importing in typescript does not always result in an equal `require(...)` in js when only using the import for type information.

I do however think that the current behavior of assigning `undefined` makes for a unnecessary gotcha.
Having the code throw or at least log a error/warning if the protractor module is loaded before it is ready would help a lot.
Other than making the workaround that I currently use possible, I have a hard time seeing the benefit to having it default to undefined.

You are not able to use the global anywhere in your test unless you access them globally.
It does not matter if you call `require('protractor')` again since the object is not reinitialized by node but instead the old version with `browser` initialized to `undefined` is returned.

I guess this issue is an improvement request rather than a bug :)

**Comment by cnishina** [comment]
@igniteram thanks for pointing out the Protractor Cookbook onPrepare example. If you import a global object in typescript prior to its creation, then the tests do not work.

So something like the example below **does not work**. The protractor object has not been created; therefore, the browser will be undefined. So even in the spec file, importing 'browser' (although created in the global namespace) should still be undefined.

config:
```
// because global['protractor']['browser'] does not exist, the browser object
// will refer to an undefined object
import {browser} from 'protractor';

export const config = {
  onPrepare: () => {
    // doing a browser.get will lead to a transpile error. 
    // undefined does not have a get method
  },
 specs: [ 'spec.js' ]
}
```

spec:
```
import {browser} from 'protractor';

describe('the browser', () => {
  it('should be undefined', () => {
    console.log(browser); // this will be undefined
  });
});
```

Using `require` is our current recommendation. I hope this was a good enough explanation... Closing this issue.

**Comment by mgiambalvo** [comment]
Just to update for anyone reading this in the future, we changed the way global imports work in 4.0.11. The config file example in the OP should now work.
