### ISSUE TITLE
Timeout because of returned value from animation transitions 

### ISSUE THREAD

**Issue by ffesseler** [angular/protractor#3628]
## Bug report
- Node Version: `4.4.7`
- Protractor Version: `4.0.9`
- Angular Version: `1.5.9`
- Browser(s): `Chrome 53.0.2785.143`
- Operating System and Version `macOS 10.12`

I've noticed my tests started failing on my computer recently.
Please note that tests still pass on our Windows 7 CI computer with Chrome 53.

One of the test fails after the waiting for page synchronization exceeds the configuration time.
After investigation and looking how the synchronization worked, I've managed to isolate where the bug comes from. 

Some of my animations transition last less than one second : 

```
  transition: opacity linear 0.25s;
```

For theses animations, timeouts used in the $browser.defer function from angular were very high (for the 0.25s, the timeout was 37500ms). So the protractor synchronization becomes very long in that case.
Looking deeper where the animation transition value was get from the css (function computeCssStyles from angular-animate), I've found the returned value from the window.getComputedStyle was "0,25s" instead of "0.25s". The computeCssStyles don't handle well this case and returns 25, instead of 0.25.

Now you're going to tell me this is not a protractor issue, maybe a Chrome bug, or angular-animate bug.
I would agree but I've noticed that only when I launched my app from protractor, the returned value format issue happens. When I launch Chrome manually, the returned value is ok ("0.25s".)

**Comment by mgiambalvo** [comment]
Thanks for the report! If it's possible, could you give us a minimal example that reproduces the issue? That'd really help us get to the bottom of this.

**Comment by ffesseler** [comment]
You can reproduce it with the animation example of the testapp.
In the css file, replace the transition value with .25s and add a console.log to output the delay property passed to the  $browser.defer function in angular.

**Comment by mgiambalvo** [comment]
Sorry, not able to reproduce this. The computeCssStyles I see is `0.25s`, and the delay is appropriate. Maybe this was a weird chromedriver bug?
