### ISSUE TITLE
Using TypeScript import inside protractor config does not work

### ISSUE THREAD

**Issue by bcherny** [angular/protractor#3629]
Contents of src/protractor.conf.ts:

```ts
import { browser } from 'protractor'

export const config = {
  baseUrl: 'http://localhost:3001',
  framework: 'jasmine2',
  onPrepare() {
    browser.ignoreSynchronization = true
  }
}
```

When compiling to JS and running via `./node_modules/.bin/protractor ./dist/protractor.conf.js`:

```text
[13:43:12] I/direct - Using ChromeDriver directly...
[13:43:12] I/launcher - Running 1 instances of WebDriver
[13:43:13] E/launcher - Error: TypeError: Cannot set property 'ignoreSynchronization' of undefined
    at onPrepare (/Site/dist/protractor.config.js:40:52)
    at /Site/node_modules/protractor/built/util.js:48:49
    at Function.promise (/Site/node_modules/q/q.js:682:9)
    at Object.runFilenameOrFn_ (/Site/node_modules/protractor/built/util.js:38:16)
    at /Site/node_modules/protractor/built/runner.js:93:27
    at _fulfilled (/Site/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Site/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Site/node_modules/q/q.js:796:13)
    at /Site/node_modules/q/q.js:556:49
    at runSingle (/Site/node_modules/q/q.js:137:13)
```

Using Protractor 4.0.9 + TypeScript 2.0.3.

**Comment by igniteram** [comment]
@bcherny This was one of the issues due to protractor generates global values after it reads the config file, so when you are trying to `import {browser} from 'protractor'` they have not been generated yet and `tsc` passes it, the issue comes when you try to run your tests. 

A way to get around this as pointed out by @cnishina is to initialise global variables inside `onPrepare()` :

```
import {ProtractorBrowser} from 'protractor';

  onPrepare: () => {
        let globals = require('protractor');
        let browser: ProtractorBrowser = globals.browser;
        browser.ignoreSynchronization = true;
        browser.manage().window().maximize();  
    }
```
For more details on how `onPrepare()` works with typescript please check out the example in [protractor-cookbook-onPrepare](https://github.com/angular/protractor-cookbook/blob/master/protractor-typescript/example-on-prepare/config.ts)

**Comment by bcherny** [comment]
@igniteram I did notice that bit of juggling while I was digging through the source. Unfortunately, the workaround you gave doesn't work - I get the same error.

If I rely on the global `browser` being defined in my config file (or `declare let browser: ProtractorBrowser`), that works. But then I get an error that `browser` is not defined in one of my PageObjects (the PageObject's file imports it: `import { browser } from 'protractor'`.

If I remove the `import` in the PageObject file as well, everything works fine, though same as the config file, TypeScript complains unless I `declare let browser`.

Am I missing something?

**Comment by bcherny** [comment]
Duh - the PageObject was being required in my onPrepare function, so it is exposed to the same timing issue as the config file.

@juliemr How feasible is it to avoid the global juggling? Is there a discussion of potential solutions somewhere on github?

**Comment by MeAriJit** [comment]
on top of @igniteram if it still not works then do with specific location of built in on prepare. like below..
onPrepare: () => {
        let globals = require('protractor/built');
        let browser: ProtractorBrowser = globals.browser;
        browser.ignoreSynchronization = true;
        browser.manage().window().maximize();  
    }
