### ISSUE TITLE
How to read css style property, if the properties are added in css file?

### ISSUE THREAD

**Issue by DeChrish** [angular/protractor#3630]
Locator strategy!!!

Based on user Action, a DOM object css property is changed 'display:none;' and this is added in a css file and exposed as class.

We need to assert the element is not visible in the DOM.

Any advice?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
