### ISSUE TITLE
Break gives SyntaxError: Illegal break statement

### ISSUE THREAD

**Issue by vitebchanka** [angular/protractor#3635]
Hi All,
I found the closed bug #3220, but really can't use break in loop.
For my check I did the simple test:

> while(i<10){
>             element(by.xpath("//a[contains(@id, 'ma-apply')]")).isPresent().then(function(result){
>                 if(!result){
>                     helper.one_page_ahead();
>                 }
>                 else{
>                     console.log('there is on the page');
>                     break;
>                 };
>                 
>             });
>             i++;
>         };

This leads to the error.
I tried to follow advice via stakeoverflow and changed **break** to **return**.
But this leads to full loop execution(up to 10)
Here is output;

> [14:17:46] I/launcher - Running 1 instances of WebDriver
> Started
> user skills: AJAX
> there is on the page
> there is on the page
> there is on the page
> there is on the page
> there is on the page
> there is on the page
> there is on the page
> there is on the page
> .
> 
> 
> 1 spec, 0 failures
> Finished in 37.93 seconds

Help me please with this issue.
Kind regards,
Halina.

**Comment by cnishina** [comment]
The previous closed issue was correct, this is a stackoverflow question. I'll be happy to answer it on stackoverflow. Just comment with the stackoverflow link on this issue.

**Comment by vitebchanka** [comment]
Hi, cnishina.
Thanks for answering me.
This is the link on my question on sof
http://stackoverflow.com/questions/39999826/protractor-break-while-of-for-loop
