### ISSUE TITLE
async / await support

### ISSUE THREAD

**Issue by christianacca** [angular/protractor#3637]
Bug report
---

- Node Version: `6.2.2`
- Protractor Version: `4.0.9`
- Angular Version: `1.5.8`
- Typescript Version: `2.0.3`
- Operating System and Version `Windows 10 Anniversary update`
- Your protractor configuration file: [protractor.config.js](https://github.com/esvit/ng-table/blob/asyn-await-spec/e2e/protractor.config.js)

According to the [typescript example](https://github.com/angular/protractor/blob/master/exampleTypescript/asyncAwait/spec.ts#L9), async / await is supported in protactor specs.

However, I get a compile error trying to use the await keyword in a spec file in the [ng-table repo](https://github.com/esvit/ng-table):

> "operand for 'await' does not have a valid callable 'then' member"

See [the failing code](https://github.com/esvit/ng-table/blob/asyn-await-spec/e2e/async-await-not-working.spec.ts#L18)

## To reproduce the problem

1. `git clone https://github.com/esvit/ng-table.git`
2. switch to branch *asyn-await-spec*:
  * `cd ng-table`
  * `git checkout asyn-await-spec`
3. `npm install`
4. Open the spec `e2e/async-await-not-working.spec.ts`
5. Uncomment the lines 18-20; 

In visual studio code, you will now see that the compile error

**Comment by wswebcreation** [comment]
I didn't clone the project, but when I compare the example with your code, should your code be this

```
if ((await rows.count()) > 0) {
     expect(rows.get(0).isPresent()).toBe(true);
 }
```

**Comment by christianacca** [comment]
Thanks @wswebcreation for the feedback. 

I've updated my code as suggest, but **I still get the same error**

**Comment by mgiambalvo** [comment]
Closing as a duplicate because this is definitely related to #3636. async/await should work, but if tsc doesn't think webdriver promises have a .then(), then this is the error it would throw.

**Comment by awarecan** [comment]
We have bunch of test cases using async/await just fine in protractor 3.2.0/typescript 1.8.9. 

I met the exactly same error today, when I was trying to upgrade to protractor 4.0.9 and typescript 2.0.3.

**Comment by ccrowhurstram** [comment]
So the problem was in the @types/selenium-webdriver. It was fixed in version @types/selenium-webdriver2.53.33
