### ISSUE TITLE
Unable to host protract 4.0.9 on a private repository

### ISSUE THREAD

**Issue by jrharshath** [angular/protractor#3641]
- Node Version: `6.3.1`
- Protractor Version: `4.0.9`

We've been hosting our own npm repository (for reasons beyond my control), and we'd been hosting protractor's older versions there. Here's the workflow we used to publish it to our repo:

* `npm install protractor@4.0.9`
* update .npmrc to point to our own repo (Sonatype Nexus based, btw)
* `npm publish node_modules/protractor` 
* dependencies of protractor are also published into the Nexus repository

Now upon running `npm install protractor@4.0.9` in a newly init-ed directory, we see:

`npm ERR! enoent ENOENT: no such file or directory, chmod '/home/username/newly-inited-dir/node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager'`

Is this because of how I'm publishing the package? Any inputs are appreciated.

**Comment by cnishina** [comment]
Are you also publishing webdriver-manager to your Sonatype Nexus repo? Just reading the error message, my guess is that webdriver-manager is not being published to your repo.

This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by jrharshath** [comment]
Thanks for your response, and for closing this out. After some digging, this turned out to be a problem with a corrupted webdriver-manager in our Sonatype Nexus repo.
