### ISSUE TITLE
Duplicate identifier : Typescript and Protractor

### ISSUE THREAD

**Issue by nachchid** [angular/protractor#3642]
Hi ..
I am new to typescript and protractor . 
I had my protractor(v3.3.0) test working in .js format.  I wanted to make use of typescript and upgrade protractor to version 4.0.9. Now I am seeing the following error. Not sure what went wrong.  I deleted my node_module and tried to do a re-install . No luck .  

- Node Version: ``  v4.6.0
- Protractor Version: ``v4.0.9
- Angular Version: `` Angular 2.0.0
- Operating System and Version `` Windows 7
- Your protractor configuration file 

**// conf.js**
exports.config = { 
	seleniumAddress: 'http://localhost:4444/wd/hub',  
	framework: 'jasmine2',
	specs: ['home-spec.ts'], 
	useAllAngular2AppRoots: true,
	
	multiCapabilities: [
		{'browserName': 'chrome'},	
	],
	maxSessions: 1,
	
    onPrepare: function() {
	var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');
	var jasmineReporters = require('jasmine-reporters');
    
        return browser.getProcessedConfig().then(function(config) {
        
        var browserName = config.capabilities.browserName;

        jasmine.getEnv().addReporter(new HtmlScreenshotReporter({
	dest: 'C:/target',
	filename: 'my-report.html',
	reportOnlyFailedSpecs: false,
	captureOnlyFailedSpecs: false,
	ignoreSkippedSpecs: true,

}))	;

**typings.json**

{
  "globalDependencies": {
    "core-js": "registry:dt/core-js#0.0.0+20160725163759",
    "google.maps": "registry:dt/google.maps#3.20.0+20160914131659",
    "jasmine": "registry:dt/jasmine#2.2.0+20160621224255",
    "node": "registry:dt/node#6.0.0+20161010101523"
  }
}

**tsconfig.json**

{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "outDir": "tmp",
    "types": ["jasmine", "node"]
  },  
  "exclude": [
    "node_modules"
  ]
}

 **Output:** 

node_modules/@types/jasmine/index.d.ts(74,9): error TS2375: Duplicate number index signature.
node_modules/@types/jasmine/index.d.ts(129,9): error TS2374: Duplicate string index signature.
node_modules/@types/node/index.d.ts(102,6): error TS2300: Duplicate identifier 'BufferEncoding'.
node_modules/@types/node/index.d.ts(263,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(549,26): error TS2300: Duplicate identifier 'Buffer'.
node_modules/@types/node/index.d.ts(549,50): error TS2300: Duplicate identifier 'SlowBuffer'.
node_modules/@types/node/index.d.ts(570,18): error TS2300: Duplicate identifier 'EventEmitter'.
node_modules/@types/node/index.d.ts(733,18): error TS2300: Duplicate identifier 'Agent'.
node_modules/@types/node/index.d.ts(791,18): error TS2300: Duplicate identifier 'Worker'.
node_modules/@types/node/index.d.ts(1377,17): error TS2300: Duplicate identifier 'CompleterResult'.
node_modules/@types/node/index.d.ts(1414,18): error TS2300: Duplicate identifier 'Script'.
node_modules/@types/node/index.d.ts(2320,18): error TS2451: Cannot redeclare block-scoped variable 'constants'.
node_modules/@types/node/index.d.ts(2550,18): error TS2300: Duplicate identifier 'TLSSocket'.
node_modules/@types/node/index.d.ts(2861,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
node_modules/@types/node/index.d.ts(2862,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
node_modules/@types/node/index.d.ts(2863,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
node_modules/@types/node/index.d.ts(2864,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
node_modules/@types/node/index.d.ts(2865,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
node_modules/@types/node/index.d.ts(3216,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3299,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3321,18): error TS2300: Duplicate identifier 'Domain'.
node_modules/@types/node/index.d.ts(3613,5): error TS2300: Duplicate identifier 'export='.
node_modules/@types/node/index.d.ts(3639,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(78,6): error TS2300: Duplicate identifier 'BufferEncoding'.
typings/globals/node/index.d.ts(234,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(518,9): error TS2502: 'BuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(519,9): error TS2502: 'SlowBuffType' is referenced directly or indirectly in its own type annotation.
typings/globals/node/index.d.ts(520,26): error TS2300: Duplicate identifier 'Buffer'.
typings/globals/node/index.d.ts(520,50): error TS2300: Duplicate identifier 'SlowBuffer'.
typings/globals/node/index.d.ts(541,18): error TS2300: Duplicate identifier 'EventEmitter'.
typings/globals/node/index.d.ts(704,18): error TS2300: Duplicate identifier 'Agent'.
typings/globals/node/index.d.ts(762,18): error TS2300: Duplicate identifier 'Worker'.
typings/globals/node/index.d.ts(1348,22): error TS2300: Duplicate identifier 'CompleterResult'.
typings/globals/node/index.d.ts(1388,18): error TS2300: Duplicate identifier 'Script'.
typings/globals/node/index.d.ts(2280,22): error TS2451: Cannot redeclare block-scoped variable 'constants'.
typings/globals/node/index.d.ts(2635,18): error TS2300: Duplicate identifier 'TLSSocket'.
typings/globals/node/index.d.ts(2946,10): error TS2300: Duplicate identifier 'Utf8AsciiLatin1Encoding'.
typings/globals/node/index.d.ts(2947,10): error TS2300: Duplicate identifier 'HexBase64Latin1Encoding'.
typings/globals/node/index.d.ts(2948,10): error TS2300: Duplicate identifier 'Utf8AsciiBinaryEncoding'.
typings/globals/node/index.d.ts(2949,10): error TS2300: Duplicate identifier 'HexBase64BinaryEncoding'.
typings/globals/node/index.d.ts(2950,10): error TS2300: Duplicate identifier 'ECDHKeyFormat'.
typings/globals/node/index.d.ts(3301,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3384,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3406,18): error TS2300: Duplicate identifier 'Domain'.
typings/globals/node/index.d.ts(3698,5): error TS2300: Duplicate identifier 'export='.
typings/globals/node/index.d.ts(3724,5): error TS2300: Duplicate identifier 'export='.

**Comment by mgiambalvo** [comment]
Hi there!

Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

That said, Protractor 4.0.9 depends on TypeScript 2.0, which removes typings. If you delete your node_modules and do `npm install`, you should be fine provided you're using TypeScript 2.0.

Thanks and good luck!

**Comment by nachchid** [comment]
Thank you. Deleted node modules and tried to do a npm install using Typescript 2.0.
Typings got installed during npm install..... so then I removed the reference from 
1. index.d.ts file 
2. and duplicate identifiers from globalDependencies    It worked. 

 Will direct my questions to Gitter Channel in future
