### ISSUE TITLE
Protractor can't pull down chromedriver2.24 for mac with webdriver-manager.js

### ISSUE THREAD

**Issue by catshark** [angular/protractor#3644]
The selenium2.52 and chromedriver2.21 drivers that comes with protractor 3.3.0 dont work with latest versions of chrome (53 and 54) and running 'webdriver-manager update --versions.chrome 2.24' on a mac doesn't pull down chromedriver 2.24 because it's only available for mac64 and webdriver-manager uses 'mac32' regardless of whether your os is 32 or 64 bit. 

I use protractor 3.3.0 instead of 4.x.x because I run my automation tests with grunt-protractor-runner which is not compatible with 4.x.x. At least not yet anyway.

- Node Version: `v4.4.3`
- Protractor Version: `v3.3.0`
- Angular Version: `v1.4.9`
- Browser(s): `Chrome 53`
- Operating System and Version `OSX El Capitan (Version 10.11.4)`

- My protractor configuration file protractor.conf.js
exports.config = {
    // ----- How to setup Selenium -----
    //
    // There are three ways to specify how to use Selenium. Specify one of the
    // following:
    //
    // 1. seleniumServerJar - to start Selenium Standalone locally.
    // 2. seleniumAddress - to connect to a Selenium server which is already
    //    running.
    // 3. sauceUser/sauceKey - to use remote Selenium servers via SauceLabs.

    // The location of the selenium standalone server .jar file.
    seleniumServerJar: './node_modules/protractor/selenium/selenium-server-standalone-2.52.0.jar',
    // The port to start the selenium server on, or null if the server should
    // find its own unused port.
    seleniumPort: null,
    // Chromedriver location is used to help the selenium standalone server
    // find chromedriver. This will be passed to the selenium jar as
    // the system property webdriver.chrome.driver. If null, selenium will
    // attempt to find chromedriver using PATH.
    chromeDriver: './node_modules/protractor/selenium/chromedriver_2.21',

    // ----- What tests to run -----
    //
    // Spec patterns are relative to the location of this config.
    specs: [
        './spec.js'
    ],

    // ----- Capabilities to be passed to the webdriver instance ----
    //
    // For a full list of available capabilities, see
    // https://code.google.com/p/selenium/wiki/DesiredCapabilities
    // and
    // https://code.google.com/p/selenium/source/browse/javascript/webdriver/capabilities.js
    capabilities: {
        'browserName': 'chrome',
        'chromeOptions': {
            args: ['test-type']
        }
    },

    // ---------------------------------------------------------------------------
    // ----- Global test information ---------------------------------------------
    // ---------------------------------------------------------------------------
    //

    // The timeout in milliseconds for each script run on the browser. This should
    // be longer than the maximum time your application needs to stabilize between
    // tasks.
    allScriptsTimeout: 60000,

    getPageTimeout: 30000,

    // ---------------------------------------------------------------------------
    // ----- The test framework --------------------------------------------------
    // ---------------------------------------------------------------------------

    // Test framework to use. This may be one of:
    // jasmine, mocha or custom.
    //
    // When the framework is set to "custom" you'll need to additionally
    // set frameworkPath with the path relative to the config file or absolute
    //  framework: 'custom',
    //  frameworkPath: './frameworks/my_custom_jasmine.js',
    // See github.com/angular/protractor/blob/master/lib/frameworks/README.md
    // to comply with the interface details of your custom implementation.
    //
    // Jasmine is fully supported as test and assertion frameworks.
    // Mocha has limited support. You will need to include your
    // own assertion framework (such as Chai) if working with Mocha.
    framework: 'jasmine2',

    // Options to be passed to jasmine.
    //
    // See https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js
    // for the exact options available.
    jasmineNodeOpts: {
        // onComplete will be called just before the driver quits.
        onComplete: null,
        // If true, display spec names.
        isVerbose: true,
        // If true, print colors to the terminal.
        showColors: true,
        // If true, include stack traces in failures.
        includeStackTrace: true,
        // Default time to wait in ms before a test fails.
        defaultTimeoutInterval: 62000
    }
};

- Output from running webdriver-manager update:

**./node_modules/.binwebdriver-manager update --versions.chrome 2.24 --versions.standalone 2.53**

"Updating selenium standalone to version 2.53
downloading https://selenium-release.storage.googleapis.com/2/selenium-server-standalone-2.53.jar...
Updating chromedriver to version 2.24
downloading https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip...
Error: Got code 404 from https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
"

-**Steps to reproduce the bug**
1. Download protractor on a MacOS.
2. Run the following command - **./node_modules/.binwebdriver-manager update --versions.chrome 2.24 --versions.standalone 2.53**
3. Observe that you get a 404 for https://chromedriver.storage.googleapis.com/2.24/chromedriver_mac32.zip
4. Navigate to https://chromedriver.storage.googleapis.com.
5. Find '2.24' on the page and observe that there is chromedriver zip files for linux32, linux64, win32 and mac64 but not mac32
6. Open webdriver-manager.js found in protractor's node_modules/.bin directory and observe that os can not be set to 64 bit mac

Feature Request
---Modify the webdriver-manager so that you can download chromedriver versions greater than 2.22 on a mac
`
suffix: function() {
      if (os.type() == 'Darwin') {
        return 'mac32.zip';
      } else if (os.type() == 'Linux') {
        if (os.arch() == 'x64') {
          return 'linux64.zip';
        } else {
          return 'linux32.zip';
        }
      } else if (os.type() == 'Windows_NT') {
        return 'win32.zip';
      }
    },
`

- Reasons for adopting new feature: unable to run protractor on mac against latest chrome versions

**Comment by NickTomlin** [comment]
Webdriver manager has moved out of protractor into it's own standalone package. If you want to use an older version of protractor with a newer chrome binary you should install [`webdriver-manager`](https://github.com/angular/webdriver-manager) from NPM and use it. It properly handles this difference in the binary names.

I'm going to close this as it deals with an older version of protractor and there's an easy workaround.
