### ISSUE TITLE
Typescript definition for protractor's map function is not correct when working with promises

### ISSUE THREAD

**Issue by megaboich** [angular/protractor#3653]
Bug report
---
Relevant versions:
"typescript": "2.0.3",
"@types/protractor": "1.5.20",
"@types/selenium-webdriver": "2.53.33",

This is quite simplified code which illustrates the problem:
```typescript
    public getTextOfAllComponents(): webdriver.promise.Promise<string[]> {
        let inputs = element.all(by.css("input"));
        return inputs.map(i => i.getText())
    }
```

Typescript shows an error here because returning type is not match.
```
[ts] Type 'Promise<Promise<string>[]>' is not assignable to type 'Promise<string[]>'.
       Type 'Promise<string>[]' is not assignable to type 'string[]'.
         Type 'Promise<string>' is not assignable to type 'string'.
```

But in reality (if you ignore the error or do types cast through ```any``` ) it works well and function returns promise of string array.

**Comment by juliemr** [comment]
We don't maintain `@types/protractor`, and instead include typings directly - please bring this issue up with DefinitelyTyped about the 'angular-protractor' file. Thanks!
