### ISSUE TITLE
Unable to open a new tab in chrome(v54) instance using CTRL+T.

### ISSUE THREAD

**Issue by Charuvaka** [angular/protractor#3660]
Hi there!

I recently updated my chrome version to the latest (v54) and then I am unable to open a new tab using CTRL+T through automation. It is working fine with the lower versions of Chrome. 

Here is the snippet: 
browser.actions().keyDown( protractor.Key.CONTROL ).perform().then( function () {    browser.actions().sendKeys( 't' ).perform();
} );

Can someone please help me out.

Regards,
Charvaka.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
