### ISSUE TITLE
When using typescript 2.0.3 and protractor 4.0.9 it is impossible to use both @types/selenium-webriver 

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3663]
Typescript compiler is complaining about i.e browser.wait( function. This function is included in "@types/selenium-webdriver" but it is not included in "@types/protractor". But when @types/selenium-webdriver is inlcuded under types in tsconfig.json, the runner complains that there are duplicate types definitions:

 `Conflicting definitions for 'selenium-webdriver' found at 'C:/Users/gwk736/Gitlab/inform-locate-E2E-tests/node_modules/@types/selenium-webdriver/index.d.ts' and 'C:/Users/gwk736/Gitlab/inform-locate-E2E-tests/node_modules/protractor/node_modules/@types/selenium-webdriver/index.d.ts'. Consider installing a specific version of this library to resolve the conflict. (4090)`

---

- Node Version: ``
- Protractor Version: `4.0.9`
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by juliemr** [comment]
You should not need to include `@types/selenium-webdriver` in your own deps. If you do, please make sure the version is compatible with Protractor's so it doesn't cause conflicts like this.
