### ISSUE TITLE
Missing browser.wait() function in typings in 4.0.9

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3665]
I am using typescript 2.0.3 and protractor 4.0.9. When I import browser like:

`import {ExpectedConditions, browser} from "protractor"
`
I have no `browser.wait(ExpectedConditions.presenceOf(locator));`

The method does not exist, thus there are compile errors.

If I use`browser.driver.wait(ExpectedConditions.presenceOf(locator)); 
`
then I get:
 `Type 'Function' is not assignable to type '(driver: WebDriver) => {}'.`

According to API I should be able to use browser.wait(ExpectedCondtions.presenceOf(locator)).then()

I am not
## Bug report
- Node Version: ``
- Protractor Version: `4.0.9`
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)
## Feature Request
- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by cnishina** [comment]
`@types/selenium-webdriver` sets the wait to 
```
wait<T>(condition: webdriver.promise.Promise<T>|webdriver.until.Condition<T>|
  ((driver: WebDriver)=>T), timeout?: number, opt_message?: string): 
  webdriver.promise.Promise<T>;
```

`browser.wait` appears to not match. 
```
wait:
      (condition: wdpromise.Promise<any>|until.Condition<any>|Function,
       opt_timeout?: number, opt_message?: string) => wdpromise.Promise<any>;
```

Since ExpectedCondition returns a `Function`, the easy fix is to just add `Function` to the `@types/selenium-webdriver`.

**Comment by cnishina** [comment]
Closed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12457

**Comment by ViktorMikhalkin** [comment]
Looks like, the similar issue has appeared again. The code below 
```
async isOpened(url: string = null): Promise<boolean> {
        try {
            const timeout = await PageObject.getPageTimeout();
            return await browser.wait(EC.or(EC.urlIs(this.url), EC.urlContains(url)), timeout, 'Page is not opened.');
        } catch (e) {
            console.log(e);
        }
    }
```
after running `tsc --alwaysStrict` produces the error message `Type '{}' is not assignable to type 'boolean'` for the line `return await browser.wait(EC.or(EC.urlIs(this.url), EC.urlContains(url)), timeout, 'Page is not opened.');`
The version of Node version is 8.8.1, Protractor is 5.2.0, and Typescript is 2.6.1
