### ISSUE TITLE
Protractor project to be build on VSTS

### ISSUE THREAD

**Issue by bharathssubramanian** [angular/protractor#3669]
Hi there!

Can you pls explain how to build protractor project (gulp task runner) inside  VSTS. 

Also VSTS extension to Selenium Grid and Saucelabs.

Thanks
Bharath

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
