### ISSUE TITLE
scripts/generate-docs.sh not working

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3670]
Publishing the `toc.json` did not work with `generate-docs.sh`. Publishing the website required running the script and also copying over the `toc.json` generated from `npm start` from the `website/` directory.

**Comment by juliemr** [comment]
This is now much better with https://github.com/angular/protractor/pull/4040

There's still some errors which are probably due to old versions, but the script actually runs now.

**Comment by sjelin** [comment]
Closing since it does actually work, even if there are some very ugly warnings on mac (they're due to old dependencies anyway).
