### ISSUE TITLE
Documentation - Broken links in Choosing a Framework section 

### ISSUE THREAD

**Issue by rajesh825** [angular/protractor#3671]
Hello, 
Few broken links present in "Choosing a Framework " Documentation 
 (http://www.protractortest.org/#/frameworks. ).  

Please refer to the screenshot for further reference.

![protractor_documentation_brokenlinks](https://cloud.githubusercontent.com/assets/5097539/19762888/af5cafc8-9c33-11e6-9b11-1cf0e2542fc9.png)

Thanks in advance.

**Comment by sjelin** [comment]
Once @cnishina reviews #3674 and we get this merged in this might be fixed
