### ISSUE TITLE
Tests failing due to timeout as browser.getTitle() does not resolve

### ISSUE THREAD

**Issue by navalkgupta** [angular/protractor#3673]
I am using protractor 4.0.10 version and trying to run tests on chrome version 2.54 with binary version 2.25 and Selenium standalone version 2.53.1

Protractor test is not able to resolve browser.getTitle() even after 15 seconds of page loaded.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
