### ISSUE TITLE
browser.restart() hangs

### ISSUE THREAD

**Issue by mwsessom** [angular/protractor#3676]
Protractor hangs on `browser.restart()` and never restarts the browser.

```
describe('Angular test', function() {
  it('Browser restart test', function() {
    browser.get("https://angularjs.org/");
    browser.restart();
  })
});
```

Output: `Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.`

Protractor 4.0.10
Chromedriver 2.25
Chrome 54.0.2840.71

**Comment by mwsessom** [comment]
Looks like using `browser.driver.get` instead of `browser.get` works.

**Comment by mgiambalvo** [comment]
Most likely, this is also caused by #3651 and related to #3677.
