### ISSUE TITLE
browser.wait() icoherent api vs documentation

### ISSUE THREAD

**Issue by pearljamik** [angular/protractor#3679]
Documentation states that `browser.wait()` is a **blocking call**. Whereas when using api, the `browser.wait()` is definitely not waiting for resolution, it continues execution. 

From documentation:

> See also ExpectedConditions
> 
> Example: Suppose you have a function, startTestServer, that returns a promise for when a server is ready for requests. You can block a WebDriver client on this promise with:
> Example
> Code
> 
> ```
> var started = startTestServer();
> browser.wait(started, 5 * 1000, 'Server should start within 5 seconds');
> browser.get(getServerUrl());
> ```

The actual behaviour is DIFFERENT !

Please correct the behaviour or the documentation since it is VERY misleading and this is BASCIC functionality people want to use. If you want Protractor to spreat this is VERY important of an issue.
## Bug report
- Node Version: ``
- Protractor Version: `4.0.9`
- Angular Version: `2.0`
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)
## Feature Request
- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by NickTomlin** [comment]
Could you clarify by what you mean by 

> Whereas when using api, the browser.wait() is definitely not waiting for resolution

`browser.wait` will pause execution of the webdriver flow until the timeout or the condition is satisfied. Without knowing what `startTestServer` returns it's hard to understand what is going on here but I suspect it is an issue in that funciton. 

Could you provide a clear reproducible example repo that isolates this?

**Comment by sjelin** [comment]
I think he means it doesn't block js execution, only control flow execution.  Which is probably confusing.
