### ISSUE TITLE
frequent and intermittent no injector found for element argument to getTestability issues

### ISSUE THREAD

**Issue by umagsfx** [angular/protractor#3681]
Hi, 

I am facing the following issue while running the protractor but I could see some of the specs are passing and some of them are failing because of the below one. 

Any thoughts?

[Chrome #01-11]     Failed: unknown error: [ng:test] no injector found for element argument to getTestability
[Chrome #01-11]     http://errors.angularjs.org/1.3.18/ng/test
[Chrome #01-11]       (Session info: chrome=53.0.2785.89)
[Chrome #01-11]       (Driver info: chromedriver=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
[Chrome #01-11]     Command duration or timeout: 8 milliseconds
[Chrome #01-11]     Build info: version: '2.51.0', revision: '1af067d', time: '2016-02-05 19:15:17'
[Chrome #01-11]     System info: host: 'mac-208-52-180-143.browserstack.com', ip: '208.52.180.143', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_51'
[Chrome #01-11]     Driver info: org.openqa.selenium.chrome.ChromeDriver
[Chrome #01-11]     Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.24.417412 (ac882d3ce7c0d99292439bf3405780058fcca0a6), userDataDir=/var/folders/3y/zz_w6_s56sl__vcrf3r5bhzr0000hr/T/.org.chromium.Chromium.T45tzS}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=53.0.2785.89, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
[Chrome #01-11]     Session ID: 675bf7d7a4a92d9a0cb08fef33605a89

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
