### ISSUE TITLE
restartBrowserBetweenTests feature is not working in protractor 4.0.10 

### ISSUE THREAD

**Issue by mmraghavendra** [angular/protractor#3684]
I have tests as below. Test1 succeeds but Test2 which is same as Test1 always fails with below error (windows.angular is undefined) when restartBrowserBetweenTests is set to true in protractor conf file. Both the tests always pass when  restartBrowserBetweenTests is set to false in protractor conf file. 

Please look into this issue and suggest me solution for the same.

Also the error is very confusing saying windows.angular is undefined when we are already setting browser.ignoreSynchronization=true at the beginning of the test.
# Error

Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"
# spec.js

describe('github homepage', function() {
    it('Test1', function() {
        browser.ignoreSynchronization=true;
        browser.get("https://github.com/");
        element(by.xpath("//input[@aria-label='Search GitHub']")).sendKeys('myrepo');
        browser.sleep(5000);  
    });

```
it('Test2', function() {
    browser.ignoreSynchronization=true;
    browser.get("https://github.com/");
    element(by.xpath("//input[@aria-label='Search GitHub']")).sendKeys('myrepo');
    browser.sleep(5000);
});
```

});

**Comment by Harsha509** [comment]
Hi There,

Facing the similar issue. **restartBrowserBetweenTests feature is not working in protractor 4.0.10**

**Comment by NickTomlin** [comment]
This looks like it's covered by https://github.com/angular/protractor/issues/3677#issuecomment-257665556 I'm going to close this to consolidate. Feel free to follow up there!
