### ISSUE TITLE
Support setting `SELENIUM_PROMISE_MANAGER` flag via the config

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#3691]
See https://github.com/SeleniumHQ/selenium/issues/2969

Impossible until they finish phase 1 and we finish https://github.com/angular/protractor/issues/3689

**Comment by cletusw** [comment]
Selenium's phase 1 is [now complete](https://github.com/SeleniumHQ/selenium/issues/2969#issuecomment-258234966).

**Comment by sjelin** [comment]
Blocked on https://github.com/angular/protractor/issues/3689

**Comment by petrkoutnysw** [comment]
#3689 closed
