### ISSUE TITLE
UnknownError: Connection reset

### ISSUE THREAD

**Issue by AniLau** [angular/protractor#3695]
Hi there!

I'm not able to run my test cases in protractor.

It opens chrome window but  then it crashes.

![image](https://cloud.githubusercontent.com/assets/3926551/19949737/114c925e-a119-11e6-83bf-113e2eed896e.png)

I hope you can help me.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
