### ISSUE TITLE
How can protractor be used to test code coverage?

### ISSUE THREAD

**Issue by hsunami** [angular/protractor#370]

**Comment by chetanladdha** [comment]
@r3b : Does your plugin works with angular types script files?

**Comment by svanishree** [comment]
@r3b @chetanladdha  can one of you please tell if the grunt-protractor-coverage works with angular type script files.?

**Comment by evilaliv3** [comment]
@r3b: from my tests withing the @GlobaLeaks project currently your plugin do not work with protractor 6 / selenium 5 specifically in relation  to "async" functions that appear to not be defined.

@chetanladdha  / @svanishree: maybe some of you have already identified a solution?

@cnishina, @juliemr: by any chance do you have a working recipe for collecting coverage on protractor 6?

thank you!

**Comment by chetanladdha** [comment]
I got a solution to one of my StackOverflow question. As per answer, a person found the solution.
https://stackoverflow.com/questions/50351276/code-coverage-for-protractor-tests-in-angular-5-application/56910948#56910948

**Comment by evilaliv3** [comment]
Thank you @chetanladdha, actually i tried to use the same solution but i encountered this issue: https://github.com/istanbuljs/nyc/issues/1117

In the end I managed to managed to handle this using an inline plugin defining postTest and using the onComplete callback: https://github.com/globaleaks/GlobaLeaks/blob/master/client/tests/protractor-coverage.config.js

@cnishina sjelin: i think that this could be recommended as a solution in the documentation.
