### ISSUE TITLE
Update to selenium webdriver 3.0.0

### ISSUE THREAD

**Issue by evilaliv3** [angular/protractor#3703]
The new stable release of selenium declare to support more native and up to date drivers.

In particular include the support required for testing version of firefox > 48

reference: https://github.com/SeleniumHQ/selenium/blob/master/dotnet/CHANGELOG

**Comment by cletusw** [comment]
Biggest change is the addition of the [`SELENIUM_PROMISE_MANAGER ` environment variable](https://github.com/SeleniumHQ/selenium/issues/2969#issuecomment-258234966), which allows disabling the proprietary Promise manager. This has been the cause of many headaches, and I would love to get a version of protractor that also works without it.

**Comment by cletusw** [comment]
This depends on #3689 and #3691
