### ISSUE TITLE
Increase wait time for various things (details inside)

### ISSUE THREAD

**Issue by szluzero** [angular/protractor#3708]
Hi, I am running protractor tests on SauceLabs, and it appears that because of the latency the first page of my tests occasionally doesn't load in time for the timeout. Because of this I get "Angular could not be found" or "Timed out waiting for Protractor to sync with the page" errors. It seems that I can fix this by increasing the wait times in configParser in protractor in node_modules, but that's only a fix for manually running tests on SauceLabs. Is it possible to implement a way (maybe in the protractor.conf.js) to increase those timeout times from outside node_modules?

Relevant information:
- Node Version: `4.2.1`
- Protractor Version: `3.1.1`
- Angular Version: `1.5.0`
- Browser(s): `Chrome, Firefox, IE10, IE11`
- Operating System and Version `Windows 7, Windows 10`

EDIT: Actually it turns out that I still get "Angular could not be found" even after increasing the timeout values in configParser. Is there another file I need to change the timeout? It also sometimes says "retries looking for angular exceeded", is there a way to keep retrying until a certain timeout period?

**Comment by cnishina** [comment]
Refer to http://www.protractortest.org/#/timeouts

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
