### ISSUE TITLE
docs: document `$` and `$$`

### ISSUE THREAD

**Issue by thorn0** [angular/protractor#3709]
The fact that there is no documentation for these shortcuts causes confusion: [an example](http://stackoverflow.com/questions/36791397/selector-in-protractor).

Or are they not documented intentionally?

**Comment by cnishina** [comment]
But these are documented:


- http://www.protractortest.org/#/api?view=ElementFinder.prototype.$
- http://www.protractortest.org/#/api?view=ElementFinder.prototype.$$

If you want to update these with better documentation, feel free to send us a PR. Since this is documented, I'm going to close this.

**Comment by thorn0** [comment]
> But these are documented

I don't mean these ones. I mean the global ones.

**Comment by cnishina** [comment]
Those are the same.

**Comment by thorn0** [comment]
> Those are the same.

To some extent, we can say this about any two things in the world. :)

But really, how are they the same if those I refer to are methods of `browser` , `protractor`, and even `global`, whereas yours are of `ElementFinder`? If something is documented as a method of `ElementFinder`, it's very not obvious that you can call it as a global. Moreover, for some reason, in all the code examples we can see `element(by.css(...))`, not `$(...)`. That's why even for those who know about the existence of these shortcuts it looks like their usage is discouraged, deprecated or something like that. That's why I asked whether they're not documented intentionally.
