### ISSUE TITLE
Getting Browser died out error on clicking a Submit button on chrome driver

### ISSUE THREAD

**Issue by sandybk** [angular/protractor#3712]
Hi there!
Am working on an Angular JS application. I have search page in which i select a search condition and click on Search. After clicking search am getting the below error. The script was working initially when ng-click was being used for this button. It was changed to form submit and am getting error after this change

....[14:19:45] W/element - more than one element found for locator By(css selector, [ng-click="vm.clear()"]) - the first result will be used
.F[14:19:50] E/launcher - Error communicating with the remote browser. It may have died.
Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: host: '1K84LC2', ip: '10.92.244.181', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: RemoteWebDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.24.417431 (9aea000394714d2fbb20
850021f6204f2256b9cf), userDataDir=C:\Users\z063544\AppData\Local\Temp\scoped_dir11396_17241}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true,
 hasTouchScreen=false, version=54.0.2840.71, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, bro
wserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 56804b261dd799397c8869e1307f6ec0

**Comment by cnishina** [comment]
It looks like you should upgrade your chromedriver to the latest.

This also looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
