### ISSUE TITLE
How to know where the file is saved or the back ground process happening when we are using phantomjs with selinium.

### ISSUE THREAD

**Issue by pavanvak** [angular/protractor#3728]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by pavanvak** [comment]
here is my code:
package com.sample;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriverService;
import org.openqa.selenium.remote.DesiredCapabilities;


public class Sample {
	
public static void main(String[] args) throws InterruptedException {
	
	
	DesiredCapabilities caps = new DesiredCapabilities();
	caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY,
	                "C:\\Users\\360035\\Desktop\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe");                  
WebDriver driver = new PhantomJSDriver(caps);
	

	
driver.get("https://metconnect.cognizant.com/sites/MetConnect/IB-PST/Governance/Forms/Allitems.aspx?RootFolder=%2Fsites%2FMetConnect%2FIB-PST%2FGovernance%2FSteady%20State%2FOperational%20Services%2F02%2EEIOB%2F02%2EHW%20and%20SW%20Upgrade%20Distributed%2F10%2EUDB%20Upgrade%2FUDB%20Upgrade%20App%20list&SortField=LinkFilename&SortDir=Asc&View=%7b08D6B542-CB51-49F5-B347-32F5500FD292%7d");
Thread.sleep(5000);



driver.findElement(By.xpath("//*[@id='100316']/tbody/tr/td[1]/a")).click();
Thread.sleep(5000);

driver.findElement(By.xpath("//*[@id='100334']/tbody/tr/td[1]/a")).click();	

Thread.sleep(2000);

**Comment by pavanvak** [comment]
Please help me

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
