### ISSUE TITLE
Async/await helper function

### ISSUE THREAD

**Issue by nerumo** [angular/protractor#3734]
Hi there!

I have a proposal for a little helper function around the async/await pattern. Since jasmine is not awaiting everything async by default (at least not without monkey patching like in angular 2). So I must use the done callback. So I end up writing the same code again and again with the following structure:
```javascript
it('should do something', async (done)=>{
  await myCoolAsyncFunction();
  done();
}
```

But if somewhere I get an exception in the async stack, `done()` will never be called and the test never completes until timeout. So I came up with 

```javascript
try {
      await myCoolAsyncFunction();
      done();
    } catch (err) {
      fail(err);
      done();
    }
```

This is then the basic code for every spec I write. So I put it together in a helper method:

```javascript
export function wait(assertion: () => Promise<any>) {
  return async (done) => {
    try {
      await assertion();
      done();
    } catch (err) {
      fail(err);
      done();
    }

  }
}
```

And a corresponding test would look like:

```javascript
it('should do something', wait(async ()=> {
  await myCoolAsyncFunction();
}));
```

What are you thinking about this?

**Comment by juliemr** [comment]
You can return the last `await`, and because we already patch Jasmine to understand returned promises, it will work. So test could look like:

```js
it('should do something', async () => {
  return await myCoolAsyncFunction();
});
```
and it'll work properly.

I think this is simpler than adding a new helper. Does it fulfill your needs?

**Comment by nerumo** [comment]
Ah great, didn't know that it's already patched. I tested it for the full project, everything working fine. I think we can close this discussion, thank you
