### ISSUE TITLE
routerLink doesn't work in e2e test using protractor in angular2

### ISSUE THREAD

**Issue by Bhushan001** [angular/protractor#3735]
- Node Version: `6.9.1`
- Protractor Version: `4.0.5`
- Angular Version: `2.0.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 7 x64`

I have this angular2 routerLink which allows user to navigate to editComponent by passing userId as parameter.

    <a [routerLink]="['/edit',user._id]" (click)="returnUser(user._id)" id="redirect" class="btn" name="user-{{i}}">
        <i class="fa fa-eye fa-fw"></i>
    </a>

I want to test this using protractor, but When I am running my e2e test.after executing click event this link is not redirecting to editComponent.

Following is my test:

    it('should redirect to edit', () => {
    element(by.id("redirect")).evaluate("user._id").then(
      function (userId) {
        browser.get('/edit/' + userId);
        browser.waitForAngular();
      }, function (err) {
        console.log(err);
      })
    });

Also I am getting below error:

> asynchronous script timeout: result was not received in 30 seconds

what am I doing wrong here?

any inputs?

thanks

**Comment by juliemr** [comment]
Which step is timing out? Your test doesn't actually include a click event.

**Comment by sjelin** [comment]
(removing `untriaged` since there's really nothing we can do until he gives us some information)

**Comment by juliemr** [comment]
Haven't heard back, closing issue as stale.
