### ISSUE TITLE
Protractor, after 20 clicks have a  Async callback error

### ISSUE THREAD

**Issue by nomid0612** [angular/protractor#3740]
I need to wait until the item will be 'completed' status
there is my 'it'
it(" should be competed generated report", function(){
        let refreshButton = element(by.buttonText('Refresh'));
        let queuedStatus = element.all(by.cssContainingText('.ui-grid-cell-contents.ng-binding.ng-scope.ng-isolate-scope','Queued')).get(0);
        let generatingStatus = element.all(by.cssContainingText('.ui-grid-cell-contents.ng-binding.ng-scope.ng-isolate-scope','Generating')).get(0);
        function waitgoodstatus(promise) {
            refreshButton.click();
            browser.params.wait(element(by.css('.ui-grid')));

            promise.isPresent().then(function(result){
                if (result){
                    waitgoodstatus(promise);
                }else {
                    waitgoodstatus(generatingStatus);
                }
         }).catch(function(er){
                    waitgoodstatus(generatingStatus);
            }
            )
        }
        waitgoodstatus(queuedStatus);

    })

it works, but after 20 clicks i have such error - Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
Set defaultTimeoutInterval is not helped

Any suggestions?

**Comment by juliemr** [comment]
Please take a look at http://www.protractortest.org/#/timeouts and in the future, the issue tracker is reserved for bugs and feature requests.

**Comment by nomid0612** [comment]
thanks @juliemr , but i've already specify jasmine.DEFAULT_TIMEOUT_INTERVAL.
Timeout - Async callback was not invoked within timeout specified by 
jasmine.DEFAULT_TIMEOUT_INTERVAL.
jasmineNodeOpts: {
        defaultTimeoutInterval: 30000,
         print: function() {}
    }
