### ISSUE TITLE
Idea: Table Driven Tests

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#3745]
Over the weekend I talked to some Go programmers about table driven tests: https://github.com/golang/go/wiki/TableDrivenTests

Those guys really loved them!  They're better suited for unit tests, and more functional code, but we could imagine something similar.  For instance, our [example spec](https://github.com/angular/protractor/blob/7da9c3a910bb000b30bf9ba82ef48c64bd751709/example/example_spec.js) might look like:

```ts
export let Tests = [{
  url: 'https://angularjs.org/', // Alternately, an `init` function
  tests: [
    {
      setup: [
        sendKeys('module=yourName', 'Julie')
      ],
      verify: [
        equals(getText('binding=yourName'), 'Hello Julie!')
      ]
    },
    {
      setup: [],
      verify: [
        equals(count('repeater=todo in todoList.todos'), 2),
        equals(getText('(repeater=todo in todoList.todos)[0]'), 'build an angular app')
      ]
    },
    {
      setup: [
        sendKeys('module=todoList.todoText', 'Julie'),
        click('[value="add"]')
      ],
      verify: [
        equals(count('repeater=todo in todoList.todos'), 3),
        equals(getText('(repeater=todo in todoList.todos)[0]'), 'write a protractor test')
      ]
    },
  ]
}];
```

This would be a custom test framework.  It would probably have limited functionality, and probably most large projects would not be able to write all their e2e tests this way.

**Comment by sjelin** [comment]
Users, let me know if this is something you'd be interested in!

**Comment by mattbrunetti** [comment]
What makes them better suited for unit tests?

Note on your example: It would be impossible to write tests that first do some setup, then some assertions/verifications, then some more setup on top of that, and then more assertions.

**Comment by sjelin** [comment]
It's better for unit tests because you can call the functions directly, so the inputs/outputs are simpler.  If you translate the Go example to js you'd get something like:

```js
tests = [
    args1, val1,
    args2, val2,
    args3, val3,
    ...
];

for (var i = 0; i + 2 <= tests.length; i += 2) {
  expect(f.call(this, tests[i]).toBe(tests[i+1]);
}
```

It's definitely the case that you could verify, do some setup, and then verify some more.  This kind of structure allows you to write some kinds of tests quickly and clearly, but is also very limiting.  I suspect most large projects could write a majority of their tests this way, but would have to write some of their tests using a more sophisticated framework (e.g. jasmine).

**Comment by sjelin** [comment]
Not enough user interest in this idea
