### ISSUE TITLE
TimeOut While waiting for element with locator

### ISSUE THREAD

**Issue by Bhushan001** [angular/protractor#3749]
I am trying to test below code:

    `
    <div name="userElem" *ngFor="let user of users ; let i=index">
        <div class="list-group-item" id="user-{{i}}" (click)='selectUser(user)' [style.backgroundColor]="user?._id==selectedUser?._id ? '#F0F0EE' : 'white'">
            <div *ngIf="user?._id==selectedUser?._id">      
                <div class="pull-right">        
                    <a  id="delete-user-{{i}}" (click)="deleteUser(user._id)">  
                        <i class="fa fa-trash fa-fw"></i>
                    </a>
                    <a  (click)="editUser(user._id)">
                       <i class="fa fa-pencil fa-fw"></i>
                    </a>
                    <a [routerLink]="['/edit',user._id]" name="userLink-{{i}}">
                        <i class="fa fa-eye fa-fw"></i>
                     </a>
                 </div>
              </div>
            </div>
        </div>`

By Using Below E2E Test Case:

    `
    it('should delete a user', () => {
        page.navigateToUserComponent();  
        let selectUserElem = element(by.id('user-0')).click();   //this event is fired as I can see user getting selected.    
        let deleteUserElem = element(by.id('delete-user-0'));    
        browser.wait(function() {
            return browser.isElementPresent(by.id('delete-user-0'));
        }, 5000);
        expect(deleteUserElem.isPresent()).toBeTruthy();  // if element is present I want to click that element .i.e. delete the first user in array
      });
`

But So Far Not Getting Any Success.

I tried Multiple Approaches as discussed in this link:

[StackOverflow Post](http://stackoverflow.com/questions/34561999/protractor-cant-click-on-embedded-span-inside-a-element)

But Couldn't make it work.
any help?

Thanks

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

Without information on which step is timing out it's hard to debug. Please open up a new SO post!
