### ISSUE TITLE
Firefox 50 and latest protractor/selenium. Timeout issues.

### ISSUE THREAD

**Issue by inthegarage** [angular/protractor#3750]
I've decided to see what was happening with Firefox 50, latest selenium and protractor
Here are my versions. 
- Node Version: v5.10.1
- Protractor Version: 4.0.11
- Angular Version: 1.4.9
- Browser(s): Firefox 50
- Operating System and Version Windows 10
- Selenium 3.0.1
- Firefox driver: 0.11.1 (gecko driver)
When I use the same test framework on Chrome or Internet explorer, everything just runs fine in my test
However when I use Firefox 50, I get many timeout related errors:

Failed: Error while waiting for Protractor to sync with the page: "[ng:test] http://errors.angularjs.org/1.4.7/ng/test"
Or
Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined

The place where you get these errors seems to be random.

The tests are the same for all browsers, my capabilities are as follows from the test file:

        capabilities: {
            'browserName': 'firefox',
            marionette : true,
        }

What is the current status of Firefox and Protractor? Is it supported?  Do I need any other options or different versions?

**Comment by juliemr** [comment]
FireFox support is definitely in flux at the moment. Please see http://www.protractortest.org/#/browser-support - we still recommend firefox 47. 

Behind the scenes - we're also still trying to figure out how to support geckodriver with firefox for versions higher than 48.

**Comment by inthegarage** [comment]
Hi Julie,

Thanks for the reply. Firefox 50 with the above framework seems much more stable then 49 say and other variants. This seems very close now and my tests *nearly* worked. 
It would appear that there just needs to be some tweaking to do, possibly in the Protractor side, but I'm not expert as to where the problem may actually lie.
Shall I keep this ticket open so we can track progress, or is that mechanism really reflected in the link you provided?

**Comment by sjelin** [comment]
(assigning to you @mgiambalvo because I didn't assign many over issues to you, and I feel like I need to balance)

**Comment by commutecat** [comment]
To mitigate the incompatibilities of Firefox multi-process architecture with any web testing tools , use Firefox ESR. 
https://www.mozilla.org/en-US/firefox/45.3.0/releasenotes/

**Comment by inthegarage** [comment]
Although that certainly tests any software on Firefox, it doesn't test it on 50+, that is what most users will be using and more importantly what most customers will require.
I will raise this issue with Selenium as suggested, although currently the issue(s) seems to be in both products.

**Comment by mgiambalvo** [comment]
Firefox 50 has [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1297551) that affects timeouts in webdriver injected scripts. This bug has been fixed, and we should support testing in Firefox 51+

**Comment by hymau** [comment]
I was struggling hard to find a solution to the FF execution and finally got it working today.
Please find the versions which worked on my end.
Mac OSX: Sierra v10.12
FF: 53 beta
Selenium Standalone jar: 3.3.1
Protractor: v 5.1.1
Config file:
{
   "browserName": "firefox",
   "marionette":true,
}
Hope this helps :)

**Comment by erved** [comment]
Hey ! juliemr,
I am trying to run protractor on firefox 47 but it doesn't make any sense.

**Comment by inthegarage** [comment]
@erved Firefox47-51ish doesn't work with protractor. Don't even bother trying. Either use Firefox ESR 45. or  the latest version.

**Comment by wswebcreation** [comment]
@erved ,

Please don't address questions directly to members. We all try to check the issue list.

By the way. FF 47 should work, only with the old driver, secondly also with Selenium 2.53 and not with Selenium 3.x.

**Comment by samsul-kabir** [comment]
Hi there,

I have tried different version of firefox and unfortunately none of them worked. Everytime i running my code, its throwing the following error:

```
[15:41:09] E/launcher - Unable to find a matching set of capabilities
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'trv2457.local', ip: '2001:920:1841:10:ac95:6fb8:a651:b9d5', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_111'
Driver info: driver.version: FirefoxDriver
remote stacktrace: stack backtrace:
   0:        0x10aad754e - backtrace::backtrace::trace::hc694823f3e7463c0
   1:        0x10aad76ec - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:        0x10aa6f3af - geckodriver::marionette::MarionetteHandler::create_connection::hfc7af8bf299cf57b
   3:        0x10aa4a707 - _$LT$webdriver..server..Dispatcher$LT$T$C$$u20$U$GT$$GT$::run::h03bbbfe904a992bd
   4:        0x10aa30c97 - std::panicking::try::do_call::he6fd7abc59b6b346
   5:        0x10abf44ba - __rust_maybe_catch_panic
   6:        0x10aa4100c - _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h8e002f7c448fbabb
   7:        0x10abf0684 - std::sys::imp::thread::Thread::new::thread_start::hba7593f2e1f1beb1
   8:     0x7fff9c77093a - _pthread_body
   9:     0x7fff9c770886 - _pthread_start
```

Version that I have
```
protractor@5.1.2
selenium-webdriver@3.0.1
Mac os x: 10.12.6
```

**Comment by inthegarage** [comment]
The web driver looks a little out of date, check here: http://www.seleniumhq.org/download/

**Comment by samsul-kabir** [comment]
@inthegarage I have update webdriver using following command:

`webdriver-manager update`

what would be the best way to update it?

**Comment by inthegarage** [comment]
That's probably the best way, you can check if it matches the version on the list. You'd suspect its probably a Mac issue.

**Comment by wswebcreation** [comment]
Hi @samsul-kabir 

Does it work with a the simple [example](https://github.com/angular/protractor/tree/master/example) script from protractor on FireFox? I don't have any issues here with firefox.

**Comment by kalesha67** [comment]
Hi,

any solution to below error:

 E/launcher - Error: Error: The wires.exe executable could not be foun
d on the current PATH. Please download the latest version from https://developer
.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver and ensure it can be fou
nd on your PATH.

**Comment by inthegarage** [comment]
@kalesha67 did you follow the instructions on the link? https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver
