### ISSUE TITLE
Error while running the spec with error window.angular is undefined

### ISSUE THREAD

**Issue by Ashishpb1** [angular/protractor#3752]
Hi,
I am getting below error while running the spec.
[13:16:11] E/launcher - Error while waiting for Protractor to sync with the page: "wind
ow.angular is undefined.  This could be either because this is a non-angular page or be
cause your test involves client-side navigation, which can interfere with Protractor's
bootstrapping.  See http://git.io/v4gXM for details"

Below id the code snippet used:

describe('Add physical model for salesforce', function() {
  'use strict';

  var loginPage = new login.LoginPage();
  var mainPage = new main.MainPage();
  var repositoryPage = new main.RepositoryPage();
  var url  = 'http://152.144.226.182:8080/metadatamanager/#/login';   
  var ConType = element(by.id('connection-type-select'));
  var SalesforceType = element(by.xpath('.//select[@name="dataSourceType"]/option[7]'));
  var ConName =element(by.id('connection-name-select'));
  var connection1 = element(by.xpath('.//select[@name="dataSourceName"]/option[2]'));	   
  var Fetch = element(by.id('fetch-button'));
  var check = element(by.xpath('.//input[@type="checkbox"]'));
  
  
  
  it('should login to homepage', function() {
	  
	  browser.get(url);
	    loginPage.username('admin').password('admin').login();
	    expect(browser.getLocationAbsUrl()).toContain('/addPhysicalModel');
	  });

browser : firefox
Please provide resolution

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by koneti123** [comment]
Non-Angular Test Login->Non-Angular Menu link -> Angular Page

Frustrated with this issue from last 1 week. Appreciate Immediate help.

1. My beforeEach() method
 beforeEach(function (done) {
       jasmine.DEFAULT_TIMEOUT_INTERVAL = 80000;
       setTimeout(function () {
           // console.log('inside timeout');
           done();
       }, 500);
    });

2. My It() section

// This url loads Non-Angular Page
     browser.driver.get('http://10.5.3.146:7070/napier-his-web/index.html');
     
      browser.driver.sleep(500);
     console.debug('Running URL----')
    // browser.driver.ignoreSynchronization = true;
    //  browser.driver.sleep(6000); 
        
        browser.driver.findElement(by.id('username')).sendKeys('admin1');
        browser.driver.findElement(by.id('username')).sendKeys(protractor.Key.TAB);
     
        browser.driver.findElement(by.id('password')).sendKeys('User@1');
        browser.driver.findElement(by.id('password')).sendKeys(protractor.Key.TAB);
      
        browser.driver.findElement(by.id('login_submit_frm')).click();
     
        browser.driver.findElement(by.id('button-1006-btnIconEl')).click();
        browser.driver.findElement(by.id('nptopmenu-menu-trigger-btnIconEl')).click();
            
        browser.driver.findElement(by.id('menuitem-1183-itemEl')).click();
      
        // The above clicks loads Angular page   
        browser.driver.sleep(5000);
     
       browser.ignoreSynchronization = true;
       browser.waitForAngular();
       browser.sleep(500); 
     
     
     // This is Angular Page elements
     var ele = element(by.model('OPVMsearchBypatient'));
     
    browser.driver.wait(function() {
                ele.sendKeys('Hello world');
               return true;
  }, 60000);

Any suggestions Plz....

**Comment by koneti123** [comment]
Small correction.

browser.ignoreSynchronization = false;
       browser.waitForAngular();
       browser.sleep(500);

**Comment by wswebcreation** [comment]
Hi @koneti123 

This is a closed issue. Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I can then try to help you there

Thanks!

**Comment by diegoalberto** [comment]
This was fixed in my case by updating to protractor 5.2.0
