### ISSUE TITLE
How to validate if element is non-editable.

### ISSUE THREAD

**Issue by deemash** [angular/protractor#3753]
Hi All,

I have a strange case to validate if a particular element is non-editable.
Unfortunately, this is a label element and hence it is non-editable.
So .isEnabled() always returns true and my test case is failing.

How to handle this situation to see if this element is non-editable.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
