### ISSUE TITLE
sendKeys() not sending space character

### ISSUE THREAD

**Issue by DarthOpto** [angular/protractor#3757]
When I run the test below, the space character, is removed from the `Test Title` string
---

- Node Version: `7.0.0`
- Protractor Version: `4.0.9`
- Browser(s): `Chrome v. 54`
- Operating System and Version `Windows 10`
- Your protractor configuration file
[protractor.config.js.zip](https://github.com/angular/protractor/files/604386/protractor.config.js.zip)

- 
```
 /// <reference path="../../reference.d.ts" />

import { CommonPageItems } from './../../../../test/e2e/common.page';
import { LoginPage } from './../../../auth-app/login/tests/login.page';
import { NavigationPage } from './../../navigation/tests/navigation.page';
import { ExplorationView } from './exploration.page';
import { ListView } from '../../../../test/e2e/listView.page';


const _ = require('lodash');

describe('create explorations', () => {
    let common = new CommonPageItems();
    let explorePage = new ExplorationView();
    let loginPage = new LoginPage();
    let navPage = new NavigationPage();
    let exploreList = new ListView();
    let params = require('./../../../../test/e2e/common.params')();
    let hotkeys = require('protractor-hotkeys');
    let longTitle = '01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'

    beforeAll(() => {
        loginPage.login(params.users.superUser.email, params.users.superUser.password)
        common.navigationOpenByHotKey();
        navPage.navigateToApp(params.apps.explorations.navLink)
    });

    afterAll(() => {
        common.signOut();
    });

    it('click new Exploration', () => {
        exploreList.newItem().then(() => {
            expect(explorePage.breakdownsBtn.isDisplayed()).toBe(true);
        });
        explorePage.exploreLink.click();
    });

    fit('Add a Title', () => {
        exploreList.newItem().then(() => {
            explorePage.addTitle('Test Title');
            expect(explorePage.saveBtn.isEnabled()).toBe(true);
        });
    });

});
```

The `addTitle()` method is below:

```
    addTitle(title: string) {
        this.titleField.click();
        this.titleField.clear().then(() => {
            this.titleField.sendKeys(title)
        });
    }
```
- The `Test Title` is changed to `TestTitle` with no space

**Comment by cnishina** [comment]
This is not reproducible. See the following example:

config.js

```
exports.config = {
  directConnect: true,
  specs: ['spec.js']
}
```

spec.js
```
describe('inputs', () => {
  beforeEach(() => {
    browser.get('http://www.protractortest.org/testapp/ng1/#/form');
  });

  it('should send keys with spaces', () => {
    let username = element(by.model('username'));
    let text = 'foo bar the great, with spaces';
    username.click();
    username.clear();
    username.sendKeys(text);

    // expect the attribute to be the text
    expect(username.getAttribute('value')).toBe(text);

    // alternatively to checking with expects, use browser.pause to manually check
    // browser.pause();
  });
});
```

There could be some logic in your title field that removes spaces.

**Comment by DarthOpto** [comment]
Nice try, but I can manually type the value and the spaces are not removed. This only happens when using the sendKeys() call.

**Comment by cnishina** [comment]
As said above, this is not reproducible. Please run the above test. The spaces are maintained. If you feel like this is a bug with Protractor, feel free to open another issue or ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by nidhisrireddyattr** [comment]
Facing the same issue. But it is not consistent. 

Is there any resolution for this?

We have already set the below attribute to "false". But facing the same issue (inconsistent)

browser.ignoreSynchronization = false;

any help
