### ISSUE TITLE
chromedriver initialization failure logging

### ISSUE THREAD

**Issue by edzius** [angular/protractor#3760]
Hi there!

The problem i was facing that protractor with "chrome" was not working -- event browser process is not spawned. (Firefox is OK)

While running using selenium, i get exception:

> [13:28:45] I/local - Starting selenium standalone server...
> [13:28:45] I/launcher - Running 1 instances of WebDriver
> [13:28:45] I/local - Selenium standalone server started at http://192.168.2.137:37006/wd/hub
> [13:29:05] E/launcher - null
> [13:29:05] E/launcher - WebDriverError: null
> [13:29:05] E/launcher - Process exited with error code 199

When running with "directConnect" enabled, i get exception:

> [13:31:21] I/direct - Using ChromeDriver directly...
> [13:31:21] I/launcher - Running 1 instances of WebDriver
> [13:31:21] E/launcher - Server terminated early with status 127
> [13:31:21] E/launcher - Error: Server terminated early with status 127
> [13:31:21] E/launcher - Process exited with error code 199

After a while debugging i found out that manually started chromedriver is missing shared libraries:

> $ ./node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25
> ./node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Exceptions aren't self-explanatory, and without diving into protractor's code there is almost impossible to guess what's happening. Google gives no results unless searched explicitly for missing library:

http://stackoverflow.com/questions/22258709/how-to-run-protractor-to-validate-chrome-on-aws
https://gist.github.com/alonisser/11192482

I suggest to add some logging when such chromedriver startup failures occur or at least list update selenium/chromedriver setup wiki page with libraries prerequisites.

- Node Version: `v7.1.0`
- Protractor Version: `4.0.11`
- Operating System and Version `Arch Linux version 4.8.6-1-ARCH`

Thanks,
Edvinas

**Comment by cnishina** [comment]
This sounds like a setup problem for Arch Linux and you'll need to install `libgconf-2.so.4`. A quick search on StackOverflow shows people with similar issues. http://stackoverflow.com/questions/37624225/shared-libraries-libgconf-2-so-4-is-missing

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by edzius** [comment]
Yes it is, i realized that when i started chromedriver manually.

You misunderstood me, i don't want you to help me solve my problem. I want to improve protractor so that other users could easily deal with such cases in future. I think chromedriver (maybe and other binaries) requires more detailed logging, because errors "WebDriverError: null" and "Error: Server terminated early with status 127" does not provide enough information why execution failed. Google/stackoverflow could help once you know that "libgconf-2.so.4" is missing.

Regards,
Edvinas

**Comment by jkuri** [comment]
this worked for me on Ubuntu 17.10:
```sh
sudo apt-get install libgconf2-dev -y
```

**Comment by AlecBenzer** [comment]
Super +1 to @edzius, `"WebDriverError: null"` isn't an acceptable error message.
