### ISSUE TITLE
Can you give me a clue?

### ISSUE THREAD

**Issue by anonomis** [angular/protractor#3762]
`  - Failed: unknown error: Element is not clickable at point (610, 1096). Other element would receive the click: <div class="player-progress-bar">...</div>`

What's up with these error messages? Why don't you tell me what element you tried to click or what line of code you were trying to execute? This is so annoying. I can't come up with any reason it's like this except laziness and/or plain evil.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
