### ISSUE TITLE
Unable to select first checkbox out of multiple checkbox available.

### ISSUE THREAD

**Issue by raghvendra-chourasia** [angular/protractor#3765]
I have a web application which has multiple checkboxes with certain text associated with it. HTML code looks like below.

```
<label ng-repeat="(key, value) in tables">
	<input type="checkbox" />
	<span> Text1 </span>
</label>
<label ng-repeat="(key, value) in tables">
	<input type="checkbox" />
	<span> Text2 </span>
</label>
<label ng-repeat="(key, value) in tables">
	<input type="checkbox" />
	<span> Text3 </span>
</label>
<label ng-repeat="(key, value) in tables">
	<input type="checkbox" />
	<span> Text4 </span>
</label>
<label ng-repeat="(key, value) in tables">
	<input type="checkbox" />
	<span> Text5 </span>
</label>

```
Now, I want change the status of checkbox based on the input provided by user. for that I have written a generic function, which looks like below.

	select_filters: function (filter_list) {
			element(by.repeater('(key, value) in tables')).isPresent().then( function (status) {
				if (status) {
					element.all(by.repeater('(key, value) in tables')).then( function (labels) {
						for (var idx=0 ; idx<labels.length ; idx++){
							var label = labels[idx];
							var span_ele = label.element(by.tagName('span'));
							span_ele.getText().then(function (txt) {
								var check_ele = label.element(by.tagName('input'));
								check_ele.isPresent().then( function (status) {
									if (status) {
										if (filter_list.indexOf(txt) > -1){
											browser.logger.info('select_filters: Filter "' + txt + '" was passed to select. Checking the checkbox.');
											check_ele.isSelected().then(function (selected) {
												if (selected) {
													browser.logger.info('select_filters: Filter "' + txt + '" is already Checked.');
												} else {
													browser.logger.info('select_filters: Filter "' + txt + '" is Un-Checked. Changing status to Checked for the same.');
													check_ele.isSelected().click();
													browser.logger.info('select_filters: Filter "' + txt + '" is Checked.');
												}
											});
										} else {
											browser.logger.info('select_filters: Filter "' + txt + '" was not passed to select. Un-Checking the checkbox.');
											check_ele.isSelected().then(function (selected) {
												if (selected) {
													browser.logger.info('select_filters: Filter "' + txt + '" is checked. Changing status to Un-Checked for the same.');
													check_ele.isSelected().click();
													browser.logger.info('select_filters: Filter "' + txt + '" is Un-Checked.');
												} else {
													browser.logger.info('select_filters: Filter "' + txt + '" is already Un-Checked.');
												}
											});
										}
									}
								});
							});
						}
					});
				}
			});
	},

**But instead of selecting checkbox within first or other label tag, it always select the last checkbox. whereas span element returns proper text which is there in the label.**

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by raghvendra-chourasia** [comment]
Problem got resolved using the forEach loop instead of normal for loop.

element.all(by.repeater('(key, value) in tables')).then( function (labels) {
    labels.forEach(function (label) {
         //Code here.
    });
});
