### ISSUE TITLE
Unable to call exported function within the same module.

### ISSUE THREAD

**Issue by raghvendra-chourasia** [angular/protractor#3768]
Hi,

I have written a export module using protractor. it has multiple function defined inside it.
Now, I want to call one of the exported function inside another function within the same module.
My module looks like  below.

_module.exports = {
    read_page_number_data: function {
        // code here
    },
    read_page_data: function {
        this.read_page_number_data().then(function () {
            // Code here.
        });
    },
}_

Now, when I run this code, I get below error.
###  **Failed: this.read_page_number_data is not a function**

I have tried all the options given in below question. still there is no success.

http://stackoverflow.com/questions/37440899/protractor-calling-an-exported-function-within-the-same-module

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
