### ISSUE TITLE
Browser automatically closing midtest

### ISSUE THREAD

**Issue by harman0093** [angular/protractor#3769]
I have been running a protractor test that closes mid test. I am using jasmine with protractor. The defaultTimeoutInterval is set to `defaultTimeoutInterval: 8000000`, the allScriptsTimeout is set to   `allScriptsTimeout: 10000000`. My tests take almost an hour to run for each it() statement. This is because they are waiting on certain objects to appear. When I increase some of my internal times to make the objects appear quicker, the browsers dont close. But this causes the tests to fail as I need to wait for an extended period of time. So what is happening is that the browsers are closing on their own, mid test. I have 4 browser instances running. I do not have browser.close() anywhere in my code and I do nothing to prompt them to close. This is the only error that I get:

```- Failed: Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.5', java.version: '1.8.0_73'
Driver info: driver.version: unknown```

I am running webdriver 2.24, newest version of chrome, with protractor version 4.0.9

This is what is causing to me to think that there is a bug somewhere in the codebase.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
