### ISSUE TITLE
Share spec files across multiCapabilities in protractor

### ISSUE THREAD

**Issue by Milan-kumar** [angular/protractor#3770]
How to share spec files across capabilities in protractor:

I tried following but rather than sharing testcases/specs its executing all the test across capabilities:

    exports.config = {
        shardTestFiles: true,
        maxSessions: 3,
        specs: ['./testExecution/UserManagement/Login/*.js'],
        verboseMultiSessions: true,
    multiCapabilities: [
             {
              browserName : 'internet explorer',
              seleniumAddress: 'http://localhost:4444/wd/hub'
             },
            {
              browserName : 'chrome',
              seleniumAddress: 'http://172.23.230.198:4444/wd/hub'         
            }
    ]
    }

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
