### ISSUE TITLE
Missing support for httpProxy?

### ISSUE THREAD

**Issue by finspin** [angular/protractor#3774]
The reference conf file doesn't list httpProxy capabilities https://github.com/angular/protractor/blob/master/lib/config.ts. Trying the below doesn't work. Also, passing any value to the `httpProxy` key passes the test which means that the `httpProxy` is probably ignored.

Is httpProxy still supported?

```
capabilities: {
    proxy: {
        proxyType: 'manual',
        httpProxy: 'host:port'
    }
}
```

Protractor Version 4.0.10

**Comment by cnishina** [comment]
Proxy is still supported. We just pass these capabilities to the server / driver provider. The config.ts is an interface that could have additional capabilities that are not listed, based on https://github.com/angular/protractor/blob/master/lib/config.ts#L239. When launching a browser, you could verify the capabilities are appearing.

get capabilities:
```
browser.getCapabilities().then(caps => {console.log(caps);});
```

console log:
```
Capabilities {
  'applicationCacheEnabled' => false,
  'rotatable' => false,
  'mobileEmulationEnabled' => false,
  'networkConnectionEnabled' => false,
  'chrome' => { chromedriverVersion: '2.25.426935 (820a95b0b81d33e42712f9198c215f703412e1a1)',
  userDataDir: '/var/folders/gx/4cw5vsyj4lx332w66xwdxwpm00b14w/T/.org.chromium.Chromium.eRNQJ1' },
  'takesHeapSnapshot' => true,
  'pageLoadStrategy' => 'normal',
  'databaseEnabled' => false,
  'handlesAlerts' => true,
  'hasTouchScreen' => false,
  'version' => '54.0.2840.98',
  'platform' => 'MAC',
  'browserConnectionEnabled' => false,
  'nativeEvents' => true,
  'acceptSslCerts' => true,
  'webdriver.remote.sessionid' => 'c2b95382-92d1-4d5b-8396-ebe336a0b2b0',
  'locationContextEnabled' => true,
  'webStorageEnabled' => true,
  'browserName' => 'chrome',
  'takesScreenshot' => true,
  'javascriptEnabled' => true,
  'cssSelectorsEnabled' => true }
```

**Comment by finspin** [comment]
I still can't get it to work. It seems to me like httpProxy capability is not passed onto webdriver. If I do this, the test still passes although it should fail on non-existent proxy. Am I missing something here?

```
 capabilities: {
    'proxy': {
        'proxyType': 'manual',
        'httpProxy': 'invalidUrl'
    }
}
```

**Comment by finspin** [comment]
Nevermind, it's the sslProxy that I had to use. Problem solved!

```
 capabilities: {
    'proxy': {
        'proxyType': 'manual',
        'sslProxy': 'hostname.com:port'
    }
}
```
