### ISSUE TITLE
Unable to debug scripts executed in browser

### ISSUE THREAD

**Issue by haimlit** [angular/protractor#378]
I've seen in the docs how to debug the code that runs in node, but not the code that executes in the browser (through protractor.getInstance().driver.executeAsyncScript). This is a part of the test so we should be able to debug this somehow.

**Comment by juliemr** [comment]
I think this isn't serving much use being open anymore - you can get logs from the browser as shown in (https://github.com/angular/protractor-cookbook/tree/master/protractor-javascript/example-browserlog), or use browser.pause() and interact with your browser however you would like. I think other features are out of scope for now.
