### ISSUE TITLE
Local driverProvider should use the update-config.json for binaries

### ISSUE THREAD

**Issue by cnishina** [angular/protractor#3782]
The binaries downloaded from webdriver-manager should be referenced from `update-config.json`

**Comment by cnishina** [comment]
Quick note: this fix should be against the beta branch.

**Comment by bobbai** [comment]
I think this is not appropriate. Or just specify the version in `update-config.json`, not with path.

**Comment by cnishina** [comment]
Response in [stackoverflow](http://stackoverflow.com/questions/43581462/unable-to-use-protractor-with-chromedriver-and-selenium-server-directly/43583194#43583194).
