### ISSUE TITLE
Unable to open tab with Angular app, getting [ng:test] no injector found

### ISSUE THREAD

**Issue by azachar** [angular/protractor#3789]
Hello, 
After an opening tab of Angular 1.5 based app I am getting 

**Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.5.9/ng/test"**

It is weird, since the whole app is angular based, and ``ng-app`` is set on the ``html`` tag and it is also set in the protractor config `` rootElement: 'html' ``

To open tab I am using this code

```js
.. some code above that sets this.browser = browser.forkNewDriverInstance();

this.openTab = function(index, timeout) {
    timeout = timeout || DEFAULT_WAIT_FOR_TIMEOUT;
    var thisBrowser = this.browser;
    var deferred = protractor.promise.defer();

    function errHandler(err) {
      deferred.reject(err);
    }

    thisBrowser.sleep(500);

    //wait to open the tab
    thisBrowser.wait(ensureNumberOfTabs(index), timeout, 'waiting for opening tab #' + index);

    thisBrowser.sleep(1000);
    //switch to the tab
    thisBrowser.getAllWindowHandles().then(function(tabs) {
      var tab = tabs[index]; // this is your new window
      thisBrowser.switchTo().window(tab).then(function() {
        thisBrowser.sleep(3000); //wait to load the page
        deferred.fulfill();
      }, errHandler);
    }, errHandler);

    return deferred.promise;
  };

```
btw. without sleeps, it doesn't work either, have a look at http://stackoverflow.com/questions/40813037/protractor-is-unable-to-open-a-new-tab

Bug report
---

- Node Version: `4.4.7` (reproducible also on 6.1.0)
- Protractor Version: `4.0.11`
- Angular Version: `1.5.9`
- Browser(s): `Chrome 53, 54 and 55.0.2883.75 `
- Operating System and Version `os x, ubuntu 14 (circleci one)`
- Your protractor configuration file
```js
exports.config = {
  rootElement: 'html',
  allScriptsTimeout: 110000,
  baseUrl: 'http://localhost:' + (process.env.PORT || '9000'),
  chromeOnly: true,
  directConnect: true,
  exclude: [],
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      args: ['--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream'],
    }
  },
  framework: 'jasmine',
  jasmineNodeOpts: {
    defaultTimeoutInterval: BASE_TIMEOUT, //1 minute
    random: true
  }
```

- Output from running the test
```
Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.5.9/ng/test"
    at /home/ubuntu/XXX/node_modules/protractor/built/browser.js:269:23
    at ManagedPromise.invokeCallback_ (/home/ubuntu/XXX/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/home/ubuntu/XX/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/home/ubuntu/XXX/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/home/ubuntu/XXX/node_modules/selenium-webdriver/lib/promise.js:2775:27)
    at /home/ubuntu/vividoctor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Do you have any idea why I am experiencing this? I think it is a bug so I decided to report it. 

Thanks for your help!

Cheers,
Andrej

**Comment by sjelin** [comment]
This is strange.  Are you sure you're never navigating to a non-angular page? Do you have the same problem if you make the root element `body`?

**Comment by azachar** [comment]
Hey @sjelin, I am 100% sure it is the same app. I can try to use it with 'body' or [ng-app] and let you know. Thanks anyway.

**Comment by azachar** [comment]
So I did the test and you when I changed `ng-app` from `html `to **body** and also from `html` to 
 **rootElement: 'body'**, it worked well. 

Anyway thanks for help.

**Comment by sjelin** [comment]
I suspect that angular just can't set an injector on an `html` tag.  Glad your problem's fixed

**Comment by azachar** [comment]
Actually, it still appears... looks like flaky one :(

```js
Error: Error while waiting for Protractor to sync with the page: "[ng:test] no injector found for element argument to getTestability\nhttp://errors.angularjs.org/1.5.9/ng/test"
    at /home/ubuntu/XXX/node_modules/protractor/built/browser.js:269:23
```
What is your next suspect? Thank you!

**Comment by sjelin** [comment]
Could you provide a more minimal example?  Preferably a github repo I could debug
