### ISSUE TITLE
Replace q with native promises

### ISSUE THREAD

**Issue by thorn0** [angular/protractor#3790]
`selenium-webdriver` depends on native promises anyway, so why keep using the q library?
Would you be interested in a PR that replaces `q` with native promises?

**Comment by sjelin** [comment]
We compile to es5, so this would actually just become whatever typescript generates.  I'd be fine with it though

**Comment by cnishina** [comment]
If someone decides to do this, they should use the `beta` branch:

- setup for ES6 support and tests in CI against node 6+
- has selenium-webdriver 3 dependency which uses native promises

**Comment by thorn0** [comment]
Even selenium-webdriver 2.x relies on native promises. It uses them to shedule microtasks.

**Comment by sjelin** [comment]
Good call.  And it appears I was wrong that typescript compiles out `Promise`.  You'll have to install `@types/es6-promise`, but that's no big deal.

**Comment by NickTomlin** [comment]
Going to go ahead and close this since https://github.com/angular/protractor/commit/4e73d5ed7b0f09c5ebe376a33c7937fb876ee686 resolves it (and it is an internally facing issue so no need to wait until for a release). If anyone feels that that is wrong holler or re-open it.
