### ISSUE TITLE
browser.get method does not fetch the url

### ISSUE THREAD

**Issue by anwani** [angular/protractor#3798]
i am using the statement browser.get(URL); but the url is not launched, rather just the browser window is opened by the previous statement browser.manage().window().setSize(1600, 1000);
which was defined in onprepare method on conf.js file

is there any solution to this?

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
