### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by hmmlopez** [angular/protractor#3799]
Bug report
---

- Node Version: `v7.0.0`
- Protractor Version: `Version 4.0.11`
- Angular Version: `2.1.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`

When I run the command **protractor** I get the following warning:
`DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

I'm using **angular-cli**:
angular-cli: 1.0.0-beta.20-4
node: 7.0.0
os: win32 x64

Maybe there is already a fix for this warning? It's not breaking and it's working but couldn't find a solution on stackoverflow or anywhere online.

**Comment by cnishina** [comment]
Initial code search of os.tmpdir in protractor:

- [spec/unit/driverProviders/direct_test.js](https://github.com/angular/protractor/blob/7da9c3a910bb000b30bf9ba82ef48c64bd751709/spec/unit/driverProviders/direct_test.js#L41)
- [spec/unit/driverProviders/local_test.js](https://github.com/angular/protractor/blob/7da9c3a910bb000b30bf9ba82ef48c64bd751709/spec/unit/driverProviders/local_test.js#L42)
- [spec/unit/logger_test.js](https://github.com/angular/protractor/blob/7da9c3a910bb000b30bf9ba82ef48c64bd751709/spec/unit/logger_test.js#L9)

There are no cases of os.tmpDir. It could be a dependency we are using...and will grep it later today.

**Comment by cnishina** [comment]
The only dependency currently using `os.tmpDir` in master is the `selenium-webdriver@2.53.3` dependency `tmp@0.0.24`. Taking a look at the beta branch, there are no uses of `os.tmpDir`.

**Comment by whyboris** [comment]
It looks like users are still getting this error consistently (Nov 2017): https://github.com/angular/protractor/issues?utf8=%E2%9C%93&q=os.tmpdir
In our project we get this error. Unsure if relevant, but we're on 
- Node 9.2.0 (error occurs with 8.9.1 and others)
- Protractor 5.2.0

**Comment by devoto13** [comment]
I've created a new issue to track this specific warning. Should be easier to track an maybe we'll get more luck maintainers noticing it this way... https://github.com/angular/protractor/issues/4657

**Comment by zecollokaris** [comment]
Update npm 

sudo npm i -g npm

**Comment by zecollokaris** [comment]
Update npm: It will work

```
sudo npm i -g npm
```
