### ISSUE TITLE
Timed out waiting for Protractor to synchronize with the page after 11 seconds

### ISSUE THREAD

**Issue by jinozinemind** [angular/protractor#3801]
Hi there!

I am new to Protractor and have been trying to run end to end test. I have tried other respondent but still i am getting the above error

My protractor conf.js looks like this:

directConnect: true,
   framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 2500000,
    print: function() {}
  },

spec.js looks like this
describe('b2-bportral standardOrder', function () {
    let onlineOrderPage: OnlineOrderPage;
    let loginPage: LoginPage

    beforeEach(() => {
        browser.driver.manage().window().maximize();;
        loginPage = new LoginPage();
        loginPage.navigateTo();
        loginPage.setUserName("canon@gmail.com");
        loginPage.setPassword("a");
        loginPage.loginClick();
        onlineOrderPage = new OnlineOrderPage();
        onlineOrderPage.navigateTo();
        browser.waitForAngular();
    });
    it('Standard Order', () => {
        onlineOrderPage.setPartnerName("");
        onlineOrderPage.addOrder();
        
    });
});
 Error:
 b2-bportral standardOrder
    × Standard Order
      - Failed: Timed out waiting for Protractor to synchronize with the page after 11 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
      - Failed: Timed out waiting for Protractor to synchronize with the page after 11 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md
While waiting for element with locator - Locator: By(css selector, *[id="selPartnerName"])

Anyone please guide me

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
