### ISSUE TITLE
selenium-webdriver is missing from node_modules

### ISSUE THREAD

**Issue by benbracha** [angular/protractor#3804]
Hi,

We found today that when re-installing our node-modules, protractor stops installing selenium-webdriver which we are dependent on in our test code.
Specifically, this line in our test code fails:

`var webdriver = require('protractor/node_modules/selenium-webdriver');`

Because there is no "selenium-webdriver" folder.
Instead, the selenium-webdriver is installed on the top level "node-modules" folder of our project.
We didn't change anything, it just started to happen on a fresh workspace.

Can you explain the root of this change / what is the practice of requiring on selenium-webdriver? Maybe we did it wrong until now?

Changing our require to the following, works:
`var webdriver = require('selenium-webdriver');`

- Node Version: `4.4.7`
- Protractor Version: `4.0.3`
- Angular Version: `1.3.15`
- Operating System and Version `OS X 10.11.1`

**Comment by NickTomlin** [comment]
Without more details its difficult to know but this may be a side effect of updating your NPM version; NPM > 3 attempts to [flatten](https://docs.npmjs.com/how-npm-works/npm3) depedencies.

That said, you probably shouldn't depend on Protractor to include `selenium_webdriver` for you, you should include it as a depedency or devDepedency of your project and require it directly.

Please direct any further question StackOverflow. Thanks! 😄

**Comment by benbracha** [comment]
Thanks for your quick answer on this.
