### ISSUE TITLE
Ignore invalid SSL Certificates  firefox

### ISSUE THREAD

**Issue by yossazou** [angular/protractor#3805]
Hi,

I would like to run my tests on firefox. I'm always getting an invalid SSL Certificates error, even though acceptSslCerts and trustAllSSLCertificates are  set to true in the config file. 

I'm starting a standalone selenium webdriver by specifying the path to the  gecko driver.

Any suggestions ???

Thanks!!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
