### ISSUE TITLE
CI build failures

### ISSUE THREAD

**Issue by dotLou** [angular/protractor#3806]
Bug report
---
- Protractor Version: `4.0.12`

The release for this version has never built successfully on circle.

https://circleci.com/gh/angular/protractor/tree/master is broken since https://circleci.com/gh/angular/protractor/169

**Comment by cnishina** [comment]
We are aware of the problem. Circle CI was recently introduced to run the entire test suite.

There have been several issues:

- Clang errors on formatting were failing at one point. clearing out the cache appeared to fix this
- Currently spec/basic/element_spec.js line 165 appears to be the culprit of these tests failing. In particular, calling `protractor.promise.when(true)` causes a Jasmine timeout issue. This test works locally and appears to only happen on CircleCI.

**Comment by cnishina** [comment]
In addition, Travis has been flaky for the past several days. On the [Travis status page](https://www.traviscistatus.com/), it shows degraded performance for Linux builds on Trusty.

**Comment by cnishina** [comment]
It also looks like Travis has a few issues.

**Comment by cnishina** [comment]
It appears that I introduced a change creating the error while doing the release yesterday. This is causing one of the build errors for `spec/basic/element_spec.js`. The issue should not impact users; however, we are going to do another release for 4.0.13.

**Comment by cnishina** [comment]
The error introduced has been fixed and 4.0.13 has been released.

**Comment by dotLou** [comment]
The build seems to be passing and as far as I can tell our usage of this is working again. Thanks!
