### ISSUE TITLE
Protractor 4.0.12 regression click doesn't work anymore

### ISSUE THREAD

**Issue by dannysu** [angular/protractor#3809]
I have a test that's been passing with 4.0.11, but broke with 4.0.12.
Not sure if #3803 is related since the behaviour I get is just timeout, but that might just be how my test is written.

That said, I've tracked down to the exact commit that caused the behaviour to change and that's 81a6eaa14b471fabe392bde04dc2f576e3d0d6ba.

My test code is like this:
```
_getRowElement(index) {
    return element.all(by.css('#something')).get(index);
}

clickRow() {
    return this.execute(function*() {
        const rowElement = yield this._getRowElement(index);
        yield rowElement.click(); // 4.0.12 caused this to get stuck
    });
}
```

The change in 81a6eaa14b471fabe392bde04dc2f576e3d0d6ba to go from:
```
// 4.0.11 has this:
then: (fn: Function, errorFn?: Function) => wdpromise.Promise<any> = null;
```
to
```
// 4.0.12 has this:
then(fn: Function, errorFn?: Function): wdpromise.Promise<any> {
  return null;
}
```
is what broke stuff

I can reliably change lib/element.ts to 4.0.11 version, run `rm -rf node_modules && npm install` and see my test pass. The npm install process runs tsc and updates built/element.js.

I can also reliably change lib/element.ts to 4.0.12 version, run `rm -rf node_modules && npm install` and see my test fail.

**Comment by cnishina** [comment]
This has been investigated, reverted, and released. Current version is 4.0.13. Thanks for looking into this as well. Closed with c3978ec166760ac07db01e700c4aaaa19d9b5c38.
