### ISSUE TITLE
@types/jasmine as package dependency clashing when trying to use mocha

### ISSUE THREAD

**Issue by jeep87c** [angular/protractor#3810]
I would like to understand why @types/jasmine is a dependency for protractor instead of a dev dependency? What is the requirement for this?

After creating a brand new TS Angular project using Angular-cli, trying to setup mocha instead of jasmine, I ran into issues while trying to write mocha test (easy example is `it.skip(...)`).

Here's what I did step by step:

- Replaced karma-jasmine by karma-mocha in package.json
- Replace @types/jasmine by @types/mocha in package.json
- Added mocha, chai, chai-as-promised in package.json
- Removed jasmine-core and jasmine-spec-reporter from package.json
- Edited my karma.con.js replacing jasmine by mocha in frameworks and karma-jasmine by karma-mocha
- Edited my protractor.conf.js replacing jasmine by mocha in framework, removed jasmineNodeOpts, onPrepare and SpecReporter, added `mochaOpts: { reporter: 'spec', timeout: 4000 }`
- npm prune
- npm install
- npm install-test.

After that, when I'm running ng e2e, I get the following error message:

> Error: TSError: ⨯ Unable to compile TypeScript
> e2e/app.e2e-spec.ts (22,6): Property 'skip' does not exist on type '(expectation: string, assertion?: (done: DoneFn) => void, timeout?: number) => void'. (2339)

The only way I got it working is by manually removing the folder node_modules/@types/jasmine. Running the exact same test without this folder works like a charm.

Obviously, next time I'll do an npm install, the @types/jasmine folder will come back and I will most probably encounter the same issue again. So how do I get this fix forever and/or why @types/jasmine is a dependency to protractor?

Thank you

**Comment by cnishina** [comment]
Noted. I thought this change was made in 4.0.13 released today but I must have did this change against the beta branch.

**Comment by jeep87c** [comment]
Thanks for looking into it.

FYI, angular-cli will create new project using protractor 4.0.9. I saw it after your comment and right away updated it to 4.0.13, but still the same issue.

**Comment by cnishina** [comment]
Alright, I had to jog my memory a bit. I answered this question earlier this week in a similar issue, https://github.com/angular/protractor/issues/3792. We are suggesting for users to specify the types the are using in the `compilerOptions` `types` array. This will let `tsc` know which types to include and to avoid duplicate identifiers (use mocha types over jasmine types).

We have a major version release planned to include breaking changes like this one and the selenium-webdriver 3.0.1 upgrade. These breaking changes are located in the `beta` branch.

So this issue has been fixed for a future release. Closing this issue.

**Comment by jeep87c** [comment]
Thanks man! Your suggestion works like you said. So at least I can get going until the fix is released. Do we have an idea of when and/or in which version it should be released?

Thanks!

**Comment by cnishina** [comment]
We do not have a date set for when. This will be released with the next semantic versioning for a breaking changes (5.0.0).

**Comment by jeep87c** [comment]
Looks like in a galaxy far far away to me ;)
