### ISSUE TITLE
Old jasmine version used by protractor

### ISSUE THREAD

**Issue by shumailarshad** [angular/protractor#3811]
Bug report
---

- Node Version: `4.2.6`
- Protractor Version: `4.0.13`
- Angular Version: `na`
- Browser(s): `na`
- Operating System and Version `na`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

We have vulnerability check implement in our project which has found vulnerability in minimatch version. Protractor not using latest version of jasmine which will fix this issue.

Name        Installed   Patched   Path                                                                                                More Info                              
minimatch   0.3.0       >=3.0.2   OURPROJECTNAME@0.0.184 > protractor@4.0.13 > jasmine@2.4.1 > glob@3.2.11 > minimatch@0.3.0   https://nodesecurity.io/advisories/118

**Comment by cnishina** [comment]
This has been considered. We originally upgraded jasmine; however, it also causes issue https://github.com/angular/protractor/issues/3609. We downgraded back to jasmine@2.4.1 and awaiting a new release of `jasmine-npm` with this change: https://github.com/jasmine/jasmine-npm/pull/98.
