### ISSUE TITLE
allow to connect directly to phantomjs

### ISSUE THREAD

**Issue by GuyMograbi** [angular/protractor#3820]
add phantomjs to the awesome `directConnect: true` feature. 
Can easily achieved since phantomjs has --webdriver option `phantomjs --webdriver=4444`

This will actually remove the need for java on build machines in many cases and simplify config to something like 

```
exports.config = {
  directConnect:true,
  capabilities: {
    'browserName': process.env.BROWSER_NAME || 'phantomjs',
  },
  specs: ['tests/protractor/**/*.ptor.js']
};
```

and will make build scripts a simple `protractor` command without any "pre" and "post" hooks required.

**Comment by juliemr** [comment]
I would look at a PR to do this, but I'm hesitant because we've had constant issues with PhantomJS and we'd like to be very clear that this is something we don't necessarily fully support. any PR would have to come with a warning.

**Comment by peder** [comment]
Any idea what would have to be changed to support this? Is there something in protractor today that explicitly only supports Chrome and Firefox?

**Comment by peder** [comment]
I see in `config.ts` the following documentation:

```  /**
   * If true, Protractor will connect directly to the browser Drivers
   * at the locations specified by chromeDriver and firefoxPath. Only Chrome
   * and Firefox are supported for direct connect.
   *
   * default: false
   */
  directConnect?: boolean;
```

And I see that `chromeDriver` and `firefoxPath` are used in `configParser.ts`:

```
  private addConfig_(additionalConfig: any, relativeTo: string): void {
    // All filepaths should be kept relative to the current config location.
    // This will not affect absolute paths.
    ['seleniumServerJar', 'chromeDriver', 'onPrepare', 'firefoxPath', 'frameworkPath'].forEach(
        (name) => {
          if (additionalConfig[name] && typeof additionalConfig[name] === 'string') {
            additionalConfig[name] = path.resolve(relativeTo, additionalConfig[name]);
          }
        });

    merge_(this.config_, additionalConfig);
  }
```
How is that `additionalConfig` value used? I'm not seeing an obvious way that we could add support for phantomjs out of this.

**Comment by peder** [comment]
Is this just about as simple as modifying the `Direct` class? I assume there's a driver like `import {Driver as ChromeDriver, ServiceBuilder as ChromeServiceBuilder} from 'selenium-webdriver/chrome';` but for PhantomJS instead? I'd also have to figure that the Chrome and PhantomJS drivers would operate nearly identically.

**Comment by peder** [comment]
I was surprised that there wasn't a declaration file for PhantomJS in the `selenium-webdriver` [DefinitelyTyped library](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/selenium-webdriver). Further, if you compare the [PhantomJS](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/phantomjs.js) and [Chrome](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/chrome.js) selenium-webdriver classes, there could be significant differences between them, including the PhantomJS library's lack of `Options` support like the other browsers.

**Comment by heathkit** [comment]
PhantomJS is no longer supported now that Headless Chrome is coming. See https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
