### ISSUE TITLE
cucumberOpts incompatible type

### ISSUE THREAD

**Issue by kacpe-r** [angular/protractor#3822]
Hi there,
I'm using protractor 4.0.13, typescript 2.1.4 and cucumber 1.3.1.
In my config.ts I've got such config in cucumberOpts:

`    cucumberOpts: {
        require: [
            '../steps/**/*Steps.js',
            '../support/hooks.js'
        ],
        format: [
            'pretty',
            'json:report.json'
        ]
    },`

Every time when I run tests I got such error:
`config/config.ts(3,12): error TS2322: Type '{ seleniumAddress: string; baseUrl: string; capabilities: { browserName: string; chromeOptions: {...' is not assignable to type 'Config'.
  Types of property 'cucumberOpts' are incompatible.
    Type '{ require: string[]; format: string[]; }' is not assignable to type '{ [key: string]: any; require?: string; tags?: string; format?: string; coffee?: any; noSnippets?...'.
      Types of property 'require' are incompatible.
        Type 'string[]' is not assignable to type 'string'.
`

The clue is in config.ts file. In lib/config.ts:563 and lib/config.ts:572 you've got 
`    require?: string;`
Could you please change them into:
`    require?: Array<string>;`

Regards,
Kacper

**Comment by wswebcreation** [comment]
@kacpe-r,

See https://github.com/angular/protractor/pull/3817. I think it will solve your problem

**Comment by kacpe-r** [comment]
@wswebcreation  So for it fixes only 'require'. I've been writing about 'require' and 'format'.

**Comment by wswebcreation** [comment]
Ok, clear, missed that, sorry

**Comment by juliemr** [comment]
Should we have `cucumberOpts` in the config at all? Can we allow arbitrary other properties on the config instead?

**Comment by cnishina** [comment]
I don't think this hurts as long as it is kept up to date. We also recently merged a docs for cucumber: #3674. Probably we should make the config more flexible with something like:

```
export interface Config {
  [key: string]: any;
```

**Comment by cnishina** [comment]
Also, at least this issue has been fixed with: https://github.com/angular/protractor/blob/master/lib/config.ts#L558

Leaving it open to discuss the above comment.

**Comment by cnishina** [comment]
Per discussion offline with Julie:

* should leave the documentation for Cucumber
* should remove the cucumber options in the Config and add the `[key:string]: any;`
