### ISSUE TITLE
Clear() not working on a input of the type: "number" after sendKeys('e').

### ISSUE THREAD

**Issue by arjan674** [angular/protractor#3824]
Hi,

Clear() doesn't work after I use sendKeys("e") on a input of the type: "number". 
It works after I change it to sendKeys("1").

`inputDialogPage.partIdInput.sendKeys("e").then(() => {
        inputDialogPage.partIdInput.clear();
    })`
    
- Node Version: v4.5.0
- Protractor Version: v4.0.11
- Angular Version: v2.2.1
- Browser(s): Chrome
- Operating System and Version: Windows 7

**Comment by cnishina** [comment]
I agree. Selenium-webdriver [sendKeys](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/webdriver.js#L2056) params states it should take a number. 

- typings prior to updating to 2.53.x inherited from the master branch: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/selenium-webdriver/index.d.ts#L3338
- typings in branch types-2.0 should be updated: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/selenium-webdriver/index.d.ts#L3338

I will create an issue on DefinitelyTyped and fix this.

**Comment by cnishina** [comment]
### Type Fixes: 
Updating the types for sendKeys in DefinitelyTyped to accept numbers. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13573

###  Clearing an input number field has been fixed: 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=839

Wrote a quick test to try it out:

```
var webdriver = require('selenium-webdriver');
var by = webdriver.By;

var browser = new webdriver.Builder()
  .usingServer('http://127.0.0.1:9515')
  .withCapabilities({'browserName': 'chrome'})
  .build();

browser.get('http://127.0.0.1:4200').then(() => {
  browser.findElement(by.css('.myform-number')).then((element) => {
    element.sendKeys('eee1').then(() => {
      browser.sleep(2000).then(() => {
        element.clear();
      });
    });
  });
});

```

Investigating what we are doing to cause this error.

**Comment by cnishina** [comment]
I am unable to reproduce this with selenium standalone server + chromedriver or just against chromedriver:

html:
```
<input class="myform-number" type="number">
```


config with standalone & chromedriver:
```
import {Config} from 'protractor';

export let config: Config = {
  // seleniumAddress: 'http://127.0.0.1:9515',
  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  specs: [
    'spec.js'
  ],
  baseUrl: 'http://localhost:4200',
  useAllAngular2AppRoots: true,
}
```

spec:
```
import {browser, by, element, protractor} from 'protractor';

describe('form test', () => {
  beforeEach(() => {
    browser.get('/');
  });
  it('should do clear', () => {
    element(by.css('.myform-number')).sendKeys('222');
    element(by.css('.myform-number')).sendKeys('111e');
    expect(element(by.css('.myform-number')).getAttribute('value')).toEqual('222111e');

    // element(by...).clear() method:
    element(by.css('.myform-number')).clear();
    expect(element(by.css('.myform-number')).getAttribute('value')).toEqual('');

    // using browser.driver commands:
    // browser.driver.findElement(by.css('.myform-number')).then((el) => {
    //   el.clear();
    // });
  });
});
```
