### ISSUE TITLE
Add second() command for selecting the second element

### ISSUE THREAD

**Issue by Marketionist** [angular/protractor#3838]
It would be great to have readable second() command for selecting the second element. Some additional evidences:
- http://stackoverflow.com/questions/33279813/locating-second-third-fourth-eigth-element-in-protractor-using-css-locator
- http://stackoverflow.com/questions/37529654/how-to-select-second-objects-second-element-with-same-classname-in-protractor

This not a breaking change. It will extend the existing functionality and make elements interactions more readable.

**Comment by juliemr** [comment]
As I mentioned in the PR, I think this adds complexity, and `get(1)` is simpler and more generic. Thanks for looking into this!

**Comment by Marketionist** [comment]
As I replied in https://github.com/angular/protractor/pull/3839 - it looks like 90% most often used cases are: `first()`, `get(1)` and `get(2)`. So adding `second()` and `third()` shortcuts looked like a reasonable addition that will give more readability for most of the cases. Anyway, it is up to you to decide if this should become a part of protractor syntax or not. Thanks for reviewing!

**Comment by Marketionist** [comment]
**Update**: created a separate package - https://github.com/Marketionist/protractor-numerator - that can be used with protractor to select second, third, etc. elements. Would be great to hear what you think about it @juliemr
