### ISSUE TITLE
Docgen is broken on beta because dgeni doesn't understand es6

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#3869]
So basically it can't parse stuff like `class`

**Comment by mgiambalvo** [comment]
Well, that's a bummer. We can just switch the tsconfig to output es5, but that means no native promises.

**Comment by sjelin** [comment]
I mean, we could `npm install @types/es6-promise`, but I'd prefer not to add a million hacks.  I guess we might have to though...

**Comment by jan-molak** [comment]
Just a thought, but promises seem to be [pretty well supported](http://node.green/#Promise) on Node 4 and up, and Protractor [requires 4.2.x](https://github.com/angular/protractor/blob/ca4f1acda3672942307d0f102d586c8889dd3d68/package.json#L79) anyway. Could you potentially target `es5` but [include the `es2015.promise` lib](https://www.typescriptlang.org/docs/handbook/compiler-options.html), convincing tsc that it's safe to proceed?

This would make the `compilerOptions` section of the [`tsconfig.json`](https://github.com/angular/protractor/blob/ca4f1acda3672942307d0f102d586c8889dd3d68/tsconfig.json) look like this:

```
{
    "compilerOptions": {
        "target": "es5",
        "lib": [ "es5", "es2015.promise" ],
   
        ....
    }
}
```

**Comment by juliemr** [comment]
Here is a branch that is generating the website using the strategy of compiling to es5 and fixing up everything else :)

https://github.com/juliemr/protractor/tree/quickfix-website

We'll probably use this for the 5.0 release, and then get generation from TS working for later versions.

**Comment by sjelin** [comment]
Fixed by https://github.com/angular/protractor/pull/4040

**Comment by juliemr** [comment]
Note that https://github.com/angular/protractor/issues/2930 is still open - we've just patched a workaround which compiles down to es5 for documentation purposes.
