### ISSUE TITLE
4.0.14 error TS2503: Cannot find namespace 'webdriver'.

### ISSUE THREAD

**Issue by philjones88** [angular/protractor#3878]
Bug report
---

- Node Version: `7.2.1`
- Protractor Version: `4.0.14`
- Typescript Version: `2.0.10`
- Angular Version: `NA`
- Browser(s): `NA`
- Operating System and Version `OSX Sierra`
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Upgraded to `4.0.14` from `4.0.11`. Now no longer builds.

Googling found: http://stackoverflow.com/questions/41238376/angular2-npm-install-didnt-find-namespace-webdriver

Can see I have:
`@types/selenium-webdriver@2.53.37`

```
protractor@4.0.14:
  version "4.0.14"
  resolved "http://private-proget-npm-cache/npm/npm/protractor/-/protractor-4.0.14.tgz#efc4a877fac3a182a9dded26cd5869f4762fd172"
  dependencies:
    "@types/jasmine" "^2.5.36"
    "@types/node" "^6.0.46"
    "@types/q" "^0.0.32"
    "@types/selenium-webdriver" "2.53.37"
    adm-zip "0.4.7"
    chalk "^1.1.3"
    glob "^7.0.3"
    jasmine "2.4.1"
    jasminewd2 "0.0.10"
    optimist "~0.6.0"
    q "1.4.1"
    saucelabs "~1.3.0"
    selenium-webdriver "2.53.3"
    source-map-support "~0.4.0"
    webdriver-manager "^10.3.0"
```

in my yarn.lock file.

Tried removing `node_module` and my `yarn.lock` file but problem still persists.

**Comment by cnishina** [comment]
A quick thought: I recently responded to an [issue on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13461). A user was using webdriver globally without importing the selenium-webdriver.

Anyway, trying out the [protractor-cookbook typescript example](https://github.com/angular/protractor-cookbook/tree/master/protractor-typescript), updating to the latest version does work, and I am unable to reproduce this. 

I think this could be a setup problem in your project. If you feel that this is an actual Protractor bug with the framework, please feel free to open a new issue and add more detail including logs, the configuration, and a simple test where this fails (even if it is a transpile error).

**Comment by philjones88** [comment]
@cnishina absolutely correct.

Was missing an import. Not sure how it worked before though. Did it as:

`import { promise as wdpromise } from 'selenium-webdriver';` 

to make it clear what type of promise it was.
