### ISSUE TITLE
TypeScript: @types/jasmine clash with @types/mocha

### ISSUE THREAD

**Issue by jan-molak** [angular/protractor#3880]
Hello!

Protractor supports [both Jasmine and Mocha](https://github.com/angular/protractor/blob/master/docs/frameworks.md), but because the library defines a [dependency on `@types/jasmine`](https://github.com/angular/protractor/blob/ca4f1acda3672942307d0f102d586c8889dd3d68/package.json#L15), having a dependency on `@types/mocha` in a typescript project utilising both protractor and mocha causes the typescript compiler to complain about duplicate global identifiers as both mocha and jasmine fight for the global space:

```
node_modules/@types/jasmine/index.d.ts(9,18): error TS2300: Duplicate identifier 'describe'.
node_modules/@types/jasmine/index.d.ts(11,18): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/jasmine/index.d.ts(13,18): error TS2300: Duplicate identifier 'it'.
node_modules/@types/jasmine/index.d.ts(15,18): error TS2300: Duplicate identifier 'xit'.
node_modules/@types/mocha/index.d.ts(33,13): error TS2300: Duplicate identifier 'describe'.
node_modules/@types/mocha/index.d.ts(34,13): error TS2300: Duplicate identifier 'xdescribe'.
node_modules/@types/mocha/index.d.ts(39,13): error TS2300: Duplicate identifier 'it'.
node_modules/@types/mocha/index.d.ts(40,13): error TS2300: Duplicate identifier 'xit'.
```

Since not all projects using protractor use jasmine, perhaps you'd like to consider making the dependency on `@types/jasmine` [optional](https://docs.npmjs.com/files/package.json#optionaldependencies)?

Many thanks,
Jan

```
node: 6.5.0
npm: 3.10.3
protractor: 4.0.14
```

**Comment by cnishina** [comment]
This has been fixed with https://github.com/angular/protractor/pull/3795.

Set the compiler options array in your tsconfig for now with mocha per https://github.com/angular/protractor/issues/3792.

**Comment by jan-molak** [comment]
Cool, cheers @cnishina. Looking forward to the next release!

J
