### ISSUE TITLE
When using ExpectedConditions after browser.restart(), getting "Driver does not have valid session ID" error

### ISSUE THREAD

**Issue by mgiambalvo** [angular/protractor#3881]
From azachar (copied from #3677)

Hi There, 
I am getting a very similar issue still on the version 4.0.13, it happens sometimes...

the test opens the page and waits to have a certain part in the url using the function bellow, the tests are using `browser.restart() ` in afterEach. Since I am using a random order of running, it happens only sometimes.

```js
  this.waitForUrl = function(url, timeout) {
    timeout = timeout || DEFAULT_WAIT_FOR_TIMEOUT;
    return this.browser.wait(EC.urlContains(url), timeout, 'waiting url to contains ' + url);
  };
```

I am getting this error:
```js

Failed: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
NoSuchSessionError: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    at WebDriverError (/home/ubuntu/xxx/node_modules/selenium-webdriver/lib/error.js:27:5)
    at NoSuchSessionError (/home/ubuntu/xxx/node_modules/selenium-webdriver/lib/error.js:170:5)
    at checkHasNotQuit (/home/ubuntu/xxx/node_modules/selenium-webdriver/lib/webdriver.js:395:15)
    at Driver.schedule (/home/ubuntu/xxx/node_modules/selenium-webdriver/lib/webdriver.js:356:5)x
    at Driver.getCurrentUrl (/home/ubuntu/xxx/node_modules/selenium-webdriver/lib/webdriver.js:804:17)
    at /home/ubuntu/xxx/node_modules/protractor/built/expectedConditions.js:306:41
```
The screenshot from this failure clearly shows that the page is fully loaded and has its content so I guess this might be a bug. I guess that is related to this issue too.

Anyway, thank you for your help.

Best regards,
Andrej

Here is the failing test case:

```js
describe('This driver instance does not have a valid session ID', function() {
  var EC = protractor.ExpectedConditions;

  function waitForUrl(url) {
    browser.wait(EC.urlContains(url), 5000).then(function() {
      console.log(url + ' found');
    })
  }

  it('Browser wait for url fails', function() {
    browser.get("https://angularjs.org/");
    waitForUrl('angular');

    browser.restart();

    browser.get("https://angularjs.org/");
    //fails here // This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.
    waitForUrl('angular');
  });

  it('Browser ignoreSynchronization fails', function() {
    browser.get("https://angularjs.org/");
    browser.restart();
    browser.get("https://angularjs.org/");

    browser.ignoreSynchronization = true;
    browser.get("https://github.com/");
    waitForUrl('github'); //fails here This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

    browser.ignoreSynchronization = false;

    browser.restart();

    browser.get("https://angularjs.org/");
    waitForUrl('angular');
  });

});

```

here is **protractor.conf**

```js
{ 
  rootElement: 'html', //it fails also with [ng-app]
  allScriptsTimeout: 110000,
  baseUrl: 'http://localhost:9000',
  chromeOnly: true,
  directConnect: true,
  exclude: [],
  capabilities: { browserName: 'chrome' },
  framework: 'jasmine',
  jasmineNodeOpts: { defaultTimeoutInterval: 15000, random: false },
  specs: [ 'e2e/**/*.spec.*.js', 'e2e/**/*.spec.js' ] 
}
```

**Comment by sjelin** [comment]
The issue is that you should be saving a reference to `ExpectedConditions` as in 
```js
  var EC = protractor.ExpectedConditions;
```

If you set `EC` again after each `restart` call, But to be sure this is confusing.  I made https://github.com/angular/protractor/issues/3884 to document a possible solution

**Comment by cnishina** [comment]
Agree. EC has a reference back to the browser object. If the browser object goes away, the EC is no longer valid after the session quits.

A work around, for now, would be to get the ExpectedConditions from the browser object:
```
  function waitForUrl(url) {
   var EC = browser.ExpectedConditions;
    browser.wait(EC.urlContains(url), 5000).then(function() {
      console.log(url + ' found');
    })
  }
```

**Comment by mgiambalvo** [comment]
Does it make sense to have `protractor.ExpectedConditions` if people can run into this problem? Should we just make `browser.ExpectedConditions` the only official way to create ExpectedConditions?

**Comment by cnishina** [comment]
^^^ Maybe we could make this as a breaking change in beta since ExpectedConditions is no longer static. @juliemr thoughts?

**Comment by azachar** [comment]
Thanks a lot for your investigation, perhaps this will resolve some issues I had to comment out. I am using chat a like app to test, so I do have many browser instances... I will come back to you if this helped.

**Comment by mustafa-turab-ali** [comment]
Is this Fixed?

**Comment by schwarcu** [comment]
Problem still occurs. I need to restart browser between 2 specific test cases and I'm not able to due to this issue. After restart page loads but error appears: -

>  Failed: This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used.

**Comment by wieta** [comment]
Hi, i have same problem with 'restartBrowserBetweenTests' parameter and 'browser.restart()'. I check selenium logs and i have test cases + 1 selenium session. And of course "This driver instance does not have a valid session ID (did you call WebDriver.quit()?) and may no longer be used."

**Comment by schwarcu** [comment]
@wieta after some study I came to the source of issue which I think is common for most of users. 
 If you are using page object pattern and you initialize and define objects in the "desc" segment, or even in bigger scope these objects will always refer to the first browser instance. 

To solve the issue, you must decache them (https://www.npmjs.com/package/decache) and then use "require" again and also agian initialize and define variables. 

For my project I created a common utility function which always returns new Page Object. After I restart the browser I use my function to re-load all Page Objects and now it works perfect.

Bare in mind to split data from PO files. If you want to pass data from one spec to another, create a module which does only that task, So you don't have to decache it too.

**Comment by ash-lionell** [comment]
Hi there!

I am facing a similar issue, when using browser.restart. In my case, a subsequent browser.wait call waits almost indefinitely, and times out after an obscene amount of time, although the page is loaded and visible the whole time.

I perform the restart operation in the After hook of Cucumber:

`Before(function(scenario) {
        let currFeatureName=scenario.sourceLocation.uri;
        console.log('feature : ',currFeatureName);
        if(featureName===null)
            featureName=currFeatureName;
        else if(currFeatureName!==featureName)
            return browser.restart();
    });`

Followed by a Given, where I perform a browser.get, followed by a browser.wait, before interacting with my element:

`Given(/^user is logged in SNAPP$/,function(){
        console.log('started : ');
        browser.ignoreSynchronization = true;
        browser.driver.get(browser.params.logon.url);
        browser.wait(until.visibilityOf(element(by.id('logonDialogLbl'))),1000,'waiting to load url');
        logonpage.logon();
        browser.sleep(2000);`

It is seemingly getting stuck in the browser.wait call, and times out, after waiting for an enormous amount of time.

**Comment by arjun1092** [comment]
same issue as mentioned above. 

`I am facing a similar issue, when using browser.restart. In my case, a subsequent browser.wait call waits almost indefinitely, and times out after an obscene amount of time, although the page is loaded and visible the whole time.`
