### ISSUE TITLE
Can I use Jest framework to assert?

### ISSUE THREAD

**Issue by Shyam-Chen** [angular/protractor#3889]
Jest seems like Jasmine.

Jest support for testing with `promises` and `async/await`.

```js
[...]
  beforeEach(async () => {
    await browser.driver.get('http://localhost:9876/en/home');
  });

  it('should be able to get the text', () => {
    let el = webdriver.findElement(by.css('h2.mdl-color-text--blue-900'));
    expect(el.getText()).toEqual('Home');
  });
[...]
```

**Comment by juliemr** [comment]
We have not experimented with using Jest yet, and we don't have built-in support for it. However, you can write and use a custom adapter a framework following the instructions in the README at https://github.com/angular/protractor/tree/master/lib/frameworks

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since there hasn't been much activity on it. I think we'd accept a pull request if folks want to add a framework adapter for Jest.

**Comment by winnemucca** [comment]
Was this ever added?

**Comment by winnemucca** [comment]
Was this ever added?

**Comment by marcus-sa** [comment]
So.... what's the update on this?

**Comment by kimamula** [comment]
Put this line in your config's `onPrepare()` function and you can use Jest functionalities in your Protractor specs.

```js
window.expect = require('expect');
```

References:
https://github.com/facebook/jest/issues/848#issuecomment-324921548
https://github.com/facebook/jest/issues/848#issuecomment-450537533

**Comment by andredesousa** [comment]
Hi, it´s possible because Jest exports your assertion library. For more details:

https://jestjs.io/docs/en/expect

So, we can configure it in the `onPrepare` function:

    onPrepare() {
      global.expect = require('expect');
    },
