### ISSUE TITLE
How can we use the variable which is having a value in another it block description

### ISSUE THREAD

**Issue by rajega** [angular/protractor#3891]
Please anyone help me on the below issue

How can we use the variable which is having a value in another it block. when i execute the below code, throwing undefined error at value1 

var home_page = require('../pages/home-page.js');
var page1 = require('../pages/transpage.js');
var confirm_page = require('../pages/confirm_page.js');

describe('Verify the Application functionality', function() {
var value1;
it('Enter your name',function () {
      home_page.enterFieldValue("text");
      home_page.getDynamicText().then(function(value){
        expect(value).toBe("text");
        console.log(value);  //-------------------------------------> working fine
value1 = value      //-------------------------------------> stored the text in 'value1' variable
      });
      var page1 = home_page.clickContinue();
      page1.selectAnimal(2);
    });

    it('Entered Name is :'+value1, function () {  //-------------------------------------> undefined value1 (Ex: Entered Name is : Undefined)
      console.log(value1);   //-------------------------------------> returning text as expected
      var confirm_page = page1.clickContinue();
      expect(confirm_page.getTitle()).toBe("thanks");
    });

});

my intension is, I want to display the actual values (which we have captured from application) in Allure Reports but it is displaying undefined instead of actual value as below

Entered Name is : Undefined

How can we parameterize the it block?

Please help me

**Comment by juliemr** [comment]
It looks like you've got a question about how variable scope works in Javascript. I'd suggest looking at http://www.w3schools.com/js/js_scope.asp.

Closing since this isn't a Protractor issue, and the issue tracker is used for bugs / feature requests.

**Comment by rajega** [comment]
Thanks for your reply,

Seems it is protractor issue, not the variable scope issue

because i can get the text on console in another it block but getting undefined error when i call the variable in it block description

CODE:
it('Entered Name is :'+value1, function () {  ----------------> in the allure reports, i'm getting undefined error
});

console.log(value1) ----------> returning text on console

if it is variable scope issue, text should not print on console ....am i right??

Is it posible to call the variable (i.e. value1) in it block description?? Ex: it('Entered Name is :'+value1, function () {});

Please help me.
Thanks in advance
