### ISSUE TITLE
[Question] SVG logo version?

### ISSUE THREAD

**Issue by JimiC** [angular/protractor#3913]
Is there somewhere an SVG version of the logo?
I've been searching (almost) everywhere with no luck.
Would really love to use it on [vscode-icons](https://github.com/robertohuertasm/vscode-icons).

**Comment by sjelin** [comment]
Judging by the resolution on our stickers, there must be.  @juliemr you know?

**Comment by juliemr** [comment]
Here ya go:
https://gist.github.com/juliemr/99c13e11f4491bd2a9e39dfa7d5f1c46

**Comment by JimiC** [comment]
@juliemr AWESOME! Many many thanks. Much obliged.
