### ISSUE TITLE
How to verify variable present in the page under script tag ?

### ISSUE THREAD

**Issue by raghavendraa** [angular/protractor#3914]
Hi,

How can i verify whether the variable '**srpTupleJson**' is present or not in the page?

Html code 

```
<script>
        srpTupleJson = [{"name":"Praveen Mishra","title":"B.Tech in Computers Science with 1 year exp. in python\/django","isPremium":false,"isFeatured":false,"isNew":false,"emplo"}]
</script>

```
Protractor version : Version 4.0.2
Chrome browser : Version 53.0.2785.143 Built on Ubuntu 
OS : Ubuntu 14.04 (64-bit)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
