### ISSUE TITLE
Docker `--link` ro be deprecated -request updated cookbook for Docker

### ISSUE THREAD

**Issue by dman777** [angular/protractor#3915]
Request update docs for [Angular's prtoractor cookbook using Docker](https://github.com/angular/protractor-cookbook/tree/master/protractor-docker).

`--link` is being used for the browser nodes. This is now considered legacy in Docker and may be removed:

> Warning: The --link flag is a deprecated legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link. One feature that user-defined networks do not support that you can do with --link is sharing environmental variables between containers. However, you can use other mechanisms such as volumes to share environment variables between containers in a more controlled way.

**Comment by cnishina** [comment]
Closing this issue since it is a cookbook issue. Created issue: https://github.com/angular/protractor-cookbook/issues/24
