### ISSUE TITLE
getting lot of dependency issues in my angular 2 appfor 4.0.9 version, please verify

### ISSUE THREAD

**Issue by chinra02** [angular/protractor#3917]
ERROR in ./~/protractor/built/browser.js
Module not found: Error: Can't resolve 'net' in 'S:\projects\trunk\util_angular2\node_modules\protractor\built'
 @ ./~/protractor/built/browser.js 8:10-24
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/built/browser.js
Module not found: Error: Can't resolve 'child_process' in 'S:\projects\trunk\util_angular2\node_modules\protractor\built'
 @ ./~/protractor/built/browser.js 770:32-56
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/built/browser.js
Module not found: Error: Can't resolve 'repl' in 'S:\projects\trunk\util_angular2\node_modules\protractor\built'
 @ ./~/protractor/built/browser.js 805:25-40
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/built/logger.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\built'
 @ ./~/protractor/built/logger.js 2:9-22
 @ ./~/protractor/built/browser.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/remote/index.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\remote'
 @ ./~/protractor/~/selenium-webdriver/remote/index.js 21:9-22
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/firefox/binary.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\firefox'
 @ ./~/protractor/~/selenium-webdriver/firefox/binary.js 26:9-22
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/firefox/profile.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\firefox'
 @ ./~/protractor/~/selenium-webdriver/firefox/profile.js 26:9-22
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/net/portprober.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\net'
 @ ./~/protractor/~/selenium-webdriver/net/portprober.js 21:9-22
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/firefox/binary.js
Module not found: Error: Can't resolve 'child_process' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\firefox'
 @ ./~/protractor/~/selenium-webdriver/firefox/binary.js 25:14-38
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/net/portprober.js
Module not found: Error: Can't resolve 'child_process' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\net'
 @ ./~/protractor/~/selenium-webdriver/net/portprober.js 20:11-35
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/io/exec.js
Module not found: Error: Can't resolve 'child_process' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\io'
 @ ./~/protractor/~/selenium-webdriver/io/exec.js 20:21-45
 @ ./~/protractor/~/selenium-webdriver/remote/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/io/index.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\io'
 @ ./~/protractor/~/selenium-webdriver/io/index.js 20:9-22
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/net/portprober.js
Module not found: Error: Can't resolve 'net' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\net'
 @ ./~/protractor/~/selenium-webdriver/net/portprober.js 22:10-24
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/chrome.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/chrome.js 117:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/edge.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/edge.js 73:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/opera.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/opera.js 75:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/ie.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/ie.js 30:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/phantomjs.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/phantomjs.js 20:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/safari.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver'
 @ ./~/protractor/~/selenium-webdriver/safari.js 30:11-24
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/firefox/extension.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\firefox'
 @ ./~/protractor/~/selenium-webdriver/firefox/extension.js 23:9-22
 @ ./~/protractor/~/selenium-webdriver/firefox/profile.js
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/lib/devmode.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\lib'
 @ ./~/protractor/~/selenium-webdriver/lib/devmode.js 25:11-24
 @ ./~/protractor/~/selenium-webdriver/firefox/binary.js
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/~/adm-zip/adm-zip.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\node_modules\adm-zip'
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/adm-zip.js 1:9-22
 @ ./~/protractor/~/selenium-webdriver/remote/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/glob/glob.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\glob'
 @ ./~/glob/glob.js 43:9-22
 @ ./~/protractor/built/configParser.js
 @ ./~/protractor/built/plugins.js
 @ ./~/protractor/built/browser.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/~/adm-zip/zipFile.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\node_modules\adm-zip'
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/zipFile.js 10:13-26
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/adm-zip.js
 @ ./~/protractor/~/selenium-webdriver/remote/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/rimraf/rimraf.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\rimraf'
 @ ./~/rimraf/rimraf.js 6:9-22
 @ ./~/protractor/~/selenium-webdriver/io/index.js
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/tmp/lib/tmp.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\tmp\lib'
 @ ./~/protractor/~/tmp/lib/tmp.js 13:11-24
 @ ./~/protractor/~/selenium-webdriver/io/index.js
 @ ./~/protractor/~/selenium-webdriver/firefox/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/glob/sync.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\glob'
 @ ./~/glob/sync.js 4:9-22
 @ ./~/glob/glob.js
 @ ./~/protractor/built/configParser.js
 @ ./~/protractor/built/plugins.js
 @ ./~/protractor/built/browser.js
 @ ./~/protractor/built/index.js

ERROR in ./~/fs.realpath/index.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\fs.realpath'
 @ ./~/fs.realpath/index.js 8:9-22
 @ ./~/glob/glob.js
 @ ./~/protractor/built/configParser.js
 @ ./~/protractor/built/plugins.js
 @ ./~/protractor/built/browser.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/~/adm-zip/util/utils.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\node_modules\adm-zip\util'
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/util/utils.js 1:9-22
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/util/index.js
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/adm-zip.js
 @ ./~/protractor/~/selenium-webdriver/remote/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/protractor/~/selenium-webdriver/~/adm-zip/util/fattr.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\protractor\node_modules\selenium-webdriver\node_modules\adm-zip\util'
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/util/fattr.js 1:9-22
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/util/index.js
 @ ./~/protractor/~/selenium-webdriver/~/adm-zip/adm-zip.js
 @ ./~/protractor/~/selenium-webdriver/remote/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/ws/lib/WebSocketServer.js
Module not found: Error: Can't resolve 'tls' in 'S:\projects\trunk\util_angular2\node_modules\ws\lib'
 @ ./~/ws/lib/WebSocketServer.js 15:10-24
 @ ./~/ws/index.js
 @ ./~/protractor/~/selenium-webdriver/safari.js
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

ERROR in ./~/fs.realpath/old.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\fs.realpath'
 @ ./~/fs.realpath/old.js 24:9-22
 @ ./~/fs.realpath/index.js
 @ ./~/glob/glob.js
 @ ./~/protractor/built/configParser.js
 @ ./~/protractor/built/plugins.js
 @ ./~/protractor/built/browser.js
 @ ./~/protractor/built/index.js

ERROR in ./~/options/lib/options.js
Module not found: Error: Can't resolve 'fs' in 'S:\projects\trunk\util_angular2\node_modules\options\lib'
 @ ./~/options/lib/options.js 6:9-22
 @ ./~/ws/lib/WebSocketServer.js
 @ ./~/ws/index.js
 @ ./~/protractor/~/selenium-webdriver/safari.js
 @ ./~/protractor/~/selenium-webdriver/builder.js
 @ ./~/protractor/~/selenium-webdriver/index.js
 @ ./~/protractor/built/index.js

**Comment by NickTomlin** [comment]
Hi there!

This sounds like an issue with `npm` or your environment; because of this, it is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
