### ISSUE TITLE
Waiting for Input element class attribute to change/disappear fails intermittently  

### ISSUE THREAD

**Issue by pedgarcia** [angular/protractor#3918]
I am using protractor 4.0.10 to test an angular 1.5.10 with chromedriverVersion: 2.26.436382

My test is basically checking if an inputbox behaves properly when typing an invalid email, and then when the email is correct.

For the first part, I wait until ng-invalid-email is present in the `class` attribute (and then test for it). This step always work fine.

After that, I clear() the inputbox and add a valid email to it. After doing so I wait to see if ng-invalid-email disappear using a helper function:

```
function waitClassValueToDisappear(fieldElement, class_value) {
    var local_class = class_value;
    browser.wait(function() {
      return element(by.model(fieldElement)).getAttribute('class').then(function(value) {
          //console.log(value ,' <> ', local_class);
          return value.indexOf(local_class) < 0;
      });
  }, 5000);
}
```

Most of the time, this seems to work properly but sometimes it times out. After doing some debugging, I found `ng-invalid-email` is kept as class attribute until the test above times out.

The test case screenshot shows the valid email in the inputbox and the inputbox has a blue frame (we are using red frame when ng-invalid-email is present).

I wonder if there is any problem in the way protractor queries the attributes of an ui element that could cause the behaviour above (or maybe this is provided by webdriver/selenium)?

If I uncomment the console.log above I see this when the error happens:

```
form-control  (..lots of other values..) ng-not-modified-remove-active ng-modified-add-active ng-valid-error-add-active ng-invalid-pattern-remove-active ng-valid-pattern-add-active ng-invalid-remove-active ng-valid-add-active  <>  ng-invalid-email (* once or twice at the beginning)
and then mutiples:
form-control ng-untouched ng-dirty ng-not-empty ng-invalid-email ng-valid-required ng-invalid-pattern ng-valid ng-valid-error ng-modified  <>  ng-invalid-email
(.... repeating until it times out)
```
So it looks like the object class attribute has changed, but ng-invalid-email is still present, even though the screenshot tells me it is valid.

For reference, the full test case is as follows:

```
    it(this.description, function() {
      ...
      utils.waitModelExist(cs.alerts.ADD_EMAIL_INPUT);
      browser.wait(EC.visibilityOf(app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT)), TIME_TO_WAIT_MILLISECONDS);
      app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT).sendKeys('username');
      actions.waitClassValueToBePresent(cs.alerts.ADD_EMAIL_INPUT, 'ng-invalid-email');
      expect(app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT).getAttribute('class')).toContain('ng-invalid-email');
      app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT).clear();
      //actions.waitForAttributeValue(cs.alerts.ADD_EMAIL_INPUT, '');
      app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT).sendKeys('username@nowitis.valid');
      //actions.waitForAttributeValue(cs.alerts.ADD_EMAIL_INPUT, 'username@nowitis.valid');
      actions.waitClassValueToDisappear(cs.alerts.ADD_EMAIL_INPUT, 'ng-invalid-email');
      expect(app.getAppElementByModel(cs.alerts.ADD_EMAIL_INPUT).getAttribute('class')).not.toContain('ng-invalid-email');
    });

```

Any ideas? Is this a protractor problem?

Thanks

Paulo

**Comment by NickTomlin** [comment]
Hi there!

Because it involves some debugging and isn't easily reproducible (and doesn't follow the issue template) your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by pedgarcia** [comment]
Sounds good. I asked on StackOverflow. Thanks
