### ISSUE TITLE
Add map() function to element.all

### ISSUE THREAD

**Issue by andresdominguez** [angular/protractor#392]
Some of my tests have to collect the values of multiple elements inside a parent element. 

For example, I want to know the labels inside a menu: 

```
Menu
  one
  two
  three
```

It would be nice to have a map function in `element.all`:

``` javascript
element.all(by.css('.menu .item')).map(function(item) {
  return item.getText();
}).then(function(labels) {
  expect(labels).toEqual(['one', 'two', 'three']);
});
```

Map would iterate through each element found with the locator. Then map would resolve all the promises and return a promise with an array of values.

**Comment by konrad-garus** [comment]
Sadly, it no longer works in 5.1. The `el` inside `map` has no `findElement` function (or equivalent).

**Comment by vermin-scripts** [comment]
i am not able to get value or row outside of function

`var trdata;
	 			
	 			$$('#tblAdvanceAdjEntry tbody tr').map(function(el)
	 			{
	 				return el.getText().then(function(row1){
	 					return row1;
	 				});

	 			}).then(function(row){

	 					console.log("rows --->"+row.length);
	 					trdata = row.length;
	 					
	 					console.log('trdata --'+trdata);
	 					var r = trdata - 2;
	 					element(by.xpath('//*[@id="'+r+'_AdjAgainstAmt"]')).sendKeys(adjsamt);
	 					return row.length;
	 			});
console.log("result "+trdata);//getting value of row here but it returns undefine

`
