### ISSUE TITLE
No elment found error when validating for is displaying

### ISSUE THREAD

**Issue by manaswinid** [angular/protractor#3937]
Hi ,

While i am validating the displaying of element..if the element is not there then it is shwing me no element found error.
expect(element(by.xpath("//div[@ng-repeat='(colRenderIndex, col) in colContainer.renderedColumns track by col.uid']")).isDisplayed()).toBe(true);

when the elemnt is not there it is thorwing me error No element found.

Please help me with it.

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
