### ISSUE TITLE
Problem running tests with node-webkit 0.19.3

### ISSUE THREAD

**Issue by ShobanaV** [angular/protractor#3940]
I recently upgraded my desktop app to node-webkit 0.19.3. I upgraded all related modules, still I am getting the following error while running protractor tests.

[16:48:47] E/launcher - chrome not reachable
  (Driver info: chromedriver=2.24 (8edff6e8b274c45f7265f8a1746be68055dc0939),platform=Windows NT 10.0.10586 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62.95 seconds
Build info: version: '2.42.2', revision: '6a6995d', time: '2014-06-03 17:42:03'
System info: host: 'host', ip: 'xxxx', os.name: 'Windows 8', os.arch: 'x86', os.version: '6.2', java.version: '1.6.0_45'
[16:48:47] E/launcher - Process exited with error code 199

- Node Version: 7.4.0
- Protractor Version: 4.0.14
- Angular Version: 1.5.8
- Browser(s): node-webkit 0.19.3
- Operating System and Version - Windows 10 64-bit

The test code does not matter for this error. My protractor config file is as follows - 

```
// conf.js

exports.config = {
    specs: ['./testfile.js'],
    
    framework: 'mocha',
    
    mochaOpts: {
        reporter: "spec-xunit-file",
        slow: 2000
    },
    
    chromeDriver: function() {
        return '../../../source/chromedriver';
    }(),
    
    seleniumServerJar: function() {
        return '../../../source/selenium-server-standalone-2.42.2.jar';
    }(),  
    
    seleniumPort: 4444
}
```

**Comment by cnishina** [comment]
Hi! Protractor runs with node. I am not sure what kind of support is required to run Protractor with node-webkit. However, chromeDriver and seleniumServerJar take strings and not functions. See https://github.com/angular/protractor/blob/master/lib/config.ts#L77.

This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
