### ISSUE TITLE
protractor.ExpectedConditions is undefined with 4.0.14

### ISSUE THREAD

**Issue by jmcollin78** [angular/protractor#3944]
Hi there!

- Node Version: `7.4.0`
- Protractor Version: `4.0.14`
- Browser(s): `Firefox 45.6.0`
- Operating System and Version `CentOS7 Linux localhost.localdomain 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
- Your protractor configuration file:
```
exports.config = {
    framework: 'mocha',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['../../../*/tests/protractor/**/*.js'],
    baseUrl: 'http://localhost:3001',
    getPageTimeout: 10000,
    allScriptsTimeout: 10000,
    mochaOpts: {
        timeout: 30000, // ms,
        reporter: 'spec',
        slow: '2000', // a test is slow if it takes over 1 sec to accomplish
        delay: true
    }
}
```
- A relevant example test:
Simply run this:

```
var protractor = require('protractor'),
	EC = protractor.ExpectedConditions;
console.log('Protractor ExpectedConditions is: "%s"', EC);
```

- Output from running the test
`Protractor ExpectedConditions is: undefined`

- Steps to reproduce the bug
Simply run this test.

I will try downgrading and keep you in touch with the result.

**Comment by cnishina** [comment]
Closing this issue because `ExpectedConditions` is available on the index and works with the command line interface. It is done here: https://github.com/angular/protractor/blob/master/lib/index.ts#L40. It also gets created in the ProtractorBrowser constructor and is no longer static (https://github.com/angular/protractor/blob/master/lib/browser.ts#L385).

This was not a breaking change since CLI users would not have this issue.

How in the context of`require('protractor')`, if the browser has not been created, then the ExpectedConditions would also not be created.

**Comment by jmcollin78** [comment]
Thx for your answer which give me the origin of my mistake: you can't anymore initialize a ExpectedConditions object in vars declaration but you have to get the ExpectedConditions just before you need it.
So this don't work anymore:

```
var protractor = require('protractor'),
	EC = protractor.ExpectedConditions;
	
	describe(...
		it ( ..., function(){
			browser.wait(EC.visibilityOf($element));
```
			
and you must fix that with something like:
```
var protractor = require('protractor');
	
	describe(...
		it ( ..., function(){
			var EC = protractor.ExpectedConditions
			browser.wait(EC.visibilityOf($element));
```

> This was not a breaking change since CLI users would not have this issue.
Changing a static object to non static is a breaking change... The fact is a that preceding code don't work anymore after the change. But it's not important here.

**Comment by cnishina** [comment]
Yup if your browser session is changing after every `it`, then you would produce a webdriver stack trace that the session is closed. If you wanted to used EC before the browser was created, you would do something like this (not recommended):

```
var protractor = require('protractor');
var ProtractorExpectedConditions = protractor.ExpectedConditions;
var EC = new ProtractorExpectedConditions(null);
```

Before you use EC, it needs to know about the browser instance:
```
EC.browser = browser;
```

Previously we defaulted to just the global browser object. The reason for the change is that you cannot fork the browser and use EC at the same time. If you did (previously) it would only make checks against the first browser session.

So the new way would let you do something like:

```
var browser2 = browser.forkNewDriverInstance();
var EC2 = browser2.ExpectedConditions;
browser2.wait(EC2.elementToBeClickable( some element ), 5000);
```

See https://github.com/angular/protractor/blob/master/spec/basic/expected_conditions_spec.js#L179.
