### ISSUE TITLE
Replace browser.rootEl with browser.setAngularRoot()

### ISSUE THREAD

**Issue by mgiambalvo** [angular/protractor#3947]
Similar to replacing `browser.ignoreSynchronization` with `browser.waitForAngularEnabled()`, we should change setting the root element from a property to a method call.

**Comment by mgiambalvo** [comment]
Also, make sure we do the right thing in this case:

```
browser.setAngularRoot('x');
browser.get('http://something.com').then(() => {
   element(by.css('button')).click();
});
browser.setAngularRoot('y');
element(by.css('other_button')).click();
```

**Comment by sjelin** [comment]
Same with `useAllAngularTestabilities`
