### ISSUE TITLE
Protractor - how to select heavily nested dropdown element?

### ISSUE THREAD

**Issue by nikhiletc** [angular/protractor#3951]
``<li ng-show="vm.authenticated &amp;&amp; vm.admin" ng-class="{ active: isActive('/users') || isActive('/suppliers') || isActive('/resources')}" class="dropdown active"><a class="dropdown-toggle ng-binding" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Administrative tools <span class="caret"></span> </a> <ul class="dropdown-menu"> <li><a href="#users" translate="" class="ng-scope">User Accounts</a></li> <li><a href="#suppliers" translate="" class="ng-scope">Suppliers</a></li> <li><a href="#resources" translate="" class="ng-scope">Resources</a></li> </ul></li>``

How can I get protractor to click the links like "User Accounts" within the dropdown menu?

**Comment by juliemr** [comment]
Please direct general support questions like this one to an appropriate support channel, see https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
