### ISSUE TITLE
Wrong url in your website

### ISSUE THREAD

**Issue by gtzinos** [angular/protractor#3976]
Hello,

Please update the url in http://www.protractortest.org/#/mobile-setup which appeared in ( Use webdriver-manager to install appium and the Android SDK. See details on the WebDriver Manager page. ).

Change 

https://github.com/angular/webdriver-manager/blob/master/mobile.md 
to
https://github.com/angular/webdriver-manager/blob/master/docs/mobile.md

**Comment by cnishina** [comment]
This has been fixed but has not been deployed yet. https://github.com/angular/protractor/pull/3957

**Comment by gtzinos** [comment]
Okay thank you.
