### ISSUE TITLE
Is it possible to make Hybrid framework in protractor testing?

### ISSUE THREAD

**Issue by nikhiletc** [angular/protractor#3979]
I want to start project its built in angular js , i am new in protractor testing, in that application many forms and different pages ,but forms are almost similar ,i want to create hybrid framework for this project,because i think its easier for me to test lots of forms, please help me to decide,if you have any hybrid framework model ,then please share. 
thank you in advance .

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by nikhiletc** [comment]
Hi Nick!
i asked same question on stackOverflow and Gitter too ,but i didn't get answer yet. can you suggest me which framework is good except page Object Model.
