### ISSUE TITLE
Stdout contains function body

### ISSUE THREAD

**Issue by edi9999** [angular/protractor#3981]
- Node Version: `6.9.4`
- Protractor Version: `5.0.0`
- Angular Version: `1.59`
- Browser(s): `Chrome`
- Operating System and Version `CentOS`

It seems that protractor outputs a lot of information in the webdriver output : 

Some of it is useful : 

```
protractor             | 2017-01-17T08:46:27.139805270Z 08:46:27.139 INFO - Executing: [find elements: By.cssSelector: .login-btn])
protractor             | 2017-01-17T08:46:27.215414640Z 08:46:27.214 INFO - Done: [find elements: By.cssSelector: .login-btn]
```

But some of the output contains functions : 

```
protractor             | 2017-01-17T08:47:02.016505394Z catch(e) { throw (e instanceof Error) ? e : new Error(e); }, [select option, My options, null, body]])
protractor             | 2017-01-17T08:47:02.029702763Z 08:47:02.029 INFO - Done: [execute script: try { return (function (cssSelector, searchText, using) {
protractor             | 2017-01-17T08:47:02.029779716Z   using = using || document;
protractor             | 2017-01-17T08:47:02.029799778Z
protractor             | 2017-01-17T08:47:02.029813343Z   var elements = using.querySelectorAll(cssSelector);
protractor             | 2017-01-17T08:47:02.029825790Z   var matches = [];
protractor             | 2017-01-17T08:47:02.029838945Z   for (var i = 0; i < elements.length; ++i) {
protractor             | 2017-01-17T08:47:02.029852925Z     var element = elements[i];
protractor             | 2017-01-17T08:47:02.029866244Z     var elementText = element.textContent || element.innerText || '';
protractor             | 2017-01-17T08:47:02.029880314Z     if (elementText.indexOf(searchText) > -1) {
protractor             | 2017-01-17T08:47:02.029894203Z       matches.push(element);
protractor             | 2017-01-17T08:47:02.029908060Z     }
protractor             | 2017-01-17T08:47:02.029921158Z   }
protractor             | 2017-01-17T08:47:02.029933373Z   return matches;
protractor             | 2017-01-17T08:47:02.029946488Z }).apply(this, arguments); }
```

This makes the output of the webdriver almost impossible to read. 

I found these functions in : 

```
node_modules/protractor/built/clientsidescripts.js
```

I don't understand why some of the functions are dumped completely (eg Function.toString is called), and some functions are shown nicely (only the name of the function + arguments are shown).

Can you explain ?

**Comment by juliemr** [comment]
Hi, this is output from the webdriver server. It looks like you're using something else to run protractor, that is probably causing these logs to be piped to your main output. Can you share your setup?

**Comment by edi9999** [comment]
Yes, I wasn't totally clear on that, **I'm actually looking at the webdriver-manager logs**, because some of the logs there are useful , for example : 

```
INFO - Executing: [find elements: By.cssSelector: .login-btn])
```

but the logs of function body in that output are very disturbing. 

My main protractor output doesn't contain these function logs

**Comment by edi9999** [comment]
Update on this ? I don't think the function logs make any sensee in the *webdriver-manager* logs. Is this something that can be silenced ?

**Comment by juliemr** [comment]
We do not control the webdriver logs - those come from webdriver, and I often find value in seeing the function body there when debugging.
