### ISSUE TITLE
Add DirectConnect Support for Firefox 51+

### ISSUE THREAD

**Issue by theandrewlane** [angular/protractor#4005]
Currently ```directConnect``` can't be used with FF 48+. FF 51 was however released today (January 24th) and should now be able to fully support Protractor. 

The two other issues impacting ```directConnect``` have been fixed:
- **Fixed**: Selenium bug [#3115](https://github.com/SeleniumHQ/selenium/issues/3115)
- **Fixed**: FF bug [#1297551](https://bugzilla.mozilla.org/show_bug.cgi?id=1297551)

This will also require a Selenium 3.0.2 release

Current _Working_  FF configuration with ```directConnect```:

Browser: [FF 47.0.2](https://ftp.mozilla.org/pub/firefox/releases/47.0.2/win64/en-US/)
Protractor: 5.0.0
Node: 7.4.0
OS: Win 7 Enterprise

```
 exports.config = {
    directConnect: true,
    process.env.BASE_URL,
    specs: ['e2e/tests/**/*-e2e.js'],
    capabilities: {
      browserName: 'firefox', //Allow execution against different browsers.
      marionette: false,
      shardTestFiles: !!process.env.SHARD_TESTS,
      maxInstances: process.env.E2E_MAX_INSTANCES || 2,
      allScriptsTimeout: 35000,
      pageLoadingStrategy: 'eager',
    },

    framework: 'jasmine2',

    plugins: [
      {path: path.resolve(__dirname) + '/protractor-plugins/coverage-plugin.js'},
      {path: path.resolve(__dirname) + '/protractor-plugins/reset-plugin.js'},
      {path: path.resolve(__dirname) + '/protractor-plugins/screenshot-plugin.js'}
    ],

    params: {
      disableAnimations: true,
      sharding: false,
      junitFileName: 'TESTS-protractor.xml'
    },

    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: {
      showColors: true,
      defaultTimeoutInterval: 30000,
      isVerbose: true,
      print() {
      } //disable and use jasmine-spec-reporter instead
    },
    onPrepare() {
      const jasmineEnv = jasmine.getEnv();
      browser.driver.manage().window().setSize(1280, 1024);
      }

      jasmineEnv.addReporter(new jasmineReporters.JUnitXmlReporter({
        consolidateAll: true,
        filePrefix: protractorConfig.params.junitFileName,
        savePath: 'results'
      }));

      jasmineEnv.addReporter(new SpecReporter({
        displayStacktrace: 'summary',
        displayPendingSpec: true,
        displaySpecDuration: true
      }));
      
      require('jasmine-expect');
    }
  };

```

**Comment by mgiambalvo** [comment]
Please see #3823 and #3953. Support for Firefox 51+ with directConnect will be in the next release. For those not using directConnect, until selenium standalone 3.0.2 is released, 3.0.0-beta4 will work.

**Comment by theandrewlane** [comment]
@mgiambalvo How soon can we expect the next release? :)

**Comment by mgiambalvo** [comment]
We're hoping for Monday. You should be able to test on Firefox 51 using
selenium standalone until then. You can see how our CircleCI config does it
for an example:
https://github.com/angular/protractor/blob/master/circle.yml

**Comment by joeydaowang** [comment]
I am using Protractor 5.1.1 + webdriver-manager 12.0.2, directConnect  true doesn't work with FF 51.0.1. I still have connection timeout issue. 
```
Here is partial of my config file
    capabilities: {
        'browserName': 'firefox',
        marionette: false,
        shardTestFiles: true,
        maxInstances: 3,
    },
    baseUrl: 'http://localhost:8000',
    framework: 'jasmine2',
    jasmineNodeOpts: {
        defaultTimeoutInterval: 120000,
        realtimeFailure: true
    },
    directConnect: true,
```
Did I do something wrong here?

**Comment by spac-valentin** [comment]
I am having the exact same issue as @joeydaowang. Any news on this?

**Comment by ngie-mp** [comment]
same issue as @joeydaowang; protractor 5.1.1, webdriver-manager 12.02 and FF 51.0.1.

**Comment by glepretre** [comment]
@joeydaowang @ngie-mp I think you should enable `marionette` (default, `true`) when running Firefox 48+, but this might not fix your issue though

**Comment by joeydaowang** [comment]
@glepretre I tried with marionette enabled. It didn't help.
Today tried with FF 52, the same issue still.
@mgiambalvo any idea what I have done wrong? thanks

**Comment by rahulmr** [comment]
@joeydaowang me too having same issue with latest protractor version and latest webdriver

**Comment by heathkit** [comment]
See the issue with directConnect here: https://github.com/angular/protractor/issues/4253

If you're on FF52 and Selenium 3, you no longer need to set marionette (it's true by default).
