### ISSUE TITLE
browser.setLocation() not working in browser, browser.get() not working on device with cordova and appium

### ISSUE THREAD

**Issue by lordgreg** [angular/protractor#4019]
Hi there!

Bug report
---

- Node Version: `6.9.4`
- Protractor Version: `5.0.0`
- Angular Version: `1.5.0`
- Browser(s): `chrome and cordova app on Android Emulator, real device or iOS simulator and real devices`
- Operating System and Version `MacOS Sierra`
- Your protractor configuration file (for browser test)
```js
'use strict';

// An example configuration file.
exports.config = {
  capabilities: {
    'browserName': 'chrome'
  },

  baseUrl: 'http://localhost:3000',
  specs: ['test/protractor/**/*.js'],
};
```

- Your protractor configuration file (for hybrid app test)
(connected using appium and clear instructions [here](https://github.com/angular/protractor/blob/master/docs/mobile-setup.md))
```
'use strict';

exports.config = {
  seleniumAddress: 'http://localhost:4723/wd/hub',
  capabilities: {
    app: '/full/path/to/app/file.app',
    autoWebview: true,
    browserName: '',
    platformName: 'iOS',
    xcodeConfigFile: '/Users/gregorpapez/Projects/@Test/generator-m-ionic-demo/xcodeConfig.xcconfig',
    automationName: 'XCUITest', // use with xcode8
    platformVersion: '', // include version of available simulator os
    udid: 'b4adddddda76e9d4e69be5f6b19c7dfc11544224',
    deviceName: 'iPad ABC', // to start on simulator: iPad 2; to get udid from real device, type `instruments -s devices`
  },

  baseUrl: 'http://localhost:3000',

  specs: ['./test/protractor/**/*.js'],

  onPrepare: function () {
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);
  }
};
```

- A relevant example test
```
'use strict';

describe('Debug page', function () {

    // console.log('window', window);
    // window.location.hash('http://localhost:3000/#/main/list');

    // works on device and browser
    // browser.get('file:///var/containers/Bundle/Application/A4B07338-8600-48F0-ADEF-6D0983BD369A/My%20Project.app/www/index.html#/main/debug');

    // works only in browser
    // browser.get('/#/main/debug');
    // browser.get('http://localhost:8100/#/main/debug');

    // works only on device
    // browser.setLocation('/main/debug');
  });

  it('should grade passwords', function () {

    var passwordInput = element(by.model('ctrl.password.input'));
    var passwordStrength = element(by.binding('ctrl.password.strength'));

    // weak
    passwordInput.sendKeys('my');
    expect(passwordStrength.getInnerHtml()).toEqual('weak');
    expect(passwordStrength.getAttribute('class')).toContain('badge-assertive');

    // medium
    passwordInput.sendKeys('test');
    expect(passwordStrength.getInnerHtml()).toEqual('medium');
    expect(passwordStrength.getAttribute('class')).toContain('badge-energized');

    // strong
    passwordInput.sendKeys('tesyasdft');
    expect(passwordStrength.getInnerHtml()).toEqual('strong');
    expect(passwordStrength.getAttribute('class')).toContain('badge-balanced');

  });
});
```

- Output from running the test
1. using browser.setLocation in browser, I get `window.angular` is not defined.
2. using browser.get in hybrid app doesn't do anything

- The URL you are running your tests against (if relevant)

You can try to install app yourself like this:
1. clone https://github.com/mwaylabs/generator-m-ionic-demo
2. npm i && bower i
3. gulp --cordova 'prepare android'
4. gulp --cordova 'build android'
5. run appium
6. run protractor CONFIG_ABOVE

My question is... how can I achieve running browser.get() without adding full path on hybrid app or at least so, that my test would ALWAYS work, no matter if testing in chrome or through hybrid app.

**Comment by lordgreg** [comment]
_To answer myself, and ask the community if there's any other non-hacky way:_

adding protractor part in config:
```
  onPrepare: function () {
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);

    //To navigate using file:// rather than http://
    var defer = protractor.promise.defer();

    /*globals browser*/
    browser.ignoreSynchronization = true;

    browser.executeScript('return window.location;').then(function (location) {
      browser.resetUrl = 'file://';
      browser.baseUrl = location.origin + location.pathname;
      defer.fulfill();
    });

    return defer.promise;
  }
```

fixes that, so that `browser.get('#/main/debug');` works. The workaround/fix was found on next website: http://flashquartermaster.com/2016/08/02/automated-cross-platform-testing-of-ios-and-android-hybrid-ionic-cordova-angular-apps-using-cucumber-protractor-chai-and-appium/

**Comment by sjelin** [comment]
So to be clear, the problem here is that you've got a different domain origin on different browsers?  Personally, I'd set `browser.baseUrl` in `config.onPrepare`.  We don't answer support questions here, and this isn't really a bug, so I'll mark it as a feature request.  But again, I think the best workaround is to set `browser.baseUrl` in `config.onPrepare`.  I'll even document it 😄

**Comment by lordgreg** [comment]
Thank you for your reply @sjelin. I'd thought this was some kind of issue since I've had to constantly use different approach in test itself, to achieve the same result. 

Overwriting baseUrl sounds like falsy way-to-go. 

But then again, I'm probably wrong. However, there's 0 docs about this topic that's why I've posted this as issue.

Thank you for updating the docs and replying.

👍

**Comment by pardhiva16** [comment]
@sjelin  What is the configuration then for  in windows OS, on Android Physical Actual Device connected via USB to Windows machine, appium and protractor combination.  The objective here is to Open a chrome browser on the Android Actual Device and go to Angular website.

I keep getting errors where in one time chrome browser on the android device opens if i use appium desktop, but the browser remains at data and hangs

If i kill appium desktop and use cmd and type this command of webdriver-manager start --avd none --appium 

then it says error code of  E/launcher - Process exited with error code 199 and in trouble shoot mode it says baseurl was not given.  I am Not testing an App.  I am only testing angular website url on chrome browser on actual android device connected to windows machine via USB cable

My conf,js code is below

exports.config = {
 // directConnect: true,
  //seleniumAddress: 'http://localhost:4733/wd/hub', //appium
  seleniumAddress: 'http://localhost:4723/wd/hub', //appium

  specs: [
    'lmsportalexampleTC3_spec.js'
	  ], 
  
	 capabilities: {
	  
	  'browserName': 'chrome',
	 //appium-version: '1.6',
	 
	 'deviceName': '0715f7905cae3234',
	 //deviceName: 'Android Device',
	 'platformName': 'android',
	// udid: '0715f7905cae3234',
     //platformVersion: '4.4',
	 'platformVersion': '7.0',
     
     //'browserName': 'Android',
	 autoWebview: true,     
	 autoWebviewTimeout : 10000,
	 newCommandTimeout: 300000
      
   },
	
	//directConnect: true,
	  // baseUrl: (
  // baseUrl: 'http://www.google.com/'
  //),   
  
  onPrepare: function () {
    var wd = require('wd'),
      protractor = require('protractor'),
      wdBridge = require('wd-bridge')(protractor, wd);
    wdBridge.initFromProtractor(exports.config);
  },
  
  //ignoreUncaughtExceptions: true,
  
  
   // configuring wd in onPrepare
  // wdBridge helps to bridge wd driver with other selenium clients
  // See https://github.com/sebv/wd-bridge/blob/master/README.md
 
  // configuring wd in onPrepare
  // wdBridge helps to bridge wd driver with other selenium clients
  // See https://github.com/sebv/wd-bridge/blob/master/README.md
  

 // onPrepare: function () {
	  
//	require('webdriver-js-extender').patch(
  //  require('selenium-webdriver/lib/command'),
  //  require('selenium-webdriver/executors'),
  //  require('selenium-webdriver/http'));
		
//browser.get("http://www.thetestroom.com/jswebapp/");
		
 //  var extendedWebdriver = require('webdriver-js-extender').extend(webdriver);

 //   extendedWebdriver.setNetworkConnection(5);
	  
 // },
  
  //const { SpecReporter } = require('jasmine-spec-reporter');
  
  
    
	
	
	//  specs: {
  //  'lmsportalexampleTC3_spec.js'
	//  }, 
	
	
		
			//cap.setCapability(MobileCapabilityType.DEVICE_NAME, "My Actual Android Samsung EJ Phone");
		//cap.setCapability(MobileCapabilityType.DEVICE_NAME, "My Phone"); // Actual Device So, We are using EJ Samsung Phone due to emulator error on EJ machine
		//cap.setCapability("udid", "0715f7905cae3234"); // These steps are required for EJ Samsung Phone
		//cap.setCapability("platformName", "Android");
		//cap.setCapability("platformVersion", "7.0");
		
  

	  
  // baseUrl: 'http://yourwebsite.com'),
	  
	useAllAngular2AppRoots: true,
	
	framework: 'jasmine2',
	
	jasmineNodeOpts: {
	
	//showColors: true,
   defaultTimeoutInterval: 30000
  },
	

	  
 };

====================================================

TestCase1spec.js code is below

describe ("Text Site for input field on home page", function() {
	
	it ("To Test input field and check text output", function() {
		
	  //browser.get("http://www.thetestroom.com/jswebapp");	
	  
	    browser.driver.get("http://www.thetestroom.com/jswebapp");	
		
		        //browser.get("http://www.google.com");	
		
          //extendedWebdriver.get("http://www.thetestroom.com/jswebapp/");
		
         //browser.get("http://www.thetestroom.com/jswebapp/");
		
		element(by.model("person.name")).sendKeys("Test LMS Portal Text");
		
		element(by.binding("person.name")).getText().then(function(text){
			console.log(text);
				});
		
	
	});
	
	
	

});


cmd output is here

[10:53:27] D/launcher - Running with --troubleshoot
[10:53:27] D/launcher - Protractor version: 5.3.0
[10:53:27] **D/launcher - Your base url for tests is undefined**
(node:13376) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[10:53:27] I/launcher - Running 1 instances of WebDriver
[10:53:27] I/hosted - Using the selenium server at http://localhost:4723/wd/hub
[10:53:28] E/launcher - **An unknown server-side error occurred while processing the command. Original error: Cannot read property 'forceStop' of undefined**
[10:53:28] E/launcher - **WebDriverError: An unknown server-side error occurred while processing the command. Original error: Cannot read property 'forceStop' of undefined**
    at Object.checkLegacyResponse (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at Function.createSession (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\chrome.js:761:15)
    at createDriver (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\index.js:626:16)
    at Hosted.getNewDriver (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
[10:53:28] E/launcher - Process exited with error code 199

C:\Users\UserName\AppData\Roaming\npm\node_modules\protractor\example>



Please help me. It has been 4 days with this issue and it is really sad for QA.

Thanks,

EJ
