### ISSUE TITLE
Browser freezes when fixture.debugElement is expected to be Null 

### ISSUE THREAD

**Issue by egdraper** [angular/protractor#4020]
I have a test that checks if a DOM element has been removed by an ngIf. When I grab the DOM element using: fixture.debugElement.query(By.css(".something")) the result is either null or a DOM element.

If the result is null, then the following test works fine. But, if the test result contains an element, it doesn't simply fail the test, it freezes up the debug browser.

The test looks like this:

`var result = fixture.debugElement.query(By.css("#something"))`
`expect(result).toBe(null) // same goes for .toBeFalsy(), .toEqual(null)`

This is not a problem if you use document.getElementById("something") to get the element. So the issue seems to be only if you try to check if a fixture element is null when it is not.

**Comment by cnishina** [comment]
`fixture.debugElement` sounds like this should be [filed against the angular project](https://github.com/angular/angular/issues/new) and not Protractor.

**Comment by volodyad** [comment]
You should read this - https://medium.com/@martatatiana/poor-detective-angular2-browser-crash-and-debugelement-f0a651dbf33#.ckjomzy34
