### ISSUE TITLE
textToBePresentInElement() method of ExpectedConditions class is not working.

### ISSUE THREAD

**Issue by helloabhi** [angular/protractor#4030]
Test to reproduce:
Navigate to https://app.p3fy.com/#/login
Enter any email address and password(it need not correct)
click on Sign In

Expected Output:
Sorry, invalid credentials! modal appears.

My test is to wait for the modal to contain text "Sorry, invalid credentials!" (using textToBePresentInElement())and then get the text(using getText()).

Below is my code which proves that textToBePresentInElement() is not working. I crosschecked the same in selenium webdriver and it works

**PageObject.js**

```
var errorModal = element(by.id('errorDialog'));

this.getErrorText = function(){

var until = protractor.ExpectedConditions;
browser.wait(until.textToBePresentInElement(errorModal, "Sorry, invalid credentials!"), 3000, "Not able to find");


     return errorModal.getText();

 };
```

**Spec.js**

`expect(Login_Page.getErrorText()).toMatch('Sorry, invalid credentials!');`
**Output**

> Message: Expected '' to match 'Sorry, invalid credentials!'.

**Comment by Batajus** [comment]
Could it be that you need to use the child of your modal dialog? 
Something like:  `var errorModal = element(by.id('errorDialog')).element(by.css('.modal-body'))`

Did the code work at an earlier point in time?

**Comment by helloabhi** [comment]
I tried using the child of the dialog box but no help. Yes, it worked 1 once but after that it didn't. The main culprit is textToBePresentInElement() method which is not working. I tried the same using Selenium Webdriver api and it worked smooth. I have mentioned the site url, can you please look into the issue.

**Comment by Batajus** [comment]
So i have tried a little bit on your site. The waiting method is still working correctly, but on my tests there was an unknown delay between the execution of the code lines. As a consequence the waiting method will start to wait, when the modal dialog disappears, so the method cannot find an element with the given text. 
As a workaround i removed the waiting method and the test was successful. 
Maybe you should look for the delay between the execution of the code lines. 

By the way i'm not a contributer, just a random guy, who wants to help ;-) . Maybe i'm wrong.

**Comment by helloabhi** [comment]
Yes, correct. This is what I am assuming. Anyways, things are not correct in protractor. There is a delay which should be ideally as compared to selenium webdriver which works smooth. People need to fix this kinda bug. Removing the wait is not correct as it will pass 70-80% of time, run for 10 times, you'll find it fail atleast once because of the internet and protractor speed :). I request concerned people to look into this and resolve this.

**Comment by pittgoose** [comment]
Speculation segment: 
Ok, I don't know if I can explain the reason why it's not working correctly, but my guess is that because the element you are looking for doesn't even exist on the DOM when you begin to perform the test (it's a popup) it immediately fails before it even shows up. 

Definite answer:
So, instead of checking for the **text** in an element when it appears, try instead to check that **an element containing that text** appears. Here's a short piece of code which is passing for me:
```
browser.get('https://app.p3fy.com/#/login');
        element(by.css('[name="email"]')).sendKeys('pittgoose@sampleemail.com');
        element(by.css('[name="password"]')).sendKeys('blah');
        element(by.css('[type="submit"]')).click();
        browser.wait(ExpectedConditions.visibilityOf(element(by.cssContainingText('#errorDialog', 'Sorry, invalid credentials!'))), 3000, 'No!');
```

**Comment by helloabhi** [comment]
Excellent this is what I was expecting. Thanks a lot @pittgoose

**Comment by wswebcreation** [comment]
Going to close this for now
