### ISSUE TITLE
Link to config on site should point to latest release version

### ISSUE THREAD

**Issue by zuzusik** [angular/protractor#4031]
Now link points to the latest master, which can be confusing since there could be some changes that are not available in latest release. For instance, now `disableChecks` option is there, though it is not available in `5.0.0`.

I am talking about this link:

<img width="325" alt="screen shot 2017-01-30 at 18 23 55" src="https://cloud.githubusercontent.com/assets/4233080/22433621/4f80461a-e719-11e6-927a-e52d05ab9089.png">

**Comment by cnishina** [comment]
This should be resolved shortly in the next release.
