### ISSUE TITLE
Link to "Framework Adapters" and "Custom Frameworks" should be correct

### ISSUE THREAD

**Issue by ludmilanesvitiy** [angular/protractor#4051]
On the bottom of page : http://www.protractortest.org/#/frameworks
We have not correct links to http://www.protractortest.org/lib/frameworks/README.md (this page didn't exist).
Seems, that here should be link to GitHub:
https://github.com/angular/protractor/blob/master/lib/frameworks/README.md
Or something similar to it.

- Browser(s): `Chrome, IE`
- Operating System and Version `All`
- Steps to reproduce the bug
1. Open http://www.protractortest.org/#/frameworks
2. Scroll to the bottom
3. Click on link 'Framework Adapters for Protractor' or `Custom Frameworks'
![image1](https://cloud.githubusercontent.com/assets/18209841/22525603/42ee671e-e8e1-11e6-9279-00989663b135.jpg)
![image2](https://cloud.githubusercontent.com/assets/18209841/22525620/4d24338a-e8e1-11e6-8eb1-dcee0975ba8a.jpg)

**Comment by wswebcreation** [comment]
Issue is fixed and will be closed.
