### ISSUE TITLE
Problem with switching between Angular versions

### ISSUE THREAD

**Issue by kacpe-r** [angular/protractor#4056]
Hi there,
I'm trying to test an application which has several microservices. Their frontends are written in Angular1 or Angular2.
Right now I'm facing an issue. While I'm trying to go from page written in Angular 1 to page written in Angular2 I get a timeout error (raised by ExpectedConditions). Neither browser.sleep(), browser.refresh(), nor browser.waitForAngularEnabled(false) help me.
In the other hand if I'm trying to switch from Angular1 to Angular2 using browser.get(url) - everything works fine.

I've compared get() and refresh() methods from https://github.com/angular/protractor/blob/master/lib/browser.ts and the difference is visible with the naked eye.

Are you planning to improve performance in this area in the nearest future?

node v6.9.1
protractor v5.1.0

**Comment by heathkit** [comment]
How are you moving between AngularJS and Angular? Are you clicking a link? Client-side navigation isn't supported, though there is [a plan](https://github.com/angular/protractor/projects/3) for it. In the meantime, if you're navigating between different URLs, you'll need to use `browser.get()`
