### ISSUE TITLE
Typings error in browser.wait with ExpectedConditions v5.1.0

### ISSUE THREAD

**Issue by valburyakov** [angular/protractor#4057]
I got this error in `browser.wait(ExpectedConditions.visibilityOf(...))` after updating protractor to 5.1.0 and selenium 3.0.1. 
I also have installed `@types/jasminewd2` as in changelog
```javascript
Error:(20, 18) TS2345:Argument of type 'Function' is not assignable to parameter of type 'Promise<{}> | Condition<{}> | ((driver: WebDriver) => {})'.
  Type 'Function' is not assignable to type '(driver: WebDriver) => {}'.
    Type 'Function' provides no match for the signature '(driver: WebDriver): {}'
```

Typescript version  `2.0.9`

Seems it uses wrong typings, because browser.wait supports Function type. 
in 5.0.0 version browser.wait is in abstract class `AbstractWebDriver` but in 5.1.0 this class is empty
in 5.1.0 method `wait`  declared in promise namespace of webdriver

**Comment by valburyakov** [comment]
The problem was solved by installing manually @types/selenium-webdriver. Seems i had already old typings for selenium-webdriver installed with types/protractor-helpers. Removing and reinstalling these types made it works.

**Comment by NickTomlin** [comment]
@valburyakov thanks for reporting back! Glad you figured it out!
