### ISSUE TITLE
Typings error for ElementArrayFinder.filter in v5.1.0

### ISSUE THREAD

**Issue by massimocode** [angular/protractor#4058]
Looking at this commit:
https://github.com/angular/protractor/commit/995b1466d8a9d89be887e6e87c59a0bfe61c2bd4

This typing is incorrect:
```
filter(
      filterFn: (element: ElementFinder, index?: number) => boolean |
          wdpromise.Promise<boolean>): ElementArrayFinder {
```

It should be: 
```
filter(
      filterFn: (element: ElementFinder, index?: number) => boolean |
          PromiseLike<boolean>): ElementArrayFinder {
```

The current typing breaks the following lines of code:
```
element.all(by.className("blah")).filter(async row => (await row.$$(".ng-binding").get(0).getText()) === "foo");
```
The error is:
```
error TS2345: Argument of type '(row: ElementFinder) => Promise<boolean>' is not assignable to parameter of type '(element: ElementFinder, index?: number) => boolean | Promise<boolean>'.
  Type 'Promise<boolean>' is not assignable to type 'boolean | Promise<boolean>'.
    Type 'Promise<boolean>' is not assignable to type 'webdriver.promise.Promise<boolean>'.
```

I think the same applies to the other places where it is written `T | wdpromise.Promise<T>`
For example `ElementArrayFinder.get`

**Comment by jan-molak** [comment]
Indeed, I provided some more details in #4049

**Comment by sjelin** [comment]
Closing as duplicate.  I talk specifically about async/await issues in https://github.com/angular/protractor/issues/4049#issuecomment-278809243
