### ISSUE TITLE
Angular 2.0, Protractor config, and C#

### ISSUE THREAD

**Issue by mkiewicz505** [angular/protractor#4082]
I have been looking for an answer to this for a little bit now to no avail. Also, I have asked a similar question on stackoverflow and have gotten crickets. So maybe this is a feature request and not a usability question. We are developing an application in Angular 2.0 and I'm pretty new to Protractor. We already have a pretty robust suite of tests that have been built in Selenium using C# and the page object model. We'd like to keep using this going forward with the new Angular applications, but I'm having a problem setting it up. I can get everything to work, i.e. getting all of the Protractor specific elements to be recognized in Visual Studio and getting all of the Angular objects set up for each page. What I can't seem to do is get Visual Studio to act on these elements. As soon as I try to click on an angular element I get the following error

unknown error: angular is not defined

In Javascript I would need to set the the following attribute in the config.js file in order to run in Angular 2

useAllAngular2AppRoots: true

There seems to be no way of accessing this attribute and/or changing it in my code. Maybe I'm missing something. If this is not the right place to ask about this, please let me know. Perhaps this might be better addressed with the NuGet package we are using

Protractor version installed on system (not sure if this has an effect on what is running through my code) -- 5.1.0
Protractor package referenced in code -- 0.10.1.0
Selenium version 3.0.0
using Visual Studio 2015

- Reasons for adopting new feature
--This would increase the ability to test angular 2.0 applications using C# and Selenium
- Is this a breaking change? (How will this affect existing functionality)
--I don;t think this would have an effect on current functionality

**Comment by NickTomlin** [comment]
Hi There, 

I'm sorry your StackOverflow question hasn't gotten any answers. Unfortunately since this is about a specific language and setup I don't think this is the appropriate forum. I think your idea of asking about the NuGet package is a great start; you should be able to configure this if you are using protractor without a wrapper.

Thanks! 😄
