### ISSUE TITLE
Do a v5.1.2 release 

### ISSUE THREAD

**Issue by sjelin** [angular/protractor#4083]
A 5.1.2 release is the best way to get the doc updates in ba544224f6cfe07b8bf3a75772835d72f397cabc...237593a2fcb3fa7a75d560aca09ad701a15e8dbf onto the website.

@seanmay this could also be a good trial run of our release process for you (although @vikerman may have to help you, since some of the passwords are only accessible to google employees).  Our [release guide](https://github.com/angular/protractor/blob/master/release.md) is pretty clear but ping me on google hangouts (sjelin@google.com) if you have any questions.

**Comment by jukebox017** [comment]
Can we include the fixes in #4196 so we can use `--stackTrace` and `--verbose`?

**Comment by wswebcreation** [comment]
@sjelin and @seanmay ,

Is still still open, so a new 5.1.3 release needs to be made, or can this be closed?

**Comment by wswebcreation** [comment]
Going to close this issue for now. Look like all documents are merged and published onto the website.
