### ISSUE TITLE
stackTrace and includeStackTrace have no effect

### ISSUE THREAD

**Issue by cmacdonnacha** [angular/protractor#4084]
Bug report
---
Even though I've set  `stackTrace` and `includeStackTrace` to false a full stack trace is still being displayed.

- Node Version: `` 6.9.2
- Protractor Version: `` 3.10.8
- Angular Version: `` 1.5
- Browser(s): `` Chrome
- Operating System and Version `` Windows 10

**Here's my protractor.conf.js file:**

```
exports.config = {
  // The address of a running selenium server. Comment this out if you want
  //'seleniumAddress': 'http://localhost:4444/wd/hub',

  // The base url your app is served on.
  baseUrl: 'http://localhost:3000',

  // Jasmine is fully supported as a test and assertion framework.
  framework: 'jasmine',


  // Capabilities to be passed to the webdriver instance.
  'capabilities': {
    'browserName': 'chrome'
  },


  // Spec patterns are relative to the location of this config.
  specs: [
    config.protractor.sources
  ],
  
  stackTrace: false,

  // Options to be passed to minijasminenode.
  // See the full list at https://github.com/juliemr/minijasminenode/tree/jasmine1
  jasmineNodeOpts: {
    // If true, display spec names.
    isVerbose: false,
    // If true, print colors to the terminal.
    showColors: true,
    // If true, include stack traces in failures.
    includeStackTrace: false,
    // Default time to wait in ms before a test fails.
    defaultTimeoutInterval: 30000,
  }
};
```

**Comment by cnishina** [comment]
Hi. Issues should be on the latest framework version. This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
