### ISSUE TITLE
Protractor hangs indefinitely when running hundreds of tests which takes more than 6 hrs to execute

### ISSUE THREAD

**Issue by mmraghavendra** [angular/protractor#4085]
Protractor hangs indefinitely when running hundreds of tests which takes more than 6 hrs to execute. Sometimes(very rarely) we are seeing this behavior with jobs which takes 30 minutes to complete as well.

We have configured jenkins job to run around 1000 tests with shardTestFiles enabled and max instances set to 10. Job always gets stuck saying 1 or 2 instances of webdriver still running.

If we connect to remote windows machine running tests, we will see 2 or 3 nodejs processes running with 0% CPU. On killing these process job completes without generating Junit xml.

Hanging issue is being seen consistently for the all the jobs which run for more than 6hrs. Please suggest solution for this.

Using windows 2012R2 and windows 2016 server machines with protractor 4.0.14, nodejs 6.9.5 and firefox 41.0.2. Seeing same behavior with latest protractor 5.0.0 as well.

we have set below parameters in conf file,
	1. jasmineNodeOpts: {
		showColors: true, 
		defaultTimeoutInterval: 600000
	  }
	2. allScriptsTimeout: 600000
	3. ignoreUncaughtExceptions: true
	4. capabilities: {
		'browserName': 'firefox',
		'version': 'ANY',
		shardTestFiles: true,
		maxInstances: 10,
	  }
	5. browser.ignoreSynchronization: true
	6. restartBrowserBetweenTests: true

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by massimocode** [comment]
We have a similar issue. Where did you ask this question? We'd be interested in the answer.

**Comment by raghavmm** [comment]
Please refer below links,
http://stackoverflow.com/questions/42172909/protractor-hangs-indefinitely-when-running-hundreds-of-tests-which-takes-more-th
https://groups.google.com/forum/?fromgroups#!topic/angular/cwsTKzIl3fA

**Comment by mmraghavendra** [comment]
Please refer below links,
http://stackoverflow.com/questions/42172909/protractor-hangs-indefinitely-when-running-hundreds-of-tests-which-takes-more-th
https://groups.google.com/forum/?fromgroups#!topic/angular/cwsTKzIl3fA
