### ISSUE TITLE
webdriver-manager start command throws error - 'Unable to access jarfile C:\Users\...\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.1.0.jar', Selenium Standalone has exited with code 1

### ISSUE THREAD

**Issue by TwinkleA** [angular/protractor#4096]
![webdriver not starting](https://cloud.githubusercontent.com/assets/18376082/23056556/fb5bc382-f511-11e6-94ad-5c0039889fa2.PNG)

upon executing webdriver-manager update, it shows selenium standalone and other files already exists but when I execute webdriver-manager start it throws error saying selenium standalone not found 
(refer to attached image)

**Comment by Xotabu4** [comment]
I don't know where you got 3.1.0 version, since latest selenium-standalone-server version is 3.0.1
Try to delete this jar file, and re-download again with webdriver-manager update

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by TwinkleA** [comment]
@Xotabu4, Yes I finally ended up re-downloading the jar and drivers using webdriver-manager start.
but I don't know why that issue had occurred

**Comment by sfdcselenium01** [comment]
same problem here. ends up with rename "selenium-server-standalone-3.0.1.jar" to "selenium-server-standalone-3.1.0.jar" and problem resolved.

**Comment by ValenOnish** [comment]
I have the same issue, nothing helped (after 'webdriver-manager update' new version is 3.1.0 and rename doesn't work) Os: Sierra

**Comment by ValenOnish** [comment]
exit code 1 means 'no java runtime'.
The next can fix it: (just create a symlink to existed source)

sudo rm /usr/bin/java
sudo ln -s /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java /usr/bin

And everything works!

**Comment by banucres** [comment]
just try :  webdriver-manager update 
then try : webdriver-manager start
will work

**Comment by perry0105** [comment]
@banucres Yeah, "webdriver-manager update" command will download the missed selenium-server-standalone jar file
