### ISSUE TITLE
Protractor chromedriver version 2.27 windows 32 bits - click on element not working as expected

### ISSUE THREAD

**Issue by chantalv** [angular/protractor#4099]
Please describe your issue:

Since I've migrated to version 2.27 for chromedriver (as Chrome is now version Version 55.0.2883.87 m (64-bit)), my automated tests (protractor) are not working anymore . Now apparently the click on elements doesn't work fine .
 Or the problem is now linked with the search I am doing to get the element back ...

If known, describe the steps to reproduce the issue:

I am doing something like
 var ftth_rb = element(by.id('FTTH')); - as my page has only one element having this id
 .....
 obj.selectRadioButton(ftth_rb);

with
 obj.selectRadioButton = function(button){
 browser.wait(function (){
 return button.isPresent();
 }).then(function (){
 //console.log('FOUND element: ' + button);
 });
 button.click( );
 browser.sleep(1000);
};

Any idea :) ?? Thank you

**Comment by chantalv** [comment]
Just rerun my tests ... apparently the zoom was below < 100 % . It s working now  => the problem is if the zoom is not set on  100% . Question is : is there a way to solve this issue if the zoom is not 100% or to reset the zoom to 100% when starting chromedriver. 

Any idea ? thanks a lot

**Comment by NickTomlin** [comment]
Hi there!

I'm glad you were able to resolve your current issue. Additional questions are better for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
