### ISSUE TITLE
Protractor fake api calls after ng-click() are never executed

### ISSUE THREAD

**Issue by lararogu** [angular/protractor#4101]
I am using protractor to test an angular application.I am using the mock module to fake API calls.When I get to the home page of my app the calls are executed correctly,but when I go to another html within my app,the htttp GET requests are never executed.

 beforeEach(function () {
        browser.addMockModule('httpMocker', function () {
            angular.module('httpMocker', ['ngMockE2E'])
            .run(function ($httpBackend) {
                $httpBackend.whenGET('http://localhost:8450/api/api/Patient').respond([
               {
                   {some data}
               }
                ]);
  $httpBackend.whenGET('http://localhost:8450/api/api/Auscultation?patientD=fc66b586-95bc-e611-b086-0050b6c3366d').respond([
                { {some data}
                ]);
$httpBackend.whenGET('http://localhost:8450/api/api/Result?recordingId=816483b0-9d22-4abf-b7e0-e121fceb69cb').respond([
                { {some data}
                ]);
       The first 2 calls are executed at the home page.The 3rd is executed after an ng-click event but is never executed.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
