### ISSUE TITLE
Enable to handle an element in html-5 using protractor

### ISSUE THREAD

**Issue by BSC11426** [angular/protractor#4102]
Hi,
I newbie to protractor  and my requirement is automating third party tools
I was unable to detect an web element 
 the functionality of element is on click it changes it's state and pulls data from other application
it is changing its class value 
FROM
ui-select-container ui-select-multiple select2 select2-container select2-container-multi ng-empty ng-valid ng-touched
TO
ui-select-container ui-select-multiple select2 select2-container select2-container-multi ng-empty ng-valid ng-touched select2-container-active select2-dropdown-open open

Im curious about one of the tag here 'select2-container-disabled what way it might effect my code

i have tried constructing different xpath and even tried by locating ng attribute using protractor but unable to detect element in it and i found ng-disabled="$select.disabled" this tag ,I tried css,xapth and 

and input tag source code

<input type="search" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" role="combobox" aria-expanded="true" aria-owns="ui-select-choices-0" aria-label="Select box" aria-activedescendant="ui-select-choices-row-0-0" class="select2-input ui-select-search ng-valid ng-touched ng-dirty ng-valid-parse ng-empty" placeholder="Name/Env. Qlf:ID" ng-disabled="$select.disabled" ng-model="$select.search" ng-click="$select.activate()" style="width: 123px;" ondrop="return false;">

can you please suggest me how to deal with this element

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
