### ISSUE TITLE
Throw Error on Protractor Run in Angular-CLI application

### ISSUE THREAD

**Issue by davidtaylorjr** [angular/protractor#4105]
I go into terminal and run ng e2e on an Angular application and get the following readout:

```
[11:31:24] I/file_manager - creating folder C:\Users\davidtaylorjr\devbox\home\angula
r2-fundamentals\node_modules\protractor\node_modules\webdriver-manager\selenium
events.js:161
      throw er; // Unhandled 'error' event
      ^

Error: unable to verify the first certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1085:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:186:7)
    at TLSSocket._finishInit (_tls_wrap.js:603:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:433:38)
```

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

Additionally, please provide more relevant details (your configuration file, an example test) when posting on StackOverflow to help others help you.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by davidtaylorjr** [comment]
@NickTomlin 

No help on SO or Gitter.

As far as the config, I have not changed anything from Angular/CLI's default configuration. Should this not work out of the box?

**Comment by NickTomlin** [comment]
@davidtaylorjr I've just posted a comment on SO. This doesn't seem to be an issue with Protractor so let's keep the discussion focused there.
