### ISSUE TITLE
waitForAngular -> callback function not called when no testabilities

### ISSUE THREAD

**Issue by xtazy** [angular/protractor#4118]
- Node Version: `v7.3.0`
- Protractor Version: `5.1.1`
- Angular Version: `2.4.8`
- Browser(s): `chrome`
- Operating System and Version `windows 7`

Hello,

In the waitForAngular method of the clientsidescripts.js file the callback function is called when all testabilities have completed, but if there is no testabilities the callback function is never called.

Regards.

**Comment by NickTomlin** [comment]
Can you provide a small example (client side code, protractor conf, and test) that reproduces this?

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this since I haven't heard back. If you can provide the examples I've requested please do so and `@` mention me. I can re-open the issue then.
