### ISSUE TITLE
Launching Multiple Browser and running the URL's

### ISSUE THREAD

**Issue by shankarbkp** [angular/protractor#4123]
- Protractor Version: 5.1.1
- NPM : 3.10.10`
- Protractor VersioMicrosoft Edge(Ver 14), Safari(Ver 5.1.7), IE Ver11.0, firefox(ver 46.0) and Opera(Ver 43.0) Ver11.0, firefox(ver 46.0) and O: Win 10 43.0)
- Operating System and Version `: Win 10`

Conf.js

 multiCapabilities: [
     {
       browserName: 'chrome',

     },
     {
       browserName: 'firefox',

    },
   {
     browserName: 'MicrosoftEdge',
   },
 {
   browserName: 'Opera',
},
{
  browserName: 'Internet Explorer',
},
{
  browserName: 'safari',
}, ],

Protractor.js

  'webDriverUpdate': {
                    'browsers': ['chrome']
                },
                'webDriverUpdate': {
                  'browsers': ['Microsoft Edge']
                },
              'webDriverUpdate': {
              'browsers': ['safari']
        },

          'webDriverUpdate': {
            'browsers': ['Internet Explorer']
          },
          'webDriverUpdate': {
            'browsers': ['firefox']
          },
          'webDriverUpdate': {
            'browsers': ['Opera']
          },
          'webDriverStart': {
          'args': ['--chrome']
      },
                    'webDriverStart': {
                    'args': ['--Microsoft Edge']
                },
                'webDriverStart': {
                  'args': ['--Opera']

            },
            'webDriverStart': {
               'args': ['--safari']
            },
          'webDriverStart': {
              'args': ['--Internet Explorer']
          },
          'webDriverStart': {
              'args': ['--firefox']
          },

1.Issue: It is unable to launch Firefox,Safari,Microsoft Edge and Internet explorer though the drivers are downloaded in specific path based on the browser versions.

2.The following is the error message which is throwing in the console for all the browser
\node_modules\gulp-angular-protractor\node_modules\gulp-protractor\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: The best matching driver provider org.openqa.selenium.edge.EdgeDriver can't create a new driver instance for Capabilities [{count=1, browserName=Microsoft Edge

**Comment by NickTomlin** [comment]
Are you able to recreate this with a isolated example (perhaps just using Safari and Edge?); i'd like to remove gulp-protractor from the equation. Our own CI tests use [edge](https://github.com/angular/protractor/blob/15a187204bb8b87255d5f4622094eabc71206315/spec/ciSmokeConf.js#L43) so my gut says that the issue lies elsewhere.

**Comment by shankarbkp** [comment]
I am facing issue when i use these browser individually under capabilities . I went through the code which you shared however its the same. Can you share me the Drivers for browser version which is listed as part of my post.

Also, share me the drivers for the current version of the browsers which you have listed as part of the code.

**Comment by NickTomlin** [comment]
Unfortunately there is no more code to share. The best way to solve this is to produce a public repo with a [minimal, complete, and verifiable example](http://stackoverflow.com/help/mcve). Without this it is going to be difficult to actually understand your issue.

**Comment by NickTomlin** [comment]
I'm going to go ahead and close this for now since I haven't heard back. Please feel free to update with an example and `@` me and I can re-open.
