### ISSUE TITLE
exampleTypescript is not working

### ISSUE THREAD

**Issue by sixinli** [angular/protractor#4125]
Bug report
---

- Node Version: `v6.8.1`
- Protractor Version: `v4.0.14`
- Angular Version: `1.5.6`
- Browser(s): `Chrome/Firefox`
- Operating System and Version `Mac OS X 10.11.6`
- Typescript: `2.1.5`
- Your protractor configuration file (copied from `exampleTypescript/tmp/config.js`)
```javascript
"use strict";
exports.config = {
    framework: 'jasmine',
    capabilities: {
        browserName: 'chrome'
    },
    specs: ['spec.js'],
    seleniumAddress: 'http://localhost:4444/wd/hub',
    // You could set no globals to true to avoid jQuery '$' and protractor '$'
    // collisions on the global namespace.
    noGlobals: true
};
```
- A relevant example test (copied from `exampleTypescript/tmp/specs.js`)
```javascript
"use strict";
// Because this file references protractor, you'll need to have it as a project
// dependency to use 'protractor/globals'. Here is the full list of imports:
//
// import {browser, element, by, By, $, $$, ExpectedConditions}
//   from 'protractor/globals';
//
// The jasmine typings are brought in via DefinitelyTyped ambient typings.
var protractor_1 = require("protractor");
describe('protractor with typescript typings', function () {
    beforeEach(function () {
        protractor_1.browser.get('http://www.angularjs.org');
    });
    it('should greet the named user', function () {
        protractor_1.element(protractor_1.by.model('yourName')).sendKeys('Julie');
        var greeting = protractor_1.element(protractor_1.by.binding('yourName'));
        expect(greeting.getText()).toEqual('Hello Julie!');
    });
    it('should list todos', function () {
        var todoList = protractor_1.element.all(protractor_1.by.repeater('todo in todoList.todos'));
        expect(todoList.count()).toEqual(2);
        expect(todoList.get(1).getText()).toEqual('build an angular app');
    });
});
```
- Output from running the test
```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
FF

Failures:

  1) protractor with typescript typings should greet the named user
   Message:
     TypeError: Cannot read property 'get' of undefined
   Stacktrace:
     TypeError: Cannot read property 'get' of undefined
    at .<anonymous> (/Users/sixinli/public-git/protractor/exampleTypescript/tmp/spec.js:12:29)
==== async task ====
Asynchronous test function: beforeEach()
Error
    at .<anonymous> (/Users/sixinli/public-git/protractor/exampleTypescript/tmp/spec.js:11:5)
    at Object.<anonymous> (/Users/sixinli/public-git/protractor/exampleTypescript/tmp/spec.js:10:1)
    at tryModuleLoad (module.js:446:12)
    at require (internal/module.js:20:19)
    at Function.promise (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:650:9)
    at _fulfilled (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:759:13)
    at /usr/local/lib/node_modules/protractor/node_modules/q/q.js:525:49
    at flush (/usr/local/lib/node_modules/protractor/node_modules/q/q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
...
```
- Steps to reproduce the bug
1. check out repo
2. cd into `exampleTypescript`
3. compile `exampleTypescript` with tsc
4. start webdriver
5. run protractor with `protractor tmp/config.js`

it seems like the imported `browser` object is null, and in `index.js` it doesnt seem like `browser` is exported... 
P.S. `global["browser"]` works

**Comment by NickTomlin** [comment]
What version of typescript are you using? I'm having other TSC problems but once I actually compile  i'm able to run the specs without the error (using ts `2.0.10`).

**Comment by sixinli** [comment]
edited, im on `2.1.5`

**Comment by NickTomlin** [comment]
Can you post an example repo? I'm assuming there's something environmental going on here. My bet is that it is the TS version but i'd be good to have some exact code to compare. Thanks!

**Comment by sixinli** [comment]
i just checkout this repo's `exampleTypescript`(checked tag `4.0.14` and `5.1.1` and it wasn't working, what example repo are you looking for? 

also `exampleTypescript` requires ts 2.1+ i believe, jasmine typing uses some newer syntax

**Comment by NickTomlin** [comment]
Yep I understand that you are using this repo; but i'm not able to reproduce the same error using tsc `2.1.5`. It my seem silly, but having an isolated example (with pinned versions preferably) will help us get to the bottom of this. Thanks!

**Comment by sixinli** [comment]
sorry i might be running it with the wrong protractor :( , will echo back soon with a confirmation

**Comment by sixinli** [comment]
sorry for the false alarm... confirmed that it's working with the right version of protractor

**Comment by NickTomlin** [comment]
No worries, thanks for closing the loop! 😄
