### ISSUE TITLE
Calling a .bat file between test cases

### ISSUE THREAD

**Issue by borga31** [angular/protractor#4128]
Good morning everyone,

How I can call a bat file inside the scripts of Protractor?

In my case, I want to "call" the shutdown.bat that terminates the Tomcat session and after that, call another bat that starts Tomcat again. This way, by restarting the application and after that, continuing the test scripts.

It's necessary to apply the configuration saved in my application during the test.

Thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
