### ISSUE TITLE
ExpectedConditions.urlContains() is escaping characters from the URL

### ISSUE THREAD

**Issue by pittgoose** [angular/protractor#4133]
I'm trying to use `ExpectedConditions.urlContains()` to verify that a string I'm passing in my test is found in the URL. The problem is that my string has some **Hebrew** characters, and it getting escaped.
If I use `ExpectedConditions.urlContains(encodeURIComponent(urlString))` it works, but only if I don't have other URI escapable characters, such as a `/` in the string I'm passing. 
Is there a way to have `browser.getCurrentUrl()`, which is the method being called to get the current URL, get the actual URL instead of the escaped version?

**My code**
```
let urlString = "תחבורה_ציבורית-countries";
console.log(urlString); // output:  תחבורה_ציבורית-countries
console.log(encodeURIComponent(urlString)); // output: %D7%AA%D7%97%D7%91%D7%95%D7%A8%D7%94_%D7%A6%D7%99%D7%91%D7%95%D7%A8%D7%99%D7%AA-countries
browser.wait(EC.urlContains(urlString)); // fails
browser.wait(EC.urlContains(encodeURIComponent(urlString))); // passes if there aren't characters such as & or / or ?
```

**Error**
```
TimeoutError: Timed out waiting for the url to contain: תחבורה_ציבורית-countries
Wait timed out after 10001ms
at WebDriverError (<MyApp>\node_modules\selenium-webdriver\lib\error.js:27:5)
at TimeoutError (<MyApp>\node_modules\selenium-webdriver\lib\error.js:238:5)
at <MyApp>\node_modules\selenium-webdriver\lib\promise.js:2107:17
at ManagedPromise.invokeCallback_ (<MyApp>\node_modules\selenium-webdriver\lib\promise.js:1366:14)
at TaskQueue.execute_ (<MyApp>\node_modules\selenium-webdriver\lib\promise.js:2970:14)
at TaskQueue.executeNext_ (<MyApp>\node_modules\selenium-webdriver\lib\promise.js:2953:27)
at asyncRun (<MyApp>\node_modules\selenium-webdriver\lib\promise.js:2813:27)
at <MyApp>\node_modules\selenium-webdriver\lib\promise.js:676:7
at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Protractor code**
```
// node_modules/protractor/built/expectedConditions.js line 281
/**
     * An expectation for checking that the URL contains a case-sensitive
     * substring.
     *
     * @example
     * var EC = protractor.ExpectedConditions;
     * // Waits for the URL to contain 'foo'.
     * browser.wait(EC.urlContains('foo'), 5000);
     *
     * @alias ExpectedConditions.urlContains
     * @param {!string} url The fragment of URL expected
     *
     * @returns {!function} An expected condition that returns a promise
     *     representing whether the URL contains the string.
     */
    urlContains(url) {
        return () => {
            return this.browser.driver.getCurrentUrl().then((actualUrl) => {
                return actualUrl.indexOf(url) > -1;
            });
        };
    }
```

**More Info**
**Browser**: chrome
**protractor**: 5.1.1

**Comment by NickTomlin** [comment]
This is actually due to the browser itself, and not `urlContains`. `this.browser.driver.getCurrentUrl()` is going to return the same url encoded string. Browsers escape the url coming back (you can test this yourself by going to [http://www.example.com/תחבורה_ציבורית-countries](http://example.com/תחבורה_ציבורית-countries) and `console.log(window.location.pathname)` or copy and pasting the url itself. 

Can you give an example of a url string that isn't encoding properly (e.g. one with `&` or `/`)? You may have to encode individual parts of a URI and join them with path delimiters in your tests.

**Comment by pittgoose** [comment]
@NickTomlin yeah, sounds like I'll have to create my string piecemeal. :( Thanks for the response.
