### ISSUE TITLE
How does waitForAngularEnabled work?

### ISSUE THREAD

**Issue by tothesky8787** [angular/protractor#4138]
Hi

I'm not reporting issues, but I'd rather post questions since I don't know where to post. I have been using protractor to do E2E test for several Angular projects. Recently some complicated problems have bothered me and I couldn't get any satisfied answers from anywhere.

Hopefully someone helps me get cleared.

1. How does waitForAngularEnabled() work, in particular, waitForAngularEnabled(false) ?
I often used it to wait for a certain criteria to meet. So for example,

        browser.get('/').then(() => {
            let theElement = ...;
            browser.waitForAngularEnabled(false);
            // different use cases here (A, B in the following)
        });

        A.  browser.wait(protractor.ExpectedConditions.presenceOf(theElement));
        B.  return browser.isElementPresent(theElement);
So the question is: should I revert waitForAngularEnabled(true) to continue normal testing after the condition met or timeout?

2. What is the difference between waitForAngularEnabled vs waitForAngular?

Hope to get clear answers with some background principle.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by tothesky8787** [comment]
Then could you answer to the question on stackoverflow: http://stackoverflow.com/questions/42643118/getmulticapabilities-not-working-with-arrow-function

Thanks!

**Comment by wcainboundary** [comment]
@first87 I suspect you mean:
http://stackoverflow.com/questions/42648077/how-does-waitforangularenabled-work?rq=1

**Comment by first87** [comment]
@wcainboundary Yes, you're right, but nobody answered to the question. Could you? Thanks.
