### ISSUE TITLE
getMultiCapabilities not working with arrow function

### ISSUE THREAD

**Issue by tothesky8787** [angular/protractor#4139]
getMultiCapabilities seems not working with arrow function. So I defined 'getMultiCapabilities' function rather than 'multiCapabilities' property in the protractor config.ts like this:

        export let config: Config = {
            ...
            getMultiCapabilities: () => { // this doesn't work;
                ...                 // replacing it with "function() {" is okay
            },
            beforeLaunch: () => { // this works fine
                ...
            },
            ...
        }

This results in "Error: Debug Failure. False expression: position cannot precede the beginning of the file". Replacing arrow with 'function' works fine. What's wrong?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by tothesky8787** [comment]
OK, so I posted same question on the stackoverflow:
http://stackoverflow.com/questions/42643118/getmulticapabilities-not-working-with-arrow-function

Hopefully answer to my question.

Thanks!
