### ISSUE TITLE
Unable to start new selenium-server-standalone-3.3.0.jar

### ISSUE THREAD

**Issue by hudson-t** [angular/protractor#4141]
Bug report
---
Hi again,

Just ran `webdriver-manager update` this morning and got a new version of Selenium Standalone server jar - v3.3.0.

I specify the Jar in my conf file to start/stop with my tests and it works perfectly with v3.2.0 if I downgrade:

```
seleniumServerJar: './node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.3.0.jar'
```

It times out when attempting to start and even if I increase the timeout it just doesn't happen. However, it does work if I start v3.3.0 via `webdriver-manager start` command and specify the address in my conf file.

Here's what goes in the console:
```
[09:26:36] I/launcher - Running 1 instances of WebDriver
[09:26:36] I/local - Starting selenium standalone server...
[09:27:06] E/launcher - Error: Error: Timed out waiting for the WebDriver server at http://128.87.191.173:4444/wd/hub
    at onError (c:\Projects\Unity\ProtractorTests\node_modules\selenium-webdriver\http\util.js:102:16)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[09:27:06] E/launcher - Process exited with error code 100
```

- Node Version: 7.5.0
- Protractor Version: 5.1.1
- Angular Version: 2.4.6
- Operating System and Version Windows 7 (64 bit)

**Comment by paveleremin** [comment]
same issue, and 3.2.0 was work perfect

**Comment by nickcmaynard** [comment]
IANAE but conceivably related to this bug: SeleniumHQ/selenium#3618

**Comment by fonzarely** [comment]
I did not find any way to change the version of selenium to use, tried to change it via --version.chrome but still downloading selenium-server-standalone-3.3.0.jar .
Any idea ?

**Comment by hudson-t** [comment]
For a temp fix I just manually downloaded the .jar from https://goo.gl/dR7Lg2, added it into /node_modules/protractor/node_modules/webdriver-manager/selenium/ and changed the seleniumServerJar setting:

```
seleniumServerJar: './node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.2.0.jar'
```

**Comment by nickcmaynard** [comment]
@fonzarely I've been using `webdriver-manager update --versions.standalone=3.2.0`.

**Comment by NickTomlin** [comment]
Thanks all for tracking this. It looks like a fix will go out in the next release. Until then pinning a standalone version as @nickcmaynard seems like the best option.

**Comment by kp2017** [comment]
I am new to protractor. I am going through the [Angular tutorial](https://docs.angularjs.org/tutorial). How do I use @nickcmaynard suggestion?

**Comment by didlich** [comment]
@kp2017 I assume you are managing your dependencies with npm, so in you package.json you have a protractor entry like:
```javascript
"protractor": "~5.1.1"
```
It's a good practice to update the webdriver during npm install, so create something like:

```javascript
"scripts": {
  "webdrivermanager:update": "node node_modules/protractor/bin/webdriver-manager update --versions.standalone=3.2.0",
  "webdrivermanager:clean": "node node_modules/protractor/bin/webdriver-manager clean",
  "install": "npm run webdrivermanager:clean && npm run webdrivermanager:update",
}
```
in you package.json

then run:
```
protractor protractor.config.js
```

**Comment by hudson-t** [comment]
Think this can be closed as it is not a Protractor issue.

**Comment by fonzarely** [comment]
Thanks @nickcmaynard !

**Comment by nickcmaynard** [comment]
FWIW, selenium-standalone 3.3.1, which just hit the CDN, fixes this issue.  

webdriver-manager caches the index XML files, so you may not get the latest when you run "update" - it's refreshed every 10 hours (though that should be 1 hour, submitting a bug).

The cache lives in `protractor/node_modules/webdriver-manager/selenium` if you want to delete it manually.
