### ISSUE TITLE
How we can get a text from TextBox which has enabled a readOnly property?

### ISSUE THREAD

**Issue by kumbharketanm** [angular/protractor#4155]
Can you please provide me the ## alternative solution for getting a text from textbox which has enabled a # readOnly Property?

**Comment by wswebcreation** [comment]
@kumbharketanm 

Isn't your question better suited for StackOverflow or Gitter. Ask the [question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor).

From the the [getting help section](https://github.com/angular/protractor#getting-help) of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Grtz

Wim
