### ISSUE TITLE
How to do drag and drop or upload files in protractor with a plugin like ng-file-upload ?

### ISSUE THREAD

**Issue by djom20** [angular/protractor#4162]
Hi everyone,

I have this plugin [ng-file-upload](https://github.com/danialfarid/ng-file-upload) in my app but I can not access to upload or drap and drop feature with protractor. Doesn't works like a traditional method with upload file and I would like know how to do upload a file with this plugin?

- Node Version: 6.9.1
- Protractor Version: 4.0.10
- Angular Version: 1.4.5
- Browser(s): chrome v56.0.2924.87
- Operating System and Version: OSX 10.12.3

This image is the structure of plugin when is render by browser:

![image](https://cloud.githubusercontent.com/assets/1834808/24046391/6172a37c-0af0-11e7-8862-464185af70fb.png)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
