### ISSUE TITLE
Protractor does not pass moz:firefoxOptions capabilities on to selenium

### ISSUE THREAD

**Issue by lutostag** [angular/protractor#4167]
None of the options set via moz:firefoxOptions from capabilities are passed onto selenium.

- Node Version: `v6.10.0`
- Protractor Version: `0.21.3`
- Browser(s): `firefox 52.0`
- Operating System and Version `Ubuntu 16.10`

When run with
```
protractor conf.js
```
where conf.js is:
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js'],
  capabilities: {
      'browserName': 'firefox',
      'moz:firefoxOptions': {
          'binary': '/opt/bin/firefox',
          'args': ['--verbose']
      }
  }
};
```
The set moz:firefoxOptions are not set (none of the ones from https://github.com/mozilla/geckodriver work), in the selenium log you will find:

[new session: Capabilities [{count=1, browserName=firefox, moz:firefoxOptions={}}]])

Thanks!

**Comment by shaungrady** [comment]
This bug doesn't exist for me in the latest Protractor release (`5.2.0`). Can this be closed?

**Comment by wswebcreation** [comment]
@shaungrady 

Tnx for the update.
