### ISSUE TITLE
Cannot run safari 10 with protractor 5.1.1

### ISSUE THREAD

**Issue by tamvo94** [angular/protractor#4169]
Bug report
---
I run safari with protractor 5.1.1 but it cannot start server and show error: ECONNREFUSED connect ECONNREFUSED. 
It work well on protractor 5.0.0, but I need to work on protractor for cross-browser.

Node Version: 6.9.5
Safari Driver: 2.48
Protractor Version: 5.1.1
Browser(s): 10.0.3
Operating System and Version: Mac 10.12.3

**Comment by NickTomlin** [comment]
I'm able to run with the same specs that you gave. Can you share your config? Can you reproduce this using the [example](https://github.com/angular/protractor/tree/master/example)?

**Comment by NickTomlin** [comment]
Hmm, so I was able to fix this by killing a run-away safari driver process:

```
ps ax | grep safari
# find safaridriver process
kill <pid of safari process>
```

Otherwise SafariDriver is launching fine. I'd either do the above or restart your computer and see if you can reproduce. Also, could you share your config?

**Comment by tamvo94** [comment]
```
exports.config = {
  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'safari'
  },
  specs: ['example-spec.js'],

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true, // Use colors in the command line report.
  }
};

```

**Comment by NickTomlin** [comment]
Interesting; I'm still not able to reproduce this. It's the same after killing all selenium/safaridriver processes?

**Comment by tamvo94** [comment]
I try to kill a run-away safari driver process about 7 days ago and it work well. 
Thank @NickTomlin :)
