### ISSUE TITLE
Error: connect ETIMEDOUT with webdriver-manager start

### ISSUE THREAD

**Issue by dipakbachhav** [angular/protractor#4174]
@juliemr 

C:\Users\Username>set PROXY=http://Username:passwrd@Ipaddress:Port

C:\Users\Username>set HTTP_PROXY=%PROXY%

C:\Users\Username>set HTTPS_PROXY=%PROXY%

C:\Windows\system32>webdriver-manager start
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT XX.XX.XX.XX:XXX
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)

I have already done setting for proxy and after setting up proxy its working fine until i restarted my machine but after restarting my machine when i was try to  to run webdriver-manager start facing above issue.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
