### ISSUE TITLE
ES6 Generators: A Yield which fails for any reason crashes Protractor

### ISSUE THREAD

**Issue by theandrewlane** [angular/protractor#4178]
When executing any/all tests and the result of a generator's yield fails, all subsequent specs fail immediately, Protractor exists with error code 199, and the webdriver's Chrome instance is not terminated.

- Node Version: `7.5`
- Protractor Version: `5.11`
- Angular Version: `1.5.x`
- Browser(s): `Chrome`
- Operating System and Version `Mac/Win`

In this example, I'm using [co](https://www.npmjs.com/package/co) (_lowercase_) to iterate through the generator. ```addNote()``` can't find the add note button in this example, which which is valid - the issue is the Protractor crash as described above. when the button is not found. 
```
const notesCO = require('../../components/notes-co'),
  workItemCO = require('../../components/management-co'),
  co = require('co');
...
  it('should update the work item note count', co.wrap(function* () {
    expect(notesCO.getNotesTabCount() === 0);
    yield notesCO.addNote('Failed in Approval', 'this note was added via automation');
    expect(notesCO.getNotesTabCount()).toEqual(1); //Validate count incremented by 1
  }));
```
**Here is ```notesCO.addNote()``` from above:**
```
 self.addNote = (noteName, noteDetail) => self.notesTab.click().then(() => self.newNoteButton.click())
    .then(() => self.setNoteName(noteName)).then(() => self.noteInputDetail.click())
    .then(() => self.noteInputDetail.sendKeys(noteDetail).then(() => self.addNoteButton.click()));
```

**Failure Output:**
```
(node:8652) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[10:26:24] I/launcher - Running 1 instances of WebDriver
[10:26:24] I/direct - Using ChromeDriver directly...
******** Deleted Test Results From Previous Execution ********
Spec started
[10:26:55] E/launcher - NoSuchElementError: No element found using locator: By(css selector, .xwi-add-note-btn)
[10:26:55] E/launcher - Error: NoSuchElementError: No element found using locator: By(css selector, .xwi-add-note-btn)
    at wrappedReject (C:\Users\a500806\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:97:32)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
[10:26:55] E/launcher - Process exited with error code 199
```

I didn't include my config because I don't necessarily think it's relevant to this issue :)

**Comment by Sheeryada** [comment]
+1

**Comment by settysreekanth** [comment]
+1

**Comment by heathkit** [comment]
Could you post an example repo? Also, what happens if you [disable the control flow](https://github.com/angular/protractor/blob/master/docs/control-flow.md)?

**Comment by theandrewlane** [comment]
Closing issue. Jasmine & Protractor now support async/await which is a much better approach to writing delicate synchronous operations. :smile:
