### ISSUE TITLE
documentation request - Protractor API

### ISSUE THREAD

**Issue by skywalker5727** [angular/protractor#4179]
Request
---
When I am using the Protractor API webpage http://www.protractortest.org/#/api (in Chrome) and I click on the API elements (list on left), the text is displayed at the top of the page, and I have to scroll back down to look at more (for example, I'm trying to work out the best locator to use).  It would be nice if the text describing the API element floats at the part of the page I am working on so I don't have to keep scrolling up and down.

**Comment by NickTomlin** [comment]
I think this is a great idea! We would welcome a pull request doing this if you'd like but I don't think it's something that we have road mapped. I'll go ahead and close this but feel free to open a PR.
