### ISSUE TITLE
Dynamically set allScriptsTimeout from an it block

### ISSUE THREAD

**Issue by mwsessom** [angular/protractor#4181]
**Feature request**: Dynamically set `allScriptsTimeout` from an `it` block.

**Motivation**: Suppose uploading a large file to a website takes 3-5min. If I have `allScriptsTimeout` set to 30s, Protractor will timeout automatically (due to the POST request taking longer than 30s). I prefer to keep `allScriptsTimeout` relatively small (e.g., 30s) for all the other tests, and it would not be appropriate to increase the global timeout.

**Comment by Xotabu4** [comment]
@mwsessom This is already exists. Please refer to the docs - 
https://jasmine.github.io/api/edge/global.html#it

Just pass third parameter (redefining timeout in milliseconds) into 'it' method
```javascript
...
it('some long test that takes more time that others', function () {
//Some slow actions here
}, 120 * 1000) //Setting timeout as 2 minutes only for this test
...
```
But actually this is not a question to protractor, this is jasmine question.

**Comment by mwsessom** [comment]
jasmine.DEFAULT_TIMEOUT_INTERVAL is different than allScriptsTimeout. 

jasmine.DEFAULT_TIMEOUT_INTERVAL is specific to Jasmine. allScriptsTimeout is specific to Protractor.

jasmine.DEFAULT_TIMEOUT_INTERVAL refers to the total time to run a single test. allScriptsTimeout refers to the time to wait for a single async request.

**Comment by Xotabu4** [comment]
@mwsessom Oh, indeed. I am so inattentive. My bad.

I tried to find where allScriptsTimeout is defined and used, and it seems like it is only one place - 
https://github.com/angular/protractor/blob/c525ca6b277a6a8fea43632ae493c13999cddc94/lib/browser.ts#L670

I think you can try directly assign another value into this property, something like:

```javascript
        browser.allScriptsTimeout = 240000;
```

and reset it back after test. Can you try?

**Comment by mwsessom** [comment]
Setting `browser.allScriptsTimeout` seems to have no effect. It's still using the value from config.js.

**Comment by wrobbinz** [comment]
@mwsessom Have you found a solution besides upping the config's `allScriptsTimeout` default value? I'm having same issue with a long download, and want to avoid upping the global value.

**Comment by mwsessom** [comment]
@wrobbinz no I haven't

**Comment by wswebcreation** [comment]
@mwsessom ,

Did you also tried this `browser.driver.manage().timeouts(). allScriptsTimeout(300*1000);`

**Comment by mwsessom** [comment]
@wswebcreation I get `TypeError: browser.driver.manage(...).timeouts(...).allScriptsTimeout is not a function`

**Comment by wswebcreation** [comment]
Ok, got the solution I think

If your run this you will see it works. Mind the comment in the first `it`-block at the end

**config**
```js
exports.config = {
    capabilities: {
        'browserName': 'chrome'
    },
    framework: 'jasmine',
    specs: ['example_spec.js'],
    allScriptsTimeout: 9000
};
```

**example test**
```js
describe('Wait a long time', () => {
    it('wait 60000 for a async response', () => {
        let start;

        // Override the default / set allScriptsTimeout
        browser.driver.manage().timeouts().setScriptTimeout(60000);
        browser.get('http://www.angularjs.org').then(() =>{
            start = new Date().getTime();
        });
        browser.executeAsyncScript('window.setTimeout(arguments[arguments.length - 1], 50000);')
            .then(() => {
                console.log('Elapsed time: ' + (new Date().getTime() - start) + ' ms');
            });

        expect(true).toBe(true);
        // Add the 70000 to the it block, or in your protractor conf (jasmineNodeOpts.defaultTimeoutInterval)
        // to not face the jasmine.DEFAULT_TIMEOUT_INTERVAL that is defaulted to 30 seconds if you don't set it
    }, 70000);

    it('wait 10 seconds for an async response, but fail', () => {
        let start;

        // Override the default / set allScriptsTimeout
        browser.driver.manage().timeouts().setScriptTimeout(10000);
        browser.get('http://www.angularjs.org').then(() =>{
            start = new Date().getTime();
        });
        browser.executeAsyncScript('window.setTimeout(arguments[arguments.length - 1], 60000);')
            .then(() => {
                console.log('Elapsed time: ' + (new Date().getTime() - start) + ' ms');
            });

        expect(true).toBe(true);
    });
});
```

**output**
```shell
✘  ~/contributions/protractor   examples ●  npm run test.example

> protractor@5.1.2 test.example /Users/wswebcreation/contributions/protractor
> node ./bin/protractor example/conf.js

[05:51:44] I/launcher - Running 1 instances of WebDriver
[05:51:44] I/hosted - Using the selenium server at http://localhost:4444/wd/hub/
Started
Elapsed time: 50265 ms
.FA Jasmine spec timed out. Resetting the WebDriver Control Flow.
A Jasmine spec timed out. Resetting the WebDriver Control Flow.


Failures:
1) Wait a long time wait 10 seconds for an async response, but fail
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:386:14)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:386:14)
        at tryOnTimeout (timers.js:250:5)
        at Timer.listOnTimeout (timers.js:214:5)

2 specs, 1 failure
Finished in 112.808 seconds

[05:53:39] I/launcher - 0 instance(s) of WebDriver still running
[05:53:39] I/launcher - chrome #01 failed 1 test(s)
[05:53:39] I/launcher - overall: 1 failed spec(s)
[05:53:39] E/launcher - Process exited with error code 1
```

I'm going to close the issue now based on the above testcase. You are able to influence it from the `it`-block. It's still open for discussion
