### ISSUE TITLE
Async/await and browser.pause not working - workaround ?

### ISSUE THREAD

**Issue by xnnkmd** [angular/protractor#4184]
I am using Async/await with SELENIUM_PROMISE_MANAGER set to false as noted by this [great example](https://github.com/angular/protractor/tree/master/exampleTypescript/asyncAwait) by @sjelin 

It seems to work except that browser.pause and browser.debugger fails to work (shows pause/debugger info on the screen but test terminates without pausing). Is that a known problem and/or is there a workaround ?

**Comment by murlinw** [comment]
I am having similar problems with browser.pause() not working with version 5.1.1. A workaround I'm doing is just using browser.sleep() with a very long timeout.

**Comment by xnnkmd** [comment]
I think this is a quite pressing problem. Asnoted on gitter today "the strange situation with protractor is that you can either write easy code (with async/await) that is hard to debug or dificult code (with promises/callbacks) that is easy to debug." (because of this issue)

**Comment by tiagomsmagalhaes** [comment]
I updated today to 5.1.1 and have problems with `browser.pause()`

**Comment by xnnkmd** [comment]
Are you using async/await in your code with "SELENIUM_PROMISE_MANAGER: false" as noted in the documentation? What version of node are you using ?

**Comment by xnnkmd** [comment]
@tiagomsmagalhaes Are you using async/await in your code with "SELENIUM_PROMISE_MANAGER: false" as noted in the documentation? What version of node are you using ?

**Comment by tiagomsmagalhaes** [comment]
@xnnkmd nope. node version is 6.10.1. I'm working with AngularJS so I suppose i don't need that (??)

**Comment by mgiambalvo** [comment]
`SELENIUM_PROMISE_MANAGER=false` disables Selenium's control flow, which will break browser.pause(). However, the big advantage of not using managed promises is the ability to debug your tests with regular NodeJS tools.

I updated [the async/await example](https://github.com/angular/protractor/tree/master/exampleTypescript/asyncAwait#debugging-with-asyncawait) example to show how you might write tests in TypeScript and debug them with Chrome's devtools. Note that you'll need Node v7 for sourcemaps to work.
