### ISSUE TITLE
Why cucumber steps shows as executed before the actual execution happened

### ISSUE THREAD

**Issue by nanichandu84** [angular/protractor#4188]
Hi,

I am new to protractor cucumber framework. The problem I am facing is, when I ran the feature file, all the steps shows as executed even before the real execution is completed. How can I made cucumber step to wait till the execution is completed. Below is my code snippet.

this.Given(/^I go to sparqHomePage$/, function (callback) {
	  homepage.goToHomePage()
	  homepage.login(data[0].UserName,data[0].Password);
	  callback();
    });
  
  this.Then(/^I create a process$/, function (callback) {
	  homepage.clickDesign();
	  homepage.clickFlowDesigner();
	  console.log(params.flow.procName + ' '+  params.flow.procDesc);
	  designPage.createNewProc(params.flow.procName, params.flow.procDesc);
          callback();
    });

homepage is the page object for my homepage. 

Any help is much appreciated.

**Comment by jlin412** [comment]
if you are using callback, you do something like homepage.login(data[0].
UserName,data[0].Password).then(callback);
You calls are probably async.

**Comment by nanichandu84** [comment]
@jlin412 thanks for your quick reply, I tried the below code, but it is throwing "TypeError: Cannot read property 'then' of undefined". 

this.Given(/^I go to sparqHomePage$/, function (callback) {
	  homepage.goToHomePage()
	  homepage.login(data[0].UserName,data[0].Password).then(callback);
    });

 Error:
     [31mTypeError: Cannot read property 'then' of undefined
         at World.<anonymous> (C:\Users\panubrolu\workspace\ProtractorCucumber\features\step_definitions\E2E_step_definition.js:35:53)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)[39m

Could you please give me your thoughts if I am missing anything.

**Comment by wswebcreation** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by nanichandu84** [comment]
Thanks wswebcreation, posted the question in the given channels.

**Comment by wswebcreation** [comment]
@nanichandu84 

Tnx,

Can you close the issue?
