### ISSUE TITLE
How to Define database undependant test cases?

### ISSUE THREAD

**Issue by amineparis** [angular/protractor#4189]
**Problem :** I define test cases that depend on the initial state of the database. Database changes over time (at least after each test execution).
_Question :_ **How to make database undependant tests ?**

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
