### ISSUE TITLE
WebDriverError: Invalid Firefox preference value: network.http.phishy-userpass-length=255

### ISSUE THREAD

**Issue by wsieb** [angular/protractor#4191]
Hi there!

sorry for double submitting of the error (I asked the same question already on [stackoverflow ](http://stackoverflow.com/questions/43078583/webdrivererror-invalid-firefox-preference-value-network-http-phishy-userpass-l?noredirect=1&lq=1))

Since updating to Protractor 5 and restructuring of firefox profiles (caused by [this](http://stackoverflow.com/questions/42151372/error-typeerror-profile-gettemplatedir-is-not-a-function-when-set-firefox-prof)), we are not able to use the Firefox preference "network.http.phishy-userpass-length" anymore.  

The line
   ` firefoxProfile.setPreference("network.http.phishy-userpass-length", 255);`
causes following error 

>  Invalid Firefox preference value: network.http.phishy-userpass-length=255

Without this setting, our TC fails with **"You are about to log in to the site "(...)" with the username "(...)""** popup.

The preference still seems to be available. When I replace the 255 value by something different, the error fails against the comparison of frozen values in /lib/firefox/webdriver.json. 

Protractor Version is 5.1.1
Gecko Driver: 0.15
FF: 52 ESR

Thanks!
Regards,
Waldemar

**Comment by NickTomlin** [comment]
Sorry to close but you should still try to pursue help on StackOverflow. This is a question that is specific to your use case with firefox and we won't be able to help you troubleshoot it in the issue queue. 

If you are able to identify an issue with protractor itself, please feel free to open a pull request or a more specific issue. Good luck!
