### ISSUE TITLE
Newb question - pipe stdout/stderr to parent process

### ISSUE THREAD

**Issue by ORESoftware** [angular/protractor#4193]
We are using protractor on the job and I am new to it

This article seems pretty good https://www.3pillarglobal.com/insights/using-the-protractor-automation-tool-to-test-angularjs-applications

Say I have a bash script with my protractor command in it:

```bash
#!/usr/bin/env bash
protractor conf.js
```

Is there a way to configure protractor to output TAP so that that the parent process which launches the above bash script can parse test results from the output?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
