### ISSUE TITLE
set window size of headless chrome

### ISSUE THREAD

**Issue by tom94zoe** [angular/protractor#4195]
Hi, 

It seems like the window-size of a headless chrome couldn't be configured. 
Some components of my application are only visible if the width is bigger than 960px, but protractor couldn't find them. If I run the test without "--headless"-attribute everything works fine. 
Does anyone solve this problem? 

- Node Version: `6.10.1`
- Protractor Version: `5.11`
- Angular Version: `1.5.8`
- Browser(s): `Chrome`
- Operating System and Version: `Ubuntu 16.04`
- Your protractor configuration file:

`capabilities{
browserName: 'chrome',
chromeOptions:{
args:[
"--headless",
"--disable-gpu",
"--window-size=1000,1000"
]
}
}`

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by heathkit** [comment]
Headless mode is cool, but stuff like changing the window size is exactly the sort of thing I'd expect to not work. I'd recommend running with Xvfb for now until --headless is a bit more mature.

**Comment by tom94zoe** [comment]
Oh I didn't know that. 
Thank you

**Comment by RazvanHidan** [comment]
> Hi there!
> 
> Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.
> 
> From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:
> 
> > Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)
> 
> Thanks!

Do you have an answer or are you with the indications?
