### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by zsong** [angular/protractor#4198]
I can run the selenium server with fresh rebooting of my Windows 7. After kill the server and start it again, i will get this error. Sometimes if I do webdriver-manager update--ignore_ssl, it may fix the problem, but most of time it doesn't fix the problem.

    C:\Users\...>webdriver-manager start --ignore_ssl
    events.js:163
          throw er; // Unhandled 'error' event
          ^

    Error: self signed certificate in certificate chain
        at TLSSocket.<anonymous> (_tls_wrap.js:1084:38)
        at emitNone (events.js:86:13)
        at TLSSocket.emit (events.js:188:7)
        at TLSSocket._finishInit (_tls_wrap.js:606:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:436:38)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
