### ISSUE TITLE
IE stability issue - Webdriver error 

### ISSUE THREAD

**Issue by AliZuhair-AI** [angular/protractor#4203]
Node version: 7.4.0
Protractor version: 5.1.1
Operating system: Windows 7
Browser: Internet Explorer 11

I recently upgraded to Protractor 5.1.1 and started to seeing this error show up occasionally:

WebDriverError: JavaScript error (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 49 milliseconds

It seems to be coming from the following code under *\lib\browser.ts

```
return this.driver.wait(() => {
            return this.executeScriptWithDescription('return window.location.href;', msg('get url'))
                .then(
                    (url: any) => {
                      return url !== this.resetUrl;
                    },
                    (err: IError) => {
                      if (err.code == 13 || err.name === 'JavascriptError') {
                        // Ignore the error, and continue trying. This is
                        // because IE driver sometimes (~1%) will throw an
                        // unknown error from this execution. See
                        // https://github.com/angular/protractor/issues/841
                        // This shouldn't mask errors because it will fail
                        // with the timeout anyway.
                        return false;
                      } else {
                        throw err;
                      }
                    });
```

If I change the the line above from 

` if (err.code == 13 || err.name === 'JavascriptError')` 

to 

` if (err.code == 13 || err.name === 'JavascriptError' || err.name === WebDriverError)` 

then the problem goes away.

**Comment by heathkit** [comment]
This was fixed by https://github.com/angular/protractor/pull/4149. It'll go out in the next release.
