### ISSUE TITLE
Expect.toContains() with if ...else if...else

### ISSUE THREAD

**Issue by hitesh-jani** [angular/protractor#4204]
want to differentiate some values from list into different different arrays
like $ 1 B , $ 2 B , $ 100 M ,$ 300 M , $ 105 K , $ 205 K
so i tried it with expect.toContain('') method
```
var ele = element.all(by.css('.company-network-list__header__income.ng-scope .ng-binding.ng-scope'));
var b =[] , m=[], k=[];
ele.map(function(eachName) {
	return eachName.getText().then(function(unSorted) {
if(expect(unSorted).toContain('B')){
     var b = unSorted;
}
else if(expect(unSorted).toContain('M')){
   var m = unSorted;
}
else{
  var k = unSorted;
}
});
});
```
for 2 values ..i tried with try catch
```
try{
	expect(unSorted).toContain('B');
	var b = unSorted;
    }catch(e) {
	var m = unSorted;
   }
```

also this....
```
expect(unSorted).toContain('B').then(function(result) {
       if(result){
           var b= unSorted;
       }else {
             var m= unSorted;
      }  
});
 ``` 
Not working anything from these
Can anyone please help me to solve this issue

**Comment by hitesh-jani** [comment]
I want to differentiate some values from list into different different arrays
like $ 1 B , $ 2 B , $ 100 M ,$ 300 M , $ 105 K , $ 205 K
so i tried it with expect.toContain('') method
var ele = element.all(by.css('.company-network-list__header__income.ng-scope .ng-binding.ng-scope'));
var b =[] , m=[], k=[];
ele.map(function(eachName) {
	return eachName.getText().then(function(unSorted) {		
if(expect(unSorted).toContain('B')){
     var b = unSorted;
} 
else if(expect(unSorted).toContain('M')){
   var m = unSorted;
}
else{
  var k = unSorted;
}
});
});

for 2 values ..i tried with try catch
try{
	expect(unSorted).toContain('B');
	var b = unSorted;
    }catch(e) {
	var m = unSorted;
    }

also this....
expect(unSorted).toContain('B').then(function(result) {
       if(result){
             var b= unSorted;
       }else {
             var m= unSorted;
       }   
});

Not working anything from these
Can anyone please help me to solve this issue

**Comment by marleitao** [comment]
@hitesh-jani 

First, like you have on your post: "Make sure you are not asking a usage or debugging question. If you are, use StackOverflow, Google Group discussion list, or Gitter to get help." this is a question not a protractor issue.

Trying to help you before this issue gets closed, I don't think expect() should be used in if...else clauses.. The expect() is an assertion.
Picking your first example, I don't understand why you define var b = [] and then in the if you redefine it with different type (var b = string). Also, you return eachName.getText() but don't return anything inside your function(unSorted).

Give it a try this way:
var ele = element.all(by.css('.company-network-list__header__income.ng-scope .ng-binding.ng-scope'));
var b =[] , m=[], k=[];
ele.each(function(eachName) {
	eachName.getText().then(function(unSorted) {
if(unSorted === 'B'){
     b.push(unSorted);
}
else if(unSorted ==='M'){
   m.push(unSorted);
}
else{
  k.push(unSorted);
}
});
});

Hope it helps and don't forget to use StackOverflow for future questions.

**Comment by hitesh-jani** [comment]
@marleitao 
Thanks for the help . I will take care of your points next time
but one last question regarding your answer 
`if(unSorted === 'B')`
this will compare $ 1 B to B which will always wrong in this case..
how can i check if unSorted has 'B' in the string then do b.push(unSorted)?

**Comment by marleitao** [comment]
You are right, missed the toContain() part..
Use:
if (unSorted.indexOf('B') > -1);

Google will help you for future js queries ;)

**Comment by hitesh-jani** [comment]
Thanks again 
Sure :)

**Comment by NickTomlin** [comment]
@marleitao thanks so much for jumping in and talking about this! Really appreciate your work in the queue 😄 

I'm going to go ahead and close this since it is a usage/debugging questions and is a better fit for Gitter/SO. Cheers everyone!
