### ISSUE TITLE
'Maximum call stack size exceeded' error when loading AsciiDoctor.js

### ISSUE THREAD

**Issue by ggranum** [angular/protractor#4209]
Bug report
---

- Node Version: `7.7.3`
- Protractor Version: `5.1.0`
- Angular Version: `4.0.0-rc-5`
- Browser(s): `chrome=57.0.2987.133`
- Operating System and Version `(Driver info: chromedriver=2.29.461585 (0be2cd95f834e9ee7c46bcc7cf405b483f5ae83b),platform=Mac OS X 10.12.4 x86_64)`

I created [this project](https://github.com/ggranum/Ng4Playground/tree/find-e2e-issue)[1] to reproduce the issue. However, simply adding the [asciidoctor.js](https://github.com/ggranum/Ng4Playground/blob/find-e2e-issue/src/assets/asciidoctor.js)[2] file to your existing project and running `ng e2e` should be sufficient to reproduce the problem. 

I have filed this issue more for the convenience of others who might encounter it than in the hopes it will be fixed by this team. I will also file an issue with the AsciiDoctor team, but I suspect that the Protractor team is better equipped to identify and fix any underlying issue, regardless of who's codebase is at fault. Also, it's pretty easy to argue that if the code works *outside* of Protractor, it should ideally work within Protractor as well. Obviously easier to say than to make so.

If no fix can come out of this ticket, perhaps an error message that implicates in some way the script that is at fault? Simply knowing it was this third party script would have saved me loads of time. 

Thanks much,

[1] https://github.com/ggranum/Ng4Playground/tree/find-e2e-issue
[2] https://github.com/ggranum/Ng4Playground/blob/find-e2e-issue/src/assets/asciidoctor.js

**Comment by NickTomlin** [comment]
This is a bit of a strange one; i'm not sure what we are doing to affect ASCII doctor but it's not an officially supported use case and It isn't something anyone here is going to actively look into. 

If you are interested in making Protractor play nicely with a 3rd party script (and doing so doesn't alter the framework that much) we'd welcome a pull request. 

I hope that makes sense. I'm going to go ahead and close this. Thanks!

**Comment by ggranum** [comment]
@NickTomlin I'm afraid I don't quite understand this view. Obviously it is a bit of an edge case, but clearly it is an issue with Protractor. Not only does it fail to load any page on which asciidoctor.js is present, it does so in a fashion that is nearly impossible to debug. However, the page, with the script, loads and works fine under non-test conditions. 

I accept that it's a back-burner item, but I am surprised at it being routed directly into "won't fix", given that there is obviously *some* issue in Protractor that is breaking the page. If a third-party script can do it, certainly other projects will stumble upon whatever "it" is as well.

As for pull requests, I'll give a shot at finding the root cause, however I suspect that the level of domain knowledge required to startup and debug browser plugins will defeat the limited time I have available. Still, I'll spend a few more hours on this issue, as I would very much like to be able to test my app without having to disable the AsciiDoc rendered components. 

Thanks,
