### ISSUE TITLE
Using done() callback outside 'it' test function

### ISSUE THREAD

**Issue by kunalshokeen** [angular/protractor#4212]
it(function (done) {
/*
asynccode
*/
xyz();
 done();
});        

function xyz() {
promise1.then(function() {                      //Async code
promise2.then(function() {
});
});
}

As you see above, in 'it' function async code runs synchronously is ensured by Jasmine done callback.Now I have called a function xyz() from the test function 'it' which has async code too.How can I ensure the code in function xyz runs synchronously(in order)  as xyz does not have done callback ?

Regards,
Kunal Shokeen

**Comment by Xotabu4** [comment]
```javascript
it(function (done) {
    xyz(done)
})

function xyz(doneCb) {
    protractor.promise.all([promise1, promise2]).then(resultsArrray=> {
         // work here with resolved values if needed.
         doneCb()  
    })
}
```
Or

```javascript
it(function (done) {
    xyz().then(done)
})

function xyz(doneCb) {
    return protractor.promise.all([promise1, promise2]).then(resultsArrray=> {
         // work here with resolved values if needed.
    })
}
```

But for future questions it is better to ask on StackOverflow.

**Comment by kunalshokeen** [comment]
Hi Xotabu4,

Passing done callback will not work in the below scenario as invoking donecb() from xyz() will eventually invoke done of 'it'.

it(function(done) {
/*Async code 1*/
xyz();
/*Async code 2*/
done();
}

Async code 2 will never execute as you have invoked done() from xyz method.I think a better way would be to use Protractor promise like :+1: 

this.xyz = function () {
        var deferred = protractor.promise.defer();
        console.log('in method');
        setTimeout(function(){
            deferred.fulfill('Success');//Yay! Everything went well!
        }, 15000);
        return deferred.promise;
    };

And then in test case :+1: 

xyz().then(function(success){...

**But the issue in this is that it is not waiting for xyz() method to resolve. And moves to second test case.**

Any suggestions on this ?

Regards,
Kunal

**Comment by Xotabu4** [comment]
@kunalshokeen 
Try also to wrap your `xyz` function into webdriverjs control flow:
```
browser.controlFlow().execute(xyz)
```

**Comment by kunalshokeen** [comment]
Thanks it helped after wrapping it is working great :).Can you take a look at this too 

https://github.com/angular/protractor/issues/4218

Regards,
Kunal

**Comment by NickTomlin** [comment]
Thanks for helping out @Xotabu4!

@kunalshokeen I'm going to close this now. In the future please keep usage question on StackOverflow. Thanks!


From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
