### ISSUE TITLE
Error with Phantomjs 2.1.1

### ISSUE THREAD

**Issue by jainshravan123** [angular/protractor#4217]
Hi Guys,

>PhantomJS 2.1.1 (Mac OS X 0.0.0) Test Case encountered a declaration exception FAILED
TypeError: undefined is not a constructor

I am trying to import a custom module that's why it's creating this problem. 

require("my-custom-module") is not working.

**Comment by mgiambalvo** [comment]
PhantomJS is kind of a weird browser and not really supported. If you need to do headless browser testing, I'd recommend using [Xvfb](http://elementalselenium.com/tips/38-headless)

**Comment by heathkit** [comment]
Note that PhantomJS is now [offically not supported](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE) given that Headless Chrome is coming.
