### ISSUE TITLE
Skip/Disable remaining specs in a single suite on first 'it' failure

### ISSUE THREAD

**Issue by kunalshokeen** [angular/protractor#4218]
Hi All,

I have two test files 'product_booking.js' and 'product_wishlist.js'.Product booking file has 5 specs(it)/test cases .Now what I require is on first 'it' failure the remaining specs should skip in 'product_booking.js' and execution should continue from next test file i.e 'product_wishlist.js'.

'Protractor-fail--fast' or 'Jasmine -bail-fast' are not meeting the needs as they just stop the overall execution.

I want to skip the remaining specs within a single test suite only.

I have gone through 'jasmine-disable-remaining' but not able to implement it.Link for reference https://github.com/whatware/jasmine-disable-remaining

Can someone provide an example of how to acheive this in protractor ?

Regards,
Kunal Shokeen

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
