### ISSUE TITLE
(Internal) Decouple Browser and Runner as First Step to Decouple From Selenium

### ISSUE THREAD

**Issue by seanmay** [angular/protractor#4223]
With a longer-term objective being the decoupling of the Protractor internals from the particulars of Selenium WebDriver, as well as a shorter-term objective being the stabilization of types, to fix both TSC compilation of Protractor, as well as TypeScript users, the seam which appears to be most readily extractable is the Browser component, both in its generation by the Runner, as well as the proxying of WebDriver (and imminently incompatible extension of AbstractExtendedWebDriver, without further updates in other dependencies), the immediate intent is to separate Browser, treat it as a proxy to WebDriver (as a dependency), and modify the instantiation from the Runner, replete with unit tests of the object.

**Comment by heathkit** [comment]
That's also the area most in need of unit tests, since we're seeing all those troubling issues people are having with forkNewDriverInstance().

**Comment by seanmay** [comment]
It's still too coupled to write any unit tests, at all, but the intent is to use the Jasmine that I'll have, to test the resultant class in isolation, once it is decoupled from all of the things it's importing / extending.
After that, it should become easier to put it in a factory function (for Runner) and divide and conquer classes at different surrounding levels.

**Comment by seanmay** [comment]
@heathkit @cnishina can either of you tell me about the pattern of `.then(() => null)` that I see at the tail end of method calls, inside of the `ProtractorBrowser` class?

Is there code that depends on that null, or is it really there just to be a void function? Generally an implicit return is `undefined`, and TS is going to treat those things differently, as we progress into type-correct territory.

If they're void, I can just replace them with a noOp; if null is a requirement, I can try to make sure the types are updated accordingly.

**Comment by heathkit** [comment]
This was added in https://github.com/angular/protractor/commit/4e40fb175e64820bbab24efb376dac80fa6ba2b0, which was kind of a last-minute effort to get things ready for a control-flow-free world. Null isn't a requirement, as far as I know.
