### ISSUE TITLE
error im getting is:Angular could not be found on the page http://www.agileready.org:4000/.If this is not an Angular application, you may need to turn off waiting for Angular.

### ISSUE THREAD

**Issue by niluherath** [angular/protractor#4229]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
Windows 10
- Your protractor configuration file
exports.config = {
directConnect: true,
capabilities: {'browserName': 'chrome'},
framework: 'jasmine',
specs: ['TestIndividualEvaluation.js'],
allScriptsTimeout: 360000,

jasmineNodeOpts: {
defaultTimeoutInterval: 360000,
},

plugins: [{
package: 'protractor-testability-plugin'
}],
onPrepare: function () {
browser.driver.manage().window().maximize();

// jasmine.getEnv().addReporter(
// new Jasmine2HtmlReporter({
// savePath: 'target/screenshots'
// })
// );

}};
- A relevant example test

it('Test Login Positive', function() {
browser.get('http://www.agileready.org:4000');

// browser.get('http://localhost:3000');
//click login button
var el = element(by.xpath('.//*[@id="navbar-brand-centered"]/ul/li[4]/a'));
browser.sleep(2000);
browser.wait(protractor.ExpectedConditions.visibilityOf(el), 20000);

el.click();

//verify login

browser.ignoreSynchronization = true;

browser.driver.findElement(by.css('input[id="username"]')).sendKeys('niluherath@hotmail.com');

browser.driver.findElement(by.css('input[id="password"]')).sendKeys('chem4kids');

   browser.ignoreSynchronization = false; 
//click

browser.driver.findElement(by.xpath('.//*[@id="login_button"]')).click();

console.log('logged in with correct credentials');

//click try it ofr free
browser.driver.findElement(by.xpath('.//*[@id="navbar-brand-centered"]/ul/li[1]/a')).click();

browser.driver.findElement(by.css('h2'));

//var el1 = element(by.xpath('html/body/div[1]/div/div/div/form/fieldset/h2'));

// browser.sleep(2000);
// browser.wait(protractor.ExpectedConditions.visibilityOf(el1), 20000);

  element(by.model('evaluationJSON[0].Organisation')).sendKeys('writsdhfusdhfu');

});
});
- Output from running the test

getting error above
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

http://www.agileready.org:4000
Feature Request
---
Thanks, Nilu
- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by niluherath** [comment]
Im sorry I couldnt add these information.

Node Version: ``6.10
Protractor Version: `` 5.1.1
Angular Version: ``2
Browser(s): ``Chrome

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by niluherath** [comment]
Simply saying I am having trouble running the scripts as this application has angular as well as non angular objects. I know that adding ignoreSynchronization=true/false solves the problem but does not work when it's added.

**Comment by niluherath** [comment]
saw your message now. Will take this to StackOverflow
