### ISSUE TITLE
Request browser.get() optionally take a promise parameter

### ISSUE THREAD

**Issue by johnhall** [angular/protractor#4232]
I'd like to request a change to the browser.get() API to allow it to optionally take a promise as a function parameter that returns a string when resolved.  Here's the scenario - we have a need to navigate to a different page in the application based on the operation of the current page at runtime.  What this means is that we won't have a fully-constructed URL string to pass to browser.get() until the test is actually running.  Basically we'd be "screen-scraping" the page during the test execution and determining the URL destination of a browser.get() call that occurs later in the test script execution.  This would be a great help to us.  Thanks for your consideration.

**Comment by seanmay** [comment]
I realize this is not likely to work quite yet, but would the more
idiomatic approach not be one of the following?

```js
readURL().then(url => browser.get(url));
// or
readURL().then(browser.get.bind(browser));
// or
const url = await readURL();
browser.get(url);
```

**Comment by NickTomlin** [comment]
Yeah; I don't think this should be built in since it's easily accomplished with the current set of APIs. You'd just add a helper to read the url and navigate to the next page based on whatever it is.

**Comment by johnhall** [comment]
Thanks Sean.  I'm currently using your first option, but it screws up the control flow.  To give an example scenario, we're reading an ng-href (e.g. button.getAttribute('ng-href')) which is returned as a promise, then this promise is passed to a function that parses a moniker out of it in that promise resolution to construct a new URL, then executing the browser.get() with that newly constructed URL.  In subsequent test case execution, I see Protractor actually execute the remaining steps in the test cases flawlessly, but then it fails at the end with an error stating that it couldn't find one of the buttons that I saw it execute successfully in the browser window while the test cases were running.

I'll give the other approaches a shot, see how it goes and let you know.

**Comment by johnhall** [comment]
So the second option ends with the same error as the first, and the third option is in TypeScript and we haven't gotten there yet; still using JavaScript.

**Comment by seanmay** [comment]
I know exactly the errors to which you are referring. There is an initiative to deprecate ControlFlow, given that class of error that comes from hiding the promise queue away from the end user.
It's of greater concern that Selenium themselves are deprecating the feature, in the near future (the queue is in their system). As such, effort toward supporting it better are probably better directed at updating the system, at least in the near future.

Any time an external promise (to selenium-webdriver) is mixed with the ControlFlow queue, in this way, you run into these scheduling errors.

It might be worth experimenting, in the meantime, with something like

```js
import { promise as webdriverPromise } from "selenium-webdriver";
browser.driver.controlFlow().execute(() => {
  return webdriverPromise
    .when(getNativePromise())
    .then(url => browser.get(url));
});
```

I'm not actually sure if this is going to work for you, either, but it's an idea.
This is a leaky hack, which digs all the way into 3rd-party code, which is given to you pretty directly, and it's not well documented, how these systems all fit together, mid-test, so caveat emptor... but if this (or this general path) works, it might tide you over until ControlFlow is deprecated, and your code can move to promise chains, or async/await (which is actually part of the ES2017 spec now; it's just brand-new, so you need Babel, at minimum, to run on anything but the bleeding edge).

It's also mostly possible to disable ControlFlow, currently. Another possible avenue (which will likely require you to rewrite your current tests).

I hope this helps.

**Comment by johnhall** [comment]
Thanks for the info Sean.  I'll take a look at this and see what I can do.

**Comment by johnhall** [comment]
Closing this out as it's unlikely to be fulfilled due to upcoming changes in the Selenium framework.
