### ISSUE TITLE
Page not navigating to next screen using PhantomJS

### ISSUE THREAD

**Issue by kamaldeep03** [angular/protractor#4238]
Hi,

We have an application wherein there are 4 pages.

1) Login screen
2) Landing screen
3) Billing Summary screen
4) Account History screen 

We have written a protractor script to execute UI testing using "phantomJS" but it is not working fine.

The scripts using PhantomJs does navigate from login -> Landing and Landing to Billing Summary screen.

On billing summary screen, there is an account number href and the data on the UI for this page is loaded through multiple APIs (e.g.3 APIs). Now script is written as such that it will click this account number href and it should open account history page and do some processing on that account history screen.

But on the click of that href "it is not navigating to the account history page" on UI, however script is getting executed correctly and starts executing the script for next function which is for Account History Page. As using PhantomJs, it is not navigating to account history screen but script is executing function for account history page and therefore script fails at that moment and gives an error "No element found" because it is searching an element on account history page that has not navigated using phantomJS.

Everything goes well, if we switch browser ..say Google Chrome.

Can anyone please suggest a solution for it?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by wswebcreation** [comment]
@kamaldeep03, see also [this post](https://github.com/angular/protractor/issues/4217) about the support for PhantomJS

**Comment by heathkit** [comment]
I'm guessing this might be your issue: https://github.com/angular/angular/issues/15586

Though, as mentioned you might want to switch to using headless Chrome instead of PhantomJS.
