### ISSUE TITLE
Unable to update the option for a select in safari for protractor with angular 2

### ISSUE THREAD

**Issue by SURENDARREDDY** [angular/protractor#4239]
I am working on automation using protractor for one of angular 2 application. I am able to get the option element what I want to select for a drop down.

Note: I have tried many different ways to get the option from DOM.

But I couldn't able to select it using `click()` method on WebElement. The `click()` is working in chrome but not in safari. Tried with `browser.sleep()`,`ActionSequences`,`waitForAngular()` etc.. But none has worked.

example code snippet:

    `element(by.css('#country')).$('[value="1"]').click();`

or

     `element(by.css('#country')).filter(function (elem, index) {
        return elem.getText().then(function (text) {
        return text.indexOf('USA') !== -1;
     });}).first().click();`

As I said earlier, I have used many ways to get the element what I want. But I am unable to select or click it in safari browser.

Safari Version: 10.0.2 Mac Version: OS EI Captain 10.11.6

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
