### ISSUE TITLE
Sendkeys does not work on Firefox 53

### ISSUE THREAD

**Issue by rstraub** [angular/protractor#4242]
Hi, I noticed that my tests that send keys to inputs are currently failing. After a lot of searching I found out that this happens after updating to the latest version of Firefox (53). The previous version I run it on successfully was version 49.0.2.

Bug report
---

- Node Version: `7.6.0`
- Protractor Version: `5.1.1`
- Angular Version: `1.6.4`
- Browser(s): `Firefox`
- Operating System and Version `Mac OS X Sierra`
- Your protractor configuration file:
```
exports.config = {
    framework: 'jasmine',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    specs: ['e2e-tests/**/*.e2e-spec.js'],
    multiCapabilities: [{
        'browserName': 'firefox'
    }, {
        'browserName': 'chrome',
        'chromeOptions': {
            'args': ['show-fps-counter=true']
        }
    }]
};
```

- Output from running the test
`Failed: Expected [object Undefined] undefined to be a string`
- Steps to reproduce the bug
Run any test spec that uses `sendKeys()` to send values to an input with type text in the latest version of Firefox.

**Comment by masonmark** [comment]
I can corroborate your experience; it's [probably a geckodriver bug](https://github.com/webdriverio/webdriverio/issues/1999), though.

**Comment by rstraub** [comment]
Ah yes! I just upgraded the drivers and now its working again. Thanks for the heads-up 👍

**Comment by sachinndt** [comment]
Not workng with gecodriver 0.18
This is my sample code
 this.setColumnCellValue = function (ColumnName, rowNumber, columnPosition, input, browserName) {
        
        columnCell = element(by.xpath("//div[not(contains(@class,'grid'))]/div/table/tbody/tr[contains(@class,'skyblue')][" + rowNumber + "]/td[" + columnPosition + "]"));
        columnCell.click().then(function () {
            var elementInsideColumn = columnCell.all(by.tagName('input'));
            elementInsideColumn.count().then(function (count) {
                if (count == 1) {
                    browser.actions().sendKeys(protractor.Key.END).perform().then(function () {
                        browser.actions().sendKeys(protractor.Key.chord(protractor.Key.CONTROL, protractor.Key.SHIFT, protractor.Key.HOME)).perform().then(function () {
                            browser.actions().sendKeys(protractor.Key.DELETE).perform().then(function () {
                                browser.actions().sendKeys(input).perform();
                            })
                        })
                    })
                }

            })

        })
    };

in this it is clicking on element but not deleting text and not able to input text

**Comment by dani-oprean** [comment]
Doesn't work for me either. 
Latest firefox 70.0.1
Latest geckodriver: 0.26
Angular 7 app

My code is something like this:
`static async setEntryValue(ledger: ElementArrayFinder, ledgerPeriodIndex: number, value: string): Promise<void> {
    const amountInputElement = ledgerEntries.get(ledgerPeriodIndex); // an input
    await amountInputElement.clear();
    amountInputElement.sendKeys(value);
  }`

after clearing the input it adds the old value along with the new one.
