### ISSUE TITLE
issue with Jasmine defaultTimeOutInterval

### ISSUE THREAD

**Issue by TwinkleA** [angular/protractor#4248]
I am using protractor 5.1.1 and jasmine 2.6.0. all it steps in my spec file fail with error - A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
below is the spec file - 

`describe('test',function(){
    it('1',function(){
        console.log('step 1');        
    },10000);

    it('2',function(){
        console.log('step 2');
    },10000);

    it('3',function(){
        console.log('step 3');
    },10000);
});`

the script executes and console output is shown but for each of the steps (it) timeout error (mentioned above) is displayed. I have also tried setting the defaultTimeOutInterval in config file. I have also tried using  framework: 'jasmine',  framework: 'jasmine2', but same error is displayed in either of the options. have also tried scriptTimeout and pagetimeout options, but same issue persists

after executing the script, console looks like this - 
step 1
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Fstep 2
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
Fstep 3
A Jasmine spec timed out. Resetting the WebDriver Control Flow.

Note- I am executing my tests using grunt. is there any need of loading the plugins like the few I already have -  grunt.loadNpmTasks('grunt-protractor-runner');, grunt.loadNpmTasks('grunt-contrib-jshint');
    grunt.loadNpmTasks('grunt-mocha-test'); ?

grunt version-
grunt-cli v1.2.0
grunt v1.0.1

**Comment by NickTomlin** [comment]
Hi there!

Because it involves an error that could be any number of things and may be specific to your testing environment, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
