### ISSUE TITLE
No easy way to wait for webdriver start

### ISSUE THREAD

**Issue by mgol** [angular/protractor#425]
I've tried to set up Protractor with Grunt via [grunt-protractor-runner](https://npmjs.org/package/grunt-protractor-runner). The problem is that I want to be able to run all that automatically and:
1. Protractor needs `webdriver start` to be run manually
2. There is apparently no way to tell when `webdriver` is ready.

This creates a problem as my `grunt testE2E` command has to start webdriver somehow to be able to run Protractor tests. `webdriver start` cannot be run in a synchronous mode since it blocks but it also cannot be run in the background as then Protractor doesn't wait until it's fully initialized.

Is there any way around that? I want to test in both Firefox & Chrome so I need the Seleniun server for that.

EDIT: I assume there is no Firefox driver available that would allow one to skip Selenium for this browser as well? (i.e. it's not only an issue of implementing support in Protractor but that needed software is missing?)

**Comment by samueltcsantos** [comment]
Nice!
