### ISSUE TITLE
Getting an error "Expected false to be true." in the end of test

### ISSUE THREAD

**Issue by anupamdas24** [angular/protractor#4254]
Hello @juliemr

I am always getting the below error in the Terminal.

Message:
    Expected false to be true.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/Users/anupamdas/workspace/dap-ui-v2/test/E2E.spec.js:39:79)
        at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:110:25
        at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:676:7

2 specs, 1 failure
Finished in 54.254 seconds

**Protractor Conf file:**
var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');

var reporter = new Jasmine2HtmlReporter({
 savePath: '../dap-ui-v2/test-result/',
filePrefix: 'DAPe2e_Automation_Report',
screenshotsFolder: 'screenshots',
  consolidate: true,
  consolidateAll: true,
  takeScreenshots: true
  //takeScreenshotsOnlyOnFailures: true
});

exports.config = {
  // seleniumAddress: '/selenium-server-standalone-3.4.0.jar',
  seleniumAddress:'http://localhost:4444/wd/hub',
  specs: ['test/*spec*.js'],
  framework: 'jasmine2',
  getPageTimeout: 120000,
  allScriptsTimeout: 120000,

  onPrepare: function () {
   jasmine.getEnv().addReporter(reporter);
  }
}

**SPEC File:**

describe('DAP End to End Testing', function () {

  beforeEach(function () {
    // originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
    // jasmine.DEFAULT_TIMEOUT_INTERVAL = 160000;
    browser.waitForAngularEnabled(false);
    browser.driver.manage().window().maximize();
  });

  it('DAP Application', function () {
  
    browser.get('https://dap-ui-dev.run.aws-usw02-pr.ice.predix.io/');
    expect(element(by.xpath('//li[contains(text(),"GE Digital")]')).isPresent()).toBe(true);
    var overview = element(by.xpath('//a[contains(text(),"Overview")]'));
    expect(overview.isPresent()).toBe(true);
    var Features = element(by.xpath('//a[contains(text(),"Features")]'));
    expect(Features.isPresent()).toBe(true);
    var Testimonial = element(by.xpath('//a[contains(text(),"Testimonial")]'));
    expect(Testimonial.isPresent()).toBe(true);
    var ContactUs = element(by.xpath('//a[contains(text(),"Contact Us")]'));
    expect(ContactUs.isPresent()).toBe(true);
    ContactUs.click();
    Testimonial.click();
    Features.click();
    var headertext = element(by.xpath('//h1[contains(text(),"Digital Asset Passport")]'));
    expect(headertext.isDisplayed()).toBe(true);
    overview.click();
    browser.sleep(3000);
    var id = element(by.id('loginaction')).click();
    element(by.id('username')).sendKeys('***********'); // Intentionally made hidden
    element(by.id('password')).sendKeys('************');  // Intentionally made hidden
    element(by.id('submitFrm')).click();
    browser.sleep(12000);
    var welcome = element(by.xpath('//h1[contains(text(),"Welcome to GE")]'));
    expect(welcome.getText()).toEqual("Welcome to GE Digital Asset Passport");
    var appnav = element(by.xpath('html/body/dap-app/div/div/px-app-nav/nav/button')).click();
    browser.sleep(3000);
    expect(element(by.xpath('//a[contains(text(),"Sign Out")]')).isPresent()).toBe(true);

  }, 120000);

  it('DAP search landing page validation', function () {
  
  var arrowdropdown= element(by.xpath('//div[@id="trigger"]/iron-icon'));
  arrowdropdown.click();

  }, 120000);

});

**Comment by NickTomlin** [comment]
Hi there!

First, please don't `@`mention individual members when opening an issue. We all collaborate on the issue queue so there's no need to do this.

Second, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by anupamdas24** [comment]
Thanks a lot for the response. I was not aware of such channels for putting the question.
