### ISSUE TITLE
Protractor+appium for automating android native app

### ISSUE THREAD

**Issue by Tanmoy-dey** [angular/protractor#4259]
- Node Version: `6.10.3`
- Protractor Version: `5.1.1`
-appium Version: '1.6.4'
 I went through the issue #1940 which is closed where i see that current protractor version is supporting automation for native apps for mobile. I just wanted to confirm that does it support the native app automation, currently my protractor framework is giving me error - An unknown server-side error occurred while processing the command. Original error: Invalid timeout 'script'. It works till launching of the app after that it exits.  I went through the documentation and changed accoridngly my config file and installed required dependencies

my current config file looks like this:-

    seleniumAddress: 'http://localhost:4723/wd/hub',
    specs           : [ './../Acceptance\ tests/features/**/*.feature' ],
    
    capabilities: {
        'browserName': '',
        'platformName': 'Android',
       'platformVersion': '6.0',
       'deviceName': 'Motorola XT1562',
      'udid': 'ZY222875D2',
 'app':'/Users/tanmoydey/Downloads/apk
      'newcommandTimeout': '100',
      'appPackage': 'com.app.beta
      'appActivity': 'com.main.activity',
      'fullReset': true,
        //'autoWebview': true,
       //'autoWebviewTimeout': 10000

    },

    baseUrl: 'http://10.0.2.2:8100',

**Comment by wswebcreation** [comment]
@Tanmoy-dey 

I think you've linked the wrong issue. As for as I know native apps are not supported, only hybrid apps because you need the webview.

**Comment by Tanmoy-dey** [comment]
Thanks for the update, Yes i have linked a wrong issue it should have been #1940 just updated it.

**Comment by wswebcreation** [comment]
@Tanmoy-dey 

Tnx for your update. 1940 only refers to Hybrid apps, not Native. According to your info you have a native app, so this won't work.

**Comment by kgbheem** [comment]
@wswebcreation : could you please share me sample code which opens hybrid app and logs into the app. im using perfecto mobile for automation.  my client wants be to try protractor for automation hybrid app. you help would be greatly appreciated
