### ISSUE TITLE
E/launcher - chrome not reachable

### ISSUE THREAD

**Issue by rafaelcs** [angular/protractor#4260]
Hello folks,

There is some time that I am having intermittent problems after the tests run automatically in the continues integration tool Codeship

Locally I could never reproduce the error, but on the server this happens sometimes yes, sometimes not. All the details are below, if any information is missing, let me know.

---

- Node Version: `Node Version read from package.json: 7.10.0; Node Version used: 7.10.0`
- Protractor Version: `5.1.1`
- Angular Version: `I'm not using angular for that`
- Browser(s): `ChromeDriver; Driver info: chromedriver=2.29.461571`
- Operating System and Version `platform=Linux 4.2.0-42-generic x86_64`
- Your protractor configuration file: See [here](https://gist.github.com/rafaelcs/ee3d86709f1434480b1f42fe4fc4d5e9)
- A relevant example test: `No specific test, no spec is performed when tests start automatically for continuous integration (Codeship)`
- Output from running the test
![image](https://cloud.githubusercontent.com/assets/8113555/25713182/39470398-30ca-11e7-8f98-ab09019f9486.png)
- Steps to reproduce the bug: `When the test starts, the error occurs immediately (as you can see in the image above)`
- The URL you are running your tests against (if relevant): `Private project, I can not send the url`

**Comment by NickTomlin** [comment]
I believe this is an issue wth chromedriver running in Codeship and not something specific to Protractor. I'd suggest pursuing other channels like StackOverflow first; especially given the intermittent nature of this. 

Are you running your test inside a container?

**Comment by rafaelcs** [comment]
@NickTomlin I'm not running inside a container.

**Comment by rohitkadam19** [comment]
@rafaelcs What's the chrome browser version?

**Comment by heathkit** [comment]
You are not using Docker, but CodeShip is running your test in a Docker container. You are running in an LXC environment, so I think [this StackOverflow](http://stackoverflow.com/questions/42136865/org-openqa-selenium-webdriverexception-chrome-not-reachable) applies to you. Trying putting `--privileged` in your chromeOptions.

Since it involves usage and debugging, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks and good luck!

**Comment by rahulsolanki-infinity** [comment]
Node Version: Node Version read from package.json: 7.10.0; Node Version used: 8.9.3
Protractor Version: 5.1.2
Angular Version: I'm not using angular for that
Browser(s): ChromeDriver; Driver info: chromedriver=2.35.528139
Operating System and Version platform=Linux 4.13.0-32-generic x86_64
Your protractor configuration file: See here
exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome',
    chromeOptions: {
      args: [ "--headless", "--disable-gpu", "--window-size=800,600" ]
    } 
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: false } }));
  }
};
Still got the same issue : Chrome not reachable, half of the spec files were running in the same config and remaining spec file  show this error : 
- Failed: chrome not reachable
        (Session info: headless chrome=64.0.3282.119)
        (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.0-32-generic x86_64)
