### ISSUE TITLE
Logo image is out of date

### ISSUE THREAD

**Issue by alexsapps** [angular/protractor#4261]
On http://www.protractortest.org/#/ the page <title> and main banner/logo image say "end to end testing for AngularJS" which makes it sound like it's not going to work for Angular apps.

**Comment by NickTomlin** [comment]
Great point @seanmay do you happen to know who does asset work? Otherwise I can try to fire up the ol' photoshop and just remove the JS part of the logo 😄

**Comment by cnishina** [comment]
Looks like all the files are https://github.com/angular/protractor/tree/master/website/img.
