### ISSUE TITLE
Unable to click select element options with IEDriver

### ISSUE THREAD

**Issue by hudson-t** [angular/protractor#4266]
Bug report
---

- Node Version: `7.9.0`
- Protractor Version: `5.1.1`
- Angular Version: `2.4.6`
- Browser(s): `Internet Explorer 11`
- Operating System and Version `Windows 7 (64 bit)`
---

It is not possible to click on a select option with IEDriver. The following error is given:

**Error**
```
- Failed: Cannot click on element (WARNING: The server did not provide any stacktrace information)
  Command duration or timeout: 47 milliseconds
  Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
  System info: host: 'COMPUTERNAME', ip: '128.87.191.165', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_121'
  Driver info: org.openqa.selenium.ie.InternetExplorerDriver
  Capabilities [{browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, ie.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, pageLoadStrategy=normal, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, version=11, platform=WINDOWS, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.browserCommandLineSwitches=, requireWindowFocus=false, browserName=internet explorer, initialBrowserUrl=http://localhost:21958/, javascriptEnabled=true, ignoreProtectedModeSettings=false, enableElementCacheCleanup=true, unexpectedAlertBehaviour=dismiss}]
  Session ID: 23cd9516-8e61-4d13-97df-937c7c1e8c61
```

**Protractor Code**
```javascript
element(by.id('role')).click();
element(by.id('role')).element(by.cssContainingText('option', 'Standard User')).click();
```

**Page HTML**
```html
<select class="form-control ng-pristine ng-invalid ng-touched" id="role" name="role" placeholder="Enter the users role" required="" type="text" ng-reflect-name="role">
    <option>Standard User</option>
    <option>Admin</option>
    <option>Super User</option>
</select>
```

I also tried doing this in the REPL by setting a `browser.explore()` and the command returns null.

This works perfectly with Chrome & Firefox!

> B.T.W. I have changed by code to not use PageObjects for the purpose of this post.

**Comment by hudson-t** [comment]
I would like to point out I have also tried adding a wait for the select option element to be visible and this fails too. When using REPL I can see the select options and firing the click event just returns null.

Really there needs to be a wrapper for this so it's possible to do something like `ElementFinder.selectOptionByText("Option text")`. This would make things much cleaner!

**Comment by wswebcreation** [comment]
@hudson-t ,

Doesn't only this `element(by.id('role')).element(by.cssContainingText('option', 'Standard User')).click();` work? I'm using IE11 also and I don't have a problem when I click on the option without clicking on the select-box to open it. The code also works on Chrome, Firefox, Edge and Safari (9)

And true for the `ElementFinder.selectOptionByText("Option text")`, maybe you can add a PR for that ;-)

**Comment by hudson-t** [comment]
@wswebcreation - that worked! no problems now. Still can't understand why the option element is clickable when it is actually not visible... but it works!

Thanks

**Comment by wswebcreation** [comment]
Tnx for the feedback and closing the issue

**Comment by abhinaba1080** [comment]
@wswebcreation

Can you suggest me a good capabilities list for IE11?
