### ISSUE TITLE
Can not click on element, It throwing timeout error

### ISSUE THREAD

**Issue by perwez123** [angular/protractor#4269]
- Node Version:  `v6.9.4 `
- Protractor Version: `5.1.1`
- Angular Version: `1.2.28`
- Browser(s): `Chrome`

- Operating System and Version `MAC OS Siera - 10.12.3`

-My Website URL: `https://www.neonmob.com/`

- protractor configuration file
exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  framework: 'jasmine',
  specs: ['./Test/LoginTest.js'],
  allScriptsTimeout: 120000,
  getPageTimeout: 120000,
  jasmineNodeOpts: {
     showColors: true,
     defaultTimeoutInterval: 120000
}
- A relevant example test

There is button in the page, when i try to click using protractor , It throws time out error . Unable to click on the element. Same thing work on selenium webdriver. Is this happining becuase old veriosn of angularjs using in my application ?

-My Html element
```<span id="trade-btn" class="btn subdued trade small tip ng-binding ng-scope ng-isolate-scope" nm-event="Clicked Trade" nm-event-user-id="78563" nm-event-source="profile" data-placement="top" nm-trades-create="user" ng-switch-default="" data-original-title="Bob zan's trader grade is: <strong>A+</strong>.">```
```<i class="icon-trade"></i><span>Trade</span><iclass="pipe"></i>A+</span>```
I used below code to click on the button.

element(by.css("span[id='trade-btn']")).click();

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by NickTomlin** [comment]
An element that matches that selector does not exist `https://www.neonmob.com/` (it doesn't resolve for `document.querySelector("#trade-btn")` or `"span[id='trade-btn']"` when I load it in my browser. the troubleshooting channels that @wswebcreation stated are the best way to pursue this.
