### ISSUE TITLE
Protractor application get paused when system sleeps

### ISSUE THREAD

**Issue by anujchandran** [angular/protractor#4271]
Hi Guys,
I am working in a large project. There are about minimum 160 specs to be executed with protractor, and it consumes more than one hour to finish automation testing.  But issue is my system get sleeps in between it when no action is performed. Is there any way to make system alive until protractor finishes its execution.
So that I could run it without system sleep. I cant increase my sleep time because it had to be run in many sytem. Please let me know how could I handle it ?

Cheers.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by anujchandran** [comment]
Thanks, posted question on stackoverflow.
http://stackoverflow.com/questions/43845910/protractor-application-get-paused-when-system-sleeps

**Comment by wswebcreation** [comment]
Cool, can you also close this issue?

**Comment by anujchandran** [comment]
Ok thank you.
