### ISSUE TITLE
protractor fails to resize on jenkins (windows)

### ISSUE THREAD

**Issue by rafalf** [angular/protractor#4274]
Bug report
- Node Version:  v6.9.4
- Protractor Version: Version 5.1.1
- Browser(s): Chrome
- Operating System and Version Windows Server 2016

Ive tried out pretty much everything, yet nothing works

- browser.driver.manage().window().setSize(width, height);
- browser.driver.manage().window().maximize();

- via config 
1)
``` capabilities: {
    browserName: 'chrome',
    chromeOptions: {
        args: ['--window-size=800,600'] // THIS!
    }
}
```
</br>
2.
</br>

```
onPrepare: function() {
    var width = 1600;
    var height = 1200;
    browser.driver.manage().window().setSize(width, height);
},
```
</br> . 

## My config: (parts)

```
    onPrepare: function() {

        jasmine.getEnv().addReporter(new SpecReporter());
        jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: './reports/',
            screenshotsFolder: 'images',
            takeScreenshotsOnlyOnFailures: true
        }));


        // browser.driver.manage().window().setSize(1440, 900);
        // browser.driver.manage().window().maximize();
    }
```

</br>

```
    capabilities: {
        browserName: 'chrome',
        'chromeOptions': {
          // args: [
          //   '--start-maximized'
          // ],
        'prefs': {
          'credentials_enable_service': false,
          'profile': {
            'password_manager_enabled': false
          }
        }
      }
    },
```
## How do i know:
the test are passing locally on when i exec them from the command line and i can see that the browser is resized. however when i run it form jenkins, tests fail and when i look at the screenshots when the failure occurs, its obvious that the its not resized

**Comment by wswebcreation** [comment]
Hi @rafalf 

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

To give you answer to your question. If this is on a Windows Virtual machine you are accessing then the problem could be that the window size is not bigger if you are not logged on as a user. I've seen this in the past in a Selenium Grid with some Windows Virtual Machines. It's a setting in the VM to set the default screensize to for example 1920x1080 so you are able to use a size that is within these limits. I don't know exactly where to adjust this.

Thanks!

**Comment by kassbinder** [comment]
> Bug report
> 
> * Node Version:  v6.9.4
> * Protractor Version: Version 5.1.1
> * Browser(s): Chrome
> * Operating System and Version Windows Server 2016
> 
> Ive tried out pretty much everything, yet nothing works
> 
> * browser.driver.manage().window().setSize(width, height);
> * browser.driver.manage().window().maximize();
> * via config
> 
> 
> ```
>     browserName: 'chrome',
>     chromeOptions: {
>         args: ['--window-size=800,600'] // THIS!
>     }
> }
> ```
> 
> 2. 
> ```
> onPrepare: function() {
>     var width = 1600;
>     var height = 1200;
>     browser.driver.manage().window().setSize(width, height);
> },
> ```
> 
> .
> 
> ## My config: (parts)
> ```
>     onPrepare: function() {
> 
>         jasmine.getEnv().addReporter(new SpecReporter());
>         jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
>             savePath: './reports/',
>             screenshotsFolder: 'images',
>             takeScreenshotsOnlyOnFailures: true
>         }));
> 
> 
>         // browser.driver.manage().window().setSize(1440, 900);
>         // browser.driver.manage().window().maximize();
>     }
> ```
> 
> ```
>     capabilities: {
>         browserName: 'chrome',
>         'chromeOptions': {
>           // args: [
>           //   '--start-maximized'
>           // ],
>         'prefs': {
>           'credentials_enable_service': false,
>           'profile': {
>             'password_manager_enabled': false
>           }
>         }
>       }
>     },
> ```
> ## How do i know:
> the test are passing locally on when i exec them from the command line and i can see that the browser is resized. however when i run it form jenkins, tests fail and when i look at the screenshots when the failure occurs, its obvious that the its not resized
