### ISSUE TITLE
browser.waitForAngular should wait for animations to complete

### ISSUE THREAD

**Issue by mrmeku** [angular/protractor#4278]
Feature Request
---

- Reasons for adopting new feature
Until protractor has a way to install mock module's into Angular applications, animations cannot be disabled when running protractor tests without custom tooling. To circumvent animation related test flakes testers need to use browser.sleep to wait for animations to finish. This testing strategy is a bit of a code smell. It'll break whenever the length of an animation increases. Thus it would be nice if browser.waitForAngular integrated with angular's animation framework and waited until the all browser animations had settled before proceeding
  
- Is this a breaking change? (How will this affect existing functionality)
I don't think so...

**Comment by machtyn** [comment]
Would making this change also allow for a spinner to stop before continuing a test?
