### ISSUE TITLE
npm install -g protractor: Cannot read property 'path' of null

### ISSUE THREAD

**Issue by MarkAvreliy** [angular/protractor#4279]
Hello everyone.

I have two questions:
1) I try to install Protractor via npm and get a following error:

```
>npm install -g protractor
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0

npm ERR! Cannot read property 'path' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ECONNRESET

npm ERR! network socket hang up
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\blablabla\AppData\Roaming\npm-cache\_logs\2017-05-11T13_53_44_104Z-debug.log
```

But the following data was added to config:

> npm config set proxy http://User:Passwprd@www-proxy.company.com:80
> npm config set https-proxy http://User:Passwprd@www-proxy.company.com:80

```
>npm config list
; cli configs
scope = ""
user-agent = "npm/4.2.0 node/v7.10.0 win32 x64"

; userconfig C:\Users\blablabla\.npmrc
https-proxy = "http://User:Passwprd@www-proxy.company.com:80/"
proxy = "http://User:Passwprd@www-proxy.company.com:80/"

; builtin config undefined
prefix = "C:\\Users\\blablabla\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; cwd = C:\Users\blablabla
; HOME = C:\Users\blablabla
; "npm config ls -l" to show all defaults.
```

Log file is empty: C:\Users\blablabla\AppData\Roaming\npm-cache\_logs\2017-05-11T13_53_44_104Z-debug.log

2) Could anyone give me a link to Protractor forum?

Thanks an advance!

**Comment by NickTomlin** [comment]
Hi there!

This is an issue with NPM and your network, and not with Protractor. Because of that, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow. (Please do not ask support questions here on Github.)

Thanks!

**Comment by MarkAvreliy** [comment]
Thank you for answer, Nick. I agree with you.
