### ISSUE TITLE
browser.navigate().back() not working on GeckoDriver

### ISSUE THREAD

**Issue by Tom-Hudson** [angular/protractor#4282]
Bug report
---

- Node Version: `7.9.0`
- Protractor Version: `5.1.1`
- Angular Version: `2.4.10`
- Browser(s): `Firefox 53.0.2`
- GeckoDriver Version: `0.16.1`
- Operating System and Version `Windows 7 (64 bit)`
---
When I use `browser.navigate().back()` in a spec with GeckoDriver, nothing happens and the spec times out. This doesn't happen with ChromeDriver or IEDriver.

However, if I use `browser.explore()` at the same place I am calling `browser.navigate().back()` and then call it in the command prompt, everything works fine and the browser navigation works...

Because of this I thought it was a syncronisation issue so I initially added `browser.waitForAngular()` with no luck (but left this in becasue it may be needed)! I then added `browser.sleep(5000)`, so it would wait for 5 seconds before doing the `browser.navigate().back()` call but this didn't help either.

I don't think I am doing anything wrong so can only assume it's a bug!

**Problematic Spec**
```
describe("Logout", () => {
    beforeAll(() => {
        AppStateHelper.Clean(); // This does DB cleaning and calls browser.manage().deleteAllCookies() - all managed properly with controlflow promises!!!
    });

    describe("when the 'Logout' link is clicked", () => {
        beforeAll(() => {
            LoginPage.loginAsSuperUser();
            Component.Header.goToAdminDashboard();
            Component.Header.Logout();
        });

        it("should take the user to the Login page", () => {
            browser.waitForAngular();
            expect(browser.getCurrentUrl()).toContain(LoginPage.fullPageUrl());
        });

        describe("when the browser's back button is used", () => {
            it("should not allow you to go back to the page", () => {
                browser.waitForAngular();
                browser.navigate().back();

                expect(browser.getCurrentUrl()).toContain(LoginPage.fullPageUrl());
            });
        });

        describe("when login is attempted with valid credentials", () => {
            it("should take the user to the dashboard", () => {
                LoginPage.login(UserData.superUser.username, UserData.superUser.password);

                expect(browser.getCurrentUrl()).toBe(DashboardPage.fullPageUrl());
            });
        });
    });
});
```

> I will be wrapping `browser.waitForAngular()` & `browser.navigate().back()` into a nice clean helper method when this is sorted!

I did think it might be related to this [GeckoDriver issue](https://github.com/mozilla/geckodriver/issues/697), but I get no error message back from Selenium or anything.

**Comment by NickTomlin** [comment]
This does sound related to the Geckodriver issue you linked to. It looks like this has been fixed in Geckodriver nightly. I'm not actually sure how to grab a nightly release (feel free to post here if you can figure it out before I do) but you can point to that version with `webdriver manager update --gecko 16.x` to update once it is.

**Comment by hudson-t** [comment]
@NickTomlin - just downloading the C++ dependencies to build GeckoDriver. I will post the build here when I'm done and let you know if it worked!

**Comment by hudson-t** [comment]
@NickTomlin - okay, I got a build but I just took it from master. It works but hasn't resolved my issue. But I am not sure I am getting the code from the right place!?

[geckodriver.zip](https://github.com/angular/protractor/files/997075/geckodriver.zip)

**Comment by NickTomlin** [comment]
I've never actually run a manually built version of Geckodriver before. Are you sure that protractor is actually pointing to the correct version?

**Comment by hudson-t** [comment]
@NickTomlin - I have the version explicitly set in my conf file:
```
// Selenium Server config
    seleniumServerJar: `${seleniumDirectory}selenium-server-standalone-3.4.0.jar`,
    localSeleniumStandaloneOpts: {
        port: 4444,
        jvmArgs: [
            `-Dwebdriver.ie.driver=${seleniumDirectory}IEDriverServer3.3.0.exe`,
            `-Dwebdriver.gecko.driver=${seleniumDirectory}geckodriver-nightly.exe`,
            `-Dwebdriver.chrome.driver=${seleniumDirectory}chromedriver_2.29.exe`]
},
```
And here is the GeckoDriver in `seleniumDirectory`:
![image](https://cloud.githubusercontent.com/assets/26221061/26047093/bc71444a-3949-11e7-826e-caf8374b08b1.png)

I am not sure why the version I have built is so much smaller than the one which comes from webdriver-manager?

I will take another look into where to build the nightly from today.

**Comment by hudson-t** [comment]
@NickTomlin - I asked the guys who make GeckoDriver where to build the nightly from and they told me:

> The fix for this bug resides in the Marionette remote protocol, which lives inside Firefox. You will need to test with the latest Firefox.

However, I have since moved to the latest nightly build of Firefox for runing the tests and the problem is still occuring.

**Comment by hudson-t** [comment]
@NickTomlin - just created a [repo](https://github.com/hudson-t/protractor-mcve) to re-create the issue. However, I could't find an Angular 2 powered site to demo this on... so I used StackOverflow and it turns out the issue doesn't occur if the site is non-Angular powered. If you send me a link to an Angular site with more than 1 page I can amend the spec as right now it all passes...

**Comment by Tom-Hudson** [comment]
@NickTomlin - this now works btw. So much has changed in my setup that I have no idea what fixed it.

So I am closing this now!
