### ISSUE TITLE
"property 'defineCommand' of undefined" error is appearing on calling apis provided by webdriver-js-extender

### ISSUE THREAD

**Issue by helloabhi** [angular/protractor#4288]
In the before annotation, I have written below code

```
var webdriver = require('selenium-webdriver');

    var extendedWebdriver = require('webdriver-js-extender').extend(webdriver);

    extendedWebdriver.setNetworkConnection(5);
```

Please see the error mentioned below

> Failed: Cannot read property 'defineCommand' of undefined
> Stack:
> TypeError: Cannot read property 'defineCommand' of undefined
> at Extender.defineCommand (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/extender.ts:33:19)
> at CommandDefinition.compile (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/command_definition.ts:13:16)
> at Object.extend (/Users/nextgen/nextgen-test-volunteeringMobileApp/node_modules/webdriver-js-extender/lib/index.ts:65:50)
> at Object. (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:45:66)
> at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:110:25
> at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1067:7)
> at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2396:12)
> at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
> at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2970:14)
> at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2953:27)
> From: Task: Run beforeEach in control flow
> at Object. (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:94:19)
> From asynchronous test:
> Error
> at Suite. (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:35:5)
> at Object. (/Users/nextgen/nextgen-test-volunteeringMobileApp/Specs/LoginSpec.js:27:1)
> at Module._compile (module.js:571:32)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:488:32)
> at tryModuleLoad (module.js:447:12)

**Comment by NickTomlin** [comment]
I'm sorry that this didn't get much chatter on the webdriver-js-extender [issue](https://github.com/angular/webdriver-js-extender/issues/15). I'm going to close this and pick up the conversation there. Thanks!
