### ISSUE TITLE
unable to update and start webdriver-manager

### ISSUE THREAD

**Issue by TwinkleA** [angular/protractor#4289]
Hi, 

I am unable to update and start webdriver-manager since 2 days, below error message is displayed when I try to run commands webdriver-manager update or webdriver-manager start

I have tried several ways, with and without proxy but nothing worked!

![image](https://cloud.githubusercontent.com/assets/18376082/26091508/5775a4f6-3a29-11e7-9cd0-b6df7e67f309.png)

has anyone seen this error before?

I have node-v6.9.1 and npm-4.2.0 version installed

**Comment by cnishina** [comment]
What version of webdriver-manager are you using? Could you remove your `node_modules` directory and reinstall your node modules? `webdriver-manager start` should not have a `ECONNRESET` error.

**Comment by NickTomlin** [comment]
I'm seeing this myself but I am also behind a corporate network that blocks requests to certain external storage providers, so it could just be an error bubbling up from that.

- OS: `OSX 10.24` 
- Node  `6.10.3`
- Protractor `5.1.2`
- Webdriver manager `12.0.6`

I'll double check this when I get home tonight.

**Comment by cnishina** [comment]
I'm trying some similar issues here...with some debugging info to manually make curl calls.

https://github.com/angular/webdriver-manager/issues/252

**Comment by NickTomlin** [comment]
Great; I think in the future i'll try to push these webdriver-manager issues to the webdriver-manager repo itself. I'll keep this open to track for now.

**Comment by cnishina** [comment]
I am already tracking a similar issue. 

@TwinkleA please open up an issue in https://github.com/angular/webdriver-manager/issues

**Comment by TwinkleA** [comment]
I am using webdriver-manager 12.0.2 version.
as @NickTomlin mentioned, I was seeing this issue as I was in corp network, but even --proxy option did not work for me, I connected to home network to install the updates

**Comment by TwinkleA** [comment]
@cnishina I have opened the issue here - https://github.com/angular/webdriver-manager/issues
