### ISSUE TITLE
I am not able to click on element using any of the locators only javascript executor works for me in angular 2 pages

### ISSUE THREAD

**Issue by Shobysukumaran** [angular/protractor#4291]
Here is my html for angular 2 applications. I am executing my tests in chrome
```
<md-card-title _ngcontent-c10="" class="ra-card-title mat-card-title">
      <a _ngcontent-c10="">Massachusetts Division of Banks Issues Decision Establishing Limit on Maximum Allowable Fee for Dishonored Checks for State - Chartered Financial Institutions</a>
    </md-card-title>
<div _ngcontent-c10="" class="ra-card-header__footer">
      <md-card-subtitle _ngcontent-c10="" class="ra-card-code mat-card-subtitle">BLN3594</md-card-subtitle>
      
      <div _ngcontent-c10="" class="ra-card-menu">
        <span _ngcontent-c10="" aria-haspopup="true" class="ra-card-menu-button">...</span>
        <md-menu _ngcontent-c10="" role="menu" xposition="before" yposition="below"><!----> </md-menu>
      </div>
    </div>

<md-card-subtitle _ngcontent-c10="" class="ra-card-code mat-card-subtitle">BLN3594</md-card-subtitle>
```
I am not able to click on the menu button using 
```
element(by.xpath("//span[@class='ra-card-menu-button'])[0]")).click();
```

But if I use below javascript executor , it is working fine.
```
var scrpt = "return document.getElementsByClassName('ra-card-menu-button')[0].click();";
        browser.executeScript(scrpt).then(function (text) {
            logger.log('info', 'Script is: ' + scrpt);

        });
```
protractor version is  5.1.1.

Could anyone please help me to identify the issue

**Comment by cnishina** [comment]
In the first example you are using xpath and then in the second one you are using class to find your element. Have you tried to identify it with css? `element(by.css('.ra-card-menu-button'))`?

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by Shobysukumaran** [comment]
Yes , I have tried element(by.css('.ra-card-menu-button')). BUt no luck. 

I am able to work only through javascript

**Comment by srii1234** [comment]
If i understand correctly , in the first statement you are tyring to select all elements and in the second i see you have given the index. I believe you should be using the following and hope it works. : 
element.all(by.css('ra-card-menu-button'])).click();

And to chose one you can use the index.

**Comment by Shobysukumaran** [comment]
I tried like below:
 element.all(by.css('ra-card-menu-button')).then(function(ele){
            var open=ele[0];
            open.click();
        })

But Getting the followng error 
 " - Failed: Cannot read property 'click' of undefined "

**Comment by wswebcreation** [comment]
Because by CSS means that you need to provide a `.` for classes and a `#` for ID's. Now you are looking for the TAG `ra-card-menu-button`, you should use `element(by.css('.ra-card-menu-button')).click();`

Don't `then()` here

**Comment by surfaslt** [comment]
I have the same issue:

`When('I write {val} inside {inputBoxName} input box', (val: string, inputBoxName: string, callback) => {

  let inputbox = element(by.css('#roomWidthInput'));
  console.log('inputBox promise set');

  var scrpt = "return document.getElementById('roomWidthInput');";
  browser.executeScript(scrpt).then(function (text) {
    console.log('info', 'Script is: ' + scrpt);
  });

  inputbox.isPresent().then(function(isElementVisible) {
    console.log('hello!');
    expect(isElementVisible).to.be.true;
    callback();
  });
});`
The console logs:
inputBox promise set
info Script is: return document.getElementById('roomWidthInput');

and then it throws Error: function timed out after 5000 milliseconds.
Any help would be really appreciated.

**Comment by stemkar123** [comment]
@Shobysukumaran Did you get any resolution for your issue ? I am facing same issue after upgrading Chrome. Normal click() function is not working. I have to use javascript executor to click. 

browser.executeScript("arguments[0].click();", <webelement>)

**Comment by Shobysukumaran** [comment]
@stemkar123 can you share the HTML of your page please?

**Comment by Shobysukumaran** [comment]
@stemkar123 In the success of execute script you can enter this inputBox.isPresent().then(function(isElementVisible) {
console.log('hello!');
console.log((isElementVisible) );
expect(isElementVisible).to.be.true;
callback();
});
