### ISSUE TITLE
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TI MEOUT_INTERVAL.

### ISSUE THREAD

**Issue by hpalusa** [angular/protractor#4296]
Hi All,

While running bulk of scripts  getting "Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL."  and scripts are Passing.

If I run scripts individually, those are working as excepted. My bulk scripts are failing . Please need help on this .

Thanks,
Hemanth Kumar Palusa

**Comment by hpalusa** [comment]
Protractor scripts

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
