### ISSUE TITLE
Cucumber times out when using browser.sleep 

### ISSUE THREAD

**Issue by pnakhat** [angular/protractor#4297]
issue is when I use below code , cucumber timeout. Global timeout is set to be 20 seconds 

`
defineSupportCode(function({setDefaultTimeout}) {
    setDefaultTimeout(20 * 1000);
});`

`browser.sleep(10000).then(
            function(){
                console.log("Waiting");
            }
        )`

Error log

` Error: function timed out after 20000 milliseconds
     at Timeout.<anonymous> (C:\code\cucumber-js\node_modules\cucumber\lib\user_code_runner.js:91:22)
     at ontimeout (timers.js:386:14)
     at tryOnTimeout (timers.js:250:5)
     at Timer.listOnTimeout (timers.js:214:5)
`
**Version of  plugins**

`   "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "cucumber": "^2.1.0",
    "cucumber-html-report": "^0.6.0",
    "cucumber-html-reporter": "^0.4.2",
    "install": "^0.10.1",
    "npm": "^4.6.1",
    "protractor": "^5.1.0",
    "protractor-cucumber-framework": "^3.1.0",
    "protractor-screenshot-reporter": "0.0.5"`

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
