### ISSUE TITLE
Angular could not be found on the page (Edge and Safari 10)

### ISSUE THREAD

**Issue by Niyarlatotep** [angular/protractor#4298]
Bug report
---

- Node Version: `7.10.0`
- Protractor Version: `5.1.2`
- Angular Version: `1.5.8`
- Browser(s): `Microsoft Edge (40.15063.0.0.0), Safari 10 (10.1.1(12603.2.4))`
- Operating System and Version `Windows 10, macOS Sierra (10.12.5)`
- Your protractor configuration file
"exports.config = {
    allScriptsTimeout: 120000,
    getPageTimeout: 10000,
    seleniumAddress: 'http://SELENIUM-HOST:4444/wd/hub',

    specs: [
        "specs/other/somesuite.js",
    ],

    multiCapabilities: [
        { browserName: 'MicrosoftEdge' },
        // {browserName: 'safari'}
    ],
    maxSessions: 1,
    framework: 'jasmine2',

    jasmineNodeOpts: {
        defaultTimeoutInterval: 90000
    },
};"

- A relevant example test
"any test"

- Output from running the test
1) Test suits
  Message:
    Failed: Angular could not be found on the page https://<address>/.If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
  Stack:
    Error: Angular could not be found on the page https://<address>/.If this is not an Angular application, you may need to turn off waiting for Angular.
                              Please see 
                              https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular-on-page-load
        at executeAsyncScript_.then (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\lib\browser.ts:936:29)
        at ManagedPromise.invokeCallback_ (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1366:14)
        at TaskQueue.execute_ (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2970:14)
        at TaskQueue.executeNext_ (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2953:27)
        at asyncRun (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2813:27)
        at C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:676:7
        at process._tickCallback (internal/process/next_tick.js:109:7)
    From: Task: Run beforeAll in control flow
        at Object.<anonymous> (C:\Users\<user>\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test: 
    Error
        at Suite.describe (C:\SELENIUM-TESTS\specs\smoke\someTest.js:10:5)
        at Object.<anonymous> (C:\SELENIUM-TESTS\specs\smoke\someTest.js:9:1)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
Pending:

1) Test 2
  Temporarily disabled with xit

2 specs, 1 failure, 1 pending spec
Finished in 16.088 seconds

- Steps to reproduce the bug
I'm trying to run protractor 5.1.2 against MicrosoftEdge, and it fails with the message: Angular could not be found on the page https://<webAppAddress>/.If this is not an Angular application, you may need to turn off waiting for Angular. If i turn off waitForAngularEnabled (set it false) it starts to work, and i have the same situation against Safari 10. But the same tests work fine against latest versions of Chrome, Fierfox and IE. AngularJS v1.5.8

**Comment by timothystone** [comment]
@Niyarlatotep any updates on this since May? Same experience in Safari 11.0.1 on Mac OS X Sierra.

**Comment by hadasshani** [comment]
Hi,

Any update?

**Comment by Niyarlatotep** [comment]
@timothystone No updates. I stoped investigating, didn't have time for it. I thing it could be our project issue, because testing AngularJS pages (in example) works fine. I'd like to research it bit later, if there will be any news, will report.

**Comment by hadasshani** [comment]
Is there any other way I can test these pages with Safari 11/10? I'm new to Angular and protractor and was wondering if there any work around.

**Comment by Niyarlatotep** [comment]
@hadasshani At least you can turn off angular synchronization, like this browser.waitForAngularEnabled(false), unfortunately then you lost profit from synchronization using. Description here https://github.com/angular/protractor/blob/master/docs/timeouts.md#how-to-disable-waiting-for-angular

**Comment by GuyMograbi** [comment]
Any update? I am running into this now.

**Comment by evilaliv3** [comment]
Did anyone found a solution here?

**Comment by sdoroshenko-CLGX** [comment]
set browser.waitForAngularEnabled(false); in test

**Comment by evilaliv3** [comment]
Thank you @sdoroshenko-CLGX but this is actually not a solution for testing angular applications.
