### ISSUE TITLE
Commands Are Being Skipped

### ISSUE THREAD

**Issue by vippakay** [angular/protractor#4301]
Hello,

During the test execution, some commands are being skipped. The execution is not getting aborted once an invalid command (like clicking on the button which does not exist) is found.. Test is failing only when the expectation is failed or else its throwing a false positive test result.

Bug report
---
Node Version: 7.8.0
Protractor Version: 5.1.1
Angular Version: 2.3.0
Browser(s): Chrome- Operating System and Version `` Windows 10

package.json,
  "dependencies": {
    "adm-zip": "0.4.7",
    "chromedriver": "^2.29",
    "colors": "1.1.2",
    "geckodriver": "1.6.1",
    "grunt": "~0.4.5",
    "grunt-cli": "~0.1.13",
    "grunt-concurrent": "~2.2.1",
    "grunt-protractor-runner": "~3.0.0",
    "jasmine-reporters": "2.2.0",
    "jasmine-spec-reporter": "3.2.0",
    "load-grunt-tasks": "~3.4.1",
    "lorem-ipsum": "1.0.3",
    "mongodb": "^2.2.26",
    "node-gyp": "~3.3.1",
    "pdf2json": "1.1.7",
    "protractor": "^5.1.0",
    "protractor-jasmine2-screenshot-reporter": "0.3.2",
    "webdriver-manager": "^12.0.5",
    "selenium-server": "^2.53.0",
    "selenium-webdriver": "^3.4.0",
    "xml2js": "~0.4.16",
    "path": "0.12.7",
    "typescript": "~2.0.0",
    "q": "1.5.0"
  },
  "devDependencies": {
    "grunt-jsdoc": "~1.0.0",
    "@types/jasmine": "^2.5.38",
    "@types/jasminewd2": "^2.0.1",
    "grunt-npm-install": "~0.3.0",
    "ink-docstrap": "~0.5.2",
    "minami": "~1.1.1",
    "protractor-perf": "^0.2.1",
    "cwi-node-api": "git+ssh://git@stash:7999/aut/cwi-api-driver-js.git"
  }
}

**Comment by wswebcreation** [comment]
Can you also provide a script that you are using? Based on your description it looks like a promise problem

**Comment by vippakay** [comment]
pages.documentManager.documents.selectDocumentByName(riskReport);
pages.riskReport.addRiskAssessment("Low");
pages.navbar.documents.click();
pages.documentManager.clickEditBtn(); pages.documentManager.documents.getDocumentIndexByName(name).then(function (index) {
documentIndex = index;
pages.documentManager.documents.editBtnByIndex(index).click();
pages.documentManager.documentProperties.editVisibility.click();
pages.documentManager.visibilityDialog.addRiskAssessmentCondition("High");
pages.documentManager.visibilityDialog.changeOverallCondition("all");
pages.documentManager.visibilityDialog.saveBtn.click();
pages.documentManager.documentProperties.saveBtn.click();
expect(pages.documentManager.documents.visibleIcon(documentIndex).isPresent()).toBe(true);
pages.documentManager.documents.selectDocumentByName(riskReport);
pages.riskReport.addRiskAssessment("High");
pages.navbar.documents.click();
pages.documentManager.clickEditBtn();
//below commands are being skipped
pages.documentManager.documents.documentName(documentIndex).click(); 
//Alternate: pages.documentManager.documents.selectDocumentByName(name);

pages.checklist.groups.selectProcedureResponseq(procedure1, 'Yes');
pages.navbar.documents.click();
pages.documentManager.clickEditBtn();
expect(pages.documentManager.documents.hiddenIcon(documentIndex).isPresent()).toBe(true);
});
});

**Comment by NickTomlin** [comment]
It's difficult to understand what is wrong here; I think @wswebcreation is probably right in that this is a scheduling issue with the webdriver promise flow but it's going to take some debugging to figure out what the issue actually is.

Because of this, you question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
