### ISSUE TITLE
IE webdriver session not clearing cookies.

### ISSUE THREAD

**Issue by Harish247** [angular/protractor#4302]
Hi,

I am using IE web driver 3.4 to run the test cases. I have to log in with different users to run different test cases. But whenever I open a new session the web driver is saving cookies from the previous login. The web driver should remove all the cookies when the session closed but in this case that is not happening. For chrome driver, there is no problem.

I changed some configuration in internet explorer by removing the history while exiting, but it is not working.

Is there any workaround?

Bug report
---

- Node Version: `7.4`
- Protractor Version: `5.1.1`
- Angular Version: `4.1`
- Browser(s): `internet explorer`
- Operating System and Version `Mac Sierra`

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
