### ISSUE TITLE
Integration with material 2 components

### ISSUE THREAD

**Issue by gtzinos** [angular/protractor#4304]
Hello guys,

Thanks for your great job. I am currently using the material 2 components for a better user experience. Now i am trying to develop some e2e tests with your framework, but i am wondering how can i set value to material 2 multiple select list (https://material.angular.io/components/component/select). I tryied to use by.model but it isn't possible for angular 4.0. Last a simple for loop in elements but it doesn't work :
     
     let want_to_select = ["test"];
     element(by.id("list")).click();
     let available_options= element.all(by.tagName('md-option'));
           
     for(var i = 0; i < want_to_select.length; i++)
     {
          for(var j = 0; j < available_options.length; j++)
          {
              available_options.get(j).getText().then(data => {
                 if(want_to_select[i] == data)
                 {
                     available_options.get(j).click();
                  }
               })    
            } 
        }

Any workaround ? 

*All packages at latest versions.

Thanks.

**Comment by gtzinos** [comment]
Workaround:
            let want_to_select = ["test"];
            element(by.id("list")).click();
            let available_options = element.all(by.tagName('md-option'));
            available_options.count().then(length => {
                for(let i = 0; i < want_to_select .length; i++)
                {
                    for(let j = 0; j < length; j++)
                    {
                        available_options.get(j).getText().then(data => {
                            if(want_to_select[i] == data)
                            {
                                available_options.get(j).click();
                            }
                        })
                    }
                }
            })

**Comment by fortunella** [comment]
I use this for selecting an option by its text:

```
element(by.id('list')).click();
element(by.cssContainingText('.mat-option', 'test')).click();
```

Or if you want to select an option by its value you can use this:

```
element(by.id('list')).click();
$('.mat-option[ng-reflect-value="' + value + '"]').click();
```

**Comment by gtzinos** [comment]
Your code doesn't work for me, it returns me this error:

 Other element would receive the click: <div class="cdk-overlay-backdrop cdk-overlay-transparent-backdrop cdk-overlay-backdrop-showing"></div>

**Comment by fortunella** [comment]
Oh sorry, I missed from your original post that you have a multiple select. My code should work for a single select.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README:


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
