### ISSUE TITLE
Protractor fails to upload files which are greater than 200 MB due to limitations of FileDetector

### ISSUE THREAD

**Issue by sri85** [angular/protractor#4305]
- Node Version: `v6.9.2`
- Protractor Version: `5.1.1`
- Angular Version: ``
- Browser(s): `Chrome`
- Operating System and Version `MAC OSX El Capitan 10.11.6`

- Steps to reproduce the bug
1. Try uploading a file which is more than 250 MB
Minimal TC

```
browser.setFileDetector(new remote.FileDetector());
$(element).sendKeys(<some big file>).then(function(){
            console.log("File uploaded");
        }).catch(function(err){
            console.log("Failed to select a file",err)
        });
```

Expected Result:
File should be uploaded successfully.

Actual Result:
```
"toString()" failed
    at Buffer.toString (buffer.js:495:11)
```
I think  I might be hitting https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/4442

Are there any workarounds ? Or a possible fix ?

**Comment by NickTomlin** [comment]
Sorry for the late reply here. This is a _very large_ file size. Protractor doesn't do any specific handling of files here so this is definitely something better raised on the selenium project. Please open an issue there if this is something you need. 

Thanks!
