### ISSUE TITLE
I follow the issue #722 "How to access nested ng-repeat elements"

### ISSUE THREAD

**Issue by tom35** [angular/protractor#4309]
I follow the issue #722 - "How to access nested ng-repeat elements".  But, when I change row_2.getText() to
row_2[j].click().  Not thing happen.  Is there any way to perform click() on nested ng-repeat element.  For example, access miscellaneous sub-elements in Angularjs FAQ page: https://docs.angularjs.org/misc.

The view: 
<ul class="nav-list naked-list">
<li class="nav-index-group ng-scope" ng-repeat="navGroup in currentArea.navGroups track by navGroup.name">
<a class="nav-index-group-heading ng-binding active current" href="misc" ng-class="navClass(navGroup)" style="">Miscellaneous</a>
<ul class="aside-nav">
<li class="nav-index-listing ng-scope active" ng-repeat="navItem in navGroup.navItems" ng-class="navClass(navItem)" style="">
<a class="ng-binding" tabindex="2" ng-class="linkClass(navItem)" href="misc/contribute">Develop</a>
</li>
<li class="nav-index-listing ng-scope active" ng-repeat="navItem in navGroup.navItems" ng-class="navClass(navItem)">
<a class="ng-binding" tabindex="2" ng-class="linkClass(navItem)" href="misc/downloading">Downloading</a>
</li>
<li class="nav-index-listing ng-scope active" ng-repeat="navItem in navGroup.navItems" ng-class="navClass(navItem)" style="">
<a class="ng-binding" tabindex="2" ng-class="linkClass(navItem)" href="misc/faq">FAQ</a>
</li>
<li class="nav-index-listing ng-scope active" ng-repeat="navItem in navGroup.navItems" ng-class="navClass(navItem)">
<a class="ng-binding" tabindex="2" ng-class="linkClass(navItem)" href="misc/started">Getting Started</a>
</li>
</ul>
</li>
</ul>

The protractor code:
element.all(by.repeater('suggestion_type in searchBoxData.suggestion_types')).then(function(rows) {
  for(var i=0;i<rows.length;i++){
    rows[i].all(by.repeater('content in suggestion_type.contents')).then(function(rows_2) {
      console.log(rows_2);
      for(var j=0;j<rows_2.length;j++){
        **rows_2[j].click(); //it doesn't work here**
        });
      }
    });
  }
});

Or alternative: 
element.all(by.repeater('content in suggestion_type.contents')).each(function(elem) {
  _elem.click();_// doesn't work too
});

Any help will be very appreciated.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
