### ISSUE TITLE
is it possible to make protractor work with none angular pages?

### ISSUE THREAD

**Issue by yhjhoo** [angular/protractor#4310]
is it possible to make protractor work with none angular pages?

Let's say jquery or some other frameworks.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

To answer your question, please check the [FAQ](https://github.com/angular/protractor/blob/b6207ead81b19e82f830b25762b2e79a84233c0c/docs/faq.md#how-do-i-deal-with-my-log-in-page).

Thanks and can you please close your question?

Grtz

**Comment by NickTomlin** [comment]
This is definitely possible and there are a lot of resources out there to help with this. I'd start with the [docs](https://github.com/angular/protractor/blob/b6207ead81b19e82f830b25762b2e79a84233c0c/docs/timeouts.md#how-to-disable-waiting-for-angular) and there are plenty of articles and Stackoverflow questions to help you along. Good luck!
