### ISSUE TITLE
I am randomly getting “ScriptTimeoutError” using protractor from last 5-6 days

### ISSUE THREAD

**Issue by helloabhi** [angular/protractor#4312]
My test suite contains more than 200 test cases and often I get ScriptTimeoutError for few test cases. This error is random and is not specific to a particulat test cases. 

Please Note: allScriptsTimeout: 120000, is set in conf.js file
protractor version = 5.1.2

Please see the error log
```

  Failed: Timed out waiting for asynchronous Angular tasks to finish after 120 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
    While waiting for element with locator - Locator: by.cssContainingText(".ng-binding", "My example").
    The following tasks were pending:
     - $http: https://api.example.com/api/exampleionUsers
  Stack:
    ScriptTimeoutError: asynchronous script timeout: result was not received in 120 seconds
      (Session info: chrome=59.0.3071.86)
      (Driver info: chromedriver=2.29.461591 (62ebf098771772160f391d75e589dc567915b233),platform=Windows NT 10.0.14393 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 120.07 seconds
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'LAPTOP-RNQ2JQBE', ip: '192.168.89.84', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.29.461591 (62ebf098771772160f391d75e589dc567915b233), userDataDir=C:\Users\NEXTGEN\AppData\Local\Temp\scoped_dir15404_10872}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=59.0.3071.86, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
```

**Comment by NickTomlin** [comment]
Hi there!

Unfortunately timeouts like this are not uncommon with selenium based integration tests. This could be a problem with your application or with your CI setup or any number of things. If you believe there is an issue with Protractor, please isolate the problem and file another issue.

If you are looking for general help, please ask a question on StackOverflow or Gitter: [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
