### ISSUE TITLE
Angular 2 waiting 30 seconds after page is loaded

### ISSUE THREAD

**Issue by fortunella** [angular/protractor#4316]
- Node Version: v7.10.0
- Protractor Version: 5.1.2
- Angular Version: 4.1.3
- Browser(s): Chrome
- Operating System and Version: Ubuntu 17.04
- Your protractor configuration file:

```
let SpecReporter = require('jasmine-spec-reporter').SpecReporter;

exports.config = {
  baseUrl: 'http://localhost:4200/',
  suites: {
    mandators:      './e2e/mandators/**/*.e2e-spec.ts',
    organizations:  './e2e/organizations/**/*.e2e-spec.ts'
  },
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    showTiming: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 120000,
    print: function() {}
  },
  allScriptsTimeout: 30000,
  getPageTimeout: 30000,
  beforeLaunch: function() {
    require('ts-node').register({ project: 'e2e' });
  },
  onPrepare: function() {
    browser.manage().window().maximize();
    jasmine.getEnv().addReporter(new SpecReporter());

    const protractorImageComparison = require('protractor-image-comparison');
    browser.protractorImageComparison = new protractorImageComparison({
      baselineFolder: './e2e/imageComparison/baseline/',
      screenshotPath: './e2e/imageComparison/temp/'
    });
  },
  useAllAngular2AppRoots: true
};
```

Running my e2e tests I'm facing the problem that there is a wait time of about 30 secs each time a page is loaded via URL.

For example, I call the login page of the application with browser.get(). The page is shown in the test browser very quick and after 30 seconds the user and password is filled into the input fields.

It seems that Protractor waits for a timeout and then continues with the test execution. This is very time consuming when executing a large test suite.

When I navigate inside the application by Angular routing there is no wait time. The application I'm testing is served by the webpack dev server via "ng serve".

**Comment by wswebcreation** [comment]
Can you manual check when the app is loaded if Angular is still processing stuff?
I'm working with Angular 4 and Protractor 5.1.2 and I'm not facing the timeouts you are

By the way, as of Protractor 5 you don't need to use ` useAllAngular2AppRoots: true` anymore.

**Comment by fortunella** [comment]
I think I found the reason for this waiting time. It's caused by Firebase :-( I read the issue #4300. This is about a similar topic.

When I deactivate Firebase the tests run fine without any waitings.

**Comment by NickTomlin** [comment]
Yep, sounds like it. Let's consolidate on #4300. I'm going to close this for now.
