### ISSUE TITLE
By.js should accept function as argument

### ISSUE THREAD

**Issue by monkpit** [angular/protractor#4319]
Created PR #4308 - the [Selenium javascript bindings](https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L183) specify that a function can be passed to By.js locator, however the Protractor typescript files do not allow a function.

This PR makes Protractor's `By.js` signature match the signature used by Selenium, since `By.js` (according to Protractor docs) is inherited directly from Selenium's `webdriver.By.js`.

See relevant source here: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L183

Bug report
---

- Node Version: `7.10.0`
- Protractor Version: `5.1.2`
- Angular Version: `n/a`
- Browser(s): `n/a`
- Operating System and Version `Mac OS Sierra v10.12.5`
- Your protractor configuration file: n/a
- A relevant example test:
```
const el = element(by.js(function(){ return document.querySelector('html');}));
```
- Output from running the test:
Run this test in Protractor's Element Explorer and it works, but if you have this test written in a .TS file, the TSC compiler will complain that by.js only accepts a string.
- Steps to reproduce the bug: put the example code into a .ts file and try to compile.
- The URL you are running your tests against (if relevant): n/a

**Comment by guojunl** [comment]
I met the same issue, somebody please help with this.

**Comment by monkpit** [comment]
PR was merged - closing this issue.
