### ISSUE TITLE
Basic auth preventing page from loading

### ISSUE THREAD

**Issue by jessehonest** [angular/protractor#4320]
- Node Version: 7.8.0
- Protractor Version: 5.1.2
- Angular Version: 1.5.3
- Browser(s): Chrome 59
- Operating System and Version OSX 10.12.5

My site requires basic auth to enter. This has been running fine as I pass the credentials through the home page url. However after todays auto update to Chrome 59 this stopped working. I found if I remove the credentials from the url the page will load fine once I enter the credentials manually. 
Anyone know the possible cause/solution for this?

Thanks.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
