### ISSUE TITLE
Protractor tests failing for ng-reflect attribute

### ISSUE THREAD

**Issue by zac11** [angular/protractor#4321]
I have a bunch of Protractor tests for for e2e of a web application. There are a lot of input boxes , and a majority of them have ng-reflect-name attribute generated due to the underlying Angular4 code. Here is an example HTML snippet

  `<input _ngcontent-c6="" class="input ng-untouched ng-pristine ng-invalid ui-inputtext 
  ui-corner-all ui-state-default ui-widget" formcontrolname="email" pinputtext="" 
  placeholder="Enter Email Address" spellcheck="false" type="text" ng-reflect-name="email">`
My issue is regarding the use of locator in this. If I use this code for this specific input box -

 `element(by.css('[formcontrolname='email']'))`
and perform any `sendKeys()` operation, it works out completely fine.

However, if I use this locator

 `element(by.css('[ng-reflect-name="email"]'))`
my tests run for the successfully for the first time, but errors out giving a `NoSuchElementException` for the subsequent runs. I have searched on SO and the Angular docs, but I can't seem to explain why this happens. If anyone has faced this issue before, can you explain what is happening here?

Bug report
---

- Node Version: `v7.7.1`
- Protractor Version: `5.1.2`
- Angular Version: `Angular4`
- Browser(s): `Chrome Version 60.0.3112.20 (Official Build) dev (64-bit)`
- Operating System and Version `Mac OS X Sierra `

**Comment by NickTomlin** [comment]
Hi there, 

I'm sorry you haven't found an answer on SO but I think that is still the best venue for the question (the protractor issue queue is not for debugging / usage). 

I'm going to go ahead and close this but please feel free to respond with a link to your SO question. If you haven't already, i'd suggest sharing a small reproducible example on SO as well.
