### ISSUE TITLE
this.runnable error when trying to use afterEach

### ISSUE THREAD

**Issue by machtyn** [angular/protractor#4322]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: `v6.9.2`
- Protractor Version: `Version 5.1.2`
- Angular Version: `4.1.3`
- Browser(s): `Chrome`
- Operating System and Version `MacOS Sierra 10.12.5`
- Your protractor configuration file
test-afterEach.conf.ts
```
import { Config } from "protractor";

export let config: Config = {
    framework: 'jasmine',
    specs: [ 'test-afterEach.spec.js' ],
    useAllAngular2AppRoots: true,
    capabilities: {
        browserName: 'chrome'
    },
    jasmineNodeOpts: {
        showColors: true
    }
};
```
- A relevant example test
```
import { afterEach } from "selenium-webdriver/testing";
describe('Testing afterEach', () => {
    beforeAll(() => {
        console.log("Before All");
    });
    beforeEach(() => {
        console.log("Before Each");
    });
    afterEach(() => {
        console.log("After Each");
    });
    afterAll(() => {
        console.log("After All");
    });
    
    it('simplet test', () => {
        expect(true).toBeTruthy();
    })
});
```
- Output from running the test

> Started
> Before All
> Before Each
> FAfter All
> 
> 
> Failures:
> 1) Testing afterEach simplet test
>   Message:
>     Failed: this.runnable is not a function
>   Stack:
>     TypeError: this.runnable is not a function

**Comment by machtyn** [comment]
Ahh! There it is...
`import { afterEach } from "selenium-webdriver/testing";`

For some reason IntelliJ is inserting this import when I type `afterEach()`.
Removing this line fixes the issue

**Comment by karsunke** [comment]
Thank you! I made the exact same stupid mistake and your bug report saved me a lot of time :)
