### ISSUE TITLE
Using getAttribute to retrieve angular translate attribute returns true

### ISSUE THREAD

**Issue by rstraub** [angular/protractor#4331]
- Node Version: `8.1.0`
- Protractor Version: `5.1.2`
- Angular Version: `1.6.4`
- Browser(s): `Chrome`
- Operating System and Version `OS X 10.12.5 `
- Your protractor configuration file
```javascript
const prefix = 'e2e-tests/';
const suffix = '*.e2e-spec.js';
exports.config = {
    framework: 'jasmine',
    specs: ['e2e-tests/**/' + suffix],
    capabilities: {
        browserName: 'chrome'
    },
    baseUrl: 'http://localhost:8080',
    directConnect: true,
    onPrepare: () => {
        const jasmineReporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            consolidateAll: true,
            savePath: 'test-reports',
            filePrefix: 'e2e-test-results.xml'
        }));
    }
};
```

- A relevant example test
In a project I am working on we're using pascalprecht's angular translate: https://github.com/angular-translate/angular-translate. This library makes it possible to place an attribute with a specific key on an element which will be translated into text later on. For example:

```javascript
<p translate="something_used_to_translate"></p>
```

For a test I wrote I needed to read out this translate attribute. I expected to get back 'something_used_to_translate'. I used the following code to read out the attribute:

```javascript
expect(formErrorBlock.getAttribute('translate')).toEqual('something');
``` 
(where 'formErrorBlock' is the element already retrieved.)
I know the element is retrieved correctly because when I read out the element's other attributes they seem to be in order.

- Output from running the test
I receive the value `true` instead of 'something_used_to_translate'

- Steps to reproduce the bug
Read out the `translate` attribute from a DOM element

 I am sure the selector is correct, because when I change the getAttribute to get the id for instance, it returns the correct id. Also I can see the 'something_used_to_translate' in the DOM.

**Comment by NickTomlin** [comment]
Hi there,

Please follow the [Issue Template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) when opening new issues. Otherwise it's unclear what the issue is and how we can actually help.

**Comment by rstraub** [comment]
@NickTomlin Updated issue according to issue template.

**Comment by wswebcreation** [comment]
@rstraub 

I think this has more to do with the angular-translate module then with Protractor. I would say that Stackoverflow is a better place to ask this question (with the ['protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor)).

Having said that, how does your html look like when you get the html from the `p`-element?

**Comment by macroking** [comment]
@rstraub Eg: ` element(by.css('a.button.button-large')).getAttribute('translate')` returned `true`. 
When I changed to ` element(by.css('a.button.button-large')).getAttribute('Translate')`, it returned the actual value of the attribute

**Comment by rstraub** [comment]
@macroking Tested it and it works! I am quite curious as to why this works though...
