### ISSUE TITLE
protractor timeout issue with $http asynchronous task

### ISSUE THREAD

**Issue by mollurumca** [angular/protractor#4334]
Hi there!
My angularJS application using event-steaming and it keeps open the http event-steam request and listening server events. So my problem is when protractor start testing of my angularJS application, it keeps wait to complete event-stream http request as i am using ignoreSynchronization=false so protractor waits until it gets timeout as event-stream http request never going to finish. So i would like to teach my protractor to ignore such event-stream $http tasks and proceed testing of my application. These event-stream is implemented throughout of my application so every time there is event-stream request then protractor getting timeout.

The following error i am getting when its timeout: Failed: Timed out waiting for asynchronous Angular tasks to finish after 300 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular. The following tasks were pending: - $http: https://example.com/custom/xxx/sse

Can anyone please help me to get rid of this issue?

FYI: I am using angular 1.6 and protractor 5.x versions.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
