### ISSUE TITLE
Problem with Async Request Function

### ISSUE THREAD

**Issue by giovanihoff** [angular/protractor#4340]
- Node Version: ` v6.10.3`
- Protractor Version: ` Version 5.1.2`
- Browser(s): `IE`
- Operating System and Version `Windows 10`
- Description: **I am testing an Angular page using Protractor. But, during tests, I also need to validate a request using POST (API REST). But, I need get tokenId for later send GET with token authentication. So, I have the following codes:**

_protractor.conf.js_
`exports.config = {
  framework: 'mocha',
  frameworkPath: require.resolve('serenity-js'),
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['vmiRest.js'],
  capabilities: {
    browserName: 'internet explorer',
    chromeOptions : {
      args : ["incognito"],
      prefs: {"profile.managed_default_content_settings.images": 2}
    }
  },
  mochaOpts: {
    reporter: "spec",
    slow: 12000,
    timeout: 20000,
    ui: 'bdd'
  },
  serenity: {
    dialect: 'mocha'
  }
}`

_vmiRest.js_
`var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
var assert = chai.assert;
var expect = chai.expect;
chai.use(chaiAsPromised);
var SecurityApi = require(__dirname + '/common/restSecurityApi.js');
var Parts = require(__dirname + '/common/restParts.js');
describe('VMI - API', function() {
  var tokenId = 'none';
  var username = 'bla';
  var password = '*';
  var dealer = '112571';
  var part = '0420665R1';
beforeEach(function () {
    //
  });
it('Get Token from SecurityApi', function() {
    //
    var restSecurityApi= new SecurityApi(username, password);
    restSecurityApi.getToken(function (tokenId) {
      assert.notEqual(tokenId, null);
      console.log(tokenId);
    });
  });
  it('Test Interface getStockFullUsingGET', function() {
    console.log(tokenId);
  });
});`

_restSecurityApi.js_
`var request = require('request');
var SecurityApi = function (username, password) {
  this.getToken = function (callback) {
    var headers = {
      'X-OpenAM-Username': username,
      'X-OpenAM-Password': password,
      'Content-Type': 'application/json'
    }
    // Configure the request
    var options = {
        url: 'https://appsqa.agcoonline.com.br/SecurityApi/Token',
        method: 'POST',
        headers: headers
    }
    // Start the request
    request(options, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            var json = JSON.parse(body);
            var tokenId = json["tokenId"];
            callback(tokenId);
        }  else {
            callback(null);
        }
    })
  };
};
module.exports = SecurityApi;`

During execution, the request function return the result/response **LATE** (async), when the test ended!!! So, how can I execute request sync or respecting the order of execution???

I used promise, asyn/await, but nothing works! Please, I need a help! Thank you very much!

**Comment by giovanihoff** [comment]
Async result:
![problem](https://user-images.githubusercontent.com/5293494/27293856-ff91cfaa-54ed-11e7-887d-92e36ebc23c0.png)

Test with async/await:

> protractor
[12:52:10] I/launcher - Running 1 instances of WebDriver
[12:52:10] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[12:52:13] E/launcher - Error: C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\vmiRest.js:23
  it('Get Token from SecurityApi', async function() {
                                   ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\dev\workspace\ilegra\agco\agconline\segmentation-strategy-acceptance-test\node_modules\mocha\lib\mocha.js:230:27
[12:52:13] E/launcher - Process exited with error code 100
npm ERR! Test failed.  See above for more details.

**Comment by giovanihoff** [comment]
Please, can someone help me?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Can you please refer to your SO question here and close this issue.

Thanks!

**Comment by giovanihoff** [comment]
Ok, thank you for help. I hope the Protractor is stable, because I did not feel safe using this tool.
