### ISSUE TITLE
setScriptTimeout not timing out 

### ISSUE THREAD

**Issue by collintob** [angular/protractor#4341]
I placed this question in a closed issue, so posting fresh here.

I've placed my browser.driver.manage().timeouts().setScriptTimeout in my beforeEach, but the timeout is not respected in the test. Here's example code that counts down 15 seconds, with a supposed 10 second timeout. The test counts down all of the way through 15 seconds without stopping/timing out. Can you advise?

```
var baseFuncs = require("../../pages/ams.base.po.js");
describe('quick test - smoke 1', function () {
beforeEach(function () {
browser.driver.manage().timeouts().setScriptTimeout(10000);
baseFuncs.getBasePage("foo1");
});
it('foo - bar1', function () {
baseFuncs.countDown(15000);
});
afterEach(function () {
console.log("done with 1");
});
});

```
- Node Version: 4.4.1
- Browser(s): Chrome
- Selenium: 3.4.0

**Comment by wswebcreation** [comment]
Hi @collintob 

Which version of Protractor are you using, as of version 5.# you need to be on Node 6.# instead of 4 that you are on. You can use node version manager (if you are on Mac/Linux) to easily download and switch to a newer version.

If you upgraded would you then try again?

**Comment by collintob** [comment]
Thanks @wswebcreation. I tried your suggestions, I'm now at:

node: 6.11.0, protractor 5, selenium 3.4.0, chrome driver 2.3.

Here's my output in console. Should time out around 4 seconds left in the first spec, but it doesn't. Your help is appreciated!

```
Debugger listening on [::]:64519
(node:58860) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
launching for chrome configs
Started
launching for chrome configs
time left is: 14000
time left is: 13000
time left is: 12000
time left is: 11000
time left is: 10000
time left is: 9000
time left is: 8000
time left is: 7000
time left is: 6000
time left is: 5000
time left is: 4000
time left is: 3000
time left is: 2000
time left is: 1000
time left is: 0
done waiting
done with 1
launching for chrome configs
time left is: 4000
time left is: 3000
time left is: 2000
time left is: 1000
time left is: 0
done waiting
done with 2
.


2 specs, 0 failures
Finished in 36.028 seconds
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 passed
```

**Comment by wswebcreation** [comment]
@collintob 

Sorry for my late reaction. Did you already got this working? If not, can you also paste your  `var baseFuncs = require("../../pages/ams.base.po.js");` so I can reproduce it? 
Did you also try to add the `browser.driver.manage().timeouts().setScriptTimeout(10000);` in your `onPrepare()`.
And last, what do you expect from the `setScriptTimeout()`, that it will stop a 'it()' after 10 seconds or only a single line of code?

Grtz

**Comment by collintob** [comment]
@wswebcreation 

Unfortunately, the base file is incredibly huge. But here's the countDown function:

    this.countDown = function (millis) {
        waitTime = 0;
        waitTimer = function () {
            foo = element(by.xpath("//form"));
            foo.isPresent().then(function (isPresent) {
                if (isPresent & (waitTime < millis)) {
                    browser.driver.sleep(1000);
                    waitTime = waitTime + 1000;
                    console.log("time left is: " + (millis-waitTime))
                    waitTimer();
                } else {
                    console.log("done waiting");
                    return;
                }
            });
        }
        waitTimer();
    }

I didn't try setting the ScriptTimeout within onPrepare, because I want to assign individual timeouts to each spec, and not a global one for all specs.

I would expect the timeout would timeout the it() function, or the spec itself, and move onto the next.

**Comment by wswebcreation** [comment]
Hi @collintob ,

Again, sorry for my late response. I think I found the problem. It might that you are misunderstanding the usage of `browser.driver.manage().timeouts().setScriptTimeout(10000);`

What it does is that it can limit the time Protractor needs to wait on a async script to return it's result. Take this example

```js
describe('quick test - smoke 1', function () {
    beforeEach(function () {
        browser.driver.manage().timeouts().setScriptTimeout(10000);
        browser.get('https://www.angularjs.org/');
    });
    it('foo - bar1', function () {
        browser.driver.executeAsyncScript('setTimeout(function(){ alert("Hello"); }, 3000)');
    });
});
```

This will show the alert after 3 seconds and the test passes. If you do this

```js
describe('quick test - smoke 1', function () {
    beforeEach(function () {
        browser.driver.manage().timeouts().setScriptTimeout(1000);
        browser.get('https://www.angularjs.org/');
    });
    it('foo - bar1', function () {
        browser.driver.executeAsyncScript('setTimeout(function(){ alert("Hello"); }, 3000)');
    });
});
```

you will get this error

```bash
Failures:
1) quick test - smoke 1 foo - bar1
  Message:
    Failed: asynchronous script timeout: result was not received in 1 seconds
      (Session info: chrome=59.0.3071.115)
      (Driver info: chromedriver=2.30.477690 (c53f4ad87510ee97b5c3425a14c0e79780cdf262),platform=Mac OS X 10.12.5 x86_64) (WARNING: The server did not provide any stacktrace information)
.....
```

The example that you are providing is doing a call to your page and checks of the form element is there. This is also a async call, but the result is returned within a few milliseconds. Each time you see the logging with the counting a async call, to search for the element, has already been executed.

What I assume you want is to limit the time the method is polling for the element. This time CAN NOT be set with the `browser.driver.manage().timeouts().setScriptTimeout(10000);`.

I hope it is clear for you know. If so please close the issue. If not, also please close it and place a question on Stackoverflow.

Tnx

wswebcreation

**Comment by collintob** [comment]
Thanks @wswebcreation, I tried your suggestion with this test, but the test still takes 60 seconds to fail, instead of 5 seconds. Is browser.wait() overriding the script timeout?

```
describe('quick test - smoke', function () {
    var suiteName = this.getFullName();
    beforeEach(function () {
        browser.driver.manage().timeouts().setScriptTimeout(5000);
        browser.get('https://www.angularjs.org/');
    });

    it('foo - bar', function () {
        new_el = element(by.xpath("//span[text()='foobar']"));
        browser.wait(protractor.ExpectedConditions.presenceOf(new_el), 60000);
    });


    afterEach(function () {
    });

});

```

**Comment by wswebcreation** [comment]
Hi @collintob 

Sorry if I was not clear with my previous comment, but the `setScriptTimeout()` is only for async calls that take longer to then a specific amount of seconds. 
You are searching for an element, that is a "different" call. Your specific call is **not** influenced by the `setScriptTimeout()`. In your case the `browser.wait()` will try for 60 seconds long if the element is present. That means that if the element is not present (it will retrieve a answer within a few milliseconds), it will check it again, checks, fires again and so on. The is no open async call there.

If you don't mind I'm gonna close this issue for now. The `setScriptTimeout()` is working as it supposed to do, also from the `beforeEach`.

**Comment by NarenderKumarA** [comment]
Hi @collintob  
This is the code I'm using to wait for asynchronus calls get completed in selenium added protractor as reference 
     public static bool WaitForAngularLoad(this NgWebDriver _ngDriver)
        {
            try
            {
                _ngDriver.WaitForAngular();
                //_ngDriver.Manage().Timeouts().SetScriptTimeout(60000);
               
                return true;
            }
            catch (Exception e)
            {
                _log.WriteLine("Exception while waiting for angular load : " + e.Message, LogType.ERROR);
                return false;
            }
I'm not seeing the setscripttimeout method
