### ISSUE TITLE
Error XMLHttpRequest: Network Error 0x2ee4, Could not complete the operation due to error 00002ee4 on IE11

### ISSUE THREAD

**Issue by tamvo94** [angular/protractor#4349]
I run automation with protractor on IE11 using InternetExplorerDriver-32 bit, but I have a error:
`XMLHttpRequest: Network Error 0x2ee4, Could not complete the operation due to error 00002ee4 `
I test manually and it work well.
I think InternetExplorerDriver has any configuration because I do some actions:
- Run IE11 with InternetExplorerDriver.
- Show this error when take an action in a page.
- Terminate session.
- Open task manager and kill InternetExplorerDriver task.
- Return page and test manually and it work well.
---

- Node Version: 6.11
- Protractor Version: 5.1.1
- Browser(s): IE11 version 11.0.43 64 bit
- Operating System and Version Windows 10 64 bit
- Your protractor configuration file
```
      {
        'browserName': 'internet explorer',
        "IE_ENSURE_CLEAN_SESSION": true
      }
```

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
