### ISSUE TITLE
why no protractor tests documentation for angular 2

### ISSUE THREAD

**Issue by nikhilrayaprolu** [angular/protractor#4354]
In official angular 2 documentation for testing there is no detailed informtion for e2e testing.

**Comment by zac11** [comment]
What do you mean by "detailed information on e2e testing"?

**Comment by luskwater** [comment]
There's a mention of _Protractor_ on the [Features and Benefits](https://angular.io/features) page under **Testing**; there's a description of the `e2e/` directory as _Jasmine_ tests to be run by the _Protractor_ test runner; likewise a mention of `protractor.conf.js` in the [QuickStart](https://angular.io/guide/quickstart) guide; many mentions in the [Upgrading from AngularJS](https://angular.io/guide/upgrade) guide; and a single table entry describing _Protractor_ in the [Testing](https://angular.io/guide/testing) guide.
That _might_ be what he means by _no_ detailed information. Detailed information would be (perhaps) guidance similar to that for writing _Jasmine_ tests running under the _Karma_ runner.

**Comment by wswebcreation** [comment]
@nikhilrayaprolu and @luskwater 

What do you expect for information and where do you expect it? Do you expect 

1. Protractor to tell more about Angular 2, 
2. orAngular 2 to tell more about protractor.

If you mean 1, than we are happy to see a PR, if you mean 2 than I would say to add a PR on the Angular website. We can then also close this issue if you agree.

Tnx in advance

**Comment by luskwater** [comment]
In my **Update** above, I noted that there was a whole Protractor subdomain of `angular.io`. This has given me enough to work with at the moment.  The official Angular guides probably could do with a link saying, "Look here for more on Angular and Protractor," even if it's just pointing next door to the [_Protractor_ and _Angular_](http://protractor.angular.io/) site.

**Comment by wswebcreation** [comment]
@luskwater ,

Sorry, tnx for your reaction. Do you agree that is is sufficient and that we can close this issue?

**Comment by luskwater** [comment]
If someone with suitable privs (I'm on a billable project, and don't have time for the contributor paperwork I might need to change the docset) can just go to the _QuickStart_ guide (mentioned above) and the single entry in the _Testing_ guide, and add, 

> [Learn more about using Protractor for end-to-end testing of Angular](http://protractor.angular.io/)

to each of those mentions of _Protractor_ (on the _Angular_ side), then I'd say, "Close the issue."

**Comment by wswebcreation** [comment]
Because this is concerning adjusting documentation on a different project then the Protractor git I'm gonna close this for now. 
Feel free to add a PR on the Angular docs site to make a reference to Protractor / Add a PR to the Protractor Git if you are missing docs.
