### ISSUE TITLE
How to do sendkeys?

### ISSUE THREAD

**Issue by knursultan** [angular/protractor#4355]
![2017-06-24 13 49 56](https://user-images.githubusercontent.com/9606441/27507071-b0bc3bc2-58e9-11e7-807e-ed08f55e5594.png)
3 labels and 3 inputs with the same class, but diff label text.
I want to sendkeys to input.
```
        element(by.css('label', 'Старый пароль'))
            .then(function(){
                element(by.css('input.mm-input')).sendKeys('qwerty');
            });

```

I tried this, but it gives me error. How to solve it?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
