### ISSUE TITLE
Call XHR Post login request in executeScript doesn't set cookie from response

### ISSUE THREAD

**Issue by MaciejCiach** [angular/protractor#4356]
Hi everyone. 
I would like to login to webpage directly via REST Api. 
I have to do that as a workaround for Captcha that is on the page. 
I would like to call AJAX inside `executeScript` , I see in browser console that it is executed correctly but cookies are not saved; 

```
    var xhrString = "$.ajax('https://loginurl', {method: 'POST',data: {user: 'MyUsername', password: 'Password'}, crossDomain: true, success: function (data) {console.log(data)},})";
     browser.executeScript(xhrString).then(function () {
      browser.sleep(5000);
// At this moment I don't have cookie set
    })
```

When I call xhr directly from console then it works as expected. 
Can I achieve the same with Protractor ? 

Bug report
---
- Node Version: `7`
- Protractor Version: `5.1.1`
- Angular Version: `1.6`
- Browser(s): `OS X`
- Operating System and Version `OS X Chrome`

**Comment by wswebcreation** [comment]
Hi @MaciejCiach ,

First of all, when I run your string 
```
$.ajax('https://loginurl', {method: 'POST',data: {user: 'MyUsername', password: 'Password'}, crossDomain: true, success: function (data) {console.log(data)},});
```

directly in the console of chrome you will get an error like 
```
VM62:1 Uncaught TypeError: Cannot read property 'ajax' of undefined at <anonymous>:1:2
``` 
Looks like you are using jQuery? 
I don't think you can access it that way, you need to inject a `xhr` function, something like [this](https://www.leggetter.co.uk/2010/03/12/making-cross-domain-javascript-requests-using-xmlhttprequest-or-xdomainrequest.html) and do `browser.executeScript(functionName)`

Secondly, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by wswebcreation** [comment]
Due to inactivity I'm going to close the issue for now
