### ISSUE TITLE
"Angular could not be found on the page with angular application" while running test for angular app in iFrame

### ISSUE THREAD

**Issue by anchaltyagi** [angular/protractor#4359]
I have an angular application running inside iFrame. I must need to launch parent application URL as it provide some flag which makes angular app working as expected. Now I need to write protractor tests for angular app in iFrame. Here is the code.

describe('French page', function() {
    var IFRAME = "iframe",
        TITLE_FR = 'Découverte automatique',
        PAGE_URL = '/SAAS/admin/app/page',
        pagePaths = browser.params.paths;;

    beforeEach(function (done) {
        LOGIN_PAGE.goToPageAndLogin().then(function (){
            browser.driver.ignoreSynchronization = true;
            browser.get(PAGE_URL); // application has angular app in iFrame
            browser.sleep(5000);
            browser.waitForAngular();
            done();
        });
    });

    afterEach(function (done) {
        demoPause();
        LOGIN_PAGE.logout().then(done);
    });

    it('should be able to launch with fr-FR locale', function (done) {
        browser.driver.switchTo().frame(IFRAME); //Switch to angular app in iFrame

       // Check if element text is in french
        browser.driver.findElement(by.css('.app-menu li:nth-child(1) p')).then(function (elem) {
            elem.getText().then(function (text) {
                expect(text).toBe(TITLE_FR); // I can see that both texts are same here while debugging
                browser.driver.ignoreSynchronization = true;
                done();
            });
        });
    });
}); 

**The test condition passed but it exit with below error.**
  Message:
    Failed: Angular could not be found on the page https://host/abcd/admin/app/page : retries looking for angular exceeded

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
