### ISSUE TITLE
Click action on checkbox not working

### ISSUE THREAD

**Issue by yosserO** [angular/protractor#4360]
Hi everyone!

I'm using the protractor version 5.1.2. 
I was trying to click on some checkbox elements, but this wasn't working for any of them.
So I installed a previous version of protractor: 4.0.14. The same code worked like a charm. I was able to perform a click action on all my checkbox elements.

```
this.optionHotspotFlat = {
        root: element(by.css('[data-qa-locator="options-hotspot-flat"]')),
        getOptionSection: function(metacode) {
            return this.root.element(by.css('[data-metacode="' + metacode + '"]'));
        },
        getOptionCheckbox: function(metacode) {
            return this.getOptionSection(metacode).element(by.css('.checkbox'));
        },
        getOptionName: function(metacode) {
            return this.getOptionSection(metacode).element(by.css('[data-ng-bind-html="option.name"]'));
        },
        getOptionText: function(metacode) {
            return this.getOptionSection(metacode).all(by.css('p')).get(0);
        },
        getOptionDescription: function(metacode) {
            return this.getOptionSection(metacode).element(by.css('[data-core-bind="option.description"]'));
        }

    };
```
I tried doing:

```
detailsPage.optionHotspotFlat.root.click();
detailsPage.optionHotspotFlat.getOptionSection(option).click();
detailsPage.optionHotspotFlat.getOptionCheckbox(option).click();
detailsPage.optionHotspotFlat.getOptionName(option).click();
detailsPage.optionHotspotFlat.getOptionText(option).click();
detailsPage.optionHotspotFlat.getOptionDescription(option).click();
```
None of them worked using protractor Version 5.1.2 

Bug report
---

- Node Version: `v8.1.2`
- Protractor Version: `5.1.2`
- Angular Version: `1.4.12`
- Browser(s): `Chrome`
- The URL you are running your tests against (if relevant): https://zuhauseplus.vodafone.de/internet-telefon/kabel/internet-phone-32.html

**Comment by wswebcreation** [comment]
Hi @yosserO,

There is also a difference in the `selenium-webdriver` version between 4.0.14 (2.53) and 5.1.2 (3.0.1). 

When I try to make a simple testcase it works on my machine

```js
describe('Checkbox', () => {
    it('click on a checkbox', () => {
        browser.get('https://zuhauseplus.vodafone.de/internet-telefon/kabel/internet-phone-32.html');
        element.all(by.repeater(`option in detail.sample.ip.getSelectableOptions({},'bundle-tarif-internet-or-phone')`)).get(0).click();
        // Added the sleep here to check if the checkbox is selected
        browser.sleep(5000)
    });
});
```

Can you also verify if this l little script works on your machine?

I'm working on:

- Node Version: v7.5
- Protractor Version: 5.1.2
- Browser(s): Chrome 59.0.3071.115

**Comment by yosserO** [comment]
Hey wswebcreation!! Thank you for answering!!

This is really confusing. I updated my protractor version again to the version 5.1.2 and tested the script on my machine and it worked!
I also tested the code I wrote yesterday, and it also worked!!! I m really confused...

I'm closing this issue...

**Comment by wswebcreation** [comment]
Nice that it works. Just 1 question, did you did a "fresh" install of 5.1.2 (not global but in your project) which means also a complete fresh install of your `npm_modules`?

**Comment by yosserO** [comment]
I only installed protractor 5.1.2 globally using

npm install protractor -g

and then

webdriver-manager update

**Comment by wswebcreation** [comment]
Ok, I'm not using protractor globally, because it gave me troubles in the past. I now have it integrated in my project and that works like a charm.
