### ISSUE TITLE
[shardTestFiles] Custom params per instance does not work

### ISSUE THREAD

**Issue by lovedota** [angular/protractor#4362]
Hi there!

I am doing a Parallel Testing with Protractor. The problem is I have 3 users and I want Protractor automatically pick one free user for each instance.

```
let usersInActions = {};

const users = [
    { username: 'aaa', password: 'aaa'},
    { username: 'bbb', password: 'bbb'},
    { username: 'ccc', password: 'ccc'}
];

let config = {
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['incognito', 'disable-extensions']
        },
        maxInstances: 3,
        shardTestFiles: true
    },
    beforeLaunch: async () => {
        const capabilities = await browser.getCapabilities();
        const sesssionId = capabilities.get('webdriver.remote.sessionid');

        if (!browser.params.usersInActions) {
            browser.params.usersInActions = {};
        }

        const freeUser = users.find(u => {
            return !browser.params.usersInActions[sesssionId];
        });

        usersInActions[sesssionId] = freeUser;

        browser.params.user = freeUser;
    },
    afterLaunch: async () => {
        const capabilities = await browser.getCapabilities();
        const sesssionId = capabilities.get('webdriver.remote.sessionid');

        browser.params.usersInActions[sesssionId]  = null;
    }
};

```

- The problem is *The usersInActions always be reset everytime the new instance is called*. I believe this is the *Protractor Bug*.

**Comment by Xotabu4** [comment]
@lovedota Hi!
Problem here is that when you use shardTestFiles - you have separate NodeJS process for each thread, so your variables will exist only in that process. Your `users` and `usersInActions` variables are not global across those nodejs processes.

In case you want to share some data across nodejs processes - you have to establish some communication channel between them. I used small http server that were handling providing users to test process.

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
