### ISSUE TITLE
Error in Communicating with Remote Browser - Windows Switch

### ISSUE THREAD

**Issue by Mithun048** [angular/protractor#4365]
Hi Julie Ralph and Team,

I am getting **Error in Communicating with Remote browser** when closing an existing browser created by protractor and switching to newly created window. Below is the code snippet. Kindly help in resolving the issue.

```
browser.driver.getAllWindowHandles().then(function(handles){
	browser.driver.switchTo().window(handles[0]);
	browser.driver.close();
	browser.driver.switchTo().window(handles[1]);
});
element(by.linkText('connect')).isPresent(); // While Executing This code it throws the above error and Fails...
```

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by Mithun048** [comment]
Kindly Apologize.. Thanks.. Let me Close this...
