### ISSUE TITLE
Manual bootstrap in angular. fixed using grunt.

### ISSUE THREAD

**Issue by diptenagile** [angular/protractor#4366]
I was facing the same issue while manual bootstrapping. and found the solution to run with grunt.
used protractor version 2.5.1. 

1. Mention this in your grunt file.

```js
grunt.initConfig({
    protractor: {
        options: {
            configFile: "protractor.conf.js", // Default protractor config file
            keepAlive: true, // If false, the grunt process stops when the test fails.
            noColor: false, // If true, protractor will not use colors in its output.
            args: {
                // Arguments passed to the command
            }
        },
        e2e: {
            options: {
                // Stops Grunt process if a test fails
                keepAlive: true
            }
        }
    }
})
```

2. Install `npm install grunt-protractor-runner --save-dev` and  add for load task `grunt.loadNpmTasks('grunt-protractor-runner')`

3. Run protractor with following command : 
`grunt protractor`
or with suite name
`grunt protractor  --suite suite_name`

Please let me know if it work for you.

**Comment by wswebcreation** [comment]
@diptenagile 

Tnx for sharing your information with us. Because this isn't an issue with Protractor (current version) 
 and about usage and debugging I'm gonna close it for now.
