### ISSUE TITLE
5 second delay between e2e test executions when running against domain vs. localhost

### ISSUE THREAD

**Issue by andreas-marschke** [angular/protractor#4373]
Hi everyone!

I'm trying to use protractor/selenium for E2E tests in [Boomerang](github.com/soasta/boomerang) and tried to use locally configured domains via `/etc/hosts` to enable cookies and prevent potential localhost handling quirks in that area. During work on this issue I've come to find a problematic behaviour in protractor where execution in the E2E tests takes 5 seconds per execution. This is observable by reviewing logs made by protractor:

Assuming the following configuration in `/etc/hosts`:
```
127.0.0.1       test.local
127.0.0.1       test2.local
```

```
00-basic: 0 of 0 passed.
00-basic : Should pass 00-basic/00-onload.html ...
>> 13:05:52.360 INFO - Executing: [get: http://test.local:4002/pages/00-basic/00-onload.html])
>> 13:05:52.479 INFO - Done: [get: http://test.local:4002/pages/00-basic/00-onload.html]
>> 13:05:57.497 INFO - Executing: [find elements: By.cssSelector: #BOOMR_test_complete])
>> 13:05:57.511 INFO - Done: [find elements: By.cssSelector: #BOOMR_test_complete]
>> 13:06:02.542 INFO - Executing: [execute script: return BOOMR_test.isComplete(), []])
>> 13:06:02.550 INFO - Done: [execute script: return BOOMR_test.isComplete(), []]
>> 13:06:07.567 INFO - Executing: [execute script: return BOOMR_test.getTestFailureMessages(), []])
>> 13:06:07.573 INFO - Done: [execute script: return BOOMR_test.getTestFailureMessages(), []]
```
Notice how each execution waits 5s after DONE was logged.

This behaviour is not observable when running against localhost:
```
Runner Started.
00-basic : Should pass 00-basic/00-onload.html ...
>> 13:57:18.458 INFO - Executing: [set script timeoutt: 11000])
>> 13:57:18.466 INFO - Done: [set script timeoutt: 11000]
>> 13:57:18.493 INFO - Executing: [get: http://localhost:4002/pages/00-basic/00-onload.html])
>> 13:57:18.610 INFO - Done: [get: http://localhost:4002/pages/00-basic/00-onload.html]
>> 13:57:18.631 INFO - Executing: [find elements: By.cssSelector: #BOOMR_test_complete])
>> 13:57:18.890 INFO - Done: [find elements: By.cssSelector: #BOOMR_test_complete]
>> 13:57:18.912 INFO - Executing: [find elements: By.cssSelector: #BOOMR_test_complete])
>> 13:57:19.165 INFO - Done: [find elements: By.cssSelector: #BOOMR_test_complete]
>> 13:57:19.193 INFO - Executing: [find elements: By.cssSelector: #BOOMR_test_complete])
>> 13:57:19.448 INFO - Done: [find elements: By.cssSelector: #BOOMR_test_complete]
>> 13:57:19.473 INFO - Executing: [find elements: By.cssSelector: #BOOMR_test_complete])
>> 13:57:19.692 INFO - Done: [find elements: By.cssSelector: #BOOMR_test_complete]
>> 13:57:19.726 INFO - Executing: [execute script: return BOOMR_test.isComplete(), []])
>> 13:57:19.734 INFO - Done: [execute script: return BOOMR_test.isComplete(), []]
>> 13:57:19.749 INFO - Executing: [execute script: return BOOMR_test.getTestFailureMessages(), []])
>> 13:57:19.759 INFO - Done: [execute script: return BOOMR_test.getTestFailureMessages(), []]
Passed.
```

The e2e tests can be found here: https://github.com/SOASTA/boomerang/blob/master/tests/e2e/e2e.js

Bug report
---

- Node Version: `v7.8.0`
- Protractor Version: `1.8.0`, 
- Angular Version: `none`, we're not using Angular for the tests as we are trying to validate Boomerang instead of an Angular App
- Browser(s): `phantomjs` version: `1.9.20`
- Operating System and Version `MacOS` `Darwin hostname 15.6.0 Darwin Kernel Version 15.6.0:`

**Comment by wswebcreation** [comment]
Hi @andreas-marschke ,

Tnx for your info. I've got a few questions:

- can you explain what you mean with "_Notice how each execution waits 5s after DONE was logged.
This behaviour is not observable when running against localhost:_" Is the first logging of a cloud service and the second of a local machine?
- is there a specific reason why you are using Protractor `1.8.0`. Protractor is currently on `5.1.2`. Are you facing the same issues on the latest version (a lot has changed in the meantime)

Tnx in advance

**Comment by andreas-marschke** [comment]
Hi @wswebcreation !

As a colleague pointed out to me this might be connected with an issue in the MacOS resolver.
See: http://gotofritz.net/blog/geekery/os-x-dns-lookups-too-slow-for-local-hosts/

Updating my `/etc/hosts` file to put the test-domain onto one line with my other entries for localhost resolved this issue.

As this is not a problem with protractor but rather the underlying development environment I'm closing this issue.

Still, thanks for jumping on so quick!

**Comment by wswebcreation** [comment]
Hi @andreas-marschke 

Tnx for the update, the detailed info and closing the issue
