### ISSUE TITLE
getCssValue() doesn't work as listed in the doc

### ISSUE THREAD

**Issue by Francoyy** [angular/protractor#4380]
Hello,
I'm trying to get the CSS value without success by following the documentation for http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.getCssValue

```
it('test using getCssValue()', function(done) {
        var inputField = element(by.css("#searchBoxNew"));
        expect(inputField.getCssValue().indexOf("rgb(105, 105, 105)")).to.eventually.not.equal(-1).notify(done);
    });
```
result >>>> TypeError: inputField.getCssValue(...).indexOf is not a function

Am I not doing exactly the same as the example in the doc? I am not doing this on an angular page but a normal web page. Does that make any difference?

In comparison, here is what I have to go through to get the CSS:

```
it('test using computedStyle()', function(done) {
        var inputField = element(by.css("#searchBoxNew"));
        browser.executeScript(function (el) {
            return window.getComputedStyle(el).getPropertyValue('color');
        }, inputField.getWebElement()).then(function (color) {
            expect(color).to.equal("rgb(105, 105, 105)");
            done();
        });
    });
```

I'm attaching a screenshot of my CSS.
<img width="203" alt="screen shot 2017-07-14 at 3 53 45 pm" src="https://user-images.githubusercontent.com/218310/28203521-ae0ec0fc-68ac-11e7-868e-ab4e7b2eaa50.png">

**Comment by wswebcreation** [comment]
Hi @Francoyy 

I think this is related to [4246](https://github.com/angular/protractor/issues/4246). There is a wrong example in the docs, that needs to be fixed. A correct working example is in the issue.

Got fixing it on my list, but a new website will only be build with a new release.

As it is related to an other issue that needs to be solved I'm gonna close this one for now.

**Comment by Francoyy** [comment]
Thanks a lot!
