### ISSUE TITLE
Protractor typescript 2.4.1 

### ISSUE THREAD

**Issue by birocarol** [angular/protractor#4381]
Bug report
---

- Protractor Version: `5.1.2`
- Angular Version: 4

Using latest version of typescritp 2.4.1 results in protractor being unable to run with .

[12:25:04] I/launcher - Running 1 instances of WebDriver
[12:25:04] I/direct - Using ChromeDriver directly...
[12:25:13] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
e2e\footer.e2e-spec.ts (17,59): Argument of type 'false' is not assignable to parameter of type 'Expected<Promise<boolean>>'. (2345)

**Comment by wswebcreation** [comment]
Hi @birocarol 

Can you please provide more info about the bug. For example your: 

- config 
- `footer.e2e-spec.ts`
- your package with all the dependencies (especially the `@types`)

**Comment by birocarol** [comment]
hi you were right the issue was with types/jasmine . Thanks.

**Comment by wswebcreation** [comment]
Tnx for closing
