### ISSUE TITLE
Error message: "update-config.json" is not found

### ISSUE THREAD

**Issue by jannhendrik** [angular/protractor#4382]
Bug report
---

The problem is that protractor searches for the folder selenium (containing update-config.json) in node_modules/protractor even when I manually run node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update this folder is not created.
My current workaround is to copy that folder manually. See the error message below.

//This is where the error occurs.
let updateJson = path.resolve(SeleniumConfig.getSeleniumDir(), 'update-config.json');

- Node Version: `v7.10.0`
- Protractor Version: `5.1.1`
- Angular Version: `1.5.8`
- Browser(s): `Chrome, but general problem`
- Operating System and Version `Win7  6.1.7601 Service Pack 1 Build 760`

```
var jasmineReporters = require('jasmine-reporters');
var env = require('./e2e/environment.js');

exports.seleniumAddress = 'http://localhost:4444/wd/hub';

exports.framework = 'jasmine2';

exports.specs = ['./e2e/**/*.spec.js'];

exports.excludes = [
    './e2e/environment.js',
    './e2e/util/*',
    './e2e/**/*.po.js'
];


exports.jasmineNodeOpts = {
    showColors: true,
    defaultTimeoutInterval: 2500000
};

exports.onPrepare = function () {
    var SpecReporter = require('jasmine-spec-reporter').SpecReporter;
    // add jasmine spec reporter
    jasmine.getEnv().addReporter(new SpecReporter({
        displayStacktrace: 'all',
        displaySuccessfulSpec: true, // display each successful spec
        displayFailedSpec: true, // display each failed spec
        displaySpecDuration: true, // display each spec duration
        displaySuiteNumber: true
    }));

    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
        savePath: 'build/test-report/e2e',
        filePrefix: 'AllE2ETests'
    }));

    var ScreenshotReporter = require('./e2e/screenshotReporter.js');
    jasmine.getEnv().addReporter(new ScreenshotReporter());

    // Disable animations so e2e tests run more quickly
    var disableNgAnimate = function () {
        angular.module('disableNgAnimate', []).run(['$animate', function ($animate) {
            $animate.enabled(false);
        }]);
    };

    browser.addMockModule('disableNgAnimate', disableNgAnimate);

    browser.get(env.baseUrl + '/index.html#/');
};
```

```
'use strict';

var common = require('./protractor.common.js');
var env = require('./e2e/environment.js');
var loginUtil = require('./e2e/components/util/loginUtil.js');

// An example configuration file.
exports.config = {
    // The address of a running selenium server.
    seleniumAddress: common.seleniumAddress,
    //seleniumServerJar: '../node_modules/webdriver-manager/selenium/selenium-server-standalone-*.jar', // Make useR you check the version in the folder

    framework: common.framework,

    directConnect: false,

    //firefoxPath: 'C:/Program Files (x86)/Mozilla Firefox/firefox.exe',

    // Capabilities to be passed to the webdriver instance.
    capabilities: {
        'browserName': 'chrome',
        'chromeOptions': {'args': ['--disable-web-security']}
    },

    baseUrl: env.baseUrl,

    // Spec patterns are relative to the current working directly when
    // protractor is called.
    specs: common.specs,

    // Exclude patterns are relative to this directory.
    exclude: common.excludes,


    // Options to be passed to Jasmine-node.
    jasmineNodeOpts: common.jasmineNodeOpts,

    params: env.params,

    allScriptsTimeout: 2500000,

    //restartBrowserBetweenTests: true,

    onPrepare: common.onPrepare
};
```
`
> [14:56:44] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
> [14:56:44] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
>   at Direct.getNewDriver (C:\Projekte\...\node_modules\protractor\built\driverProviders\direct.js:63:31)
>   at Runner.createBrowser (C:\Projekte....\node_modules\protractor\built\runner.js:195:43)
>   at q.then.then (C:\Projekte\...\node_modules\protractor\built\runner.js:339:29)
>   at _fulfilled (C:\Projekte\...\node_modules\protractor\node_modules\q\q.js:834:54)
>   at self.promiseDispatch.done (C:\Projekte\...\node_modules\protractor\node_modules\q\q.js:863:30)
>   at Promise.promise.promiseDispatch (C:\Projekte\...\node_modules\protractor\node_modules\q\q.js:796:13)
>   at C:\Projekte\...\node_modules\protractor\node_modules\q\q.js:556:49
>   at runSingle (C:\Projekte\....\node_modules\protractor\node_modules\q\q.js:137:13)
>   at flush (C:\Projekte\....\node_modules\protractor\node_modules\q\q.js:125:13)
>   at _combinedTickCallback (internal/process/next_tick.js:73:7)
>   at process._tickCallback (internal/process/next_tick.js:104:9)
>   at Module.runMain (module.js:607:11)
>   at run (bootstrap_node.js:427:7)
>   at startup (bootstrap_node.js:151:9)
>   at bootstrap_node.js:542:3

**Comment by wswebcreation** [comment]
Hi @jannhendrik 

Can you please explain the steps you take when you do a fresh install of your project, how you update your webdrivers and run your test. Do you use your `package.json` for that?

**Comment by jannhendrik** [comment]
I run "webdriver-manager.cmd update" in my node_modules/.bin folder, I also tried running node_modules/protractor/node_modules/.bin

**Comment by wswebcreation** [comment]
What happens if you add this to your `package.json` in the scripts section.

```
    "webdriver-update":"webdriver-manager update"
```

This should kick of the `webdriver-manager` script that is located in the `.bin/`-folder. It should update webdriver and you can then run all.

**Comment by jannhendrik** [comment]
That was our initial configuration. And it indeed runs "node_modules/.bin/webdriver-manager update" as far as i can say. The selenium folder in "node_modules/webdriver-manager/" is created.

**Comment by wswebcreation** [comment]
Ok, 

From what I understand now is that you use we `webdriver-manager` that protractor provides to setup your server. The only thing is that it doesn't update, based on your info, the `webdriver-manager` in the right place.

This is because of the reason you are calling the update from the wrong place. There are 2 solutions.

1. First solution is to add a `npm script`, as described above, and add it after for example the `npm install`, so make a `"postinstall": "webdriver-manager update"`. It will automatically update it after the `npm install`. 
2. install `webdriver-manager` global on your machine with `npm install webdriver-manager -g`. You can then call it from the command line with `webdriver-manager update` and `webdriver-manager start` to start the server.

If you did the first you can also use `directConnect:true` in your config. It will then automatically start a selenium server for Firefox and Chrome each time you run a test. You don't need to add a `seleniumAddress: "http://localhost:4444/wd/hub"` in your config.

Based on the fact that this is more a local configuration I'm gonna close the issue for now.

**Comment by jannhendrik** [comment]
Thanks for your help. I will try this.
