### ISSUE TITLE
Quick Question on .clear() and .sendKeys()

### ISSUE THREAD

**Issue by DarthOpto** [angular/protractor#4383]
I have been reading around and would like a clear answer. 

Should I able to chain `element.clear().sendKeys()` or do I have to resolve the `.clear()` promise first? 

When I try to do the chaining I am getting a message that says:
 `Property 'sendKeys' does not exist on type 'Promise<void>'`

**Comment by wswebcreation** [comment]
Hi @DarthOpto 

You should be able to do that when you are using Javascript. Based on your provided info you are using TypeScript. 
I've also done some reading and looked into [@types/selenium-webdriver](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selenium-webdriver/index.d.ts#L4722). There you will see it returns a `Promise<void>` and you can't chain it. 
So based on the types you can't , based on "plain" Javascript you can. I understand the confusion.

@NickTomlin , is this something Protractor needs to do something with or is this more an external library thing?

**Comment by DarthOpto** [comment]
Thank you for the response, yes we are using Typescript. So it looks like I am going to be using the `.then()` to resolve the promise. Thank you for clearing that up.

**Comment by wswebcreation** [comment]
If it's clear for you know can I close the issue then?

**Comment by wswebcreation** [comment]
Going to close the issue for now.

**Comment by GarfieldDeepClone** [comment]
Why is this possible? clear() returns a Promise. Why can I call sendKeys on it?
