### ISSUE TITLE
protractor work fine with resolving promises in my localhost but return an error in Circle CI

### ISSUE THREAD

**Issue by BassemDev** [angular/protractor#4384]
Hi there!
i have a small question about how to use protractor in circle ci

**my configuration is :**
- Node Version: `6.9.1`
- Protractor Version: `5.1`
- Angular Version: `4`
- Browser(s): `chrome`
- Operating System and Version `ubuntu 16.4`
- Your protractor configuration file:

```
import { environment } from './environment';
import { browser, Config } from 'protractor';
import { SpecReporter } from 'jasmine-spec-reporter';

export let config: Config = {
  directConnect: true,
  allScriptsTimeout: 11000,
  seleniumAddress: 'http://localhost:4444/wd/hub',
  baseUrl: environment.baseUrl,
  capabilities: environment.capabilities,
  framework: environment.framework,
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },

  specs: [
    '../../build/app.spec.js'
  ],
  // This utility function helps prepare our scripts with required actions like browser maximize
  onPrepare: () => {
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
    browser.driver.manage().window().maximize();
  }
};
```

- A relevant example test:
```
import { browser, Config, element, by } from 'protractor';
import { assert } from 'chai';
describe('simple test', function() {

    beforeEach(function() {
        browser.ignoreSynchronization = true;
    });

    it('should login', function() {
        browser.get('http://localhost:8080/#/signin');
        const email = element(by.name('email'));
        const password = element(by.name('password'));
        const button = element(by.css('[type="submit"]'));
        email.sendKeys('qa-test@domain.fr');
        password.sendKeys('12345678');
        button.click();
        browser.sleep(1500);
        const logout = element(by.className('ll-navbar-icon fa fa-power-off'));
        expect(browser.getCurrentUrl()).toMatch('/dashboard');
        browser.isElementPresent(logout);
    });
});
```
- when i run this locally everything is fine and pass but when i run this on CircleCi i got this error.
<img width="946" alt="screen shot 2017-07-14 at 7 13 58 pm" src="https://user-images.githubusercontent.com/18507791/28232615-fb3d3d6e-68f1-11e7-8e5f-0d111576a502.png">

but such test pass when i use firefox with circle ci , my question then do i have any wrong configuration or maybe wrong set up ?

I remark also that when ever i start using promises , the code fail and return those error !

**Comment by NickTomlin** [comment]
Hi there!

Because it is focused on troubleshooting an issue with your continuous integration setup and not an issue with protractor itself, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
