### ISSUE TITLE
Protractor 5.1.2 not able to start chrome 59 and exits with error code 199

### ISSUE THREAD

**Issue by arshdefoamed** [angular/protractor#4391]
I am trying to run some basic tests via protractor on chrome. After I hit the command "**protractor protractor.conf.js**", the selenium server starts but chrome doesn't open. Soon "**chrome not avalaible**" error comes up. Please refer to the screenshot below:
![protractor-problem](https://user-images.githubusercontent.com/4056835/28303515-40019500-6bb1-11e7-96ad-6aeacfc8e1db.png)

However, if we check the windows task manager, there are two chrome processes that run in background. If I stop one of them then everything works fine.
![taskmanagerss](https://user-images.githubusercontent.com/4056835/28303570-84c56efa-6bb1-11e7-8e39-6a268b456020.png)

Following is my code for conf file:
``` javascript
exports.config = {
  // The address of a running selenium server.
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // The address where our server under test is running
  baseUrl : 'http://localhost:8080/MYAPP',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },
  // Spec patterns are relative to the location of the
  // spec file. They may include glob patterns.
  specs: ['*spec*.js'],

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true, // Use colors in the command line report.
	 isVerbose: true
  } ,
   onPrepare: function () {
	browser.driver.manage().window().maximize();
  } 
};
```

My system parameter are as follows:
**Node version:** 6.11.0
**Browser:** Chrome  version 59.0.3071.115 
**Protractor version:**  5.1.2
**OS:** windows

Please comment if there is further information needed.

**Comment by wswebcreation** [comment]
Hi @arshdefoamed 

Is this issue still open? I don't have a windows machine so I can't check it, but because I don't see any issue here and on the net I assume it's a local problem. Therefore I'm going to close the issue but it's still open for the discussing
