### ISSUE TITLE
Feature Request: MicrosoftEdge direct connect support 

### ISSUE THREAD

**Issue by laynelin** [angular/protractor#4395]
Feature Request
---

- Reasons for adopting new feature
We are heavily relying on Edge browser for our projects so testing in Chrome is not enough.
We don't want to introduce the dependency of JDK
- Is this a breaking change? (How will this affect existing functionality)
No.

**Comment by wswebcreation** [comment]
Hi @laynelin 

Tnx for the feature request. What do you exactly mean with "_We don't want to introduce the dependency of JDK_"?

**Comment by laynelin** [comment]
HI, @wswebcreation , 

If we want to use Edge webdriver and it's not supported by direct connect, we need to use Selenium Server will requires the JDK to be installed. We don't want to install JDK.

Thanks.
Layne.

**Comment by wswebcreation** [comment]
Hi @laynelin 

When you look at the `directConnect` option of Protractor it relies on `webdriver-manager` and the "default" drivers it downloads (chrome and geckodriver) Edge is not part of that, see also [direct.ts](https://github.com/angular/protractor/blob/master/lib/driverProviders/direct.ts) and [webdriver-manager](https://github.com/angular/webdriver-manager/blob/master/lib/config.ts).

The feature request can only be implemented when a feature request / change has been implemented in `webdriver-manager` which makes this a "third-party" feature request. 

I would advice you to place a feature request there and therefor I'm going to close the issue here

**Comment by sandipchitale** [comment]
Because new Edge(Chromium) is very chrome like....you can fake it like this:

```
exports.config = {
  multiCapabilities: [
    {
      'browserName': 'chrome',
      'goog:chromeOptions': {
        // Faked out chrome binary
        'binary': 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
      }
    }
  ],
  // Faked out chrome driver
  chromeDriver: './msedgedriver/msedgedriver.exe',
```
Make sure to download and save the correct ```msedgedriver.exe```

**Comment by ashirbad1986** [comment]
> Because new Edge(Chromium) is very chrome like....you can fake it like this:
> 
> ```
> exports.config = {
>   multiCapabilities: [
>     {
>       'browserName': 'chrome',
>       'goog:chromeOptions': {
>         // Faked out chrome binary
>         'binary': 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
>       }
>     }
>   ],
>   // Faked out chrome driver
>   chromeDriver: './msedgedriver/msedgedriver.exe',
> ```
> 
> Make sure to download and save the compatible `msedgedriver.exe`

Hi,

Thanks for the solution.
I have a query how to use EdgeOptions here, because the ChromeOtions block is not working when Edge browser is running.

**Comment by VlamisT** [comment]
> > Because new Edge(Chromium) is very chrome like....you can fake it like this:
> > ```
> > exports.config = {
> >   multiCapabilities: [
> >     {
> >       'browserName': 'chrome',
> >       'goog:chromeOptions': {
> >         // Faked out chrome binary
> >         'binary': 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'
> >       }
> >     }
> >   ],
> >   // Faked out chrome driver
> >   chromeDriver: './msedgedriver/msedgedriver.exe',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Make sure to download and save the compatible `msedgedriver.exe`
> 
> Hi,
> 
> Thanks for the solution. I have a query how to use EdgeOptions here, because the ChromeOtions block is not working when Edge browser is running.

I have the exact same issue. Any ideas?

**Comment by wswebcreation** [comment]
Move away from Protractor and use something else, see https://github.com/angular/protractor/issues/5502
