### ISSUE TITLE
Protractor hangs after click into a routerlink. 

### ISSUE THREAD

**Issue by ctyy** [angular/protractor#4396]
Bug report
---

- Node Version: v8.1.3
- Protractor Version: ~5.1.2
- Angular Version: v4.2.4
- Browser(s): Chrome
- Operating System and Version: linux 4.8.0-58-generic
- Your protractor configuration file: [protractor.conf.txt](https://github.com/angular/protractor/files/1163048/protractor.conf.txt)

- A relevant example test
I could not provide a simplified test example but I would give as much details I could of the bug producing process.

- Output from running the test: [--troubleshoot.txt](https://github.com/angular/protractor/files/1163049/--troubleshoot.txt)

- Steps to reproduce the bug

We start from a non-angular page for user to login, then it directs user to our angular page: call it activity, where we can navigate to request. Any other click event done by protractor in these pages is fine except one:

So imagine here's a list of links to all those 'request' on the left side of the page, 
`<a [routerLink]="[request.id]" [routerLinkActive]="['active']" class="list-group-item" *ngFor="let request of (requestService.request | orderBy: 'start_date': false)">` 
Then I used 
`element.all(by.css('.list-group .list-group-item')).get(0).click()` to click into the first one and  protractor did find it and made the click event successfully. 

The source code then append the 'request''s id to the current URL. For example, from 
`http://localhost:4200/#/request`  to `http://localhost:4200/#/request/xxxxxx01ac11ca4f0ea450ee0310c7e5` 
and displays its detail on that list's right side on the same page correctly. Right after that click, the protractor freezes and hangs there. 

I've modified the source code so there's no setTimeout and all http requests are running on a separate zone or it only request once or none. Currently the solution is to set `browser.ignoreSynchronization = true`, which prevent protractor from freezing. But since ignoreSynchronization leads to more troubles as it does, and stackoverflow doesn't seem to help this problem, I posted the problem here.

**Comment by ctyy** [comment]
After seeming than protractor may not be compatible with node 8.x.x, I downgraded to version 6.11.1. Problem still exists.

**Comment by wswebcreation** [comment]
Hi @ctyy ,

Tnx for the detailed issue report. You are saying that _Protractor freezes and hanges there_, what do you exactly mean with that? Do you get timeouterrors?
And does it happen on all links, or only one?

I'm currently automating a portal for customers to see all there train travels, we also use a non-angular logon and then come onto a Angular (4) portal with router links and I don't have Protractor freezing / hanging. I know it's hard, but an example project would be very nice to check out the problem.

**Comment by ctyy** [comment]
Thanks for your feedback!@wswebcreation. Yes, when talking about freeze I actually mean protractor starts waiting until it finally times out. And for question two, I guess the answer is yes: I got the error on every link I tried (Although I didn't test all of them since there are tons of them). I have included all the outputs inside the --troubleshoot.txt, just for convenient, I appended the error below:

- Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
          at ontimeout (timers.js:488:11)
          at tryOnTimeout (timers.js:323:5)
      - Failed: Timed out waiting for asynchronous Angular tasks to finish after 50 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular...

Also may I ask some more details in your case, please? Do you navigate to a new page or stays on the same page(with some updates on that page) after click on the router link?

**Comment by wswebcreation** [comment]
Hi @ctyy 

Tnx for your quick response. 

We still stay on the same page, all actions, news functionality is loaded into the same page. For example. When you are logged on you see a dashboard with your latest train travels. There are multiple links all over the page that go to new functionality. One of them is to see your travel history in a given time. When you click on that link you still stay on the same page, but a travel-history page is shown with filters to search your travels.

**Comment by ctyy** [comment]
Hi @wswebcreation 

I was thinking is it possible that time out is caused by using rxjs's combineLatest function? Although the page is done loading, protractor assumes it's still doing work?

**Comment by wswebcreation** [comment]
Hi @ctyy 

It could be, it would still be nice if we have an example repo where we can reproduce the issue and debug it.

**Comment by ctyy** [comment]
Solved, caused by an ignored type error inside the code.

**Comment by wswebcreation** [comment]
Tnx!
