### ISSUE TITLE
Why must set the webdriver.gecko.driver system property?

### ISSUE THREAD

**Issue by rkrisztian** [angular/protractor#4408]
Bug report
---

- Node Version: `6.10.3`
- Protractor Version: `5.1.2`
- Angular Version: `4.2.6`
- Browser(s): `Firefox 52.2.0 (64-bit), Google Chrome 59`
- Operating System and Version `RHEL 7`
- Your protractor configuration file: Angular CLI 1.2.0 defaults +
```
    capabilities: {
        browserName: 'firefox',
        marionette: true
    },
    directConnect: false,
    localSeleniumStandaloneOpts: {
        jvmArgs: ['-Dwebdriver.gecko.driver=/home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.18.0']
    },
```
- A relevant example test: Not needed, issue is driver-specific, and when driver is OK, tests pass.
- Output from running the test:

When I specify no `jvmArgs` in the configuration file, I get:

```
[13:54:20] I/launcher - Running 1 instances of WebDriver
[13:54:20] I/local - Starting selenium standalone server...
[13:54:24] I/local - Selenium standalone server started at http://10.20.204.182:59199/wd/hub
[13:54:25] E/launcher - The path to the driver executable must be set by the webdriver.gecko.driver system property; for more information, see https://github.com/mozilla/geckodriver. The latest version can be downloaded from https://github.com/mozilla/geckodriver/releases
```

Otherwise everything is OK and tests are executed:

```
[13:55:03] I/launcher - Running 1 instances of WebDriver
[13:55:03] I/local - Starting selenium standalone server...
[13:55:05] I/local - Selenium standalone server started at http://10.20.204.182:33088/wd/hub
Jasmine started
(...)
```

But specifying the full path to the GeckoDriver defeats the purpose of the webdriver-manager which should just provide this setting for me, including whatever version is available. I shouldn't be setting this `jvmArg` property, it doesn't make any sense. As we don't do the same with Chrome, which just works.

- Steps to reproduce the bug:

I'm using Angular CLI 1.2.0, and [the developers there provide no support in this regard](https://github.com/angular/angular-cli/issues/6924), so I came here.

**Comment by wswebcreation** [comment]
Hi @rkrisztian 

I don't have any experience with RHEL 7, but looking at the error that is thrown and the site that is shown in the error you should take a look at this

> Selenium client bindings will pick up the _geckodriver_ binary executable
from your [system’s `PATH` environmental variable](https://en.wikipedia.org/wiki/PATH_(variable))
unless you override it by setting the `webdriver.gecko.driver`
[Java VM system property](http://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html):

```java
System.setProperty("webdriver.gecko.driver", "/home/user/bin");
```

Can you please check the provided info and let us know if that works for you?

**Comment by rkrisztian** [comment]
Hi, @wswebcreation,

I hope it's clear that my real problem is that I shouldn't have to care about the `webdriver.gecko.driver` system property. Protractor should handle it somehow using the `webdriver-manager`. If I set the `jvmArg` myself, it will be a lot of scripting in `protractor.conf.js` and code duplication coming from `webdriver-manager`, just to fetch the right path.

Regardless, the following also works:

```
ln -s /home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver{-v0.18.0,}
export PATH=$PATH:/home/rkrisztian/projects/testProject/node_modules/protractor/node_modules/webdriver-manager/selenium
```

Then I don't need the `jvmArg`.

**Comment by cnishina** [comment]
I just also came to the same conclusion that this is not good. Protractor should be able to get this done. With Chrome, we let users set chromeDriver in the configuration file and the local driver will use it...if not we check the webdriver-manager/selenium folder.

Proposed idea to fix this: https://github.com/angular/protractor/issues/4411

I think I can fix this now. I've been meaning to have a distraction from writing my book.

**Comment by cnishina** [comment]
Oh good news. We have this in the config: `firefoxPath`. So I just need to use it for local. :) #suchWin

**Comment by cnishina** [comment]
Huzzah! PR in.

**Comment by wswebcreation** [comment]
Tnx @cnishina ,

Didn't saw that, sorry
