### ISSUE TITLE
Using vscode debugger is not working anymore

### ISSUE THREAD

**Issue by scenage** [angular/protractor#4410]
Bug report
---

**- Node Version:** `v.7.9.0`
**- Protractor Version:** `5.1.2`
**- Operating System and Version** `Windows 10 Pro, 64 bit`
**Launch.json**

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "cwd": "${workspaceRoot}",
            "program": "C:\\Users\\<username>\\AppData\\Roaming\\npm\\protractor",
            "args": ["${workspaceRoot}\\conf.js"],
            "outFiles": ["${workspaceRoot}/**/*.js"],
            "sourceMaps": true,
            "protocol": "inspector",
            "trace": true
        }
    ]
}
```

Alternatively, I've tried the following too:

```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}\\node_modules\\.bin\\protractor",
            "args": ["${workspaceRoot}\\conf.js"],
            "outFiles": ["${workspaceRoot}/**/*.js"],
            "sourceMaps": true,
            "protocol": "inspector",
            "trace": true
        }
    ]
}
```

**- Steps to reproduce the bug**
Setup the launch.json file and run the debugger.

VS code shows the error message: "Cannot launch program 'c:\Repos\leo.tests\node_modules\.bin\protractor'; setting the 'outDir or outFiles' attribute might help."

![image](https://user-images.githubusercontent.com/8476191/28704127-f1a2205c-73ab-11e7-9393-d9b3ecf9c222.png)

In the trace logs, I keep getting the message. I would love to use the vscode debugger as it's handy as was working! It looks like it's looking for a sourcemapURL which isn't available.

[vscode-node-debug2.txt](https://github.com/angular/protractor/files/1182116/vscode-node-debug2.txt)

Below is the message to the client from the log file:
```
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot launch program '{path}'; setting the 'outDir or outFiles' attribute might help.","body":{"error":{"id":2003,"format":"Cannot launch program '{path}'; setting the 'outDir or outFiles' attribute might help.","variables":{"path":"c:\\Repos\\leo.tests\\node_modules\\.bin\\protractor"}}}}
From client: disconnect({"restart":false})
Terminated: Got disconnect request
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

**Comment by wswebcreation** [comment]
@scenage 

Since it involves usage and debugging, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
