### ISSUE TITLE
how to close chrome.exe process after execution of all testcase with failure

### ISSUE THREAD

**Issue by gaurabhi1986** [angular/protractor#4420]
Hi !

I am using protractor 4.0 with chrome driver 2.29.

Whenever my all UI test cases finish with failure always there is chrome.exe process still running, but when all UI test cases passes that is not the case.

Can you please let e know how can I close all the chrome.exe process ?

Thanks,
Abhishek

**Comment by wswebcreation** [comment]
Hi @gaurabhi1986 

You also asked this question yesterday, see [here](https://github.com/angular/protractor/issues/4415#issuecomment-319264481). 

Please follow the advice as shown in the comment. I'm going to close it for now

**Comment by gaurabhi1986** [comment]
Hi @wswebcreation ,

Can you please give me answer of my question?

Thanks,
Abhishek
