### ISSUE TITLE
Upgrade selenium-webdriver to support headless mode

### ISSUE THREAD

**Issue by pedrro** [angular/protractor#4427]
Bug report
---
Today actual version of protractor use selenium-webdriver 3.0.1 that doesn't support run chrome on headless mode, can we update to selenium-webdriver latest version 3.4.0? 

As described on error, selenium-webdriver provide chromeDriver on version 2.20, but only version 2.3 support the headless mode of chrome.

https://developers.google.com/web/updates/2017/04/headless-chrome
`ChromeDriver 2.3.0 supports Chrome 59 and later and works with headless Chrome. In some cases, you may need Chrome 60 to work around bugs.`

- Node Version: `6.9.0`
- Protractor Version: `5.0.0`
- Angular Version: `1.5.0`
- Browser(s): `chrome (chromeless)`
- Operating System and Version `OSX Yosemite`
- Your protractor configuration file
 ```
exports.config = {
  baseUrl: 'http://localhost:8081',
  framework: 'jasmine',
  specs: ['*_spec.js'],
  seleniumPort: process.env.SELENIUM_PORT,
  seleniumArgs: ['-Djava.security.egd=file:///dev/urandom'],
  maxSessions: 3,
  multiCapabilities: [{
    'browserName': 'chrome',
    chromeOptions: {
      args: [ "--headless", "--disable-gpu", "--window-size=1600,1200" ]
    },
    'shardTestFiles': true,
    'maxInstances': 3
  }]
};
```
- Output from running the test
```
UnknownError: unknown error: unrecognized Chrome version: HeadlessChrome/59.0.3071.115
(Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
```

**Comment by pedrro** [comment]
May #4265 can fix it!

**Comment by jan-molak** [comment]
Agreed, it actually would be great to upgrade to 3.5.0; see #4451

**Comment by csvan** [comment]
+1

**Comment by csvan** [comment]
This has landed: https://github.com/angular/protractor/commit/0fbc2c0ac12992bd61712188a96aef6684bef0c1

**Comment by qiyigg** [comment]
Selenium-webdriver has already upgraded to 3.6.0. Close this issue.
