### ISSUE TITLE
sendKeys(<uppercase>) causes Chrome 62 to show it's About page

### ISSUE THREAD

**Issue by scottohara** [angular/protractor#4430]
Bug report
---

- Node Version: `8.2.1`
- Protractor Version: `master (4b7cada)`
- Angular Version: `2.2.1 (as specified in /testapp/package.json)`
- Browser(s): `Chrome 62.0.3175.4 (Official Build) dev (64-bit)`
- Operating System and Version `macOS 10.12.6`

### Background
I was experiencing an issue in my own app's test suite, where certain tests would cause Chrome to open `chrome://settings/help` in a new tab.

It appears that calling `sendKeys()` and passing **any upper case characters** is causing this.

To be sure that the problem wasn't isolated to my own code, I was able to reproduce the same issue using protractor's own test suite as follows:

### Setup
1. Clone the protractor repo (`git clone https://github.com/angular/protractor.git`) (latest `master`, as at commit 4b7cada)
2. Install (`npm install && webdriver-manager update && webdriver-manager start`)
3. Start the test app (`npm start`)

### Demonstrate the issue
For a reduced test, I wanted to only execute the specs in `basic/elements_spec.js`.

I wasn't 100% sure how to limit the specs that run, so I hacked the following:
a. In `scripts/test.js`, comment out everything so that only `spec/basicConf.js` is executed
b. In `spec/basicConf.js`, change the specs pattern to only include `basic/elements_spec.js`

Run the test suite (`npm test`).

**Expected outcome**: The two tests in `elements_spec.js` that call `sendKeys('Jane')` cause Chrome to open `chrome://settings/help` in a new tab.

### Demonstrate the cause
In `spec/basic/elements_spec.js`, modify the two instances of:
a. `sendKeys('Jane')` to `sendKeys('jane')`
b. `expect(name.getText()).toEqual('Jane');` to `expect(name.getText()).toEqual('jane');`

(i.e. change the uppercase J to lowercase J)

Run the test suite (`npm test`).

**Expected outcome**: The `chrome://settings/help` tab no longer opens.

I'm unsure whether the issue lies with either:
* Node 8
* Chrome 62
* webdriver / chomedriver 2.31
* Protractor 5.1.2

**Comment by wswebcreation** [comment]
Hi @scottohara 

Tnx for logging the issue. I'll try to reproduce it when I'm online.

Based on the specs I would say it's a Chromedriver issue, also because 2.31 only supports version 58-60, 61 and 62 are not mentioned.

What happens if you downgrade to 60?

**Comment by scottohara** [comment]
Hi @wswebcreation,

You're absolutely right...I found [this issue](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1896#c1) (now [fixed](https://chromium-review.googlesource.com/c/585651)) in Chromedriver, that mentions:

> And typing character '#' opens a new tab with 'chrome://settings/help' page.

From the patch, it looks like they were sending a `nativekeyevent` that was causing this.

Will wait for the next release of Chromedriver to confirm if fixed; and I'll close this issue.

**Comment by wswebcreation** [comment]
@scottohara 

Tnx for referring to the issue and closing this one.
