### ISSUE TITLE
Testing framework design breaks SOLID principle for simplicity

### ISSUE THREAD

**Issue by megamindbrian** [angular/protractor#4435]
Hi there!

1. Done.
2. I am not asking a usage question
3. Please see description below.
4. Done.
5. Deleted the intro.  Done.

Bug report
---

- Node Version: `7.7.2`
- Protractor Version: `5.1.2`
- Angular Version: `4.1.3`
- Browser(s): `Chrome`
- Operating System and Version `Windows/Mac`
- Your protractor configuration file - Default config built in to angular-cli
- A relevant example test
From the docs:
```
describe('BannerComponent (inline template)', () => {

  let comp:    BannerComponent;
  let fixture: ComponentFixture<BannerComponent>;
  let de:      DebugElement;
  let el:      HTMLElement;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ BannerComponent ], // declare the test component
    });

    fixture = TestBed.createComponent(BannerComponent);

    comp = fixture.componentInstance; // BannerComponent test instance

    // query for the title <h1> by CSS element selector
    de = fixture.debugElement.query(By.css('h1'));
    el = de.nativeElement;
  });
});
```

- Output from running the test
Test passes!
- Steps to reproduce the bug
Here's the meat of the issue; let's say, hypothetically, I want to use ngx-translate in my component.  I add the module, and I don't have to test someone else's library because it's already tested, so I create a stub.
```
describe('BannerComponent (inline template)', () => {

  let comp:    BannerComponent;
  let fixture: ComponentFixture<BannerComponent>;
  let de:      DebugElement;
  let el:      HTMLElement;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [ BannerComponent ], // declare the test component
      providers: [
        {
           provide: TranslationService,
           useClass: TranslationServiceStub
        }
      ]
    });

    fixture = TestBed.createComponent(BannerComponent);

    comp = fixture.componentInstance; // BannerComponent test instance

    // query for the title <h1> by CSS element selector
    de = fixture.debugElement.query(By.css('h1'));
    el = de.nativeElement;
  });
});
```
This makes perfect sense to me.  I've added my translation stub.  Great! 
Here is my issue: When I an using the Angular framework, I abstract this provider in to my module, specifically for the very reason that I DON'T have to write the two lines above in every single component.  There is 1 module, and 1 translation service provided for the entire module.  Why then, do I have to include the stub TranslationService in every spec'ed out component that I am testing?  I am told the following example is an incorrect usage of this testing framework.
```
describe('BannerComponent (inline template)', () => {

  let comp:    BannerComponent;
  let fixture: ComponentFixture<BannerComponent>;
  let de:      DebugElement;
  let el:      HTMLElement;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [TranslationModule],
      declarations: [ BannerComponent ], // declare the test component
    });

    fixture = TestBed.createComponent(BannerComponent);

    comp = fixture.componentInstance; // BannerComponent test instance

    // query for the title <h1> by CSS element selector
    de = fixture.debugElement.query(By.css('h1'));
    el = de.nativeElement;
  });
});
```
With this example, I am importing the TranslationModule and expecting it to act normally (which it doesn't).

This is my problem with this framework.  Why do I need to write twice as much code in order to test my working angular code?  Please fix this issue.

Feature Request

- Reasons for adopting new feature
Please stop creating nuanced testing frameworks.
- Is this a breaking change? (How will this affect existing functionality)
Yes, everything you are doing is wrong and should be broken in order to create something new that is better.

**Comment by NickTomlin** [comment]
This looks like a unit test, not an integration test. Typically those are run using karma + a front end testing framework and not through protractor. 

I'd look at the [angular and angular.js google groups](https://groups.google.com/forum/#!forum/angular) as a way of discussing this further. If you do have an issue with protractor and how it relates to testing, you're more than welcome to contribute to the project with a pull request that makes things better.

I'm going to go ahead and close this. I hope those other venues provide a productive way forward for you. Thanks! 😄

**Comment by megamindbrian** [comment]
Thanks.  There isn't really a good place to discuss design decisions because as soon as someone questions the design, they are redirected somewhere else.  I am holding you all responsible for this mess.  Karma test runner is no longer maintained.
