### ISSUE TITLE
How to choose Chrome User Profile before a test (e2e)?

### ISSUE THREAD

**Issue by Natanael1234** [angular/protractor#4439]
I would like to choose Chrome user profile to test my app (Ionic 3 PWA) so that I can do login mannually before run the tests. . The app tests are based on the [ionic-unit-testing-example](https://github.com/ionic-team/ionic-unit-testing-example) which uses protractor.

In the way it works today it opens a new user profile which only exists during the test execution.

How to choose Chrome User Profile before a test (e2e)?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
