### ISSUE TITLE
Protractor-Cucumber test steps passes before executing the step

### ISSUE THREAD

**Issue by vsaharoy** [angular/protractor#4442]
Hi,
 below is my step definition file and also i am new to protractor-cucumber. When i am running the config file it is showing all the step def with green colour  i.e. passed and after the driver opens and rest of the step is executed, i am not able to figure out why it is happening. please help.

//features/step_definitions/my_step_definitions.js

module.exports = function() {
 
this.Given(/^I go to page$/, function() {
    browser.ignoreSynchronization = true
    browser.driver.manage().window().maximize();
    browser.get("http://toolsqa.com");
    
  
  });
 this.When(/^I enter text in textbox$/, function() { 	  
	 
	 element(by.xpath('.//*[.="Enroll Your Self"]')).click();
	
	 
  });
 
 this.When(/^I enter text in angular$/, function() { 	
	 
	 element(by.xpath(".//input[@name='your-name']")).sendKeys("abc");
	 element(by.xpath(".//input[@name='your-email']")).sendKeys("abc");

 });
}

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
