### ISSUE TITLE
Why do we need webdriver-manager start?

### ISSUE THREAD

**Issue by smajazayeri** [angular/protractor#4446]
Hi there!

In order to run my unit tests against IE, I just run protractor without running the `webdriver-manager start`. According to the existing online docs (such as [here](https://stackoverflow.com/questions/30395011/is-webdriver-manager-start-necessary)), we should run selenium server before running tests on browsers except Chrome and Firefox, 
Do you know how my does protractor work which doesn't need the selenium server?

**Comment by NickTomlin** [comment]
The short answer is that you don't, protractor will [start a selenium server for you](https://github.com/angular/protractor/blob/4b7cada1317079c20ddf1bb105303e21adba6e32/lib/driverProviders/index.ts#L51-L54) by default. As long as you've `webdriver-manager update`d.

That said, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by smajazayeri** [comment]
Thanks Nick. I followed your advice in here: https://stackoverflow.com/questions/45685308/do-we-really-need-to-run-webdriver-manager-start-before-running-protractor/45685328#45685328
