### ISSUE TITLE
Upgrade to Jasmine 2.7 or 2.8

### ISSUE THREAD

**Issue by mwsessom** [angular/protractor#4464]
Protractor is using a rather old version of Jasmine that's preventing one from using the latest JavaScript features such as async/await.

```
xit("skipped async test", async => {
  //Jasmine 2.5.3 throws exception
  //Jasmine 2.8 works
})
```

**Comment by qiyigg** [comment]
This shouldn't prevent you from using Jasmine 2.8, will it?
My understanding is that ^2.5.3 just indicates 2.5.3 <= jasmine version < 3.0.0.

**Comment by qiyigg** [comment]
pin jasmine version to 2.8 for compatibility issue
#4669
close this issue.
