### ISSUE TITLE
Ability to use different seleniumAddresses for each shard instance

### ISSUE THREAD

**Issue by aaronyoungkash** [angular/protractor#4466]
Our testing uses vnc recording of selenium's screens to record test runs. Playing with the sharding feature I was able to parallelize the execution nicely, however the recorded video isn't very helpful as all the runs occur in the same selenium server and thus it's only recording the top Chrome instance. It would thus be nice if there was a way to use a separate Selenium instance for each shard, unless there's already a nice way to do something like this.

**Comment by NickTomlin** [comment]
There isn't currently a way to do this through the config and It's not something we are actively planning on bringing into core. 

I wonder if there's a way to configure VNC or another utility to handle multiple instances for your recordings?

I'm going to go ahead and close this; good luck in your search!
