### ISSUE TITLE
Modal page pops-up and dis-appears while running tests

### ISSUE THREAD

**Issue by smahalingam** [angular/protractor#4468]
Modal window appears and dis-appears while running test from protractor. But modal everything works fine when doing manually ie., modal screen stays

  Protractor version : 5.1.2
  Browser            : Chrome
  Node version       : v7.4.0
  OS                 : Mac OS
  Angular version    : 1

  1. Start the element explorer - ```protractor --baseUrl https://betastar:valkyrie@test2.quantumwings.com --elementExplorer```
  2. Login using et@pp.co/Test1234 and PIN '111'
  3. browser.get('https://test2.quantumwings.com/properties/UKBN21QA001/quote')
  4. Manually - Enter the amount as 1 in 'How much' field | Click 'Continue' button
  5. Manually - Accept the terms & conditions | Click "BUY" button

  Actual:
  Modal window appears and dis-appears quickly. ie., It does not stops

  Note: Modal page is not stays fow following case,
  1. Start the element explorer - ```protractor --baseUrl https://betastar:valkyrie@test2.quantumwings.com --elementExplorer```
  2. Login using et@pp.co/Test1234 and PIN '111'
  3. Manually - Open https://test2.quantumwings.com/properties/UKBN21QA001/quote
  4. Manually - Enter the amount as 1 in 'How much' field | Click 'Continue' button
  5. Manually - Accept the terms & conditions | Click "BUY" button

  Actual: Modal page is pops-up and stays untill close by user

Any help would be appreciated. 

Thanks,
Shan

**Comment by aravindhanarjunan** [comment]
I have tried this.....but me too receiving the same error.....modal stays during manual....bt it not sleeps while automation testing....

**Comment by balaspace** [comment]
i could get it to work in the interactive mode, but not when running using a config file .. i.e

1. open the interactive mode `./node_modules/protractor/bin/protractor --elementExplorer --baseUrl https://betastar:valkyrie@test2.quantumwings.com`
2. then i logged in manually as the user
3. then i did `browser.get('https://test2.quantumwings.com/properties/UKBN21QA001/quote')`
4. then i filled in all the details manually
5. finally on the review page i did `element(by.buttonText('Buy')).click()` and the page stops at the modal
6. but the same when i kick off the test using a config file it does not stop in the modal `./node_modules/protractor/bin/protractor config.js`

**Comment by NickTomlin** [comment]
This sounds like a timing issue; i'd suggest using StackOverflow to explore some different solutions and opening another issue with an small reproducible example if you believe this is an issue with Protractor itself and not a selenium quirk.
