### ISSUE TITLE
Why do the examples not show any use of Promises?

### ISSUE THREAD

**Issue by brandonros** [angular/protractor#4469]
https://github.com/angular/protractor/blob/master/example/example_spec.js

```
describe('angularjs homepage', function() {
  it('should greet the named user', function() {
    browser.get('http://www.angularjs.org');

    element(by.model('yourName')).sendKeys('Julie');

    var greeting = element(by.binding('yourName'));

    expect(greeting.getText()).toEqual('Hello Julie!');
  });

  describe('todo list', function() {
    var todoList;

    beforeEach(function() {
      browser.get('http://www.angularjs.org');

      todoList = element.all(by.repeater('todo in todoList.todos'));
    });

    it('should list todos', function() {
      expect(todoList.count()).toEqual(2);
      expect(todoList.get(1).getText()).toEqual('build an AngularJS app');
    });

    it('should add a todo', function() {
      var addTodo = element(by.model('todoList.todoText'));
      var addButton = element(by.css('[value="add"]'));

      addTodo.sendKeys('write a protractor test');
      addButton.click();

      expect(todoList.count()).toEqual(3);
      expect(todoList.get(2).getText()).toEqual('write a protractor test');
    });
  });
});
```

Aren't most of these calls supposed to be treated as async and chained with Promises?

**Comment by brandonros** [comment]
Update: I found this https://github.com/angular/protractor/blob/master/docs/control-flow.md, which is kind of disheartening. Apparently, the expect() framework of Jasmine knows to wait to resolve Promises... kind of "magic" for first timer examples.

One step further in a different direction: can an example be shown to handle a rejected Promise?

As far as I can tell:

```
it('should reject', function() {
  Promise.resolve()
  .then(function() {
    throw new Error('Good bye');
  });
});
```

This test will still pass (when it should really fail), and instead this will be shown: 

`UnhandledPromiseRejectionWarning: Unhandled promise rejection ...`

Am I doing something wrong?

**Comment by NickTomlin** [comment]
Agreed that the control flow is confusing and magical. The original intent was to save users the overhead of worrying about promises, but the general consensus is it makes things _more_ complicated.

Your example will work if you return the promise from your test:

```javascript
describe('protractor/jasmine', function() {
  it('it should handle promise rejections', function () {
    return Promise.resolve()
      .then(function () {
        throw new Error('test')
      })
  });
});
```

Generally trying to mix vanilla promises with the control flow is not a very fun adventure, so i'd suggest leaning on the "magic" of jasmin2wd whenever possible unless you are disabling the control flow entirely.


In the future, please also ask usage/debugging questions on StackOverflow; the issue queue is meant to focus on bugs/improvements to protractor's core.

Thanks!
