### ISSUE TITLE
protractor is doing nothing (or hangs)

### ISSUE THREAD

**Issue by Gobliins** [angular/protractor#4470]
I have done  everything from this tutorial http://www.protractortest.org/#/tutorial

i have created a protractor.config.js:

`exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4455/wd/hub',
  specs: ['../tests/protractor/spec.js'],
}`

these are my selenium hub and chrome node:

`f039451f8e72        selenium/node-chrome:latest   "/opt/bin/entry_point"   About a minute ago   Up About a minute                                      tender_panini
a4df1462a3d7        selenium/hub:latest           "/opt/bin/entry_point"   2 minutes ago        Up 2 minutes        4444/tcp, 0.0.0.0:4455->4455/tcp   selenium-hub
` 

and this is whats happening:

`./node_modules/.bin/protractor tests/config/protractor.conf.js \n
[16:01:28] I/launcher - Running 1 instances of WebDriver
[16:01:28] I/hosted - Using the selenium server at http://localhost:4455/wd/hub
`
and nothing more

What could be the reason?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
