### ISSUE TITLE
Regular expression with Pipe symbol is not working for the node grep options in protractor for windows operating system

### ISSUE THREAD

**Issue by npurnpau** [angular/protractor#4474]
Bug report
---

- Node Version: `v6.9.0`
- Protractor Version: `5.1.2`
- Angular Version: `1.6.4`
- Browser(s): `All`
- Operating System and Version `Windows 7 enterprise`
- Your protractor configuration file 
- A relevant example test
When I send the regular expression from the command prompt which contains pipe in windows , It is throwing an exception like below 

`gulp e2e -s <servername> -g "TCID:62274|TCID:64575"`

Error: 
```shell
############## [ '--jasmineNodeOpts.grep',
  'TCID:62274|TCID:64575',
  '--baseUrl',
  'http://servername:/mp' ]
The filename, directory name, or volume label syntax is incorrect.
{ [Error: protractor exited with code 255]
  message: 'protractor exited with code 255',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
```

How ever I am able to execute this pattern by hard coding jasmineNodeOpts grep in protractor.config.js file like below, Only specified test cases are executed.

```js
  "jasmineNodeOpts": {
        "showColors": true,
        "defaultTimeoutInterval": 60000
        "grep":'TCID:62274|TCID:64575'
    }
```
- Output from running the test

Error: 
```shell
############## [ '--jasmineNodeOpts.grep',
  'TCID:62274|TCID:64575',
  '--baseUrl',
  'http://servername:/mp' ]
The filename, directory name, or volume label syntax is incorrect.
{ [Error: protractor exited with code 255]
  message: 'protractor exited with code 255',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)
```

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by wswebcreation** [comment]
Hi @npurnpau 

Can you please fill in the form ;-). The title itself is not helpful

**Comment by npurnpau** [comment]
@wswebcreation Updated the STR, Please let me know for any other information.

**Comment by wswebcreation** [comment]
Hi @npurnpau 

This is more a Windows thing than a Protractor thing. Windows parsers the arguments differently than Linux.

For example, in my previous project we needed to pass some command line arguments and it worked differently on a Mac than on Windows

```bash
# Mac: 
grunt protractor:subtask --arg='[{"environment": "browserlab", "browserName":"chrome"}]'
# Windows (escape): 
grunt protractor: subtask --arg="[{\"environment\": \"browserlab\", \"browserName\":\"chrome\"}]"
```

Since it involves usage and debugging, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
