### ISSUE TITLE
Support question - recommended TAP reporter to use with Protractor

### ISSUE THREAD

**Issue by ORESoftware** [angular/protractor#4476]
Simple question for y'all - I am looking for a good TAP reporter than I can use with Protractor (with Jasmine or Mocha) so that I can get TAP output from each protractor process.

I found this:
https://github.com/larrymyers/jasmine-reporters

is that one recommended or is there a better one?

Please advise, thanks!

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by ORESoftware** [comment]
thx
