### ISSUE TITLE
running protractor as a script in package.json gives an error after tests are executed

### ISSUE THREAD

**Issue by afaqi** [angular/protractor#4477]
Hi, 

We recently decided to control easy installation of protractor on local machines (by specifying it in package.json) instead of installing individually with -g flag. So addition is something like this

_"scripts": {
    "protractor": "protractor protractor.config.js --directConnect"
}_

After that when I try to execute protractor using
npm run protractor

It gives following console error after running tests. 
--------------------------------------------------------------------------------------------------------------
_npm ERR! Failed at the @ protractor script 'sudo protractor protractor.config.js --directConnect'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself._
.....
....
--------------------------------------------------------------------------------------------------------------
Running protractor using following command works fine.
_node_modules/protractor/bin/protractor protractor.config.js --directConnect_

Also it works ok if protractor is installed as global package and run as below
_protractor protractor.config.js --directConnect_

Only problem that running it as scripts always gives errors after tests run is finished.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
