### ISSUE TITLE
Test not exitting with code > 0, when using TAP reporter

### ISSUE THREAD

**Issue by ORESoftware** [angular/protractor#4479]
So when I use the default dot reporter, everything works.
When I disable the dot reporter and and use the TAP reporter from `require('jasmine-reporters');` then the exit code will be 0, even with a failing test case.

In detail, when I change the protractor.conf.js file:

```js
 onPrepare: function () {
    let env = jasmine.getEnv();
    env.clearReporters();    // disable dot reporter
    env.addReporter(new jasmineReporters.TapReporter());
  },
```

now all my tests will exit with code 0, even if there is a test case failure.

**Comment by wswebcreation** [comment]
Closing this one in favour of https://github.com/angular/protractor/issues/4575

**Comment by ORESoftware** [comment]
Ok cool, any thoughts on #4575 ?
