### ISSUE TITLE
Invalid timeout 'script' - Android Native

### ISSUE THREAD

**Issue by josepmc** [angular/protractor#4486]
This is basically a copy of https://github.com/appium/appium/issues/8465.

## Environment
- Node Version: `8.4.0 (Not Relevant)`
- Protractor Version: `5.1.2`
- Appium Version: `1.6.5`
- Operating System and Version `Android Emulator (API 25) - Any version affected`

## Issue
When trying to use protractor to launch a native android application, Appium will throw the following error 
`Error: WebDriverError: An unknown server-side error occurred while processing the command. Original error: Invalid timeout 'script'`. This doesn't occur on iOS native applications.

## Details
The problem occurs due to this line: https://github.com/angular/protractor/blob/c525ca6b277a6a8fea43632ae493c13999cddc94/lib/runner.ts#L281

Setting scripts timeout is not supported in Android (Appium). You would normally overcome this issue by setting `Autowebview: true` in the capabilities (when using a Hybrid application).
However the problem arises when trying to launch a Native application that doesn't have a Webview to hook to. The exception occurs too early in Protractor's initialization and it causes an instant crash.
Adding a catch statement or commenting that line altogether will allow protractor to fully initialize and work without issues.

## Steps to Reproduce
To reproduce the problem, you need to:
- webdriver-manager update --android
- webdriver-manager start --android
- Grab an 'apk' and set the absolute path to the 'app' capability in the following config.
```
{
        seleniumAddress: 'http://localhost:4723/wd/hub',
        capabilities: {
            platformName: 'android',
            platformVersion: '7.1',
            deviceName: 'Nexus 6P',
            browserName: '',
            //autoWebview: true, // This would 'solve' the issue if it was a hybrid application
            app: <app package name>
            //autoWebviewTimeout: 4000
        },
        specs,
        useAllAngular2AppRoots: true,
        jasmineNodeOpts: {
            showColors: true,
            defaultTimeoutInterval: 300000
        },
}
```

**Comment by wswebcreation** [comment]
Hi @josepmc 

Protractor only supports browsers (desk / mobile) see [docs](https://github.com/angular/protractor/blob/23478f520e47db2eb7b7bcf3ef890774bfc77cc8/docs/mobile-setup.md), it doesn't support Native automation. I know supporting iOS Safari is on the roadmap, but this is still browser and not native app.

I also do wonder if Protractor is the right tool to do the native automation, there are a lot of alternatives do do this better, but that's my humble opinion.

Gonna close this for now.

I'm going to close it for now

**Comment by josepmc** [comment]
Relating to whether it's a good tool or not, well in the case you have a native application that uses a bunch of Webviews with Angular then yes.
I wonder we'll need to fork then.
