### ISSUE TITLE
Unable to hover over element on Firefox

### ISSUE THREAD

**Issue by BillalPatel** [angular/protractor#4487]
Hi there,

I have a test that is working perfectly fine on Google Chrome; however, it is not working whatsoever on FF. 

The code looks something like this:
`browser.driver.actions().mouseMove(element)).perform();` - If you need the specific element details and URL then just let me know.

When running in FF, it doesn't seem to recognise 'mouseMove'. Like I say, this exact same test is not an issue for Chrome.

Thanks,
Billal

**Comment by wswebcreation** [comment]
@BillalPatel 

This issue is _double_, see https://github.com/angular/protractor/issues/4177, I'm going to close this for now
