### ISSUE TITLE
Auto scroll and click breaks with Chrome v61?

### ISSUE THREAD

**Issue by uscengineer** [angular/protractor#4490]
- Node Version: `7.7`
- Protractor Version: `5.1.2`
- Angular Version: `1.5.3`
- Browser(s): `Chrome v61`
- Operating System and Version `OSX 10.12.6`

I was using regular element.click() which would scroll to the element and then click. With Chrome v61 I started getting a bunch of failures. After some troubleshooting I discovered that the scrolling was no longer happening. I ran the same tests on the same app with both versions(60,61) and it only breaks with Chrome v61.

For now I have a temp solution to add scrolling but was hoping there is a fix going forward.

Thanks.

**Comment by wswebcreation** [comment]
Hi @uscengineer

I think it's related to Chronedriver instead of Protractor. See The changelog https://sites.google.com/a/chromium.org/chromedriver/downloads

Looks like it would be fixed in Version 2.32, but I wonder if this is really fixed

**Comment by uscengineer** [comment]
Thanks @wswebcreation

I am using chromedriver 2.32 so I guess it is not fixed. 
Since it is chromedriver related I will close this.

**Comment by wswebcreation** [comment]
@uscengineer 

Tnx for the feedback. I think it is related to this https://bugs.chromium.org/p/chromedriver/issues/detail?id=2015&q=&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary
