### ISSUE TITLE
strategy for shard describes (vs specs/files)  to allow adaptative test / generalizations

### ISSUE THREAD

**Issue by gustavomick** [angular/protractor#4491]
Hi team, thanks for your work, i know this is not an issue per se, but is related to sharding configuration strategy, and test efficiency.

our requirement is executing multiple times same spec but using variants of input parameters. The most simple example is to execute with sharding login spec using different users / roles.

currently i have something similar to this

```
users.map((key) => {
    describe(key + ' - authentication ', () => {
.....
..... adaptative tests upon users (or other context inputs)
.....
      })
})
```
issue here is that we need to run all those sequentially, others issues like retry and sharding by suites i can workaround some how, but i am not seeing other solution here but 
A to wrap protractor flake to run same file with different parameters, but that's kind of braking this clean sharding solution.
B create a spec per entity and call a helper, but that's is not a long term viable solution if when we have flexible test for like dozen+ workflows. 

any thoughts or doc reference will be much appreciated. 

Thank you.

**Comment by wswebcreation** [comment]
Hi @gustavomick 

As you also mention it's not an issue per se, but this issue log on git is for issues. 
Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


I'm going to close this issue now, but it's still open for discussion. 

If I look at your question and your example of the login spec I wonder why you need to test a login with different roles? Are you connected to real services and can you only test is then, or can you mock it making this less depending on each other?

**Comment by gustavomick** [comment]
@wswebcreation thanks, i gonna ask on stack thou i think i need a feature that may be is no there yet.

our system allows to customize / design entities, so,  to allow to test different customizations i created those tests with a very basic adaptability logic, they consider inputs parameters like json configs (that describes those tests) and create simple execution steps to cover all of them.

specific for the users scenario mentioned above, bc each role has a customized dashboard, i check which "dashboard/settings" are rendered for each main role on each main scenario.

**Comment by wswebcreation** [comment]
@gustavomick 

Does that mean that the output of the services define the "dashboard / settings" ?

**Comment by gustavomick** [comment]
yes

**Comment by wswebcreation** [comment]
Ok, do you really need to use the services or can you mock them? For example, I'm using [ng-apimock](https://github.com/mdasberg/ng-apimock) and an example implementation can be found here http://www.wswebcreation.nl/mocking-angular-and-angularjs-applications/

It's really easy to use and it will isolate my frontend so I can test it how it should be tested ;-)

**Comment by gustavomick** [comment]
Hey sorry to say but, I m not seeing how this resolves/breaks secuenciality on sharding scenarios restricted currently per file (vs per describe). Could you elaborate a little, thanks!

**Comment by wswebcreation** [comment]
With mocking your services you are not depending on (test)data and you can run in paralel to make your tests more efficient and faster

**Comment by gustavomick** [comment]
Ahh well we really use these not only for ui test, but primary for end 2 end test.. i cant use mocking only on units. Thanks
