### ISSUE TITLE
Invalid timeout type specified

### ISSUE THREAD

**Issue by jared-ziqxu** [angular/protractor#4500]
No need for help! It's solved after I downgrade also the IEWebdriver.exe. Thank you!

Bug report
--- all my test code running well on selenium grid 2.X, when I upgrade my selenium grid to 3.5.3
It reports 'Invalid timeout type specified: ms' with IE but works well with Chrome.
did a bit google, other people also came across this and suggested to downgrade selenium to 3.4.0 as:
https://github.com/angular/protractor/issues/4445, so I followed to do so, but now it reports:
'Invalid timeout type specified: page load'

- Node Version: `3.4.0` && '3.5.3'
- Protractor Version: `5.1.2`
- Angular Version: `1.3.13`
- Browser(s): `IE11`
- Operating System and Version `windows7`
- Your protractor configuration file

exports.config = {
  allScriptsTimeout: 60000,

  capabilities: {
    browserName: 'internet explorer'
  },

  maxSessions: 1,
  framework: 'jasmine2',
  jasmineNodeOpts: {
    isVerbose: true,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 120000
  }
}
- A relevant example test

- Output from running the test
 E/launcher - Error: WebDriverError: Invalid timeout type specified: page load
Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
System info: host: 'SELENIUM-WIN7-B', ip: '192.168.0.164', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.ie.InternetExplorerDriver
Capabilities [{acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0.0, ie.ensureCleanSession=false, elementScrollBehavior=0.0, enablePersistentHover=false, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=true, initialBrowserUrl=http://localhost:31865/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, javascriptEnabled=true, platformName=windows, setWindowRect=true, platform=ANY}]
Session ID: 6ccd03ad-c507-4fc2-aa26-8a26dea44980
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.manage().timeouts().pageLoadTimeout(19000)
    at /home/jaredxu/Workspace/connectionsbuilder/cc_builder_e2e/test/protractor-conf.js:49:35
    at <anonymous>
[15:37:52] E/launcher - Process exited with error code 100
>> 
Warning: Tests failed, protractor exited with code: 100 Use --force to continue.

- Steps to reproduce the bug
just open an web url
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by wswebcreation** [comment]
Ok, nice, will close the issue now
