### ISSUE TITLE
Is it necessary to create "angular project" in Eclipse IDE to test the respective "angular application using "Protractor tool"

### ISSUE THREAD

**Issue by Vasundhara-vasu** [angular/protractor#4505]
Hi All,

I want to test the "angular application" using "Protractor" tool .

I am using below data.
1.Eclipse IDE
2.Nodejs -- v6.11.3
3.Protractor -- version 5.1.2 
4. I have installed "angular eclipse" plug in to my "eclipse" IDE 
5. I have installed "angular CLI" using "npm install -g angular -cli" command

Now , can any one suggest me the set up required to "automate the angular application" , Is it necessary to create "angular project" in eclipse to test "angular application" ? Is it necessary to have the "complete code" of the "angular application" which i would like to test ?

**Comment by wswebcreation** [comment]
@Vasundhara-vasu 

Please don't use the Protractor Github for usage questions. See also you previously closed questions. Ask your question(s) on StackOverflow or Gitter. [Ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by Vasundhara-vasu** [comment]
@wswebcreation 

ok thanks for your reply
