### ISSUE TITLE
Click on a Map location using their latitude and longitude

### ISSUE THREAD

**Issue by makwanaparth94** [angular/protractor#4509]
Automating a site where root functionality starting from a clicking on  map location.

I have that particular latitude and longitude for that location(18.649247,73.812793)
and On web app ,I found the map height and width where map frame is set.
mapwidth * mapheight = 812.81 * 500;

So my question is , can we click on a map location using these values using protractor?

Help me out to resolve it!

**Comment by wswebcreation** [comment]
Hi @makwanaparth94 

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
