### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by avril-verhaeghen** [angular/protractor#4510]
Bug report
---

- Node Version: `6.11.2`
- Protractor Version: `5.1.2`
- Angular Version: `4.4.3`
- Browser(s): `chrome`
- Operating System and Version `OS 10.12.6`
- Your protractor configuration file

``` js
var SpecReporter = require('jasmine-spec-reporter').SpecReporter;

exports.config = {
  baseUrl: 'http://localhost:4444/',

  specs: [
    'src/**/**/*.e2e-spec.ts'
  ],
  exclude: [],
  framework: 'jasmine2',
  allScriptsTimeout: 110000,
  jasmineNodeOpts: {
    showTiming: true,
    showColors: true,
    isVerbose: false,
    includeStackTrace: false,
    defaultTimeoutInterval: 400000
  },
  directConnect: true,
  capabilities: {
    'browserName': 'chrome'
  },
  onPrepare: function () {
    jasmine.getEnv().addReporter(new SpecReporter({displayStacktrace: true}));
    browser.ignoreSynchronization = true;
  },
  useAllAngular2AppRoots: true
};
```

- A relevant example test
```js
import { by, element } from 'protractor';

describe('Testing external CSS', () => {
  it('should contain navigation step titles with no text transformation', () => {
    let current = element(by.css('.current'));
    expect(current).toBeTruthy();
  });
});
```

- Output from running the test

> SyntaxError: Unexpected token import

Hi,

I'm having this issue with a simple E2E test. Not sure what I'm missing here or what I'm doing wrong.

**Comment by wswebcreation** [comment]
Hi @avril-verhaeghen 

Looks like using `import` with NodeJS 6. This can't be used unless you use a transpiler like Babel or something.

By the way, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

I'm going to close it for now.

Thanks!
