### ISSUE TITLE
Set capability from CLI with dot inside (jenkins.nodeName) 

### ISSUE THREAD

**Issue by MaciejCiach** [angular/protractor#4516]
Hi there!

I'm trying to pass jenkins.nodeName capability from CLI , I need it to specify Selenium Node from 
https://wiki.jenkins.io/display/JENKINS/Selenium+Plugin
`protractor  --capabilities.jenkins.nodeName=JenkinsMacbook` gives me capability 
` capabilities: 
   { browserName: 'chrome',
     jenkins: { nodeName: 'Jenkins-Macbook' },
     count: 1 },`
But I would like to get something that I can achieve in protractor.conf.js by 
`  capabilities: {
    browserName: 'chrome',
    "jenkins.nodeName":'JenkinsMacbook'
  },`
what gives me correctly 
`capabilities: 
   { browserName: 'chrome',
     'jenkins.nodeName': 'Jenkins-Macbook',
     count: 1 },`

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
