### ISSUE TITLE
The Element not clickable error lacks helpful debugging information

### ISSUE THREAD

**Issue by benjaminapetersen** [angular/protractor#4517]
Greetings!

This may be related to [this issue](), though it has been open since 2014 so is definitely stale.  

I'm finding that the `Element is not clickable` error is not helpful in determining what can be fixed.  My stack trace is as follows:

```bash
Failures:
1) User adds a template to a project after creating a new project using the Import YAML tab should process and create the objects in the template
  Message:
    Failed: unknown error: Element is not clickable at point (274, 2075)
      (Session info: chrome=61.0.3163.100)
      (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 39 milliseconds
    Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'
    System info: host: 'dhcp129-121.rdu.redhat.com', ip: '10.13.129.121', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_65'
    Driver info: org.openqa.selenium.chrome.ChromeDriver
    Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6), userDataDir=/var/folders/bh/k6l0fj7j4d7792vq0zbhp2sh0000gn/T/.org.chromium.Chromium.wFM4MZ}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=61.0.3163.100, platform=MAC, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, unexpectedAlertBehaviour=}]
    Session ID: 8496838dedb8efd05f2a62cde8f4402f
  Stack:
    WebDriverError: unknown error: Element is not clickable at point (274, 2075)
      (Session info: chrome=61.0.3163.100)
      (Driver info: chromedriver=2.26.436421 (6c1a3ab469ad86fd49c8d97ede4a6b96a49ca5f6),platform=Mac OS X 10.11.6 x86_64) (WARNING: The server did not provide any stacktrace information)
```

I can drop into `repl` mode, use jQuery & easily trigger a click event.  The selector is not a problem.  

The test looks something like this:

```javascript 
class CreatePage {
  // skipped irrelevant.... 
  clickCreate() {
    let button = element(by.id('create-submit'));
    browser.wait(EC.elementToBeClickable(button), 15000, 'Create button is not clickable');
    button.click().then(() => {
      console.log('did it click?');   // nopes.
    });
  }
}

```

Requested details:

- Node Version: `v6.10.2`
- Protractor Version: `5.1.1`
- Angular Version: `1.5.11`
- Browser(s): `Chrome`
- Operating System and Version `OS X El Capitan 10.11.6 `
- protractor conf: [here](https://gist.github.com/benjaminapetersen/461c8d2f9574ba57958489d72f779cb2)
- test details: I can provide links to Travis & other things if its helpful, just let me know.

**Comment by wswebcreation** [comment]
Hi @benjaminapetersen 

Looking at your setup you are using Chrome 61 and ChromeDriver 2.26. You are advised to use at least the latest version of Chromedriver 2.32. There should be an issue fixed there that the element is scrolled to automatically when the element is not in view (see the frist point on Chromedriver 2.32 [changelog](https://sites.google.com/a/chromium.org/chromedriver/downloads)). 
There is also an issue that states that is not fixed correctly, see here https://github.com/angular/protractor/issues/4490. 

The error you get would mean that the element has not been scrolled to and that the coordinates to click on are not in the view. Because it's a Chromedriver thing and not a Protractor issue I'm going to close it for now. Feel free to discuss it here further

**Comment by benjaminapetersen** [comment]
Thanks for the reply!  Very much appreciate.

Is there a sensible way to control these things via a standard setup such as `package.json`?  Best I have is `karma-chrome-launcher` at latest `2.2.0` [link](https://github.com/karma-runner/karma-chrome-launcher/releases) which I assume is responsible for `Chromedriver`.  

I'm finding it incredibly hard to truly nail down the versions of everything needed, wether `selenium`, `webdriver`, `chromedriver`, etc.  We have been struggling for a few months with a protractor e2e flow falling over fairly regularly due to subtle breakages.

**Comment by wswebcreation** [comment]
Hi @benjaminapetersen 

> Is there a sensible way to control these things via a standard setup such as package.json?

Well it depends, the browser (Chrome and Firefox) keep updating so you need to keep track of that. To be able to automate those browsers you need to update the webdrivers. I don't think you need Karma, Protractor can do it all for you.

After you installed Protractor in your project you have 2 options,  use the `webdriver-manager` that is provided by protractor by running this command from the command line `node ./node_modules/protractor/bin/webdriver-manager update` to update the selenium server and get the latest version of ChromeDriver and Geckodriver or use `webdriver-manager` as a local installation.

You can follow the docs [here](https://github.com/angular/webdriver-manager) to see how that works. 

Hope that helps

**Comment by benjaminapetersen** [comment]
Thanks!

I have a couple `npm` tasks setup to do this:

```JavaScript 
// package.json
"postinstall": "node_modules/protractor/bin/webdriver-manager update",
// solves problem where github api rate limit keeps us from getting 
// dependency updates & an update-config.json error...
"install_protractor_backup": "rm -rf node_modules/protractor && cp -pr test/package_backups/protractor_5.1.2 -T node_modules/protractor"
```

I've been working out a couple issues with `webdriver-manager`, the latest version seems to have some issues wit github api [rate limits](https://github.com/angular/webdriver-manager/issues/270) being one.  

In a perfect world, I'd love to be able to specify `chromeddriver` in my `package.json` and have `protractor`/`webdriver-manager` honor the version specified.

**Comment by wswebcreation** [comment]
Hi @benjaminapetersen 

That perfect world is already there. I use it in the project I work for. We need to have a static version of the selenium server and I have this

``js
"webdriver-update": "node ./node_modules/protractor/bin/webdriver-manager update --standalone --versions.standalone 3.4.0"
``

So yeah, it's possible, even for a static version of ChromeDriver / Geckodriver. Is this then still open or can we close this issue?

**Comment by benjaminapetersen** [comment]
Ah, so you aren't defining it as a dependency in `package.json` (like `protractor: 5.0`), but are defining the specific version  in your update script.  I'll give that a spin.

Would love to be able to define it specifically in `package.json` under `dependencies` or in `protractor.conf.js` in a similar way.

Thanks!

**Comment by chriso86** [comment]
Just to add my 2 cents here, I am new to Protractor testing, and so far everything is easy... except for this topic on scrolling elements into view.

I don't see it covered anywhere in Protractor's documentation, and I can't seem to find out why the "actions" or "executeScript" solutions out on the Internet aren't working in my case, to focus an element within a scrollable section on the page.

Why isn't this scrolling concern covered in the documentation?

I feel like this "Element is not clickable" error is really easy trigger and common, since scrolling is common in web applications.
Its driving me crazy, I can't understand why something so simple is giving me so much trouble,
