### ISSUE TITLE
Only first page elements can be found with selectors in Ionic 3

### ISSUE THREAD

**Issue by sasos90** [angular/protractor#4526]
Bug report
Hi!

In Ionic3, I can normally find the HTML elements with '$' selector like: `$('#start-game')`, but when I start the game, which leads me to the next Page (executed with nav.setRoot or nav.push), then it doesn't find me any HTML elements anymore, but I get the error instead (provided below).

I already tried to set some browser.wait on hundred ways but nothing helps.

- Node Version: `6.10.2`
- Protractor Version: `5.1.2`
- Angular Version: `4.1.0`
- Browser(s): `Chrome`
- Operating System and Version `Win 10`
- Your protractor configuration file: https://pastebin.com/1g7j4Ekf
- A relevant example test
`const goalWrapper = $('#goal-wrapper');`
`const until = protractor.ExpectedConditions;`
`browser.wait(until.presenceOf(goalWrapper), 5000, 'Element taking too long to appear in the DOM');`
`$('#goal-wrapper').getSize().then((size) => {
            // this is not executed!
            console.log(size);
        });`
- Output from running the test
`      - Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
      While waiting for element with locator - Locator: By(css selector, .level-complete-wrapper)`
- Steps to reproduce the bug: Try the code above.

**Comment by wswebcreation** [comment]
Hi @sasos90 

First of all the error message and the line of code it fails on don't match each other. 

Your line of code that fails
> `$('#goal-wrapper').getSize().then((size) => { // this is not executed! console.log(size); });
`

Your error message
> `While waiting for element with locator - Locator: By(css selector, .level-complete-wrapper)`

Do you have an example project on which we can verify your error?

**Comment by sasos90** [comment]
I see, it was too late to think clearly :D
The thing is that I had more examples but they were calling the same thing "getSize", so I can simply change the selector. Let's say thisi is now relevant test example:
`const levelCompletedWrapper = $('.level-completed-wrapper');
const until = protractor.ExpectedConditions;
browser.wait(until.presenceOf(levelCompletedWrapper), 5000, 'Element taking too long to appear in the DOM');
$('.level-completed-wrapper').getSize().then((size) => { // this is not executed! console.log(size); });
`

**Comment by wswebcreation** [comment]
Are you also executing some commands before you do the `$('.level-completed-wrapper').getSize().then((size) => { // this is not executed! console.log(size); });`? For example, can you get the title of the page 

```js
browser.getTitle().then((title) => {
    console.log('title = ', title);
});
```

If you also can't you have a problem with the app it self and  I would refer you to the [timeouts](https://github.com/angular/protractor/blob/master/docs/timeouts.md)-docs and try the solutions there and close this issue because it's then app related instead of Protractor related

**Comment by sasos90** [comment]
browser.title works until I change the root page in Ionic.
I already checked timeouts docs but no success.
Perhaps I will turn on ionic community, because I really assume it's Ionic's navigation problem.

Thanks a lot!

**Comment by wswebcreation** [comment]
Ok,

I'm going to close this issue for now. It's still open for discussion.

**Comment by MattiLehtinen** [comment]
@sasos90 Did you found a solution? I'm having the same problem

**Comment by sasos90** [comment]
Hey, @MattiLehtinen unfortunately not. I even tried Ionic's example but neither of tests was even working. So I am not sure how actively they're actually working on it.
I found some other tools for E2E testing, but in that time I didn't have time to try them out, how well they work with Ionic. I even left the topic there but nobody hasn't responded.

**Comment by paulbriton** [comment]
@sasos90 Any news ? I've found this [related issue](https://github.com/ionic-team/ionic-unit-testing-example/issues/73) without response. 
Is Cypress a working solution ?

**Comment by sasos90** [comment]
I have stopped working on that specific Ionic project where I've used protractor for testing.
Cypress works as a charm.
