### ISSUE TITLE
External Json file for suite name is not working

### ISSUE THREAD

**Issue by goyalak22000** [angular/protractor#4531]
conf.js and the specs file are in the different folders

JSON
1. "Module" : "../tests/Module/module-us.spec.js, ../tests/Module/module-base.spec.js"

Conf.js
var suitesJson = require('./ab.json');
exports.config = {
     suites : {
          M1 = suitesJson.Module.split(",")
},
}

Issues
1. "../" is not working for the module-base.spec.js.
2. Not able to find the spec file for the first parameter i.e. module-us.spec.js whereas the path is fine.

Please let me know if i am doing anything wrong here?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
