### ISSUE TITLE
Protractor fails if HTTP Service return 404 error

### ISSUE THREAD

**Issue by Bartosz-D3V** [angular/protractor#4533]
Bug report
---

- Node Version: `6.10.3`
- Protractor Version: `5.1.2`
- Angular Version: `4`
- Browser(s): `Chrome v. 61`
- Operating System and Version `Windows 10`
- Your protractor configuration file: Standard, generated by Angular CLI
- A relevant example test: Example, generated by Angular CLI (simple getter for HTML element is fine, for the sake of simplicity)
- Output from running the test:
```
Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
```
- Steps to reproduce the bug:
	1. Generate the sample, Angular project (for example using Angular CLI)
	2. Create a simple service with GET request (without backend, so the response will be 404)
	3. Inject the service into the component that you run E2E tests against
	4. Run protractor

Protractor will return the above error. Setting timeout in the HTTP service does not seem to resolve the issue.
Interestingly, if I focus the browser opened by a protractor (instead of running it in the background) the tests will execute correctly.
Also, increasing the timeout does not seem to resolve the issue.

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by textbook** [comment]
I had a similar issue, seems to be related to #4584 - in the meantime you can `browser.waitForAngularEnabled(false)` to avoid it.
