### ISSUE TITLE
Unknown policy 

### ISSUE THREAD

**Issue by mkranjan** [angular/protractor#4539]
Chrome version: 57.0.2987.110
Chrome web driver: 2.28
Protractor: 5.1.2
Node: 6.9.1

When i run my scripts via protractor I see below error:

`ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: DnsPrefetchingEnabled
ERROR:configuration_policy_handler_list.cc(92)] Unknown policy: PasswordManagerAllowShowPasswords`

When I run the similar test case via java selenium it works fine & does not return error like above.
So am assuming local group policy is not an issue here but protractor is dealing with web driver in some different way than java.

**Note:** Have already tried below chrome options:
`'chromeOptions': { 'args': ['incognito','--no-sandbox','--disable-gpu','--disable-web-security','--dns-prefetch-disable']}`

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
