### ISSUE TITLE
Reports with shardTestFiles true

### ISSUE THREAD

**Issue by nomid0612** [angular/protractor#4540]
I  have a lot of spec files, about 100.
I want to run my tests in parallel, maxInstances: 4, shardTestFiles: true
So, shardTestFiles gives me a new instance for each spec 
In the end I get 4 reports for each instance, but each report just contains the last spec file 
And the question is:
Are there any options to run spec files in parallel and get full report?

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
