### ISSUE TITLE
Time out error waitinf for synchronous Angular tasks

### ISSUE THREAD

**Issue by EstherSalinas** [angular/protractor#4542]
**Bug report**

Time out error when I send instructions to Protractor after refirect to URL.
The error occurs since in the Angular page the yarn file has been updated.
To discard an error in my Protractor project I'm debugging Interactively:

https://github.com/angular/protractor/blob/master/docs/debugging.md#testing-out-protractor-interactively

I have the following error:

**Error**

```
ScriptTimeoutError: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
While waiting for element with locator - Locator: By(css selector, *[id="customer-name"])

```
I have an Angular 4 web project and I have other project to test the Angular web with Protractor.
My test in protractor were working fine, but a few days ago there were an error. 

*Steps to reproduce the error*
I do the login in the web, at the login page, Protractor find and interact with the elements correctly. **The problem is after do the login, when the web redirects to the main page**, when I try to find and click or get text from an element (at the main page), the error occurs.

The error occurs since in the Angular web page the yarn file has been updated.
I attach the yarn file that works fine (yarnGOOD.lock) and the yarn file update that doesn't works.

[Yarn.zip](https://github.com/angular/protractor/files/1390138/Yarn.zip)

- Node Version: `` 6.9.1
- Protractor Version: `` 5.1.2
- Angular Version: `` 4.4.5
- Browser(s): `` Chrome  61.0.3163.100
- Operating System and Version `` Windows 8.1
- Your protractor configuration file 
I'm debugging Interactively, so the problem is not related with the Protractor project.
[cucumber.conf.zip](https://github.com/angular/protractor/files/1390158/cucumber.conf.zip)
- A relevant example test
   I'm not able to send more information because of the confidentiality policies of my company.
   If it is not enough with this info I'll send an example project.

  
Feature Request
I thing that there are a problem with 

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!

**Comment by textbook** [comment]
I had a similar issue, seems to be related to #4584 - in the meantime you can `browser.waitForAngularEnabled(false)` to avoid it.
