### ISSUE TITLE
protractor tests fail to click on Linux + Chrome 62

### ISSUE THREAD

**Issue by d3ming** [angular/protractor#4547]
Bug report
---
- Node Version: `6.10.2`
- Protractor Version: `5.2.0`
- Angular Version: `1.0`
- Browser(s): `Chrome 62`
- Operating System and Version `Ubuntu 14.04` (on CircleCI)

### Sample test:
```
browser.get(homePageUrl)
  .then(() => $(emailSelector).click())
  .then(() => $(emailSelector).sendKeys(email))
  .then(() => $(passwordSelector).click())
  .then(() => $(passwordSelector).sendKeys(password))
  .then(() => $('#login_button').click());
```

The click to login used to work 100% and directs us to next page, now it fails 100%.  From the screenshot of the failure, it looks like it attempted to click but it doesn't go to the next page.

The only change was that chrome updated from 61 to 62.  This is happening for us on CircleCI where we install Chrome on the Ubuntu 14.04 container before running protractor.

We were able to work around this for now by downgrading back to Chrome 61 so it definitely seems like a regression caused by Chrome upgrading.  This does not repro on OSX

**Comment by wswebcreation** [comment]
Hi @d3ming 

On which version of ChromeDriver are you on? You should be on 2.33. Mostly this is an issue with a new version of Chrome and Chromedriver, not Protractor itself

**Comment by d3ming** [comment]
Yeah I run `webdriver-manager update` before running protractor in CI, and it looks like it does update it to 2.33:

```
[localhost] local: ./node_modules/.bin/webdriver-manager update
[17:46:37] I/file_manager - creating folder /home/ubuntu/placelocal/node_modules/webdriver-manager/selenium
[17:46:38] I/update - chromedriver: unzipping chromedriver_2.33.zip
[17:46:38] I/update - chromedriver: setting permissions to 0755 for /home/ubuntu/placelocal/node_modules/webdriver-manager/selenium/chromedriver_2.33
[17:46:38] I/update - geckodriver: unzipping geckodriver-v0.19.0.tar.gz
[17:46:38] I/update - geckodriver: setting permissions to 0755 for /home/ubuntu/placelocal/node_modules/webdriver-manager/selenium/geckodriver-v0.19.0
```

So is this an issue that should get reported to https://github.com/SeleniumHQ/selenium/issues?

**Comment by wswebcreation** [comment]
I tested it on my local machine and I don't have an issue with the clicks. This is my setup

**Chrome**: 62.0.3202.62
**Chromedriver**: 2.33
**Node:** v6.11.1
**OS:** 10.12.6
**Protractor:** 5.2.0

![image](https://user-images.githubusercontent.com/11979740/31807065-26a1e574-b56c-11e7-899b-895ca71bb3d1.png)

There are 144 scenario's with a lot of clicks and they all succeed.

**Comment by d3ming** [comment]
@wswebcreation this issue only repros for me on Linux, specifically Ubuntu 14.04.  I also don't hit it on OSX 10.12.6

**Comment by wswebcreation** [comment]
@d3ming 

Sorry, I was focusing to much on the remark of @tricky21  and didn't read your last line. I would advice you to file a bug on the Chromedriver project with your config an an example script because it only happens with that specific config.

For now I'm going to close this issue.
