### ISSUE TITLE
Browser is restarted automatically if 'shardTestFiles': true

### ISSUE THREAD

**Issue by avient** [angular/protractor#4550]
Hi there!

I have a lot of specs files.
I run them in one browser instanse ('shardTestFiles': false) and DO NOT restart Browser between tests.
So tests are going smoothly and everything is OK.

But I want to run tests in several Browser instances: 
so I set 
'shardTestFiles': true
and 
'maxInstances': 4.
And now Browser is restarted automatically after each spec file, even when 
restartBrowserBetweenTests: false.
So it dramatically slows down my tests.

Is it possible not to restart Browser after each spec file?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by ReactiveThings** [comment]
Currently there is no way to execute tests in parallel without restarting web browser after each spec. I have created an Pull Request that solves this issue. #4836.
To enable this feature you have to create custom spec scheduler and add it to the configuration. Here is an example:
```
function shardScheduler(specs, capabilities) {
  const numberOfShards = capabilities.maxInstances;
  if(numberOfShards > 1) {
      const bucketSize = Math.ceil(specs.length/numberOfShards);
      const shards = [];
      let start = 0
      while (start < specs.length) {
          let end = start + bucketSize;
          if ( end > specs.length) {
              end = specs.length
          }
          shards.push(specs.slice(start,end));
          start = end;
      }
      return shards;
  }
  return [specs];
}

exports.config = {
  ........
  capabilities: {
    shardTestFiles: shardScheduler,
    'browserName': 'chrome',
    maxInstances: 2
  },
........
}
