### ISSUE TITLE
E2E Coverage for the E2E protractor cases.

### ISSUE THREAD

**Issue by PramodDutta** [angular/protractor#4556]
We have huge E2E test cases with Protractor for our Angular App. Can anyone suggest how we can calculate the Coverage for these test cases?

P.S: They are separated from the code and are more into E2E and Selenium-based.
Please pardon if noob question

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
