### ISSUE TITLE
Time out exception is displaying while running "Protractor test script" in "internet explorer" browser

### ISSUE THREAD

**Issue by Vasundhara-vasu** [angular/protractor#4558]
Hi All,

I am unable to run "protractor test script" in "Internet explorer" browser.

I run below command.
webdriver-manager update --ie --versions.standalone 3.4.0 --versions.ie 3.4.0

my configuration file code is as below.

```js
exports.config = {
  allScriptsTimeout: 15000,
   seleniumAddress:'http://localhost:4444/wd/hub',
    capabilities: 
   { 
     'browserName': 'internet explorer',
       'platform' : 'ANY',
       'version' : '11'
    }, 
   suites: {
    heropage: ['e2e/hero/hero.e2e-spec.ts'],
    dashboardpage : ['e2e/dashboard/dashboard.e2e-spec.ts']
  },
  baseUrl: 'http://localhost:4200/',
 // directConnect : true,
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 50000,
    includeStackTrace: true
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });    
  },
}
```

I change all the required setting for internet explorer browser in "internet options"  by following http://elgalu.github.io/2014/run-protractor-against-internet-explorer-vm/ 

I am getting below error 

```shell
Failed: JavaScript error in async script. (WARNING: The server did not provide any stacktrace information)
    Command duration or timeout: 26 milliseconds
    Build info: version: '3.4.0', revision: 'unknown', time: 'unknown'
    System info: host: 'BHUVISDESK-16', ip: '192.168.0.109', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0',
java.version: '1.8.0_144'
    Driver info: org.openqa.selenium.ie.InternetExplorerDriver
    Capabilities [{se:ieOptions={browserAttachTimeout=0.0, ie.enableFullPageScreenshot=true, enablePersistentHover=true, i
e.forceCreateProcessApi=false, ie.forceShellWindowsApi=false, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000.0,
ie.useLegacyFileUploadDialogHandling=false, nativeEvents=true, ie.ensureCleanSession=false, elementScrollBehavior=0.0, ie.
browserCommandLineSwitches=, requireWindowFocus=false, initialBrowserUrl=http://localhost:39545/, ignoreProtectedModeSetti
ngs=false, enableElementCacheCleanup=true}, browserName=internet explorer, pageLoadStrategy=normal, javascriptEnabled=true
, version=11, platform=WINDOWS, unexpectedAlertBehaviour=dismiss}]
    Session ID: 01bf3915-d549-421b-a6f1-771e17c78cc7
```

Can any one help me what's my mistake in this process

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by Vasundhara-vasu** [comment]
Thanks for your reply . i posted above question in stack over flow
