### ISSUE TITLE
Cannot create async method which return ElementArrayFinder

### ISSUE THREAD

**Issue by VladimirKovalenko** [angular/protractor#4559]
Hi there!

I have a class where I want to make a async method which will return ElementArrayFinder. I need exactly this type, not ElementFinder[] because my waiters based on it and I can wait element which isn't present now in DOM. Below you can find a simple example of the structure. At row 'return this.collection;' i have an error:

> [ts]
>Type 'any[]' is not assignable to type 'ElementArrayFinder'.
>  Property 'browser_' is missing in type 'any[]'.

I tried to cast result in a different way and tried to use Promise.resolve, but no success. Could somebody help me with this case?

```js
export class Test {
	private grid: ElementFinder;

	get collection(): ElementArrayFinder {
		return this.grid
			.element(by.css('tbody'))
			.all(by.tagName('tr'));
	}

	public async getCollection(): Promise<ElementArrayFinder> {

		if (await this.collection.get(5).isPresent()) {
			return null;
		}
		return this.collection;
	}
}
```

Bug report
---

- Node Version: `v8.2.1`
- Protractor Version: `5.2.0`

**Comment by wswebcreation** [comment]
Hi @VladimirKovalenko 

I'm not really sure that I understand what you want, but your `getCollection()` returns 2 types, it can return `any` (the `null`) or an `ElementArrayFinder`. Is that what you want?

By the way, you can write this (but that's more a personal favour ;-))

`return this.grid.element(by.css('tbody')).all(by.tagName('tr'));`

like this

`return this.grid.$$('tbody tr');`

**Comment by VladimirKovalenko** [comment]
Hello, thank you for response.

My goal is to make method which can return ElementArrayFinder depending on some conditions. Example that I show above is synthetic and do not contain all conditions, that's why it can seems ridiculous, but the problem is that I cannot implement the method which will return  Promise<ElementArrayFinder >. To simplify example I get rid of the return null, and the error will be the same.

```js
export class Test {
	private grid: ElementFinder;

	get collection(): ElementArrayFinder {
		return this.grid
			.element(by.css('tbody'))
			.all(by.tagName('tr'));
	}

	public async getCollection(): Promise<ElementArrayFinder> {
		return this.collection;
	}
}
```

**Comment by wswebcreation** [comment]
Ok,

Since it involves usage and debugging, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

So I'm going to close it for now.
