### ISSUE TITLE
Find element by text (content)

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#456]
Is there a built-in locator to find an element by its html content?

This is for example the xpath expression to locate any element containing the string _"You have successfully signed up!"_

```
by.xpath("//*[contains(text(),'You have successfully signed up!')]");
```

I wonder if there is a nicer DSL for this, e.g.

```
by.text('You have successfully signed up!');
```

Or see an example of how to write this with `Protractor.By.addLocator`

**Comment by samccone** [comment]
I implemented this in Pioneer as follows
https://github.com/mojotech/pioneer/blob/master/src/widgets/Widget.coffee#L189

full method:
https://github.com/mojotech/pioneer/blob/master/src/widgets/Widget.coffee#L184-L197

**Comment by radostjane** [comment]
@juliemr I'm new in protractor and javascript. But want to learn :)
I have a problem with that function.
try to use  it like 

> element(by.myLocatorName('english')).getText();

that test fail with message " Failed: unknown error: Cannot read property 'length' of undefined"
What do I do wrong?
Thank you in advance

**Comment by elhigu** [comment]
I was mislead by this issue... currently correct answer seems to be:
```js
var dog = element(by.cssContainingText('.pet', 'Dog'));
```
https://angular.github.io/protractor/#/api?view=ProtractorBy.prototype.cssContainingText

**Comment by rolobm** [comment]
Hi guys, somebody knows how declare locators for this case: 

<li ng-click="$ctrl.openScript('1');">Phone_assign_43534</li>


![image](https://cloud.githubusercontent.com/assets/26281590/25507190/9320b88e-2b78-11e7-833f-87cacb502df9.png)
