### ISSUE TITLE
Phantomjs. Webpage. Cannot find element.

### ISSUE THREAD

**Issue by Stage001** [angular/protractor#4569]
Hello gentleman.
Following code is giving me null all the time. Although element exists and classname is correct. FindElementsByClassName is giving the same. What am I doing wrong?

    var webPage = require('webpage');
        var page = webPage.create();
        page.open('https://www.google.com/', function(status) {
          var title = page.evaluate(function() {
            return document.querySelector('.hp vasq');
          });
          console.log(title);
          phantom.exit();
        });

**Comment by wswebcreation** [comment]
Hi @Stage001 

Phantomjs isn't officially supported by Protractor. Secondly, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
