### ISSUE TITLE
using element.all(locator).filter(filterFN) with async/await is not supported

### ISSUE THREAD

**Issue by pontusnyman** [angular/protractor#4579]
Hi,

I want to filter on a specific collection of elements. This works great with promises. But with **async/await** one have to hack to get it to work.

```
  async goToSheet(sheetName) {
    const elems = await $$(selectors.sheet);
    const sheet = await filter(elems, sheetName);
    await browser
      .actions()
      .click(sheet)
      .perform();
  }
}

function filter(elems, sheetName) {
  return new Promise((resolve) => {
    elems.filter(async (elem) => {
      const text = await elem.getText();
      if (text === sheetName) {
        resolve(elem);
      }
    });
  });
}
```
And this is not pretty at all. Would like to have a better way of doing it.

Update:  
I have realised that this method dont work all the time. More luck then anything. So if someone have a fix or bugfix for this it would be great

Bug report
---

- Node Version: `9.0.0`
- Protractor Version: `5.1.1`
- Angular Version: `1.5.8`
- Browser(s): `chrome`
- Operating System and Version `Linux / OSX`

**Comment by pontusnyman** [comment]
This works, closing this bug.
`async openSheet(sheet) {

    await $$(appOverview.sheet)
      .filter(elem => elem.getText().then(text => text === sheet))
      .first()
      .click();
    await browser.wait(EC.visibilityOf($(selectors.grid)), timeout, '#grid element did not appear');
    await browser.wait(EC.invisibilityOf($(selectors.loader)), timeout, 'qv-loader did not disappear');
  }`

**Comment by simonlebonbon** [comment]
I'm using this code snippet above by @pontusnyman but I seem to get WebDriverError: java.io.IOException: Error writing to server when i run it (intermittently).
