### ISSUE TITLE
How to iterate through table smooth

### ISSUE THREAD

**Issue by elmnas** [angular/protractor#4585]
Hello everyone I have been looking on many different examples how to iterate a table.

If I am using this code for selenium I get exactly what I want.

  ` driver.findElement(By.xpath("//td[contains(.,'Apple Pomace')]"));`

how do I make this to a for loop instead for protractor

this is my table

notice I fetch --> **`<td class="ng-binding">Apple Pomace</td>`**
`

<div class="container-fluid ng-scope" ng-view=""><div class="row ng-scope">
    <div class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <h3 ng-show="searchQuery" class="page-header page-header-sm"><span translate="TITLE_SEARCH_RESULTS" class="ng-scope">Search Results</span> <span class="label label-default ng-binding" ng-bind-html="searchQuery">Apple Pomace</span></h3>
        <h3 ng-show="!searchQuery" class="page-header page-header-sm ng-scope ng-hide" translate="TITLE_ALL_PRODUCTS">All Products</h3>

        <div class="alert-info ng-hide" ng-show="confirmation">
            <p class="ng-binding"></p>
        </div>

        <table class="table table-striped table-bordered table-condensed">
            <tbody><tr>
                <th translate="LABEL_IMAGE" class="ng-scope">Image</th>
                <th translate="LABEL_PRODUCT" class="ng-scope">Product</th>
                <th translate="LABEL_DESCRIPTION" class="ng-scope">Description</th>
                <th translate="LABEL_PRICE" class="ng-scope">Price</th>
                <th></th>
            </tr>
            <tr data-ng-repeat="product in products" class="ng-scope" style="">
                <td><img src="/public/images/products/apple_pressings.jpg" class="img-responsive img-thumbnail" style="width: 200px" ng-click="showDetail(product.id)"></td>
                <td class="ng-binding">Apple Pomace</td>
                <td><div ng-bind-html="product.description" class="ng-binding">Finest pressings of apples. Allergy disclaimer: Might contain traces of worms. Can be <a href="/#reccyle">sent back to us</a> for recycling.</div></td>
                <td class="ng-binding">0.89</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-default btn-xs" ng-click="showDetail(product.id)"><i class="fa fa-eye"></i></a>
                        <a class="btn btn-default btn-xs ng-hide" ng-click="addToBasket(product.id)" ng-show="isLoggedIn()"><i class="fa fa-cart-plus"></i></a>
                    </div>
                </td>
            </tr>
        </tbody></table>

    </div>
</div></div>

<div class="github-fork-ribbon-wrapper right" ng-show="showGitHubRibbon">
    <div class="github-fork-ribbon">
        <a href="/redirect?to=https://github.com/bkimminich/juice-shop" target="_blank" translate="RIBBON_GITHUB_FORK" translate-value-fork="<i class=&quot;fa fa-code-fork&quot;></i>" translate-value-github="<i class=&quot;fa fa-github&quot;></i> GitHub" class="ng-scope"><i class="fa fa-code-fork"></i> me on <i class="fa fa-github"></i> GitHub</a>
    </div>
</div>

`

Thank you in advance

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
