### ISSUE TITLE
Is it possible to run protractor tests in more than one browser language?

### ISSUE THREAD

**Issue by Lilly2016** [angular/protractor#4586]
Feature enquiry 
---

I need to run protractor tests in more than one browser language. 
Are there any features currently available which allow this? OR is documentation on how to format the args to allow for multiple languages?
Apologies if the answer is obvious...I'm new to js and scripting!

- Node Version: `v8.9.0`
- Protractor Version: `5.2.0`
- Browser(s): `Chrome`

My config file:
`exports.config = {
  framework: 'jasmine',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
      //here i'd like to configure multiple languages for a single browser for test
      args: ['lang=en-AU,ja-JP'],
      prefs: { accept_languages: 'en-AU,ja-JP' }
    }
  },
  suites: {
    home: './home/home.spec.js'
  }
}`

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
