### ISSUE TITLE
"How do I deal with my log-in page" in the FAQ outdated(?)

### ISSUE THREAD

**Issue by jdk339** [angular/protractor#4593]
Doc Change Request:

- Update [How do I deal with my log-in page](https://github.com/angular/protractor/blob/master/docs/faq.md#how-do-i-deal-with-my-log-in-page) so that it properly reflects the information it links to in [here](https://github.com/angular/protractor/blob/master/docs/timeouts.md#how-to-disable-waiting-for-angular)

**Comment by wswebcreation** [comment]
Hi @jdk339 ,

Do you want to make a PR for it?

**Comment by MichaelRijsdijk** [comment]
#4632
