### ISSUE TITLE
Getting a parent from a chain of elements

### ISSUE THREAD

**Issue by igorPrdr** [angular/protractor#4597]
Hi!

I can not find a simle way to get a parent elementFinder (/elementArrayFinder) from a chain of elements. Something that looks like '.getParent': 
`let chained = $('parent').$('child);`
`chained.getParent(); // should return equal to $('parent') or $$('parent');`

I've fould suggestions using '.parentElementArrayFinder', but actually it works differently:
`let chained = $('parent').$('child);`
`chained.parentElementArrayFinder; // returns equal to $('parent').$$('child)` 

Is there a solution for the case?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

By the way, an "easy" but "dirty" way would be to do something like this

```js
let chained = $('parent').$('child);
chained.element(by.xpath('..')); // should return equal to $('parent') or $$('parent');
```

But be aware, you can chain like this `$('grandparent').$('child')`. Getting the parent would always return `$('parent')` and not the `$('grandparent')`

Thanks!

**Comment by igorPrdr** [comment]
Thanks for the advice and redirection ))
