### ISSUE TITLE
Dots representing the progress instead checked scenarios description

### ISSUE THREAD

**Issue by Odravison** [angular/protractor#4598]
Hey Folks,

Earlier I got this versions of protractor and framework:

```
    "protractor-cucumber-framework": "4.0.7",
    "protractor-jasmine2-screenshot-reporter": "0.3.2",
```
now when I run `proctractor:cucumber` task, the output is dots and letters that represents result of each test instead checked scenario descriptions like before the update.

My question is: Is possible use some configuration or flag (in CLI) to use scenario descriptions instead dots?

**Comment by wswebcreation** [comment]
@Odravison

To which version of Cucumber are you referring? Version 3 doesn't have the pretty formatter anymore.

Secondly it's a question about a third party library, please ask it there. I'm going to close it for now.

**Comment by Odravison** [comment]
First, thanks in advance about fast answer.

Thank you @wswebcreation, about this information. I didn't know who is responsible for this output logs.
Yeah, my cucumber is above version 3 =/ 
Unfortunately they didn't make this feature as optional configs, or they did? I will ask there, I'm sorry about wrong place to this issue.

Thanks again @wswebcreation

**Comment by wswebcreation** [comment]
Hi @Odravison 

Protractor gets the log from CucumberJS. `protractor-cucumber-framework` is the "middleware" that passes all the data between protractor and CucumberJS.

For reporting, have you also taken a look at [this plugin](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin) that uses this kind of report ;-)

![image](https://user-images.githubusercontent.com/11979740/33131857-254d4042-cf98-11e7-8646-111124889511.png)

**Comment by Odravison** [comment]
Thank you! ;)

**Comment by Odravison** [comment]
I just have tested this plugin, it's very helpful, however, see the scenarios while tests are running was more helpful, to me.
