### ISSUE TITLE
Selenium standalone server won't run since updating to v3.8.0

### ISSUE THREAD

**Issue by Lilly2016** [angular/protractor#4607]
- Node Version: `v8.9.0`
- Protractor Version: `Version 5.2.0`
- Operating System and Version `Windows 10`
- Selenium Standalone Version: `3.8.0`

Since updating to Selenium Standalone Server 3.8.0, the server won't run. 
Logged err:
`seleniumProcess.pid: 40300
Error: Invalid or corrupt jarfile`

I've tried:
`npm install -g webdriver-manager`
`webdriver-manager update`
`webdriver-manager update --standalone`

**Comment by MichaelRijsdijk** [comment]
probably related:
#4451

**Comment by Lilly2016** [comment]
Yes, it was. resolved now.
