### ISSUE TITLE
cucumber-html-reporter-Unhandled rejection TypeError: registerHandler is not a function

### ISSUE THREAD

**Issue by narayanasamyramaiah** [angular/protractor#4610]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``8.9.1
- Protractor Version: ``5.2.0
- Angular Version: ``
- Browser(s): ``chrome
- Operating System and Version ``Windows 10
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

-config.ts

import{browser,Config} from 'protractor'

export const config:Config ={

    allScriptsTimeout: 500000, //This is the overall Timeout
    getPageTimeout: 500000,

    seleniumAddress: "http://127.0.0.1:4444/wd/hub",
    
        SELENIUM_PROMISE_MANAGER: false,

        capabilities: {
            browserName:"chrome"
        },

    
       
        suites:{
            "DefaultBookMark":["../features/bCDfeature"],
           // "CreateDraft":["../features/ABC.feature"]

          
        },
        framework:"custom",
        frameworkPath:require.resolve("protractor-cucumber-framework"),
        onPrepare: () => {

           
            browser.manage().window().maximize();
           
         
           browser.waitForAngularEnabled();

           
        },

      
        
        cucumberOpts: {
            compiler: "ts:ts-node/register",
            require: ["../Sprint1/steps/ABC.ts","../hooks/support.ts"],
          
            strict: true,
            tags: "@smoke",
            format:'pretty'
            
            

        },
        

        // onComplete:()=>{
        //     browser.close();
        // }

}

--hooks.ts

const Cucumber = require('cucumber');
import { browser } from 'protractor';
import * as fs from 'fs';
import { config } from '../config/config';
import { defineSupportCode } from "cucumber";
import * as reporter from 'cucumber-html-reporter';
import { mkdirp } from 'mkdirp';
import{Md5} from 'ts-md5/dist/md5'

defineSupportCode(function ({ registerHandler, registerListener, After, setDefaultTimeout,Before }) {
    setDefaultTimeout(10 * 4000);
    let jsonReports = process.cwd() + "/reports/json";
    let htmlReports = process.cwd() + "/reports/html";
    let targetJson = jsonReports + "/cucumber_report.json";
    let screenshots = process.cwd() + "/reports/images/";

    registerHandler('BeforeFeature', async function () {
        await browser.get(config.baseUrl);
    });

    registerHandler('AfterStep', async(event) => {

       if (event.name) {
         let featurename = event.scenario.name
        
            // if(event.name.toString().le
            //     {
            //         var stepname = event.name.replace("BiGFILENAME");
            //     }else
            //     {
            //         var stepname = event.name;
            //     }

         if (!fs.existsSync(screenshots)) {
           mkdirp.sync(screenshots);
         }
         let screenShot = await browser.takeScreenshot();
         var timeInMs = Date.now();
         var stream = fs.createWriteStream(screenshots + featurename+"_"+timeInMs+".png");
         stream.write(new Buffer(screenShot, 'base64'));
         stream.end();
       }

    });

    After(async (scenarioResult) => {
        let world = this;
        if (scenarioResult.status=="FAILED") {
            let screenShot = await browser.takeScreenshot();
            // screenShot is a base-64 encoded PNG
            world.attach(screenShot, 'image/png');
        }
    })

    let cucumberReporterOptions = {
        theme: "bootstrap",
        jsonFile: targetJson,
        output: htmlReports + "/cucumber_reporter.html",
        reportSuiteAsScenarios: true
    };

    let logFn = string => {
        if (!fs.existsSync(jsonReports)) {
            mkdirp.sync(jsonReports);
        }
        try {
            fs.writeFileSync(targetJson, string);
            reporter.generate(cucumberReporterOptions); // invoke cucumber-html-reporter
        } catch (err) {
            if (err) {
                console.log(`Failed to save cucumber test results to json file. 
                             Failed to create html report.
                             `);
                console.log(err);
            }
        }
    };
    let jsonformatter = new Cucumber.JsonFormatter({
        log: logFn
    });
    registerListener(jsonformatter);
})

--dev dependencies--
"devDependencies": {
    "@types/chai": "^4.0.4",
    "@types/core-js": "~0.9.34",
    "@types/cucumber": "^2.0.4",
    "@types/jasmine": "^2.8.2",
    "@types/node": "^6.0.90",
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "concurrently": "2.2.0",
    "cucumber": "^3.0.6",
    "cucumber-html-reporter": "^3.0.4",
    "jasmine": "^2.8.0",
    "protractor": "^5.2.0",
    "protractor-cucumber-framework": "^4.1.1",
    "ts-md5": "^1.2.2",
    "ts-node": "^3.3.0",
    "typescript": "^2.6.1",
    "update": "^0.7.4"
  },

Error--
Unhandled rejection TypeError: registerHandler is not a function
    at C:\ABC\hooks\support.ts:67:5
    at Object.defineSupportCode (C:\ABC\node_modules\cucumber\src\support_code_library_builder\index.js:20:9)
    at Object.<anonymous> (C:\ABC\hooks\support.ts:60:1)
    at Module._compile (module.js:635:30)
    at Module.m._compile (C:\ABC\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\ABC\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\ABC\node_modules\cucumber\src\cli\index.js:61:42
    at Array.forEach (<anonymous>)
    at Cli.getSupportCodeLibrary (C:\ABC\node_modules\cucumber\src\cli\index.js:61:22)
    at Cli.<anonymous> (C:\ABC\node_modules\cucumber\src\cli\index.js:76:37)

Please help me-

What is the best way for cuumberHtmlReporting?
is there any compatible issues?
for the latest version how to use the reporting feature?

please help

Thanks

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

By the way, this has to do with breaking changes in CucumberJS, see the [changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes). The `registerHandler` but also the `jsonformatter` and the `pretty`-formatter have been removed. Check the site of  `cucumber-html-reporter` and `cucumberjs` how to deal with that.
You can also use [this](https://github.com/wswebcreation/protractor-multiple-cucumber-html-reporter-plugin) that works with all versions of cucumber.

Thanks!
