### ISSUE TITLE
Protractor Help: Admin Error Issues on a client machine

### ISSUE THREAD

**Issue by amad410** [angular/protractor#4619]
Hi

I am an automation tester that is developing tests using a laptop given to me by the client. With the client laptop there are certain security restrictions that will not allow me to add certain software, plugins, or browser extensions.  For my protractor tests, I was able to get ChromeDriver working (and run my test), but only after disabling the automation extension to bypass the security restriction.
 
Are there any implications of having that extension disabled and if it will affect any automation capability going forward.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
