### ISSUE TITLE
Unable to click on the below xpath

### ISSUE THREAD

**Issue by Balajikl** [angular/protractor#4620]
Hi,

As I am new to the protractor, I am trying to enter email id and I am using the below xpath I am able to click and enter the emailid. Whereas the same is working in selenium. 

XPATH:
driver.findElement(by.xpath('//input[@name='userlogin']')).sendkeys("xyz@xyz.com");

Element:

![email](https://user-images.githubusercontent.com/12830976/33763334-1548485e-dc36-11e7-8b9f-83c32eb18f63.PNG)

**Comment by macroking** [comment]
This issue does not belong here. Please ask this in SO.

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
