### ISSUE TITLE
protractor cannot locate elements within ng-repeat-start loop

### ISSUE THREAD

**Issue by vishaln79** [angular/protractor#4624]
Bug report
---

- Node Version: 8.4.0
- Protractor Version: 5.2.0
- Angular Version: 1.5.7
- Browser(s): chrome
- Operating System and Version CentOS Linux release 7.4.1708 

I am having trouble locating an element within an ng-repeat loop with protractor.

The UI code looks something like this: 

```
    <tr ng-repeat-start="app in appsData.result" class="bordered"> 
    <td>
    <md-button id="{{app.name}}" class="md-raised primary" ng-click="appAction('configure', app)">
    Configure and Run 
    </md-button> 
    </td>
    </tr> 
    <tr ng-repeat-end ng-show="expanded" ng-class="{'highlighted': expanded}">
```

..... 
I tried

```
    var rows = element.all(by.repeater("app in appsData.result"));
    rows.first().element(by.tagName("button")).getText().then(function(text){
    console.log("Text: "+text);
    });
```

but I am getting a

> [12:24:40] E/launcher - NoSuchElementError: Index out of bound. Trying
> to access element at index: 0, but there are only 0 elements that
> match locator by.repeater("app in appsData.result")

(I also tried tagName = md-button)

I did a browser.getPageSource()
 but I only see

```
    <tbody>
    <!-- ngRepeat: app in appsData.result -->
    </tbody>
```

My protractor conf file looks like this:

```
    exports.config = {
      seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
      getPageTimeout: 600000,
      allScriptsTimeout: 5000000,
      framework: 'custom',
      // path relative to the current config file
      frameworkPath: require.resolve('protractor-cucumber-framework'),
      capabilities: {
        browserName: 'chrome',
        'chromeOptions': {
          args: ['--no-sandbox', 'headless']
        }
      },
    
      // Spec patterns are relative to this directory.
      specs: [
        'features/*.feature'
      ],
    
      baseURL: 'http://localhost:8080/',
    
      cucumberOpts: {
        require: 'features/step_definitions/*.js',
        tags: false,
        format: 'pretty',
        profile: false,
        'no-source': true
      }
    };
```

**Comment by wswebcreation** [comment]
Hi @vishaln79 

Just 1 check, did you also try the repeater method on the TO-DO list on https://angularjs.org/. As far as I can see it looks like the code is working.

If you don't get any source back on the `browser.getPageSource()` it looks like you calling this method before the page has been build.

For now I'm going to close it because the method works and it looks like an implementation issue.
