### ISSUE TITLE
Not able to install Protractor

### ISSUE THREAD

**Issue by PINTusin** [angular/protractor#4633]
i am trying to install protractor, but i am getting following issues. Check screenshot. 
Please tell me how to solve this issues. 
![image](https://user-images.githubusercontent.com/5688489/33983204-4b71b3c8-e0d9-11e7-8ae5-fd849681eb65.png)

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
