### ISSUE TITLE
Update Page Objects doc for testing with node 8 async/await

### ISSUE THREAD

**Issue by vsravuri** [angular/protractor#4637]
Bug report
---
- Node Version: `v8.9.3`
- Protractor Version: `5.2.2`

The latest Node.js provides native async/await. Control flow will be completely removed in future version of Selenium [Selenium 4.0]. The Page Object example provided in the http://www.protractortest.org/#/page-objects document is written using Control Flow. 

I've referred to the http://www.protractortest.org/#/async-await document to understand how to convert a spec file written in Control Flow to async/await but struggling to find an example to convert the Page Objects written in Control flow to async/await. 

**Requirement:**
Update the existing Page Object document to include an example to write Page Object using Node async/await. The examples in existing Page Object document will be obsolete after Control Flow is removed from  Selenium.

**Comment by qiyigg** [comment]
This was done by #4675.
Close the issue
