### ISSUE TITLE
execute element.all recursively for different locators

### ISSUE THREAD

**Issue by bitquality** [angular/protractor#4639]
Hi there!

I don't know if this feature is supported . But something i am trying to achieve is filter elements by multiple conditions. I have a condition where i first want to filter elements by tagname , then name , then id. The order of this filter condition execution should go in sequence. If my tagname filter doesn't fetch any elements or empty it shouldn't throw any error(or should go to catch condition) and continue to filter with rest of the conditions.

```js
element.all(by.tagName(paramTagName))
    .reduce(function (acc, tagElement) {
        tagElement.getText()
            .then(function (text) {});
    })
    .all(by.name(paramName))
    .reduce(function (acc, nameElement) {
        nameElement.getText()
            .then(function (text) {});
    })
    .all(by.id(paramId)
    .reduce(function (acc, IdElement) {
        IdElement.getText()
            .then(function (text) {});
    });
```

This doesn't work and it fails with error:

```
    Failed: element.all(...).reduce(...).all is not a function
```

And also when user passes empty value for 'paramName' variable i want to skip that and use next filter locator condition.Currently it throws an error saying invalid locator.

Regards,
Krishna

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

But trying to give an answer to your question, your are not returning a value in each reduce, see also http://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.reduce

Thanks!
