### ISSUE TITLE
not clicked or sth wrong

### ISSUE THREAD

**Issue by cybermerlin** [angular/protractor#4642]
Hi there!

Bug report
---

- Node Version: `8.6`
- Protractor Version: `5.2`
- Angular Version: `-`
- Browser(s): `chrome latest`
- Operating System and Version `win 10`
- Your protractor configuration file
```
import './helpers';

export default {config : {
    directConnect: true,

    multiCapabilities: [
        {browserName: 'chrome'}
    ],

    framework: 'jasmine',

    specs: ['e2e/**/test.js'],
    params: require('./CoreTest.conf.js'),

    allScriptsTimeout: 4e4,

    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        isVerbose: false,
        showColors: true,
        showTiming: true,
        includeStackTrace: false, // If true, include stack traces in failures.
        defaultTimeoutInterval: 4e4
    },

    onPrepare: () => {
        browser.ignoreSynchronization = true;
        browser.waitForAngularEnabled(false);

        browser.driver.manage().window().maximize();
        browser.get(browser.params.url + '/');
        browser.sleep('2e3');
    }
}};
```
- A relevant example test
https://stackoverflow.com/questions/47969039/protractorselenium-not-clicked-on-html-element
- Output from running the test
`not thruty contextmenu`
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!

**Comment by cybermerlin** [comment]
this does not question. 
it's a bug. 
because if click() used in it() then all be right, but if used in the class hierarchy then it's not worked. 
for solving this problem need a little change code protractor but I haven't more time. 

this project needs to the better team of support or we lose all clients.
good luck.

**Comment by wswebcreation** [comment]
Hi @cybermerlin 

If I look at your SO question you have enough people you want to help. I also checked your question and saw you were using a custom click, not the Protractor click method. Because your method implementation isn't related to the project and is more a usage question I've closed it.
