### ISSUE TITLE
Custom logging in for JUnitXmlReporter

### ISSUE THREAD

**Issue by bboycs** [angular/protractor#4643]
Hi,

i have trying to populate console.log("xx")  to JUnitReport, but it seems console.log will not be written down as a part of JUnitXmlReporter.
Is there any way to have a custom logging with JUnitXmlReporter ?

Thanks

**Comment by Xotabu4** [comment]
@bboycs Hi!
JUnitXmlReporter is not a part of protractor package. If you believe this is a bug - consider to provide small reproducible example and create issue here - https://github.com/larrymyers/jasmine-reporters.

Your question more looks like support question, try to ask it on stackoverflow.

Thanks!

**Comment by wswebcreation** [comment]
@Xotabu4 

Thanks for your reply. You are right, the question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
