### ISSUE TITLE
Applying the toAppear matcher to CssContainingText element finder

### ISSUE THREAD

**Issue by Alextunchii** [angular/protractor#4644]
Hi there!
I got some problem I can't resolve to add to my test text assertions
I test login form where i want to check text error presence after submitting the Sign In button.

But the test is passing despite is there present correct text or fully opposite.
What do I do wrong guys? Perhaps for this purpose exists another way to do that, will be grateful for your pieces of advice.

**await expect(element(by.cssContainingText('.common-form-error', 'Please try again or Sign-up to create an account.')))**

```
it('Sign in with correct email email and incorrect password', async function () {
        loginEmailField.sendKeys('tylermac2030@gmail.com');
        await loginPassField.sendKeys('Alexandro123');
        await signInButton.click();
        await browser.sleep(1500);
        await expect(element(by.cssContainingText('.common-form-error', 'Please try again or Sign-up to create an account.')))
            .toAppear(2000, 'Error message did not appear');
        await expect(text).to
```

**Comment by Xotabu4** [comment]
@Alextunchii 
This question is better suitable on stackoverflow:
https://stackoverflow.com/questions/tagged/protractor

**Comment by wswebcreation** [comment]
@Xotabu4 

Tnx for the reply, I'm going to close it for now
