### ISSUE TITLE
Protractor doesn't see dropdown list consist of ul > li

### ISSUE THREAD

**Issue by Alextunchii** [angular/protractor#4645]
The problem I got stuck in like for one day, never been like this before, but i literally can't locate drop down list and click any option inside.
Please, help with, even devs from my project can't help me, we tried a lot of things but still...

a test is failing on these rows:
```
const dropDown = browser.element(by.css('.suggestion:first-of-type'));
        const waitDropDown = EC.visibilityOf(dropDown);
        await wait(waitDropDown, 1000);
        await dropDown.click();
```

```
it('first Sign Up', async function () {
        await email.sendKeys(chance.email());
        await passField.sendKeys('Alex2030');
        await passConfField.sendKeys('Alex2030');
        await prefix.click();
        await browser.sleep(3000);
        await mr.click();
        await firstName.sendKeys('Protractor');
        await lastName.sendKeys('AutoTest');
        await company.sendKeys('ITREX QA');
        await fullAddress.sendKeys('Chicago');  
        const dropDown = element(by.css('.suggestion:first-of-type'));
        const waitDropDown = EC.visibilityOf(dropDown);
        await browser.wait(waitDropDown, 1000);
        await dropDown.click();
        await address1.sendKeys('Chicago Address 1 90000');
        await address2.sendKeys('This is second test address, Chicago');
        await zip.sendKeys('12345');
        await phone.sendKeys('1234567890');
        await browser.wait(isClickable, 2000);
        await buttonSignUp.click();
    });
```

> Failed: Timed out waiting for asynchronous Angular tasks to finish after 11 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
> While waiting for element with locator - Locator: By(css selector, .suggestion:first-of-type)
>         While waiting for element with locator - Locator: By(css selector, .suggestion:first-of-type)
>     at Object.checkLegacyResponse (/Users/alexandertunick/WebstormProjects/build/node_modules/selenium-webdriver/lib/error.js:546:15)
>     at parseHttpResponse (/Users/alexandertunick/WebstormProjects/build/node_modules/selenium-webdriver/lib/http.js:509:13)
>     at doSend.then.response (/Users/alexandertunick/WebstormProjects/build/node_modules/selenium-webdriver/lib/http.js:441:30)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> From asynchronous test: 
> Error
>     at Suite.<anonymous> (/Users/alexandertunick/WebstormProjects/build/specs/sign_up.spec.ts:38:5)
>     at Object.<anonymous> (/Users/alexandertunick/WebstormProjects/build/specs/sign_up.spec.ts:5:1)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)

Here is the link for DOM structure -> https://ibb.co/izTc7G (if don't want to got through it, I will attach a code manually

**Comment by MichaelRijsdijk** [comment]
Not sure without a running example, but:

You're specifying the dropdown by finding the first occurence of an li element, I would suggest finding the dropdown by it's container. When found, activate the dropdown (hover of click, don't know the application), then search and interact with an element in the dropdown.

===
pseudo:
const dropDown = browser.element(by.css('.menu'));
dropDown.activate();
dropDown.pressItem(itemSelector);

**Comment by Alextunchii** [comment]
@MichaelRijsdijk thanks for your response.
We have resolved this issue, the problem was in polling $timeout by AngularJS

Resolved with help of: `await browser.waitForAngularEnabled(false);`
