### ISSUE TITLE
Usage.days_mnth_lbl<...>.gettext is not a function error. 

### ISSUE THREAD

**Issue by KavitaForProtractor** [angular/protractor#4646]
I really need help on this issue. I think my protractor script is not able to recognize the element in my ionic app. I am running my script on an Andoid app so browser.sleep() is not working for me. Please help. 

Element detail : <div class="oeb-usage-date">Saturday, December 31st</div>

pageObjects_Usage : 
days_month_lbl : function(){
       return element(by.xpath('//*[@id="tabpanel-t0-1"]/oeb-usage-component/ion-content/div[2]/oeb-usage-summary-swipe-cards/ion-slides/div/div[1]/ion-slide[1]/div/oeb-usage-summary-swipe-card/div/div[1]'));
    },
module.exports =  Usage;

var screenshotUtil = require('../utils/screenshot.js');
var HomePage = require('../pageobjects/pageObjects_home');
var Login = require('../pageobjects/pageObjects_SignIn');
var Usage= require('../pageobjects/pageObjects_Usage');
var Dashboard = require('../pageobjects/pageObjects_dashboad');
var testData = require('../testData/testData.json');
var Global = require('../global.js')
describe('Ensure that from bottom shell Usage is highlighted ',() => {
    
        
            
        //browser.get(HomePage.url);
        //console.log("Opening the URL");
        //await screenshotUtil.saveScreenShot(browser,  "Signup"+new Date().toDateString() + '.jpg');
        beforeAll(() => {
            HomePage.sigIn().click();
            Login.username_txt().sendKeys(Global.EMAIL);
            Login.password_txt().sendKeys(Global.PASSWORD);
            Login.next_btn().click();
            Dashboard.usage_menu().click();
            
            //console.log("Usage");
    
       });
       it(' Ensure that from bottom shell Usage is highlighted ', (done) => {
       
    //Click on Usage from the bottom shell
    //Tap on Usage Detail as Take a closer look button is not available for now. 
    //element(by.xpath('//*[@id="tab-t0-1"]/span')).click();
    
    //browser.driver.sleep(10000);
    //to expect that usage menu is highlighted.
    var submitButton = ptor.findElement(protractor.By.css('.loginbutton'));
    submitButton.click();
    
    setTimeout(() => {
        
        //expect(Usage.days_month_lbl().getAttribute()).toBe("Saturday, December 31st");
        expect(Usage.days_month_lbl().gettext()).toBe("DAILY");
    }, 10000);
       
     
    });
      
});

**Comment by Xotabu4** [comment]
`expect(Usage.days_month_lbl().gettext()).toBe("DAILY");`
Must be
`expect(Usage.days_month_lbl().getText()).toBe("DAILY");`

http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.getText

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
