### ISSUE TITLE
ES2017 support for protractor

### ISSUE THREAD

**Issue by BarrMan** [angular/protractor#4648]
Hey, when I try to use ES2017 with protactor (in angular v5.0.1 unit-tests using karma) I get this error:
> TypeError: undefined is not a function (evaluating 'Object.values(

Trying to add `babel/register` to the config file did not help. 

Is there a way to use ES2017 syntax with protactor and karma in angular v5 unit-tests?

Thanks.

- Versions -
- Node Version: 7.1.0
- Protractor Version: 2.1.7
- Angular Version: 5.0.1
- Operating System and Version Linux (Ubuntu)

**Comment by Xotabu4** [comment]
> Node Version: 7.1.0

Probably you should update your nodejs version atleast to 8.x.x or 9.x.x

I pretty sure this is not protractorjs issue.

**Comment by BarrMan** [comment]
- node version is now updated to 9.3.0
- protractor version is now 5.2.2
I also manually ran webdriver-manager update, but no luck so far.

**Comment by BarrMan** [comment]
Adding this line `import 'core-js/es7/object';` to my `polyfills.ts` file solved the problem.

Thanks :+1:

**Comment by Xotabu4** [comment]
@BarrMan 
I see that you are using typescript
If you getting this error in runtime - you can try to set compiler target to "ES2016", "ES2017" or "ESNext", maybe that would allow you not to include polyfills.

**Comment by raulovidiu** [comment]
@BarrMan , thanks for doing a follow-up. Would you like to close this issue?
