### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by devoto13** [angular/protractor#4657]
Bug report
---

- Node Version: `8.7.0`
- Protractor Version: `5.2.2`
- Angular Version: `-`
- Browser(s): `-`
- Operating System and Version `macOS High Sierra`

1. Clone repo https://github.com/devoto13/protractor-warning
2. `npm install`
3. `node --trace-warnings ./node_modules/.bin/protractor protractor.conf.js`

Observe warning being printed to console:

    DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

It does not break anything, but is annoying. I would like to get rid of it once and for all. It comes from the following dependency chain `webdriver-js-extender -> selenium-webdriver@2.* -> tmp`. One possible fix would be to update `selenium-webdriver` dependency for `webdriver-js-extender` or replace it with peer dependency. There is even a PR trying to do that - https://github.com/angular/webdriver-js-extender/pull/12. However it didn't get any attention and @sjelin does not seem to be active on Github for almost a year. I just thought that maybe somebody from the Protractor team can give `webdriver-js-extender` some maintainer love :) Or if it is not possible maybe Protractor can consider dropping/replacing `webdriver-js-extender`.

**Comment by andreasmarkussen** [comment]
I have the exact same issue, which I think everyone has?

**Comment by jjdereu** [comment]
+1

**Comment by ksteuer** [comment]
+1

**Comment by andreasmarkussen** [comment]
@juliemr - Are you aware what It takes to get some attention with this from the maintainers? And alternatively open up for additional maintainers?

**Comment by hassankaz** [comment]
Is there any workaround for this issue? This prevents me from running tests.

**Comment by qiyigg** [comment]
Sorry, I don't know much about webdriver-js-extender. Probably I can get some time to take a look at it this week, sorry for late response.
@hassankaz  as far as I know, this shouldn't affect running tests, it just bring some annoying warnings, what error did you get?

**Comment by hassankaz** [comment]
Sorry my bad. My tests were not running for some other reason (webdriver-manager update needed to be run) . After I fixed the issue it's running again. thanks!

**Comment by heltonalves99** [comment]
I have same issue. Any idea to fixes it ?

**Comment by devoto13** [comment]
@qiyigg did you get a chance to look at `webdriver-js-extender` project yet?

**Comment by qiyigg** [comment]
@devoto13 Not yet. The thing is this project is maintained by another contributor who is not active for a long time, I did check with other contributors to see who is familiar with it, but unfortunately no one knows the detail. From what I know so far, probably we don't need this dependency any more, but it requires some investigation to remove it safely.

**Comment by devoto13** [comment]
@qiyigg Thanks for an update!
Please let me know if there is something specific I can do to help move the investigation forward?

**Comment by garlapati99** [comment]
I am facing the same issue. how to resolve this
(node:21031) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Thanks

**Comment by devoto13** [comment]
This issues was fixed by https://github.com/angular/protractor/commit/056eec23a7d1534d5e8624d42a6c9d1f3106cf5d and released in 5.4.0.
