### ISSUE TITLE
seleniumServerJar : Absolute path instead of relative

### ISSUE THREAD

**Issue by AnandVishnu** [angular/protractor#467]
Is there any way I could provide absolute path instead of releative path in the exports.config.

The reason why I want to do this because of the following. I have following project structure

```
Project
  |- Controllers
  |-Views
  |- Scripts
  |- Test
         |-e2e
         |-----Selenium
         |      |-----selenium.jar
         |      | -----chromedriver
         |-----testConfig.js
         |-----testSpecs.js
```

Now to run the test for CI server I have to put the selenium folder inside e2e but this selenium folder is already present inside npm-module/protractor/selenium. I just want to use the jar file from there. I could do a dirty path transalation which would look something like this

```
../../../../../../c/users/username/appdata/roaming/npm/node_modules/protractor/selenium
```

This would make it very brittle. Is there any way I could specify that not use path.combine (inside cli.js and runner.js)

**Comment by developeromI89** [comment]
But where are these files
