### ISSUE TITLE
right click not working with IE driver

### ISSUE THREAD

**Issue by doshinam** [angular/protractor#4672]
[protractor.config.zip](https://github.com/angular/protractor/files/1657394/protractor.config.zip)

- Node Version: `` 8.9.3
- Protractor Version: ``5.2.2
- Angular Version: `` 1.5.0
- Browser(s): ``Internet Explorer 11 (IEDriverServer 3.8.0)
- Operating System and Version `` Windows 7
- Your protractor configuration file: PFA
- Steps to reproduce the bug : I am using the following commands to right click on the screen.
This works well with Chrome.
this.executeSequence([
browser.actions().mouseMove(element(by.xpath("//span[text()='xyz'']")).perform(),
browser.actions().click(element(by.xpath("//span[text()='xyz'']"), protractor.Button.RIGHT).perform()
]);

On creating the issue for this on selenium, we got a response
IEDriverServer 3.8.0 expects w3c actions, not the OSS actions. As of right now, protractor does not send w3c compatible actions. Protractor needs to update in order to use IEDriverServer 3.5.0+.
Alternatively, you can downgrade your IEDriverServer to 3.4.0

After downgrading to the IEDriverServer to 3.4.0, I was unable to create a new session

17:22:04] I/hosted - Using the selenium server at http://localhost:5555/wd/hub
undefined
[17:22:05] E/launcher - Unable to create new service: InternetExplorerDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'LT-160501', ip: '192.168.21.101', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: unknown
[17:22:05] E/launcher - SessionNotCreatedError: Unable to create new service: InternetExplorerDriverService
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'LT-160501', ip: '192.168.21.101', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_112'
Driver info: driver.version: unknown

Here is the config
capabilities: {
browserName: 'internet explorer',
version: '11',
'ignoreProtectedModeSettings': true
},

seleniumAddress: 'http://localhost:5555/wd/hub',

**Comment by IgorSasovets** [comment]
Hi, @doshinam ! Did you try to use browser.executeScript() method to simulate right click?

**Comment by doshinam** [comment]
It worked with browser.executeScript().  Here is the code snippet I used.

return browser.executeScript(" if (document.createEvent) {"
        +"   var ev = document.createEvent('HTMLEvents');"
        +"   ev.initEvent('contextmenu', true, false);"
        +"   arguments[0].dispatchEvent(ev);"
       +"} else {" // Internet Explorer
        +"   arguments[0].fireEvent('oncontextmenu');"
       +"}", el);

Thank you

**Comment by IgorSasovets** [comment]
You are welcome! Thanks for your code snippet. I had the same issue but with Firefox browser. Here is my solution: https://github.com/IgorSasovets/protractor-firefox-support.
