### ISSUE TITLE
how to use a specific element to locate anothor equative element ？

### ISSUE THREAD

**Issue by amberjin1994** [angular/protractor#4685]
Hello !  
here is the code:  

```
// fist line
<table class="table">
<tbody class="table-body">
    <tr class="table-tree" ng-repeat="items in page">
         <td class="checkbox" >
              <input type="checkbox">
         <td class="node-name">
              <span class="node-icon" title="tree">

// second line
    <tr class="table-tree" ng-repeat="items in page">
         <td class="checkbox" >
              <input type="checkbox">
         <td class="node-name">
              <span class="node-icon" title="flower">

// third line
    <tr class="table-tree" ng-repeat="items in page">
         <td class="checkbox" >
              <input type="checkbox">
         <td class="node-name">
              <span class="node-icon" title="flower">
</tbody>
</table>

```
Im want to click the sencond checkbox , and the first line is not always present,  so i cant use $$('.checkbox').get(1) to get it,    so I trying to locate the first checkbox where has [title = "flower"],  then I write this:

```
var a = $$('[title="flower"]').get(0).getWebElement();
var b = a.getDriver().findElement(by.css('.checkbox'));
b.click();
```

but when the process finish , the first line checkbox was be click, 
whats the wrong?  and how can I fix it?

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
