### ISSUE TITLE
Finding child element in Protractor

### ISSUE THREAD

**Issue by vinodkpasi** [angular/protractor#4686]
How to get child element of parent element?
I tried this way:

          var parent =element(by.xpath('somexpath'))
           var child = parent.element(by.xpath('//h4')) // There are multiple h4 elements in page 
           child.getText().then(function(t){
                    console.log(t);
                    callback();
               })

After running I am getting following message and  getText()  returning text of first //h4 tag in page not child //h4 element of parent element 

**[18:29:04] W/element - more than one element found for locator By(xpath, //h4) - the first result will be used**

**Comment by wswebcreation** [comment]
Hi there!


Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
