### ISSUE TITLE
angular/protractor

### ISSUE THREAD

**Issue by UJURA** [angular/protractor#4698]
So i am new to cucumber. My tests results are shown before it executes. It Shows all passed even though the browser is still loading. 

Below is my *page.js

var CalculatorPage = function() {
  //const {setDefaultTimeout} = require('cucumber');

  this.get = function() {
    browser.get('');
        };

Below is my steps.js file

 this.Given(/^The LoginPage is open$/, function () {
    this.page.get();
     });

**Comment by NickTomlin** [comment]
Hi there!

Your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

Thanks!
