### ISSUE TITLE
Is there any progress on including by.model/by.binding to be used with Angular2 and above.

### ISSUE THREAD

**Issue by twaraich** [angular/protractor#4717]
Hey,
I have already looked into the StackOverFlow questions related to my question but I just wanted to ask if there is any current development going on to help use by.model/by.bindings instead of by.css for testing angular 2 and above apps .

References : 
 https://angular.io/guide/upgrade#e2e-tests 
https://stackoverflow.com/questions/36201691/protractor-angular-2-failed-unknown-error-angular-is-not-defined

**Comment by qiyigg** [comment]
@twaraich sorry, there's no plan for supporting by.model/by.bindings in angular2 right now.
