### ISSUE TITLE
How to get deviceName value from Multicapabilities definition at run time 

### ISSUE THREAD

**Issue by kat0072** [angular/protractor#4719]
Hi Team,

This might be repeated question for you guys but really I didn't answer yet.
Here is my multi-capabilities definition in protractor config file.
I want to access the deviceName parameter value. How can I do it?

```
exports.config = {
directConnect:true,
    multiCapabilities: [
        {
            browserName: 'chrome',
            'chromeOptions': {
                'mobileEmulation': {
                    'deviceName': 'iPad'
                }
            }
        }
],
```

Tried under onPrepare but not giving multi-capabilities values

```
browser.getCapabilities().then(function(c) {
            console.log(c.get('deviceName'));
        });
```

**Comment by IgorSasovets** [comment]
Hi, @kat0072 ! You can do it using browser.getProcessedConfig() function.

**Comment by kat0072** [comment]
@IgorSasovets it worked. Can you please tell me that how I can access the value outside the function...
I tried assigning it to a global variable defined in the config but didnt worked and cannot access its value outside the function.

**Comment by IgorSasovets** [comment]
@kat0072,  please take a look at [get-config-capabilities](https://github.com/IgorSasovets/get-config-capabilities) for requested example.

**Comment by kat0072** [comment]
thanks, buddy got it.

**Comment by Ashish-chamoli002** [comment]
Above mentioned works fine if my config is in .JS but if I create config file in TS format. it doesn't work.
