### ISSUE TITLE
MobileEmulation resized incorrectly in Chrome v65

### ISSUE THREAD

**Issue by uscengineer** [angular/protractor#4731]
When using MobileEmulation(iPhone 6 Plus) in Chrome v65 the view resizes incorrectly only showing the top left corner of the page. I have tested this with chromedriver v2.35 and v2.36 with the issue appearing in both. The page loads correctly in MobileEmulation mode if I do this manually (without protractor). The page I am using is internal but here is an example from another site:

- Node Version: `7.8.0`
- Protractor Version: `5.3.0`
- Browser(s): `Chrome v65`
- Operating System and Version `OSX 10.12.6`

![image](https://user-images.githubusercontent.com/4692975/37365320-63aab878-26ba-11e8-8260-cad8d8ddfbe6.png)

**Comment by IgorSasovets** [comment]
Hi, @uscengineer ! Maybe there are some problems with your configuration or tests. Same behaviour works as expected for me. 
- Protractor version: 5.3.0
- Chrome browser: v.65
- node: v.8.9.4
- chromedriver: 2.36 
![test](https://user-images.githubusercontent.com/27974884/37371795-4c02ea10-2719-11e8-98ac-62413ab15a94.png)
![chrome](https://user-images.githubusercontent.com/27974884/37371796-4c225242-2719-11e8-839a-2e8fa7bcc217.png)

**Comment by uscengineer** [comment]
@IgorSasovets after restarting my IDE and system I can no longer reproduce this issue. Thanks!
