### ISSUE TITLE
Can somebody tell me how can I run multiple specs from the sub-folders?

### ISSUE THREAD

**Issue by aasimali** [angular/protractor#4743]
Hi, 

My folder structure is..  **D:/ protractor/test**

folder 1  _(D:/ protractor/test/folder1/myspec.js)_

      -myspec.js

folder 2  _(D:/ protractor/test/folder2/sub-folder1/myspec2.js)_

    -sub-folder1
       --myspec2.js

    sub-folder2
        ---myspec3.js

and so on..
**Now, I just want to keep a single configuration file for all the specs, so that, I can run all the spec at once.**

**Comment by IgorSasovets** [comment]
Hi, @aasimali ! You can add it to specs list in your config file.

**Comment by aasimali** [comment]
@IgorSasovets - Thank you. Actually, I had more than 50-60 specs file in different different folders including more than 1k test cases,  So, adding all the files one by one in the config was not an appropriate way, So, I have used 'glob' npm module to handle the situation as of now.

@IgorSasovets - It will be helpful, if you can help me out on this too? [issue](https://github.com/angular/protractor/issues/4739)
