### ISSUE TITLE
Protractor taking long time to load the Page. Manually it is loading quickly.

### ISSUE THREAD

**Issue by binpol** [angular/protractor#4746]
I am trying to access the page https://www.dice.com/employer/login.  Manually it is loading in ms. Where as with protractor, it is taking 1 minute, 16 seconds.

**Comment by IgorSasovets** [comment]
Hi, @binpol ! Probably there might be some problems in test or configuration file. For me all works as expected. If you are interested in, I can provide simple test case example.

**Comment by binpol** [comment]
Please Share, Thank you @IgorSasovets

**Comment by IgorSasovets** [comment]
@binpol , take a look at [test case example](https://github.com/IgorSasovets/protractor-long-load-bug). I investigated this issue and found out that it needs more time when you run tests first time. But even in that case test execution time achieved 30 seconds. Second run took only 12 seconds.

**Comment by binpol** [comment]
Thank you for your time and code @IgorSasovets.
