### ISSUE TITLE
[Debugger] Cannot find module '_debugger'

### ISSUE THREAD

**Issue by djom20** [angular/protractor#4750]
Hi team,

Today when I tried to use the `brw.enterRepl();`  command to run the debugger into my tests I got this weird error.

My Environment
---

- Node Version: 8.9.4
- Protractor Version: 5.2.2
- Browser(s): Chrome 65.0.3325.181
- Operating System and Version: MacOs High Sierra 10.13.3
- Output from running the test:
![image](https://user-images.githubusercontent.com/1834808/37993520-81a887fe-31d4-11e8-9c24-b562c34c7fa8.png)

- Steps to reproduce the bug
I just used `brw.enterRepl();` and I got the error where says the debugger cannot found the _debugger module.

It seems when I installed all the NPM modules, the protractor module not installed all the dependencies.

**Comment by qiyigg** [comment]
Closing because duplicate with  #4307
