### ISSUE TITLE
browser.actions().sendKeys(protractor.Key.ESCAPE).perform(); is not working on firefox browser

### ISSUE THREAD

**Issue by Iam-surendra** [angular/protractor#4757]
hi all, can any one help me how to archive this.

when we click on FlyoutAnchor its open the menu items, we need to close that menu items (manually we can close by clicking on parent (FlyoutAnchor) control ), but focus is not coming to FlyoutAnchor because menu items are overlaps the FlyoutAnchor control.

we tried with pressing the escape button by the help of below code, but this code not working on firefox browser (open issue).

browser.actions().sendKeys(protractor.Key.ESCAPE).perform();

can any one help me how to archive this.

**Comment by IgorSasovets** [comment]
Hi, @Iam-surendra ! There are problems with using Actions class on Firefox. You can try to call sendKeys() function for menu item. 
```
menuItem.sendKeys()
```

**Comment by Iam-surendra** [comment]
thanku @IgorSasovets  now its working fine.

**Comment by Iam-surendra** [comment]
Hi @IgorSasovets  Similar issue like mouse move to particulre element is not working on firefox. 

browser.actions().mouseMove(element);

can you suggest how to achieve this with out using helpers lib

**Comment by IgorSasovets** [comment]
I tried to do this but didn't find any possible solution. Similar problems I had with mouseDown, mouseUp, dragAndDrop and right click methods. That's why I decided to create [custom implementation of Action class functions](https://github.com/IgorSasovets/protractor-firefox-support).

**Comment by Iam-surendra** [comment]
ok @IgorSasovets , how to use this custom implementation of action class for mouseMove to element (we need to move to the element not with coordinates)

**Comment by IgorSasovets** [comment]
If you want to perform DnD action than just take a look at [examples](https://github.com/IgorSasovets/protractor-firefox-support/blob/master/tests/drag-and-drop-test.js). In other case, you can create simple workaround like this:
```
const location = await tgtElement.getLocation();
await browser.executeScript(helper.mouseMove, {x: Math.floor(location.x), y: Math.floor(location.y)})
```

**Comment by Iam-surendra** [comment]
Hi @IgorSasovets  i tired your helper to mouse move but looks like it doesn't work in chrome / fireforx also, or may i used the wrong approach, can you please help me house archive this challenge. 

i need to add title for the page, it a <span inside the <p tag, i used below element finder to get that span,
 **this.pageTitleId = element.all(by.css('#WACViewPanel_EditingElement .NormalTextRun')).get(0);**

![image](https://user-images.githubusercontent.com/22834029/38731386-9b31ec86-3f37-11e8-9aec-c7c3460e5046.png)

then i used this line of code for sendKeys
 browser.actions().mouseMove(this.pageTitleId).sendKeys('Test Hello').perform();

its working fine in the chrome browser. not working in the firefox browser.

then i used ur helper like below but iam getting the error at sendkeys.

var location = this.pageTitleId.getLocation();
browser.executeScript(helper.mouseMove, {x: Math.floor(this.pageTitleId.x), y: Math.floor(this.pageTitleId.y)})

or

browser.executeScript(helper.mouseMove,{ x: 441, y: 192});

getting the below error


   Failed: unknown error: cannot focus element
      (Session info: chrome=65.0.3325.181)
      (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.16299 x86_64)

**firefox**

 Failed: Element <span class="NormalTextRun"> is not reachable by keyboard

**Comment by santirogu** [comment]
https://github.com/angular/protractor/issues/4757#issuecomment-378381829

Excelente, it was very useful for me.

**Comment by deepakbohra** [comment]
In firefox browser ,  await browser.actions().sendKeys(protractor.Key.ENTER).perform(); is not working . Is there any way it can work ?
