### ISSUE TITLE
Breaking Change in 5.1.1 to change default selenium relay protocol to 'https'

### ISSUE THREAD

**Issue by martin770** [angular/protractor#4770]
A feature was added in protractor 5.1.1 that broke my ability to run tests on sauce labs.

feat(saucelabs): Add Sauce Labs HTTPS Support (#4071) -- [commit](https://github.com/angular/protractor/commit/3edd62eccccb67ec7cb71b8c3d8b2c2921a6f7ca)

Version 5.1.1 added this commit to change the default protocol for the sauce labs selenium relay to 'https' instead of the previous 'http'. This should be pointed out as a **breaking change in the changelog.md file**.

Version 5.1.2 added the ability to change the protocol via a **new configuration option** (protractor.conf.js sauceSeleniumUseHttp). This new configuration option should be mentioned in the changelog.

It took me a bit of time to track down the problem as I was upgrading from 4.0.14 to 5.2.0. And in this case, 5.1.1 is completely unusable on sauce labs.

Bug report
---

- Node Version: `6.9.1`
- Protractor Version: `5.1.2`
- Angular Version: `n/a`
- Browser(s): `any (sauce labs via sauce-connect-launcher)`
- Operating System and Version `linux`
- Your protractor configuration file
(sauceSeleniumAddress points to selenium relay started via the sauce-connect-launcher npm module)
`sauceSeleniumAddress: localhost:47521/wd/hub`
`sauceSeleniumUseHttp: null`
- A relevant example test `any`
- Output from running the test
`[12:55:21] E/launcher - EPROTO write EPROTO 139622020233088:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:`

**Comment by qiyigg** [comment]
Would you mind sending a PR for this? Since you have a clear understanding of this problem

**Comment by martin770** [comment]
Pull Request #4793 

https://github.com/angular/protractor/pull/4793
