### ISSUE TITLE
alert.accept not working 

### ISSUE THREAD

**Issue by uinest** [angular/protractor#4775]
Hi , 

I am trying to accept an alert and here is my code. Inspite of accepting i see there is no change in the application. 
Ex : deleting a item from the list -- user is alerted -- alert is accepted. But the item still exists. 

    await browser.switchTo().alert();
    await alert.accept();
    await browser.switchTo().defaultContent();

I tried to refresh the browser after accepting the alert to see if there is any change. That dint work either. 

Is there a known issue with this ? 

Bug report
---

- Node Version: 8.6.0
- Protractor Version: 5.3.0
- Angular Version: 5
- Browser(s): Chrome
- Operating System and Version Mac High Sierra
- A relevant example : included

**Comment by IgorSasovets** [comment]
Hi, @uinest ! Can you provide link to your application if it possible or at least to relevant example of app with such functionality?

**Comment by uinest** [comment]
@IgorSasovets  , hey i cannot share my application.  Unfortunately i donno if any other app has the same issue.

**Comment by uinest** [comment]
But this has been bothering me since long time now. I tried changing the code here and there to see if it works .. but no use.

**Comment by uinest** [comment]
Code to delete and this is when the alert is prompted : 

if (window.confirm('This will delete the item. Do you want to proceed?')) {
      this.itemService.deleteItem(this.Item);
    }
  }. 
When the user clicks on delete and user is alerted

**Comment by IgorSasovets** [comment]
Ok, I'll try to solve this problem. But at first please take a look at [this example](https://www.jquery-az.com/javascript/demo.php?ex=151.1_1) and describe is it similar to your functionality because for me it seems to be. Than I'll provide simple test case for this app.

**Comment by uinest** [comment]
Yes, it pretty much the same. My application will not return a confirmation after accepting the alert though as in the example.

**Comment by IgorSasovets** [comment]
Here is my config file:
```
exports.config = {
  specs : [ 'example_spec.js' ],
  directConnect: true,
  SELENIUM_PROMISE_MANAGER: false,
  capabilities : {
    browserName : 'chrome'
  },
  onPrepare: function() {
    browser.ignoreSynchronization = true;
  }
}
```
example_spec,js
```

const chai = require("chai");
const chaiAsPromised = require("chai-as-promised");
const expect = chai.expect;
chai.use(chaiAsPromised);


describe('Confirm accept', function() {
	const showConfirmButton = $('.indtd>button');
	it('should successfully accept confirm', async function() {
      browser.get("https://www.jquery-az.com/javascript/demo.php?ex=151.1_1");
      browser.wait(protractor.ExpectedConditions.visibilityOf(showConfirmButton), 8000);
		  return browser.sleep(5000)
				.then(() => showConfirmButton.click())
				.then(() => browser.sleep(3000))
				.then(() => browser.switchTo().alert().accept())
				.then(() => browser.sleep(2000))
				.then(() => {
					const notifyAlert = browser.switchTo().alert();
					return notifyAlert.getText();
				})
				.then(text => {
					expect(text).to.equal('Your Account deleted!');
				});

	});
});
```

**Comment by IgorSasovets** [comment]
Ok, this is example where I used async/await (same config):
```
const chai = require("chai");
const chaiAsPromised = require("chai-as-promised");
const expect = chai.expect;
chai.use(chaiAsPromised);


describe('Confirm accept', function() {
	const showConfirmButton = $('.indtd>button');
	it('should successfully accept confirm', async function() {
      await browser.get("https://www.jquery-az.com/javascript/demo.php?ex=151.1_1");
      await browser.sleep(5000);
		  await showConfirmButton.click();
			await browser.switchTo().alert().accept();
		  await browser.sleep(2000);
		  const notifyAlert = await browser.switchTo().alert().getText();
			expect(notifyAlert).to.equal('Your Account deleted!');
	});
});
```
In your code you try to call accept() function of undefined. If I do the same in my code I'll get 'alert is not defined '. So, please try to use next command:
```
await browser.switchTo().alert().accept();
```

**Comment by uinest** [comment]
Sorry for the late response. I dont get it to working still. i use the following code : 

    browser.wait(protractor.ExpectedConditions.alertIsPresent(), 1000);
    await browser.switchTo().alert().accept();
    await browser.switchTo().defaultContent();

**Comment by IgorSasovets** [comment]
@uinest , why do you use this command?
```
await browser.switchTo().defaultContent();
```
Code snippet which I posted before works as expected. There might be a lot of possible reasons why actually your tests fail. It's difficult to say exactly what's wrong without working with application because it is just guessing. So, you can try to add additional browser.sleep(5000) command after accept action and see result. Also, increase wait for 'alert is present' time. You must be sure that alert is present and than accepted. Or you can provide simple app example with same functionality.

**Comment by uinest** [comment]
I am sorry , i realised my mistake. There was no await statement before the alertIsPresent.  I added await before that and deleted switching back to defaultcontent.  Corrected code as below :  

    browser.waitForAngularEnabled(false);
    await browser.wait(protractor.ExpectedConditions.alertIsPresent(), 10000);
    await browser.switchTo().alert().accept();
    await browser.sleep(1000);
    browser.waitForAngularEnabled(true);

**Comment by uinest** [comment]
Thanks for the support. Closing the issue.

**Comment by IgorSasovets** [comment]
@uinest , I'm glad to hear that it works for you! Good luck)
