### ISSUE TITLE
Run the sample protractor script using Eclipse IDE throws error. The cmd shows SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by kannannageswaran** [angular/protractor#4777]
Hi Friends,

I am new to this tool, could you please take a look on this below error and provide your suggestions.

Bug Report:

Node Version: v9.11.1
Protractor Version: 5.3.1
Browser(s): chrome v 2.37
Operating System and Version win8 32-bit
Java v 1.8.0.161
Selenium Server 3.11.0
Webdriver-Manager v 12.0.6

Create the Java Script project in the Eclipse IDE.
Copy and paste the sample conf.js, example_spec.js files to the JS Project.
Convert the project into Tern Project.
Select the Perferences - Jasmine, Protractor.
Configure the Run settings.
Clicking Run.

IDE throws the below error

E:\EclipseWorkSpace\TestProtractor\node_modules\protractor\built\logger.js:79
    info(...msgs) {
         ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (E:\EclipseWorkSpace\TestProtractor\node_modules\protractor\built\configParser.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    
    Note: Run the same config via command prompt, it works fine.

![protractor ss](https://user-images.githubusercontent.com/38446684/38845711-6b2a5b22-4216-11e8-90eb-335bda29894a.JPG)

**Comment by masthandev** [comment]
it seems some config files are missed.  better to use vs code ide

**Comment by wswebcreation** [comment]
Hi @kannannageswaran 

First of all this issue list is for issues with Protractor, not with 3rd party tools.

From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

But here's the answer ;-). https://stackoverflow.com/questions/43893756/error-while-running-conf-js-file-from-eclipse

I'm going to close it for now.
