### ISSUE TITLE
Tests failure when run in parallel

### ISSUE THREAD

**Issue by ziXet** [angular/protractor#4779]
Bug report
---
- Node Version: `8.8.1`
- Protractor Version: `5.3.1`
- Angular Version: `4.4.6`
- Browser(s): `chrome 66`
- Operating System and Version `Linux`
- Protractor config file
```// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './e2e/**/*.spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome',
    'shardTestFiles': true,
    'maxInstances': 2
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',

  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
  }
};
```

- Ouput: https://pastebin.com/hYxtBcW2
- Steps to reproduce the bug

1. Clone this repo. https://bitbucket.org/ziXet/angular-protractor-test
2. npm install
3. npm run e2e

**Comment by gremjua** [comment]
Hi @ziXet , I had a similar problem. Some things to take into account:
- According to http://chromedriver.storage.googleapis.com/2.38/notes.txt, the chromedriver you are using (latest) supports Chrome v65-v67, make sure you have one of those versions.
- If you update Chrome it should work, but if it doesn't, you can go back to chromedriver v2.37, running something like 'webdriver-manager update --versions.chrome 2.37'

I don't think this is a Protractor issue, but the Protractor team should check it out just in case.

**Comment by ziXet** [comment]
Thanks @gremjua for the answer.
My chrome version is 66. I just changed the webdriver version to 2.37 but same problem.
Could you please try my repo to see if it works on your computer? I just want to make sure it's not the protractor issue.

**Comment by ziXet** [comment]
The error I'm getting is not consistent as well. Sometime I get "cannot reach chrome..." error and sometime it runs the test on one instance and stuck at `[09:44:38] I/launcher - 1 instance(s) of WebDriver still running` for the other instances.

**Comment by ziXet** [comment]
Edit to my previous comment: I have downgraded the webdriver to 2.37 and it wroked!

**Comment by ziXet** [comment]
@erictsai6 : No it just worked when I downgraded it to 2.37. The reason that it initially did not was because I was changing the global webdriver package not the local one which was in "node_modules/protractor/node_modeuls/webdriver-manager/selenium/" directory.

**Comment by erictsai6** [comment]
@ziXet hey, I appreciate you getting back to me so quickly.

So I'm not able to do the same downgrade to fix the same issue.  Do you mind sharing your files inside that selenium folder so I can just do a quick comparison that way? Thanks.  

chrome-response.xml
chromedriver_2.37
chromedriver_2.37.zip
gecko-response.json
geckodriver-v0.20.1
geckodriver-v0.20.1.tar.gz
selenium-server-standalone-3.11.0.jar
standalone-response.xml
update-config.json

**Comment by ziXet** [comment]
@erictsai6 everything looks fine in that dir. Just make sure that you run `ng e2e --webdriver-update false` that prevents protractor to do the auto update.

**Comment by ziXet** [comment]
BTW this is the command I ran to downgrade the webdriver: 
`./node_modules/protractor/node_modules/webdriver-manager/bin/webdriver-manager update --versions.chrome 2.37`

**Comment by erictsai6** [comment]
I found the problem.  When you run ./node_modules/.bin/webdriver-manager start you need to specify the version there too.  I am on MacOS for anyone else having this issue.  

`./node_modules/.bin/webdriver-manager start --versions.chrome=2.37`

**Comment by awarecan** [comment]
ChromeDriver issue has been fixed. See https://bugs.chromium.org/p/chromedriver/issues/detail?id=2391
Please download the new version. Please note, the version did not bumped, still 2.38

**Comment by ziXet** [comment]
@awarecan Yeah! I just confirmed that! 
I think this issue could be closed now. Thanks for the help.
