### ISSUE TITLE
How do we know index value of an element if same element used multiple times in multiple pages?

### ISSUE THREAD

**Issue by Payal96** [angular/protractor#4784]
Hello

I would like to select an element in HTML page for testing using the protractor, that element used repeatedly in multiple HTML pages. Is that will be accessed using the index of that element? then how do we get an index of that element?

Thanks

**Comment by CrispusDH** [comment]
No, it will not.

**Comment by Payal96** [comment]
Hi CrispusDH

Then is there any other way to access element? that will be more flexible according to developer point of view.

Thankyou

**Comment by qiyigg** [comment]
I don't know exactly what you mean. How do you define the index if an element is exist in multiple pages (which means they won't exist at the same time).
If you want to find an element that are used multiple times in one page, you can get it by all(locator).get(index)

By the way, I believe this question should be asked in stackoverflow. The github issue only track bug and request new feature. Close it now, Thanks!
