### ISSUE TITLE
Please configure auto-cancellation on Travis

### ISSUE THREAD

**Issue by rodrigc** [angular/protractor#4801]
Feature Request
---

Please configure auto-cancellation on Travis so that if someone
pushes multiple changes to a single branch or PR, it will cancel the previous
build and only build the tip of the branch.  See:

https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by rodrigc** [comment]
@qiyigg

**Comment by qiyigg** [comment]
Double checked the Travis config, Travis has already been set to auto-cancellation for pr and branch builds on Travis before.
