### ISSUE TITLE
Timed out waiting for asynchronous Angular tasks to finish after 500 seconds.

### ISSUE THREAD

**Issue by Suprabhad** [angular/protractor#4803]
Below is protractor config.js

`
'use strict';
exports.config = {

    seleniumAddress: 'http://localhost:4444/wd/hub',

    getPageTimeout: 60000,
    allScriptsTimeout: 500000, 
    jasmineNodeOpts: {defaultTimeoutInterval: 10000},
    ignoreUncaughtExceptions: false,

    framework: 'custom',
    // path relative to the current config file
    frameworkPath: require.resolve('protractor-cucumber-framework'),
    multiCapabilities: [{
     'browserName': 'chrome',
     'shardTestFiles' : true,
     'maxInstances' : 3,
     'maxSession':3
     }]
    /*capabilities: {
        'browserName': 'chrome',
        'chromeOptions': {
            'mobileEmulation' : {
                'deviceName': 'Google Nexus 5'
            }
        }
    }*/,

    // Spec patterns are relative to this directory.
    specs: [
        '../features/Login.feature'
    ],

    baseUrl: 'http://libris.api.dev.bv',
    params: {
        userName: 'test',
        password: 'password',
		Token:'',

        ecWait: {
            waitTime: 100000
        },
    },

    plugins: [{
        package: 'protractor-multiple-cucumber-html-reporter-plugin',
        options:{
            // read the options part
            automaticallyGenerateReport: true,
            removeExistingJsonReportFile: true,
            removeOriginalJsonReportFile: true
        }
    }],

    onPrepare: function () {
        var chai = require('chai');
        chai.use(require('chai-as-promised'));
        chai.should();
        //browser.manage().window().maximize(); // maximize the browser before executing the feature files
        var timeStamp = require('../commons/commons.js');
        timeStamp.setTimeStamp()
    },

    onComplete: function () {
        console.log('all tests have finished');
        browser.close();
    },

    // This setting tells protractor to wait for all apps

    // to load on the page instead of just the first.
    // useAllAngular2AppRoots: true,
    rootElement: '[ng-app="app"]',
    ng12Hybrid: false,

    cucumberOpts: {
        require: ['../commons/*.js', '../steps/*.js', '../support/*.js'],
        tags: false,
        strict: true,
        'no-colors': true,
        dryRun: false,
        format: ['json:cucumberReports/cucumber.json']
       // parallel: 2
    }
};
`

below is package.json

`{
  "name": "ProtractorDemo",
  "version": "0.0.0",
  "description": "protractor demo",
  "author": "Aniruddh Solanki",
  "main": "config/conf.js",
  "dependencies": {
    "chai": "^4.1.2",
    "chai-as-promised": "^7.1.1",
    "cucumber": "^4.2.1",
    "cucumber-html-reporter": "^4.0.2",
    "protractor-cucumber-framework": "^5.0.0",
    "cucumber-html-report": "^0.6.5",
    "protractor": "^5.3.1",
    "relative-path": "^1.1.0",
    "protractor-multiple-cucumber-html-reporter-plugin":"1.7.0"
  },
  "scripts": {
    "test": "./node_modules/.bin/protractor config/conf.js"
  },
  "license": "MIT"
}`

When we run the test it throws an  as below

> Timed out waiting for asynchronous Angular tasks to finish after 500 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
While waiting for element with locator - Locator: By(css selector, [ng-model="user"]).
The following tasks were pending:
 - $timeout: function c(e){t.$broadcast("$keepalive"),i.isObject(n.http)?r(n.http).success(function(n,i){u(n,i,e)}).error(function(n,i){u(n,i,e)}):e||a()}
 - $timeout: function c(){s.idling=!s.idling;var i=s.idling?"Start":"End";e.$broadcast("$idle"+i),s.idling?(a(),s.countdown=n.warningDuration,l()):u()}
[14:54:13] E/launcher - ScriptTimeoutError: asynchronous script timeout: result was not received in 500 seconds

ng-app is defined in html tag
`<html lang="en" ng-app="app" class="ng-scope">`

also tried changing rootElement: '[ng-app="app"]', to rootElement: 'html', but it does not work.

Please help

**Comment by IgorSasovets** [comment]
Hi, @Suprabhad ! What you actually trying to do? Can you provide app example and describe your aims.

**Comment by Suprabhad** [comment]
Hi @IgorSasovets  
I am trying to run the below steps for login page using the above configurations I have posted

Step defination 
'user strict';
var commons = require('../commons/commons.js');
var expect = require('chai').expect;
var assert = require('chai').assert;
const { Given, When, Then } = require('cucumber');

Given('I am on Libris Login page', { timeout: 60 * 1000 }, function () {

    browser.waitForAngularEnabled(false);
    console.log('Welcome to BRAVISSIMO Libris');
});

When('I enter username {string} and password {string} and click on login button', { timeout: 60 * 1000 }, function(username, password) {

    $('[ng-model="user"]').sendKeys(username);
    $('[ng-model="pin"]').sendKeys(password);
    $('.clearfix button').click();
    browser.waitForAngularEnabled(true);
});

The issue I am facing is the system does not enter the username and password rather gives me the message of timeout: 
"Timed out waiting for asynchronous Angular tasks to finish after 500 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular
While waiting for element with locator - Locator: By(css selector, [ng-model="user"]).
The following tasks were pending:
$timeout: function c(e){t.$broadcast("$keepalive"),i.isObject(n.http)?r(n.http).success(function(n,i){u(n,i,e)}).error(function(n,i){u(n,i,e)}):e||a()}
$timeout: function c(){s.idling=!s.idling;var i=s.idling?"Start":"End";e.$broadcast("$idle"+i),s.idling?(a(),s.countdown=n.warningDuration,l()):u()}
[14:54:13] E/launcher - ScriptTimeoutError: asynchronous script timeout: result was not received in 500 seconds"
My aim is to run few set of test cases for an application build using angular js.

**Comment by IgorSasovets** [comment]
Thanks for detailed description! If you want to work with non-angular app and be confident that target element presented on page, please take a look at [this issue](https://github.com/angular/protractor/issues/4726). To handle this I use [offsetParent](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) property of DOM element and protractor.execureScript() function. Small example:
```
const isElementVisible = await browser.executeScript('return document.querySelector(\'.contentCollection.mobile-tablet-only\').offsetParent');
```
If isElementVisible not null, you can interact with it. So, to use this approach just put above code in cycle.

**Comment by IgorSasovets** [comment]
@Suprabhad , are there any updates on this issue?

**Comment by Suprabhad** [comment]
@IgorSasovets I have tried your suggestion which made it work so close the issue. Thankyou
