### ISSUE TITLE
baseUrl full path of the resource support

### ISSUE THREAD

**Issue by psech** [angular/protractor#482]
Thanks for fixing baseUrl in 0.17.0. Now it works fine with `ignoreSynchronization = true`.

It works fine for URLs like `http://domain` but does not work for `http://domain/resource_path`. The resource path is being ignored.

My AUT lies under `http://domain_name/demo` which is static for all tests.

Would it be possible to support extended paths?

**Comment by Pablodotnet** [comment]
Why we can't put the '#' in baseUrl? Like this:
baseUrl: 'http://localhost/#'
Url in spec: '/login'
For example.
Because if I do that it doesn't work, but if i put the hashtag in url in spec and not in baseUrl it works, why is that?
