### ISSUE TITLE
How to click the second binding value in the table list and getting the error as "Index out of bound."

### ISSUE THREAD

**Issue by kannannageswaran** [angular/protractor#4828]
Hi Friends!

My Scenario is compared the input data with the table value and click the corresponding element.

While running the script, a script has fetched and displayed the 'ng-binding' value in the console but not able to select the element.

A first binding name has no value (empty) and the second thing have the value. My scenario is to compare the value with the second 'ng-binding' value and click the particular row.

I have attached the HTML page table view, Console output and script.

Can you please take a look and provide the suggestion to click the expected row.

![htmlview1](https://user-images.githubusercontent.com/38446684/40608405-05839412-6289-11e8-8cd6-dc4a94ae1ad1.jpg)

![console error](https://user-images.githubusercontent.com/38446684/40608414-0b739386-6289-11e8-9a9e-22e04bd1385d.jpg)

	**```
var vDeveloper_Table = element.all(by.repeater('device in $ctrl.devices'));
			
			vDeveloper_Table.count().then(function(vcount){
				console.log("No of rows " +vcount );
			});
			
			var new1 = vDeveloper_Table.filter(function(fListItem)
			{
				//console.log(fListItem);
				return fListItem.all(by.binding('device.host')).getText().then(function(fAppLabel) {					
					console.log(fAppLabel);					
					return fAppLabel === '13.61.14.211';
				});
			});
			
			new1.get(0).element(by.css('.td')).click();
```**
Bug report
---
Node Version: v9.11.1
Protractor Version: 5.3.1
Browser(s): chrome v 2.37
Operating System and Version win7 64-bit
Java v 1.8.0.161
Selenium Server 3.11.0
Webdriver-Manager v 12.0.6

Please find the attachment.

**Comment by IgorSasovets** [comment]
Hi, @kannannageswaran ! Please provide test case example (with html page file, or at least reference to the similar project).

**Comment by yongcy** [comment]
There is an issue in your following code lines:
```
var new1 = vDeveloper_Table.filter(function(fListItem) {
    return fListItem.all(by.binding('device.host')).getText().then(function(fAppLabel) { 
            // because you used `fListItem.all` which will return an element list
            // therefor call `getText()` on an element list will return an string list
            // so `fAppLabel` is a list not a string, like ['13.61.14.211']
            // It means `fAppLabel === '13.61.14.211'` never be true.
            console.log(fAppLabel);                 
            return fAppLabel === '13.61.14.211';
        });
});
```
so the `new1` will be an empty list, when you call `new1.get(0)`, it report index out of bound as expected.
you should change to 
`return fAppLabel.includes('13.61.14.211')`

**Comment by wswebcreation** [comment]
Hi there!


Since it involves usage and debugging (and you haven't used the [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) to indicate otherwise), your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.


From the [getting help](https://github.com/angular/protractor#getting-help) section of the README.


> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
