### ISSUE TITLE
No TEXT on Web pages after updating to macOS Sierra

### ISSUE THREAD

**Issue by iamhaseebiqbal** [angular/protractor#4832]
Hi There!

I'm using a dedicated Mac-Mini for testing Angular application.

Everything was fine until i changed Mac-Mini's language to German. After restarting the Mac-Mini, it started updating macOS.

Still tests run perfectly, only problem is now i can't see any text on screen. UI elements (Images etc.) are visible during testing. Sometimes i can see different colors while loading Web Pages. Issue is that in case of failures, i'm taking screenshots and then the screenshots doesn't contain any **TEXT** and i'm unable to see the reason.

Bug report
---

- Node Version: `7.10.0`
- Protractor Version: `5.1.2`
- Angular Version: `5.2.9`
- Browser(s): `Chrome 67.0.3396.62`
- Operating System and Version `macOS Sierra 10.12.6`

const {SpecReporter} = require('jasmine-spec-reporter');
exports.config = {
    framework: 'jasmine2',
    seleniumAddress: 'http://localhost:4444/wd/hub',
    suites: {
        local: [
            './e2e/specs/login/*e2e-spec.ts'
        ]
    },
    browserName: 'chrome',
    chromeOptions: {
        args: [
            // disable chrome's wakiness
            '--disable-infobars',
            '--disable-extensions',
            'verbose',
            'log-path=/tmp/chromedriver.log'
        ],
        prefs: {
            // disable chrome's annoying password manager
            'profile.password_manager_enabled': false,
            'credentials_enable_service': false,
            'password_manager_enabled': false
        }
    },
    useAllAngular2AppRoots: true,
    allScriptsTimeout: 300000,
    getPageTimeout: 300000,
    jasmineNodeOpts: {
        isVerbose: true,
        showColors: true,
        defaultTimeoutInterval: 300000
    },
    directConnect: true,
    baseUrl: 'http://localhost:8000/',
    onPrepare: function () {
    global.utils = Object.assign(
            require('./e2e/utilities/helpers')
        );
    },
    onComplete: function () {
        utils.helpers.configureHTMLReports();//Configure HTML Reports
    }

};

**Comment by wswebcreation** [comment]
Hi there,

This doesn't look like an issue with Protractor,  but with you app. I'm going to close this issue now.

Your question is better suited for StackOverflow or Gitter. Please ask a question there.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow
 (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by iamhaseebiqbal** [comment]
@wswebcreation ! App is working fine when i run it manually. This issue during Testing only.

**Comment by iamhaseebiqbal** [comment]
[Here ](https://ibb.co/fU3oLy) is a sample of the issue.

**Comment by wswebcreation** [comment]
@iamhaseebiqbal 

Tnx for the image, can you please run it again with:

- latest version of Protractor
- clean config, so also without all the methods you add in the onprepare

reason why I'm asking this is because of the only thing protractor does that could influence the app is an async injection, the rest is clicking and so on in the app.

**Comment by iamhaseebiqbal** [comment]
@wswebcreation 

Jenkins is configured to get latest protractor and webdriver.

Protractor's Global version is 5.3.2

I made a new directory and tried with following default spec and configuration

// conf.js
```
exports.config = {
  directConnect: true,
  specs: ['todo-spec.js']
};
```

// todo-spec.js
```
describe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
  });
});
```
Still i'm facing the same issue. Please see the screenshot  below.
![protractor default conf](https://user-images.githubusercontent.com/26551451/40967970-b8f886f2-68b4-11e8-891c-89aaeb0f3196.png)

**Comment by iamhaseebiqbal** [comment]
Keeping everything the same, i updated OSX to **maxOS High Sierra 10.13.5** and everything is back on track.

**Comment by iamhaseebiqbal** [comment]
@wswebcreation If i change the language back to English and it works fine. But if i try it with German again, similar issues occur.

**Comment by iamhaseebiqbal** [comment]
For now i solved the issue by switching OS language to English and then forced protractor to run browser in German. 

> capabilities: {
>         browserName: 'chrome',
>         chromeOptions: {
>             args: [
>                 // disable chrome's wakiness
>                 '--disable-infobars',
>                 '--disable-extensions',
>                 'verbose',
>                 'log-path=/tmp/chromedriver.log'
>             ],
>             prefs: {
>                 // disable chrome's annoying password manager
>                 'profile.password_manager_enabled': false,
>                 'credentials_enable_service': false,
>                 'password_manager_enabled': false,
>                 'intl': { accept_languages: 'de-DE' }
>             }
>         }
>     },

Actual issue still exists.
