### ISSUE TITLE
I am receiving the error [Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.   Stack:     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.         at ontimeout (timers.js:460:11)         at tryOnTimeout (timers.js:298:5)         at Timer.listOnTimeout (timers.js:261:5)] using chrome 66 version

### ISSUE THREAD

**Issue by donseenugmail** [angular/protractor#4839]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by wswebcreation** [comment]
Please update the form with all needed info and change the title.

If this is an issue with Protractor itself we keep it open, else we'll close it, see the docs

**Comment by CrispusDH** [comment]
This error appears if your specs run more than this specific time jasmine.DEFAULT_TIMEOUT_INTERVAL  . You can also find description in the official doc https://jasmine.github.io/2.1/introduction at the end.

**Comment by wswebcreation** [comment]
Going to close it for now
