### ISSUE TITLE
Malicious package in protractor lib dependencies

### ISSUE THREAD

**Issue by IgorSasovets** [angular/protractor#4844]
Security issue
---

- Node Version: `8.4.0`
- Protractor Version: `5.3.2`

Hi, Team! Recently I found vulnerable package in protractor dependencies when was analyzing small protractor project using [Snyk tool](https://snyk.io/). I've opened [issue](https://github.com/angular/webdriver-js-extender/issues/19) in [webdriver-js-extender](https://github.com/angular/webdriver-js-extender) repository and now waiting for response. Issue related to usage of outdated selenium-webdriver package version. They've already fixed it and replaced adm-zip(vulnerable package previously used by selenium-webdriver). Please pay attention to this.

Best regards,
Igor
![screen shot 2018-06-04 at 12 31 29 pm](https://user-images.githubusercontent.com/27974884/40960966-ed8d0984-68a9-11e8-8af5-c8da971a0181.png)

**Comment by awarecan** [comment]
I bet this pending PR angular/webdriver-js-extender#12 will fix it.

**Comment by IgorSasovets** [comment]
Hi, @awarecan ! I think so too and waiting for feedback from core team.

**Comment by IgorSasovets** [comment]
Hi, @Quenty ! Thanks for investigation) As I said, [adm-zip replaced with jszip](https://github.com/SeleniumHQ/selenium/commit/8e77b5402b30be159b5a8d435d5487647fbe544f) in selenium-webdriver package. So, update of webdriver-js-extender dependencies will fix this issue.

**Comment by kylecordes** [comment]
(BTW, from the point of view of a casual follower of the project, it would feel a lot better if someone tagged as a contributor/owner were to drop a comment in about the likelihood of merging+shipping a fix to a scary sounding issue ("malicious package"!) promptly.)

**Comment by IgorSasovets** [comment]
Can be closed now because of #4882.
