### ISSUE TITLE
High vulnerability in ws

### ISSUE THREAD

**Issue by peter-borgstedt** [angular/protractor#4862]
Hi!
- Node Version: `10.5.0`
- Protractor Version: `5.3.2`
- Angular Version: `6.0.6`
- Operating System and Version `MacOS Sierra High`

I get the follow high vulnerability:
* High: Denial of Service
* Package: ws 
* Dependency of: protractor [dev]
* Path: protractor > webdriver-js-extender > selenium-webdriver > ws
* More info: https://nodesecurity.io/advisories/550

See https://nodesecurity.io/advisories/550

Remediation (from https://nodesecurity.io/advisories/550)
Update to version 3.3.1 or later.

**Comment by IgorSasovets** [comment]
Hi, @peter-borgstedt ! I also found [security issue](https://github.com/angular/protractor/issues/4844)  in webdriver-js-extender lib. Probably, it would be better if you create issue there to.

**Comment by qiyigg** [comment]
Both webdriver-js-extender and Protractor have released new version to update selenium to 3.x which drops the dependency of ws.
