### ISSUE TITLE
Not able to click or identify any element when logged into the application. Third party application is involved for the authentication purpose. 

### ISSUE THREAD

**Issue by pranesh517** [angular/protractor#4872]
Hello,

We are automating the Angular application using Protractor ver- 5.3.2. 

About application - The application evolves third party authentication media during login.
Issue: When tried running any script , the login is successful every time , but when we landed on the Home page, Protractor is not able to click or identify any element. We tried browser.sleep(); for that matter , but still not result. Tried $timeout and browser.wait() as well. Also when tried to get current URL from Homepage, we did not get any output, but when when we tried to get URL from Login page its working there. Need your help here.

**Comment by IgorSasovets** [comment]
Hi, @pranesh517 ! Please provide your config file and test example.

**Comment by cswanPWW** [comment]
@IgorSasovets I'm seeing a similar scenario in the tests I'm trying to set up - After it goes through the third party auth process (which is being bypassed, but it still has to pass through it), when I get to the sites home page, the test just hangs indefinitely.  Tried browser.wait() and browser.sleep().  Theres nothing in the console, as it seems to just stop running entirely.  Below is my config and test  (with specific values omitted).  Sorry if I'm hijacking this incorrectly @pranesh517 , please let me know if so.  

conf.js: 
exports.config = {
    seleniumAddress: 'http://localhost:4444/wd/hub',
    getPageTimeout: 60000,
    allScriptsTimeout: 500000,
    framework:'jasmine',
      jasmineNodeOpts: {
          showColors: true,
          defaultTimeoutInterval: 3600000
      },
    capabilities: {
    'browserName': 'chrome'
    },
    specs: [
        '../specs/loginTests.js'
    ],
  };

describe('login', function() {

    var Main = require('../pages/main.js');
    var Login = require('../pages/login.js');
    var Dashboard = require('../pages/dash.js');
    var lp = new Login();
    var mp = new Main();
    var dash = new Dashboard();

    beforeEach(function() {
        browser.get('*/Site URL/*')
    });

    it('should display all page elements', function(){
        expect((mp.Banner).isDisplayed());
        expect((mp.idlogo).isDisplayed());
        expect((lp.introText).isDisplayed());
        expect((lp.introTitle).isDisplayed());
        expect((lp.introDesc).isDisplayed());
        expect((lp.username).isDisplayed());
        expect((lp.password).isDisplayed());
        expect((lp.loginButton).isDisplayed());
        expect((lp.forgotPassword).isDisplayed());
        expect((mp.footer).isDisplayed());
    });

    it('should allow active admin to log in with valid password', function(){
        lp.username.sendKeys('/*USERNAME*/');
        lp.password.sendKeys('invalidpass');
        expect((lp.loginError).isPresent()).toBe(false);
        lp.loginButton.click();
        expect((lp.loginError).isDisplayed());
        lp.password.clear();
        lp.password.sendKeys('/*PASSWORD*/');
        lp.loginButton.click();
        browser.wait(protractor.ExpectedConditions.visibilityOf(dash.greeting), 5000);
        mp.logOut.click();
    }); 

    });

});

Thanks in advance for any insight you can provide!

**Comment by cswanPWW** [comment]
Thank you @IgorSasovets !  This solution worked perfectly.

**Comment by cswanPWW** [comment]
@CrispusDH I kinda hijacked the issue, wasn't mine to begin with, so I can't close.

**Comment by IgorSasovets** [comment]
@cswanPWW , not at all)
