### ISSUE TITLE
How to use mat-paginator with protractor

### ISSUE THREAD

**Issue by avne31** [angular/protractor#4881]
Hi,

not able to access next and previous arrow neither the **pageSizeOptions** through protractor.

thanks!

**Comment by IgorSasovets** [comment]
Hi, @avne31 ! Please provide your config file and test example.

**Comment by avne31** [comment]
this is the screenshot where i have to click
**Screenshot**
![capture](https://user-images.githubusercontent.com/38249841/42721094-84d24712-8751-11e8-904e-ca2702e117c4.PNG)

this one is the HTML code that i supposed to use for getting the element
**HTML FILE**
` <mat-paginator [length]="dataSource.data.length" [pageSize]="5" [pageSizeOptions]="[5, 10, 25]">
                </mat-paginator>`

this one is the main config file
**CONFIG FILE**
`exports.config = {
  allScriptsTimeout: 50000,
  specs: ['./e2e/app/app.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 200000,
    print: function () { }
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(
      new Jasmine2HtmlReporter({
        savePath: 'target/',
        screenshotsFolder: 'images',
        takeScreenshots: true,
        consolidate: true,
        consolidateAll: true,
        cleanDestination: true,
        fixedScreenshotName: true
      })
    );
  }`

so here, 
1. I want to click on next and previous arrow provided by mat-paginator.
2. Click on PageSizeOption to select particular pagesize through protractor.

**Comment by IgorSasovets** [comment]
@avne31 , here are some basic tests for mat-paginator component. To work with material components tou have to disable synchronization. In tests I used custom synchronization using `browser.sleep()` method but you can add another type of synchronization (e.g. using `offsetParent` option of DOM element). Also, I used [protractor-firefox-support](https://github.com/IgorSasovets/protractor-firefox-support) because sometimes standard `click` protractor function doesn't work with material select component.
conf.js
```
const Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');

exports.config = {
  allScriptsTimeout: 50000,
  specs: ['spec.js'],
  capabilities: {
    browserName: 'chrome'
  },
  
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 200000,
    print: function () { }
  },
  onPrepare() {
	browser.ignoreSynchronization = true;
    /*require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });*/
    jasmine.getEnv().addReporter(
      new Jasmine2HtmlReporter({
        savePath: 'target/',
        screenshotsFolder: 'images',
        takeScreenshots: true,
        consolidate: true,
        consolidateAll: true,
        cleanDestination: true,
        fixedScreenshotName: true
      })
    );
  }
}
```
spec.js
```
'use strict';
const support = require('protractor-firefox-support');
const EC = protractor.ExpectedConditions;

describe('Material paginator test', () => {
  beforeAll(async() => {
    await browser.get('https://material.angular.io/components/paginator/examples');
    await browser.sleep(5000);
  });
  it('Should click on \'Next\' button', async() => {
    await $('button[aria-label=\'Next page\']').click();
	await browser.sleep(1000);
    await expect($('.mat-paginator-range-label').getAttribute('innerText')).toEqual('11 - 20 of 100');
  });
  it('Should click on \'Previous\' button', async() => {
    await $('button[aria-label=\'Previous page\']').click();
	await browser.sleep(1000);
    await expect($('.mat-paginator-range-label').getAttribute('innerText')).toEqual('1 - 10 of 100');
  });
  it('Should change list length to 10 items per page', async() => {
    await $('mat-select>div').click();
	await browser.sleep(300);
    await browser.executeScript(support.mouseClick, {selector: 'mat-option>.mat-option-text', elementIndex: 0});
    await expect($('.mat-paginator-range-label').getAttribute('innerText')).toEqual('1 - 5 of 100');
  });
});
```

**Comment by IgorSasovets** [comment]
![image](https://user-images.githubusercontent.com/27974884/42725987-e31c9eaa-8795-11e8-98e4-c6e4a9e6ed5b.png)

**Comment by IgorSasovets** [comment]
@avne31 , did it help you?

**Comment by avne31** [comment]
hi @IgorSasovets 

thank you so much.It's working perfect

It would be a great help if you will answer some of my questions as i'm beginner in protractor 
1. In config file you are using `browser.ignoreSynchronization = true;` but as far as i have seen we apply
 `browser.ignoreSynchronization = true;` if it is a non-angular app.So the above example that you have provided is of non-angular app?
2.  ```
 $('mat-select>div').click();
	await browser.sleep(300);
    await browser.executeScript(support.mouseClick, {selector: 'mat-option>.mat-option-text', elementIndex: 0});
```
can you please tell me how you did it because in my html file i don't see any these type of elements and tags?

**Comment by IgorSasovets** [comment]
Mentioned option usage caused by material components structure. Otherwise, protractor will wait infinitely and tests execution fail. `mat-option` components appear when you click on material selector. Otherwise, they are hidden. Also, if you had some questions, please email me. I'm ready to share my experience and help with such issues. Please close this issue because it's resolved.

**Comment by avne31** [comment]
Thanks!! It really helped me alot.

Please share your mail Id for the future assistance.

I'm closing this issue.

**Comment by IgorSasovets** [comment]
You can find my email on my profile page)
