### ISSUE TITLE
sendkeys is not working in input through protractor

### ISSUE THREAD

**Issue by avne31** [angular/protractor#4888]
Hello,

I'm trying to pass sendkeys in input but unable to do so.

i successfully click on it(**first screenshot**)

![first](https://user-images.githubusercontent.com/38249841/42876256-bfb2fce6-8aa3-11e8-8d09-41c51f5bd2ed.PNG)

after clicking on it (**+**)dailog box opens to fill the input in the given field(screenshot attached)

(see in **second screenshot**)

![second](https://user-images.githubusercontent.com/38249841/42876345-fca44394-8aa3-11e8-87bd-efb11db5d966.PNG)

**HTML file** of this:

` <div>
      <label>Enter payment mode : </label>
      <mat-form-field class="w-100">
        <input #paymentMode matInput autocomplete="off"/>
      </mat-form-field>
    </div>`

in input field i'm unable to pass sendkeys like credit card, paypal etc.

so please let me know if there is any away of doing this

thanks

**Comment by IgorSasovets** [comment]
Hi, @avne31 ! Please provide you config file and test example.

**Comment by avne31** [comment]
hi, @IgorSasovets 

thanks for instant reply

**`config file:`**

``exports.config = {
  allScriptsTimeout: 50000,
  specs: ['./e2e/app/app.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 200000,
    print: function () { }
  },
  onPrepare() {
    require('ts-node').register({
      project: 'e2e/tsconfig.e2e.json'
    });
    jasmine.getEnv().addReporter(
      new Jasmine2HtmlReporter({
        savePath: 'target/',
        screenshotsFolder: 'images',
        takeScreenshots: true,
        consolidate: true,
        consolidateAll: true,
        cleanDestination: true,
        fixedScreenshotName: true
      })
    );
  }``

Can you please tell me, what test example you wants as we have already provided you the HTML code and the screenshot

**Comment by IgorSasovets** [comment]
@avne31 , I need basic example because it would save my time. Otherwise, I will have to create own test case example for issue.

**Comment by avne31** [comment]
@IgorSasovets ,

**abc.e2e-spec.ts**

`describe('User Profile Test Cases', () => {
  beforeEach(() => {
    let userPage = new AbcPage();
    browser.waitForAngularEnabled(false); 
  });

    it('User Remove Services', () => {
    userPage.userProfileDashboard();
    userPage.removeServices();
  });
`
**abc.po.ts**

```
export class AbcPage { 
removeServices() {
const input = element.all(by.tagName('input')).get(1);
browser.wait(EC.visibilityOf(input));
input.sendKeys('Text');
}
}

```
the function in po file is not working.
we have taken `element.all(by.tagName('input')).get(1);` because in that particular screen we have one more input element

**Comment by IgorSasovets** [comment]
Thanks, I'll dive into it.

**Comment by IgorSasovets** [comment]
@avne31 , try this example:
`conf.js`
```
const Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');

exports.config = {
allScriptsTimeout: 50000,
specs: ['spec.js'
],
capabilities: {
 browserName: 'chrome'
},

directConnect: true,
baseUrl: 'http://localhost:4200/',
framework: 'jasmine',
jasmineNodeOpts: {
showColors: true,
defaultTimeoutInterval: 200000,
print: function () { }
},
onPrepare() {
/*require('ts-node').register({
project: 'e2e/tsconfig.e2e.json'
});*/
jasmine.getEnv().addReporter(
new Jasmine2HtmlReporter({
savePath: 'target/',
screenshotsFolder: 'images',
takeScreenshots: true,
consolidate: true,
consolidateAll: true,
cleanDestination: true,
fixedScreenshotName: true
})
);
}
};
```
`spec.js`
```
const EC = protractor.ExpectedConditions;

describe('Material input test case', () => {
  it('Should change input component value', async() => {
    await browser.get('https://material.angular.io/components/input/examples');
    await browser.wait(EC.elementToBeClickable($('.mat-button-wrapper>.mat-icon')), 5000);
    const emailInputField = $$('.mat-form-field-infix>input').get(1);
    await emailInputField.sendKeys('invalid');
    expect($('mat-error').isPresent()).toBe(true);
  });
});
```

**Comment by avne31** [comment]
it's working fine... thanks for the help.
