### ISSUE TITLE
Not able to click on radio button in Internet Explorer 11

### ISSUE THREAD

**Issue by Gaurav08021989** [angular/protractor#4893]
Hi All,

I am not able to click on radio button male nor the submit buttons. It is able to detect the xpath but not able to click it in IE 11  
The functionality is working fine in Google Chrome browser.

PFB the details of my files

- Node Version: ``10.5.0
- Protractor Version: ``5.3.2
- Angular Version: ``
- Browser(s): ``Internet Explorer
- Operating System and Version ``Windows 10
- Your protractor configuration file
// An example configuration file.
exports.config = {
 seleniumAddress: 'http://localhost:4444/wd/hub',
 capabilities: {
		'browserName': 'internet explorer',
		'platform': 'ANY',
		'version': '11',
         'nativeEvents': false,
        'unexpectedAlertBehaviour': 'accept',
        'ignoreProtectedModeSettings': true,
        'enablePersistentHover': true,
        'disable-popup-blocking': true
		
  },
   framework: 'jasmine',
 specs: ['zoo_spec.js'],
 jasmineNodeOpts: {
defaultTimeoutInterval: 60000,
},
};
- A relevant example test 
zoo.js
describe ("Test site for input field",function(){
	it("to test input field and check output",function() {
		browser.waitForAngularEnabled(false);
		browser.ignoreSynchronization = true;
		browser.driver.get("http://automationcop.blogspot.com");
		browser.driver.sleep(3000);
		browser.driver.findElement(by.id("firstname")).clear();
		browser.driver.findElement(by.id("firstname")).sendKeys("Gaurav");
		browser.driver.findElement(by.id("lname")).clear();
		browser.driver.findElement(by.id("lname")).sendKeys("Shetty");
		element(by.id("male")).click().then(function(){ console.log("clicked"); });
	
		element(by.buttonText('Submit')).click();
		browser.driver.sleep(3000);

		
	});
	
	
});

- Output from running the test:Doesnt give any error but passes the test
- Steps to reproduce the bug: Run the zoo.js file 
- The URL you are running your tests against (if relevant):http://automationcop.blogspot.com

**Comment by IgorSasovets** [comment]
Hi, @Gaurav08021989 ! I will try your example on IE 10. Will it be OK for you?

**Comment by IgorSasovets** [comment]
I modified your example and tested it on IE 10, OS - Windows 7, IE webdriver - 3.13.0. Test passed. Try it and provide feedback. Before test manually run IE driver from <path_to_project_root_folder>\node_modules\protractor\node_modules\webdriver-manager\selenium (I used IEDriverServer3.13.0.exe) and then start tests.
config.js
```
exports.config = {
  //directConnect: true,
  //TO RUN UNDER IE MANUALLY LAUNCH DRIVER IN node_modules\protractor\node_modules\selenium\<ie_driver>
  seleniumAddress: 'http://localhost:5555',
  capabilities: {
    browserName: 'internet explorer',
    ignoreProtectedModeSettings: true,
	nativeEvents: false,
	unexpectedAlertBehaviour: 'accept',
	ignoreProtectedModeSettings: true,
	enablePersistentHover: true,
	'disable-popup-blocking': true
  },
  specs: [
    'zoo_spec.js'
  ],
  framework: 'jasmine',
  localSeleniumStandaloneOpts: {
    jvmArgs: [
      '-Dwebdriver.ie.driver=./node_modules/protractor/node_modules/webdriver-manager/selenium/IEDriverServer3.13.0.exe'
    ]
  },
  jasmineNodeOpts: {
	defaultTimeoutInterval: 60000
  }
}
```
zoo_spec.js
```
'use strict';

describe("Test site for input field",function(){
    beforeAll(() => {
		browser.ignoreSynchronization = true;
		browser.driver.get("http://automationcop.blogspot.com");
		browser.driver.sleep(3000);
	});
	it("to test input field and check output",function() {
		browser.driver.findElement(by.id("firstname")).clear();
		browser.driver.findElement(by.id("firstname")).sendKeys("Gaurav");
		browser.driver.findElement(by.id("lname")).clear();
		browser.driver.findElement(by.id("lname")).sendKeys("Shetty");
		element(by.id("male")).click().then(function(){ console.log("clicked"); });
		element(by.buttonText('Submit')).click();
		browser.driver.sleep(3000);
	});
});
```

**Comment by Gaurav08021989** [comment]
hi @IgorSasovets...Thanks for your response...It worked for me...

**Comment by navinika** [comment]
Wow this is really amazing post. Thanks for sharing the useful informative data. I appreciate your difficulty work. Keep blogging.<a href="https://www.emexotechnologies.com/courses/software-testing-training/protractor-training/
"> Protractor Training in Electronic City </a>
