### ISSUE TITLE
While using Md-select ,How to drop down list in protractor?

### ISSUE THREAD

**Issue by nikhiletc** [angular/protractor#4895]
<md-select ng-model="card.type" name="type" aria-label="Select card type" ng-change="$ctrl.onCardSelectionChange(card);$ctrl.onChange(true)" cmtr-no-multiple-bahn-cards="" required="" class="ng-pristine ng-empty ng-invalid ng-invalid-required ng-valid-cmtr-no-multiple-bahn-cards ng-touched" tabindex="0" aria-disabled="false" role="listbox" aria-expanded="false" aria-multiselectable="false" id="select_2162" aria-invalid="true" aria-required="true" aria-owns="select_container_2163" style=""><md-select-value class="md-select-value md-select-placeholder" id="select_value_label_2161"><span>Type</span><span class="md-select-icon" aria-hidden="true"></span></md-select-value></md-select>
<div class="md-select-menu-container md-active md-clickable" aria-hidden="false" role="presentation" id="select_container_2163" style="display: block; left: 52px; top: 137px; min-width: 295.797px; font-size: 16px;"><md-select-menu role="presentation" class="_md" style="transform-origin: 147.898px 8px 0px;"><md-content class="_md">
          <md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2166" aria-checked="true" value="blue_biz"><div class="md-text">
            Blue Biz (AF/KL)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2167" aria-checked="true" value="partner_plus_benefit_lh"><div class="md-text">
            Partner Plus Benefit (LH)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2168" aria-checked="true" value="onbusiness_ba_aa_ib"><div class="md-text">
            OnBusiness (BA/AA/IB)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2169" aria-checked="true" value="SK"><div class="md-text">
            SAS Credit (SK)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2170" aria-checked="true" value="AY"><div class="md-text">
            Finnair Plus (AY)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2171" aria-checked="true" value="DY"><div class="md-text">
            Norwegian Reward (DY)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2172" aria-checked="true" value="D8"><div class="md-text">
            Norwegian Reward (D8)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2173" aria-checked="true" value="EK"><div class="md-text">
            Skywards (EK)
          </div></md-option><md-option ng-repeat="loyaltyCard in ::$ctrl.loyaltyCards" ng-value="::loyaltyCard.value" tabindex="0" class="md-ink-ripple" role="option" aria-selected="false" id="select_option_2174" aria-checked="true" value="TP"><div class="md-text">
            Air Portugal (TAP)
          </div></md-option>
        </md-content></md-select-menu></div>

I have tried different ways ,but none of the thing worked ((
https://stackoverflow.com/questions/51422064/while-using-md-select-how-to-drop-down-list-in-protractor

**Comment by IgorSasovets** [comment]
Hi, @nikhiletc ! Please provide your config file and test example. I have a deal with such type of issues)

**Comment by nikhiletc** [comment]
/* global angular */
// use should
/* eslint-disable no-unused-vars */
const should = require('should');
/* eslint-enable no-unused-vars */

const utvaraToken = require('ct-factories/jwt').generateUtvaraToken();

// use local https
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

exports.config = {
  framework: 'mocha',
  mochaOpts: {
    reporter: "spec",
    slow: 10000,
    ui: "bdd",
    timeout: 600000
  },
  seleniumAddress: 'http://selenium:4444/wd/hub',
  specs: ['helpers/init_db.js', 'cockpit/**/*.spec.js'],

  onPrepare: function() {
    browser.driver.get('http://cockpit');

    // Disable animations so e2e tests run more quickly
    let disableNgAnimate = function() {
      angular.module('disableNgAnimate', []).run(['$animate', function($animate) {
        $animate.enabled(false);
      }]);
    };

    browser.addMockModule('disableNgAnimate', disableNgAnimate);

    return browser.manage()
      .addCookie('gtoken', utvaraToken, '/', 'cockpit');
  }
};
--------------------------------spec.js
`"use strict";
const Company = require('./company.page-object');
const { createCompany } = require('../../helpers/util');
const faker = require("faker");
describe('Company', () => {
    let companyData = null;
    beforeEach(() => {
        return createCompany()
            .then(company => {
                companyData = company;
            });
    });
    describe('- Company list -', () => {
        it('company list should work', () => {
            browser.get('http://cockpit/#/company-list');
            let companies = $$('[md-virtual-repeat="company in ctrl.filteredCollection"]'),
                companyElement = companies.get(0);
            // the assertion        companyElement.element(by.binding('company.name')).getText().should.be.finally.equal(companyData.name);
        });
    });
    describe('- Company detail -', () => {
        /** @type {Company} **/
        let company;
        beforeEach((done) => {
            browser.get(`http://cockpit/#/company-detail/${companyData._id}`);
            company = new Company();
            done();
        });
        it.only('Loyalty card should be saved ',()=>{
            console.log(' test the loyalty');
            company.switchTab('Loyalty cards');
            browser.sleep(2000);
            let adLoyaltyCard = company.addcard;
            adLoyaltyCard.add_card.click();
            browser.sleep(3000);
                            adLoyaltyCard.cardnum.sendKeys("12345676543");
                         adLoyaltyCard.cardpin.sendKeys("12343");
                         adLoyaltyCard.cardstatus.sendKeys('');
                         adLoyaltyCard.expire.sendKeys('');
                      adLoyaltyCard.cardtype.click();
                         //adLoyaltyCard.saveit.click();
                         console.log(' loyalty test failed ?');*/
        });  
});
`_----------------
`"use strict"
class AddLoyaltyCard {
    constructor() {
        this.add_card = element(by.buttonText('+ add card'));
        browser.driver.sleep(3000);
    }
          this.cardnum  = element(by.model('card.card_number'));
          this.expire = element(by.model('card.expires_at'));
          this.cardpin = element(by.model('card.pin'));
          this.cardstatus = element(by.model('card.status'));
          // this.saveit = element(by.model('Ok'));
          browser.sleep(3000);
      console.log(' what happened with you ?');
      browser.sleep(3000);
}
module.exports = AddLoyaltyCard;
`

**Comment by IgorSasovets** [comment]
Thanks, I'll check it.

**Comment by nikhiletc** [comment]
yeah sure, i am only stuck in this part, (((

**Comment by IgorSasovets** [comment]
Great)) Yesterday I added examples of using protractor with angular-material components. One of tests includes interaction with `mat-select` component. Here is [link](https://github.com/angular/protractor/blob/master/example/angular_material/mat_paginator_spec.js). Test name -> "Should change list length to 5 items per page". Try it and provide feedback about the results.

**Comment by nikhiletc** [comment]
finally able to click on drop down 
var dropdown = element(by.model('card.type'));
          var dropdownItems = element.all(by.repeater("loyaltyCard in ::$ctrl.loyaltyCards"));
          dropdown.click().then(() => {
              dropdownItems.get(2).click();
          });
