### ISSUE TITLE
Protractor E2E test times out when app polls an API at regular intervals

### ISSUE THREAD

**Issue by stickel** [angular/protractor#49]
Our app has a poller which makes calls to an API every 3 seconds. When I load a page with has an active instance of the poller Protractor will always time out.

The poller is started when the page loads and uses the Angular `$timeout` function.

Is there a way to get Protractor to ignore the poller or send a signal to the app to pause the poller momentarily so the E2E test can finish running?

**Comment by nvsoares** [comment]
Given that Angular 2, as of yet, at least to my knowledge, does not provide an interval service for polling. Would you propose people using protractor to test angular 2 apps workaround this issue? In cases where dropping synchronization is not possible.
In our use case we have a timeout of 20 minutes, set up as a sort of ticker, to revalidate a JWT token. When our protractor tests hit the homepage, they sit there waiting for a 20min timeout.

Cheers,
Nuno

**Comment by tobiaseisenschenk** [comment]
@nvsoares That is exactly what I wanted to write as well! Is there any solution or workaround for this yet @juliemr ?

**Comment by mgiambalvo** [comment]
Please see our updated documentation (https://github.com/angular/protractor/blob/master/docs/timeouts.md#angular) on this issue and let us know if we need to make it more clear. Thanks!

**Comment by MuraliMolluru** [comment]
@juliemr 
using $interval service is not working for long running api calls when running protractor e2e tests.. I am still getting timeout for pending http tasks. What could be the fix for this issue? please respond asap i am struggling with this issue since couple of weeks.
Thanks
Murali

**Comment by wswebcreation** [comment]
@MuraliMolluru ,

Addressing protractor members won't help directly. If you still experience problems please create a new issue and use the  [issue template](https://github.com/angular/protractor/blob/master/.github/ISSUE_TEMPLATE) in which you provide all needed info. Otherwise you can [ask a question on Stackoverflow with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

**Comment by MuraliMolluru** [comment]
@wswebcreation 
I had already created an issue but it was closed without answer and told me that i have to ask in stackoverflow. I even asked in stakoverflow but have not get any answer.

**Comment by wswebcreation** [comment]
@MuraliMolluru , can you give me the link on SO, then I can check if I can help you there

**Comment by MuraliMolluru** [comment]
@wswebcreation Thank you for the response.
https://stackoverflow.com/questions/44813083/protractor-timeout-with-long-running-http-asynchronous-tasks

**Comment by MuraliMolluru** [comment]
@wswebcreation Did u get a chance to look at the issue?
