### ISSUE TITLE
undefined: Stacktrace

### ISSUE THREAD

**Issue by debuggerpk** [angular/protractor#490]
I am trying out angular js tests based upon protractor. the stacktrace i have at the moment is 

``` bash
    Starting selenium standalone server...
    Selenium standalone server started at http://192.168.0.150:51197/wd/hub
    F

    Failures:

      1) E2E: The Dashboard : Main Page should have a working dashboard
       Message:
         timeout: timed out after 5000 msec waiting for spec to complete
       Stacktrace:
         undefined

    Finished in 5.659 seconds
    1 test, 1 assertion, 1 failure

Shutting down selenium standalone server.
```

here is my spec.js

``` javascript
    describe('E2E: Open Login Page', function() {
      var driver = browser.driver;
      driver.get('http://localhost:8080/accounts/login/?next=/dashboard/')
      driver.findElement(By.name("username")).sendKeys("user");
      driver.findElement(By.name("password")).sendKeys('password');
      //driver.findElement(By.xpath("\\button[]")
      driver.findElement(By.xpath("//button[contains(text(), 'Login')]")).click();
    });

    describe('E2E: The Dashboard', function() {
      var ptor = protractor.getInstance();

      describe(': Main Page', function() {
        it('should have a working dashboard', function() {
          ptor.get('/dashboard/#/');
          expect(ptor.getTitle()).toContain('Dashboard');
        })
      })
    });
```

What am i doing wrong?? any help in this regard would be appreciated

**Comment by kumar1600** [comment]
Hello Juliemr,

What is the stack trace? and also increased the jasmine test time too but still I'M facing the same issue? 

Failures:

  1) Delete Suite contains a test to select and unselect all entries
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

  2) Delete Suite selects one entry delete entry
   Message:
     timeout: timed out after 20000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 51.349 seconds
6 tests, 4 assertions, 2 failures, 0 skipped


Thank you
