### ISSUE TITLE
Issue in maximizing browser window

### ISSUE THREAD

**Issue by bharukaRupesh** [angular/protractor#4907]
**browser.driver.manage().window().maximize();** This line is giving me below error while running my tests on **Linux(Ubuntu) machine.**

- **WebDriverError:** unknown error: **failed to change window state to maximized, current state is normal**
        (Session info: chrome=68.0.3440.75)
        (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.15.0-20-generic x86_64)

**Comment by CrispusDH** [comment]
Could you try `browser.manage().window().setSize(width number, height number);`

**Comment by bharukaRupesh** [comment]
```browser.manage().window().setSize(width number, height number);``` This is also not working.

```I am using Xming software to launch the browser from linux server.``` So it may not be maximizing the window of ```Xming.``` That's the reason I might be getting the error.

**Comment by CrispusDH** [comment]
Yep, I think you are right about it.
