### ISSUE TITLE
browser.getWindowHandle( ) giving same GUID for all tabs

### ISSUE THREAD

**Issue by bharukaRupesh** [angular/protractor#4912]
Hi,
I have a use case as whenever I'll click a link ```Eg. 'About Us', it'll open a new tab``` and will display an information. 

Now, I want to manage multiple tabs in my Automation Tests which I tried by using ```browser.getWindowHandle( ) but it is giving me same GUID(Globally Unique Identifier) for all the tabs.```

Can you please help me in knowing how can I manage ```switching between multiple tabs as an when required?```

**Comment by CrispusDH** [comment]
Please, provide `HTML` of your `DOM`. Maybe, your `tab` it is just element in `DOM` instead of `browser tab`? So, you can just find it and click on it.

**Comment by bharukaRupesh** [comment]
We are using ```target="_blank"``` in anchor tag like,
```<a target="_blank" href="someURL">SomeText</a>```

**Comment by CrispusDH** [comment]
so you can find it via CSS Selector `$('[target="_blank"]')` for example, or `$('[href="someURL"]')`

**Comment by bharukaRupesh** [comment]
@CrispusDH ```I want to switch between browser tabs``` and do not want to locate an element.

**What you are talking below is about locating the element if I am not wrong,**
so you can find it via CSS Selector ```$('[target="_blank"]')``` for example, or ```$('[href="someURL"]')```

**Comment by CrispusDH** [comment]
When you will locate an element then click on it. `someTab.click()`

**Comment by bharukaRupesh** [comment]
I tried using ```getAllWindowHandles( )``` and ```switchTo( )``` method. It seems, it's working perfectly fine as of now.
