### ISSUE TITLE
Run specific test case

### ISSUE THREAD

**Issue by bharukaRupesh** [angular/protractor#4924]
Hi,

Is there a way we can run any specific test in protractor? When I say specific test that means a particular ```'it' block.```

**Comment by ElzioJunior** [comment]
Look here how to add tags into your features:
https://docs.cucumber.io/cucumber/api/#tags

Then into you protractor.conf.js add tags array into cucumperOpts:
```js
cucumberOpts: {
    tags: ['@yourTag']
  }
```

**Comment by IgorSasovets** [comment]
@bharukaRupesh , it depends on framework that you use. If it's mocha you should mark this block `it.only` and for jasmine you should mark it `fit`.

**Comment by bharukaRupesh** [comment]
But how we are gonna achieve solution to our query of executing ```specific test.``` I am using jasmine framework and not the cucumber.

```Do we have anything in jasmine using which we can reach out to our solution?```

**Comment by IgorSasovets** [comment]
@bharukaRupesh , take a look at [documentation](https://jasmine.github.io/2.1/focused_specs.html).

**Comment by IgorSasovets** [comment]
@bharukaRupesh , if issue resolved please close it.

**Comment by bharukaRupesh** [comment]
Sure.
