### ISSUE TITLE
Browser Size difference in regular UI e2e execution

### ISSUE THREAD

**Issue by naveenrunthla** [angular/protractor#4930]
Hi there!

I have observed an issue while running the e2e tests in different browser sizes. I am running e2e on following browser sizes (W x H): (1920 x 5000), (1280 x 1919), (960 x 1279), (600 x 959). In my tests everything works perfectly fine but when i get the browser size when spec is executing, i see the difference in browser window size than what i have mentioned in my protractor.conf file.
After getting the browser size in console i see following differences:

protractor.conf                    In Console
(1920 x 5000) ==> (1920 x 1032)
(1280 x 1919)==> (1280 x 1032)
(960 x 1279)==> (960 x 1032)
(600 x 959)==> It has the same size

Its happening only in regular UI e2e execution, but when i run tests in headless mode, the browser sizes are same as mentioned in protractor.conf file.

I am getting browser size in my spec using following method:

const browserSize = browser.manage().window().getSize().then(function(size) {
    return JSON.stringify(size);
});

Bug report
---

- Node Version: `8.11.1`
- Protractor Version: `5.3.1`
- Angular Version: `5`
- Browser(s): `Chrome 68.0.3440.75 (Official Build) (64-bit) `
- Operating System and Version `Ubuntu 16.04.2 LTS`

- Your protractor configuration file

const localOrHeadlessSize = (size) => {
    return process.env.NODE_ENV === 'local' ?
        ['--no-sandbox', `--window-size=${size}`] :
        ['--no-sandbox', '--headless', `--window-size=${size}`];
};

multiCapabilities: [
        {
            'browserName': 'chrome',
            'chromeOptions': {
                'args': localOrHeadlessSize('1920,5000')
            },
            specs: ['e2e/UI/All Screens/**/*.spec.ts']
        },
        {
            'browserName': 'chrome',
            'chromeOptions': {
                'args': localOrHeadlessSize('1280,1919')
            },
            specs: ['e2e/UI/All Screens/**/*.spec.ts']
        },
        {
            'browserName': 'chrome',
            'chromeOptions': {
                'args': localOrHeadlessSize('960,1279')
            },
            specs: ['e2e/UI/All Screens/**/*.spec.ts']
        },
        {
            'browserName': 'chrome',
            'chromeOptions': {
                'args': localOrHeadlessSize('600,959')
            },
            specs:['e2e/UI/Small Screen/*.spec.ts']
        }
    ],

**Comment by IgorSasovets** [comment]
Hi, @naveenrunthla! What is your machine screen resolution? You can't run your tests with browser size parameters greater than working machine screen resolution in normal mode.

**Comment by naveenrunthla** [comment]
Hi @IgorSasovets ,
I am running the e2e inside the ubuntu VM and the screen resolution is 1920 x 1080.

**Comment by IgorSasovets** [comment]
That's why you can't set screen height greater than 1032 in normal mode. Please close this issue.

**Comment by naveenrunthla** [comment]
@IgorSasovets  thanks for help
