### ISSUE TITLE
How to identify Kendo Controls using Protractor

### ISSUE THREAD

**Issue by vishalranjan15nov** [angular/protractor#4933]
Hi Team,

We have kendo controls in our angular application. While writing automation script using protractor we are unable to identify the controls by any of the available locators. Can someone help me how to proceed with this type of control?

<button kendobutton="" kendotoolbarfocusable="" tabindex="-1" class="k-button k-button-icontext ng-star-inserted" dir="ltr"><span class="k-icon k-i-file ng-star-inserted" role="presentation"></span> New </button>

**Comment by IgorSasovets** [comment]
Hi, @vishalranjan15nov ! Please provide links to test app (Kendo UI examples also possible) and mention desired components.

**Comment by vishalranjan15nov** [comment]
Hi Please find details as below:

Login Url: https://iceuxangular5.azurewebsites.net/
Server: https://e10testserver1.epicor-mobile.net/demo102100db1
Credentials: manager/manager

Once you open the url. Please give above server and credentials.
After the login. You need to set the company and site.
Navigate to ABC Code Maintenance and try to identify Kendo Controls like New, Save, Clear etc

**Comment by IgorSasovets** [comment]
Ok. thanks) I'll check it)

**Comment by IgorSasovets** [comment]
Selectors: 
- "New" - $$('button.k-button').first();
- "Save" - $$('button.k-button').get(1);
- "Clear" - $$('button.k-button').get(2)
or you can try to use unique selectors as following:
- "New" - element(by.cssContainingText('button.k-button', 'Clear'))

**Comment by IgorSasovets** [comment]
Also, please close this issue and change access credentials to your app. If you'll have any other questions, related to the Kendo UI, please email me.

**Comment by vishalranjan15nov** [comment]
Thanks for the help. I have tried as following:
"New" - element(by.cssContainingText('button.k-button', 'New'))

This is working fine. 
Could you please give me your mail id?

**Comment by IgorSasovets** [comment]
You can find it on my profile page. Also, please close this issue.

**Comment by vishalranjan15nov** [comment]
Yeah. I have found it. I am closing the issue.
For further issue and doubt, I will write a mail to you.
