### ISSUE TITLE
Can't use browser.params.variable in afterLaunch function, fails on Jenkins but local is fine 

### ISSUE THREAD

**Issue by RamaSuda** [angular/protractor#4938]
Hi, 

I am having an issue passing browser.params.updateTest to afterLaunch() when running on Jenkins. 

The error I see is : Error: TypeError: Cannot read property 'params' of undefined

But it's running fine locally and able to use the variable in afterLaunch() function 

Attached are package.json and config files.

[protractor.conf.ts.txt](https://github.com/angular/protractor/files/2315104/protractor.conf.ts.txt)
[Pakage.json.txt](https://github.com/angular/protractor/files/2315105/Pakage.json.txt)

Any help is highly appreciated.

**Comment by RamaSuda** [comment]
@juliemr Can you please take a look at this?

**Comment by viktorgogulenko** [comment]
Just fixed this issue on my side. Problem was that on remote machine (Jenkins, for me it was Bamboo etc.) Protractor wasn't installed globally. Just 'npm install' will not be enough, so you need also to add extra step  which is installing Protractor globally with 'npm install -g protractor' (be sure that '-g' is there!) and then call protractor using a place where it was globally installed on that machine - for me it was '/usr/local/bin/protractor':
`/usr/local/bin/protractor protractor.conf.js`

After that 'browser.params' started to work properly in afterLaunch section as well.

**Comment by rphacker1618** [comment]
Facing similar issue, can someone provide an workaround/solution on how we can access browser.params.variable value in afterLaunch functions

@juliemr

**Comment by DMazona** [comment]
I would guess that by the time the afterLaunch is run, the browser object is destroyed. if you want to pass a params command line argument and have it available in the afterLaunch, instead set a process.env variable. It should be available for as long as node is running.

**Comment by rphacker1618** [comment]
@DMazona  Thank you for responding.
Can you please let me know where can i set process.env variable or how do i use process.env variable ?? Also can you provide any reference link which i can refer.

**Comment by DMazona** [comment]
> @DMazona Thank you for responding. Can you please let me know where can i set process.env variable or how do i use process.env variable ?? Also can you provide any reference link which i can refer.

https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs

if you just want your browser params value to be available in afterLaunch, then in your onPrepare do something like this:
process.env.new_value = browser.params.new_value || 'default value'

then anywhere in your code, including your afterLaunch, you should be able to reference the process.env.new_value variable.
if you want your command line argument to be available sooner, including your beforeLaunch, then you'll need to process it separately, such as using the yargs package, and setting it in a similar manner with process.env.

**Comment by rphacker1618** [comment]
**if you just want your browser params value to be available in afterLaunch, then in your onPrepare do something like this:
process.env.new_value = browser.params.new_value || 'default value'**

@DMazona  I have tried assigning process.env.new_value = browser.params.new_value || 'default value under onPrepare, but it is not working.
Can we edit process.env.new_value during runtime?? If yes, Please provide working sample code.

**Comment by DMazona** [comment]
> **if you just want your browser params value to be available in afterLaunch, then in your onPrepare do something like this: process.env.new_value = browser.params.new_value || 'default value'**
> 
> @DMazona I have tried assigning process.env.new_value = browser.params.new_value || 'default value under onPrepare, but it is not working. Can we edit process.env.new_value during runtime?? If yes, Please provide working sample code.

I tested it myself, I could only speculate why your code is not working. is your onPrepare sync or async? How are you setting your browser params? In code? from command line? 

```
onPrepare: async function () {

        browser.params.env = new String(browser.params.env).toLowerCase();

        process.env.enviro = browser.params.env || 'dave'
 
        require('ts-node').register({
            project: 'tsconfig.json'
        });
    },
    afterLaunch: () =>{
        console.log(process.env.enviro)
    }
```

**Comment by rphacker1618** [comment]
@DMazona My onPrepare function is async. I am setting my browser params under conf.js file.

Let me try your sample code. One question is there any significance of using ts-node ??

**Comment by DMazona** [comment]
> @DMazona My onPrepare function is async. I am setting my browser params under conf.js file.
> 
> Let me try your sample code. One question is there any significance of using ts-node ??

No significance.

**Comment by rphacker1618** [comment]
@DMazona 
Based on implementation done in our framework , I have tried to in-corporate your sample code and here are the observation:

1.Able to overwrite process.env.enviro with browser.params.env under onPrepare function, but when I tried to access the value in afterlaunch function then it takes default value/ value define under .env file -> this happen when we are running multiple spec , if we try to run single spec then your code is working fine.

Below is the sample code from our project
1.conf.js file: In this file we set browser.params value :  
[conf.js.txt](https://github.com/angular/protractor/files/8909280/conf.js.txt)
2.global.conf.js : In this file we define onprepare, afterlaunch function and call them in conf.js file : [global.conf.js.txt](https://github.com/angular/protractor/files/8909286/global.conf.js.txt)

**Note**: We run our test case separately i.e for every test case new instance is created when multiple test case is selected for run
