### ISSUE TITLE
Impossible to locate an element

### ISSUE THREAD

**Issue by craffate** [angular/protractor#4959]
Hello!

I've been running into an odd issue recently, I'm not entirely sure this is Protractor related but I've been researching a lot and trying different things but I still can't solve the problem itself.

It seems that no matter what I do, Protractor just fails at locating one specific element.

The element I'm trying to locate:
```html
<a id="addDayButton" class="color-grey md-grey-theme" ng-click="cposAdminCtrl.pushObject(cposAdminCtrl.pointOfSales.mappedDays)">Rajouter un jour</a>
```

My locator:
```javascript
this.pointOfSaleAddDayButton = element(by.id('addDayButton'));
```

Simple test case:
```javascript
const helpers = require('../../helpers');
const ConcessionPageObject = require('../page_objects/concession.pageObject');

describe('Sample test', function() {
  const concessionPage = new ConcessionPageObject();

  it('should get to the page', async function() {
    await concessionPage.get();
    await helpers.waitForSpinner();
  });

  it('should click the point of sale card', async function() {
    await concessionPage.pointOfSaleButton.click();
    await helpers.waitForSpinner();
  });

  it('should open the point of sale creation form dialog', async function() {
    await concessionPage.createPointOfSaleButton.click();
    await helpers.waitForVisibility(concessionPage.createPointOfSaleDialog);
  });

  it('should click the unclickable button', async function() {
    await concessionPage.pointOfSaleAddDayButton.click();
  });
});
```

Reporter's output:
```
Failed: Cannot read property 'click' of undefined
```

I have written numerous tests and currently have 14 page objects and everything has always been working perfectly, I'm not 100% sure the issue is Protractor-related but one can hardly fail locating an element which has a unique ID.
I've tried pretty much every location method I could think of but no luck.

I thought I'd submit an issue, even though it'll probably make me feel very stupid in a couple days.

---

- Node Version: `10.9.0`
- Protractor Version: `5.4.0`
- Angular Version: `1.5.10`
- Browser: `Chrome 68.0.3440.106`
- Chrome Driver Version: `2.41.578706`
- Webdriver Version: `3.0.1`
- Operating System and Version `macOS Mojave 10.14 Beta (18A384a)`

---

```
Satanael% ./protractor conf.js --specs e2e/backoffice/scenarios/concession.scenario.js --troubleshoot
[16:06:31] D/launcher - Running with --troubleshoot
[16:06:31] D/launcher - Protractor version: 5.4.0
[16:06:31] D/launcher - Your base url for tests is <redacted>
[16:06:31] I/launcher - Running 1 instances of WebDriver
[16:06:31] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[16:06:32] D/runner - WebDriver session successfully started with capabilities Capabilities {
  map_:
   Map {
     'mobileEmulationEnabled' => false,
     'hasTouchScreen' => true,
     'platform' => 'MAC',
     'acceptSslCerts' => false,
     'goog:chromeOptions' => { debuggerAddress: 'localhost:52212' },
     'acceptInsecureCerts' => false,
     'webStorageEnabled' => true,
     'browserName' => 'chrome',
     'takesScreenshot' => true,
     'javascriptEnabled' => true,
     'setWindowRect' => true,
     'unexpectedAlertBehaviour' => '',
     'applicationCacheEnabled' => false,
     'rotatable' => false,
     'networkConnectionEnabled' => false,
     'chrome' => { chromedriverVersion: '2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db)',
     userDataDir:
      '/var/folders/7h/tks2vtq54b3_3mnd6x4w9n780000gn/T/.org.chromium.Chromium.vLstJN' },
     'takesHeapSnapshot' => true,
     'pageLoadStrategy' => 'normal',
     'databaseEnabled' => false,
     'handlesAlerts' => true,
     'version' => '69.0.3497.92',
     'browserConnectionEnabled' => false,
     'nativeEvents' => true,
     'webdriver.remote.sessionid' => 'dd528767-ea12-4852-a1a1-80eea131a13b',
     'locationContextEnabled' => true,
     'cssSelectorsEnabled' => true } }
[16:06:32] D/runner - Running with spec files /Users/cyril/projects/<redacted>/e2e/backoffice/scenarios/concession.scenario.js
```

Thank you for your attention.

**Comment by craffate** [comment]
> Perhaps the problem is in `concession.pageObject`. Try removing that dependency and clicking the element directly:
> 
> ```
>   it('should click the point of sale card', async function() {
>     await element(by.id('addDayButton')).click();
>     await helpers.waitForSpinner();
>   });
> ```
> Also, why have you split your test up into fragmentary specs? Why not a single `it`? Specs should always be complete, independent, and able to run in any order. If Jasmine ever tries to run just some of those `it` statements, or to run them out of order, it's going to fail. [By default, Jasmine runs specs in random order](https://github.com/jasmine/jasmine/blob/master/spec/support/jasmine.json). See protractor's sample spec file [here](https://github.com/angular/protractor/blob/master/example/example_spec.js).

Hello!

Thanks for your suggestion but it hasn't solved the issue, still getting `undefined` from that. I've checked a billion times and I'm 100% positive about the element being present, visible and clickable when the `.click()` statement is reached.

As for the `it` statements, I always thought they were run from top to bottom within `describe`s, that's something new to me!

Also, this is not an actual test I'm using, I've been tasked with a kind of unconventional end-to-end testing format where everything has to run sequentially, interact with two web-apps simultaneously and feature complete app coverage + scenarios that are more of a task automation thing rather than actual tests.

> Oh, and FYI, you should post questions like this to StackOverflow, unless you have some reason to think there's a bug in Protractor itself.

Yes, I wanted to but since the problem is such a trivial task that you can hardly mess up and I've spent hours reviewing what could be wrong with what I've written, searching the Internet and asking around without success, I started thinking that the problem's cause wasn't actually me but either the front-end developers I'm working with (which've checked and edited that element numerous times to make it as simple as possible) or Protractor itself.

I can hardly believe this comes from Protractor myself but I'm kind of desperate and feel like I've done all I could to make this work so that leaves me with the one thing that is (or should be) at the very bottom of anyone's checklist: submit an issue. I feel like this issue has no real use to be honest since I can't confirm whether or not Protractor has a bug but after using it for 3 months, I've learned quite a lot and developed some habits and ways of doing things that have been working well so far so I'm pretty sure this isn't a typo, a problem with the element's visibility or presence, a window focus issue or one of these things I check for to solve 99% of the problems I face.

**Comment by GitSage** [comment]
I'm afraid we probably won't be able to diagnose the issue without much better reproduction. If you cannot provide direct access to the site, I suggest you make an [SSCCE](http://sscce.org) for us. Here's one way to do it:

* Grab a snapshot of the page as it is when the error occurs. To do this:
 * Navigate to the page
 * Open the dev tools
 * Go to the `elements` tab
 * Right-click on the root `html` element
 * Click "Copy" -> "Copy OuterHTML"
 * Paste that into a blank html file
* Most likely you'll want to remove all `<script>` tags
* Run the relevant piece of your automation against that page and verify that the error still occurs
* Start cutting things out of the page (irrelevant html nodes, irrelevant css, etc) until you're down to the absolute core of what makes the error happen
* Post that. It might look something like [this](https://github.com/SeleniumHQ/selenium/issues/1834#issuecomment-418532915).

**Comment by craffate** [comment]
Front-end developers working on all this have changed a couple things on the element itself and everything now magically works. I can't tell what caused the issue since there's very little communication between us, sorry. At least this confirms that Protractor isn't to be incriminated!

My apologies for cluttering the issue board.
