### ISSUE TITLE
How to use Protractor with kendoUI

### ISSUE THREAD

**Issue by kambleaa007** [angular/protractor#4967]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`
- Your protractor configuration file
- A relevant example test
<select k-options="kOptions" kendo-combo-box="dirEbTemplateSelect" k-data-source="datasource" k-auto-bind="false" k-data-text-field="textField" ng-model="ngModel" k-data-value-field="valueField" k-select="eBTemplateSelect.onTemplateSelected(item, currentItemIndex, previousItem)" k-on-change="eBTemplateSelect.onTemplateChange(kendoEvent)" class="kendo-form-control ng-valid-parse ng-touched ng-empty ng-dirty ng-invalid ng-invalid-required" ng-required="isRequired" ng-disabled="" data-role="combobox" aria-disabled="false" required="required" style="display: none;"><option value="450">Evaluation Report - ERP-DH</option><option value="260">Evaluation Report - ERP-SCJ</option><option>eval</option></select>
- Output from running the test
k-options="kOptions" 
No ng-options here
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by IgorSasovets** [comment]
Hi, @kambleaa007 ! Please take a look at https://github.com/angular/protractor/issues/4933.

**Comment by kambleaa007** [comment]
its private companies website so cant disclose link to you.
Examples :
k-options attribute of <select> tag

**Comment by IgorSasovets** [comment]
Then please find another public available app that uses KendoUI.
