### ISSUE TITLE
No Inputs were found in config file Error

### ISSUE THREAD

**Issue by demisx** [angular/protractor#4976]
Hi there!

The VS Code 1.28.0 on Mac shows the following error in`node_modules/protractor/tsconfig.json`:

```
No inputs were found in config file
 '~/projects/myproject/node_modules/protractor/tsconfig.json'. 

Specified 'include' paths were '["**/*"]' and 'exclude' paths were
'["built","node_modules","testapp","website","scripts","exampleTypescript","spec/**/*"]'.
```

Very annoying and makes the proble window show up all the time. Is it something that can be fixed? 

- Node Version: 10.11
- Protractor Version: 5.4.1
- Angular Version: 6
- Browser(s): Chrome
- Operating System and Version: Mac High Sierra

**Comment by IgorSasovets** [comment]
They are almost the same, but take a look at `specs` definition in provided example. Maybe you need to change regex to 
```
specs: [
    './src/**/*.e2e-spec.ts'
 ]
```

**Comment by CrispusDH** [comment]
maybe you could try just pass `../test/**/*.js`. I mean the real way from your specific `outdir` path?

**Comment by demisx** [comment]
@CrispusDH I am sorry, but I am not following. My e2e specs are  `./e2e` folder, so is `protractor.config.js`. The specs are in TypeScript and compiled on the fly by `ts-node`. This is why it's set to `specs: ['./*.e2e-spec.ts']`. If I change it to `../test/**/*.js` nothing is going to match.

**Comment by demisx** [comment]
And do you think the problem is somewhere in my code and not in protractor and/or maybe a bug in VS Code? After all, it complains about `node_modules/protractor/tsconfig.json` file, outside of my project folders.

**Comment by CrispusDH** [comment]
I suggest that it could be an issue with `on fly` by `ts-node`. Could you try without it :)

**Comment by demisx** [comment]
Disabling `ts-node` makes no difference.

**Comment by CrispusDH** [comment]
My second suggestion that it is a mess in path. Could you try to do the same as in @IgorSasovets example:
- `baseUrl` in `tsconfig.json`
- `specs` in `protractor.conf.js`
- `project` path in `protractor.conf.js`

**Comment by IgorSasovets** [comment]
@demisx , could you share your test project (you can modify it and delete essential data)? I'd run it on my local machine and notify you about the results.

**Comment by demisx** [comment]
I am currently under a couple of deadlines, so preparing this project will be difficult. I'll see if I can come up with anything if that error still stays on. Currently, it's gone again.

**Comment by demisx** [comment]
@IgorSasovets Is there any way I could give you a temporary access to the project repo, so you can clone and see the error yourself?

**Comment by IgorSasovets** [comment]
@demisx , yes, just mail me.

**Comment by demisx** [comment]
Upon further testing, this error appears to be VS Code related and very intermittent. Even @IgorSasovets could not replicate it. Closing it hoping 🤞 that one of the future IDE releases will fix it.

**Comment by sergiogomes** [comment]
Hello,

I'm also using VS Code 1.20.1, but on windows, and I started receiving the same message @demisx reported.
I noticed that it started after I imported EventEmitter from Protractor by mistake (I needed to import it form angular core). It doesn't disturb me tho.
It could be a starting point...

**Comment by demisx** [comment]
@raheel0452 See if this error is back after restart. It disappeared for me initially, but then, some time later, the old good friend was knocking back at the front door.

**Comment by danwellman** [comment]
I started to get this issue today after updating macOS to 10.14.4

VSCode did not update (or at least, did not show usual 'welcome' screen it usually shows after update), and is currently version 1.32.3

Not only is it giving me this warning in tsconfig, it is also showing red underlines for all of my imports that start with `@`. I am working on a very large app, and in tsconfig and tsconfig.app.ts we have many common paths aliased using `paths` config. The app itself still works as it did before, but VSCode is underlining all of my aliases, and I am now unable to right-click on an import and peek/go to definition. Really frustrating.

**Comment by boisamazing** [comment]
Restarting VSCode fixed this error like a magic in my case.

**Comment by demisx** [comment]
For me, this error would disappear after restart, but then would be back later. I haven't figured out how to get rid of it, except exclude `node_modules/` from the navigation tree which is not optimal, of course.

**Comment by runchicken** [comment]
> Restarting VSCode fixed this error like a magic in my case.

me too 😄

**Comment by leafdropco** [comment]
I'm still getting this issue on:

Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0


tsconfig.json
`{
    "compilerOptions": {
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es6",
        "noImplicitAny": true,
        "moduleResolution": "node",
        "sourceMap": true,
        "outDir": "dist",
        "baseUrl": ".",
        "paths": {
            "*": [
                "node_modules/*",
                "src/types/*"
            ]
        },
        "lib": [
            "es2015"
        ]
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [""]
}`

**Comment by demisx** [comment]
Seeing this error again in the latest `v1.39.2`. 😞 Turns one of the top folders red.

```
No inputs were found in config file '/Users/dmoore/projects/bm/dl/dl-mono/web/node_modules/protractor/tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '["built","node_modules","testapp","website","scripts","exampleTypescript","spec/**/*"]'.
```

**Comment by cluzier** [comment]
> Restarting VSCode fixed this error like a magic in my case.

did not fix my problem

**Comment by dragonslayer77** [comment]
i had the same problem, stopped seeing the error by changing my "include": [ "src/**/*.ts" ], to  "include": [ "**/*.ts" ]. hope this helps

**Comment by RemoteRacoon** [comment]
> Thank you. I've cloned [your example project](https://github.com/IgorSasovets/baseNgApp) and didn't see this error showing up there yet. I've tried to update the `specs` array in my project to something more restrictive `specs: ['./*.e2e-spec.ts'],`, but it didn't make any difference. The "No inputs were found..." error still shows up after a few minutes following opening of the project in VS Code. Pretty puzzled at this point.
> 
> ![screen shot 2018-10-16 at 8 09 23 am](https://user-images.githubusercontent.com/4452412/47027066-96418a80-d11b-11e8-9ed8-5c27c2295610.gif)

Try restarting ts server
