### ISSUE TITLE
elementexplorer won't work if Chrome Dev Tools is open

### ISSUE THREAD

**Issue by owenmead** [angular/protractor#498]
When using the elementexplorer typos and other simple errors will cause the following:
`There was a webdriver error: UnknownError unknown error: Runtime.evaluate threw exception: TypeError: Cannot call method 'click' of null`

Any element find command after this will result in the same error. This results in having to restart the explorer and lose any state you were in when creating the selections. Very frustrating.

**Comment by heathkit** [comment]
Unfortunately, this is a design issue in chromedriver. WebDriver is using the same interface that devtools uses to control the browser.

Thankfully, because it's the same interface, any information you could get from devtools you can also get with WebDriver.
