### ISSUE TITLE
--fail-fast CLI option

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#499]
Nice to have a `--fail-fast` option that `process.exit(1)` after first error found.

**Comment by konrad-garus** [comment]
The fix from @stolidity is nice, but unfortunately Jasmine does not call `afterEach` after timeouts. As far as I can see there is no hook for it, unless you use reporters.

**Comment by LaiaPR** [comment]
Hi!

I am using Protractor with Cucumber (and I also run my tests on Travis with Gulp). I have not found a way to fail when the first failed test occurs... Would you include that in Protractor? Is there a workaround I can use?

Thanks!

**Comment by willem-groeneveld** [comment]
cucumberOpts: {
    require: [
      '../features/step_definitions/*.js',
      '../features/support/handlers.js',
    ],
    format: 'pretty', // or summary, progress
    'fail-fast': true
  },
