### ISSUE TITLE
Question about avoiding ptor.sleep() in e2e test

### ISSUE THREAD

**Issue by GrishaAngelov** [angular/protractor#502]
I have the following sample code and I want to avoid use of sleep() 

``` js
describe("E2E Sample",function(){
    var ptor = protractor.getInstance();

    it("should display all names",function(){

        ptor.get("/");

        var button = ptor.findElement(protractor.By.linkText('view names'));
        button.click();

        ptor.actions().mouseMove(ptor.findElement(protractor.By.linkText('option menu'))).perform();

        ptor.sleep(500);     

        ptor.actions().mouseMove(ptor.findElement(protractor.By.linkText('view all'))).click().perform();

        var elements = element.all(by.repeater('name in names'));

        expect(elements.count()).toEqual(2);

    },30000)
});
```

I tried with `ptor.waitForAngular();`,`setTimeout(...);`,`driver.manage().timeouts().implicitlyWait(...)` 
but the count of expected elements is always 0. Am I missing something ? How can I avoid `ptor.sleep(500);`?

**Comment by Sankannavar** [comment]
@sallojusuresh Currently am using browser.sleep in many place 
ex:deleting few lines, here we cant use isprsent,clickable and all.
some times delete is taking 20 sec some times 2 sec  in such case how to use browser wait please help me.
thanks in advance.
