### ISSUE TITLE
browser.actions() not working in firefox browser

### ISSUE THREAD

**Issue by gugvel** [angular/protractor#5040]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``9.11.2
- Protractor Version: ``5.4.1
- Angular Version: ``
- Browser(s): ``Firefox-63.0.1
- Operating System and Version ``MacOs
- Your protractor configuration file
- A relevant example test
I am using below the code for a right click event in my test suit. When suit running in firefox browser the moseMove action is not working....

browser.actions().mouseMove(element).perform();
browser.actions().click(protractor.button.RIGHT).perform();

- Output from running the test
Nothing happend when running firefox brower
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by cnishina** [comment]
Thank you for your issue. I'm leaning towards this being a geckodriver issue (https://github.com/mozilla/geckodriver/issues) and not a Protractor bug. Here are some debugging questions:

1. Does this work in Chrome? If this does, this is not a Protractor bug and it belongs with geckodriver. 
2. Has this work in a previous version of geckodriver / Firefox and recently does not work?
3. Has there been an upgrade in geckodriver versions or Firefox versions that have caused an incompatibility?

Please provide more information / answers to the question above. I have not had this issue on the test suite.

**Comment by cnishina** [comment]
Closing issue. If you feel like this is still a Protractor error, feel free to open a new one.
