### ISSUE TITLE
TypeError: "protractor_1.$ is not a function" when using imports in protractor.conf.ts

### ISSUE THREAD

**Issue by doppelganger23** [angular/protractor#5042]
Node Version: `10.13.0`
Protractor Version: `5.4.1`
Operating System: `Windows 10 Enterprise v1803`
Protractor configuration file:
```
import { Config, browser } from 'protractor';
import Steps from './utils/steps';

const conf: Config = {
  onPrepare: async function () {
    await browser.driver.manage().window().maximize();
    await Steps.login();
  },

  // ... 
  // (skipped some props here)
  // ... 

  params: {
    defaultUser: {login : 'my login', password: 'my password'}
  },
  SELENIUM_PROMISE_MANAGER: false,
  framework: 'jasmine',
  capabilities: {
    browserName: 'chrome'
  }
};

exports.config = conf;
```
After compiling with
```
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
    "moduleResolution": "node",
  }
```
and running causes this error:
```
[12:59:44] E/configParser - Error code: 105
[12:59:44] E/configParser - Error message: failed loading configuration file ./build/protractor.conf.js
[12:59:44] E/configParser - TypeError: protractor_1.$ is not a function
```
with stacktrace leading to this compiled code
```
const protractor_1 = require("protractor");
class MyPageObject {
    constructor() {
        this.rootElement = protractor_1.$('.my-selector');
    }
}
```
(here is original ts code:)
```
import { $, by, ElementFinder } from 'protractor';

class MyPageObject {
  private rootElement = $('.my-selector');
}
```
(MyPageObject  is imported in Steps module this way:)
```
import MyPageObject from '../page-objects/header.po';
```

If I remove `import Steps from './utils/steps';` and place `const Steps = require('./utils/steps').default;` in `onPrepare` all works nice. But I spent much time trying to understand this confusing behavior - it definitely should be fixed.

**Comment by cnishina** [comment]
Quick answer...  you should use require since these are global objects and are not built at the time you import.

```
import Steps from './utils/steps';

export const config: Config = {
  onPrepare: async function () {
    const browser = require('protractor').browser;
    await browser.driver.manage().window().maximize();
    await Steps.login();  
    // if steps also relies on element, expected conditions, or browser,
    // you should pass it to the login method. So maybe something like:
    //   const element = require('protractor').element
    //   Steps.login(browser, element);
  },

  // ... 
  // (skipped some props here)
  // ... 

  params: {
    defaultUser: {login : 'my login', password: 'my password'}
  },
  SELENIUM_PROMISE_MANAGER: false,
  framework: 'jasmine',
  capabilities: {
    browserName: 'chrome'
  }
};
```

**Comment by doppelganger23** [comment]
> Try this out and let me know how that works out.

As I said earlier, if I change importing step module with require all works nice.
Importing browser itself in config is working for me with import (and thats strange).

Because of such inconsistancy it's look more like a bug then like a feature.

**Comment by cnishina** [comment]
Previously discussed above that this is exactly how this works. The global objects are not created when your config is loaded in the protractor CLI. This does not appear to be a bug but rather how Protractor does things. We have a potential roadmap to fix some of these issues.

So I am closing this issue. Thanks!
