### ISSUE TITLE
i am not able to get value or row outside of function

### ISSUE THREAD

**Issue by vermin-scripts** [angular/protractor#5046]
````
var trdata;
	 			
	 			$$('#tblAdvanceAdjEntry tbody tr').map(function(el)
	 			{
	 				return el.getText().then(function(row1){
	 					return row1;
	 				});

	 			}).then(function(row){

	 					console.log("rows --->"+row.length);
	 					trdata = row.length;
	 					
	 					console.log('trdata --'+trdata);
	 					var r = trdata - 2;
	 					element(by.xpath('//*[@id="'+r+'_AdjAgainstAmt"]')).sendKeys(adjsamt);
	 					return row.length;
	 			});
console.log("result "+trdata);//getting value of row here but it returns undefine

`
```

_Originally posted by @vermin-scripts in https://github.com/angular/protractor/issues/392#issuecomment-439294305_

**Comment by CrispusDH** [comment]
Could someone close this issue? Please go to `stackoverflow`. It is not an issue of protractor

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
