### ISSUE TITLE
Could not use `chromeOptions.prefs.profile.default_content_setting_values.notifications` of chrome browsers with docker

### ISSUE THREAD

**Issue by sakshingp** [angular/protractor#5057]

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
