### ISSUE TITLE
Request to update examples in Protractor API docs for async/await

### ISSUE THREAD

**Issue by vsravuri** [angular/protractor#5080]
Some of the examples provided in Protractor API docs should be updated to include how to use the API methods with async/await.

http://www.protractortest.org/#/api

It will be helpful if async/await examples are provided for below API methods. I use some of the API methods extensively in my code, refactoring the code to make it work with async/await.

- Filter
http://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.filter

- Map
http://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.map

- Each
http://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.each

**Comment by cnishina** [comment]
Sure. I'll add this to the list.

**Comment by devoto13** [comment]
I'll work on it.

**Comment by cnishina** [comment]
Closed with https://github.com/angular/protractor/pull/5081
