### ISSUE TITLE
The sendKeys function is clearing the text after to write it

### ISSUE THREAD

**Issue by djom20** [angular/protractor#5086]
Hi there!

I'm facing this issue today, it's weird bug since I'm try to send a random text to a input and the text should stay there but it is erased, even sometimes the input is empty. I just used:

```
element(by.css('.myclass')).sendKeys('randomText');
```

![image](https://user-images.githubusercontent.com/1834808/49812543-a8aefd80-fd33-11e8-94a5-50d5582f5c22.png)
---
![image](https://user-images.githubusercontent.com/1834808/49812562-b19fcf00-fd33-11e8-930e-826bf4f02519.png)
-- -
[Gif]
![sendkeysbug_shoot](https://user-images.githubusercontent.com/1834808/49812466-7b624f80-fd33-11e8-83fb-123646f3049d.gif)
---

Bug report

- Node Version: `6.9.1`
- Protractor Version: `5.4.1`
- Browser(s): `Chrome 70.0.3538.110`
- Operating System and Version `MacOx 10.14`

**Comment by cnishina** [comment]
This appears to be more of a StackOverflow question but since you have such great pictures... could you provide what's happening right before? Also your config (partial config is fine) and if this is an Angular or AngularJS application. Also are you using async await...

**Comment by cnishina** [comment]
Closing since this issue has not changed. Please ask this on StackOverflow.
