### ISSUE TITLE
Protractor doesn't navigate to URL and shows data written in then address bar at random point of execution.

### ISSUE THREAD

**Issue by Enigmaderockz** [angular/protractor#5090]
Hello Team,

I have started using protractor recently and it is doing great for angular websites. But I have observed some annoying issues with the protractor:

I have 60 TCs in my project and while running those test cases, 

1. sometimes protractor is not able to find elements on a page for a TC but next time protractor can find the same element on the same page for same TC.

**2. The most annoying issue is protractor doesn't navigate to URL and show only data written in the address bar at one point of execution and hence it fails that corresponding TC. Next time, it happens for some other TC. I have searched everywhere this issue but couldn't find any response.**

Note: If I run 60 TCs in 5 groups (execute 12 first and then some rest then next 12 ) then the script won't fail. it is happening when all 60 TCs are running one by one.

3. There is a button which gets disabled after clicking Go button so I am using code expect(foo.isEnabled()).toBe(false); but it is not working.

I can't provide any info about my files since it is from my office project. Sorry about that.

if someone can tell me a solution of the 2nd point then it would be very helpful.

Bug report
---

- Node Version: `` 8.12
- Protractor Version: `` 5.3
- Angular Version: ``
- Browser(s): `` Chrome
- Operating System and Version `` Windows 7
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug: There are no steps. If many test cases then 2nd issue happens at some random TC.
- The URL you are running your tests against (if relevant)

Feature Request
---
1. There should be an option to provide a delay between multiple specs when we are running multiple specs one by one. It would be so helpful. 
- Reasons for adopting new feature: I think Chrome browser is using too much memory when running so many TCs so delay will provide some rest to chrome and hopefully 2nd issue won't happen
- Is this a breaking change? (How will this affect existing functionality): Same as mentioned above

**Comment by cnishina** [comment]
It is difficult to help without more information.  Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by Enigmaderockz** [comment]
thast's fine but Haven't you come across these kind of issues like inconsistency or above issues?
