### ISSUE TITLE
Can protractor test a login that is not angular based

### ISSUE THREAD

**Issue by Hardcode37** [angular/protractor#51]
This question is on stackoverflow.

I am testing an application written predominantly in angularjs however some elements of the application are written in .NET C#, such as the login form.

My question is this.

Can I leverage Protractor and test my application fully with e2e testing.

I have tried using protractor and I am happy with it thus far. However I do not seem to be able to test a page that written in .NET. I am not sure if this is because protractor only tests the elements of an angular application or if it is the way I have written my tests.

I have tried searching for the elements in the page like the example below.

ptor.findElement(protractor.By.xpath('/html/body/div/div[1]/section/input')).sendKeys('xxx');

But this only returns an UnknownError: javascript error: cannot call method 'get' of undefined.

I know that this error means the elements are not visible on the page, however I have placed a timeout in my test shown below to see if this helps. I have also tried sleep(5000) but this doesn't help either.

it('test if div apears', function () {
        ptor = protractor.getInstance();
        ptor.get('/Test/Index');
        var text = ptor.findElement(protractor.By.xpath('/html/body/div/div[1]/section/input')).sendKeys('xxx');
        expect(text).toEqual('Index');
    }, 10000);

all I require is to be able to add text to a dynamically created input box, created by Html.TextBoxFor()

**Comment by didando8a** [comment]
Great solution!!

Thanks

**Comment by ProtHelp** [comment]
Hi ,
I am new to protractor and i am trying to run few sample tests on non- angular pages, Following is the code i am trying to run on google page:

describe('cct homepage',function(){
	it('should open the page with title',function()
	{ browser.manage().timeouts().setScriptTimeout(60000);
			browser.pause(5000);
		    browser.ignoreSynchronization=true;
			browser.get("http://google.com",400000);
			browser.sleep(2000);
			element(by.id('q')).sendKeys('hi');
	});

protractor is unable to locate element. Can you help me  with this issue ?

**Comment by NickTomlin** [comment]
@ProtHelp please [ask a question on stackoverflow with the 'protractor' tag](http://stackoverflow.com/questions/ask?tags=protractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

> Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)

**Comment by philipb4u** [comment]
I am trying to use browser.driver and it throws the exception saying driver is not defined. Can someone suggest how to debug further

**Comment by VinishaDsouza** [comment]
I am having the same error too, i cant find browser.driver :(
