### ISSUE TITLE
Clearing inputs doesn't work with type=number.

### ISSUE THREAD

**Issue by rsboarder** [angular/protractor#510]
``` html
<input type="number" min="0" id="limit" ng-model="limit" required>
```

``` js
var input = element(by.input('limit'));
var generatedNum = generateNum(4);

input.sendKeys(generateString()).then(function () {
  expect(input.getAttribute('class')).toMatch(/ng-invalid/gi);
});

input.clear(); // this doesn't clear input

input.sendKeys(generatedNum).then(function () {
  refreshModel().then(function () {
    expect(model.limit).toBe(generatedNum);
  });
});
```

Changing type to `text` fixes everything. I don't know, maybe it's a webdriver bug.

**Comment by amwill1** [comment]
this is still an issue for me. I've tried the suggestions in this [question](http://stackoverflow.com/questions/32326978/the-clear-function-does-not-work-on-input-of-type-number) and did

        elem.click();
        browser.sleep(1000);
        elem.clear().sendKeys(val);

but this solution only seems to work sometimes. i'm not sure what to do. i just updated to 3.0.0
