### ISSUE TITLE
input.clear() breaks further input using sendKeys()

### ISSUE THREAD

**Issue by samuelkilada** [angular/protractor#5104]
Running protractor 5.4.1, and Chrome Version 71.0.3578.98 (Official Build) (64-bit).

The tests used to pass no problem, but now the very same code is failing. I believe this is due to a Chrome or protractor update (probably Chrome). If you target an input and clear it, it won't let you sendKeys after the clear.

Example:

var inputElement = element(by.id('firstName'));
inputElement .clear().sendKeys('test123');

The above IN SOME CASES (I don't know when) yields this error: "Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, #firstName)"

A workaround I figured out is this:

var ctrlA = protractor.Key.chord(protractor.Key.CONTROL, "a");
var deleteKey = protractor.Key.chord(protractor.Key.DELETE);
var inputElement = element(by.id('firstName'));
inputElement.sendKeys(ctrlA).sendKeys(deleteKey).sendKeys('test123');

**Comment by cnishina** [comment]
This is a support question and please try to ask this question on StackOverflow. I'm going to close it but I would try the following...

Can you try to move your tests off of the control flow and use async / await? Could you also break up your chained actions to two separate lines?
```
  await inputElement.clear();
  await inputElement.sendKeys('test123');
```

Now that we've separated it into two lines, could we also add in a timeout? Maybe your input box takes a while to clear?

```
  await inputElement.clear();
  await new Promise(resolve => {
    setTimeout(resolve, 500);
  });
  await inputElement.sendKeys('test123');
```

Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
