### ISSUE TITLE
Jamine timout

### ISSUE THREAD

**Issue by nsrikanth456** [angular/protractor#5107]
I am working behind the proxy.. For my use I added ''Proxy Auto Auth'' exception in the conf.js file
After adding that i am getting the error (Jasmine timout). Even i increase the time it waiting and finally giving the same error.. Please help to solve

**Comment by nsrikanth456** [comment]
Ok, Thanks Crispus DH

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
