### ISSUE TITLE
Is it possible to integrate winium driver through protractor? In my scenario i need to interact with windows application which i used to do with winium driver in java.

### ISSUE THREAD

**Issue by AdityaAutomationTechniques** [angular/protractor#5116]

**Comment by cnishina** [comment]
I am going to close this. I do not think there is bandwidth to focus on just Windows. Although this is an interesting feature request, I also do not think that this is the goal of Protractor. Currently we are trying to keep up with the W3C standards.

It sounds like you could just interact directly with winium?
