### ISSUE TITLE
Running 'ng e2e' on Angular 7 can't find element with dynamic one-way bound [id] attribute

### ISSUE THREAD

**Issue by ZachRHale** [angular/protractor#5118]
Bug report
---

- Node Version: `10.4.1`
- Protractor Version: `5.4.2`
- Angular Version: `7.1.4`
- Browser(s): `Chrome`
- Operating System and Version `Microsoft Windows 10 Pro - Version	10.0.17134 Build 17134`
- Your protractor configuration file
```
const { SpecReporter } = require('jasmine-spec-reporter');

exports.config = {
  allScriptsTimeout: 11000,
  specs: [
    './src/**/*.e2e-spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: 'http://localhost:4200/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.e2e.json')
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};
```
- A relevant example test
`https://stackblitz.com/edit/protractor-bug-example`
- Output from running the test
```
1) workspace-project App should display welcome message
  - Failed: No element found using locator: By(css selector, *[id="\31 23-456-789"])

Executed 1 of 1 spec (1 FAILED) in 2 secs.
[15:03:53] I/launcher - 0 instance(s) of WebDriver still running
[15:03:53] I/launcher - chrome #01 failed 1 test(s)
[15:03:53] I/launcher - overall: 1 failed spec(s)
[15:03:53] E/launcher - Process exited with error code 1
An unexpected error occurred: undefined
```
- Steps to reproduce the bug
` Run ng e2e on the current project in the stackblitz example`

**Comment by ZachRHale** [comment]
As my example shows, the test "should find the app-summary ID" when nested inside of a component will fail to find the id but the test "should find the ID in app component" that is in the root component doesn't fail.  They use the same base classes, functions, properties, etc.

**Comment by cnishina** [comment]
So I'm not sure why you are finding something with `[id="\31 23-456-789"]`. I'm looking at your example and your id is "123-345-789". This kind of question might be better to ask this on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor).

I'm going to take a quick guess since I don't have the actual spec file:

```
it('should find the element', async () => {
  expect(async element(by.css('[id="123-345-789"]').getWebElement()).toBeTruthy();
});
```

**Comment by ZachRHale** [comment]
@cnishina Will do. My spec file was in the stackblitz project (https://stackblitz.com/edit/protractor-bug-example) but this is all I was doing.

```
import { browser, by, element } from 'protractor';

export class AppPage {
  navigateTo() {
    return browser.get('/');
  }

  getBadID() {
    return element(by.id('123-456-789')).getText();
  }

  getGoodID() {
    return element(by.id('123-789')).getText();
  }
}
```
```
  it('should find the app-summary ID', () => {
    page.navigateTo();
    expect(page.getBadID()).toEqual('Trying to find this element');
  });

  it('should find the ID in app component', () => {
    page.navigateTo();
    expect(page.getGoodID()).toEqual('This works');
  });
});

```

**Comment by ZachRHale** [comment]
Not sure why `by.id('123-456-789')` doesn't work in this case but `by.css('[id="123-456-789"]')` works.
