### ISSUE TITLE
special key change to its keyboard number with sendkey

### ISSUE THREAD

**Issue by bboycs** [angular/protractor#5119]
Bug report
---

- Node Version: 6.4.1
- Protractor Version: 5.4.1
- Browser(s): MicrosoftEdge 
- Operating System and Version Window 10

--

element.sendkey('*')  will result 8 
element.sendkey('@') will result 2 
however in other browser it works fine 

Kindly direct me to correct party if it is non protractor issue 

Thanks

**Comment by CrispusDH** [comment]
`Protractor Version: 4.0.0-alpha.1` it is not Protractor version. You typed `selenium-webdriver` version. Currently, such version does not support by protractor. 
This support question might be better to ask on [StackOverflow](http://stackoverflow.com).

**Comment by bboycs** [comment]
Reopen the issue.
Edited and updated on the issue description

**Comment by SchnWalter** [comment]
When you want create an issue on an Open Source project it's best to read the [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md) guidelines or at least read the default text that appears in the "New Issue" form. Both specify that you should ask usage and debugging questions on discussion forums, not in the project issue queue.

> 2. Make sure you are not asking a usage or debugging question. If you are, use StackOverflow, Google Group discussion list, or Gitter to get help.

Please close this issue and post your question somewhere else.

---
P.S. The task you are trying to accomplish is related to the keyboard layout, it's not related to Protractor at all.
