### ISSUE TITLE
Show step name while execute

### ISSUE THREAD

**Issue by Prabha83** [angular/protractor#5120]
Bug report
---

- Node Version: `8.11.1`
- Protractor Version: `5.4.0`
- Angular Version: `6.1.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`

1#: While I run e2e, it does not show the step name and it does show only dots. Is there a way to change config to show step names instead of dots. It helps to identify the failed steps quickly and fix it.

**Comment by CrispusDH** [comment]
It depends on your test runner and reporter, not on protractor

**Comment by Prabha83** [comment]
I could not get you. I run e2e scripts through protractor (npm run e2e). Could you explain how to show scenario name while execute e2e.

**Comment by cnishina** [comment]
Yes, this depends on your jasmine reporter. You could override some of the reporting functions but this is not an issue with Protractor. This is a support question and please ask it on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor). You should maybe ask about the Jasmine Reporter or Jasmine Console Reporter and Protractor plugin hooks.
