### ISSUE TITLE
sendKeys with multiple keys (CTRL+a) no more working on lastest chrome and driverchrome

### ISSUE THREAD

**Issue by hieutrandn9889** [angular/protractor#5129]
Hi there!
this.uploadFile = function () {

       var uploadPath = path.resolve(__dirname, '../../../resource/Excel_files_XLSX/');
        console.log('---',uploadPath);

**Case1:**
        const elementFind = element(By.xpath(UI_TIME_TABLE_PAGE.UploadInput));
        elementFind.sendKeys(protractor.Key.chord(protractor.Key.CONTROL, "a"));
        browser.actions().sendKeys(protractor.Key.ENTER).perform();

**Case2:**
        browser.actions().keyDown(protractor.Key.CONTROL).sendKeys('a').perform();
        browser.actions().sendKeys(protractor.Key.ENTER).perform();
        browser.sleep(9000);
}
- Node Version: `v8.14.0`
- Protractor Version: `5.1.1`
- Browser(s): `chrome`
- Operating System and Version `Mac OX`

It can't work for this code

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
