### ISSUE TITLE
seleniumSessionId fails with Firefox on GET /session

### ISSUE THREAD

**Issue by tfaron** [angular/protractor#5133]
---

- Node Version: `nodeJs 6.4.1`
- Protractor Version: `5.4.1`
- Angular Version: `6.1.0 but also tried older version`
- Browser(s): `Firefox `64.0.2 but tried older versions as well'
- Operating System and Version `Windows 10`
- Chrome driver: 2.45
- Geckodriver: 0.23.0

I have been running successfully when I use chrome browser along with seleniumSessionId as it's important we keep the browser session alive in our testing environment. I recently tried to run with firefox but it's failing details below:

Sample Protractor.conf file, that I have tried with and without marionette: true. 
`exports.config = {
  framework: 'jasmine',

  seleniumAddress: 'http://127.0.0.1:4444/wd/hub',
  seleniumSessionId: 'd67f1e1d-da57-4683-b24d-2700058b6395',
  directConnect: false,

  capabilities: { browserName: 'firefox', marionette: true, 'moz:firefoxOptions': { log: { level: 'trace' } } },'

Steps to reproduce:
Start a firefox webdriver session.
update the conf file, seleniumSessionId to use the newly created Firefox session

The following error exists:
`1548378361023 webdriver::server DEBUG -> GET /session/37a84d31-6258-4a95-83df-71636be0486b
1548378361023 webdriver::server DEBUG <- 404 Not Found {"value":{"error":"unknown command","message":"GET /session/37a84d31-6258-4a95-83df-71636be0486b did not match a known command","stacktrace":""}}`

As you can see this is a GET request to the session end-point, which is not supported per the WebDriver spec: https://w3c.github.io/webdriver/#endpoints. Only a DELETE request is allowed. This is information told to me in a different forum.

Example session information:
{
  "status": 0,
  "sessionId": "f99e6368-2c20-4f1c-a4aa-8e82996891a0",
  "value": {
    "acceptInsecureCerts": false,
    "browserName": "firefox",
    "browserVersion": "60.0.2",
    "moz:accessibilityChecks": false,
    "moz:geckodriverVersion": "0.23.0",
    "moz:headless": false,
    "moz:processID": 4136,
    "moz:profile": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\rust_mozprofile.1lAT8bhXRIlV",
    "moz:useNonSpecCompliantPointerOrigin": false,
    "moz:webdriverClick": true,
    "pageLoadStrategy": "normal",
    "platformName": "windows_nt",
    "platformVersion": "10.0",
    "rotatable": false,
    "timeouts": {
      "implicit": 0,
      "pageLoad": 300000,
      "script": 30000
    },
    "webdriver.remote.sessionid": "f99e6368-2c20-4f1c-a4aa-8e82996891a0"
  }

Here is the trace logging from the webdriverJs:

C:\svt-web-client\projects\client-ng>npm run webdriver-start

hpe-simplivity-web-client@1.0.0 webdriver-start C:\svt-web-client\projects\client-ng
webdriver-manager start

[19:05:03] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
[19:05:03] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[19:05:04] I/config_source - curl -oC:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[19:05:05] I/start - java -Dwebdriver.chrome.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\chromedriver_2.45.exe -Dwebdriver.gecko.driver=C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\geckodriver-v0.23.0.exe -jar C:\svt-web-client\projects\client-ng\node_modules\webdriver-manager\selenium\selenium-server-standalone-3.141.59.jar -port 4444
[19:05:05] I/start - seleniumProcess.pid: 2240
19:05:05.430 INFO [GridLauncherV3.parse] - Selenium server version: 3.141.59, revision: e82be7d358
19:05:05.570 INFO [GridLauncherV3.lambda$buildLaunchers$3] - Launching a standalone Selenium Server on port 4444
2019-01-24 19:05:05.664:INFO::main: Logging initialized @606ms to org.seleniumhq.jetty9.util.log.StdErrLog
19:05:06.008 INFO [WebDriverServlet.] - Initialising WebDriverServlet
19:05:06.226 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
19:05:15.586 INFO [ActiveSessionFactory.apply] - Capabilities are: {
"browserName": "firefox",
"marionette": true,
"moz:firefoxOptions": {
"log": {
"level": "trace"
}
}
}
19:05:15.601 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
1548378316617 mozrunner::runner INFO Running command: "C:\Program Files\Mozilla Firefox\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\Users\ADMINI~1\AppData\Local\Temp\rust_mozprofile.Og9GpA9J0LSo"
1548378316617 geckodriver::marionette DEBUG Waiting 60s to connect to browser on 127.0.0.1:60167
1548378317118 Marionette DEBUG Received observer notification profile-after-change
1548378317241 Marionette DEBUG Received observer notification command-line-startup
1548378317241 Marionette DEBUG Received observer notification nsPref:changed
1548378318871 Marionette DEBUG Received observer notification sessionstore-windows-restored
1548378319053 Marionette DEBUG Setting recommended pref apz.content_response_timeout to 60000
1548378319055 Marionette DEBUG Setting recommended pref browser.download.panel.shown to true
1548378319056 Marionette DEBUG Setting recommended pref browser.EULA.override to true
1548378319056 Marionette DEBUG Setting recommended pref browser.offline to false
1548378319056 Marionette DEBUG Setting recommended pref browser.pagethumbnails.capturing_disabled to true
1548378319056 Marionette DEBUG Setting recommended pref browser.search.update to false
1548378319057 Marionette DEBUG Setting recommended pref toolkit.cosmeticAnimations.enabled to false
1548378319057 Marionette DEBUG Setting recommended pref browser.tabs.disableBackgroundZombification to false
1548378319057 Marionette DEBUG Setting recommended pref browser.tabs.warnOnCloseOtherTabs to false
1548378319058 Marionette DEBUG Setting recommended pref browser.tabs.warnOnOpen to false
1548378319058 Marionette DEBUG Setting recommended pref browser.usedOnWindows10.introURL to
1548378319058 Marionette DEBUG Setting recommended pref browser.urlbar.suggest.searches to false
1548378319058 Marionette DEBUG Setting recommended pref browser.urlbar.userMadeSearchSuggestionsChoice to true
1548378319058 Marionette DEBUG Setting recommended pref datareporting.policy.dataSubmissionPolicyAccepted to false
1548378319058 Marionette DEBUG Setting recommended pref dom.disable_open_during_load to false
1548378319058 Marionette DEBUG Setting recommended pref dom.file.createInChild to true
1548378319059 Marionette DEBUG Setting recommended pref dom.max_chrome_script_run_time to 0
1548378319059 Marionette DEBUG Setting recommended pref dom.max_script_run_time to 0
1548378319059 Marionette DEBUG Setting recommended pref extensions.getAddons.cache.enabled to false
1548378319059 Marionette DEBUG Setting recommended pref extensions.shield-recipe-client.api_url to
1548378319059 Marionette DEBUG Setting recommended pref extensions.webservice.discoverURL to http://%(server)s/dummy/discoveryURL
1548378319060 Marionette DEBUG Setting recommended pref network.http.prompt-temp-redirect to false
1548378319060 Marionette DEBUG Setting recommended pref network.http.speculative-parallel-limit to 0
1548378319060 Marionette DEBUG Setting recommended pref security.fileuri.strict_origin_policy to false
1548378319060 Marionette DEBUG Setting recommended pref security.notification_enable_delay to 0
1548378319060 Marionette DEBUG Setting recommended pref signon.autofillForms to false
1548378319060 Marionette DEBUG Setting recommended pref signon.rememberSignons to false
1548378319115 Marionette DEBUG New connections are accepted
1548378319116 Marionette INFO Listening on port 60167
1548378319398 geckodriver::marionette DEBUG Connection established on 127.0.0.1:60167. Waiting for Marionette handshake
1548378319420 Marionette DEBUG Accepted connection 0 from 127.0.0.1:60178
1548378319414 geckodriver::marionette DEBUG Connected to Marionette
1548378319426 Marionette TRACE 0 -> [0,1,"WebDriver:NewSession",{"browserName":"firefox"}]
1548378319578 Marionette DEBUG Register listener.js for window 4294967297
19:05:19.617 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
1548378319591 Marionette TRACE 0 <- [1,1,null,{"sessionId":"37a84d31-6258-4a95-83df-71636be0486b","capabilities":{"browserName":"firefox","browserVersion":"60.0. ... AppData\Local\Temp\rust_mozprofile.Og9GpA9J0LSo","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true}}]
19:05:19.742 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 37a84d31-6258-4a95-83df-71636be0486b (org.openqa.selenium.firefox.GeckoDriverService)
1548378319586 webdriver::server DEBUG <- 200 OK {"value":{"sessionId":"37a84d31-6258-4a95-83df-71636be0486b","capabilities":{"acceptInsecureCerts":false,"browserName":"firefox","browserVersion":"60.0.2","moz:accessibilityChecks":false,"moz:geckodriverVersion":"0.23.0","moz:headless":false,"moz:processID":8340,"moz:profile":"C:\Users\Administrator\AppData\Local\Temp\rust_mozprofile.Og9GpA9J0LSo","moz:useNonSpecCompliantPointerOrigin":false,"moz:webdriverClick":true,"pageLoadStrategy":"normal","platformName":"windows_nt","platformVersion":"10.0","rotatable":false,"timeouts":{"implicit":0,"pageLoad":300000,"script":30000}}}}
1548378361023 webdriver::server DEBUG -> GET /session/37a84d31-6258-4a95-83df-71636be0486b
1548378361023 webdriver::server DEBUG <- 404 Not Found {"value":{"error":"unknown command","message":"GET /session/37a84d31-6258-4a95-83df-71636be0486b did not match a known command","stacktrace":""}}

**Comment by cnishina** [comment]
Did you check if the session actually exists? If you navigate to http://127.0.0.1:4444/wd/hub on your browser, do you actually see the session?

**Comment by tfaron** [comment]
Yes I create the session from the URL and it exists. Then i use the SessionId and set seleniumSessionId to it. Also if I run the curl command to get all the sessions /SESSIONS it returns them all, and if i run the command to get the session url /SESSION/<id>/url it returns so it seems to be specific to GET

**Comment by tfaron** [comment]
Any chance anyone has gotten Firefox to work with protractor when using seleniumSessionId or is there any more information I should provide.

**Comment by tfaron** [comment]
@cnishina in the 6.0 beta this seems to be fixed.
For 5.4.1 it looks like the problem is related getNewDriver() as changing these lines work.

getNewDriver() {

		
		// Jesse changed these 3 lines
		const session = new selenium_webdriver_1.Session(this.config_.seleniumSessionId, null);
		const newDriver = new selenium_webdriver_1.WebDriver(session, executor);

Also is there an ETA on when 6.0.0 is expected to go live?

**Comment by jvitorino** [comment]
to clarify Tim's post, the change was made manually in attachSession.js

I commented out:
const newDriver = selenium_webdriver_1.WebDriver.attachToSession(executor, this.config_.seleniumSessionId); 

and added:
const session = new selenium_webdriver_1.Session(this.config_.seleniumSessionId, new selenium_webdriver_1.Capabilities(this.config_.capabilities));
const newDriver = new selenium_webdriver_1.WebDriver(session, executor);

**Comment by cnishina** [comment]
Sweet. Then this is fixed! Protractor 6 is live. Closing this issue.
