### ISSUE TITLE
Failed: stale element reference: element is not attached to the page document

### ISSUE THREAD

**Issue by think4ideas** [angular/protractor#5134]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

Bug report
here is my code:

- Node Version: `~10.11.3`
- Protractor Version: `~5.4.0`
- Angular Version: `~6.1.1`
- Browser(s): `chrome`
- Operating System and Version `ubuntu 16.04`
-
protractor file: 
exports.config = {
  allScriptsTimeout: 11000,
  specs: ['./src/**/*.e2e-spec.ts'],
  capabilities: {
    browserName: 'chrome',
    chromeOptions: {
    },
  },
  directConnect: true,
  baseUrl: 'http://localhost:8100/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {},
  },
  onPrepare() {
    require('ts-node').register({
      project: 'tsconfig.e2e.json',
    });
    jasmine
      .getEnv()
      .addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  },
};
code:
    const items = element.all(by.css('ion-card ion-label'));
    // console.log(items);
        items.each((ele) => {
          ele.getText().then((res) => {
            console.log(res);
            done();
          });
        });
expecting result:
 list of items labels
output:
-----------------
Some time it may get correct output. most of the case it shows errors,
sometime shows this
1. Failed: stale element reference: element is not attached to the page document
some time shows this,
2. Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
