### ISSUE TITLE
feat(locators): cssContainingText may include provision for exact match

### ISSUE THREAD

**Issue by Jayasankar-m** [angular/protractor#5139]
Feature Request
---
A provision to match exactly for 'cssContainingText' may be introduced

- Reasons for adopting new feature
Consider the following case
```
<div>
<h4>Textarea</h4>
<h4>Text</h4>
</div>
```
With element locator as `element(by.cssContainingText('h4', 'Text')) ` it will return `Textarea` element

- Is this a breaking change? (How will this affect existing functionality)
    Not a breaking change as only a flag needs to be added for matching

**Comment by GitSage** [comment]
I'd like this feature too.

Workaround I found was to use `xpath`:

```element(by.xpath('//h4[text()="Text"'))```

This queries for an exact match. 

Be warned, "exact match" includes case sensitivity and whitespace. You can use xpath function `transform` to deal with case sensitivity and `normalize-whitespace` for weird whitespace.

**Comment by cnishina** [comment]
This would have to be a new API. I'm not sure how often you have an exact match on text. Also you can already do this with more a little bit more work.

Why not do something like:

```
const textEl = element.all(by.cssContainingText('h4', 'Text')).filter(async (el) => {
  return await el.getText() === 'Text';
});
```

Also it looks like you can do this already with xpath. Closing this issue.
