### ISSUE TITLE
the source-map-support is an old version, causes [DEP0005] DeprecationWarning: Buffer() 

### ISSUE THREAD

**Issue by AlexanderGuncenko** [angular/protractor#5141]
hey,

please update the "source-map-support": "~0.4.0"  package.
it causes: "[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead."
when used with typescript and its sourcemap Feature.

- node -v v11.9.0
- npm -v 6.5.0
- protractor --version Version 5.4.2

**Comment by cnishina** [comment]
We are not updating 5.4.2 and it looks like we should update it on selenium4.
https://github.com/angular/protractor/blob/selenium4/package.json#L23

**Comment by cnishina** [comment]
Okay closing this issue. I did an audit on the release for Protractor 6. This should be fixed.
