### ISSUE TITLE
multiple browser.waitForAngularEnabled in a method not working

### ISSUE THREAD

**Issue by tfaron** [angular/protractor#5143]
Hi there!
---

- Node Version: `10.15.0`
- Protractor Version: `6.0.0-beta`
- Angular Version: `4.3.0`
- Browser(s): `chrome`
- Operating System and Version `Windows 10`

I have methods I call where I was previously ran using multiple ignoreSynchronization but I switch to waitForAngularEnabled from within my test and I get the following output based on the same function below.

[2019-02-07T11:18:44.618] [INFO] VClientActions.login - a1: true
[2019-02-07T11:18:44.622] [INFO] VClientActions.login - a2: true

I would assume a2 would equal false after browser.waitForAngularEnabled(false); is called.

`login(): void {
    // Get the page
    browser.waitForAngularEnabled().then((a1: any) => {
      logger.info('a1: ' + a1);

      browser.waitForAngularEnabled(false);
      browser.waitForAngularEnabled().then((a2: any) => {
        logger.info('a2: ' + a2);
      });
    });`

Subsequently: in 5.4 if I run 
log (browser.ignoreSynchronization);
browser.ignoreSynchronization = true;
log (browser.ignoreSynchronization);

I get 'false' followed by 'true'

**Comment by GitSage** [comment]
You've called `waitForAngularEnabled()` 3 times. You're setting it to `true`, then `false`, then back to `true`. But you're never printing the middle `false`.

Try this:

```
login(): void {
  // Get the page
  browser.waitForAngularEnabled().then((a1: any) => {
    logger.info('a1: ' + a1);
    browser.waitForAngularEnabled(false).then((a2: any) => {
      logger.info('a2: ' + a2);
    });
  });
}
```

**Comment by tfaron** [comment]
@GitSage Thanks for the reply.
My understanding from the method doc is calling `browser.waitForAngularEnabled()` with no arguments is that it will just return the current setting. So my intention was to get the current setting, set it to true by passing false and then getting the value again to verify it changes

**Comment by GitSage** [comment]
@tfaron ahh you're right, my mistake. In this case I suspect your issue is an asynchronous one. You didn't wait for your middle promise to complete before moving on to the third one.

Try this: 

```
login(): void {
  // Get the page
  browser.waitForAngularEnabled().then((a1: any) => {
    logger.info('a1: ' + a1);
    browser.waitForAngularEnabled(false).then(() => {
      browser.waitForAngularEnabled(false).then((a2: any) => {
        logger.info('a2: ' + a2);
      });
    });
  });
}
```

Alternatively, if you're using Node 8+, you can accomplish the same thing using `async/await`:

```
async login(): void {
  // Get the page
  const a1 = await browser.waitForAngularEnabled();
  logger.info('a1: ' + a1);
  await browser.waitForAngularEnabled(false);
  const a2 = await browser.waitForAngularEnabled();
  logger.info('a2: ' + a2);
}
```

**Comment by tfaron** [comment]
Thanks I'll give it a try, appreciate the help.

**Comment by cnishina** [comment]
It looks like I can close this. `waitForAngularEnabled` when getting and setting should be awaited. If this is still an issue please feel free to open. @GitSage thank you for your responses.
