### ISSUE TITLE
Protractor|| webdriver-manager start or update is not recognized

### ISSUE THREAD

**Issue by Ranjithsamalla** [angular/protractor#5157]
Hi there!
 I'm not able to recognize protractor in my PC and even web driver-manger start or update cmd also not able to recognized 

for above issue i set path in environment variable but still I'm facing same issue could you please help on this how to resolve

I can able to see version names node -v and npm -v but not able to see for protractor etc..

protractor : The term 'protractor' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ protractor --version
+ ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (protractor:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by samiullah** [comment]
@Ranjithsamalla  Can u check if protractor is installed in system. Also please share the code snippet which u r writing for tests

**Comment by Ranjithsamalla** [comment]
Yes, it is installed globally and locally but when I type protractor --version it is showing the above error,

please check the code snippet
describe('angularjs homepage', function() {
  it('should greet the named user', function() {
    browser.get('http://www.angularjs.org');

    element(by.model('yourName')).sendKeys('Julie');

    var greeting = element(by.binding('yourName'));

    expect(greeting.getText()).toEqual('Hello Julie!');
  });

  describe('todo list', function() {
    var todoList;

    beforeEach(function() {
      browser.get('http://www.angularjs.org');

      todoList = element.all(by.repeater('todo in todoList.todos'));
    });

    it('should list todos', function() {
      expect(todoList.count()).toEqual(2);
      expect(todoList.get(1).getText()).toEqual('build an AngularJS app');
    });

    it('should add a todo', function() {
      var addTodo = element(by.model('todoList.todoText'));
      var addButton = element(by.css('[value="add"]'));

      addTodo.sendKeys('write a protractor test');
      addButton.click();

      expect(todoList.count()).toEqual(3);
      expect(todoList.get(2).getText()).toEqual('write a protractor test');
    });
  });
});
![capture](https://user-images.githubusercontent.com/37171202/53473232-d92f4980-3a8f-11e9-8778-a14bc4030046.PNG)
![capture1](https://user-images.githubusercontent.com/37171202/53473271-f95f0880-3a8f-11e9-878b-f1b482d18cce.PNG)

**Comment by cnishina** [comment]
You should run Protractor locally as well as webdriver-manager. You should add scripts to your package.json file to get this to work. I answered something similar here:

https://stackoverflow.com/questions/24656341/npm-run-webdriver-manager-update-seems-bugged/42751988#42751988

Closing this issue since it is not an issue with the Protractor framework.
