### ISSUE TITLE
Writing Page Objects in Protractor - Is this Implementation Correct

### ISSUE THREAD

**Issue by mangeshkhaire14** [angular/protractor#5164]
Hi,

I have come with this kind of implemention for page objects but i don't know whether this is correct or not but its working file. I am not expert in node js programming but I want to know that will all page elements will be initialised or it will find the elements as an when constructor loads  or will it find when actual operatios on that elements will  be performed. please provide suggestion on this

var emailTextBox='[name="login_email"]';
var passwordTextBox='[name="login_password"]';
var signInButton="button>.signin-text";

class SignInPage{
    
    constructor(){
        this.emailTextBox=element(by.css(emailTextBox));
        this.passwordTextBox=element(by.css(passwordTextBox));
        this.signInButton=element(by.css(signInButton));

**Comment by jithinkmatthew** [comment]
@mangeshkhaire14 , Please post questions in [gitter](https://gitter.im/angular/protractor) or [StackOverflow](http://stackoverflow.com)

**Comment by mangeshkhaire14** [comment]
@jithinkmatthew  Ok
