### ISSUE TITLE
Actions doesn't work with SELENIUM_PROMISE_MANAGER

### ISSUE THREAD

**Issue by andreroggeri** [angular/protractor#5169]
Bug report
---

The action builder doesn't execute/wait the action chain in the correct order if SELENIUM_PROMISE_MANAGER is set to false.

- Node Version: `10.1.0`
- Protractor Version: `5.4.2`
- Angular Version: `7.0.0`
- Browser(s): `Chrome`
- Operating System and Version `Windows 10`
- Your protractor configuration file
```
exports.config = {
  allScriptsTimeout: 50000,
  specs: [
    './src/*spec.ts'
  ],
  capabilities: {
    'browserName': 'chrome'
  },
  directConnect: true,
  baseUrl: '',
  framework: 'jasmine',
  SELENIUM_PROMISE_MANAGER: false,
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000,
    print: function() {}
  },
  onPrepare() {
    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.json')
    });
    jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
  }
};
```
- A relevant example test
```
describe('angular homepage', function() {
      it('Should navigate with action builder', async function() {
        await browser.manage().window().maximize()
        await browser.get('https://angular.io/docs')
        await browser.actions()
                      .mouseMove($('button[title="The fundamentals of Angular"]'))
                      .click()
                      .mouseMove($('button[title="The basic building blocks of Angular applications."]'))
                      .click()
                      .mouseMove($('a[title="Beyond the basics."]'))
                      .click()
                      .perform();
        await browser.sleep(5000);
      });
  });
```
- Output from running the test
N/A
- Steps to reproduce the bug
Run the test with SELENIUM_PROMISE_MANAGER = false and true and check the difference
- The URL you are running your tests against (if relevant)
N/A

**Comment by cnishina** [comment]
I think mouseMove takes a WebElement and not an ElementFinder. This might have worked via the magic of the control flow. 

So maybe:
```
await browser.actions()
  .mouseMove(await $('button[title="The fundamentals of Angular"]').getWebElement())
  .click()
```

**Comment by cnishina** [comment]
Yes this might not be in the typings because of the state of the actions API / current typings. If you have time, feel free to create a PR and @ me on it. Thanks!

**Comment by andreroggeri** [comment]
Yeah, that worked, but I'm kinda lost here.


Since the `actions()`  is from the webdriverjs, there is no Angular handling during the action chain, right ?

So whats the proper fix here ? Implement the actions in Protractor or something else ?

**Comment by cnishina** [comment]
This is actually probably a complicated fix. Currently we expose `actions()` from selenium-webdriver. If you wanted it to take an `ElementFinder`, you would have to implement the entire Actions / ActionSequence API and check if it is an ElementFinder or a WebElement and convert ElementFinders to WebElements then pass it the Actions / ActionSequence API.

I think understanding that sometimes Protractor outputs and exposes the underlying library is important. I am not sure if it is currently worth fixing. I'm going to close this issue since it looks resolved.
