### ISSUE TITLE
Unhandled alert message appear twice with IE Driver

### ISSUE THREAD

**Issue by nramprakash88** [angular/protractor#5175]
I get a unhandled alert in my execution with content "Press a button!"

When i run the protractor test scripts in **Chrome browser**, I get the exception message like  
unexpected alert open: {Alert text : **Press a button!**}
  (Session info: chrome=72.0.3626.119)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

But when i run the protractor test scripts in **IE browser**, I get the exception message like below 
UnexpectedAlertOpenError: Modal dialog present with text: **Press a button!**: **Press a button!**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'LRAMPRAKASH', ip: '192.168.220.105', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: unknown

You can see that the alert message is appearing twice in the exception.  

The IEDriver version is 3.141.5

Is this a problem with the IE Driver ?

**Comment by cnishina** [comment]
There are always problems with IE Driver. I am not sure how much development or support is going into IE Driver since IE has reached its end of life a while ago. I'm going to close this issue since it is not a Protractor issue. I would write this issue with maybe Selenium.
