### ISSUE TITLE
Question: Updates about Protractor

### ISSUE THREAD

**Issue by Ptit-Biscuit** [angular/protractor#5179]
Hi there!

Just a little issue to know if protractor is dead or not ?
As there have not been any single commit since December I'm wondering if the Angular team still works on the project or if I should seek for alternatives.
Thank you

**Comment by CrispusDH** [comment]
Here you could track some progress https://github.com/angular/protractor/issues/5159 .

**Comment by cnishina** [comment]
Oh hey! I'm trying to do the release some time today. Sorry about that. Its been sitting in beta and I got busy with other priority items.

**Comment by Ptit-Biscuit** [comment]
No problem. I'm aware that you guys have priorities other than protractor xD.
Thanks anyway.

**Comment by cnishina** [comment]
Okay so Protractor 6 is released. All the commits were in the selenium4 branch... which is now the master branch. Huzzah!

Closing this issue. 😃

**Comment by yevhen309** [comment]
And now? Is protractor dead or not?

**Comment by edimitchel** [comment]
@cnishina ?
