### ISSUE TITLE
My code is not performing any action on browser even though the method is getting executed

### ISSUE THREAD

**Issue by Satish152** [angular/protractor#5188]
i'm trying to implement the Protractor-Cucumber-framework in my project.. when execute the code.. methods are getting executed but the code inside the method is not getting executed.. i mean when i tried to click or enter the data in field or pause the browser execution through browser.sleep these actions are getting performed.. and also my script is not failing.

**My StepDef file**

`var login=require("../src/main/java/Utilities/LoginPage.js");

var test1=function(){

   var local=this;

      Given('Open the Browser', function () {
       console.log("first executed")
       browser.ignoreSynchronization=true;
       login.get("https://abhibus.com");

     });

     Given('Load the URL', function () {
       // Write code here that turns the phrase above into concrete actions
       console.log("second executed");
         browser.getTitle().then(function(title){
             console.log(title+" title of the webpage");
         });
         browser.sleep(5000);
     });

     Then('Get the Title of the webpage', function () {
       // Write code here that turns the phrase above into concrete actions  
       console.log("third executed");
     browser.driver.findElement(By.id("LoginForm_username")).sendKeys("admin@admin@bkcms.com");
      browser.driver.findElement(By.id("Loginform_password")).sendKeys("test");
     //  login.loginpage("admin@admin@bkcms.com","test");
    browser.sleep(3000);
     });

    }
    module.exports=new test1();`

**My Config file**
`exports.config = {

seleniumAddress: 'http://localhost:4444/wd/hub',
getPageTimeout: 60000,
allScriptsTimeout: 500000,
framework: 'custom',
// path relative to the current config file
frameworkPath: require.resolve('protractor-cucumber-framework'),
capabilities: {
    'browserName': 'chrome'
},

// Spec patterns are relative to this directory.
specs: [
    '../Protractor.Cucumber.Test/src/main/java/featureFiles/Test.feature'
],

cucumberOpts: {
    require: '../Protractor.Cucumber.Test/src/test/java/StepDefinitions/test1.js',
    tags: false,
    profile: false,
    'no-source': true
},
 onPrepare: function () {
const {Given, Then, When, Before} = require('cucumber');
global.Given = Given;
global.When = When;
global.Then = Then;
global.Before = Before;
} };`

please some one help me to find out the issue..

**Comment by cnishina** [comment]
If you are using the driver object, you are using selenium-webdriver. I would look into the selenium-webdriver APIs why this is not working. Just a quick review of your code snippet, I would suggest making this async / await.

Since this looks like a support question, I am closing this issue. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
