### ISSUE TITLE
Change the default audio capture device of browser

### ISSUE THREAD

**Issue by iamporus** [angular/protractor#5195]
I've a USB microphone connected to my system which I want to use while running my tests. However, the browser always uses the default system microphone; which my system doesn't have :( and hence my test fails.
I tried adding the following in conf.js to disable default mic, but it's not working.
```
prefs:{
'media.default_audio_capture_device' : 0
}
```
I tried passing in the name of the audio device as shown in chrome settings as well but to no success. 

Any help is much appreciated.

**Comment by cnishina** [comment]
I did not know Protractor has a microphone setting. What does it do? What was it supposed to do?

**Comment by iamporus** [comment]
My use case depends upon using a microphone inside a browser window. There are configurations available in protractor to simulate fake audio/video streams coming through to the browser. But my use case depends upon using an actual USB microphone. I stumbled upon `media.default_audio_capture_device` configuration when I was looking to change the default one to USB. Just not sure how to invoke it.

**Comment by iamporus** [comment]
I was finally able to achieve this by changing my system's default audio source to USB using pulseaudio.

Here's the command:
`pacmd list-sources`
This will present you with available audio capture devices. Note down the name of the device are interested in. Then,
`pacmd set-default-source <name of audio capture device> `

Starting protractor after this, it automatically picked up the USB microphone.  Not sure how one would be able to do this on non-linux platforms.
