### ISSUE TITLE
Should be able to chain findElement to find child elements

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#52]
This currently doesn't work in webdriver with js selectors, but it's a huge pain when there are two elements with the same binding (e.g. item.name).

**Comment by EMCP** [comment]
I needed this but the url is 404 `https://github.com/angular/protractor/blob/master/spec/basic/findelements_spec.js`

**Comment by dhanrajpru** [comment]
<input class="form-control input-sm" type="text" placeholder="Username">
<input class="form-control input-sm" type="text" placeholder="Confirm Username">

how to locate both  in protractor using java script?
