### ISSUE TITLE
CHANGELOG References are re-directing to 404 Page

### ISSUE THREAD

**Issue by jithinkmatthew** [angular/protractor#5204]
Bug report
---
Hi, 
Please open CHANGELOG.md(`v6.0.0`) file and check `Features `  ,  `Dependencies ` commit references. It is redirecting to 404 Page. 

It is not difficult to find those commits. Created just for your information.

[features](https://github.com/angular/protractor/blob/master/CHANGELOG.md#features)
[dependencies](https://github.com/angular/protractor/blob/master/CHANGELOG.md#dependencies)

**Comment by cnishina** [comment]
Weird. I wonder if this is because I created these when I was in the selenium4 branch? I'll fix this next week. Thanks!

**Comment by cnishina** [comment]
Oh nevermind. I just saw the PR. Thank you!

**Comment by cnishina** [comment]
Closed with https://github.com/angular/protractor/pull/5205
