### ISSUE TITLE
Trying to execute API request multiple times by keeping the browser active in protractor(JavaScript)

### ISSUE THREAD

**Issue by JasonDarus9** [angular/protractor#5207]
Hi there!

Thanks for helping an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. I trying to execute the function that hitting the POST API call multiple times and validates a field in the response, I've to wait around 6 mins(this is because their is Job processor that runs every 5 mins process the action that I do on the UI ) until the field changes to what I'm excepting.
2. The other problem is while I'm waiting for 5/6 mins I should keep the browser active(like doing a refresh for every 10 seconds).

So I wrote the below function but I'm not sure it is not doing what I want. Can someone please help me out

Bug report
---

- Node Version: `5.8`
- Protractor Version: `5.4.2`
- Angular Version: `5.2.10`
- Browser(s): `Chrome`
- Operating System and Version `Mac OS Mojave`

Code I trying to Execute
---
const payload = [{
key: 'parentId',
value: `hdsf3-hds3e-2334jhk-kjka3842`,
matchType: 'EXACT'
}];
this.waitFortheEntryRecord = function() {
return browser.wait(function () {
browser.sleep(15000);
browser.refresh();
return request.post({
url: `${Configuration.endpoint}/configuration/search?take=10&skip=0&orderBy=created&orderDirection=DESC`,
headers: {
'Content-Type': 'application/json'
},
auth: {
bearer: `${env.auth.token}`
},
body: JSON.stringify(payload)
}, function (error, response) {
if (error) {
console.log(error);
return false;
}
if (JSON.parse(response.body)[0].currentState === 'Cancelled') {
console.log('Passed');
return true;
}
console.log(`Waiting for the entry record to go to cancelled State ${JSON.parse(response.body)[0].currentState}`);
return false;
}, function () {
console.log('Waiting!');
return false;
});
}, 120000, 'Entry record did not turn to cancelled within the given time');
};
done();
});

**Comment by cnishina** [comment]
Could you format your code? This is difficult to read.

**Comment by JasonDarus9** [comment]
<img width="976" alt="Screen Shot 2019-04-13 at 8 16 43 PM" src="https://user-images.githubusercontent.com/48900681/56087062-1b86cd00-5e29-11e9-805d-49312e16845a.png">

**Comment by JasonDarus9** [comment]
@cnishina I tried searching in the stackOverflow but no luck

**Comment by JosephBittman** [comment]
You do not need to refresh the browser to keep it active. There is at least one jasmine/cucumber/etc timeout that you will need to set to a value above the 6 min you require. Which framework are you using with protractor?

The following is all you need besides increasing the framework timeout to allow a test case to run that long.

```
// call api to add your item for processing

// now wait for processing
await browser.wait(async () => yourPostCall(args).then(response => {
  if (JSON.parse(response.body)[0].currentState === 'Cancelled') {
    return true;
  } else return browser.sleep(15000);
}, err => {console.log(err); return false; }), timeoutValue, 'waiting for processing to finish');

// the rest of the test code
```

**Comment by JasonDarus9** [comment]
@JosephBittman  Thanks for the suggestion. I'll try that out.I'm using `framework: 'jasmine2'`

**Comment by JosephBittman** [comment]
@JasonDarus9 , you have two options for increasing the jasmine timeout and one for the protractor timeout.

One is increasing the default timeout, jasmine.DEFAULT_TIMEOUT_INTERVAL.  This would increase the timeout of all specs, its, etc. A big impact here is when things start to fail during waits, each failure can take a very long time and in aggregate you may end up just having to kill the test run which means you don't get a good report or stack traces/etc.

You can set this by adding the following in your protractor conf file.

```
jasmineNodeOpts: {
    defaultTimeoutInterval: seconds*1000
}
```

Second is increasing the time allowed for an individual It to run. This is done by passing an extra argument.

it('your description', function () {}, seconds*1000)

Details on the second option are here: https://jasmine.github.io/api/3.4/global.html#it

For the overall protractor timeout, you can set the "allScriptsTimeout" variable in the protractor conf file (outside the jasmineNodeOpts object though).

Hope this helps ~

**Comment by SchnWalter** [comment]
When you want create an issue on an Open Source project it's best to read the [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md) guidelines or at least read the default text that appears in the "New Issue" form. Both specify that you should ask usage and debugging questions on discussion forums, not in the project issue queue.

> 2. Make sure you are not asking a usage or debugging question. If you are, use StackOverflow, Google Group discussion list, or Gitter to get help.

Please close this issue and post your question somewhere else.

P.S. I took a quick glance at your code, and I think that the RxJS `retry` operator might be able to help you. But this is definitely not protractor related.
