### ISSUE TITLE
Unable to select range for range selector control graph

### ISSUE THREAD

**Issue by PreetalC** [angular/protractor#5217]
Bug report
Unable to select range for range selector control graph

- Node Version: `10.1.0`
- Protractor Version: `5.3.2`
- Browser(s): `Chrome`
- Steps to reproduce the bug -

1) Try to automate range selector graph as shown in below image
2) Script need to move the circle left or right and graph should calculated the correct result
Please find below sample image for same

https://d585tldpucybw.cloudfront.net/sfimages/default-source/productsimages/winforms/controls/screenshots/winforms-rangeselector.png?sfvrsn=3d4f97_5

For security reason, can not post actual image of graph but our graph is made using D3.  
here we have used below HTML tags to achieve selection of range in graph
2 Circle tag ,1 rect tag and ,1 line tag 

For eg :- If manually i am moving the circle then pixcel value for above 4 elements is getting changed in DOM.

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!

**Comment by PreetalC** [comment]
Thank you for your response
