### ISSUE TITLE
Protractor to pass Google Authentication and redirect to app

### ISSUE THREAD

**Issue by luli0822** [angular/protractor#5218]
Hi there!

I am facing an issue while doing our e2e testing using protractor with Google Authentication. The flow is as below:
1. When the app loads initially, it just shows a Google Sign In button and a user can click it to log in.
2. It will display a popup window for Google Sign In as usual where we all are familiar with. 
3. From the window, it requires an email or phone firstly, then click Next if finished; now enter password, and click Next again; sometimes it may ask for a 2-step Authentication that requires a secure code.
4. After this external authentication piece completes, it will redirect to the dashboard screen.

- Node Version: `8.9.4`
- Protractor Version: `5.4.0`
- Angular Version: `7.1.0`
- Browser(s): `Chrome v73.*`
- Operating System and Version `MacOS 10.13.6`
- Protractor configuration file

const { SpecReporter } = require('jasmine-spec-reporter');
exports.config = {
     allScriptsTimeout: 11000,
     specs: [
       './src/**/*.e2e-spec.ts'
     ],
     capabilities: {
        'browserName': 'chrome',
        // chromeOptions: {
        //   binary: process.env.CHROM_BIN,
        //   args: [ '--headless', '--no-sandbox' ]
        // }
      },
      directConnect: true,
      baseUrl: 'http://localhost:4200/',
      framework: 'jasmine',
      jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 30000,
        print: function() {}
      },
      onPrepare() {
        require('ts-node').register({
          project: require('path').join(__dirname, './tsconfig.e2e.json')
        });
        jasmine.getEnv().addReporter(new SpecReporter({ spec: { displayStacktrace: true } }));
     }
}; 

- Spec file: dashboard.e2e-spec.ts:

`it('should land Dashboard Page after authentication', () => {
    loginPage.getGoogleButton().click();
    loginPage.authenticate();
    expect(dashboard.getHeader()).toBeTruthy();
});`

- login page auth.po.ts
`async authenticate() {

    await browser.driver.get('https://accounts.google.com/signin/oauth/oauthchooseaccount?client_id=***&destination=http%3A%2F%2Flocalhost%3A4200&approval_state=***&oauthgdpr=1&xsrfsig=***&flowName=GeneralOAuthFlow');  
    await browser.driver.findElement(by.id('identifierId')).sendKeys('useremail@abc.com');
    await browser.driver.findElement(by.id('identifierNext')).click();
    await browser.driver.findElement(by.css('input')).sendKeys('password');
    await browser.driver.findElement(by.id('passwordNext')).click();
    await browser.driver.findElement(by.id('totpPin')).sendKeys('111222');
    await browser.driver.findElement(by.id('totpNext')).click();
    return await browser.driver.wait(async() => {
      const url = await browser.driver.getCurrentUrl();
      return /profile/.test(url);
    }, 10000);

  } 
`

- Output from running the test

(node:47811) UnhandledPromiseRejectionWarning: NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":"*[id="identifierId"]"}
  (Session info: chrome=73.0.3683.103)
  (Driver info: chromedriver=2.46.628411 (3324f4c8be9ff2f70a05a30ebc72ffb013e1a71e),platform=Mac OS X 10.13.6 x86_64)

How do we bypass or process this Google popup using protactor or webdriver? Any feedback is highly appreciated. Thanks.

**Comment by cnishina** [comment]
Could you format your markdown? This is hard to read.

**Comment by cnishina** [comment]
Upon further inspection this looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
