### ISSUE TITLE
Protractor 5.4.2 does not work with Chrome 74+ combine with webdriver-manager 12.1.4, mime-types 2.1.24, and mime-db 1.40.0 (ubuntu:16.04  node:6.x)

### ISSUE THREAD

**Issue by shihuawang** [angular/protractor#5230]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: ``
- Protractor Version: ``
- Angular Version: ``
- Browser(s): ``
- Operating System and Version ``
- Your protractor configuration file
- A relevant example test
- Output from running the test
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by shihuawang** [comment]
Node Version: `6.x`
Protractor Version: `5.4.2`
Angular Version: `1.5.8`
Browser(s): `Chrome`
Operating System and Version `ubuntu 16.04`

**Comment by shihuawang** [comment]
The conf.js file is attached.
[conf.js.txt](https://github.com/angular/protractor/files/3149912/conf.js.txt)

**Comment by shihuawang** [comment]
A segment of failed test case:
  create:function(){
      var nnn_name = "E6-SIM-TEST";
      var nnn_filter = nei_name;
      var field_name_list = new Array();
      var field_value_list = new Array();

      if (arguments.length > 0) {
          nnn_name = arguments[0];
          nnn_filter = nnn_name;
          for (var i = 1; i < arguments.length; i+=2) {
              field_name_list.push(arguments[i]);
              field_value_list.push(arguments[i + 1]);
              console.log('Will modify ' + field_name_list[(i-1)/2] + ' to ' + field_value_list[(i-1)/2]);
          }
      }

      util.findElementByXPath("Create New Element").click();
      browser.sleep(1000);
      browser.driver.findElement(by.id('nnnElemId')).sendKeys(nnn_name);
      browser.driver.findElement(by.id('location')).sendKeys('TEST LOCATION');
      browser.driver.findElement(by.id('xxMmmm')).sendKeys(env.XXX_IP);
      browser.driver.findElement(by.id('yyMmmm')).sendKeys(env.YYY_IP);
      browser.sleep(1000);
      var elem = browser.driver.findElement(by.id('xxxxxxxxxx'));
      elem.clear();
      browser.sleep(2000);
      elem.sendKeys('bbbbb');
      browser.sleep(2000);
      var elem2 = browser.driver.findElement(by.id('xxxxxx'));
      elem2.clear();
      browser.sleep(2000);
      elem2.sendKeys('bbbb');
      browser.sleep(2000);

      for (var i = 0; i < field_name_list.length; i++) {
          var func = (function() {
              var j = i;
              return function() {
                  var field_name = field_name_list[j];
                  var field_value = field_value_list[j];
                  console.log('Modifying ' + field_name + ' to ' + field_value);

                  var elem = browser.driver.findElement(by.id(field_name));
                  if ((field_name == 'xxxxxx') || (field_name == 'yyyyyyy') || (field_name == 'zzzzzzz')) {
                      elem.sendKeys(field_value);
                      expect(elem.getAttribute('value')).toBe('string:' + field_value);
                  } else {
                      elem.clear();
                      elem.sendKeys(field_value);
                      expect(elem.getAttribute('value')).toBe(field_value);
                  }
              }
          })();
          browser.driver.findElement(by.id(field_name_list[i])).then(func);
          browser.sleep(1000);
      }
      if (field_name_list.includes('netElemType')) {
          browser.driver.findElement(by.id('ecoreGcpIP')).sendKeys(env.IN_BAND_IP);
      }
      browser.driver.findElement(by.xpath('//*[contains(text(), "Save")]')).click();
      browser.sleep(2000);
      util.findInList('Network Element Inventory',nei_filter, nei_name).then(function(res) {
          expect(res.getText()).toBe(nei_name);
          console.log("Element created successfully");
      },function(err) {
will fail the LM verification
          console.log("Warn: Element creation failed");
      });
  },

**Comment by shihuawang** [comment]
This failure happened several times recently when google-chrome-stable version changed.  Previously, I can work around this issue by using old version of Chrome, Chrome Driver, webdriver-manager, and a few weeks later the latest versions were fixed.  Friday (3 days ago) this was also fixed, but failed again today. And this time I can't find a work around. I tried to reverse to the previously worked combination of 73.x of chrome, chrome driver, webdriver-manager 12.1.1, mime-db@^1.38.0, mime-types@^2.1.22, but no luck this time.

**Comment by cnishina** [comment]
From the last comment, it appears you are using an old version of webdriver-manager. You need webdriver-manager@12.1.4. This should download with Protractor 5.4.2. You can get this by doing a fresh install of your node modules. If you are using Chrome 73 (please note that this is not the latest), you can download the correct chromedriver with `webdriver-manager update --versions.chrome 73.0.3683.68`. See http://chromedriver.chromium.org/downloads

Closing this issue since this appears to be similar to https://github.com/angular/protractor/issues/5225.

**Comment by shihuawang** [comment]
Because the new version of webdriver-manager@12.1.4 doesn't work (it worked only on May 3, Friday ), I had to try old version, but it doesn't work either.
