### ISSUE TITLE
Unable to run in parallel with Protractor 6 and shardTestFiles: true

### ISSUE THREAD

**Issue by GitSage** [angular/protractor#5232]
Bug report
---

- Node Version: 10.15.3
- Protractor Version: 6.0.0
- Angular Version: 6.1.8
- Browser(s): Chrome 74
- Operating System and Version Windows 10
 
Configuration file:
```
const path = process.cwd();
module.exports = {
	seleniumAddress: 'http://localhost:4444/wd/hub',
	framework: 'custom',
	frameworkPath: require.resolve('protractor-cucumber-framework'),

	specs: [ `${path}/features/**/*.feature` ],

	capabilities: {
		browserName: 'chrome',
		'chromeOptions': {
			'args': ['--headless', '--disable-gpu', '--disable-extensions', '--no-sandbox']
		},
		shardTestFiles: true,
		maxInstances: 2
	},
};
```

This configuration will fail to execute two tests in parallel. I have tracked down the bug in the Protractor source code.

The problem is in `launcher.ts`. https://github.com/angular/protractor/blob/4f74a4ec753c97adfe955fe468a39286a0a55837/lib/launcher.ts#L247-L251

The `await` causes the library to wait for each task to complete before spinning up a new one. This prevents more than a single test from being executed in parallel. I found that this fixed the issue:

```
  const maxConcurrentTasks = scheduler.maxConcurrentTasks();
  const taskArray = [];
  for (let i = 0; i < maxConcurrentTasks; ++i) {
    taskArray.push(createNextTaskRunner());
  }
  await Promise.all(taskArray);
  logger.info('Running ' + scheduler.countActiveTasks() + ' instances of WebDriver');
```

I do not believe this is an acceptable production solution, but I am not certain how to properly fix the bug. Let me know if you need more information or a more-complete minimal test case.

**Comment by vsravuri** [comment]
Could be similar to https://github.com/angular/protractor/issues/5145

**Comment by vsravuri** [comment]
Both multiCapabilities & shardTestFiles doesn't work in Protractor 6.0.0

**Comment by GitSage** [comment]
Yep, looks like the same problem. Do you think I should close this issue as a duplicate?

**Comment by vsravuri** [comment]
I added follow up note on https://github.com/angular/protractor/issues/5145

**Comment by cnishina** [comment]
Duplicate https://github.com/angular/protractor/issues/5145

Closing issue.
