### ISSUE TITLE
How to get the text of of div which has sub elements along with direct text?

### ISSUE THREAD

**Issue by karthiktelajala** [angular/protractor#5248]
Hi,

Can someone please help me in writing the XPath to get the text of a <div> which contains some other elements as well along with the text. Below is the HTML code:

<div class="message success fadable">
Successfully Deleted        
<a class="messageCloseButton" href="#">Close</a>
</div>

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
