### ISSUE TITLE
Protractor webdriver-manager update command doesnot update the chromedriver version to latest

### ISSUE THREAD

**Issue by GoutamNaikGaonkar** [angular/protractor#5250]
Node Version: v12.3.1
Protractor Version: 5.4.2
Angular Version: 6.0.3
Browser(s): `74.0.3729.169`
Operating System and Version Macbook Air MacOS Mojave

currently when we try to run the command webdriver-manager update it downloads the version 2.46 which supports chrome browser version v71-73 but current latest chrome version is 74.0.3729.169

![Screenshot 2019-05-26 at 2 40 34 PM](https://user-images.githubusercontent.com/34531138/58379712-0757f300-7fc5-11e9-9c31-585315476757.png)

If I try to install the chrome driver version 74.0.3729.6 via command webdriver-manager update --versions.chrome=74.0.3729.6 it doesnot update the version to 74.0.3729.6 and throws error

![Screenshot 2019-05-26 at 2 41 25 PM](https://user-images.githubusercontent.com/34531138/58379851-c2cd5700-7fc6-11e9-8574-2725c7db49b9.png)

Also I tried manually downloading the chromedriver zip 74.0.3729.6 and pasting in webdriver-manager/selenium folder but still it doesnot work

The chromedriver version numbers have changed after 2.46 to 74.0.3729.6

![Screenshot 2019-05-26 at 2 50 23 PM](https://user-images.githubusercontent.com/34531138/58379758-bbf21480-7fc5-11e9-813b-10e0df3a8c7b.png)

Can anyone suggest any solution to update chromedriver version to 
74.0.3729.6 since currently my test cases are failing because my chromedriver version is 2.46 and browser version is 74.0.3729.169

**Comment by cnishina** [comment]
This is a resolved issue and you'll need to update your webdriver-manager node module. The current version is 12.1.5. There are two ways to do this:

* Remove your node modules directory and reinstall
*  Do an `npm i -f` which will force install the latest

webdriver-manager 12.1.5 will download chromedriver version 75 by default. Chrome version 75 was released either yesterday or today.
