### ISSUE TITLE
How can we Run Few Specs[it blocks] on firefox browser and few specs[it blocks] on Chrome browser of same js file in protractor

### ISSUE THREAD

**Issue by janilkumarreddy** [angular/protractor#5257]
Say I have one test case [one js file - say name Test.js] with 10 specs[10 it blocks] in it. Now requirement is need to execute first 8 it blocks in chrome browser and remaining two it blocks should run in firefox.

In another way how to initialize a browser [i.e. what ever the browser required firefox, chrome...]at it block level wherever required. Is there any method/process to achieve that?

**Comment by cnishina** [comment]
I just saw this question on StackOverflow and I believe it is the right place to post this question. This is more for issues to do with Protractor itself. For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
