### ISSUE TITLE
Support for the Firefox >=48

### ISSUE THREAD

**Issue by imaynotbereal** [angular/protractor#5299]
Hello, 

From the protractor docs, I see the statement 'For the moment, we recommend testing against FireFox 47.' 
When can we expect protractor to support higher versions of Firefox? 

In the interim, can protractor be used with any higher version of Firefox, if there are issues with the latest.

**Comment by cnishina** [comment]
Closing this issue. This has been resolved a while ago. Also responded to the stackoverflow thread. https://stackoverflow.com/questions/57506688/protractor-support-for-the-firefox-48/57514513#57514513

**Comment by imaynotbereal** [comment]
The documentation still needs to be updated.
