### ISSUE TITLE
./node_modules/protractor/bin/protractor: No such file or directory

### ISSUE THREAD

**Issue by venky2k57** [angular/protractor#5305]
Hi Team,

We are getting below error when we are running test cases from Jenkins workspace.

$WORKSPACE/pymtsrv-org/disputes/SIT/HFE_UI_Regression_Pipeline/epp-system-qe@tmp/durable-26f7816f/script.sh: line 1: ./node_modules/protractor/bin/protractor: No such file or directory

From the project under ./node_modules/protractor/bin/ **protractor** is getting deleted suddenly.

Can you please let us know the issue?

**Comment by cnishina** [comment]
This might be something with Jenkins. You might be calling Protractor but not installing it? Or maybe your call to Protractor is out of order? I would ask this question on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor) with my context.

Thank you!
