### ISSUE TITLE
Not able to open chrome browser on protractor using eclipse

### ISSUE THREAD

**Issue by deepak8325** [angular/protractor#5307]
Hi there!

Thanks for submitting an issue to Protractor.

To help us help you better, please do the following before submitting an issue:

1. Review the questions section of [CONTRIBUTING.md](https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#contributing).
2. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor) to get help.
3. Provide a minimally reduced test case. This makes it much more likely that your bug will be fixed. Protractor has a test Angular application available at `http://www.protractortest.org/testapp` which you can use for the reproducible test case.
4. Fill in the information that corresponds to your type of issue below.
5. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue.)

Bug report
---

- Node Version: `v10.16.3`
- Protractor Version: `Version 5.4.2`
- Angular Version: ``
- Browser(s): `Chrome - 76.0.3809.132`
- Operating System and Version `linux`
- Your protractor configuration file
- A relevant example test
- Output from running the test - E/launcher - unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
E/launcher - Process exited with error code 199
- Steps to reproduce the bug
- The URL you are running your tests against (if relevant)

Feature Request - 
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

Issue - i have chrome (76.0.3809.132) and chromedriver which is updated using webdriver-manager update is "76.0.3809.12" & when i try to run config file, it throws following error - "I/launcher - Running 1 instances of WebDriver
[18:06:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[18:06:07] E/launcher - unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
E/launcher - Process exited with error code 199"

**Comment by cnishina** [comment]
Hi! This looks like a support question. Please ask your support questions on [StackOverflow](http://stackoverflow.com/questions/tagged/protractor), [Google Group discussion list](https://groups.google.com/forum/?fromgroups#!forum/angular), or [Gitter](https://gitter.im/angular/protractor). For more information please reference https://github.com/angular/protractor/blob/master/CONTRIBUTING.md#questions

Thank you!
