### ISSUE TITLE
SELENIUM_PROMISE_MANAGER: false, still not turned off

### ISSUE THREAD

**Issue by liekeninon** [angular/protractor#5309]
In your documentation you say that when somebody wants use the native async await of javascript they should set the selenium promise manager to false. 
When I go to the config option on github there is a command that the selenium promise manager will be fully disabled in Q4 of 2017.
Also when I open the GitHub issue https://github.com/SeleniumHQ/selenium/issues/2969 about removing the promise manager, this one is already closed.  

It is a bit confusing if the promise manager is removed or not. It is 2019 now and so far I can see it is not removed yet. When will the promise manager be removed for good?

**Comment by tymfear** [comment]
The promise manager is a part of Selenium webdriver, not Protractor. It is removed in Selenium 4 (and Protractor 6 as well). Since Protractor 6 is in alpha, and Protractor 5 is current stable version, the promise manager is still there. You can disable it and use native async await.

**Comment by cnishina** [comment]
Internally there are still some issues with the control flow but it allows you to write your test with async / await. Protractor 6 (still not released but mostly done) has removed the control flow completely and removed q promises.

Having your test with async / await (SELENIUM_PROMISE_MANAGER: false) is the step in the right direction.
