### ISSUE TITLE
Incorrect imports in lib/index.ts

### ISSUE THREAD

**Issue by sandersn** [angular/protractor#5325]
- Typescript: `3.7`, currently available as `typescript@3.7.0-beta`
- Protractor Version: `master`

lib/index.ts incorrectly re-exports two types from plugins.ts:

```ts
import {PluginConfig, ProtractorPlugin} from './plugins';
export type PluginConfig = PluginConfig;
export type ProtractorPlugin = ProtractorPlugin;
```

The references in the type aliases should be circular, but in current versions of Typescript, are not. The correct way to write this is:

```ts
export {PluginConfig, ProtractorPlugin} from './plugins';
```

In Typescript 3.7 the current code will be an error. The beta is available as `typescript@3.7.0-beta`. 

I'll create a PR shortly with the fix.

**Comment by esturkce** [comment]
I got the same error, is there a solution yet?
thanks

**Comment by userJulienMoreau** [comment]
I have the same error, for the moment I downgrade for typescript 3.6.4

**Comment by beh-rouz** [comment]
Same issue here, when I updated my angular project from version 8.x.x to 9.x.x and tried to get a production build with `ng build -c <config>` but eventually found a way to get around it.

I just removed node_modules, package-lock.json and run npm install.
```
$ rm -rf node_modules/ package-lock.json
$ npm install
```
