### ISSUE TITLE
drag and drop not working with protractor

### ISSUE THREAD

**Issue by aiswaryakg** [angular/protractor#5366]
`
sourceStop:ElementFinder = element(by.xpath('//div[@class="ui-table-scrollable-body"]//tr[1]//td[1]'));

destinationStop:ElementFinder =element(by.xpath('//div[@class="ui-table-scrollable-body"]'));`
browser.actions().dragAndDrop(source,dest).mouseUp().perform();

<div class="ui-dialog-titlebar ui-widget-header ui-helper-clearfix ui-corner-top ng-tns-c23-216 ng-star-inserted"
    style="">
    <span class="ui-dialog-title ng-tns-c23-216 ng-star-inserted" id="ui-dialog-24-label">
        <p-header _ngcontent-c28="">
            <p _ngcontent-c28="" class="modal-prompt">Resequence Stops</p>
        </p-header>
    </span>

</div>
<div class="ui-dialog-content ui-widget-content">
    <div _ngcontent-c28="" class="modal-body">
        <p-table _ngcontent-c28="" scrollheight="350px">
            <div class="ui-table ui-widget">

                <div class="ui-table-scrollable-wrapper ng-star-inserted">
                    
                    <div class="ui-table-scrollable-view">
                        <div class="ui-table-scrollable-header ui-widget-header">
                            <div class="ui-table-scrollable-header-box" style="margin-right: 0px;">
                                <table class="ui-table-scrollable-header-table">
                                    
                                    <thead class="ui-table-thead">
                                        
                                        <tr _ngcontent-c28="" class="ng-star-inserted">
                                            <th _ngcontent-c28=""></th>
                                            <th _ngcontent-c28="">Site</th>
                                            <th _ngcontent-c28="">Address</th>
                                        </tr>
                                    </thead>
                                    <tbody class="ui-table-tbody">
                                        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="ui-table-scrollable-body" style="max-height: 350px;">
                            <table class="ui-table-scrollable-body-table">
                                
                                <tbody class="ui-table-tbody">

                                    <tr _ngcontent-c28="" class="ng-star-inserted">
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> 1 </td>
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> City Of Ashland 20Yd Recy </td>
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> 201 Bass St, Ashland, MO 65010
                                        </td>
                                    </tr>
                                    <tr _ngcontent-c28="" class="ng-star-inserted">
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> 2 </td>
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> City Of Linn Tank/recy 3O Ot
                                        </td>
                                        <td _ngcontent-c28="" preorderablerowhandle=""
                                            class="ui-table-reorderablerow-handle"> City Hall, Linn, MO 65051 </td>
                                    </tr>

                                </tbody>
                            </table>
                            
                        </div>
                        
                    </div>
                </div>

            </div>
        </p-table>
    </div>
</div>

<div class="ui-dialog-footer ui-widget-content ng-tns-c23-216 ng-star-inserted" style="">
    <p-footer _ngcontent-c28=""><button _ngcontent-c28="" disabled="">
            OK </button>
       <button _ngcontent-c28=""> Close </button></p-footer>
</div>

<img width="370" alt="Capture" src="https://user-images.githubusercontent.com/24777812/70002509-789cd380-151d-11ea-875c-b9fdd4926285.PNG">

**Comment by SachinGowlikar** [comment]
Drag and drop is not working with protractor and typescript


<div class="panel panel-default">
				  <div class="panel-heading">Drag and Drop</div>
					<div class="panel-body">
						<div id="todrag" class="w25 moveleft">
						<h3 class="text-left">Items to Drag</h3>
							<span draggable="true" style="background: white;">Draggable 1</span>
							<span draggable="true">Draggable 2</span>
							<span draggable="true">Draggable 3</span>
							<span draggable="true">Draggable 4</span>
						</div>
						<div class="w50 moveleft">
							<h2 class="text-center">Drop here</h2>
							<div id="mydropzone" dropzone="move" style="background: white;">
							</div>
						</div>
						<div class="w25 fright"><h3 class="text-center">Dropped Items List</h3>
							<div id="droppedlist">
							</div>
						</div>
					</div>
				</div>


await browser.actions().dragAndDrop(element(by.xpath("//span[text()='Draggable 1']")), element(by.xpath("//div[@id='mydropzone']"))).mouseUp().perform();

Below is the screen shot from UI:

![image](https://user-images.githubusercontent.com/27900097/70032808-34b8d580-15d4-11ea-8f69-eeaf35af475f.png)
![dragNdropUI](https://user-images.githubusercontent.com/27900097/70032925-73e72680-15d4-11ea-90ee-98094747b7ba.png)

**Comment by SachinGowlikar** [comment]
Drag and drop is not woking with protractor and typescript.

<div class="panel panel-default">
				  <div class="panel-heading">Drag and Drop</div>
					<div class="panel-body">
						<div id="todrag" class="w25 moveleft">
						<h3 class="text-left">Items to Drag</h3>
							<span draggable="true" style="background: white;">Draggable 1</span>
							<span draggable="true">Draggable 2</span>
							<span draggable="true">Draggable 3</span>
							<span draggable="true">Draggable 4</span>
						</div>
						<div class="w50 moveleft">
							<h2 class="text-center">Drop here</h2>
							<div id="mydropzone" dropzone="move" style="background: white;">
							</div>
						</div>
						<div class="w25 fright"><h3 class="text-center">Dropped Items List</h3>
							<div id="droppedlist">
							</div>
						</div>
					</div>
				</div>

Below is the drop down UI :

![image](https://user-images.githubusercontent.com/27900097/70033080-bd377600-15d4-11ea-9930-871983511b56.png)
