### ISSUE TITLE
Data is re-entered in the target field if sendKeys() is used immediately for a different field after using .clear() on the target field

### ISSUE THREAD

**Issue by praveendvd** [angular/protractor#5370]
Bug report
---

- Node Version: `v10.16.3`
- Protractor Version: `Version 5.4.2`
- Angular Version: `7`
- Browser(s): `Chrome`
- Operating System and Version `windows 10 pro `
- Your protractor configuration file
- A relevant example test:

A program that has two text field , i.e name and description
**usecase:** 

**When** user enters "hi" in name field **Then** name field gets the value "hi"
**When** user clears data in name field **Then** name field get cleared
**Then** user enters "Hello" in description field **Then** description field gets value "Hello" **And** name field remains empty
**Then** user enters new value 'W' in Name field **Then** name field gets value 'W'   [**Failing**, name field gets value hiW]

**Code:**
 ```
               await element(by.id("package-name")).sendKeys("hi");
                await element(by.id("package-name")).clear();
                await element(by.id("package-description")).sendKeys("Hello");
                await element(by.id("package-name")).sendKeys("W");
                await browser.sleep(5000);
```

**Expected Behavior:**

Name field should get only "W" , should not have previous input cached

**Comment by SinghRajKr** [comment]
@praveendvd 
If you think it's an issue with cached then use below statements
`browser.executeScript('window.localStorage.clear();');
 browser.executeScript('window.sessionStorage.clear();');
 browser.driver.manage().deleteAllCookies();`

Or if you are running in headless mode:
Add chromeOptions:
`'chromeOptions': {
      'args': ['incognito']
  }`

**Comment by praveendvd** [comment]
@SinghRajKr  Thanks Raj , this behavior was happening only for our product i am not sure why , will try this if the issue comes up again . THanks again for the help :)
