### ISSUE TITLE
Unnecessary count property in capabilities causes failure when sending request to AWS Device Farm

### ISSUE THREAD

**Issue by gokhanoner** [angular/protractor#5383]
```
[07:47:10] E/launcher - Create Session request doesn't have capabilities defined. Request was {"desiredCapabilities":{"browserName":"chrome","count":1}}.
```

`count` property is not part of Selenium or  [webdriver capabilites](https://w3c.github.io/webdriver/#capabilities) config objects & causes issue here. Is it possible to remove it in the request or is there a way to not populate it?

**Comment by gokhanoner** [comment]
apparently, even when removing `count`, same error occurs so probably related to AWS setup. closing the issue.

**Comment by aleenadavy90** [comment]
Hi @gokhanoner running into similar issue, did you find a way around it?

**Comment by gokhanoner** [comment]
@aleenadavy90 yes, issue was AWS Device Farm expect you to send `capabilities`, not `desiredCapabilities` defined, which is part of the W3C Standard. However, this standard is only supported in Selenium 4 + Protractor 6. So you need to use Protractor 6 to use AWS Device Farms, it has nothing to do with count property. As the error message saying: `Create Session request doesn't have capabilities defined`

**Comment by aleenadavy90** [comment]
thanks @gokhanoner! Protractor 6 breaks a lot of my tests, found a workaround here https://stackoverflow.com/questions/58457533/protractor-w3c-capability to keep using protractor 5x.

**Comment by gokhanoner** [comment]
Thanks @aleenadavy90 , for sharing the workaround. I'll give it a try as well.
