### ISSUE TITLE
protractor.Button.RIGHT simulates a left click every time

### ISSUE THREAD

**Issue by Fuun347** [angular/protractor#5391]
Currently in protractor version 5.4.2 there seems to be no way to simulate a mouse right click. The old version pre chromedriver 74 was to use browser.actions().click(elem, protractor.Button.RIGHT), but that always simulates a left click. No other method I attempted was able to reproduce a right.

Bug report
- Node Version: `12.13.0`
- Protractor Version: `5.4.2`
- Angular Version: ``
- Browser(s): `chrome, version 79`
- Operating System and Version `win 10`

**Comment by Harsha509** [comment]
Hi @Fuun347 ,

can you please include an SSCCE (Short, Self Contained, Correct [compilable] example) http://sscce.org/
This will help to understand/debug the issue

**Comment by Fuun347** [comment]
let elem = element(by.css('button'));
await browser.actions().click(elem, protractor.Button.RIGHT);

This should perform a right click on the element "elem", but it performs a left click. This is an issue with the new actions API used in version ^75 of chromedriver.

**Comment by adinapitul** [comment]
@Fuun347  , try it like this:

await browser.actions().click(elem, protractor.Button.RIGHT).perform();

**Comment by Fuun347** [comment]
@adinapitul yea, excuse me there, forgot to type out the perform() function at the end

**Comment by adinapitul** [comment]
@Fuun347  , I use it like this, and it works fine (Chrome 80, MacOS) 

await browser.actions().mouseMove(elem).perform();
await browser.actions().click(protractor.Button.RIGHT).perform();

I just tried it now with browser.actions().click(elem, protractor.Button.RIGHT).perform(), and indeed it's misbehaving. In my app it does a right click + a left click :)

**Comment by Fuun347** [comment]
I'm pretty sure when experimenting I did indeed try your solution and it did not work. I will try again with your method and confirm if it works for me.

**Comment by Fuun347** [comment]
@adinapitul I tried again and it does not work me. It always seems to only use a left click.

**Comment by praveendvd** [comment]
#5271 

use

capabilities: {
  'browserName': 'chrome' ,
  'chromeOptions': {
w3c: false
},// or 'safari'
},

**Comment by lyubomiraleksiev-abertay** [comment]
@praveendvd yes, that did fix the issue for me. Thank you!

**Comment by Fuun347** [comment]
@praveendvd That completely fixed it! Thank you so much!
