### ISSUE TITLE
Protractor adds a huge delay after downloading a file while test is running

### ISSUE THREAD

**Issue by testautomationengr** [angular/protractor#5496]
- Node Version: `12.19.2`
- Protractor Version: `7.0.0`
- Angular Version: `9.1.13`
- Browser(s): `Chrome 89`
- Operating System and Version `Windows10`

File Download happens without any issue. But after clicking the download button, Protractor seems to be adding a delay till the file gets downloaded. As the script wont perform any other action during the download process. Only after download is completed, it can do any other action. In my test case, i have to perform other actions while download is happening in background.

**Comment by testautomationengr** [comment]
Already tried that option but there is no difference

**Comment by StanislavKharchenko** [comment]
@testautomationengr You need to check manually if actually any actions could be done during downloading.
Another choice - try to call any other element on page (e.g. is it enabled).
E.g.

```
await browser.waitForAngularEnabled(false);
await someDownloadingFunc();
await checkIfSomeAnotherElementPresent(); //how this action will be performed, with delay or not?
```

**Comment by testautomationengr** [comment]
Manually it works fine. I tried the exact same steps u mentioned, but script just freezes and only after download is done, it does any other step.

**Comment by testautomationengr** [comment]
disabling angular wait actually works. closing issue.
