### ISSUE TITLE
Protractor will not switchTo().window(handle). nameOrHandle Undefined error.

### ISSUE THREAD

**Issue by rlrhett** [angular/protractor#55]
Question cross-posted on SO. http://stackoverflow.com/q/18394261/1226721

I have gone around this as many ways as I can think, and still can't get this to work. I am trying to switch to a popUp as a way to automate a login. Protractor goes to my main page, clicks the login button and waits for the loggin popup.

The setup:

``` javascript
var ptor;
beforeEach(function() {
  var handlesDone = false;
  ptor = protractor.getInstance();
  ptor.get('#/');
  runs(function() {
    return ptor.findElement(protractor.By.className('btn')).click();
  });
  waits(3000);
  runs(function() {
    return ptor.getAllWindowHandles().then(function(handles) {
      popUpHandle = handles[1];
      parentHandle = handles[0];
      return handlesDone = true;
    });
  });
  waitsFor(function() {
    return handlesDone;
   });
 });
```

So far so good, next I want to make sure that I have, in fact, a window handle for my pop-up:

``` javascript
describe('login', function() {
  it('should switch to popUp\'s handle', function() {
    expect(popUpHandle).toBeDefined();
```

finally, I try to switch to this window:

``` javascript
  ptor.switchTo().window(popUpHandle).getWindowHandle().then(function(handle) {
    expect(handle).toEqual(popUpHandle);
    });
  });
});
```

Yet no matter what I have tried, I keep getting the following error:

---

login
    should switch to popUp's handle

Failures:

  1) login should switch to popUp's handle
   Message:
     ReferenceError: nameOrHandle is not defined
   Stacktrace:
     ReferenceError: nameOrHandle is not defined
    at webdriver.WebDriver.TargetLocator.window (.../node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:1385:32)
    at null.<anonymous> (.../test/e2e/e2e-spec.js:40:21)
    at ...node_modules/protractor/jasminewd/index.js:54:12
    at webdriver.promise.ControlFlow.runInNewFrame_ (.../node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1438:20)
    at webdriver.promise.ControlFlow.runEventLoop_ (.../node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1303:8)
    at Timer.exports.setInterval.timer.ontimeout (timers.js:234:14)
==== async task ====

Finished in 5.388 seconds
1 test, 2 assertions, 1 failure

---

as you can see, I have 2 assertions:

1) that popUpHandle is defined

2) that the handle after the switchTo is the same as the popUpHandle

I have tested that I have 2 handles total. I have tested that they are both strings. I have tested that they are different from each other. In this example I test that popUpHandle is defined. All those test pass. Yet no mater what I do, when I try to plug a handle into the .switchTo().window() method I get the same "nameOrHandle is not defined".

I'm stumped. There is so little documentation on WebDriverjs I can't even be sure that switchTo is implemented. Does anyone know what is going on here?

Thanks.

**Comment by latobibor** [comment]
Hi everyone,
  I can still reproduce this with 3.0.0 and webdriver 2.53.0. Code:

```javascript

it('checks tabs', () => {
  const url1 = 'http://stackoverflow.com/';
  const url2 = 'http://programmers.stackexchange.com/';

  let windowHandles = {
    oldTab: '',
    newTab: ''
  };

  await browser.get(url1);
  await browser.getWindowHandle().then(handle => {
     windowHandles.oldTab = handle;
  });

  await browser.executeScript('window.open("' + url2 + '", "whatever")');

  await browser.getAllWindowHandles()
    .then(handles => {
      expect(handles[0]).toEqual(windowHandles.oldTab);

      windowHandles.newTab = handles[1];
      return browser.driver.switchTo().window(windowHandles.oldTab);
    })
    .then(() => {
      let handle = browser.driver.getWindowHandle();
      expect(handle).toEqual(windowHandles.oldTab);
    })
    .then(() => browser.sleep(6000));
});
```

If you are using stackoverflow, here's the link for the same question there: http://stackoverflow.com/questions/36578927/protractor-3-0-0-webdriver-2-53-0-switching-tabs-error

**Comment by sophiaatif** [comment]
Hello, I have the same issue. I am using : 
1. Selenium WebDriver dll. Version 2.53.0 Installed by Nuget
2. IEDriverServer.exe Version 2.53.0 64 bit version downloaded from Selenium Website

My code is same as @latobibor 's code, and it gets stuck on line 
`browser.driver.switchTo().window(windowHandles.oldTab);`

Is it a Selenium Bug, or is this the wrong syntax to Switch Window Handle?

when i debug the issue, i get the following exception after waiting a long time : 
`An exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll but was not handled in user code

Additional information: The HTTP request to the remote WebDriver server for URL http://127.0.0.1:4444/wd/hub/session/36fa4074-3b34-4dea-9da8-c8278b135c4f/window timed out after 240 seconds.`

**Comment by shane-reaume** [comment]
For a single pop-up I just do `browser.switchTo().frame(1);` and works like a champ.
