### ISSUE TITLE
browser.driver.manage().window().fullscreen(); is not working in protractor

### ISSUE THREAD

**Issue by aasimali** [angular/protractor#5500]
**browser.driver.manage().window().fullscreen();**

This method is not working in protractor, any alternate solution to full screen the browser?

**Note**: I'm not looking for browser.driver.manage().window().maximize(); (as I want to full screen my browser not maximize)

**Comment by StanislavKharchenko** [comment]
There is no method "fullscreen()" on Window object.
You need to call browser.driver.manage().window().maximize() if you want to have browser in full screen mode. (don't forget to use async/await with it).

**Comment by aasimali** [comment]
okay, but in selenium we are able to call **fullscreen();** method.

/* Java selenium code */
WebDriverManager.chromedriver().setup();
WebDriver driver = new ChromeDriver();
driver.manage().window().fullscreen();

**Don't we have any alternate solution in protractor to do the same?**

**Comment by StanislavKharchenko** [comment]
There is no such method for selenium 3.x on javascript binding.
You could pass option 'start-fullscreen' for your chrome driver and it should work:
```
  'goog:chromeOptions': {
         args: ['start-fullscreen']
   }
```

So, this is not question for protractor, but for Selenium implementation in JS.
Please, check with start-fullscreen and close the issue.

**Comment by aasimali** [comment]
Ok, Thank you!!
