### ISSUE TITLE
Keywords like describe, browser are not reflecting in vs code

### ISSUE THREAD

**Issue by austindarren** [angular/protractor#5512]
When I type browser inside it() test, bhxBrowser is auto suggested. On navigating to go to definition for describe it says "no definition found for describe". Any help would be much appreciated. Not sure why auto suggestions are not reflecting. 

![image](https://user-images.githubusercontent.com/49337520/116634856-94213d80-a9a0-11eb-8165-2b92b0f00815.png)

Bug report
---

- Node Version: `14.16.1`
- Protractor Version: `6.14.12`
- Operating System and Version `macOS Big Sur 11.3`

**Comment by andredesousa** [comment]
Do you have a project or isolated files?
You can see my project:
https://github.com/andredesousa/essential-angular-scaffold
Go to the e2e folder.

**Comment by austindarren** [comment]
thanks for your input. I just executed example_spec.js and conf.js available in the path /usr/local/lib/node_modules/protractor/example in vscode and it worked. 
![image](https://user-images.githubusercontent.com/49337520/116802210-82809700-ab54-11eb-9cf3-6daa3e8bef7f.png)
