### ISSUE TITLE
Can't find element after Login

### ISSUE THREAD

**Issue by offirpeer** [angular/protractor#5515]
This issue is very similar to this [issue](https://github.com/angular/protractor/issues/143) from 2013.

On login page everything works perfect, I can select the inputs, select the submit button and click the submit button, the url changes like I expect, but after the login I can't select elements anymore from some reason.

```
  it('should send check in desktop', async () => {

    loginPage.login(environment.e2e.user.phone, environment.e2e.user.password);

    await loginPage.verifySuccessfullLogin();
    console.log('After verifySuccessfullLogin');

    await browser.sleep(3000);
    console.log('After sleep');

    const sendBtn = $('#sendCheckBtnDesktop');
    console.log(sendBtn);
    // Nothing happens
    await sendBtn.click();

    // Not getting here
    await browser.sleep(10000);
  });
```

![Ask](https://user-images.githubusercontent.com/6349007/118813746-2047c600-b8b8-11eb-999e-1b55573d58be.PNG)

**Comment by StanislavKharchenko** [comment]
This is very frequent issue when app you test incorrectly handle angular zones.
There 2 ways to fix:
1. On app side, you need to run all async tasks outside angular zone. See details: https://www.protractortest.org/#/timeouts (Waiting for Angular)
2. Another choice - is to switch off "waitForAngularEnabled". If you do this - you need to handle and make explicit waits for all elements you want to interact.
