### ISSUE TITLE
Protractor Mouse Right click not working in Firefox Browser

### ISSUE THREAD

**Issue by A-Kavin** [angular/protractor#5529]
System:
Firefox Version: 90.0.2 (64-bit)
Protractor Version: 7.0.0
Typescript
Webdriver updated

Issue in Firefox Browser:
WebDriverError: HTTP method not allowed

Code:
await browser.actions().click(protractor.Button.RIGHT).perform();

**Comment by StanislavKharchenko** [comment]
This is because this action is non w3c.
Until Protractor won't become w3c compliant some browser/mouse actions will not work.
Perhaps @cnishina could maintain upgrade to w3c selenium soon?
