### ISSUE TITLE
need support for finding element under shadow root

### ISSUE THREAD

**Issue by ravi005e** [angular/protractor#5549]
protractor 7 has no support to find element under shadow root

Feature Request
---

- Reasons for adopting new feature
- Is this a breaking change? (How will this affect existing functionality)

**Comment by ravi005e** [comment]
found solution

**Comment by autTestUser** [comment]
> found solution

What is the solution?

**Comment by ravi005e** [comment]
Here is the link

 

protractor-react-selector - npm (npmjs.com) <https://www.npmjs.com/package/protractor-react-selector>
