### ISSUE TITLE
Support Sharding

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#569]
This has come up a couple times, so I wanted to consolidate discussion into one issue. 

Test sharding would mean automagically splitting up a suite of tests to run in parallel, with the goal of reducing test time. Implementation will be very dependent on the test runner, and so would probably happen for Jasmine first.

Currently, you can achieve this by splitting tests into multiple files and creating different configs for different specs.

**Comment by tonyeung** [comment]
is this still only for jasmine? I'm running mocha.
