### ISSUE TITLE
ptor.getCurrentUrl() is not working correct

### ISSUE THREAD

**Issue by apankov1** [angular/protractor#57]
Hello, 

I've just started looking at protractor for our angularjs apps and looks very promising. 

I want to use ptor.getCurrentUrl() to get url after login to make sure that I actually got logged in. My code looks something like this: 

```
var util = require('util');

describe('Sign In Page', function() {
    var ptor;

    beforeEach(function() {
        ptor = protractor.getInstance();
        ptor.get('#/login/');
        ptor.waitForAngular();
    });

    it ('Login', function(){
        ptor.findElement(protractor.By.css('input[name=email]')).sendKeys("***");
        ptor.findElement(protractor.By.css('input[name=password]')).sendKeys("***");
        ptor.waitForAngular();
        var currentUrl = ptor.getCurrentUrl();
        console.log(currentUrl);
    }, 20000);

    it('afterAll', function(){
    });
});
```

I'm using 

```
    var currentUrl = ptor.getCurrentUrl();
    console.log(currentUrl);
```

to see what exactly gets stored and in console I see following result:

```
APankov$ node_modules/.bin/protractor conf.js
Using the selenium server at http://localhost:4444/wd/hub
{ then: [Function: then],
  cancel: [Function: cancel],
  isPending: [Function: isPending] }
```

What am doing wrong in this case?

Thank you

**Comment by bitliner** [comment]
On ie11 browser.getCurrentUrl() does not return the current url, but the previous url.

The hack from @tot-ra works.

To be honest, all the APIs from protractor suck. 
The best way looks like to run always javascript code inside the browser.
So may problems I am getting with protractor...

**Comment by ctamas** [comment]
Its not a 'hack', you simply still don't understand the concepts of promises that have been linked above on this very page.

**Comment by bitliner** [comment]
@ctamas you don't understand the way protractor and js selenium api manages promises.
and `getCurrentUrl()` always worked, while in ie11 don't.

**Comment by bitliner** [comment]
@ctamas the point is that it is not clear when to resolve promises with then and when not, and selenium api communicates like there is no need to resolve promises with then, while there is this need as we are demonstrating in this thread.

**Comment by ctamas** [comment]
Without proper use of then keywords its a matter of luck that it works in the other browsers in the first place, you have to prepare for the worst case if you are testing on multiple browsers.

**Comment by bitliner** [comment]
I think the confusion comes from this sentence `The promise manager maintains a queue of scheduled tasks, executing each once the one before it in the queue is finished.`
and from the fact that someone - not only me apparently - expects a different behavior from `getCurrentUrl()`

**Comment by anwani** [comment]
i am using the statement browser.get(URL); but the url is not launched, rather just the browser window is opened by the previous statement browser.manage().window().setSize(1600, 1000);
        which was defined in onprepare method on conf.js file
