### ISSUE TITLE
isEnabled() assertion returns incorrect value for disabled <label> element

### ISSUE THREAD

**Issue by mcalthrop** [angular/protractor#577]
I just discovered what I am pretty sure is a bug.

The markup I am using looks like this:
``` html
<label id='blah-label-id' disabled="disabled" data-ng-click="handleClick()">
<input type="radio">blah</label>
```

The Protractor assertion I am using looks like this:
```javascript
expect(element(by.id('blah-label-id')).isEnabled()).toBe(false);
```

However, the above assertion fails.

When I test it to see the result of `isEnabled()`, it returns `true`, when you'd expect it to return `false`.

I have tested this by calling `getAttribute('disabled')` on the same element – it returns `'true'` (as a string, not a boolean value).

Note that in the same suite of tests, I am successfully using the `isEnabled()` assertion on `<input type="range">`, `<input type="text">` and `<button>` elements.

**Comment by adam-back** [comment]
In my case, I have a variable set on the scope which is used with `ng-disabled` to set the `disabled` attribute.

I'm running Chrome Version 39.0.2171.99 (64-bit) and OS X10.10.

![screen shot 2015-01-20 at 3 53 28 pm](https://cloud.githubusercontent.com/assets/8163408/5828731/99207b0a-a0bc-11e4-942f-ca7a74c0e78e.png)

This test passes:
![screen shot 2015-01-20 at 3 55 59 pm](https://cloud.githubusercontent.com/assets/8163408/5828744/dc3542d6-a0bc-11e4-83ae-4ee41bac925c.png)

**A workaround may be to use `ng-disabled`.**

**Comment by juliemr** [comment]
I think, as mentioned above, this is webdriver working as intended.

**Comment by bmsoko** [comment]
Thanks @adam-back ! your reply saved my a lot of time!! thanks!!

**Comment by adam-back** [comment]
No problem! Glad to help.

**Comment by dmitroboltenko** [comment]
This trouble sounds strange. Looks like it happened because attribute disabled has string value instead of boolean, and WebDriver expect boolean. Correct me if I'm wrong.
       According to HTML 5 standards this attribute should be boolean 
http://www.w3.org/TR/html5/forms.html#concept-fe-disabled. 
Does Angula make this attribute string?
Another question why Chrome displays this element correct as disabled?
My guess if it works in another browsers the same way it works in Chrome. Probably WebDriver should update their behavior.

**Comment by awerlang** [comment]
@dmitroboltenko you're refering to an attribute shared by form *controls* (under 4.10.19 Attributes common to form controls). `label` isn't a form control though.

also, see my answer above.

**Comment by ItsSarronya** [comment]
When the button is disabled, the below is the web structure,
<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button" disabled="">
            <i _ngcontent-pyf-127="" class="save"></i> Save </button>
Similary when the button is enabled, the below is the web structure,
<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="save"></i> Save and Close</button>
if this is the case, when i do a getattribute of disabled, a null is returned. 
How to I verify in protractor if the button is disabled or enabled for a certain condition ?

**Comment by ItsSarronya** [comment]
When the button is disabled, the below is the web structure,
Save Button Disabled- "<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="save"></i> Save and Close</button>"
Similary when the button is enabled, the below is the web structure,
 
Save Button Enabled - "<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="save"></i> Save and Close</button>"
 if this is the case, when i do a getattribute of disabled, a null is returned.
 How do I verify in protractor if the button is disabled or enabled for a certain condition ?

**Comment by ItsSarronya** [comment]
<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="save"></i> Save and Close</button>

**Comment by ItsSarronya** [comment]
<button _ngcontent-pyf-127="" class="btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class=-save"></i> Save and Close</button>

**Comment by ItsSarronya** [comment]
<button _ngcontent-pyf-127="" class="btn btn-sm btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="glyphicon glyphicon-save"></i> Save and Close</button>

**Comment by ItsSarronya** [comment]
<button _ngcontent-pyf-127="" class="btn btn-sm btn-primary" id="Save" type="button">
            <i _ngcontent-pyf-127="" class="glyphicon glyphicon-save"></i> Save and Close</button>
