### ISSUE TITLE
Loading Config asynchronously

### ISSUE THREAD

**Issue by axemclion** [angular/protractor#578]
Currently the configuration needs to be specified as an object in module.exports. This means that everything, include the browser capabilities need to be synchronous. 

However, packages like [firefox-profile](https://github.com/saadtazi/firefox-profile-js) are easier to use with their async API. Generating the zip and crx file for chrome extensions also work well with an async API.

What would be the best way to use the config where the capabilities object is generated asynchronously? Is [this](https://github.com/angular/protractor/blob/master/docs/library-only.md) the best way of using protractor? 

P.S: I am working on [browser-perf](http://github.com/axemclion/browser-perf) and am looking at reusing protractor tests to test performance of Angular web apps. I am also generating the browser capabilities object asynchronously, hence this question.

**Comment by donaldpipowitch** [comment]
What is the best way to do it now? I'd love to have some async code in my configuration (or have https://github.com/angular/protractor/issues/2334).
