### ISSUE TITLE
stepNumber, specFileName, screenshots and stepStatus

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#587]
I'm currently using [protractor-screenshot-reporter](https://github.com/swissmanu/protractor-screenshot-reporter) and manually keep track of stepNumber and specFileName.

Leave you a screenshot of an example test run where i can easily see where a step failed and which ones passed, in what order and so on.

Perhaps useful to think about some new ideas and or absorb protractor-screenshot-reporter into protractor.

![specfilename_screenshots_stepnumbes_stepstatus](https://f.cloud.github.com/assets/111569/2347726/d0440430-a54f-11e3-965d-5b424ea283a5.png)

**Comment by juliemr** [comment]
I'm closing up old issues - there are great ideas here, but because they're specific to a framework I think they are better implemented in separate libraries like the one @elgalu linked. Thanks!
