### ISSUE TITLE
"Error while waiting for Protractor to sync with the page" when navigating with window.location.href

### ISSUE THREAD

**Issue by sJhonny** [angular/protractor#598]
All my tests are working well on chrome, but on firefox I (sometimes) get the following error:

Error while waiting for Protractor to sync with the page: {"message":"angular.element(...).injector(...) is undefined","stackTrace":[{"fileName":"http://localhost/app/main#/home","lineNumber":72,"methodName":"anonymous/<"},{"fileName":"http://localhost/app/main#/home","lineNumber":77,"methodName":"anonymous"},{"fileName":"http://localhost/app/main#/home","lineNumber":68,"methodName":"handleEvaluateEvent"}]}

after which, every consequent test run fails with the same message; I have to re-start the webdriver-manager in order to get things to work again.

All my tests begin with a login action (fill in username and password, click 'login' and be redirected to the home page).
That error occurs when redirecting to the homepage- after the login button was clicked, but before the home page has a chance to load.

after this error occurs I have to forcefully end all nodeJS processes to get things going again.

I'm running the latest protractor and webdriver-manager (0.20.1), latest firefox (27.0.1) on win8.
This also happened with protractor 0.19.1 and firefox 26.

I'm not sure what's the source of the issue is, so I don't know what code I can post here..
Can anyone point at any possible cause for this? 

EDIT:
Forgot to mention I'm using angular 1.2.9

Also I've found that this error message repeats on every test run, except for the very first run.
However, If I shutdown all NodeJS processes (shown in windows task manager as 'evented I/O for v8 javascript) EXCEPT for one (the main-loop thread of the webdriver-manager, I assume, since webdriver-manager stays alive) after every run, then this problem does not appear.
This may suggest some issue with improper cleanup after tests have run...

I've also found that after getting this error with FF, the problem may appear with chrome on subsequent runs, unless I completely shut down the webdriver-manager.
This also may indicate that something is lingering with the selenium server after the firefox tests finish.
(of course- it may not; I've really no clue here :))

**Comment by w-green** [comment]
I had the same issue when using the $location service with multiple instances of Firefox.
The mentioned fix, of using webdriver, worked well.

**Comment by makwanaparth94** [comment]
I am also getting the same error
**ERROR : Error while waiting for Protractor to sync with the page: "Unable to get property '$$testability' of undefined or null reference"**

conf.js
exports.config = {
  framework: 'jasmine2',
  seleniumAddress:'http://localhost:4444/wd/hub',
  capabilities: {
      'browserName': 'internet explorer',
     'ignoreProtectedModeSettings': true,
     'count' : 3,
      },


    specs: ['maintest.js'],
    allScriptsTimeout: 100000,
    getPageTimeout : 100000,

    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 1000000,
        isVerbose: true,
    },
};

maintest.js:

describe('Atos Factory Maintenance web app', function() {
	
var homePage = require('C:/Users/A622864/WebstormProjects/sample/homePage.js');
var loginPage = require('C:/Users/A622864/WebstormProjects/sample/loginPage.js');
var assingJob = require('C:/Users/A622864/WebstormProjects/sample/assingJob.js');
var assignjobTask = require('C:/Users/A622864/WebstormProjects/sample/assignjobTask.js');

it('Verify the HomePage', function(){
	
	 homePage.loadURL();
	 expect(browser.getTitle()).toEqual('Factory Maintenance');
	 console.log('HomePage test case is passed..!!');	
});


it('Verify the LoginPage',function(){
	 
	 loginPage.UserName();
	 loginPage.Password();
	 loginPage.clickLogin();
	 console.log('Login is successful..!!');	 
});


it('Verify the title assign job task to technicain', function(){
	  
	assingJob.Clickassinjob();
	console.log(' Assign job task link is worked successfully');
	
});


it('Verify the Job task', function(){
	 
	assignjobTask.SelectLoc();
	assignjobTask.EntertaskDescription();
	assignjobTask.SelectUserJob();
	assignjobTask.ClickSubmit();
	console.log('....');
});

});
 
![image](https://cloud.githubusercontent.com/assets/28529639/26141213/51f2ed48-3af8-11e7-9025-10a665289720.png)
