### ISSUE TITLE
Junit Reporter

### ISSUE THREAD

**Issue by rodikal** [angular/protractor#60]
We want to run protractor tests on Jenkins, so it would be very useful if there was a junit reporter (like karma has) so the status of the tests can be reported by Jenkins

**Comment by luixaviles** [comment]
@jonniespratley  I found that `npm install jasmine-reporters` installs `1.0.1` version by default.
So, make sure you have installed latest version of `jasmine-reporters`. For example

```
npm install jasmine-reporters@~2.0.3 --save-dev
```
After that, I updated protractor configuration as follows:

```
var jasmineReporters = require('jasmine-reporters');
exports.config = {
    framework: 'jasmine2',
    //...  
    //Other configurations...
    //...  
    onPrepare: function () {
        jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
            savePath: '..',
            consolidateAll: false
        }));
    },
    jasmineNodeOpts: {
        showColors: true,
        defaultTimeoutInterval: 60000,
        print: function() {}
    }
};
```
Now jasmine-reporters is working fine to me.

**Comment by mscharp** [comment]
In protractors' documentation for upgrading to jasmine2 framework, in the reporters section it would be nice if @luixaviles answer were documented.  I can't imagine I'm the only one that had a difficult time figuring out how to get junit reports for jasmine2.  Granted, once I found this and reread the current documentation it is clearer, but originally I mistakenly read it to mean jasmine-reporters didn't work (at all) with jasmine2.  Having the above answer, or a link to jasmine-reporters' readme would make things a bit easier.

**Comment by spatchamatla** [comment]
tried the jasmine reports 
var jasmineReporters = require('jasmine-reporters');
 jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter('../TestReports/test', true, true));

it ran good, but no xml file is been created

**Comment by bloveridge** [comment]
@spatchamatla Your example is using a weird combination of jasmine-reporters@1.x syntax (ordered arguments) with what looks like the jasmine-reporters@2.x reporter (jasmineReporters.JUnitXmlReporter vs jasmine.JUnitXmlReporter).

Try using the correct syntax to create the reporter and see if you get further.

Modified from the example in the jasmine-reporters README:

    var junitReporter = new jasmineReporters.JUnitXmlReporter({
        savePath: '../TestReports/test'
    });
    jasmine.getEnv().addReporter(junitReporter);

**Comment by spenoir** [comment]
Make sure that the folder '../TestReports/test' exists as I think it fails
silently too.

**Comment by bloveridge** [comment]
Never a bad idea, though jasmine-reporters will use https://github.com/substack/node-mkdirp to try and create the directory.

**Comment by spatchamatla** [comment]
@bloveridge @spenoir , i downgraded to jasmine-reporters@1.x and used the below 
```
   //For junit output reports
        var reporters = require('jasmine-reporters');
        var capsPromise = browser.getCapabilities();
        capsPromise.then(function (caps) {
            var browserName = caps.caps_.browserName.toUpperCase();
            var browserVersion = caps.caps_.version;
            var prePendStr = browserName + "-" + browserVersion + "-";
            jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('Protractor/TestReports', true, true, prePendStr));
        });
```

it started working, the only down side is its creating the folder in home directory rather than in project folder. When i tried using the project folder path, it still says
  
Rhino attempt: java is not defined
PhantomJs attempt: window is not defined
NodeJS attempt: Arguments to path.resolve must be strings

i created the folder manually and still shows the above in the console

**Comment by spenoir** [comment]
is 'Protractor/TestReports' the correct path and does that folder exist?

**Comment by spatchamatla** [comment]
'Protractor/TestReports' is the path that been created in the home folder, then i used
```
jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('../TestReports', true, true, prePendStr));
```
and i manually created

![screen shot 2015-04-15 at 12 07 09 pm](https://cloud.githubusercontent.com/assets/4671240/7163457/278cffa6-e368-11e4-9994-2c0b5d33f07c.png)

when i ran the test, it still gives
Warning: writing junit report failed for '../TestReports', 'CHROME-41.0.2272.118-TestImpersonationPage.xml'. Reasons:
  Rhino attempt: java is not defined
  PhantomJs attempt: window is not defined
  NodeJS attempt: EACCES, permission denied '/Users/TestReports'

**Comment by spenoir** [comment]
you could try relaxing the permissions on the TestReports folder, Not sure
after that.

**Comment by spatchamatla** [comment]
Sure,Thanks @spenoir for your suggestions and input

**Comment by guy-mograbi-at-gigaspaces** [comment]
Hi guys, I just ran into this thread, and followed it. 

I downgraded the reporters version - which seems to help. 

However, I am not getting anything right now.. 
In the output, everything seems to work just fine, but I don't see any file at the end. 

I eventually added 2 prints inside the reporter to make sure it is invoked properly and that seems to be the case. 
This is my output. 

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Session created: platform=ANY, count=1, browserName=phantomjs, version=
reporter created!
.report spec results invoked


Finished in 0.019 seconds
1 test, 1 assertion, 0 failures

Session deleted: Going to shut down the Selenium server
Shutting down Selenium server: http://127.0.0.1:4444
Shut down Selenium server: http://127.0.0.1:4444 (OKOK)
[launcher] 0 instance(s) of WebDriver still running
[launcher] phantomjs #1 passed
```

This is my configuration 

```
 onPrepare:function( ){
        //For junit output reports
        var reporters = require('jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('test_result', true, true, 'demo'));
    },
```

what am I doing wrong?

I tried the mocha version setup and successfully got a report

**Comment by Guardiannw** [comment]
@jkmurthy @ksraja It seems that the jasmineReports listed is actually the export of the require function.

e.g., 
`
var jasmineReporters = require('jasmine-reporters');
`

**Comment by josephdpurcell** [comment]
The example on the jasmine-reporters readme works for me: https://github.com/larrymyers/jasmine-reporters#protractor

If you only need console output, I was pleased with https://github.com/bcaudan/jasmine-spec-reporter/blob/master/docs/protractor-configuration.md

**Comment by javierquevedo** [comment]
@josephdpurcell the link you provided also worked for me. Here is my config, how it helps!

```javascript
   var folderName = ('build/coverage/e2e');
        var mkdirp = require('mkdirp');
        mkdirp(folderName, function(err) {
              if (err) {
                console.error(err);
              } else {
                 var jasmineReporters = require('jasmine-reporters');
                  jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
                    consolidateAll: true,
                    savePath: folderName,
                    filePrefix: 'xmloutput-'
                  }));
              }
            });
```
