### ISSUE TITLE
Proper Way of Selecting an Option from a Dropdown List

### ISSUE THREAD

**Issue by demisx** [angular/protractor#600]
Hi. What's the current best way of doing this in protractor tests:

``` js
select('orderProp').option('Alphabetical')
```

for 

``` html
<select ng-model="orderProp">
   <option value="name">Alphabetical</option>
   <option value="age">Newest</option>
 </select>
```

This was taken from the tutorial on http://docs.angularjs.org/tutorial/step_04 (last test at the end of the page). I am trying to convert e2e tests to protractor as an exercise and can't figure out a clean way to select an option from a drop down list. Some examples found on the web seemed too verbose and, perhaps, outdated. Thank you.

**Comment by SeleniumShooters** [comment]
Hi there, the solution you have suggested above is not working for me and my dropdown element is not having model attribute. it has id locator and under that i have some options.

**Comment by aldorianmode** [comment]
Hi, 

I tried the way @demisx proposed, but wasn't working fine completely. I modified what he recommends  dividing it in two steps as:

element(by.model('orderProp')).click();
$('[value="age"]').click();

Im not shure if the first step is necessary...
Try this @SeleniumShooters, this is working for me 10/10.

**Comment by adnanghaffar07** [comment]
I read this solution from somewhere and it perfect that selecting by option number, and therefore wrote a method that takes an element and the optionNumber, and selects that optionNumber. If the optionNumber is null it selects nothing (leaving the dropdown unselected).

```
var selectDropdownbyNum = function ( element, optionNum ) {
  if (optionNum){
    var options = element.findElements(by.tagName('option'))   
      .then(function(options){
        options[optionNum].click();
      });
  }
};
```

**Comment by krishnaGottipati** [comment]
Hi,
My scenario: I wanted to search address and need to click the search suggestions.
I have a html like below:
---------------
<div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;">
<div class="tt-dataset tt-dataset-4"></div>
<div class="tt-dataset tt-dataset-5">
<div class="search-result-sub-heading">Address Results</div>

<div class="tt-suggestion tt-selectable">
<strong class="tt-highlight">Hyde</strong>
, Cheshire England United Kingdom
</div>

<div class="tt-suggestion tt-selectable">
<strong class="tt-highlight">Hyde</strong>
St, Spotswood VIC 3015
</div>

<div class="tt-suggestion tt-selectable">
<strong class="tt-highlight">Hyde</strong>
's Quality Drycleaners, 28 Hamilton St 3437
</div>
</div>
</div>
----------------
Below is my protractor spec:
element.all(by.css('.tt-suggestion.tt-selectable')).first().click();

I can able to select and click the search suggestions on chrome, InternetExplorer, MicrosoftEdge.
But in firefox, click() is not happening.

Could you please anyone help me.

**Comment by vishwabharatraju** [comment]
guys use this command 

select obj=new select(driver.findElement(by.xpath("//select[@class='gwt-ListBox']")));
obj.selectbyvisibleText(" ");
guys as per your  convenience  use locators and depends on situation use selectbyvalue or selectbyindex

**Comment by dhanrajpru** [comment]
It is really working thanku  @demisx 
// JavaScript
element(by.model('orderProp')).$('[value="age"]').click();

**Comment by 123-anju** [comment]
Can anyone tell me that for jasemine language in protractor, this will be the code of selecting one option out of dropdown list.
element.findElements(by.tagName('option')) ,will this be used inplace of "....element.all()..."????
var selectDropdownbyNum = function(element, optionNum) {
		if (optionNum) {
			var options = element.all(by.tagName('option'))
				.then(function(options) {
					options[optionNum].click();
				});

**Comment by Asargiotakis** [comment]
@123-anju it didn't worked for me. i used element.all(...)...

**Comment by thirupathi-d** [comment]
> YES! this is absolutely what I meant! Sorry for the confusion.
> 
> ```js
> var select = element(by.model('orderProp'));
> select.$('[value="age"]').click();
> ```

This is perfect!!
works for me /:

**Comment by softskul** [comment]
Hi I want to display all the value coming in Dropdown using Typescript protractor can anyone tell me how to do it
