### ISSUE TITLE
SauceLabs with corporate proxy

### ISSUE THREAD

**Issue by smtripathi99** [angular/protractor#604]
Hi,

I am trying to run a test using SauceLabs but it just hangs with no error. I am behind a corporate proxy and i my config is as follows:

// An example configuration file.
exports.config = {
  // Do not start a Selenium Standalone sever - only run this using chrome.
  //chromeOnly: true,
 // chromeDriver: '../selenium/chromedriver',
seleniumAddress: 'http://127.0.0.1:4444/wd/hub',

sauceUser:'==',
sauceKey:'==',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Spec patterns are relative to the current working directly when
  // protractor is called.
  specs: ['../spece2e/*Test.js'],

  onPrepare: function() {
        require('../jasmine-reporters');
        jasmine.getEnv().addReporter(new jasmine.JUnitXmlReporter('outputdir/', true, true));
    },

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  }

};

**Comment by michalsi** [comment]
@smtripathi99 you might consider to removing your SL credentials from this thread.

**Comment by wswebcreation** [comment]
@michalsi ,

Good catch, removed it from the initial question
