### ISSUE TITLE
multiCapabilities ignores spec

### ISSUE THREAD

**Issue by mcalthrop** [angular/protractor#605]
Hi

I'd like to be able to use the `multiCapabilities` feature like this:

``` javascript
multiCapabilities: [
    {
        browserName: 'chrome',
        specs: ['path/to/test-1-suite.js']
    },
    {
        browserName: 'chrome',
        specs: ['path/to/test-2-suite.js']
    }
],
```

However, Protractor ignores the `specs` object in both cases, and bails out with an error that it couldn't find the specs.

Would this be simple to implement?

many thanks

Matt

**Comment by pradeep-kumar-JP** [comment]
@YukonSaint
@hankduan
I am trying parallel execution for angular application using protractor-cucumber-framework , i have tried with 2 types of capabilities but i am getting only last executed feature file json report , below are the 2 types of capabilities i have used.
1)
capabilities: {
    browserName: 'chrome',
    shardTestFiles: 'true',
    maxInstances: 3,	
  },     
2)
 multiCapabilities: [
        {
            shardTestFiles: true,            
            browserName:'chrome',          
        },
        {
            shardTestFiles: true,            
            browserName: 'internet explorer',
			}
    ],

my cucumber opts look like this:

cucumberOpts: {
        require:[ 'Generic_Protractor/StepDefinitions/**/*.js', 'Generic_Protractor/Support/**/*.js' ],
        format: [ 'json:Generic_Protractor/Report/cucumber_report.json', 'pretty' ],
        plugin : "pretty",
        keepAlive: false
        
    }

Please help me out to get complete json report.

Thanks in advance
