### ISSUE TITLE
How to run cucumber test by the example https://github.com/angular/protractor/tree/master/spec/cucumber

### ISSUE THREAD

**Issue by emyphan** [angular/protractor#618]
Hi Julie,
i'm new to protractor and cucumber. I've set up my new cucumber test like yours in : https://github.com/angular/protractor/tree/master/spec/cucumber

but i don't find any document for how to run the feature file (and then call the protractor test step). I know there is already adapter for cucumber in protractor runner. But how can i/ do i have to set up any thing more, so that cucumber knows about protractor? And how can i run cucumber tests?

thanks a lot in advance for a quick answer
BR, Emy

**Comment by bmsoko** [comment]
Hey @emyphan  can you please share what you have done? thanks!
