### ISSUE TITLE
Possibility for parameterized/data driven test with protractor 

### ISSUE THREAD

**Issue by emyphan** [angular/protractor#620]
Hi,
for tests which are only different from data, is it possible to parameterize the test like table in cucumber or unit test? If not yet, it could be a nice feature.
Thanks

**Comment by hankduan** [comment]
For anyone still stuck on this, I wrote a mini tutorial on how to do it in your code in stackoverflow: http://stackoverflow.com/questions/27872783/how-do-i-open-multiple-windows-or-operate-multiple-instances/27874090#27874090

While this still requires some effort on your end and I've pointed out some shortcomings, it should allow you to write parametrized tests with protractor before there is a good solution for this.

**Comment by extdevelopment** [comment]
I created a simplified version of my spec.
I would like to run "it" blocks in loop.
I could use some of that value of element.all.count() in loop?
thx, I tried a lot

```javascript
'use strict';

describe('loopTest', function() {
	
	var count;
	var executionCounter = 0;
	
	beforeAll(function() {
		console.log('loopTest beforeAll begin', executionCounter++);
		browser.get(''); //baseUrl set in protractor.conf.js
		element
			.all(by.css('.row .btn.btn-link.btn-flat'))
			.count()
			.then(function(c) {
				count = c;
				console.log('loopTest beforeAll element.all.then', executionCounter++);
			});
	});
	
	var its = function() {
		console.log('its function begin', executionCounter++);
		it('it first', function() {
			expect(true).toEqual(true);
		});
		it('it second', function() {
			expect(true).toEqual(true);
		});
	};

	//protractor(jasmine) answere: No specs found, because this loop run, before beforeAll run
	//for (var int = 0; int < count; int++) {
	//with fixed constant value worked, but I want to use element.all.count() value
	for (var int = 0; int < 2; int++) {
		console.log('for loop', executionCounter++);
		its();
	}
});
```
<pre>
[chrome #2] Using the selenium server at http://localhost:4444/wd/hub
[chrome #2] for loop 0
[chrome #2] its function begin 1
[chrome #2] for loop 2
[chrome #2] its function begin 3
[chrome #2] Started
[chrome #2] loopTest
[chrome #2] loopTest beforeAll begin 4
[chrome #2] loopTest beforeAll element.all.then 5
[chrome #2]   it first 0 ...
[chrome #2]  Passed
[chrome #2] .  it second 0 ...
[chrome #2]  Passed
[chrome #2] .  it first 1 ...
[chrome #2]  Passed
[chrome #2] .  it second 1 ...
[chrome #2]  Passed
[chrome #2] .4 of 4 passed (0 skipped).
[chrome #2] SUCCESS: 4 specs, 0 failures, 0 skipped, 0 disabled in 4.884s.
</pre>

loop with count value
<pre>[chrome #2] Using the selenium server at http://localhost:4444/wd/hub
[chrome #2] Started
[chrome #2] loopTest
[chrome #2] 0 of 0 passed (0 skipped).
[chrome #2] SUCCESS: 0 specs, 0 failures, 0 skipped, 0 disabled in 0.003s.
[chrome #2]
[chrome #2]
[chrome #2] No specs found
[chrome #2] Finished in 0.003 seconds

</pre>

**Comment by juliemr** [comment]
I think this is answered with Hank's post above.

**Comment by extdevelopment** [comment]
@juliemr 
I think partially answered, 
http://stackoverflow.com/a/27874090
"Disadvantage is that since everything is in just 1 test, if 1 case out of 100 fails, you'll just get a single failure."

**Comment by cvakiitho** [comment]
Hi everyone, 

I\ve found this nice npm package for data driven jasmine: https://www.npmjs.com/package/jasmine-data-provider , 

so now I have data in params like this:

    params: {
        users: {
            admin_user: 'ADMIN-USER',
            manager_user: 'MANAGER-USER',
            supervisor_user: 'SUPERVISOR-USER',
            root_user: 'ROOT-USER',
            moderator_user: 'MODERATOR-USER'
        },
(but you can load them from json there.)

and use it like this:

    using(Object.keys(params.users), function (data) {
        it('all user roles should...

hope this helps someone.

**Comment by sachin-qe** [comment]
I want to execute the test where I can specify the browsername, environement name, suite name in execution command as follows
protractor conf.js browser=chrome env=staging suite=smoke

1. Is that possible with Jasmine and Protractor and 
2. Can any one show me how to achieve that?

**Comment by Milan-kumar** [comment]
Hi Sachin,
Try following command 
protractor conf.js --capabilities.browserName="chrome" --suite smoke

**Comment by lynn-fisher** [comment]
Hi All, 

I am looking to run test very like extdevelopment above but I dont think the important bit of the issue is covered in Hanks post as it is the looping of dynamic value that is tricky.

In the code above the sticking point is in the for loop where I want to be able to count rows of table on page and then run a test per row

 //protractor(jasmine) answere: No specs found, because this loop run, before beforeAll run
    //for (var int = 0; int < count; int++) {
    //with fixed constant value worked, but I want to use element.all.count() value
    for (var int = 0; int < 2; int++) {
        console.log('for loop', executionCounter++);
        its();
    }

So I would like to be able to replace the 'int < 2' with 'int < someTableRowOnPage'. As far as can see looping through table rows and doing a test cannot be done using Jasmine Data Provider as this uses static files. If I do count elements on a page in the beforeAll and use the count in the for loop the test doesn't run. It needs a hard coded value in the for loop.

Any suggestion would be most welcome
