### ISSUE TITLE
Unable to find modules

### ISSUE THREAD

**Issue by cambiph** [angular/protractor#630]
Hello,

I'm starting out with protractor and everything works fine.
But when I try out the page object structure, it seems that my pageobjects never seem to get loaded. The following stacktrace appears:

> Failures:
> 
>  1) homepage encountered a declaration exception
>   Message:
>     Error: Cannot find module './pageobjects/loginPage.js'
>   Stacktrace:
>     Error: Cannot find module './pageobjects/loginPage.js'
>    at require (module.js:380:17)
>    at null.<anonymous> (C:\mlbdev\responsive\tests\test.js:5:21)
>    at jasmine.Env.describe_ (C:\Users\pcambie1\AppData\Roaming\npm\node_modules\protractor\node_modules>>minijasminenode
> \lib\jasmine-1.3.1.js:907:21)
>    at jasmine.Env.describe (C:\Users\pcambie1\AppData\Roaming\npm\node_modules\protractor\node_modules>minijasminenode\
> lib\jasmine-1.3.1.js:892:15)
>    at describe (C:\Users\pcambie1\AppData\Roaming\npm\node_modules\protractor\node_modules>minijasminenode\lib\jasmine-
> 1.3.1.js:652:27)
>    at Object.<anonymous> (C:\mlbdev\responsive\tests\test.js:3:1)
> 
> Finished in 0.014 seconds
> 1 test, 1 assertion, 1 failure`

This is the page-object

``` javascript
var ptor;

var loginPage = function () {

    ptor       = protractor.getInstance();
    var driver = ptor.driver;

    this.usernameInput = ptor.driver.findelement(protractor.By.id('username'));
    this.passwordInput = ptor.driver.findelement(protractor.By.id('password'));
    this.loginButton   = ptor.driver.findelement(protractor.By.id('login_button_link'));
    this.header        = ptor.driver.findelement(protractor.By.tagName('h1'));

    this.login = function() {
        usernameInput.sendKeys('xxxxxxxx');
        passwordInput.sendKeys('xxxxxxx');
        loginButton.click();
    };
};

module.exports = new loginPage();
```

This is the actual test

``` javascript
var ptor;

describe('homepage', function() {

    var loginPage = require('./pageobjects/loginPage.js');

    beforeEach(function() {
        ptor = protractor.getInstance();
        ptor.driver.get('xxxxxxxxxx');
    });

    it('load page', function() {
        var header = ptor.driver.findElement(protractor.By.tagName('h1'));
        expect(header.getText()).toEqual('xxxxxx');
    });

    it('login', function() {
        loginPage.login;
        expect(loginPage.header.getText()).toEqual('xxxxxx');
    });
});
```

Any idea what I'm doing wrong here?

**Comment by ryanlitalien** [comment]
Just a random comment, I had the same issue, but capitalization was the problem. I renamed the page object file to lowercase and it worked.
I had `../pageobjects/page.js` and the file was named `Page.js`. Renamed to `page.js` and all was well.

**Comment by pinkninjajess** [comment]
I was having the same issue, and ryanlitalien's recommendation to remove capitalization from the beginning of file and folder names worked for me as well

**Comment by rcadia** [comment]
I can confirm that this issue is still experienced.

**Comment by adnanghaffar07** [comment]
Yeah, format should be camelCase e.g objectPage.

**Comment by subrato29** [comment]
Below is my pageobject:

'use strict';

import Promise from 'promise';

let EC = protractor.ExpectedConditions;


export default class LoginPage extends YCCObject{

	constructor() {
		super();
		this._username = () => {
            return new Promise((resolve, reject) => {
                 element(by.xpath("//input[@type='email']")).isPresent().then((present) => {  
                    if (present) {
                            resolve(element(by.xpath("//input[@type='email']")));
                    } else {
                        	browser.getCurrentUrl().then((url) => {
                            reject('Error1 in setting email address in Login page.' + url);
                        });
                    }
                });
            });
        };


     } 

    set_username(email_address) {
        let _this = this;
        let username = undefined;
        return _this._username().then((_username) => {
            username = _username;
            return username.clear();
        }).then(() => {
            return username.sendKeys(email_address);
        }).catch((err) => {
            log.warn('Error2 in setting email address in Login page.', err);
            return Promise.reject(err);
        });
    }    
}


Below is my spec file:

'use strict'

browser.ignoreSynchronization = true;

//import LoginPage from '../../pages/login_page';
//import '../..//pages/login_page.js';
var LoginPage = require('specs/login_page.js');
//import LoginPage from 'src/specs/login_page.js';

var loginPage = new LoginPage();
let browserName = browser.params.browser;
let version = browser.params.version;
let product = browser.params.product;

describe('YSB test cases::', function() {

    beforeEach((done) => {
        browser.waitForAngularEnabled(false);
        browser.get("https://login.yahoosmallbusiness.com/login?.done=https%3A%2F%2Flogin.yahoosmallbusiness.com%2FSAML2%2FSSO%2Fredirect%3FSAMLRequest%3DnVNdj9owEPwrlt%252FJV69FWIQTBVVF4noRSfvQl8o4y2HVsVOvzXH%252Fvk4IJ1r1UMVTpN3x7OzMZnp%252FbBQ5gEVpdE7TKKH3synyRrVs7t1eb%252BCXB3QkwDSyvpFTbzUzHCUyzRtA5gQr5w9rlkUJa61xRhhFyWqZ0x817CbpNqmT8VhsOX83%252BZDtKPl2HhheBCCih5VGx7ULpSSdjJJslI2r5I7dJSx5H02S8XdKioH6o9S11E%252FXdWxPIGSfq6oYFY9lRckcEawLgxdGo2%252FAlmAPUsDXzTqne%252BdaZHGszJPUkfKN1NxBJEwTd6RZXJaPseBKbbn4SckyuNIh%252BjX%252BfPvC98Zg00E9Sg2If7FYqKUF4Sj5ZKyA3uicOuuhX%252FIga7BfwkY5XS0fyLojJdyR9aCJnhJivW%252F2IprrjvDz9nT2X3o7xml8Mel8GJ201bIwSoqXWw4jLN1w9zY6jdK%252BIuvRrocy72Ud4lPKPC8sBAsGt%252BKzpOFMoe69DPE6ON50tAvTtNxK7FKFIw8ZDWZfEi9U8HIDu1usvwoTTHTUoVyEz7OxdXfz4VKgrizX2Brrhkj%252BpWd26r1hx2v38see%252FQY%253D%26RelayState%3Dhttps%253A%252F%252Fwww.yahoosmallbusiness.com%252Fservices%253F_ga%253D2.96332436.982347178.1551242403-1359328870.1551242403%2526authRedirect%253Dtrue%26idp%3Doff%26userid%3D%26SigAlg%3Dhttp%253A%252F%252Fwww.w3.org%252F2001%252F04%252Fxmldsig-more%2523rsa-sha256%26Signature%3DLzRflzdugb2neWkahkYtSIHh721w%252Fqi0Jsa3Ai0tEMnhuZPhXgVUAm9xw%252FVJ4kY2dICj8zJhdLaFpOKBGVC6O9xCgJZydGcFzLMzeEvx14qu0rlBlaoukb4HeZWis7NlSdl6b1yW3369KxaPMD%252FowP5rN09X0RNIM5ArafLDNlBTxefgtsn8vM4o%252F30HceD3VMKMru71IUmu1NeAZ1imFAMYsrXW41fwiNq7tFwNTGk0j3elY5RSblpEZ2f1pUK%252BVNxcHpactD%252BblNs4whd5Aw9Cfjpfh16h3k7NnLNXud%252BDqj7AKew7TCPUNyn4Qp%252BYK%252FoxcDg%252Bu4Xnl%252BJXt%252Fv%252BAw%253D%253D").then(() => {
            done();
        });
    });

    it('Successful login- ', function() {
          browser.driver.manage().deleteAllCookies().then(() => {
              console.log("cookies deleted")
          }).then(() => {
              return browser.driver.manage().window().maximize();
          }).then(() => {
              return loginPage.set_username("ysbyccauto@gmail.com");
              //return element(by.xpath("//input[@type='email']")).sendKeys("ysbyccauto@gmail.com")
          }).then(() => {
              return element(by.xpath("//input[@type='password']")).sendKeys("Kolkata123*");
          }).then(() => {
              return element(by.xpath("//button[@type='submit']")).click()
          }).then(() => {
              //expect(element(by.xpath("//h1[text()='My Services']")).getText()).toBe('My Services');
              //console.log(element(by.xpath("//h1[text()='My Services']")).getText());
              //console.log(element(by.xpath("//a[text()='GET IT NOW']")).getText());
              //done();
          });
          
    });

});

  I am getting the below error, not sure about the reason, can anybody help
[13:45:44] I/launcher - Running 1 instances of WebDriver
[13:45:44] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[13:45:45] E/launcher - Error: Error: Cannot find module 'specs/login_page.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/shaurosenipalchoudhuri/protractor/practice/src/specs/ysb-spec.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[13:45:45] E/launcher - Process exited with error code 100

**Comment by subrato29** [comment]
practice shaurosenipalchoudhuri$ protractor conf.js
[14:02:07] I/launcher - Running 1 instances of WebDriver
[14:02:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:02:08] E/launcher - Error: /Users/shaurosenipalchoudhuri/protractor/practice/src/specs/ysb-spec.js:6
import LoginPage from '../src/pages/login_page';
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[14:02:08] E/launcher - Process exited with error code 100
Subratos-Air:practice shaurosenipalchoudhuri$

**Comment by subrato29** [comment]
Any idea about the error message?
practice shaurosenipalchoudhuri$ protractor conf.js
[14:02:07] I/launcher - Running 1 instances of WebDriver
[14:02:07] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[14:02:08] E/launcher - Error: /Users/shaurosenipalchoudhuri/protractor/practice/src/specs/ysb-spec.js:6
import LoginPage from '../src/pages/login_page';
       ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
[14:02:08] E/launcher - Process exited with error code 100
Subratos-Air:practice shaurosenipalchoudhuri$
