### ISSUE TITLE
Corrupted selenium server jar

### ISSUE THREAD

**Issue by gtramontina** [angular/protractor#656]
Hi there,

I used `webdriver-manager` to download the latest version of the selenium server. In my `protractor.conf.js` I specify `seleniumServerJar` so that protractor would take care of starting it up and shutting it down. Then, when running the tests, I started getting a timeout when starting the selenium server.
Digging into protractor's code, I found that protractor is only accounting for the happy path when running `java -jar ...`. It turns out that the selenium server jar that was downloaded with `webdriver-manager` got corrupted somehow (during download, probably) and protractor didn't know about that.

My suggestion here is to also consider this scenario, as I spent an awful lot of time to figure this out.

**Comment by jackwhit3** [comment]
Is this fixed? 
I'm still having this problem, please see [this](https://github.com/angular/angular-phonecat/issues/276).
