### ISSUE TITLE
Protractor and angular manual bootstrap

### ISSUE THREAD

**Issue by scastelein** [angular/protractor#66]
I'm having a problem when running  protractor 0.8 and having troubles running protractor on our app that is manually bootstrapped. 

Here are some snippets revealing the relevant parts of the application and setup:
index.html:

``` javascript
 <script type="text/javascript" data-main="js/main" src="js/libraries/require.js"></script>
```

js/main.js:

``` javascript
require({
    shim: {
        .... snip ..
            }
           }, 
  ['require', ..... ], function(require) {
    return require(['bootstrap']);
```

bootstrap.js:

``` javascript
var appElm = $('html');
appElm.addClass('ng-app'); // this
angular.bootstrap(document, ['app']);
```

This works in practice and Angular is started in a correct way. When I view the html source I cannot see the ng-app attribute appearing on the html element. May be Protractor also fails to do so?

I use the protractor sample configuration and changed the relevant values to suit my app:

``` javascript
specs: [
    '../src/test/javascript/protractorSpec/*_spec.js',
  ],
  baseUrl: 'http://localhost:8080/Viewer/',
  rootElement: 'html',
```

Sample test:

``` javascript
describe('List SMC Charts', function() {
        var ptor= protractor.getInstance();

        beforeEach(function() {
          ptor.get('#/smcChart');
        });

        it('list, no filter', function() {
          var selectOption = ptor.findElement(ptor.By.input("selectOption"));
        });
});
```

When I run this test two errors appear:

``` javascript
 1) List SMC Charts   list, no filter
   Message:
     Error: Angular could not be found on the page http://localhost:8080/Viewer/#/smcChart
   Stacktrace:
     Error: Angular could not be found on the page http://localhost:8080/Viewer/#/smcChart
    at /usr/local/lib/node_modules/protractor/lib/protractor.js:392:15
```

and

``` javascript
2) List SMC Charts list, no filter
   Message:
     TypeError: Cannot call method 'input' of undefined
   Stacktrace:
     TypeError: Cannot call method 'input' of undefined
    at null.<anonymous> (/Users/........//Viewer/src/test/javascript/protractorSpec/some_spec.js:9:55)
```

The first error seems to be the most important one, but the last error is also quite interesting. It appears to me that the line: ptor.By.input is not working.

Any ideas?

**Comment by mindmelting** [comment]
@jongunnip Yep that worked for me too, thanks!

**Comment by chenchengxing** [comment]
@mikaraento It worked for me, thanks~

**Comment by GuyMograbi** [comment]
Hi guys, strange thing relevant for this thread. 

I have a regular angular app - no requirejs or anything, I am using protractor 2.0.0. 

When I run the system tests on staging environment it works. 
When I run it locally it gives me : 
`org.openqa.selenium.WebDriverException: unknown error: [ng:btstrpd] App Already Bootstrapped with this Element ` ... message

Does it matter if I run it with livereload in development?

**Comment by Crotery** [comment]
Seems like static servers behave differently, and grunt serves some 404s or redirects, so webdriver goes crazy.

**Comment by erkobridee** [comment]
Hi all,

after a lot of time reading and reading, I found one solution that works well to my project ([fix protractor execution flow](https://github.com/the-front/angularjs-ee-boilerplate/commit/57a42c52af17b1c22fd1f30b2b278dc266ab94c7))

1. when open the app to protractor add `?protractor-test` to URL ([project code](https://github.com/the-front/angularjs-ee-boilerplate/blob/57a42c52af17b1c22fd1f30b2b278dc266ab94c7/tools/gulp/tasks/protractor.js#L19))
2. change the angular bootstrap code to be like the bellow ([project code](https://github.com/the-front/angularjs-ee-boilerplate/blob/57a42c52af17b1c22fd1f30b2b278dc266ab94c7/src/ng.app.js#L29-L36))

```javascript
if(location.href.indexOf("protractor-test") < 0){
  // start angular app
  angular.bootstrap(document, [module.name]);
} else {
  // start angular app to protractor tests
  window.name = 'NG_DEFER_BOOTSTRAP!' + window.name;
  angular.bootstrap(document, [module.name]);
}
```

and finally all back to work again \o/

with copy @juliemr

**Comment by WINSUNKING** [comment]
I recently(just 1-2 weeks) started using Protractor to test my Angular application. My application has ng-App defined in body tag on Login page. My Test keep complaining saying "Angular could not be found on the page httP://(WebSite Address) : angular never provided resumeBootstrap"  But test execution is fine. Not sure about the issue ( if i turn on browser ignoresync parameter then it is working fine , but this is not correct way ), I can try what Juliemr suggesting ( use legacy driver to navigate ), but just trying to understand why my app complaining even though it has ng-App in body tag. App Functional Behavior is like this.. Login Page..Once Log In click on some link on Home Page and it opens another Window/Tab.  Could someone help me in finding steps what all need to verify to make sure bootstraping is done automatic way ( one is ng-app parameter in body tag ) ? Do i need to check something in bootstrap.js file ( I do not see any ng-app parameter in bootstrap file hence checking. Thank you

**Comment by gd46** [comment]
Is there any updates on this issue? What are the best practices or methods for configuring protractor to work on with an angular app that doesnt have an ng-app? @erkobridee could you explain your example further? And can someone explain how to properly handle window.name in regards to how protractor should wait for when angular is done loading?

**Comment by bcherny** [comment]
@juliemr With Angular 1.5, manually bootstrapping is the preferred way to bootstrap. Is there blessed protractor support on the way?

**Comment by tommyz0123** [comment]
+1  I think this issue should be higher priority.  If Protractor does not work with manual bootstrap, then there's no benefit of using Protractor.  The whole point of using Protractor over Webdriver is that Protractor handles all the angular sync for you.

**Comment by antoniodimaio** [comment]
I have the same issue. Any update?

**Comment by millerwx** [comment]
hi, is there any plan or process to improve this ?

**Comment by antoniodimaio** [comment]
Strange there is no feedback. I have apps missing ng-app and I can not test
them with protractor

**Comment by juanmendez** [comment]
To this date in 2016, this was still a problem for me. I followed Magnetized answer to solve the issue. I just did  a few changes. What is nice and out of scope with the conversation is to track also redirects and land back inside your app.

`describe('login screen', ()=>{

    var urlTimeout = 60000;

    const waitForUrlRegex = (regex, urlMatcher )=>{

        return driver.wait(function() {
            return driver.getCurrentUrl().then(function(url) {
                return regex.test(url);
            });
        }, urlTimeout, "Expectation error: Timeout for url not matching " + urlMatcher );
    };

    const waitForRoute = (route)=>{
        return waitForUrlRegex( new RegExp( route + "$" ), route  );
    }

    const waitForUrl = ( url )=>{
        return waitForUrlRegex( new RegExp( "^https?:\/\/" + url ), url );
    }

    it('should login and land in user-screen', ()=>{

        driver.get( app_url, urlTimeout);

        //there is a redirect to welcome route
        waitForRoute("welcome")
        .then( () =>{

            const loginButton = element.all(by.className("login_button")).get(1);
            loginButton.click();

            return waitForUrl( non_angular_login_url );
        }).then( ()=>{

            driver.findElement( by.name("user")).sendKeys( "username");
            driver.findElement( by.name("password")).sendKeys( "userpassword");
            driver.findElement( by.tagName("button")).click();

            return waitForRoute( "user-screen");
        }).then(()=>{
           //continue now on with your tests.
        });
    });
});`

**Comment by juanmendez** [comment]
If there was no initial route redirection, how about just `browser.driver.sleep( milliseconds );` before testing. This might work as your app might have already angular done the bootstrapping.

**Comment by sjelin** [comment]
We do actually support manual bootstrapping, this information is old.  Bootstrapping will become even more reliable once we handle https://github.com/angular/protractor/issues/3857 as well.

**Comment by miguelrincon** [comment]
@sjelin What's the documented way to support manual bootstrapping? I can't find the relevant information for protractor 5.0.

**Comment by diptenagile** [comment]
I was facing the same issue while manual bootstrapping. and found the solution to run with grunt.
used protractor version 2.5.1. 

1. Mention this in your grunt file.

`grunt.initConfig({
    protractor: {
        options: {
            configFile: "protractor.conf.js", // Default protractor config file
            keepAlive: true, // If false, the grunt process stops when the test fails.
            noColor: false, // If true, protractor will not use colors in its output.
            args: {
                // Arguments passed to the command
            }
        },
        e2e: {
            options: {
                // Stops Grunt process if a test fails
                keepAlive: true
            }
        },
    }
})`

2. Run protractor with following command : 
`grunt protractor`
or with suite name
`grunt protractor  --suite suite_name`


Please let me know if it work for you.

**Comment by NaveenKVN** [comment]
This worked for me.    
  `  browser.ignoreSynchronization = true;
    browser.get(url);
    browser.ignoreSynchronization = false;`
