### ISSUE TITLE
Overriding modules with addMockModule

### ISSUE THREAD

**Issue by newmedio** [angular/protractor#667]
I am attempting to overwrite a module in the application with a mock module, but it does not seem to be working, and it is possible that I do not understand the documentation correctly.

In the main code, I have:

``` javascript
angular.module('myApp.authServices', [])
.service("myLoginService", ['$http', function($http) {
    this.authenticate = function() {
           /* Do authentication here */
         };
}]);
```

So, in my e2e test script, I attempted to do the following:

``` javascript
var authServiceMock = function() {
  angular.module('myApp.authServices', [])
  .service("myLoginService", ['$http', function($http) {
    this.authenticate = function() {
           /* Do alternative authentication here */
         };
  }]);
};
```

Then, I do:

```
browser.addMockModule("myApp.authServices", authServiceMock);
```

I have tried putting that line in several places - before any tests, in a beforeEach, and in the middle of tests, but it _always_ calls the "myLoginService" from the main code.  Any ideas?

**Comment by pablolopezmera** [comment]
Did you get resolved?

**Comment by filipesiqueira** [comment]
same doubt

**Comment by dogmatic69** [comment]
I have the same issue, tried the browser.addMockModule all, its never called.

**Comment by zhuk-aa** [comment]
I have the same issue if I put
```
browser.ignoreSynchronization = true; 
```
before _browser.addMockModule_.
If I do it after _browser.get_ - everything works.

**Comment by picodoth** [comment]
@zhuk-aa  seriously, you just saved me from hell!
