### ISSUE TITLE
element ... .getAttribute(...) returning Objects unexpectedly

### ISSUE THREAD

**Issue by geppy** [angular/protractor#673]
I'm collecting all of the anchor tags on a page with the intent of checking to ensure that they aren't dead links...  but I'm unexpectedly finding that I'm unable to get valid HREF values for half of them.

```
element.all(by.css('a')).each(function (element) {
    var linkTarget = element.getAttribute('href');
    expect(typeof linkTarget).toBe("string");
});
```

If I run code in the browser on the same site, I find that all of my anchor tags have an href of type "string".  Am I using the API incorrectly?  I'm using Protractor on a non-Angular page: does this functionality depend on Angular?

**Comment by dman777** [comment]
thanks!

**Comment by SteveKelly** [comment]
thanks!

**Comment by georgepapas** [comment]
+1

**Comment by alediaferia** [comment]
Since pretty much everything in Protractor returns a promise I was wondering when is required to `then` and when it is not.

As per this excerpt from the web page, why is this OK
```javascript
// You wrote your first test, cross it off the list
todoList.get(2).element(by.css('input')).click();
var completedAmount = element.all(by.css('.done-true'));
expect(completedAmount.count()).toEqual(2);
```

instead of the following?
````javascript
// You wrote your first test, cross it off the list
todoList.get(2).element(by.css('input')).click().then(function() {
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
});
````

Do I have any guarantee that what is triggered by the click has finished executing by the time the rest of the code is executed?

**Comment by diegognt** [comment]
Thats explain a lot of things, Thanks

**Comment by patproc** [comment]
hi, i am new to protractor and need some help. i have a scenario where i need to assert if image have alt attribute. please see the following eg:

1) <img class="img-responsive" itemprop="logo" src="/1.5.19.0-SNAPSHOT/assets/ch-logo.png" alt="CHI">

expect(element(by.css(a.brand-logo img.img-responsive))).toBe(true); 


2) <img src="/1.5.19.0-SNAPSHOT/assets/cp-logo-small.png">

expect(element(by.css(img[src="/1.5.19.0-SNAPSHOT/assets/cp-logo-small.png"]))).toBe(true); 

when i run the above two assertions they both are passing, but i want first to be pass and second to be fail as there is no alt attribute.

**Comment by flexin777** [comment]
Hello!
I can not take value form place holder. I do not why.
<input class="form-control ng-pristine ng-valid ng-not-empty ng-touched" type="text" ng-disabled="!conn.active" ng-model="conn.connection_name" placeholder="Connection Name"/>

Yes input does not have text value. But i can see value "new Connection" on page.

**Comment by flexin777** [comment]
<input class="form-control ng-pristine ng-valid ng-not-empty ng-touched" type="text" ng-disabled="!conn.active" ng-model="conn.connection_name" placeholder="Connection Name"/>

**Comment by flexin777** [comment]
input class="form-control ng-pristine ng-valid ng-not-empty ng-touched" type="text" ng-disabled="!conn.active" ng-model="conn.connection_name" placeholder="Connection Name"/>

**Comment by ovidiu8** [comment]
Hello. Try **element.getText()**.then (function (data) { ....});

**Comment by flexin777** [comment]
hello! I found solution. Uses element(...).getAttribute('value').then(function(value){
....
})

**Comment by bhushanborse** [comment]
Hello all I want to print the value of textbox in a console. Here is my code 

<input id="ProFName" type="text" name="Fname" class="string_validation" value="Bhushan" readonly="true">

  $('#ProFName').getText().then(function(text){
         console.log(text);
});

How I can use getAttribute('value ')

**Comment by NathanCH** [comment]
Compare the values to two elements...

```
var input1, input2;

driver.findElement(By.id('input1')).getAttribute('value').then(function(attr) {
  input1 = attr;
});

driver.findElement(By.id('input2')).getAttribute('value').then(function(attr) {
  input2 = attr;
});

expect(input1).to.equal(input2);
```

Quite tedious unfortunately

**Comment by prashantbismani** [comment]
Thank you @juliemr and @geppy, it helped a lot!.
