### ISSUE TITLE
Idea: surface information about latency for webdriver commands

### ISSUE THREAD

**Issue by juliemr** [angular/protractor#674]
This could be helpful for debugging where some environments (e.g. travis -> sauce) have much longer command round-trip times than others (local -> local).

**Comment by elgalu** [comment]
Very nice Julie! is it possible to include the event id on mouse hover?

![include id](https://cldup.com/nz9FFYpOLs-3000x3000.png "Include Id")

**Comment by bailejl** [comment]
I like the timeline plugin.  I am new to Protractor, so I am using it with Cucumber and Chai.  Here is a screen shot of my timeline.  It does not have the detail of what exactly ran.  It only shows "execute async script" and not the Cucumber step name or browser action.  Is there any configuration I can do to change the output?

I am also having two problems with Chrome and Firefox maybe you can give me some guidance.  When I launch my Angular app in Firefox from Protractor, Angular does not execute.  Thus, the Angular elements remain on the page "{{ }}" and the tests hang.  When running in Chrome, each browser interaction takes about ten seconds.  Any thoughts on where I should register these issues?
![screen shot 2015-01-25 at 1 27 37 pm](https://cloud.githubusercontent.com/assets/2799489/5891600/a6a5b482-a497-11e4-8812-a172f4bd003b.png)

**Comment by bailejl** [comment]
I stumbled on something strange.  I started up my dev server which listens on 3000, while I ran my protractor tests and everything ran fast.  My tests starts the server on 3001, so they are not using the dev server.  The timelines look different, as you can see.

![screen shot 2015-01-25 at 1 27 37 pm](https://cloud.githubusercontent.com/assets/2799489/5891652/38f88074-a49a-11e4-9d65-0204b0edb898.png)
![screen shot 2015-01-25 at 1 52 16 pm](https://cloud.githubusercontent.com/assets/2799489/5891651/329e7828-a49a-11e4-9b4f-edd020f72a3e.png)

**Comment by Phoscur** [comment]
I'm also using Protractor with Cucumber, but I couldn't get any timeline printout yet, can you describe your setup? @bailejl 
I also tried protractor-perf, but it's outdatet and doesn't work with protractor versions >1.4

**Comment by juliemr** [comment]
I think that the best way to deal with this would be via blockingproxy. See https://github.com/angular/blocking-proxy/issues/5
