### ISSUE TITLE
Click link and wait for URL to change?

### ISSUE THREAD

**Issue by andrewboni** [angular/protractor#685]
I'm trying to do something seemingly simple, yet I can't get it to work properly. Others have asked similar questions, but the solutions haven't fixed things for me.

I want to do the following:
1. Click a form submit button
2. Wait for the new page to load
3. Expect the URL to be something else

Here is the relevant code:

```
 beforeEach(function () {
        ptor = protractor.getInstance();
        ptor.ignoreSynchronization = true;
        ptor.get('/campaigns');
    }, 60000);

it("selecting continue", function() {
       var continueBtn = element(by.id('continue'));
        continueBtn.click().then(function() {
            expect(ptor.getCurrentUrl()).toContain(ptor.baseUrl + '/templates');
        });
    });
```

Clicking the submit button can take some time (anywhere from 1 - 10+ secs on my local machine), before the new page is loaded.

The `expect` statement consistently leads to an error:

```
Message:
     Expected 'http://localhost:9000/campaigns' to contain 'http://localhost:9000/templates'.
```

Any thoughts on the correct way to resolve this?

**Comment by rahul-wenable** [comment]
Thanks a ton @juliemr.. You've been an awesome reference to me whenever I'm stuck at something in Protractor js..

**Comment by AEIOU-1** [comment]
i an having an issue - the URL i need to wait for is not static. The  base URL is same but then there are some numbers which is issued randomly .  My question how can i put a wait for specific URL with giving the partial URL . 
   Example : baseURL/some_random_number/someStaticText

**Comment by stwic** [comment]
@AEIOU-1 I had a similar issue, and here is my solution.

``` javascript
function waitForUrl(newUrl) {
      browser.getCurrentUrl().then(function () {
          browser.wait(function () {
              return browser.getCurrentUrl().then(function (url) {
                  return newUrl.test(url);
              });
          });
      });
}

it('opens up the url', () => {
    browser.get('yoururlhere');
    // call the wait function and pass a part of your url, 
    // in my case it was /app#/app/inbox/empty
    waitForUrl(/app#\/app\/inbox\/empty/);
}); 
```
