### ISSUE TITLE
E2E Testing with a custom DSL for remote backend server configuration (node server)

### ISSUE THREAD

**Issue by leifhanack** [angular/protractor#69]
Hi, 
if I understand it correct, protractor will be a replacement (alternative?) for karma's E2E testing, so that karma can focus on unit testing. Does that mean that ngScenario and it's [dsl](https://github.com/angular/angular.js/blob/master/src/ngScenario/dsl.js) will be removed from angular 1.2+?

Currently we extended angular's e2e testing, so that we can run e2e tests with a mocked backend. We can configure how the mocked backend (a node server) should answer to incoming requests. Besides _browser().xxx()_ we can do _server().yyy()_ things ([see the extended API for more details](https://github.com/hypoport/node-config-ngscenario-dsl/wiki/API-Documentation)). Doing that, we can test the UI, error handling and all that with the speed of unit tests. 

We would love to have something similar in protractor as well. 

What do you think about it? 

Best regards, Leif

For more details about our extension of ngScenario dsl please take a look at the [introduction](http://blog-it.hypoport.de/2013/08/20/introduction-to-an-angular-scenario-dsl-for-remote-node-backend-configuration/) or the [github project](https://github.com/hypoport/node-config-ngscenario-dsl).

**Comment by juliemr** [comment]
I'm not sure if this is still in progress or not, but I don't think having this issue open is helping out. I'm going to close for now, but please let us know how things go!

**Comment by weeksling** [comment]
@juliemr are you aware if this project was ever undertaken? My team is interested in finding a better way to control our backendMock from within our integration tests.
