### ISSUE TITLE
OSX protractor.Key.COMMAND not available

### ISSUE THREAD

**Issue by elgalu** [angular/protractor#690]
We are trying to test copy & paste functionality on OSX browsers but this isn't working:

``` js
pasteArea.sendKeys(protractor.Key.chord(protractor.Key.COMMAND, "v"));
```

Nor this

``` js
browser.actions().keyDown(protractor.Key.COMMAND).sendKeys('v').
    keyUp(protractor.Key.COMMAND).perform();
```

I also tried `CMD` but fails with `Error: Not a modifier key`.

On Linux and Windows, `CONTROL` works fine. IE11 needs some workarounds though. But _CTRL+V_ doesn't paste on OSX, as you know _(CMD+V)_

There are [java bindings for COMMAND](http://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/Keys.html#COMMAND) but can't find them [on webdriver.js source](https://code.google.com/p/selenium/source/browse/javascript/webdriver/webdriver.js#1724)

**Comment by mrzmyr** [comment]
Just referencing my answer in https://github.com/angular/protractor/issues/1037#issuecomment-150226458.
