### ISSUE TITLE
Cannot find module 'cucumber'

### ISSUE THREAD

**Issue by benhoIIand** [angular/protractor#703]
Hi,

I've cloned this respository and am attempting to run the example cucumber tests, but am sadly getting this error message

```
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Error: Cannot find module 'cucumber'
```

I've run `npm install` and the cucumber module has been pulled down. Is anyone else seeing this issue?

**Edit:** I am also seeing the same issue with Mocha.
**Edit:** Installing Cucumber globally seems stop the error message. Shouldn't protractor look in the local bin folder? Do they need to be specified in the `package.json` file?

Thanks

**Comment by lbrown768** [comment]
I am new to using cucumber with protractor and I am receiving the same error even after installing cucumber globally. Any idea what else I can try?
