### ISSUE TITLE
Cannot run all tests sequentially in protractor

### ISSUE THREAD

**Issue by nethulap** [angular/protractor#708]
I am new to E2E testing with Protractor. I have created 3 test specs. Each test spec has one <code>describe</code> and several <code>it</code> in it. I want to run all specs sequentially.

My protractor config file with specs listed like this
specs: [
      'tests/../test1_spec.js',
      'tests/../test2_spec.js',
      'tests/../test3_spec.js'
    ]

When I run my protractor config file all the tests start running simultaneously.
I am not sure if my config file is wrong or something else which is triggering the simultaneous tests runs.

**Comment by sharathbabupulumati** [comment]
I tried running the protractor config using the above example but still it doesn't seem like its running sequentially.

The above example will only wait until the login is successful and it triggers the second test without waiting for the first test to finish. I need the first test to run completely and finish and then the second test should start to run.but the first and second files are in different folders.

**Comment by Mms2510** [comment]
i am also getting same issue, i have one describe associated with one "it"
and similarly, 10 different suites with each spec, when i am executing with Jenkins, it is not executng sequencially, any suite is getting triggered, 

I wan to know is there any annotation or keyword in Jenkin or Jasmine, to make suite run sequentially ione after the other like we used to work in TestNG using @priority annotation

**Comment by sharathbabupulumati** [comment]
For the above mentioned problem, the alternative way, i think so is, to place all these files names in a sequential order as a suite in one file and make the trigger to collect the testcase from that file which contains the all the testcase names.

**Comment by LalithVigneshS** [comment]
+1
