### ISSUE TITLE
Focus issues make tests failing

### ISSUE THREAD

**Issue by giosakti** [angular/protractor#713]
Hi, 

I'm using osx 10.9.2, protractor 0.21.0, selenium-server-standalone 2.40.0 and chromedriver 2.9. 

I'm having some problems, which (I believe) was due to window focusing issue.

When I run my e2e test using protractor, the browser window would show but my terminal will still be the one in focus. This is apparent from "Terminal" was still shown in my menu bar rather than "Chrome" (osx behavior that indicates which app is in focus).

I tried to remedy this situation by doing this:

```
  browser.driver.getAllWindowHandles().then(function(handles) {
    console.log(handles[0]);
    browser.driver.switchTo().window(handles[0]);
  });
```

to no avail.

This situation causes some of my tests to fail. For example, tests that include clicking a field with bootstrap datepicker won't show the calendar and making my test cannot interact with the datepicker calendar.

The situation is even worse on firefox. Firefox won't even show any dropdown menu when clicked if the browser is not in focus.

Funnily, when I click the browser window manually after it shows up the first time, the tests will work normally.

**Comment by Szuchow** [comment]
> My workaround is to delegate `:focus` tests to a machine or VM or BrowserStack instance that I can leave alone while executing, i.e. the browser never loses focus in which case I never need manual intervention like clicking.

Could you elaborate?
