### ISSUE TITLE
How to access nested ng-repeat elements

### ISSUE THREAD

**Issue by AlexCppns** [angular/protractor#722]
I am trying something like: 

```
element.all(by.repeater('suggestion_type in searchBoxData.suggestion_types')).then(function(rows) {
  for(var i=0;i<rows.length;i++){
    rows[i].then(function(){
      element.all(by.repeater('content in suggestion_type.contents')).then(function(rows_2) {
        console.log(rows_2);
      });
    });
  }
});
```

but I am getting duplicate rows...

**Comment by reddynr** [comment]
Hi All,

I am testing an example using protractor. I need to select the data which is showing in ng-repeate <li></li>

getting error. Any help much appreciated. Thanks

element.all(by.repeater('branch in branches')).get(1).element(by.linkText('branchName')).click()
