### ISSUE TITLE
UnknownError: unknown error: session deleted because of page crash from tab crashed

### ISSUE THREAD

**Issue by lynndylanhurley** [angular/protractor#731]
When I run the following test (and any test that uses `browser.get()`):

``` coffee
it 'should wrap webdriver', ->
  browser.get('/')
```

I get this error:
`UnknownError: unknown error: session deleted because of page crash from tab crashed`

screenshot of protractor error:
![screen shot 2014-04-20 at 4 49 54 pm](https://cloud.githubusercontent.com/assets/468037/2751543/3b00bf62-c8d6-11e3-99b1-c0c5f26cda04.png)

screenshot of error output from `webdriver-manager start`:
![screen shot 2014-04-20 at 4 54 35 pm](https://cloud.githubusercontent.com/assets/468037/2751545/8f9e04a8-c8d6-11e3-8bd0-461592b0083c.png)

here is my protractor conf:

``` js
exports.config = {
  // The address of a running selenium server.
  seleniumAddress: 'http://localhost:4444/wd/hub',

  // Capabilities to be passed to the webdriver instance.
  capabilities: {
    'browserName': 'chrome'
  },

  // Spec patterns are relative to the current working directly when
  // protractor is called.
  specs: ['test/e2e/**/*.coffee'],

  framework: 'mocha',
  baseUrl: 'http://databox-admin.192.168.1.62.xip.io',

  mochaOpts: {
    reporter: "nyan",
    slow: 10000
  }
};
```

The strange thing is that everything works when I run selenium from a different project (using `webdriver-manager start` from that project's directory).

I've run `webdriver-manager update` and it says I'm using the latest version. 

I've been struggling with this for several hours - any idea what's going on?

**Comment by atav32** [comment]
+1

Had the same problem. Thanks!
