### ISSUE TITLE
timeout: timed out after 30000 msec waiting for spec to complete

### ISSUE THREAD

**Issue by iwoogy** [angular/protractor#739]
Hello,

I'm quite new to protractor and I love the concept of it. I plan to implement systematically protractor on all my angular projects.

But on my first tests, I got a reccuring issue with timeout 30000 ms from selenium.
My angular projects contain a lot of files small modules, that's why it takes so long to load each page. On production, I compile of those files into one, but in dev mode, it's not that possible.

I've searched through the web to find a solution that may help, but I didn't find anything that was working for my case.

![image](https://cloud.githubusercontent.com/assets/479162/2774555/9ea0acbe-cab9-11e3-8913-76b516151988.png)

I'm also using astrolabe to make it easier to use page_objects.

Can anyone help me understand how to fix this issue ?

**Comment by robertye112** [comment]
+1 this is happening to me in version 3.3.0. (this never used to happen, I know how to use these pause/debug features, it's a new issue in 3.3.0)
