### ISSUE TITLE
setting request headers

### ISSUE THREAD

**Issue by mmaquevice** [angular/protractor#740]
Hey,

I'm having difficulties setting headers in my requests (browser.get('/path');) 
Is there a way to do so ?

Thanks !

**Comment by armw4** [comment]
Custom headers would be more than nice. :+1:

**Comment by sksamuel** [comment]
+1 using headers to enable things in non-prod env is very common. Please add this feature.

**Comment by sonata82** [comment]
+1

In my case the browsers in prod env have to go through proxy and authentication servers, which set a number of HTTP headers. Currently our solution is to proxy all requests from protractor through connect.

**Comment by stefanvangastel** [comment]
+1; We use SSO / Kerberos and I would like to imitate another user than me. Hence I need to set the Authorization header.

**Comment by ch0wdan** [comment]
+1 on adding headers

**Comment by nobso** [comment]
+1 for modifying headers

**Comment by peterjcaulfield** [comment]
+1 on adding headers. In my case, I want to be able to control different responses from the same user action coming back from a mocked API.

**Comment by britez** [comment]
+1 We don't want to log allways... we have a test case testing it. We need to bypass them. We want setting headers!

**Comment by herinruhela** [comment]
+1

**Comment by sjelin** [comment]
We'd need webdriver to implement this feature, which they've [already rejected doing](https://code.google.com/p/selenium/issues/detail?id=141).  You could try contacting them on [their github](https://github.com/SeleniumHQ/selenium) but I don't think it will get you anywhere.

**Comment by jackspaniel** [comment]
The selenium issue you linked does not seem to be the same thing we are asking for. People in that thread are asking to be able to **test response headers** going to protractor. We are asking to be able to **set request headers** coming from protractor to the server at the start of the test. This is to do things like simulate a logged in user w/o having to take the extra time to explicitly log in every time. Or in our case to bypass an annoying resource-consuming overlay which sets a cookie when the user closes it not to show up again.

**Comment by sjelin** [comment]
Sorry, sounds like I linked to the wrong issue.  This has been raised with WebDriver though and they have rejected it.  @juliemr is probably more able to find the exact issue, but you could just make a new issue on their github

**Comment by finspin** [comment]
+1 for having the possibility to set request headers

@jackspaniel for setting a cookie you can use the `browser.manage().addCookie()` method.

**Comment by fabien7474** [comment]
+1 for setting/modifying request headers. 

BTW, why this issue has been closed ?

**Comment by sjelin** [comment]
It was closed because we'd need webdriver to implement this feature, which they've [already rejected doing](https://code.google.com/p/selenium/issues/detail?id=141).  You could try contacting them on [their github](https://github.com/SeleniumHQ/selenium) but I don't think it will get you anywhere.

**Comment by g2graman** [comment]
To add, though it does not seem possible to arbitrarily set request headers, if you just want to set cookies, that is at least possible with `browser.manage().addCookie('foo', 'bar', '/')`

**Comment by jackspaniel** [comment]
It's been a while but if I recall correctly that doesn't actually send a cookie to the server with the request - it just registers in the browser that it received a cookie.

**Comment by ch0wdan** [comment]
If you support having the ability to set request headers on tests, please go to this ticket and add +1 to the request. I just created it as it inherently has and is affecting the way i have to create tests. 



[https://github.com/SeleniumHQ/selenium/issues/2131](https://github.com/SeleniumHQ/selenium/issues/2131)

**Comment by qualityshepherd** [comment]
+1 for modheaders - we use modheaders to access our app during a release... so this would make that easy.

**Comment by Schemiii** [comment]
+1

**Comment by anderserikpersson** [comment]
+1

**Comment by ORESoftware** [comment]
workaround, just put the "header" in the url

`GET localhost:6969?my_headers={"a":"b"}`

**Comment by ganqqwerty** [comment]
our app uses two-factor authentication and sends you an sms. It would be hard (impossible?) to login as user would normally login.

**Comment by tymfear** [comment]
> our app uses two-factor authentication and sends you an sms. It would be hard (impossible?) to login as user would normally login.

Just use Twilio number (they have even free one). Using Twilio API get an sms with the code. That's not difficult. https://www.twilio.com/docs/usage/api
