### ISSUE TITLE
How protractor can detect javascript errors ?

### ISSUE THREAD

**Issue by iwoogy** [angular/protractor#749]
Hello,

I start doing my first tests and I was wondering how protractor can make the test failed if an error is raised in the javascript console.

I start my tests by just loading the page, and tests results where successfull.
![image](https://cloud.githubusercontent.com/assets/479162/2797608/59dd5988-cc35-11e3-9400-d20d106acb8e.png)

But when I'm loading the page manually and check the console, I got those errors :
![image](https://cloud.githubusercontent.com/assets/479162/2797611/9edb7baa-cc35-11e3-8f40-12886c2c7834.png)

Can anyone help me to understand how to make the test fail in this case ?

Thanks

Bobby

**Comment by skbeacon** [comment]
@hanssgo & @juliemr 

I have tried your solutions to get the JS error from browser console. The issue is that it shows all the errors from the console and I want to check the JS error only. The "type" argument from the browser log is showing empty. Is there anyway I get filter the JS Errors only?
