### ISSUE TITLE
Selecting an option from a dropdown

### ISSUE THREAD

**Issue by MrTricks** [angular/protractor#75]
Hi all. Hoping someone can help.

I have:

select ng-model="data.productType" ng-options="p for p in data.productTypes" class="ng-valid ng-dirty">
<option value="0" selected="selected">All</option>
<option value="1">USA</option>
<option value="2">UK</option>
<option value="3">INDIA</option>
<option value="4">AUSTRALIA</option></select>

I am trying to select one of these values using Protractor.  I have tried a few methods including:

ptor.findElement(protractor.By.css('select option:2').click());

But I get:

TypeError: Object By.cssSelector("select option:2") has no method 'click'

Any idea what is wrong?

**Comment by r0ckyyr0cks** [comment]
On the similar ground, I am not able to get. I have:

**Comment by sallojusuresh** [comment]
Hi,
If you would like to select 'Hybrid' value from a drop down, you need to arrange your code using call back sequence, as its a Asynchronous execution

A. Selecting from drop down value:
//First click on Drop: 
element(dropdownlocator).click().then(function(){
	//second move mouse to particular value in list
	browser.action().mouseMove(element(by.xpath(".//*[text()='Hybrid']"))).click().perform();
});

B. Verifying using count:
element.all(by.model("selectedBaseLayer")),count().then(function(n){
expect(n).toEqual(1); });

**Comment by Zehra-89** [comment]
hi, 
I am trying to select value from calendar control using protractor, any one can please help

**Comment by tony2tones** [comment]
Thanks @sallojusuresh just careful that browser.action().mouseMove(element(by.xpath(".//*[text()='Hybrid']"))).click().perform();
});

needs to be browser.actions().mouseMove...  having the browser.action() is not a function had me stumped for a bit thanks again
