### ISSUE TITLE
Check to see if a table is sorted

### ISSUE THREAD

**Issue by andrewboni** [angular/protractor#761]
I'm trying to write a simple test to ensure a table gets sorted on a click to the table column head, but am running into an issue. Code is as follows:

```
    it("should sort the table on click", function() {
        // Gets the ID of the first item in the row
        var id1 = element(by.repeater("item in $data").row(0).column("item.id.toString() | highlight:filter"));

        // Gets the clickable column heading (clicking will sort the table)
        var thead = element(by.xpath("//*[@id=\"intro-4\"]/thead/tr[1]/th[2]"));
        thead.click();
        ptor.sleep(5000);

        // Gets the ID of the first item in the newly sorted table
        var id2 = element(by.repeater("item in $data").row(0).column("item.id.toString() | highlight:filter"));

        // Expect the two IDs to be different
        expect(id1.getText()).not.toEqual(id2.getText());
    });
```

But the expectation fails:

```
Failures:

  1) Manage campaigns should sort the table on click
   Message:
     Expected '1' not to equal '1'.
   Stacktrace:
     Error: Expected '1' not to equal '1'.
```

Why is `id2` not different even though the DOM actually changes?

**Comment by sdseenu** [comment]
Hi Any one to help how to sorting function it will work on protractor for angular UI gird,

 //Sorting gird
  var rows = element(by.id('.gss-grid')).$('.ui-grid-render-container').all(by.repeater('(rowRenderIndex, row) in rowContainer.renderedRows track by $index'));
  var results = [];
  var res =  rows.count().then(function(cnt){
           console.log('inside loop');
           console.log(cnt);
           for(i=0; i < cnt; i++){
              ele = test.datacell('gss-grid',i,0);
              ele.getText().then(function(txt){
              console.log(txt);
              results.push(txt);
               });
            }
          var unsorted = results.map(function(element) {
              console.log(element.getText());
                return element.getText();
                 });

            var sorted = unsorted.then(function(texts) {
                 return texts.slice(0).sort();
              });

          ele = cmn.datacell('gss-grid',0,colcount);
           expect(ele.getText()).toEqual(sorted[0]);

});


am getting unsorted is not a funtion.

If any one help

**Comment by wswebcreation** [comment]
Hi @sdseenu 

First of all you are reacting on a closed issue, the change you will get an answer is very small.
Secondly, your question is better suited for StackOverflow or Gitter. Please [ask a question there with the 'protractor' tag](https://stackoverflow.com/users/login?ssrc=anon_ask&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2fask%3ftags%3dprotractor) or post in the [Gitter Channel](https://gitter.im/angular/protractor) to get help.

From the the [getting help](https://github.com/angular/protractor#getting-help) section of the README:

>Please ask usage and debugging questions on StackOverflow (use the "protractor" tag) or in the Angular discussion group. (Please do not ask support questions here on Github.)


Thanks!
