### ISSUE TITLE
[Question] Start Google Chrome with Network tab enabled

### ISSUE THREAD

**Issue by nvhoang56123** [angular/protractor#770]
Dear all,

I'd like to have Google Chrome starts with Network console/Tab enabled. How to set it up in protractor.conf file?

The reason why I need this thing is:
1 - protractor run on  function A very slow
2 - manual run on function A only takes 1-5s

Many thanks,

**Comment by hardvolk** [comment]
For people looking to run tests in chrome with **dev-tools** opened you can do it now with the arg '**--auto-open-devtools-for-tabs**' for **chromeOptions** in your **config** for protractor:

`{
   ...
   baseUrl: 'localhost:4200',
    capabilities: {
        browserName: 'chrome',
        chromeOptions: {
            args: ['--auto-open-devtools-for-tabs']
        }
    }
   ...
}`

**Comment by djom20** [comment]
> For people looking to run tests in chrome with **dev-tools** opened you can do it now with the arg '**--auto-open-devtools-for-tabs**' for **chromeOptions** in your **config** for protractor:
> 
> ```js
> {
>    ...
>    baseUrl: 'localhost:4200',
>     capabilities: {
>         browserName: 'chrome',
>         chromeOptions: {
>             args: ['--auto-open-devtools-for-tabs']
>         }
>     }
>    ...
> }
> ```

Amazing, It's a great option. Thanks!

**Comment by Benedicttt** [comment]
> For people looking to run tests in chrome with **dev-tools** opened you can do it now with the arg '**--auto-open-devtools-for-tabs**' for **chromeOptions** in your **config** for protractor:
> 
> ```js
> {
>    ...
>    baseUrl: 'localhost:4200',
>     capabilities: {
>         browserName: 'chrome',
>         chromeOptions: {
>             args: ['--auto-open-devtools-for-tabs']
>         }
>     }
>    ...
> }
> ```

Need open Network tab
