### ISSUE TITLE
unable to select iframe element using locators

### ISSUE THREAD

**Issue by Hardcode37** [angular/protractor#80]
I have been trying to click an anchor element from inside an iframe on one of my views and so far I have been unable to achieve this.

I have so far tried the locators below
ptor.findElement(protractor.By.css()).click(), 
ptor.findElement(protractor.By.xpath()).click(), 
ptor.findElement(protractor.By.id()).click() 
and 
ptor.findElement(protractor.By.name()).click()

along with all of the above locators I have tried the same using webdriver and as yet am still unable to grab the element. 

Is there a way of achieving this is it a limitation?

**Comment by quiz1991** [comment]
Encountering the same problem with @lovacuzitu. Any update?

**Comment by tot-ra** [comment]
Got same issue, unable to find iframe to check its size with getSize()
