### ISSUE TITLE
Does the element explorer work for non angular pages?

### ISSUE THREAD

**Issue by spenoir** [angular/protractor#834]
If so, could you explain how to make it work? I'm currently getting the following error:

> list(by.id('username'))
> There was a webdriver error: undefined undefined

**Comment by jusefb** [comment]
I have tried this with the version 5.1.2 of protractor and am experiencing elementExplorer not workign for non angualr applications. I keep getting there error "E/protractor - Could not find Angular on page https://www.meetup.com/LeedsJS/?_cookie-check=9f3Ali7VJ-b1u1sm : retries looking for angular exceeded" even though I have browser.waitForAngularEnabled(false)

All works fine without elementExplorer flag
