### ISSUE TITLE
Protractor / Angular version compatibility matrix?

### ISSUE THREAD

**Issue by aabes** [angular/protractor#868]
I've spent some quality time tracking down why waitForAngular has been failing. I (_think_) i tracked it down to a version mismatch between angular and protractor.
Angular 1.2.16 does not have:
    angular.element(el).injector()

Which was causing the waitForAngular to fail immediately (in ptor 0.23.1)
This is possibly the opposite of : https://github.com/angular/protractor/issues/325, but both point to a possible need to have a compatibility story of ptor and angular.

It would be nice if ptor could do version discovery, and adapt to the applicable angular API's that are known to have changed in a given version, but that might just add too much complexity. Maybe just provide a warning if the version of angular is not known to be working with the ptor version?
Other possibilities?

**Comment by tmagilldotcom** [comment]
This is still an issue.
