### ISSUE TITLE
Tests fails on different screens

### ISSUE THREAD

**Issue by dmoskovtsov** [angular/protractor#872]
Hey. 
Probably it's not an issue but I haven't found a way of solving this. 

I have a simple test which checks width

 `labelBackground.getAttribute('width').then(function (width) {
        expect(width).toBe('60');
    });`

It works on my laptop but fails if I run it on another laptop whose screen resolution is different. I've tried played with config and setting screen size in before each but it didn't help:

`browser.driver.manage().window().setSize(1000, 1000);`

Is there a way of solving this issue? 
Thank you!

**Comment by muzamilabbasi** [comment]
@dmoskovsov how did you solved the issue? making height and width to 1000px?
