### ISSUE TITLE
timeout after 5000 msec

### ISSUE THREAD

**Issue by ranjanbhambroo** [angular/protractor#88]
I am really new at this. When i click the login button It logs in and then i wait for angular to finish. but its timing out for some reason. 
The code is:

``` javascript
var util = require('util');
describe('Login', function(){
    var ptor;
    beforeEach(function(){
        ptor = protractor.getInstance();
        ptor.get('#/login');
    });

    it('The user should be able to login', function(){
        ptor = protractor.getInstance();
        ptor.findElement(protractor.By.input('login')).sendKeys("****");
        ptor.findElement(protractor.By.input('password')).sendKeys("****");
        ptor.findElement(protractor.By.css("input.login-form-container-button")).click().then(function() {
        ptor.waitForAngular();
        expect(ptor.getCurrentUrl()).toBe(ptor.baseurl + '/#/missioncontrol');    
        },30000);

    });
});
```

Error that i get:

Failures:

  1) Login The user should be able to login
   Message:
     timeout: timed out after 5000 msec waiting for spec to complete
   Stacktrace:
     undefined

Finished in 8.685 seconds
1 test, 1 assertion, 1 failure

Shutting down selenium standalone server

/Users/ranjanbhambroo/Documents/protractor_voloforce_tests/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/promise.js:1542
      throw error;
            ^
ScriptTimeoutError: Timed out waiting for async script result after 99953ms

**Comment by mahmoud-nb** [comment]
Property 'getInstance' does not exist on type 'Ptor'.
any idea
