### ISSUE TITLE
var ptor in onPrepare

### ISSUE THREAD

**Issue by qidonna** [angular/protractor#880]
I moved var ptor from beforeEach in the tests to onPrepare, but when running the tests, I got "ReferenceError: ptor is not defined". Any ideas? Thanks!

```
  onPrepare: function() {
    // to generate test report
    require('jasmine-reporters');
    jasmine.getEnv().addReporter(
      new jasmine.JUnitXmlReporter('xmloutput', true, true));

    var ptor = protractor.getInstance();
    var url = ptor.baseUrl;
    browser.get(url);
    browser.ignoreSynchronization = true;
  },
```

**Comment by csharsha** [comment]
hi

**Comment by csharsha** [comment]
i faced an issue in angular application :
eg. driver.findElement(by.className('login'));  - its not working
but i made a slight modification to identify it adding 'browser'
browser.driver.findElement(by.className('login')); - This worked fine when i included (browser) 

But when comes to angular properties
element(by.model('pin')).sendKeys(3);
This is not working .. how to proceed
