### ISSUE TITLE
It is running very slow

### ISSUE THREAD

**Issue by gaelazzo** [angular/protractor#884]
I'm using protractor with phantomjs  and jasmine to test a very simple application, that does little more than a login/logout. Page response measured by node time are about 1-2 ms, but 9 tests with 11 assertion are taking 35 sec to complete. 
I'm simply checking the login / logout are working sending some good/bad user credential, so I wonder if those test-timings are normal using protractor. 
For comparison, always with phantomjs, client-unit test, with 232 tests and 1735 assertions are taking about 3.2 sec, while server-unit tests with 183 tests are taking 0.42 sec, and those are doing  a lot of db query, transactions and so on. 23 Midway tests are taking 2.11 sec.  All done with jasmine, karma, phantomjs.
So I don't understand where is the problem with protractor. Any suggestion?
Thanks

**Comment by bitliner** [comment]
I did not get the reason why test last much longer in this case. Is there any explanation?

**Comment by flaurian** [comment]
+1

**Comment by AntonRand** [comment]
@maxtardiveau I have a for loop that does 25 clicks to increment a counter. Just tried your solution on one of my tests and it went from 10 seconds to 2 seconds.

I know I'm probably creating a lot of promises in Protractor with the clicks but that's quite a performance difference!
