### ISSUE TITLE
Question: How can you save off values for use in other scenarios?

### ISSUE THREAD

**Issue by lavinjj** [angular/protractor#891]
I've been trying to capture values from one test scenario for use in a second test scenario without any success. I've tried two ways and both fail.

values are undefined when second test executes:

```
element(by.id('groupOrderId')).getText().then(function(value){
   global.groupOrderId = value;
});
element(by.id('groupOrderPassword')).getText().then(function(value){
   global.groupOrderPassword= value;
});
```

values are promises when second test executes:

```
global.groupOrderId = element(by.id('groupOrderId')).getText();
global.groupOrderPassword = element(by.id('groupOrderPassword')).getText();
```

When I set breakpoints in the second scenario in WebStorm the values are never set. Shouldn't the promises at least have been resolved before the second test is executed? Is there a way to do this so I can execute one scenario that sets up the environment for the second scenario.

Thanks for your help...

**Comment by dyingangel666** [comment]
I would prefer to use a singleton class which can be used to share data between multiple test cases:

`
export class Globals
{
  private static _instance: Globals;

  constructor()
  {
    if (Globals._instance)
    {
      return Globals._instance;
    }

    Globals._instance = this;
  }

  publicMember1: string;
  publicMember2: string;
}

`

Which can then be used as follows within your tests:

`
const globals = new Globals();
globals.publicMember1 = 'awesome';
`
