### ISSUE TITLE
Different global variables depending on capabilities

### ISSUE THREAD

**Issue by FuturaITLtd** [angular/protractor#892]
Is there a way calling a different set of static variables depending on what capability is used. For example if I'm testing in Chrome and IE, could I use different login credentials to enable me to run tests concurrently that might not possible if restricted to using the same user (due to the way the the app in test handles sessions).

Thanks

**Comment by Saurabh06** [comment]
@elgalu i am trying to set the global variable from onPrepare() method using browser.variablename and try to get value in spec using browser.variablename but i am not getting. I have also tried global instead of browser but still it is not working.
