### ISSUE TITLE
Docs: relationship with Karma

### ISSUE THREAD

**Issue by dylang** [angular/protractor#9]
I'm not sure if Protractor is intended to to be used with, in addition to, or instead of Karma.

Maybe a few words in the Readme would be helpful?

**Comment by reddynr** [comment]
I using protractor to perform unit testing.. I am getting error if use expect function  like below. Please advice is highly  appreciated.
 element(by.model('ctrl.formData.emailAddress')).sendKeys('xyz@abc.com');
            var emailaddress = element(by.model('ctrl.formData.emailAddress'));

expect(emailaddress.getText()).toEqual('xyz@abc.com');

error : Expected '' to equal 'narendra@abc.com'.
