### ISSUE TITLE
If protractor runs tests synchronously, why do we need to use waitForAngular()?

### ISSUE THREAD

**Issue by SowmyaCVBS** [angular/protractor#909]
I am a newbie in this. As far as I understand, protractor runs the tests synchronously. I have a scenario where I do a click event and expect for a particular text at many places in my test cases. Seldom,  I see the expect fails and hence the test cases fail. Do I need to put waitForAngular() at all places to be on a safer side or is there any simpler way to get the lines executed in sequence i.e only after the DOM completely loads?

**Comment by anandalex** [comment]
@juliemr 

I tried following ways

    passing number of arguments via command array and executing in shell.write method

    var command = [java -jar xxx.jar, xxxuser, xxxpass];

    return shell.promise.then(function (shell) {
              return {
                output: output.promise,
                error: error.promise,

                sendMultipleCommand: function (command) {
                  for (var i = 0; i < command.length; i++) {
                   console.log(command[i] + '\n');
                   shell.write(command[i] + '\n');
                  }
                }
              };
            });

    executing commands with space

    var command = java -jar xxx.jar xxxuser xxxpass;

It is not executing as expected, browser and protractor are stuck.

By manual (the same way need to execute via script)

java -jar xxx.jar
enter username: xxxuser
enter password: xxxpass

Problem seems jar file take some time to execute, but all other commands are executed before the execution of Jar file

Thanks in advance, help me to solve this issue

**Comment by gauravAuto** [comment]
Can I execute protractor scripts from java file? If yes, please update how.

**Comment by sjelin** [comment]
You can execute arbitrary shell commands from java, so just do `protractor conf.js`

**Comment by keithdtyler** [comment]
I have run into quite a lot of cases where I could not simply do

    // close a modal dialog, which causes an ajax view update
    modal.closeButton.click();
    // expect the ajax view to be updated
    expect(element(by.id('viewbox').getText()).toContain('updated value');

This fails: "Expected 'previous value' to equal 'updated value'."

The solution:

    modal.closeButton.click().then(function(){
        expect(element(by.id('viewbox').getText()).toContain('updated value');
    });

My tests are now chock full of  lines that look like

    }).then(function(){
        return x.y.z()
    }).then(function(){
        return a.b.c()
    }).then(function(){
        return expect(a.b).toBe(q)
....
