### ISSUE TITLE
EINVAL error inside Docker container

### ISSUE THREAD

**Issue by HenrikBechmann** [angular/protractor#965]
I'm trying to run the basic protractor test from inside a Docker container (base = dockerfile/nodejs), and getting:

```
Error: EINVAL connect EINVAL
  at ClientRequest.<anonymous> (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:136:16)
```

changes to conf.js:

```
seleniumAddress: '192.168.33.34:4444/wd/hub',

// Capabilities to be passed to the webdriver instance.
capabilities: {
    'browserName': 'firefox'
 },
```

This selenium address works from a behat container.

nodejs version v0.10.28.

Any advice would be much appreciated.

**Comment by PLEEROCK** [comment]
for those who will face this error like me: http:// is required in `seleniumAddress: 'http://selenium:4444/wd/hub'` to resolve this problem

**Comment by ralberts** [comment]
@PLEEROCK Thanks - helped me :-)
