### ISSUE TITLE
Shift+Click on Checkbox doesn't work with PhantomJS

### ISSUE THREAD

**Issue by nwinkler** [angular/protractor#972]
I'm trying to simulate a Shift+Click on a checkbox on a web page. The checkbox has an `ng-click` event handler registered. The event is fired in both Chrome and PhantomJS, but the difference is that in Chrome, the event's `shiftKey` property is set to `true`, while in PhantomJS, it's set to `false`.

This is the code I'm using to do the click:

```
var checkbox = element.findElement(by.css('input[type="checkbox"]'));

protractor.getInstance().actions()
    .keyDown(protractor.Key.SHIFT)
    .click(checkbox)
    .perform();
```

Is this a known limitation, or am I using the wrong code? I've tried adding a `keyUp` for the shift key after the `click`, but it didn't change anything.

Versions:
* Protractor: 0.23.1
* Selenium Webdriver: 2.41.0
* PhantomJS: 1.9.7-10

**Comment by juliemr** [comment]
For the record, issue is https://github.com/detro/ghostdriver/issues/364

Closing, as this is now covered elsewhere.
