### ISSUE TITLE
browser.ignoreSynchronization

### ISSUE THREAD

**Issue by Ronsku** [angular/protractor#973]
Hi,

I have been trying to search for answers for a day now. My simple protractor test doesn't work unless i have set:
browser.ignoreSynchronization = true

If i have browser.ignoreSynchronization = false (as it is by default) it gets stuck in the first thing that should be synchronous, expect browser.get('') works!

I have a login script in my onPrepare on my config, works fine:
enviroinment.js: http://jsfiddle.net/LrgDz/
config.js: http://jsfiddle.net/PEJj3/

I have ng-app tag in 'html' tag.

login.spec.js: http://jsfiddle.net/8rQ3n/

This makes no sense. I've tried everything it feels like.
- I have the newest version of protractor and angularjs.
- Login works without any problems, but after that I cannot get anything to work without 'browser.ignoreSynchronization = true'.

appConfig.js: http://jsfiddle.net/rn37U/

Please help me!

Best regards,
Ron

**Comment by shendrix** [comment]
Is there any way to have `ignoreSynchronization = false;` and have Protractor ignore $timeout requests?
