### ISSUE TITLE
Is it possible to verify that HTTP backend mock's expectations have been satisfied?

### ISSUE THREAD

**Issue by elnur** [angular/protractor#977]
``` javascript
describe('foo', function () {
    it('bar', function () {
        browser.addMockModule('httpBackendMock', function () {
            angular
                .module('httpBackendMock', ['ngMockE2E'])
                .run(function ($httpBackend) {
                    $httpBackend.expectGET('/api/foo');
                });
        });

        // do something through the UI

        // somehow verify that a GET to /api/foo has been done
    });
});
```

After two days of relentless googling, I've finally figured out how to mock the backend in Protractor tests.

Now, what is left to figure out is how to verify that expectations I've set on the mock have been satisfied. Is it even possible? If yes, I'd really like to know how.

**Comment by gustavocoelho** [comment]
I'm trying this code but it doesn't work at all, can't figure it out, any sighns

describe('HTTP backend REST methods', function() {
    it('should validate action when POST request', function() {        
        var isCalled = false;
        
        browser.addMockModule('httpBackendMock', function () {
            angular.module('httpBackendMock', ['ngMockE2E']).run(function ($httpBackend) {
                httpBackend.whenPOST('app/mock-data/post-action.json').respond(function (method, url, data) {
                    isCalled = true;
                    return "baz";
                });
            });
        });

        var buttons = [
            'button_A', 
            'button_B', 
            'button_C', 
            'button_9', 
            'button_5', 
            'button_7', 
            'button_6', 
            'base-keyboard-ok' 
        ];

        var buttonsClick = function(j){
            var buttonKey = browser.driver.findElement(by.id(buttons[j]));
            buttonKey.click();
        }

        for(j=0; j<buttons.length; j++){
            buttonsClick(j);
        }

        browser.sleep(2000);

        expect(isCalled).toBe(true);
    });
});
