### ISSUE TITLE
Include test data file in protractor

### ISSUE THREAD

**Issue by priyabrat1801** [angular/protractor#978]
Is there a way i can put my test data in a json file and use that file in my specs to get the test data. I need to use a lot of hard coded data which i want to put inside the data file. I know karma has the functionality for unit tests but not sure of using in protractor. Any suggestions.

**Comment by nattimorgan** [comment]
Thanks Suresh, this helped me out big time man!!!  I am now able to create my data driven tests in Protractor. One day, I hope to contribute something as helpful as this. Thanks.

**Comment by meneghia** [comment]
I am attempting to create the data file that was referenced Suresh. However I am having issues with protractor when I got to execute. I am getting unexpected token. Something isn't correct in my syntax. What does the whole data.json look like. 
My Example:

projectData.json:
{
"url":"https://google.com",
"projectCode":"5c5d3ca2",
"memberId":"1",
"externalId":"1"
}

Then I save this off and reference the json file. 
var testdata = require('../data/projectdata.json');

**Comment by priyabrat1801** [comment]
Can you put the json in jsonlint to verify if it is valid or not. That will
give you idea on where the issue is.

Thanks.

**Comment by sautomation** [comment]
I followed Suresh's approach and It doesn't work for me either. My json is a valid file. I checked it in the json validator 

{
"user1":"email@email.com",
"user2":"email2@email.com"

} 

In my test, 

  var diff = require('../helper/differentlogin.json');

      it('Should click on Login button', function() {

        browser.get('/#/');

        element(by.name('username')).sendKeys(diff.user1);
        element(by.name('password')).clear().sendKeys('pass');
        element(by.id("login"))..click();;
    
     //});
      });

	});

I need to pass the different userID in the send keys and password is the same for all our test users.

**Comment by nagadinesh49** [comment]
@sautomation : Can you give a try by referencing the values as diff[user1] or diff['user1'] inside sendkeys.

**Comment by pavangkumar** [comment]
Thanks for Every one, Iam very new to protractor this helped me a lot and also can any one send the links to learn protractor?

**Comment by bhamaresanket** [comment]
Hi,
The solution from Suresh worked perfectly fine.
Next thing I need to try is write some text using protractor to the json file from which we read the values.
e.g. 
If the original json file is this:
{
"user1":"email@email.com",
"user2":"email2@email.com"
}

I want to add an extra field through protractor code to json file. So the file should be like.
{
"user1":"email@email.com",
"user2":"email2@email.com",
"user3":"email3@email.com"
}

Please help.

**Comment by krish0205** [comment]
Is there a way to run same it for several times based on array size in the JSON. 
My JSON file looks like this:
```
[{
        "titleText": "U1"
    },

    {
        "titleText": "U2"
    },
    {
        "titleText": "U3"
    }

]
```
