### ISSUE TITLE
HAR file generation in Protractor/Phantom using netsniff.js

### ISSUE THREAD

**Issue by h4wlt** [angular/protractor#980]
Hi,  I have been trying to get a HAR file generated for days now, I have been messing with netsniff.js (add on for Phantom) I can get this to work easily enough by calling it directly at the command prompt like this:

bin/phantomjs examples/netsniff.js http://www.google.co.uk > test.har

Is there a way of calling this from within my tests in Protractor, or setting it up some how in the on-prepare function?

Thanks,
Craig.

**Comment by jfroffice** [comment]
any update on this.

maybe using [chrome-har-capturer](https://github.com/cyrus-and/chrome-har-capturer)
