### ISSUE TITLE
Add argument to webdriver-manager to allow custom jar file name

### ISSUE THREAD

**Issue by sajidmohammed** [angular/protractor#987]
Just like argument "out_dir", allow "out_jarname" to allow custom name for the selenium server standalone jar. For example, currently the file name is selenium-server-standalone-2.42.0.jar which contains version number in the name. I would like to name it generic: selenium-server-standalone.jar so that I do not have to hard code in the config file.

**Comment by fat-troll** [comment]
Isn't it "seleniumServerJar" parameter?

**Comment by cnishina** [comment]
Instead of allowing for a generic name for selenium server jar or having to fix the `config.json`,  `webdriver-manager ` could download / start different selenium version numbers from the command line. See #2998 for more details.
