### ISSUE TITLE
Test configuration

### ISSUE THREAD

**Issue by ghost** [angular/protractor#989]
Hi! Sorry for broken English, use a translator.  
To run the first test, I found will in Google and started doing it. Here's the code -  
**index.html**

```
**index.html**  
<!DOCTYPE html>
<html lang="en" ng-app="app">
<head>
    <meta charset="UTF-8">
    <title>Tests</title>
    <script type="text/javascript" src="bower_components/angular/angular.min.js"></script>
    <script type="text/javascript" src="app.js"></script>
</head>
<body>
    <div ng-controller="MainCtrl">
        <label>First name</label>
        <input type="text"  ng-model="firstName"/>
        <p>Hello {{firstName}}!</p>
    </div>
</body>
</html>
```

**app.js**

```
var app = angular.module('app', [])
.controller('MainCtrl', function($scope){
    $scope.firstName = "";
})
```

**conf.js**

```
exports.config = {
  seleniumServerJar:"./node_modules/protractor/selenium/selenium-server-standalone-2.42.2.jar",

  seleniumAddress: 'http://localhost:4444/wd/hub',

  capabilities: {
    'browserName': 'chrome'
  },

  specs: ['protractor.spec.js'],

  baseUrl: 'http://localhost:9000',

  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  }
};
```

**protractor.spec.js**

```
describe("My one unit-test", function() {
    it('should greet the name user', function() {
        browser.get('http://localhost:9000/index.html');
        element(by.model('firstName')).sendKeys('TestName');
        var greeting = element(by.binding('firstName'));
        expect(greeting.getText()).toEqual('Hello TestName!');
    });
});
```

**Here's how I do -**  
1. npm install protractor -g
2. webdriver-manager update
3. webdriver-manager start
4. protractor conf
And after these steps, the browser opens in which it is written -  

> The web page is not available.  

And here is what is written in the console -  

> e:\OpenServer\domains\my-site-one>protractor conf  
> Using the selenium server at http://localhost:4444/wd/hub  
> F  
> 
> Failures:
> 
>  1) My one unit-test should greet the name user
>    Message:
>      Error: Angular could not be found on the page http://localhost:9000/index.html : retries looking for angular exceeded
>    Stacktrace:
>      Error: Angular could not be found on the page http://localhost:9000/index.html : retries looking for angular exceeded
>     at assertAngularOnPage (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\lib\protractor.js:1013:13)
>     at C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
>     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
>     at notify (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
>     at notifyAll (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
>     at resolve (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
>     at fulfill (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
>     at Object.webdriver.promise.asap (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:671:5)
>     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1550:25)
>     at notify (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
> ==== async task ====
> WebDriver.executeScript()
>     at webdriver.WebDriver.schedule (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:268:15)
>     at webdriver.WebDriver.executeAsyncScript (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:496:15)
>     at Protractor.get (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\lib\protractor.js:1020:15)
>     at null.<anonymous> (e:\OpenServer\domains\my-site-one\protractor.spec.js:3:11)
>     at C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd\index.js:94:14
>     at webdriver.promise.ControlFlow.runInNewFrame_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1539:20)
>     at webdriver.promise.ControlFlow.runEventLoop_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:1404:8)
> ==== async task ====
> Asynchronous test function: it()
>     at null.<anonymous> (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd\index.js:93:33)
>     at null.<anonymous> (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\async-callback.js:45:37)
>     at jasmine.Block.execute (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1174:17)
>     at jasmine.Queue.next_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2209:31)
>     at null._onTimeout (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:2199:18)
> Error
>     at null.<anonymous> (e:\OpenServer\domains\my-site-one\protractor.spec.js:2:2)
>     at jasmine.Env.describe_ (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:913:21)
>     at jasmine.Env.describe (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:898:15)
>     at describe (C:\Users\acopalipsis\AppData\Roaming\npm\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:658:27)
>     at Object.<anonymous> (e:\OpenServer\domains\my-site-one\protractor.spec.js:1:63)
> 
> Finished in 16.049 seconds  
> 1 test, 1 assertion, 1 failure
> 
> e:\OpenServer\domains\my-site-one>

In General three days I can't run the test. And during that time I had read all the responses on stackoverflow function here and not one I don't helps. Only hope for You.

**Comment by ganeshbonangi** [comment]
Tell me how you resolved the problem. I faced same problem

**Comment by mynameTT** [comment]
@ghost 
please tell me how you resolved, because I am also facing same issue. since two days I am struggling.

**Comment by flexin777** [comment]
hi,did you find solution?
