### ISSUE TITLE
Find a better way for Protractor to sync with Angular

### ISSUE THREAD

**Issue by hankduan** [angular/protractor#996]
In order to inject mock modules into Angular before it bootstraps, Protractor currently does this:

Protractor changes window.name before navigating to an Angular site. Angular sees this name, halts bootstrap. After Angular injects the mock modules, Angular resumes bootstrap. This would be fine, except window.name isn't persistent across location.assign().

The way protractor is syncing with Angular implies the following:
1) protractor cannot implement back or forward
2) if another site redirects to Angular, mock modules will not be injected unless the test reloads Angular (i.e. if non-Angular log in page redirects to Angular app)

Need to think of a new communication protocol between Angular/protractor

**Comment by juliemr** [comment]
Removing needs investigation, since this is in icebox.

**Comment by juliemr** [comment]
Example of issues that this causes: https://github.com/angular/protractor/issues/2461

**Comment by juliemr** [comment]
Closing in favor of https://github.com/angular/protractor/issues/3374
